### ISSUE TITLE
Port Trac issues to Github, preserving usernames

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1]
There are over 300 tickets at http://www.mlpack.org/trac/ which should be ported to Github.  In addition, the milestones and wiki should also be ported, and old svn/Trac usernames should be ported to Github usernames (where possible).

So this should actually wait until I have (most) everyone's Github username.

**Comment by rcurtin** [comment]
Test update; hopefully this should go to the mailing list.

**Comment by mlpack-mailing-lists** [comment]
On Wed, Dec 31, 2014 at 06:08:59PM -0800, Ryan Curtin wrote:
> Test update; hopefully this should go to the mailing list.

Test reply from mailing list.

-- 
Ryan Curtin    | "I just ran out of it, you see."
ryan@ratml.org |   - Howard Beale

**Comment by rcurtin** [comment]
On Wed, Dec 31, 2014 at 06:15:07PM -0800, mlpack mailing lists wrote:
> On Wed, Dec 31, 2014 at 06:08:59PM -0800, Ryan Curtin wrote:
> > Test update; hopefully this should go to the mailing list.
> 
> Test reply from mailing list.

Okay, so replying from mailing lists doesn't work.  Therefore I've
stripped the reply-to for posts to the mailing list.  Let's see if that
worked right.

-- 
Ryan Curtin    | "We need some time for some things to happen!"
ryan@ratml.org |   - Bells

**Comment by rcurtin** [comment]
Everything is set up.  The Trac site is deprecated (and the Wiki says so).  So this is done.
