### ISSUE TITLE
rodeo-KDE implementation?

### ISSUE THREAD

**Issue by bkj** [mlpack/mlpack#1003]
Hi All --

In the density estimation tree paper, they compare their results to the rodeo-KDE method.  It doesn't look like there's an implementation of r-KDE in `mlpack`, but is anyone aware of where I might be able to find such an implementation?  I've looked around a bit, but no luck so far -- thought maybe someone in this community might have some ideas.

Thanks

**Comment by rcurtin** [comment]
Hi there Ben,

I talked to Pari, the author of the DET code (and paper).  He writes:

> I used a self/labmate implemented rodeo kde in Matlab as the baseline. So not                                                                                                                                                                 
> sure if there is a standard one anywhere. However rodeo kde is more of a                                                                                                                                                                   
> bandwidth selection scheme and hence can be wrapped around mlpack's kde for                                                                                                                                                                
> the actual kde task.

Unfortunately though, there's not an implementation of standard dual-tree KDE in mlpack (or even regular KDE) although it should be easy to whip one up if you are up for the task... :)

I hope this helps.  Let me know if I can clarify anything.

**Comment by bkj** [comment]
Ah -- that helps.  Interesting that there's not a good implementation, given that the comparisons in the DET paper show rKDE performing pretty well -- I wonder if it was superceded by some other method.  Thanks for your help.

**Comment by rcurtin** [comment]
Unfortunately there are lots of papers where code is not produced, meaning that people who want to compare against that paper have to write the implementation from scratch.  My guess is that rKDE was pretty easy to implement in MATLAB, and since the rKDE comparisons in the paper aren't runtime, the fact that MATLAB is a lot slower didn't matter. :)
