### ISSUE TITLE
mlpack_decision_tree rejects a valid parameter name for -p

### ISSUE THREAD

**Issue by pmarini** [mlpack/mlpack#1007]
I have built mlpack2.2.2 and noticed a potential bug in calling the method mlpack_decision_tree regarding the predictions save operation.
The method issues a 
[WARN ] No extension given with filename ''; type unknown.  Save failed.
even if the file name is correctly specified.

Here is the complete call:
`pietro@xxx:~/temp$ mlpack_decision_tree -t X.csv -l y.csv  -M model.txt -T X.csv -p p.csv -v`
and output

[INFO ] Loading 'X.csv' as CSV data.  Size is 784 x 1000.
[INFO ] Loading 'y.csv' as raw ASCII formatted data.  Size is 1 x 1000.
[INFO ] Loading 'X.csv' as CSV data.  Size is 784 x 1000.
**[WARN ] No extension given with filename ''; type unknown.  Save failed.
prediction_file: unknown data type**
[INFO ]
[INFO ] Execution parameters:
[INFO ]   help: false
[INFO ]   info: ""
[INFO ]   input_model_file: ""
[INFO ]   labels_file: y.csv
[INFO ]   minimum_leaf_size: 20
[INFO ]   output_model_file: model.txt
[INFO ]   prediction_file: (Unknown data type - )
[INFO ]   predictions_file: p.csv
[INFO ]   print_training_error: false
[INFO ]   probabilities_file: ""
[INFO ]   test_file: X.csv
[INFO ]   test_labels_file: ""
[INFO ]   training_file: X.csv
[INFO ]   verbose: true
[INFO ]   version: false
[INFO ]
[INFO ] Program timers:
[INFO ]   loading_data: 0.323236s
[INFO ]   saving_data: 0.000001s
[INFO ]   total_time: 0.522415s

If I try to:

-  call another method (e.g. mlpack_decision_stump) with the same parameter names, or
`pietro@xxx:~/temp$ mlpack_decision_stump -t X.csv -l y.csv  -M model.txt -T X.csv -p p.csv -v`
-  the same method with -P instead of -p. 
`pietro@xxx:~/temp$ mlpack_decision_tree -t X.csv -l y.csv  -M model.txt -T X.csv -P p.csv -v`
It works fine.

I'm on a Ubuntu 16.04 OS and built mlpack from the github repo.

**Comment by rcurtin** [comment]
Hi there,

I released mlpack 2.2.3 to fix this issue, so if you download the newest version from http://mlpack.org/files/mlpack-2.2.3.tar.gz and recompile, this should fix your issue.  The problem itself was just a small typo... sorry about that!

Thanks,
Ryan
