### ISSUE TITLE
local mlpack includes should have higher priority than system mlpack includes

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1013]
This was reported by @czdiao in IRC:

https://gist.github.com/czdiao/7caf730ed12e43bcc65ee2061cff1d1f

The installation in `/usr/local/include/` is being included before the mlpack source in `/Users/chenzhe/mlpack_czdiao/`.

Probably a CMake configuration change needs to happen to make this operate correctly.

**Comment by shikharbhardwaj** [comment]
Looks as if by default, cmake appends the `include_directories` to the existing list of include directories, placing them after the system includes.

Setting [CMAKE_INCLUDE_DIRECTORIES_BEFORE](https://cmake.org/cmake/help/v3.0/variable/CMAKE_INCLUDE_DIRECTORIES_BEFORE.html#variable:CMAKE_INCLUDE_DIRECTORIES_BEFORE) to ON will override this default behaviour.

**Comment by rcurtin** [comment]
Thanks for pointing this out, I used that to assemble a fix and merged fd1cb71cc which appears to fix the issue.
