### ISSUE TITLE
Require Armadillo 6.500 as a minimum

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1045]
Several things need to happen for this:

- [x] Update README.md, HISTORY.md, and any documentation in doc/
- [x] Remove any unnecessary backports from `src/mlpack/core/arma_extend` (I think this will be just about everything)
- [x] Update Jenkins build matrix to remove builds against older Armadillo versions
- [x] Update Armadillo EPEL packages (only I can do this)

**Comment by Rajiv2605** [comment]
I would like to contribute to this. It would be great if you could help me as I am new to this library and to open source. It would be really helpful if you could guide me through this.

**Comment by zoq** [comment]
Hello @Rajiv2605, you can start with the first point, search through the codebase (``README.md``, ``HISTORY.md``, https://github.com/mlpack/mlpack/tree/master/doc) and search for ``Armadillo  4.200.0`` or something along the lines and update the line according to the new version.

**Comment by Rajiv2605** [comment]
I have updated README.md, HISTORY.md and /doc folder files with the latest version of Armadillo. I have submitted a pull request **Updated Armadillo version to 6.500.0 #1050**. Please review it and suggest changes if any.

**Comment by rcurtin** [comment]
I filed a bug on Launchpad to update the Armadillo version on trusty: https://bugs.launchpad.net/bugs/1703454 .

**Comment by rcurtin** [comment]
Trying again with a different bug, https://bugs.launchpad.net/trusty-backports/+bug/1703626

**Comment by Rajiv2605** [comment]
@rcurtin @zoq Should I close this issue?

**Comment by Rajiv2605** [comment]
@rcurtin @zoq The wiki still shows minimum version for Armadillo as `4.200.0`
This is the screenshot of the wiki:
<img width="516" alt="version" src="https://user-images.githubusercontent.com/16632603/30323677-bb24d44e-97db-11e7-995d-64d1e3c1d252.PNG">

**Comment by zoq** [comment]
Nice catch! I think, instead of updating the page: https://github.com/mlpack/mlpack/wiki we can remove the part you pointed out. The main readme or the build tutorial provides that kind of information so it's redundant; for me, it's just another page we have to update if something changed.

**Comment by Rajiv2605** [comment]
@zoq But, shouldn't the page wiki have all the info about the repository?

**Comment by zoq** [comment]
I think it does, but instead of providing the information on the same page, we reference the existing page that provides all the information about building mlpack, dependencies, etc. Let me know what you think.

**Comment by Rajiv2605** [comment]
@zoq That's a good idea 👍

**Comment by rcurtin** [comment]
I updated the wiki to point to the doxygen-generated build information; that should be a sufficient solution.

I am packaging the updated Armadillo versions for EPEL6 and EPEL7 too, but I have to wait on a few other things before that is done.  Then we can close this issue.

**Comment by rcurtin** [comment]
EPEL7 update submitted: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2017-e36735026b

Once that's done I'll get the EPEL6 update too.  It took a while to get a provenpackager for Fedora to help rebuild dependent packages.

**Comment by rcurtin** [comment]
The EPEL7 update was finally merged, and I think that's as good as we'll manage to do for this one.  Ubuntu will update when they manage to update...
