### ISSUE TITLE
Documentation for the RANN API

### ISSUE THREAD

**Issue by naveenjafer** [mlpack/mlpack#1058]
Hi, Could someone kindly add documentation on the API for the RANN package? http://www.mlpack.org/docs/mlpack-2.2.3/doxygen.php?doc=classRASearch.html it is empty.

**Comment by zoq** [comment]
Hello, this link is working for me: http://www.mlpack.org/docs/mlpack-2.2.3/doxygen.php?doc=classmlpack_1_1neighbor_1_1RASearch.html

Can you tell us which link references to the one you mentioned?

**Comment by naveenjafer** [comment]
Hi @zoq  clicking the API corresponding to RANN leads to the link I had posted above, http://www.mlpack.org/about.html Maybe it is linking to some older link.

**Comment by zoq** [comment]
@naveenjafer thanks for the fast response, that helps a lot, we will fix that.

**Comment by naveenjafer** [comment]
@zoq  Thank you, WIll close the issue then :)

**Comment by zoq** [comment]
Actually, do you mind to let this open, as a reminder?

**Comment by rcurtin** [comment]
Sorry! I was working on this Friday, I thought I had everything patched back up by the time I left.  I'll handle it when I get home this afternoon.  I'll let you know when it is done and the doxygen output will look a lot nicer too. :)

**Comment by rcurtin** [comment]
Fixed.  The correct link now is http://www.mlpack.org/docs/mlpack-2.2.3/doxygen/classmlpack_1_1neighbor_1_1RASearch.html , and I updated about.html to reflect that.  Sorry for the inconvenience.
