### ISSUE TITLE
Using floats instead of double

### ISSUE THREAD

**Issue by etano** [mlpack/mlpack#1062]
Hi, long time armadillo user, newer mlpack user (looks great!).

I'd like to be able to change the datatype in the ann implementation to float (instead of double).

I'm willing to go through and add a template parameter for the datatype as it seems pretty straightforward. But before I go through the effort, I'm just wondering if there's a possibility something like this would be accepted.

Cheers!

**Comment by rcurtin** [comment]
I think actually this should not be too hard---all of the layers (or at least most of them) in `src/mlpack/methods/ann/layer/` already support templated matrix types, meaning you could use floats with them.  But still, I think that `FFN` and `RNN` should probably be refactored at some point to support generic matrix types.  I'm not sure what the exact best way to do that will be---@zoq, any ideas in particular?

This is related to the long-standing issue #290.

**Comment by etano** [comment]
Yeah looking at it, it seems as you say. I think there is an option between templating on a matrix type or templating on an underlying datatype, or both.

Looking forward, having arbitrary types might be convenient when integrating with bandicoot: https://github.com/conradsnicta/bandicoot-code

**Comment by rcurtin** [comment]
Absolutely, I want to be able to drop in bandicoot types when the time comes.  I'm surprised, word is spreading fast about that project I guess... :)

I think that templating on a matrix type would be better---like you pointed out, this would allow us to accept bandicoot types and also `arma::sp_mat`, etc.  I would think the way to do this would be to simply templatize the `Train()` and other related functions to accept arbitrary input types, so that you can train on whatever.

**Comment by etano** [comment]
Well I opened a pull request (not meant to be merged yet), just to get an idea of what this change might look like.

I'm realizing now, though, that it will be a bit more involved because of this LayerTypes boost::variant thing.

**Comment by zoq** [comment]
Right, we have to find a good solution for ``boost::variant``, have to think about it.

**Comment by rcurtin** [comment]
Do you think we could do something like this?

```
template<typename ElemType>
using LayerTypes = boost::variant<
    Add<arma::Mat<ElemType>, arma::Mat<ElemType>>,
    ...
>;
```

**Comment by dheeraj135** [comment]
@rcurtin Is anyone working on it? If not, I would like to look into this.

**Comment by zoq** [comment]
Please feel free to look into the issue.

**Comment by dheeraj135** [comment]
@zoq Okk..

**Comment by Tanishq-Banyal** [comment]
Any updates ?
