### ISSUE TITLE
Matrix transpose written to file?

### ISSUE THREAD

**Issue by JSybrandt** [mlpack/mlpack#1063]
Hey,

I'm running NMF and I'm using mlpack to interface with some other code.

I provide a large n x m matrix and expect W to be of size n x r and H to be of size r x m.
But I'm looking at the resulting files (both pgm and csv format) and I'm seeing that W is of size r x n and H is of size m x r.

How should I interpret these files then? Are they simply the transposes of each file written because the data is stored in column-major order? Are the factors being written out wrong?

**Comment by rcurtin** [comment]
You're correct---mlpack (or really Armadillo) stores the data in column-major order, so the matrix is transposed when it is written as output.  Note that if you are using mlpack to load the matrices back in, i.e.

```
arma::mat w;
data::Load("w.csv", w);
```

then the matrix will be automatically transposed on load, and you will get the size that you expect.  Note that if you do this, `w` will have size n x r, and `h` (if you loaded it the same way) would have size r x m, so if you then do `w * h` you get the approximation of the original matrix `v`.

I hope this clarifies everything---let me know if not. :)

**Comment by JSybrandt** [comment]
Thank you again!
I just wanted to make sure. I'm loading these files in a different library, but transposes are easy.

**Comment by rcurtin** [comment]
No problem, glad to help. :)  If you have issues in the future, feel free to ask.
