### ISSUE TITLE
Arm cross compilation error.

### ISSUE THREAD

**Issue by Muthiang** [mlpack/mlpack#1076]
While cross compiling in ubuntu/64 for arm 32 bit processor, the following error has occurred. 
 Static linking of OpenBLAS with the flag in armadillo ARMA_USE_WRAPPER commented out. Please help.

[ 53%] Linking CXX executable ../../../../bin/mlpack_range_search
../../../../lib/libmlpack.a(rs_model.cpp.o): In function `mlpack::range::BiSearchVisitor::BiSearchVisitor(arma::Mat<double> const&, mlpack::math::RangeType<double> const&, std::vector<std::vector<unsigned int, std::allocator<unsigned int> >, std::allocator<std::vector<unsigned int, std::allocator<unsigned int> > > >&, std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >&, unsigned int)':
rs_model.cpp:(.text+0x508): multiple definition of `mlpack::range::BiSearchVisitor::BiSearchVisitor(arma::Mat<double> const&, mlpack::math::RangeType<double> const&, std::vector<std::vector<unsigned int, std::allocator<unsigned int> >, std::allocator<std::vector<unsigned int, std::allocator<unsigned int> > > >&, std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >&, unsigned int)'
CMakeFiles/mlpack_range_search.dir/range_search_main.cpp.o:range_search_main.cpp:(.text+0x5c4): first defined here
../../../../lib/libmlpack.a(rs_model.cpp.o): In function `mlpack::range::BiSearchVisitor::BiSearchVisitor(arma::Mat<double> const&, mlpack::math::RangeType<double> const&, std::vector<std::vector<unsigned int, std::allocator<unsigned int> >, std::allocator<std::vector<unsigned int, std::allocator<unsigned int> > > >&, std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >&, unsigned int)':
rs_model.cpp:(.text+0x508): multiple definition of `mlpack::range::BiSearchVisitor::BiSearchVisitor(arma::Mat<double> const&, mlpack::math::RangeType<double> const&, std::vector<std::vector<unsigned int, std::allocator<unsigned int> >, std::allocator<std::vector<unsigned int, std::allocator<unsigned int> > > >&, std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >&, unsigned int)'
CMakeFiles/mlpack_range_search.dir/range_search_main.cpp.o:range_search_main.cpp:(.text+0x5c4): first defined here
../../../../lib/libmlpack.a(rs_model.cpp.o): In function `mlpack::range::TrainVisitor::TrainVisitor(arma::Mat<double>&&, unsigned int)':
rs_model.cpp:(.text+0x518): multiple definition of `mlpack::range::TrainVisitor::TrainVisitor(arma::Mat<double>&&, unsigned int)'
CMakeFiles/mlpack_range_search.dir/range_search_main.cpp.o:range_search_main.cpp:(.text+0x5d4): first defined here
../../../../lib/libmlpack.a(rs_model.cpp.o): In function `mlpack::range::TrainVisitor::TrainVisitor(arma::Mat<double>&&, unsigned int)':
rs_model.cpp:(.text+0x518): multiple definition of `mlpack::range::TrainVisitor::TrainVisitor(arma::Mat<double>&&, unsigned int)'
CMakeFiles/mlpack_range_search.dir/range_search_main.cpp.o:range_search_main.cpp:(.text+0x5d4): first defined here
../../../../lib/libmlpack.a(rs_model.cpp.o): In function `mlpack::range::BiSearchVisitor::operator()(mlpack::range::RangeSearch<mlpack::metric::LMetric<2, true>, arma::Mat<double>, mlpack::tree::KDTree>*) const':
rs_model.cpp:(.text+0x7cc): multiple definition of `mlpack::range::BiSearchVisitor::operator()(mlpack::range::RangeSearch<mlpack::metric::LMetric<2, true>, arma::Mat<double>, mlpack::tree::KDTree>*) const'
CMakeFiles/mlpack_range_search.dir/range_search_main.cpp.o:range_search_main.cpp:(.text+0xc74): first defined here
../../../../lib/libmlpack.a(rs_model.cpp.o): In function `mlpack::range::TrainVisitor::operator()(mlpack::range::RangeSearch<mlpack::metric::LMetric<2, true>, arma::Mat<double>, mlpack::tree::KDTree>*) const':
rs_model.cpp:(.text+0x808): multiple definition of `mlpack::range::TrainVisitor::operator()(mlpack::range::RangeSearch<mlpack::metric::LMetric<2, true>, arma::Mat<double>, mlpack::tree::KDTree>*) const'
CMakeFiles/mlpack_range_search.dir/range_search_main.cpp.o:range_search_main.cpp:(.text+0xcb0): first defined here
../../../../lib/libmlpack.a(rs_model.cpp.o): In function `mlpack::range::TrainVisitor::operator()(mlpack::range::RangeSearch<mlpack::metric::LMetric<2, true>, arma::Mat<double>, mlpack::tree::Octree>*) const':
rs_model.cpp:(.text+0xaa4): multiple definition of `mlpack::range::TrainVisitor::operator()(mlpack::range::RangeSearch<mlpack::metric::LMetric<2, true>, arma::Mat<double>, mlpack::tree::Octree>*) const'
CMakeFiles/mlpack_range_search.dir/range_search_main.cpp.o:range_search_main.cpp:(.text+0xe5c): first defined here
../../../../lib/libmlpack.a(rs_model.cpp.o): In function `mlpack::range::BiSearchVisitor::operator()(mlpack::range::RangeSearch<mlpack::metric::LMetric<2, true>, arma::Mat<double>, mlpack::tree::BallTree>*) const':
rs_model.cpp:(.text+0xc50): multiple definition of `mlpack::range::BiSearchVisitor::operator()(mlpack::range::RangeSearch<mlpack::metric::LMetric<2, true>, arma::Mat<double>, mlpack::tree::BallTree>*) const'
CMakeFiles/mlpack_range_search.dir/range_search_main.cpp.o:range_search_main.cpp:(.text+0x1008): first defined here
../../../../lib/libmlpack.a(rs_model.cpp.o): In function `mlpack::range::TrainVisitor::operator()(mlpack::range::RangeSearch<mlpack::metric::LMetric<2, true>, arma::Mat<double>, mlpack::tree::BallTree>*) const':
rs_model.cpp:(.text+0xc8c): multiple definition of `mlpack::range::TrainVisitor::operator()(mlpack::range::RangeSearch<mlpack::metric::LMetric<2, true>, arma::Mat<double>, mlpack::tree::BallTree>*) const'
CMakeFiles/mlpack_range_search.dir/range_search_main.cpp.o:range_search_main.cpp:(.text+0x1044): first defined here
../../../../lib/libmlpack.a(rs_model.cpp.o): In function `mlpack::range::BiSearchVisitor::operator()(mlpack::range::RangeSearch<mlpack::metric::LMetric<2, true>, arma::Mat<double>, mlpack::tree::Octree>*) const':
rs_model.cpp:(.text+0x1ec4): multiple definition of `mlpack::range::BiSearchVisitor::operator()(mlpack::range::RangeSearch<mlpack::metric::LMetric<2, true>, arma::Mat<double>, mlpack::tree::Octree>*) const'
CMakeFiles/mlpack_range_search.dir/range_search_main.cpp.o:range_search_main.cpp:(.text+0x14e4): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [bin/mlpack_range_search] Error 1
make[1]: *** [src/mlpack/methods/range_search/CMakeFiles/mlpack_range_search.dir/all] Error 2

**Comment by zoq** [comment]
Looks like your compiler doesn't support the visitor pattern (c++11), with some changes it should be possible to build the main parts without the pattern, let me know if that would be an option for you and which part you like to use.

**Comment by Muthiang** [comment]
I will try disabling the range_search part and compile as a short term solution. The compiler I have used is gcc-6 and g++-6. Gcc is widely used when there is a need for native and cross compilations and making mlpack compile in gcc becomes important for wider adoption.

**Comment by rcurtin** [comment]
To be clear, mlpack already does compile on gcc---we check this rigorously.  But none of our testing reveals the same bug you have encountered here.

**Comment by Muthiang** [comment]
The problem was resolved by merging src/mlpack/methods/range_serach/rs_model.cpp code with src/mlpack/methods/range_serach/rs_model_impl.hpp and commenting out all the lines in rs_model.cpp.

**Comment by rcurtin** [comment]
So do you mean that the PR #1082 fixed the issue?

**Comment by Muthiang** [comment]
At the moment, for me a work around has been found by merging rs_model.cpp code into rs_model_impl.hpp. Workaround is not a fix. When you make this change in the source code that you maintain and release the next version with the fix, it can be considered fixed.

**Comment by rcurtin** [comment]
I just released mlpack 2.2.5: http://www.mlpack.org/files/mlpack-2.2.5.tar.gz.  It includes the fix for this issue, so I'll go ahead and close this here.  Please feel free to report any other problems you might have.  Thanks! :)
