### ISSUE TITLE
Cannot Load csv file containing Categorical features

### ISSUE THREAD

**Issue by AyushExel** [mlpack/mlpack#1080]
```
#include <iostream>
#include <fstream>
#include <mlpack/core.hpp>
#include <armadillo>
using namespace std;

int main()
{
arma::mat dataset; // Load into this matrix.
mlpack::data::DatasetInfo info;
mlpack::data::Load("activity/test.csv",dataset,info);
cout << arma::size(dataset) << endl;
}
```
I have executed the above code using this command : 
`g++ test.cpp -std=c++14 -larmadillo -lblas -llapack -lmlpack -lboost_filesystem -lboost_serialization -lboost_program_options`

On executing, I get this error message : 
```
/tmp/cc2fkDXM.o: In function `main':
test.cpp:(.text+0x3f8): undefined reference to `bool mlpack::data::Load<double, mlpack::data::IncrementPolicy>(std::__cxx11::basic_string<char,std::char_traits<char>, std::allocator<char> > const&, arma::Mat<double>&, mlpack::data::DatasetMapper<mlpack::data::IncrementPolicy>&, bool, bool)'
collect2: error: ld returned 1 exit status
```
I don't know what is causing this problem as I have already linked to all required libraries.

**Comment by rcurtin** [comment]
I can't seem to reproduce this.  Can you tell me what version on mlpack you are using?  Do you have multiple mlpack versions installed on your machine?  I think this could happen if there is not a valid libmlpack.so found on the system, or the libmlpack.so version found is too old, so you may need to also add `-L/path/to/mlpack/lib/`.

Also I think `-lboost_filesystem` should not be necessary, and `-lblas -llapack` isn't necessary if Armadillo is configured to be a wrapper library (i.e. `ARMA_USE_WRAPPER` is defined in `armadillo_bits/config.hpp`), and `-larmadillo` isn't necessary if `ARMA_USE_WRAPPER` is not defined.

**Comment by AyushExel** [comment]
@rcurtin I guess I had installed multiple versions of mlpack . Adding the path to library, as you suggested solved the problem. The program compiles successfully but when I try to run the 'a.out' file it gives this error : 
`./a.out: symbol lookup error: ./a.out: undefined symbol: _ZN6mlpack4data4LoadIdNS0_15IncrementPolicyEEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERN4arma3MatIT_EERNS0_13DatasetMapperIT0_EEbb`

**Comment by rcurtin** [comment]
Ah, I'm glad you got it figured out.  I'd strongly suggest removing the older version of mlpack from your system---multiple installed versions can be the source of a ton of headaches. :)

For the next problem, you'll have to set `LD_LIBRARY_PATH`:

```
$ export LD_LIBRARY_PATH=/path/to/mlpack/lib/
$ ./a.out
```

and then it should work.  There's a bit on `LD_LIBRARY_PATH` in this section of the readme: https://github.com/mlpack/mlpack/#4-building-mlpack-from-source

**Comment by AyushExel** [comment]
@rcurtin Thanks . It fixed the problem

**Comment by rcurtin** [comment]
No worries, glad to help. :)
