### ISSUE TITLE
Cannot access mappings of a DatasetMapper

### ISSUE THREAD

**Issue by alexandretea** [mlpack/mlpack#1081]
There is no way to access the mappings of a DatasetMapper, from the code (the only way to get them is to serialise the DatasetMapper).

An example of application is that I need to display a text representation of a decision tree, so I need to get the string associated to each categorical mapping.

**Comment by rcurtin** [comment]
Couldn't you do this:

```
extern data::DatasetInfo info; // This is the DatasetInfo object we are using.
// Print all mappings for dimension 1.
for (size_t i = 0; i < info.NumMappings(1); ++i)
{
  std::cout << info.UnmapString(i, 1) << std::endl;
}
```

The mappings will be from 0 to `info.NumMappings(d)` in dimension `d`, so you can just call `UnmapString()` to access what has been mapped.  Does that help?

**Comment by alexandretea** [comment]
Wouldn't that remove the mapping with that string? I assumed so as the member function is not const and is named "Unmap".

Also, I believe that would only work if we use an IncrementPolicy, wouldn't it?

**Comment by rcurtin** [comment]
`UnmapString` doesn't actually remove the mapping---I clarified that in the documentation in 40903f7.  And you are correct, this only works for `IncrementPolicy`.

If you need more functionality, unfortunately I don't have time to contribute it, but I am happy to merge a patch if the solution above doesn't work for you.

**Comment by alexandretea** [comment]
I found a workaround in my project to be able to use your solution :) Thanks! If I have time after my deadline I'll try to come up with a patch to solve that problem, could be useful to others.

**Comment by rcurtin** [comment]
Great---a patch would definitely be appreciated.  I think the `DatasetMapper` class could use some improvements. :)  If you open a PR, we can take a look and get it merged.  Should we go ahead and close this issue then?
