### ISSUE TITLE
LinearRegression copy and move constructors

### ISSUE THREAD

**Issue by micyril** [mlpack/mlpack#1086]
`LinearRegression` has a copy constructor with the following implementation:
```
LinearRegression::LinearRegression(const LinearRegression& linearRegression) :
    parameters(linearRegression.parameters),
    lambda(linearRegression.lambda)
{ /* Nothing to do. */ }
```
There two issues with that:
1. It doesn't copy the `intercept` parameter. In my development environment it results in random initialization of this parameter when the copy constructor is used, which in turn makes the `Predict` method work wrong sometimes.
2. It prevents generation of the implicit move constructor.

I guess a possible solution will be to remove the explicit copy constructor and let compilers generate implicit one.

**Comment by rcurtin** [comment]
Agreed, I think removing the explicit copy constructor is fine.  If you'd like to open a PR for that we can merge it.

**Comment by micyril** [comment]
Ok, I will do it shortly.
