### ISSUE TITLE
Faster Cover Trees

### ISSUE THREAD

**Issue by AbdealiJK** [mlpack/mlpack#1090]
Is there an implementation for Faster Cover Trees here ?

https://izbicki.me/public/papers/icml2015-faster-cover-trees.pdf

Which papers can I refer to for the mlpack cover tree implementation

**Comment by rcurtin** [comment]
I talked with Mike when the paper came out at ICML, but I think he implemented it in HLearn (https://github.com/mikeizbicki/HLearn).  There are some nice ideas in the paper, but unfortunately we don't have them implemented in mlpack.

If you're interested in contributing support, I'd be happy to take a look over it and then merge it.

Thanks!

**Comment by AbdealiJK** [comment]
I'm not sure I'll have time to implement it right now. But I'd really like
to see the feature in mlpack.

Keeping this issue open in case someone else is interested in contributing
or just as a reminder to me so I come back when I'm a bit more free =)

**Comment by rcurtin** [comment]
Sounds good---I'd love to add the support.  Personally what I found with my work with cover trees is that they took a really long time to build, and the build time being so long outweighed any speed improvement for search (if any).  But with Mike's faster version of cover trees, the build time may be significantly shorter.

**Comment by KARTHEEKCIC** [comment]
@rcurtin I would like to work on this.

**Comment by zoq** [comment]
@KARTHEEKCIC  please feel free to work on an implementation and don't hesitate to ask any questions either here or via IRC #mlpack.

**Comment by KARTHEEKCIC** [comment]
@zoq. Ok I will work on that.

**Comment by manish7294** [comment]
@rcurtin @zoq @KARTHEEKCIC  I would like to know whether anyone working on this issue. And if not I would like to take it on.

**Comment by KARTHEEKCIC** [comment]
Yes, I am. But if you are interested, we can work together.

**Comment by manish7294** [comment]
Sure, can you sync your updates with me via mail or irc.

**Comment by KARTHEEKCIC** [comment]
Sure, we can connect via email. Send me the address.

**Comment by manish7294** [comment]
@KARTHEEKCIC Sorry for replying this late. I totally got busy with other stuff. Here is my mail manish887kr@gmail.com. Please drop me a mail as you get the time.

**Comment by lozhnikov** [comment]
@KARTHEEKCIC @manish7294 Hello, I'd like to know if you are working on the implementation. If not I'd like to implement it if you don't mind.

**Comment by manish7294** [comment]
Hi @lozhnikov , I don't think any work have been done in this regard, at least on my part. Still let's wait for @KARTHEEKCIC confirmation. If you'd like, please go ahead with the implementation. It will definitely be a good addition :)

**Comment by lozhnikov** [comment]
@manish7294 @KARTHEEKCIC Ok, thanks for the response.
