### ISSUE TITLE
Streaming scoring in knn

### ISSUE THREAD

**Issue by AbdealiJK** [mlpack/mlpack#1092]
Currently it looks like in KNN the query data KS being read completely. As scoring is a record by record level computation, it would be great if that can be done in a streaming way or a mini batch way. 

Here are the cases I see: 
 - If query data is same as reference data load the full data
 - If query data is different from reference data load the full reference data but give an argument to choose how many lines of query data should be loaded into RAM at a time

If my reference data is 1000 lines and query data is in millions mlpack fails right now as the whole query data is loaded into RAM

**Comment by rcurtin** [comment]
Hmm, so there is no streaming support for loading from a file, but you could at least use `Search()` with a single query point at a time, and write the rest of the support for streaming from a file, i.e.:

```
// Use single-tree mode since we do a single query at a time.
KNN knn(std::move(referenceData), NeighborSearchMode::SINGLE_TREE_MODE);

while (reading file)
{
  arma::vec queryPoint = getNextLine(file); // however you want to implement that is up to you

  arma::Mat<size_t> neighbors;
  arma::mat distances;
  knn.Search(queryPoint, k, neighbors, distances);

  // I guess maybe at this point you would want to write neighbors.col(0) and distances.col(0)
  // to some output files or similar.
}
```

I hope this gets the idea across, let me know if I can clarify any further.

**Comment by AbdealiJK** [comment]
Would you be open to adding this to the MLPack source code itself ?

**Comment by rcurtin** [comment]
I'm not sure how we could provide this type of support in a reasonable way.  The code I wrote is a pretty simple combination of whatever file I/O the user wants and mlpack, so if we were to merge this type of code in, we'd have to create a new abstraction for file I/O, which unfortunately I think would be a huge amount of code.  So I don't think this one would work, unfortunately. :(

**Comment by AbdealiJK** [comment]
Yep, I noticed the same when I checked the code. 
Closing this, thanks for the example code!

**Comment by rcurtin** [comment]
Sounds good---glad I could help.  :)
