### ISSUE TITLE
LoadHDF5Test issue

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/mlpack#1110]
With Armadillo 8.100 I'm getting this error when running mlpack_test:

`src/mlpack/tests/load_save_test.cpp(678): fatal error in "LoadHDF5Test": critical check test.n_rows == 4 failed [2 != 4]`

This looks like an issue in the test itself or perhaps in mlpack's data::Load().

**Comment by rcurtin** [comment]
Fixed in 86cb5b2.  Looks like there used to be an issue where Armadillo transposed HDF5 on load/save, but that is no longer the case for any versions that mlpack supports.  Thanks for pointing out the issue. :)

**Comment by conradsnicta** [comment]
If I recall correctly, the underlying issue is that software such as Octave, Matlab and Python take arbitrary interpretation on the layout of data in HDF5 files.  Some assume column major, some row major, etc. Data saved as column major in Armadillo can end up being read as row major in other software, and vice versa. I believe this is a deficiency in the HDF5 standard itself.

This is why Armadillo ended up having a `hdf5_binary_trans` file type in addition to `hdf5_binary`.

**Comment by rcurtin** [comment]
Yep---when that happened, apparently I didn't pay attention to the memo and didn't update the code internally.  Glad to have it fixed now though.
