### ISSUE TITLE
mlpack.org

### ISSUE THREAD

**Issue by DeveloperAlfa** [mlpack/mlpack#1121]
Hey there! I am a student from https://en.wikipedia.org/wiki/Delhi_Technological_University Delhi Technological University. 

I look forward to help you  with the design and content of your website. I am a student of computer science and have basic knowledge of Machine Learning(Andrew ng's course on coursera) and am fairly proficient in C++. Your project got me interested because most of the machine learning applications today are made in python or MATLAB. But your organisation works towards making the implementation possible on C++, which has much more control than python.

I am a Content Writer and a Web Developer, I look forward to contribute for your website as well as your project.
 http://developeralfa.me/Poemcircle-Web-App/ a sample website made by me.

https://github.com/DeveloperAlfa/Poemcircle-Web-App, this is the repository link

**Comment by rcurtin** [comment]
Hi there,

If you are interested in contributing to mlpack I would suggest you first take a look at http://www.mlpack.org/involved.html.

Thanks!
