### ISSUE TITLE
Error compiling cython file

### ISSUE THREAD

**Issue by newling** [mlpack/mlpack#1123]
Hello

(((probably unrelated to issue #1122, this is a clean build on a different (ubuntu) machine)))

I'm encoutering an error with `make install`, the output below. I'm posting my cython version (I've encountered issues specific to cython versions in the past, so just in case):

```
cython --version
Cython version 0.23.4
```

.
.
.

[ 95%] Building Cython binding hmm_generate.so...
/usr/lib/python2.7/dist-packages/setuptools/dist.py:294: UserWarning: The version specified ('3.0.x') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running build_ext
cythoning /home/james/clustering/mlpack/mlpack/build/src/mlpack/bindings/python/mlpack/gmm_train.pyx to /home/james/clustering/mlpack/mlpack/build/src/mlpack/bindings/python/mlpack/gmm_train.cpp

Error compiling Cython file:
  \ - -----------------------------------------------------------
...
from cython.operator import dereference

cdef extern from "</home/james/clustering/mlpack/mlpack/src/mlpack/methods/det/det_main.cpp>" nogil:
  cdef void mlpackMain() nogil except +RuntimeError
  
  cdef cppclass DTree[T=*]:
                      ^
 \  - -----------------------------------------------------------

mlpack/det.pyx:21:23: Expected ']', found '='
building 'mlpack.det' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/home/james/clustering/mlpack/mlpack/build/src/mlpack/bindings/python/ -I/home/james/clustering/mlpack/mlpack/src -I/usr/include -I/usr/include -I/home/james/clustering/mlpack/mlpack/build/src/mlpack/.. -I/usr/include/python2.7 -c /home/james/clustering/mlpack/mlpack/build/src/mlpack/bindings/python/mlpack/det.cpp -o build/temp.linux-x86_64-2.7/home/james/clustering/mlpack/mlpack/build/src/mlpack/bindings/python/mlpack/det.o -DBINDING_TYPE=BINDING_TYPE_PYX -std=c++11 -Wall -Wextra -ftemplate-depth=1000 -O3 -fopenmp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/james/clustering/mlpack/mlpack/build/src/mlpack/bindings/python/mlpack/det.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.

.
.
.

**Comment by rcurtin** [comment]
Ah, I see in the changelog of Cython that version 0.24 is the minimum for default-template types.  So I will have to modify the CMake configuration to have a minimum version of 0.24.  Sorry about that!  But if you upgrade Cython it should solve your issue.  I'll close the issue when this is fixed.

**Comment by newling** [comment]
Cool, with Cython version 0.26.1 the templates compile. Thanks!

(now I'm facing the same prob on this machine as on thread #1122)

**Comment by newling** [comment]
It's working now, thanks!

**Comment by rcurtin** [comment]
It took a long time but #1125 is merged so this is now fixed.  Sorry about the delay...
