### ISSUE TITLE
Calling Train from multiple threads

### ISSUE THREAD

**Issue by sgiurgiu** [mlpack/mlpack#1133]
Hi, 
I have the following code:

```c++ 
std::thread worker_threads[5];
for(int i = 0; i < 5; ++i)
{
  worker_threads[i]=std::thread([](){
          try{
                   mlpack::regression::SoftmaxRegression model(3,3,false);
                   arma::Row<size_t> label({0,1,2});
                   arma::mat data = arma::randu<arma::mat>(3,3);
                   model.Train(data,label,3);
                 }catch(const std::exception& e){
                      std::cerr<< "Multithreaded SoftmaxRegression::Train failed: "<<e.what() ;
                 }
   });
}

  for(int i = 0; i < 5; ++i)
  {
        worker_threads[i].join();
  }
```

This code fails with 

> Multithreaded SoftmaxRegression::Train failed: Timer::Start(): timer 'softmax_regression_optimization' has already been started

As far as I can tell this is due to the fact that Train calls Timers::Start and Timers::Stop, which in turn calls CLI::GetSingleton().timer.StartTimer(name);

Therefore, no matter what, even if my code is supposed to be thread safe (using one object per thread), because of the CLI object this particular usage is not possible. 

Is there another way of using the library by not triggering the timers? Or, alternatively, is it possible to disable those timers? Something like this would make me happy enough:

```c++
void Timer::Start(const std::string& name)
{
#ifndef DISABLE_TIMERS
  CLI::GetSingleton().timer.StartTimer(name);
#endif
}

/**
 * Stop the given timer.
 */
void Timer::Stop(const std::string& name)
{
#ifndef DISABLE_TIMERS
  CLI::GetSingleton().timer.StopTimer(name);
#endif
}
```

Thank you.

**Comment by rcurtin** [comment]
Hi there,

You are right that this is a big problem, and thank you for bringing it to attention.  When the timers code was originally written, I think multithreading was not common yet (or at least it wasn't on my radar).  Now there is no excuse for something to not be threadsafe.  I'll look into this tomorrow and get a patch out.

Sorry for the inconvenience...
