### ISSUE TITLE
negative subindex

### ISSUE THREAD

**Issue by jhc0025** [mlpack/mlpack#1138]
Hi, i've take mlpack from nuget package manager in visual studio 2017.

I wanted just radical, but no problem taking all.

The fact is, i've followed an example, that include care/math/random.hpp.
Of course, i included it, but as long as i kept it in project (didn't used it), at compiling time armadillo give me negative subindex because a trouble with boost, mlpack, or armadillo, don't know where it starts. (mlpack 2.2.0.3 and 2.2.0.5, armadillo 7.8 and boost 1.60 - 1.65 and 1.65.1)

I've just deleted the line and that error goes away, but maybe this problem stay for other people, or maybe it is fixed in a newer version than the nuget published.

Hope it can be fixed and help.

Regards

**Comment by rcurtin** [comment]
Hi there, thanks for the feedback. Can you say which line you had to delete? Thanks!

**Comment by jhc0025** [comment]
I just deleted the
#include <mlpack/math/random.hpp>




El 11 oct. 2017 14:26, "Ryan Curtin" <notifications@github.com> escribió:

Hi there, thanks for the feedback. Can you say which line you had to
delete? Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mlpack/mlpack/issues/1138#issuecomment-335792791>, or mute
the thread

**Comment by jhc0025** [comment]
In my Code.
 I didn't touch mlpack code.

**Comment by rcurtin** [comment]
Ah, okay.  Thanks for the clarification.  I'll go ahead and close this issue then, and anyone searching for a similar issue will be able to find this.  Thank you for sharing! :)

**Comment by jhc0025** [comment]
Hi Ryan.

It disappeared when i deleted the line of the random hpp.
I added and dont need It, so it doesnt affect to me when i delete the line.

But all the time ive compiled and added random library i got the error of
compiling and It didnt work.

My project was fixed deleting the include, but the failure was on mlpack or
boost.

Was a really weird error message.

Regards
