### ISSUE TITLE
RNN, LSTM examples

### ISSUE THREAD

**Issue by kvcuong** [mlpack/mlpack#1139]
Hi,  
The examples in the mlpack/tests help me a lot to understand ML. Could you share some tests on RNNs, LSTMs? 

Thanks.

**Comment by rcurtin** [comment]
Hi there, I think maybe you are looking for `src/mlpack/tests/recurrent_network_test.cpp`.  Also take a look at the models repository: https://github.com/mlpack/models/.  @partobs-mdp did some nice work there with some benchmarking tasks for various RNN-related tasks.

**Comment by kvcuong** [comment]
Thank for your quick reply. 
Yes, I did not see that in my mlpack 2.2.5 but in online repos. 
A+

**Comment by rcurtin** [comment]
Yep, the neural network support has not been released yet.  When it is (mlpack 3.0.0), those tests will be included.  Glad you found what you need. :)
