### ISSUE TITLE
error during built

### ISSUE THREAD

**Issue by sagartripathy** [mlpack/mlpack#1146]
during building mlpack this error is throwing during testing
/home/Music/mlpack-2.2.4/src/mlpack/tests/gmm_test.cpp(234): fatal error in "GMMTrainEMSingleGaussianWithProbability": difference{5.40066%} between g.Component(0).Mean()[0]{0.47299670939187255} and 0.5{0.5} exceeds 5%
/home/Music/mlpack-2.2.4/src/mlpack/tests/load_save_test.cpp(637): fatal error in "LoadHDF5Test": critical check test.n_rows == 4 failed [2 != 4]

*** 2 failures detected in test suite "mlpackTest"

 how to solve this problem. Need help?

**Comment by rcurtin** [comment]
Can you try with the latest version, mlpack-2.2.5?  The GMMTrainEMSingleGaussianWithProbability test failure is an unlucky random seed, nothing is actually wrong.  I believe that test's tolerance was updated in the newer release to reduce false positives.

**Comment by sagartripathy** [comment]
same error for mlpack-2.2.5

home/Music/mlpack-2.2.5/src/mlpack/tests/gmm_test.cpp(234): fatal error in "GMMTrainEMSingleGaussianWithProbability": difference{5.40066%} between g.Component(0).Mean()[0]{0.47299670939187255} and 0.5{0.5} exceeds 5%
/home/Music/mlpack-2.2.5/src/mlpack/tests/load_save_test.cpp(637): fatal error in "LoadHDF5Test": critical check test.n_rows == 4 failed [2 != 4]

*** 2 failures detected in test suite "mlpackTest"

**Comment by zoq** [comment]
Perhaps it makes sense to use 6% tolerance instead of 5% (because of random error), as done for the covariance components.

**Comment by zoq** [comment]
Also, it might be helpful to see how often the test fails. This could be done by setting the random seed at the top of the ``GMMTrainEMSingleGaussianWithProbability`` test case and afterwards run that test in a loop:

```
while(true); do bin/mlpack_test -t GMMTest/GMMTrainEMSingleGaussianWithProbability; sleep 1; done
```

**Comment by rcurtin** [comment]
I did some testing with both mlpack 2.2.5 and the current git master branch; I saw about the same rate of failure for this test in both (12/4000 = 0.003 in 2.2.5, 10/3500 = 0.0029 in git master).  So increasing the tolerance to 6% is a reasonable change in my opinion.

The HDF5 bug is fixed recently with this commit: https://github.com/mlpack/mlpack/commit/86cb5b20ae9632b9908b6abb63cfaaa5c23a92a5, but that has not been released yet.  If you wanted, you could patch your mlpack 2.2.5 code to include this, but it doesn't really matter if you are not planning on using HDF5 support.

@sagartripathy: are you willing to try and debug a little to make sure that the GMM test failure rate is about the same we are seeing?  You could follow Marcus' instructions above; you would insert the `math::RandomSeed(std::time(NULL))` call at line 218 of `src/mlpack/tests/gmm_test.cpp`.  Then you can run the test many times and count the number of failures.  Here's a slightly more complex script that will only print failures (it's what I used):

```
i=0; while(true); do bin/mlpack_test -t GMMTest/GMMTrainEMSingleGaussianWithProbability 2>&1 | grep -v "No errors" | grep -v '^[ \t]*$' | grep -v "Running "; echo $i; i=$(($i + 1)); sleep 1; done
```

**Comment by sagartripathy** [comment]
Guys thank you for the help.

**Comment by rcurtin** [comment]
I'm going to go ahead and close this for inactivity---if there is still a problem that needs to be resolved, we can reopen it.

**Comment by Hunting-Party10** [comment]
Hi, Just got the same error while testing.

`fatal error: in "GMMTest/GMMTrainEMSingleGaussianWithProbability": difference{0.0668215} between g.Component(0).Mean()[0]{0.46868196311231264} and 0.5{0.5} exceeds 5%
`
But the difference seems to be ~0.066%
How did the test trigger this error ?

**Comment by rcurtin** [comment]
Hey @Hunting-Party10, unfortunately that just means you are unlucky. :)  We have many probabilistic tests and sometimes they fail randomly even though nothing is wrong.  Take a look at #1993 if you want to see how you could help fix these---there are some instructions in the description there to reproduce this failure, and then see how much it fails.  For this particular case it should be just fine to widen the tolerances a bit.
