### ISSUE TITLE
HRectBound can only be used with the LMetric<> metric type

### ISSUE THREAD

**Issue by sohaibali01** [mlpack/mlpack#1149]
Hi,
Following example at http://mlpack.org/docs/mlpack-2.2.2/doxygen.php?doc=metrics.html, I wrote this,

class ExampleMetric
{
public:
	ExampleMetric() { }
	template<typename VecTypeA, typename VecTypeB>
	static double Evaluate(const VecTypeA& a, const VecTypeB& b)
	{
		return arma::norm(a - b);
	}
};

Then used this function in the NN computation as under,

int main()
{
	NeighborSearch<NearestNeighborSort, ExampleMetric> nn(trainingData);
	arma::Mat<size_t> neighbors;
	arma::mat distances;
	nn.Search(queryData, 1, neighbors, distances);
}

But it throws an error at hrectbound.hpp at line 58 stating that HRectBound can only be used with the LMetric<> metric type

I'm using mlpack2.2.5....

**Comment by sohaibali01** [comment]
My bad.....
I should have used VP tree....
just replaced the line 
NeighborSearch < NearestNeighborSort, ExampleMetric, arma::mat, mlpack::tree::VPTree> nn(trainingData);

and it works now.......

**Comment by rcurtin** [comment]
Glad you got it figured out, feel free to open any more issues if you have any more problems in the future. :)
