### ISSUE TITLE
Core dumped

### ISSUE THREAD

**Issue by hOdOrNight** [mlpack/mlpack#1156]
While runing
$ mlpack_knn --help
or,
$ mlpack_knn -r dataset.csv -n neighbors_out.csv -d distances_out.csv -k 5 -v

Output:
Segmentation fault (core dumped)

**Comment by rcurtin** [comment]
This isn't enough information to help debug.  Can you tell us what you have done?

**Comment by tnaveen1998** [comment]
Hi @hOdOrNight,
I faced the same issue a while ago and got it fixed.
Run this in your command line,
echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/" >> ~/.bashrc

**Comment by rcurtin** [comment]
Yep, adding it to the bashrc can be useful.  The need for `LD_LIBRARY_PATH` is mentioned in the README too.  I'll go ahead and close this unless there is some other issue.
