### ISSUE TITLE
Allow custom layer types in neural networks

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1160]
Currently a user can't implement their own custom layer type and use it in an `FFN` or `RNN`.  We'd discussed a solution that might look a little bit like this for the user:

```
template<typename OutputLayerType,
         typename InitializationType,
         typename... ExtraLayerTypes>
```

Something like that could be implemented by making the `LayerTypes` typedef a template typedef that also includes the set of extra classes.  (Of course that is not the only way to do it.)

**Comment by scrcro** [comment]
Thank you. 
This is much needed. I tried to look at the code, looks like many visitor implementation will also have to be templated to get this done. Thoughts?

**Comment by rcurtin** [comment]
I don't think any modifications to the visitor implementations will be necessary; if we make `LayerTypes` a template typedef and any custom layers have the correct `Forward()`, `Backward()`, and `Gradient()` signatures, then the existing visitor infrastructure should work fine.

**Comment by scrcro** [comment]
The Model() functions are returning the network. Which needs to be of type std:: vector<LayerTypes<CustomLayers*...> >. Now the HasModel checks should also therefore change. Am I getting this wrong?

**Comment by scrcro** [comment]
I agree that the visitor infra should not have to be aware of the layer types. But the HasModel checks have inadvertently added the dependency on LayerTypes. Ideally the actual layer type (parameter T) should decide what other layers are required. Therefore the return type for the Model functions should be also dependent on the template parameter T in HasModelCheck. 
I struggled with the code, as I am new to mlpack, but looks like this option is a massive change, albeit not complex. 
Also let me take the opportunity to thank you and all the contributors for this package. There is only a handful of these in C++ and this is by far the best I have come across. 
I would love to contribute to the changes for supporting custom layers. Please let me know how to start, specially to understand and establish the ground rules.

**Comment by zoq** [comment]
You are right, that's an issue, I have to think about a clever solution. Btw. if we use clang the custom layer can just inherit from an existing layer and it works, maybe we can achieve the same with gcc. Not sure, that's possible, will look into each direction. Thanks again for bringing this issue up.

**Comment by scrcro** [comment]
I tried with clang (3.x) but that did not work for me. I mean I added a layer which I had derived from linear. But it rightly calls the linear layer functions (Forward) rather than my class'. 
One option could be to use a typedef inside the layers for LayerTypes or the LayerTypes<CustomLayers...> and use the same typedef in the HasModelCheck. This would be a large scale change I think.

**Comment by zoq** [comment]
Sorry for the slow response on this one, I like the typedef idea and I agree it would come with some necessary adjustments. Adding on the typedef idea, perhaps we can just rewrite the model visitor so that it is type agnostic. All we really like to know is, does the layer implement the ``Model`` method, the return type is somewhat unimportant. According to this thread: https://stackoverflow.com/questions/87372/check-if-a-class-has-a-member-function-of-a-given-signature it should be possible to check for a member function with given name and any signature.

**Comment by scrcro** [comment]
The example is not just looking for name but for a function which returns `size_t` and has a name `used_memory` . How do we specify the second template parameter in `struct SFINAE`  in this particular example? I have not run the example though, this is from reading the code. If this works for any return type that would be the right solution in our case.

**Comment by zoq** [comment]
Sorry for the confusion I was talking about: https://stackoverflow.com/a/16867422 which shows how to check for a function with any signature, haven't tested the code yet, however, I think it might be possible to adapt the snippet accordingly.

**Comment by rcurtin** [comment]
We do have some code that does something like this already that I think you could adapt---take a look at `src/mlpack/core/data/has_serialize.hpp` and `src/mlpack/core/util/sfinae_utility.hpp`.  Right now the `HAS_EXACT_METHOD_FORM()` macro will not work for an arbitrary type, but I think some of the ideas could be adapted.  I've come across the StackOverflow post @zoq mentioned before, I think that's a great post and you could use the ideas there.

**Comment by scrcro** [comment]
Sounds good. Let me try these out. I did try to run the code provided in the stackoverflow link. It does not work yet for me. I will try some more.

**Comment by scrcro** [comment]
I tried the code mentioned in the stackoverflow link. It did not work for me in VS 2015, but worked in Linux. It is a great post but I thought it does a lot more than we need.
I investigated a little bit more and found `std::is_member_function_pointer` (C++11) which makes it far more simpler to check for a member function. I have the following macro which does the job. Tested with VS2015, Clang-5 GCC-6 and GCC-7.  Perhaps a little more work needed to make it robust and perhaps take both class name and function name as parameters. But does the job.
```
#include <type_traits>
#define CHECK_MEM_FUNC(NAME)                                                   \
template <typename T>                                                          \
struct has_member_function                                                     \
{                                                                              \
    template <typename Q = T>                                                  \
    static typename                                                            \
    enable_if<is_member_function_pointer<decltype(&Q::NAME)>::value,int>::type \
    f(int t)                                                                   \
    {                                                                          \
	return 1;                                                              \
    }                                                                          \
                                                                               \
    template <typename Q = T>                                                  \
    static char f(char t)                                                      \
    {                                                                          \
	return 0;                                                              \
    }                                                                          \
                                                                               \
    static const bool value = sizeof(f<T>(0)) != sizeof(char);                 \
};

```
And then use this like:
```
using namespace std;
CHECK_MEM_FUNC(FnName)
int main(int argc, char** argv)
{
   cout << has_member_function<ClassName>::value << endl;
}
```

**Comment by zoq** [comment]
Looks really good to me; also I agree it would be great if we could make this solution more general, so that we can write ``HAS_ANY_METHOD_FORM(METHOD, NAME)``, or something like that. What do you think? Also https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/util/sfinae_utility.hpp and https://github.com/mlpack/mlpack/blob/847a4bfd69f9bf7c6269166673158a88ceac89a8/src/mlpack/core/data/has_serialize.hpp#L41 might be helpful.

Thanks again for take a closer look into the issue.

**Comment by scrcro** [comment]
Thank you and happy to contribute my 2 cents to this excellent C++ ML package. 
Yes this is possible. Here is a sample implementation.
```
#ifndef HASMEMFUNC_H
#define HASMEMFUNC_H

#include <type_traits>
#define HAS_ANY_METHOD_FORM( FUNC, NAME )                                                                                  \
  template < typename T >                                                                                                  \
  struct has_member_function                                                                                               \
  {                                                                                                                        \
    template < typename Q = T >                                                                                            \
    static typename std::enable_if< std::is_member_function_pointer< decltype( &Q::FUNC ) >::value, int >::type f( int t ) \
    {                                                                                                                      \
      return 1;                                                                                                            \
    }                                                                                                                      \
                                                                                                                           \
    template < typename Q = T >                                                                                            \
    static char f( char t )                                                                                                \
    {                                                                                                                      \
      return 0;                                                                                                            \
    }                                                                                                                      \
                                                                                                                           \
    static const bool value = sizeof( f< T >( 0 ) ) != sizeof( char );                                                     \
  };                                                                                                                       \
                                                                                                                           \
  template < typename T >                                                                                                  \
  struct NAME                                                                                                              \
  {                                                                                                                        \
    static const bool value = has_member_function< T >::value;                                                             \
  };
#endif // HASMEMFUNC_H
```

**Comment by zoq** [comment]
Great, can you open a PR, we have to add some tests to make sure this works as expected.

**Comment by scrcro** [comment]
I guess this can be closed now.

**Comment by rcurtin** [comment]
Agreed, I believe this is done now.  Thank you for your hard work with the PR; it is really nice to see the support. :)
