### ISSUE TITLE
Weak Learner for AdaBoost

### ISSUE THREAD

**Issue by olesyaksyon** [mlpack/mlpack#1163]
I would like to see examples, how to pass weak learner to AdaBoost. Agree to definition - weak learner is some weak classifier (perceptron is by default). But when I create weak classifier like:

mlpack::perceptron::Perceptron<> w_l(mat_, labels, 2)

and pass it to AdaBoost like:

mlpack::adaboost::AdaBoost<arma::mat> adaboost(mat_, labels, w_l);

it return mistake - w_l should be arma::Mat<double>. So how should I get the weak classifier correctly?

**Comment by olesyaksyon** [comment]
I also tried to pass weights (w_l.Weights()), but I have another mistake:

error: no matching function for call to ‘arma::Mat<double>::Mat(const arma::Mat<double>&, arma::Mat<double>&, const arma::Row<long unsigned int>&, arma::rowvec&)’
     WeakLearnerType w(other, tempData, labels, weights);

**Comment by rcurtin** [comment]
Can you give the exact error output?  I reviewed thd documentation and your code and it appears you are doing everything correctly.

Note that when you pass a weak learner to `AdaBoost`, only the parameters it was trained with are used to train new learners.  So in your example you are passing a `Perceptron` with default parameters, which will be no different than passing no weak learner at all.

In any case if you can provide more exact error output I can help more.

**Comment by olesyaksyon** [comment]
in more details:

1. Var:

**mlpack::perceptron::Perceptron<> w_l(mat_, labels, 2); 
mlpack::adaboost::AdaBoost<arma::mat> adaboost(mat_, labels, w_l);**

where mat is arms::Mat<double> and labels is arma::Row <long unsigned int>.

**error:** no matching function for call to ‘mlpack::adaboost::AdaBoost<arma::Mat<double> >::AdaBoost(arma::Mat<double>&, arma::Row<long unsigned int>&, mlpack::perceptron::Perceptron<>&)’
     mlpack::adaboost::AdaBoost<arma::mat> adaboost(mat_, labels, w_l);

no known conversion for argument 3 from ‘mlpack::perceptron::Perceptron<>’ to ‘const arma::Mat<double>&’

2 Var:

I am passing weights of weak classifier

**mlpack::perceptron::Perceptron<> w_l(mat_, labels, 2); 
mlpack::adaboost::AdaBoost<arma::mat> adaboost(mat_, labels, w_l.Weghits());**

 **error:** no matching function for call to ‘arma::Mat<double>::Mat(const arma::Mat<double>&, arma::Mat<double>&, const arma::Row<long unsigned int>&, arma::rowvec&)’
     WeakLearnerType w(other, tempData, labels, weights);
error occures in file **adaboost_impl.hpp:120:55**
no known conversion for argument 1 from ‘const arma::Mat<double>’ to ‘const arma::arma_vec_indicator&’

**Comment by rcurtin** [comment]
The issue is with the type you are using: `mlpack::adaboost::AdaBoost<arma::mat>`.  Instead this should be `mlpack::adaboost::AdaBoost<mlpack::perceptron::Perceptron<>>`.

**Comment by olesyaksyon** [comment]
thanks for help, now it works!

**Comment by rcurtin** [comment]
Sure, happy to help. :)
