### ISSUE TITLE
Memory leaks detected by Boost tests

### ISSUE THREAD

**Issue by e-freiman** [mlpack/mlpack#1187]
When running tests on Windows machine (and compiled by Visual C++ compiler in Debug mode), Boost find many memory leaks. They aren't visible on Linux because of [this](http://www.boost.org/doc/libs/1_64_0/libs/test/doc/html/boost_test/utf_reference/rt_param_reference/detect_memory_leaks.html):

> The only platform which supports memory leak detection is Microsoft Visual Studio family of compilers in debug builds.

I guess this could be a hard issue to handle. As a first step I want to try running each test separately (may be through a python script) and post here which tests exactly reveal memory leaks. Does it make sense? Any ideas?

**Comment by zoq** [comment]
Sounds like a good plan; we should reactive the existing memory test jenkins job (valgrind), btw. you can use: ``mlpack_test --list_content`` to get all test suites/cases; perhaps: https://gist.github.com/zoq/a7ab3d96f0872f03a7aa63a2bd38980d is helpful to clear the output.

**Comment by evgfreyman** [comment]
I run tests separately by using [this script](https://gist.github.com/evgfreyman/fc60883150b2d215df52f418e0a439f2) on my machine - Windows 8.1, Visual C++ 2015. The results are following:

ANNLayerTest/SimpleAddMergeLayerTest - has memory leaks
ANNLayerTest/GradientGRULayerTest - failed
CFTest/CFPredictTest - failed
FastMKSTest/SimpleTrainKernelTest - has memory leaks
FastMKSTest/SerializationTest - has memory leaks
FastMKSTest/FastMKSModelLinearTest - has memory leaks
FastMKSTest/FastMKSModelPolynomialTest - has memory leaks
FastMKSTest/FastMKSModelCosineTest - has memory leaks
FastMKSTest/FastMKSModelGaussianTest - has memory leaks
FastMKSTest/FastMKSModelEpanTest - has memory leaks
FastMKSTest/FastMKSModelTriangularTest - has memory leaks
HoeffdingTreeTest/MultipleSerializationTest - has memory leaks
HoeffdingTreeTest/HoeffdingTreeModelSerializationTest - has memory leaks
LSHTest/CopyConstructorAndOperatorTest - has memory leaks
QDAFNTest/QDAFNUniformSet - failed - has memory leaks
RecurrentNetworkTest/SequenceClassificationTest - has memory leaks
RecurrentNetworkTest/GRURecursiveReberGrammarTest - failed
RecurrentNetworkTest/GRUDistractedSequenceRecallTest - failed
RecurrentNetworkTest/GRUBatchSizeTest - failed
RecurrentNetworkTest/SerializationTest - has memory leaks
SerializationTest/CubeSerializeTest - has memory leaks
SerializationTest/HoeffdingTreeAfterSplitTest - has memory leaks
SerializationTest/HoeffdingTreeTest - has memory leaks
TreeTest/BinarySpaceTreeCopyConstructor - has memory leaks
VantagePointTreeTest/HollowBallBoundTest - has memory leaks
ANNLayerTest/SimpleAddMergeLayerTest - has memory leaks
ANNLayerTest/GradientGRULayerTest - failed
CFTest/CFPredictTest - failed
FastMKSTest/SimpleTrainKernelTest - has memory leaks
FastMKSTest/SerializationTest - has memory leaks
FastMKSTest/FastMKSModelLinearTest - has memory leaks
FastMKSTest/FastMKSModelPolynomialTest - has memory leaks
FastMKSTest/FastMKSModelCosineTest - has memory leaks
FastMKSTest/FastMKSModelGaussianTest - has memory leaks
FastMKSTest/FastMKSModelEpanTest - has memory leaks
FastMKSTest/FastMKSModelTriangularTest - has memory leaks
HoeffdingTreeTest/MultipleSerializationTest - has memory leaks
HoeffdingTreeTest/HoeffdingTreeModelSerializationTest - has memory leaks
LSHTest/CopyConstructorAndOperatorTest - has memory leaks
QDAFNTest/QDAFNUniformSet - failed - has memory leaks
RecurrentNetworkTest/SequenceClassificationTest - has memory leaks
RecurrentNetworkTest/GRURecursiveReberGrammarTest - failed
RecurrentNetworkTest/GRUDistractedSequenceRecallTest - failed
RecurrentNetworkTest/GRUBatchSizeTest - failed
RecurrentNetworkTest/SerializationTest - has memory leaks
SerializationTest/CubeSerializeTest - has memory leaks
SerializationTest/HoeffdingTreeAfterSplitTest - has memory leaks
SerializationTest/HoeffdingTreeTest - has memory leaks
TreeTest/BinarySpaceTreeCopyConstructor - has memory leaks
VantagePointTreeTest/HollowBallBoundTest - has memory leaks

Total tests 1067
Total failed 6
Total leaked 20

**Comment by evgfreyman** [comment]
Personally, I'm interested in recurrent networks, so I'll try to investigate memory leaks in this algorithm with [Valgrind](http://valgrind.org/ )

**Comment by zoq** [comment]
Sounds good, I think to resolve all recurrent network related memory issues we have to resolve: https://github.com/mlpack/mlpack/pull/1091 first.

**Comment by zoq** [comment]
Also, I will reactivate the jenkins valgrind job.

**Comment by evgfreyman** [comment]
It appeared to be hard for me start fixing these issues right away. At the beginning I should try using FNN and RNN classes as a user. However, it'll take some time, so if anybody can fix memory issues faster than me - welcome. 

By the way, I might create a well commented example of FNN usage for solving [MINST problem from Kaggle](https://www.kaggle.com/c/digit-recognizer)

**Comment by rcurtin** [comment]
@evgfreyman---an example would be great; we could then add it to the mlpack/models repository if you liked.

I'll handle the FastMKS leaks since I wrote that test, if I can reproduce the leaks on Linux.

**Comment by rcurtin** [comment]
I only saw a leak with valgrind for `FastMKSTest/SerializationTest`; here is a patch:

https://gist.github.com/rcurtin/a0b1e5d128eef34f877b538c86a00e5f

**Comment by zoq** [comment]
I'll take a look at the nn related issue.

**Comment by rcurtin** [comment]
@evgfreyman: just a note, if you are working with RNNs to make a tutorial, #1192 has just been merged which changes the format of the input data, so I hope this doesn't break anything you have been working on.  (If it does, well, the changes should not be so hard, hopefully.)

**Comment by evgfreyman** [comment]
I'm working on FFN so far

**Comment by rcurtin** [comment]
Sorry, my FastMKS fix from earlier was incorrect and incomplete.  Here's a better one:

https://gist.github.com/rcurtin/58e010fbf4344e905f8b892390b0d0fe
