### ISSUE TITLE
Use Clang-Format

### ISSUE THREAD

**Issue by ShikharJ** [mlpack/mlpack#1203]
Currently, one has to manually format the code after implementation. In my short time with `mlpack`, I had to push twice a couple of times just to fix the formatting issue, which leads to unnecessary CI backlogs. It'd be nice if a contributor could just run a script to automatically format the code. Thoughts?

**Comment by zoq** [comment]
I think that's a good idea, as long as we can provide something that's compliant with our style guidelines (https://github.com/mlpack/mlpack/wiki/DesignGuidelines).

**Comment by rcurtin** [comment]
Yeah, I agree, I think it would be reasonable to add a utility script to the repository to format code (or provide a configuration for a tool).  See also #420, #978.

**Comment by sbrodehl** [comment]
Uhhh yes, I like.

**Comment by Shashi456** [comment]
How i probably go about completing the travis integration @ShikharJ

**Comment by ShikharJ** [comment]
Hi @Shashi456. As you can see from the discussion in #1205, we're still under discussion regarding what should be done regarding this issue. We're probably past the idea of `Travis` integration for `Clang-Format`, though you might want to dig into @rcurtin's idea [here](https://github.com/mlpack/mlpack/pull/1205#issuecomment-360147330)?

**Comment by ShikharJ** [comment]
Closing this for now.
