### ISSUE TITLE
GAN tests implementation

### ISSUE THREAD

**Issue by lozhnikov** [mlpack/mlpack#1206]
In summer 2017 @kris-singh wrote an implementation of GAN as a part of his GSoC program. He checked the implementation on this [test](http://blog.aylien.com/introduction-generative-adversarial-networks-code-tensorflow/).
Unfortunately we were unable to reimplement this [test](https://www.oreilly.com/learning/generative-adversarial-networks-for-beginners).
Ongoing work: [Kris's GAN implementation](https://github.com/mlpack/mlpack/pull/1066), [Kris's GAN test (gan_conv.cpp) ](https://gist.github.com/kris-singh/40dc1db9f257c1694245393392e4e9cf), [ResizeLayer implementation](https://github.com/mlpack/mlpack/pull/1098), [CrossEntropyWithLogits implementation](https://github.com/mlpack/mlpack/pull/1200) and [a clone of the original GAN PR](https://github.com/mlpack/mlpack/pull/1204).

Our GAN implementation differs from others since it uses only one optimizer for both the discriminator and the generator network. I think it shouldn't be an error, however, I can't be sure since we didn't try the original implementation.

So, we should fix either the test, or the GAN implementation. It would be nice to discover the fix.

**Comment by ShikharJ** [comment]
@lozhnikov Was this done for any performance improvement? If not, I would go for the implementation fix in the GAN PR.

**Comment by lozhnikov** [comment]
@ShikharJ That was done in order to comply with the mlpack API since other mlpack methods use only one optimizer. Actually, I don't know how to add the second optimizer without API violation and crutches.

**Comment by ShikharJ** [comment]
@lozhnikov Optimizer separation would be tested out soon. This issue can be closed as well @zoq.

**Comment by zoq** [comment]
Thanks!
