### ISSUE TITLE
SpikeSlab RBM tests implementation

### ISSUE THREAD

**Issue by lozhnikov** [mlpack/mlpack#1207]
In summer 2017 @kris-singh wrote an implementation of Binary RBM and Spike and Slab RBM. The first one is implemented according to this [article](http://deeplearning.net/tutorial/rbm.html). And the second one is implemented according to this [paper](http://www.jmlr.org/proceedings/papers/v15/courville11a.html).
We reproduced the deeplearning.net MNIST generation test. Here are some samples generated by the binary RBM:

![mnist_out](https://user-images.githubusercontent.com/10090844/35193117-43cb15bc-feaf-11e7-80e7-abbf9b3aeaa0.png)

Moreover we tried these models for classification on [the Digit dataset](http://archive.ics.uci.edu/ml/datasets/Pen-Based+Recognition+of+Handwritten+Digits).

Unfortunately, we didn't implement extensive tests for the spike and slab RBM implementation. It would be nice to reproduce some tests from the original [paper](http://www.jmlr.org/proceedings/papers/v15/courville11a.html) e.g. see section 6.3. "Learning Features for classification".

Ongoing work: [Kris's RBM PR](https://github.com/mlpack/mlpack/pull/1046), [some thoughts on the ssRBM classification test](https://gist.github.com/kris-singh/55a4934c463bbddb3c8d321dd889d194).

**Comment by ShikharJ** [comment]
@lozhnikov I had actually started working on some of Kris' PRs, after the discussion on the [IRC](http://www.mlpack.org/irc/mlpack.20180111.html). I have a branch [here](https://github.com/ShikharJ/mlpack/tree/RBM). Again it contains only minor conflict resolutions. I'll file a PR soon.

**Comment by lozhnikov** [comment]
@ShikharJ ok, feel free to ask questions

**Comment by Rajiv2605** [comment]
Can I work on this issue?

**Comment by KunvarThaman** [comment]
@lozhnikov I'm looking to work on the _Essential Deep learning modules_ project. Is it okay if I work on this issue?

**Comment by sundar-10** [comment]
Hello,
I have seen the 2 papers- Binary RBM and Spike and Slab RBM. And i would like to work on this issue..Is it okay?

**Comment by PrashantSaroj** [comment]
@lozhnikov @ShikharJ @Rajiv2605  I am willing to work on the "Essential Deep learning modules" project. How do I get started?

**Comment by zoq** [comment]
Actually, this was implemented by @ShikharJ. But if anybody likes to work on additional tests, please feel free. The tests can be found here: https://github.com/mlpack/mlpack/blob/master/src/mlpack/tests/rbm_network_test.cpp.

About how to get started, see http://mlpack.org/gsoc.html for a general answer. For the "Essential Deep learning modules" idea, it's helpful to get familiar with the network codebase, run and understand the tests, the models repo https://github.com/mlpack/models might be interesting as well.

**Comment by ShikharJ** [comment]
We currently have an additional open PR for SSRBM test implementation at #1477. If someone wishes to take it up, please feel free to do so.

**Comment by heisenbuug** [comment]
Hey, I am actually thinking of taking this on as my GSoC project, but I think the implementation is already done. So why is this still listed in GSoC idealist? Does this need reimplementation?
