### ISSUE TITLE
Examples of using MLPack

### ISSUE THREAD

**Issue by evgfreyman** [mlpack/mlpack#1212]
Not sure where to put this message. Please close it if it's a wrong place. 

I created an example of using Feed Forward Network (FFN) for [Digit Recognizer problem](https://www.kaggle.com/c/digit-recognizer) from Kaggle with tons of comments. [Here it is](https://github.com/evgfreyman/KaggleExperiments/blob/master/MNIST-MLPack/main.cpp). It would be very cool if you could criticize my code as much as possible

**Comment by rcurtin** [comment]
Agreed, it looks great!  It might be useful to put the Kaggle-specific functionality into its own header file, so that someone else could easily use that for their Kaggle-mlpack experiments. :+1:

**Comment by evgfreyman** [comment]
Added [a pull request](https://github.com/mlpack/models/pull/5) to models project.

**Comment by sourabhvarshney111** [comment]
@evgfreyman I think the work regarding this issue has been completed in your pr. Will you mind closing this? : )

**Comment by rcurtin** [comment]
@sourabhvarshney111---thanks for pointing this out; I agree that this issue can be closed so I'll go ahead and do that. 

@evgfreyman: thanks again for the Kaggle model; I am happy to have it as a nice example in the repository. :)

**Comment by evgfreyman** [comment]
Sure, this can be closed
