### ISSUE TITLE
Missing common initializations in the ann module

### ISSUE THREAD

**Issue by sshkhr** [mlpack/mlpack#1228]
Xavier initialization (introduced in [Understanding the difficulty of training deep feedforward neural networks](http://proceedings.mlr.press/v9/glorot10a/glorot10a.pdf) ) and He initialization (introduced in [Delving Deep into Rectifiers: Surpassing Human-Level Performance on ImageNet Classification](https://arxiv.org/abs/1502.01852) ) are among the most common initializations used today in training deep neural nets. I found that mlpack is missing an implementation of these in the init_rules of the ann module.  

#939 was working on implementing these but no work has been done on it for some time now. Is this feature still being worked on ?

**Comment by sshkhrnwbie** [comment]
Thanks for the update @zoq . I will try and work on it over the weekend. If I need any help I will take the discussion to the irc channel.

**Comment by zoq** [comment]
Sounds good.

**Comment by saurabhpal97** [comment]
@sshkhrnwbie any updates regarding the implementation? I also want to work on this issue so if you have not already implemented the initialization modules maybe we can split the work.

**Comment by sshkhrnwbie** [comment]
That sounds like a great idea @saurabhpal97 . I am trying to get a VarianceScaling initializer implementation to work. You will find it much easier to implement the Xavier and He initializers using it once it is finished.

**Comment by saurabhpal97** [comment]
Thanks @sshkhrnwbie  I will get right to it

**Comment by kartikdutt18** [comment]
Hey @rcurtin, should we close this issue ?
He Initialization(#1280) and Glorot Initialization (Xavier #1272) are already present in mlpack. Thanks.

**Comment by kartikdutt18** [comment]
Hey @rcurtin, @zoq should we close this issue ?
He Initialization and Glorot Initialization (Xavier) are already present in mlpack. Thanks.

**Comment by rcurtin** [comment]
@kartikdutt18 you're right, thanks for pointing it out.  I think we can close it.  (If I missed something, let me know, we can reopen it. :))
