### ISSUE TITLE
armadillo 8.400 RC1

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/mlpack#1230]
@rcurtin  - I've released Armadillo 8.400 RC1 (Release Candidate 1):
http://sourceforge.net/projects/arma/files/armadillo-8.400-RC1.tar.xz

Could you test it and let me know if you encounter any issues?

Apart from the changes listed below, I've also tagged a bunch of iterator functions to warn if their output is unused.  This shows up as many warnings when compiling mlpack.  The most relevant is SpMat::iterator::operator++(int), which creates a copy of the iterator and returns it.

Changes:
- added [wishrnd()](http://arma.sourceforge.net/docs.html#wishrnd) and [iwishrnd()](http://arma.sourceforge.net/docs.html#iwishrnd) for generation of random Wishart matrices
- added [chi2rnd()](http://arma.sourceforge.net/docs.html#chi2rnd) for generation of chi-squared random numbers
- added [normcdf()](http://arma.sourceforge.net/docs.html#normcdf)
- added [submatrix & subcube iterators](http://arma.sourceforge.net/docs.html#iterators_submat)
- faster handling of sparse matrices by [repmat()](http://arma.sourceforge.net/docs.html#repmat)
- faster [loading](http://arma.sourceforge.net/docs.html#save_load_mat) of CSV files
- expanded [kron()](http://arma.sourceforge.net/docs.html#kron) to handle sparse matrices
- expanded [index_min()](http://arma.sourceforge.net/docs.html#index_min_and_index_max_standalone) and [index_max()](http://arma.sourceforge.net/docs.html#index_min_and_index_max_standalone) to handle cubes
- expanded [randi()](http://arma.sourceforge.net/docs.html#randi), [randu()](http://arma.sourceforge.net/docs.html#randu_randn_standalone), [randn()](http://arma.sourceforge.net/docs.html#randu_randn_standalone), [randg()](http://arma.sourceforge.net/docs.html#randg) to output single scalars

**Comment by rcurtin** [comment]
Thanks for the notification.  I built with gcc and clang and there were a few internal Armadillo warnings:

```
In file included from /home/ryan/src/mlpack/src/mlpack/tests/drusilla_select_test.cpp:1:
In file included from /home/ryan/src/mlpack/build-arma8.4/src/mlpack/tests/cotire/mlpack_test_CXX_prefix.hxx:4:
In file included from /home/ryan/src/mlpack/build-arma8.4/src/mlpack/tests/cotire/mlpack_test_CXX_prefix.cxx:4:
In file included from /home/ryan/src/mlpack/src/mlpack/core.hpp:238:
In file included from /home/ryan/src/mlpack/src/mlpack/prereqs.hpp:105:
In file included from /home/ryan/src/mlpack/src/mlpack/core/arma_extend/arma_extend.hpp:52:
In file included from /home/ryan/src/armadillo-8.400-RC1/tmp/include/armadillo:597:
/home/ryan/src/armadillo-8.400-RC1/tmp/include/armadillo_bits/SpMat_iterators_meat.hpp:490:7: warning: ignoring return value of function declared with warn_unused_result attribute [-Wunused-result]
    it++;
```

```
In file included from /home/ryan/src/mlpack/src/mlpack/methods/nmf/nmf_main.cpp:12:
In file included from /home/ryan/src/mlpack/src/mlpack/prereqs.hpp:105:
In file included from /home/ryan/src/mlpack/src/mlpack/core/arma_extend/arma_extend.hpp:52:
In file included from /home/ryan/src/armadillo-8.400-RC1/tmp/include/armadillo:436:
/home/ryan/src/armadillo-8.400-RC1/tmp/include/armadillo_bits/fn_accu.hpp:600:44: warning: unused parameter 'P' [-Wunused-parameter]
accu_cube_proxy_at_mp(const ProxyCube<T1>& P)
```

I also went ahead and fixed some of the mlpack-specific warnings as an add-on to another open PR (#1229); thanks for pointing those out.

**Comment by conradsnicta** [comment]
@rcurtin - thanks for testing this. I've fixed the problems you listed and addressed a bunch of other minor issues.  Could you do test RC2?
http://sourceforge.net/projects/arma/files/armadillo-8.400-RC2.tar.xz

**Comment by rcurtin** [comment]
Built, ran tests, looks good to me.  No warnings in gcc or clang.  Thanks!  I'll go ahead and close this now (unless you have more you want me to test).
