### ISSUE TITLE
Python import takes too long.

### ISSUE THREAD

**Issue by akhandait** [mlpack/mlpack#1231]
I built mlpack from source according to the documentation.
Importing mlpack in python 2.7 takes too much time, I timed it:
It takes about 30 seconds to import mlpack or any of its specific parts like knn.
Is it due to it being kept as an egg file in python dist-packages?

**Comment by rcurtin** [comment]
Hi there,

You are absolutely right; the fact that mlpack is an egg file in dist-packages means that all of the .so files have to be unpacked and then loaded.  If you unpack the egg file directly into dist-packages, this should help fix the issue.  However, I have not managed to find a way to get setuptools to install directly and not as an egg.  If you know the trick for how to do that, it would definitely be worthwhile to merge. :)  (see `src/mlpack/bindings/python/setup.py.in`; that's what we generate the setuptools configuration from)

**Comment by akhandait** [comment]
#1233

**Comment by akhandait** [comment]
@rcurtin Do look into the pull request.

**Comment by rcurtin** [comment]
Don't worry, repository owners get emails for just about everything that happens in the repository, so no reminder is needed.  I had just not taken the time to look into it yet.
