### ISSUE TITLE
Greedy algorithm in neighbor search gives wrong results

### ISSUE THREAD

**Issue by akhandait** [mlpack/mlpack#1266]
While writing tests to check outputs of all algorithms for `knn` and `kfn` bindings, I found that outputs of greedy algorithm are not the same as other three(dual_tree, naive, single_tree).
I checked manually and it is indeed the case.

I have used `test_data_3_1000.csv` as reference and `rann_test_r_3_900.csv` as query.
k = 10.

The first 10 nearest neighbor entries of the dual_tree output
(naive and single_tree are the same as this):
100 | 618 | 666 | 942 | 504 | 978 | 462 | 609 | 633 | 314
101 | 315 | 84 | 327 | 587 | 79 | 366 | 498 | 624 | 459
102 | 967 | 623 | 189 | 652 | 136 | 690 | 571 | 484 | 755
103 | 399 | 450 | 222 | 563 | 428 | 457 | 828 | 85 | 41
104 | 708 | 458 | 817 | 400 | 70 | 390 | 474 | 582 | 488
105 | 986 | 640 | 343 | 631 | 96 | 588 | 252 | 669 | 362
106 | 296 | 414 | 556 | 32 | 943 | 761 | 448 | 944 | 800
107 | 192 | 197 | 698 | 571 | 129 | 295 | 145 | 885 | 368
108 | 941 | 175 | 513 | 788 | 378 | 856 | 616 | 973 | 123
109 | 927 | 529 | 155 | 535 | 204 | 619 | 703 | 421 | 656

The first 10 entries of the greedy output:
100 | 618 | 666 | 942 | 504 | 978 | 609 | 633 | 140 | 290
101 | 315 | 84 | 327 | 587 | 79 | 366 | 624 | 297 | 559
102 | 967 | 623 | 652 | 136 | 755 | 443 | 175 | 973 | 123
222 | 828 | 526 | 505 | 940 | 1 | 703 | 864 | 813 | 858
104 | 708 | 817 | 582 | 389 | 875 | 83 | 302 | 794 | 693
362 | 860 | 954 | 912 | 949 | 836 | 576 | 991 | 54 | 357
106 | 296 | 32 | 761 | 800 | 680 | 342 | 697 | 379 | 69
107 | 192 | 197 | 698 | 571 | 129 | 145 | 368 | 115 | 988
108 | 941 | 175 | 788 | 856 | 973 | 123 | 388 | 751 | 755
109 | 927 | 529 | 155 | 204 | 619 | 656 | 219 | 776 | 423

Do see #1263 for the algorithm test.

**Comment by rcurtin** [comment]
That is because the greedy algorithm is an approximate algorithm.  Please read the paper:

http://papers.nips.cc/paper/2666-an-investigation-of-practical-approximate-nearest-neighbor-algorithms.pdf

**Comment by akhandait** [comment]
Okay, sorry for that. I would make sure to check next time whether something really is an issue.
