### ISSUE TITLE
undefined reference to `zgemv_' when making a new block in gnu radio, using code which is using armadillo

### ISSUE THREAD

**Issue by farhanrao895** [mlpack/mlpack#1292]
i have installed libraries lapack,open blas,blas, arpack, mlpack.

armadillo is working normally with mycode.cpp file and giving me the expexted output but when i put my code in gnu radio new block .cc file it gives errors, when i made a simple block using armadillo using simple functions like sum and generation of complex vectors in gnu radio, new block was made perfectly and is working. As in my actual code i am using some functions like solve which uses libs like lapack etc then it give these errors

make
[  8%] Built target gnuradio-cos
[ 12%] Linking CXX executable test-cos
CMakeFiles/test-cos.dir/first_impl.cc.o: In function `gr::cos::first_impl::CoSaMP(arma::Col<std::complex<double> >, arma::Mat<std::complex<double> >, int, int, arma::Col<std::complex<double> >&)':
first_impl.cc:(.text+0x2893): undefined reference to `zgemv_'
first_impl.cc:(.text+0x295d): undefined reference to `zgemv_'
first_impl.cc:(.text+0x2c18): undefined reference to `zgbsv_'
CMakeFiles/test-cos.dir/first_impl.cc.o: In function `bool arma::auxlib::solve_square_refine<arma::Mat<std::complex<double> > >(arma::Mat<std::complex<arma::Mat<std::complex<double> >::pod_type> >&, arma::Mat<std::complex<double> >::pod_type&, arma::Mat<std::complex<arma::Mat<std::complex<double> >::pod_type> >&, arma::Base<std::complex<arma::Mat<std::complex<double> >::pod_type>, arma::Mat<std::complex<double> > > const&, bool)':
first_impl.cc:(.text._ZN4arma6auxlib19solve_square_refineINS_3MatISt7complexIdEEEEEbRNS2_IS3_INT_8pod_typeEEEERS7_SA_RKNS_4BaseIS8_S6_EEb[_ZN4arma6auxlib19solve_square_refineINS_3MatISt7complexIdEEEEEbRNS2_IS3_INT_8pod_typeEEEERS7_SA_RKNS_4BaseIS8_S6_EEb]+0x427): undefined reference to `zgesvx_'
CMakeFiles/test-cos.dir/first_impl.cc.o: In function `void arma::glue_times::apply<std::complex<double>, false, false, false, arma::Mat<std::complex<double> >, arma::Mat<std::complex<double> > >(arma::Mat<std::complex<double> >&, arma::Mat<std::complex<double> > const&, arma::Mat<std::complex<double> > const&, std::complex<double>)':
first_impl.cc:(.text.hot._ZN4arma10glue_times5applyISt7complexIdELb0ELb0ELb0ENS_3MatIS3_EES5_EEvRNS4_IT_EERKT3_RKT4_S6_[_ZN4arma10glue_times5applyISt7complexIdELb0ELb0ELb0ENS_3MatIS3_EES5_EEvRNS4_IT_EERKT3_RKT4_S6_]+0x111): undefined reference to `zgemm_'
first_impl.cc:(.text.hot._ZN4arma10glue_times5applyISt7complexIdELb0ELb0ELb0ENS_3MatIS3_EES5_EEvRNS4_IT_EERKT3_RKT4_S6_[_ZN4arma10glue_times5applyISt7complexIdELb0ELb0ELb0ENS_3MatIS3_EES5_EEvRNS4_IT_EERKT3_RKT4_S6_]+0x1f1): undefined reference to `zgemv_'
CMakeFiles/test-cos.dir/first_impl.cc.o: In function `bool arma::auxlib::solve_square_fast<arma::Mat<std::complex<double> > >(arma::Mat<arma::Mat<std::complex<double> >::elem_type>&, arma::Mat<arma::Mat<std::complex<double> >::elem_type>&, arma::Base<arma::Mat<std::complex<double> >::elem_type, arma::Mat<std::complex<double> > > const&)':
first_impl.cc:(.text._ZN4arma6auxlib17solve_square_fastINS_3MatISt7complexIdEEEEEbRNS2_INT_9elem_typeEEES9_RKNS_4BaseIS7_S6_EE[_ZN4arma6auxlib17solve_square_fastINS_3MatISt7complexIdEEEEEbRNS2_INT_9elem_typeEEES9_RKNS_4BaseIS7_S6_EE]+0x2a3): undefined reference to `zgesv_'
CMakeFiles/test-cos.dir/first_impl.cc.o: In function `bool arma::auxlib::solve_band_refine<arma::Mat<std::complex<double> > >(arma::Mat<std::complex<arma::Mat<std::complex<double> >::pod_type> >&, arma::Mat<std::complex<double> >::pod_type&, arma::Mat<std::complex<arma::Mat<std::complex<double> >::pod_type> >&, unsigned int, unsigned int, arma::Base<std::complex<arma::Mat<std::complex<double> >::pod_type>, arma::Mat<std::complex<double> > > const&, bool)':
first_impl.cc:(.text._ZN4arma6auxlib17solve_band_refineINS_3MatISt7complexIdEEEEEbRNS2_IS3_INT_8pod_typeEEEERS7_SA_jjRKNS_4BaseIS8_S6_EEb[_ZN4arma6auxlib17solve_band_refineINS_3MatISt7complexIdEEEEEbRNS2_IS3_INT_8pod_typeEEEERS7_SA_jjRKNS_4BaseIS8_S6_EEb]+0x478): undefined reference to `zgbsvx_'
CMakeFiles/test-cos.dir/first_impl.cc.o: In function `bool arma::auxlib::solve_approx_fast<arma::Mat<std::complex<double> > >(arma::Mat<arma::Mat<std::complex<double> >::elem_type>&, arma::Mat<arma::Mat<std::complex<double> >::elem_type>&, arma::Base<arma::Mat<std::complex<double> >::elem_type, arma::Mat<std::complex<double> > > const&)':
first_impl.cc:(.text._ZN4arma6auxlib17solve_approx_fastINS_3MatISt7complexIdEEEEEbRNS2_INT_9elem_typeEEES9_RKNS_4BaseIS7_S6_EE[_ZN4arma6auxlib17solve_approx_fastINS_3MatISt7complexIdEEEEEbRNS2_INT_9elem_typeEEES9_RKNS_4BaseIS7_S6_EE]+0x388): undefined reference to `zgels_'
CMakeFiles/test-cos.dir/first_impl.cc.o: In function `bool arma::auxlib::solve_approx_svd<arma::Mat<std::complex<double> > >(arma::Mat<std::complex<arma::Mat<std::complex<double> >::pod_type> >&, arma::Mat<std::complex<arma::Mat<std::complex<double> >::pod_type> >&, arma::Base<std::complex<arma::Mat<std::complex<double> >::pod_type>, arma::Mat<std::complex<double> > > const&)':
first_impl.cc:(.text._ZN4arma6auxlib16solve_approx_svdINS_3MatISt7complexIdEEEEEbRNS2_IS3_INT_8pod_typeEEEESA_RKNS_4BaseIS8_S6_EE[_ZN4arma6auxlib16solve_approx_svdINS_3MatISt7complexIdEEEEEbRNS2_IS3_INT_8pod_typeEEEESA_RKNS_4BaseIS8_S6_EE]+0x317): undefined reference to `ilaenv_'
first_impl.cc:(.text._ZN4arma6auxlib16solve_approx_svdINS_3MatISt7complexIdEEEEEbRNS2_IS3_INT_8pod_typeEEEESA_RKNS_4BaseIS8_S6_EE[_ZN4arma6auxlib16solve_approx_svdINS_3MatISt7complexIdEEEEEbRNS2_IS3_INT_8pod_typeEEEESA_RKNS_4BaseIS8_S6_EE]+0x49c): undefined reference to `zgelsd_'
first_impl.cc:(.text._ZN4arma6auxlib16solve_approx_svdINS_3MatISt7complexIdEEEEEbRNS2_IS3_INT_8pod_typeEEEESA_RKNS_4BaseIS8_S6_EE[_ZN4arma6auxlib16solve_approx_svdINS_3MatISt7complexIdEEEEEbRNS2_IS3_INT_8pod_typeEEEESA_RKNS_4BaseIS8_S6_EE]+0x59a): undefined reference to `zgelsd_'
collect2: error: ld returned 1 exit status
lib/CMakeFiles/test-cos.dir/build.make:159: recipe for target 'lib/test-cos' failed
make[2]: *** [lib/test-cos] Error 1
CMakeFiles/Makefile2:174: recipe for target 'lib/CMakeFiles/test-cos.dir/all' failed
make[1]: *** [lib/CMakeFiles/test-cos.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

this is the CMakeLists.txt of the block i have edited it ,

[CMakeLists.txt](https://github.com/mlpack/mlpack/files/1777190/CMakeLists.txt)

i am trying from 2 days to resolve this issue,but still no success , kindly help me to resolve this linking issue. 
Thanks .

**Comment by rcurtin** [comment]
This is not an mlpack issue.  Why did you not open this issue in the gnuradio repository?
