### ISSUE TITLE
error while compiling linear_regression.cpp

### ISSUE THREAD

**Issue by donjin-master** [mlpack/mlpack#1295]
/usr/include/mlpack/core/util/mlpack_main.hpp:146:2: error: #error "Unknown binding type!  Be sure BINDING_TYPE is defined if you are " "including <mlpack/core/util/mlpack_main.hpp>.";
 #error "Unknown binding type!  Be sure BINDING_TYPE is defined if you are " \
  ^~~~~
/usr/include/mlpack/core/util/mlpack_main.hpp:151:28: fatal error: param_checks.hpp: No such file or directory
 #include "param_checks.hpp"
                            ^
compilation terminated.

Please help me on this...

**Comment by rcurtin** [comment]
It's difficult to compile the programs by hand. Use 'make mlpack_linear_regression'.

**Comment by rcurtin** [comment]
I'm going to close this for inactivity.  Please reopen it if needed.
