### ISSUE TITLE
broken tests in SVM

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#130]
**Reported by nslagle on 27 Jan 41716769 11:46 UTC**
The autotests in SVM fail.

**Comment by gmcather** [comment]
why does SVM not exist? In my understanding, SVM is an important classifier in Machine Learning

**Comment by rcurtin** [comment]
Yes, SVMs are important, but we have never had anyone contribute a fast implementation.  Getting SVMs to scale well is a difficult problem.  If you would like to try and implement them you are more than welcome to, we just need to make sure they are faster than libsvm and other implementations. :)

**Comment by gmcather** [comment]
Sounds cool. And I also heard some great ideas from wiki. Actually, it's my first time to get access to this project. However, I also want to make some contributions. Maybe I will get started by fixing some bugs. :)
