### ISSUE TITLE
Implementation of Radial Basis Function Networks(RBFNs)

### ISSUE THREAD

**Issue by sourabhvarshney111** [mlpack/mlpack#1311]
Implementation of RBFNs is not present in the codebase of mlpack.

**Comment by sourabhvarshney111** [comment]
I would like to work on this issue @zoq @lozhnikov

**Comment by zoq** [comment]
Do you mean in the context of GSoC?

**Comment by sourabhvarshney111** [comment]
Ya, I want to work in GSoC on this project but I will start the work from now.

**Comment by zoq** [comment]
I think we should leave this one for the actual GSoC project, we haven't settled on anything yet, so to avoid the risk of code that's not going to be merged let's close this for now.

**Comment by sourabhvarshney111** [comment]
Ok, I would provide a proposal for the same and would love to work on it during the actual GSoc Project.
