### ISSUE TITLE
missing closing bracket ')'

### ISSUE THREAD

**Issue by Namrata96** [mlpack/mlpack#1318]
Missing closing bracket in description of to_matrix_with_info function: https://github.com/mlpack/mlpack/blob/0e14562937fbbe3fba007d93e251d07496e7dced/src/mlpack/bindings/python/mlpack/matrix_utils.py#L61

**Comment by Namrata96** [comment]
Closed #1318

**Comment by sourabhvarshney111** [comment]
@Namrata96 @zoq @rcurtin Is this issue solved?

**Comment by sourabhvarshney111** [comment]
@zoq @Namrata96 I think the issue is solved. Can we close this issue?

**Comment by zoq** [comment]
Nice catch, let's close this one, thanks @Namrata96.
