### ISSUE TITLE
Implementation of more OpenAI gym Environments

### ISSUE THREAD

**Issue by yashsharan** [mlpack/mlpack#1322]
As of now only 2 environments are present for openAI gym namely cart-pole and mountain car. I was thinking of adding more environments. For starters I can include mountain car Continuous environment.
Can I work on this issue?

**Comment by zoq** [comment]
Hello, @yashsharan feel free to implement another environment. Ideally we add something that isn't covered yet, e.g. a continuous environment as you proposed.

**Comment by yashsharan** [comment]
Ok then. I will try to add mountain cart continuous environment

**Comment by luffy1996** [comment]
I am already working on this task :)

**Comment by yashsharan** [comment]
Are you working on a different environment? If no please chose an environment different than continuous mountain car as I already mentioned I'm working on that

**Comment by luffy1996** [comment]
Oh yeah I would do so. :)
