### ISSUE TITLE
Implement Bidirectional Recurrent Neural Network

### ISSUE THREAD

**Issue by Imraj** [mlpack/mlpack#1326]
I'll like to work on deep learning modules for mlpack during GSOC and start with the implementation of [bidirectional recurrent neural network](https://ai.intel.com/wp-content/uploads/sites/53/2017/06/BRNN.pdf).

@zoq Can I get started ?

**Comment by zoq** [comment]
I think we should leave this one for the actual GSoC project, we haven't settled on anything yet, so if you agree let's close the issue.
