### ISSUE TITLE
Implement Reward Clipping for Reinforcement Learning games

### ISSUE THREAD

**Issue by chennakeshava1998** [mlpack/mlpack#1332]
If different games use different scales of rewards, then it becomes hard to train the same RL algorithm for different games. This issue will be solved if clipped rewards are used

**Comment by sshkhr** [comment]
@chennakeshava1998  I think this can be marked as resolved now. Thanks for pointing out this issue

**Comment by ShikharJ** [comment]
Thanks for the work @sshkr.
