### ISSUE TITLE
The benchmarks page is incomprehensible

### ISSUE THREAD

**Issue by alexanderkjeldaas** [mlpack/mlpack#1350]
http://www.mlpack.org/benchmark.html is incomprehensible.  Most of the pull-down selectors are empty, and when a bar chart is presented, there might only be a single entry.

After some time it became clear that there are *lots* of benchmark entries with only a single library?!

Example of confusing layout and data:
<img width="1010" alt="skarmavbild 2018-04-02 kl 22 08 22" src="https://user-images.githubusercontent.com/339369/38213683-751d9fd6-36c2-11e8-8dc3-6d6603f67455.PNG">

**Comment by rcurtin** [comment]
Hi there @alexanderkjeldaas,

Sorry that you found the output confusing.  Mostly we use this internally to look at specific benchmarking tasks---and yes for these there may be only one library we are benchmarking.   The readability of the output is really dependent on running the benchmarking system with the right configuration, and I agree that it could be better.  I've opened mlpack/benchmarks#116 and as I am able to I will go through and try and rework the configuration to produce better output.  We can continue any discussion there.
