### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by sadlion** [mlpack/mlpack#1351]
Hello.
I'm glad to know this Library and test it.
But, while I compile this source, there are some errors.
I installed boost lib by installing libboost-all-dev.
I don't know why this error was occurred.
I found some doubt message and is it related to this error?
-- Could NOT find LIBBFD (missing:  LIBBFD_BFD_LIBRARY LIBBFD_INCLUDE_DIRS) 
CMake Warning at CMakeLists.txt:178 (message):
  No libBFD and/or libDL has been found!

If there is some fixed point, please let me know it.
I'd like to test it as soon as possible.
Thank you.

========================================================================
[ 15%] Linking CXX executable ../../../../bin/mlpack_sparse_coding
CMakeFiles/mlpack_sparse_coding.dir/sparse_coding_main.cpp.o: In function `mlpack::bindings::cli::ParseCommandLine(int, char**)':
/home/engfw/install/Python/mlpack-3.0.0/src/mlpack/bindings/cli/parse_command_line.hpp:77: undefined reference to `boost::program_options::options_description::find(std::string const&, bool, bool, bool) const'
CMakeFiles/mlpack_sparse_coding.dir/sparse_coding_main.cpp.o: In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::string const&, std::string const&, int)':
/usr/include/boost/program_options/errors.hpp:373: undefined reference to `boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)'
.....
CMakeFiles/mlpack_adaboost.dir/adaboost_main.cpp.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
collect2: error: ld returned 1 exit status
src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/build.make:102: recipe for target 'bin/mlpack_adaboost' failed
make[2]: *** [bin/mlpack_adaboost] Error 1
CMakeFiles/Makefile2:1867: recipe for target 'src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/all' failed
make[1]: *** [src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rcurtin** [comment]
Hi @sadlion, thanks for reporting the issue.  This one seems unusual; it looks like CMake is not linking against boost::program_options (if I am reading the output right).  Can you post the output if you run `VERBOSE=1 make mlpack_sparse_coding`?  That will show the actual linker command.

**Comment by zoq** [comment]
Maybe setting ``-DBOOST_INCLUDEDIR="path/to/boost/include `` and  ``-DBOOST_LIBRARYDIR=path/to/boost/libs/`` does solve the issue, but I agree ``VERBOSE=1 make mlpack_sparse_coding`` should be helpful here.

**Comment by anupgangwar** [comment]
Also, if you are compiling with gcc version > 5.x on older system where default version of gcc < 5.x, you may be facing the issue as listed here: https://stackoverflow.com/questions/12179154/undefined-reference-to-boostprogram-optionsoptions-descriptionm-default-l/12179310

<snip>
There were changes to the <string> class in the C++11 standard which may conflict with versions of the Boost library that were compiled with a non-C++11 compiler (such as G++-4.8). Try recompiling boost or using a version of C++ compiler that was used to compile your Boost libraries.
</snip>

Anup

**Comment by rcurtin** [comment]
I'm going to go ahead and close this issue for inactivity.  Please feel free to reopen it if needed.

**Comment by saraansh1999** [comment]
Hi!
I'm stuck at the same problem and am not able to figure out a solution. 
I installed boost and the other dependencies using apt-get (except for armadillo) as mentioned in the documentation.
