### ISSUE TITLE
manpage .TH line section missing and trailer line duplication

### ISSUE THREAD

**Issue by barak** [mlpack/mlpack#1352]
The manpages generated for the executables are missing the correct section (namely 1) on their `.TH` lines, presumably due to a missing `txt2man -s 1` option in the manpage generation script, on the penultimate line of `CMake/exec2man.sh` where `txt2man` is invoked. This is in turn causing the debian packaging tool `dh_installman` to be upset, and other manpage-related tools may experience similar sorts of indigestion.

Related: the `.TH` line date is that of the build rather than some release timestamp, which will require remediation for "reproducible builds" which many distributions are attempting as a security measure. A blank string `""` for the date is probably easiest and best in this case. And the origin and section description that follow the date should either be missing or sensible, like `"MLpack 3.0.0 Utilities"` and `"User Commands"`, not empty strings.
```
$ cd .../mlpack-3.0.0/obj-x86_64-linux-gnu/share/man/
$ zegrep '^[.]TH' mlpack_*
mlpack_adaboost.1.gz:.TH mlpack_adaboost  "04 April 2018" "" ""
mlpack_approx_kfn.1.gz:.TH mlpack_approx_kfn  "04 April 2018" "" ""
mlpack_cf.1.gz:.TH mlpack_cf  "04 April 2018" "" ""
mlpack_dbscan.1.gz:.TH mlpack_dbscan  "04 April 2018" "" ""
...
```
So I'd suggest something like this:
```
.TH mlpack_adaboost 1 "" "MLpack 3.0.0 Utilities" "User Commands"
```
There is also something funny going on with duplicate lines in the tails of the man pages.
```
$ zcat mlpack_adaboost.1.gz | tail -14
value ''.
\fB--output_model_file\fP (\fB-M\fP) [unknown] 
Output trained AdaBoost model. Default value
\(cq'.
.SH ADDITIONAL INFORMATION
.SH ADDITIONAL INFORMATION


For further information, including relevant papers, citations, and theory,
For further information, including relevant papers, citations, and theory,
consult the documentation found at http://www.mlpack.org or included with your
consult the documentation found at http://www.mlpack.org or included with your
DISTRIBUTION OF MLPACK.
DISTRIBUTION OF MLPACK.
```

**Comment by rcurtin** [comment]
Hi Barak,

Thanks for the clear description of the problem.  It looks like there are a couple issues here, and thanks for the patch in #1353.  Before I commit any kind of fix, I want to make sure that it works for your situation.  So if you apply the following patch, does it work for you?

https://gist.github.com/rcurtin/c1cb5ef47abed9e9a8a21f5d9701eb0f

Basically I had to rewrite the awk script somewhat because the output of the mlpack `--help` commands has changed a bit.

If that works, we can go with it.  I guess for the packaging 3.0.0 release, you could just backport the patches for now and when 3.0.1 is released it will incorporate the fixes.

**Comment by barak** [comment]
Don't worry, I already uploaded the 3.0.0 package, albeit with the funny manpage trailers. I'll upload a fix when this all settles down.

Anyway, yes your gist patch works (well, not the patch itself which was mangled by gisting and had to be manually applied, but you get the idea.)

However you are sort of abusing txt2man: you're using "1" as the date (`-d 1`) and no section option (`-s 1`) which is being left blank, then the other fields (origin and section name) are defaulting to empty strings `""`. It displays okay because what txt2man thinks is the date is actually where the section should be since the section is just whitespace, but I suspect some man-page-processing tools may be a little bit indignant about the empty strings.

The `-P mlpack` option does absolutely nothing: can remove with no change in the output regardless of whether `-s 1` is added or not.

**Comment by barak** [comment]
After a bit more digging, it turns out that the `txt2man -d DATE` option can be safely (reproducible) omitted. The date will default to the current date, *unless* inside a debian build (or other build process that supports these mechanisms) in which case it will end up using the date from the first stanza in `debian/changelog` (or the appropriate analogue).

**Comment by rcurtin** [comment]
Ack, sorry about the mangling.  In any case, thanks for the information.  It looks like the last time I seriously considered this script was over six years ago, so it's good to update it.  Who knows what I was thinking then?  (Apparently not something correct...)

I read through what you wrote and reviewed the txt2man man page (which, hey, is properly formatted!) and I'll actually change the txt2man call a little bit:

```
txt2man -t "$name" -r "mlpack-$version" -s 1
```

where I define `$version` by extracting from the actual program:

```
# Get the version.
version=`./"$name" --version | sed 's/^.* \([^ ]*\)\.$/\1/'`;
```

I'll add this as part of the merge process for #1353, then you can either get the patch from that merge commit or I can get it for you---whichever works better for you.  Thanks again for pointing this out.

**Comment by barak** [comment]
Grand! Don't worry my git-fu is up to cherry picking the odd commit.
