### ISSUE TITLE
mlpack On Windows

### ISSUE THREAD

**Issue by degski** [mlpack/mlpack#1357]
You could add to the write-up that apart from ICC (comm.) and MSYS2 (brrrrr!), one could use Clang/LLVM, which b.t.w. also supports all GCC-extensions (including handy ones like f.e. calculated goto's). The latest build (clang 7 branch) is here: https://llvm.org/builds/ . The llvm-site mentions that 32-bit integrates better than x64. I have seen no proof of that, while on the other hand Clang does not integrate at all with VS2017, without for the moment some manual config (after which it runs without (major) issues).

**Comment by rcurtin** [comment]
Hi there @degski, thanks for pointing that out.  I've added some information about this to the https://github.com/mlpack/mlpack/wiki/WindowsBuild page.  Let me know if you think I should modify it further.

Thanks! :)
