### ISSUE TITLE
Hierarchical Softmax

### ISSUE THREAD

**Issue by scrcro** [mlpack/mlpack#1359]
This is not really an issue, but more of a query. 
Is there a hierarchical softmax layer available in mlpack?

**Comment by zoq** [comment]
Hierarchical softmax isn't implemented, might be interesting to implement something in that direction based on the existing tree infrastructure.

**Comment by rcurtin** [comment]
The tree infrastructure is built for multidimensional trees, so I don't know if that would fully apply here.  Maybe something in the STL might be usable---for instance, `std::map` is built on RB-trees.  But I am not fully familiar with the hierarchical softmax.

**Comment by rcurtin** [comment]
This has been inactive for a while so I'll close it now.  If there is more work to be done here or anything we can reopen it. :+1:
