### ISSUE TITLE
I would like to use mlpack to implement gan, need help

### ISSUE THREAD

**Issue by wxjeacen** [mlpack/mlpack#1371]
Hi all,

I would like to use mlpack to implement a GAN network. 

I have referred a sample but there were missing header files. such as gan.hpp.

Would you please help to provide me a sample that can run in current updated version?

**Comment by ShikharJ** [comment]
Hi @wxjeacen,
I had been working on a GAN implementatiom in #1204, but it is not completely debugged, and I'll be busy with exams for the rest of the month. You might take a look there. Though I should mention that probably more work would be done in the coming summers.

**Comment by wxjeacen** [comment]
@ShikharJ  Thanks for your reply.

I have checked out your private repo in "gan" branch from your github. 
When I compile your sample, there is an error  no "CrossEntropyErrorLogits" found.

How can I work the problem out?

**Comment by zoq** [comment]
Agreed, let's continue the work over in #1204, @wxjeacen if you like to help, any review is helpful.

**Comment by ShikharJ** [comment]
@wxjeacen We now have the support for single-input mini-batch GANs, and we'll be working on the support for different batch-sizes in the coming weeks. You might want to check that out.
