### ISSUE TITLE
A way to generate output model using c++ api

### ISSUE THREAD

**Issue by rizalishan** [mlpack/mlpack#1376]
I apologize if this is a stupid question but I can't seem to find a way to store my trained Adaboost model and then reuse it using c++ API.

Any help or example would be greatly appreciated

**Comment by zoq** [comment]
mlpack uses boost::serialization(www.boost.org/libs/serialization/doc/) to load and save a model. To save a trained model (model is the initiated object e.g. AdaBoost) to disk you can use:

```c++
data::Save("model.xml", "model", model, false);
```

which will save the model as an xml file, you can also use txt, json, etc.. Loading is similar:

```c++
data::Load("model.xml", "model", model);
```

I hope this is helpfu, let me know if I should clarify anything.

**Comment by rizalishan** [comment]
Seems like, I was missing just one parameter ... Thank you so much you have saved me.
