### ISSUE TITLE
Implementation like Scikit learn

### ISSUE THREAD

**Issue by prabhat-krai** [mlpack/mlpack#1383]
to develop an implementation in C++ that will gravitate people towards C++ for fast prototyping.

**Comment by samitpmc** [comment]
Hi

Is there a way to convert scikit learn model to MLPack compatible model. Basically I want to do the following

1 Create model using scikit learn
2 Convert model to MLPack format
3 Load the model using MLpack and start classifying.

**Comment by rcurtin** [comment]
@samitpmc there is not specific code that does this automatically.  However, you could extract the weights from a scikit model and load them into mlpack with some handwritten code.

**Comment by samitpmc** [comment]
Hi Ryan
Thanks a lot. I didn't realized that question, response has been posted in another thread.
It would be great if you could share handwritten code which will use weights from scikit model and load them into mlpack. I think this use case would be extremely useful for someone who has already built model using scikit and use the weights of the model to classify new items using MLPack.
Regards

**Comment by rcurtin** [comment]
I have not written any code to do this.  I only meant that it would be possible to write it.
