### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by teibit** [mlpack/mlpack#1398]
Hi. Browsing your library I notice that there is a file called mlpack_export.hpp which is not included in any of the releases. Where can I find it? Without it the code cannot be run. Thanks.

**Comment by rcurtin** [comment]
Hi there @teibit,

The file `mlpack_export.hpp` is generated by CMake at build time.  So you can configure and build the library, then in the `include/` folder under your build directory you will be able to find it there.

Hope this helps!

**Comment by teibit** [comment]
The thins is that I am using XCode and so it doesn't even let me compile the code since this file hasn't been generated. Do you have any suggestions on possible fixes? I appreciate this very much.

**Comment by teibit** [comment]
Hmm, I just figured it out I think. I ran cmake on the folder previously and now the file was generated. Thanks for the help!

**Comment by rcurtin** [comment]
Right, CMake generates the file.  Sorry that I did not respond to this earlier, I must have seen that you fixed it in an email but forgot to follow up.  I'll go ahead and close the issue then.
