### ISSUE TITLE
Implement .shed_rows() and .shed_cols() for arma::Cube

### ISSUE THREAD

**Issue by ShikharJ** [mlpack/mlpack#1402]
Currently these routines are only available for matrices, however an efficient implementation of these routines for cubes can speedup our computation of `Gradients` for `AtrousConvolution` class. 
Relevant: #1390

**Comment by conradsnicta** [comment]
@ShikharJ - you're welcome to submit a pull request on the Armadillo repo: https://github.com/conradsnicta/armadillo-code

**Comment by ShikharJ** [comment]
@conradsnicta Sure, I'll submit one over the weekend.

**Comment by ShikharJ** [comment]
Fixed in https://github.com/conradsnicta/armadillo-code/pull/77. @zoq I'd like to keep this issue open till the changes are released to a stable. Then we can probably update our `AtrousConvolution` implementation.

**Comment by zoq** [comment]
Thanks for looking into this one, let me know if this can be closed.

**Comment by ShikharJ** [comment]
@zoq This can be closed now, the new `Gradient` method would not need the support of the above routines for cubes.
