### ISSUE TITLE
[JOSS] DOIs needed in paper

### ISSUE THREAD

**Issue by mlgill** [mlpack/mlpack#1403]
@rcurtin I am reviewing the mlpack submission for the JOSS submission. It looks like DOIs are missing from the paper.

**Comment by rcurtin** [comment]
I added the DOIs that I could find for the references in #1408, but not every reference had a DOI.  I am not the most familiar person in the world with DOIs, so please double-check my work (83b697d) and let me know if I didn't do what you were hoping for.  Thanks!

**Comment by rcurtin** [comment]
I think this is fixed now so I will go ahead and close the issue.
