### ISSUE TITLE
Add shuffle parameter to KFoldCV constructor

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1409]
(from an IRC discussion) It would be useful to add a `shuffle` flag to the `KFoldCV` constructor, which would shuffle the data before the k-fold cross-validation is done.  This can be important for situations where the data is ordered by class---a k-fold split as-is would fail horribly.

It'd probably be easiest to implement this by just calling `ShuffleData()` inside the constructor for `KFoldCV`.  We should also implement a test, which can basically just be running `KFoldCV` with and without the shuffle option and ensuring the results are close, but not exactly the same.

**Comment by conradsnicta** [comment]
@octogman - if there's an issue with arma::shuffle(), please submit a bug report at the Armadillo repo: https://github.com/conradsnicta/armadillo-code
We take reproduceable bug reports seriously and aim to fix them quickly.

**Comment by rcurtin** [comment]
Support is now available with #1412 being merged.  Let me know if there are any problems!
