### ISSUE TITLE
ShuffleData directly reads sparse matrix arrays

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/mlpack#1411]
Looking at this
https://github.com/mlpack/mlpack/blob/8985af2fd6704dbcd3e8362bea996d5889c2ccd7/src/mlpack/tests/math_test.cpp#L634-L635
leads to:
https://github.com/mlpack/mlpack/blob/8985af2fd6704dbcd3e8362bea996d5889c2ccd7/src/mlpack/core/math/shuffle_data.hpp#L51
which directly reads sparse matrix arrays here:
https://github.com/mlpack/mlpack/blob/8985af2fd6704dbcd3e8362bea996d5889c2ccd7/src/mlpack/core/math/shuffle_data.hpp#L64-L65
This is problematic, as the caching in mechanism in Armadillo 8 means it's not safe to assume that the underlying storage arrays in SpMat are valid:

https://github.com/conradsnicta/armadillo-code/blob/d5a4278bfb919a7b5e3529ca522041010b643b7c/include/armadillo_bits/SpMat_bones.hpp#L48-L49

Possible solutions to fix mlpack's ShuffleData():
1. Instead of directly reading the underlying storage arrays in SpMat, use the [sparse matrix iterators](http://arma.sourceforge.net/docs.html#iterators_spmat).
2. Call SpMat::sync() before reading the underlying storage arrays.

Solution 1 is probably the safer option, as it avoid surprises in the future (eg. potential extensions/modifications to the sparse storage format in Armadillo).

**Comment by rcurtin** [comment]
Good call, thanks. I am working on #1409 so I'll add this to the eventual PR since it's related.  The fix is easy, I'll just fill a `values` array with the iterator that method is already using.

**Comment by conradsnicta** [comment]
I did a quick search through the mlpack code base, and there are several other instances of SpMat::values[] (and the other SpMat arrays) being read directly.  It's not a pressing problem, though to be on the safe side there should be a call to SpMat::sync() before accessing these arrays.

**Comment by rcurtin** [comment]
Fixed throughout the codebase in #1412.
