### ISSUE TITLE
[JOSS] Can't obtain the distribution from the link provided in the docs

### ISSUE THREAD

**Issue by rasbt** [mlpack/mlpack#1413]
For the review, I am trying out the installation instructions on http://www.mlpack.org/docs/mlpack-3.0.1/doxygen/build.html and it seems to hang 

```bash
wget http://www.mlpack.org/files/mlpack-3.0.1.tar.gz
--2018-06-01 03:19:13--  http://www.mlpack.org/files/mlpack-3.0.1.tar.gz
Resolving www.mlpack.org (www.mlpack.org)... 216.24.161.178
Connecting to www.mlpack.org (www.mlpack.org)|216.24.161.178|:80... failed: Connection timed out.
Retrying.

--2018-06-01 03:21:22--  (try: 2)  http://www.mlpack.org/files/mlpack-3.0.1.tar.gz
Connecting to www.mlpack.org (www.mlpack.org)|216.24.161.178|:80... 
...
```

Is this a temporary issue, or is the link maybe incorrect? 

(I was able to get the files via `wget https://github.com/mlpack/mlpack/archive/mlpack-3.0.1.tar.gz` but I am wondering if the http://www.mlpack.org/files/mlpack-3.0.1.tar.gz should still be the recommended one in the docs?)

**Comment by rcurtin** [comment]
Sounds like a routing issue, hopefully temporary.  The system is still up (I was just checking my email on it, so clearly it can talk to Github at least...).  Are you able to load mlpack.org at all?

If the problem persists I can try and find the right person to fix the routing issue, but often it can be hard to find who that person will be...

**Comment by rasbt** [comment]
> Are you able to load mlpack.org at all?

Yes, that works fine.

> If the problem persists I can try and find the right person to fix the routing issue, but often it can be hard to find who that person will be...

I just tried it again, and somehow, the problem just resolved itself, maybe it was just a temporary server hickup :)
