### ISSUE TITLE
Problem with the sample code in ann::ffn. trying to fit the data ("thyroid_train.csv") mlpack-3.0.1.

### ISSUE THREAD

**Issue by IshanSeidenberg** [mlpack/mlpack#1415]
Compilation:
g++ -DDEBUG -g fnn.cpp -o fnn -O2  -larmadillo -lmlpack -std=c++11 -fopenmp -lboost_serialization

Output:
24, 3772
21, 3772
3, 3772
Training...

error: Mat::operator(): index out of bounds
terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::operator(): index out of bounds
Aborted (core dumped)

Code:
`
#include <fstream>
#include <cmath>
#include <mlpack/core.hpp>

#include <mlpack/methods/ann/layer/layer.hpp>
#include <mlpack/methods/ann/layer/layer_types.hpp>
#include <mlpack/methods/ann/loss_functions/mean_squared_error.hpp>
#include <mlpack/methods/ann/loss_functions/sigmoid_cross_entropy_error.hpp>
#include <mlpack/methods/ann/init_rules/random_init.hpp>
#include <mlpack/methods/ann/init_rules/const_init.hpp>
#include <mlpack/methods/ann/init_rules/nguyen_widrow_init.hpp>
#include <mlpack/methods/ann/ffn.hpp>
#include <mlpack/methods/ann/rnn.hpp>

using namespace mlpack;
using namespace std;
using namespace ann;
using namespace mlpack::ann;
using namespace optimization;

int main(int argc,char **argv)
{
 
    // Load the training set.
    arma::mat dataset;
    data::Load("thyroid_train.csv", dataset, true);
    // Split the labels from the training set.
    arma::mat trainData = dataset.submat(0, 0, dataset.n_rows - 4,
        dataset.n_cols - 1);
    // Split the data from the training set.
    arma::mat trainLabels = dataset.submat(dataset.n_rows - 3, 0,
        dataset.n_rows - 1, dataset.n_cols - 1);
    // Initialize the network.
    FFN<> model;
    model.Add<Linear<> >(trainData.n_rows, 8);
    model.Add<SigmoidLayer<> >();
    model.Add<Linear<> >(8, 3);
    model.Add<LogSoftMax<> >();
    // Train the model.
    StandardSGD opt(0.1, 1, trainData.n_cols /* 1 epoch */, -100);

    cout << dataset.n_rows << ", " << dataset.n_cols << std::endl;
    cout << trainData.n_rows << ", " << trainData.n_cols << std::endl;
    cout << trainLabels.n_rows << ", " << trainLabels.n_cols << std::endl;
    cout << "Training..." << std::endl;
    model.Train(trainData, trainLabels, opt);
    // Use the Predict method to get the assignments.
    arma::mat assignments;
    cout << "Predicting." << std::endl;
    model.Predict(trainData, assignments);
}`

**Comment by zoq** [comment]
The ``LogSoftMax`` layer expects the labels to be in range ``[1, #classes]``, the ``thyroid`` dataset from the tests directory has to be transformed first:

```c++
arma::mat trainLabelsTemp = dataset.submat(dataset.n_rows - 3, 0,
    dataset.n_rows - 1, dataset.n_cols - 1);
arma::mat trainLabels = arma::zeros<arma::mat>(1, trainLabelsTemp.n_cols);
for (size_t i = 0; i < trainLabelsTemp.n_cols; ++i)
{
  trainLabels(i) = arma::as_scalar(arma::find(
      arma::max(trainLabelsTemp.col(i)) == trainLabelsTemp.col(i), 1)) + 1;
}
```

should work just fine. Let me know if you encounter any further issues.

**Comment by sungliner** [comment]
arma::mat trainData = dataset.submat(0, 0, dataset.n_rows - 4,
    dataset.n_cols - 1);
arma::mat trainLabels = dataset.submat(dataset.n_rows - 3, 0,
    dataset.n_rows - 1, dataset.n_cols - 1);

class arma subview<double>is not compatible with class arma mat

**Comment by rcurtin** [comment]
I've closed this for inactivity.  Please feel free to reopen if needed! :)

**Comment by GLmontanari** [comment]
@zoq and @rcurtin  it's a real pity that @IshanSeidenberg  didn't reply because I had the very same problem and I tried @zoq suggestion and it worked for me.
You should consider updateing the tutorial with his few lines of code:

```
arma::mat trainLabels = arma::zeros<arma::mat>(1, trainLabelsTemp.n_cols);
for (size_t i = 0; i < trainLabelsTemp.n_cols; ++i)
{
  trainLabels(i) = arma::as_scalar(arma::find(
      arma::max(trainLabelsTemp.col(i)) == trainLabelsTemp.col(i), 1)) + 1;
}
```

The differences, if they are worth be known are I used MSVS 2017 compiler and mlpack 3.0.3

**Comment by brightprogrammer** [comment]
I was having the same problem while working on a stock price dataset... I divided each and every component by 1000 and now everything works fine!! So I think that all you have to do is just divide each and every point and its components by it's size!
