### ISSUE TITLE
[JOSS] Documentation typo in Adaboost code example

### ISSUE THREAD

**Issue by rasbt** [mlpack/mlpack#1418]
In the Python Bindings docs of Adaboost (http://www.mlpack.org/docs/mlpack-3.0.1/python/adaboost.html), the following code example is provided:

    >>> adaboost(training=data, weak_learner='perceptron')
    >>> model = output['output']

I believe this should be 

    >>> adaboost(training=data, weak_learner='perceptron')
    >>> model = output['output_model']

based on the description at the very bottom: (`output_model (mlpack.AdaBoostModelType): Output trained AdaBoost model.`)?

**Comment by rcurtin** [comment]
You're right about the lack of `output =`, this is a bug in the auto-generated documentation.  It always helps to have an extra set of eyes---thank you for pointing this out.  The `output` -> `output_model` is a specific error in the AdaBoost code.

**Comment by rasbt** [comment]
>  It always helps to have an extra set of eyes

I agree :). Coincidentally, not too long ago, I submitted a ML toolkit library to JOSS as well (mlxtend) and was bumping into similar issues with the autogenerated docs that the reviewer found

**Comment by rcurtin** [comment]
Fixed with #1421.

**Comment by rcurtin** [comment]
#1421 is merged, so I will close this now.
