### ISSUE TITLE
policy gradients

### ISSUE THREAD

**Issue by sshkhr** [mlpack/mlpack#1432]
There are a couple of open PRs #1328 #1271 and a closed PR #934 which were working on implementing policy gradient algorithms in the mlpack framework but none of them were merged due to some reasons. I would like to clean up and finish on those and add some tests. This is what I have thought of doing : 

- [ ] Implement Policy as a layer in ann/ rl module
- [ ] Add a test for policy layer in rl_components_test
- [ ] Add a policy gradient method (REINFORCE) with baseline and entropy loss in the rl module
- [ ] Add a test showing convergence on mountain car or cartpole environment

I will send a PR sometime next week. I will also add @mirraaj and @ShangtongZhang  as contributors since they have already done a lot of work. 

I would ask @zoq and @ShangtongZhang over irc and in discussing the PRs for help as I am not that comfortable with RL. Please feel free to add anything here regarding how to go about this task. Thanks

**Comment by mirraaj** [comment]
Hello @sshkhr, I sincerely thank you for looking into the incomplete PR. As a matter of fact, the policy gradient method (Reinforce) is almost complete. If you are comfortable, I will like to complete that work within few days. You may like to work on actor-critic methods which is a more challenging task. I have shifted my focus to implementing ACER/PPO on MLPACK. There is an closed PR #934 where you may find the code for A3C. You may use that as a baseline to implement other algorithms.

Thanks

**Comment by mirraaj** [comment]
@zoq, I am following this issue presently. This issue deals with implementation of Reinforce algorithm in Mlpack. As per experimentation, Reinforce generally suffers from the high variance. I personally feel that A2C would be better to implement. Please let me know your inputs.

Also, do you know of any issue/PRs which concentrates of A2C presently? It seems that A2C is still not supported by Mlpack.

**Comment by joeljosephjin** [comment]
> Hello @sshkhr, I sincerely thank you for looking into the incomplete PR. As a matter of fact, the policy gradient method (Reinforce) is almost complete. If you are comfortable, I will like to complete that work within few days. You may like to work on actor-critic methods which is a more challenging task. I have shifted my focus to implementing ACER/PPO on MLPACK. There is an closed PR #934 where you may find the code for A3C. You may use that as a baseline to implement other algorithms.
> 
> Thanks

@mirraaj  Can I know what is the status of the policy_gradient function? I want to implement DDPG and I need the policy gradient to do that. Can I go ahead and implement one?
