### ISSUE TITLE
Occasional failures for ConvolutionalNetworkTest/VanillaNetworkTest

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1438]
I noticed some failures on masterblaster:

http://masterblaster.mlpack.org/job/docker%20mlpack%20nightly%20build/armadillo_version=armadillo-6.500.5,boost_version=boost_1_66_0,buildmode=debug,compiler_version=gcc-6.1.0,label=linux-amd64/lastCompletedBuild/testReport/

So I checked out the code and found that maybe 1 in every 50 runs fails randomly.  I tried three different revisions---current master, 49e3cda, and 674ee50, and saw the same behavior for each of them.  So I don't think that this was caused by any of @ShikharJ's recent changes.

@zoq: do you think that this is a random failure or that something is really wrong here?  If it appears to be fully random, we can just run the test 3 times and make sure it succeeds at least once to get the failure probability down.

**Comment by zoq** [comment]
I'll see if I can reproduce the issue later today.

**Comment by zoq** [comment]
Okay, looks like a random failure, the output looks good and is the same, compared with the latest and previous version. Will open a new PR with a 'fix'.

**Comment by rcurtin** [comment]
#1442 is merged, so this is fixed.  I'll go ahead and close it.  Happy to see a green build again :)
