### ISSUE TITLE
'svd': illegal use of namespace identifier in expression 

### ISSUE THREAD

**Issue by kilasuelika** [mlpack/mlpack#1443]
When build mlpack using Windows, an error occured:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	C2882	'svd': illegal use of namespace identifier in expression (compiling source file G:\Coding\C++\mlpack-master\src\mlpack\Release\cotire\mlpack_CXX_unity_54_62.cxx)	mlpack_unity	g:\coding\c++\mlpack-master\src\mlpack\methods\radical\radical.cpp	190	

The file contains error is mlpack\methods\radical\radical.cpp.

**Comment by kilasuelika** [comment]
I modify the 190 line of source file to: 
`arma::svd(matU, s, matV, cov(matX));`

And build successfully.

**Comment by zoq** [comment]
Good point, do you like to open a PR with the modification, don't feel obligated, just wanted to ask first.

**Comment by rcurtin** [comment]
Thanks for pointing this out, it's such a simple change that I went ahead and made a PR (#1451).

**Comment by rcurtin** [comment]
Ok, #1451 is merged so this is closed now.  Thanks again for pointing out the issue, and don't hesitate to post any more problems if you have them. :)
