### ISSUE TITLE
LMNN: low-rank matrix optimization

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1447]
This one is already implemented in #1407, so really this issue is just more about seeing that it works okay.  We want to ensure that when we run LMNN with a low-rank distance matrix, that the following things are true:

 1. We can get roughly equivalent kNN accuracy improvements.  (That will be incredibly different with choice of rank and dataset.)
 2. We get some amount of speedup by the use of the low-rank dataset, and the speedup increases as the rank gets lower (if the number of iterations is held constant).

I expect that low-rank does make it faster, since kNN search will be faster as the dimension decreases.  So really this issue, at this point, is more of a sanity check to make sure that this idea works as we expect.

**Comment by manish7294** [comment]
I tried running a test for this one. But the results vary just too much, sometimes learning a low-rank perform better, other times not so (like for vc2 it's always way better and runtime is almost half, on other the hand with iris results are more and less same). Overall I would say reducing data dimensionality have some real visible effects on outcome. The result of which, currently I have commented out the test https://github.com/mlpack/mlpack/pull/1407/commits/bc3b5bba37bcd87fb56daa0deeb9688cf7584b6c

**Comment by manish7294** [comment]
Parameters (k = 5, optimizer: L-BFGS)
Iris:
Accuracy:
Initial Accuracy:  96.6667%
Rank = 1:  97.3333%
Rank = 2:  96.6667%
Rank = 3:  97.3333%
Rank = 4 (max dimensionality reached):  96.6667%

vc2:
Accuracy:
Initial Accuracy: 77.7778%
Rank = 1:  71.4976%
Rank = 2:  78.2609%
Rank = 3:  82.1256%
Rank = 4:  77.7778%
Rank = 5:  77.7778%
Rank = 6 (max dimensionality reached):  78.744%

letters_recognition (Range: 100):
Accuracy: 
Initial Accuracy: 99.505%
Rank = 1:  31.92%
Rank = 2: 47.565%
Rank = 3:  95.645% 
Rank = 5:  99.86%
Rank = 10:  100%
Rank = 17 (max dimensionality reached):  100%

**Comment by manish7294** [comment]
Parameters (k = 5, optimizer: L-BFGS)

Every data consists of 10 runs all with different seeds, the timings are on my system with DEBUG=ON and KNNAccuracy() time included as well.

Iris:
----------------------------------Accuracy------------------------ |---------------------Runtime----------------------
--------------Mean------Variance------Min-------Max---------|-------Mean------Variance------Min-------Max
Rank=1:---97.33----------0-----------97.33----97.33---------|-------0.82--------0.0003--------0.79------0.85
Rank=2:---96.67----------0-----------96.67----96.67---------|-------0.86--------0.0006--------0.83------0.92
Rank=3:---97.33----------0-----------97.33----97.33---------|-------0.89--------0.0003--------0.87------0.92
Rank=4:---96.67----------0-----------96.67----96.67---------|-------0.83--------0.0003--------0.81------0.86

vc2:
----------------------------------Accuracy------------------------ |---------------------Runtime----------------------
--------------Mean------Variance------Min-------Max---------|-------Mean------Variance------Min-------Max
Rank=1:---71.50----------0-----------71.50----71.50---------|-------2.57--------0.0020--------2.51------2.67
Rank=2:---78.26----------0-----------78.26----78.26---------|-------2.19--------0.0034--------2.11------2.29
Rank=3:---82.13----------0-----------82.13----82.13---------|-------2.49--------0.0034--------2.40------2.60
Rank=4:---77.78----------0-----------77.78----77.78---------|-------2.81--------0.0019--------2.77------2.91
Rank=5:---77.78----------0-----------77.78----77.78---------|-------2.75--------0.0060--------2.61------2.90
Rank=6:---78.74----------0-----------78.74----78.74---------|-------3.32--------0.0027--------3.22------3.40

**Comment by rcurtin** [comment]
Hmm, there's no variance in the result accuracy.  Are you sure this is running correctly with different random seeds?

**Comment by manish7294** [comment]
These were the results I got on running on with different seeds but later on the same day I found a logical error while updating iterations, for which I had pushed a commit. So, maybe the results are not absolutely correct, I still have to check the accuracy after new changes.

**Comment by rcurtin** [comment]
Right, I saw that, but no matter what there should definitely be some amount of variance in the accuracy---I don't expect that LMNN would converge to the same result with SGD when it is starting from a different (random) initial point each time.

**Comment by manish7294** [comment]
Will have to cross check with SGD like optimizers.

**Comment by manish7294** [comment]
I see the problem, no matter what seed I am passing `arma::randu()` is initializing the matrix to same value every time. When I replaced the `math::RandomSeed` with `arma::arma_rng::set_seed`, the variance in accuracy on different seed was visible.

**Comment by manish7294** [comment]
These are the results over the current LMNN code after solving `RandomSeed()` issue. Parameters are same as that of previous simulation except each data consists of 5 (previously it was 10) runs with different seed.

```
Iris:
-------------------------Accuracy------------------------ |---------------------Runtime----------------------
------------Mean------Variance------Min-------Max---------|-------Mean------Variance------Min-------Max
Rank=1:---97.33-------0.0000-------97.33----97.33---------|-------0.91--------0.0070--------0.82------1.04
Rank=2:---97.06-------0.3591-------96.67----98.00---------|-------1.32--------0.3152--------0.87------2.09
Rank=3:---96.93-------0.1307-------96.67----97.33---------|-------0.93--------0.0068--------0.88------1.07
Rank=4:---97.33-------0.2211-------96.67----98.00---------|-------1.15--------0.1355--------0.82------1.69



vc2:
-------------------------Accuracy------------------------ |---------------------Runtime----------------------
------------Mean------Variance------Min-------Max---------|-------Mean------Variance------Min-------Max
Rank=1:---73.91-------16.570-------68.59----79.71---------|-------5.02--------4.5000--------2.60------7.43
Rank=2:---77.29-------0.5834-------76.32----78.26---------|-------2.66--------0.0055--------2.57------2.76
Rank=3:---81.25-------0.6310-------80.19----82.12---------|-------2.96--------0.0104--------2.81------3.10
Rank=4:---78.93-------4.2666-------77.29----81.64---------|-------3.02--------0.0642--------2.74------3.43
Rank=5:---78.16-------0.6341-------77.29----79.22---------|-------3.17--------0.0522--------2.77------3.33
Rank=6:---78.84-------0.5136-------77.77----79.71---------|-------3.12--------0.0191--------2.99------3.34

```

**Comment by rcurtin** [comment]
Right, looks good, could you also give results for covertype-5k and letters_recognition?  For the accuracy results it looks like as long as the rank is "high enough" (which for iris is 1 or larger and for vc2 is 3 or larger it seems), LMNN can still perform well, which is good.

The runtime results look roughly like I was hoping, but it seems like in some cases the number of iterations must be different---for instance, iris with rank 2 takes longer than rank 3, and vc2 with rank 1 takes twice as long as with rank 2.  Could you verify that when you hold the number of iterations constant, we see the expected pattern?  (where runtime increases as the rank increases)  You could do this by running with, e.g., max_iterations = 5 or something.  The accuracy results may not be great, but we'll get a good idea of how much speedup low-rank computation can give us, while not having the number of iterations be a point of confusion in our results.

Remember overall the questions we'd like to answer are:

 * Can low-rank optimization still provide good-enough performance?  (seems like yes, we should see on covertype-5k and letters_recognition too)
 * Does low-rank optimization provide acceleration?  (this can be done with the experiment holding the number of iterations constant)

I think we are close to being able to answer both questions positively. :)

**Comment by manish7294** [comment]
Shall I take till tomorrow for further simulations by tomorrow? It takes quite some time ;)

I made some quick simulations on iris with `max_teration : 5` and the results totally depends over seed, the lowest runtime is as low as 0.14 to as high as 0.87 (which can be seen from above results)

**Comment by rcurtin** [comment]
Sure, it's ok if it takes some time.  Are you sure the maximum number of iterations is being properly passed and reached?  I can't see any reason why the results for a given maximum number of iteration would depend on the random seed.

**Comment by manish7294** [comment]
As per the debug log number of iterations are 5 only. Though the number of `node combinations `and `base cases calculated `(which I think is a part of neighbor search) differs a lot.

**Comment by rcurtin** [comment]
Hmm, I guess the different dimensionality could cause significantly different nearest neighbor search runtimes.  I would not expect that so much but I think I will try to do a little investigation.  In the mean time, I do think the results are at least promising (even if the speedup is not so much).  For much higher-dimensional datasets, I expect that low-rank LMNN could provide even more speedup.
