### ISSUE TITLE
Does mlpack - hmm support mutilple sequences ?

### ISSUE THREAD

**Issue by kvcuong** [mlpack/mlpack#1450]
Hi,
I have some issues on word-spotting with mutiple sequences. Let's say one observation Oi = {o1, o2, o3.., ok...} and each ok = {ok1, ok2, ok3.., okn}. 

Does mlpack-hmm support such kind of data structure ? 

Thanks

**Comment by kvcuong** [comment]
Did you mean a std::vector<arma::mat> which is :

`std::vector<arma::mat> dataSeq = {O1, O2, ...Oi......Om}`  where 
`Oi = arma::mat{arma::col(o1), arma::col(o1), arma::col(o1), ...arma::col(ok)....arma::col(on)};`
and 
`arma::col(ok) = {ok1, ok2...., okp,.......}`

?

**Comment by rcurtin** [comment]
Right, in the code you wrote, `O1`, `O2`, `Oi`, and `Om` would be sequences, and then each column of `Oi` would be an observation in the sequence.  So if I have understood your notation right, I believe that we are on the same page.  Give it a shot, let us know if there are any problems. :)

**Comment by rcurtin** [comment]
I'm going to go ahead and close this for inactivity---please feel free to reopen if needed.
