### ISSUE TITLE
AppVeyor build for Windows tutorial

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1463]
It would be really nice to automatically test the Windows tutorial from #1436.  In order to do this, we could create a special .vcproj configuration and put it in an .appveyor directory, then modify appveyor.yml to drop that configuration in place and build it.  That's not the only way to do it, but it's one idea.

**Comment by shrit** [comment]
@rcurtin I think we can close this once #2664 is merged what do you think?

**Comment by rcurtin** [comment]
@shrit actually, the problem would still exist; we'd simply need to implement it on Azure instead of AppVeyor. :+1:
