### ISSUE TITLE
KNN result differ for different values of K 

### ISSUE THREAD

**Issue by manish7294** [mlpack/mlpack#1470]
Sorry, but the title may seem a bit confusing. 

So Here's the problem - 
If we call `KNN` for some `k`, and now if we again make a new call to `KNN` but this time with some value of `k` greater than previous one (Let's just say `k + 1`). Then the results of the first call will differ from the first `k` rows of the results from the second call. Ideally, It shouldn't be. And by results, I specifically mean `neighbors`, not the `distances`.

Here's what I have observed - This happens when we have more than one neighbor on exactly same distance from the query point. Resulting in different permutations for different value of `k`.

**Comment by rcurtin** [comment]
Ok, sorry, I did not realize that only the neighbors differed and not the distances.  If the distances differ, it is a bug, but if the neighbors differ, I don't think this is a problem.  Is it possible to work around this for #1466?

**Comment by manish7294** [comment]
Ahh! I think somehow I have confused you.

>  And by results, I specifically mean neighbors, not the distances.

By this I mean just neighbors are differing, distances are the same.

And if it's okay then I think we don't have to worry about the deviation of learned distance in #1466.

**Comment by rcurtin** [comment]
I'll go ahead and close this, I don't think it's a problem we need to deal with.
