### ISSUE TITLE
mixed distributions in a multivariate HMM 

### ISSUE THREAD

**Issue by asalhab** [mlpack/mlpack#1471]
Hi,

I have a data looks like:
ID var1 var2 var3 var4 var5 var6 var7
id1      23        1        0       3       0      31 0.9253731
id2       3        0       23       0       0       1 0.5000000
id3      10        0       97      10       0       0 1.0000000
id4      18        1       94       2       9       4 0.9375000
id5       0        0        2       4       0       0 1.0000000
id6       1        0        0       0       0       0 0.0000000
..............
..............
the first column is the observation's ID (n=300,000), the first six variables (var1-var6) follow zero inflated Poisson distribution (ZIP) distribution while the last variable follows a normal distribution.
I want to apply multivariate HMM on this data with different number of states. 
I wounder if there is a possibility in mplack to apply/implement a multivariate HMM with mixed distributions. 

Best,
Abdul

**Comment by rcurtin** [comment]
Hi Abdul,

Yes, it is definitely possible to implement this in mlpack.  But the key is that you will need to implement a function to estimate this mixed distribution.  This could be easy or kind of difficult depending on whether or not each dimension of output is independent.

In any case, here is how you would do it: by default, you would normally use the `HMM` class with a discrete distribution, Gaussian distribution, or GMM distribution (i.e. `HMM<DiscreteDistribution>`, `HMM<GaussianDistribution>`, or `HMM<GMM>`.  You will need to implement your own distribution that you can use like this: `HMM<AbdulsDistribution>`.  So you just need to write the `AbdulsDistribution` class (or whatever you'd like to call it :)).

It will need to implement the following methods:

```
class Distribution
{
 public:
  // Return the probability of the given observation.
  double Probability(const DataType& observation) const;

  // Estimate the distribution based on the given observations.
  void Train(const std::vector<DataType>& observations);

  // Estimate the distribution based on the given observations, given also
  // the probability of each observation coming from this distribution.
  // (This is the tricky one.  You need it if you are doing training without
  // knowing the hidden states.  You could take a look at the other classes
  // like GaussianDistribution to see how this function works and help
  // derive what it will need to be in your case.)
  void Train(const std::vector<DataType>& observations,
             const std::vector<double>& probabilities);
};
```

I hope this helps---let me know if I can clarify anything.

**Comment by rcurtin** [comment]
I've closed this for inactivity.  Please feel free to reopen if needed! :)
