### ISSUE TITLE
How do I explicit disable OpenMP using cmake in mlpack?

### ISSUE THREAD

**Issue by marcelotrevisani** [mlpack/mlpack#1473]
How do I explicit disable OpenMP using cmake in mlpack?

**Comment by zoq** [comment]
Currently, there is no such option; an easy option is to set ``OMP_NUM_THREADS=1`` to just use a single thread or to comment:

https://github.com/mlpack/mlpack/blob/3b7bbf0f14172cdb00fd16cbf12918b07c888b96/CMakeLists.txt#L351-L359


to disable any OpenMP functionality at build time. Let me know if one of the ideas work for you.

**Comment by rcurtin** [comment]
I opened the PR #1474 to add this support---I've been meaning to do something like this for quite some time but I guess I did not remember to actually do it.  Thank you for opening the issue to make me do it; this will be a part of the mlpack 3.0.3 release (probably will be released in the next few days).

**Comment by rcurtin** [comment]
Thanks for reporting this, it should be fixed now.  I'll release mlpack 3.0.3 shortly (I'll start the process tomorrow morning).

**Comment by marcelotrevisani** [comment]
Thanks @rcurtin !
