### ISSUE TITLE
CMA-ES inconsistencies

### ISSUE THREAD

**Issue by FloopCZ** [mlpack/mlpack#1475]
Hi everyone, first of all, thank you for the huge amount of work you have done on this project.
After a brief pass through the [CMA-ES](https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/optimizers/cmaes/cmaes_impl.hpp) implementation, I found a few inconsistencies with the documentation.

1. The documentation of the `Optimize` function states that the last parameter (`iterate`) is also used as the starting point of the algorithm. However, this parameter seems to be basically ignored and the starting point is generated randomly [here](https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/optimizers/cmaes/cmaes_impl.hpp#L91).

2. When the algorithm does not converge, it suggests to use a smaller step size [here](https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/optimizers/cmaes/cmaes_impl.hpp#L266), yet there is no way to change the step size.

3. The `lowerBound` and `upperBound` variables don't seem to be true bounds for the variables. As far as I understand the code, those are only used to deduce the initial `sigma` value and the random starting point.

Have a nice day!

**Comment by zoq** [comment]
Hello Filip,

thanks for taking the time to look into the code.

> 1. The function Optimize states that its parameter iterate is also used as the starting point of the algorithm. However, this parameter seems to be basically ignored and the starting point is generated randomly here.

I see your point, that we should be able to provide and use initial parameter; the issue I saw is that CMAES really kicks off if we start with some "reasonable" parameter; but "reasonable" highly depends on the task, and I agree that the parameter has to be tailored down for each task.

> 2. When the algorithm does not converge, it suggests to use a smaller step size here, yet there is no way to change the step size.


Good point, we should introduce two new methods to control the step size damping and the cumulation constant.

> 3. The lowerBound and upperBound variables don't seem to be true bounds for the variables. As far as I understand the code, those are only used to deduce the initial sigma value and the random starting point.

Right, I think we would have to define some general strategy to define optimizer wide bounds.

I will look into each point, in the next days and open a PR, unless someone likes to pick this up, in which case I'm happy to share the work.

**Comment by FloopCZ** [comment]
Thank you for such a swift reply. The first and the second point should be quite straightforward. The third point could be a bit tricky. One way might be to project and optimize the variables in some kind of bounded space (e.g., evaluate `sin(x)*(upper-lower)+lower` instead of `x`). But in such a case, the recommended default `sigma` and maybe some other parameters will probably need to be scaled appropriately.

I am tagging the father of the algorithm - @nikohansen, maybe he has some guidelines for this (he usually does). :slightly_smiling_face:

**Comment by zoq** [comment]
Please feel free to work on this one.
