### ISSUE TITLE
Adapt classifiers to return final objective value from `Train()`

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1483]
This is an extension of the PR #1430.  Basically, we need to look through all the mlpack classifiers (anything that implements `Train()`) and see if it is appropriate to return some kind of objective value.  Then we also have to update the documentation, and where applicable, the tests.

This could be a nice first issue for someone looking to contribute.

**Comment by starlord1311** [comment]
@rcurtin can i take up this issue?

**Comment by rcurtin** [comment]
@starlord1311 sure, you are welcome to. :)

**Comment by yashodeepm** [comment]
@rcurtin can you be more specific as to what is an objective value that needs to be returned? Can it something as simple as returning the vector of weight(with reference to a trained model using linear regression) ?

**Comment by rcurtin** [comment]
Each model is optimizing some objective function, and this is what should be returned.  Linear regression is actually a little tricky since the optimization there does not explicitly calculate the objective (which should be the mean squared error I believe), so there it may be needed to explicitly compute it (assuming the computation does not take too long).

**Comment by vaibhavb007** [comment]
Seems like there hasn't been much activity over this bug. Can I take this up?

**Comment by kss682** [comment]
Hi, I am new to mlpack and getting to know the code base.Is this issue taken and I would like to get some help to resolve it.

**Comment by rcurtin** [comment]
Hi @kss682, there is not a PR open for this issue so you are welcome to look at it.  I would suggest first trying to use the library's classifiers (like logistic regression, decision trees, etc.) from C++ to solve some simple machine learning tasks and then this should provide enough background to understand what needs to change in the code.

**Comment by walragatver** [comment]
Hi Can I work on this issue? I am new to mlpack looking forward to contribute in GSOC 19.
 I have seen code of logistic regression.

**Comment by zoq** [comment]
Hello @walragatver the comment above still applies, so if you like to work on the issue, please feel free.

**Comment by rcurtin** [comment]
Since #1678 is merged, I think this issue can be closed.  Thanks again @walragatver! :+1:
