### ISSUE TITLE
broken 3.0.3 docs on mlpack.org

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/mlpack#1484]
The following pages linked from mlpack.org/docs.html currently lead to 404:
http://mlpack.org/docs/mlpack-3.0.3/man.html
http://mlpack.org/docs/mlpack-3.0.3/python.html

**Comment by rcurtin** [comment]
Thanks, fixed.  Absent-minded while between jobs :)

**Comment by rcurtin** [comment]
Right, fixed.  Some of the release process severely needs to be automated.  I'll have to see if I can make the time in the next weeks...
