### ISSUE TITLE
FFN::Add() doesn't make copies

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1489]
The following code (from #1468) doesn't compile:

```
  FFN<NegativeLogLikelihood<>, RandomInitialization> model;
  model.Add<Linear<> >(5, 10);

  // Add a new Add<> module which adds a constant term to the input.
  Add<> addModule(10);
  model.Add(addModule);
```

This is because the type can't be matched---`addModule` can't be converted to a `LayerTypes`, which is a `boost::variant<... lots of type pointers ...>`:

```
/home/ryan/src/mlpack-atharva/src/mlpack/methods/ann/ffn.hpp:246:8: note:   no known conversion for argument 1 from ‘mlpack::ann::Add<arma::Mat<double>, arma::Mat<double> >’ to ‘mlpack::ann::LayerTypes<> {aka boost::variant<...>}
```

The other overload can't be matched because the template parameter can't be deduced:

```
/home/ryan/src/mlpack-atharva/src/mlpack/methods/ann/ffn.hpp:239:8: note:   template argument deduction/substitution failed:
/home/ryan/src/mlpack-atharva/src/mlpack/tests/feedforward_network_test.cpp:633:22: note:   couldn't deduce template parameter ‘LayerType’
   model.Add(addModule);
                      ^
```

So, I think that `model.Add<Add<>>(addModule)` could work, but it seems unnecessary to force the user to do that.  Should we change the overload `Add(LayerTypes& layer)` to actually be internally implemented as this?

```
network.push_back(&layer);
```

But the problem here is, if we do that, this doesn't make a copy so two objects will try and delete the layer (the `FFN` object and also whatever we allocated `layer` with).  I think ideally a user should be able to do this:

```
model.Add(addModule); // makes a copy
model.Add(std::move(addModule)); // uses a move and avoids a copy
```

I'm not seeing a very easy change to make though, because `LayerTypes<CustomLayers...>` is this `boost::variant` type that holds pointers.  Any thoughts on a good way to handle this?

**Comment by prateeksingh0001** [comment]
@rcurtin I would like to take up this issue, I have understood the bug. However, I have some questions

* I wasn't able to understand when you said, if we do that, this doesn't make a copy so two objects will try and delete the layer (the `FFN` object and also whatever we allocated `layer` with). Why would they try to delete the layer?
* Also, do you have any solutions in mind as of now or any pointers along which I could explore for the solution?

**Comment by darthgera123** [comment]
is this issue still open?

**Comment by rcurtin** [comment]
This issue also is not closed, so, yes, it is still open, and you can work on it if you like.  But I see that you've asked on a few issues if you can work on them, and I'd definitely suggest working on one at a time.  :+1:  So you should feel free to do any of them, but it'll probably be easier if you aren't juggling several different tasks at once.

**Comment by himanshupathak21061998** [comment]
I will try to change overload `Add(LayerTypes& layer)`  first.

**Comment by himanshupathak21061998** [comment]
@rcurtin I tried to change overload but that does not going to be good thing because we need to perform lot of changes because and  `model.Add<Add<>>(addModule)` does work. I think we should add some documentation for this `model.Add<Add<>>(addModule)` . Please suggest if you have any better idea for this.
