### ISSUE TITLE
Man page not found for 3 functions in command-line program reference page

### ISSUE THREAD

**Issue by e-aakash** [mlpack/mlpack#1498]
The man page of [mlpack_allknn](https://www.mlpack.org/docs/mlpack-3.0.3/man/mlpack_allknn.html), [mlpack_allkfn](https://www.mlpack.org/docs/mlpack-3.0.3/man/mlpack_allkfn.html) and [mlpack_allkrann](https://www.mlpack.org/docs/mlpack-3.0.3/man/mlpack_allkrann.html) are displaying 404 Not found in [command-line program reference page](https://www.mlpack.org/docs/mlpack-3.0.3/man.html).

**Comment by rcurtin** [comment]
Right, thank you!  These three were removed in mlpack 3.0.0, and the names are now `mlpack_knn`, `mlpack_kfn`, and `mlpack_krann`.  I've updated all four corresponding documentation pages, and the documentation for those three command-line programs would be these links:

https://www.mlpack.org/docs/mlpack-3.0.3/man/mlpack_knn.html
https://www.mlpack.org/docs/mlpack-3.0.3/man/mlpack_kfn.html
https://www.mlpack.org/docs/mlpack-3.0.3/man/mlpack_krann.html

Sorry for the inconvenience, but thank you for the report! :+1:
