### ISSUE TITLE
hmm in mlpack seams more slower than hmmlearn 

### ISSUE THREAD

**Issue by jerrylucky** [mlpack/mlpack#1499]
hmmlearn is a hmm lib implemented by python(https://hmmlearn.readthedocs.io/)

I use same data to train mlpack and hmmlearn, but it seams mlpack is ten times slower than hmmlearn, why ?
some parameter:
3 hidden states
8*600 train data matrix

//mlpack codes:
 ` arma::mat observation =....; //(8*600 matrix)

    HMMGaussianDistribution> _hmm = new HMM<GaussianDistribution>(3, 8);

    _hmm->Tolerance() = 0.001;

     _hmm->Train({observation});

     _hmm->Predict(observation, stateSeq);`

//hmmlearn codes:
  `  model = GaussianHMM(random_state=1, n_components=n, tol=0.001, covariance_type="diag", n_iter=1000, ).fit(observation)

    hidden_states = model.predict(observation)`

**Comment by jerrylucky** [comment]
thx you for response so quickly!

If i want use GaussianHMM with " covariance_type='diag'", what should i do ?
or could you support 'diag' in mlpack?

**Comment by rcurtin** [comment]
I know how to do it, but I don't currently have the time to implement it.  If you are willing to give it a shot, I can try and walk you through it.  Basically, we would need a class like `DiagonalGaussianDistribution` or something like this that implements the same functions as the `GaussianDistribution` class, but for a Gaussian distribution with diagonal covariance.  The "guts" of the implementation would be in the `Train()` functions, which basically just need to estimate the parameters of the (diagonal) covariance and mean given the data.  That actually turns out to be fairly simple in the diagonal case.  If you can implement that (and it works correctly) then you can just write `HMM<DiagonalGaussianDistribution>` and it should work fine.

**Comment by jerrylucky** [comment]
ok, I'll try this, thank you!

**Comment by rcurtin** [comment]
If it works and you're willing to share your code, I'd be happy to merge it in! :+1:

**Comment by jerrylucky** [comment]
ok, Hope I can complete it

**Comment by jerrylucky** [comment]
in this function:
```
void GaussianDistribution::FactorCovariance()
{
covLower = arma::chol(covariance, "lower");
....
  const arma::mat invCovLower = arma::inv(arma::trimatl(covLower));
}
arma::chol(covariance, "lower") is same to : arma::trimatl(covLower) 

```
so, why you write like this?

**Comment by shashvatshahi1998** [comment]
OK, I am not getting the file path in which we can contribute.Can anybody please tell me the file path????

**Comment by jerrylucky** [comment]
Hi, rcurtin, I read the codes about hmm, I try to modify the code to support 'diag', to sure the process is right, I think there several place should be modified:

In
`void GaussianDistribution::Train(const arma::mat& observations,  const arma::vec& probabilities)`
get the diag of covariance, like this:
`  covariance = diagmat(covariance.diag());`

then In:
`double GaussianDistribution::LogProbability(const arma::vec& observation) const`
modify the expression of probability, is that ok?

I also read the code of hmmlearn, It seams much different between mlpack and hmmlearn, the obvious different is that In hmmlearn, mean and cov be calculated like this:
```
kmeans = cluster.KMeans(n_clusters=self.n_components, random_state=self.random_state)
            kmeans.fit(X)
            self.means_ = kmeans.cluster_centers_

cv = np.cov(X.T) + self.min_covar * np.eye(X.shape[1])
 self._covars_ = distribute_covar_matrix_to_match_covariance_type(cv, self.covariance_type, self.n_components).copy()
```
It seams more efficiency than mlpack?

**Comment by rcurtin** [comment]
Ah, so the changes that you made will still try to compute the full covariance matrix, but then force it to be diagonal.  This is some extra computation there, so if you rewrote the `Train()` function such that it computed a diagonal covariance directly, I think you would see some additional significant speedup.

Otherwise, note that the different implementations may converge to somewhat different minima in different ways.  You could get a faster solution with mlpack, for instance, by reducing the tolerance for convergence in the `HMM()` constructor (the default is 1e-5, maybe you can try a larger value).

**Comment by jerrylucky** [comment]
I have modify codes , but It's not good enough, I read codes carefully, I discover that GaussianDistribution::LogProbability will be processed twice, which is in Forward and Backward?

It seems very low efficiency? Maybe I should work out LogProbability in Estimate before call Forward?

**Comment by jerrylucky** [comment]
In GaussianHMMTrainTest, I found that if I train hmm without labels, like this:
  hmm.Train(observations);
  cout << transition << endl;
  cout << hmm.Transition() << endl;

 hmm.Transition()  is not equal to transition, is this right?

**Comment by rcurtin** [comment]
I don't understand your most recent comment here about the transition matrix, unfortunately.

For the speed issue, it's actually very hard to know exactly what is going on here.  It's likely the implementation of each library is a little different, and the optimization routine will be somewhat different.  So my first thought would be to check the number of iterations of the Baum-Welch algorithm that are being used by each library (assuming you are training without labels).

Realistically I don't expect that the calls to `emission[j].Probability(dataSeq.unsafe_col(t))` (and similar) in `Forward()` and `Backward()` would cause that much slowdown, but if you'd like to adapt the code to only compute those once, perhaps this could result in some speedup.

Maybe it would be useful to share the dataset you are using?  I can try and reproduce your results when I have the time.

**Comment by sadaharu-inugami** [comment]
For 40-dimensional MFCC speech features, the HMM in MLPack is really slow (10 to 20 times) when compared to HMMLearn (which is a huge mess and doesn't actually work without a set of hotfixes). The main reasons are the slow GMM implementation and not precalculating the likelihoods in `Forward()` and `Backward()` methods. For speech data, I mostly use diagonal GMMs. However, to my best knowledge, the only speedup MLPack offers for diagonal GMMs is during training phase.

My nasty way of adapting the MLPack was as follows:
1. Create a new `DiagonalGMM` class, wrapping a `gmm_diag` object from Armadillo. Include a new `Probabilities()` method for calculation of likelihoods in multiple points (supported by Armadillo).
2. Precalculation of the likelihoods in `Forward()` and `Backward()` methods like this:
    `auto probas = arma::mat(transition.n_rows, dataSeq.n_cols);
    for (size_t state = 0; state < transition.n_rows; state++)
        probas(state, arma::span(0, dataSeq.n_cols-1)) = emission[state].Probabilities(dataSeq);`

It's my first comment here and I would like to express my appreciation for your great work. It's the first non-Kaldi/HTK library I've seen which actually has a well-written, working GMM-HMM implementation.

**Comment by rcurtin** [comment]
@sadaharu-inugami: thanks for the detailed description.  Actually I have always thought that a `DiagonalGMM` class that wraps the Armadillo functionality would be a good idea.  In fact if you have a `GMM` object named `gmm` and call `gmm.Train<EMFit<KMeans<>, DiagonalConstraint>>>` it will use Armadillo's functionality.

I can write up a nice wrapper class that will do this, and I can also incorporate the precalculation of forward and backward probabilities.  We can see how much this improves things. :)

Thanks for the nice comments about the HMM implementation.  I too once used HTK and it is a bit unwieldy and quite old now, so I have always hoped to provide something similarly powerful in mlpack.

**Comment by rcurtin** [comment]
I've opened #1658 and #1660 to handle the two suggestions here, so let's move discussion to there.  Once those are closed, I think that we will see significant speedups for the HMM code. :+1:
