### ISSUE TITLE
implement KDE

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#150]
**Reported by nslagle on 26 Feb 41795516 04:51 UTC**
KDE requires work to compile under the new mlpack::core/logger/CLI scheme.  

Migrated-From: http://trac.research.cc.gatech.edu/fastlab/ticket/148

**Comment by rcurtin** [comment]
A simple implementation can be found as a tree-independent dual-tree algorithm in the paper "Tree-Independent Dual-Tree Algorithms".

**Comment by serendipity5497** [comment]
Hey I would like to work on this.

**Comment by rcurtin** [comment]
Go ahead, I'd suggest starting with a single-tree implementation.  You can take a look at the paper referenced in the comment above and references (or my thesis "Improving Dual-Tree Algorithms" although I can't guarantee it's exciting to read), and at the implementations of single-tree and dual-tree algorithms already in mlpack as an example.

**Comment by robertohueso** [comment]
I would like to start working on this, please @serendipity5497 let me know if you continue to work on this :smiley:

**Comment by rcurtin** [comment]
@robertohueso great work, very happy to have this merged.  I will finally close this issue as fixed after so many years. :+1:
