### ISSUE TITLE
On account of running MLPACK in WINDOWS 10

### ISSUE THREAD

**Issue by atulim** [mlpack/mlpack#1514]
Sir ,

When building in Visual Studio 2017  as stated under Windows Build Instructions in http://www.mlpack.org/docs/mlpack-3.0.3/doxygen/build_windows.html , when we enter the given project location and type of project , it is showing an **error message that there is no template at expected path.**
Hence further instructions cannot be followed.
(Kindly help as I am inclined towards contributing in mlpack)
![mlpack](https://user-images.githubusercontent.com/22341556/45951567-86092480-c021-11e8-8792-5883ac4f640c.jpg)

**Comment by atulim** [comment]
As stated by-  Keon https://keon.io/mlpack-on-windows/ This also doesn't work.

**Comment by atulim** [comment]
Yes sir I have done everything as prescribed to me. Unpacked for the same
location as given in the first url mentioned, but it won't help.
Kindly help.
Thanks for your concern.

**Comment by zoq** [comment]
can you open a command prompt (cmd) and run:
```
devenv.exe /installvstemplates
```
let's see if that solves the issue.

**Comment by atulim** [comment]
Sir,
I have installed Visual Studio Community 2017 and after typing cmd command it shows error.
![untitled](https://user-images.githubusercontent.com/22341556/45989304-ce175e00-c098-11e8-8541-365b33e0e71c.jpg)
Kindly check if the software I am using is correct one or not , in the image below
![untitled2](https://user-images.githubusercontent.com/22341556/45989363-0454dd80-c099-11e8-87f1-d1e5ac5a5766.jpg)

**Comment by atulim** [comment]
Sir,
After entering the code in prompt it shows error
![untitled](https://user-images.githubusercontent.com/22341556/45989439-55fd6800-c099-11e8-940b-678239a366e7.jpg)
Kindly check if I have installed correct software or not in the image below
![untitled2](https://user-images.githubusercontent.com/22341556/45989450-67df0b00-c099-11e8-9477-724dfb91c918.jpg)

**Comment by atulim** [comment]
Followed as prescribed but not working

**Comment by zoq** [comment]
Can you click the modify button in the installer and post the image? My guess is you haven't installed the C++ desktop development module.

**Comment by zsogitbe** [comment]
Maybe I can help. First of all you have to start a Developer Command Prompt for VS and not a standard Windows command prompt for the above command Marcus (zoq) was referring to!
Secondly the description you are following seems far too complicated to me. I never followed any description just used CMake (reads the CMakeLists.txt in the root folder of the mlpack install) and generated automatically the VS project files which worked without any problem immediately.

**Comment by atulim** [comment]
@zsogitbe Kindly give me the link you want me to follow.

**Comment by zsogitbe** [comment]
Atul, please learn to use CMake [https://cmake.org](https://cmake.org) . This is really necessary if you want to be able to easily create VS project files automatically. It is very easy to use but you will have to invest a little bit of time in it to learn it. With CMake it takes 5 minutes to make the mlpack VS project files. I can not provide you an easier solution.
I hope this helps. -Z

**Comment by atulim** [comment]
@zoq thanks for your help. It solved the issue.
However can you guide me to build mlpack http://www.mlpack.org/docs/mlpack-3.0.3/doxygen/build_windows.html from here as I am facing unable to build it as it contains no mlpack.sin file even after running the command in the command prompt.
It would be grateful.
![untitled](https://user-images.githubusercontent.com/22341556/46112200-6b90a000-c207-11e8-9217-f80d83b86aca.jpg)

**Comment by zoq** [comment]
@atulim it looks like cmake can't find the necessary boost packages; if you can provide some more information (like what's inside the C:/boost/boost_1_66_0/boost_1_66_0 folder) I can see if I can help you fix the issue, what cmake command did you use.

**Comment by GLmontanari** [comment]
@atulim I had the very same problem a couple of days ago: I followed the guided procedure step by step, but mlpack refused to build for several reasons. At last I succeded using boost_1_64_0 instead of 1_66_0.
Same OpenBlas, same Armadillo version, same everything as stated in the tutorial except from the boost library version (therefore if you wanna try you will have to change the command line arguments to
-DBOOST_INCLUDEDIR:PATH="C:/boost/boost_1_64_0/" 
-DBOOST_LIBRARYDIR:PATH="C:/boost/boost_1_64_0/lib64-msvc-14.1"
)
Then a solution appeared and trying to build mlpack gave a last "Compiler out of heap space" error, which I solved by updating Visual Studio.

I used MSVS 2017 Professional, version 15.8.6

**Comment by rcurtin** [comment]
@GLmontanari: strange that Boost 1.66 didn't work, CMake should be able to find it just fine, especially with `1.66` and `1.66.0` set in the `Boost_ADDITIONAL_VERSIONS` CMake option inside of `CMakeLists.txt`.  Do you have any more information on why using Boost 1.66 failed?

**Comment by GLmontanari** [comment]
Ok, so here is the whole story: I initially tried the procedure as explained here  http://www.mlpack.org/docs/mlpack-3.0.3/doxygen/build_windows.html using boost_1_66_0 and I got the problem stated in this closed issue: https://github.com/mlpack/mlpack/issues/563

Fundamentally, or so I guess..., CMake couldn't find some libraries called boost_... .lib and libboost_....lib.
I checked under the corresponding folder and they where there.
Then I checked the CMakeLists.txt file and added Boost 1.66 in the Boost_ADDITIONAL_VERSIONS as you said.
Here is a copy of the file:

set(Boost_ADDITIONAL_VERSIONS
  "1.66.0" "1.66"
  "1.65.1" "1.65.0" "1.65"
  "1.64.1" "1.64.0" "1.64"
  "1.63.1" "1.63.0" "1.63"
  "1.62.1" "1.62.0" "1.62"
  "1.61.1" "1.61.0" "1.61"
  "1.60.1" "1.60.0" "1.60"
  "1.59.1" "1.59.0" "1.59"
  "1.58.1" "1.58.0" "1.58"
  "1.57.1" "1.57.0" "1.57"
  "1.56.1" "1.56.0" "1.56"
  "1.55.1" "1.55.0" "1.55"
  "1.54.1" "1.54.0" "1.54"
  "1.53.1" "1.53.0" "1.53"
  "1.52.1" "1.52.0" "1.52"
  "1.51.1" "1.51.0" "1.51"
  "1.50.1" "1.50.0" "1.50"
  "1.49.1" "1.49.0" "1.49")
find_package(Boost 1.66.0
    COMPONENTS
      program_options
      unit_test_framework
      serialization
    REQUIRED
)

But still didn't work. At last I decided to try using an older boost release and with version 1_64_0 it worked.
I am no expert, but I'll try to help if you have further questions.

**Comment by GLmontanari** [comment]
By the way this seems to be a generalized problem, since another issue reports the same for boost 1_68_0:
#1524

**Comment by rcurtin** [comment]
Thanks for the update.  In #1524 the idea of using `BOOST_ALL_NO_LIB` was suggested, so once I find out some more information about that, perhaps I can work up a fix that will make finding Boost a lot more robust on Windows in general and solve both of these issues.

So I'll close this now since I think at this point it'll be solved the same way as that other issue.  If I'm wrong about that please feel free to reopen. :)
