### ISSUE TITLE
-lrt is not needed on OpenBSD either

### ISSUE THREAD

**Issue by marcespie** [mlpack/mlpack#1516]
Seems to me someone should really write a test for the location of clock_gettime().

Or maybe just reverse the test.

Because NetBSD and FreeBSD have clock_gettime as part of libc either. They won't error out because they have a stub -lrt.

AFAIK, only Linux requires -lrt to get clock_gettime...

**Comment by rcurtin** [comment]
Thanks for the input!

Where are you seeing that `-lrt` is being used?  As far as I know we're not explicitly linking against it.  Also the timers use stuff from `chrono`, not `clock_gettime()` (unless `chrono` internally uses `clock_gettime()`, but that shouldn't make a huge difference in our case anyway).

Are you by chance using a really old version of mlpack (like mlpack 1.x or 2.x)?  I seem to remember those explicitly linking against -lrt in places.

**Comment by marcespie** [comment]
On Mon, Oct 08, 2018 at 07:28:25PM -0700, Ryan Curtin wrote:
> 
>    Thanks for the input!
> 
>    Where are you seeing that -lrt is being used? As far as I know we're
>    not explicitly linking against it. Also the timers use stuff from
>    chrono, not clock_gettime() (unless chrono internally uses
>    clock_gettime(), but that shouldn't make a huge difference in our case
>    anyway).
> 
>    Are you by chance using a really old version of mlpack (like mlpack 1.x
>    or 2.x)? I seem to remember those explicitly linking against -lrt in
>    places.

On libmlpack itself,  version 3.0.3

see the main CMakeLists.txt. Line 155 or so.

# For clock_gettime().
if (UNIX AND NOT APPLE AND NOT HAIKU)
  set(MLPACK_LIBRARIES ${MLPACK_LIBRARIES} "rt")
endif ()

**Comment by rcurtin** [comment]
Oh, you're right, there it is.  Seems like my grepping around didn't find it.  I think we can just remove that block entirely since clock_gettime() isn't used anymore, so I'll do that.  :+1:

**Comment by rcurtin** [comment]
Fixed in #1523. Thanks again for the report :+1:
