### ISSUE TITLE
execman linux'isms

### ISSUE THREAD

**Issue by marcespie** [mlpack/mlpack#1518]
- those scripts are not bash. They're perfectly portable bourne shell
- find -executable is a GNUism, the same thing is easy to do with POSIX find.
- compressing manpages  shouldn't be hard-coded, as that's a system preference...

[patch2.txt](https://github.com/mlpack/mlpack/files/2456615/patch2.txt)
[patch1.txt](https://github.com/mlpack/mlpack/files/2456616/patch1.txt)

**Comment by rcurtin** [comment]
Agreed on all three counts, thanks.  Do you want to open a PR?  I'd be happy to commit these with your name on the patches and add your name to the list of contributors if you like.  (And, we also mail stickers you could put on your laptop or wherever to people who have contributed!  So if you want I can get some in the mail too.)

**Comment by marcespie** [comment]
On Mon, Oct 08, 2018 at 07:31:12PM -0700, Ryan Curtin wrote:
> 
>    Agreed on all three counts, thanks. Do you want to open a PR? I'd be
>    happy to commit these with your name on the patches and add your name
>    to the list of contributors if you like. (And, we also mail stickers
>    you could put on your laptop or wherever to people who have
>    contributed! So if you want I can get some in the mail too.)
> 
>    --
>    You are receiving this because you authored the thread.
>    Reply to this email directly, [1]view it on GitHub, or [2]mute the
>    thread.

Please go ahead and commit directly.

It's small enough that I don't think it needs any attribution yet.

**Comment by rcurtin** [comment]
Fixed in #1523.
