### ISSUE TITLE
packaging of python extensions fail

### ISSUE THREAD

**Issue by marcespie** [mlpack/mlpack#1522]
The build system mistakenly assumes you can install stuff directly. This breaks havoc with any modern packaging system.

At the very least, support setting DESTDIR during configuration. It would be better to do that during the install stage, but it allows things to proceed correctly.
[patch.txt](https://github.com/mlpack/mlpack/files/2460366/patch.txt)

**Comment by rcurtin** [comment]
You can get the same effect by just configuring CMake with `-DCMAKE_INSTALL_PREFIX=/your/preferred/install/root/`. :)

**Comment by rcurtin** [comment]
(I already responded to this via a personal email, but probably better to respond here publicly just so all the discussion is in one place.)

Thanks for the clarification---I understand the difference now.  Are you sure that DESTDIR doesn't already work?  i.e.

`make DESTDIR=/path/to_staging_area/ install`?

The CMake documentation suggests this already should work on UNIX-like CMake systems:

https://cmake.org/cmake/help/latest/envvar/DESTDIR.html

**Comment by rcurtin** [comment]
Fixed in #1523.
