### ISSUE TITLE
Trouble using mlpack with g++ in ubuntu 17.10

### ISSUE THREAD

**Issue by HelioStrike** [mlpack/mlpack#1527]
This is a code snippet I got from [here](http://www.mlpack.org/docs/mlpack-3.0.3/doxygen/formatdoc.html):

```
#include <mlpack/core.hpp>
using namespace mlpack;

arma::mat matrix1;
data::Load("dataset.csv", matrix1);
```

I'm trying to compile it using "g++ a.cpp -lmlpack -larmadillo", but I keep getting the following output:

```
1.cpp:5:11: error: expected constructor, destructor, or type conversion before ‘(’ token
 data::Load("dataset.csv", matrix1);
```

The cli and python bindings seem to work properly though.

Here's how I installed mlpack:
- Downloaded the tar.gz file
- tar -xvzf mlpack-3.0.3.tar.gz
- mkdir mlpack-3.0.3/build && cd mlpack-3.0.3/build
- cmake ../
- make
- sudo make install
- export LD_LIBRARY_PATH=/usr/local/lib
- export PATH=$PATH:~/mlpack/build/bin

I put both export statements in ~/.bashrc.

What am I missing?

**Comment by rcurtin** [comment]
That's a snippet not an entire working program, so you'll need to put it in `int main()` or something.

**Comment by HelioStrike** [comment]
Oh darn... this is embarassing. Sorry about that, all that python is finally getting to me.

**Comment by rcurtin** [comment]
No worries. :) One of the open issues right now is to redo all the documentation so it's fully buildable, so that should be helpful in the future.
