### ISSUE TITLE
An example/tutorial of time series prediction 

### ISSUE THREAD

**Issue by jbensabat** [mlpack/mlpack#1528]
Hello 
I am new to mlpack and just managed to build the library
I would like to start using it by training and predicting time series
Where can I find an example to start from ?

best
jac

**Comment by zoq** [comment]
Glad you managed to build mlpack; @zsogitbe wrote an example for a neural network regression model #1529 , so if you can phrase the problem as a regression problem, I think this could be really helpful here.

**Comment by jbensabat** [comment]
Thanks
Jac


Jacob Bensabat, PH.D.
CTO
EWRE Ltd.
Tel: +972-4-8383919.
Fax: +972-4-8387621.
Mobile: +972-544-417511.
