### ISSUE TITLE
Wrong HMM predict (state sequence) and LogLikelihood

### ISSUE THREAD

**Issue by aabghari** [mlpack/mlpack#1538]
Hi,
I have a HMM model. Sometime the state sequence estimation is wrong which all the states are zero for  example. I have checked the output with a python hmm implementation hmmlearn. hmmlearn seems to give the right answers for the same model and parameters. I have attached a cpp file which uses MLPACK and a python file which uses hmmlearn. Both have the same parameters and observation. I have put enough comment in the cpp file to follow. The version of the MLPACK is 3.0.3.

Thanks,

Arash
[hmm_test.zip](https://github.com/mlpack/mlpack/files/2493314/hmm_test.zip)

**Comment by aabghari** [comment]
I think I know why it happens. The problem is the numerical instability when calculating logStateProb. I am going to provide you with a patch.

**Comment by rcurtin** [comment]
Ah, great, thanks for digging in!  I have not had time to look into it---I was hoping I could maybe tonight or tomorrow.  But if you can provide a patch, it accelerates the whole bug fixing process :)

**Comment by aabghari** [comment]
How do you want me to provide you with the patch?

**Comment by rcurtin** [comment]
A pull request is fine, or if you prefer, you can just post the diff here and I can create the PR.  Whatever is most convenient for you. :+1:

**Comment by aabghari** [comment]
Hi, 
Please find the attached diff file. Let me explained what I have done. I think there are two cases which are the root of the problem.
1. Using the emission probability  instead of the logprob directly. For example in Predict() there is this line which uses the log of the emission probability like this log(emission.probability()). If you look at the emission prob calculation, you see that it's actually calculated from the logprob by taking an exp(). So we have log()->exp()->log() which causes numerical instability.
2. In all probability calculation either Forward() or Backward() for example, All the values are getting multiplied with each other which makes them very small at the end.

To fix the above mentioned causes, I replaced all the prob calculations with the log version. Thus, instead of multiply, it's all addition now. It can even reduce the CPU consumption since everything is now addition and subtraction. To achieve this I have to add to new functionalities which are AddLog() and AccuLog(). I have put this functions under core/math/log_add.{cpp,hpp}. Feel free to restructure them according to mlpack policy. 
I have to add a LogProbability function to GMM distribution as well so it can work with the new log version of the HMM.
I have also added a test case. This is the one originally failed on my application and that's how I discovered the issue at the first place.
All the tests are passed with this patch.

Please let me know when you have accepted this patch and merged it into the main branch.

BTW, the patch is against the master branch.

Thanks,

Arash 

P.S. the same approach (using LogAdd()) can be used where ever you have softmax  layer to avoid instability too.

[hmm.patch.zip](https://github.com/mlpack/mlpack/files/2501925/hmm.patch.zip)

**Comment by rcurtin** [comment]
I opened #1547 with your patch, which I adapted slightly in a few cases.  I inliend the `LogAdd()` and `AccuLog()` functions, as well as templatizing them.

Would you like me to add your name to the files that you modified?  This is a really nice contribution and we can add your name to `src/mlpack/core.hpp` and `COPYRIGHT.txt` as well as the website.  In addition, we like to mail mlpack stickers to new contributors that they can put on their laptop. :)  If you want some, just send me an email at ryan@ratml.org and I can get them in the mail for you.  It could take a few weeks for them to arrive.

**Comment by rcurtin** [comment]
No problem, it is still a patch that you prepared.  :)  Let me know what name (and email if you want to add that) you'd like me to use, and if you want any stickers.

**Comment by rcurtin** [comment]
Updated.  Thanks! :+1:

**Comment by rcurtin** [comment]
Hey @aabghari, thanks again for the patch.  It is merged now. :+1:
