### ISSUE TITLE
CF: add alternatives in command-line program

### ISSUE THREAD

**Issue by wenhaoh2** [mlpack/mlpack#1542]
Over the summer we have added alternative algorithms in the collaborative filtering module for rating normalization, neighbor search and weight interpolation. But we haven't added supports for these alternatives in the command-line binding. I think this is a good task for someone who is interested in collaborative filtering or looking for a way to contribute to mlpack.

The current command-line program of CF uses `NoNormalization` for rating normalization, `EuclideanSearch` for neighbor search, `AverageInterpolation` for weight interpolation. But there are other alternative algorithms. For example, we can use `OverallMeanNormalization`, `CosineSearch`, `RegressionInterpolation`. You can find the alternative algorithms in the folder `normalization`, `neighbor_search_policies`, `interpolation_policies` under `src/mlpack/methods/cf/`.

To complete this, I suggest:

1. Roughly go through the classes and function definitions in `src/mlpack/methods/cf/` to get a basic idea of what the cf module is doing.
2. Read `cf_main.cpp`, `cf_model.hpp`, `cf_model_impl.hpp` because they are directly related to the implementation of CF's command-line program.
3. Reading the actual implementation of the algorithms is not necessary but it could give you a better understanding.

There are three small tasks:

- [x] **Easier**: add supports for alternative **neighbor search** and **interpolation** algorithms. We might only need to modify the `RecommendationVisitor` and `PredictVisitor` in `CFModel`, and the corresponding parts in `cf_main.cpp`.
- [x] **Perhaps harder**: add support for alternative **rating normalization** . I don't have a good idea on how to do this neatly. Please comment below if anyone comes up with a neat solution.
- [x] Testing: add test cases for these alternative algorithms in `src/mlpack/tests/main_tests/cf_test.cpp`.

Let me know if you need help or if I can clarify anything.

**Comment by kaushik-p9** [comment]
@Wenhao-H I will definitely work on this :)

**Comment by bikram99** [comment]
I could find the RecommendationVisitor and PredictVisitor in CFType in the file cf.hpp and not in CFModel.
I mean should I make the modifications there? I am new to this ,so I dont quite understand.Would you please clarify this?

**Comment by Wenhao-H** [comment]
Because a PR has been opened for the first small task so I've marked it as taken. To avoid duplicated work, if you want to take one of the other two tasks, please comment here so I can mark it as taken for you :)

**Comment by Wenhao-H** [comment]
@bikram99 Sure but I might have to make a reply later because I am taking exams these two days:)

**Comment by bikram99** [comment]
Okay ,Thanks. :)

**Comment by rcurtin** [comment]
I wrote a couple of ideas for the main_tests in #1546.  @bikram99 perhaps the ideas in those comments can be helpful---you can work with those test ideas and adapt them.

**Comment by bikram99** [comment]
Sorry I was unable to fix the issue after some tries maybe due to lack of understanding .If someone else wants to work on the issue they can
I apologise for the delay 😅

**Comment by zoq** [comment]
No worries, Ryan outlined a test here: https://github.com/mlpack/mlpack/pull/1546#pullrequestreview-170290683, but don't feel obligated to work on that part, perhaps @AYESDIE is interested to work on that part as well.

**Comment by shishir1310** [comment]
@Wenhao-H, Is second issue(rating normalization) still on? If yes I would like to work on this issue.

**Comment by Wenhao-H** [comment]
@shishir1310 Sorry for the late reply. The second issue is not fixed yet and you are welcome to work on this one:)

**Comment by rcurtin** [comment]
With #2136 solved, I think that we can close this issue. :)
