### ISSUE TITLE
CNN crash, possible connection to 'ANN Input/Output Size #1267'

### ISSUE THREAD

**Issue by zsogitbe** [mlpack/mlpack#1549]
When running DigitRecognizerCNN.cpp from 'models' the calculation crashes at the first training run (optimization) in Mat_meat.hpp (armadillo) at line 809: 

`arrayops::copy( memptr(), in_mat.mem, in_mat.n_elem );`

in function:

```
template<typename eT>
inline
Mat<eT>&
Mat<eT>::operator=(const Mat<eT>& in_mat)
```

which is called by (in convolution_impl.hpp ):

`arma::Mat<eT> deltaSlice = mappedError.slice(outMap);`

in template function:

```
::Gradient(
    const arma::Mat<eT>&& /* input */,
    arma::Mat<eT>&& error,
    arma::Mat<eT>&& gradient)
```
It gives an error:

`Exception thrown at 0x00007FFEF2D4C3C7 (vcruntime140.dll) in sample-ml-app.exe: 0xC0000005: Access violation reading location 0x00000294CD481000.`

It is most probably a parameter size problem in the convolution network which causes memory corruption.

I am experiencing a lot of problems with CNN networks (random crashes). If the problem is found and corrected then I think that a further step will be needed to make the code more robust and less error/crash prone. It is not OK to just crash when there is a wrong parameter (from the user or from the algorithm itself). I think that some kind of parameter check should be built in and probably more exception handling where needed...

**Update**:
After further investigation setting the BATCH_SIZE to 1 (instead of the original 50) solves the crash problem. In this way it probably stays in the allocated memory.

**Comment by rcurtin** [comment]
Ah, thanks for the update about the batch size.  That should make finding the issue easier.

I took a quick look in valgrind a few days ago when you filed this and saw all kinds of invalid memory accesses, but I haven't had the time to track down the exact code that's failing quite yet.

**Comment by rcurtin** [comment]
I opened #1554; this should fix the issue.
