### ISSUE TITLE
Not Working of the Range function in MLPack

### ISSUE THREAD

**Issue by atulim** [mlpack/mlpack#1563]
![screenshot from 2018-11-13 19-52-05](https://user-images.githubusercontent.com/22341556/48419658-89e23900-e77e-11e8-8557-6ee8fa82d339.png)

Able to build the solution without the for loop. But with the for loop it gives error. I want to print the distances  from a data set to all the neighbors of a point that fall into a certain range of distances.

**Comment by rcurtin** [comment]
You actually need a double for loop here---both `neighbors` and `distances` are vectors of vectors.  So `neighbors[i]` is actually a vector, not a single value.  You'll need to do something like `neighbors[i][j]`.

**Comment by atulim** [comment]
Okay, can u write the loop fr it if i create neighbours[20] and distance
[20]? It would be helpful.

**Comment by rcurtin** [comment]
I'm not sure what you mean.  The code is very simple and what you have already written is close.  Remember that you are using range search, so the number of points in the given range for each query point might be different (hence the need for `vector<vector<size_t>> neighbors`).  Maybe you should consider taking a look at the documentation for RangeSearch or at the files `src/mlpack/tests/range_search_test.cpp` or `src/mlpack/tests/main_tests/range_search_test.cpp` to get an idea of how to use the results?

**Comment by atulim** [comment]
Ok sir. I ll take a look at it. You can close the issue.
Thank you.

**Comment by rcurtin** [comment]
Sounds good. :+1:
