### ISSUE TITLE
option inconsistency --output_file vs --predictions_file

### ISSUE THREAD

**Issue by barak** [mlpack/mlpack#1565]
Why is it
* `mlpack_perceptron --output_file` and
* `mlpack_logistic --output_file` but
* `mlpack_decision_tree --predictions_file`?

**Comment by rcurtin** [comment]
Oversight. :)

I think that we should change all to `predictions_file`, but we have to do this in a reverse-compatible way until mlpack 4.0.0 when we can remove the `output_file` options.

If anyone is looking for a new task to do, I think this is a good one:

 1. Find all bindings in `src/mlpack/methods/` that have some line like `PARAM_MATRIX_OUT("output", ...)` where the output matrix is some output predictions.  That's probably just `mlpack_perceptron` and `mlpack_logistic_regression` but there may be some others so we should check them all.
 2. Add an option `PARAM_MATRIX_OUT("predictions", ...)` that does the same thing.
 3. Add a comment pointing out that `output` can be removed in mlpack 4.0.0, and modify the documentation for the `output` option to point out that it is deprecated.
 4. Ensure that, for now, the output matrix for `predictions` and `output` is identical.
 5. Update any tests in `src/mlpack/tests/main_tests/` to make sure that `predictions` and `output` are the same.

**Comment by e-aakash** [comment]
@rcurtin Can i take up this issue?

**Comment by Hemal-Mamtora** [comment]
I've found all occurences of PARAM_MATRIX_OUT in `src/mlpack/methods/` which are as follows:

kmeans/kmeans_main.cpp:PARAM_MATRIX_OUT
kmeans/kmeans_main.cpp:PARAM_MATRIX_OUT
lmnn/lmnn_main.cpp:PARAM_MATRIX_OUT
lmnn/lmnn_main.cpp:PARAM_MATRIX_OUT
lmnn/lmnn_main.cpp:PARAM_MATRIX_OUT
decision_tree/decision_tree_main.cpp:PARAM_MATRIX_OUT
det/det_main.cpp:PARAM_MATRIX_OUT
det/det_main.cpp:PARAM_MATRIX_OUT
det/det_main.cpp:PARAM_MATRIX_OUT
radical/radical_main.cpp:PARAM_MATRIX_OUT
radical/radical_main.cpp:PARAM_MATRIX_OUT
rann/krann_main.cpp:PARAM_MATRIX_OUT
pca/pca_main.cpp:PARAM_MATRIX_OUT
logistic_regression/logistic_regression_main.cpp:PARAM_MATRIX_OUT
approx_kfn/approx_kfn_main.cpp:PARAM_MATRIX_OUT
nmf/nmf_main.cpp:PARAM_MATRIX_OUT
nmf/nmf_main.cpp:PARAM_MATRIX_OUT
fastmks/fastmks_main.cpp:PARAM_MATRIX_OUT
preprocess/preprocess_binarize_main.cpp:PARAM_MATRIX_OUT
preprocess/preprocess_split_main.cpp:PARAM_MATRIX_OUT
preprocess/preprocess_split_main.cpp:PARAM_MATRIX_OUT
gmm/gmm_probability_main.cpp:PARAM_MATRIX_OUT
gmm/gmm_generate_main.cpp:PARAM_MATRIX_OUT
hoeffding_trees/hoeffding_tree_main.cpp:PARAM_MATRIX_OUT
nca/nca_main.cpp:PARAM_MATRIX_OUT
sparse_coding/sparse_coding_main.cpp:PARAM_MATRIX_OUT
sparse_coding/sparse_coding_main.cpp:PARAM_MATRIX_OUT
neighbor_search/knn_main.cpp:PARAM_MATRIX_OUT
neighbor_search/kfn_main.cpp:PARAM_MATRIX_OUT
mean_shift/mean_shift_main.cpp:PARAM_MATRIX_OUT
mean_shift/mean_shift_main.cpp:PARAM_MATRIX_OUT
kernel_pca/kernel_pca_main.cpp:PARAM_MATRIX_OUT
mvu/mvu_main.cpp:PARAM_MATRIX_OUT
emst/emst_main.cpp:PARAM_MATRIX_OUT
naive_bayes/nbc_main.cpp:PARAM_MATRIX_OUT
random_forest/random_forest_main.cpp:PARAM_MATRIX_OUT
dbscan/dbscan_main.cpp:PARAM_MATRIX_OUT
hmm/hmm_generate_main.cpp:PARAM_MATRIX_OUT
local_coordinate_coding/local_coordinate_coding_main.cpp:PARAM_MATRIX_OUT
local_coordinate_coding/local_coordinate_coding_main.cpp:PARAM_MATRIX_OUT
lsh/lsh_main.cpp:PARAM_MATRIX_OUT

There are some examples like PARAM_MATRIX_OUT("**distances**", ...). Do we need the changes for these examples too ?
or is it only for PARAM_MATRIX_OUT("**output**", ..)

@rcurtin 
Could I take up the issue ?

**Comment by ShyamPandya** [comment]
Hi, @rcurtin 

I have closely been following mlpack for a few months and using it in my projects as well. I am really eager to start contributing to the organization. But as a beginner, I felt this is the best fit issue that I could fix and start collaborating to mlpack. Could I take up this issue please?

**Comment by rcurtin** [comment]
@e-aakash @Hema-Mamtora @ShyamPandya: It doesn't make sense for me to give permission to a certain person to work on the issue.  In the end the only thing that really matters from my end is that the issue is solved, so whatever PR comes around first is the one I'll review first.  This one might be too simple to work together on, but maybe it makes sense to coordinate efforts so you are not duplicating work.

@barak: I see where you are coming from, but I feel like a system like that might be a little too intensive to set up, and I don't know if there is actually enough similarity between all the programs to enforce only a small set of possible option names. :(  Probably better might be to run something like `find ./src/mlpack/methods/ -iname '*_main.cpp' -exec cat \{\} \; | grep PARAM_ | sed 's/^PARAM_[A-Z_]*("\(.*\)".*$/\1/' | sort | uniq -c` before a release.  (I think that will work... didn't actually try it though, just wrote it here...)

**Comment by barak** [comment]
@rcurtin Well people could always add a new option to that file. The idea is just to make a central place where all option names are listed, to make it easier to reuse an existing one when appropriate rather than coining a new one. (As you might imagine, I hit this when trying to write an shell script to apply a variety of methods to a single dataset automatically. This was intended as an example.)

**Comment by barak** [comment]
Yeah, a checklist, and a shell script to help scan for outliers and such, seems like a very sensible approach.

Another idea, a bit heavier-handed, that could be used in addition, would be to add each new command to a shell script that runs each command against whichever of some small set of tiny datasets it can work on. As a sort of last-ditch reality check plus command-line option revelation.

**Comment by Hemal-Mamtora** [comment]
> Oversight. :)
> 
> I think that we should change all to `predictions_file`, but we have to do this in a reverse-compatible way until mlpack 4.0.0 when we can remove the `output_file` options.
> 
> If anyone is looking for a new task to do, I think this is a good one:
> 
> 1. Find all bindings in `src/mlpack/methods/` that have some line like `PARAM_MATRIX_OUT("output", ...)` where the output matrix is some output predictions.  That's probably just `mlpack_perceptron` and `mlpack_logistic_regression` but there may be some others so we should check them all.
> 2. Add an option `PARAM_MATRIX_OUT("predictions", ...)` that does the same thing.
> 3. Add a comment pointing out that `output` can be removed in mlpack 4.0.0, and modify the documentation for the `output` option to point out that it is deprecated.
> 4. Ensure that, for now, the output matrix for `predictions` and `output` is identical.
> 5. Update any tests in `src/mlpack/tests/main_tests/` to make sure that `predictions` and `output` are the same.

Doubts :
1. "Modify the documentation showing depracated." Where is the documentation to be modified? 
2. The string "output" seems to be used in the code (for example in kmeans_main.cpp: line no. 256, 272, 293, 295, 303, 316) etc.
Do we need to modify all those to "predictions"?

**Comment by rcurtin** [comment]
@Hemal-Mamtora: #1582 is open and I reviewed it, so maybe you could base some work off that.  Perhaps that would clarify things?

It would probably be worthwhile to look through one of the bindings (like `kmeans_main.cpp`) to get an idea of how it is structured.  Specifically this issue has to do with the `PARAM_...` macros, which are what define the parameters used by the binding.

**Comment by shashank-007** [comment]
@rcurtin i am beginner .can you provide me guidelines and steps so that i can work on this issue?

**Comment by ShikharJ** [comment]
@rcurtin Should this be kept open?

**Comment by rcurtin** [comment]
Yeah, let's keep this one open.  I forgot to mark it with the relevant tag, sorry.

**Comment by rcurtin** [comment]
Thanks @jeffin143 and @Hemal-Mamtora.  It looks to me like all of the classifiers now have `--predictions` as output not `--output`.  So we now have consistency. :+1:
