### ISSUE TITLE
Problems in Optimizer Problem

### ISSUE THREAD

**Issue by atulim** [mlpack/mlpack#1571]
Sir , 
Following your tutorial at http://www.mlpack.org/docs/mlpack-3.0.4/doxygen/optimizertutorial.html and subheading **Simple Function and Optimizer example**  , I can't compile the example . I have made following program - 
class ObjectiveFunction
{
 public:
  // A separable function consisting of four quadratics.
  ObjectiveFunction()
  {
    in = arma::vec("20 12 15 100");
    bi = arma::vec("-4 -2 -3 -8");
  }
  size_t NumFunctions() { return 4; }
  void Shuffle() { ord = arma::shuffle(arma::uvec("0 1 2 3")); }
  double Evaluate(const arma::mat& para, const size_t s, const size_t bs)
  {
    double cost = 0;
    for (size_t i = s; i < s + bs; i++)
      cost += para(ord[i]) * para(ord[i]) + bi(ord[i]) * para(ord[i]) + in(ord[i]);
    return cost;
  }
  void Gradient(const arma::mat& para, const size_t s, arma::mat& g, const size_t bs)
  {
    g.zeros(para.n_rows, para.n_cols);
    for (size_t i = s; i < s + bs; i++)
      g(ord[i]) += (1.0 / bs) * 2 * para(ord[i]) + bi(ord[i]);
  }
 private:
  // Intercepts.
  arma::vec in;
  // Coefficient.
  arma::vec bi;
  // Function order.
  arma::uvec ord;
};

class SimpleOptimizer
{
 public:
  SimpleOptimizer(const size_t bs = 1, const double lr = 0.02) : bs(bs), lr(lr) { }
  template<typename FunctionType>
  double Optimize(FunctionType& function, arma::mat& parameter)
  {
    arma::mat gradient;
    for (size_t i = 0; i < 5000; i += bs)
    {
      if (i % function.NumFunctions() == 0)
      {
        function.Shuffle();
      }
      function.Gradient(parameter, i % function.NumFunctions(), gradient, bs);
      parameter -= lr * gradient;
    }
    return function.Evaluate(parameter, 0, function.NumFunctions());
  }
 private:
  size_t bs;
  double lr;
};

int main()
{
  ObjectiveFunction function;
arma::mat parameter("0 0 0 0;");
SimpleOptimizer optimizer;
double objective = optimizer.Optimize(function, parameter);
std::cout << "Objective: " << objective << std::endl;
std::cout << "Optimized function parameter: " << parameter << std::endl;
}
and the following command to compile it -  g++ example.cpp -o knn_example -std=c++11 -larmadillo -lmlpack -lboost_serialization
It shows various kind of errors which I am unable to debug - 
![screenshot from 2018-11-18 20-45-14](https://user-images.githubusercontent.com/22341556/48674495-f68c7780-eb72-11e8-9de1-3bc05cb9513d.png)

**Comment by rcurtin** [comment]
Hi Atul, the questions you are asking are basic C++ questions and so I am not sure they are fully appropriate here.  I would suggest consulting basic C++ references to learn to debug these problems.

By the way, issue #1511 is open which may help with this in the long run but it may be a while until that is resolved.

**Comment by atulim** [comment]
Sir,
As you can see the errors are related to keywords related to MLPACK such as arma etc. Had it been basic I would have solved it or had taken help from internet. But I cannot find help for this question.

**Comment by rcurtin** [comment]
You are not including Armadillo or mlpack headers.

**Comment by atulim** [comment]
#include <mlpack/core.hpp>
using namespace mlpack;

Would work out fine ?

**Comment by rcurtin** [comment]
Have you tried it?  Please be self sufficient---my time to help out is pretty limited. (Actually I am on vacation right now...)

**Comment by atulim** [comment]
Ok. I am sorry. Its just that I wanna involve all the files of MLPack. Can
it be done by these headers?

Lastly. I won't ask irrelevant questions.
Sorry. Enjoy your vacay. :)
