### ISSUE TITLE
Incorrect formula for derivative of logistic_function on vectors

### ISSUE THREAD

**Issue by ajaysub110** [mlpack/mlpack#1572]
template<typename InputVecType, typename OutputVecType>
  static void Deriv(const InputVecType& y, OutputVecType& x)
  {
    x = y % (1.0 - y);
  }
This is the current function for calculating the derivative of x = 1/(1+e^-y) (logistic function used between layers in anns). I think it is incorrect and should be changed to x = y*(1.0-y)

**Comment by ajaysub110** [comment]
Can I take it up?

**Comment by rcurtin** [comment]
This is not an error. Please read the Armadillo documentation. `%` is elementwise multiplication.
