### ISSUE TITLE
Unable to build mlpack on mac: 'armadillo' file not found 

### ISSUE THREAD

**Issue by kayoyin** [mlpack/mlpack#1573]
Hello,

I have installed and built mlpack, boost and armadillo from source following all the steps and using cmake. However, when I try to run a sample code on Xcode, I get buildtime errors from "'armadillo' file not found" next to `#include <armadillo>` in `arma_extend.hpp`.
I have also included the search paths in my xcode project too.
I noticed that all the other includes work when they're including header files, and `#include <armadillo/Mat_bones.hpp>` works as well for instance, but I cannot include armadillo as a folder.

I'm new to using installed libraries on c++, thank you for your help

**Comment by rcurtin** [comment]
Hi there, there's not much information here to help debug.  One thing to point out here though is that `#include <armadillo>` does not include a directory---actually `armadillo` is a header file (but it does not have a `.h` or `.hpp` suffix).

**Comment by zoq** [comment]
Also, make sure to link against armadillo/mlpack, for example I use something like: ``clang++ test.cpp -larmadillo -lmlpack``

**Comment by kayoyin** [comment]
Hi! So I ended up installing Ubuntu on a VM and built mlpack from there, and everything seems to work there now. I gave up installing on mac OS but thank you for your replies, cheers!

**Comment by rcurtin** [comment]
Hey there, glad you got it worked out!  If you want to debug OS X sometime we are happy to help, but if not I'll close this issue for now. :+1:
