### ISSUE TITLE
nitpicks post 3.0.4

### ISSUE THREAD

**Issue by marcespie** [mlpack/mlpack#1576]
- comment 
# We can probably use FindPythonInterp when we require CMake 3.0.
in src/mlpack/bindings/python/CMakeLists.txt    is obsolete

- allexec2man still contains one linuxism.
find ..  -executable
is gnu find only, the portable idiom would read:
find . -perm -u+x

**Comment by rcurtin** [comment]
See #1583 for the fixes---thanks again for pointing these out.  Always happy to make further changes if more make your life easier. :+1:

**Comment by rcurtin** [comment]
#1583 is merged so I will close this.  Thanks again for reporting the issues. :)
