### ISSUE TITLE
non-configurable install directory locations

### ISSUE THREAD

**Issue by marcespie** [mlpack/mlpack#1578]
I still have a patch in OpenBSD because we install our man pages straight under /usr/local/man and not /usr/local/share/man

Actually, there's a module in cmake that ought to take care of that:
`
include(GNUInstallDirs)`

but this is likely to affect a bit more than just manpages...

Please consider it.

**Comment by rcurtin** [comment]
:+1: I can work up a patch for that.  I think I have meant to use `GNUInstallDirs` for some time now.

**Comment by rcurtin** [comment]
#1583 includes the patch. :)

**Comment by rcurtin** [comment]
#1583 is merged so I will close this now.  Thanks again for the report and if you find more please don't hesitate to open more issues. :+1:
