### ISSUE TITLE
Binary space tree (and subtypes) can't use non static metrics

### ISSUE THREAD

**Issue by reverendbedford** [mlpack/mlpack#1579]
Reading the documentation it seems I should be able to use a non-static metric with state with neighbor searches and range queries.  However, when I try to setup a tree (specifically a BallTree) with a metric with a non-static Evaluate function I get errors pointing to

https://github.com/mlpack/mlpack/blob/dabd108b38c8f58648c0b137dd60c8e9cf51f243/src/mlpack/core/tree/binary_space_tree/binary_space_tree_impl.hpp#L797-L799

Which of course makes sense, as it's calling a static Evaluate.

Is there a work around or a fix in the works?

**Comment by rcurtin** [comment]
Hey there @reverendbedford, I can handle this one.  It should be a relatively easy fix.  Originally (as the documentation says) the code was designed to handle non-static metrics but it looks like a case was overlooked.

Actually the fix should basically be as simple as changing `MetricType::` to `metric.`, but I'll also write a test to ensure it works.
