### ISSUE TITLE
Multidimensional RNN in mlpack ?

### ISSUE THREAD

**Issue by kvcuong** [mlpack/mlpack#1580]
Hi,
I've read about CRNN net papers for word-spotting, they reported really good result. Does Mlpack support Multi-Dim RNN like Bi-LSTM or MD-LSTM and CTC layers in order to build CRNN ?

I saw that mlpack has lstm, how can i stack 2 lstm to build Bi-LSTM ? 

thanks in advance.

**Comment by zoq** [comment]
Currently, there is no support for MD-LSTM or B-LSTM; in case of B-LSTM it could be simulated by using two instances of the RNN class that are merged after each iteration.

**Comment by shravankumar9892** [comment]
@zoq  So is it worth creating a blstm.hpp separately in the methods/ann/layer directory? Does it apply to brnn as well?

**Comment by zoq** [comment]
What I had envisioned is another class similar to the ``RNN`` class, so there is no need to adjust or rewrite any layer. The basic idea would be to do two passes at the "same" time and merge the output at the end. Perhaps we could even reuse the RNN class internally. Let me know what you think.

**Comment by sourabhvarshney111** [comment]
@zoq @shravankumar9892 I think first we can try to make that BRNN class similar to RNN class, which I took the responsibility this summer, but couldn't complete due to my tight schedule. I think that would be a good start.

**Comment by shravankumar9892** [comment]
Yeah can work on the issue @sourabhvarshney111

**Comment by zoq** [comment]
I think the easiest thing would be to start with the Forward pass, so right now we perform a single Forward step:

https://github.com/mlpack/mlpack/blob/823c34d46c67c6ff652af0bdf3ebbaddc96bc2b8/src/mlpack/methods/ann/rnn_impl.hpp#L208-L211

to get this to work, we also have to do another Forward step with the data from the other direction.

**Comment by shravankumar9892** [comment]
Yes @zoq, we'll have to do it from other direction as well.

**Comment by zoq** [comment]
Okay, great, let me know if I should clarify anything.
