### ISSUE TITLE
Documentation is 404ing

### ISSUE THREAD

**Issue by Amndeep7** [mlpack/mlpack#1590]
https://www.mlpack.org/docs/mlpack-git/doxygen/index.html

http://www.mlpack.org/docs/mlpack-git/doxygen/namespacemlpack_1_1rl.html

All this stuff is 404ing cause it appears that the doxygen folder was deleted / is no longer there.

**Comment by rcurtin** [comment]
Fixed now.  Strange, a system upgrade on mlpack.org resulted in the Boost libraries being removed, which meant that the library (and thus documentation) failed to build.  And I did not look closely enough at the log email to notice. :(  (Hence the importance of log emails that only point out problems and aren't filled with noise!)

Thanks for pointing out the issue! :+1:
