### ISSUE TITLE
MLPACK build failed on MSVC + permissive- on windows

### ISSUE THREAD

**Issue by QuellaZhang** [mlpack/mlpack#1593]
MLPACK failed when build with /permissive- by msvc on Windows, I use latset version dabd108 on master branch. Could you please help look at this?

**You can repro this issue as the steps below:**

1. git clone https://github.com/mlpack/mlpack D:\MLPACK\src
2. it dependent armadillo and OpenBlas, put them to D:\MLPACK\external\
3. open a VS 2017 amd64 command prompt as admin and browse to D:\MLPACK
4. set _CL_=/permissive-
5. mkdir build_x64 && pushd build_x64
6. cmake -G "Visual Studio 15 2017 Win64" -DBLAS_LIBRARY=%cd%\..\external\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a -DLAPACK_LIBRARY=%cd%\..\external\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a -DARMADILLO_INCLUDE_DIR=%cd%\..\external\armadillo-9.200.4\include -DARMADILLO_LIBRARY=%cd%\..\external\armadillo-9.200.4\lib\armadillo.lib -DBOOST_INCLUDEDIR=C:\boost_1_67_0\x64 -DBOOST_LIBRARYDIR=C:\boost_1_67_0\x64\lib64-msvc-14.1 -DDEBUG=OFF -DPROFILE=OFF ..\src
7. msbuild /m /p:Configuration=Release;Platform=x64 mlpack.sln /t:Rebuild

**Failures:**
cl : Command line error D8021 : invalid numeric argument '/Wno-unknown-pragmas'

**Comment by rcurtin** [comment]
Thanks for the report.  I don't have a Windows system set up, but I took a look at the error and I think I know what it is.

Can you try replacing `CMakeLists.txt` with the following file and let me know what happens?  http://www.ratml.org/misc/CMakeLists.1593.txt

Thanks! :+1:

**Comment by QuellaZhang** [comment]
Thank you @rcurtin . I verified the new CMakeLists and MLPACK compiled very well under /permissive- mode.

**Comment by ShikharJ** [comment]
@QuellaZhang Feel free to close this issue if you feel it has been addressed :)

**Comment by QuellaZhang** [comment]
Yes, I could use the workround. And I want to know if there is a plan to fix the source code? @rcurtin @ShikharJ Thanks in advanced!

**Comment by rcurtin** [comment]
Definitely, I am planning to open a PR today.  Glad to hear that the fix worked. :+1:  I'll close this issue once that PR is merged.

**Comment by rcurtin** [comment]
I opened #1599 to fix the issue in the codebase.  Once that is merged I will close this. :+1:

**Comment by rcurtin** [comment]
#1599 is merged, so this is closed now.  Thanks again for the report! :)
