### ISSUE TITLE
Linking errors when compiling with VS 2017

### ISSUE THREAD

**Issue by tharindu-mathew** [mlpack/mlpack#1597]
I'm getting errors such as this when compiling the release version.

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol wrapper_dsyrk_ referenced in function "public: static void __cdecl arma::syrk<1,0,0>::apply_blas_type<double,class arma::Mat<double> >(class arma::Mat<double> &,class arma::Mat<double> const &,double,double)" (??$apply_blas_type@NV?$Mat@N@arma@@@?$syrk@$00$0A@$0A@@arma@@SAXAEAV?$Mat@N@1@AEBV21@NN@Z)	mlpack_cf	<some_path>\dev\mlpack-3.0.4.tar\mlpack-3.0.4\mlpack-3.0.4\build\src\mlpack\methods\cf\cf_main.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol wrapper_dnrm2_ referenced in function "public: static double __cdecl arma::op_norm::vec_norm_2_direct_std<double>(class arma::Mat<double> const &)" (??$vec_norm_2_direct_std@N@op_norm@arma@@SANAEBV?$Mat@N@1@@Z)	mlpack_kernel_pca	<some_path>\dev\mlpack-3.0.4.tar\mlpack-3.0.4\mlpack-3.0.4\build\src\mlpack\methods\kernel_pca\kernel_pca_main.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol wrapper_dgemv_ referenced in function "public: static void __cdecl arma::gemv<1,1,0>::apply<class arma::Mat<double> >(double *,class arma::Mat<double> const &,double const *,double,double)" (??$apply@V?$Mat@N@arma@@@?$gemv@$00$00$0A@@arma@@SAXPEANAEBV?$Mat@N@1@PEBNNN@Z)	mlpack_nbc	<some_path>\dev\mlpack-3.0.4.tar\mlpack-3.0.4\mlpack-3.0.4\build\src\mlpack\methods\naive_bayes\nbc_main.obj	1

**Comment by rcurtin** [comment]
Hmm, these errors are linking errors against Armadillo---so for whatever reason, CMake has chosen to not link against Armadillo libraries directly.

How did you install and set up Armadillo on your system?

The Windows tutorial might have some good information about how to set up Armadillo so that it links correctly with mlpack: http://mlpack.org/docs/mlpack-3.0.4/doxygen/build_windows.html

**Comment by tharindu-mathew** [comment]
Thanks for the hint. The problem was I was using OpenBlas that I built myself without using mingw. After using mingw compatible pre-built binaries as mentioned in the above link it mostly completed. But, the mlpack-tests still will not built. I don't think that's a blocker though. I will close this issue.

**Comment by rcurtin** [comment]
Ok, great to hear you got it solved.  If you are having problems building the tests and the issue is mlpack, please feel free to open another issue and we can try and get it fixed. :)
