### ISSUE TITLE
Can't build , Window10 - x64 , CMake GUI client 

### ISSUE THREAD

**Issue by maifeeulasad** [mlpack/mlpack#1598]
Using CMake version: 3.2.2
Compiling dlib version: 19.16.99
CMake Error at dlib/cmake_utils/use_cpp_11.cmake:74 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "GNU"

  version 6.2.0.
Call Stack (most recent call first):
  dlib/CMakeLists.txt:857 (enable_cpp11_for_target)

C++11 activated.
Configuring incomplete, errors occurred!
See also "D:/softwares/dlib-master/build/CMakeFiles/CMakeOutput.log".
See also "D:/softwares/dlib-master/build/CMakeFiles/CMakeError.log".

**Comment by rcurtin** [comment]
Hi there,

This bug is not filed with the right project.  Please file it with dlib.
