### ISSUE TITLE
MLPack error C3546: '...': there are no parameter packs available to expand in visual studio 2017

### ISSUE THREAD

**Issue by Mirage1089** [mlpack/mlpack#1603]
I am following the tutorial to build mlpack from here
[https://www.mlpack.org/docs/mlpack-3.0.4/doxygen/build_windows.html](url)

I am using 
Windows 10
Visual Studio 2017 Version 15.9.4
mlpack-3.0.4
OpenBLAS.0.2.14.1
boost_1_66_0-msvc-14.1-64
armadillo-9.200.6 (The latest version)
and x64 configuration

I followed the instruction but while building, it can build the mlpack dll but only for one project "mlpack_test" it generated the error. The error says
"build\include\mlpack\core\cv\meta_info_extractor.hpp(51): error C3546: '...': there are no parameter packs available to expand"

As the mlpack library build so i tried to run the sample program given in the tutorial from here,
[https://www.mlpack.org/docs/mlpack-3.0.3/doxygen/sample_ml_app.html](url)

But here also it is giving me the same error
"build\include\mlpack\core\cv\meta_info_extractor.hpp(51): error C3546: '...': there are no parameter packs available to expand"

So, it can not compile the file meta_info_extractor.hpp, line number 51.

Can anyone help me to get rid of this problem?

If you need any information to understand this problem please feel free to ask me.

**Comment by rcurtin** [comment]
This looks like a bug in the Visual Studio compiler.  Can you try a different version of the compiler?  We have always had problems with Visual Studio although AppVeyor reports that mlpack 3.0.4 (and the git master branch) are able to compile without problems.

**Comment by Mirage1089** [comment]
Thank you for your reply. Currently i am using Visual Studio 2017 Version 15.9.4 (toolset v141). Do you mean I need to switch to Visual Studio 2017 Version 15.7 or earlier? Can you tell me the correct Version?

**Comment by Mirage1089** [comment]
Thanks a lot @rcurtin . I changed the visual studio version to 15.6.7 and now everything is running fine.
Thank you once again for saving me.

**Comment by rcurtin** [comment]
Great, glad that the idea was helpful.  At some point in the future if there is a new release of MSVC you could try upgrading and see if that works. :)

**Comment by Mirage1089** [comment]
@NacOJerk , yes I was able to compile and run mlpack with the VS version 15.6.7.

**Comment by NacOJerk** [comment]
@Mirage1089 I was able to actually run mlpack on the latest VS17 release

**Comment by Mirage1089** [comment]
@NacOJerk oh okay, congrats! I tried first with vs 15.9.4 but not able to...….then I had to switch previous version.
