### ISSUE TITLE
mlpack 3.0.4 does not need ARMADILLO_LIBRARY?

### ISSUE THREAD

**Issue by tharindu-mathew** [mlpack/mlpack#1604]
I'm following this guide - [http://mlpack.org/docs/mlpack-3.0.4/doxygen/build_windows.html](url)

I notice this warning come up when I set ARMADILLO_LIBRARY. Upon checking the CMake file I see ARMADILLO_LIBRARIES being set. But it seems ARAMADILLO_LIBRARY is never used?

So do we even need to build ARMADILLO?

CMake Warning:
  Manually-specified variables were not used by the project:

    ARMADILLO_LIBRARY

**Comment by rcurtin** [comment]
So, whether or not `ARMADILLO_LIBRARY` gets used depends on whether or not `ARMA_USE_WRAPPER` is enabled in the configuration file `armadillo_bits/config.hpp`.  If you take a look at `CMake/FindArmadillo.cmake`, you can see on line 94 we determine whether or not the wrapper library (`armadillo.dll` on Windows) is even needed.  Actually the wrapper library is just a convenience to avoid the headache of linking against BLAS, LAPACK, etc. directly.  Some setups may use the wrapper and others may not (I guess your setup does not).

So in your case, you are right that you don't even need to build the Armadillo library.  But this will probably not be the case for every system.

I hope this helps clarify things---let me know if I can explain any further. :)

**Comment by tharindu-mathew** [comment]
I see. That clarifies the issue, and there's no need of any fix.

**Comment by rcurtin** [comment]
:+1: Glad the explanation was helpful.
