### ISSUE TITLE
Linker problem with mlpack on Windows10 and VS17

### ISSUE THREAD

**Issue by NacOJerk** [mlpack/mlpack#1607]
So I built mlpack-3.0.4 on windows using this guide: https://keon.io/mlpack-on-windows/ and this one https://github.com/mlpack/mlpack/wiki/WindowsBuild
I built it on vs-2017 (Had to change some stuff in the guide so it will work with it (mostly the NuGet dependencies))
Now I am trying to compile some pre written code for an XOR gate (This code: http://www.mlpack.org/docs/mlpack-git/doxygen/cnetutorial.html)
And Im receving the follow linker errors:

1>Source.obj : error LNK2019: unresolved external symbol sdot_ referenced in function "double __cdecl arma::blas::dot<double>(unsigned __int64,double const *,double const *)" (??$dot@N@blas@arma@@YAN_KPEBN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol ddot_ referenced in function "double __cdecl arma::blas::dot<double>(unsigned __int64,double const *,double const *)" (??$dot@N@blas@arma@@YAN_KPEBN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol sgemv_ referenced in function "void __cdecl arma::blas::gemv<double>(char const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemv@N@blas@arma@@YAXPEBDPEBH1PEBN21212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol dgemv_ referenced in function "void __cdecl arma::blas::gemv<double>(char const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemv@N@blas@arma@@YAXPEBDPEBH1PEBN21212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol cgemv_ referenced in function "void __cdecl arma::blas::gemv<double>(char const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemv@N@blas@arma@@YAXPEBDPEBH1PEBN21212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol zgemv_ referenced in function "void __cdecl arma::blas::gemv<double>(char const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemv@N@blas@arma@@YAXPEBDPEBH1PEBN21212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol sgemm_ referenced in function "void __cdecl arma::blas::gemm<double>(char const *,char const *,int const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemm@N@blas@arma@@YAXPEBD0PEBH11PEBN21212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol dgemm_ referenced in function "void __cdecl arma::blas::gemm<double>(char const *,char const *,int const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemm@N@blas@arma@@YAXPEBD0PEBH11PEBN21212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol cgemm_ referenced in function "void __cdecl arma::blas::gemm<double>(char const *,char const *,int const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemm@N@blas@arma@@YAXPEBD0PEBH11PEBN21212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol zgemm_ referenced in function "void __cdecl arma::blas::gemm<double>(char const *,char const *,int const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemm@N@blas@arma@@YAXPEBD0PEBH11PEBN21212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol ssyrk_ referenced in function "void __cdecl arma::blas::syrk<double>(char const *,char const *,int const *,int const *,double const *,double const *,int const *,double const *,double *,int const *)" (??$syrk@N@blas@arma@@YAXPEBD0PEBH1PEBN212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol dsyrk_ referenced in function "void __cdecl arma::blas::syrk<double>(char const *,char const *,int const *,int const *,double const *,double const *,int const *,double const *,double *,int const *)" (??$syrk@N@blas@arma@@YAXPEBD0PEBH1PEBN212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol sgesv_ referenced in function "void __cdecl arma::lapack::gesv<double>(int *,int *,double *,int *,int *,double *,int *,int *)" (??$gesv@N@lapack@arma@@YAXPEAH0PEAN00100@Z)
1>Source.obj : error LNK2019: unresolved external symbol dgesv_ referenced in function "void __cdecl arma::lapack::gesv<double>(int *,int *,double *,int *,int *,double *,int *,int *)" (??$gesv@N@lapack@arma@@YAXPEAH0PEAN00100@Z)
1>Source.obj : error LNK2019: unresolved external symbol cgesv_ referenced in function "void __cdecl arma::lapack::gesv<double>(int *,int *,double *,int *,int *,double *,int *,int *)" (??$gesv@N@lapack@arma@@YAXPEAH0PEAN00100@Z)
1>Source.obj : error LNK2019: unresolved external symbol zgesv_ referenced in function "void __cdecl arma::lapack::gesv<double>(int *,int *,double *,int *,int *,double *,int *,int *)" (??$gesv@N@lapack@arma@@YAXPEAH0PEAN00100@Z)
1>Source.obj : error LNK2019: unresolved external symbol sposv_ referenced in function "void __cdecl arma::lapack::posv<double>(char *,int *,int *,double *,int *,double *,int *,int *)" (??$posv@N@lapack@arma@@YAXPEADPEAH1PEAN1211@Z)
1>Source.obj : error LNK2019: unresolved external symbol dposv_ referenced in function "void __cdecl arma::lapack::posv<double>(char *,int *,int *,double *,int *,double *,int *,int *)" (??$posv@N@lapack@arma@@YAXPEADPEAH1PEAN1211@Z)
1>Source.obj : error LNK2019: unresolved external symbol cposv_ referenced in function "void __cdecl arma::lapack::posv<double>(char *,int *,int *,double *,int *,double *,int *,int *)" (??$posv@N@lapack@arma@@YAXPEADPEAH1PEAN1211@Z)
1>Source.obj : error LNK2019: unresolved external symbol zposv_ referenced in function "void __cdecl arma::lapack::posv<double>(char *,int *,int *,double *,int *,double *,int *,int *)" (??$posv@N@lapack@arma@@YAXPEADPEAH1PEAN1211@Z)

Now when I use the test code given in the "mlpack on Windows" (https://github.com/mlpack/mlpack/wiki/WindowsBuild) guide everything is fine.

**Comment by rcurtin** [comment]
Is your code linking against mlpack, Armadillo, or LAPACK and BLAS?  You could look through the build configuration for when you compiled mlpack and make sure you are linking against the same set of libraries.

**Comment by NacOJerk** [comment]
I followed the guides so Im using that (like the exact configuration as the guides)

I just noticed that my mlpack-test failed and I saw a fix on the issues so Im gonna try and downgrade vs and try to compile everything again

**Comment by NacOJerk** [comment]
So when compiling everything in VS 15.6.7 the linking problem is gone.
But I have a new error

1>c:\projects\armadillo\include\armadillo_bits\arma_rng.hpp(444): error C2760: syntax error: unexpected token 'identifier', expected ';'

(I compiled everything now in VS 15.6.7 , the armadillo the mlpack and the code I copied from your site)
Any suggestions ?

**Comment by rcurtin** [comment]
That looks like just a syntax error somewhere in the code.  Are you sure the Armadillo sources you are using haven't been modified, and are you sure that your program is valid?  What have you tried for debugging?

(Glad the VS version change helped.)

**Comment by NacOJerk** [comment]
Well I can't debug that much because the program wont compile. I downloaded Armadillo from their own website. And the code should be valid because I just copied from an example on the mlpack website (So I can see that everything works)

**Comment by NacOJerk** [comment]
From what I read online this is another problem related to bugs in VS17 so I am just going to reinstall VS17 completely and try again

**Comment by NacOJerk** [comment]
This seems to still be a problem if anyone can find a fix it will really help me
1>c:\projects\armadillo\include\armadillo_bits\arma_rng.hpp(444): error C2760: syntax error: unexpected token 'identifier', expected ';'

**Comment by rcurtin** [comment]
> Are you sure the Armadillo sources you are using haven't been modified, and are you sure that your program is valid?

Please check the above, it could be helpful.  This is a syntax error, so even though it does not compile you should be able to trace down the compiler error message to figure out exactly where the syntax error is.  Unfortunately from here I cannot help too much, since I can't see the entirety of the code that you are working with.

**Comment by NacOJerk** [comment]
I have downloaded the Armadillo sources directly from their website (I downloaded it again in my second try) and you can view the entirety of the code because Im just using code directly from the mlpack website like I said right now even the validation code doesn't work

**Comment by rcurtin** [comment]
Have you tried to debug what the syntax error is at all?

**Comment by NacOJerk** [comment]
There isn't one thats the point the problem seems to be with VS

**Comment by NacOJerk** [comment]
Keeping this issue thread updated about my quest to run mlpack on windows
Using this guide:
https://www.mlpack.org/docs/mlpack-git/doxygen/build_windows.html
I was able to compile mlpack without having to downgrade the version of VS17 but now everything is compiled but I still have the linking errors like I had at the start of the thread

1>Source.obj : error LNK2019: unresolved external symbol sdot_ referenced in function "double __cdecl arma::blas::dot<double>(unsigned __int64,double const *,double const *)" (??$dot@N@blas@arma@@YAN_KPEBN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol ddot_ referenced in function "double __cdecl arma::blas::dot<double>(unsigned __int64,double const *,double const *)" (??$dot@N@blas@arma@@YAN_KPEBN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol sgemv_ referenced in function "void __cdecl arma::blas::gemv<double>(char const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemv@N@blas@arma@@YAXPEBDPEBH1PEBN21212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol dgemv_ referenced in function "void __cdecl arma::blas::gemv<double>(char const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemv@N@blas@arma@@YAXPEBDPEBH1PEBN21212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol cgemv_ referenced in function "void __cdecl arma::blas::gemv<double>(char const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemv@N@blas@arma@@YAXPEBDPEBH1PEBN21212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol zgemv_ referenced in function "void __cdecl arma::blas::gemv<double>(char const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemv@N@blas@arma@@YAXPEBDPEBH1PEBN21212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol sgemm_ referenced in function "void __cdecl arma::blas::gemm<double>(char const *,char const *,int const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemm@N@blas@arma@@YAXPEBD0PEBH11PEBN21212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol dgemm_ referenced in function "void __cdecl arma::blas::gemm<double>(char const *,char const *,int const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemm@N@blas@arma@@YAXPEBD0PEBH11PEBN21212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol cgemm_ referenced in function "void __cdecl arma::blas::gemm<double>(char const *,char const *,int const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemm@N@blas@arma@@YAXPEBD0PEBH11PEBN21212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol zgemm_ referenced in function "void __cdecl arma::blas::gemm<double>(char const *,char const *,int const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemm@N@blas@arma@@YAXPEBD0PEBH11PEBN21212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol ssyrk_ referenced in function "void __cdecl arma::blas::syrk<double>(char const *,char const *,int const *,int const *,double const *,double const *,int const *,double const *,double *,int const *)" (??$syrk@N@blas@arma@@YAXPEBD0PEBH1PEBN212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol dsyrk_ referenced in function "void __cdecl arma::blas::syrk<double>(char const *,char const *,int const *,int const *,double const *,double const *,int const *,double const *,double *,int const *)" (??$syrk@N@blas@arma@@YAXPEBD0PEBH1PEBN212PEAN1@Z)
1>Source.obj : error LNK2019: unresolved external symbol sgesv_ referenced in function "void __cdecl arma::lapack::gesv<double>(int *,int *,double *,int *,int *,double *,int *,int *)" (??$gesv@N@lapack@arma@@YAXPEAH0PEAN00100@Z)
1>Source.obj : error LNK2019: unresolved external symbol dgesv_ referenced in function "void __cdecl arma::lapack::gesv<double>(int *,int *,double *,int *,int *,double *,int *,int *)" (??$gesv@N@lapack@arma@@YAXPEAH0PEAN00100@Z)
1>Source.obj : error LNK2019: unresolved external symbol cgesv_ referenced in function "void __cdecl arma::lapack::gesv<double>(int *,int *,double *,int *,int *,double *,int *,int *)" (??$gesv@N@lapack@arma@@YAXPEAH0PEAN00100@Z)
1>Source.obj : error LNK2019: unresolved external symbol zgesv_ referenced in function "void __cdecl arma::lapack::gesv<double>(int *,int *,double *,int *,int *,double *,int *,int *)" (??$gesv@N@lapack@arma@@YAXPEAH0PEAN00100@Z)

**Comment by NacOJerk** [comment]
So I was able to solve this issue
The solution is to use this guides
https://github.com/mlpack/mlpack/wiki/WindowsBuild
https://www.mlpack.org/docs/mlpack-git/doxygen/build_windows.html

And also add libopenblas.dll.a file to additional dependencies like this issue says
https://github.com/mlpack/mlpack/issues/881

**Comment by rcurtin** [comment]
Would it have helped you if this tutorial: https://www.mlpack.org/docs/mlpack-git/doxygen/sample_ml_app.html had had the additional dependency on libopenblas.dll.a listed?  That is definitely a change that would be easy to make.
