### ISSUE TITLE
Is there a way to separate a layer out of a trained network

### ISSUE THREAD

**Issue by NacOJerk** [mlpack/mlpack#1613]
So Im using a code that is very similar to this code https://github.com/mlpack/models/blob/master/vae/vae_generate.cpp now I wish to separate the encoding layer out of the neural network once the network is trained. Is there a way to do it ? (I have looked in the API and I cant find any guide about it)

**Comment by NacOJerk** [comment]
Thx hopefully O can save the layer aswell

**Comment by rcurtin** [comment]
Yes, you could use the serialization to save the layer:

```
data::Save("encoder.bin", "encoder", *encoder);
```

and later you could load it again:

```
Sequential<> encoder;
data::Load("encoder.bin", "encoder", encoder);
```

and it would be ready for use.

**Comment by rcurtin** [comment]
I think this question is answered so I'll close the issue to try and keep the issues list manageable. :)  Feel free to reopen if needed. :+1:
