### ISSUE TITLE
Code duplication in EvaluateWithGradient

### ISSUE THREAD

**Issue by saksham189** [mlpack/mlpack#1619]
I was going through the codebase regarding RNN implementation. 

In this PR https://github.com/mlpack/mlpack/pull/1467/files, where `EvaluateWithGradient` was added I see that the call to `Evaluate` was [removed](https://github.com/mlpack/mlpack/pull/1467/files#diff-0e560b4ae5054e7fe4c029ec9eb0f1a7L264) and[ code added that is exactly the same as that in the `Evaluate` function. ](https://github.com/ShikharJ/mlpack/blob/0de8f083101465208d62c5d9fcdefda85369e3cb/src/mlpack/methods/ann/rnn_impl.hpp#L275-L326)
I think it should be possible to remove this duplicate code and simply call the Evaluate function as before and assign the result to a variable and return this result. 

`
performance = Evaluate(parameters, begin, batchSize, false);
`

Or am I missing something?

**Comment by zoq** [comment]
Nice catch, looks reasonable to me, always nice to remove unnecessary code.

**Comment by saksham189** [comment]
Okay, I will open a PR.

**Comment by ShikharJ** [comment]
@zoq @saksham189 The code looks duplicated, but it isn't because of the checks made in the initial part of `Evaluate` and `EvaluateWithGradient`. I had thought of reducing the duplication, but it would come at the cost of performance, which is more important.

**Comment by zoq** [comment]
It looks like it should be possible to call the Evaluate function inside the EvaluateWithGradient without adding up to the performance.

**Comment by ShikharJ** [comment]
Yeah, even I seemingly missed the checks, but luckily the rationale behind keeping the current changes came back to me.

**Comment by zoq** [comment]
Just to be sure the part we . are talking about is:

```

  ResetCells();

  double performance = 0;
  size_t responseSeq = 0;

  for (size_t seqNum = 0; seqNum < rho; ++seqNum)
  {
    // Wrap a matrix around our data to avoid a copy.
    arma::mat stepData(predictors.slice(seqNum).colptr(begin),
        predictors.n_rows, batchSize, false, true);
    Forward(std::move(stepData));
    if (!single)
    {
      responseSeq = seqNum;
    }

    if (!deterministic)
    {
      for (size_t l = 0; l < network.size(); ++l)
      {
        boost::apply_visitor(SaveOutputParameterVisitor(
            std::move(moduleOutputParameter)), network[l]);
      }
    }

    performance += outputLayer.Forward(std::move(boost::apply_visitor(
        outputParameterVisitor, network.back())),
        std::move(arma::mat(responses.slice(responseSeq).colptr(begin),
            responses.n_rows, batchSize, false, true)));
  }

  if (outputSize == 0)
  {
    outputSize = boost::apply_visitor(outputParameterVisitor,
        network.back()).n_elem / batchSize;
  }
```

in the ``EvaluateWithGradient`` function, which could be replaced by a call to ``Evaluate``.

**Comment by ShikharJ** [comment]
Yes, this part sure does borrow from `Evaluate`, but we also do a number of `if - else` checks before these, which would be redundant, and here will hit performance.

**Comment by saksham189** [comment]
Just read the conversation. But I think the checks performed in `Evaluate` and `EvaluateWithGradient` are exactly the same so, we could remove them from `EvaluateWithGradient`?

**Comment by zoq** [comment]
The difference I see is:

```c++
if (deterministic != this->deterministic)
  {
    this->deterministic = deterministic;
    ResetDeterministic();
  }
```

which calls the function only if the given ``deterministic`` is different from the current one. The ``Evaluate`` function only checks if ``deterministic`` is true (inference mode).

**Comment by zoq** [comment]
I agree with @ShikharJ the check is essential, and does add up to the performance if called each time. Perhaps there is a solution we could avoid that check or modify the check in the ``Evaluate`` method.

**Comment by ShikharJ** [comment]
@zoq `Evaluate` also has a mandatory check:
```
if (parameter.is_empty())
  {
    ResetParameters();
  }
```
which is given in `EvaluateWithGradient` as:
```
if (gradient.is_empty())
  {
    if (parameter.is_empty())
    {
      ResetParameters();
    }
    gradient = arma::zeros<arma::mat>(parameter.n_rows, parameter.n_cols);
  }
  else
  {
    gradient.zeros();
  }
```
and I don't think we can remove the `if (parameter.is_empty())` line from `EvaluateWithGradient` as IIRC the dimensions of `parameter` are initialized through `ResetParameters()`. So this would be a logical error in my opinion.

**Comment by saksham189** [comment]
I don't think I understand. If I call the `Evaluate` from `EvaluateWithGradient` then the `parameter` check will be performed inside `Evaluate` and `ResetParameters()` called accordingly. So, we could remove it from `EvaluateWithGradient`? @ShikharJ

**Comment by saksham189** [comment]
> I agree with @ShikharJ the check is essential, and does add up to the performance if called each time. Perhaps there is a solution we could avoid that check or modify the check in the Evaluate method.

If we call `Evaluate` will deterministic = false then the check should not run twice?

**Comment by zoq** [comment]
> I don't think I understand. If I call the Evaluate from EvaluateWithGradient then the parameter check will be performed inside Evaluate and ResetParameters() called accordingly. So, we could remove it from EvaluateWithGradient?

Agreed, in this case we just have to check for ``gradient.is_empty()`` in the ``EvaluateWithGradient`` function to initialize the gradient if necessary. I think @ShikharJ's point is that this introduces another if  expression that we have to check, one for ``gradient`` and another one for ``parameter``, which might be neglectable.
