### ISSUE TITLE
Cannot delete submodules when model parameter is true

### ISSUE THREAD

**Issue by akhandait** [mlpack/mlpack#1631]
In layers that can have multiple layer objects such as the `Sequential`, `AddMerge` and others, the destructor only deletes the submodules when the `model` parameter is `false`. 
So, if a new layer is added without maintaining a pointer like this:
```cpp
Sequential.Add<Linear<> >(in, out);
```
there is no way to free the memory of that `Linear` object.
For now, a solution has been provided in #1594 by adding a new `DeleteModules()` function in the `Sequential` object. However, it is not consistent with the rest of the codebase and a better solution in the future will be appreciated.
I think we will also need to look into the `Recurrent` object as the `Sequential` layer was designed for it.

**Comment by KimSangYeon-DGU** [comment]
I just checked the sequential.hpp code. 
The network variable is used based on vector container.
Is it the proper solution making the method to delete sub layer by index? If not, I will think about it more. 
I want to hear your opinion. :)

**Comment by shishir1310** [comment]
HI@akhandait , 
I would like to work on this issue.

**Comment by MuLx10** [comment]
Hello, @akhandait @rcurtin I want to take this issue.

**Comment by Hunting-Party10** [comment]
@akhandait @rcurtin 
Taking up this issue , I have convinced myself that the memory leak exists by running valgrind, which spat out a memory leak message. 

`==8872== LEAK SUMMARY:
==8872==    definitely lost: 1,264 bytes in 1 blocks
==8872==    indirectly lost: 880 bytes in 1 blocks
==8872==      possibly lost: 0 bytes in 0 blocks
==8872==    still reachable: 0 bytes in 0 blocks
==8872==         suppressed: 0 bytes in 0 blocks
`

Any pointers on how i should proceed ?
