### ISSUE TITLE
Ambiguous use of WeightSizeVisitor in recurrent

### ISSUE THREAD

**Issue by saksham189** [mlpack/mlpack#1639]
I am not sure about the use `WeightSizeVisitor` on this line in recurrent.
https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/ann/layer/recurrent_impl.hpp#L89-L92

`WeightSizeVisitor` returns the number of weights or is there a different use?

**Comment by zoq** [comment]
Nice catch, we should remove the lines.

**Comment by ShikharJ** [comment]
Fixed in #1645.
