### ISSUE TITLE
Why mlpack is running slow?

### ISSUE THREAD

**Issue by Mirage1089** [mlpack/mlpack#1643]
Hello,

I am trying to train the mnist dataset using Randomforest algorithm in mlpack. I am following the tutorial that is given in the mlpack website (https://www.mlpack.org/docs/mlpack-3.0.4/doxygen/sample_ml_app.html).

I am not understanding one thing why mlpack is taking very very long time. Like, in my program i am just loading mnist data and train the model. Last day, I waited almost 6 hours but the training process was not finished. Unfortunately i could not finish last day. Today again i have started my program.

Now, the problem is, I had implemented the same program using sklearn using python. Data loading, Training model (60,000 data) and testing the model with test data (10,000) took around 56 seconds.

My question is why mlpack is very slow? 

I am very new in ML area. 

If you have any question please ask me also to understand the problem.

Thank you.

**Comment by rcurtin** [comment]
Can you tell me how you have compiled the program?  I compiled the same on my system and I see fast performance for MNIST training and testing for a random forest.

Another note is that the example program there actually (effectively) trains 11 random forests---1 at the beginning at 10 for the `KFoldCV` part.  So I would expect it to take longer than the Python implementation that just learns one model.

**Comment by rcurtin** [comment]
Right, so this is not running `KFoldCV`---that's fine, but the runtime should be comparable to scikit-learn then since it is (roughly) the same operation.  How did you compile the code?  If it is so slow I am suspecting that you have debugging symbols on or that you have not enabled optimizations.

**Comment by Mirage1089** [comment]
I have compiled the code with visual studio (x64).  Basically I did not change any settings in the project except which are mandatory to run mlpack. So, no debugging symbols are turned on, But yes I did not enable optimization.

Although i did not enable the optimization it should not take this amount of time(7 hours and still running).

**Comment by rcurtin** [comment]
That entirely depends on the compiler.  mlpack makes use of a lot of advanced C++ template metaprogramming features, so it would be pretty important to enable optimization.  I have no idea how much of a difference optimization vs. no optimization will make on Visual Studio but I can say that with gcc (with optimizations), the code produced is quite fast.

**Comment by Mirage1089** [comment]
Okay, then I will definitely try this and let you know. Just one thing, 

Can you please tell me, did you run the Random Forest dataset for mnist full dataset in Visual Studio 2017 (using gcc compiler)  in Windows machine? And how long it took to train the mnist dataset for you? Maybe you do not remember the correct time, you can tell me the approximation time.

Thank you.

**Comment by rcurtin** [comment]
I don't use Visual Studio or Windows.  My simulations were run on Linux.  On my system (a reasonably modern desktop) the training took under a minute.  However, it is very hard to compare the two numbers since I don't know anything about your system; and the speeds given by different compilers can differ quite a lot too.

**Comment by Mirage1089** [comment]
The machine configuration is, core i7 6th generation, 3.4 Ghz, 32 GB memory and NVIDIA Quadro K2200 (2 GB memory).  I think enough to run :)
Basically i did not know that mlpack is targeted Linux user, otherwise i would not come here definitely. I was really convinced by reading its high performance. My work is to perform something in the real time that's why performance is very important.

**Comment by rcurtin** [comment]
Yes, that system is roughly as powerful as the one I am running on too.  mlpack should do fine for your task on Windows, but I am relatively convinced that you are seeing slow speeds because optimizations are not enabled by the compiler or some other part of your compilation configuration is not right.  In fact even in our AppVeyor builds we see roughly the same performance of the mlpack test suite as on Linux machines, so mlpack should be usable for real-time applications like you are trying to do.

**Comment by zoq** [comment]
I'll try to reproduce the issue on my windows machine, just to get some more results.

**Comment by Mirage1089** [comment]
Okay, yesterday I tried by turning on the optimization. I had selected the "Maximum Optimization (Favor Speed) (/O2)" option in the project property page.
Unfortunately, I did not see any change. After running around 80 mins, I stopped the program.

**Comment by zoq** [comment]
Looks like I can reproduce the issue on Windows and on Mac OS as well, I use https://pjreddie.com/media/files/mnist_train.csv for the test; @rcurtin if you have a chance can you test the dataset as well? Or maybe you already did.

**Comment by zoq** [comment]
Okay, just another update, the mac OS run finished in about 10 minutes with a single thread, which might be reasonable.

**Comment by zoq** [comment]
I get the same results if I build with ``-DUSE_OPENMP=OFF`` on windows as well, which should be the case anyway since MSVC doesn't support OpenMP > 2.0. So I guess one option is to use Clang on Windows.

**Comment by rcurtin** [comment]
I double-checked with the CSV you used @zoq and saw roughly the same things.  With OpenMP using 8 cores the whole process takes 30 minutes on my system (that includes RF training and k-fold cross-validation).  I also tested with `mlpack_random_forest`, just to build one RF, and that takes roughly a minute if `num_trees` is 10 and less than 5 if `num_trees` is 50.

**Comment by Mirage1089** [comment]
@zoq , yes, Visual Studio 2017 supports only OpenMP 2. Basically from the beginning I enabled openmp in visual studio. It seems the mlpack uses OpenMP 3.1 or upper version. This might be the problem. So, in windows did you test it with Clang or other compiler?

**Comment by zoq** [comment]
I used MSVC and forced to use a single thread only (``set OMP_NUM_THREADS=1``). Will test clang in the next days.

> With OpenMP using 8 cores the whole process takes 30 minutes on my system (that includes RF training and k-fold cross-validation).

So I wonder if scikit does something different here, since 56 seconds for the same model (@Mirage1089 did you use the same settings?) is way faster.

**Comment by rcurtin** [comment]
I don't think it's a fair comparison, since I don't believe scikit was doing k-fold cross-validation and I'm not sure all the parameters were the same.

**Comment by zoq** [comment]
Right, so perhaps @Mirage1089 can share the script he used and we can at least compare the settings.

**Comment by Mirage1089** [comment]
@zoq the python script,

import time
import numpy as np
import pandas as pd
import pickle
import matplotlib.pyplot as pt
from sklearn.ensemble import RandomForestClassifier
from sklearn.externals import joblib

start_time = time.time()
training_data = pd.read_csv("data/mnist_train.csv").values
rf = RandomForestClassifier(n_estimators=100)

xtrain = training_data[:,1:]
ytrain = training_data[:,0]

#Train the model
rf.fit(xtrain,ytrain)
print("Data Load and Training Time----- %s seconds-----" % (time.time() - start_time))

Its the same code I mentioned earlier in mlpack. Nothing fancy.

The thing is I could not finish the training after even 13 hours and I could not finish the training even for 1 time. One more thing I want to mention, I have tried with the same dataset and the same code in OpenCV. The training took around 3 hours 50 mins.

**Comment by jsxs0** [comment]
Trying changing the environment of the code. I tried working on it with Windows but it didn't show anything wrong, either.

**Comment by Mirage1089** [comment]
@jsxs0 , Can you please tell a bit more that what did you try and in which environment and compiler did you use in windows? It will be helpful if you write in more details.
