### ISSUE TITLE
Bound terminal state of mountain_car environment to goal position

### ISSUE THREAD

**Issue by manish7294** [mlpack/mlpack#1647]
Currently terminal state of mountain car reinforcement learning environment (`mountain_car.hpp`) is bounded by the `max_position`. Though using `goal_position` is slightly better option in-place of `max_position`, as it allows us to move past the terminal state which is not possible while using `max_position` as terminal state.

In short, the aim is to introduce a goal_position parameter in mountain_car environment that will decide the terminal state.
i.e. the terminal state should be determined somewhat similar to
```
bool IsTerminal(const State& state) const
  {
    return bool(state.Position() >= positionGoal);
  }
```

For reference see - continuous mountain car environment (`continuous_mountain_car.hpp`)

**Comment by KimSangYeon-DGU** [comment]
@manish7294 Is there person who was assigned?? if not, I would like to try it.

**Comment by KimSangYeon-DGU** [comment]
Please tell me, if there's anything I can do to help. :)

**Comment by manish7294** [comment]
@KimSangYeon-DGU If you would like, please feel free to take this up.

**Comment by KimSangYeon-DGU** [comment]
@manish7294 Okay, I'm working now. :)

**Comment by manish7294** [comment]
> Hi, msnish7294. I edited the code, but I want to make a performance comparison table about before & after algorithms. So, how can I test this code??

As @zoq mentioned in https://github.com/mlpack/mlpack/pull/1649#issuecomment-453087922, a Q learning test could be a good check.

> The OpenAI gym is officially provided for Python version.
> Also, their [HTTP API](https://github.com/openai/gym-http-api) doesn't work.
> 
> The mlpack also provides [TCP API](https://github.com/zoq/gym_tcp_api), and I checked the program works correctly a few weeks ago, but it doesn't work now. I think the OpenAPI gym's interface has changed.

@zoq could you please help out here.

**Comment by KimSangYeon-DGU** [comment]
Thanks!! I'll try it. :)

**Comment by zoq** [comment]
> > The mlpack also provides TCP API, and I checked the program works correctly a few weeks ago, but it doesn't work now. I think the OpenAPI gym's interface has changed.

> 
> @zoq could you please help out here.

Have to take a closer look into the issue, but I think for now we can just go with the C++ test.

**Comment by KimSangYeon-DGU** [comment]
> Have to take a closer look into the issue, but I think for now we can just go with the C++ test.
@zoq Agreed!! :)

**Comment by manish7294** [comment]
I'm going to close this issue as it has been dealt with in #1649.
