### ISSUE TITLE
Accelerate HMM `Forward()` and `Backward()` by precomputing probabilities

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1660]
This is a nice issue based on #1499 that could result in a pretty large speedup for mlpack's HMM implementation.  Basically, to notice the problem, see that in `src/mlpack/methods/hmm/hmm_impl.hpp`, we have these methods `Forward()` and `Backward()` that contain loops that individually call `LogProbability()` over and over again for different data points and different emission states.

Ideally we want to use the proposed solution in #1499 where we only do that once.  But this turns out to add a little bit of complexity, because we have to implement some extra infrastructure to make this as fast as possible.

Some reasonable steps to approach the problem are below.  This is a good starter task for someone looking to get involved in contributing to mlpack, and is best done by someone who is willing to spend some time profiling and figuring out where the bottlenecks are, because the idea I present below may not be the best road to acceleration (but I think it is a good start).

1. We should modify `HMM::Forward()` and `HMM::Backward()` to take in also a parameter `const arma::mat& logProbs`, which will be a matrix with `transition.n_cols` rows and `dataSeq.n_cols` columns.  `logProbs(s, i)`, then, will correspond to `emission[s].LogProbability(dataSeq.unsafe_col(i))`.  We also need to modify the code before everywhere `Forward()` is called in order to compute that matrix `logProbs`.

2. But... we should not call `LogProbability()` individually for every single point.  In most cases it will be faster to compute log-probabilities for many points at once.  Therefore, we should implement the function `void LogProbability(const arma::mat& observations, arma::vec& logProbabilities)` in each class in `src/mlpack/core/dists/`, and add tests in `src/mlpack/tests/distribution_test.cpp` that when we call `LogProbability()`, it gives the same result as if we called `LogProbability()` sequentially with each point.  *(This is the majority of the work in this ticket.  How much speedup you get overall will depend on how fast you can make `LogProbability()`.)*

3. Run `mlpack_hmm_train` before and after your changes (make sure the random seed is the same!) and check to see how much speedup you get.  Consider running `gprof` or some other profiler to see if you can speed it up even more!  But with just the changes above, I would still expect fairly significant speedup.

**Comment by amet-vikram13** [comment]
Hey @rcurtin...I am new here (Hello!)..I have pretty much understand the problem and  i am looking into it...

**Comment by amet-vikram13** [comment]
Hey @rcurtin ..can you tell me how to run your tests once you made changes in the file of the method....basically i want to run mlpack_hmm_train..

**Comment by mirraaj** [comment]
@rcurtin Your point is correct that we should add the feature to compute log probabilities at one time.

Just a quick check, Are you looking something like this (https://github.com/mlpack/mlpack/blob/fc8d296f9c42837fca232e67a4d0e40bed93aed6/src/mlpack/core/dists/gaussian_distribution.hpp#L175-L194). Here I think, log probabilities are being calculated all at once.

**Comment by rcurtin** [comment]
@amet-vikram13: I saw your question was answered earlier in IRC.  `make mlpack_hmm_train` and `make mlpack_test` should be helpful.

@mirraaj: Yeah, exactly like what you pointed out.  But that function doesn't exist for every distribution type.  I've updated the description---we should call it `LogProbability()` just as it is for `GaussianDistribution`.

**Comment by mirraaj** [comment]
@rcurtin , I think we should go with ```LogProbability``` instead of ```LogProbabilities```. I think I can complete this work before coming weekend. Let me see if I need any help.

**Comment by rcurtin** [comment]
Hey @mirraaj, with #1679 and #1726 now done, I think that you are ready to make the changes to the HMM code.  Would you like to do that and see how much faster it is? :)

**Comment by mirraaj** [comment]
Hello @rcurtin ,

I would love to accelerate HMM implementation on MLPACK. However, I haven't been through those codes yet. It would be great if you elaborate on your idea you intend for HMM. Also, please let me know which area should I tackle in the beginning. 

Thanks

**Comment by rcurtin** [comment]
Basically if you take a look at the existing HMM implementation in `HMM::Forward()` and `HMM::Backward()`, you will see where you can use the new batch `LogProbability()` functions.  When you use those instead of the single-point ones, then it should accelerate HMM training significantly.  You can test by training some HMMs (see the tests in `src/mlpack/tests/main_tests/hmm_train_test.cpp` for an idea of what parameters to give, and then you can adapt those parameters so you can run from the command-line, and then if you run with `-v`, it will show you how long it takes).  You can do the timing both before and after your changes, and you'll be able to see the amount of speedup. :+1:

**Comment by mirraaj** [comment]
@rcurtin Are we trying to tackle this? https://github.com/mlpack/mlpack/blob/5e854c665e95103f1dd84c56de68e90b81e9a9c1/src/mlpack/methods/hmm/hmm_impl.hpp#L578-L600

**Comment by rcurtin** [comment]
@mirraaj right, exactly, now we can call `LogProbability()` in batch instead of on each individual point, and that should be much faster. :+1:

**Comment by mirraaj** [comment]
@rcurtin I have applied the same concept for the PR #1774. Thanks

**Comment by abernauer** [comment]
@rcurtin  Assuming this issue is not resolved given the closed pull request I would like to finish the remaining work, so this gets implemented in the next release.

**Comment by rcurtin** [comment]
@abernauer yeah, if it is something you'd like to do it would be great to get a fix in.  Let me know if I can help out through the process.  :+1:

**Comment by abernauer** [comment]
Yeah I will let you know if I have any issues once I get started on the fix 👍. Need to rebuild mlpack on a vm or lower resource linux server first, so going to do that.

**Comment by aghinsa** [comment]
Hey,
Is this issue still open?If yes,I'd like to start contributing towards this.Any starting points?

**Comment by Hunting-Party10** [comment]
Hi whats the progress on this issue ? I would like to work on it if that's possible?

**Comment by rcurtin** [comment]
Hey @Hunting-Party10, @jeffin143 has put together a nice PR in #2031, but it didn't speed things up as expected.  It's waiting on me. :(  However, if you want, you could try checking out that code, running it through a profiler, and seeing if you can identify why the changes aren't producing speedup.  That's what I've been meaning to do but I just haven't had the time.

**Comment by Hunting-Party10** [comment]
Alright @rcurtin will try to look it through its been almost 7 months since last update of this issue,so wasnt sure if this was done.
