### ISSUE TITLE
`GradientAtrousConvolutionTest` and `GradientTransposedConvolutionTest` fail often; is `Gradient()` implemented right?

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1661]
I noticed when working on #1640 that I had to significantly adjust the tolerance of `ANNLayerTest/GradientAtrousConvolutionTest` in order to get it to reliably pass.  Often the difference could be quite large, even larger than 0.1.  I am concerned that this might be an implementation bug.

So, I think that `src/mlpack/methods/ann/layer/atrous_convolution_impl.hpp` needs to be reviewed to ensure that both the implementations of `Evaluate()` and `Gradient()` are correct.

@zoq, @ShikharJ: could I be wrong about this mattering?  If a larger tolerance is okay with both of you and you are both happy with the implementation, we can close this issue without doing anything.

Relevant: #1640 #1777

**Comment by ShikharJ** [comment]
@rcurtin Hmm, the code was merged in a hurry as far as I remember, though I don't think I suspect its correctness. I'll take a thorough look and reach back.

**Comment by saksham189** [comment]
This is quite strange but adding an `IdentityLayer<>` before the convolution layer in the test seems to reduce the failures and works with a tolerance of `1e-2`

**Comment by saksham189** [comment]
I tried debugging this a bit more. Every-time the test fails the `inputTemp` variable inside the `AtrousConvolution` seems to be changed/corrupted. 
The input to the NN is `arma::linspace<arma::colvec>(0, 35, 36)`.
After printing the `inputTemp` variable inside the `Forward` method I get the output below which is what I would expect. 
```
         0    6.0000   12.0000   18.0000   24.0000   30.0000
    1.0000    7.0000   13.0000   19.0000   25.0000   31.0000
    2.0000    8.0000   14.0000   20.0000   26.0000   32.0000
    3.0000    9.0000   15.0000   21.0000   27.0000   33.0000
    4.0000   10.0000   16.0000   22.0000   28.0000   34.0000
    5.0000   11.0000   17.0000   23.0000   29.0000   35.0000
```
Whenever the test fails the `inputTemp` variable inside the `Gradient()` method `inputTemp` has some corrupted values as such below:
```
  3.1050e+169   6.0000e+00   1.2000e+01   1.8000e+01   2.4000e+01   3.0000e+01
  9.8216e+252   7.0000e+00   1.3000e+01   1.9000e+01   2.5000e+01   3.1000e+01
  1.6920e+190   8.0000e+00   1.4000e+01   2.0000e+01   2.6000e+01   3.2000e+01
   3.0000e+00   9.0000e+00   1.5000e+01   2.1000e+01   2.7000e+01   3.3000e+01
  -2.3158e+77   1.0000e+01   1.6000e+01   2.2000e+01   2.8000e+01   3.4000e+01
  -2.3158e+77   1.1000e+01   1.7000e+01   2.3000e+01   2.9000e+01  2.2946e-308
``` 
I am not sure why this is happening. When the test does not fail the values are alright.
