### ISSUE TITLE
commands to install mlpack dependencies in ubuntu and debian

### ISSUE THREAD

**Issue by durgesh21** [mlpack/mlpack#1665]
the commands to install mlpack dependencies is not working without "sudo"

**Comment by rcurtin** [comment]
The `#` character for the prompt indicates that it is a command to be run as root; that can be via sudo or a root shell or any other way.  However, I am not opposed to changing it to `$ sudo apt-get install ...` since that is what the other documentation does.  Would you like to open a PR for that?
