### ISSUE TITLE
ISO C++ study group on Machine Learning

### ISSUE THREAD

**Issue by inglada** [mlpack/mlpack#1671]
A study group on machine learning has been created by the ISO C++
committee. There are interesting discussions about the features and
tools needed for efficiently implement ML algorithms in C++ and I am
sure that mlpack developers will have very interesting things to say.

The goals of the SG are outlined in this paper http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1360r0.pdf

There is a collaborative document here
https://groups.google.com/a/isocpp.org/forum/?fromgroups#!topic/sg19/5A7YeItAXbM
to which you may contribute.

**Comment by rcurtin** [comment]
Hi @inglada,

Thanks for the information.  I think that my thoughts are roughly the same as yours in the Google Groups comment you left---I'm not clear on exactly what the group is aiming to do.  It would definitely be nicer to have better interoperability between different machine learning toolkits, but I'm not sure that native language support is lacking for this anywhere.  We've already built everything we need on top of the language with libraries...

Is the SG actively looking for people to participate, or people to interview or something?

**Comment by inglada** [comment]
@rcurtin AFAIK the SG is open to anyone willing to contribute, so do not hesitate to join the mailling list and share your thoughts.

Furthermore, I think that, if authors of different C++ ML toolkits could discuss together, that would be great to mitigate the drawbacks of fragmentation we suffer from today.

**Comment by rcurtin** [comment]
Hehe, I don't think I have the time to join the group, but it's good to know it exists. :)  I see the Shogun developers regularly, but we haven't had too many discussions or efforts to reduce fragmentation.  I suspect that we all have different goals in mind in our development, and this leads us all to different solutions (hence the fragmentation).  It's not great for the user, to be sure, but I think it's something of an intractable problem. :(
