### ISSUE TITLE
Building mlpack using the Intel Compiler

### ISSUE THREAD

**Issue by chrisvwn** [mlpack/mlpack#1688]
I am trying to build mlpack using the intel compiler. However, I am getting an error to the effect:

```
mlpack-2.2.2/src/mlpack/methods/kmeans/dual_tree_kmeans_impl.hpp(113): internal error: null pointer
        NNSTreeType> nns(std::move(*centroidTree));
```
Is the intel compiler not supported as seems to be suggested at [https://mailman.cc.gatech.edu/pipermail/mlpack-git/2015-June/006789.html](https://mailman.cc.gatech.edu/pipermail/mlpack-git/2015-June/006789.html)?

Screenshot for reference:
![screenshot from 2019-01-22 21-53-35](https://user-images.githubusercontent.com/6387770/51558360-51529000-1e90-11e9-84b8-3d269096244e.png)

**Comment by rcurtin** [comment]
It looks like you're trying to use mlpack-2.2.2... have you tried a newer mlpack version?  The error may not be present in newer code.

We've done our best to support the Intel compiler but at least at the time of the message that you found, it appeared that the Intel compiler crashed while trying to compile mlpack.  It's been three and a half years since I tried with the Intel compiler, so I'm not sure of whether it will work now; but the code is valid C++ and should (ideally) compile fine on any compiler...

**Comment by chrisvwn** [comment]
I have just tried it with mlpack 3.0.4 and got the same error.

**Comment by rcurtin** [comment]
Ok---thanks for the information.  Honestly I believe this is a bug with the Intel compiler and so the right thing to do is probably file an issue with them.  If you can produce a workaround, I'd be happy to incorporate it into the codebase, but I don't have a copy of the Intel compiler to try and figure something out with, unfortunately.

**Comment by zoq** [comment]
I'm currently on a compiler journey, so I might be able to take a look into the issue over the next days probably over the weekend; unless somebody else likes to. But as Ryan already pointed out this is probably a compiler bug, in which case we have to find a workaround. Btw. not sure the kmeans code is the only place that triggers the error, if that's the case and you don't need the kmeans code it might be possible to build mlpack without it.

**Comment by chrisvwn** [comment]
@zoq We would be delighted if you could get the time and dig around on our workstation. My colleague even reminded me that we are not restricted to a particular intel compiler version after all so you have free rein. Come to think of it, yes, it has built a few other modules so kmeans might be the only culprit. However, we are happy to use this opportunity to see if the full mlpack build for intel can be fixed. Will contact you via email for creds.
