### ISSUE TITLE
Help regarding contribution

### ISSUE THREAD

**Issue by awesumrit** [mlpack/mlpack#1690]
Hi! I am new here. Can somebody please guide me how can I start contributing, which issues to take and which suborganization shall I work for. I have installed mlpack but I am confused which tutorials to see first and how to basically start contributing. Any help would be greatly appreciated.

**Comment by rcurtin** [comment]
Hi, have you seen http://www.mlpack.org/involved.html?  That has a pretty detailed description of how one might get involved.

**Comment by awesumrit** [comment]
Thanks. I was just confused regarding where to start and what issue to take.
