### ISSUE TITLE
Will your latest library run on visual studio 2012?

### ISSUE THREAD

**Issue by coderboyisongithub** [mlpack/mlpack#1693]
I have visual studio 2012 and I am using your latest release 3.4.0,Its tutorial says i require visual studio 2017,So can i run do this?

**Comment by rcurtin** [comment]
Have you tried it?  Since you have both mlpack and Visual Studio 2012, you're the most qualified to answer the question.  Older versions of mlpack caused 'internal compiler error's though, so I'd say it's unlikely to work.
