### ISSUE TITLE
Segmentation Fault: preprocess_split

### ISSUE THREAD

**Issue by bhavya01** [mlpack/mlpack#1694]
I am getting a segmentation fault when I run this in python3.5

```
df = pd.read_csv('covertype-small.csv')
labels = df['label']
dataset = df.drop('label', 1)
output = mlpack.preprocess_split(input=dataset, input_labels=labels, test_ratio=0.1)
```

but on removing input_labels, it works fine.

`output = mlpack.preprocess_split(input=dataset, test_ratio=0.1)`

I built mlpack-3.0.4 from source on Ubuntu 16.04
Armadillo version: 6.5

Please suggest how to find out the issue.

**Comment by KimSangYeon-DGU** [comment]
Hi @bhavya01 .
I think it will work.
```
df = pd.read_csv('covertype-small.csv')
labels = pd.DataFrame(data=df['label'])
dataset = df.drop('label', 1)
output = mlpack.preprocess_split(input=dataset, input_labels=labels, test_ratio=0.1)
```

**Comment by rcurtin** [comment]
@KimSangYeon-DGU: nice workaround, thanks! :+1:

@bhavya01: I can reproduce this also, and I agree that it is a bug.  But can I ask why you did not use the 'bug report' issue template?  It makes it a lot easier for us...

If anyone wants to look into this (it may be a while until I can get to it), I am willing to bet that the issue will be in the `to_matrix()` function found in `src/mlpack/bindings/python/mlpack/matrix_utils.py`.  In the code snippet, `labels` is of type `pandas.core.series.Series`, so I guess that we are not handling this case correctly.

**Comment by bhavya01** [comment]
Sorry, I wasn't sure if this was a bug or a problem in my installation. I would like to look into it.

**Comment by souvik3333** [comment]
Hi, I am new here. Can I work on this?

**Comment by mrkeremyilmaz** [comment]
While I was testing out the [simple quickstart example](http://mlpack.org/docs/mlpack-3.0.4/doxygen/python_quickstart.html), I got a segmentation fault. Moreover, neither the given workaround nor the removal of _input_labels_ worked for me.

I am on Ubuntu 18.04 and I installed mlpack using `pip install mlpack3`.

I will check the `to_matrix()` function as soon as I can to solve the problem.

**Comment by halwai** [comment]
@mrkeremyilmaz refer [#1772](https://github.com/mlpack/mlpack/issues/1772#issuecomment-475972722)

**Comment by phantomcoder1996** [comment]
May be I can work on this issue

**Comment by rcurtin** [comment]
I tried to reproduce this with the current master branch and I am unable to.  I think the issue has been solved.  If anyone's still encountering it, feel free to reopen (or file a new issue). :+1:
