### ISSUE TITLE
Cannot use saved network outputs rnn

### ISSUE THREAD

**Issue by saksham189** [mlpack/mlpack#1695]
In `rnn` class we can call `Evaluate` with `deterministic = false` which saves the output parameters from each layer of rnn. 
https://github.com/mlpack/mlpack/blob/7d448192cc045555e36ee76a2dca51ce9637ac66/src/mlpack/methods/ann/rnn_impl.hpp#L217-L224

But I don't think there is any way to use these saved parameters for training the rnn. 

- `EvaluateWithGradient` will save its own parameters during forward pass. 
- `Forward()`, `Gradient()`, `Backward()` are all private methods.

Please let me know if I am missing something. @zoq

**Comment by mirraaj** [comment]
@saksham189 I am trying to understand the issue. I believe we are saving the parameters in the ```Evaluate``` function. Please elaborate on what is meant by, ```I don't think there is any way to use these saved parameters for training the rnn.``` I would like to try to answer the question as per my knowledge.

**Comment by saksham189** [comment]
> Please elaborate on what is meant by, `I don't think there is any way to use these saved parameters for training the rnn.`
These parameters are saved but it is not possible to use these for training. @mirraaj 
@zoq Please let me know what you think.

**Comment by saksham189** [comment]
@zoq Please let me know what you think. 
One easy solution would be to remove the overload of `Evaluate()` that allows to save the parameters.

**Comment by zoq** [comment]
Just to be clear you are talking about the network weights? In this case, you could use the serialization method: https://www.mlpack.org/docs/mlpack-git/doxygen/anntutorial.html#model_saving_loading_anntut or:

```c++
// Get network weights.
arma::mat weights = model.Parameters();

// Set network weights.
model.Parameters() = weights;
model.ResetParameters();
```

Let me know what you think.

**Comment by saksham189** [comment]
Sorry, I think I used the wrong terminology. I meant to say the network outputs (rather than parameters) for each layer that are stored in the `moduleOutputParameter` vector in the `Evaluate` method.

**Comment by saksham189** [comment]
@zoq @ShikharJ I do think this is a valid issue. There is no way to use the output parameters stored in `moduleOutputParameter` vector from `Evaluate` method for training.

**Comment by zoq** [comment]
I see, do you think looping over all layer of the model could work to get the output? Something like:

```c++
for (size_t = 0; i < model.Model().size(); i++)
{
	model.Model()[i].OutputParameter();
}
```

**Comment by saksham189** [comment]
> do you think looping over all layer of the model could work to get the output?

I don't think I understand. I was just thinking about removing these lines:
https://github.com/mlpack/mlpack/blob/7d448192cc045555e36ee76a2dca51ce9637ac66/src/mlpack/methods/ann/rnn_impl.hpp#L217-L224

**Comment by zoq** [comment]
Ahh, I was thinking you actually like to access the output parameter, but you are right, they are never used and can be removed, might give us some performance improvements as well.
