### ISSUE TITLE
Implementation of Siamese Networks and related Loss function

### ISSUE THREAD

**Issue by shardulparab97** [mlpack/mlpack#1699]
@rcurtin  @zoq I am really interested in contributing to MLPack. I feel that MLPack can grow further in the computer vision domain too.

However being new to the codebase, I wanted to begin with the implementation of the following:
- [ ] Contrastive Loss
- [ ] A basic Siamese Network module 
- [ ] Triplet Loss

Please let me know your thoughts about the same and any other ideas in computer vision/image domain which can be worked upon. Thanks a lot! :smile:

**Comment by zoq** [comment]
Hello, glad you find the project interesting. Contributions are always welcome, and I think the computer vision sector could be a great fit for mlpack.

Personally I like the idea to start with a loss function to get familiar with the codebase, so as you suggested Triplet /Contrastive Loss might be a good candidate. About a basic Siamese Network module, not sure there is need to write an extra module/layer do you think it would be possible to implement the module with the existing codebase and to implement an example similar to what was done here: https://github.com/mlpack/models?

**Comment by shardulparab97** [comment]
Thank you @zoq. I will begin with the loss functions and then go towards implementing the Siamese Network as per your suggestion. :smiley:

**Comment by zoq** [comment]
Sounds great, let me know if I should clarify anything.

**Comment by shardulparab97** [comment]
@zoq I have opened Pull Request for the implementation here: #1704  
Please let me know what you think :)

**Comment by zoq** [comment]
Great, will take a look at the PR in the next days.

**Comment by Hemal-Mamtora** [comment]
Hello ! @zoq @shardulparab97
I am also interested in developing the Siamese network. May I assist you in developing it ?
I would like to start with the triplet loss function 
Please let me know. Thanks.

**Comment by zoq** [comment]
I'll let @shardulparab97 answer this one.

**Comment by shardulparab97** [comment]
Hi @Hemal-Mamtora  sorry for the late reply, was caught up with exams.
Yes please go ahead with the triplet loss function, it will only make the process faster! :smiley:  
Let me know if you need any help.
At the same time, we could work on the implementation of the Siamese Model.

**Comment by Hemal-Mamtora** [comment]
Hi @shardulparab97 , I'll start right away on the triplet loss function.
Meanwhile if you have any reference material like technical papers about the topic(Siamese, triplet) please forward the link
This will help us stay on the same page and we could implement it faster.

**Comment by johnsoncarl** [comment]
@Hemal-Mamtora @shardulparab97 , I hope none of you guys is working on the lossless Losses for the siamese networks.
I have begun with it. Just to make sure in case anyone is working.
I want to work on the same.

**Comment by johnsoncarl** [comment]
Hey @zoq , I couldn't see any activities in this lately.
What is the current status for this?

**Comment by zoq** [comment]
@johnsoncarl Are you talking about Contrastive Loss or the Triplet Loss? There is an open PR for the Triplet Loss (https://github.com/mlpack/mlpack/pull/1744) which lacks a test.

**Comment by johnsoncarl** [comment]
Hey @zoq , 
I'm talking about adding "lossless triplet loss".

**Comment by zoq** [comment]
So, #1744 should be helpful, feel free to build on the open PR.

**Comment by Hemal-Mamtora** [comment]
I've created a new PR #1868 for triplet loss function implementation following a mistake in #1744  which is now closed.
