### ISSUE TITLE
Is there a way to use Mat<float> instead of Mat<double>

### ISSUE THREAD

**Issue by NacOJerk** [mlpack/mlpack#1712]
This is sort of a follow up question for this issue https://github.com/mlpack/mlpack/issues/1677
Now I have seen this answer:
https://github.com/mlpack/mlpack/issues/1062#issuecomment-316462704

So I tried doing the following thing:
Source.cpp (https://pastebin.com/QUZd8JaN)
vae_utils.cpp (https://pastebin.com/28RL0Rsp)

And I still get the following errors:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'void mlpack::ann::FFN<mlpack::ann::ReconstructionLoss<arma::fmat,arma::fmat,mlpack::ann::BernoulliDistribution<arma::fmat>>,mlpack::ann::HeInitialization>::Add(boost::variant<mlpack::ann::Add<arma::mat,arma::mat> *,mlpack::ann::AddMerge<arma::mat,arma::mat> *,mlpack::ann::AtrousConvolution<mlpack::ann::NaiveConvolution<mlpack::ann::ValidConvolution>,mlpack::ann::NaiveConvolution<mlpack::ann::FullConvolution>,mlpack::ann::NaiveConvolution<mlpack::ann::ValidConvolution>,arma::mat,arma::mat> *,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> *,mlpack::ann::BaseLayer<mlpack::ann::IdentityFunction,arma::mat,arma::mat> *,mlpack::ann::BaseLayer<mlpack::ann::TanhFunction,arma::mat,arma::mat> *,mlpack::ann::BaseLayer<mlpack::ann::RectifierFunction,arma::mat,arma::mat> *,mlpack::ann::BaseLayer<mlpack::ann::SoftplusFunction,arma::mat,arma::mat> *,mlpack::ann::BatchNorm<arma::mat,arma::mat> *,mlpack::ann::BilinearInterpolation<arma::mat,arma::mat> *,mlpack::ann::Concat<arma::mat,arma::mat> *,mlpack::ann::Concatenate<arma::mat,arma::mat> *,mlpack::ann::ConcatPerformance<mlpack::ann::NegativeLogLikelihood<arma::mat,arma::mat>,arma::mat,arma::mat> *,mlpack::ann::Constant<arma::mat,arma::mat> *,mlpack::ann::Convolution<mlpack::ann::NaiveConvolution<mlpack::ann::ValidConvolution>,mlpack::ann::NaiveConvolution<mlpack::ann::FullConvolution>,mlpack::ann::NaiveConvolution<mlpack::ann::ValidConvolution>,arma::mat,arma::mat> *,mlpack::ann::TransposedConvolution<mlpack::ann::NaiveConvolution<mlpack::ann::ValidConvolution>,mlpack::ann::NaiveConvolution<mlpack::ann::FullConvolution>,mlpack::ann::NaiveConvolution<mlpack::ann::ValidConvolution>,arma::mat,arma::mat> *,mlpack::ann::DropConnect<arma::mat,arma::mat> *,mlpack::ann::Dropout<arma::mat,arma::mat> *,mlpack::ann::AlphaDropout<arma::mat,arma::mat> *,mlpack::ann::ELU<arma::mat,arma::mat> *,mlpack::ann::FlexibleReLU<arma::mat,arma::mat> *,mlpack::ann::Glimpse<arma::mat,arma::mat> *,mlpack::ann::HardTanH<arma::mat,arma::mat> *,mlpack::ann::Join<arma::mat,arma::mat> *,mlpack::ann::LayerNorm<arma::mat,arma::mat> *,mlpack::ann::LeakyReLU<arma::mat,arma::mat> *,mlpack::ann::Linear<arma::mat,arma::mat> *,mlpack::ann::LinearNoBias<arma::mat,arma::mat> *,mlpack::ann::LogSoftMax<arma::mat,arma::mat> *,mlpack::ann::Lookup<arma::mat,arma::mat> *,mlpack::ann::LSTM<arma::mat,arma::mat> *,mlpack::ann::GRU<arma::mat,arma::mat> *,mlpack::ann::FastLSTM<arma::mat,arma::mat> *,mlpack::ann::MaxPooling<arma::mat,arma::mat> *,mlpack::ann::MeanPooling<arma::mat,arma::mat> *,mlpack::ann::MultiplyConstant<arma::mat,arma::mat> *,mlpack::ann::MultiplyMerge<arma::mat,arma::mat> *,mlpack::ann::NegativeLogLikelihood<arma::mat,arma::mat> *,mlpack::ann::PReLU<arma::mat,arma::mat> *,mlpack::ann::Recurrent<arma::mat,arma::mat> *,mlpack::ann::RecurrentAttention<arma::mat,arma::mat> *,mlpack::ann::ReinforceNormal<arma::mat,arma::mat> *,mlpack::ann::Reparametrization<arma::mat,arma::mat> *,mlpack::ann::Select<arma::mat,arma::mat> *,mlpack::ann::Sequential<arma::mat,arma::mat> *,mlpack::ann::Subview<arma::mat,arma::mat> *,mlpack::ann::VRClassReward<arma::mat,arma::mat> *>)': cannot convert argument 1 from 'mlpack::ann::Sequential<arma::fmat,arma::fmat> *' to 'boost::variant<mlpack::ann::Add<arma::mat,arma::mat> *,mlpack::ann::AddMerge<arma::mat,arma::mat> *,mlpack::ann::AtrousConvolution<mlpack::ann::NaiveConvolution<mlpack::ann::ValidConvolution>,mlpack::ann::NaiveConvolution<mlpack::ann::FullConvolution>,mlpack::ann::NaiveConvolution<mlpack::ann::ValidConvolution>,arma::mat,arma::mat> *,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> *,mlpack::ann::BaseLayer<mlpack::ann::IdentityFunction,arma::mat,arma::mat> *,mlpack::ann::BaseLayer<mlpack::ann::TanhFunction,arma::mat,arma::mat> *,mlpack::ann::BaseLayer<mlpack::ann::RectifierFunction,arma::mat,arma::mat> *,mlpack::ann::BaseLayer<mlpack::ann::SoftplusFunction,arma::mat,arma::mat> *,mlpack::ann::BatchNorm<arma::mat,arma::mat> *,mlpack::ann::BilinearInterpolation<arma::mat,arma::mat> *,mlpack::ann::Concat<arma::mat,arma::mat> *,mlpack::ann::Concatenate<arma::mat,arma::mat> *,mlpack::ann::ConcatPerformance<mlpack::ann::NegativeLogLikelihood<arma::mat,arma::mat>,arma::mat,arma::mat> *,mlpack::ann::Constant<arma::mat,arma::mat> *,mlpack::ann::Convolution<mlpack::ann::NaiveConvolution<mlpack::ann::ValidConvolution>,mlpack::ann::NaiveConvolution<mlpack::ann::FullConvolution>,mlpack::ann::NaiveConvolution<mlpack::ann::ValidConvolution>,arma::mat,arma::mat> *,mlpack::ann::TransposedConvolution<mlpack::ann::NaiveConvolution<mlpack::ann::ValidConvolution>,mlpack::ann::NaiveConvolution<mlpack::ann::FullConvolution>,mlpack::ann::NaiveConvolution<mlpack::ann::ValidConvolution>,arma::mat,arma::mat> *,mlpack::ann::DropConnect<arma::mat,arma::mat> *,mlpack::ann::Dropout<arma::mat,arma::mat> *,mlpack::ann::AlphaDropout<arma::mat,arma::mat> *,mlpack::ann::ELU<arma::mat,arma::mat> *,mlpack::ann::FlexibleReLU<arma::mat,arma::mat> *,mlpack::ann::Glimpse<arma::mat,arma::mat> *,mlpack::ann::HardTanH<arma::mat,arma::mat> *,mlpack::ann::Join<arma::mat,arma::mat> *,mlpack::ann::LayerNorm<arma::mat,arma::mat> *,mlpack::ann::LeakyReLU<arma::mat,arma::mat> *,mlpack::ann::Linear<arma::mat,arma::mat> *,mlpack::ann::LinearNoBias<arma::mat,arma::mat> *,mlpack::ann::LogSoftMax<arma::mat,arma::mat> *,mlpack::ann::Lookup<arma::mat,arma::mat> *,mlpack::ann::LSTM<arma::mat,arma::mat> *,mlpack::ann::GRU<arma::mat,arma::mat> *,mlpack::ann::FastLSTM<arma::mat,arma::mat> *,mlpack::ann::MaxPooling<arma::mat,arma::mat> *,mlpack::ann::MeanPooling<arma::mat,arma::mat> *,mlpack::ann::MultiplyConstant<arma::mat,arma::mat> *,mlpack::ann::MultiplyMerge<arma::mat,arma::mat> *,mlpack::ann::NegativeLogLikelihood<arma::mat,arma::mat> *,mlpack::ann::PReLU<arma::mat,arma::mat> *,mlpack::ann::Recurrent<arma::mat,arma::mat> *,mlpack::ann::RecurrentAttention<arma::mat,arma::mat> *,mlpack::ann::ReinforceNormal<arma::mat,arma::mat> *,mlpack::ann::Reparametrization<arma::mat,arma::mat> *,mlpack::ann::Select<arma::mat,arma::mat> *,mlpack::ann::Sequential<arma::mat,arma::mat> *,mlpack::ann::Subview<arma::mat,arma::mat> *,mlpack::ann::VRClassReward<arma::mat,arma::mat> *>'	MLPack-CNN-Test	c:\users\nacoj\source\repos\machinelearning\mlpack-cnn-test\mlpack-cnn-test\source.cpp	110	
`

**Comment by zoq** [comment]
Haven't tested it, but a super hacky solution might be to do something like:

```
typedef float double;
typedef arma::fmat arma::mat;
```

**Comment by NacOJerk** [comment]
I will give it a try thx :)

**Comment by NacOJerk** [comment]
Well apparently it is illegal to typedef float double @zoq .

**Comment by rcurtin** [comment]
Another way to do this is to manually change the typedef in `src/mlpack/methods/ann/layer/layer_types.hpp` so that every `<arma::mat,arma::mat>` is `<arma::fmat,arma::fmat>` in the definition of `LayerTypes`.  You may also have to change around some of the function definitions in the `FNN` class.  It may take some work to get that working correctly.

Definitely support for non-double matrices is something that I consider important, although I haven't been able to approach it quite yet.

**Comment by zoq** [comment]
I guess, that also includes the optimizer, since they take ``arma::mat`` as input.

**Comment by NacOJerk** [comment]
Oke that sounds easy enough to do thx

**Comment by NacOJerk** [comment]
I still have an error @rcurtin 
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'double mlpack::ann::BernoulliDistribution<arma::fmat>::LogProbability(const DataType &&) const': cannot convert argument 1 from 'const arma::Mat<double>' to 'const DataType &&'	MLPack-CNN-Test	c:\mlpack\mlpack\build\include\mlpack\methods\ann\loss_functions\reconstruction_loss_impl.hpp	37

**Comment by Tanishq-Banyal** [comment]
> Well apparently it is illegal to typedef float double @zoq .

You can still use #define
