### ISSUE TITLE
Adapting test cases after modifying train functions.

### ISSUE THREAD

**Issue by walragatver** [mlpack/mlpack#1715]
This issue is a next step of #1483 Issue. 
After returning final objective from train function's it looks like some of the `tests` can be restructured.Also some `tests` are needed to be returned to ensure that always a reasonable `value` is returned. 

This is a nice issue for newbie's who want to understand the code base. Currently I am working on this, but if you are interested please feel free.

**Comment by shardulparab97** [comment]
@walragatver we could work on this together?

**Comment by walragatver** [comment]
> @walragatver we could work on this together?

@shardulparab97 Sorry for late reply. I think it will be better if only one of us work on it as it is not that big issue. So if you want to work on it just let me know.

**Comment by ShikharJ** [comment]
Fixed in #1724.
