### ISSUE TITLE
Runtime of each epoch increases with increasing the maxEpochs / totalEpochs

### ISSUE THREAD

**Issue by shardulparab97** [mlpack/mlpack#1718]
I was running a basic FFN network and realized that as I increased the number of **maxEpochs**, the run time of **each epoch** (not speaking about the total time for training) . I wanted to ask whether there is any specific reason for the same and whether this issue can be tackled?

**Comment by zoq** [comment]
Some optimizer (e.g. BigBatchSGD) use a dynamic batch size, so so time between epochs could increase. Do you think you could provide a simple model to reproduce the issue?

**Comment by shardulparab97** [comment]
Hi sorry for the late reply, was caught up with exams. There was a small issue from my side, I am sorry for any confusion caused. Thanks!
