### ISSUE TITLE
Any plan to add gpu support for ann module?

### ISSUE THREAD

**Issue by memoiry** [mlpack/mlpack#1719]
Hi

I have gone through the codebase of the neural network module and found that there is no GPU support for ann training, is there any plan to support it since CPU training is far slower than GPU?

**Comment by memoiry** [comment]
Maybe add cudnn implementation layer for conv, relu, pooling and etc...which should made ann module's training more practical.

**Comment by NacOJerk** [comment]
There is GPU support you just have to use nvblas aswell when you compile mlpack and armadillo
Once I fully solve my issues (the last thing I have to do is to make sure mlpack uses floats and not doubles)

**Comment by rcurtin** [comment]
NVBLAS is one solution.  Another way is using the Bandicoot GPU matrix library in place of Armadillo, but Bandicoot is still under development so it's not ready yet.  It is definitely a high priority for me though.

**Comment by memoiry** [comment]
Hi, I know that armadillo could use NVBLAS as its BLAS backend, but I think there is some overhead when you only put your matrix calculation into GPU since there might be a lot of matrix calculation in one layer and you need to move data between GPU and CPU repeatedly, which is highly inefficient.

Instead, we could write GPU implementation for every layer separately, so that we only need to move the input data into GPU memory first and then have the data and the intermediate result kept in the GPU memory. There is no need to move data between CPU and GPU during the Forward and the Backward.

What's more, Nvidia has written some highly optimized DNN layer for us in [cudnn](https://developer.nvidia.com/cudnn), we could replace some self-written CUDA implemented layer with cudnn's one. Such as conv, relu, pooling and etc. What do you think?

Thanks!

**Comment by rcurtin** [comment]
You're right that nvidia offers some nice functionality for these types of tasks but to keep the mlpack code simple we want to abstract the linear algebra away.  Hence Bandicoot is the right way to go here.

If you want to experiment with manually adding CUDA code to mlpack feel free---it will be interesting to see the speedup. But for code maintainability reasons I would not want to merge it into the mlpack codebase.

Let's see where Bandicoot gets us when it is ready---it should be able to avoid a lot of the issues with NVBLAS that you pointed out.

**Comment by NacOJerk** [comment]
@rcurtin do you know maby when the bandicoot library will release ?

**Comment by rcurtin** [comment]
Not sure, depends on my free time (and other contributors' free time).  I'm hoping a few months, but don't hold me to it. :)
