### ISSUE TITLE
Implement pointer-generator network technique for abstractive text summarization

### ISSUE THREAD

**Issue by Namrata96** [mlpack/mlpack#1725]
Implementing text summarization techniques in mlpack:
 - Pointer generator networks [abstractive]

Paper: https://arxiv.org/pdf/1704.04368.pdf
Dataset - CNN/Daily Mail news

Preliminary tasks:
- [ ] LSTMs
- [ ] Attention network
- [ ] Encoder-decoder model

**Comment by MuLx10** [comment]
@Namrata96 Are you willing to do this alone ? Can I join in the sub-tasks?

**Comment by zoq** [comment]
@Namrata96 thanks for opening the PR, looking forward to take a look through the code.

**Comment by Namrata96** [comment]
@MuLx10 sure, would be great to have help! We can divide the tasks among ourselves. Let me know once you have read the paper and we can discuss further.

**Comment by MuLx10** [comment]
@Namrata96 I have read the paper and also python [code](https://github.com/Namrata96/Text-Summarization). Except for 'coverage' I am good to go.

**Comment by MuLx10** [comment]
@Namrata96 Are we using pre-processed data or processing is a part of the implementation?

**Comment by Namrata96** [comment]
I think we can process the data on our end and then just the code to consume it for our model can be part of the implementation. @MuLx10 any other thoughts on this?

**Comment by Namrata96** [comment]
@MuLx10 which tasks are you interested in taking up?

**Comment by MuLx10** [comment]
@Namrata96 I think we should process the dataset and store so that what we feed in the implementation is just numbers, because a lot of work has to be done on string processing. I like to take up the Attention Decoder model. I am following the code structure from [here](https://github.com/abisee/pointer-generator). Will that be ok?

**Comment by iAhmedMaher** [comment]
Sorry for the intrusion, may I ask whether any progress been made in this direction?

**Comment by MuLx10** [comment]
Hey, there is nothing like intrusion. I have built a data loader that loads the text dataset and converts it to sequence needed by the network. However I am trying to add layers/support that may help to complete the implementation(like #1800, #1756 ) . So basically the implementation has just started.

**Comment by iAhmedMaher** [comment]
Okay, I was just asking because this issue/PR overlaps with my idea for GSoC and wanted to tailor my proposal accordingly. Thanks for the quick reply!

**Comment by heisenbuug** [comment]
@MuLx10 I am interested in working on this one, I am actually a bit familiar with LSTMs. I made this page for my GSoC proposal: https://heisenbuug.github.io/Long-Short-Term-Memory/
You were asking for a hand in IRC so I want to help...

**Comment by MuLx10** [comment]
Apologies for the delay. Sure, we will distribute work. Also, it's better to discuss the idea in IRC. 
Thanks for the help. 

Mehul Kumar Nirala 
Department of Computer Science and Engineering, 
IIT Kharagpur 
mehulkumarnirala@iitkgp.ac.in 
+91-9474415026

**Comment by heisenbuug** [comment]
Yea, i agree IRC will be a better place to discuss these issues.
