### ISSUE TITLE
Windows install with vcpkg

### ISSUE THREAD

**Issue by kereslas** [mlpack/mlpack#1727]
I have made a [PR](https://github.com/Microsoft/vcpkg/pull/5409) to add mlpack 3.0.4 to vcpkg library manager. Right now it's open, but I hope it gets merged to master. If you have vcpkg on your system, installing mlpack should be as easy as executing:

.\vcpkg install mlpack:x64-windows

This should download, build and install mlpack and all its dependencies. After that, if you have vcpkg user-wide integration enabled, you can create a project on Visual Studio and it will manage automatically linking with the library. So, you only need to write code and compile, without worrying about include directories or libraries. If you don't have user-wide integration you can manually set up the project and use as usual.

It would be nice if some people can try the PR and check if it works fine. vcpkg was created for Windows, but now it works on Linux and Mac. I have not tested on this systems.

**Comment by rcurtin** [comment]
@kereslas awesome!  Thank you for taking the time to do that.  I don't personally have Windows so I can't test it there, but maybe some other people watching this repository can do that.  Making the Windows installation process easier is definitely helpful.

I took a look at the installation scripts... do you think it would be good to install the header files (from `${CMAKE_BINARY_DIR}/include/` to somewhere also?  Maybe I overlooked something but I don't see that currently being done (maybe it's implicit?).  It may also be interesting to build the Python bindings but that would probably be hard to set up right...

**Comment by kereslas** [comment]
The header files are copied to vcpkg\installed\<architecture>\include by the build process. This is the place later VS will try to found it, so you can use all the includes in any project without setting anything manually. In vcpkg\installed\<architecture> are also a lib and bin folder with libs and dlls.

Usually the people at vcpkg project recomend to only compile the libraries and not the execs of samples or tests. Because of that I have made an optional exe compilation flag "tools" that builds this assets also:

.\vcpkg install mlpack[tools]:x64-windows

If you use the build command without the flag, only the library is build. If I have some time I will check if the script can build the python bindings with this or similar flag.

**Comment by kereslas** [comment]
The PR is officially merged to master branch, so anybody can install mlpack from now with vcpkg. The tests made by Microsoft include Mac OSX and seems it works on this system too.

**Comment by ShikharJ** [comment]
@kereslas Amazing, thanks for the work! Do you think we should include this in the documentation as well? If you wish to do it, let me know, else I can open a PR.

**Comment by rcurtin** [comment]
Nice!  Thanks for the clarification about the header files.  Building the Python bindings might be a bit tricky---I have been spending a few weeks now trying to get them to build right on Fedora. :)

**Comment by kereslas** [comment]
@ShikharJ Please, feel free to include in the documentation. I have made a [Gist](https://gist.github.com/kereslas/ac86f5323f78aa9cf8d09a3227acd674) with a simple tutorial. Use it as you want, modifying, completing or as you wish.

**Comment by zoq** [comment]
Awesome, will test this on windows, linux and mac OS in the next days.

**Comment by ShikharJ** [comment]
@kereslas I have opened a PR in #1736. Can you please confirm your name and give the PR a look?

**Comment by kereslas** [comment]
@ShikharJ yes, my name is correct. The PR looks great to me, thanks for the work.

**Comment by TryerGit** [comment]
@kereslas 

I am hoping to use the above procedure for CMake projects on Visual Studio in Windows that use the Ninja generator. Your gist states:

`After installing, in Visual Studio, you can create a New Project (or open an existing one). The library is immediately ready to be #include'd and used in your project without additional configuration.`

Would you happen to know if it is that one can use your procedure only for native Visual Studio IDE .sln solution files or would they work even with CMake projects on Visual Studio IDE that do not have the concept of a .sln/.vcxproj (project files) also "out of the box"?

The current official documentation available at https://www.mlpack.org/doc/user/build_windows.html seems to indicate both the vcpkg version as well as the CMake version to install MLPack. Are both these methods of installing equivalent in that the header files and the libraries will be installed into the same location under C:\? For e.g, the CMake installation procedure on the official page seems to indicate that everything will be installed in C:\mlpack\mlpack\build\Release 

Thank you.

**Comment by TryerGit** [comment]
I want to point out that the statement:

"After installing, in Visual Studio, you can create a new project (or open an existing one). The library is immediately ready to be included (via preprocessor directives) and used in your project without additional configuration."

is not true atleast at my end --  on a brand new Windows 11 machine using Visual Studio 2022

I followed the steps and installed mlpack via vcpkg. At the end, I obtain the lines:

The package mlpack is header only and can be used from CMake via:
  find_path(MLPACK_INCLUDE_DIRS "mlpack.hpp")
  target_include_directories(main PRIVATE ${MLPACK_INCLUDE_DIRS})

But including these lines in my CMakeLists.txt and opening the folder via Visual Studio gives me the following error:

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
C:/GoogleDrive/research_programming/mlpack/MLPACK_INCLUDE_DIRS
   used as include directory in directory C:/GoogleDrive/research_programming/mlpack		C:\GoogleDrive\research_programming\mlpack\   used as include directory in directory C

Any help is appreciated.
