### ISSUE TITLE
Ensmallen documentation yet to be removed

### ISSUE THREAD

**Issue by favre49** [mlpack/mlpack#1733]
In mlpack/doc/tutorials, there exists tutorials for CNE and Optimizers, both of which have now been shifted to the ensmallen repository. Shouldn't they be removed?

**Comment by zoq** [comment]
Right, I think it makes sense to remove those files.

**Comment by rcurtin** [comment]
Agreed, if you want to open a simple PR to do that I think we should merge it. :+1:
