### ISSUE TITLE
`BRNNReberGrammarTest` fails more than 50% of the time

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1740]
#### Issue description

Since #1626 was merged, the Jenkins builds are marked as unstable for different builds:

http://ci.mlpack.org/job/docker%20mlpack%20nightly%20build/

All of these failures are `BRNNReberGrammarTest`.

#### Your environment

 * version of mlpack: git master
 * operating system: Linux (debian)
 * compiler: any gcc version or clang version
 * version of dependencies (Boost/Armadillo): doesn't matter
 * any other environment information you think is relevant: see http://ci.mlpack.org/job/docker%20mlpack%20nightly%20build/

#### Steps to reproduce

Add `mlpack::math::RandomSeed(std::time(NULL))` to the top of `BRNNReberGrammarTest` in `src/mlpack/tests/recurrent_network_test.cpp`.  This step is important because otherwise the test will always run with the same random seed.  Compile and run (potentially in a loop like this):

```
$ i=0; while(true); do echo $i; bin/mlpack_test -t RecurrentNetworkTest/BRNNReberGrammarTest 2>&1 | grep 'fatal error'; i=$(($i + 1)); sleep 1; done
```

You can see that it fails more than half the time.

#### Expected behavior

The test should not fail.

#### Actual behavior

Here's some example output:

```
$ bin/mlpack_test -t RecurrentNetworkTest/BRNNReberGrammarTest
Running 1 test case...
/home/ryan/src/mlpack/src/mlpack/tests/recurrent_network_test.cpp(648): fatal error: in "RecurrentNetworkTest/BRNNReberGrammarTest": critical check successes >= 1 has failed [0 < 1]

*** 1 failure is detected in the test module "mlpackTest"
```

I can see also that the test is only running 1 iteration, which could be part of the problem.

@saksham189 can you please look into this?  If we can't get this solved then we should remove the BRNN code since it is not stable.  Thanks!

**Comment by saksham189** [comment]
Hey @rcurtin , this is unexpected. I am currently busy with my exams right now and will try to investigate the problem in the next few days. Sorry about the delay.

**Comment by rcurtin** [comment]
No problem; I may find a workaround but it warrants further investigation.

**Comment by saksham189** [comment]
I was able to reproduce the failure after adding the random seed.

**Comment by saksham189** [comment]
There was a pretty big mistake in the code code. It is now fixed. I will open a PR. 
`$ i=0; while(true); do echo $i; bin/mlpack_test -t RecurrentNetworkTest/BRNNReberGrammarTest 2>&1 | grep 'fatal error'; i=$(($i + 1)); sleep 1; done`

I have tested running this for 50 iterations without producing any failures.

**Comment by rcurtin** [comment]
@saksham189 thanks again for fixing this. :+1:
