### ISSUE TITLE
Installation fails for freebsd 11 amd64 machine.

### ISSUE THREAD

**Issue by Horopter** [mlpack/mlpack#1748]
make -j12 fails with the following error:

```
[ 15%] Building CXX object src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/approx_kfn_main.cpp.o
[ 16%] Building CXX object src/mlpack/methods/cf/CMakeFiles/mlpack_cf.dir/cf_main.cpp.o
[ 16%] Building CXX object src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/adaboost_main.cpp.o
[ 16%] Linking CXX executable ../../../../bin/mlpack_approx_kfn
//usr/local/lib/gcc6/libgfortran.so.3: undefined reference to `__multf3@GCC_4.6.0'
//usr/local/lib/gcc6/libgfortran.so.3: undefined reference to `__subtf3@GCC_4.6.0'
//usr/local/lib/gcc6/libgfortran.so.3: undefined reference to `__unordtf2@GCC_4.6.0'
//usr/local/lib/gcc6/libgfortran.so.3: undefined reference to `__netf2@GCC_4.6.0'
//usr/local/lib/gcc6/libgfortran.so.3: undefined reference to `__floatunditf@GCC_4.6.0'
//usr/local/lib/gcc6/libgfortran.so.3: undefined reference to `__letf2@GCC_4.6.0'
//usr/local/lib/gcc6/libgfortran.so.3: undefined reference to `__floatsitf@GCC_4.6.0'
//usr/local/lib/gcc6/libgfortran.so.3: undefined reference to `__floatditf@GCC_4.6.0'
//usr/local/lib/gcc6/libgfortran.so.3: undefined reference to `__lttf2@GCC_4.6.0'
//usr/local/lib/gcc6/libgfortran.so.3: undefined reference to `__eqtf2@GCC_4.6.0'
//usr/local/lib/gcc6/libgfortran.so.3: undefined reference to `__gttf2@GCC_4.6.0'
//usr/local/lib/gcc6/libgfortran.so.3: undefined reference to `__getf2@GCC_4.6.0'
//usr/local/lib/gcc6/libgfortran.so.3: undefined reference to `__addtf3@GCC_4.6.0'
//usr/local/lib/gcc6/libgfortran.so.3: undefined reference to `__divtf3@GCC_4.6.0'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
--- bin/mlpack_approx_kfn ---
*** [bin/mlpack_approx_kfn] Error code 1

make[2]: stopped in /root/mlpack-3.0.4/build
1 error

make[2]: stopped in /root/mlpack-3.0.4/build
--- src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/all ---
*** [src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/all] Error code 2

make[1]: stopped in /root/mlpack-3.0.4/build
A failure has been detected in another branch of the parallel make

make[2]: stopped in /root/mlpack-3.0.4/build
--- src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/all ---
*** [src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/all] Error code 2

make[1]: stopped in /root/mlpack-3.0.4/build
A failure has been detected in another branch of the parallel make

make[2]: stopped in /root/mlpack-3.0.4/build
--- src/mlpack/methods/cf/CMakeFiles/mlpack_cf.dir/all ---
*** [src/mlpack/methods/cf/CMakeFiles/mlpack_cf.dir/all] Error code 2

make[1]: stopped in /root/mlpack-3.0.4/build
```

Now, gcc 4.6 is deprecated starting from freebsd 11. So, is there a way to work it out?

**Comment by rcurtin** [comment]
Hmm, this one looks strange to me.  What happens if you do `ldd /usr/local/lib/gcc6/libgfortran.so.3`?  I'm suspecting there may be some things that version of `libgfortran.so` is linking to but not finding.

Also, are you compiling with gcc 6.x?

**Comment by Horopter** [comment]
```
# ldd /usr/local/lib/gcc6/libgfortran.so.3
        /usr/local/lib/gcc6/libgfortran.so.3:
        libquadmath.so.0 => /usr/local/lib/gcc6/libquadmath.so.0 (0x801327000)
        libm.so.5 => /lib/libm.so.5 (0x801566000)
        libgcc_s.so.1 => /usr/local/lib/gcc6/libgcc_s.so.1 (0x801791000)
        libc.so.7 => /lib/libc.so.7 (0x800824000)
```
Yes I am working with gcc6
 # gcc6 --version
gcc6 (FreeBSD Ports Collection) 6.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by zoq** [comment]
Building with:

``cmake -DCMAKE_CXX_FLAGS="-L/usr/local/lib/gcc6 -rpath /usr/local/lib/gcc6" ..``

let me know if that solves the issue on your side.

**Comment by robotcator** [comment]
Hi, @zoq @rcurtin, there is my initial thought that why we provide some built docker for the user to use mlpack?

**Comment by zoq** [comment]
Right, there is https://hub.docker.com/r/mlpack/mlpack which I have to update. Probably a good idea to create a jenkins job for this.

**Comment by robotcator** [comment]
> Right, there is https://hub.docker.com/r/mlpack/mlpack which I have to update. Probably a good idea to create a jenkins job for this.

I found that many people faced with the problem with installation, so my original thought was to build some dockers, but I found that there is already a docker image in docker hub. The image was created by your account :).  I thought that mlpack already support that feature. 

Actually, docker image is very popular in the Python library community. I built an image before, it seems fine.  But I was not sure there will be any obstacles when building images which contain C++ project.

**Comment by rcurtin** [comment]
We already provide several packages for seamless installation via pip, apt, dnf, pacman, and so forth.  Definitely it would be useful to update the Docker image, but the fact we can't get around is that a lot of people want to contribute to mlpack, and to do that effectively one must build mlpack from source.  So in some sense we'll always have issues like this.

**Comment by robotcator** [comment]
As far as I know, we can write the command which installs the library from the source into the docker image file.  So can we rebuild the image if there are any modifications? Also, we can maintain some stale version docker images.

**Comment by Horopter** [comment]
Hello Devs,
I would like to have a docker image for freebsd 11+, not as an alternative but more as a convenience. Anyway, the compilation is working now with repeated message/warning:

c++: warning: -rpath /usr/local/lib/gcc6: 'linker' input unused [-Wunused-command-line-argument]
c++: warning: argument unused during compilation: '-L/usr/local/lib/gcc6' [-Wunused-command-line-argument]

Please consider my request to put this on the web-page. 
https://www.mlpack.org/docs/mlpack-3.0.4/doxygen/build.html

**Comment by robotcator** [comment]
@Horopter  Here is a docker image for [ubuntu 16.04](https://cloud.docker.com/u/robotcator/repository/docker/robotcator/ubuntu-16.04-mlpack), it built a month ago. I am not sure it is useful for you.

**Comment by Horopter** [comment]
Hello @robotcator , I will look into it. I need a freeBSD version if possible. Also, please let me know the solution to the aforementioned error. I am very close to starting work with mlpack.

**Comment by Horopter** [comment]
Outputs of make
https://pastebin.com/nCTwaQG4
https://pastebin.com/UfnYU7cP
https://pastebin.com/gxLQqumK
https://pastebin.com/DD232ZAe

**Comment by robotcator** [comment]
> Hello @robotcator , I will look into it. I need a freeBSD version if possible. Also, please let me know the solution to the aforementioned error. I am very close to starting work with mlpack.
> 
> Output of make
> PART 1 : https://pastebin.com/nCTwaQG4
> PART 2 : https://pastebin.com/UfnYU7cP
> PART 3 : https://pastebin.com/gxLQqumK
> PART 4 : https://pastebin.com/DD232ZAe

I am very sorry about that. Actually, I am not familiar with freeBSD. If I were you, I will create a container in localhost which is a new clean environment.  Then follow the tutorial to build mlpack.

**Comment by Horopter** [comment]
All I have done is load a fresh installation of freebsd 11 on my system and followed the instructions on the page https://www.mlpack.org/docs/mlpack-3.0.4/doxygen/build.html with modifications suggested on this very thread.

The instruction make -j4 spat out the outputs which I have presented in the links by chunking them up. The installation failed with 1 error which I wish to resolve soon. You may find the error in last 20 lines of part 4.

**Comment by zoq** [comment]
@Horopter run ``make`` once again without using multiple jobs (``-jx``). The last time I checked, the docker support on FreeBSD is experimental, but maybe you already worked with docker? Not sure I see the benefit of using docker vs installing the dependencies in a new jail if a chroot environment is the decision point here.

**Comment by Horopter** [comment]
Hello zoq, 
The issue is that (from what I gather), is that it's not able to run tests pertaining to mnist data set 4s and 9s. Is it possible that it tried to download some off internet and failed? I hadn't connected my system to internet when I had run make. 

UPDATE : I have connected system to internet and ran make without multiple jobs...  It failed with same error.

**Comment by zoq** [comment]
I think the issue you see was solved in https://github.com/mlpack/mlpack/pull/1640, if you like you can rerun the test against the master branch.

**Comment by Horopter** [comment]
Since I am authorised to work only on mlpack releases and not the master branch, I am gonna go ahead and close this issue hoping that this won't occur with 3.0.5 stable release. Thanks for all the help.

**Comment by zoq** [comment]
You are still fine if you run the latest release, if you don't use the imputer.

**Comment by rcurtin** [comment]
Ok, hopefully we have it fixed by then.  If you can patch the code, you can cherry-pick the commits from #1640 (or make the changes manually).  You'll want the changes to `hoeffding_tree_impl.hpp`, `dataset_mapper.hpp`, `dataset_mapper_impl.hpp`, and `load_csv.hpp`.

In any case @zoq is right, if you don't use the imputer and if you don't serialize a Hoeffding tree, there should be no issues.  That is only a small part of the functionality of the library so probably you will still be able to do what you are aiming to do. :)
