### ISSUE TITLE
Documentation or tutorial for each machine learning method

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#175]
**Reported by rcurtin on 9 Jan 41971920 05:35 UTC**
I talked to a scikit-learn contributor at NIPS (actually, the guy who wrote their ball trees), and we discussed documentation and I noted that scikit-learn has far better tutorials and documentation than any other machine learning library I've seen.

For example, take this tutorial on classification:

http://scikit-learn.org/stable/auto_examples/plot_classification_probability.html#example-plot-classification-probability-py

Certainly, MLPACK is far different and needs different handling, but we should have complete examples for usage like this.  I envision one tutorial for each method we have, with the following general sections:
- Introduction to task / method (what are we trying to do?)
- Command-line executable documentation and usage [it exists](if)
- Simple, barebones C++ example (and documentation)
- More complex C++ example
- Full documentation of generalizability of class (through template parameters) and link to Doxygen documentation (or, Doxygen documentation inlined?)

This shouldn't be too incredibly difficult because we don't have too many methods already.  CCing the usual suspects for comments on the style / format / my own poor life choices / etcetera...

Migrated-From: http://trac.research.cc.gatech.edu/fastlab/ticket/181

**Comment by kartik-nighania** [comment]
@rcurtin  @zoq 
any easy to understand algorithm available for documentation?

**Comment by avantikasingh** [comment]
@rcurtin 
Interested in documenting Logical Regression. Is it done or may I go for it?

**Comment by rcurtin** [comment]
I think this is obsolete since the plans for documentation are changing so significantly.  We can continue the discussion in #1511 but I think this issue is no longer relevant in the way it was originally written.
