### ISSUE TITLE
Add hard_sigmoid activation function 

### ISSUE THREAD

**Issue by Bk073** [mlpack/mlpack#1763]
I wanted to contribute to this forum and thought of implementing **hard_sigmoid** activation function. I went through the codebase, I found LeakyRelu and other activation function but didn't find **hard_sigmoid** activation. Can I implement it ? 

Hard sigmoid helps to compute faster than sigmoid function

if x is input then hard_sigmoid return 

Hard sigmoid activation:

0 if x < -2.5
1 if x > 2.5
0.2 * x + 0.5 if -2.5 <= x <= 2.5.

**Comment by ShikharJ** [comment]
Hi @Bk073, I'm not sure if it would be useful to fix on just a single value of the coefficient of `x`. Maybe we implement a layer where a user can fix that coefficient? Thoughts @rcurtin @zoq?

**Comment by zoq** [comment]
I'm not aware of any other function that would need this form, so personally I would implement this as another activation function, instead of as another layer.

**Comment by ShikharJ** [comment]
Hmm, makes sense that way, feel free to implement this @Bk073.

**Comment by Bk073** [comment]
Ok thank you @zoq and @ShikharJ . I would then go for it.

**Comment by Bk073** [comment]
I have implemented the function and test related to it. I don't know how much of it is correct so I wanted to make review of it from you guys. How may I post my code ? Pushing into a new branch ?

**Comment by zoq** [comment]
Fork the repository, push the changes to the fork (new branch) and open a PR.
