### ISSUE TITLE
Trouble compiling new programs for cli

### ISSUE THREAD

**Issue by khan-07** [mlpack/mlpack#1769]
I am trying to compile a test code for cli with mlpack binding. The two codes i have tried to compile are  [here](http://www.mlpack.org/docs/mlpack-3.0.4/doxygen/iodoc.html). These codes are official samples taken from the documentation.  I am only running into problems when compiling test program with bindings. I am compiling the code  using the following way 

 **_g++ network_main.cpp -o cli -DDEBUG -g -rdynamic -lmlpack -lboost_program_options -fopenmp_**

i keep getting the following error. 

/tmp/cc73FXaq.o: In function `mlpack::bindings::cli::ParseCommandLine(int, char**)':
/usr/local/include/mlpack/bindings/cli/parse_command_line.hpp:43: undefined reference to `mlpack::CLI::Parameters[abi:cxx11]()'
/usr/local/include/mlpack/bindings/cli/parse_command_line.hpp:136: undefined reference to `mlpack::CLI::ProgramName[abi:cxx11]()'
/usr/local/include/mlpack/bindings/cli/parse_command_line.hpp:144: undefined reference to `mlpack::bindings::cli::PrintHelp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/local/include/mlpack/bindings/cli/parse_command_line.hpp:158: undefined reference to `mlpack::bindings::cli::PrintHelp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/local/include/mlpack/bindings/cli/parse_command_line.hpp:163: undefined reference to `mlpack::bindings::cli::PrintHelp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/cc73FXaq.o: In function `main':
/usr/local/include/mlpack/core/util/mlpack_main.hpp:63: undefined reference to `mlpack::Timer::EnableTiming()'
/tmp/cc73FXaq.o: In function `__static_initialization_and_destruction_0(int, int)':
/mnt/c/Linux/network_main.cpp:6: undefined reference to `mlpack::util::ProgramDoc::ProgramDoc(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()> const&)'
/tmp/cc73FXaq.o: In function `mlpack::bindings::cli::EndProgram()':
/usr/local/include/mlpack/bindings/cli/end_program.hpp:29: undefined reference to `mlpack::Timers::StopAllTimers()'
/usr/local/include/mlpack/bindings/cli/end_program.hpp:32: undefined reference to `mlpack::CLI::Parameters[abi:cxx11]()'
/tmp/cc73FXaq.o: In function `mlpack::bindings::cli::CLIOption<bool>::CLIOption(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/local/include/mlpack/bindings/cli/cli_option.hpp:112: undefined reference to `mlpack::CLI::Parameters[abi:cxx11]()'
/usr/local/include/mlpack/bindings/cli/cli_option.hpp:138: undefined reference to `mlpack::CLI::Add(mlpack::util::ParamData&&)'
/tmp/cc73FXaq.o: In function `mlpack::bindings::cli::CLIOption<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::CLIOption(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/local/include/mlpack/bindings/cli/cli_option.hpp:112: undefined reference to `mlpack::CLI::Parameters[abi:cxx11]()'
/usr/local/include/mlpack/bindings/cli/cli_option.hpp:138: undefined reference to `mlpack::CLI::Add(mlpack::util::ParamData&&)'
/tmp/cc73FXaq.o: In function `mlpack::bindings::cli::CLIOption<arma::Mat<double> >::CLIOption(arma::Mat<double>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/local/include/mlpack/bindings/cli/cli_option.hpp:112: undefined reference to `mlpack::CLI::Parameters[abi:cxx11]()'
/usr/local/include/mlpack/bindings/cli/cli_option.hpp:138: undefined reference to `mlpack::CLI::Add(mlpack::util::ParamData&&)'
/tmp/cc73FXaq.o: In function `mlpack::bindings::cli::CLIOption<int>::CLIOption(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/local/include/mlpack/bindings/cli/cli_option.hpp:112: undefined reference to `mlpack::CLI::Parameters[abi:cxx11]()'
/usr/local/include/mlpack/bindings/cli/cli_option.hpp:138: undefined reference to `mlpack::CLI::Add(mlpack::util::ParamData&&)'
collect2: error: ld returned 1 exit status

**Comment by rcurtin** [comment]
Looks like a linking issue to me.  Are you sure the version of mlpack that you installed is the same one you are linking against?  If you have mlpack installed twice on your system this could occur.

**Comment by khan-07** [comment]
Thanks @rcurtin  . I indeed had two version of mlpack installed . One that i build from the source and another one i installed using apt-get. I removed both the version and made a new clean build from source. The code with bindings is compiling now. If you don't mind asking how did you figure out that there are two installations of mlpack ?

**Comment by rcurtin** [comment]
I've just seen the problem a lot of times, for one. ;)

To give a little more detail, basically I can see from the output that your compiler has successfully included `mlpack/core.hpp`, and I can also see that you're linking against mlpack with `-lmlpack` and I can even see that the linker found a library to link against (otherwise it would have said something like `libmlpack.so not found` or something like that).  But there are some symbols in the version of `libmlpack.so` that aren't there that the compiler needed... so the most common explanation here is that it's the wrong `libmlpack.so` for the include/ directory.  The most likely cause of that is two installations. :)

**Comment by rcurtin** [comment]
Since you got the issue figured out, I'll go ahead and close this. :+1:
