### ISSUE TITLE
grammatical mistake in  comment in mlpack/src/mlpack/core/data/imputer.hpp 

### ISSUE THREAD

**Issue by greatsharma** [mlpack/mlpack#1778]

**Comment by Shubhangi100** [comment]
@rcurtin I would like to work on this issue, can I proceed?

**Comment by zoq** [comment]
@Shubhangi100 @greatsharma already open a PR: https://github.com/mlpack/mlpack/pull/1779.

@greatsharma No need to open an issue first.

**Comment by greatsharma** [comment]
> 
> 
> @Shubhangi100 @greatsharma already open a PR: #1779.
> 
> @greatsharma No need to open an issue first.

I closed #1779 and open #1789  solving the same PR
