### ISSUE TITLE
confusing and missleading comment 

### ISSUE THREAD

**Issue by greatsharma** [mlpack/mlpack#1781]
#### Problem location

src/mlpack/core/data/map_policies/increment_policy.hpp 

#### Description of problem

In multiline comment at line 25, instead of  " one if the "  it should be " one of the ". At a very first 
look it just confuses the reader regarding the IncrementPolicy helper class.

**Comment by ShikharJ** [comment]
Since this is included in #1779, and we have an issue open in #1778, there's no need to keep this open.

**Comment by greatsharma** [comment]
ShikharJ sir can you please elaborate more why you closed #1781 I didn't understand the above reason as I am not an active github user

**Comment by ShikharJ** [comment]
The above reason has nothing to do with being an active GitHub user :) There is already a documentation based issue opened by you, and it is redundant to open individual issues for single line documentation errors. Additionally, you did end up including this in the PR, so no reason to keep it open.
