### ISSUE TITLE
Exposing Cell and hidden state in LSTM.

### ISSUE THREAD

**Issue by MuLx10** [mlpack/mlpack#1782]
**Besides  the weights I guess cell state and hidden state should also be exposed. It is helpful for building networks that rely on cell state in LSTMs.**
```c++
 //! Get the parameters.
  OutputDataType const& Parameters() const { return weights; }
  //! Modify the parameters.
  OutputDataType& Parameters() { return weights; }

```
**Currently they are private members so unavailable.**
```c++
private:
....
  //! Locally-stored hidden layer parameter.
  OutputDataType hiddenLaye
  //! Locally-stored hidden layer activation.
  OutputDataType hiddenLayerActivation;
....
  //! Locally-stored cell parameter.
  OutputDataType cell;

  //! Locally-stored cell activation error.
  OutputDataType cellActivation;
....
```

 (I am not sure if it's a good idea at the current moment.)

**Comment by abhinavsagar** [comment]
@MuLx10 Recognized me? Can i work on this?

**Comment by MuLx10** [comment]
I don't know if it's a good idea right now. @zoq Is this issue reasonable? Because the entire code structure allows access of parameters only. 
@abhinavsagar yes of course.

**Comment by zoq** [comment]
Agreed that should be useful.

**Comment by ShikharJ** [comment]
Added in #1800.
