### ISSUE TITLE
No test for NormalizeLabels (normalize_labels.hpp) function

### ISSUE THREAD

**Issue by jeffin143** [mlpack/mlpack#1783]
I couldn't find any test for NormalizeLabels function (/src/mlpack/core/data/normalize_label.hpp) in test directory.Is it not required to test or already implemented.If already implemented could some one point it to me.

**Comment by zoq** [comment]
Here you go:

https://github.com/mlpack/mlpack/blob/2326bf8bd0b380c17eed6b5b1c34fbfab1563774/src/mlpack/tests/load_save_test.cpp#L774-L823

**Comment by jeffin143** [comment]
Thanks for the info
