### ISSUE TITLE
Documentation issue in Leaky_relu.hpp

### ISSUE THREAD

**Issue by jeffin143** [mlpack/mlpack#1787]
I am not sure what does the description about the parameters for the function below means.

#### Problem location

[documentation link](https://github.com/mlpack/mlpack/blob/cfcc1e33a0c65de1077299ea515c7864a882f046/src/mlpack/methods/ann/layer/leaky_relu.hpp#L137)

#### Description of problem

/src/mlpack/methods/ann/layer/leaky_relu.hpp
`
/*
   * Computes the first derivative of the LeakyReLU function.
   *
   * param **y Input activation**.
   * param **x The resulting derivatives.**
   *
*/

  template<typename InputType, typename OutputType>
  void Deriv(const InputType& x, OutputType& y)
  {
    y = x;

    for (size_t i = 0; i < x.n_elem; i++)
    {
      y(i) = Deriv(x(i));
    }
  }
` 
I guess the parameters x,y got interchanged, still not sure what does it mean if not interchanged. If so i would like to raise a PR to sought it.

**Comment by ShikharJ** [comment]
@jeffin143 If you don't mind, I am working on a PR on the same code. I'd like to include this there itself. Please let me know if it is fine by you?

**Comment by jeffin143** [comment]
@ShikharJ ok, no issues with it.
