### ISSUE TITLE
Error during make for mlpack

### ISSUE THREAD

**Issue by karlzhang-hhg** [mlpack/mlpack#1802]
I am following https://www.mlpack.org/doc/mlpack-3.0.4/doxygen/build.html to build mlpack from source. I found two errors:

```
/anaconda3/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: 
      "Using deprecated NumPy API, disable it with "          "#define
      NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
In file included from /Users/GSoC/mlpack-3.0.4/build/src/mlpack/bindings/python/mlpack/arma_numpy.cpp:609:
In file included from /Users/GSoC/mlpack-3.0.4/src/mlpack/core.hpp:256:
/Users/GSoC/mlpack-3.0.4/src/mlpack/prereqs.hpp:32:10: fatal error: 
      'cstdint' file not found
#include <cstdint>
         ^~~~~~~~~
 ##
```

Another error is:

```
1 warning and 1 error generated.
error: command '/usr/bin/clang' failed with exit status 1
make[2]: *** [python] Error 1
make[1]: *** [src/mlpack/bindings/python/CMakeFiles/python.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```
Please let me know how to fix them. Thanks.

**Comment by zoq** [comment]
I think the issue was solved in: https://github.com/mlpack/mlpack/pull/1523, so can you build against the master branch?

**Comment by karlzhang-hhg** [comment]
Hi Marcus,

Thanks for your quick response. I download the master branch and follow the install instruction on link https://www.mlpack.org/doc/mlpack-3.0.4/doxygen/build.html#build_dep. It reports lots of warning like following:

[  5%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/laplace_distribution.cpp.o
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//cc8frEgl.s:3:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//cc8frEgl.s:3:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//cc8frEgl.s:52:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//cc8frEgl.s:52:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//cc8frEgl.s:85:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//cc8frEgl.s:85:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//cc8frEgl.s:156:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//cc8frEgl.s:156:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//cc8frEgl.s:300:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//cc8frEgl.s:300:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//cc8frEgl.s:551:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//cc8frEgl.s:551:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//cc8frEgl.s:651:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//cc8frEgl.s:651:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//cc8frEgl.s:801:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//cc8frEgl.s:801:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~

And also there are some error:

[ 14%] Linking CXX executable ../../../../bin/mlpack_decision_tree
Undefined symbols for architecture x86_64:
  "boost::program_options::to_internal(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > boost::program_options::to_internal<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) in decision_tree_main.cpp.o
  "boost::program_options::invalid_option_value::invalid_option_value(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      void boost::program_options::validate<double, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, double*, long) in decision_tree_main.cpp.o
      void boost::program_options::validate<int, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int*, long) in decision_tree_main.cpp.o
  "boost::program_options::error_with_option_name::error_with_option_name(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)", referenced from:
      boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) in decision_tree_main.cpp.o
  "boost::program_options::detail::cmdline::set_additional_parser(boost::function1<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>)", referenced from:
      boost::program_options::basic_command_line_parser<char>::extra_parser(boost::function1<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>) in decision_tree_main.cpp.o
  "boost::program_options::detail::cmdline::cmdline(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)", referenced from:
      boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*) in decision_tree_main.cpp.o
  "boost::program_options::validate(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)", referenced from:
      boost::program_options::typed_value<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::xparse(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const in decision_tree_main.cpp.o
  "boost::archive::xml_iarchive_impl<boost::archive::xml_iarchive>::load(std::basic_string<char, std::char_traits<char>, std::allocator<char> >&)", referenced from:
      void boost::archive::load_access::load_primitive<boost::archive::xml_iarchive, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::archive::xml_iarchive&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&) in decision_tree_main.cpp.o
  "boost::archive::xml_iarchive_impl<boost::archive::xml_iarchive>::xml_iarchive_impl(std::basic_istream<char, std::char_traits<char> >&, unsigned int)", referenced from:
      boost::archive::xml_iarchive::xml_iarchive(std::basic_istream<char, std::char_traits<char> >&, unsigned int) in decision_tree_main.cpp.o
  "boost::archive::xml_oarchive_impl<boost::archive::xml_oarchive>::save(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      void boost::archive::save_access::save_primitive<boost::archive::xml_oarchive, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::archive::xml_oarchive&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in decision_tree_main.cpp.o
  "boost::archive::xml_oarchive_impl<boost::archive::xml_oarchive>::xml_oarchive_impl(std::basic_ostream<char, std::char_traits<char> >&, unsigned int)", referenced from:
      boost::archive::xml_oarchive::xml_oarchive(std::basic_ostream<char, std::char_traits<char> >&, unsigned int) in decision_tree_main.cpp.o
  "boost::archive::text_iarchive_impl<boost::archive::text_iarchive>::load(std::basic_string<char, std::char_traits<char>, std::allocator<char> >&)", referenced from:
      void boost::archive::load_access::load_primitive<boost::archive::text_iarchive, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::archive::text_iarchive&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&) in decision_tree_main.cpp.o
  "boost::archive::text_iarchive_impl<boost::archive::text_iarchive>::text_iarchive_impl(std::basic_istream<char, std::char_traits<char> >&, unsigned int)", referenced from:
      boost::archive::text_iarchive::text_iarchive(std::basic_istream<char, std::char_traits<char> >&, unsigned int) in decision_tree_main.cpp.o
  "boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::save(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      void boost::archive::save_access::save_primitive<boost::archive::text_oarchive, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::archive::text_oarchive&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in decision_tree_main.cpp.o
  "boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::text_oarchive_impl(std::basic_ostream<char, std::char_traits<char> >&, unsigned int)", referenced from:
      boost::archive::text_oarchive::text_oarchive(std::basic_ostream<char, std::char_traits<char> >&, unsigned int) in decision_tree_main.cpp.o
  "boost::archive::basic_text_iprimitive<std::basic_istream<char, std::char_traits<char> > >::~basic_text_iprimitive()", referenced from:
      boost::archive::text_iarchive_impl<boost::archive::text_iarchive>::~text_iarchive_impl() in decision_tree_main.cpp.o
      boost::archive::text_iarchive_impl<boost::archive::text_iarchive>::~text_iarchive_impl() in decision_tree_main.cpp.o
  "boost::archive::basic_text_oprimitive<std::basic_ostream<char, std::char_traits<char> > >::~basic_text_oprimitive()", referenced from:
      boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::~text_oarchive_impl() in decision_tree_main.cpp.o
      boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::~text_oarchive_impl() in decision_tree_main.cpp.o
  "boost::archive::basic_binary_iprimitive<boost::archive::binary_iarchive, char, std::char_traits<char> >::init()", referenced from:
      boost::archive::binary_iarchive_impl<boost::archive::binary_iarchive, char, std::char_traits<char> >::init(unsigned int) in decision_tree_main.cpp.o
  "boost::archive::basic_binary_iprimitive<boost::archive::binary_iarchive, char, std::char_traits<char> >::load(std::basic_string<char, std::char_traits<char>, std::allocator<char> >&)", referenced from:
      void boost::archive::load_access::load_primitive<boost::archive::binary_iarchive, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::archive::binary_iarchive&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&) in decision_tree_main.cpp.o
  "boost::archive::basic_binary_iprimitive<boost::archive::binary_iarchive, char, std::char_traits<char> >::basic_binary_iprimitive(std::basic_streambuf<char, std::char_traits<char> >&, bool)", referenced from:
      boost::archive::binary_iarchive_impl<boost::archive::binary_iarchive, char, std::char_traits<char> >::binary_iarchive_impl(std::basic_istream<char, std::char_traits<char> >&, unsigned int) in decision_tree_main.cpp.o
  "boost::archive::basic_binary_iprimitive<boost::archive::binary_iarchive, char, std::char_traits<char> >::~basic_binary_iprimitive()", referenced from:
      boost::archive::binary_iarchive_impl<boost::archive::binary_iarchive, char, std::char_traits<char> >::~binary_iarchive_impl() in decision_tree_main.cpp.o
      boost::archive::binary_iarchive_impl<boost::archive::binary_iarchive, char, std::char_traits<char> >::~binary_iarchive_impl() in decision_tree_main.cpp.o
      boost::archive::binary_iarchive_impl<boost::archive::binary_iarchive, char, std::char_traits<char> >::binary_iarchive_impl(std::basic_istream<char, std::char_traits<char> >&, unsigned int) in decision_tree_main.cpp.o
  "boost::archive::basic_binary_oprimitive<boost::archive::binary_oarchive, char, std::char_traits<char> >::init()", referenced from:
      boost::archive::binary_oarchive_impl<boost::archive::binary_oarchive, char, std::char_traits<char> >::init(unsigned int) in decision_tree_main.cpp.o
  "boost::archive::basic_binary_oprimitive<boost::archive::binary_oarchive, char, std::char_traits<char> >::save(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      void boost::archive::save_access::save_primitive<boost::archive::binary_oarchive, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::archive::binary_oarchive&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in decision_tree_main.cpp.o
  "boost::archive::basic_binary_oprimitive<boost::archive::binary_oarchive, char, std::char_traits<char> >::basic_binary_oprimitive(std::basic_streambuf<char, std::char_traits<char> >&, bool)", referenced from:
      boost::archive::binary_oarchive_impl<boost::archive::binary_oarchive, char, std::char_traits<char> >::binary_oarchive_impl(std::basic_ostream<char, std::char_traits<char> >&, unsigned int) in decision_tree_main.cpp.o
  "boost::archive::basic_binary_oprimitive<boost::archive::binary_oarchive, char, std::char_traits<char> >::~basic_binary_oprimitive()", referenced from:
      boost::archive::binary_oarchive_impl<boost::archive::binary_oarchive, char, std::char_traits<char> >::~binary_oarchive_impl() in decision_tree_main.cpp.o
      boost::archive::binary_oarchive_impl<boost::archive::binary_oarchive, char, std::char_traits<char> >::~binary_oarchive_impl() in decision_tree_main.cpp.o
      boost::archive::binary_oarchive_impl<boost::archive::binary_oarchive, char, std::char_traits<char> >::binary_oarchive_impl(std::basic_ostream<char, std::char_traits<char> >&, unsigned int) in decision_tree_main.cpp.o
  "boost::program_options::options_description::find(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool) const", referenced from:
      mlpack::bindings::cli::ParseCommandLine(int, char**) in decision_tree_main.cpp.o
  "boost::program_options::abstract_variables_map::operator[](std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const", referenced from:
      boost::program_options::variables_map::operator[](std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const in decision_tree_main.cpp.o
  "boost::program_options::error_with_option_name::substitute_placeholders(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const", referenced from:
      vtable for boost::program_options::invalid_option_value in decision_tree_main.cpp.o
      vtable for boost::program_options::validation_error in decision_tree_main.cpp.o
      vtable for boost::wrapexcept<boost::program_options::validation_error> in decision_tree_main.cpp.o
      construction vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::validation_error> >-in-boost::wrapexcept<boost::program_options::validation_error> in decision_tree_main.cpp.o
      vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::validation_error> > in decision_tree_main.cpp.o
      vtable for boost::exception_detail::error_info_injector<boost::program_options::validation_error> in decision_tree_main.cpp.o
      vtable for boost::wrapexcept<boost::program_options::invalid_option_value> in decision_tree_main.cpp.o
      ...
  "boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const", referenced from:
      vtable for boost::program_options::typed_value<double, char> in decision_tree_main.cpp.o
      vtable for boost::program_options::typed_value<int, char> in decision_tree_main.cpp.o
      vtable for boost::program_options::typed_value<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, char> in decision_tree_main.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [bin/mlpack_decision_tree] Error 1
make[1]: *** [src/mlpack/methods/decision_tree/CMakeFiles/mlpack_decision_tree.dir/all] Error 2

I think there is something wrong. 

Then, I go back to install the version 3.0.4. Because during previously trying of building against the master branch, I updated many of my libraries in homebrew. This trying of installing mlpack-3.0.4 works out with no error. Just the cmake cannot find the OpenMP. I am not sure if it really matters. Also, the warning part of "make" command is following:

[ 89%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/scd_test.cpp.o
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:327:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:327:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:353:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:353:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:385:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:385:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:451:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:451:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:589:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:589:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:829:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:829:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:924:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:924:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:1067:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:1067:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:26118:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:26118:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:26350:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:26350:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:28075:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:28075:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:28372:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:28372:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:28536:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:28536:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:28721:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:28721:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:28955:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:28955:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:29172:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:29172:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:29253:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:29253:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:29390:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:29390:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:29545:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:29545:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:29956:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:29956:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:30037:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:30037:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:30193:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:30193:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:30196:11: warning: section "__datacoal_nt" is deprecated
        .section __DATA,__datacoal_nt,coalesced
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:30196:11: note: change section name to "__data"
        .section __DATA,__datacoal_nt,coalesced
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:31381:11: warning: section "__datacoal_nt" is deprecated
        .section __DATA,__datacoal_nt,coalesced
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:31381:11: note: change section name to "__data"
        .section __DATA,__datacoal_nt,coalesced
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:31406:11: warning: section "__datacoal_nt" is deprecated
        .section __DATA,__datacoal_nt,coalesced
                 ^      ~~~~~~~~~~~~~
/var/folders/fr/bf53vrjd5t5c63kql06b_9bw0000gn/T//ccDens53.s:31406:11: note: change section name to "__data"
        .section __DATA,__datacoal_nt,coalesced
                 ^      ~~~~~~~~~~~~~

Sorry for this long question.

**Comment by phantomcoder1996** [comment]
Are you building on mac OS??I was having issues with the build as well on OS high Sierra.
First, I updated Xcode to the latest version and then updated the command line tools using
`xcode-select --install`
Then I made sure that I had the latest version from cmake
`brew install cmake`
Then I followed the instruction in that previous issue #1602 
1- Change the set up file to that one (http://www.ratml.org/misc/setup-2.py.in ) in the path: "src/mlpack/bindings/python/setup.py.in"
1- Remove the build directory
2- mkdir build 
3-cd build
4- cmake -DCMAKE_CXX_FLAGS="-stdlib=libc++" ../
5- make
I don't know if that will work with you,but it was what I did so that the build will work for me
