### ISSUE TITLE
Link to "build_config" and many other links @ README.MD are not working

### ISSUE THREAD

**Issue by gmanlan** [mlpack/mlpack#1804]
#### Problem location

README.MD --> 4. Building mlpack from source --> See[ this section of the build guide](http://www.mlpack.org/docs/mlpack-git/doxygen/build.html#build_config) for more details, including a full list of options, and their default values.

The same happens with many other links @ README.MD

#### Description of problem

The link doesn't work - probably after the recent changes to the documentation/website

**Comment by rcurtin** [comment]
Thanks for pointing this out---I opened a fix with #1808. :+1:

**Comment by rcurtin** [comment]
#1808 is merged, so I'll go ahead and close this now.  If you find anything else please do feel free to open an issue. :)
