### ISSUE TITLE
No velocity goal in mountain_car.hpp

### ISSUE THREAD

**Issue by abhinavsagar** [mlpack/mlpack#1806]
#### Issue description

There should also be a velocity goal just like position goal variable as a reference value as and when velocity is updated.

#### Your environment

 * version of mlpack: 3.0.4
 * operating system: Windows 10
 * compiler: g++

#### Steps to reproduce

Compile and execute `mountain_car.hpp`

#### Expected behavior
The velocity goal variable will dictate in which direction and by how much change is allowed in each step.

#### Actual behavior
Due to lack of velocity goal variable controls are not that great.

**Comment by zoq** [comment]
This makes the mountain car environment much more challenging; don't think this should be part of the default environment, either we implement another mountain car V2 environment or provide a flag to enable the constraint.

**Comment by abhinavsagar** [comment]
@zoq Got it. Can i work on a V2 environment for this?

**Comment by zoq** [comment]
Sure, feel free, I think you already open a PR, either we close this one or you use this to make the changes.

**Comment by abhinavsagar** [comment]
@zoq OK thanks, I am closing this PR. I will open the new one with the required changes as soon as it is done.

**Comment by zoq** [comment]
Okay, sounds good.
