### ISSUE TITLE
Links in the README.md of mlpack/mlpack not working.

### ISSUE THREAD

**Issue by ktj-code-debug** [mlpack/mlpack#1812]
#### README.md ([mlpack repository](https://github.com/mlpack/mlpack))

- [1. Introduction](https://github.com/mlpack/mlpack#1-introduction)
  - Tutorials http://www.mlpack.org/docs/mlpack-git/doxygen/tutorials.html
  - API documentation http://www.mlpack.org/docs/mlpack-git/doxygen/index.html
- [4. Building mlpack from source](https://github.com/mlpack/mlpack#4-building-mlpack-from-source)
  - Building mlpack From Source http://www.mlpack.org/docs/mlpack-git/doxygen/build.html
  - Building mlpack From Source on Windows http://www.mlpack.org/docs/mlpack-git/doxygen/build_windows.html
- [7. Further documentation](https://github.com/mlpack/mlpack#7-further-documentation)
  - Tutorials http://www.mlpack.org/docs/mlpack-git/doxygen/tutorials.html
  - API documentation http://www.mlpack.org/docs/mlpack-git/doxygen/index.html

#### Description of problem

 The following URL's not found on the server
 http://www.mlpack.org/docs/mlpack-git/doxygen/tutorials.html
 http://www.mlpack.org/docs/mlpack-git/doxygen/index.html
 http://www.mlpack.org/docs/mlpack-git/doxygen/build.html
 http://www.mlpack.org/docs/mlpack-git/doxygen/build_windows.html

**Comment by abhinavsagar** [comment]
Claim

**Comment by rcurtin** [comment]
@abhinavsagar I'm not sure the meaning of your comment.

@ktj-code-debug thanks for the report; #1808 is already open to fix this. :+1:

**Comment by rcurtin** [comment]
#1808 is merged, so I'm going to go ahead and close this.  Thanks again for the report. :+1:
