### ISSUE TITLE
Serial and parallel runtimes

### ISSUE THREAD

**Issue by 8hantanu** [mlpack/mlpack#1826]
I want to compare the run times of serial and parallel code.
I could build using `cmake -D USE_OPENMP=OFF`  but currently I am setting `OMP_NUM_THREADS=1` to get the serial runtime. This might account for some overhead due to the omp pragmas.
**Is there a way to get more accurate runtime for the serial run?**

Also in the mlpack/benchmarks repo I didn't find any method which gives a timing report. Please point me to it if I have missed it.

**Comment by zoq** [comment]
Not entirely sure, but I think it's fine to set `OMP_NUM_THREADS=1`. Not sure I get what you mean regarding the timing benchmarks, can you clarify that point? Btw. nice picture.

**Comment by rcurtin** [comment]
OpenMP may have a little bit of overhead when you compile with `-D USE_OPENMP=ON` but it's not likely to be seriously noticeable.  So running with `OMP_NUM_THREADS=1` should be pretty close to fine.  You can always compile both ways and compare, but I wouldn't expect the difference to be more than a few percent when running machine learning algorithms on large data.

**Comment by 8hantanu** [comment]
@zoq By timing report, I meant the runtimes along with the benchmark results. Anyway, I found the Timer API useful for finding runtime of code sections. Thanks for the compliment :)

@rcurtin Thank you for clarifying. Will be using `OMP_NUM_THREADS=1`, since its quicker than recompiling.

Since I have a little experience with OMP I thought implementing parallelized algorithms would be a great way for me to start with ML again. If there are any specific methods/modules which might benefit from parallel implementation, please let me know.
