### ISSUE TITLE
Use batchSize parameter for GAN

### ISSUE THREAD

**Issue by saksham189** [mlpack/mlpack#1827]
Currently the parameter `batchSize` is commented out for methods `EvaluateWithGradient` and `Evaluate` in GAN. I think this is resulting in a bug where we pass both the real and fake images for training the discriminator at once. 

For example consider `batchSize = 4` and `numFunctions = 10`.
Then we would have calls to `EvaluateWithGradient` with values of `i` being 0, 4, and 8.
When we use value of `i = 8` with batchSize of `4` we end up training the discriminator on fake data as well.
```
double res = discriminator.EvaluateWithGradient(discriminator.parameter,
      i, gradientDiscriminator, batchSize);
```

Instead I think we should use the `batchSize` parameter passed to `EvaluateWithGradient` in GAN which would be 2 when `i` is equal to 8.

@ShikharJ @zoq  let me know what you think.

**Comment by ShikharJ** [comment]
I'm not sure that this is a bug-report. If you really want to setup a batch size, it is always going to be a number which is a divisor of the total number of input data points you wish to consider. So I'd rather that this remain untouched. Also if you make use of the `batchSize` parameter which is passed, you'll face a problem here, if you try to reason:
```
generator.Gradient(generator.parameter, 0, gradientGenerator, batchSize);
```
Now the `generator` will only pick up the gradients from the reduced number of data points, which is not what we want. Let me know if I should clarify anything.

**Comment by saksham189** [comment]
>  If you really want to setup a batch size, it is always going to be a number which is a divisor of the total number of input data points you wish to consider. 

So this must always be true? If this is true, then obviously there will be no problem. 

I was considering using the max batch size for the generator and reduced batch size for the discriminator.

**Comment by ShikharJ** [comment]
> So this must always be true? If this is true, then obviously there will be no problem.
Yes, it hardly makes sense to choose a `batchSize` such that for certain `epochs` it leads to uneven gradient update.
