### ISSUE TITLE
Issue #189

### ISSUE THREAD

**Issue by jeffin143** [mlpack/mlpack#1833]
I checked out all the closed issues, but couldn't find out issue related to mvu which is pointed at line no 10 in mvu.hpp, is it really #189 ?
[here](https://github.com/mlpack/mlpack/blob/d99a9a6043fb03dbd25165954b060318400a636b/src/mlpack/methods/mvu/mvu.hpp#L10)

**Comment by rcurtin** [comment]
I'm willing to bet #189 was the issue number when mlpack was on Trac a very very long time ago.  You can search through the Github issues and you may be able to find some issues having to do with MVU (there should be very few).

**Comment by jeffin143** [comment]
Thanks @rcurtin , I am closing this issue.
