### ISSUE TITLE
mlpack cmake error:

### ISSUE THREAD

**Issue by zhaohaixu** [mlpack/mlpack#1838]
![TIM图片20190405111026](https://user-images.githubusercontent.com/49297029/55601420-710d0b00-5793-11e9-9be4-16bed06819fc.png)

**Comment by rcurtin** [comment]
Is there a reason you didn't use the issue templates?

It looks like the relevant error is above the line you circled.

**Comment by monicayao** [comment]
Download doxygen following instructions from here!
http://www.doxygen.nl/download.html
