### ISSUE TITLE
Regarding Python dependencies

### ISSUE THREAD

**Issue by chandramoulirajagopalan** [mlpack/mlpack#1839]
#### Problem location

MLpack Documentation .Readme
#### Description of problem

The documentation doesn't specifically talk about python dependencies as they are generalised for python2.x. I would like the documentation to be more particular for different python versions as python2.x will be deprecated soon.

**Comment by rcurtin** [comment]
Please point to the exact documentation that is not compatible with Python 3.  The dependencies in the readme are not specific to any version of Python.

**Comment by chandramoulirajagopalan** [comment]
I will make changes to the documentation by today.
