### ISSUE TITLE
Some expired URLs on the website https://www.mlpack.org 

### ISSUE THREAD

**Issue by Akeepers** [mlpack/mlpack#1844]
#### Problem location

[python quickstart](https://www.mlpack.org/doc/mlpack-3.0.4/doxygen/python_quickstart.html)

* [Python mlpack binding documentations](http://www.mlpack.org/docs/mlpack-git/python.html)
* [mlpack C++ tutorials](http://www.mlpack.org/docs/mlpack-git/doxygen/sample.html)
* [Simple sample C++ mlpack programs](http://www.mlpack.org/docs/mlpack-git/python.html)
* [mlpack Doxygen documentation homepage](http://www.mlpack.org/docs/mlpack-git/doxygen/tutorials.html)

###### 404
Not Found

**Comment by MuLx10** [comment]
Replace [http://www.mlpack.org/docs/*](#) with [http://www.mlpack.org/doc/*](#)

**Comment by zoq** [comment]
@Akeepers nice picture, looks like Spotify.

**Comment by rcurtin** [comment]
I think they are mentioned in the documentation on the new site that is for the old versions.  Probably I can just fix this with some regex on the Doxygen documentation for old versions.  I'll do that when I have a chance (so it will be a little while) unless someone beats me to it with the scripts on mlpack.org.  But I am not sure those are very easy to approach...

**Comment by zoq** [comment]
Ahh, haven't checked the python quickstart link.

**Comment by Akeepers** [comment]
> Replace [http://www.mlpack.org/docs/*](#) with [http://www.mlpack.org/doc/*](#)
I tried, but it still doesn't work. Actually, I found more expired URLs in Wiki, such as [list of tutorials](http://mlpack.org/docs/mlpack-git/doxygen/tutorials.html)

**Comment by rcurtin** [comment]
No need to close this yet, I still have one or two things to fix. :+1: Working on it, but rebuilding the website is a bit slow.

**Comment by rcurtin** [comment]
It took me a while but I finally got this to work right.  Let me know if you find any more issues, and thanks for reporting! :+1:
