### ISSUE TITLE
RNN: Fails to run Predict() if called before Train().

### ISSUE THREAD

**Issue by MuLx10** [mlpack/mlpack#1846]
#### Issue description
```c++
  const size_t rho = 5;
  arma::cube questions = arma::ones(1,2,rho);
  arma::cube answers = arma::ones(1,2,rho);
  
  mlpack::ann::RNN<mlpack::ann::MeanSquaredError<> > model(rho);
  model.Add<mlpack::ann::Linear<> >(1, 10);
  model.Add<mlpack::ann::LSTM<> >(10,10);
  model.Add<mlpack::ann::Linear<> >(10, 1);
  
  model.Parameters().randu();
  model.Predict(questions, answers);
```
Running the above snippet produces :
```bash
error: Mat::submat(): indices out of bounds or incorrectly used
  terminate called after throwing an instance of 'std::logic_error'
    what():  Mat::submat(): indices out of bounds or incorrectly used
  Aborted (core dumped)
```
However, if the last line in the above snippet is replaced by:
```c++
model.Train(questions, answers);
model.Predict(questions, answers);
```
It works perfectly. 
#### Steps to reproduce

Running the [code](https://pastebin.com/LNafNMUu).

#### Expected behaviour

RNN class methods Predict() and Train() (actually Evalute()) should be consistent.

#### Actual behavior

Fails to run Predict() if called before Train()/ Evaluate().

**Comment by chandramoulirajagopalan** [comment]
Can I work on this issue ? Should we just modify the predict function to call train and evaluate in itself implicitly not explicitly by the user ? Will that work ?

**Comment by RMaron** [comment]
I have the same problem, it has something to do with the model's parameters not being initialized beforehand. You can try printing the parameters before calling Train, they're empty. Predict does call Reset() if they're empty but for some reason that doesn't seem to do anything.

**Comment by MuLx10** [comment]
@chandramoulirajagopalan I figured out the fix. I guess calling Train() inside Predict is not a good way. One reason would be that targets are not available. Also, Training may take time. Usually Predict is called to check whether the output shapes are consistent. @RMaron Reset() is called in both however, some parameters like `outputSize'  were only set during Evaluate().

**Comment by RMaron** [comment]
@MuLx10 The error is caused directly by outputsize being 0. 1 is subtracted from it and it underflows. Then it tries to use that number as an index

**Comment by MuLx10** [comment]
@RMaron Exactly.
