### ISSUE TITLE
An alternate for imputation handling

### ISSUE THREAD

**Issue by jeffin143** [mlpack/mlpack#1854]
Currently we use our imputer function to handle missing data, no doubt it is good to handle using imputer function, but we could look for some alternative.

Instead of a user handle missing values we could let our algorithms handle it. Some ways to handle may be,Duplicates may be there :
 

- Allow our algorithm to call the imputer function via a **constructor internally**, for example 
      `LinearRegression() : lambda(0.0), intercept(true) { imputer() }`
      May be not so good because , a user could implement a pipeline -> imputer -> linear regression 

- Allowing our algorithm to **ignore** the missing values when generating splits 
   `Again an over head may be`

- **Gilles' suggestion** : We could send the missing valued samples to either side while finding splits and choose the direction that bring the maximum reduce in entropy.This is conceptually same as the "separate-class-method", where the missing values are considered as a separate categorical value. This is considered by [Ding and Simonoff's paper](http://people.stern.nyu.edu/jsimonof/jmlr10.pdf) to be the best method in different situations.

- In same paper : **Probabilistic method** - both children would receive missing values, but are weighed with a proportion of the number of non-missing values in each split.
    For example  - [ 4, 5 , nan, nan 6, nan] : split would be (4 5) (6) so making them equal and then having two class [(4 5 nan)] [ (6 nan nan) ]
    

- Use **machine Learning** to fill up the missing values :
    Use the missing values feature as target variable and perform ml using other features and predict the missing values
 Computationally very costly, but more accurate imputation possible

- Using  median of the **k-nearest neighbors** for imputation , [example](https://medium.com/airbnb-engineering/overcoming-missing-values-in-a-random-forest-classifier-7b1fc1fc03ba)

It would be good, if we can implement some if not all in mlpack, may be some with slight optimization or may be make some of them robust.Would love to have inputs from other contributors and collaborators. This [research work](http://people.stern.nyu.edu/jsimonof/jmlr10.pdf) could be a good starting point. Some of the python libraries do have some of these implemented and on the way to implement others. 

cc @ShikharJ @zoq @rcurtin @akhandait

**Comment by greatsharma** [comment]
I agree, me to think that we have very few and less robust methods for imputation in mlpack. I indeed added one new method which impute mode for voids in the dataset in PR #1790 but still it's not that robust method of imputation. And I personally think that we should go with hot deck imputation method ( indeed I decided to work on it ) or other imputation method like knn which might be computationally expensive but is very robust and better imputation methods. And at the end it's the call of the user what to use, we just can provide them all possible ways of doing that

**Comment by greatsharma** [comment]
Apart from this I also think that there are very few metric classes in mlpack. Some extensively used metrics like R2 and adjR2 for regression are missing which are widely used. Apart from this some metric for classification is also missing. I indeed took an initiative for this around 3 weeks back by adding various new metric classes in PR #1796 with tests.

Apart from this we only have one error i.e.,MSE other important error metric like MAE and RMSE are missing although user can call MSE and then take root to calculate RMSE but still it's very frequently used metric so we should be giving that as a feature but MAE should be there because it is very common and cannot be calculated use mse. I also took an initiative for this in my PR #1836.

Please review them as they seems to be promising

**Comment by rcurtin** [comment]
It would be really hard to expect the algorithm to handle missing values.  Not every algorithm is designed to handle that, and it would be a non-trivial research task to adapt some of them.

So I would suspect that it would be best for us to stick to our current abstraction of "data is an Armadillo matrix that has real-valued numbers for each entry".  I hope this comment is helpful to your ideas. :+1:

**Comment by jeffin143** [comment]
@rcurtin , Yep thanks :)
