### ISSUE TITLE
Question on Running ANN example,"ensmallen.hpp" cannot be found

### ISSUE THREAD

**Issue by dbsxdbsx** [mlpack/mlpack#1866]
I followed official tutorial [here ](http://mlpack.org/doc/mlpack-3.0.4/doxygen/build_windows.html)to build MLPACK.  But i failed to compile example for ann which taught [here](https://medium.com/@vedant_bassi/extremely-efficient-feedforward-neural-network-implemented-in-mlpack-a-basic-tutorial-9bc516ce9576) on win10.   The error is "No such file or directory".  

Indeed, I found "ensmallen.hpp" in `C:\mlpack\mlpack-3.0.4\build\deps\ensmallen-1.14.2\include\ensmallen.hpp>`. But even when I copyed the path in ffn.hpp:
```
//#include <ensmallen.hpp>
#include <C:\mlpack\mlpack-3.0.4\build\deps\ensmallen-1.14.2\include\ensmallen.hpp>
```
It raised other errors. So I guess this is not a proper way to modify.
Does it mean that I need to rebuild MLPACK with some option, so that I can take advange of  "ensmallen.hpp"?

**Comment by rcurtin** [comment]
Can you try adding `C:\mlpack\mlpack-3.0.4\build\deps\ensmallen-1.14.2\include` to the include directories for the project?

**Comment by dbsxdbsx** [comment]
@rcurtin ，thanks, it issue is solved by including this path, but there seems several libs should be included, as it pops errors like .
Besides, when I searching ANN tutorial of MLPACK, the 1st 3 links should be helpful, but the [links](https://www.google.com.hk/search?hl=zh-CN&q=mlpack%20%20neural%20network) are not valid any more.

**Comment by sreenikSS** [comment]
> Besides, when I searching ANN tutorial of MLPACK, the 1st 3 links should be helpful, but the links are not valid any more

@dbsxdbsx the website (and its address) has been updated. Google still points to the old site, you can switch to the new site by replacing *docs* with *doc* in the link. For example, the ANN tutorial site is now:
https://www.mlpack.org/doc/mlpack-git/doxygen/anntutorial.html

> but there seems several libs should be included, as it pops errors like LNK2019 LNK1120 . But I don't know what other libs I should include

This might be a linking error. #1687 might help you.

> Does it mean that I need to rebuild MLPACK with some option, so that I can take advange of "ensmallen.hpp"?

You do not need to build mlpack differently to include ensmallen. Just do not forget to include ensmallen.hpp and use the namespace `ens`.

Since this is quite a late response you might have solved these already, however, please let me know if something does not work out according to what I have mentioned.

**Comment by dbsxdbsx** [comment]
@sreenikSS , thanks. I  would give it a try soon.

**Comment by dbsxdbsx** [comment]
@sreenikSS, I tried it just now.  Still , errors like LNK2019 LNK1120 still pos up, but this time I notice  that the lib that it could not find related to blas. And What I've configured with this project is just like that taught in[ RandomForest Example](http://mlpack.org/doc/mlpack-3.0.4/doxygen/sample_ml_app.html) :
```
#include path
C:\boost\boost_1_70_0
C:\mlpack\armadillo-9.300.2\include
C:\mlpack\mlpack-3.0.4\build\include
C:\mlpack\mlpack-3.0.4\build\deps\ensmallen-1.14.2\include

#lib
C:\mlpack\mlpack-3.0.4\build\Debug\mlpack.lib
C:\boost\boost_1_70_0\lib64-msvc-14.1\libboost_program_options-vc141-mt-gd-x64-1_70.lib
C:\boost\boost_1_70_0\lib64-msvc-14.1\libboost_serialization-vc141-mt-gd-x64-1_70.lib
```
Then, as I took visual studio 2017 as tool on win10,   I configure it with Openblas in ` NuGet Package Manager `of visual studio. Now it worked. 
But I wonder why there is no need to configure openblas in the RandomForest example--- it should take openblas too, I think.

**Comment by sreenikSS** [comment]
Glad it is fixed. I don't have much knowledge about anything Windows specific or Visual Studio specific (I use Visual Studio Code on Linux Mint), but what I did was configure VSCode to compile it with the following flags:

`-std=c++11 -lboost_serialization -lboost_program_options -usr/local/cuda/lib64/libnvblas.so -larmadillo -lopenblas -lmlpack`

-lnvblas is optional of course given that you have it configured.
