### ISSUE TITLE
clion+mlpack

### ISSUE THREAD

**Issue by yangninghua** [mlpack/mlpack#1867]
clion+mlpack
``
/home/spple/clion-2018.2.5/bin/cmake/linux/bin/cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" /home/spple/code/mlpack-mlpack-3.0.4
-- cotire 1.7.10 loaded.
-- Armadillo libraries: /usr/lib/libarmadillo.so
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
--   unit_test_framework
--   serialization
CMake Warning at CMakeLists.txt:425 (message):
  txt2man not found; man pages will not be generated.

-- Found Python: /usr/bin/python
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/spple/code/mlpack-mlpack-3.0.4/cmake-build-debug

Problems were encountered while collecting compiler information:
	cc1plus: fatal error: /home/spple/code/mlpack-mlpack-3.0.4/cmake-build-debug/src/mlpack/cotire/mlpack_CXX_prefix.hxx: No such file or directory
	cc1plus: fatal error: /home/spple/code/mlpack-mlpack-3.0.4/cmake-build-debug/src/mlpack/tests/cotire/mlpack_test_CXX_prefix.hxx: No such file or directory

[Finished]
``

**Comment by zoq** [comment]
At a first glance this looks really similar to: https://github.com/mlpack/mlpack/issues/1530, which was fixed in https://github.com/mlpack/mlpack/pull/1537. Do you mind to rerun the build against the master branch?

**Comment by MathsionYang** [comment]
您还，我想问一下，您解决了那个关于Graph Cut RANSAC

**Comment by MathsionYang** [comment]
代码有一些错误，我解决不了，您若有时间，请帮我一下1114809057@qq.com
