### ISSUE TITLE
Enforcing Conformance Mode breaks arma_rng.hpp:444 [Windows / VS]

### ISSUE THREAD

**Issue by gmanlan** [mlpack/mlpack#1873]
#### Issue description

Because Conformance Mode is enabled by default in Visual Studio, attempting to compile an mlpack program will fail with the error:

Error C2760 syntax error: unexpected token 'identifier', expected ';' \armadillo-9.300.2\include\armadillo_bits\arma_rng.hpp 444

I have reported this to Microsoft already but it seems the issue is still around. See here:
https://developercommunity.visualstudio.com/solutions/275835/view.html

Because I have noticed mlpack users are still facing this issue, it would be appropriate to add a note in the documentation (maybe in the Windows tutorial?).

#### Your environment

 * version of mlpack: 3.0.4
 * operating system: windows
 * compiler: msvc
 * version of dependencies (Boost/Armadillo): boost 1.65.1, armadillo 9.300.2

#### Steps to reproduce

Try to follow the Windows tutorial to build the sample ML app using Visual Studio.

#### Expected behavior

Sample app should build without problems.

#### Actual behavior

Sample app fails to build because of a conformance mode issue. To workaround this, disable conformance mode in C/C++ > Language > Conformance mode

**Comment by conradsnicta** [comment]
@gmanlan - For any issues relating to Armadillo, use the issue tracker at GitLab:
https://gitlab.com/conradsnicta/armadillo-code/issues

The relevant code in Armadillo is:

    template<typename T>
    struct arma_rng::randn< std::complex<T> >
      {
      inline
      operator std::complex<T> () const
        {
        T a = T(0);
        T b = T(0);
        
        arma_rng::randn<T>::dual_val(a, b);
        
        return std::complex<T>(a, b);
        }
        
       // ... more functions ...
       };

The "problem" appears with the initialisation of the `a` and `b` variables, ie. `T a = T(0);`.  This uses standard C++ initialisation and casting, like `double a = double(0)`.  The explicit casting here is to prevent paranoid compilers issuing warnings about implicit type conversion.  So the C2760 syntax error is bogus (ie. false positive).  

As a possilble workaround, try changing the declaration of the `a` and `b` variables to:

        T a(0);
        T b(0);

or

        T a = 0;
        T b = 0;

Let me know which one of the above works, and I'll incorporate this into Armadillo.

**Side note:** for any real work, I'd suggest that you save yourself (many) headaches and use a proper compiler like gcc or clang.  From experience over many years, the MSVC "compiler" is not exactly known to be of high quality.  I'm not convinced that the folks responsible for developing MSVC actually know what they are doing.

**Comment by jeffin143** [comment]
> @gmanlan - For any issues relating to Armadillo, use the issue tracker at GitLab:
> https://gitlab.com/conradsnicta/armadillo-code/issues
> 
> The relevant code in Armadillo is:
> 
> ```
> template<typename T>
> struct arma_rng::randn< std::complex<T> >
>   {
>   inline
>   operator std::complex<T> () const
>     {
>     T a = T(0);
>     T b = T(0);
>     
>     arma_rng::randn<T>::dual_val(a, b);
>     
>     return std::complex<T>(a, b);
>     }
>     
>    // ... more functions ...
>    };
> ```
> The "problem" appears with the initialisation of the `a` and `b` variables, ie. `T a = T(0);`. This uses standard C++ initialisation and casting, like `double a = double(0)`. The explicit casting here is to prevent paranoid compilers issuing warnings about implicit type conversion. So the C2760 syntax error is bogus (ie. false positive).
> 
> As a possilble workaround, try changing the declaration of the `a` and `b` variables to:
> 
> ```
>     T a(0);
>     T b(0);
> ```
> or
> 
> ```
>     T a = 0;
>     T b = 0;
> ```
> Let me know which one of the above works, and I'll incorporate this into Armadillo.
> 
> **Side note:** for any real work, I'd suggest that you save yourself (many) headaches and use a proper compiler like gcc or clang. From experience over many years, the MSVC "compiler" is not exactly known to be of high quality. I'm not convinced that the folks responsible for developing MSVC actually know what they are doing.

@conradsnicta , Your last line was a gem . :-p

**Comment by gmanlan** [comment]
Thanks @conradsnicta. I'm actually ok with the issue (I use the workaround) and you are right, it's a bogus MSVC implementation. However this impacts mlpack because new Windows users are immediately thrown away with an issue like this one. For instance, if you download mlpack and attempt to run the bundled sample-ml-app it will not work because of this. Therefore, in an effort to polish these tiny but important details, I submitted this issue to see if we can either fix it or at least document the workaround I found for MSVC. Again, you are right about gcc/clang, but we can't ignore the rest of the world and that's why mlpack supports Windows/MSVC. I will try your suggestion and report back. Thanks!

**Comment by gmanlan** [comment]
@conradsnicta : I have tried the initialization changes you suggested but none of these worked. Errors are pretty much the same as before:
![errors](https://user-images.githubusercontent.com/40178166/57004267-77b85380-6b82-11e9-8428-b261786cf6e6.png)

**Comment by conradsnicta** [comment]
@gmanlan - Well, here we have proof once again that MSVC is not exactly reliable. Since there is no possible workaround, the fix must be made in MSVC.

Maybe they pulled their fingers out and fixed this bug in a more recent version of MSVC ?

**Comment by conradsnicta** [comment]
@gmanlan - Well, here we have proof once again that MSVC is not exactly reliable. Since there is no possible workaround, the fix must be made in MSVC.  Maybe they pulled their fingers out and fixed this bug in a more recent version of MSVC ?

Over at the so-called "developer community", there is post by Phil Reid dated 07 Aug 2018, stating that "seems to work for me with 15.8.0 preview 5.0".  Then Blair Wang, dated 17 Aug  2018, states: "This issue has been fixed and is now available in our latest update"
https://developercommunity.visualstudio.com/content/problem/189476/cannot-compile-the-armadillo-library.html

More relevant threads:
https://developercommunity.visualstudio.com/content/problem/242307/armadillo-compatibility.html

The latest post seems to be dated 09 Apr 2019, also stating that "A fix for this issue has been released! Install the most recent release":
https://developercommunity.visualstudio.com/content/problem/228194/when-i-compiled-armadillo-in-compiling-vs2017-i-ge.html

**Comment by gmanlan** [comment]
Perfect timing.
So I have faced this dilemma many times already since last year: I just updated to the latest VS version, and that indeed solves the problem with Armadillo (conformance mode is enabled and it doesn't complain about arma_rng.hpp). The downside is that the last three versions of VS are introducing a new issue with mlpack:

`Error C3546	'...': there are no parameter packs available to expand	sample-ml-app	\build\include\mlpack\core\cv\meta_info_extractor.hpp	51`

Which is another issue that I have also already reported to Microsoft: https://developercommunity.visualstudio.com/comments/387643/view.html

...and they keep claiming it's fixed but it's not! I have also asked them to put mlpack into their testing, but who knows if that's happening.

So the contradictory options are:
a) downgrade to an older VS to get rid of the mlpack C3546 issue (param expansion issue), but face the armadillo one
b) upgrade to a recent version of VS to get rid of the armadillo C2760 issue, but face the mlpack one

If these are the only options, then I would suggest (a) because Conformance Mode can be disabled and you will get a successful build. With (b) I don't have a workaround, unless we can do something on the mlpack side.

Thoughts @conradsnicta, @rcurtin ?

**Comment by gmanlan** [comment]
And it seems the mlpack issue "should" be fixed in an upcoming release of VS: https://developercommunity.visualstudio.com/content/problem/428732/159-c-compiler-regression-template-parameter-pack.html

**Comment by zoq** [comment]
The C3546 issue should be fixed with https://github.com/mlpack/mlpack/pull/1667, isn't that an option?

**Comment by gmanlan** [comment]
That's great @zoq ! I probably missed that as this bug was submitted for mlpack 3.0.4 and #1667 might be part of mlpack 3.1.0 - which was released just a few days ago. In that case, we can get a win-win by suggesting users to switch to the latest available Visual Studio to get rid of the armadillo (false positive) issue and use it to build mlpack 3.1.0.

**Comment by gmanlan** [comment]
Double checked that mlpack **3.1.0** with Visual Studio **15.9.11** works fine and is able to build the samepl-ml-app without disabling conformance mode.

**Comment by conradsnicta** [comment]
@gmanlan - looking forward to the next MSVC bug :)

**Comment by gmanlan** [comment]
FYI: https://developercommunity.visualstudio.com/content/problem/558844/error-c3546-there-are-no-parameter-packs-available.html
