### ISSUE TITLE
Two different versions of the Windows Build Tutorial co-existing (build_windows.html)

### ISSUE THREAD

**Issue by gmanlan** [mlpack/mlpack#1874]
#### Problem location

Website points to: http://mlpack.org/doc/mlpack-3.0.4/doxygen/build_windows.html
Readme.md points to: https://www.mlpack.org/doc/mlpack-git/doxygen/build_windows.html

#### Description of problem

The "build mlpack for Windows from source" documentation is duplicated and is different depending on how you navigate. If you access through the website, you get one version, if you access through the Readme.md, you get a different (more recent?) version.

- NOTE: the apparently more recent version of the tutorial is now confusing because it has "options" or "different paths" to follow during the procedure. For example, the tutorial originally provided cmake cmd line steps but now we are offering cmake GUI steps as well, all in the same place, without proper formatting. This is very confusing. Also, it seems we now support package installation via vcpkg, which again, it is explained without context, under the same page and without even a subtitle. So it would be nice to separate or reformat all this information:
1) Building from source using cmake (the original tutorial)
  1.b) Alternatively using cmake GUI
2) Alternatively, installing via vcpkg

**Comment by zoq** [comment]
Agreed this is somewhat confusing, since we already cover different build/installation it would be great if we could present each in a more structured view.

**Comment by gmanlan** [comment]
This issue is covered with: https://github.com/mlpack/mlpack/pull/1893
