### ISSUE TITLE
Using Sphinx for Documentation

### ISSUE THREAD

**Issue by amirmasoudabdol** [mlpack/mlpack#1877]
I'm wondering what you think about producing the HTML files using [Sphinx](https://www.sphinx-doc.org/en/master/). Besides looks, there are a lot of advantages here. The [reStructuredText](http://docutils.sourceforge.net/rst.html) is much more suitable for documentation and many projects adopted it already, e.g., GSL, Boost. Recent Sphinx can produce PDF via LaTeX as well which is handy.

The way it works is, we use Doxygen to produce the XML and Sphinx extensions like [Breathe](https://breathe.readthedocs.io/en/latest/) and [Exhale](https://exhale.readthedocs.io/en/latest/) handles XML and produce RST files for Sphinx to produce HTML or LaTeX.

I've already run a test and for the most parts, Breathe and Exhale handle inline comments pretty well and class documentation is clear. You can see an example below. 

What is missing is tutorials and that's because Doxygen handles them rather strangely. For instance if I just put them into a `.cpp` file then, I'll get them. A better way of course would be to convert them to `.rst` files and let Sphinx generate the HTML.

I was wondering what the community thinks about this? If you think this is something we are interested in, I can start slowly working on it. 

EDIT: I almost forget to mention the reasoning being this. The reason being that Doxygen documentations are rather ugly, hard to navigate and outdated. I think it's important that documentation looks and behaves modern and be accessible for many people on different devices.

![Screen Shot 2019-04-25 at 16 54 52](https://user-images.githubusercontent.com/1290841/56745620-fffdb980-677a-11e9-8ca3-651620933d3d.png)

**Comment by rcurtin** [comment]
Hey @amirmasoudabdol, I think a lot of your concerns are spot on and it seems like there could be some improvement by using Sphinx.

> What is missing is tutorials and that's because Doxygen handles them rather strangely.

Oh absolutely, what we have now in `doc/guide/` is really not great.  It might be nice to adapt and rewrite these in some cleaner way.

> EDIT: I almost forget to mention the reasoning being this. The reason being that Doxygen documentations are rather ugly, hard to navigate and outdated. I think it's important that documentation looks and behaves modern and be accessible for many people on different devices.

Yeah, it is true.  I did a lot of work to clean up the formatting of different Doxygen pages.  Here's an example:

http://mlpack.org/doc/stable/doxygen/classmlpack_1_1neighbor_1_1NeighborSearch.html#affa7257868588792956a7f30493ae564

There was a lot of CSS work that went into making those arguments line up nicely, and if we adapted to something new I'd want to make sure that we can still provide that.  Probably the CSS work I already did can be adapted.

Also, does Sphinx work better with awful template types?  Example of Doxygen garbage:

http://mlpack.org/doc/stable/doxygen/classmlpack_1_1neighbor_1_1NeighborSearch.html#details

If you can provide some examples of how these types of difficult template classes would look with Sphinx, I think it would help me in understanding the benefits.  In any case, there are a lot of disadvantages to Doxygen's output that could be improved upon.

The last bit is making sure that we can integrate it with the website's automatic update process.  In short, mlpack.org is a Jekyll site, but before the Jekyll site is built, the Doxygen HTML documentation is built and somewhat modified so it fits with the site's theme, and then Jekyll just copies the HTML to the right place.

Hopefully this is clarifying---let me know what you think. :+1:

**Comment by amirmasoudabdol** [comment]
Hi Ryan,

Thanks for the reply. I can see some of the complications but hopefully we can work though them, the example you've mentioned for long template types would look like this.

![Screen Shot 2019-04-29 at 09 57 27](https://user-images.githubusercontent.com/1290841/56882866-38481500-6a65-11e9-9b1a-2eaa9d16e085.png)

You see that Sphinx decides to link to classes in the template definition and use the table just for description. I think this is fine and makes the signature less uniform and more readable but we can work around it probably and maybe put the link in both, or get something similar to the current format.

Regarding the parameters formatting, although I think it's nice but I am in favor of doing least amount of hacking both to the CSS and the documentation engine as possible, because hacks will tighten our hands when it comes to updates and upgrades. So, there is a danger that we got stuck with an older configuration for years again. Moreover, I'm a bit concern that the extra padding and margin that we enforce will break that responsiveness of the page which I think we should try to avoid. That being said, if we can do it at the CSS level — and you mentioned you did — it should be possible to modify the CSS and possibly get the same result. I'll try to look into that too.

Regarding the deploy process, I think Sphinx will do just fine with Jekyll. You get a complete HTML/CSS/JS out of it and it's easy to deploy that on Github or any other hosting platform, with a very similar process to what you used to with Jekyll and Doxygen. 

Your comment was indeed very useful. Please let me know if you know any other edge cases, or complicated function signatures that I need to consider. Or, any other concerns that you have. In the meantime, I'll slowly try to prepare a RP with a Sphinx configuration and correct build that you see it in action. 

I'll leave the guides out for now, let's see if we can get the Doc -> Doxygen -> Sphinx -> HTML in a way we want too. I'm less worried about them now, they are usually less tricky.

**Comment by rcurtin** [comment]
Hey @amirmasoudabdol, sorry for the slow response---I got busy with some other things.  The bit that you posted looks nice, but I hae a big concern about how the template parameters for `NeighborSearch` are printed.  Data scientists are already (in general) scared of C++ and that won't help, so providing readable and good documentation is really important.

> Regarding the parameters formatting, although I think it's nice but I am in favor of doing least amount of hacking both to the CSS and the documentation engine as possible, because hacks will tighten our hands when it comes to updates and upgrades.

Yeah, I know where you are coming from when you say this, but in my view, "good user experience plus less good upgradeability" is better than "bad user experience but really easily upgradeable".  The set of hacks I do for the website include parsing the output that it gives for template types and inserting more tags and spans so that I can then handle it and format it nicely with CSS.

I do it like this:

https://github.com/mlpack/mlpack.org/blob/master/_src/doxygen/html_template_labeler.py

It's not really a huge problem to adapt that to newer versions, since Doxygen doesn't update too often.  I'd imagine the same is true with Sphinx---so I don't have an issue if we come up with a kind of hacky solution to be able to style those reasonably.

> Your comment was indeed very useful. Please let me know if you know any other edge cases, or complicated function signatures that I need to consider.

Hehe, basically everything is templated like that throughout the library (and if it's not that templated now, it probably will be at some point).  That would be most of the edge cases, I think.

> I'll leave the guides out for now, let's see if we can get the Doc -> Doxygen -> Sphinx -> HTML in a way we want too. I'm less worried about them now, they are usually less tricky.

Agreed, the guides should perhaps be rewritten to interface more directly with Jekyll, like maybe someday we should rewrite them in Markdown or something.

Let me know how it's going---I'm happy to help try and adapt the scripts to label template parts if you like.

**Comment by zoq** [comment]
Let us keep this open.

**Comment by rcurtin** [comment]
@amirmasoudabdol just checking in to see, are you still interested in looking into this?

**Comment by amirmasoudabdol** [comment]
@rcurtin I'm, and I actually ran quite a few tests and experiments, but I had to do some "real" work and had to stop with this. One of the main difficulties was super slow build of Sphinx. While this is expected, it makes experimenting rather cumbersome. I try to see if I can pick it up again.

**Comment by rcurtin** [comment]
@amirmasoudabdol ah, yeah; well, if it makes you feel better, mlpack itself already builds slowly so if Sphinx does too it is not the biggest issue for deployment. :)  Of course I can see how that would make development hard though...

@gmanlan has put together a new prototype website at https://github.com/mlpack/mlpack.org/pull/9 and suggested that moving to Sphinx could really help clean things up.

If I can be helpful during the experimentation process just let me know!  I'm not a Sphinx expert but I am an mlpack expert. :smile:
