### ISSUE TITLE
Hello, I have compiled mlpack using vcpkg on windows. How can I find data.csv and other files?

### ISSUE THREAD

**Issue by yangninghua** [mlpack/mlpack#1883]
Hello, I have compiled mlpack using vcpkg on windows. How can I find data.csv and other files?

>#pragma once
#pragma execution_character_set("utf-8")
// Includes all relevant components of mlpack.
#include <mlpack/core.hpp>
// Convenience.
using namespace mlpack;
int main()
{
	// First, load the data.
	arma::mat data;
	// Use data::Load() which transposes the matrix.
	data::Load("data.csv", data, true);
	// Now compute the covariance.  We assume that the data is already centered.
	// Remember, because the matrix is column-major, the covariance operation is
	// transposed.
	arma::mat cov = data * trans(data) / data.n_cols;
	// Save the output.
	data::Save("cov.csv", cov, true);
}

**Comment by rcurtin** [comment]
Any file that you have will work; `data.csv` is just meant as a placeholder.  So you can just get a CSV that contains numeric data.  Here's one: http://ratml.org/datasets/winequality.csv
