### ISSUE TITLE
Random forest implementation not available in Linux installation. 

### ISSUE THREAD

**Issue by pranka02** [mlpack/mlpack#1909]
I am installing it using apt like this "$ sudo apt-get install libmlpack-dev". 
Other methods work fine.

**Comment by rcurtin** [comment]
I can't make heads or tails of this.  How are you installing?  What version are you using?  Do you mean for the Python bindings or the command-line programs?  We wrote the issue templates for a reason...

**Comment by yashagrawal3** [comment]
Hello @rcurtin , I installed mlpack using `$ sudo apt-get install libmlpack-dev` and tried running example mentioned in [quickstart](https://www.mlpack.org/doc/mlpack-3.2.2/doxygen/cli_quickstart.html), but CLI shows `zsh: command not found: mlpack_random_forest
`. Any suggestions on how I can fix it?

**Comment by rcurtin** [comment]
Hey @yashagrawal3, you should feel free to open a new issue for this. :+1:  The quickstart points out that the package name is `mlpack-bin`---on Debian and Ubuntu, it's split into a few different packages (`libmlpack3` for the shared library itself, `mlpack-bin` for the command-line programs, `mlpack-doc` for documentation, and `libmlpack-dev` for headers).  Can you tell me what part of the documentation suggested `libmlpack-dev` so that I can update it and add `mlpack-bin` to the list?  Thanks!

**Comment by yashagrawal3** [comment]
I started from [quickstart](https://www.mlpack.org/doc/mlpack-3.2.2/doxygen/cli_quickstart.html) and used the command `sudo apt-get install mlpack-bin` as mentioned. Following example failed to run showing `zsh: command not found: mlpack_random_forest`. Then went onto [this](https://www.mlpack.org/doc/mlpack-3.2.2/doxygen/build.html) page and installed `libmlpack-dev`, but random forest still seems to be absent. I am avoiding building from source at this point.

**Comment by rcurtin** [comment]
What version of mlpack did you install?  Did you check that random forests are available in that version?

**Comment by yashagrawal3** [comment]
version`2.2.5-1build1`, It says it's the latest version. Since random forest was mentioned in the very first example, I assumed it will come pre-installed with the latest version.

**Comment by rcurtin** [comment]
The latest version of mlpack is 3.2.2.  You can see from the changelog that random forests were added in version 3.0.0: http://mlpack.org/doc/mlpack-3.2.2/cli_documentation.html#mlpack-300

You'll have to file a bug with the Ubuntu packagers to have them pull a newer version in.  Your other options are to use a newer version of Ubuntu (here is the list of Ubuntu versions and mlpack versions: https://packages.ubuntu.com/search?keywords=mlpack-bin) or to build from source. :+1:
