### ISSUE TITLE
mlpack 3.1.1 fails to compile with gcc 9.1.0 and USE_OPENMP=yes

### ISSUE THREAD

**Issue by janbraun** [mlpack/mlpack#1928]
#### Issue description

I cannot compile mlpack 3.1.1 with openmp support when using gcc 9.1.0.
Compiling without openmp support (USE_OPENMP=no) and gcc 9.1.0 works fine.

Compilation with openmp support and clang 8.0.0 also works.

#### Your environment

 * version of mlpack: 3.1.1
 * operating system: Gentoo Linux
 * compiler: gcc 9.1.0
 * version of dependencies (Boost/Armadillo): boost 1.65, armadillo 9.200.6
 * any other environment information you think is relevant:

#### Steps to reproduce

 1. Unpack sources
 2. Change to source dir, create build dir and change to that.
 3. Call cmake with -DUSE_OPENMP=yes ```cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_CLI_EXECUTABLES=yes -DDEBUG=no -DARMA_EXTRA_DEBUG=no -DBUILD_MARKDOWN_BINDINGS=no -DMATHJAX=yes -DUSE_OPENMP=yes -DPROFILE=no -DBUILD_PYTHON_BINDINGS=no -DBUILD_TESTS=no -DMATHJAX_JS_PATH=/usr/share/mathjax/MathJax.js ..```
 4. Call `ninja`

#### Expected behavior

Compilation completes

#### Actual behavior

Compilation fails for src/mlpack/methods/det/CMakeFiles/mlpack_det.dir/det_main.cpp.o

Call ```/usr/bin/c++  -DARMA_NO_DEBUG -DBOOST_TEST_DYN_LINK -DHAS_OPENMP -DNDEBUG -I../src -Isrc/mlpack/.. -fdiagnostics-color -fdiagnostics-color -Wall -Wextra -ftemplate-depth=1000 -O3 -fopenmp   -DBINDING_TYPE=BINDING_TYPE_CLI -std=gnu++11 -MD -MT src/mlpack/methods/det/CMakeFiles/mlpack_det.dir/det_main.cpp.o -MF src/mlpack/methods/det/CMakeFiles/mlpack_det.dir/det_main.cpp.o.d -o src/mlpack/methods/det/CMakeFiles/mlpack_det.dir/det_main.cpp.o -c ../src/mlpack/methods/det/det_main.cpp```

Output
 ```
In file included from ../src/mlpack/methods/det/dt_utils.hpp:147,
from ../src/mlpack/methods/det/det_main.cpp:15:
../src/mlpack/methods/det/dt_utils_impl.hpp: In function 'mlpack::det::DTree<MatType, TagType>* mlpack::det::Trainer(MatType&, size_t, bool, size_t, size_t, bool) [with MatType = arma::Mat<double>; TagType = int]':
../src/mlpack/methods/det/dt_utils_impl.hpp:189:3: error: 'folds' not specified in enclosing 'parallel'
189 |   for (omp_size_t fold = 0; fold < (omp_size_t) folds; fold++)
|   ^~~
../src/mlpack/methods/det/dt_utils_impl.hpp:187:11: error: enclosing 'parallel'
187 |   #pragma omp parallel for default(none) \
|           ^~~
../src/mlpack/methods/det/dt_utils_impl.hpp:192:33: error: 'testSize' not specified in enclosing 'parallel'
192 |     const size_t start = fold * testSize;
|                                 ^~~~~~~~
../src/mlpack/methods/det/dt_utils_impl.hpp:187:11: error: enclosing 'parallel'
187 |   #pragma omp parallel for default(none) \
|           ^~~
../src/mlpack/methods/det/dt_utils_impl.hpp:194:61: error: 'cvData' not specified in enclosing 'parallel'
194 |                                 * testSize, (size_t) cvData.n_cols);
|                                                      ~~~~~~~^~~~~~
../src/mlpack/methods/det/dt_utils_impl.hpp:187:11: error: enclosing 'parallel'
187 |   #pragma omp parallel for default(none) \
|           ^~~
../src/mlpack/methods/det/dt_utils_impl.hpp:222:5: error: 'minLeafSize' not specified in enclosing 'parallel'
222 |     cvDTree.Grow(train, cvOldFromNew, useVolumeReg, maxLeafSize,
|     ^~~~~~~
../src/mlpack/methods/det/dt_utils_impl.hpp:187:11: error: enclosing 'parallel'
187 |   #pragma omp parallel for default(none) \
|           ^~~
../src/mlpack/methods/det/dt_utils_impl.hpp:222:5: error: 'maxLeafSize' not specified in enclosing 'parallel'
222 |     cvDTree.Grow(train, cvOldFromNew, useVolumeReg, maxLeafSize,
|     ^~~~~~~
../src/mlpack/methods/det/dt_utils_impl.hpp:187:11: error: enclosing 'parallel'
187 |   #pragma omp parallel for default(none) \
|           ^~~
../src/mlpack/methods/det/dt_utils_impl.hpp:222:5: error: 'useVolumeReg' not specified in enclosing 'parallel'
222 |     cvDTree.Grow(train, cvOldFromNew, useVolumeReg, maxLeafSize,
|     ^~~~~~~
../src/mlpack/methods/det/dt_utils_impl.hpp:187:11: error: enclosing 'parallel'
187 |   #pragma omp parallel for default(none) \
|           ^~~
```

**Comment by janbraun** [comment]
The main difference when switching compilers seems to be that clang has openmp 3.1 and gcc has openmp 4.5, using their corresponding libraries.

**Comment by janbraun** [comment]
A similar bug seems to occur with blender, according to
https://bugs.gentoo.org/685922, which references
https://bugzilla.redhat.com/show_bug.cgi?format=multiple&id=1674700

the critical change in gcc 9 is due to a change in OpenMP 4.0:
https://gcc.gnu.org/gcc-9/porting_to.html#ompdatasharing

**Comment by zoq** [comment]
So my first guess is to change:

https://github.com/mlpack/mlpack/blob/e2f696cfd5b7ccda2d3af1c7c728483ea6591718/src/mlpack/methods/det/dt_utils_impl.hpp#L187-L188

to:

```c++
#pragma omp parallel for default(none) firstprivate(folds) \
      shared(prunedSequence, regularizationConstants)
```

if that works we could do this for the other cases as well, will check this tomorrow, unless you like to.

**Comment by janbraun** [comment]
Thanks for looking at this issue! When I am using
```
  #pragma omp parallel for default(none) \
      firstprivate(folds, testSize, cvData, minLeafSize, maxLeafSize, \
              useVolumeReg) \
      shared(prunedSequence, regularizationConstants)
 ```
i.e., including all variables gcc complains about, it compiles on.

But besides your guess and the referenced site saying "…Specifying them in firstprivate clause is one way to achieve compatibility with both older GCC versions and GCC 9…" I have no idea what the code actually needs.

**Comment by otto-dev** [comment]
I got this error when installing from the Arch Linux AUR package repository, but manually applying the solution in @janbraun 's post fixed it.

**Comment by rcurtin** [comment]
Could we also just drop the `default(none)`?  That seems to work on my system but I am not sure it works in all cases.

**Comment by rcurtin** [comment]
Just a ping on this one; has anyone affected by the issue tried dropping the `default(none)`?  If that works that seems like the easiest patch to merge.  But if nobody has a chance to check then I can just open a PR with @janbraun's fix.

**Comment by rcurtin** [comment]
I think now that #1970 is merged, this should be fixed.  Feel free to comment if the current master branch doesn't fix the issue, and we can reopen it. :)
