### ISSUE TITLE
'streaming' training data for ann

### ISSUE THREAD

**Issue by snakelizzard** [mlpack/mlpack#1929]
Hello.

Is it ok to call FNN/RNN Train method several times for different chunks of data? Or is it better to concat all data I have into single matrix and do training only once?

Thank you.

**Comment by zoq** [comment]
Hello, with different chunks do you mean you like to feed in parts of a single sequence or do you mean to split the training data and fine-tune the model step by step?

**Comment by snakelizzard** [comment]
I mean parts of same sequence.

**Comment by zoq** [comment]
I see, in this case you are better off to pass the complete sequence, haven't seen the need for a streaming mode yet, but perhaps there is need?

**Comment by snakelizzard** [comment]
I just do not like idea of loading several GB of data into memory.

**Comment by rcurtin** [comment]
Do you mean that a single sequence is several GB of memory?  Unfortunately I don't really know any tricks for that.  The only trick I can think of is really ugly: write a class with the same API as `arma::cube`, but make the rght amount of streaming data available at each `slice()` call.  That will, I guess, depend on how many BPTT time steps are being taken.  Anyway, I am not sure if what I wrote makes sense, but in any case it would not be trivial at all, unfortunately.

If a single data sequence *could* fit into memory well, then you could just call `Train()` repeatedly with individual sequences, which could fix the problem.

Also, if your sequences are so large or so long that holding them in memory is a problem, I might suggest that a recurrent neural network would have problems with "remembering" the important parts of a sequence that long.

Also also (sorry, this response is a bit stream-of-consciousness), maybe you can split your sequences into subsequences of manageable length and use the strategy of calling `Train()` repeatedly for each subsequence?

I hope any of this is helpful...

**Comment by snakelizzard** [comment]
Thanks. I am thinking in same direction. Other option can be de-duplicating part of look-alike fragments form whole sequence.
