### ISSUE TITLE
GradientAtrousConvolutionLayerTest fails more than 20% of the time

### ISSUE THREAD

**Issue by saksham189** [mlpack/mlpack#1936]
#### Issue description

GradientAtrousConvolutionLayerTest fails more than 20% of the time. The builds are unstable.

#### Your environment

 * version of mlpack:development
 * compiler: clang
 * version of dependencies (Boost/Armadillo):
 * any other environment information you think is relevant:

#### Steps to reproduce

Add `mlpack::math::RandomSeed(std::time(NULL));` at the top of the test.
and run using:
`i=0; while(true); do echo $i; bin/mlpack_test -t ANNLayerTest/GradientAtrousConvolutionLayerTest 2>&1 | grep 'fatal error'; i=$(($i + 1));done`

#### Expected behavior

The test should not fail.

#### Actual behavior

The test fails almost 20% of the time.

**Comment by saksham189** [comment]
This is due to  https://github.com/mlpack/mlpack/pull/1930 merged. 
Also the tolerance for the https://github.com/mlpack/mlpack/blob/master/src/mlpack/tests/ann_layer_test.cpp#L1901
test is `0.2` which is quite high.

**Comment by rcurtin** [comment]
See also #1661 and #1777---I think this has been going on for quite a while now.  Ideally I think we should fix it soon or comment out the tests and remove the layer, if we can't get it to work.  @ShikharJ you were working on this; have you had a chance to dig in any further?  What do you think the right way to go here is?

**Comment by rcurtin** [comment]
#1953 is an attempt to help with this but it doesn't seem to be a complete fix.  Still, I thought it was useful to reference it here.
