### ISSUE TITLE
undefined reference to `_gfortran_stop_string'

### ISSUE THREAD

**Issue by hlhis** [mlpack/mlpack#1937]
/usr/lib64/libarmadillo.so: undefined reference to `dzasum_'
/usr/lib64/libarmadillo.so: undefined reference to `dtbsv_'
/usr/lib64/libarmadillo.so: undefined reference to `strsm_'
/usr/lib64/libarmadillo.so: undefined reference to `ztrsm_'
/usr/lib64/libarmadillo.so: undefined reference to `cgerc_'
/usr/lib64/libarmadillo.so: undefined reference to `ssyr2_'
/usr/lib64/libarmadillo.so: undefined reference to `_gfortran_stop_string'
/usr/lib64/libarmadillo.so: undefined reference to `_gfortran_st_write'

i receive the above error while compiling mlpack, what is the reason maybe?

**Comment by rcurtin** [comment]
Hi @hlhis, this looks like Armadillo is linked against some libraries that aren't present on the system.  Can you say a little bit about how you installed Armadillo on the system?

**Comment by hlhis** [comment]
@rcurtin thank you, i have solved the problem, i built static library of lapack   at first, and got the above problem, after switched to dynamic library, the problem was solved

**Comment by rcurtin** [comment]
@hlhis great to hear you got it figured out. :+1: I'll go ahead and close this issue then.
