### ISSUE TITLE
MLPACK failed to run ANNLayerTest test on release and debug configuration with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [mlpack/mlpack#1940]
MLPACK failed to run ANNLayerTest test on release and debug configuration with MSVC on windows. I use latest version 897b0cd . Could you please help look at this? Thanks a lot!

You can repro this issue as the steps below:
1. git clone https://github.com/mlpack/mlpack D:\MLPACK\src
2. it dependent armadillo and OpenBlas, put them to D:\MLPACK\external\
3. open a VS 2017 amd64 command prompt as admin and browse to D:\MLPACK
4. mkdir build_x64 && pushd build_x64
5. cmake -G "Visual Studio 15 2017 Win64" -DBLAS_LIBRARY=D:\MLPACK\build_x64\..\external\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a -DLAPACK_LIBRARY=D:\MLPACK\build_x64\..\external\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a -DARMADILLO_INCLUDE_DIR=D:\MLPACK\build_x64\..\external\armadillo-9.200.4\include -DARMADILLO_LIBRARY=D:\MLPACK\build_x64\..\external\armadillo-9.200.4\lib\armadillo.lib -DBOOST_INCLUDEDIR=C:\boost_1_67_0\x64 -DBOOST_LIBRARYDIR=C:\boost_1_67_0\x64\lib64-msvc-14.1 -DDEBUG=OFF -DPROFILE=OFF ..\src
6. msbuild /m /p:Configuration=Release;Platform=x64;PreferredToolArchitecture=x64 mlpack.sln /t:Rebuild
7. ctest --build-config Release -V -R "ANNLayerTest"

[log_x64_test.log](https://github.com/mlpack/mlpack/files/3324453/log_x64_test.log)

Failures:

D:\MLPACK\build_x64>ctest --build-config Release -V -R "ANNLayerTest"
UpdateCTestConfiguration  from :D:/MLPACK/build_x64/DartConfiguration.tcl
UpdateCTestConfiguration  from :D:/MLPACK/build_x64/DartConfiguration.tcl
Test project D:/MLPACK/build_x64
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 6
    Start 6: ANNLayerTest
6: Test command: D:\MLPACK\build_x64\Release\mlpack_test.exe "-t" "ANNLayerTest"
6: Test timeout computed to be: 10000000
6: Running 66 test cases...
6: D:/MLPACK/src/src/mlpack/tests/ann_layer_test.cpp(1903): fatal error: in "ANNLayerTest/GradientAtrousConvolutionLayerTest": critical check CheckGradient(function) <= 0.2 has failed [1 > 0.20000000000000001]
6:
6: *** 1 failure is detected in the test module "mlpackTest"
1/1 Test #6: ANNLayerTest .....................***Failed    2.88 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   2.96 sec

The following tests FAILED:
          6 - ANNLayerTest (Failed)
Errors while running CTest

**Comment by zoq** [comment]
Thanks for the report, there is an open issue for the GradientAtrousConvolutionLayer: https://github.com/mlpack/mlpack/issues/1936, which should be the same issue you see on your system.
