### ISSUE TITLE
mlpack_test fails in execution of CFTest/RecommendationAccuracyBiasSVDTest

### ISSUE THREAD

**Issue by jwdinius** [mlpack/mlpack#1944]
#### Issue description

Unit testing fails when executing `mlpack_test` executable.

#### Your environment

 * version of mlpack: master @ 897b0cddf6ba23733f701b4679fac08f9f90ebb2 hash
 * operating system: Ubuntu 18.04
 * compiler: gcc 7.4.0
 * version of dependencies (Boost/Armadillo): Boost: 1.65.1, Armadillo: 9.599, Ensmallen: 9d2a5f07c63e292d116c5b182a7682615798f04e
 * any other environment information you think is relevant:

#### Steps to reproduce

After cloning mlpack, execute

```bash
mkdir build && \
    cd build && cmake .. -DENSMALLEN_INCLUDE_DIR=$PATH_TO_ENS/ensmallen/include && \
    make -j && ./bin/mlpack_test
```

`PATH_TO_ENS`  is the directory where I have ensmallen checked out to.

#### Expected behavior

Expect to see stdout

```
Running 1649 test cases...
[FATAL] Cannot open file 'nonexistentfile.arff'.

*** 0 failures detected in the test module "mlpackTest"
```
#### Actual behavior

Observed output was:

```
Running 1649 test cases...
/home/joe/github/sdrsac-cpp/external/mlpack/src/mlpack/tests/cf_test.cpp(217): fatal error: in "CFTest/RecommendationAccuracyBiasSVDTest": critical check failures < 17 has failed [19 >= 17]
[FATAL] Cannot open file 'nonexistentfile.arff'.

*** 1 failure is detected in the test module "mlpackTest"
```

**Comment by zoq** [comment]
mlpack has many tests that are probabilistic. Meaning that they can randomly fail, even when something isn't actually wrong with the code. However, in each case, we should make sure if the method is correct or if the test configuration isn't working for the random seed. So what I normally do is to add ``math::RandomSeed(std::time(NULL));`` to the test:


```c++
BOOST_AUTO_TEST_CASE(RecommendationAccuracyBiasSVDTest)
{
  math::RandomSeed(std::time(NULL));
  RecommendationAccuracy<BiasSVDPolicy>();
}
```

and then, run that the test in a loop to see how often it fails:

```bash
while(true); do bin/mlpack_test -t CFTest/RecommendationAccuracyBiasSVDTest; sleep 1; done
```

Perhaps you can modify the code as mentioned above and post the numbers for your system here?

**Comment by jwdinius** [comment]
Done: see raw output below.  Summary statistics: *5 / 50 failed*

Is it a good idea to have a unit test that can randomly fail?  With random processes, isn't it best practice to fix a seed for repeatability?

See raw output:
```
count=0
Running 1 test case...

*** No errors detected
count=1
Running 1 test case...

*** No errors detected
count=2
Running 1 test case...

*** No errors detected
count=3
Running 1 test case...

*** No errors detected
count=4
Running 1 test case...

*** No errors detected
count=5
Running 1 test case...
/home/joe/github/mlpack/src/mlpack/tests/cf_test.cpp(217): fatal error: in "CFTest/RecommendationAccuracyBiasSVDTest": critical check failures < 17 has failed [17 >= 17]

*** 1 failure is detected in the test module "mlpackTest"
count=5
Running 1 test case...

*** No errors detected
count=6
Running 1 test case...

*** No errors detected
count=7
Running 1 test case...

*** No errors detected
count=8
Running 1 test case...

*** No errors detected
count=9
Running 1 test case...

*** No errors detected
count=10
Running 1 test case...
/home/joe/github/mlpack/src/mlpack/tests/cf_test.cpp(217): fatal error: in "CFTest/RecommendationAccuracyBiasSVDTest": critical check failures < 17 has failed [18 >= 17]

*** 1 failure is detected in the test module "mlpackTest"
count=10
Running 1 test case...

*** No errors detected
count=11
Running 1 test case...

*** No errors detected
count=12
Running 1 test case...

*** No errors detected
count=13
Running 1 test case...

*** No errors detected
count=14
Running 1 test case...

*** No errors detected
count=15
Running 1 test case...

*** No errors detected
count=16
Running 1 test case...

*** No errors detected
count=17
Running 1 test case...

*** No errors detected
count=18
Running 1 test case...

*** No errors detected
count=19
Running 1 test case...

*** No errors detected
count=20
Running 1 test case...

*** No errors detected
count=21
Running 1 test case...

*** No errors detected
count=22
Running 1 test case...

*** No errors detected
count=23
Running 1 test case...

*** No errors detected
count=24
Running 1 test case...

*** No errors detected
count=25
Running 1 test case...

*** No errors detected
count=26
Running 1 test case...

*** No errors detected
count=27
Running 1 test case...

*** No errors detected
count=28
Running 1 test case...

*** No errors detected
count=29
Running 1 test case...

*** No errors detected
count=30
Running 1 test case...

*** No errors detected
count=31
Running 1 test case...

*** No errors detected
count=32
Running 1 test case...

*** No errors detected
count=33
Running 1 test case...

*** No errors detected
count=34
Running 1 test case...

*** No errors detected
count=35
Running 1 test case...
/home/joe/github/mlpack/src/mlpack/tests/cf_test.cpp(217): fatal error: in "CFTest/RecommendationAccuracyBiasSVDTest": critical check failures < 17 has failed [17 >= 17]

*** 1 failure is detected in the test module "mlpackTest"
count=35
Running 1 test case...

*** No errors detected
count=36
Running 1 test case...

*** No errors detected
count=37
Running 1 test case...

*** No errors detected
count=38
Running 1 test case...

*** No errors detected
count=39
Running 1 test case...

*** No errors detected
count=40
Running 1 test case...
/home/joe/github/mlpack/src/mlpack/tests/cf_test.cpp(217): fatal error: in "CFTest/RecommendationAccuracyBiasSVDTest": critical check failures < 17 has failed [17 >= 17]

*** 1 failure is detected in the test module "mlpackTest"
count=40
Running 1 test case...

*** No errors detected
count=41
Running 1 test case...

*** No errors detected
count=42
Running 1 test case...

*** No errors detected
count=43
Running 1 test case...

*** No errors detected
count=44
Running 1 test case...

*** No errors detected
count=45
Running 1 test case...

*** No errors detected
count=46
Running 1 test case...
/home/joe/github/mlpack/src/mlpack/tests/cf_test.cpp(217): fatal error: in "CFTest/RecommendationAccuracyBiasSVDTest": critical check failures < 17 has failed [17 >= 17]

*** 1 failure is detected in the test module "mlpackTest"
count=46
Running 1 test case...

*** No errors detected
count=47
Running 1 test case...

*** No errors detected
count=48
Running 1 test case...

*** No errors detected
count=49
Running 1 test case...

*** No errors detected
count=50
Running 1 test case...
```

**Comment by zoq** [comment]
Thanks for the data, it looks like the test fail rate is 5/50; I see if I can find a seed to reproduce the issue.

Testing on a random dataset instead of a specific, hand-chosen dataset has revealed very many bugs to us in the past, so I think there is definitely a benefit in probabilistic tests, however I agree, it's not perfect.

**Comment by rcurtin** [comment]
Hmm, I wonder if we should set a fixed seed for releases but not for the master branch.  I suppose this could reduce false positive failures reported by users but still allow us the robustness to see how well things work.  Just an idea...

**Comment by zoq** [comment]
That might be an option.

**Comment by rcurtin** [comment]
Actually I thought about it a bit more, and unfortunately even the same seed on different systems (or even different compilers) is likely to produce different sequences of random numbers, so the idea I suggested won't work in general.  I think we are stuck with our current best option, which is just to do our best to keep the test failure probability as low as we can.

**Comment by rcurtin** [comment]
Actually I thought about it a bit more, and unfortunately even the same seed on different systems (or even different compilers) is likely to produce different sequences of random numbers, so the idea I suggested won't work in general.  I think we are stuck with our current best option, which is just to do our best to keep the test failure probability as low as we can.

**Comment by zoq** [comment]
Good point, but maybe it makes it easier to fix a potential issue since it's easier to reproduce the issue not in general but on the same system/config.

> I think we are stuck with our current best option, which is just to do our best to keep the test failure probability as low as we can.

Right, I thought the idea is to only use a fixed seed if ``-DDEBUG=OFF``.

**Comment by rcurtin** [comment]
Ah, yeah, true, that is an easy enough change.  I'll look into it shortly.

**Comment by rcurtin** [comment]
This bug still exists, so I'll mark this "keep open".  There are two things to do: set a fixed seed (I'll handle this when I'm able to) and fix the CF test so it fails less often.
