### ISSUE TITLE
Reclaim not used absolute error in KDE

### ISSUE THREAD

**Issue by robertohueso** [mlpack/mlpack#1954]
This issue came out of the review of #1934.

The current KDE implementation provides the possibility to set an absolute/relative error tolerance. This accelerates computations by pruning nodes whose computation would not be very relevant for the estimation (you can find a more detailed explanation [here](https://arxiv.org/pdf/1304.4327.pdf) in section 8).

[This paper](https://arxiv.org/pdf/1206.6857.pdf), in section 5 after "Theorem 2", mentions how current implementation is not taking full advantage of error tolerance. The main idea is that, when a traverser was not able to prune and has to evaluate the `BaseCase()` for some combination of points, there's an amount of error tolerance that has not been used and could potentially be used later to try and prune even more.

As an example, this has been already implemented for `alpha` when using probabilistic error bounds in #1934.

**Comment by rcurtin** [comment]
A PR is open as #1984.

**Comment by rcurtin** [comment]
#1984 is merged, so I will go ahead and close this.
