### ISSUE TITLE
Add assignment operators for all trees

### ISSUE THREAD

**Issue by robertohueso** [mlpack/mlpack#1957]
As a [rule of thumb](https://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming)#Rule_of_Five) it would be nice to have assignment operators for all trees in mlpack.

At the moment @rcurtin has implemented copy-assignment and move-assignment operators for `RectangleTree` in #1934 (Thanks! :smile: ) so that could work as an example for the rest of the trees.

**Comment by rcurtin** [comment]
The trees that need to be looked at would be `BinarySpaceTree` in `src/mlpack/core/tree/binary_space_tree/`, `CoverTree` in `src/mlpack/core/tree/cover_tree/`, `SpillTree` in `src/mlpack/core/tree/spill_tree/`, `CosineTree` in `src/mlpack/core/tree/cosine_tree/`, and `Octree` in `src/mlpack/core/tree/octree/`.

Some of those may already have assignment operators, but in the cases where they don't, an implementation plus a test for it should be all that's needed.

**Comment by gauravk97** [comment]
Hi, I would like to work on this. Can I take this up?

**Comment by rcurtin** [comment]
Sure, but I would suggest working on only one thing at a time.  If you do this one, feel free to open a PR when it is done. :+1:

**Comment by geekRishabhjain** [comment]
Is someone else working on it? Can I?

**Comment by robertohueso** [comment]
Hi @geekRishabhjain :) Sure, you can work on it, but it would be great if you could talk to @gauravk97 to avoid working on the same type of tree :+1:

**Comment by geekRishabhjain** [comment]
@robertohueso @gauravk97  does not seem to be working on it. His account looks passive. Should I?

**Comment by robertohueso** [comment]
@geekRishabhjain I think you're right, so yeah :)

It would be nice if you could say which type of tree will you be working on (in case you want to work on one at a time) so that, in case other people join the issue, your work doesn't overlap with theirs. :smile:

**Comment by geekRishabhjain** [comment]
@robertohueso I tried understanding the code(new to open source contribution to an organization) and was overwhelmed.
But I think once I start getting comfortable I'll be working on cover trees.

**Comment by geekRishabhjain** [comment]
@rcurtin I am new to Open Source contribution to organizations. I took a course on ML by Andrew ng, and read the book hands-on machine learning in pyhton, and have good knowledge of C/C++. I am here with a motive to contribute and learn. But was overwhelmed by the code. Any tips on how should I start?

**Comment by rcurtin** [comment]
Hey there @geekRishabhjain, I think that the best way to get started with the mlpack code would be to the follow the tutorials and what's written on this page: http://mlpack.org/community.html#getting-involved

Once you're comfortable, for this task, I would start by implementing tests for the assignment operator for all types of trees, based on the tests that are already there (the code in #1934 might help as an example), and then modifying the trees as necessary so that the tests work. :+1:

**Comment by sriramsk1999** [comment]
@rcurtin could you mark this with the keep open label? I'm nearly done with this issue.

**Comment by rcurtin** [comment]
Sure, no problem.

**Comment by rcurtin** [comment]
Now that #2036 is merged, this issue is done. :+1:
