### ISSUE TITLE
DESTDIR improperly passed to python install, fix included!

### ISSUE THREAD

**Issue by marcespie** [mlpack/mlpack#1963]
#### Issue description

python binding installation broken.

#### Your environment

 * version of mlpack: 3.1.1
 * operating system: OpenBSD
 * compiler: clang
 * version of dependencies (Boost/Armadillo): not relevant
 * any other environment information you think is relevant:

#### Steps to reproduce

Try to install the bindings with DESTDIR not empty.

creating "/build/pobj/mlpack-3.1.1-python3/fake-amd64-python3"/usr/local/lib/python3.7/site-packages/mlpack

Notice the quotes.
#### Expected behavior

The quotes are extra, the destination directory is bad.

Fix is trivial, this was fucked up when moving the python install target in its own file. Somehow, --root=$ENV{DESTDIR} gained quotes. That breaks things very thoroughly.

[p.txt](https://github.com/mlpack/mlpack/files/3455494/p.txt)

**Comment by rcurtin** [comment]
You are the best!  I was just debugging this actually when working on the Fedora package and now you have made my life easy.  I opened #1964.  Thanks!

**Comment by marcespie** [comment]
No problem. As usual it took longer to find the culprit file than to fix the issue.

Hahaha.
