### ISSUE TITLE
Resurrect and finish stale PRs

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1965]
Since mlpack-bot is ruthless about closing stale issues and PRs (although that is my fault :)), I wanted to make a place where we can list PRs that have been closed for inactivity, but could still have useful functionality that could be merged, if someone was willing to either (a) handle the unresolved comments on the PR or (b) give a comprehensive review to the PR (and then we can reopen it, if the original author is still interested).

I'm hoping this is better than just leaving the stale PRs open indefinitely---it should keep the PR list from getting too long.  If anyone else has any old PRs they'd like to see eventually merged, I can add them to the list here.

If you're looking for a place to start contributing to mlpack, this could be a good issue: just take a look through the PRs listed below as well as any comments, and see if any of those PRs are interesting to you.  If so, see if you can figure out what the current status of that PR is, and if there are comments that need to be addressed, then you can address those starting from the current code and open a new PR (and hopefully we can review it).

Here's the list:

 - #1072: Implementation of Neural Turing Machine [likely needs update to any API changes]
 - #1367: NMF: allow user to specify one of W/H matrices [very useful functionality!]
 - #1842: change weak learner type of the Adaboost to DecisionTree::ID3DecisionStump [allows lots of code simplification when we're done]

**Comment by mrbuddhu** [comment]
I wish to contribute to the above mentioned issue.

**Comment by jzy95310** [comment]
I will give it a try on the second PR.

**Comment by darthgera123** [comment]
which of them still need to be resolved?

**Comment by darthgera123** [comment]
which of these still need to be looked at @rcurtin

**Comment by rcurtin** [comment]
@darthgera123 all of them are still there.  There are many other stale/closed PRs that you could resurrect and finish also.  I suggest searching through the closed PRs.  Some digging will be necessary.

**Comment by joeljosephjin** [comment]
@rcurtin  #1432  can i work on the policy gradient mentioned here? It seems to me as if the original authors are no longer interested.

**Comment by kartikdutt18** [comment]
Hey @rcurtin, I am adding another PR here as well, I hope that's okay :

#1716 : Addition of Dense blocks
(This would be interesting to have, though I have a different approach in mind, To put it simply : The Dense Block class should be like FFN, That we can add layers to it such that it automatically forms a dense block. I hope this makes, Let me know if I missed something).

Thanks a ton!

**Comment by iamshnoo** [comment]
#2122 seems to be an interesting feature to add proper support for raising an error message about incorrect input sizes. Would like to take this up at some point if the original author is no longer interested.
