### ISSUE TITLE
Can't build 3.1.1 binaries on CentOS7 due to boost version mismatch

### ISSUE THREAD

**Issue by AjitDingankar** [mlpack/mlpack#1966]
#### Issue description
Trying build 3.1.1 from sources fails with a ton of messages re boost such as:  
![image](https://user-images.githubusercontent.com/2213240/62391345-608a5880-b519-11e9-9908-86da5eac4867.png)

#### Your environment

 * version of mlpack: 3.1.1
 * operating system: CentOS 7.6.1810 
 * compiler: gcc 4.8.5 
 * version of dependencies (Boost/Armadillo): Boost 1.70.0 Armadillo 8.300.0
 * any other environment information you think is relevant:
`BOOST_ROOT /opt/boost`
#### Steps to reproduce
 
1. Download 3.1.1 sources 
1. Create build subdirectory and run cmake/make there

#### Expected behavior
1. Cmake should find pthread_create 
1. Boost version found should be 1.70 (not 1.49)
1. The bin subdirectory should have all the executables such as mlpack_preprocess_split 

#### Actual behavior
1. Cmake configure stage shows: 
> -- Looking for pthread_create - not found

2. Boost version is inconsistent: 
> -- Found Boost 1.70.0 at /opt/boost/lib/cmake/Boost-1.70.0
> --   Requested configuration: QUIET REQUIRED COMPONENTS program_options;unit_test_framework;serialization
> -- Found boost_headers 1.70.0 at /opt/boost/lib/cmake/boost_headers-1.70.0
> -- Found boost_program_options 1.70.0 at /opt/boost/lib/cmake/boost_program_options-1.70.0
> --   libboost_program_options.so.1.70.0
> -- Adding boost_program_options dependencies: headers
> -- Found boost_unit_test_framework 1.70.0 at /opt/boost/lib/cmake/boost_unit_test_framework-1.70.0
> --   libboost_unit_test_framework.so.1.70.0
> -- Adding boost_unit_test_framework dependencies: headers
> -- Found boost_serialization 1.70.0 at /opt/boost/lib/cmake/boost_serialization-1.70.0
> --   libboost_serialization.so.1.70.0
> -- Adding boost_serialization dependencies: headers
> -- Boost 1.49 found.
> -- Found Boost components:
>    program_options;unit_test_framework;serialization

3. The bin subdirectory is empty

#### Attachments
[mlpack3-cmake3-console.txt](https://github.com/mlpack/mlpack/files/3462584/mlpack3-cmake3-console.txt)
[mlpack3-make-console.txt](https://github.com/mlpack/mlpack/files/3462591/mlpack3-make-console.txt)
[CMakeError.log](https://github.com/mlpack/mlpack/files/3462594/CMakeError.log)
[CMakeOutput.log](https://github.com/mlpack/mlpack/files/3462595/CMakeOutput.log)

**Comment by AjitDingankar** [comment]
Fixed by removing the latest (1.70.0) version of boost and using 1.53.0 from the repo. 
`sudo yum install boost-devel`

**Comment by rcurtin** [comment]
Glad you got it worked out.  Note that I just pushed some updated mlpack 3 packages to the Fedora (and EPEL7) testing repositories; more details in #1955.  The relevant EPEL7 package update page is here:

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-ab9a7a4c40

And, as with the F30 package, I'm in the process of building 3.1.1 for it, and will probably push that by tomorrow. :+1:
