### ISSUE TITLE
Can't run mlpack executables on CentOS 7

### ISSUE THREAD

**Issue by AjitDingankar** [mlpack/mlpack#1967]
#### Issue description
Get error "undefined symbol" when I try to run any mlpack executable 

#### Your environment

 * version of mlpack: 3.1.1
 * operating system: CentOS 7.6
 * compiler: gcc 4.8.5 
 * version of dependencies (Boost/Armadillo): Boost 1.53.0 Armadillo 8.300.0 
 * any other environment information you think is relevant:
`export LD_LIBRARY_PATH=/usr/local/lib/`

#### Steps to reproduce

Build 3.1.1 and `sudo make install` 

#### Expected behavior
Executable runs

#### Actual behavior

> (base) ~$ mlpack_knn --version
> mlpack_knn: symbol lookup error: mlpack_knn: undefined symbol: _ZN6mlpack4util10ProgramDocC1ERKSsS3_RKSt8functionIFSsvEERKSt6vectorISt4pairISsSsESaISB_EE
> (base) ~$ which mlpack_knn
> /usr/local/bin/mlpack_knn

#### Related issues
https://github.com/mlpack/mlpack/issues/1966#issue-476315270

**Comment by AjitDingankar** [comment]
Tried the work-around/debug step suggested in: 
https://github.com/mlpack/mlpack/issues/1760#issuecomment-469839621 
by pointing LD_LIBRARY_PATH to the lib subdirectory under the build directory. 
Now the executable works! 

How do I debug why `sudo make install` **did __not__** put the `libmlpack*` files under `/usr/local/lib` since I closed terminal where I built it? 

> **Note:** I also had the same error for importing in Python, but that was fixed with the above and 
> setting `PYTHONPATH` to `/usr/local/lib/python3.7/site-packages` as suggested in:  
> https://github.com/mlpack/mlpack/issues/1760#issuecomment-472697952

**Comment by rcurtin** [comment]
Wow, very odd that `sudo make install` did not put it in `/usr/local/lib`.  Is it possible that it put it in `/usr/local/lib64` by any chance?  I've not used to RHEL conventions (I am a Debian user primarily) but I know that some things end up in `lib64` and some in `lib`.

Otherwise, we can figure out a bit more if you can run `sudo make install` again and share the output.  I've never observed CMake failing to install libmlpack.so, so my guess is that it just put it somewhere weird for some weird CMake+RHEL reason.  I am sure we can get it figured out, just need to figure out what actually happened. :)

**Comment by AjitDingankar** [comment]
Thanks for the prompt response on Friday evening, Ryan! 😉 
Will try to find the so in some unusual suspects, but if that doesn't work, should I just install it again or remove the build and start from scratch? 
Thanks,Ajit==== 
Sent from Yahoo Mail on Android 
 
  On Fri, Aug 2, 2019 at 6:50 PM, Ryan Curtin<notifications@github.com> wrote:   
Wow, very odd that sudo make install did not put it in /usr/local/lib. Is it possible that it put it in /usr/local/lib64 by any chance? I've not used to RHEL conventions (I am a Debian user primarily) but I know that some things end up in lib64 and some in lib.

Otherwise, we can figure out a bit more if you can run sudo make install again and share the output. I've never observed CMake failing to install libmlpack.so, so my guess is that it just put it somewhere weird for some weird CMake+RHEL reason. I am sure we can get it figured out, just need to figure out what actually happened. :)

**Comment by rcurtin** [comment]
Installing again is just fine---it'll just install all the files to the same place, so nothing on the system except the modification times of the mlpack files should change. :)
