### ISSUE TITLE
mlpack build error because of ensmallen

### ISSUE THREAD

**Issue by gauravk97** [mlpack/mlpack#1974]
Hi,

I was trying to build mlpack from source in linux (Ubuntu 19.04) using this guide : https://mlpack.org/doc/mlpack-3.1.1/doxygen/build.html

When I ran "cmake", the source for library ensmallen-1.16.0 was also downloaded in the local directory. During the execution of command, "make -j4", the following error pops up :

> In file included from /home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen.hpp:86,
                 from /home/gk/mlpack/src/mlpack/methods/matrix_completion/matrix_completion.hpp:16,
                 from /home/gk/mlpack/src/mlpack/methods/matrix_completion/matrix_completion.cpp:13:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp: In member function ‘size_t ens::PSOType<VelocityUpdatePolicy, InitPolicy>::LowerBound() const’:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp:162:38: error: cannot convert ‘const vec’ {aka ‘const arma::Col<double>’} to ‘size_t’ {aka ‘long unsigned int’} in return
   size_t LowerBound() const { return lowerBound; }
                                      ^~~~~~~~~~
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp: In member function ‘size_t& ens::PSOType<VelocityUpdatePolicy, InitPolicy>::LowerBound()’:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp:165:33: error: invalid initialization of reference of type ‘size_t&’ {aka ‘long unsigned int&’} from expression of type ‘arma::vec’ {aka ‘arma::Col<double>’}
   size_t& LowerBound() { return lowerBound; }
                                 ^~~~~~~~~~
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp: In member function ‘size_t ens::PSOType<VelocityUpdatePolicy, InitPolicy>::UpperBound() const’:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp:168:38: error: cannot convert ‘const vec’ {aka ‘const arma::Col<double>’} to ‘size_t’ {aka ‘long unsigned int’} in return
   size_t UpperBound() const { return upperBound; }
                                      ^~~~~~~~~~
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp: In member function ‘size_t& ens::PSOType<VelocityUpdatePolicy, InitPolicy>::UpperBound()’:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp:171:33: error: invalid initialization of reference of type ‘size_t&’ {aka ‘long unsigned int&’} from expression of type ‘arma::vec’ {aka ‘arma::Col<double>’}
   size_t& UpperBound() { return upperBound; }
                                 ^~~~~~~~~~
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp: In member function ‘size_t& ens::PSOType<VelocityUpdatePolicy, InitPolicy>::ImpTolerance()’:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp:189:35: error: cannot bind non-const lvalue reference of type ‘size_t&’ {aka ‘long unsigned int&’} to an rvalue of type ‘size_t’ {aka ‘long unsigned int’}
   size_t& ImpTolerance() { return impTolerance; }
                                   ^~~~~~~~~~~~
In file included from /home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen.hpp:86,
                 from /home/gk/mlpack/src/mlpack/methods/softmax_regression/softmax_regression.hpp:16,
                 from /home/gk/mlpack/src/mlpack/methods/softmax_regression/softmax_regression.cpp:13:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp: In member function ‘size_t ens::PSOType<VelocityUpdatePolicy, InitPolicy>::LowerBound() const’:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp:162:38: error: cannot convert ‘const vec’ {aka ‘const arma::Col<double>’} to ‘size_t’ {aka ‘long unsigned int’} in return
   size_t LowerBound() const { return lowerBound; }
                                      ^~~~~~~~~~
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp: In member function ‘size_t& ens::PSOType<VelocityUpdatePolicy, InitPolicy>::LowerBound()’:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp:165:33: error: invalid initialization of reference of type ‘size_t&’ {aka ‘long unsigned int&’} from expression of type ‘arma::vec’ {aka ‘arma::Col<double>’}
   size_t& LowerBound() { return lowerBound; }
                                 ^~~~~~~~~~
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp: In member function ‘size_t ens::PSOType<VelocityUpdatePolicy, InitPolicy>::UpperBound() const’:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp:168:38: error: cannot convert ‘const vec’ {aka ‘const arma::Col<double>’} to ‘size_t’ {aka ‘long unsigned int’} in return
   size_t UpperBound() const { return upperBound; }
                                      ^~~~~~~~~~
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp: In member function ‘size_t& ens::PSOType<VelocityUpdatePolicy, InitPolicy>::UpperBound()’:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp:171:33: error: invalid initialization of reference of type ‘size_t&’ {aka ‘long unsigned int&’} from expression of type ‘arma::vec’ {aka ‘arma::Col<double>’}
   size_t& UpperBound() { return upperBound; }
                                 ^~~~~~~~~~
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp: In member function ‘size_t& ens::PSOType<VelocityUpdatePolicy, InitPolicy>::ImpTolerance()’:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp:189:35: error: cannot bind non-const lvalue reference of type ‘size_t&’ {aka ‘long unsigned int&’} to an rvalue of type ‘size_t’ {aka ‘long unsigned int’}
   size_t& ImpTolerance() { return impTolerance; }
                                   ^~~~~~~~~~~~
In file included from /home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen.hpp:86,
                 from /home/gk/mlpack/src/mlpack/methods/sparse_autoencoder/sparse_autoencoder.hpp:16,
                 from /home/gk/mlpack/src/mlpack/methods/sparse_autoencoder/sparse_autoencoder.cpp:13:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp: In member function ‘size_t ens::PSOType<VelocityUpdatePolicy, InitPolicy>::LowerBound() const’:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp:162:38: error: cannot convert ‘const vec’ {aka ‘const arma::Col<double>’} to ‘size_t’ {aka ‘long unsigned int’} in return
   size_t LowerBound() const { return lowerBound; }
                                      ^~~~~~~~~~
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp: In member function ‘size_t& ens::PSOType<VelocityUpdatePolicy, InitPolicy>::LowerBound()’:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp:165:33: error: invalid initialization of reference of type ‘size_t&’ {aka ‘long unsigned int&’} from expression of type ‘arma::vec’ {aka ‘arma::Col<double>’}
   size_t& LowerBound() { return lowerBound; }
                                 ^~~~~~~~~~
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp: In member function ‘size_t ens::PSOType<VelocityUpdatePolicy, InitPolicy>::UpperBound() const’:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp:168:38: error: cannot convert ‘const vec’ {aka ‘const arma::Col<double>’} to ‘size_t’ {aka ‘long unsigned int’} in return
   size_t UpperBound() const { return upperBound; }
                                      ^~~~~~~~~~
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp: In member function ‘size_t& ens::PSOType<VelocityUpdatePolicy, InitPolicy>::UpperBound()’:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp:171:33: error: invalid initialization of reference of type ‘size_t&’ {aka ‘long unsigned int&’} from expression of type ‘arma::vec’ {aka ‘arma::Col<double>’}
   size_t& UpperBound() { return upperBound; }
                                 ^~~~~~~~~~
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp: In member function ‘size_t& ens::PSOType<VelocityUpdatePolicy, InitPolicy>::ImpTolerance()’:
/home/gk/mlpack/build/deps/ensmallen-1.16.0/include/ensmallen_bits/pso/pso.hpp:189:35: error: cannot bind non-const lvalue reference of type ‘size_t&’ {aka ‘long unsigned int&’} to an rvalue of type ‘size_t’ {aka ‘long unsigned int’}
   size_t& ImpTolerance() { return impTolerance; }
                                   ^~~~~~~~~~~~
[  1%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_autoencoder/sparse_autoencoder_function.cpp.o
make[2]: *** [src/mlpack/CMakeFiles/mlpack.dir/build.make:638: src/mlpack/CMakeFiles/mlpack.dir/methods/softmax_regression/softmax_regression.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/mlpack/CMakeFiles/mlpack.dir/build.make:554: src/mlpack/CMakeFiles/mlpack.dir/methods/matrix_completion/matrix_completion.cpp.o] Error 1
make[2]: *** [src/mlpack/CMakeFiles/mlpack.dir/build.make:666: src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_autoencoder/sparse_autoencoder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:344: src/mlpack/CMakeFiles/mlpack.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

>

Although from the error message it looks like the issue is in the ensmallen library, since you guys use it here maybe you could help me figure out the reason behind this. Or maybe direct me to the correct forum, if this isn't it. 

Perhaps the wrong version was downloaded and there is a mismatch.
Is there any other info I can provide for better help?

**Comment by rcurtin** [comment]
Hey @gauravk97, thanks for the report.  This actually got reported in the ensmallen repository as ensmallen#123 and was fixed just now in ensmallen#124.  I just released ensmallen 1.16.1 with that fix, so if you remove the downloaded ensmallen and reconfigure CMake, it should get the new version and there should be no problem. :+1:

**Comment by rcurtin** [comment]
With 1.16.2 released this is definitely fixed, so I'll go ahead and close this issue now.  Please feel free to reopen if issues persist! :+1:
