### ISSUE TITLE
No libBFD and/or libDL has been found!

### ISSUE THREAD

**Issue by geekRishabhjain** [mlpack/mlpack#1982]
#### https://www.mlpack.org/doc/stable/doxygen/build.html#build_dep
I tried following the instructions to build mlpack from the link given above and from the README.md.
It works fine till I run
```cmake -D DEBUG=ON -D PROFILE=ON ../```
I have installed 
Armadillo
Boost
CMake
cython, numpy, pandas
But running above command does not work fine.

This is the error it shows:

-- cotire 1.7.10 loaded.
-- Could NOT find LIBBFD (missing: LIBBFD_BFD_LIBRARY LIBBFD_INCLUDE_DIRS) 
CMake Warning at CMakeLists.txt:192 (message):
  No libBFD and/or libDL has been found!

-- Armadillo libraries: /usr/lib/libarmadillo.so
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   program_options
--   unit_test_framework
--   serialization
CMake Warning at CMakeLists.txt:517 (message):
  txt2man not found; man pages will not be generated.

-- Not building Markdown bindings.
-- Found Python: /usr/bin/python
-- Found PY_pandas: /home/rishabh/.local/lib/python2.7/site-packages/pandas  
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rishabh/coding/GoogleSummerOfCode/mlpack/mlpack-3.1.1/build

**Comment by zoq** [comment]
LIBBFD is an optional dependency for debugging that is only available on some systems, so unless you like to use the bfd functionality you can ignore the warning. Let me know if I should clarify anything further.

**Comment by geekRishabhjain** [comment]
@zoq  How can I install this dependency? Not able to find any relevant link for it on google?

**Comment by zoq** [comment]
I think on Debian the package you are searching for is ``libbfd-dev`` but as I said, you can ignore the warning in most cases. Do you build on Debian?

**Comment by geekRishabhjain** [comment]
@zoq  I use ubuntu. Yes, for now, I have moved to the next step. But in case I need it in the future. Thanks, btw.
