### ISSUE TITLE
Collaborative Filtering models (nearly all of them) crash in Cholesky decomposition

### ISSUE THREAD

**Issue by zsogitbe** [mlpack/mlpack#1990]
#### Issue description

I have regular crashes with real datasets in nearly all of the Collaborative Filtering (CF) models except the regularized SVD model.

#### Your environment

 * version of mlpack: last
 * operating system: Windows 10
 * compiler: VS 2017 last version
 * version of dependencies (Boost/Armadillo): both
 * any other environment information you think is relevant: N/A

#### Steps to reproduce

You need to download the ml-20m dataset from the movielens website and use the example (cf_test.cpp) cf code in the mlpack distribution (replace GroupLensSmall.csv with the larger movielens csv file, I think “ratings.csv” – you need to loose the last column with the timestamp). 

#### Expected behavior

No crash.

#### Actual behavior

All CF models give “chol(): decomposition failed” except the Regularized SVD which works fine. 

#### Feedback from Ryan Curtin

I have got quick info from Ryan and I have tested his first suggestion (see below) but it did not solve the problem.

=========> INFO from Ryan: 

Hey Zoltán,

Thanks for getting in touch and I'm glad you've found the CF code
useful.  I took a quick look into the code and I find it strange that
the Cholesky decomposition is failing.  Specifically, the only code that
uses the Cholesky decomposition uses it for accelerated nearest neighbor
search, like this (from decomposition_methods/batch_svd_method.hpp):

  // We want to avoid calculating the full rating matrix, so we will do
  // nearest neighbor search only on the H matrix, using the observation
  // that if the rating matrix X = W*H, then d(X.col(i), X.col(j)) = d(W
  // H.col(i), W H.col(j)).  This can be seen as nearest neighbor search
  // on the H matrix with the Mahalanobis distance where M^{-1} = W^T W.
  // So, we'll decompose M^{-1} = L L^T (the Cholesky decomposition),
  // and then multiply H by L^T. Then we can perform nearest neighbor
  // search.
  arma::mat l = arma::chol(w.t() * w);

So, we're taking the Cholesky decomposition of w' * w, which *should* by
definition be positive definite and thus have no problem with Cholesky
decomposition.  (i.e., all the eigenvalues of w' * w should be positive)

However, I suspect the real issue here is that it cannot be inverted
because the matrix is *close* to being not positive definite (i.e., I
bet an eigenvalue is really close to 0), and floating-point errors and
the realities of the numerical algorithms used to implemented the
Cholesky decomposition mean that it fails.

I suspect the problem could be solved in the following way:

  1. Find the decomposition strategy you are using (if you are using the
     defaults in the mlpack CF binding, `mlpack_cf`, this will be
     src/mlpack/methods/cf/decomposition_policies/nmf_method.hpp).

  2. (optional) Insert the following code to print the eigenvalues of w' *
     w before the Cholesky decomposition:

     std::cout << "eigenvalues of w' * w: " << arma::eig_sym(w.t() * w);

  3. Add to the diagonals of w.t() * w to prevent Cholesky decomposition
     issues by changing the chol() line to this:

     arma::mat l = arma::chol(w.t() * w +
         1e-20 * arma::eye<arma::mat>(w.n_cols, w.n_cols))

     The specific number of 1e-20 may need to be made larger or smaller
     depending on your problem.

If that works, we can adapt it into a more permanent solution and
incorporate it into the codebase.

Hope that helps!
Thanks,
Ryan

<========= END INFO from Ryan:

**Comment by inhocho89** [comment]
I am also experiencing the same issue on Ubuntu 18.04

**Comment by conradsnicta** [comment]
This may help.  As of Armadillo 10.6, the [chol()](http://arma.sourceforge.net/docs.html#chol) function optionally allows pivoted Cholesky decomposition, which has the less stringent requirement of positive semi-definite matrices.  This is in contrast to standard Cholesky decomposition, which requires positive definite matrices.
