### ISSUE TITLE
CLion CMake project linking problem

### ISSUE THREAD

**Issue by Georgiana1197** [mlpack/mlpack#1991]
I'm trying to integrate mlpack in my CMake project, using CLion, and it doesn't seem to recognise the library. I'm using Ubuntu as the os

**Comment by zoq** [comment]
Happy to help, do you think you could provide some more information, maybe a stripped down CMake file? Here is an example file that links against mlpack: https://github.com/zoq/nes/blob/master/CMakeLists.txt

The important parts are:

- https://github.com/zoq/nes/blob/ba622e134db0548ebbc9bd2c5c3d587b348f6ab8/CMakeLists.txt#L9

The ``cmake/modules/`` folder contains an mlpack module to search for the lib in common places.

- https://github.com/zoq/nes/blob/ba622e134db0548ebbc9bd2c5c3d587b348f6ab8/CMakeLists.txt#L41

Here we just use the module mentioned above.

- https://github.com/zoq/nes/blob/ba622e134db0548ebbc9bd2c5c3d587b348f6ab8/CMakeLists.txt#L54

Add the include path.

- https://github.com/zoq/nes/blob/ba622e134db0548ebbc9bd2c5c3d587b348f6ab8/CMakeLists.txt#L91

Add mlpack lib.
