### ISSUE TITLE
Temporarily revert changes to RL `Action` for 3.2.0 release

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1994]
After a discussion in IRC, @zoq and @favre49 agreed that the right thing to do for the next release is to temporarily "undo" the change to the `Action` struct until the 4.0.0 release, which we can postpone until later.  This issue is just a placeholder that we can associate with the 3.2.0 milestone. :)

**Comment by zoq** [comment]
https://github.com/mlpack/mlpack/pull/1996 will address the issue.

**Comment by rcurtin** [comment]
#1996 is merged, so we can close this. :+1:
