### ISSUE TITLE
Naive Bayes Classifier: mlpack vs scikit-learn

### ISSUE THREAD

**Issue by marcovirgolin** [mlpack/mlpack#2017]
Hello,
I am running the NBC in mlpack and scikit learn, on datasets from here: https://drive.google.com/drive/folders/1GPCGpycMqoQjnY7-uQ4ROPdn6bsbVrE1
See e.g., the ecoli dataset. I get much better results using scikit-learn (with any of the three available NBCs: Gaussian, Multinomial, Bernoulli's).

If I am not mistaken, the mlpack implementation should correspond to scikit-learn's Gaussian NBC.

I attach code to reproduce my results (including dataset).
[reproducing.zip](https://github.com/mlpack/mlpack/files/3610600/reproducing.zip)

Here's a summary of what I get: 
Test F1 score (monte-carlo cross-validation, 10 repetitions, 80-20 split)
  > mlpack - mean: 0.22, std: 0.14
  > scikit-learn - mean: 0.50, std: 0.10

For this large gene-expression dataset https://archive.ics.uci.edu/ml/datasets/gene+expression+cancer+RNA-Seq the difference is even larger: F1=0.10 for mlpack, and F1=0.65 for scikit-learn.

**Comment by ShikharJ** [comment]
Thanks @marcovirgolin for the report, we need to analyse this thoroughly. NBC code is pretty old, and we haven't looked at it in a while, but hopefully we can get some answers.

**Comment by KimSangYeon-DGU** [comment]
@marcovirgolin Thanks for reporting, I'll look into it.

**Comment by rcurtin** [comment]
Since #2022 is merged, I think that this issue is fixed, so I'll go ahead and close it.  The fix will be incorporated into mlpack 3.2.1, which will be released shortly.  If you still have any problems please don't hesitate to open more issues in the future. :+1:
