### ISSUE TITLE
Library bindings for other languages

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#202]
**Reported by speet3 on 30 Jul 42178952 12:20 UTC**
Is it a good idea to generate and maintain bindings for languages other than C++?  Perhaps languages like java, python or php?

That way a developer using one of those languages could take advantage of the speed offered our C++ implementation without wading through the torrents of newbie C++ development pitfalls.

Perhaps these bindings could be automatically generated by a tool like [swig](http://www.swig.org/).

Migrated-From: http://trac.research.cc.gatech.edu/fastlab/ticket/208

**Comment by rcurtin** [comment]
For some clarification on where this idea has gone, see the summer of code ideas page and the automatic bindings project: https://github.com/mlpack/mlpack/wiki/SummerOfCodeIdeas

**Comment by MikeLing** [comment]
Hey @rcurtin, I have experience for python coding(two years experience for Mozilla A-team and I worked for it as GSoC student) and I'm a postgraduate student majoring in CS. Could I worked for Python binding for mlpack? However, I never do the binding job before, could you give me some information about it?

**Comment by MikeLing** [comment]
After I found some more information about swig[1][2], I guess I know how to bind it with python. Do I need to create a PR on my branch for discussing for now? 


[1] http://www.swig.org/Doc3.0/SWIG.html#SWIG
[2]http://www.swig.org/Doc3.0/Python.html#Python

**Comment by rcurtin** [comment]
I'm going to go ahead and close this now that the automatic binding generator is done and we have Python bindings.  Although it would be nice to add more languages (and that will happen over time), we can either open a new issue for that or simply work on it without an issue.
