### ISSUE TITLE
How to perform DBSCAN clustering on 3D points

### ISSUE THREAD

**Issue by dbots94** [mlpack/mlpack#2021]
I want to perform the DBSCAN clustering algorithm, but I can't find how to use it... I already tried understanding your documentation, but I can't find how to call that algorithm's function. So how should I proceed to process a std::vector<cv::Point3f> into multiple std::vector<cv::Point3f>, containing the clusters detected.

**Comment by zoq** [comment]
Hello @dbots94 https://github.com/mlpack/mlpack/blob/master/src/mlpack/tests/dbscan_test.cpp contains some examples about how to use ``DBSCAN`` with the C++ interface. Or are you searching for a solution to convert an opencv data type into a armadillo matrix.

**Comment by dbots94** [comment]
It's exactly that. Sorry for my noobness, but I stil don't understand where the different cluster points are stored. Thank you very much for your help

**Comment by rcurtin** [comment]
Hey @dbots94, have you tried looking at the DBSCAN documentation?  The command-line program documentation for `mlpack_dbscan` is here:

http://mlpack.org/doc/mlpack-3.1.1/cli_documentation.html#dbscan

and in the "see also" section, there is a link to the C++ documentation:

https://mlpack.org/doc/mlpack-git/doxygen/classmlpack_1_1dbscan_1_1DBSCAN.html

I would suggest taking a look through that documentation to figure out what it is that you need.  If you aren't familiar with mlpack, you may consider starting with some documentation related to that:

http://mlpack.org/doc/stable/cli_documentation.html#tutorials

All of these links should be easily accessible from the mlpack homepage and should help out.  In your particular case, you have the choice of multiple `Cluster()` overloads, which can return either the cluster assignments of each point or the centroids of each cluster (or both).

**Comment by dbots94** [comment]
Ok thank you very much for your help, I'll look into those links.
Best regards
