### ISSUE TITLE
mlpack does not load data

### ISSUE THREAD

**Issue by BryanSWeber** [mlpack/mlpack#2024]
I have installed mlpack on windows using vcpkg (specifically ".\vcpkg install mlpack[tools]:x86 - windows") 

I intended to integrate mlpack with an existing project (x86) that produced a .dll
I then resolved all the compiler/linker problems, etc. and my program now successfully compiled.

Not wanting to be ambitious I simply tried to integrate the existing script:
https://www.mlpack.org/doc/mlpack-3.0.4/doxygen/sample_ml_app.html

Curiously the following 

```
    #pragma once
# include "Source\MyModule.h"
# include "Source\RFLearn.h"

# include "mlpack/core.hpp"
# include "mlpack/methods/random_forest/random_forest.hpp"
# include "mlpack/methods/decision_tree/random_dimension_select.hpp"
# include "mlpack/core/cv/k_fold_cv.hpp"
# include "mlpack/core/cv/metrics/accuracy.hpp"
# include "mlpack/core/cv/metrics/precision.hpp"
# include "mlpack/core/cv/metrics/recall.hpp"
# include "mlpack/core/cv/metrics/F1.hpp"

using namespace arma;
using namespace mlpack;
using namespace mlpack::tree;
using namespace mlpack::cv;

int RFLearn::test_function() {

//Method A
	mat dataset;
	bool loaded = mlpack::data::Load("C:\\Users\\MainUser\\mlpack\\src\\mlpack\\tests\\data\\german.csv", dataset);
	if (!loaded)
		return -1;
//Method B
	//arma::sp_mat dataset;
	//dataset.load("C:\\Users\\MainUser\\mlpack\\src\\mlpack\\tests\\data\\german.csv", arma::coord_ascii);
	//dataset = dataset.t(); // We must transpose after load!

	MyModule::DiagnosticText("Hey, we're here.");

	return 1;
    }
```

Method A results in an inability to link the .dll, the project compiles but presumably fails early in operation.

Method B works just fine. But Method A is the sample data set with the sample code, german.csv is not sparse. What's going on?

**Comment by BryanSWeber** [comment]
As a note, I have been trying to consider that perhaps the line endings are not correct (eg. linux vs windows .csv files), but that should be resolved using the files directly from the mlpack git.

**Comment by zoq** [comment]
Maybe it is some format issue, does it fail as well if you remove every line from the dataset except the first one?

**Comment by BryanSWeber** [comment]
Indeed, it does fail if I remove every line after the first from the dataset.  I made sure the end of line characters were deleted using the line ending display in notepad++.   I called this german_short.csv

I also did a find&replace for \r\n into \n over the extended character set, which should convert to unix line endings. I called this german_unix.csv

Both german_short.csv and german_unix.csv had the same problem, and both were loadable by the alternative method.  I am quite perplexed, but recognize the data load/save portion tends to be the least exciting part of a project.

After peeking at the function directly, it looks like it does indeed look for  \r \n line endings, so there should be nothing wrong with the endings I currently have, (pulled from this git anyway).  https://github.com/mlpack/mlpack/blob/2635297c8793396e57469bc731451fbe18bed656/src/mlpack/core/data/load_csv.cpp#L37

>   // Set rules.
>   if (extension == "csv")
>   {
>     // Match all characters that are not ',', '\r', or '\n'.
>     stringRule = quotedRule.copy() | qi::raw[*~qi::char_(",\r\n")];
>   }


Is it possible I am not loading the function properly or it is not linked correctly in some way? I would anticipate their to be a compiler error in those cases.

**Comment by BryanSWeber** [comment]
Following my previous line of reasoning, I wanted to see what would happen if I simply artificially created my own data. it seems like the RF function has a similar problem. This merely makes me more curious as to what is actually going on.

```
int RFLearn::test_function() {


	//mat dataset;
	//bool loaded = data::Load("C:\\Users\\Bryan\\mlpack\\src\\mlpack\\tests\\data\\german.csv", dataset);

	//arma::sp_mat dataset;
	//dataset.load("C:\\Users\\Bryan\\mlpack\\src\\mlpack\\tests\\data\\german.csv", arma::coord_ascii);
	//dataset = dataset.t(); // We must transpose after load!

	mat dataset = arma::randi<mat>(24, 1000); // german.csv is 24 columns and 1000 rows.

	CUNYAIModule::DiagnosticText("Hey, we're here. %s", std::experimental::filesystem::current_path().c_str() );

    Row<size_t> labels;
    labels = conv_to<Row<size_t>>::from(dataset.row(dataset.n_rows - 1));
    dataset.shed_row(dataset.n_rows - 1);

    const size_t numClasses = 2;
    const size_t minimumLeafSize = 5;
    const size_t numTrees = 10;
    RandomForest<GiniGain, RandomDimensionSelect> rf;
    rf = RandomForest<GiniGain, RandomDimensionSelect>(dataset, labels,
        numClasses, numTrees, minimumLeafSize);

 //   Row<size_t> predictions;
 //   rf.Classify(dataset, predictions);
 //   const size_t correct = arma::accu(predictions == labels);
	//CUNYAIModule::DiagnosticText("Training Accuracy: %4.2f", double(correct) / double(labels.n_elem));

 //   const size_t k = 10;
 //   KFoldCV<RandomForest<GiniGain, RandomDimensionSelect>, Accuracy> cv(k,
 //       dataset, labels, numClasses);
 //   double cvAcc = cv.Evaluate(numTrees, minimumLeafSize);
	//CUNYAIModule::DiagnosticText("KFoldCV Accuracy:  %4.2f", cvAcc);


 //   double cvPrecision = Precision<Binary>::Evaluate(rf, dataset, labels);
 //   cout << "\nPrecision: " << cvPrecision;
 //   double cvRecall = Recall<Binary>::Evaluate(rf, dataset, labels);
 //   cout << "\nRecall: " << cvRecall;
 //   double cvF1 = F1<Binary>::Evaluate(rf, dataset, labels);
 //   cout << "\nF1: " << cvF1;


 //   //mlpack::data::Save("mymodel.xml", "model", rf, false);

 //   //mlpack::data::Load("mymodel.xml", "model", rf);

 //   mat sample("2 12 2 13 1 2 2 1 3 24 3 1 1 1 1 1 0 1 0 1 0 0 0");
 //   mat probabilities;
 //   rf.Classify(sample, predictions, probabilities);
 //   u64 result = predictions.at(0);
 //   cout << "\nClassification result: " << result << " , Probabilities: " <<
 //       probabilities.at(0) << "/" << probabilities.at(1);

	return 1;
};
```

The program will stop connecting to successfully compiled .DLL once I choose to include the following:
>     RandomForest<GiniGain, RandomDimensionSelect> rf;
>     rf = RandomForest<GiniGain, RandomDimensionSelect>(dataset, labels,
>         numClasses, numTrees, minimumLeafSize);

Perhaps that sheds some light on the problem.

**Comment by rcurtin** [comment]
> The program will stop connecting to successfully compiled .DLL once I choose to include the following:

Can you explain what you mean by this?  I don't understand.  Thanks!

**Comment by BryanSWeber** [comment]
So the goal is to go from:

x86 MLPack->myproject.dll->someone_else's_project.exe

MLPack seems to compile, and myproject.dll also compiles when including mlpack.  But whenever myproject.dll uses any mlpack functions, someone_else's_project.exe can no longer connect.

I am starting to suspect that this has to do with the x32 vs x64 nature of the programs.

**Comment by rcurtin** [comment]
Okay, I think that I understand the basic idea of what you are trying to do, but I'm hung up on the term "can no longer connect"... is there an associated error message?  To me the terminology doesn't make sense.
