### ISSUE TITLE
Returning class probabilities in AdaBoost model is missing

### ISSUE THREAD

**Issue by yanivbi** [mlpack/mlpack#2025]
The AdaBoost model isn't returning the "Predicted class probabilities for each point in the test set", as the RandomForest returns (with the -P flag).

**Comment by khizirsiddiqui** [comment]
@rcurtin I was thinking to take up this issue. No one is working on this, right?

**Comment by zoq** [comment]
@khizirsiddiqui Please feel free to work on this one.

**Comment by rcurtin** [comment]
#2050 is open for this issue.

**Comment by ashutosh-b-b** [comment]
Is the issue still free to work on? Where do I start?

**Comment by rcurtin** [comment]
@ashutosh-b-b thanks for the interest---in this case, @adityaviki already opened #2050 to handle this issue.  You can take a look at the PR and review it too if you like. :+1:

**Comment by rcurtin** [comment]
Since #2050 is merged, I think that we can mark this closed and fixed. :)
