### ISSUE TITLE
Armadillo matrix transposition doubles memory usage for a matrix

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#203]
**Reported by jcline3 on 4 Nov 42190545 23:25 UTC**
This was with a large CSV loaded via the kmeans executable, profiled using valgrind's massif tool.

This isn't a big problem for small matrices, but when it uses several GB of memory...

One possibility: https://en.wikipedia.org/wiki/In-place_matrix_transposition

Another might be to modify the way Armadillo loads files?

Migrated-From: http://trac.research.cc.gatech.edu/fastlab/ticket/209

**Comment by VladimirGl** [comment]
Armadillo supports in-place transpose now.

![rplot](https://cloud.githubusercontent.com/assets/3522399/6196970/92ebc60e-b3ef-11e4-9eac-eccbcc71bc66.png)
size in MB, time in seconds.
0 - transpose, using mat = mat.t();
1 - transpose, using inpalce_trans(mat). looks like the same as 0;
2 - inplace_trans(mat, "lowmem");

End memory usage snapshots:
![lowmem_transpose](https://cloud.githubusercontent.com/assets/3522399/6196968/92eb2686-b3ef-11e4-9aa7-d7bd0cff4a2c.png)
![simple_transpose](https://cloud.githubusercontent.com/assets/3522399/6196969/92eb9cc4-b3ef-11e4-9408-bd27e6c9cd9f.png)

**Comment by VladimirGl** [comment]
maybe, need add flag for method. or use automatically for data sets larger then available memory / 2.

**Comment by rcurtin** [comment]
Ah, this is very nice!  I'm a bit confused about the memory graphs, though; the first image is using method 1?  What does the memory usage look like when using method 2?

Getting the available memory will be hackish and difficult (though, on some systems, possible).  If the runtime is very similar between methods 0 and 1 at larger sizes, too, then maybe we can just default to `inplace_trans()`; would you be willing to scale your graph up to more like an 8000x8000 matrix?  (It may also be useful to try more typical machine learning dataset sizes, so more like 50x100000 or some other very non-square matrix.)

Thanks for looking into this!

**Comment by VladimirGl** [comment]
First memory usage picture is method number 2, and the second picture is method 0. method 1 have same memory usage as 0.

So, low memory implementation (method 2) is not so fast (should be O(NlogN) complexity, instead of O(N) in methods 0 and 1).

**Comment by rcurtin** [comment]
Hm, so we can't easily determine the amount of available RAM.  One way to do this is to attempt to allocate the memory we need for the transpose, then if that fails, use `inplace_trans()`.  Looking at `armadillo_bits/debug.hpp`, when an allocation fails, the error will be printed (unless `ARMA_PRINT_ERRORS` is not defined), and then a `std::bad_alloc` is thrown.  Maybe a solution is to try and catch the `bad_alloc`, and if that happens, then transpose inplace?

**Comment by VladimirGl** [comment]
Looks hackish, but i can implement this. I think, the right solution is to add property for this (maybe, global, if this can be useful in other methods).

**Comment by rcurtin** [comment]
I agree that it seems a little bit hackish, but at least in terms of runtime, checking for a failed memory allocation won't cost anything noticeable, since none of the transpose logic happens before the memory allocation.  If you can think of a better way, do that instead. :)

**Comment by rcurtin** [comment]
Huh, looks like this should have been closed when #408 was merged.
