### ISSUE TITLE
In OSX check of Travis, `GmmTrainMainTest/GmmTrainDiffKmeansMaxIterationsTest` index out of bounds error.

### ISSUE THREAD

**Issue by KimSangYeon-DGU** [mlpack/mlpack#2035]
I noticed this error from #2022.
In OSX check of Travis, `GmmTrainMainTest/GmmTrainDiffKmeansMaxIterationsTest` failed because of `std::logic_error: Mat::col(): index out of bounds`, while all the 3 Linux checks passed.

Below is the log of the OSX check in the Travis.
[log.txt](https://github.com/mlpack/mlpack/files/3665728/log.txt)

**Comment by rcurtin** [comment]
Hey @KimSangYeon-DGU, I took a look into this one today but I haven't seen any OS X test failures for `GmmTrainMainTest` in the past month or so (looking at the Travis build history).  I think that maybe #2026 solved this one---have you seen the issue since #2026 was merged?

**Comment by KimSangYeon-DGU** [comment]
Hey @rcurtin, I think it is a temporary issue that occurs rarely because I haven't seen any issue since I opened this one. I'll close it until I find the same issue.

**Comment by rcurtin** [comment]
Sounds good! :+1:
