### ISSUE TITLE
Cannot compile mlpack on Ubuntu 18.04 and below

### ISSUE THREAD

**Issue by favre49** [mlpack/mlpack#2037]
#### Issue description

Compiling the `master` branch of mlpack without libstb-dev gives the errors:

```
In file included from /home/favre49/mlpack/src/mlpack/core/data/load.hpp:23:0,
                 from /home/favre49/mlpack/src/mlpack/core/util/cli_impl.hpp:19,
                 from /home/favre49/mlpack/src/mlpack/core/util/cli.hpp:329,
                 from /home/favre49/mlpack/src/mlpack/core.hpp:72,
                 from /home/favre49/mlpack/src/mlpack/bindings/tests/clean_memory.cpp:14:
/home/favre49/mlpack/src/mlpack/core/data/image_info.hpp:29:10: fatal error: stb_image_write.h: No such file or directory
 #include <stb_image_write.h>
```
However, libstb-dev is only available for Ubuntu eoan and Ubuntu disco. Hence, it isn't possible for users with older versions to compile.

This problem also exists for libensmallen-dev, but can be compiled from source.

#### Your environment

 * version of mlpack: master branch
 * operating system: Ubuntu 18.04 LTS
 * compiler: gcc 7.4.0
 * version of dependencies (Boost/Armadillo): Sufficient
 * any other environment information you think is relevant:

#### Steps to reproduce

Run `make mlpack_test` on a machine on Ubuntu 18.04 and below.

#### Expected behavior

Code compiles.

#### Actual behavior

Error specified

**Comment by rcurtin** [comment]
Interesting, I'm a bit surprised because if STB isn't found, then mlpack should automatically download it.  Can you also provide the output of the CMake configuration step?

**Comment by zoq** [comment]
> This problem also exists for libensmallen-dev, but can be compiled from source.

Do you mean it's not detected by CMake, as libensmallen doesn't depend or use stb.

**Comment by zoq** [comment]
Just tested ``cmake -DDOWNLOAD_STB_IMAGE=OFF ..``, which disables STB; haven't encountered any issue.

**Comment by walragatver** [comment]
I tried it on my own machine.
To solve it delete your current `build` directory. Make it once again and run `cmake ../` once again. It will resolve everything.

**Comment by favre49** [comment]
Sorry for the late reply, been busy.
Thanks for the suggestions, deleting the build file and starting over worked for me. Works as I had expected now.

**Comment by rcurtin** [comment]
Awesome, great to hear you got it worked out. :+1:
