### ISSUE TITLE
Model()[1].Parameters() does not work in FFN

### ISSUE THREAD

**Issue by rirod17** [mlpack/mlpack#2041]
Hi,

I believe this bug has been indicated in https://github.com/mlpack/mlpack/issues/1906, but I can't seem to have it working.
I tried to use model.Model()[1].Parameters() to extract the weights of the network, given the simple use of Parameters() - model.Parameters() - gives a fairly complicated, not so useful thing. I am told by the compiler there is no such member called Model().

I tried adding

`const std::vector<LayerTypes<CustomLayers...> >& Model() const { return network; }`

in the FFN class - "~/mlpack-3.1.1/src/mlpack/methods/ann" - but with no success. 

The "not rebuild solution"

`#define private public`

doesn't do the trick for me. 

#### Environment

 * version of mlpack: 3.1.1
 * operating system: Ubuntu 19.04
 * compiler: cmake 3.13.4-1
 * version of dependencies (Boost/Armadillo): 
ensmallen-1.15.1
boost-1.67.0.1
armadillo-9.500.2

#### Expected behavior

Get the weights of the Neural Network

**Comment by zoq** [comment]
Opened #2043, checkout the test case for an example.

**Comment by rirod17** [comment]
Well, the instantiated network can now be exposed, so that's all on my end : )
