### ISSUE TITLE
Use Padding layer in TransposedConvolution layer

### ISSUE THREAD

**Issue by akhandait** [mlpack/mlpack#2051]
#1493 has been merged currently merged without the new `Padding` layer used in it. For consistency, we would prefer using the `Padding` layer instead of defining a function for it. It should not be a very tough task and can be a good first issue for someone looking to contribute.

**Comment by Raahul-Singh** [comment]
@akhandait Hi I'm a newbie here and would like to contribute. Could you please give me a little more information?

**Comment by akhandait** [comment]
Hi @Raahul-Singh, welcome here :). In #1952, a `Padding` layer was added which was then used in `AtrousConvolution` and `Convolution` layers. Before that, padding was done by defining functions in each class. What needs to be done now is to use the `Padding` layer in `TransposedConvolution` layer as well. You might want to check out the above PR to see how it's done in the other two layers.

**Comment by vss96** [comment]
Hey @Raahul-Singh, are you working on this?

**Comment by walragatver** [comment]
Hi @vss96,
It looks like @Raahul-Singh is quite busy. So please feel free to work on this. :+1:

**Comment by Raahul-Singh** [comment]
@vss96 Hi! Sorry for replying so late. I am working on it but I am facing some difficulties, following the code. Please go ahead with it, and I hope to learn from your implementation too!

**Comment by jaibhageria** [comment]
Hey @vss96 are you working on this issue?

**Comment by vss96** [comment]
@jaibhageria Couldn't get around to it. You can pick it up if you want.

**Comment by vss96** [comment]
@jaibhageria Just a heads up, some of the refactoring is not straightforward so take your time and do it :)

**Comment by walragatver** [comment]
Closing this as #2082 is merged
