### ISSUE TITLE
Armadillo matrix representation

### ISSUE THREAD

**Issue by E-Alharbi** [mlpack/mlpack#2061]
Hello, 
I have a question about loading data into Armadillo matrix that is when loads integer numbers from CSV file into a matrix and print it out, it shows them in decimal format.  
For example, 
-163 will be printed in this format -1.6300e+02 
why this happens and how I can fix it?

**Comment by zoq** [comment]
Hello @E-Alharbi you can set the precision:

```
cout.precision(11);
cout.setf(ios::fixed);
```

or if you know you will work with integers only you could store the result into: ``arma::Mat<int>`` instead of ``arma::mat`` (``arma::Mat<double>``).

**Comment by E-Alharbi** [comment]
Thanks for your reply. 
The problem of using arma::Mat<int> cause a compiler error because  Train and Predict methods only accept  :Mat<double>. Any suggestion?

**Comment by E-Alharbi** [comment]
I used` arma::conv_to<arma::Mat <int>>::from(a)` and this solved the problem.

**Comment by zoq** [comment]
You are right, most methods take `arma::mat` as input, in your case you can just convert the input or load the data as `arma::mat` as you did before; as the issue you described above is just about how we represent the data.
