### ISSUE TITLE
RNNs and FFNs should issue clear errors if the input is the wrong shape

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#2071]
#### Issue description

When building a neural network, it's often the case that getting the input shape right can be a little confusing (for instance, see #2048, although that is far from the only issue of that type).  Unfortunately, the error output we have now is not so great.  Take this example, where I've passed an 11-dimensional input to an RNN whose first layer has 256 neurons:

```
error: matrix multiplication: incompatible matrix dimensions: 128x256 and 11x1
terminate called after throwing an instance of 'std::logic_error'
  what():  matrix multiplication: incompatible matrix dimensions: 128x256 and 11x1
Aborted
```

That can make it really hard to debug what is going wrong, and every time I encounter this I end up pulling out `gdb` to figure out exactly where the error was---and then after a bunch of digging I find out that the input size was simply a little bit wrong.

#### Your environment

 * version of mlpack: git master
 * operating system: Debian :penguin:
 * compiler: gcc 8.3.0
 * version of dependencies (Boost/Armadillo): Boost 1.67, Armadillo 9.600.5
 * any other environment information you think is relevant: This should be reproducible on any system.

#### Steps to reproduce

Here's an example program:

```
#include <mlpack/core.hpp>
#include <mlpack/methods/ann/rnn.hpp>
#include <mlpack/methods/ann/ffn.hpp>
#include <mlpack/methods/ann/layer/lstm.hpp>
#include <mlpack/methods/ann/layer/dropout.hpp>

#include <vector>
#include <string>

int main(int argc, char *argv[])
{
  using namespace mlpack;
  using namespace mlpack::data;
  using namespace mlpack::tree;
  using namespace mlpack::cv;
  using namespace mlpack::ann;
  using namespace arma;

  // We have to make sure backpropagation through time doesn't take more
  // time steps than we have.
  const int maxLineLength = 17;
  const int hiddenSize = 128;
  const int numLetters = 256;

  using MatType = cube;
  std::vector<std::string> trainingData;
  trainingData.push_back(std::string("THIS IS THE INPUT"));

  //This is the orignal network that I used (FFN) but then I also tried a RNN
  RNN<> rnn(maxLineLength);
  rnn.Add<IdentityLayer<>>();
  rnn.Add<LSTM<>>(numLetters, hiddenSize, maxLineLength);
  rnn.Add<Dropout<>>(0.1);
  rnn.Add<Linear<>>(hiddenSize, numLetters);

  const auto makeInput = [](const char *line) -> MatType {
    const auto strLen = strlen(line);
    // rows: number of dimensions
    // cols: number of sequences/points
    // slices: number of steps in sequences
    MatType result(numLetters, 1, strLen, fill::zeros);
    for(int i = 0; i < strLen; ++i)
    {
      const auto letter = line[i];
      result.at(static_cast<uword>(letter), 0, i) = 1.0;
    }
    return result;
  };

  const auto makeTarget = [] (const char *line) -> MatType {
    const auto strLen = strlen(line);
    // responses for NegativeLogLikelihood should be
    // non-one-hot-encoded class IDs (from 1 to num_classes)
    cube result(1, 1, strLen, fill::zeros);
    // the response is the *next* letter in the sequence
    for(int i = 0; i < strLen - 1; ++i)
    {
      const auto letter = line[i + 1];
      result.at(0, 0, i) = static_cast<uword>(letter) + 1.0;
    }
    // the final response is empty, so we set it to class 0
    result.at(0, 0, strLen - 1) = 1.0;
    return result;
  };

  std::vector<cube> inputs(trainingData.size());
  std::vector<cube> targets(trainingData.size());
  for(int i = 0; i < trainingData.size(); ++i)
  {
    inputs[i] = makeInput(trainingData[i].c_str());
    targets[i] = makeTarget(trainingData[i].c_str());
  }

  ens::SGD<> sgd(0.01, 1, 100 /* only 100 maximum iterations, just to see it work */);
  // FAILS with .rows(0, 10)
  // SUCCEEDS without the .rows(0, 10) call (because it is the right shape)
  rnn.Train(inputs[0].rows(0, 10), targets[0], sgd);
  return 0;
}
```

I compiled this in my mlpack build directory like this:

```
$ g++  -g -O0 -o test ../test.cpp -Iinclude/ -Llib/ -lmlpack -larmadillo -I deps/stb/ -I deps/ensmallen-2.10.3/include/ -fopenmp
```

#### Expected behavior

I think it would be really helpful if the error given was along the lines of

```
RNN<>::Train(): the first layer of the network expects 256 elements, but the input has 11 rows!  Check your input size for correctness: the number of rows in the input should be 256.
```

#### Actual behavior

This is the displayed error:

```
$ ./test 

error: matrix multiplication: incompatible matrix dimensions: 128x256 and 11x1
terminate called after throwing an instance of 'std::logic_error'
  what():  matrix multiplication: incompatible matrix dimensions: 128x256 and 11x1
Aborted
```

#### Notes for helping out

If you're interested in helping out, and you're not currently familiar with the neural network code, these steps could be helpful.

1.  Spend a little time reading through the `FFN` and `RNN` classes in `src/mlpack/methods/ann/ffn.hpp`, `src/mlpack/methods/ann/ffn_impl.hpp`, `src/mlpack/methods/ann/rnn.hpp`, and `src/mlpack/methods/ann/rnn_impl.hpp`.  Specifically, it's important to understand how the `Train()`, `Predict()`, `Evaluate()`, and `EvaluateWithGradient()` functions work, as those are what will be called during training and testing time.
2.  Figure out how to get the expected input size from the first layer of the network.
3.  Compare what's given to `Train()` or `Predict()` with that, and generate an error message.

It may take a while to understand the code well enough to contribute to this issue, but the actual patch itself is likely to be relatively few lines (maybe 10 to 20 total?).

**Comment by khizirsiddiqui** [comment]
@rcurtin I would like to take up this issue.

**Comment by rcurtin** [comment]
Sure, feel free---once you have a PR ready I'll do my best to review it quickly. :+1:

**Comment by khizirsiddiqui** [comment]
@rcurtin I have opened a PR, if you could look into it and see if it satisfies the requirement.

**Comment by rcurtin** [comment]
Awesome, thanks---I'll take a look when I have a chance.

**Comment by vikram2000b** [comment]
I would like take up this issue. Is it still open?

**Comment by rcurtin** [comment]
Hi @vikram2000b, you can probably see from the comments right above yours that a PR is already open.  You are welcome to help out by reviewing it. :+1:

**Comment by NippunSharma** [comment]
Hi, I saw that the PR #2122 is still open. Nobody has worked on it for quite some time now. If it is fine can I work on this and open a seperate PR for this issue?

**Comment by rcurtin** [comment]
@NippunSharma sure, feel free!

**Comment by rcurtin** [comment]
It might be a good idea to use #2122 as a starting point. :+1:

**Comment by NippunSharma** [comment]
Hi @rcurtin I have opened a PR for this issue. It is a WIP but it will be helpful if you can go through it and check if my approach is correct or not

**Comment by NippunSharma** [comment]
Hi @rcurtin the PR #2739 is completed. Can you take look at it ?

**Comment by rcurtin** [comment]
@NippunSharma thanks! I'll take a look. :+1:

**Comment by NippunSharma** [comment]
@rcurtin can we close this ? now that #2739 is merged.

**Comment by rcurtin** [comment]
Sorry for the slow response---I just wanted to test that the issue was solved by running the example above.  It works great!  This is awesome:

```
$ ./rnn_test
terminate called after throwing an instance of 'std::logic_error'
  what():  RNN<>::Train(): the first layer of the network expects 256 elements, but the input has 11 dimensions!
Aborted
```

Thanks @NippunSharma!
