### ISSUE TITLE
Missing delete in RangeSearch

### ISSUE THREAD

**Issue by HugoSoszynski** [mlpack/mlpack#2078]
#### Issue description

Hi,

Has I was testing my program with valgrind memcheck and it seems like I came accross a missing `delete`.
This seems to come from the RangeSearch constructor using `new` without deleting the allocated object (maybe because `naive` is not true ?).

#### Your environment

 * version of mlpack: 3.1.1
 * operating system: Ubuntu 19.04
 * compiler: g++ (Ubuntu 8.3.0-6ubuntu1) 8.3.0
 * version of dependencies (Boost/Armadillo):
    * Boost 1.71.0
    * Armadillo 9.599.0
 * any other environment information you think is relevant:

#### Actual behavior

Valgrind trace:
```
==2912== 176 bytes in 1 blocks are definitely lost in loss record 2 of 2
==2912==    at 0x4838DBF: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==2912==    by 0x197BE4: mlpack::range::RangeSearch<mlpack::metric::LMetric<2, true>, arma::Mat<double>, mlpack::tree::KDTree>::RangeSearch(bool, bool, mlpack::metric::LMetric<2, true>) (range_search_impl.hpp:100)
==2912==    by 0x191715: AnomalyThreadManager::Detection() (TAnomalyThreadManager.cpp:63)

...

==2912== LEAK SUMMARY:
==2912==    definitely lost: 176 bytes in 1 blocks
```

TAnomalyThreadManager.cpp line 60-63:
```c++
double epsilon = 100;
const size_t newDataDimension = 2, sizePoint = 5;
arma::Row<size_t> assignments;

// _matrix was filled by a previously executed method.
// _matrix is a member of the current class.
// arma::mat _matrix;

mlpack::pca::PCA<> pcaa;
mlpack::dbscan::DBSCAN<> db(epsilon, sizePoint);

pcaa.Apply(_matrix, newDataDimension);
db.Cluster(_matrix, assignments);
```

range_search_impl.hpp line 100-102:
```c++
referenceSet(new MatType()), // Empty matrix.
treeOwner(false),
naive(naive),
```

**Comment by rcurtin** [comment]
Hey @HugoSoszynski, thank you so much for the clear bug report.  It made it easy for me to dig in and figure out what the problem was, and I've opened a PR in #2079. :+1:

**Comment by HugoSoszynski** [comment]
Thanks a lot @rcurtin for the quick response and fix !
