### ISSUE TITLE
Add manual type specification support to `data::Load()` and `data::Save()`

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#2084]
Right now the mlpack `data::Load()` and `data::Save()` functions automatically determine the type of the file based on the extension.  You can see the documentation here:

http://mlpack.org/doc/mlpack-3.2.1/doxygen/namespacemlpack_1_1data.html#a19805d6585ac8b0be7c4e4b7f081977c

(and the sources are `src/mlpack/core/data/load.hpp`, `src/mlpack/core/data/load_impl.hpp`, `src/mlpack/core/data/save.hpp`, and `src/mlpack/core/data/save_impl.hpp`)

It would be nice to add an additional optional parameter to this that allows manually specifying the format, instead of automatically inferring it.  By default, we should leave the behavior as-is.

Since we load just the Armadillo formats, we can actually use the `arma::file_type` struct (which even has a `auto_detect` member) as the type of this extra parameter.

If you're interested in helping out with this issue, make sure that you first understand the issue above, and then go ahead and make modifications to `data::Load()` and `data::Save()`.  The methods will probably have to be refactored somewhat.  Make sure also that you test the manual format specification functionality in `src/mlpack/tests/load_save_test.cpp`, and update `HISTORY.md` to point out the change.

**Comment by knakul853** [comment]
Taking up : )

**Comment by Hemal-Mamtora** [comment]
I would like to take this up

**Comment by kunakl07** [comment]
I would like to work on this issue, Can I take this issue?

**Comment by heytanay** [comment]
I would like to take a try at this, Am I free to do so?

**Comment by Aa20475** [comment]
I would like to work on this issue. Can I proceed? :D

**Comment by Aa20475** [comment]
I would like to work on this issue. Can I proceed? :D

**Comment by Shikhar-S** [comment]
Please go ahead. I am not working on the issue anymore.

**Comment by Aa20475** [comment]
@Shikhar-S okay thanks for the info!

**Comment by aniket-chowdhury** [comment]
Is anyone still working on this?

**Comment by rcurtin** [comment]
@aniket-chowdhury there currently isn't an open PR.  The issue still needs to be solved.  So feel free! :+1:

**Comment by aniket-chowdhury** [comment]
Great @rcurtin

**Comment by rcurtin** [comment]
Fixed in #2602.
