### ISSUE TITLE
Link error caused by incorrect 'Libs' entry in mlpack.pc file

### ISSUE THREAD

**Issue by tomjpsun** [mlpack/mlpack#2097]
#### Issue description

The `Libs` entry of mlpack.pc  seems to be incorrect, which causes the link error.

#### Your environment

 * version of mlpack: 3.2.2
 * operating system:macOS 10.14.6
 * compiler:clang++
 * version of dependencies (Boost/Armadillo):Boost 1.71, Armadillo 9.800
 * any other environment information you think is relevant:
         clang version 9.0.0 (tags/RELEASE_900/final)
         Target: x86_64-apple-darwin18.7.0
#### Steps to reproduce

Compile the following gist ( compile command is located at the first line )
[test.cpp](https://gist.github.com/tomjpsun/276b6c44046154c7ff11eb17b4c7dded)
#### Expected behavior

Normally, the sample code should be built without problem.

#### Actual behavior

We get the build error message:
ld: library not found for -l/usr/local/lib/libarmadillo.dylib

**Comment by rcurtin** [comment]
Hey @tomjpsun, thanks for reporting the issue!  I opened a PR in #2101.  The fix turns out to be easy. :)  Nice to know someone is getting use out of the pkgconfig files!  I think they make it a lot easier to link against all the mlpack dependencies.

**Comment by rcurtin** [comment]
Fixed via #2101---let me know if that doesn't fix your issue. :+1:

**Comment by tomjpsun** [comment]
Test on [Commit:e35ef2e24](https://github.com/mlpack/mlpack/commit/e35ef2e249be997f03afb51d78d509979583ec32) 
Generated mlpack.pc is:
>Name: mlpack
>Description: scalable C++ machine learning library
>URL: http://www.mlpack.org/
>Version: 3.2.2
>Cflags:  -I/usr/local/include -I/usr/local/include/
>Libs: -L/usr/local/lib -lm -L/usr/local/lib/ -larmadillo -lBoost::program_options >-lBoost::unit_test_framework -lBoost::serialization -lmlpack

The armadillo is OK now, while the Boost libs have incorrect formats.
Since it is get from the CMake `FindBoost` call. 
No idea about what 'mlpack' should fix.

**Comment by rcurtin** [comment]
I guess you are using Boost 1.70? I am not sure why or how they rewrote the CMake scripts so significantly in that version. I have been working around it with the CMake option `-DBoost_NO_BOOST_CMAKE=1`.  I'll reopen this issue and look into some kind of solution that doesn't need that workaround.

**Comment by rcurtin** [comment]
I opened #2107 to work around the Boost CMake issue.  My conclusion is that it would be a massive undertaking to revamp the CMake configuration, and it wouldn't be worth it, so I think we can just hardcode the workaround.

**Comment by tomjpsun** [comment]
IMHO, I agree with the considerations in #2107 . For now its a better choice to go ahead. Thanks for reviewing this problem.

**Comment by rcurtin** [comment]
:+1: since #2107 is merged, I'll go ahead and close this.  Maybe someday we will redo the CMake configuration but it doesn't need to be today.
