### ISSUE TITLE
Python3 Bindings

### ISSUE THREAD

**Issue by barak** [mlpack/mlpack#2106]
I'd like to generate an mlpack Python bindings package for Debian. It's no problem for Python2 (in fact I've pushed the required code to my mlpack fork on github) but that's frowned upon: Python2 is EOL on Debian, and they don't want new modules for it: only Python3.

So, my question/request: do you folks plan to support a Python3 module?

**Comment by rcurtin** [comment]
Already do! :)  Try `-DBUILD_PYTHON_BINDINGS=ON -DPYTHON_EXECUTABLE=/path/to/python3`.

**Comment by barak** [comment]
Maybe update the documentation accordingly?

**Comment by jeffin143** [comment]
![IMG_20191205_194949](https://user-images.githubusercontent.com/21286134/70243420-8dd16680-1798-11ea-9578-aaf4e8424b42.jpg)

@barak , it's there 
How can we make it like bold ??
Or bullet points

**Comment by barak** [comment]
Maybe "to build for Python3, specify -D...=/usr/bin/python3" in `README.md` where it talks about building Python bindings?
