### ISSUE TITLE
No homebrew tap/formulae for mlpack.

### ISSUE THREAD

**Issue by qureshinomaan** [mlpack/mlpack#2108]
# Issue Description
Homebrew is an opensource package management system for macOS users. It is very easy to install libraries using homebrew. <br >
For Example
```
brew install boost
```
If would be great if we can add a tap/formula for mlpack too!.

**Comment by zoq** [comment]
mlpack was part of homebrew/science: https://github.com/Homebrew/homebrew-science which was deprecated some time ago. I did setup: https://github.com/zoq/homebrew-mlpack that can be tabbed or you could use it directly. I'm planning to integrate the steps into a mlpack build page on the homepage.

**Comment by rcurtin** [comment]
@zoq maybe we should submit the `homebrew-mlpack` to the upstream `homebrew` repo? https://github.com/Homebrew/homebrew-core

**Comment by zoq** [comment]
Definitely, will checkout the necessary steps.

**Comment by qureshinomaan** [comment]
OK, Thanks.

**Comment by birm** [comment]
I've added PRs for now following the guide [here](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) based upon https://github.com/zoq/homebrew-mlpack (with some minor edits to pass audit)
PRs are at 
https://github.com/Homebrew/homebrew-core/pull/48036 and 
https://github.com/Homebrew/homebrew-core/pull/48033

**Comment by rcurtin** [comment]
@birm this is really awesome!  Great to see the quick responses from the Homebrew team.  Feel free to triumphantly close this issue once they merge mlpack in. :)

**Comment by birm** [comment]
Both have been merged in. Of course, we'll still need to keep up with new releases.
