### ISSUE TITLE
new mlpack website has old download link

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/mlpack#2109]
http://mlpack.org provides a download link for mlpack 3.1.1, which is outdated; should be 3.2.2 ?

**Comment by rcurtin** [comment]
Crap! It was supposed to deploy to a test location during merge. I will have it fixed before I go to bed.

**Comment by rcurtin** [comment]
Ok, the link at least seems correct now. I still have to do a pass on the whole site to make sure everything is right, but the biggest issue is fixed for now.

**Comment by gmanlan** [comment]
@rcurtin: I think the links @ http://mlpack.org/getstarted.html are still pointnig to the previous mlpack version (MSI/ZIP).
Also, the link to github was not updated (http://mlpack.org/github.html) - there is a comment in the MD that says it should get updated during deployment.

Looking nice!

**Comment by rcurtin** [comment]
@gmanlan thanks for pointing that out---fixed now.  I can't see any other issues with the deployment, so I'll work on turning the rest of the comment into issues on the mlpack/mlpack.org repository. :+1:
