### ISSUE TITLE
Adding 'Valid' and 'Same' padding option in Transposed Convolution layer.

### ISSUE THREAD

**Issue by walragatver** [mlpack/mlpack#2114]
This task is similar to #1988. In #1988 Valid and Same padding option is added into `Convolution` and  `Atrous` Convolution Layer. Similar is to be done for the `TransposedConvolution` Layer. This is a good first issue for new users.

Following would be the basic steps to do:
1. Glance through the changes made in #1988. 
2. Then look at what does `Valid` and `Same` option would mean for `TransposedConvolution` Layer.
    The following links might be helpful for that. 
     https://arxiv.org/abs/1603.07285   
     https://www.tensorflow.org/api_docs/python/tf/nn/conv2d_transpose

3. Then, go through the implementation of `TransposedConvolution`  in `src/mlpack/methods/ann/layer/transposed_convolution_impl.hpp`.
4. Make suitable changes.

**Comment by qureshinomaan** [comment]
I have gone through the docs. I don't have much experience with Armadillo and Boost, but I feel I can learn the basic syntax by working on this issue.

**Comment by walragatver** [comment]
HI @qureshinomaan ,
Feel free to go ahead.

**Comment by dubesar** [comment]
```cpp
if(Padding == 'same'){
    padWidth = 0;
    padHeight = 0
  }
  else if(Padding == 'valid'){
    padWidth == padWidth;
    padHeight == padHeight;
  }
```

This is the code that we can add in the given file. But I am confused about how we can ensure the **same** and the **valid** keywords.

**Comment by walragatver** [comment]
Hi @dubesar, you can look through the codebase to understand what should be done about it.

**Comment by kartikdutt18** [comment]
Hey everyone, I think I understand what needs to be done, is it ok if I try to contribute to this issue?

**Comment by walragatver** [comment]
Hi @kartikdutt18,
Not sure whether @qureshinomaan is working on it. If he is not working on it feel free to go ahead as I don't see any pull request opened up.

**Comment by kartikdutt18** [comment]
Hi @walragatver 
Could you suggest some ways to test the changes made before sending a pull request?

**Comment by walragatver** [comment]
@kartikdutt18, If you refer to section 4 of the paper I have mentioned in my comment you can generate test case from the examples given in it.

**Comment by kartikdutt18** [comment]
> @kartikdutt18, If you refer to section 4 of the paper I have mentioned in my comment you can generate test case from the examples given in it.

Thanks, I will test it out.

**Comment by sainikhit2k** [comment]
Hi is anyone working on this issue  ? If not i could work on this

**Comment by kartikdutt18** [comment]
Hi @sainikhit2k, I have currently take up this issue and almost done with it.

**Comment by Pranshu54** [comment]
Hi, is this issue resolved? If not, I am a beginner and would like to work on it.

**Comment by kartikdutt18** [comment]
Hi @Pranshu54, there is a PR open for this issue and currently taken up by me. In the PR this feature has been added and tested.I think there might be some issue that haven't been taken up.
Thanks.

**Comment by Pranshu54** [comment]
Ok. Thanks for letting me know.

**Comment by saksham189** [comment]
Closing as https://github.com/mlpack/mlpack/pull/2163 has been merged.
