### ISSUE TITLE
Errors in trying to install mlpack on OSX 10.15

### ISSUE THREAD

**Issue by dihelium** [mlpack/mlpack#2115]

**Comment by dihelium** [comment]
Hi, I was trying to install mlpack on OSX 10.15(MacOS Catalina), and I'm getting the following errors, when i execute the command:
‘’’
make -j4
‘’’
‘’’
 build % make
[  0%] Updating arma_config.hpp (if necessary)
[  0%] Built target mlpack_arma_config
[  0%] Updating gitversion.hpp (if necessary)
-- Found Git: /usr/local/bin/git (found version "2.24.1") 
-- gitversion.hpp is already up to date.
[  0%] Built target mlpack_gitversion
Moving header files to include/mlpack/
[  0%] Built target mlpack_headers
[  1%] Generating mlpack.pc (pkg-config) file.
[  1%] Built target pkgconfig
[  1%] Building CXX precompiled header src/mlpack/cotire/mlpack_CXX_prefix.hxx.pch
In file included from /Users/sharvankumar/mlpack-3.2.1/build/src/mlpack/cotire/mlpack_CXX_prefix.hxx:4:
In file included from /Users/sharvankumar/mlpack-3.2.1/build/src/mlpack/cotire/mlpack_CXX_prefix.cxx:4:
In file included from /Users/sharvankumar/mlpack-3.2.1/src/mlpack/prereqs.hpp:16:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:314:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:315:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
/usr/local/include/math.h:749:12: note: 'finite' declared here
extern int finite(double)
           ^
In file included from /Users/sharvankumar/mlpack-3.2.1/build/src/mlpack/cotire/mlpack_CXX_prefix.hxx:4:
In file included from /Users/sharvankumar/mlpack-3.2.1/build/src/mlpack/cotire/mlpack_CXX_prefix.cxx:4:
In file included from /Users/sharvankumar/mlpack-3.2.1/src/mlpack/prereqs.hpp:16:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:316:9: error: no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:317:9: error: no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:318:9: error: no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:319:9: error: no member named 'isgreater' in the global namespace
using ::isgreater;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:320:9: error: no member named 'isgreaterequal' in the global namespace
using ::isgreaterequal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:321:9: error: no member named 'isless' in the global namespace
using ::isless;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:322:9: error: no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:323:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:324:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:325:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:331:9: error: no member named 'abs' in the global namespace; did you mean 'fabs'?
using ::abs;
      ~~^
/usr/local/include/math.h:417:15: note: 'fabs' declared here
extern double fabs(double);
              ^
In file included from /Users/sharvankumar/mlpack-3.2.1/build/src/mlpack/cotire/mlpack_CXX_prefix.hxx:4:
In file included from /Users/sharvankumar/mlpack-3.2.1/build/src/mlpack/cotire/mlpack_CXX_prefix.cxx:4:
In file included from /Users/sharvankumar/mlpack-3.2.1/src/mlpack/prereqs.hpp:16:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:551:28: error: expected a qualified name after 'typename'
_LIBCPP_CONSTEXPR typename enable_if<is_floating_point<_A1>::value, bool>::type
                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:551:37: error: expected ';' at end of declaration
_LIBCPP_CONSTEXPR typename enable_if<is_floating_point<_A1>::value, bool>::type
                                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:551:37: error: expected unqualified-id
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:563:39: error: use of undeclared identifier 'is_floating_point'
_LIBCPP_CONSTEXPR typename enable_if<!is_floating_point<_A1>::value, bool>::type
                                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:563:57: error: '_A1' does not refer to a value
_LIBCPP_CONSTEXPR typename enable_if<!is_floating_point<_A1>::value, bool>::type
                                                        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:561:17: note: declared here
template <class _A1>
                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
CMake Error at /Users/sharvankumar/mlpack-3.2.1/CMake/cotire.cmake:1885 (message):
  cotire: error 1 precompiling
  /Users/sharvankumar/mlpack-3.2.1/build/src/mlpack/cotire/mlpack_CXX_prefix.hxx.
Call Stack (most recent call first):
  /Users/sharvankumar/mlpack-3.2.1/CMake/cotire.cmake:3558 (cotire_precompile_prefix_header)


make[2]: *** [src/mlpack/cotire/mlpack_CXX_prefix.hxx.pch] Error 1
make[1]: *** [src/mlpack/CMakeFiles/mlpack.dir/all] Error 2
make: *** [all] Error 2
‘’’
Now, otherwise when I get these errors, while using g++ to compile a cpp file, i can resolve these errors by providing the directory for including the required header files, by specifying the option:
‘’’
-isysroot /path/to/header/files
‘’’
However, in this case, it does not work since -isysroot is only a valid flag for g++ (or other gcc compilers).  Please help in making this work

**Comment by zoq** [comment]
Can you run `xcode-select --install`, does that help?

**Comment by dihelium** [comment]
Hi @zoq xcode command line tools are already installed.

**Comment by zoq** [comment]
> Now, otherwise when I get these errors, while using g++ to compile a cpp file, i can resolve these errors by providing the directory for including the required header files, by specifying the option:
> ‘’’
> -isysroot /path/to/header/files
> ‘’’

You could replicate that with:

`cmake -DCMAKE_CXX_FLAGS="-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include" ..`
 
or 

`cmake -DCMAKE_CXX_FLAGS="-I/path/to/header/files" ..`


Did you modify the search path?

**Comment by dihelium** [comment]
Hi @zoq , executing the first command in the directory ~/mlpack-3.2.1 gives the following output, of which I'm only showing the last line, since it seems the command executed successfully:
'''
Build files have been written to: /Users/sharvankumar/mlpack-3.2.1
'''
But when I run
'''
make -j4
'''
in the build subdirectory of the mlpack-3.2.1 directory, I'm still getting the same errors as before

**Comment by rcurtin** [comment]
It really looks like the compiler setup is not right on your system and I'd suggest fixing that otherwise compiling everything will be hard. :)  Setting `-isystem` would kind of just be a workaround; ideally you would want your compiler to automatically point to the right place for the system includes.  You could try installing a compiler via Homebrew and abandon the Xcode approach---maybe that would be easier?  Personally, I don't have any particular advice on how to fix the system includes for your existing setup though; I am not familiar with Xcode.

**Comment by dihelium** [comment]
Hi @rcurtin I installed one from Homebrew and it totally worked! I still had to uninstall the xcode compiler by running:
sudo rm -rf /Library/Developer/CommandLineTools
After this, the command 'make -j4' ran just fine.

**Comment by rcurtin** [comment]
Awesome, glad that you got it worked out! :+1:
