### ISSUE TITLE
Object file for serialization_text.cpp taking unusually long to build 

### ISSUE THREAD

**Issue by PRISHIta123** [mlpack/mlpack#2116]
#### Issue description

While building all the installed mlpack modules using the make command, the object file for serialization_text.cpp is taking unusually long to build. I have tried to use the make command to build other NLP modules belonging to mlpack such as the viterbi and hmm modules, it has successfully worked, but is taking more than 3 hours to build this particular object file, the build progress percentage is not going beyond 69%. Any workaround for this would be helpful. 

#### Your environment

 * version of mlpack: mlpack-3.0.4
 * operating system: Linux Ubuntu 18.04
 * compiler: clang++ 
 * version of dependencies (Boost/Armadillo): 
 * any other environment information you think is relevant:

#### Steps to reproduce

The issue can be reproduced by executing the following commands in the Linux Terminal: 
1. cd mlpack-3.0.4/build 
2. cmake ../ 
3. make -j1 (I am using 1 core to build) 

#### Expected behavior

The build progress should not get stuck in between

#### Actual behavior

If all the dependencies are installed properly (such as boost, armadillo and Doxygen), all the other modules should build quickly, but progress gets stuck when trying to build serialization_text.cpp.

**Comment by rcurtin** [comment]
Thanks for the report.  How much RAM do you have?  I strongly suspect your system is swapping when compiling `serialization_test.cpp`.  Usually I'd recommend 2GB or more---compiling complex C++ template code unfortunately requires a lot of resources.

**Comment by PRISHIta123** [comment]
I currently have 4 GB of RAM

**Comment by PRISHIta123** [comment]
Is there a way to skip building this particular module, and continue with the other ones that are left?

**Comment by rcurtin** [comment]
Ok, great---that should be enough.  Do you know that all the RAM is available for use by your compiler?  Are you running Linux in a VM?  Can you check more about what resources the compiler is using and why it might have hung up?  There's nothing wrong (as far as I know) about the file itself, and I've never heard of this particular file causing slowdowns.

You can comment out `serialization_test.cpp` in `src/mlpack/tests/CMakeLists.txt` if you want to skip the compilation of that file for the tests.  For that matter, if the tests don't matter for your use case, you can configure CMake with `-DBUILD_TESTS=OFF` and none of the tests will be built.

**Comment by PRISHIta123** [comment]
Yes, I am running Linux in a VM. It is working after I commented out the file in the CMake list.
