### ISSUE TITLE
Build error in CMakeLists.txt

### ISSUE THREAD

**Issue by jzy95310** [mlpack/mlpack#2117]
I'm getting the following error when I try building with CMake in armadillo/build, and I'm sure I create a VS 2019 solution file in mlpack directory. Can someone explain what happens?

C:\Users\45329\Desktop\OPT Year 1\Github Open Source Project\mlpack\armadillo-9.800.3\build>cmake -G "Visual Studio 16 2019" -A Win64 -DBLAS_LIBRARY:FILEPATH="C:\Users\45329\Desktop\OPT Year 1\Github Open Source Project\mlpack\mlpack-3.2.2\packages\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a" -DLAPACK_LIBRARY:FILEPATH="C:\Users\45329\Desktop\OPT Year 1\Github Open Source Project\mlpack\mlpack-3.2.2\packages\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a" -DCMAKE_PREFIX:FILEPATH="C:\Users\45329\Desktop\OPT Year 1\Github Open Source Project\mlpack\armadillo-9.800.3" -DBUILD_SHARED_LIBS=OFF ..
-- *** set cmake policy CMP0025 to NEW
-- Selecting Windows SDK version  to target Windows 10.0.18363.
CMake Error at CMakeLists.txt:40 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 12/16/2019 11:43:07 PM.
    Project "C:\Users\45329\Desktop\OPT Year 1\Github Open Source Project\mlpack\armadillo-9.800.3\build\CMakeFiles\3.16.1\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(775,5): error : The OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Win64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\45329\Desktop\OPT Year 1\Github Open Source Project\mlpack\armadillo-9.800.3\build\CMakeFiles\3.16.1\VCTargetsPath.vcxproj]
    Done Building Project "C:\Users\45329\Desktop\OPT Year 1\Github Open Source Project\mlpack\armadillo-9.800.3\build\CMakeFiles\3.16.1\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\Users\45329\Desktop\OPT Year 1\Github Open Source Project\mlpack\armadillo-9.800.3\build\CMakeFiles\3.16.1\VCTargetsPath.vcxproj" (default target) (1) ->
    (_CheckForInvalidConfigurationAndPlatform target) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(775,5): error : The OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Win64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\45329\Desktop\OPT Year 1\Github Open Source Project\mlpack\armadillo-9.800.3\build\CMakeFiles\3.16.1\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.69

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "C:/Users/45329/Desktop/OPT Year 1/Github Open Source Project/mlpack/armadillo-9.800.3/build/CMakeFiles/CMakeOutput.log".

**Comment by birm** [comment]
Hello, and thanks for the report.
For building mlpack on windows, [this link](https://github.com/mlpack/mlpack/wiki/WindowsBuild) to the wiki may be of use to you, in case you haven't already seen it.

If I'm reading your report correctly, it looks like you issue arises from the CmakeLists file in armadillo, [here](https://gitlab.com/conradsnicta/armadillo-code/blob/9.900.x/CMakeLists.txt#L40). Also, if you haven't seen the advice from Armadillo on windows building and installation [here](https://gitlab.com/conradsnicta/armadillo-code/blob/9.900.x/README.md#7-windows-installation).

Personally, I think the issue may have to do with registry values associated with "VCTargetsPath"; [see this stackoverflow question](https://stackoverflow.com/questions/20076303/vctargetspath-is-wrong-when-building-with-msbuild-on-build-server).

**Comment by jzy95310** [comment]
@birm Many thanks for your advice! I adjust the Visual Studio project configuration, and there is no problem with MSBuild. However, now the CMake keeps saying that "No CMake_C/CXX_Compiler could be found", but I believe I have already installed MinGW GCC on my computer. Is that a correct C++ compiler for CMake or shall I use another compiler?

Error in command prompt:
-- *** set cmake policy CMP0025 to NEW
-- Selecting Windows SDK version  to target Windows 10.0.18363.
-- The CXX compiler identification is unknown
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:40 (project):
  No CMAKE_CXX_COMPILER could be found.



CMake Error at CMakeLists.txt:40 (project):
  No CMAKE_C_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "C:/Users/45329/Desktop/OPT Year 1/Github Open Source Project/mlpack/armadillo-9.800.3/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/45329/Desktop/OPT Year 1/Github Open Source Project/mlpack/armadillo-9.800.3/build/CMakeFiles/CMakeError.log".

**Comment by birm** [comment]
There are some environment variables and cmake flags that can be used to specify where the compiler is; see this [stackoverflow post](https://stackoverflow.com/questions/32801638/cmake-error-at-cmakelists-txt30-project-no-cmake-c-compiler-could-be-found) which should walk you through that more thoroughly than I could.

If you're curious about why this may have happened, see if any of those values were set to anything before.

For further help, please share what the call to cmake itself was; that would make it much easier to troubleshoot.

**Comment by jzy95310** [comment]
@birm Thank you so much for helping. I carefully went over the error log and found that CMake cannot identify the compiler because my Windows SDK is not correctly installed. I re-install the SDK and it now works fine.
