### ISSUE TITLE
Tutorials link not found 404

### ISSUE THREAD

**Issue by OO7kartik** [mlpack/mlpack#2128]
![image](https://user-images.githubusercontent.com/41287435/71527424-6423df00-2901-11ea-8f9d-39c8ec63f617.png)

In the [Introduction](https://github.com/mlpack/mlpack#1-introduction) the [Tutorials](https://www.mlpack.org/doc/mlpack-git/doxygen/tutorials.html) link seems to not work.
resulting in 

![image](https://user-images.githubusercontent.com/41287435/71527381-2fb02300-2901-11ea-9a71-4235d74d9d87.png)

**Comment by rcurtin** [comment]
Ah, actually, this has to do with ensmallen#153; once a new version of ensmallen is released, the documentation will build correctly, and then this issue will be fixed.  That should happen tomorrow, and I'll close this issue when it works again.  Thank you for reporting this! :)

**Comment by OO7kartik** [comment]
oh cool, :)

**Comment by rcurtin** [comment]
Ok, fixed now that ensmallen 2.11.1 is released.  Thanks for the report! :+1:
