### ISSUE TITLE
Same link with different names.

### ISSUE THREAD

**Issue by OO7kartik** [mlpack/mlpack#2129]
[Introduction](#1-introduction) and [Further documentation](#7-further-documentation) have the same link names differently.
![image](https://user-images.githubusercontent.com/41287435/71528111-59b71480-2904-11ea-8c19-fd0900cb1d57.png)      ![image](https://user-images.githubusercontent.com/41287435/71528130-7d7a5a80-2904-11ea-8757-245da4c35bed.png)

**Comment by zoq** [comment]
With https://github.com/mlpack/mlpack/pull/2130 merged, let's close this one.
