### ISSUE TITLE
mlpack::CLI::ParseCommandLine(argc, argv);

### ISSUE THREAD

**Issue by haozhou00** [mlpack/mlpack#2132]
Dear All, I copied the following code
mlpack::CLI::ParseCommandLine(argc, argv); as it was originally in mlpack's sample code.
However in the visual studio 2017 there is a compiler error - class mlpack::CLI has no
"ParseCommandLine", the other matrix calculation seems work fine for me. Alos, the 
system feedback "unknown compiler version - please run the configure tests and report the results"
anyone can help me to figure out where I did wrong? Many thanks!!

**Comment by rcurtin** [comment]
Hey there @haozhou00, can you post a link to the sample code you are trying to use?  `CLI::ParseCommandLine()` was removed when mlpack 3.0.0 was released (March 2018), so my guess is that the sample code you are looking at is out of date.  If you can point me to the documentation you are using, I can provide more information. :)

**Comment by haozhou00** [comment]
Hey there @rcurtin I think you are absolutely correct. Thanks very much you solved my confuse.
I think the code I copied is outdated. Many thanks you solved my question!!

**Comment by rcurtin** [comment]
Awesome, glad you got it figured out! :+1:
