### ISSUE TITLE
Duplicated evaluations on the same pair of points for Cover-Tree

### ISSUE THREAD

**Issue by robertohueso** [mlpack/mlpack#2134]
#### Issue description

`BaseCase(...)` gets evaluated multiple times for the same pair of points when using `DualTreeTraverser` on Cover-Trees

#### Your environment

 * version of mlpack: 707e65870c6dc88ae78313d4d9b386fac5764ac5
 * operating system: Arch Linux
 * compiler: GCC 9.2.0
 * version of dependencies (Boost/Armadillo): Boost 1.71.0, Armadillo 9.800.3

#### Steps to reproduce

```c++
template<typename TreeType>
class DuplicatedRule
{
 public:
  typedef typename mlpack::tree::TraversalInfo<TreeType> TraversalInfoType;

 private:
  TraversalInfoType traversalInfo;

  size_t lastQueryIndex;

  size_t lastReferenceIndex;

 public:
  DuplicatedRule() { /* Nothing to do. */ }

  //! Base Case.
  double BaseCase(const size_t queryIndex , const size_t refIndex )
  {
    if ((lastQueryIndex == queryIndex) && (lastReferenceIndex == refIndex))
      return 0.0;
    std::cout << queryIndex << ", " << refIndex << ";" << std::endl;
    lastQueryIndex = queryIndex;
    lastReferenceIndex = refIndex;
    return 0;
  }

  //! SingleTree Score.
  double Score(const size_t /* queryIndex */, TreeType& referenceNode)
  {
    traversalInfo.LastReferenceNode() = &referenceNode;
    return 0;
  }

  //! SingleTree Rescore.
  double Rescore(const size_t /* queryIndex */,
                 TreeType& /* referenceNode */,
                 const double oldScore) const { return oldScore; }

  //! Dual-Tree Score.
  double Score(TreeType& queryNode, TreeType& referenceNode)
  {
    traversalInfo.LastQueryNode() = &queryNode;
    traversalInfo.LastReferenceNode() = &referenceNode;
    return 0;
  }

  //! Dual-Tree Rescore.
  double Rescore(TreeType& /* queryNode */,
                 TreeType& /* referenceNode*/ ,
                 const double oldScore) const { return oldScore; }

  //! Get traversal information.
  const TraversalInfoType& TraversalInfo() const { return traversalInfo; }

  //! Modify traversal information.
  TraversalInfoType& TraversalInfo() { return traversalInfo; }
};

BOOST_AUTO_TEST_CASE(CoverDuplicatedPairs)
{
  arma::mat datasetA, datasetB;
  datasetA.randu(2, 100);
  datasetB.randu(2, 100);

  typedef StandardCoverTree<EuclideanDistance, EmptyStatistic, arma::mat>
    TreeType;
  TreeType treeA(datasetA);
  TreeType treeB(datasetB);

  DuplicatedRule<TreeType> rule;
  TreeType::template DualTreeTraverser<DuplicatedRule<TreeType>> traverser(rule);
  traverser.Traverse(treeA, treeB);
}
```

#### Expected behavior

No branches are pruned so it should print every possible **unique** combination of query and reference points.

#### Actual behavior

The same pair of points is printed multiple times, this means that `BaseCase(...)` is being executed multiple times on the same pair of points.

I'm already working on solving this issue :smile:

**Comment by rcurtin** [comment]
Thanks for writing this up and coming up with an easy-to-reproduce test case.  We should definitely add that to `tree_test.cpp` when you get it figured out. :)

I think that this is an error in the cover tree's dual tree traversal, specifically at line 126 in `dual_tree_traverser_impl.hpp`.  The `if` statement here is attempting to catch the situation where we have recursed into the self-child of the query and reference nodes, meaning that we have definitely done the base case between the points held in each of those already.

But I think that this misses a couple situations, which is what causes the tests to fail above.  Each cover tree node is associated with a `scale` parameter, and when we recurse in a cover tree (whether that's single-tree or dual-tree), we go from large scale to small scale.  So, suppose we have a very simple situation: consider a query node `q1` with scale `3`, and that query node has a self-child `q2` of scale `0`.  Then consider a reference node `r1` with scale `2`, and that reference node has a self-child `r2` of scale `1`.  If, during the course of a dual-tree traversal, we encounter the combination `(q1, r1)`, the recursion order will be this (ignoring any other children that `q1` or `r1` may have):

 * `(q1, r1)`: scales are `(3, 2)`
 * `(q2, r1)`: scales are `(0, 2)`: we recursed in the node that had largest scale, which was `q1`
 * `(q2, r2)`: scales are `(0, 1)`: we recursed in the node that had largest scale, which was `r1`

But when you take this in combination with the condition above... we'll run the base case on the points *both* at `(q1, r1)`, and `(q2, r1)`!  So the condition needs to be modified to consider the situations that we may recurse in only one.

Anyway, I *think* this is the issue.  It might not be exactly it.  But it's what springs to mind when I read the report. :)
