### ISSUE TITLE
No MacOS installation guide in "Get Started". 

### ISSUE THREAD

**Issue by qureshinomaan** [mlpack/mlpack#2137]
#### Description of problem
Now that the #2108 is fixed, we should update the getting started page of mlpack website. The users can directly install mlpack using homebrew.
https://www.mlpack.org/getstarted.html

**Comment by zoq** [comment]
Agreed, if you like to take a look at it, please free. Happy to help.

**Comment by qureshinomaan** [comment]
Hey @zoq, I have created a pull request in mlpack/mlpack.org
Here is the link to it :
https://github.com/mlpack/mlpack.org/pull/21

**Comment by rcurtin** [comment]
mlpack/mlpack.org#21 is merged now, so I'll go ahead and close this.
