### ISSUE TITLE
Build error in linux

### ISSUE THREAD

**Issue by manolas478** [mlpack/mlpack#2141]
$ make 
[  0%] Updating arma_config.hpp (if necessary)
[  0%] Built target mlpack_arma_config
Moving header files to include/mlpack/
[  0%] Built target mlpack_headers
[  1%] Generating mlpack.pc (pkg-config) file.
[  1%] Built target pkgconfig
[ 10%] Built target mlpack
running build
running build_py
package init file '/home/tonbo/Desktop/valiappan/contrib/mlpack-3.2.1/build/src/mlpack/bindings/python/mlpack/__init__.py' not found (or not a regular file)
copying /home/tonbo/Desktop/valiappan/contrib/mlpack-3.2.1/build/src/mlpack/bindings/python/mlpack/matrix_utils.py -> build/lib/mlpack
[ 10%] Built target python_copy
[ 10%] Generating ../../bindings/python/generate_pyx_sparse_coding.cpp
Scanning dependencies of target generate_pyx_sparse_coding
[ 11%] Building CXX object src/mlpack/methods/sparse_coding/CMakeFiles/generate_pyx_sparse_coding.dir/__/__/bindings/python/generate_pyx_sparse_coding.cpp.o
[ 11%] Building CXX object src/mlpack/methods/sparse_coding/CMakeFiles/generate_pyx_sparse_coding.dir/__/__/bindings/python/print_pyx.cpp.o
[ 11%] Linking CXX executable ../../../../bin/generate_pyx_sparse_coding
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dpbtrf_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgemv_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Ovisit'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Dget_space'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgesv_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Dclose'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5T_NATIVE_LLONG'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dpocon_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Tcopy'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dlansy_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgelsd_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dposvx_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Sclose'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5T_NATIVE_DOUBLE'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgesdd_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5T_NATIVE_INT'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Dread'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dposv_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dtrtrs_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgesvx_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgetrs_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgbcon_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Eget_auto'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dnrm2_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgbsvx_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgeqrf_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dtrcon_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgetrf_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5T_NATIVE_UINT'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Fclose'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgetri_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Dopen'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5T_NATIVE_UCHAR'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dlangb_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Fopen'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Dget_type'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dlange_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dsyrk_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dorgqr_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgtsv_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dpotrf_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Sget_simple_extent_ndims'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgbsv_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5T_NATIVE_ULONG'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5T_NATIVE_SHORT'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma::H5check_version(unsigned int, unsigned int, unsigned int)'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Tclose'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_ilaenv_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgbtrf_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgemm_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dsyevd_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgbtrs_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5T_NATIVE_ULLONG'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dsyev_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Tequal'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dpotri_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Eset_auto'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Tcreate'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgels_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5T_NATIVE_USHORT'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dpotrs_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgesvd_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dtrtri_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5T_NATIVE_FLOAT'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Sget_simple_extent_dims'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5T_NATIVE_LONG'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_ddot_'
../../../../lib/libmlpack.so.3.2: undefined reference to `wrapper2_dgecon_'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5T_NATIVE_CHAR'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Tinsert'
../../../../lib/libmlpack.so.3.2: undefined reference to `arma_H5Fis_hdf5'
collect2: error: ld returned 1 exit status
src/mlpack/methods/sparse_coding/CMakeFiles/generate_pyx_sparse_coding.dir/build.make:107: recipe for target 'bin/generate_pyx_sparse_coding' failed
make[2]: *** [bin/generate_pyx_sparse_coding] Error 1
CMakeFiles/Makefile2:7387: recipe for target 'src/mlpack/methods/sparse_coding/CMakeFiles/generate_pyx_sparse_coding.dir/all' failed
make[1]: *** [src/mlpack/methods/sparse_coding/CMakeFiles/generate_pyx_sparse_coding.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zoq** [comment]
Hello @manolas478 did you install armadillo via the package manager or did you build armadillo manually? Also can you provide some additional system related informations as mentioned in the bug template: https://github.com/mlpack/mlpack/blob/master/.github/ISSUE_TEMPLATE/0-bug.md

**Comment by nappaillav** [comment]
I did face similar issue, it is because of armadillo and hdf5 error. 
@manolas478  You will be encountering the same issue when you compile a test armadillo code also. So I would request you to updated the LD_LIBRARY_PATH variable in `~./bashrc `  

locate the lib folder with the libhdf5.so.10 file and add the corresponding lib folder path to `.bashrc` as explained in the [Link ](https://stackoverflow.com/questions/49435688/error-compiling-armadillo-c-library-on-ubuntu-16-04)

**Comment by manolas478** [comment]
Thanks @zoq and @nappaillav . 
The issue is solved.
