### ISSUE TITLE
Why do we need a template to merge give_init and random_init in AMF?

### ISSUE THREAD

**Issue by jzy95310** [mlpack/mlpack#2147]
Hi Developers,

I just take a thorough look at PR #1367 and read through the changes. I felt a little bit confused about the point of using a class template here: 
`template<typename WInitializationRuleType, typename HInitializationRuleType>`
Since we only want the user to initialize one of W and H matrices with the given matrix and the other one randomly, can I just use multiple constructors to achieve this? For example:
```
MergeInitialization(GivenInitialization& givenInitialization, 
                      RandomInitialization& randomInitialization) : 
  {...}

MergeInitialization(RandomInitialization& randomInitializationRule, 
                      GivenInitialization& givenInitializationRule) : 
  
  {...}`
```
In my opinion, by using a template, we can merge any of the 2 existing rules (not limited to given_init and random_init).But to implement this, other init rules like average_init may also need to be refactored.

**Comment by zoq** [comment]
You are right, we could avoid the two template types, but would have to stick with `given_init and random_init` and yes we would have to adjust some of the other rules, which i think is fine.

**Comment by jzy95310** [comment]
@zoq Thank you for your reply. Also, in PR #1367 you mentioned that given_init should be a one-time initialization rule, but what about random_init? For example, if a user call the function MergeInitialization.Initialize(V, r, W, H) multiple times where H is initialized using random_init rule, is H expected to be the same (only initialized once) or different (initialized multiple times) each time we call this function?

**Comment by zoq** [comment]
The last one, "different (initialized multiple times) each time we call this function", I got it wrong the first time.

**Comment by jzy95310** [comment]
Got it. Thank you!

**Comment by rcurtin** [comment]
Hey @jzy95310, just to add, the choice to use templates for initialization strategies here allows a lot of freedom to the user, who may actually want to implement their own strategy entirely.  So even though we only currently have `RandomInitialization` and `GivenInitialization`, it is still quite flexible. :+1:
