### ISSUE TITLE
Problems compiling mlpack 3.2.2 from source any ideas  as to what I'm doing wrong?

### ISSUE THREAD

**Issue by drboo** [mlpack/mlpack#2149]
I'm trying to build the MLPACK source code on Ubuntu 18.04, I've installed and built all the necessary dependencies including the latest version of Armadillo. 

base) femi@DESKTOP-OMK90ES:~/dev/libs/mlpack-3.2.2/build$ cmake -D DEBUG=ON -D PROFILE=ON ../
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cotire 1.7.10 loaded.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found LIBBFD: /usr/lib/x86_64-linux-gnu/libbfd.so
-- Found LibDL: /usr/lib/x86_64-linux-gnu/libdl.so
-- Performing Test LIBDL_NEEDS_UNDERSCORE
-- Performing Test LIBDL_NEEDS_UNDERSCORE - Failed
-- Found Armadillo: /usr/lib/x86_64-linux-gnu/libarmadillo.so (found suitable version "9.800.3", minimum required is "8.400.0")
-- Armadillo libraries: /usr/lib/x86_64-linux-gnu/libarmadillo.so
-- Found STB_IMAGE: /usr/local/include
-- Found Ensmallen: /usr/local/include (found suitable version "2.11.1", minimum required is "2.10.0")
-- Boost 1.49 found.
-- Found Boost components:
   program_options;unit_test_framework;serialization
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found Git: /usr/bin/git (found version "2.17.1")
-- Regenerating arma_config.hpp.
CMake Warning at CMakeLists.txt:611 (message):
  txt2man not found; man pages will not be generated.

-- Not building Markdown bindings.
-- Found PythonInterp: /home/femi/anaconda3/bin/python (found version "3.7.5")
-- Found Python: /home/femi/anaconda3/bin/python
-- Found PY_distutils: /home/femi/anaconda3/lib/python3.7/distutils
-- Found PY_Cython: /home/femi/anaconda3/lib/python3.7/site-packages/Cython
-- Found PY_numpy: /home/femi/anaconda3/lib/python3.7/site-packages/numpy
-- Found PY_pandas: /home/femi/anaconda3/lib/python3.7/site-packages/pandas
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- CXX target mlpack cotired.
-- CXX target mlpack_test cotired.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/femi/dev/libs/mlpack-3.2.2/build
(base) femi@DESKTOP-OMK90ES:~/dev/libs/mlpack-3.2.2/build$ make -j2

However when I try and compile MLPACK I get the following below:

[  9%] Linking CXX shared library ../../lib/libmlpack.so
[  9%] Built target mlpack
Scanning dependencies of target python_copy
Scanning dependencies of target mlpack_adaboost
[  9%] Building CXX object src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/adaboost_main.cpp.o
[  9%] Built target python_copy
Scanning dependencies of target mlpack_approx_kfn
[  9%] Building CXX object src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/approx_kfn_main.cpp.o
[  9%] Linking CXX executable ../../../../bin/mlpack_adaboost
/usr/lib/x86_64-linux-gnu/libarmadillo.so: undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/build.make:104: recipe for target 'bin/mlpack_adaboost' failed
make[2]: *** [bin/mlpack_adaboost] Error 1
CMakeFiles/Makefile2:1366: recipe for target 'src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/all' failed
make[1]: *** [src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 10%] Linking CXX executable ../../../../bin/mlpack_approx_kfn
/usr/bin/ld: ../../../../bin/mlpack_approx_kfn: hidden symbol `pthread_atfork' in /usr/lib/x86_64-linux-gnu/libpthread_nonshared.a(pthread_atfork.oS) is referenced by DSO
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/build.make:104: recipe for target 'bin/mlpack_approx_kfn' failed
make[2]: *** [bin/mlpack_approx_kfn] Error 1
CMakeFiles/Makefile2:1833: recipe for target 'src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/all' failed
make[1]: *** [src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Any ideas as to what I'm doing wrong, any assistance would be greatly appreciated.

**Comment by adithya-tp** [comment]
hey @drboo , maybe pthread library is missing? I'm not sure though. 

You could install it using:
`sudo apt-get install libpthread-stubs0-dev`

However, do tell me if it is already installed. The problem could be something else.

**Comment by adithya-tp** [comment]
Actually, upon closer inspection, I'm pretty sure this is because doxygen is not installed. Because of the following line in your cmake output:

`Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)`

try installing doxygen using : `sudo apt-get install doxygen`

You should then retry the cmake command, followed by make. Hope this helps!

**Comment by zoq** [comment]
@adithya-tp doxygen is optional, if the cmake configure step failed you will get a corresponding message at the end.

I guess the easiest solution is to install armadillo via conda, instead of building it from source.

**Comment by drboo** [comment]
Hi @adithya-tp thanks for the suggestion I do have pthread library installed, with respect to doxygen I didn't think this necessary I installed all the same and it didn't make any difference

Scanning dependencies of target mlpack_approx_kfn
[ 10%] Building CXX object src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/approx_kfn_main.cpp.o
[ 10%] Linking CXX executable ../../../../bin/mlpack_adaboost
[ 10%] Linking CXX executable ../../../../bin/mlpack_approx_kfn
/usr/lib/x86_64-linux-gnu/libarmadillo.so: undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/build.make:104: recipe for target 'bin/mlpack_adaboost' failed
make[2]: *** [bin/mlpack_adaboost] Error 1
CMakeFiles/Makefile2:1398: recipe for target 'src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/all' failed
make[1]: *** [src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: ../../../../bin/mlpack_approx_kfn: hidden symbol `pthread_atfork' in /usr/lib/x86_64-linux-gnu/libpthread_nonshared.a(pthread_atfork.oS) is referenced by DSO
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/build.make:104: recipe for target 'bin/mlpack_approx_kfn' failed
make[2]: *** [bin/mlpack_approx_kfn] Error 1
CMakeFiles/Makefile2:1865: recipe for target 'src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/all' failed
make[1]: *** [src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Thanks for the suggestion @zoq I'll give your suggestion a go

**Comment by adithya-tp** [comment]
Oh I didn't realize that. Sorry for the misleading info. Thanks for correcting me @zoq !

**Comment by zoq** [comment]
@adithya-tp No worries, the output can be confusing.

**Comment by rcurtin** [comment]
Hey @drboo, can you give some more details about how you installed Armadillo?  I am thinking maybe that is the issue.  If you install Armadillo via `apt-get install libarmadillo-dev`, there should typically be no problem.  Anyway if you can provide more details about that we might be able to get closer to figuring out what is going on. :)

**Comment by drboo** [comment]
Hi @rcurtin I downloaded Armadillo and all its dependencies and built those, then I downloaded mlpack

~/dev/libs/mlpack-3.2.2/build$ cmake -D DEBUG=ON -D PROFILE=ON -D ARMADILLO_INCLUDE_DIR=$ARMADILLO_INCLUDE_DIR -D ARMADILLO_LIBRARY=$ARMADILLO_LIBRARY ..

where $ARMADILLO_INCLUDE_DIR and $ARMADILLO_LIBRARY point to the include and library paths

Unfortunately, I get the following below: 

[ 79%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/rectangle_tree_test.cpp.o
g++ -pthread -shared -B /home/femi/anaconda3/compiler_compat -L/home/femi/anaconda3/lib -Wl,-rpath=/home/femi/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/mlpack/test_python_binding.o -L/home/femi/dev/libs/mlpack-3.2.2/build/lib -o build/lib.linux-x86_64-3.7/mlpack/test_python_binding.cpython-37m-x86_64-linux-gnu.so -fopenmp /home/femi/dev/libs/mlpack-3.2.2/build/lib/libmlpack.so / /home/femi/anaconda3/lib/libcblas.so /home/femi/anaconda3/lib/liblapack.so
/usr/bin/ld: cannot find /: File format not recognized
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
src/mlpack/bindings/python/tests/CMakeFiles/build_pyx_test_python_binding.dir/build.make:57: recipe for target 'src/mlpack/bindings/python/tests/CMakeFiles/build_pyx_test_python_binding' failed
make[2]: *** [src/mlpack/bindings/python/tests/CMakeFiles/build_pyx_test_python_binding] Error 1
CMakeFiles/Makefile2:806: recipe for target 'src/mlpack/bindings/python/tests/CMakeFiles/build_pyx_test_python_binding.dir/all' failed
make[1]: *** [src/mlpack/bindings/python/tests/CMakeFiles/build_pyx_test_python_binding.dir/all] Error 2
[ 79%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/recurrent_network_test.cpp.o
[ 79%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/regularized_svd_test.cpp.o
g++ -pthread -shared -B /home/femi/anaconda3/compiler_compat -L/home/femi/anaconda3/lib -Wl,-rpath=/home/femi/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/mlpack/adaboost.o -L/home/femi/dev/libs/mlpack-3.2.2/build/lib -o build/lib.linux-x86_64-3.7/mlpack/adaboost.cpython-37m-x86_64-linux-gnu.so -fopenmp /home/femi/dev/libs/mlpack-3.2.2/build/lib/libmlpack.so / /home/femi/anaconda3/lib/libcblas.so /home/femi/anaconda3/lib/liblapack.so
/usr/bin/ld: cannot find /: File format not recognized
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
src/mlpack/methods/adaboost/CMakeFiles/build_pyx_adaboost.dir/build.make:57: recipe for target 'src/mlpack/methods/adaboost/CMakeFiles/build_pyx_adaboost' failed
make[2]: *** [src/mlpack/methods/adaboost/CMakeFiles/build_pyx_adaboost] Error 1
CMakeFiles/Makefile2:1435: recipe for target 'src/mlpack/methods/adaboost/CMakeFiles/build_pyx_adaboost.dir/all' failed

I will attempt installing Armadillo via apt-get and let you know how I get on

**Comment by rcurtin** [comment]
Thanks for the output.  This seems different from the original output that you were getting.  I do think using apt for installation will help, but if you want to keep debugging the setup you currently have I'd be happy to try and help.  If so, can you tell me what `ARMADILLO_INCLUDE_DIR` and `ARMADILLO_LIBRARY` are?  Also, the value of `ARMADILLO_LIBRARIES` in `CMakeCache.txt` would be helpful.  It looks like the linker is trying to link against `/` as a library for some reason.

**Comment by drboo** [comment]
@rcurtin  I tried using apt-get install and got the following
[  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_autoencoder/maximal_inputs.cpp.o
make[2]: *** No rule to make target '/usr/lib/libarmadillo.so', needed by 'lib/libmlpack.so.3.2'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_coding/sparse_coding.cpp.o
CMakeFiles/Makefile2:338: recipe for target 'src/mlpack/CMakeFiles/mlpack.dir/all' failed
make[1]: *** [src/mlpack/CMakeFiles/mlpack.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

I'll pick this up again when I'm back in the office tomorrow

**Comment by rcurtin** [comment]
Did you clean your build directory before reconfiguring with the new Armadillo? (i.e. remove all the files in it and reconfigure with CMake)

**Comment by drboo** [comment]
@rcurtin  I did clean the directory and still no joy. I decided to go back to the version of Armadillo I had built myself, verified its dependencies

base) femi@DESKTOP-OMK90ES:~/dev/libs/mlpack-3.2.2/build$ ldd ../../armadillo-9.800.3/libarmadillo.so
        linux-vdso.so.1 (0x00007fffc1127000)
        liblapack.so.3 => /usr/lib/x86_64-linux-gnu/liblapack.so.3 (0x00007fdbc3940000)
        libarpack.so.2 => /usr/lib/x86_64-linux-gnu/libarpack.so.2 (0x00007fdbc36f0000)
        libsuperlu.so.5 => /usr/lib/x86_64-linux-gnu/libsuperlu.so.5 (0x00007fdbc3480000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdbc30f0000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdbc2d50000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdbc2b30000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdbc2720000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdbc4c00000)
        libopenblas.so.0 => /usr/lib/x86_64-linux-gnu/libopenblas.so.0 (0x00007fdbc0470000)
        libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007fdbc0090000)
        libblas.so.3 => /usr/lib/x86_64-linux-gnu/libblas.so.3 (0x00007fdbbfe30000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdbbfc10000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fdbbf9c0000)

I then proceeded to set these dependencies explicitly in the CMakeList.txt file by doing the following:

find_package(Armadillo 8.400.0 REQUIRED)
set(ARMADILLO_LIBRARIES "/usr/lib/x86_64-linux-gnu/libopenblas.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libarpack.so;/usr/lib/x86_64-linux-gnu/libla    pack.so;/usr/lib/x86_64-linux-gnu/libblas.so")
message(STATUS "Manually set Armadillo libraries to: ${ARMADILLO_LIBRARIES}")

I then reconfigured the build by setting the paths to the armadillo explicitly:

(base) femi@DESKTOP-OMK90ES:~/dev/libs/mlpack-3.2.2/build$ cmake -D DEBUG=ON -D PROFILE=ON -D ARMADILLO_INCLUDE_DIR=/home/femi/dev/libs/armadillo-9.800.3/include -D ARMADILLO_LIBRARY=/home/femi/dev/libs/armadillo-9.800.3/libarmadillo.so ..
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cotire 1.7.10 loaded.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found LIBBFD: /usr/lib/x86_64-linux-gnu/libbfd.so
-- Found LibDL: /usr/lib/x86_64-linux-gnu/libdl.so
-- Performing Test LIBDL_NEEDS_UNDERSCORE
-- Performing Test LIBDL_NEEDS_UNDERSCORE - Failed
-- ARMA_USE_WRAPPER is not defined, so all dependencies of Armadillo must be manually linked.
-- Using MKL for LAPACK/BLAS: /usr/lib/x86_64-linux-gnu/libiomp5.so
-- Found Armadillo: /home/femi/dev/libs/armadillo-9.800.3/include (found suitable version "9.800.3", minimum required is "8.400.0")
-- Armadillo libraries: /usr/lib/x86_64-linux-gnu/libiomp5.so
-- Manually set Armadillo libraries to: /usr/lib/x86_64-linux-gnu/libopenblas.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libarpack.so;/usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libblas.so
-- Found STB_IMAGE: /usr/local/include
-- Found Ensmallen: /usr/local/include (found suitable version "2.11.1", minimum required is "2.10.0")
-- Boost 1.49 found.
-- Found Boost components:
   program_options;unit_test_framework;serialization
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found Git: /usr/bin/git (found version "2.17.1")
-- Regenerating arma_config.hpp.
CMake Warning at CMakeLists.txt:616 (message):
  txt2man not found; man pages will not be generated.


-- Not building Markdown bindings.
-- Found PythonInterp: /home/femi/anaconda3/bin/python (found version "3.7.5")
-- Found Python: /home/femi/anaconda3/bin/python
-- Found PY_distutils: /home/femi/anaconda3/lib/python3.7/distutils
-- Found PY_Cython: /home/femi/anaconda3/lib/python3.7/site-packages/Cython
-- Found PY_numpy: /home/femi/anaconda3/lib/python3.7/site-packages/numpy
-- Found PY_pandas: /home/femi/anaconda3/lib/python3.7/site-packages/pandas
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- CXX target mlpack cotired.
-- CXX target mlpack_test cotired.
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen missing components:  dot
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ARMADILLO_LIBRARY


-- Build files have been written to: /home/femi/dev/libs/mlpack-3.2.2/build

after which I ran make:
make -j4

with the snippet of the output presented below:
[ 85%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/main_tests/decision_tree_test.cpp.o
Scanning dependencies of target build_pyx_test_python_binding
[ 85%] Building Cython binding test_python_binding.so...
running build_ext
cythoning mlpack/test_python_binding.pyx to mlpack/test_python_binding.cpp
/home/femi/anaconda3/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/femi/dev/libs/mlpack-3.2.2/build/src/mlpack/bindings/python/mlpack/test_python_binding.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
building 'mlpack.test_python_binding' extension
gcc -pthread -B /home/femi/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -UNDEBUG -UHAS_BFD_DL -I/home/femi/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/femi/dev/libs/mlpack-3.2.2/build/src/mlpack/bindings/python/ -I/home/femi/dev/libs/mlpack-3.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/home/femi/dev/libs/armadillo-9.800.3/include -I/usr/include -I/usr/include -I/home/femi/dev/libs/mlpack-3.2.2/build/src/mlpack/.. -I/home/femi/anaconda3/include/python3.7m -c mlpack/test_python_binding.cpp -o build/temp.linux-x86_64-3.7/mlpack/test_python_binding.o -DBINDING_TYPE=BINDING_TYPE_PYX -std=c++11 -fopenmp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/femi/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1830:0,
                 from /home/femi/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/femi/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from mlpack/test_python_binding.cpp:613:
/home/femi/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/mlpack
g++ -pthread -shared -B /home/femi/anaconda3/compiler_compat -L/home/femi/anaconda3/lib -Wl,-rpath=/home/femi/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/mlpack/sparse_coding.o -L/home/femi/dev/libs/mlpack-3.2.2/build/lib -o build/lib.linux-x86_64-3.7/mlpack/sparse_coding.cpython-37m-x86_64-linux-gnu.so -fopenmp /home/femi/dev/libs/mlpack-3.2.2/build/lib/libmlpack.so **/** /usr/lib/x86_64-linux-gnu/libopenblas.so /usr/lib/x86_64-linux-gnu/libpthread.so /usr/lib/x86_64-linux-gnu/libarpack.so /usr/lib/x86_64-linux-gnu/liblapack.so /usr/lib/x86_64-linux-gnu/libblas.so
/usr/bin/ld: cannot find /: File format not recognized
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
src/mlpack/methods/sparse_coding/CMakeFiles/build_pyx_sparse_coding.dir/build.make:57: recipe for target 'src/mlpack/methods/sparse_coding/CMakeFiles/build_pyx_sparse_coding' failed
make[2]: *** [src/mlpack/methods/sparse_coding/CMakeFiles/build_pyx_sparse_coding] Error 1
CMakeFiles/Makefile2:7598: recipe for target 'src/mlpack/methods/sparse_coding/CMakeFiles/build_pyx_sparse_coding.dir/all' failed
make[1]: *** [src/mlpack/methods/sparse_coding/CMakeFiles/build_pyx_sparse_coding.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 85%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/main_tests/decision_stump_test.cpp.o
[ 85%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/main_tests/gmm_generate_test.cpp.o
[ 86%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/main_tests/gmm_probability_test.cpp.o
[ 86%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/main_tests/gmm_train_test.cpp.o
g++ -pthread -shared -B /home/femi/anaconda3/compiler_compat -L/home/femi/anaconda3/lib -Wl,-rpath=/home/femi/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/mlpack/test_python_binding.o -L/home/femi/dev/libs/mlpack-3.2.2/build/lib -o build/lib.linux-x86_64-3.7/mlpack/test_python_binding.cpython-37m-x86_64-linux-gnu.so -fopenmp /home/femi/dev/libs/mlpack-3.2.2/build/lib/libmlpack.so / /usr/lib/x86_64-linux-gnu/libopenblas.so /usr/lib/x86_64-linux-gnu/libpthread.so /usr/lib/x86_64-linux-gnu/libarpack.so /usr/lib/x86_64-linux-gnu/liblapack.so /usr/lib/x86_64-linux-gnu/libblas.so
/usr/bin/ld: cannot find /: File format not recognized
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
src/mlpack/bindings/python/tests/CMakeFiles/build_pyx_test_python_binding.dir/build.make:57: recipe for target 'src/mlpack/bindings/python/tests/CMakeFiles/build_pyx_test_python_binding' failed
make[2]: *** [src/mlpack/bindings/python/tests/CMakeFiles/build_pyx_test_python_binding] Error 1
CMakeFiles/Makefile2:806: recipe for target 'src/mlpack/bindings/python/tests/CMakeFiles/build_pyx_test_python_binding.dir/all' failed
make[1]: *** [src/mlpack/bindings/python/tests/CMakeFiles/build_pyx_test_python_binding.dir/all] Error 2
[ 86%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/main_tests/fastmks_test.cpp.o

What's rather interesting is the fact that it fails trying to navigate a "/" which I can't see how that's been set up - any ideas?

**Comment by rcurtin** [comment]
Hey @drboo, thanks for the clear explanation.  It's really helpful to understand what's going on.

When I read the output it looks to me like the problem occurs when trying to compile the Python bindings.  If you aren't interested in those, you can specify `-DBUILD_PYTHON_BINDINGS=OFF` and they won't be built.  You can also disable building the tests with `-DBUILD_TESTS=OFF`.  I'm not sure what your goals are, so maybe that's useful, maybe it's not.

If you are interested in building the Python bindings, then I'm happy to dig further if you want to too.

Given the error, I agree with you, it seems that somehow a `/` got included in the list of libraries and this is very strange.  Do you think that you could post the contents of the `CMakeCache.txt` file and the `src/mlpack/bindings/python/setup.py` file in the build directory?  Maybe there is a stray `/` in the list of libraries or something and that can help us figure out how it got there. :+1:  (Just for context, CMake will generate the `setup.py` file with all the information that setuptools needs to compile the generated Python bindings, and perhaps there is some issue or typo there.)

**Comment by drboo** [comment]
Hi @rcurtin  thanks so much for your help, I finally succeeded in building MLPACK, I disabled python and the julia bindings. I'll paste the contents of the CMakeCache.txt on Saturday. All in all, I have a successful build now and can proceed with my evaluation.
