### ISSUE TITLE
GMM::Classify() is slow

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#215]
**Reported by rcurtin on 16 Sep 42238823 05:55 UTC**
Currently, in gmm.cpp, `GMM::Classify()` is defined like so:

```

void GMM::Classify(const arma::mat& observations,
                   arma::Col<size_t>& labels) const
{
  // This is not the best way to do this!

  // We should not have to fill this with values, because each one should be
  // overwritten.
  labels.set_size(observations.n_cols);
  for (size_t i = 0; i < observations.n_cols; ++i)
  {
    // Find maximum probability component.
    double probability = 0;
    for (size_t j = 0; j < gaussians; ++j)
    {
      double newProb = Probability(observations.unsafe_col(i), j);
      if (newProb >= probability)
      {
        probability = newProb;
        labels[i] = j;
      }
    }
  }
}
```

This is an O(n*m) operation, where m is the number of Gaussians and n is the number of points.  It could be sped up greatly with the use of trees -- using the means of the Gaussians as "reference points" and the phi() function as the distance metric.

In addition, at the very least, running `GMM::Probability()` over and over again for each point is slow, as it will invert each covariance matrix each time the method is called.  It could be replaced with a better call, perhaps to one of the overloads of `phi()` which takes many observations at once.

Migrated-From: http://trac.research.cc.gatech.edu/fastlab/ticket/221

**Comment by VladimirGl** [comment]
Can you explain, that you mean using phi as metric? How we can use this to compute the distance between points? (And we can't compute phi(one observation) for all mixture, becouse it gives us O(m) complexity. ) 
And you propose to build a tree only on means, or on all dataset? (In http://www.ri.cmu.edu/pub_files/pub1/moore_andrew_1998_2/moore_andrew_1998_2.pdf we built kd tree on the all dataset, because it helps us to faster compute each em_fit iteration).
Thanks.

**Comment by rcurtin** [comment]
Give me a couple days to write up the exact algorithm I'm thinking of in a tree-independent way, and then when you implement it you'll only need to implement a `BaseCase()` and `Score()` function, and you won't need to worry about implementing the tree itself or the way that the tree is traversed.

**Comment by rcurtin** [comment]
Okay, so this took more than a couple days.  But here it is...
http://www.ratml.org/pub/pdf/2015single.pdf

The algorithm detailed there is general, and it should not be (too) difficult to use the existing mlpack framework for dual-tree and single-tree algorithms to figure out how to adapt the `BaseCase()` and `Score()` function given there.  An example of another single-tree algorithm in mlpack is the `NeighborSearchRules` class, which implements `BaseCase()` and `Score()`; the version of `Score()` for the single-tree algorithm is `Score(size_t, TreeType&)`.

For this GMM algorithm, the first parameter (`size_t`) isn't really needed so it could be ignored during implementation.

Anyway, if there are any errors or difficulties in the document, let me know and I'll happily revise it...
