### ISSUE TITLE
Refactor STB code into a .cpp file

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#2152]
#### Issue description

When using `data::Load()` to load images with STB, the `HAS_STB` macro must be set.  But this means that the user must actually specify `HAS_STB` if they are compiling a program that links against mlpack or includes it.

Not only is there no documentation for that, it's actually not necessary either: it is possible to refactor this code such that the image loading code is not in a header file at all, `HAS_STB` is not necessary, and whether or not the library will load images depends on whether or not STB was available at compile time.

#### Your environment

 * version of mlpack: git master
 * operating system: Linux
 * compiler: any
 * version of dependencies (Boost/Armadillo): any
 * any other environment information you think is relevant:

#### Steps to reproduce

To reproduce this issue, see the discussion on the mailing list or the linked issue:

 - http://knife.lugatgt.org/pipermail/mlpack/2020-January/004142.html
 - https://github.com/mlpack/models/issues/35#issuecomment-571184576

#### Expected behavior

Code that links against or uses mlpack should not need to specify `-DHAS_STB` during compilation, or the include path for STB.

Whether or not image loading works should depend entirely on whether or not STB was available at the time of mlpack compilation (not at the time of compilation of the program that links against mlpack).

#### Actual behavior

Currently any code that links against mlpack that tries to use `data::Load()` must be compiled with `-DHAS_STB` otherwise it will throw the following exception:

```
terminate called after throwing an instance of 'std::runtime_error' 
what(): Load(): HAS_STB is not defined, so STB is not available and images cannot be loaded!
Aborted (core dumped)
```

#### How to solve the issue

The problem here is that the code that uses STB is in a header file.  That means any program that includes mlpack will have to include this header file.  Specifically, `load.hpp` and `load_image.hpp` and `load_image_impl.hpp`, in the directory `src/mlpack/core/data/`, all depend on the `HAS_STB` macro.

It is possible to refactor this code such that the code that calls out to STB's image loading functions can be entirely placed inside of a new file `load_image.cpp`, which can be compiled into the library itself (i.e. into libmlpack.so).  Then, `load.hpp` and `load_image.hpp` can be refactored such that the `HAS_STB` macro is not present in them.

**Comment by vsai121** [comment]
Hey! I'm a beginner here. Can I take up this issue?

**Comment by jeffin143** [comment]
> Hey! I'm a beginner here. Can I take up this issue?

Sure, Go ahead @vsai121

**Comment by DantrazTrev** [comment]
Is this issue still open?

**Comment by jeffin143** [comment]
> Is this issue still open?

Yes it is open , you can ping @vsai121 , to know if he is working currently on the issue

**Comment by vsai121** [comment]
> > Is this issue still open?
> 
> Yes it is open, you can ping @vsai121, to know if he is working currently on the issue

Hey! I'm kinda stuck here and need some help. I understand what the issue is, but I am confused as to how to start solving it. It would be helpful if you can give me a starting point and I can proceed from there.
Thank you.

**Comment by himanshupathak21061998** [comment]
@vsai121 I think you should try to read the issue description carefully and for solving this issue try to create a file `load_image.cpp` to put all the code which uses STB like here.
https://github.com/mlpack/mlpack/blob/dcfcff4a91bf93f1486a5716b222263153fea1b4/src/mlpack/core/data/load_image_impl.hpp#L47
In that file.

**Comment by PranavReddyP16** [comment]
@rcurtin I'm new here and if this issue is still open I would like to work on it. Has it been solved yet?

**Comment by rcurtin** [comment]
@PranavReddyP16 it's not closed, so yes, it's still open.  At this point nobody has opened a PR to solve the issue.  If you can do it, it would be great.  Once you have a PR ready let me know and I'll review it.  Thanks. :+1:

**Comment by PranavReddyP16** [comment]
@rcurtin Thanks for the response. I'll get working on it

**Comment by PranavReddyP16** [comment]
Hey, @rcurtin I'm getting an error on this line in the file load_image_impl.hpp:

https://github.com/PranavReddyP16/mlpack/blob/f77ef6197981d04b16dbc3d26fc8c35b4a79bb47/src/mlpack/core/data/load_image_impl.hpp#L40

This error came up when I removed the #ifdef HAS_STB statements. 
The error is:
'loadFileTypes' was not declared in this scope
which wasn't showing up when the ifdef statemement were still there

Do you know why this may be happening or where loadFileTypes is declared before this? Or if you need more information?

**Comment by jeffin143** [comment]
> Hey, @rcurtin I'm getting an error on this line in the file load_image_impl.hpp:
> 
> https://github.com/PranavReddyP16/mlpack/blob/f77ef6197981d04b16dbc3d26fc8c35b4a79bb47/src/mlpack/core/data/load_image_impl.hpp#L40
> 
> This error came up when I removed the #ifdef HAS_STB statements.
> The error is:
> 'loadFileTypes' was not declared in this scope
> which wasn't showing up when the ifdef statemement were still there
> 
> Do you know why this may be happening or where loadFileTypes is declared before this? Or if you need more information?


Here you go @PranavReddyP16  , you need to adjust this out 

https://github.com/PranavReddyP16/mlpack/blob/f77ef6197981d04b16dbc3d26fc8c35b4a79bb47/src/mlpack/core/data/image_info_impl.hpp#L24

**Comment by PranavReddyP16** [comment]
Thanks @jeffin143. Looks like I forgot to change image_info_impl.hpp.
I have a couple more questions and have updated my previous comment accordingly. Can you help me out?

**Comment by jeffin143** [comment]
> Should I delete any unwanted files or leave them as is?

If it's unwanted then you should probably delete it

> I have created load_image.cpp but I don't know if I have to do anything else so that it can be compiled directly into the library itslef as mentioned above.
 
Try and build build Mlpack with your changes if it does build then you are good to go , just go ahead and raise a pr

**Comment by PranavReddyP16** [comment]
Got it. Thanks for all the help :)

**Comment by PranavReddyP16** [comment]
Hey I've submitted a PR and it has passed all the required tests. Can someone please review it?

**Comment by zoq** [comment]
@PranavReddyP16 thanks for opening the PR, someone will review it, once there is time.

**Comment by Vasniktel** [comment]
I found an issue with `FindStbImage.cmake` file: under certain circumstances, it can set `STB_IMAGE_INCLUDE_DIR` incorrectly.
To reproduce this:
- `mkdir build && cd build`
- `cmake <your flags here> ..`
At this point, STB is likely to be downloaded from the Internet.
- open some cmake file and make trivial changes to it (e.g. remove a letter in some warning message)
- try to run `make <your target>`

You should expect to get a compile error that `stb_image.h` is not found.

The reason is here:
```
file(GLOB STB_IMAGE_SEARCH_PATHS
    ${CMAKE_BINARY_DIR}/deps/
    ${CMAKE_BINARY_DIR}/deps/stb)
find_path(STB_IMAGE_INCLUDE_DIR
    NAMES stb/stb_image.h stb/stb_image_write.h
    PATHS ${STB_IMAGE_SEARCH_PATHS})

if(STB_IMAGE_INCLUDE_DIR)
  set(STB_IMAGE_FOUND YES)
  set(STB_IMAGE_INCLUDE_DIR "${STB_IMAGE_INCLUDE_DIR}/stb/")
else ()
```
when `find_path` is being called the first time, it saves `STB_IMAGE_INCLUDE_DIR` in the cache. On a second call, it doesn't do anything and just returns the cached value. CMake then incorrectly appends `/stb` at the end. Thus, we are getting invalid include path

**Comment by jeffin143** [comment]
> I found an issue with `FindStbImage.cmake` file: under certain circumstances, it can set `STB_IMAGE_INCLUDE_DIR` incorrectly.
> To reproduce this:
> 
> * `mkdir build && cd build`
> * `cmake <your flags here> ..`
>   At this point, STB is likely to be downloaded from the Internet.
> * open some cmake file and make trivial changes to it (e.g. remove a letter in some warning message)
> * try to run `make <your target>`
> 
> You should expect to get a compile error that `stb_image.h` is not found.
> 
> The reason is here:
> 
> ```cmake
> file(GLOB STB_IMAGE_SEARCH_PATHS
>     ${CMAKE_BINARY_DIR}/deps/
>     ${CMAKE_BINARY_DIR}/deps/stb)
> find_path(STB_IMAGE_INCLUDE_DIR
>     NAMES stb/stb_image.h stb/stb_image_write.h
>     PATHS ${STB_IMAGE_SEARCH_PATHS})
> 
> if(STB_IMAGE_INCLUDE_DIR)
>   set(STB_IMAGE_FOUND YES)
>   set(STB_IMAGE_INCLUDE_DIR "${STB_IMAGE_INCLUDE_DIR}/stb/")
> else ()
> ```
> 
> when `find_path` is being called the first time, it saves `STB_IMAGE_INCLUDE_DIR` in the cache. On a second call, it doesn't do anything and just returns the cached value. CMake then incorrectly appends `/stb` at the end. Thus, we are getting invalid include path

I second this , I had this issues in past didn't test it again

**Comment by rcurtin** [comment]
@Vasniktel @jeffin143 I thought I fixed this issue in https://github.com/mlpack/mlpack/commit/4d782785f97ac8d96e7cd9d24c352ffd58e6c190, are you still experiencing it?

**Comment by jeffin143** [comment]
> @Vasniktel @jeffin143 I thought I fixed this issue in [4d78278](https://github.com/mlpack/mlpack/commit/4d782785f97ac8d96e7cd9d24c352ffd58e6c190), are you still experiencing it?

Completely missed this commit , didn't fetch the upstream , I will get back on this in a hour

**Comment by Vasniktel** [comment]
> > @Vasniktel @jeffin143 I thought I fixed this issue in [4d78278](https://github.com/mlpack/mlpack/commit/4d782785f97ac8d96e7cd9d24c352ffd58e6c190), are you still experiencing it?
> 
> Completely missed this commit , didn't fetch the upstream , I will get back on this in a hour

Same here :)

**Comment by jeffin143** [comment]
> @Vasniktel @jeffin143 I thought I fixed this issue in [4d78278](https://github.com/mlpack/mlpack/commit/4d782785f97ac8d96e7cd9d24c352ffd58e6c190), are you still experiencing it?

@rcurtin , The issue doesn't exist 

Also I will request you and @Vasniktel to minimize the comment as our comment is off topic. :)

**Comment by kartikdutt18** [comment]
Hey @rcurtin, should we close this as well because of #2312.

**Comment by rcurtin** [comment]
Thanks, you're right! :+1:
