### ISSUE TITLE
Error trying to make mlpack on Ubuntu

### ISSUE THREAD

**Issue by steffkop** [mlpack/mlpack#2153]
I have issues trying to install Mlpack. I first installed it via Package Manager but the linker had some troubles therefore I uninstalled all and I'm trying to build it manually right now. 
I'm at step 

> make clean && VERBOSE=1 make -j2  # The -j is the number of cores you want to use for a build.

and receive this output.

> 
> [ 25%] Building CXX object src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/approx_kfn_main.cpp.o
> cd /home/steffen/mlpack-3.0.4/build/src/mlpack/methods/approx_kfn && /usr/bin/c++  -DARMA_NO_DEBUG -DBOOST_TEST_DYN_LINK -DHAS_OPENMP -DNDEBUG -I/home/steffen/mlpack-3.0.4/src -I/home/steffen/mlpack-3.0.4/build/src/mlpack/..  -Wall -Wextra -ftemplate-depth=1000 -O3 -fopenmp   -DBINDING_TYPE=BINDING_TYPE_CLI -std=gnu++11 -o CMakeFiles/mlpack_approx_kfn.dir/approx_kfn_main.cpp.o -c /home/steffen/mlpack-3.0.4/src/mlpack/methods/approx_kfn/approx_kfn_main.cpp
> c++: internal compiler error: Getötet (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
> src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/build.make:62: recipe for target 'src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/approx_kfn_main.cpp.o' failed
> make[2]: *** [src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/approx_kfn_main.cpp.o] Error 4
> make[2]: Verzeichnis „/home/steffen/mlpack-3.0.4/build“ wird verlassen
> CMakeFiles/Makefile2:1883: recipe for target 'src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/all' failed
> make[1]: *** [src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/all] Error 2
> make[1]: *** Auf noch nicht beendete Prozesse wird gewartet …
> [ 26%] Linking CXX executable ../../../../bin/mlpack_adaboost
> cd /home/steffen/mlpack-3.0.4/build/src/mlpack/methods/adaboost && /usr/bin/cmake -E cmake_link_script CMakeFiles/mlpack_adaboost.dir/link.txt --verbose=1
> /usr/bin/c++   -Wall -Wextra -ftemplate-depth=1000 -O3 -fopenmp  -rdynamic CMakeFiles/mlpack_adaboost.dir/adaboost_main.cpp.o  -o ../../../../bin/mlpack_adaboost -Wl,-rpath,/home/steffen/mlpack-3.0.4/build/lib: ../../../../lib/libmlpack.so.3.0 /usr/lib/x86_64-linux-gnu/libboost_program_options.so /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so /usr/lib/x86_64-linux-gnu/libboost_serialization.so -lpthread /usr/lib/libarmadillo.so /usr/lib/x86_64-linux-gnu/libboost_program_options.so /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so /usr/lib/x86_64-linux-gnu/libboost_serialization.so 
> make[2]: Verzeichnis „/home/steffen/mlpack-3.0.4/build“ wird verlassen
> [ 26%] Built target mlpack_adaboost
> make[1]: Verzeichnis „/home/steffen/mlpack-3.0.4/build“ wird verlassen
> Makefile:140: recipe for target 'all' failed
> make: *** [all] Error 2

Boost is installed and I already used it in a different project to process a csv file. Do I have to edit the CmakeLists.txt?

**Comment by rcurtin** [comment]
Hey there, in this case you need some more RAM or to build without `-j2`. Here's the relevant part of the error output:

```
c++: internal compiler error: Getötet (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-7/README.Bugs for instructions.
```

Basically, when the operating system runs out of RAM, it will kill processes that are using lots of memory---that typically includes the compiler.

You say you had trouble installing from the package manager because of linking; if you were compiling a C++ program against mlpack, are you sure you linked against all the necessary libraries? You could use `pkg-config` for that, for instance. :+1:

**Comment by zoq** [comment]
`c++: internal compiler error: Getötet (program cc1plus)` - `Getötet` sounds german :)

**Comment by steffkop** [comment]
> `c++: internal compiler error: Getötet (program cc1plus)` - `Getötet` sounds german :)

Yes it is ;)

**Comment by steffkop** [comment]
Making with option - j4 helped.

**Comment by rcurtin** [comment]
I'm surprised `-j4` helped; that would actually typically use *more* RAM!  But anyway maybe some other processes were running the first time.  Regardless, it worked, so, 🚀 
:)
