### ISSUE TITLE
confused about the dimension of labels in recurrent_network_test.cpp

### ISSUE THREAD

**Issue by kathy-lee** [mlpack/mlpack#2159]
Hi, I got confused with a rnn test function "BOOST_AUTO_TEST_CASE(SequenceClassificationBRNNTest)"  in line 78-145 of  recurrent_network_test.cpp. The input data has dimension of (1,12,10), and the labels has also dimension (1,12,10), why is not (1,12)? Why is it also a cube type? All the slices of the labels are the same.  Because a training sample is a nosiy sines with length 10, there are 12 sines, so I think one sines should correspond to a single label, I'm confused with this. Could some help me to make it clear? Thanks a lot!

**Comment by rcurtin** [comment]
Hey @kathy-lee, sorry, I don't have an answer for you on this (I'm not familiar with the test), but this question looks really close to #2160.  Can we close one and keep discussion to another?  That makes things easier both for the discussion and for people searching later. :+1:

**Comment by kathy-lee** [comment]
Yes, sure, thanks!

**Comment by kathy-lee** [comment]
will be discussed in [https://github.com/mlpack/mlpack/issues/2160](url)
