### ISSUE TITLE
LayerTypes design problem

### ISSUE THREAD

**Issue by zsogitbe** [mlpack/mlpack#2161]
#### Issue description

The **default BOOST mpl list size is 20**! LayerTypes is much longer already! Even the introduction of MoreTypes is not sufficient for solving this issue! Furthermore CustomLayers (template argument) adds to this list even more items. **This could cause compiler errors and crashes.**
Perhaps this part of the code needs to be redesigned.

#### Your environment

MSVC

**Comment by zoq** [comment]
I guess you already use the latest compiler? When I try to reproduce the issue, I try to use the same compiler as you.

**Comment by zsogitbe** [comment]
I use the latest version of MVS 2017. There is already a MVS 2019 which is newer. I do think however that this problem is only effected by the compiler in how the compilation ends. I guess that there will be some compilers which show an error and some which crash with e.g. a heap is full message. Strangely BOOST is using more list items than there are in LayerTypes, therefore if you decide to cut this in peaces then I think that you need to cut it in smaller peaces than the set BOOST mpl list size. I think that this is the problem.
