### ISSUE TITLE
Windows 64 bit - ZIP link is not working

### ISSUE THREAD

**Issue by saikat-here** [mlpack/mlpack#2165]
#### Problem location

https://www.mlpack.org/getstarted.html

#### Description of problem

The following "Windows 64 bit - ZIP" download link is not working.

![image](https://user-images.githubusercontent.com/2095290/73377067-77511280-42e4-11ea-8e72-f966d086c55e.png)

**Comment by rcurtin** [comment]
Hey @saikat-here, thanks for the report.  I realized that we forgot to get the artifact out of AppVeyor.  I've updated the website (and pushed changes to https://github.com/mlpack/mlpack.org/) and the link should work now. :+1:

**Comment by saikat-here** [comment]
@rcurtin , it's working now, thanks.
