### ISSUE TITLE
Adding soft shrinkage activation function

### ISSUE THREAD

**Issue by ojhalakshya** [mlpack/mlpack#2170]
Hi everyone, I wanted to contribute to the organisation by adding the SOFT SHRINKAGE activation function.
It can be referred from [link](https://pytorch.org/docs/stable/nn.html#torch.nn.Softshrink).
I think simplified activation function might be easier to compute compared to complex functions as they require less CPU resources.
I want to contribute by adding the same, would it be okay if I pursue this further?

**Comment by kartikdutt18** [comment]
Hi @ojhalakshya, I don't think this activation is implemented in this library, I might be wrong. I think this would be okay.However a member of this organization will provide better guidance.

**Comment by zoq** [comment]
@ojhalakshya interessting, I think I haven't seen the activation function in the wild, are you aware of any model/paper that used the function?

**Comment by ojhalakshya** [comment]
Yes, it has been used in Deep Learning Based Noise Reduction for Brain  MR Imaging which can be seen [here](https://www.researchgate.net/publication/335596314_Deep_Learning_Based_Noise_Reduction_for_Brain_MR_Imaging_Tests_on_Phantoms_and_Healthy_Volunteers).
It useful to remove noise when working with machines such as MRI.

**Comment by zoq** [comment]
Thanks for the link, this looks interesting, if you like to see this function please feel free to open a PR.

**Comment by khizirsiddiqui** [comment]
@ojhalakshya how's the progress? Can I take up this if you are busy?

**Comment by kartikdutt18** [comment]
Hi @khizirsiddiqui , There is already a PR open for the same. I think it is ready.

**Comment by kartikdutt18** [comment]
I think we can close this PR. (Contents transferred to #2181 )

**Comment by kartikdutt18** [comment]
@ojhalakshya, Can you close this. Thanks.
