### ISSUE TITLE
Can't find header in mlpack/core/cv/

### ISSUE THREAD

**Issue by hl-xue** [mlpack/mlpack#2173]
Hello, I would like to use mlpack crossvalidation module. But when I did 
`#include <mlpack/core/cv/k_fold_cv.hpp>`, it seemed that this header was not found (mlpack/core/cv seems not exist).
I am using Ubuntu 18.04, and I did `sudo apt-get install libmlpack-dev` for installation.
Do you have any idea why this happens please ?
Thanks a lot.

**Comment by zoq** [comment]
> it seemed that this header was not found (mlpack/core/cv seems not exist).

On your system, did you search for `k_fold_cv.hpp`?

**Comment by hl-xue** [comment]
> > it seemed that this header was not found (mlpack/core/cv seems not exist).
> 
> On your system, did you search for `k_fold_cv.hpp`?

Yes, I have done that, but no file was found.

**Comment by zoq** [comment]
Okay, what mlpack version did you install?

**Comment by hl-xue** [comment]
> Okay, what mlpack version did you install?
I did `sudo apt-get install libmlpack-dev` on ubuntu 18.04. And it installed libmlpack-dev version 2.2.5-1build1.

**Comment by zoq** [comment]
I see, looks like the latest version that was packaged for 18.04 is mlpack 2.2.5, the cv code was added in mlpack 3.0.0. So either you might  be able to update to 19.04 which provides a updated package or you build from source.

**Comment by hl-xue** [comment]
> I see, looks like the latest version that was packaged for 18.04 is mlpack 2.2.5, the cv code was added in mlpack 3.0.0. So either you might be able to update to 19.04 which provides a updated package or you build from source.

OK, thanks. Just to be sure, is the "mlpack 2.2.5" is equivalent to "libmlpack-dev 2.2.5" ?

**Comment by zoq** [comment]
Yes, libmlpack-dev will only install the lib and header files, so no bindings or executables.

**Comment by hl-xue** [comment]
OK, thanks, and when I build from the source, there are also some errors when I did the step of `make`:

The first one occurs at:
`[ 10%] Linking CXX executable ../../../../bin/mlpack_sparse_coding
CMakeFiles/mlpack_sparse_coding.dir/sparse_coding_main.cpp.o: In function `boost::archive::basic_binary_oprimitive<boost::archive::binary_oarchive, char, std::char_traits<char> >::save_binary(void const*, unsigned long) [clone .isra.723]':
sparse_coding_main.cpp:(.text+0x4297): undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception::exception_code, char const*, char const*)'`

I have already installed boost on my computer, do you know why is there this problem please ?

Thanks.

**Comment by zoq** [comment]
Awesome, glad you got it working. Let's close the issue for now; if there is anything that we should clarify, we can reopen it later.
