### ISSUE TITLE
"pip install mlpack" for Windows

### ISSUE THREAD

**Issue by gmanlan** [mlpack/mlpack#2176]
#### Issue description

pip install mlpack on Windows fails to install mlpack: "No matching distribution found for mlpack".

#### Your environment

 * version of mlpack: 3.2.2
 * operating system: Windows 10
 * any other environment information you think is relevant: python 3.6

#### Steps to reproduce

1) pip install mlpack or pip install mlpack3

**Comment by rcurtin** [comment]
Thanks, good to open an issue for this.  I am still fighting with AppVeyor on the mlpack-wheels repo when I'm able to. :( You can see the carnage here: https://ci.appveyor.com/project/mlpack/mlpack-wheels/history

**Comment by gmanlan** [comment]
That's a big bloodbath there. Let me know if you need help, I have a couple of Windows horses to add to the battle.

**Comment by gauthampkrishnan** [comment]
Hello why could we try uploading to Pypi?

**Comment by Karthikeyan564** [comment]
Hey, Is anyone working on this?

**Comment by Prath06** [comment]
I am unable to install the mlpack package on Windows 10.

command: pip install mlpack
message:

ERROR: Could not find a version that satisfies the requirement mlpack (from versions: none)
ERROR: No matching distribution found for mlpack
