### ISSUE TITLE
Adding the GELU activation function

### ISSUE THREAD

**Issue by gaurav-singh1998** [mlpack/mlpack#2179]
Hi everyone, I want to start contributing to this organization by implementing the GELU activation function. The research paper regarding it can found [here](https://arxiv.org/pdf/1606.08415.pdf). Should I go forward with it?

**Comment by himanshupathak21061998** [comment]
Hey @gaurav-singh1998 I was already working on this I have my implentation ready locally I was going to submit a pr for it this evening.

**Comment by himanshupathak21061998** [comment]
Can you try any other issue

**Comment by gaurav-singh1998** [comment]
Okay no problem

**Comment by gaurav-singh1998** [comment]
Can you suggest some other activation function that I can implement or some other good first timer issues because most of them are taken by someone else?

**Comment by himanshupathak21061998** [comment]
You can try for CELU it is quite similar to elu or can see pytorch library for more function.

**Comment by kartikdutt18** [comment]
Hi @himanshupathak21061998, @gaurav-singh1998 you can refer to #2181
