### ISSUE TITLE
Clangd fails to fully index the project

### ISSUE THREAD

**Issue by ocelaiwo** [mlpack/mlpack#2193]
Hello everyone.

I wanted to explore the source code of this project, so I cloned the repository, installed the dependencies and ran `cmake -D CMAKE_EXPORT_COMPILE_COMMANDS=1`
After that, I tried opening the project in emacs with lsp-mode configured. Clangd started indexing the whole project, but in the buffer called `*clangd::stderr*` there were many messages like the following one:
`Failed to compile /home/ocelaiwo/Workspace/mlpack/src/mlpack/tests/linear_regression_test.cpp, index may be incomplete`

And if, for example, I open `columns_to_blocks.hpp`, `arma` namespace gets highlighted red and the popup says
`clang: Use of undeclared identifier 'arma'; did you mean 'std:arma'?`
Does anybody have any idea on how to fix this?
Thank you in advance, sorry if the question is irrelevant to the project itself.

**Comment by mrityunjay-tripathi** [comment]
Can you give us some more info such as which version of Armadillo you have?
Is the directory where Armadillo is installed is included to the path?
