### ISSUE TITLE
Confused with Mean Pooling output.

### ISSUE THREAD

**Issue by kartikdutt18** [mlpack/mlpack#2194]
Hi everyone, I wanted to see output of max pooling layer so I implemented the following code,
```
#include <mlpack/core.hpp>
#include <mlpack/prereqs.hpp>
#include <mlpack/methods/ann/layer/layer.hpp>
using namespace mlpack;
using namespace mlpack::ann;
using namespace std;

int main()
{
  arma::mat input = arma::mat(12, 1);
  // arma::mat input = arma::linspace<arma::colvec>(0,11,12);
  arma::mat output;
  input.zeros();
  input(0)=1;
  input(1)=2;
  input(2)=3;
  input(3)=input(8)=7;
  input(4)=4;
  input(5)=5;
  input(6)=input(7)=6;
  input(10)=8;
  input(11)=9;
  MeanPooling<> layer1(2, 2, 1, 1);
  layer1.InputHeight() = 3;
  layer1.InputWidth() = 4;
  layer1.Forward(std::move(input), std::move(output));
  output.print();
}
```
I got the following output, 

> 3.0000
   4.0000
   5.5000
   4.0000
   4.7500
   7.2500

When run the code on Pytorch using , 
inp = torch.tensor([[[[1,2.,3, 7], [4,5,6,6], [7,0,8,9]]]], dtype = torch.float)
nn.AvgPool2d(2,1)(inp)

I got the following output,
> tensor([[[[3.0000, 4.0000],
          [5.5000, 7.2500]]]]) 

The main difference is that the **number of elements** aren't the same,
Could anyone help me in figuring out what I did wrong?
Sorry If this issue seems fairly obvious, I couldn't seem to figure it out. 
Thanks.
PS: If there aren't test written for pooling layers (that check the output), I would love to work on the same. As I wasn't able to find them in ann_layer_tests.hpp nor as a separate file.

**Comment by mrityunjay-tripathi** [comment]
Actually PyTorch is also returning the same answer.
![pytorch](https://user-images.githubusercontent.com/35535378/74158729-98005d00-4c40-11ea-9ff0-00ff422fb6c7.png)

**Comment by kartikdutt18** [comment]
Ohh thanks, I will check it out. I will reopen this if needed. Thanks.
