### ISSUE TITLE
Adding All Loss Functions

### ISSUE THREAD

**Issue by ojhalakshya** [mlpack/mlpack#2200]
Hello, I was going through loss functions and managed to get a list of loss functions that aren't implemented yet. I found these using pytorch and tensor flow kindly refer for more informations.
The list goes as:

1. HingeEmbedding Loss (taken by me)
2. CosineEmbedding Loss (taken up by @kartikdutt18)
3. MultiLabelMargin Loss
4. TripletMargin Loss
5. L1 Loss
6. BCE Loss

This might not be complete list. I will update this list as I find more.
I hope this is ok with the community. Kindly feel free to take up any of the idle loss functions here.
Thank You. :)

**Comment by gaurav-singh1998** [comment]
Hi, I would like to add MultiLabelMargin Loss, is it okay to move forward?

**Comment by kartikdutt18** [comment]
Hi @gaurav-singh1998, feel free to do so.

**Comment by prince776** [comment]
Hi, I would like to work on L1 loss, is it okay if i work on it?

**Comment by kartikdutt18** [comment]
Feel free to do the same. Just a suggestion, Last time I missed a function that had already been implemented, just check that the function you want to work on hasn't been implemented.

**Comment by codeboy5** [comment]
Hi, I would like to work on TripletMargin Loss, can I start working on it ?

**Comment by kartikdutt18** [comment]
Hi @codeboy5, feel free to do so.

**Comment by ojhalakshya** [comment]
I am quite overwhelmed by the responses :).
Kindly make yourself comfortable with the above list.
You might also like to add some if you get your hands on some by doing some research.

**Comment by UmarJ** [comment]
Hey @ojhalakshya @prince776, I found the L1 loss function [here](https://github.com/mlpack/mlpack/blob/f68fc14a77fbab24d586092ceac2294f62564b18/src/mlpack/core/metrics/lmetric.hpp#L101) as a typedef under the LMetric template.

For anyone looking for information about the addition of metrics, the documentation [here](https://www.mlpack.org/doc/mlpack-3.1.0/doxygen/metrics.html) might be useful.

**Comment by rcurtin** [comment]
Awesome to see this collaborative effort, thanks everyone for pitching in. :+1:

**Comment by ojhalakshya** [comment]
Happy to be of help!
:)

**Comment by himanshupathak21061998** [comment]
Sorry @prince776 I didn't noticed your comment. Let me know if you want to work further.

**Comment by kartikdutt18** [comment]
Hi everyone, I think it would be best if everyone could comment on what they start working on as this would prevent people from working on the same issue. Also if you want to drop an issue then feel free to do the same by leaving a comment.

**Comment by kartikdutt18** [comment]
Hi @prince776, you can work on smooth L1 loss if it hasn't been implemented.

**Comment by codeboy5** [comment]
Hi @kartikdutt18, I am having some problems working with TripletMargin Loss,  can I work on smooth L1 or can you help me a little bit with the triplet loss, I am familiar with the mathematics but have some problem implementing it.
Thanks

**Comment by kartikdutt18** [comment]
Hi @codeboy5, No worries you can leave TripletMargin Loss for now, we can work on it later, Sure you can work on smooth L1, if @prince776 has no issue with and if @prince776 would like it he can work on TripletMarginLoss. I would more than happy to help in anyway I can.
You two can decide what you want implement and I would be more than happy to help.
Thanks for all your work.

**Comment by codeboy5** [comment]
Hi @prince776, can you take up the triplet margin loss?
Thanks a lot in advance!!!

**Comment by ojhalakshya** [comment]
Hey guys, I found BCE(Binary Cross Entropy) loss function and I am adding it to the list as well. If anyone interested kindly feel free to take it.
It can be referred [here](https://towardsdatascience.com/understanding-binary-cross-entropy-log-loss-a-visual-explanation-a3ac6025181a), it is also on pytorch [here](https://pytorch.org/docs/stable/_modules/torch/nn/modules/loss.html).
Thanks.

**Comment by ojhalakshya** [comment]
> Hi everyone, I think it would be best if everyone could comment on what they start working on as this would prevent people from working on the same issue. Also if you want to drop an issue then feel free to do the same by leaving a comment.

I kindly request all to please mention who is taking up which loss function to avoid ambiguity.
You may add it to the following text.

1. HingeEmbedding Loss (taken by me)
2. CosineEmbedding Loss (taken up by @kartikdutt18)
3. MultiLabelMargin Loss
4. TripletMargin Loss
5. L1 Loss
6. BCE Loss

**Comment by codeboy5** [comment]
> > Hi everyone, I think it would be best if everyone could comment on what they start working on as this would prevent people from working on the same issue. Also if you want to drop an issue then feel free to do the same by leaving a comment.
> 
> I kindly request all to please mention who is taking up which loss function to avoid ambiguity.
> You may add it to the following text.
> 
> 1. HingeEmbedding Loss (taken by me)
> 2. CosineEmbedding Loss (taken up by @kartikdutt18)
> 3. MultiLabelMargin Loss
> 4. TripletMargin Loss
> 5. L1 Loss 
> 6. BCE Loss
> 7. Smooth L1 Loss (taken up by @codeboy5)
> 
> Thanks.

**Comment by bicycleman15** [comment]
> > Hi everyone, I think it would be best if everyone could comment on what they start working on as this would prevent people from working on the same issue. Also if you want to drop an issue then feel free to do the same by leaving a comment.
> 
> I kindly request all to please mention who is taking up which loss function to avoid ambiguity.
> You may add it to the following text.
> 
> 1. HingeEmbedding Loss (taken by me)
> 2. CosineEmbedding Loss (taken up by @kartikdutt18)
> 3. MultiLabelMargin Loss
> 4. TripletMargin Loss
> 5. L1 Loss
> 6. BCE Loss (taken up by @bicycleman15)
> 
> Thanks.

**Comment by gaurav-singh1998** [comment]
> > > Hi everyone, I think it would be best if everyone could comment on what they start working on as this would prevent people from working on the same issue. Also if you want to drop an issue then feel free to do the same by leaving a comment.
> > 
> > 
> > I kindly request all to please mention who is taking up which loss function to avoid ambiguity.
> > You may add it to the following text.
> > 
> > 1. HingeEmbedding Loss (taken by me)
> > 2. CosineEmbedding Loss (taken up by @kartikdutt18)
> > 3. MultiLabelMargin Loss (taken up by
@gaurav-singh1998)
> > 4. TripletMargin Loss
> > 5. L1 Loss
> > 6. BCE Loss (taken up by @bicycleman15)
> > 
> > Thanks.

**Comment by codeboy5** [comment]
> > Hi everyone, I think it would be best if everyone could comment on what they start working on as this would prevent people from working on the same issue. Also if you want to drop an issue then feel free to do the same by leaving a comment.
> 
> I kindly request all to please mention who is taking up which loss function to avoid ambiguity.
> You may add it to the following text.
> 
> 1. HingeEmbedding Loss (taken by me)
> 2. CosineEmbedding Loss (taken up by @kartikdutt18)
> 3. MultiLabelMargin Loss
> 4. TripletMargin Loss
> 5. L1 Loss
> 6. BCE Loss
> 7. Itakura-Saito Distance (taken up by @codeboy5 )
> Thanks.

**Comment by codeboy5** [comment]
> > Hi everyone, I think it would be best if everyone could comment on what they start working on as this would prevent people from working on the same issue. Also if you want to drop an issue then feel free to do the same by leaving a comment.
> 
> I kindly request all to please mention who is taking up which loss function to avoid ambiguity.
> You may add it to the following text.
> 
> 1. HingeEmbedding Loss (taken by me)
> 2. CosineEmbedding Loss (taken up by @kartikdutt18)
> 3. MultiLabelMargin Loss
> 4. TripletMargin Loss
> 5. L1 Loss
> 6. BCE Loss
> 7. Root Mean Squared Logarithmic Error (@codeboy5 )
> Thanks.

**Comment by prince776** [comment]
Sorry for the late response @kartikdutt18 I will gladly work on TripletMarginLoss, I was almost done with the L1 loss but it's okay if it's already been done. @codeboy5 Feel free to work on smooth L1 loss.

My internet was out for some time so I couldn't respond. Sorry for the delay.

**Comment by prince776** [comment]
> > > > Hi everyone, I think it would be best if everyone could comment on what they start working on as this would prevent people from working on the same issue. Also if you want to drop an issue then feel free to do the same by leaving a comment.
> > > 
> > > 
> > > I kindly request all to please mention who is taking up which loss function to avoid ambiguity.
> > > You may add it to the following text.
> > > 
> > > 1. HingeEmbedding Loss (taken by me)
> > > 2. CosineEmbedding Loss (taken up by @kartikdutt18)
> > > 3. MultiLabelMargin Loss (taken up by
> > >    @gaurav-singh1998)
> > > 4. TripletMargin Loss (taken up by @prince776 )
> > > 5. L1 Loss
> > > 6. BCE Loss (taken up by @bicycleman15)
> > > 
> > > Thanks.

**Comment by kartikdutt18** [comment]
Great @prince776 , If you need any help, I would more than happy to help in anyway I can. Thanks.

**Comment by codeboy5** [comment]
Hi, @kartikdutt18 , I was searching for loss functions to implement and came across Hellinger Distance 
> https://datascience.stackexchange.com/questions/22725/what-is-hellinger-distance-and-when-to-use-it
> https://gist.github.com/larsmans/3116927
> https://datascience.stackexchange.com/questions/22324/combine-two-sets-of-clusters
It is the probabilistic analog of the Euclidean distance

Can I work on this ?
Best Regards

**Comment by kartikdutt18** [comment]
Sure, just check it hasn't been implemented (I don't think it has but please confirm).

**Comment by badrinath-reddy** [comment]
Hi, @kartikdutt18 , I am new to mlpack and i found **Mean Absolute Percentage Error** which is not implemented.
https://www.tensorflow.org/api_docs/python/tf/keras/losses/MeanAbsolutePercentageError

can i work on this.

**Comment by kartikdutt18** [comment]
Hi @badrinath-reddy, I think this is similar to MAE, if MAE isn't implemented feel free to pursue it.

**Comment by badrinath-reddy** [comment]
there is pull request for L1. So, i think i would be better if i implement Mean Absolute Percentage Error instead of MAE.

**Comment by kartikdutt18** [comment]
Could you give a use for MAPE as it's 100* MAE.

**Comment by kartikdutt18** [comment]
If that's the case we need not add it.

**Comment by badrinath-reddy** [comment]
MAE: **abs(y_true - y_pred)**
MAPE: **100 * abs(y_true - y_pred) / y_true**

It is 100*MAE / y_true. 

Moreover it is used in xgboost.

**Comment by codeboy5** [comment]
> MAE: **abs(y_true - y_pred)**
> MAPE: **100 * abs(y_true - y_pred) / y_true**
> 
> It is 100*MAE / y_true.
> 
> Moreover it is used in xgboost.

I think we can also implement it by adding a parameter in MAE itself, how about it? @kartikdutt18

**Comment by kartikdutt18** [comment]
I think that might be a better idea, However a member will provide better insight.

**Comment by gauthampkrishnan** [comment]
> > > > > Hi everyone, I think it would be best if everyone could comment on what they start working on as this would prevent people from working on the same issue. Also if you want to drop an issue then feel free to do the same by leaving a comment.
> > > > 
> > > > 
> > > > I kindly request all to please mention who is taking up which loss function to avoid ambiguity.
> > > > You may add it to the following text.
> > > > 
> > > > 1. HingeEmbedding Loss (taken by me)
> > > > 2. CosineEmbedding Loss (taken up by @kartikdutt18)
> > > > 3. MultiLabelMargin Loss (taken up by
> > > >    @gaurav-singh1998)
> > > > 4. TripletMargin Loss (taken up by @prince776 )
> > > > 5. L1 Loss ( taken up by @gauthampkrishnan )
> > > > 6. BCE Loss (taken up by @bicycleman15)
> > > > 
> > > > Thanks.

**Comment by gauthampkrishnan** [comment]
Can I take up L1 Loss?

**Comment by kartikdutt18** [comment]
It's taken up by @himanshupathak21061998 . I think all functions have been taken up.

**Comment by gauthampkrishnan** [comment]
ok

**Comment by bisakhmondal** [comment]
Is there any Loss function remaining  I can work with?

**Comment by bisakhmondal** [comment]
Hello @ojhalakshya, I want to contribute to this issue. After looking through different loss functions, I think adding `Sparse Categorical Cross-Entropy` would be a good idea. What do you say? Thanks.

**Comment by ojhalakshya** [comment]
> Hello @ojhalakshya, I want to contribute to this issue. After looking through different loss functions, I think adding `Sparse Categorical Cross-Entropy` would be a good idea. What do you say? Thanks.

Hi @bisakhmondal 
can you add some more details about the same like some research paper of the function.
Thanks.

**Comment by iamshnoo** [comment]
> Hi, I would like to add MultiLabelMargin Loss, is it okay to move forward?

Hi @gaurav-singh1998 are you still working on the MultiLabelMargin Loss or is it okay if I want to take it up?

**Comment by gaurav-singh1998** [comment]
Hi, @iamshnoo you can move forward with it.

**Comment by bisakhmondal** [comment]
Hi @bicycleman15, are you still working on BCE loss?

**Comment by parthsuresh** [comment]
Hi @ojhalakshya and @kartikdutt18 ,

I see that :
- [cosine embedding loss](https://pytorch.org/docs/stable/nn.html#cosineembeddingloss)
-  [multi-margin loss](https://pytorch.org/docs/stable/nn.html#multimarginloss) (not the same as multilabel margin loss)
- [soft margin loss](https://pytorch.org/docs/stable/nn.html#softmarginloss)
- [multilabel soft margin loss](https://pytorch.org/docs/stable/nn.html#multilabelsoftmarginloss)

are loss functions that are implemented in Pytorch but not in mlpack.

I can work on implementing them if you think they would be useful.

**Comment by ojhalakshya** [comment]
I think a draft pr for multilabel soft margin loss is already open. #2345
But I think soft margin loss is available, but it would be good if you can add some some reference of it's use or maybe a research paper. 
It is okay if you proceed with the same :)

**Comment by kartikdutt18** [comment]
Also kindly refer to existing PRs as some of the above loss functions already have a PR open.

**Comment by parthsuresh** [comment]
My bad, I see that a PR for multilabel soft margin loss has been opened. Edited my comment to reflect this.

I could not find a PR for the other three, so I'm starting with Cosine Embedding Loss. Hope that's okay.

Btw, if anyone else wants to start working on the others, go for it.

**Comment by kartikdutt18** [comment]
Hey @parthsuresh, Kindly refer to #2209. It aims to implement Cosine embeddings loss function. Thanks a lot.

**Comment by ojhalakshya** [comment]
> My bad, I see that a PR for multilabel soft margin loss has been opened. Edited my comment to reflect this.
> 
> I could not find a PR for the other three, so I'm starting with Cosine Embedding Loss. Hope that's okay.
> 
> Btw, if anyone else wants to start working on the others, go for it.

I suggest kindly go to the loss functions folder in mlpack code and see if what you want to implement is already there or not.
You can go to this directory for the same.
>mlpack/src/mlpack/methods/ann/loss_functions/

**Comment by parthsuresh** [comment]
Sorry about that @kartikdutt18 , I see the cosine loss now. Edited comment again.

@ojhalakshya , I checked the folder you mentioned before posting my comment but did not check the open PRs, which led to this mistake from my side. I checked again and I'm pretty sure that Soft Margin Loss and Multi Margin Loss have not been implemented yet.

Sorry for the trouble, thank you for your patience.

**Comment by iamshnoo** [comment]
Hi @parthsuresh I have been working on the Multi Label Soft Margin Loss and the Multi Label margin loss. Currently, there is a PR open for the multilabel soft margin loss, which has already been mentioned here. Also, I have been working since last week on multilabel margin loss and soft margin loss locally, haven't create a PR for these two yet. I should be able to push the code within the next week.

So, I guess you can implement the Multi Margin Loss function. Or any other function which isn't already implemented. Thanks!

**Comment by bisakhmondal** [comment]
> Hi @bicycleman15, are you still working on BCE loss?

Hey @kartikdutt18, @ojhalakshya I want to take it up if @bicycleman15 is not working on it.
It's completely fine @bicycleman15 if you are working it. Take your time. It would be great if we can have some response from you. Thanks.

**Comment by bicycleman15** [comment]
> > Hi @bicycleman15, are you still working on BCE loss?
> 
> Hey @kartikdutt18, @ojhalakshya I want to take it up if @bicycleman15 is not working on it.
> It's completely fine @bicycleman15 if you are working it. Take your time. It would be great if we can have some response from you. Thanks.

I am really sorry for the late reply. I was unwell for past few days. I am working on it and will make a PR in a day or two.

**Comment by bisakhmondal** [comment]
Great👍. Get well soon! Looking forward to your PR.

**Comment by ojhalakshya** [comment]
Whichever function you take up, do mention your pr here so that there is confusion for anyone.
Thanks.

**Comment by kartikdutt18** [comment]
Get well soon. Looking forward to your PR.

**Comment by ojhalakshya** [comment]
> > > Hi @bicycleman15, are you still working on BCE loss?
> > 
> > 
> > Hey @kartikdutt18, @ojhalakshya I want to take it up if @bicycleman15 is not working on it.
> > It's completely fine @bicycleman15 if you are working it. Take your time. It would be great if we can have some response from you. Thanks.
> 
> I am really sorry for the late reply. I was unwell for past few days. I am working on it and will make a PR in a day or two.

Get well soon.

**Comment by parthsuresh** [comment]
> Hi @parthsuresh I have been working on the Multi Label Soft Margin Loss and the Multi Label margin loss. Currently, there is a PR open for the multilabel soft margin loss, which has already been mentioned here. Also, I have been working since last week on multilabel margin loss and soft margin loss locally, haven't create a PR for these two yet. I should be able to push the code within the next week.
> 
> So, I guess you can implement the Multi Margin Loss function. Or any other function which isn't already implemented. Thanks!

Understood, will work on the multi-margin loss function.

**Comment by bicycleman15** [comment]
I dont think I'll be able to work on the BCE Loss. Would anyone like to take it up ? Sorry for holding onto it for so long.

**Comment by codeboy5** [comment]
@bicycleman15 I will take it up, no issue.

**Comment by bicycleman15** [comment]
Sure @codeboy5 , go ahead.

**Comment by kartikdutt18** [comment]
Let's keep this open until all PRs related to this are merged.

**Comment by rcurtin** [comment]
Weird, I wonder why mlpack-bot closed it anyway.

**Comment by kartikdutt18** [comment]
Thanks @rcurtin!

**Comment by khizirsiddiqui** [comment]
Can someone update the list with losses already done?

**Comment by ANSH-RIYAL** [comment]
Hi I am an intermediate ML enthusiast and I am trying to contribute to the community. I don't have much experience with contributing to Open Source but I am familiar with Python, C++ libraries like OpenCV and frameworks like PyTorch. 
I opened this issue as I do know about some loss functions used in ML libraries and thought I can contribute but it seems like most (or all) of them are already taken up by people.
Can someone please guide/ direct me towards some issue/ project where I can help/ participate? Much appreciated.

**Comment by kartikdutt18** [comment]
Hey @khizirsiddiqui, @ANSH-RIYAL, I think all the loss functions have a PR open however some of them have gone (or are now closed). Maybe going through the PR might be a good idea and cross reference it with the list of loss functions.
As far as I know these are merged / ready for merging :
HingeEmbedding Loss
CosineEmbedding Loss
MultiLabelMargin Loss
L1 Loss

**Comment by iamshnoo** [comment]
- MultiLabel Margin Loss
- Multi Margin Loss
- Triplet Margin Loss
- Poisson NLL Loss
- CTC Loss

These are loss functions present in PyTorch, but not in mlpack. If anyone is interested in this issue, try picking up one of these and working on it. Every other loss function is either merged or has a open PR or is in progress.

**Comment by iamshnoo** [comment]
> As far as I know these are merged / ready for merging :
> HingeEmbedding Loss
> CosineEmbedding Loss
> MultiLabelMargin Loss
> L1 Loss

L1, Hinge Embedding, Cosine Embedding have been merged.

Multi label soft margin loss is open. No one is working on it.

Multi label soft margin loss is ready for merging.

**Comment by kartikdutt18** [comment]
Keep Open.

**Comment by R-Aravind** [comment]
Hey.. I would like to work on Multi Label Margin loss.

**Comment by iamshnoo** [comment]
> Hey.. I would like to work on Multi Label Margin loss.

Sure, feel free to do so.

**Comment by kartikdutt18** [comment]
Keep Open.

**Comment by kushagrabhushan** [comment]
Hi. I'm very new to open source. Can someone tell me how to get started? I'd really like to contribute!

**Comment by manityagi** [comment]
Hey! I checked the pull requests and I don't see a BCE loss function being implemented. I would like to take this up if it's alright with the community. I find these resources given by @ojhalakshya [this](https://towardsdatascience.com/understanding-binary-cross-entropy-log-loss-a-visual-explanation-a3ac6025181a) and [this](https://pytorch.org/docs/stable/_modules/torch/nn/modules/loss.html) to be helpful and would be using them for my implementation. Any tips and advice is more than welcome as I am new to mlpack and this will be my first issue. 
Thank you

**Comment by Rupeshkoushik** [comment]
Hi , I'm interested in this project can you suggest me ways to get started?

**Comment by ayushsingh11** [comment]
Hello Everyone, I am interested in implementing the Poisson loss function. 
Can I start with this task?

**Comment by ayushsingh11** [comment]
Hello everyone, I would like to take up the Triplet Margin Loss issue. @prince776 you are not still working on that, right?
Should I start afresh or review and comment on https://github.com/mlpack/mlpack/pull/2208?

**Comment by zoq** [comment]
@ayushsingh11 let's see if @prince776 comes back, but I guess the easiest would be to create a new branch and cherry pick the commits from #2208.

**Comment by ayushsingh11** [comment]
Thanks @zoq, will cherry-pick the commits and create a new issue of it subsequently.

**Comment by Anmol2001** [comment]
Hello everyone , can I work on Binary cross entropy function?

**Comment by prince776** [comment]
Thanks, @ayushsingh11 for completing the Triplet Margin Loss PR. 
Sorry for the late response, I was off from Github for quite some time so I didn't respond.

**Comment by hello-fri-end** [comment]
Is there anything left to do here?

**Comment by deeplearningera** [comment]
> 
> 
> Hey guys, I found BCE(Binary Cross Entropy) loss function and I am adding it to the list as well. If anyone interested kindly feel free to take it.
> It can be referred [here](https://towardsdatascience.com/understanding-binary-cross-entropy-log-loss-a-visual-explanation-a3ac6025181a), it is also on pytorch [here](https://pytorch.org/docs/stable/_modules/torch/nn/modules/loss.html).
> Thanks.

Can I work on it?

**Comment by Aakash-kaushik** [comment]
Do you guys thinking we still need this, as a lot of the Functions mentioned in this were initial not there in mlpack but now the state of ann code base has changed and is a lot more mature now, and maybe if a new activation function comes which is worthwhile to implement someone can take it as a feature directly.
