### ISSUE TITLE
LASSO regression (L1 regularization)

### ISSUE THREAD

**Issue by mhangaard** [mlpack/mlpack#2202]
Is it possible to do LASSO regression with mlpack?
I see both linear ridge regression and LARS implemented, but straight LASSO seems not to be available?

**Comment by mhangaard** [comment]
Related to #2200

**Comment by rcurtin** [comment]
Hey @mhangaard, the LARS paper details a simple modification that makes the algorithm equivalent to LASSO.  I believe that our implementation, which is based not just on the original "Least angle regression" paper but also a later paper by Zou and Hastie, will do that if you specify `lambda1 != 0.0`.

So, if you're using the C++ interface, just create LARS as

```
LARS l(useCholesky, lambda1, 0.0);
```

where `lambda1` is greater than `0.0` and it should use the LASSO modification.  If you're using a binding from another language, the interface is basically the same---just ensure that `lambda1` is greater than 0 and `lambda2` is 0.

Let me know if I can clarify anything. :+1:

**Comment by jeffin143** [comment]
@rcurtin , I think so we should document this , 

Is there any way we can add it to websit , where all the methods are there

Since it is automatically generated , I doubt it , but I guess this is worth while adding

**Comment by himanshupathak21061998** [comment]
Hey, @jeffin143 @rcurtin I think it is already mentioned in docs 
https://github.com/mlpack/mlpack/blob/97627c84ca36936af8b79676c91094437a621930/src/mlpack/methods/lars/lars.hpp#L50
Do we need any improvement over this.

**Comment by jeffin143** [comment]
> Hey, @jeffin143 @rcurtin I think it is already mentioned in docs
> https://github.com/mlpack/mlpack/blob/97627c84ca36936af8b79676c91094437a621930/src/mlpack/methods/lars/lars.hpp#L50
> 
> 
> Do we need any improvement over this.

Thanks , just overlooked it , that looks good :)
