### ISSUE TITLE
Removing DecisionStump class from mlpack

### ISSUE THREAD

**Issue by himanshupathak21061998** [mlpack/mlpack#2205]
`DecisionStump` has been marked as deprecated see #2099 . So, in mlpack 4.0.0 release we need to entirely remove `DecisionStump`  as user will use the `DecisionTree`
    class with `NoRecursion=true` or use `ID3DecisionStump` instead of using `DecisionStump`.

**Comment by rcurtin** [comment]
Just as a note to anyone interested in working on this, this issue is kind of a code maintenance task, so if a PR gets opened for it, even if it's approved it shouldn't be merged until the 4.0.0 release is imminent. :+1:

**Comment by PranavReddyP16** [comment]
I would like to work on this issue

**Comment by niranjanrao1509** [comment]
I would like to work on this issue

**Comment by PranavReddyP16** [comment]
@niranjanrao1509 maybe we could collaborate?

**Comment by niranjanrao1509** [comment]
@PranavReddyP16  yeah sure.

**Comment by PranavReddyP16** [comment]
@himanshupathak21061998 Can you please elaborate on what exactly needs to be done regarding this issue in a bit more detail? Thanks.

**Comment by himanshupathak21061998** [comment]
@PranavReddyP16 As you can see in #2099 The `DecisionStump` class has been marked as deprecated. 
https://github.com/mlpack/mlpack/blob/be6d79db6a420bcc243d01d6ea7afc937abb6d65/src/mlpack/methods/decision_stump/decision_stump.hpp#L50
So, now It needs to be removed from mlpack During the mlpack 4.0.0 release. So, only task of this issue is to remove `DecisionStump` from mlpack. Let me know If you want more information regarding this.

**Comment by bisakhmondal** [comment]
@PranavReddyP16 have you solve the issue? Can we collaborate?

**Comment by PranavReddyP16** [comment]
Nope I haven't solved it yet. My college midsemester exams just ended today
so I've been a bit busy. Also I would love to collaborate as I'm not
completely sure how to solve this issue

**Comment by bisakhmondal** [comment]
@PranavReddyP16 okay then, I am acquianted with the codebase. So from where should we start?

**Comment by Shandilya21** [comment]
@himanshupathak21061998  I would like to solve this issue. How can I proceed with this can you explain? I am new contributor.

**Comment by bisakhmondal** [comment]
Hello @Shandilya21, I appreciate your interest👍. But there is already a PR open for the issue. Feel free to have a look.

**Comment by Shandilya21** [comment]
Hello, @bisakhmondal Thanks for your comment. I will look into your PR. 
Thanks for an update.

**Comment by favre49** [comment]
I guess we can close this due to #2266
