### ISSUE TITLE
Error while "make"-ing mlpack on Google Colab Notebook

### ISSUE THREAD

**Issue by joeljosephjin** [mlpack/mlpack#2214]
#### Issue description

Everything until the "make" step ran fine on the colab notebook.
#### Your environment

 * version of mlpack:
 * operating system:
 * compiler:
 * version of dependencies (Boost/Armadillo):
 * any other environment information you think is relevant:

#### Steps to reproduce

https://colab.research.google.com/drive/1TjlXF0frwJLanUEZs4HssAO1CIyuD4Ha - this is the link to the colab notebook. You can take a look at this.

#### Actual behavior
"make -j4" was the command given.

[ -2%] Updating arma_config.hpp (if necessary)
[ -2%] Built target mlpack_arma_config
Moving header files to include/mlpack/
[ -2%] Built target mlpack_headers
[ -1%] Generating mlpack.pc (pkg-config) file.
[ -1%] Built target pkgconfig
[ -1%] Linking CXX shared library ../../lib/libmlpack.so
CMake Error: cmake_symlink_library: System Error: Function not implemented
CMake Error: cmake_symlink_library: System Error: Function not implemented
src/mlpack/CMakeFiles/mlpack.dir/build.make:822: recipe for target 'lib/libmlpack.so.3.2' failed
make[2]: *** [lib/libmlpack.so.3.2] Error 1
make[2]: *** Deleting file 'lib/libmlpack.so.3.2'
CMakeFiles/Makefile2:213: recipe for target 'src/mlpack/CMakeFiles/mlpack.dir/all' failed
make[1]: *** [src/mlpack/CMakeFiles/mlpack.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rcurtin** [comment]
Hey @joeljosephjin, thanks for the report. This particular error looks like a Colab problem, not an mlpack problem:

```
CMake Error: cmake_symlink_library: System Error: Function not implemented
CMake Error: cmake_symlink_library: System Error: Function not implemented
```

So unfortunately I think you'll have to contact the Colab maintainers for this one; we can't fix it here. :(
