### ISSUE TITLE
Documentation for reinforcement learning module not available. Can anyone help me out in running these programs

### ISSUE THREAD

**Issue by niranjanrao1509** [mlpack/mlpack#2217]

**Comment by khizirsiddiqui** [comment]
Hey, @niranjanrao1509 did you try running any program/code yourself? 
You can look here: [Reinforcement Learning Documentation](https://www.mlpack.org/doc/mlpack-3.2.2/doxygen/namespacemlpack_1_1rl.html) for various methods and policies. 
You can also look at various tests implemented like: `reward_clipping_test.cpp`, `rl_components_test.cpp` and `q_learning_test.cpp` to better understand how the RL library is used.

But yeah, I don't think there's a proper tutorial.

**Comment by favre49** [comment]
Since #2295 has been merged, I think we can close this.
