### ISSUE TITLE
Addition of Residual Blocks.

### ISSUE THREAD

**Issue by prince776** [mlpack/mlpack#2225]
Hi, since MLPack doesn't have implementation of Residual Blocks and since they are crucial in making very deep networks I think adding it should be a good idea.

I would like to work on it, but first in which way it should be implemented should be decided. So I opened this issue.

**How it should be implemented?**
I think a residual block should take some variable amount of layers in template parameter then establish a residual connection between the layer's activation just behind the Res blocks and the final layer added to the block. This will offer flexibility to have any type of layer(Dense, Conv etc.) and any number of layers between a residual connection can be added.

Its usage would become somewhat like:
`model.Add<ResBlock<Layertype1,LayerType2,...>>();`

One more detail I'm unsure is If I should add whether the input activation is added to final layer activation or should it be added to weighted sum (input to activation).
Mathematically:
L = final layer , l = initial layer
Option 1: `A[L] = A[L] + A[l]`
Option 2: `A[L] = g( Z[L] + A[l])`

**Comment by zoq** [comment]
`ResBlock` could also be similar to the FFN class, which stores a layer vector and allows adding layers via the `Add` method. About the last layer, it should go over the weighted sum.

**Comment by prince776** [comment]
> `ResBlock` could also be similar to the FFN class, which stores a layer vector and allows adding layers via the `Add` method. About the last layer, it should go over the weighted sum.

Thanks for your suggestion. One last question, when new layer is added to `ResBlock` the residual connection will be changed to add to this new layer right?

**Comment by zoq** [comment]
That is correct.

**Comment by prince776** [comment]
I did it to a great extent but then realized that Residual Connections are already implemented in `Sequential` Layer. I think this Issue can be closed.
