### ISSUE TITLE
Unable to install mlpack using conda command 

### ISSUE THREAD

**Issue by gauthampkrishnan** [mlpack/mlpack#2227]
#### Issue description
Cant install mlpack using conda 

Unable to install mlpack using conda command "conda install -c conda-forge mlpack"
#### Your environment

 * version of mlpack: none
 * operating system: Windows 10
 * compiler:
 * version of dependencies (Boost/Armadillo):
 * any other environment information you think is relevant:

**Comment by rcurtin** [comment]
It's quite hard to get mlpack to build in conda, but it's being worked on in conda-forge/mlpack-feedstock#18.

**Comment by Goshikhar23** [comment]
I faced similiar problem when installing via conda. You can do this instead:
1. Install vcpkg((https://github.com/Microsoft/vcpkg)
2. In cmd, go to vcpkg directory and write this:
    .\vcpkg install mlpack[tools]:x64-windows   (If you wanna install library and its console programs)
    .\vcpkg install mlpack:x64-windows  (If you wanna install just the library)

**Comment by Adityachaturvedi2906** [comment]
to install the package of Mlpack you can run one of the following:
conda install -c conda-forge mlpack
conda install -c conda-forge/label/gcc7 mlpack
conda install -c conda-forge/label/cf201901 mlpack
