### ISSUE TITLE
Addition of hardtanh and tanhshrink activation functions

### ISSUE THREAD

**Issue by PranavReddyP16** [mlpack/mlpack#2228]
Hey everyone, I was thinking we have tanh activation function so why not add hardtanh annd tanhshrink functions too. Just wanted to see what the members think of this idea before moving forward. Would this be ok?

The relevant sources for the above functions can be found here in PyTorch documentation:
HardTanh : https://pytorch.org/docs/stable/nn.html#hardtanh
Tanhshrink: https://pytorch.org/docs/stable/nn.html#tanhshrink

**Comment by prince776** [comment]
Hi @PranavReddyP16 tanhshrink seems like a good idea, can I work on it(if you're not already working on it) . Also hardtanh is already implemented in mlpack.

**Comment by PranavReddyP16** [comment]
Oh I've already finished a good chunk of it. But there are many more activation functions I saw in the pytorch documentation that mlpack doesn't already have. Should we maybe open up an issue covering them?

**Comment by prince776** [comment]
> Oh I've already finished a good chunk of it. But there are many more activation functions I saw in the pytorch documentation that mlpack doesn't already have. Should we maybe open up an issue covering them?

@kartikdutt18 had already opened an issue #2181 for the same purpose, so I'm not sure if we should open a new issue for that. I think we can just add most activation functions in that list.

**Comment by kartikdutt18** [comment]
HardTanh is already implemented .

**Comment by kartikdutt18** [comment]
Agreed, opening up issue to solve the same thing only increases work for members.

**Comment by kartikdutt18** [comment]
I went through the list again, other than tanhshrink I don't see any activation functions that need to implemented.

**Comment by PranavReddyP16** [comment]
Ok I will do that. Thanks for the input

**Comment by PranavReddyP16** [comment]
Hey @prince776 @kartikdutt18 The one problem I'm having with this is computing the inverse of tanhshrink function. I'm unable to work out the mathematics of it. Can either of you help me out?

**Comment by kartikdutt18** [comment]
I would leave the inverse. It's not an algebraically solvable equation.

**Comment by PranavReddyP16** [comment]
Ok thanks
