### ISSUE TITLE
some probability distribution functions not implemented

### ISSUE THREAD

**Issue by mrityunjay-tripathi** [mlpack/mlpack#2230]
I was just going through the codebase and found that some probability distribution functions are missing. Also, there are two directories for distribution functions, one ```src/mlpack/core/dists/``` and other ```src/mlpack/methods/ann/dists/```. Any reasons? Can they be merged into one directory? I am looking ahead for collaboration to implement the remaining distribution functions as well. A list of   distribution functions that can be worked on:
- [ ] [Dirichlet Distribution](https://en.wikipedia.org/wiki/Dirichlet_distribution) (taken by @mrityunjay-tripathi)
- [ ] [Rademacher Distribution](https://en.wikipedia.org/wiki/Rademacher_distribution)
- [ ] [Fisher Snedecor Distribution](https://en.wikipedia.org/wiki/F-distribution)
- [ ] [Beta-Binomial Distribution](https://en.wikipedia.org/wiki/Beta-binomial_distribution)
- [ ] [Multinomial Distribution](https://en.wikipedia.org/wiki/Multinomial_distribution)
- [ ] [Categorical Distribution](https://en.wikipedia.org/wiki/Categorical_distribution)
I will add further if I get it.
Thanks.

**Comment by anishk74** [comment]
Great Idea. Can you name some of the distributions which are not there? I would like to collaborate with you on implementing these distributions. Looking for your reply... :)

**Comment by mrityunjay-tripathi** [comment]
I am just jotting them down. :)

**Comment by anishk74** [comment]
I am familiar with most of these distribution. Would you like to collaborate with me implementing these distributions? I can start working on them right now...

**Comment by mrityunjay-tripathi** [comment]
Nice. Mention whichever you are working on.

**Comment by anishk74** [comment]
I am working on
 Dirichlet Distribution
 Beta Distribution
 Uniform Distribution
 Binomial Distribution
 Negative Binomial Distribution
 Beta-Binomial Distribution
 Geometric Distribution
 Hyper-Geometric Distribution
 Multinomial Distribution
 Multivariate Hypergeometric Distribution
 Poisson Distribution
 Exponential Distribution
 Log-normal Distribution
Will try to implement and open a PR as soon as possible..

**Comment by codeboy5** [comment]
Hi @anishk74 would it be okay if we work on them one by one ? 
As It would everyone a better chance to work on this and make contributions. I just feel this might be a better option. 
The members would be able to give a better overview.
@kartikdutt18 , what do you think ?

**Comment by anishk74** [comment]
Hi @codeboy5, that's okay with me. I would like to start with Poisson distribution and will continue implementing exponential distribution as these two are closely related..
Is that okay with you?

**Comment by codeboy5** [comment]
@anishk74 hahah everything is okay, working on small issues really helped me to get started with the repo so I thought if someone new wants to join this might be a good first issue .

**Comment by codeboy5** [comment]
> I was just going through the codebase and found that some probability distribution functions are missing. Also, there are two directories for distribution functions, one `src/mlpack/core/dists/` and other `src/mlpack/methods/ann/dists/`. Any reasons? Can they be merged into one directory? I am looking ahead for collaboration to implement the remaining distribution functions as well. A list of distribution functions that can be worked on:
> 
> * [ ]  Cauchy Distribution
> * [ ]  Chi-Squared Distribution
> * [ ]  Dirichlet Distribution
> * [ ]  Beta Distribution
> * [ ]  Uniform Distribution (taken by @codeboy5 ) 
> * [ ]  Wishart Distribution
> * [ ]  Rademacher Distribution
> * [ ]  Fisher Snedecor Distribution
> * [ ]  Binomial Distribution
> * [ ]  Negative Binomial Distribution
> * [ ]  Beta-Binomial Distribution
> * [ ]  Geometric Distribution
> * [ ]  Hyper-Geometric Distribution
> * [ ]  Multinomial Distribution
> * [ ]  Categorical Distribution
> * [ ]  Multivariate Hypergeometric Distribution
> * [ ]  Poisson Distribution
> * [ ]  Exponential Distribution
> * [ ]  Rayleigh Distribution
> * [ ]  Rice Distribution
> * [ ]  F Distribution
> * [ ]  Pareto Distribution
> * [ ]  Log-normal Distribution
> * [ ]  Student-t Distribution
>   Will add further if I get.
>   Thanks.

**Comment by mrityunjay-tripathi** [comment]
> Uniform Distribution (taken by @codeboy5 )

Nice.

**Comment by anishk74** [comment]
> I was just going through the codebase and found that some probability distribution functions are missing. Also, there are two directories for distribution functions, one `src/mlpack/core/dists/` and other `src/mlpack/methods/ann/dists/`. Any reasons? Can they be merged into one directory? I am looking ahead for collaboration to implement the remaining distribution functions as well. A list of distribution functions that can be worked on:
> 
> * [ ]  Cauchy Distribution
> * [ ]  Chi-Squared Distribution
> * [ ]  Dirichlet Distribution
> * [ ]  Beta Distribution
> * [ ]  Uniform Distribution
> * [ ]  Wishart Distribution
> * [ ]  Rademacher Distribution
> * [ ]  Fisher Snedecor Distribution
> * [ ]  Binomial Distribution
> * [ ]  Negative Binomial Distribution
> * [ ]  Beta-Binomial Distribution
> * [ ]  Geometric Distribution
> * [ ]  Hyper-Geometric Distribution
> * [ ]  Multinomial Distribution
> * [ ]  Categorical Distribution
> * [ ]  Multivariate Hypergeometric Distribution
> * [ ]  Poisson Distribution (taken by @anishk74)
> * [ ]  Exponential Distribution (taken by @anishk74)
> * [ ]  Rayleigh Distribution
> * [ ]  Rice Distribution
> * [ ]  F Distribution
> * [ ]  Pareto Distribution
> * [ ]  Log-normal Distribution
> * [ ]  Student-t Distribution
>   Will add further if I get.
>   Thanks.

**Comment by kartikdutt18** [comment]
Agreed, It is a nice idea to implement them one by one.
I am taking one up, but it might be a while before I open an PR. So incase the list is full and I haven't implemented it, feel free to comment and take up the issue.

- [ ]  Cauchy Distribution
- [ ]   Chi-Squared Distribution
- [ ]   Dirichlet Distribution
- [ ]   Beta Distribution
- [ ]   Uniform Distribution (@codeboy5)
- [ ]   Wishart Distribution
- [ ]   Rademacher Distribution
- [ ]   Fisher Snedecor Distribution
- [ ]   Binomial Distribution
- [ ]   Negative Binomial Distribution
- [ ]   Beta-Binomial Distribution
- [ ]   Geometric Distribution
- [ ]   Hyper-Geometric Distribution
- [ ]   Multinomial Distribution
- [ ]   Categorical Distribution
- [ ]   Multivariate Hypergeometric Distribution
- [ ]   Poisson Distribution (taken by @anishk74)
- [ ]   Exponential Distribution (taken by @anishk74)
- [ ]   Rayleigh Distribution (taken up by @kartikdutt18 )
- [ ]   Rice Distribution
- [ ]   F Distribution
- [ ]   Pareto Distribution
- [ ]   Log-normal Distribution
- [ ]   Student-t Distribution

**Comment by codeboy5** [comment]
@kartikdutt18  any idea why there are 2 different folders for distribution ?

**Comment by gaurav-singh1998** [comment]
> Agreed, It is a nice idea to implement them one by one.
> I am taking one up, but it might be a while before I open an PR. So incase the list is full and I haven't implemented it, feel free to comment and take up the issue.
> 
> * [ ]   Cauchy Distribution
> * [ ]    Chi-Squared Distribution
> * [ ]    Dirichlet Distribution
> * [ ]    Beta Distribution
> * [ ]    Uniform Distribution (@codeboy5)
> * [ ]    Wishart Distribution
> * [ ]    Rademacher Distribution
> * [ ]    Fisher Snedecor Distribution
> * [ ]    Binomial Distribution
> * [ ]    Negative Binomial Distribution
> * [ ]    Beta-Binomial Distribution
> * [ ]    Geometric Distribution
> * [ ]    Hyper-Geometric Distribution
> * [ ]    Multinomial Distribution
> * [ ]    Categorical Distribution
> * [ ]    Multivariate Hypergeometric Distribution
> * [ ]    Poisson Distribution (taken by @anishk74)
> * [ ]    Exponential Distribution (taken by @anishk74)
> * [ ]    Rayleigh Distribution (taken up by @kartikdutt18 )
> * [ ]    Rice Distribution
> * [ ]    F Distribution
> * [ ]    Pareto Distribution
> * [ ]    Log-normal Distribution (taken up by 
@gaurav-singh1988)
> * [ ]    Student-t Distribution

**Comment by kartikdutt18** [comment]
I think the reason for that is Bernoulli distribution doesn't have same functions as rest of the distributions in `core/dists`. It has some other functions such as `LogProbBackward`. It might be a good idea to implement rest of the missing functions in Bernoulli and missing Backward(if not in others) in all distributions if necessary. Then, we can shift Bernoulli to `core/dists` and remove that folder entirely.

**Comment by gaurav-singh1998** [comment]
> Agreed, It is a nice idea to implement them one by one.
> I am taking one up, but it might be a while before I open an PR. So incase the list is full and I haven't implemented it, feel free to comment and take up the issue.
> 
> * [ ]   Cauchy Distribution
> * [ ]    Chi-Squared Distribution
> * [ ]    Dirichlet Distribution
> * [ ]    Beta Distribution
> * [ ]    Uniform Distribution (@codeboy5)
> * [ ]    Wishart Distribution
> * [ ]    Rademacher Distribution
> * [ ]    Fisher Snedecor Distribution
> * [ ]    Binomial Distribution
> * [ ]    Negative Binomial Distribution
> * [ ]    Beta-Binomial Distribution
> * [ ]    Geometric Distribution
> * [ ]    Hyper-Geometric Distribution
> * [ ]    Multinomial Distribution
> * [ ]    Categorical Distribution
> * [ ]    Multivariate Hypergeometric Distribution
> * [ ]    Poisson Distribution (taken by @anishk74)
> * [ ]    Exponential Distribution (taken by @anishk74)
> * [ ]    Rayleigh Distribution (taken up by @kartikdutt18 )
> * [ ]    Rice Distribution
> * [ ]    F Distribution
> * [ ]    Pareto Distribution
> * [ ]    Log-normal Distribution (taken by @gaurav-singh1998 )
> * [ ]    Student-t Distribution

**Comment by himanshupathak21061998** [comment]
> I was just going through the codebase and found that some probability distribution functions are missing. Also, there are two directories for distribution functions, one `src/mlpack/core/dists/` and other `src/mlpack/methods/ann/dists/`. Any reasons? Can they be merged into one directory? I am looking ahead for collaboration to implement the remaining distribution functions as well. A [list of distribution functions](https://en.wikipedia.org/wiki/List_of_probability_distributions) that can be worked on:
> 
>     * [ ]  Cauchy Distribution
> 
>     * [ ]  Chi-Squared Distribution
> 
>     * [ ]  Dirichlet Distribution (taken by @mrityunjay-tripathi)
> 
>     * [ ]  Beta Distribution
> 
>     * [ ]  Uniform Distribution (taken by @codeboy5 )
> 
>     * [ ]  Wishart Distribution
> 
>     * [ ]  Rademacher Distribution
> 
>     * [ ]  Fisher Snedecor Distribution
> 
>     * [ ]  Binomial Distribution(taken by @himanshupathak21061998 )
> 
>     * [ ]  Negative Binomial Distribution
> 
>     * [ ]  Beta-Binomial Distribution
> 
>     * [ ]  Geometric Distribution
> 
>     * [ ]  Hyper-Geometric Distribution
> 
>     * [ ]  Multinomial Distribution
> 
>     * [ ]  Categorical Distribution
> 
>     * [ ]  Multivariate Hypergeometric Distribution
> 
>     * [ ]  Poisson Distribution (taken by @anishk74)
> 
>     * [ ]  Exponential Distribution (taken by @anishk74)
> 
>     * [ ]  Rayleigh Distribution (taken by @kartikdutt18 )
> 
>     * [ ]  Rice Distribution
> 
>     * [ ]  F Distribution
> 
>     * [ ]  Pareto Distribution
> 
>     * [ ]  Log-normal Distribution (taken by @gaurav-singh1998)
> 
>     * [ ]  Student-t Distribution
>       I will add further if I get.
>       Thanks.

**Comment by ojhalakshya** [comment]
> > Agreed, It is a nice idea to implement them one by one.
> > I am taking one up, but it might be a while before I open an PR. So incase the list is full and I haven't implemented it, feel free to comment and take up the issue.
> > 
> > * [ ]    Cauchy Distribution (taken up by @ojhalakshya)
> > * [ ]     Chi-Squared Distribution
> > * [ ]     Dirichlet Distribution
> > * [ ]     Beta Distribution
> > * [ ]     Uniform Distribution (@codeboy5)
> > * [ ]     Wishart Distribution
> > * [ ]     Rademacher Distribution
> > * [ ]     Fisher Snedecor Distribution
> > * [ ]     Binomial Distribution (taken by @himanshupathak21061998 )
> > * [ ]     Negative Binomial Distribution
> > * [ ]     Beta-Binomial Distribution
> > * [ ]     Geometric Distribution
> > * [ ]     Hyper-Geometric Distribution
> > * [ ]     Multinomial Distribution
> > * [ ]     Categorical Distribution
> > * [ ]     Multivariate Hypergeometric Distribution
> > * [ ]     Poisson Distribution (taken by @anishk74)
> > * [ ]     Exponential Distribution (taken by @anishk74)
> > * [ ]     Rayleigh Distribution (taken up by @kartikdutt18 )
> > * [ ]     Rice Distribution
> > * [ ]     F Distribution
> > * [ ]     Pareto Distribution
> > * [ ]     Log-normal Distribution (taken by @gaurav-singh1998 )
> > * [ ]     Student-t Distribution

I would like to work on cauchy distribution function.
Thanks.

**Comment by rcurtin** [comment]
Before we implement any of these, can we connect them to actual needs?  Otherwise we are just implementing a ton of distributions that may not be used, and we will have to maintain it.  I'd really request that we only implement distributions as they are needed---or if we do choose to implement a distribution, we have strong support for why the distribution should be added.

Many of the distributions listed here either are already implemented in Armadillo or in boost, meaning there's not much gain for us to actually implement them.

**Comment by mrityunjay-tripathi** [comment]
Hi @rcurtin 
Sorry that I missed the libraries which are the basis for mlpack. I removed those from the list which are already implemented. Even then some important distribution functions are yet to be implemented such as Dirichlet Distribution which is used as prior in Bayesian Statistics. Should I make the PR related to distributions to Boost itself? Also, I wanted to know what's the difference b/w distributions implemented in mlpack and boost (some distribution functions are there in both mlpack and boost)?

**Comment by rcurtin** [comment]
What I'm saying is that adding distributions that aren't directly used and applied by other mlpack code just makes for more maintenance overhead. The users of mlpack generally use the machine learning models found in `src/mlpack/methods/`, not the probability distributions that mlpack implements. Said another way, the probability distributions that mlpack *does* implement are connected directly to user tasks and are used directly by the machine learning algorithm implementations.

So, what I'm saying is that anything that we add should be similarly directly connected to a use of the library; otherwise, it's just extra code to maintain that makes it harder for us to refactor and redesign our internals as necessary.  I'm not opposed to adding more distributions---but we must clearly justify why the library requires them and how and where they will be used.

The other point in this issue, about the distributions living in two places, is perhaps something that could be improved.  I remember that it was discussed some years ago but I'm on a phone right now and can't easily search for issues---maybe you can find something?

**Comment by kartikdutt18** [comment]
Hi @rcurtin, I think this might be the reason.
> I think the reason for that is because Bernoulli distribution doesn't have same functions as rest of the distributions in core/dists. It has some other functions such as LogProbBackward. It might be a good idea to implement rest of the missing functions (such as Train) in Bernoulli and missing Backward(if not in others) in all distributions if necessary. Then, we can shift Bernoulli to core/dists and remove that folder entirely. However I think a member will provide better insight.

**Comment by kartikdutt18** [comment]
Ohh, I think  I found the PR you referred. @mrityunjay-tripathi, have a look at,
#1730

**Comment by saraansh1999** [comment]
I am not really well versed with these distributions but I would love to read up on the and contribute.
I would like to start with Rademacher Distribution.

**Comment by gaurav-singh1998** [comment]
Hey, @saraansh1999 thank you for taking up this task but before implementing it look if it is used directly by the machine learning algorithm implementations that mlpack provides.

**Comment by conradsnicta** [comment]
As these distributions are general, it might be more useful to add a small subset of them directly into Armadillo rather than mlpack.  Specifically, the Poisson and exponential distributions, with functionality mimicking the rande() and randp() functions in Octave/Matlab.

The Armadillo development site is at:  https://gitlab.com/conradsnicta/armadillo-code

Note that Armadillo already has the Wishart, Chi-Squared, and Gamma distributions:  
* http://arma.sourceforge.net/docs.html#wishrnd
* http://arma.sourceforge.net/docs.html#chi2rnd
* http://arma.sourceforge.net/docs.html#randg

**Comment by anishk74** [comment]
> As these distributions are general, it might be more useful to add a small subset of them directly into Armadillo rather than mlpack. Specifically, the Poisson and exponential distributions, with functionality mimicking the rande() and randp() functions in Octave/Matlab.
> 
> The Armadillo development site is at: https://gitlab.com/conradsnicta/armadillo-code
> 
> Note that Armadillo already has the Wishart, Chi-Squared, and Gamma distributions:
> 
> * http://arma.sourceforge.net/docs.html#wishrnd
> * http://arma.sourceforge.net/docs.html#chi2rnd
> * http://arma.sourceforge.net/docs.html#randg
> 
> Also note that the exponential distribution is a special case of the Gamma distribution, so it may be possible to implement rande() as a wrapper around randg().

Thanks, I will look into it.
