### ISSUE TITLE
make fails in building mlpack from source

### ISSUE THREAD

**Issue by Mindjolt2406** [mlpack/mlpack#2245]
#### Your environment

 * version of mlpack: 3.2.2
 * operating system: Mac OS X
 * compiler: clang 1001.0.46.4
 * version of dependencies (Boost/Armadillo): Boost (1.72.0) Armadillo (9.850.1)
 * any other environment information you think is relevant: 

#### Steps to reproduce

1. Download the source code
2. make the build directory and run cmake ../
3. Run make -j4
4. make fails

#### Expected behavior

make should succeed

#### Actual behavior

Error: Symbols not found in architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libmlpack.3.2.dylib] Error 1
make[1]: *** [src/mlpack/CMakeFiles/mlpack.dir/all] Error 2
make: *** [all] Error 2

**Comment by rcurtin** [comment]
Hey there @Mindjolt2406, thanks for the error report.  Can you paste the full build output?  The output you gave is *most* of what we need but not everything. :)

**Comment by Mindjolt2406** [comment]
Sure. 

[  0%] Updating arma_config.hpp (if necessary)
-- Regenerating arma_config.hpp.
[  0%] Built target mlpack_arma_config
Moving header files to include/mlpack/
[  0%] Built target mlpack_headers
[  1%] Generating mlpack.pc (pkg-config) file.
[  1%] Built target pkgconfig
[  2%] Building CXX precompiled header src/mlpack/cotire/mlpack_CXX_prefix.hxx.pch
Scanning dependencies of target mlpack
[  3%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/bindings/cli/print_help.cpp.o
[  3%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/bindings/tests/clean_memory.cpp.o
[  3%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/data/load_csv.cpp.o
[  4%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/data/load.cpp.o
[  4%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/discrete_distribution.cpp.o
[  4%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/gaussian_distribution.cpp.o
[  5%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/laplace_distribution.cpp.o
In file included from /Users/rathinbhargava/IIITB/GSOC/mlpack-3.2.2/src/mlpack/core/data/load.cpp:13:
/Users/rathinbhargava/IIITB/GSOC/mlpack-3.2.2/src/mlpack/core/data/load_impl.hpp:116:30: warning: 'guess_file_type' is deprecated [-Wdeprecated-declarations]
    loadType = arma::diskio::guess_file_type(stream);
                             ^
/usr/local/include/armadillo_bits/diskio_meat.hpp:216:1: note: 'guess_file_type' has been explicitly marked deprecated here
arma_deprecated
^
/usr/local/include/armadillo_bits/compiler_setup.hpp:286:44: note: expanded from macro 'arma_deprecated'
    #define arma_deprecated __attribute__((__deprecated__))
                                           ^
In file included from /Users/rathinbhargava/IIITB/GSOC/mlpack-3.2.2/src/mlpack/core/data/load.cpp:13:
/Users/rathinbhargava/IIITB/GSOC/mlpack-3.2.2/src/mlpack/core/data/load_impl.hpp:180:32: warning: 'guess_file_type' is deprecated [-Wdeprecated-declarations]
      loadType = arma::diskio::guess_file_type(stream);
                               ^
/usr/local/include/armadillo_bits/diskio_meat.hpp:216:1: note: 'guess_file_type' has been explicitly marked deprecated here
arma_deprecated
^
/usr/local/include/armadillo_bits/compiler_setup.hpp:286:44: note: expanded from macro 'arma_deprecated'
    #define arma_deprecated __attribute__((__deprecated__))
                                           ^
[  5%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/regression_distribution.cpp.o
[  5%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/gamma_distribution.cpp.o
[  5%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/diagonal_gaussian_distribution.cpp.o
[  6%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/kernels/epanechnikov_kernel.cpp.o
[  6%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/kernels/pspectrum_string_kernel.cpp.o
[  6%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/columns_to_blocks.cpp.o
[  7%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/lin_alg.cpp.o
[  7%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/random.cpp.o
[  7%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/random_basis.cpp.o
[  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/tree/cosine_tree/cosine_tree.cpp.o
[  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/backtrace.cpp.o
[  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/cli.cpp.o
[  9%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/log.cpp.o
[  9%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/prefixedoutstream.cpp.o
[  9%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/program_doc.cpp.o
[  9%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/singletons.cpp.o
[ 10%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/timers.cpp.o
[ 10%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/version.cpp.o
[ 10%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/adaboost/adaboost_model.cpp.o
[ 11%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/block_krylov_svd/randomized_block_krylov_svd.cpp.o
2 warnings generated.
[ 11%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/fastmks/fastmks_model.cpp.o
[ 11%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/gmm/gmm.cpp.o
[ 12%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/gmm/diagonal_gmm.cpp.o
[ 12%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/hoeffding_trees/hoeffding_tree_model.cpp.o
[ 12%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/lars/lars.cpp.o
[ 13%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/linear_regression/linear_regression.cpp.o
[ 13%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/local_coordinate_coding/lcc.cpp.o
[ 13%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/matrix_completion/matrix_completion.cpp.o
[ 13%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/neighbor_search/unmap.cpp.o
[ 14%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/quic_svd/quic_svd.cpp.o
[ 14%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/radical/radical.cpp.o
[ 14%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/randomized_svd/randomized_svd.cpp.o
[ 15%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/rann/ra_util.cpp.o
[ 15%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/softmax_regression/softmax_regression.cpp.o
[ 15%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/softmax_regression/softmax_regression_function.cpp.o
[ 16%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_autoencoder/sparse_autoencoder.cpp.o
[ 16%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_autoencoder/sparse_autoencoder_function.cpp.o
[ 16%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_autoencoder/maximal_inputs.cpp.o
[ 17%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_coding/sparse_coding.cpp.o
[ 17%] Linking CXX shared library ../../lib/libmlpack.dylib
Undefined symbols for architecture x86_64:
  "___kmpc_critical", referenced from:
      mlpack::math::Svec(arma::SpMat<double> const&, arma::SpCol<double>&) in lin_alg.cpp.o
      arma::SpMat<double>::sync_csc() const in lin_alg.cpp.o
      mlpack::matrix_completion::MatrixCompletion::InitSDP() in matrix_completion.cpp.o
      arma::SpMat<double>::sync_csc() const in matrix_completion.cpp.o
      arma::SpMat<double>::init(arma::SpMat<double> const&) in matrix_completion.cpp.o
      arma::SpMat<double>::sync_csc() const in randomized_svd.cpp.o
      arma::SpMat<double>::init(arma::SpMat<double> const&) in randomized_svd.cpp.o
      ...
  "___kmpc_end_critical", referenced from:
      mlpack::math::Svec(arma::SpMat<double> const&, arma::SpCol<double>&) in lin_alg.cpp.o
      arma::SpMat<double>::sync_csc() const in lin_alg.cpp.o
      mlpack::matrix_completion::MatrixCompletion::InitSDP() in matrix_completion.cpp.o
      arma::SpMat<double>::sync_csc() const in matrix_completion.cpp.o
      arma::SpMat<double>::init(arma::SpMat<double> const&) in matrix_completion.cpp.o
      arma::SpMat<double>::sync_csc() const in randomized_svd.cpp.o
      arma::SpMat<double>::init(arma::SpMat<double> const&) in randomized_svd.cpp.o
      ...
  "___kmpc_for_static_fini", referenced from:
      _.omp_outlined. in gaussian_distribution.cpp.o
      _.omp_outlined. in gamma_distribution.cpp.o
      _.omp_outlined..44 in gamma_distribution.cpp.o
      _.omp_outlined..45 in gamma_distribution.cpp.o
      _.omp_outlined. in diagonal_gaussian_distribution.cpp.o
      _.omp_outlined..40 in diagonal_gaussian_distribution.cpp.o
      _.omp_outlined..41 in diagonal_gaussian_distribution.cpp.o
      ...
  "___kmpc_for_static_init_8u", referenced from:
      _.omp_outlined. in gaussian_distribution.cpp.o
      _.omp_outlined. in gamma_distribution.cpp.o
      _.omp_outlined..44 in gamma_distribution.cpp.o
      _.omp_outlined..45 in gamma_distribution.cpp.o
      _.omp_outlined. in diagonal_gaussian_distribution.cpp.o
      _.omp_outlined..40 in diagonal_gaussian_distribution.cpp.o
      _.omp_outlined..41 in diagonal_gaussian_distribution.cpp.o
      ...
  "___kmpc_fork_call", referenced from:
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in gaussian_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Mat<double> >(arma::Mat<double>&, arma::eOp<arma::Mat<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Col<double> >(arma::Mat<double>&, arma::eOp<arma::Col<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_scalar_times>::apply_inplace_plus<arma::eOp<arma::subview_col<double>, arma::eop_log> >(arma::Mat<arma::eOp<arma::subview_col<double>, arma::eop_log>::elem_type>&, arma::eOp<arma::eOp<arma::subview_col<double>, arma::eop_log>, arma::eop_scalar_times> const&) in gamma_distribution.cpp.o
      arma::eOp<arma::Col<double>, arma::eop_log>::elem_type arma::accu_proxy_linear<arma::eOp<arma::Col<double>, arma::eop_log> >(arma::Proxy<arma::eOp<arma::Col<double>, arma::eop_log> > const&) in diagonal_gaussian_distribution.cpp.o
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in diagonal_gaussian_distribution.cpp.o
      void arma::eglue_core<arma::eglue_plus>::apply<arma::Mat<double>, arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double> >(arma::Mat<double>&, arma::eGlue<arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double>, arma::eglue_plus> const&) in diagonal_gaussian_distribution.cpp.o
      ...
  "___kmpc_global_thread_num", referenced from:
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in gaussian_distribution.cpp.o
      _.omp_outlined. in gaussian_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Mat<double> >(arma::Mat<double>&, arma::eOp<arma::Mat<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      _.omp_outlined. in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Col<double> >(arma::Mat<double>&, arma::eOp<arma::Col<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      _.omp_outlined..44 in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_scalar_times>::apply_inplace_plus<arma::eOp<arma::subview_col<double>, arma::eop_log> >(arma::Mat<arma::eOp<arma::subview_col<double>, arma::eop_log>::elem_type>&, arma::eOp<arma::eOp<arma::subview_col<double>, arma::eop_log>, arma::eop_scalar_times> const&) in gamma_distribution.cpp.o
      ...
  "___kmpc_push_num_threads", referenced from:
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in gaussian_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Mat<double> >(arma::Mat<double>&, arma::eOp<arma::Mat<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Col<double> >(arma::Mat<double>&, arma::eOp<arma::Col<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_scalar_times>::apply_inplace_plus<arma::eOp<arma::subview_col<double>, arma::eop_log> >(arma::Mat<arma::eOp<arma::subview_col<double>, arma::eop_log>::elem_type>&, arma::eOp<arma::eOp<arma::subview_col<double>, arma::eop_log>, arma::eop_scalar_times> const&) in gamma_distribution.cpp.o
      arma::eOp<arma::Col<double>, arma::eop_log>::elem_type arma::accu_proxy_linear<arma::eOp<arma::Col<double>, arma::eop_log> >(arma::Proxy<arma::eOp<arma::Col<double>, arma::eop_log> > const&) in diagonal_gaussian_distribution.cpp.o
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in diagonal_gaussian_distribution.cpp.o
      void arma::eglue_core<arma::eglue_plus>::apply<arma::Mat<double>, arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double> >(arma::Mat<double>&, arma::eGlue<arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double>, arma::eglue_plus> const&) in diagonal_gaussian_distribution.cpp.o
      ...
  "_omp_get_max_threads", referenced from:
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in gaussian_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Mat<double> >(arma::Mat<double>&, arma::eOp<arma::Mat<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Col<double> >(arma::Mat<double>&, arma::eOp<arma::Col<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_scalar_times>::apply_inplace_plus<arma::eOp<arma::subview_col<double>, arma::eop_log> >(arma::Mat<arma::eOp<arma::subview_col<double>, arma::eop_log>::elem_type>&, arma::eOp<arma::eOp<arma::subview_col<double>, arma::eop_log>, arma::eop_scalar_times> const&) in gamma_distribution.cpp.o
      arma::eOp<arma::Col<double>, arma::eop_log>::elem_type arma::accu_proxy_linear<arma::eOp<arma::Col<double>, arma::eop_log> >(arma::Proxy<arma::eOp<arma::Col<double>, arma::eop_log> > const&) in diagonal_gaussian_distribution.cpp.o
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in diagonal_gaussian_distribution.cpp.o
      void arma::eglue_core<arma::eglue_plus>::apply<arma::Mat<double>, arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double> >(arma::Mat<double>&, arma::eGlue<arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double>, arma::eglue_plus> const&) in diagonal_gaussian_distribution.cpp.o
      ...
  "_omp_in_parallel", referenced from:
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in gaussian_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Mat<double> >(arma::Mat<double>&, arma::eOp<arma::Mat<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Col<double> >(arma::Mat<double>&, arma::eOp<arma::Col<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_scalar_times>::apply_inplace_plus<arma::eOp<arma::subview_col<double>, arma::eop_log> >(arma::Mat<arma::eOp<arma::subview_col<double>, arma::eop_log>::elem_type>&, arma::eOp<arma::eOp<arma::subview_col<double>, arma::eop_log>, arma::eop_scalar_times> const&) in gamma_distribution.cpp.o
      arma::eOp<arma::Col<double>, arma::eop_log>::elem_type arma::accu_proxy_linear<arma::eOp<arma::Col<double>, arma::eop_log> >(arma::Proxy<arma::eOp<arma::Col<double>, arma::eop_log> > const&) in diagonal_gaussian_distribution.cpp.o
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in diagonal_gaussian_distribution.cpp.o
      void arma::eglue_core<arma::eglue_plus>::apply<arma::Mat<double>, arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double> >(arma::Mat<double>&, arma::eGlue<arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double>, arma::eglue_plus> const&) in diagonal_gaussian_distribution.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libmlpack.3.2.dylib] Error 1
make[1]: *** [src/mlpack/CMakeFiles/mlpack.dir/all] Error 2
make: *** [all] Error 2

**Comment by rcurtin** [comment]
Looks like your compiler isn't linking correctly with OpenMP.  I'm not sure what the exact solution for that would be, but, maybe can you configure CMake with `-DUSE_OPENMP=OFF` to disable OpenMP?

**Comment by Mindjolt2406** [comment]
Thanks! I believe it's successful now.
