### ISSUE TITLE
Upsampling in ann.

### ISSUE THREAD

**Issue by saraansh1999** [mlpack/mlpack#2248]
I am not able to find the implementation of upsampling as a layer in the ann codebase. Upsampling is an approximation of the inverse of pooling operation and can be used in symmetrical networks like the unet.

Is it implemented somewhere?
If not can I take up this task?
Thanks.

**Comment by kartikdutt18** [comment]
Hi @saraansh1999, I am currently working on it (as discussed in models/#54). I hope that's okay with you.

**Comment by saraansh1999** [comment]
How is #54 related to upsampling?

**Comment by kartikdutt18** [comment]
hmm, I made a tagging mistake. Have a look at this (https://github.com/mlpack/models/issues/54)

**Comment by saraansh1999** [comment]
I see that you are busy rn. If you want we can collaborate on this. I can take it up from where you have left it off.

**Comment by kartikdutt18** [comment]
I had spent a lot of time debugging this, So I wanted to make it across the finish line. I hope you understand.

**Comment by saraansh1999** [comment]
Cool. Best of luck!

**Comment by kartikdutt18** [comment]
Thanks for understanding. I hope to work with you on the other issue that we had discussed regarding activation functions.
I will update the benchmarks soon. (I recently changed machines and CUDA is a bit tricky to install).
