### ISSUE TITLE
Instance Norm

### ISSUE THREAD

**Issue by saraansh1999** [mlpack/mlpack#2249]
I couldnt find the implementation of Instance Norm in mlpack. 
Link to pytorch doc: [https://pytorch.org/docs/stable/nn.html#instancenorm1d](url)

Is it implemented?
If not can I take this up?

**Comment by zoq** [comment]
mlpack doesn't implement a style transfer model, so I'm not sure this would be of any use right now, or maybe this layer is used in another model/area as well?

**Comment by saraansh1999** [comment]
Yes it is true that this layer is mostly used in style transfer models. 
But considering the fact that this year GSOC involves an idea of showing the use cases of mlpack ann module, I was thinking of implementing a style transfer model for images. And like you said, this normalization mechanism might be useful.

**Comment by saraansh1999** [comment]
Should I proceed with this?
