### ISSUE TITLE
Accessor method implementations for layers in ANN module

### ISSUE THREAD

**Issue by iamshnoo** [mlpack/mlpack#2258]
#### Issue description

- Hi! I have been going through the ```.hpp``` files in  ```src/mlpack/methods/ann/layer``` and found some discrepancies regarding accessor implementations (getter and setter methods for the private variables). Specifically, in quite a large number of files, some of these methods are missing and thus makes the files a bit incomplete. I am listing out the ones I found below (there might be a few that I missed). 
- Also, I am not exactly sure if all the stuff I am listing below need to have accessor implementations (for example, some variable might have been left private without an accessor on purpose.) So, I would really appreciate if someone provides some clue as to accessor methods I should go about implementing for which of the variables from the list below.
- I intend to implement all those methods and submit a PR very soon with the changes. 
----
### add_merge.hpp 

- OutputDataType gradient

### add.hpp

- size_t outSize

### atrous_convolution.hpp

-  size_t batchSize
-  arma::cube weight

### batch_norm.hpp

- size_t size
- double eps
- bool loading
- OutputDataType gamma
- OutputDataType beta
- OutputDataType mean
- OutputDataType variance
- OutputDataType normalize
- OutputDataType inputMean

### bilinear_interpolation.hpp

- size_t inRowSize
- size_t inColSize
- size_t outRowSize
- size_t outColSize
- size_t depth
- size_t batchSize

### concat_performance.hpp

- OutputLayerType outputLayer
- size_t inSize

### concat.hpp

- size_t axis
- bool useAxis
- bool model
- size_t channels

### concatenate.hpp

- size_t inRows

### constant.hpp

- size_t inSize
- size_t outSize
- OutputDataType constantOutput

### convolution.hpp

- size_t batchSize
- arma::cube weight

### dropconnect.hpp

- double scale
- OutputDataType mask
- OutputDataType denoise

### dropout.hpp

- double scale
- OutputDataType mask

### elu.hpp

- bool deterministic
- arma::mat derivative

### fast_lstm.hpp

- size_t inSize
- size_t outSize
- size_t forwardStep
- size_t backwardStep
- size_t gradientStep
- OutputDataType prevOutput
- size_t batchSize
- size_t batchStep
- size_t gradientStepIdx
- size_t rhoSize
- size_t bpttSteps

### flexible_relu.hpp

- possible error on lines 134-136

### glimpse.hpp

- size_t inSize
- size_t size
- size_t depth
- size_t scale
- size_t inputDepth

### gru.hpp

- size_t inSize
- size_t outSize
- size_t batchSize
- size_t forwardStep
- size_t backwardStep
- size_t gradientStep
- arma::mat prevError

### highway.hpp

- size_t inSize
- bool model
- bool reset
- OutputDataType transformWeight
- OutputDataType transformBias
- OutputDataType transformGate
- OutputDataType transformGateActivation
- OutputDataType transformGateError
- size_t width
- size_t height
- OutputDataType networkOutput

### join.hpp

- size_t inSizeRows
- size_t inSizeCols

### layer_norm.hpp

- size_t size
- double eps
- bool loading
- OutputDataType gamma
- OutputDataType beta
- OutputDataType normalized
- OutputDataType inputMean

### lookup.hpp

- size_t inSize
- size_t outSize

### lstm.hpp

- size_t inSize
- size_t outSize
- size_t rho
- size_t forwardStep
- size_t backwardStep
- size_t gradientStep
- OutputDataType prevOutput
- size_t batchSize
- size_t gradientStepIdx
- size_t rhoSize
- size_t bpttSteps

### max_pooling.hpp

- bool reset
- size_t offset
- size_t batchSize
- OutputDataType gradient

### mean_pooling.hpp

- bool reset
- size_t offset
- size_t batchSize
- OutputDataType gradient

### minibatch_discrimination.hpp

- size_t batchSize
- OutputDataType weight
- arma::cube M
- arma::cube distances

### multiply_merge.hpp

- bool model
- bool run
- bool ownsLayer

### recurrent_attention.hpp

- size_t outSize
- size_t rho
- size_t forwardStep
- size_t backwardStep
- bool deterministic
- std::vector<arma::mat> feedbackOutputParameter
- std::vector<arma::mat> moduleOutputParameter
- arma::mat recurrentError
- arma::mat actionError
- arma::mat actionDelta
- arma::mat rnnDelta
- arma::mat initialInput
- arma::mat attentionGradient

### recurrent.hpp

- size_t rho
- size_t forwardStep
- size_t backwardStep
- size_t gradientStep
- bool deterministic
- bool ownsLayer
- std::vector<arma::mat> feedbackOutputParameter
- arma::mat recurrentError

### reinforce_normal.hpp

- double stdev

### reparametrization.hpp

- bool stochastic
- bool includeKl
- double beta
- OutputDataType gaussianSample
- OutputDataType mean
- OutputDataType preStdDev
- OutputDataType stdDev

### select.hpp

- size_t index
- size_t elements

### sequential.hpp

- bool model
- bool reset

### subview.hpp

- size_t inSize
- size_t beginRow
- size_t endRow
- size_t beginCol
- size_t endCol

### transposed_convolution.hpp

- size_t aW
- size_t aH

### virtual_batch_norm.hpp

- size_t size
- double eps
- bool loading
- OutputDataType gamma
- OutputDataType beta
- OutputDataType referenceBatchMean
- OutputDataType referenceBatchMeanSquared
- double oldCoefficient
- double newCoefficient
- OutputDataType mean
- OutputDataType variance
- OutputDataType inputParameter
- OutputDataType normalized
- OutputDataType inputSubMean

### vr_class_reward.hpp

- std::vector<LayerTypes<> > network
- double reward
- bool sizeAverage
- double scale

### weight_norm.hpp

- size_t biasWeightSize
- size_t layerWeightSize
- OutputDataType scalarParameter
- OutputDataType vectorParameter
- OutputDataType layerGradients
- OutputDataType layerWeights

**Comment by kartikdutt18** [comment]
Hmm, The list is too long for me to see what is needed. However since I have worked with convolution layers, You don't need setters and getters for weights as we have Parameters in each class. So no need of adding setters/getters for it. (This applies to other layers as well).
Also transposed_convolution doesn't need aW and aH, changing them after intialization will most probably make the layer seg fault (Will make input size and output mismatch).
I highly suggest making changes so that you ensure that it doesn't it's working.

**Comment by kartikdutt18** [comment]
Also some of the points mentioned include variables that depend on constructor values so we shouldn't have setters/getters for them as well.

**Comment by iamshnoo** [comment]
Okay! Thank you for the suggestions. I will take these into account.
Regarding ```flexible_relu``` the reason I thought that lines 134-136 was possibly wrong was because those 2 functions return ```double alpha````, but the private members only have ```OutputDataType alpha``` and ```double userAlpha```, not ```double alpha````. So, possibly lines 134-136 wanted to return userAlpha instead of alpha? I don't know, maybe I am wrong with this.

**Comment by iamshnoo** [comment]
> Also some of the points mentioned include variables that depend on constructor values so we shouldn't have setters/getters for them as well.

Regarding this, I have one question. Assuming this statement to be the ground truth, many files don't follow this because they implement getter functions (not setters) for variables initialised in constructors. [for example, the variable ```size_t inSize```  in ```convolution.hpp```] So, should I be writing at least only the getter functions for such variables or just ignore them completely for the time-being?

**Comment by sreenikSS** [comment]
Hey @iamshnoo thanks for taking out time to compile such a massive list. I think we can narrow this down to the ones we require. This approach is actually helpful as we just need to exclude items and not add on to this list.

To start with you can exclude all weights (as @kartikdutt18 has mentioned) and also leave out any variable that is a matrix (arma::mat) or a cube (arma::cube). That might require checking out the exact type of variables of type ```OutputDataType```.

Also, keep in mind that the exact purpose of accessor functions is to make the extraction of each and every feature of each and every layer possible from a **given** ```FFN<>``` object.
You can think of this in a different way too. Let's say you are creating an mlpack model. You proceed by stacking different layers with some particular parameters for each layer. Hence those particular parameters are the only ones you would need to extract later, you can safely leave out any internal variables used.

I hope this helps :)

**Comment by kartikdutt18** [comment]
>  So, should I be writing at least only the getter functions for such variables or just ignore them completely for the time-being?

IMO, Some variables such as aW depend upon values such calculated during say, Forward Pass and then a user decides to change them (not sure why) in that case we would a differently padded output when we call backward which is incorrect. So variable that are set once depending on other parameters shouldn't have getters or setters.

Another example would be:

```
size_t forwardStep
size_t backwardStep
```

in recurrent_attention.hpp, These are internal parameters so we don't really need setters etc for them. Sorry that I can't go through the list in one go but I think @sreenikSS has covered major chunk of what need not be included, So I will only mention variables that aren't required.

> also leave out any variable that is a matrix (arma::mat) or a cube (arma::cube).

Agreed, that makes sense a lot of sense.

**Comment by iamshnoo** [comment]
Okay! Thanks, both of you! I will get started on trimming the list first and then will get down to the implementations.

**Comment by kartikdutt18** [comment]
Great! Looking forward to the PR.

**Comment by iamshnoo** [comment]
- I am updating this issue with the trimmed-down list. I will be committing the PR very soon. There are approximately 55 variables across 23 files which I am writing getter() functions for.
---

#### add.hpp

- *size_t* outSize

#### batch_norm.hpp

- *size_t* size
- *double* eps

#### bilinear_interpolation.hpp

- *size_t* inRowSize
- *size_t* inColSize
- *size_t* outRowSize
- *size_t* outColSize
- *size_t* depth

#### concat_performance.hpp

- *OutputLayerType* outputLayer
- *size_t* inSize

#### concat.hpp

- *size_t* axis
- *bool* model

#### constant.hpp

- *size_t* outSize
- *double* scalar

#### fast_lstm.hpp

- *size_t* inSize
- *size_t* outSize

#### glimpse.hpp

- *size_t* inSize
- *size_t* size
- *size_t* depth
- *size_t* scale

#### gru.hpp

- *size_t* inSize
- *size_t *outSize

#### highway.hpp

- *size_t* inSize
- *bool* model
- *size_t* width
- *size_t* height

#### layer_norm.hpp

- *size_t* size
- *double* eps

#### lookup.hpp

- *size_t* inSize
- *size_t* outSize

#### lstm.hpp

- *size_t* inSize
- *size_t* outSize
- *size_t* rho

#### multiply_merge.hpp

- *bool* model
- *bool* run

#### recurrent_attention.hpp

- *size_t* outSize
- *size_t* rho

#### recurrent.hpp

- *size_t* rho

#### reinforce_normal.hpp

- *double* stdev

#### reparametrization.hpp

- *bool* stochastic
- *bool* includeKl
- *double* beta

#### select.hpp

- *size_t* index
- *size_t* elements

#### sequential.hpp

- *bool* model

#### subview.hpp

- *size_t* inSize
- *size_t* beginRow
- *size_t* endRow
- *size_t* beginCol
- *size_t* endCol

#### virtual_batch_norm.hpp

- *size_t* size
- *double* eps

#### vr_class_reward.hpp

- *std::vector<LayerTypes<> >* network
- *bool* sizeAverage
- *double* scale
