### ISSUE TITLE
Addition of "ELiSH" activation function.

### ISSUE THREAD

**Issue by bisakhmondal** [mlpack/mlpack#2272]
Hi everyone, while looking through different activation functions, I have found an interesting one. The `Exponential Linear Sigmoid SquasHing` (ELiSH), a piecewise activation function, which shares the goodness of Swish in positive part & ELU and Sigmoid in its negative part. As per the [paper](https://arxiv.org/pdf/1808.00783.pdf) 

> Moreover, we would like to take advantage of compositional functions. For example in Swish, Sigmoid improves the information flow and Linear avoids a vanishing gradient, which is also the main motivation to design ELiSH and HardELiSH 

And after seeing the performance and benchmark of this activation function across different architecture, I think it's a good idea to include it in mlpack. We have Swish, ELU, Sigmoid and as the papers said it outperforms all three.
If it is okay, I would love to integrate it into mlpack. Thanks.

**Comment by kartikdutt18** [comment]
Hey @bisakhmondal, I think we have an issue open for activation function, do you think we need another issue for this. I think this is great and I'm looking forward to the PR.

**Comment by bisakhmondal** [comment]
Scrolling through the issues, I completely forgot that there is still an open issue regarding the Activation Functions. Thanks, I am working on it.

**Comment by zoq** [comment]
Okay, let's close this one than.
