### ISSUE TITLE
testReturn of q learning agent won't improve

### ISSUE THREAD

**Issue by joeljosephjin** [mlpack/mlpack#2275]
#### Issue description
I have been test the Deep Q Learning module on the MountainCar environment. I copied some code from "q_learning_test.cpp" for this. I have found that the average reward increases from -400 to -321 after training for 150 episodes. But on testing the thing with 20 episodes, the averageReturn is still -400, meaning that not a single Car actually crossed the goal in the testing phase. This might be due to some error my code(pasted below). This could also mean that the "q_learning_test.cpp" is also not implemented properly. 

#### Steps to reproduce

```
// ---------TRAINING PHASE--------------
int max_episodes = 150;
while (episodes < max_episodes)
{
episodeReturn = agent.Episode();		// training
averageReturn(episodeReturn);
episodes += 1;
cout << "Average return: " << averageReturn.mean()
    << " Episode return: " << episodeReturn << std::endl;
if (episodes == max_episodes)
{
	// ---------TESTING PHASE----------------
	agent.Deterministic() = true;		// enter testing mode
	arma::running_stat<double> testReturn;

	for (size_t i = 0; i < 20; ++i)		// run for 20 test episodes
		testReturn(agent.Episode());

	cout << "Average return in deterministic test(after " << episodes << " training episodes): "
			<< testReturn.mean() << std::endl;
	// -------------------------------------
}
} // end of while
// --------------------------------------
```

Whole Code : https://codeshare.io/alRVr8

**Comment by abinezer** [comment]
sure, will have a look and see what can be done to better it.
Also, would like to ask the core team if I could take this issue forward...

**Comment by zoq** [comment]
@abinezer please feel free to take a look at the issue.
