### ISSUE TITLE
Hard Shrink Activation Function does not comply to new method signatures

### ISSUE THREAD

**Issue by favre49** [mlpack/mlpack#2287]
The hard shrink activation function was added in #2186 before method signatures were changed in #2259 . Since it was merged before #2259 was merged, it still has the old method signatures.

**Comment by kartikdutt18** [comment]
Taking it up, Will fix remaining functions as well if there are any. 
Thanks.

**Comment by ojhalakshya** [comment]
Hi @favre49 
I was going to open a pr for the same today but it is okay with me if @kartikdutt18 is doing other functions also.
Thanks.
