### ISSUE TITLE
Feasibility of addition of SLIDE algorithm

### ISSUE THREAD

**Issue by sriramsk1999** [mlpack/mlpack#2290]
I came across this [article](https://insidehpc.com/2020/03/slide-algorithm-for-training-deep-neural-nets-faster-on-cpus-than-gpus/) and found it quite intriguing. I went through the paper and the results seem promising. 

It occurs to me that mlpack could make good use of this, since OpenMP is already being used and GPU support is not completely there yet, with bandicoot under development. 

Would this be a worthwhile addition to mlpack? I'd like to know what all of you think about this.

Repo link - https://github.com/keroro824/HashingDeepLearning
Paper link - https://arxiv.org/abs/1903.03129

**Comment by zoq** [comment]
Agree it's an interesting approach, but it would be better to have an implementation over here: https://github.com/mlpack/ensmallen. Let me know what you think.

**Comment by sriramsk1999** [comment]
Ah you're right, it is more suited for the ensmallen repo. I'll move this over there.
