### ISSUE TITLE
Adding Local Response Normalization

### ISSUE THREAD

**Issue by prince776** [mlpack/mlpack#2291]
HI everyone,
I'm planning to add inception network to the models repository but for that we need this normalization and a few more things. I'm opening this issue to notify that I'm working on this normalization so as to avoid multiple people working on the same thing.

**Comment by zoq** [comment]
What normalization do you mean? Also some time ago I did some work on the inception network, maybe the code is helpful in some way.

https://gist.github.com/zoq/39f972cbb11e8b4442b5dadeb6bc35d7
https://gist.github.com/zoq/d8119e2a8e2db629b6d9a896dc7f6bf2

**Comment by prince776** [comment]
Sorry for the late response @zoq . I read This paper https://arxiv.org/pdf/1409.4842.pdf and in this they were using Local Response Normalization. To understand what this meant since I was found it for the first time, I read https://towardsdatascience.com/difference-between-local-response-normalization-and-batch-normalization-272308c034ac .
