### ISSUE TITLE
Addition of Essential Metrics Only.

### ISSUE THREAD

**Issue by kartikdutt18** [mlpack/mlpack#2294]
This is a **good first issue** and will **help new contributors** to get familiar with the codebase. Also This issue **doesn't aim to add all Metrics** to mlpack since each metric would have to be maintained, this aims to add metrics that either I find essential (or have used a couple of time) or those metrics which are very common.
List of metrics that can be added include:

1. IoU and meanIoU (Taken up by me)
2. SSIM (Useful when you augment data and need to ensure that you don't augment it to an extent such that it becomes irrelevant. I used this in medical scans where there was heavy bias so I used as metric to find right augmentation parameters to perform oversampling [set augmentation parameters s.t. (average SSIM) > threshold] to automate process a bit). I think @ojhalakshya is working on it.

Other interesting metrics would:
1. r metric
2. Top K Accuracy metric
3. ~RMSE (Already implemented)~
4. [Maybe, Not really sure about this.] Sparse Top K Accuracy

In case some of these are implemented, please forgive my ignorance. Also anyone who starts working on them please check the following:
1. Has it been implemented.
2. Is there a PR open for this.
3. Is this taken up by some one. 

This is especially necessary for functions like RMSE, r metric.
Sorry for increasing workload of members and contributors, I think at least some of them will be nice additions. Thanks.

**Comment by bisakhmondal** [comment]
SSIM is interesting. @ojhalakshya are u working on it?

**Comment by zoq** [comment]
@kartikdutt18 Do you have an interface for a metric in mind, I think there is more than one approach how the interface could look like, but ideally a metric could be used by more than the one method.

**Comment by kartikdutt18** [comment]
Hi @zoq, I think the implementation would follow along the line of metrics implemented in `core/metrics`. The class has a static evaluate function with all relevant parameters. The main reason I wanted to open this PR is because when I making changes to use ensmallen in time series data (PR models/56), I noticed that we have implemented our own accuracy, MSE metric even though mlpack already has an inbuilt function for them. So at-least in that case, a static function makes sense.
I think `core/cv/metrics` does something a bit different. It also requires `model`, `input-data` and `labels` however I think above metrics are constrained to classification so approach similar to `core/metric` might make more sense. 
 However as you pointed out that might not be the only use, so is there any interface that would suggest or is this one okay?

**Comment by ojhalakshya** [comment]
> SSIM is interesting. @ojhalakshya are u working on it?

Hi @bisakhmondal 
Yup I am working on it.
Thanks.

**Comment by jeffin143** [comment]
@zoq Yes we definitely need to have a concrete API  that can be used by more than the one method and IG for that we need to define which all methods and functionality are using this metrics and thus can finally come up with the api 

There was an api in one of previous PR , which was sought of different from the current implementation

Also all most of the metrics were implemented 

https://github.com/mlpack/mlpack/pull/1836 

https://github.com/mlpack/mlpack/pull/1796 

May be while implementing some of these, We can use the previous work done

**Comment by kartikdutt18** [comment]
Hey @jeffin143, Thanks for PR links. I think it has r-metric which would be useful for anyone who takes that up. Also, I think all them have a static member function called `Evaluate` which is same what is done for other metrics. I am open to implementing a different API, Could you help us out with the same. Thanks.

**Comment by bisakhmondal** [comment]
Hey @kartikdutt18, I want to implement r metric. Just to be sure, are we talking about coefficient of determination popularly known as `R squared` metric?

**Comment by kartikdutt18** [comment]
Hey @bisakhmondal, You could take a look at #1796 for more details. I think it has the implementation. Here is the link for pytorch [PR](https://github.com/pytorch/ignite/pull/496/files/f285629b74758d571b5613c7f40cc128c0e6a2e3).

**Comment by bisakhmondal** [comment]
yeah, I was talking about the same. Issue #1796 already has the r metric implementation, but the pr is closed due to inactivity, what should I do now @kartikdutt18, implement it or go for top-k accuracy metric.

**Comment by kartikdutt18** [comment]
I think it's fine to go for it, Just build on top of it. Could you just ensure that implementation in the PR is correct and add tests. Thanks.

**Comment by bisakhmondal** [comment]
Okay then, working on it. Thanks.

**Comment by Shandilya21** [comment]
@kartikdutt18 Are all issues is still open or solved? I would like to build SSIM or Top K accuracy?

**Comment by kartikdutt18** [comment]
Hey @Shandilya21, This issue is open. SSIM is currently taken up, if you would like to work on Top K accuracy, that would be great. Just one thing I have to ask is that kindly ensure the metric isn't implemented in core/metrics or core/cv. Looking forward to your PR. Thanks a lot 👍
Also you can refer to the implementation in #2323.

**Comment by Shandilya21** [comment]
@kartikdutt18 Thanks for your comment. I am a new contributor here. I am happy to implement the Top K accuracy. Do you explain a bit more about the issue? How to proceed with it?

Thanks in Advance

**Comment by Shandilya21** [comment]
@kartikdutt18 I have checked the core/metric and core/metrics, there is no such file and implementation of Top K accuracy. Shall I proceed to build the same?

Thanks

**Comment by kartikdutt18** [comment]
Great. In this issue we plan to add some metrics as well as add tests for the same. Metrics can be found in core/cv/metrics or core/metrics. We would implement them as class with a static function Evaluate that would perform the required operation. For more info you can refer to any existing implementation. Recently, #2323 was merged and would be a great source of reference. Also tests can be found in src/tests/ . Let me know if you need any help. Looking forward to your PR. 👍

**Comment by Shandilya21** [comment]
Thanks, @kartikdutt18  for explaining the issue in detail and sharing reference #2323 . This will help me to complete the task. I will let you know if I have any doubt/problem.

**Comment by Karthikeyan564** [comment]
Hey, Is any metric still remaining?

**Comment by kartikdutt18** [comment]
I think Sparse Top K, is still available. if you would like to work on Sparse Top K accuracy, that would be great. Just one thing I have to ask is that kindly ensure the metric isn't implemented in core/metrics or core/cv. Looking forward to your PR. Thanks a lot 👍
Also you can refer to the implementation in #2323.

**Comment by Karthikeyan564** [comment]
Hey thanks, I am working on it.

**Comment by Shandilya21** [comment]
Hi, @kartikdutt18 I stuck in one point, where I need to test cases for my score.
CMake ../
CMake build
However, I added it into CmakeList.txt, but unable to check my code. Can you help me out?

Thanks

**Comment by kartikdutt18** [comment]
The commands to build are `sudo make -j2` or -jN where N is the number of cores. I am not really sure I understood the issue , do you mind pasting the error below. Thanks a lot.

**Comment by Shandilya21** [comment]
Hi, @kartikdutt18  while running the similar command as you mentioned are throwing a single line error as:

make: Nothing to be done for 'cv_test.cpp'.

I don't understand this problem. Can you remark? or I am committing a mistake?
Thanks

**Comment by kartikdutt18** [comment]
Hmm, Can you do one thing, Create a draft PR and I will probably be able to tell what's happening. Just tag me in the PR and I will respond as quickly as I can. Sorry I couldn't help you here. Thanks a lot. 👍

**Comment by Shandilya21** [comment]
Okay, @kartikdutt18 I draft a PR and tag you in it. I will raise similar PR as you suggested #2323.
Thanks.

**Comment by bisakhmondal** [comment]
> Hi, @kartikdutt18 I stuck in one point, where I need run test cases for topK accuracy score.
> CMake ../
> CMake build
> However, I added it into CmakeList.txt, but unable to run my code even with all dependencies. Can you help me out?
> 
> Thanks

Hi @Shandilya21, as told by @kartikdutt18 after building using make,  if you have written your test in cv_test.cpp and want to check it for topK, you can run `./bin/mlpack_test -t CVTest`. Hope it helps. Thanks.

**Comment by Shandilya21** [comment]
Hi, @bisakhmondal @kartikdutt18 I have some error, Further, I have set a root path of the library using the command: CMake -D BOOST_ROOT= /PATH/ -D. But I unable to figure out the error. Can you help me out? The error I got is as follows:  

  Could not find the following Boost libraries:

          boost_program_options

  Some (but not all) of the required Boost libraries were found.  You may need to install these additional Boost libraries.  Alternatively, set BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:302 (find_package)



CMake Warning at CMakeLists.txt:425 (message):
  txt2man not found; man pages will not be generated.


-- Found Python: /home/shandilya/nlp_project/bin/python
-- Configuring incomplete, errors occurred!

Thanks in advance

**Comment by bisakhmondal** [comment]
Hi @Shandilya21  before building from source, ensure your system has the required mlpack dependencies installed. You can run
```bash
sudo apt-get install libboost-math-dev libboost-program-options-dev
  libboost-test-dev libboost-serialization-dev libarmadillo-dev binutils-dev
  python-pandas python-numpy cython python-setuptools libensmallen-dev
  libstb-dev
```
(for debian based distro)
or 
```bash
dnf install boost-devel boost-test boost-program-options boost-math
  armadillo-devel binutils-devel python2-Cython python2-setuptools
  python2-numpy python2-pandas ensmallen-devel stbi-devel
```
for more details visit [link](https://www.mlpack.org/doc/mlpack-3.2.2/doxygen/build.html)
Thanks.

**Comment by himanshupathak21061998** [comment]
Hey, @Shandilya21 can, you share some details about your environment. Which operating system you are using and version of boost? I think you are are using windows I am facing same problem in windows build of conda forge https://github.com/conda-forge/mlpack-feedstock/pull/18

**Comment by Shandilya21** [comment]
Hey, @himanshupathak21061998 Thanks for your comment. My environment is as follows:
OS: Ubuntu 18.04
mlpack = 3.0.4
armadillo = 0.968
boost_version = 1.58
If you are facing problem-related to boost libraries missing then you can check the error using. I have similarly solved this issue. 
```
CMake -D BOOST_DEBUG = ON -D Boost_DETAILED_FAILURE_MSG=ON ../ 

```
However, I am not using windows but you can refer to issues #1757 for the problem. I hope that helps you.

Thanks to @bisakhmondal  for advice

**Comment by kartikdutt18** [comment]
Let's keep this open for a while. Thanks!

**Comment by joybhallaa** [comment]
@kartikdutt18 , is someone working on this issue?

**Comment by kartikdutt18** [comment]
Hey @joybhallaa, The issue is open for taking up (other than IoU metric).

**Comment by UtR491** [comment]
@kartikdutt18 I am new in open source development, reasonably comfortable with C++, recently learnt about template metaprogramming, this project really intrigued me. Is there an way I can contribute?
Thanks in advance and sorry if I appear to be an idiot.

**Comment by kartikdutt18** [comment]
Hey @UtR491, please feel free to take up any issue you like. For this particular issue, would like to implement SSIM metric ?
There are also tons of issues open if you want to check them out. If you want to play around with mlpack you can probably take a look at our examples repo.
No worries, if you get stuck at any point or face any issue, you can either tag me or any contributor in your PR and we will try to help you out. Please feel free to ask any questions here or on the IRC. We are happy to help out.
Welcome to the community!

**Comment by UtR491** [comment]
@kartikdutt18 I'll be more than happy to implement the SSIM metric, thanks for the reply!

**Comment by kartikdutt18** [comment]
Awesome! Looking forward to your PR.

**Comment by UtR491** [comment]
@kartikdutt18 From what I have understood till now, I have to take two images as arguments, the reference and the processed image, these will be armadillo matrices.Then I have to check if both have the same size. If they have the same size, I have to use the formula to calculate the SSIM index and if not then throw the relevant error. The terms in the formula can be found using armadillo member functions. Is there anything I am missing or not doing right? If this is it, then I think I am more than half way through the implementation.

**Comment by kartikdutt18** [comment]
Right, that is correct. If you want to refer some PRs regarding metrics you can take a look at #2323 or #2402.

**Comment by UtR491** [comment]
@kartikdutt18 I think I am stuck, yesterday I thought that I had to just apply the SSIM formula to the entire image at once. Today, I realise I had to apply it locally in an 11X11 window using a 
> Gaussian Weighting Function
When I googled about it, there were Wikipedia articles about the Gaussian function, which I know about and other things like Gaussian Blur. I do realise that the former is somehow the extension of the latter but I am essentially lost. I did take a look at an octave implementation of the SSIM metric but it had predefined functions to calculate the 11X11 Gaussian Kernel(or Weighting Function) is there some function in armadillo or mlpack which i can use to create a Gaussian Kernel? I tried to find something but was unable to do so. I am sorry that this is taking this much time.

**Comment by UtR491** [comment]
@kartikdutt18 I think I am stuck, yesterday I thought that I had to just apply the SSIM formula to the entire image at once. Today, I realise I had to apply it locally in an 11X11 window using a
    Gaussian Weighting Function
When I googled about it, there were Wikipedia articles about the Gaussian function, which I know about and other things like Gaussian Blur. I do realise that the former is somehow the extension of the latter but I am essentially lost. I did take a look at an octave implementation of the SSIM metric but it had predefined functions to calculate the 11X11 Gaussian Kernel(or Weighting Function) is there some function in armadillo or mlpack which i can use to create a Gaussian Kernel? I tried to find something but was unable to do so. I am sorry that this is taking this much time.

**Comment by kartikdutt18** [comment]
No worries, I think you refer to this [implementation](https://github.com/Po-Hsun-Su/pytorch-ssim/blob/master/pytorch_ssim/__init__.py). It uses pytorch tensor but converting it to armadillo shouldn't be very hard. It also has the code for to initialize a Gaussian window. And armadillo might have a way of filling a window but I am not sure. In mlpack, we also have Gaussian distribution [here](https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/dists/gaussian_distribution.hpp).

>  I am sorry that this is taking this much time.

No worries, take your time. Let me know if I need to clarify anything.

**Comment by UtR491** [comment]
@kartikdutt18 I think I am done with the main part of the implementation other than the documentation stuff. Would you mind taking a look at it? I haven't ever worked with makefiles. I just followed the steps in the README but inside the core/cv/metrics/  directory and did not receive any error specific to the files I added to the folder.

**Comment by kartikdutt18** [comment]
Sure, You can make a PR and I'll take a look. Just tag me there. Thanks a lot for the contribution.
Regards.

**Comment by DuP-491** [comment]
Greetings,
I am new to open source development, I went through the details of mlpack project via gsoc organization list. I would like to do contribute to the project, can someone please guide me?

**Comment by kartikdutt18** [comment]
Hey @DuP-491,
Welcome to the community, You can take a look at out [Getting Started Page](https://www.mlpack.org/community.html) and our [GSoC Page](https://www.mlpack.org/gsoc.html). You can also contact everyone through the mailing list or the IRC.
Regards.

**Comment by DuP-491** [comment]
@kartikdutt18 thanks for the quick reply,I'll surely go through them

**Comment by kartikdutt18** [comment]
Keep Open.

**Comment by kartikdutt18** [comment]
Keep open.

**Comment by kartikdutt18** [comment]
Keep Open.

**Comment by rishishounak** [comment]
Hello I am new to this library, could you suggest some metric that I could add. Also please tell me how to get started

**Comment by rishishounak** [comment]
@kartikdutt18 please reply?

**Comment by kartikdutt18** [comment]
Hey @rishishounak,
You can try to add SSIM metric to this repo. To get started you can take a look at the getting atarted page as well as the GSoC page for this repo. Links to both are mentioned above.
Thanks for interest in this organization and welcome to community.
Regards.

**Comment by kartikdutt18** [comment]
Also you can take a look at the metrics that were recently added. This includes PRs for NMS metric and IoU metric.

**Comment by kushagrabhushan** [comment]
Hi. I'm very new to open source. Can someone tell me how to get started? I'd really like to contribute!

**Comment by rcurtin** [comment]
Hi @kushagrabhushan, you've already asked that on three other issues in the past ten minutes.  Perhaps you should wait for an answer on one of those other issues, or see the mlpack website, which has clear directions for how to get involved?

**Comment by kushagrabhushan** [comment]
@rcurtin I'm really sorry I didn't know everyone could see those..... I'll go read up. Thank you

**Comment by rishishounak** [comment]
https://github.com/mlpack/mlpack/pull/2427
@zoq  could you give some description of what went wrong with the above pull request for implementing SSIM metric. Thanks

**Comment by CharanpreetSingh056** [comment]
Hey @kartikdutt18 , I was thinking to implement Adjusted R squared , since it is one of the of the key evaluation metrics used for regression tasks . Also I think I am halfway and will complete soon , should I go forward with the same ?

**Comment by Anmol2001** [comment]
hey @kartikdutt18  I am trying to work on SSIM .

**Comment by Rishabhc711** [comment]
Hi! I find the Top K accuracy metric to be rather interesting. If poosible, should I start working on it?

**Comment by Rishabhc711** [comment]
And where do I start with in the codebase?

**Comment by kartikdutt18** [comment]
Hi, Sure I think #2378 has went stale. Maybe you can build upon that.

**Comment by Rishabhc711** [comment]
Oh okay thanks! Will surely start looking into it!
However, what was the reason the PR was closed rather than merged?

**Comment by Anmol2001** [comment]
Hi @Rishabhc711 ! That  PR was closed due to many issues in implementation and I am already looking into Addition of useful metrics as a summer project. You can have a look at another good first issue.
@kartikdutt18  Can I get suggestions on some more useful metrics.
