### ISSUE TITLE
Addition of Transformer Layer

### ISSUE THREAD

**Issue by mrityunjay-tripathi** [mlpack/mlpack#2296]
I was just reading the BERT (language representation model) [paper](https://arxiv.org/abs/1810.04805). BERT requires the Transformer Layer. I think it should be in ```src/mlpack/methods/ann/layer```, but is not already there. Is it implemented somewhere else? If not can I start working on it?
References: 
1. [Attention Is All You Need](https://arxiv.org/abs/1706.03762)
2. [PyTorch - Transformer](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/transformer.py)
3. [Keras - Transformer](https://pypi.org/project/keras-transformer/)

Todo:
- [ ] Addition of Multihead Attention Layer
- [ ] Addition of Transformer Encoder Layer
- [ ] Addition of Transformer Decoder Layer
- [ ] Addition of Transformer Layer
- [ ] Addition of tests for all layers

**Comment by zoq** [comment]
Feel free, but keep in mind to write a test suite for the layer as well.

**Comment by mrityunjay-tripathi** [comment]
>Feel free, but keep in mind to write a test suite for the layer as well.

Sure @zoq. Once I am done with the implementation, I will add tests as well.

**Comment by jeffin143** [comment]
I am not sure but #1725 , There are some works or discussion which could be helpful for this, Looking forward to this

**Comment by mrityunjay-tripathi** [comment]
Thanks @jeffin143 for the reference. I think this is what I am going to implement (attention network and encoder-decoder layer), but I see that the methods are different according to the references. Even though I need to get a closer look into it (maybe in 2-3 days).
