### ISSUE TITLE
Tests fail to run: 'arma_config.hpp' has been modified since the precompiled header

### ISSUE THREAD

**Issue by yurivict** [mlpack/mlpack#2297]
```
fatal error: file '/usr/ports/math/mlpack/work/mlpack-3.2.2/src/mlpack/core/util/arma_config.hpp' has been modified since the precompiled header '/usr/ports/math/mlpack/work/.build/src/mlpack/cotire/mlpack_CXX_prefix.hxx.pch' was built
note: please rebuild precompiled header '/usr/ports/math/mlpack/work/.build/src/mlpack/cotire/mlpack_CXX_prefix.hxx.pch'
```

**Comment by himanshupathak21061998** [comment]
Hey @yurivict Can please provide some steps to reproduce this.

**Comment by yurivict** [comment]
The steps are:
1. Build with these options off: ```BUILD_PYTHON_BINDINGS BUILD_TESTS BUILD_CLI_EXECUTABLES BUILD_PYTHON_BINDINGS```
2. Then build with the same, but ```BUILD_TESTS=ON```

**Comment by rcurtin** [comment]
Can you do `make clean` and then rebuild?  This seems like an artifact was left around from the previous build.

**Comment by himanshupathak21061998** [comment]
I can't able to reproduce this I tried it with both master and mlpack 3.2.2 maybe you should `make clean` as suggested by @rcurtin .

**Comment by yurivict** [comment]
Something in the build touches the header after the pre-compiled headers file has been built.

**Comment by kartikdutt18** [comment]
Hey @yurivict, I have faced this issue. As suggested about run `make clean` and then you should be good to go. Did you try it yet?

**Comment by yurivict** [comment]
Doing ```make clean``` first works as a workaround.

But it's weird that this should be done, the logic of make is broken. You should fix this.

**Comment by kartikdutt18** [comment]
I think it's completely fine. If you have built mlpack before the cmake patch and then fetched upstream and built again, you'll get this error. Performing make clean removes compilations from previous version and build won't fail. You can try running build as many time as you want now, I think it should work. However I might be missing something.
Thanks.

**Comment by yurivict** [comment]
> and then fetched upstream and built again

I didn't fetch upstream. Fetchcing invalidates the build, and it should automatically rebuild it before test.

Your target dependencies are broken. Any target should be able to run independently.

**Comment by rcurtin** [comment]
I tried to reproduce the issue and I can't.  I'd love to fix the issue but it's not very helpful to just say "you should fix it" when none of us have successfully reproduced it and none of us actually understand what is causing the problem.  (BTW there was a bug report issue template, which could have been helpful if you filled it out.)  What CMake generator are you using?  Can you reproduce the issue in, e.g., a Docker container running Ubuntu or something? (I know you're on FreeBSD, so maybe that isn't trivial, but I'm not sure any developers here are on FreeBSD so I don't know if we'll have success reproducing it outside that environment.  Maybe?  I'm not sure.)
