### ISSUE TITLE
Padding in Pooling Layers

### ISSUE THREAD

**Issue by codeboy5** [mlpack/mlpack#2303]
Pytorch has the support for adding padding in pooling layers (https://pytorch.org/docs/stable/nn.html#maxpool2d). Going through the codebase I saw that mlpack does not have support for it.
I would like to work on this unless it has not been added by choice. I would add default values so existing codes not break.
I would open a PR if this sounds good.

**Comment by kartikdutt18** [comment]
Hey @codeboy5, we have a PR open for this that pretty much done (at least from my side). There is also an issue open for this.
Refer #2127. 
Thanks.

**Comment by codeboy5** [comment]
ohh okay!
