### ISSUE TITLE
load_save_test fails on MacOS (at least through Azure)

### ISSUE THREAD

**Issue by birm** [mlpack/mlpack#2308]
Azure tests have been failing, namely those around value tests of test_file.h5 https://github.com/mlpack/mlpack/blob/295398e46816df3663a5c851b46981ca2a03d56e/src/mlpack/tests/load_save_test.cpp#L867 and https://github.com/mlpack/mlpack/blob/295398e46816df3663a5c851b46981ca2a03d56e/src/mlpack/tests/load_save_test.cpp#L813

I'm reporting this so, at least, it's a _known issue_ rather than a thing each new PR needs a disclaimer about.

See https://dev.azure.com/mlpack/mlpack/_build/results?buildId=1015&view=logs&j=1b38ea94-fede-5667-20eb-44d3de1ec085&t=72087b03-c17c-5a26-b713-236d9bb6c096&l=138

**Comment by kartikdutt18** [comment]
Hey @birm, Thanks for raising an issue for this, There is a kind of working solution in #2278, I think it needs some changes but the last time I checked it had passed the LoadSaveTest on MacOS. Thanks a lot.

**Comment by kartikdutt18** [comment]
Also it fails locally when I ran an update on my dependencies, I wasn't able to fix it so maybe the PR will provide us with the solution for the same.

**Comment by zoq** [comment]
Right, #2278, should fix the issue, let's see if https://dev.azure.com/mlpack/mlpack/_build/results?buildId=1028&view=results returns green, and close the issue afterwards.

**Comment by birm** [comment]
And we're good!
