### ISSUE TITLE
Adding IBEGAN module to mlpack library 

### ISSUE THREAD

**Issue by rakeshacharya-d** [mlpack/mlpack#2313]
Hello guys  !

I'm Rakesh, i want to contribute to mlpack library by building the Image Generation modules .

Currently  mlpack has GAN,WGAN.Many latest GAN models have disrupted the Image Generation field like BEGAN,Energy Based GAN,Manifold Matching GAN,Probabilistic GAN.Among the existing models BEGAN/I-BEGAN outruns most of the models,including Energy Based GANs.I hope it will be a good leap forward in building mlpack Image Generation modules.

After the discussion that i had with @zoq on the same , i would like to proceed by starting the  work on building the module.

**Comment by favre49** [comment]
That would be great, I look forward to seeing it :)
