### ISSUE TITLE
Padding layer implementation seems wrong.

### ISSUE THREAD

**Issue by prince776** [mlpack/mlpack#2318]
If we look at padding layer's Forward function, it is:
```
void Padding<InputDataType, OutputDataType>::Forward(
    const arma::Mat<eT>& input, arma::Mat<eT>& output)
{
  nRows = input.n_rows;
  nCols = input.n_cols;
  output = arma::zeros(nRows + padWLeft + padWRight,
      nCols + padHTop + padHBottom);
  output.submat(padWLeft, padHTop, padWLeft + nRows - 1,
      padHTop + nCols - 1) = input;
}
```

Here the padding is being done assuming input is a single data point, however it is `nCols` datapoints and each datapoint having `nRows` features. Padding should be done to each col after converting it into a cube of shape `(inputWidth, inputHeight, inSize)`. 

This layer also causes incorrect dimension multiplication errors when used, which I believe is due to this.

I would like to fix the layer, but before that if I will be glad to know if I am missing something, Thanks.

**Comment by ShikharJ** [comment]
That's okay, for padding, we're simply passing individual inputs to the layers anyways. See the `Forward` function in `ann/layer/convolution_impl.hpp`:
```
void Convolution<
    ForwardConvolutionRule,
    BackwardConvolutionRule,
    GradientConvolutionRule,
    InputDataType,
    OutputDataType
>::Forward(const arma::Mat<eT>& input, arma::Mat<eT>& output)
{
  batchSize = input.n_cols;
  inputTemp = arma::cube(const_cast<arma::Mat<eT>&>(input).memptr(),
      inputWidth, inputHeight, inSize * batchSize, false, false);

  if (padWLeft != 0 || padWRight != 0 || padHTop != 0 || padHBottom != 0)
  {
    inputPaddedTemp.set_size(inputTemp.n_rows + padWLeft + padWRight,
        inputTemp.n_cols + padHTop + padHBottom, inputTemp.n_slices);

    for (size_t i = 0; i < inputTemp.n_slices; ++i)
    {
      padding.Forward(inputTemp.slice(i), inputPaddedTemp.slice(i));
    }
  }
...
```
Hope this helps.

**Comment by prince776** [comment]
I see. I used it directly in FFN.Add() before max pooling so I can get same pooling effect so it gave error. 
Just a little doubt, is it a good thing to have some layers in layer folders that can't be directly used in FFN/RNN, just from design point of view.

**Comment by ShikharJ** [comment]
> Just a little doubt, is it a good thing to have some layers in layer folders that can't be directly used in FFN/RNN, just from design point of view.
I'm not sure I understand what you mean by "can't be directly used".

**Comment by prince776** [comment]
By directly using padding layer I meant something like:
```
FFN<> model;
model.Add<Convolution<>>(3, 16,3,3,1,1,1,1,28,28) ;
model.Add<Padding<>>(1, 1,1,1) ;
model.Add<MaxPooling<>>(3, 3, 2, 2) ;
....
```
Since pooling layer currently doesn't support padding(there is a PR #2127 but not merged yet) , but inception network required same  padded pooling, I used it for this purpose and thought implementation is wrong.

**Comment by ShikharJ** [comment]
To be honest, having a separate direct layer for padding seems a bit too excessive for me. I'd rather have the pad variables overloaded in the pooling layer implementation itself, if they're needed. Very few models need intermittent padding anyways. Not sure if that's what the other PR does.

**Comment by prince776** [comment]
Yes having a direct layer for padding is unnecessary, but since Pooling layers don't have padding feature(and it was required in Inceptionv1) I was just trying to use this as a temp solution, but its usage was different than I thought.
I think I will wait till #2127 is merged or write some temp code to solve it.
Thanks for all the information.
