### ISSUE TITLE
Multithread Naive Convolution?

### ISSUE THREAD

**Issue by adiwajshing** [mlpack/mlpack#2319]
Hi,

Is there a reason why the NaiveConvolution::Convolution functions haven't been multithreaded?

**Comment by zoq** [comment]
OpenBLAS should be able to use multiple cores for the computation, so there is often no need to explicitly implement threading.

**Comment by adiwajshing** [comment]
Actually, the code does not use Armadillo. Is there a reason why that is?
`
template<typename eT, typename Border = BorderMode>
  static typename std::enable_if<
      std::is_same<Border, ValidConvolution>::value, void>::type
  Convolution(const arma::Mat<eT>& input,
              const arma::Mat<eT>& filter,
              arma::Mat<eT>& output,
              const size_t dW = 1,
              const size_t dH = 1,
              const size_t dilationW = 1,
              const size_t dilationH = 1)
  {
    output = arma::zeros<arma::Mat<eT> >(
        (input.n_rows - (filter.n_rows - 1) * dilationW - 1) / dW + 1,
        (input.n_cols - (filter.n_cols - 1) * dilationH -  1) / dH + 1);

    // It seems to be about 3.5 times faster to use pointers instead of
    // filter(ki, kj) * input(leftInput + ki, topInput + kj) and output(i, j).
    eT* outputPtr = output.memptr();

    for (size_t j = 0; j < output.n_cols; ++j)
    {
      for (size_t i = 0; i < output.n_rows; ++i, outputPtr++)
      {
        const eT* kernelPtr = filter.memptr();
        for (size_t kj = 0; kj < filter.n_cols; ++kj)
        {
          const eT* inputPtr = input.colptr(kj * dilationW + j * dW) + i * dH;
          for (size_t ki = 0; ki < filter.n_rows; ++ki, ++kernelPtr,
              inputPtr += dilationH)
            *outputPtr += *kernelPtr * (*inputPtr);
        }
      }
    }
  }
`

**Comment by Param-29** [comment]
Hey @adiwajshing, I could help you check if OpenBLAS converts it to a multithreaded program, can you add a testing code which you used to check this. Thanks :)

**Comment by adiwajshing** [comment]
Hey, the matrix functions are parallelized, but I don't think it OpenBLAS parallelizes a for loop.
Anyway, I think I figured something out, please see here  #2341

**Comment by FabioMBB** [comment]
Hi Guys, was this ever merged?
