### ISSUE TITLE
Data type of loss functions

### ISSUE THREAD

**Issue by mrityunjay-tripathi** [mlpack/mlpack#2338]
The [loss functions](https://github.com/mlpack/mlpack/tree/master/src/mlpack/methods/ann/loss_functions) in ann return ```double``` type loss only. Can we have the template for that as well so that users can set the precision whatever they want? In general, we don't use precision up to 17 decimal points for calculating loss, so using just float should work fine I think.

For example
```
template<typename InputDataType, typename OutputDataType>
template<typename InputType, typename TargetType>
typename InputType::value_type MyLossFunction<InputDataType, OutputDataType>::Forward(
    const InputType& input,
    TargetType& target)
{
  using RealType = typename InputType::value_type;
  
  // Use RealType wherever loss variable has to be dealt with.
}
```
What do you think?

**Comment by kartikdutt18** [comment]
Maybe this is same as #1062 ?
What do you think.
Thanks.

**Comment by mrityunjay-tripathi** [comment]
Yeah, You are a miner @kartikdutt18 ;) As mentioned by @rcurtin [here](https://github.com/mlpack/mlpack/issues/1062#issuecomment-316462704) and further in the conversation about templating matrix types (which is already done) but extracting the underlying data types of matrices is not implemented. Boost uses something as ```RandomAccessContainer``` for non-scalar data-types where ```RandomAccessContainer::value_type``` returns the data-type of element in the container.

**Comment by kartikdutt18** [comment]
I think we can close this then.

**Comment by zoq** [comment]
Agreed, with https://github.com/mlpack/mlpack/pull/2339 merged let's close this one.
