### ISSUE TITLE
Dual cover tree traverser is quite slow

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#235]
**Reported by rcurtin on 25 Oct 42625579 22:12 UTC**
Using current sources (r13421), CoverTree<>::DualTreeTraverser performs particularly slow searches.  For example, running (and then profiling) allknn with query and reference sets equal to 50k points out of the covtype dataset (covtype_r-50k.csv), here are the number of base case computations:
- jl's implementation: 22.5M
- mlpack, single kd-tree: 9.1M
- mlpack, dual kd-tree: 8.9M
- mlpack, single cover tree: 37.9M
- mlpack, dual cover tree: 411M

So the problem is fairly clear.  When getting numbers for this, one must be careful to compile disabling inlining if using profiles to get the numbers (-fno-inline).

**Comment by stinger0962** [comment]
Great working process. Now we are facing the same issue as you once had. Our team is trying to figure out why MLPack's kd-tree is superior than ours.
