### ISSUE TITLE
1x0 matrix

### ISSUE THREAD

**Issue by Trento89** [mlpack/mlpack#2358]
#### Issue description

When passing an arma::Row<size_t> object into the Train() method of mlpack::regression::LogisticRegression, I get an error message stating that the program is being terminated due to incompatible matrix dimensions.  Only problem is that one of the matrices is shown with the wrong dimensions, specifically 1x0 when it is actually supposed to be 1x4.

#### Your environment

 * version of mlpack: 3.0.4-1
 * operating system: Debian 10 (Buster)
 * compiler: g++
 * version of dependencies (Boost/Armadillo): Armadillo 1:9.200.7+dfsg-1
 * any other environment information you think is relevant:

#### Steps to reproduce

Compile the program below using the command  **g++ -std=gnu++17 -larmadillo -fopenmp -lmlpack bug_reproduction.cpp -o buggy_program** and then execute it.
[bug_reproduction.cpp.txt](https://github.com/mlpack/mlpack/files/4440460/bug_reproduction.cpp.txt)

#### Expected behavior

Program trains a model based on the hardcoded values specified in the program.

#### Actual behavior
The following output appears in the terminal:
> error: matrix multiplication: incompatible matrix dimensions: 1x0 and 3x4
> terminate called after throwing an instance of 'std::logic_error'
>   what():  matrix multiplication: incompatible matrix dimensions: 1x0 and 3x4
> Aborted

**Comment by rcurtin** [comment]
Hey there @Trento89, thanks for the clear and concise bug report.  I had to modify the code a little bit to get it to compile, but it's quite similar:

```
#include <iostream>
#include <string>
#include <filesystem>
#include <vector>
#include <algorithm>

#include <mlpack/core.hpp>
#include <mlpack/methods/logistic_regression/logistic_regression.hpp>

using namespace arma;
using namespace mlpack;

int main(){
  mat myMatrix;

  myMatrix << 0.555950 << 0.274690 << 0.540605 << 0.798938 << endr
	   << 0.948014 << 0.973234 << 0.216504 << 0.883152 << endr
	   << 0.023787 << 0.675382 << 0.231751 << 0.450332 << endr;

  Row<size_t> myTargets = Row<size_t>("1 0 1 0");

  std::cout << myMatrix << "\n\n" << myTargets << "\n\n";

  regression::LogisticRegression<> lr;

  lr.Train(myMatrix,myTargets);

  return 0;
}
```

I found that the problem still exists on the git master branch, and then I dug a bit more and figured out what was wrong.  #2359 fixes the issue, so once that's merged (...and eventually pushed to Debian) the problem should be solved.

In the mean time, you can work around the issue by initializing the `LogisticRegression` object at the same time as training it:

```
regression::LogisticRegression<> lr(myMatrix, myTargets);
// no separate call to Train() necessary
```

Thanks for the bug report! :+1:
