### ISSUE TITLE
Support for CheckSameSizes & CheckSameDimensionality utility

### ISSUE THREAD

**Issue by bisakhmondal** [mlpack/mlpack#2361]
Currently, we have `AssertSizes()` method in `core/cv/metrics/facilities.hpp` for checking same number of data points & labels. But its scope & usage is limited to only metrics only.

  As suggested by @rcurtin on issue #2346 we should add `CheckSameSizes()`, `CheckSameDimensionality()` utilities in `core\utils`  for size and dimensionality checking, as it can improve code readability and reduce code size & duplication of same code over and over.

**Comment by kartikdutt18** [comment]
Keep Open, please. Thanks.

**Comment by rcurtin** [comment]
Oops, let's leave this open until #2370 is merged.
