### ISSUE TITLE
Implementation of Policy Gradient Methods

### ISSUE THREAD

**Issue by abinezer** [mlpack/mlpack#2363]
In the reinforcement learning module, we already have a value-based implementation which involves methods like q_learning and the greedy policy. We could now move to policy optimization . Below are a few policy gradient methods I know of and plan to implement soon. Please feel free to add to the list... - 
1. Vanilla Policy Gradient (VPG)
2. Trust Region Policy Optimization (TRPO)
3. Proximal Policy Optimization (PPO) #1912 
4. Deep Deterministic Policy Gradient (DDPG)

**Comment by joeljosephjin** [comment]
I have been trying to implement REINFORCE for some time now, but I'm stuck because the softmax layer isn't implemented yet, and the log_softmax layer has some problems it seems. I hope it's not an issue if I keep working on it in "parallel" with you.

**Comment by abinezer** [comment]
Absolutely no problem. I would require lots of help, so that's a good thing!

**Comment by aadarsh-asthana** [comment]
I would like to hop on to this if that's fine. I'd specifically like to work on the actor-critic algorithms
