### ISSUE TITLE
Access violation reading location 

### ISSUE THREAD

**Issue by markodjordjic** [mlpack/mlpack#2372]
#### Your environment

 * version of mlpack:
 * operating system: W10
 * compiler:
 * version of dependencies (Boost/Armadillo):
 * any other environment information you think is relevant:

#### Steps to reproduce

This is the example that throws an error:

#include <iostream>
#include <vector>
#include <mlpack/core.hpp>
#include <mlpack/methods/lars/lars.hpp>
int main()
{
    arma::mat features(11, 100);
    arma::rowvec targets(100);
    mlpack::regression::LARS glm (false, .5, .5);
    std::vector<mlpack::regression::LARS> inventoryofModels;
    inventoryofModels.emplace_back(glm);
    inventoryofModels[0].Train(features, targets);
    std::cout << "Training completed\n";
}

#### Expected behavior

The LARS should be trained.

#### Actual behavior

Exception: read access violation has been thrown.

**Comment by rcurtin** [comment]
This appears to be an issue with `LARS`'s lack of copy constructor and copy operator.  It should be a relatively easy fix.

**Comment by kartikdutt18** [comment]
Hey @rcurtin, @markodjordjic, I tried reproducing this issue on OSX and on lab-mlpack.org . However, it doesn't cause any failure. Does this failure only exist on windows?
Here is the link for the [notebook](https://github.com/kartikdutt18/mlpack-models-weights-and-datasets/blob/master/DoesLARSFailOnline.ipynb). Also, will other methods such as linear regression also fail when we perform something like this. I will setup my windows and try it again.

**Comment by rcurtin** [comment]
@kartikdutt18 I bet you can make it happen like this:

```
arma::mat features(11, 100);
arma::rowvec targets(1, 100);
mlpack::regression::LARS* glm = new mlpack::regression::LARS(false, .5, .5);
std::vector<mlpack::regression::LARS> inventoryofModels;
inventoryofModels.emplace_back(*glm);
delete glm; // Force freeing of LARS internal memory.
inventoryofModels[0].Train(features, targets);
std::cout << "Training completed\n";
```

I haven't tried it, but if you do, let us know what happens. :)

**Comment by markodjordjic** [comment]
@rcurtin and @kartikdutt18 thank you both.
I have updated the snippet. (There was one extra line, that is now gone.) The snippet above definitely does not work. Once placed inside a vector, declared LARS object, cannot be trained. Funny enough, if a trained object is placed into a vector, predictions can be made.
The suspectable line in the lars.cpp is:
          matGramActive(i, j) = (*matGram)(activeSet[i], activeSet[j]);

**Comment by kartikdutt18** [comment]
Hmm, This still works on the notebook. However I got them to fail locally (both of them). I will try adding a copy constructor and checking if it works. Thanks a lot.

**Comment by markodjordjic** [comment]
Yes, the notebook consists of old snippet. Can you spot the difference? ;)

**Comment by markodjordjic** [comment]
I'll save your time. Trained model can be added, and accessed. However, declared model, with parameter only cannot.

**Comment by kartikdutt18** [comment]
Yep, I updated the notebook also. However I got both the above codes to fail locally. So l'll try and fix them.

**Comment by markodjordjic** [comment]
Thanks!

**Comment by rcurtin** [comment]
@markodjordjic we'll release mlpack 3.3.1 soon with a fix.  Thanks again for the report! :+1:
