### ISSUE TITLE
I couldn't  find CMakelists in mlpack file

### ISSUE THREAD

**Issue by WayneDrem** [mlpack/mlpack#2381]
I build my mlpack following the tips from https://www.mlpack.org/doc/mlpack3.2.2/doxygen/build_windows.html
The mistake apeared when I linked armadillo and built mlpack.
(1)
Download the newest version of Armadillo from Sourceforge
Unzip to "C:\mlpack\armadillo"
Create a "build" directory into "C:\mlpack\armadillo\"
Open the Command Prompt and navigate to "C:\mlpack\armadillo\build"
Run cmake:
cmake -G "Visual Studio 15 2017 Win64" -DBLAS_LIBRARY:FILEPATH="C:/mlpack/mlpack/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" -DLAPACK_LIBRARY:FILEPATH="C:/mlpack/mlpack/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" ..

There are what I did and mistakes:
C:\mlpack\mlpack\build>cmake -G "Visual Studio 16 2019" -A x64 -DBLAS_LIBRARY:FILEPATH="C:/mlpack/mlpack/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" -DLAPACK_LIBRARY:FILEPATH="C:/mlpack/mlpack/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a"..
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

CMake Error: The source directory "C:/mlpack/mlpack/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

(2)
Create a "build" directory into "C:\mlpack\mlpack\"
You can generate the project using either cmake via command line or GUI. If you prefer to use GUI, refer to the appendix
To use the CMake command line prompt, open the Command Prompt and navigate to "C:\mlpack\mlpack\build"
Run cmake:
cmake -G "Visual Studio 15 2017 Win64" -DBLAS_LIBRARY:FILEPATH="C:/mlpack/mlpack/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" -DLAPACK_LIBRARY:FILEPATH="C:/mlpack/mlpack/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" -DARMADILLO_INCLUDE_DIR="C:/mlpack/armadillo/include" -DARMADILLO_LIBRARY:FILEPATH="C:/mlpack/armadillo/build/Debug/armadillo.lib" -DBOOST_INCLUDEDIR:PATH="C:/boost/" -DBOOST_LIBRARYDIR:PATH="C:/boost/lib64-msvc-14.1" -DDEBUG=OFF -DPROFILE=OFF ..

There are what I did and mistakes:
C:\mlpack\mlpack\build>cmake -G "Visual Studio 16 2019" -A x64 -DBLAS_LIBRARY:FILEPATH="C:/mlpack/mlpack/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" -DLAPACK_LIBRARY:FILEPATH="C:/mlpack/mlpack/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" -DARMADILLO_INCLUDE_DIR="C:/mlpack/armadillo/include" -DARMADILLO_LIBRARY:FILEPATH="C:/mlpack/armadillo/build/Debug/armadillo.lib" -DBOOST_INCLUDEDIR:PATH="C:/boost/" -DBOOST_LIBRARYDIR:PATH="C:/boost/lib64-msvc-14.1" -DDEBUG=OFF -DPROFILE=OFF ..
CMake Error: The source directory "C:/mlpack/mlpack" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by zoq** [comment]
> CMake Error: The source directory "C:/mlpack/mlpack/build" does not appear to contain CMakeLists.txt.
> Specify --help for usage, or press the help button on the CMake GUI.

Maybe the configure command (cmake) got split into multiple lines, because it looks like the `..` at the end (point cmake to the directory `../build`) is ignored, looks like a missing space after the last `"`

Let me post the command here again:

```
cmake -G "Visual Studio 16 2019" -A x64 -DBLAS_LIBRARY:FILEPATH="C:/mlpack/mlpack/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" -DLAPACK_LIBRARY:FILEPATH="C:/mlpack/mlpack/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" ..
```

**Comment by WayneDrem** [comment]
@zoq I failed again.The problem is that I find there are no cMakelists.txts in these files indeed.

**Comment by WayneDrem** [comment]
@zoq Somebody told me that I should to use git to clone.But I really don't know what to do.It seems like that there should be CMakelists.txts in the files?

**Comment by conradsnicta** [comment]
@WayneDrem - Windows is not exactly the most user friendly environment for this sort of work. It has a lot of problems, including unreliable compliers (ie. MSVC).

You would be much better off and save yourself a lot of time (and headaches!) by using an instance of Linux (eg. Ubuntu or Fedora). This will provide you with a proper environment and a decent compiler.  You can use Linux in a virtual machine within Windows, through software like VirtualBox.

**Comment by WayneDrem** [comment]
@conradsnicta  Thanks a lot.

**Comment by zoq** [comment]
> @zoq I failed again.The problem is that I find there are no cMakelists.txts in these files indeed.

You mean, you can't find: https://github.com/mlpack/mlpack/blob/master/CMakeLists.txt?

**Comment by WayneDrem** [comment]
@zoq 
yep.It always says that my path don't contain Cmakelists.txt.
I guess I have to give up  and try to use ubuntu

**Comment by zoq** [comment]
> @zoq
> yep.It always says that my path don't contain Cmakelists.txt.
> I guess I have to give up and try to use ubuntu

Can you download the archive: https://www.mlpack.org/files/mlpack-3.3.0.tar.gz it's the official release and I just checked it has the CMake file.
