### ISSUE TITLE
Dataset used in Python Get Started example is not available at mlpack.org

### ISSUE THREAD

**Issue by gmanlan** [mlpack/mlpack#2384]
The quick start guide offers a Random Forest example in Python here: https://www.mlpack.org/doc/mlpack-3.3.0/doxygen/python_quickstart.html

Which refers to the dataset:
`df = pd.read_csv('http://www.mlpack.org/datasets/covertype-small.csv.gz')`

But this dataset file is not available in the web server: "The requested URL was not found on this server"

**Comment by birm** [comment]
I get a 301, but my version of pandas seems to have no problem with it.
Curl output:
```bash
$ curl -v http://www.mlpack.org/datasets/covertype-small.csv.gz
*   Trying 216.24.161.178...
* TCP_NODELAY set
* Connected to www.mlpack.org (216.24.161.178) port 80 (#0)
> GET /datasets/covertype-small.csv.gz HTTP/1.1
> Host: www.mlpack.org
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Date: Fri, 24 Apr 2020 04:20:01 GMT
< Server: Apache
< Location: https://www.mlpack.org/datasets/covertype-small.csv.gz
< Content-Length: 262
< Content-Type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.mlpack.org/datasets/covertype-small.csv.gz">here</a>.</p>
</body></html>
* Connection #0 to host www.mlpack.org left intact
```
Python:
```python
>>> import pandas as pd
>>> df = pd.read_csv('http://www.mlpack.org/datasets/covertype-small.csv.gz')
>>> df
       elevation  aspect  slope  ...  soil_type_39  soil_type_40  label
0           3493      16     14  ...             1             0      7
1           2917       4     15  ...             0             0      2
2           3281      64     13  ...             0             0      2
3           3021      90     14  ...             0             0      1
4           3287      28     10  ...             0             0      1
...          ...     ...    ...  ...           ...           ...    ...
99995       3258      45      8  ...             0             0      1
99996       3290      33     11  ...             1             0      1
99997       2977     271     33  ...             0             0      1
99998       3084     323      7  ...             0             0      1
99999       3210     236      2  ...             0             0      1

[100000 rows x 55 columns]
```

**Comment by rcurtin** [comment]
Right, I just took a look and the file appears to be there:

https://www.mlpack.org/datasets/

@gmanlan maybe the 301 redirect to HTTPS is causing a problem on your system or something?  Do you have any additional output from when you tried?

(Also, maybe it is possible that you got extremely unlucky and happened to access the website right when a rebuild was being deployed?  That seems really unlikely though.)

**Comment by gmanlan** [comment]
Wow, that's extremely weird. I can assure that I was getting 404, tried like 10 times yesterday from Databricks and from the browser. Now it's working.... maybe a deployment or proxy issue?
Anyway, thanks for checking! We can move on.

**Comment by rcurtin** [comment]
Huh, that is strange; but I can't think of what the issue would have been.  The website only rebuilds every night at midnight UTC (8pm EST, 5pm PST), and even then it just drops the new website in place so any 404s or issues should be basically instantaneously fixed.

**Comment by shrit** [comment]
@rcurtin, How much time is required for a build to finish? When this issue has been posted I tried 20 minutes later and I got also 404. I thought some maintenance was happening. I found it strange that a build takes as long as 20 minutes. :thinking:

**Comment by rcurtin** [comment]
Wow, sorry to fail to respond to this one for so long.  @shrit it can take a decent amount of time for the website to build, because we actually have to build mlpack's Doxygen documentation, which can take a little while.  However the scripts that run the build drop the new website in place all in one command:

```
jekyll clean && \
    jekyll b -d tmp_site/ -b / && \
    ln -s /home/ryan/irclogs/freenode/mlpack/ tmp_site/irc/logs && \
    ln -s /home/jenkins-mlpack/workspace/blog/script/blog/doxygen tmp_site/gsocblog && \
    mkdir old_site/ && \
    mv "$1/"* old_site/ && \
    mv tmp_site/* "$1/" && \
    ln -s "$1/doc/$newest_version" "$1/doc/stable" && \
    rm -rf tmp_site old_site;
```

(That's from `_src/scripts/deploy-site.sh` in https://github.com/mlpack/mlpack.org.)  You can see that the last four lines are actually what deploys the website and it should be instantaneous.  (`$1` there is the destination directory for the deployed website.)
