### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by menkaur** [mlpack/mlpack#2389]
I'm trying to compile first example from the neural networks tutorial here https://www.mlpack.org/doc/mlpack-3.3.0/doxygen/anntutorial.html .

Here's my cmakelist.txt

> cmake_minimum_required (VERSION 3.8)
> 
> project ("test-cmake-project")
> 
> add_definitions(/ZI)#enable edit and continue
> add_definitions(/bigobj)
> 
> 
> add_executable (${PROJECT_NAME} 
> 	"test-cmake-project.cpp" 
> 	"test-cmake-project.h")
> 
> target_include_directories(${PROJECT_NAME} PRIVATE
> 	"G:\\boost\\boost_1_72_0" 
> 	"G:\\c++source\\armadillo-9.860.2\\include" 
> 	"G:\\c++source\\mlpack-3.3.0\\include",
> 	"G:\\c++ source\\ensmallen-master\\include")
> 
> target_link_libraries(${PROJECT_NAME} 
> 	"G:\\c++source\\lapack-build\\lib\\Debug\\blas.lib"
> 	"G:\\c++source\\lapack-build\\lib\\Debug\\lapack.lib"
> 	"G:\\c++source\\OpenBLAS\\build\\lib\\DEBUG\\openblas.lib"	
> 	"G:\\c++source\\armadillo-9.860.2\\Debug\\armadillo.lib"	
> 	"G:\\boost\\boost_1_72_0\\stage\\lib\\libboost_serialization-vc142-mt-gd-x64-1_72.lib"
> 	"G:\\boost\\boost_1_72_0\\stage\\lib\\libboost_program_options-vc142-mt-gd-x64-1_72.lib"
> 	"G:\\c++source\\mlpack-3.3.0\\Debug\\mlpack.lib" 
> 	)

The compilation fails with following error messages:

> -- Build files have been written to: D:/My Projects/test-cmake-project/out/build/x64-Debug
>   [1/1] cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\test-cmake-project.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MIB055~1\2019\ENTERP~1\VC\Tools\MSVC\1423~1.281\bin\Hostx64\x64\link.exe /nologo CMakeFiles\test-cmake-project.dir\test-cmake-project.cpp.obj  /out:test-cmake-project.exe /implib:test-cmake-project.lib /pdb:test-cmake-project.pdb /version:0.0  /machine:x64 /debug /INCREMENTAL /subsystem:console  G:\c++source\lapack-build\lib\Debug\blas.lib G:\c++source\lapack-build\lib\Debug\lapack.lib G:\c++source\OpenBLAS\build\lib\DEBUG\openblas.lib G:\c++source\vcpkg\installed\x64-windows\lib\armadillo.lib G:\boost\boost_1_72_0\stage\lib\libboost_serialization-vc142-mt-gd-x64-1_72.lib G:\boost\boost_1_72_0\stage\lib\libboost_program_options-vc142-mt-gd-x64-1_72.lib G:\c++source\mlpack-3.3.0\Debug\mlpack.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
>   FAILED: test-cmake-project.exe 
>   cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\test-cmake-project.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MIB055~1\2019\ENTERP~1\VC\Tools\MSVC\1423~1.281\bin\Hostx64\x64\link.exe /nologo CMakeFiles\test-cmake-project.dir\test-cmake-project.cpp.obj  /out:test-cmake-project.exe /implib:test-cmake-project.lib /pdb:test-cmake-project.pdb /version:0.0  /machine:x64 /debug /INCREMENTAL /subsystem:console  G:\c++source\lapack-build\lib\Debug\blas.lib G:\c++source\lapack-build\lib\Debug\lapack.lib G:\c++source\OpenBLAS\build\lib\DEBUG\openblas.lib G:\c++source\vcpkg\installed\x64-windows\lib\armadillo.lib G:\boost\boost_1_72_0\stage\lib\libboost_serialization-vc142-mt-gd-x64-1_72.lib G:\boost\boost_1_72_0\stage\lib\libboost_program_options-vc142-mt-gd-x64-1_72.lib G:\c++source\mlpack-3.3.0\Debug\mlpack.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
>   LINK Pass 1: command "C:\PROGRA~2\MIB055~1\2019\ENTERP~1\VC\Tools\MSVC\1423~1.281\bin\Hostx64\x64\link.exe /nologo CMakeFiles\test-cmake-project.dir\test-cmake-project.cpp.obj /out:test-cmake-project.exe /implib:test-cmake-project.lib /pdb:test-cmake-project.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console G:\c++source\lapack-build\lib\Debug\blas.lib G:\c++source\lapack-build\lib\Debug\lapack.lib G:\c++source\OpenBLAS\build\lib\DEBUG\openblas.lib G:\c++source\vcpkg\installed\x64-windows\lib\armadillo.lib G:\boost\boost_1_72_0\stage\lib\libboost_serialization-vc142-mt-gd-x64-1_72.lib G:\boost\boost_1_72_0\stage\lib\libboost_program_options-vc142-mt-gd-x64-1_72.lib G:\c++source\mlpack-3.3.0\Debug\mlpack.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\test-cmake-project.dir/intermediate.manifest CMakeFiles\test-cmake-project.dir/manifest.res" failed (exit code 1120) with the following output:
>      Creating library test-cmake-project.lib and object test-cmake-project.exp
> D:\My Projects\test-cmake-project.cpp.obj : error LNK2019: unresolved external symbol sgesdd_ referenced in function "void __cdecl arma::lapack::gesdd<double>(char *,int *,int *,double *,int *,double *,double *,int *,double *,int *,double *,int *,int *,int *)" (??$gesdd@N@lapack@arma@@YAXPEADPEAH1PEAN1221212111@Z)
> D:\My Projects\test-cmake-project.cpp.obj : error LNK2019: unresolved external symbol dgesdd_ referenced in function "void __cdecl arma::lapack::gesdd<double>(char *,int *,int *,double *,int *,double *,double *,int *,double *,int *,double *,int *,int *,int *)" (??$gesdd@N@lapack@arma@@YAXPEADPEAH1PEAN1221212111@Z)
> D:\My Projects\test-cmake-project.cpp.obj : error LNK2019: unresolved external symbol sgesv_ referenced in function "void __cdecl arma::lapack::gesv<double>(int *,int *,double *,int *,int *,double *,int *,int *)" (??$gesv@N@lapack@arma@@YAXPEAH0PEAN00100@Z)
> D:\My Projects\test-cmake-project.cpp.obj : error LNK2019: unresolved external symbol dgesv_ referenced in function "void __cdecl arma::lapack::gesv<double>(int *,int *,double *,int *,int *,double *,int *,int *)" (??$gesv@N@lapack@arma@@YAXPEAH0PEAN00100@Z)
> D:\My Projects\test-cmake-project.cpp.obj : error LNK2019: unresolved external symbol cgesv_ referenced in function "void __cdecl arma::lapack::gesv<double>(int *,int *,double *,int *,int *,double *,int *,int *)" (??$gesv@N@lapack@arma@@YAXPEAH0PEAN00100@Z)
> D:\My Projects\test-cmake-project.cpp.obj : error LNK2019: unresolved external symbol zgesv_ referenced in function "void __cdecl arma::lapack::gesv<double>(int *,int *,double *,int *,int *,double *,int *,int *)" (??$gesv@N@lapack@arma@@YAXPEAH0PEAN00100@Z)
> D:\My Projects\test-cmake-project.cpp.obj : error LNK2019: unresolved external symbol sposv_ referenced in function "void __cdecl arma::lapack::posv<double>(char *,int *,int *,double *,int *,double *,int *,int *)" (??$posv@N@lapack@arma@@YAXPEADPEAH1PEAN1211@Z)
> D:\My Projects\test-cmake-project.cpp.obj : error LNK2019: unresolved external symbol dposv_ referenced in function "void __cdecl arma::lapack::posv<double>(char *,int *,int *,double *,int *,double *,int *,int *)" (??$posv@N@lapack@arma@@YAXPEADPEAH1PEAN1211@Z)
> D:\My Projects\test-cmake-project.cpp.obj : error LNK2019: unresolved external symbol cposv_ referenced in function "void __cdecl arma::lapack::posv<double>(char *,int *,int *,double *,int *,double *,int *,int *)" (??$posv@N@lapack@arma@@YAXPEADPEAH1PEAN1211@Z)
> D:\My Projects\test-cmake-project.cpp.obj : error LNK2019: unresolved external symbol zposv_ referenced in function "void __cdecl arma::lapack::posv<double>(char *,int *,int *,double *,int *,double *,int *,int *)" (??$posv@N@lapack@arma@@YAXPEADPEAH1PEAN1211@Z)
> D:\My Projects\test-cmake-project.exe : fatal error LNK1120: 10 unresolved externals
>   ninja: build stopped: subcommand failed.

What am I missing?

I'm compiling with Visual Studio 2019

**Comment by birm** [comment]
Hi, thanks for sharing your issue. This looks similar to #1607 to me, and the unresolved symbols all seem to be in lapack (openblas).
So, to copy a comment "Is your code linking against mlpack, Armadillo, or LAPACK and BLAS? You could look through the build configuration for when you compiled mlpack and make sure you are linking against the same set of libraries."
You may also find [this guide to mlpack and windows](https://www.mlpack.org/doc/mlpack-git/doxygen/build_windows.html) useful.
(Also, it's a fair bit easier to develop c++ with linux, but we still do want to support windows)

**Comment by menkaur** [comment]
I've made doubly sure that they are the same. In mlpack solution, the mlpack.lib compiled successfully, but, now that I look at it, the executable projects (like mlpack_emst) fail to compile with the same errors. I've checked the LAPACK and BLAS projects, and it seems to be compiled for the same environment (Debug, x64) that mlpack targets

Do you know of any tools that would help me diagnose what is the problem?

**Comment by birm** [comment]
I don't want to leave you hanging, so I'll give you what may approach something useful:
You may find the model zoo's cmakelists useful as a reference at the least. https://github.com/mlpack/models/blob/master/CMakeLists.txt
It's often easier to use the find_package if you can, and if it will work.

**Comment by rcurtin** [comment]
@menkaur it seems to me like `mlpack_emst` is maybe not linking against LAPACK and BLAS?  Is there any chance you can check the Visual Studio linker configuration to see what's happening?

Another idea, potentially a workaround, is to specify the exact path to the OpenBLAS library in the CMake configuration variable `_ARMADILLO_LIBRARIES`.  Maybe that will help?  I'm not sure---if you're willing to give it a shot, let us know what you find.

**Comment by menkaur** [comment]
I've been thinking. When you guys are making the vpkg distro, do you compile on windows or on linux? Because, if you compile on linux, I can just work around the problem and compile it there, and copy the files to windows afterwards (If you do compile on linux, can you share the command line?)

**Comment by rcurtin** [comment]
Hey @menkaur, actually, we don't provide the vcpkg distro, that's done in the vcpkg repository.  You could look at how it's done there.  I do know that the Julia packaging scripts cross-compile from Linux; here's the script: https://github.com/JuliaPackaging/Yggdrasil/blob/master/M/mlpack/build_tarballs.jl

Hopefully that's helpful---I know that there's a lot of other tooling going on in that script, so you would have to adapt it heavily to your case.  At the end of the day it's just a bash script, so, you can follow the code path for when `${target}` is `*mingw*` and I think that it will work with some amount of adaptation.
