### ISSUE TITLE
Possible bug for GMMTest

### ISSUE THREAD

**Issue by bisakhmondal** [mlpack/mlpack#2393]
I am facing a strange issue every time while running the `build/bin/mlpack_test` executable (complete module), an error from GMMTest (test for the Gaussian Mixture Model) suite is getting popped up. 
But this is not the case when I am running the test cases for GMMTest suite only. The test case `DiagonalGMMTrainEMMultipleGaussiansWithProbability` involves dealing with random numbers. This may be the cause, but not sure why it's working in solo execution.
![Screenshot from 2020-05-03 12-38-19](https://user-images.githubusercontent.com/41498427/80908232-e99a1e80-8d3b-11ea-9cc8-2bc277968866.png)

**Not sure if the problem is specifically happening only to my system after the latest build. But it's happening each and every time.

As a solution maybe we can increase the percentage tolerance from 10% to say 12 or 13%, or maybe that's not required at all as the tests for the PRs are passing.
https://github.com/mlpack/mlpack/blob/c3fb2eb48fa4a546cfc4e6ae31b11ffbb795fb9a/src/mlpack/tests/gmm_test.cpp#L1034-L1038

**Comment by kartikdutt18** [comment]
Hey, Does this occur on master branch?

**Comment by bisakhmondal** [comment]
Let me check. This is the build, before the final push of #2268.

**Comment by kartikdutt18** [comment]
> Let me check. This is the build, before the final push of #2268.

My master is the same as the one you mentioned. I ran the test a couple of hours back, No test failed. The branch is the same as the branch in #2387

**Comment by KimSangYeon-DGU** [comment]
@bisakhmondal @kartikdutt18 Thanks for the reporting and it's understandable as the test is stochastic. I remember each `DiagonalGMM` test went through about more than 3,000 trials and passes with the random seed (`mlpack::math::RandomSeed(std::time(NULL))`). Despite those efforts, it seems to be failed sometimes.

I think your solution works and would it be better to make the 3 diagonal distributions far more distinguishable each other including your solution?

**Comment by kartikdutt18** [comment]
Hey @KimSangYeon-DGU, thanks for the input. I'll try one thing, I will run the `GMMTest` like a 1000 times and see if it fails. Mainly because I haven't gotten it to fail on my machine yet in a couple of runs.

**Comment by KimSangYeon-DGU** [comment]
@kartikdutt18 Thanks for letting me know. @bisakhmondal After increasing the tolerance, was the test passed?

**Comment by bisakhmondal** [comment]
@kartikdutt18 Yep I have run the build on the master branch. Still it's failing. As a reference 
![Screenshot from 2020-05-03 17-02-55](https://user-images.githubusercontent.com/41498427/80913255-e9f8e080-8d60-11ea-9ccd-96746afd8679.png)

@KimSangYeon-DGU after increasing the tolerance to `13%` it's working fine now.
![Screenshot from 2020-05-03 17-13-39](https://user-images.githubusercontent.com/41498427/80913325-74414480-8d61-11ea-9ffd-5fe18bf63d58.png)

Thanks guys.

**Comment by KimSangYeon-DGU** [comment]
@bisakhmondal Can you open a PR?

**Comment by bisakhmondal** [comment]
Ya Sure.

**Comment by kartikdutt18** [comment]
So I ran this :
```
for i in {1..1000}
do sudo ./bin/mlpack_test -t GMMTest;
done;
```
I didn't get any error in 1000 iterations. I am using OSX. As far as I can tell azure pipeline also isn't showing any failure. I don't mind increasing the tolerance but I am unable to reproduce this issue.
@bisakhmondal Do you mind sharing your OS details. Thanks.

**Comment by bisakhmondal** [comment]
Hi @kartikdutt18, magically `./bin/mlpack_test -t GMMTest` this works fine in my system too :)) as I said in the issue description. The issue arises while running the complete test modules.

Sure, I am using `Ubuntu 19.10 eoan release`.

**Comment by kartikdutt18** [comment]
Hmm, Let me change that. If that's the case that's definitely strange. Let do 5 iterations.

**Comment by bisakhmondal** [comment]
Exactly. Very strange.

**Comment by KimSangYeon-DGU** [comment]
@kartikdutt18 When running tests, did you  put the code `mlpack::math::RandomSeed(std::time(NULL))` on the top of the test by any chance?

**Comment by kartikdutt18** [comment]
>  did you put the code mlpack::math::RandomSeed(std::time(NULL)) on the top of the test by any chance?

Ahh, I didn't, I just rebased my master and ran the above command. Currently I am running this : 
```
for i in {1..5}
do sudo ./bin/mlpack_test;
done;
```
Did I miss something?

**Comment by kartikdutt18** [comment]
In a single run, the test still doesn't fail on OSX, maybe it's only associated with linux?
Will update with the rest of the iterations in roughly an hour.

**Comment by KimSangYeon-DGU** [comment]
Ok, if we run one test many times and didn't set the seed to random, the test will use the same seed, so it resulted in duplication.

**Comment by kartikdutt18** [comment]
> Ok, if we run one test many times and don't set the seed to random, the test will use the same seed in stochatic test, so it resulted in duplication

Ahh, sorry I missed that. That makes sense. Let me make the changes.
