### ISSUE TITLE
How to gracefully exit agent training?

### ISSUE THREAD

**Issue by menkaur** [mlpack/mlpack#2397]
I've been playing with the CartPole example. Here's the modified code:

    
    std::ofstream myfile;
    myfile.open("history.txt");
	
	//mlpack::ann::
    // Set up the network.
    FFN<MeanSquaredError<>, GaussianInitialization> model(MeanSquaredError<>(), GaussianInitialization(0, 0.01));
    model.Add<Linear<>>(4, 128);
    model.Add<LeakyReLU<>>();
    model.Add<Linear<>>(128, 128);
    model.Add<LeakyReLU<>>();
    model.Add<Linear<>>(128, 128);
    model.Add<LeakyReLU<>>();
    model.Add<Linear<>>(128, 2);

    AggregatedPolicy<GreedyPolicy<CartPole>> policy({ GreedyPolicy<CartPole>(0.7, 5000, 0.1),
                                                     GreedyPolicy<CartPole>(0.7, 5000, 0.01),
                                                     GreedyPolicy<CartPole>(0.7, 5000, 0.5) },
        arma::colvec("0.4 0.3 0.3"));

    const int stepLimit = 300;
	
    TrainingConfig config;
    config.StepSize() = 0.01;
    config.Discount() = 0.9;
    config.TargetNetworkSyncInterval() = 100;
    config.ExplorationSteps() = stepLimit;
    config.DoubleQLearning() = true;
    config.StepLimit() = stepLimit;

    OneStepQLearning<CartPole, decltype(model), ens::VanillaUpdate, decltype(policy)>
        agent(std::move(config), std::move(model), std::move(policy));

    arma::vec returns(100, arma::fill::zeros);
    size_t position = 0;
    size_t episode = 0;
    int executionPosition = -1;

    auto measure = [&](double episodeReturn)
    {
        returns[position++] = episodeReturn;
        position = position % returns.n_elem;
        episode++;

        auto mean = arma::mean(returns);
    	
        if (mean>stepLimit*.95&&episode> returns.n_elem)
        {
            std::cout << "returning because mean=" << mean << std::endl;
            return true;
        }

        std::cout << "["<< executionPosition <<"," << episode<<"]"
            << "; Episode Return: " << episodeReturn
            << "; Average Return: " << mean 
	    	<<std::endl;

        myfile << episodeReturn << std::endl;
        myfile.flush();
        return false;
    };

    agent.Train(measure);
    myfile.close();`

The idea behind it was running the training until majority of items in the sample will balance for max steps. It turns out, when running training in this manner, something else is happening: for around the first 6000 iterations, the model keeps gradually improving, and than improvement stops and it oscillates at low values (can be seen by studying the content of `history.txt`).

My question is - is this expected behaviour?  What can be done to make the model keep gradually improving? Is there a better way to stop training the agent?

Update:
I'm having this issue with mlpack installed with vcpkg on Windows. 
When I'm running latest version of the software on Linux, it doesn't seem to have the same issue. 

I still am looking for a suggestion about what is a graceful way to exit the training

**Comment by zoq** [comment]
We will have to look into the windows issue, about the exit strategy, what about checking the reward? See https://github.com/mlpack/mlpack/blob/6a64926e4436bcb799d0e655190fbdd5d76e5019/src/mlpack/tests/async_learning_test.cpp#L81 for an example?

**Comment by menkaur** [comment]
Yes, this is approximately what I'm doing
