### ISSUE TITLE
MLPACK failed due to link error on MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [mlpack/mlpack#2401]
MLPACK failed due to link error with MSVC on windows. I use latest version aa2f59f. Could you please help look at this? Thanks a lot!

You can repro this issue as the steps below:

1. git clone https://github.com/mlpack/mlpack D:\MLPACK\src
2. it dependent armadillo and OpenBlas, put them to D:\MLPACK\external\
3. open a VS 2017 amd64 command prompt as admin and browse to D:\MLPACK
4. mkdir build_x64 && pushd build_x64
5. cmake -G "Visual Studio 16 2019" -A x64 -DBLAS_LIBRARY=D:\MLPACK\build_x64..\external\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a -DLAPACK_LIBRARY=D:\MLPACK\build_x64..\external\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a -DARMADILLO_INCLUDE_DIR=D:\MLPACK\build_x64..\external\armadillo-9.200.4\include -DARMADILLO_LIBRARY=D:\MLPACK\build_x64..\external\armadillo-9.200.4\lib\armadillo.lib -DBOOST_INCLUDEDIR=C:\boost_1_67_0\x64 -DBOOST_LIBRARYDIR=C:\boost_1_67_0\x64\lib64-msvc-14.1 -DDEBUG=OFF -DPROFILE=OFF ..\src
6. msbuild /m /p:Configuration=Release;Platform=x64;PreferredToolArchitecture=x64 mlpack.sln /t:Rebuild

build log: [mlpack_build.log](https://github.com/mlpack/mlpack/files/4621418/mlpack_build.log)

Failures:
   Creating library F:/mlpack/build_amd64/Release/mlpack_emst.lib and object F:/gitP/mlpack/mlpack/build_amd64/Release/mlpack_emst.exp
emst_main.obj : error LNK2001: unresolved external symbol dasum_
emst_main.obj : error LNK2001: unresolved external symbol dnrm2_
emst_main.obj : error LNK2001: unresolved external symbol dgesdd_
F:\mlpack\build_amd64\Release\mlpack_emst.exe : fatal error LNK1120: 3 unresolved externals

**Comment by zoq** [comment]
This looks similar to: https://github.com/mlpack/mlpack/issues/881 maybe you can test: https://github.com/mlpack/mlpack/issues/881#issuecomment-282397637?

**Comment by QuellaZhang** [comment]
Thanks @zoq , we have added BLAS lib in cmake build commad line. Recently we updated the sha of MLPACK, the old commit 2e2e0f5 is work fine on the same version of MSVC, if you have any other suggestions please let me know, thanks.

**Comment by zoq** [comment]
Sorry for the slow response, just to see if I get this right, you say the version 2e2e0f5 works fine, but the current master branch is not? If that's the case let me see if I can find a change in the history that might have caused an issue like this.

**Comment by rcurtin** [comment]
What happens if you specify `_ARMADILLO_LIBRARIES=/path/to/openblas.lib` as a CMake variable?  i.e. `cmake ... -D_ARMADILLO_LIBRARIES=/path/to/openblas.lib ...`?  Does that fix the issue?  I think, if so, I know what the fix needs to be. :+1:

**Comment by QuellaZhang** [comment]
Thank you very much, @zoq @rcurtin , I also find the version 97fd462a98a66e52e41720f9954f2dd7d901c466, I have updated the cmake commands, now MLPACK is clean on MSVC.

**Comment by birm** [comment]
@rcurtin before this stales and is lost to time, what fix are you proposing?

**Comment by rcurtin** [comment]
@birm good point, I didn't actually specify what I meant.  I think that we could just modify `FindArmadillo.cmake` such that when the compiler is MSVC, all of the support libraries are automatically added to `ARMADILLO_LIBRARIES` (even if `ARMA_USE_WRAPPER` is set!), and this would cause the problem @QuellaZhang had to not occur.
