### ISSUE TITLE
access weight and bias of linear layer

### ISSUE THREAD

**Issue by mrityunjay-tripathi** [mlpack/mlpack#2403]
There are getters and setters for `bias` and for the concatenated form of `weight` and `bias` i.e. `weights` in Linear layer (`linear.hpp`). But there is no such method for accessing `weight`. I can get the `weight` from `weights` but that would only increase the lines of code or make the expression complex. Is this something intentional? 

I require to initialize the weight of that particular layer with different initialization rule than that of the network's. Is there any other way to do this?

**Comment by zoq** [comment]
Some examples to modify the weights: https://gist.github.com/zoq/3f4d43efed7dc76cc600bb7674519994

We can add a method to modify the weights without the bias, if that makes things easier.

**Comment by mrityunjay-tripathi** [comment]
>Some examples to modify the weights: https://gist.github.com/zoq/3f4d43efed7dc76cc600bb7674519994

Hey @zoq, the `Initialize` method takes `arma::Mat<>` object. But this method returns a `arma::subview<>` object.
So, when I try to initialize weights using `XavierInitialization` (say), it doesn't compile.
```
#include <mlpack/core.hpp>
#include <mlpack/methods/ann/layer/linear.hpp>
#include <mlpack/methods/ann/init_rules/glorot_init.hpp>

using namespace mlpack;
using namespace mlpack::ann;

int main()
{
  size_t inSize = 4, outSize = 4;
  Linear<>* linear = new Linear<>(inSize, outSize);
  XavierInitialization().Initialize(linear->Parameters().submat(0, 0, inSize * outSize, 0), outSize, inSize);
  linear->Parameters().print();
}
```
This code returns error -
```
mlpack_ann.cpp: In function ‘int main()’:
mlpack_ann.cpp:12:108: error: no matching function for call to ‘mlpack::ann::GlorotInitializationType<true>::Initialize(arma::subview<double>, size_t&, size_t&)’
   XavierInitialization().Initialize(linear->Parameters().submat(0, 0, inSize * outSize, 0), outSize, inSize);

```

>We can add a method to modify the weights without the bias, if that makes things easier.

Yeah, I also think it would be better to add a setter method to access `weight`.
