### ISSUE TITLE
Trouble installing / linking mlpack on Windows

### ISSUE THREAD

**Issue by kartikdutt18** [mlpack/mlpack#2409]
Hey everyone,
I followed the following steps to install mlpack :

The complete file can be found [here](https://github.com/mlpack/models/blob/2dcebdd3d5628525d473d3c0f7418be5511e24ff/.ci/windows-steps.yaml)
```
cmake $(CMakeGenerator) `
     $(CMakeArgs-mlpack) `
     -DBLAS_LIBRARIES:FILEPATH=$(Agent.ToolsDirectory)\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a `
     -DLAPACK_LIBRARIES:FILEPATH=$(Agent.ToolsDirectory)\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a `
     -DARMADILLO_INCLUDE_DIR="..\..\armadillo-8.400.0\include" `
     -DARMADILLO_LIBRARY="..\..\armadillo-8.400.0\Release\armadillo.lib" `
     -DBOOST_INCLUDEDIR=$(Agent.ToolsDirectory)\boost.1.60.0.0\lib\native\include `
     -DBOOST_LIBRARYDIR=$(Agent.ToolsDirectory)\boost_libs `
     -DBUILD_JULIA_BINDINGS=OFF `
     -DCMAKE_BUILD_TYPE=Release ..
'mlpack/build/*.sln'
```
In the Cmake mlpack was found and all other libraries required were found. However I am still facing this [error](https://dev.azure.com/mlpack/mlpack/_build/results?buildId=1897&view=logs&j=9bb75cf0-500a-52c4-dbba-9c305edd1534&t=a4060360-b178-58da-4c70-0da5e743f9b0&l=43) : 
```
 Cannot open include file: 'mlpack/core/data/scaler_methods/min_max_scaler.hpp': No such file or directory
```

The Cmake file can be found [here](https://github.com/mlpack/models/blob/2dcebdd3d5628525d473d3c0f7418be5511e24ff/CMakeLists.txt)
Kindly help me with this, I have spent last couple of days trying to fix this. I did make some progress but I am stuck at this now.
Thanks a lot,
Regards.

**Comment by Yashwants19** [comment]
Hey @kartikdutt18 I am not sure, but do we are including the mlpack header properly [here](https://github.com/mlpack/models/blob/2dcebdd3d5628525d473d3c0f7418be5511e24ff/.ci/windows-steps.yaml#L106)? I think so it must be `..\mlpack\build\include`.

**Comment by kartikdutt18** [comment]
Thanks @Yashwants19, I'll give it a try and Get back to you shortly.

**Comment by kartikdutt18** [comment]
Hey @Yashwants19, That did change the error, Now this is the error
```
boost_unit_test_framework-vc140-mt-1_60.lib
(boost_unit_test_framework-vc140-mt-1_60.dll)(0,0): 
Error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'
```

I saw that the boost files (x64) are copied to build folder of mlpack so I copied them to my build folder as well. So I did that but that didn't help. Sorry, I am novice with windows. Could I trouble you with this error as well?
This is the error link on azure [pipeline](https://github.com/mlpack/models/pull/3/checks?check_run_id=682931198).
Regards.

**Comment by zoq** [comment]
` Cannot open include file: 'mlpack/core/data/scaler_methods/min_max_scaler.hpp': No such file or directory`

Looks like `scaler_methods` is missing here:

https://github.com/mlpack/mlpack/blob/4f68502270b1dc49d0ca1db69bdd8ae92a1cade7/src/mlpack/core/data/CMakeLists.txt#L44-L48

**Comment by zoq** [comment]
I'll comment about the architecture issue on the PR itself.

**Comment by kartikdutt18** [comment]
> `Cannot open include file: 'mlpack/core/data/scaler_methods/min_max_scaler.hpp': No such file or directory`
> 
> Looks like `scaler_methods` is missing here:
> 
> https://github.com/mlpack/mlpack/blob/4f68502270b1dc49d0ca1db69bdd8ae92a1cade7/src/mlpack/core/data/CMakeLists.txt#L44-L48

I'll make a PR for this thanks.

**Comment by jeffin143** [comment]
> I'll make a PR for this thanks.

Done
