### ISSUE TITLE
Can't use optimizers

### ISSUE THREAD

**Issue by Razarabi** [mlpack/mlpack#2418]
Hello!

I am unable to include any optimizers from mlpack
mlpack/core/optimization does not exist. I installed via VSCPKG and everything installed and linked just fine. All other mlpack files ive included in the project work fine as well. Is there an error in the installation via VSCPKG or am I not looking in the right place? 

Thanks!

**Comment by kartikdutt18** [comment]
Hello @Razarabi,
Could you also please share the mlpack version. mlpack started using [ensmallen](https://github.com/mlpack/ensmallen) for optimization process and removed optimizers from mlpack/core. The latest version of mlpack should automatically install ensmallen. You can simply include optimizers by adding the following line to the top : 
```
#include <ensmallen.hpp>
```
and using ensmallen namespace. 
Here is a code snippet that works:
```
    // Set parameters for the Adam optimizer.
    ens::Adam optimizer(
        STEP_SIZE, // Step size of the optimizer.
        BATCH_SIZE, // Batch size. Number of data points that are used in each iteration.
        0.9, // Exponential decay rate for the first moment estimates.
        0.999, // Exponential decay rate for the weighted infinity norm estimates.
        1e-8, // Value used to initialise the mean squared gradient parameter.
        MAX_ITERATIONS, // Max number of iterations.
        1e-8, // Tolerance.
        true);
```
We can train a model using:
```
 model.Train(trainX, trainY,  optimizer)
```
Information about optimizers can be found [here](https://github.com/mlpack/ensmallen/tree/master/doc) and some examples in mlpack that use ensmallen can be found in [examples repo](https://github.com/mlpack/examples). 
Regards.

**Comment by Razarabi** [comment]
Okay! Got it working thank you!

**Comment by kartikdutt18** [comment]
Awesome!
