### ISSUE TITLE
Discussion: revamp bindings to a train/predict-type interface?

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#2421]
This came up in the video chat discussion today and @zoq suggested that I write it down, which is definitely a good idea, to gather comments and thoughts about the idea.

When we originally made the command-line executables, it made sense to try and stuff as much functionality as possible into each executable.  This is because in the command-line setting, every time we call the binding it will incur a runtime loading penalty for any models or datasets.  So, e.g., if I use `mlpack_logistic_regression` to build a model and then predict with it as *two separate calls*, it incurs a runtime penalty for loading the data/model:

```sh
mlpack_logistic_regression -t train_data.csv -l train_labels.csv -M model.bin -v
# We have to pay the cost of loading train_data.csv a second time for this call...
mlpack_logistic_regression -m model.bin -T train_data.csv -P probabilities.csv -v
```

However, from any other language, this problem doesn't actually exist, as everything is loaded in memory.  So, the following Python code would *not* load the training data a second time (or copy it):

```py
// Not sure if I remember how to write Python right... I think this is right...
from mlpack import logistic_regression
model = logistic_regression(training=train_data, labels=train_labels)["model"]
probabilities = logistic_regression(input_model=model, test=train_data)["probabilities"]
```

That same situation exists not just for Python, but also for Julia, Go, Java, and soon R.  So suddenly, the command-line bindings are the odd ones out.

So, basically, to languages like Python and Julia and others, we are providing a "one function" interface where that one function does everything---you call `mlpack.logistic_regression()` to train the model, but then you also call it to compute class predictions and also class probabilities.  From the perspective of these other languages, this doesn't make much sense.  A Python-native library for machine learning will generally provide a `fit()` and `predict()` function (plus `predict_proba()` perhaps) for each learner, and so folks trying to use mlpack's interface may find it a little bit strange and alien.  In fact, this structure means that it's not trivial to bind mlpack to MLJ.jl in Julia (#2388).

In fact, we actually have a couple sets of bindings that already operate like this---`gmm_train()`/`gmm_probability()`/`gmm_generate()` and `hmm_train()`/`hmm_viterbi()`/`hmm_loglik()`/`hmm_generate()`.  However that is certainly not the majority usage.

So, a couple of questions for discussion:

 1. Does it make sense to revamp the mlpack bindings into separate bindings for model training and model prediction?

 2. If so, what restrictions can we place on the bindings so that they fit this format?  i.e. only one output parameter?

 3. What do we do with bindings that don't fit that format?  Do we need a couple more abstractions?  e.g., NMF doesn't fit cleanly into train/predict... it's just a transformation.

 4. Is there a way that we could manage to avoid the multiple loading cost issue for the command-line bindings by somehow "combining" bindings that are marked as "grouped" in the CMake configuration or something?

 5. If we could "group" bindings together in CMake, could this then be used to generate, e.g., a Python class for each set of bindings?  So we could actually have a `RandomForest` object that isn't just an opaque pointer but actually has functions that return something?

 6. ...how would we restructure our binding documentation?

Anyway, the purpose of this issue is just to start discussion.  I certainly don't have time at the moment to devote to the issue, but maybe in the future.  I'd be happy to help out if anyone else wanted to spearhead the effort, of course!  Given the quick restructuring did as a group in the examples/models repository after a discussion, I wonder if we can't pull off something awesome here as a group too. :)

**Comment by Yashwants19** [comment]
Hi @rcurtin, This is looking interesting, do you have idea/vision regarding this, If you want then I can help in this revamping, I might am not able devote 100% till Feb, as I will start my preparation for my Mtech's entrance, but sure I definitely will try to devote some my time here. :)

**Comment by rcurtin** [comment]
Hey @Yashwants19, good luck on the Mtech entrance!  I am sure it will go well.

So I think there are several issues that would need to be figured out.  But let's consider Python.  The general idea would be that instead of generating these standalone functions `gmm_train()`, `gmm_generate()`, `gmm_probability()`, we would have some way to "group" these bindings so that we could generate a Python *class* `mlpack.GMM` which internally contained the functions `train()`, `generate()`, and `probability()`, each of which would call the bindings defined in `gmm_train_main.cpp`, `gmm_generate_main.cpp`, and `gmm_probability_main.cpp`.  So making that work could be a first step.  For Julia and Go, we could do the same thing.  (For R, I'm not sure, I don't know enough about R to know if that makes sense.)  For the command-line, probably the "group" could be ignored and things could be just like they are now.  Or maybe we could think of some way to "combine" bindings for the command-line.

But then the second part would be to split other bindings that have multiple functionalities.  So, for instance, `mlpack_logistic_regression` does *two* things: it trains a model, and it also predicts with it.  We could split this into two bindings: `train` and `predict`, and then if we have a "grouping" of these two, we can get Python classes like `mlpack.LogisticRegression` that have a `train()` and `predict()` function.

Anyway there is a lot of design work that would need to be done.  But, if we were able to do this, it would give us a much more "native" interface in other languages, which would really help with some of the drawbacks of using mlpack in other languages.  If you have better ideas than what I wrote above, feel free to propose them!  Right now this is a vague idea. :)  (It could also, perhaps, be a GSoC project next year or something.)

**Comment by NippunSharma** [comment]
Hi @rcurtin @zoq @Yashwants19 , any chance that this will be included in GSoC 2021 projects ? I am planning to apply this time and I am making myself more familiar with the binding system of mlpack so that I can make some good contributions to the bindings.
