### ISSUE TITLE
Some versions of Doxygen don't like current unnamed size_t params

### ISSUE THREAD

**Issue by birm** [mlpack/mlpack#2428]
#### Issue description
For at least doxygen >= 1.8.17, an unnamed size_t param returns a warn/err which is resolved by pretending the param is literally called "size_t".

So, as far as I can tell, it's only concerned with size_t params, which it thinks are called size_t.

See https://github.com/doxygen/doxygen/issues/7818

**Comment by birm** [comment]
I believe that #2429 fixed all of the doxygen issues in 1.8.17 EXCEPT for this one, so I think this is all that is blocking doxygen version upgrades.

**Comment by rcurtin** [comment]
:+1: thanks for looking into this.  Kind of a strange issue!  The only other thing about doxygen version upgrades is these scripts: https://github.com/mlpack/mlpack.org/tree/master/_src/doxygen

See specifically the `.py` files in there---these are used as a postprocessing step on the Doxygen HTML output.  Sometimes versions of Doxygen significantly change the HTML output, and so if we do upgrade Doxygen (which I'm happy to do on mlpack.org) we would need to make sure that those scripts still worked right.

(You can test by checking out the (very large) mlpack.org repository and building the website from scratch with `_src/scripts/build-website-from-scratch.sh`, then `jekyll s`.  I *think* that will work?)

**Comment by kolbma** [comment]
It starts with doxygen **1.8.14**.

But the `@param size_t (rank) Rank of factorization.` doesn't work with **1.8.14**.  
It misses a parameter named size_t. So different to 1.8.17 or 1.8.19.
