### ISSUE TITLE
Modifying maxpooling.hpp to access poolingIndices

### ISSUE THREAD

**Issue by iamshnoo** [mlpack/mlpack#2439]
The *```maxpooling```* layer has a private member called *```poolingIndices```* of the type *```std::vector<arma::cube>```*. Currently, the forward function returns only the maxpooled values.

I am writing an Unpooling layer, which needs as input, the output of the maxpool layer and also the corresponding poolingIndices. Currently, there is no way to access the indices outside the max pool layer.

My primary idea was to simply write an accessor method for the poolingIndices and then pass it in as a parameter in the constructor of the forward function. The only problem is that doesn't look too good. ***```std::vector<arma::cube> poolingIndices```*** seems like a pretty complicated data type for the average user to handle. So, using this data type as a return type in the accessor from maxpool and then passing this data type as a constructor parameter for unpooling is probably the least desirable way of doing this.

I am looking for alternative ways of modifying the maxpooling layer so that I can access its' private member poolingIndices more smoothly outside of it.

**Comment by zoq** [comment]
What about you pass the layer to the forward function and use the accessor method inside the method itself, that way you hide the complexity. Let me know what you think.

**Comment by sreenikSS** [comment]
@iamshnoo @zoq I was thinking of a different approach. Firstly summarizing the respective layers:
**maxpool** - takes a **4x4 input** and gives a **2x2 output** using the **max values** of each quadrant.
**meanpool** - does a similar thing.
**unpool** - takes a **2x2 input** (which is essentially the max values of each quadrant) and pads it with **zeroes** to make it **4x4**, basically making it somewhat the inverse of maxpool.
Someday some research may come out with some other sort of similar pooling too.

The common factor in these is computing **poolingIndices** depending on whether it is max/mean/etc. What do you think about keeping a **separate util function** under the util directory that just does the pooling operation. Its constructor can takes a parameter called **type** which can take values like *max* and *mean* and return the respective matrix.

This util function can be used by all of these *pooling layers* which might be a better representation of dependability and code re-usage.

Let me know what you guys think.

Also, if this idea does not sound right and no change is done to the maxpool or meanpool layer,  I think a small change still needs to be made due to an inconsistency in naming the pooling operation. It is called **Pooling()** in maxpool and **PoolingOperation()** in meanpool.

**Comment by iamshnoo** [comment]
> What about you pass the layer to the forward function and use the accessor method inside the method itself

This sounds good to me, but I am not very sure how to implement this. Could you point me to some example for how I might pass a layer to the Forward function of another? 

Sreenik's idea seems a bit more lengthy to implement, so, maybe we can avoid that for now and implement it later on?

**Comment by kartikdutt18** [comment]
> This sounds good to me, but I am not very sure how to implement this. Could you point me to some example for how I might pass a layer to the Forward function of another?

I might not have the right context, but Adaptive pooling uses forward function of maxPooling.

**Comment by iamshnoo** [comment]
> I might not have the right context, but Adaptive pooling uses forward function of maxPooling.

Yeah. I had a look at that. Don't think that is going to work for this case, because in Adaptive Pooling, we are creating a local object of maxpooling layer and then using the forward function from that object. 

But, here, imagine you have a network with a maxpool layer and a unpool layer one after the other. The forward pass of the network will first go through the forward pass of maxpool and calculate the maxpooled values and also the indices. What I want is that this output and the indices are passed to the unpooling layer somehow. So, using a local maxpooling object as done in adaptive pooling won't serve the purpose here, most probably.

**Comment by zoq** [comment]
Do you think wrapping the MaxPooling layer is an option, or just use the functions you need and implement them as part of the UnPooling Layer?

**Comment by iamshnoo** [comment]
To me, I see 4 options till now as listed below.

> wrapping the MaxPooling layer

This won't work. Adaptive pooling takes this approach and I have explained above why it won't work for this case.

> use the functions you need and implement them as part of the UnPooling Layer

Same case as above and won't work

> Using accessor methods directly 

Looks ugly. Will work.

> pass the layer to the forward function and use the accessor method inside the method itself

The idea seems right and should work. But I don't know how to pass a layer to the forward function of a different layer. Maybe you can help me with this?


Let me explain the situation with a concrete example to express it more clearly.

Consider that the input to MaxPool is this.
<pre>
Matrix A: 
   1.5000   1.7000   1.4000   1.3000
   2.0000   2.1000   1.8000   1.6000
   2.3000   1.9000   1.5000   1.4000
   2.2000   2.1000   1.6000   1.7000
</pre>

The Forward method of MaxPool will produce the output as this
<pre>
Matrix B: 
   2.1000   1.8000
   2.3000   1.7000
</pre>

The Forward method of MaxPool also calculates the pooling indices as this
<pre>
Matrix C:
    5.0000    9.0000
    2.0000   15.0000
</pre>

The Forward of UnPool will take Matrix B as **```input```** and Matrix C (most probably as a user provided parameter, either via a accessor method or via the constructor), to calculate this
<pre>
Matrix D:
        0        0        0        0
        0   2.1000   1.8000        0
   2.3000        0        0        0
        0        0        0   1.7000
</pre>

UnPool needs Matrix B and Matrix C in its Forward method calculations, and only Matrix C for its Backward method calculations. UnPool will obviously receive Matrix B as the **```input```**. But, it can't receive Matrix C, as that is a private member of MaxPool. Also, we can't calculate Matrix C within the UnPool layer itself, because Matrix A is not available within UnPool and we need Matrix A to calculate Matrix C.

So, either we need to pass the MaxPool layer to the UnPool layer's Forward method (but I don't know how this can be done) or we need accessor methods to access the indices from maxpool (ugly).

**Comment by kartikdutt18** [comment]
Also I if anyone likes to understand the issue a bit more they can take a look at [this issue](https://github.com/tiny-dnn/tiny-dnn/issues/612). I found it really helpful.

**Comment by iamshnoo** [comment]
Let's keep this open please!
