### ISSUE TITLE
What do you think of boost dependencies in mlpack?

### ISSUE THREAD

**Issue by shrit** [mlpack/mlpack#2440]
Hello everyone,

I am starting this issue to open a discussion considering mlpack dependencies. My GSOC project is to put mlpack on resource-constrained devices. As you know, mlpack binaries have a big foot-print. For example, `mlpack_knn` on my machine is 100MB when compiled with profiling and debugging symbols.
Luckily, there are several techniques can be used to reduce the size. Today after adding all possible flags that I know, the final binary size is about 4.7 MB for `mlpack_knn`.
The footprint of this binary is still considerable for embedded systems. I would say 0.7 MB is a good objective for an example like this one,
One might ask what is mlpack_knn made of? well, the answer is a set of segments, sections, and symbols. Boost:: serialization symbols are around 600KB (reported by profiler) when you statically link binaries. 
If you can compile everything statically you can do a simple test, you can comment on everything in `mlpack_knn `and leave only `PARAM_MODEL_IN`, this one is adding 1.5 MB to import only knn model.

Another disadvantage caused by serialization is the requirement for static linking. Therefore, for every new architecture to support, we have to re-cross compile `boost::serialization`. To give more details, in most embedded systems we have to cross-compile all dependencies that constitute a binary, which means that we need to download boost, (in this case, `serialization`, `program options`, and `tests`) and cross-compile them, then, we cross-compile OpenBLAS, and finally, cross-compile `mlpack` and its `cli-binding` and re-iterate this process for each architecture.
In essence,  `boost::serialization` is causing a major footprint and making the task more complicated.

A possible solution is to use libraries that : 
* Do not require linking (Header only)
* Have a very small impact on binary size

If we use headers library, we can remove boost dependencies that require linking (sure there still boost math and spirit.) We can add these libraries to CMake, and download them directly to `deps/` directory as it is done with ensmallen.

Possible replacement:
* `Boost::serialization`  --> [cereal](https://github.com/USCiLab/cereal)
* `Boost::program_options` --> [CLI11](https://github.com/CLIUtils/CLI11)
* `Boost::Test` -->  [Catch2](https://github.com/catchorg/Catch2)

If you have any other libraries that match the above criteria, do not hesitate in proposing them, or maybe we have to keep boost if there are some features provided by Boost that no other library provides,

So I open this issue to discuss possible replacement, also this is just an idea if you have any major binary size reducing techniques just tell me.

**Comment by conradsnicta** [comment]
During the very early development of Armadillo, Boost was also used.  However, I stripped it out for several reasons:
* Using Boost resulted in a much slower compilation, as there was a long chain of internally included headers.  Some of the headers were also quite large.  Almost all of the "extra" stuff was not directly relevant for the functionality that was used by Armadillo.
* Using Boost adds a massive sprawling dependency (150+ MB installed), which ends up becoming a barrier to entry. An extra step is required to make sure the user has Boost, has the correct version, that the headers can actually be found, and that the corresponding run-time libraries are available. People can put the headers and libraries in bizarre places, especially on systems where they don't have administrator access.
* Boost can't be trusted to keep a stable API.  On some enterprise systems there might be an ancient version of Boost installed.  This in turn requires workarounds within code to handle several versions of Boost.  Worst of all, an update to Boost can render previously perfectly working source code broken all of a sudden. All of this is an unnecessary pain and adds to the technical burden.

In the end I replaced the functionality from Boost by roughly equivalent functions written from scratch.  It must also be noted that a lot of the need for Boost goes away with functionality present in C++11, C++14, C++17, C++20, etc.

**Comment by shrit** [comment]
@conradsnicta Thank you for sharing your experience.
I agree, in the early development of a library or a project, Boost seems to accelerate the process of prototyping and early code, especially when we would like to test the project.
However, when the project starts to grow, a local implementation of these features resolve unexpected dependencies issues.

**Comment by shrit** [comment]
@rcurtin Considering `CLI11` it can be compiled into one header file and included in the distributed sources directly, exactly the same as catch.
Program options do not seem to be updated frequently in mlpack, if necessary we can check for updates on `CLI11` only on major version updates, or if we included a specific feature in program option.

**Comment by conradsnicta** [comment]
> * `boost::spirit`: this is used for the custom CSV parser that we use to handle files with non-numeric data.  When we wrote it we also found that it was faster for numeric-only data than Armadillo's CSV parser, but that was years ago and I have no idea if it's still true.  I don't have a problem removing the `boost::spirit` parser---so long as we can replace the functionality with something else equivalent (maybe a handwritten parser instead of a generated one).

I reworked the CSV loader in Armadillo 8.400, resulting in about a 2x to 3x speedup.  There are further refinements to CSV handling in later versions of Armadillo, including loading/saving of sparse matrices and complex dense matrices.

The Armadillo CSV loader is aimed for numeric data.  However, as of version 9.850, it can also handle non-numeric data in the first line (header) of the CSV file, by explicitly specifying that a header is present.  More details in the docs: http://arma.sourceforge.net/docs.html#save_load_mat

**Comment by rcurtin** [comment]
Awesome, nice to hear about the speedup!  I'm sure that our benchmarks are from before you did that.  For the header line, is there any support for automatically detecting the header?  i.e. if something that's parsed doesn't turn out to be numeric, then that first row is considered as the header?  I don't see anything suggesting that from the API, but maybe I missed something.

We do still have to be able to handle non-numeric data though, so probably a custom implementation for that part is necessary.  The `boost::spirit` parser is self-contained---it lives entirely in `src/mlpack/core/data/load_csv.hpp` and `src/mlpack/core/data/load_csv.cpp`, and the interface is pretty well-defined, making it easy to change whatever's used under the hood.

**Comment by steven-varga** [comment]
I am working on this [HDF5 C++ project](http://lightning-talk.h5cpp.org/) that supports armadillo. While armadillo C++  comes with good hdf5 implementation, there are differences in expressiveness and scalability. As an alternative to the built-in armadillo save/load operators one can write:
```c++
arma::vec V( {1.,2.,3.,4.,5.,6.,7.,8.});
h5::write( "arma.h5", "arma vec inside matrix", V,
   h5::current_dims{40,50}, h5::max_dims{40,H5S_UNLIMITED},
   h5::offset{5,0} ,h5::stride{3,5}, h5::block{2,4},
   h5::chunk{20,10} | h5::gzip{9} | h5::fill_value<double>{42.0});
```
The above [example](https://github.com/steven-varga/h5cpp/blob/master/examples/linalg/arma.cpp) creates an hdf5 container, writes `V` vector into a `40x50` matrix with default value `42` to some position, with scatter pattern where the target matrix is extendable, chunked and compressed.

The CRUD like templates support POSIX and MPI-IO operations, considers compact, contiguous and chunked layouts depending on the type/size of the object, provides full support for all property lists with attractive syntax.
 
In addition to homogeneous types, arbitrary POD types are supported with LLVM based introspection tool, the `h5cpp` compiler. From compiler assisted introspection, the header only library gravitates towards recent papers in C++ feature detection, reflection and linear algebra. On the long term the project aims to provide general non-intrusive scalable persistence for C++ containers as well as popular linear algebra systems such as armadillo C++.

C++TO orginised [online presentation](https://www.meetup.com/CPPTORONTO/events/270916922/) will be on Tuesday, June 30, 2020 6:30 PM to 8:30 PM EDT

**Comment by rcurtin** [comment]
Let's go ahead and close this---I think we're all agreed that we should remove boost dependencies where possible, and the work is underway with #2458 and #2459 and #2457 (and others). :+1:
