### ISSUE TITLE
Templating mlpack's data::Split.

### ISSUE THREAD

**Issue by kartikdutt18** [mlpack/mlpack#2443]
Currently mlpack's split takes in labels as rows and features as matrices. However that may not always be the case. Example labels that represent bounding boxes will be matrices. This issue aims to address the same. A solution for this is templating mlpack's split. If any one would like to work on this that would be great.
Kindly let me know your thought or if you need any help. A reference implementation will be made available. When that is the case I will update the issue with the link.
Regards.

**Comment by zoq** [comment]
Correct me if I'm wrong, but I guess we could vectorize the matrix before the split and maybe reshape it afterwards if necessary.

**Comment by zoq** [comment]
That is right, I guess using vectorize is more like a workaround.

**Comment by jonpsy** [comment]
Can I take up this?

**Comment by rcurtin** [comment]
@jonpsy feel free, I don't think that anyone has started to work on it yet. :+1:

**Comment by kartikdutt18** [comment]
Hi @jonpsy, Could you also add support for field type while templating. For field type the operations will be a bit different (maybe overload this function). Take a look this implementation for field [type](https://github.com/mlpack/models/pull/18/files#diff-41f072fe5e54db1663f9b261a99b948aR391).

**Comment by jonpsy** [comment]
@kartikdutt18 
I was thinking something along the lines of
```template<typename T, typename labelType = arma::Row<unsigned long int>>``` 
and for your field type (since it needs different implementation)  we could do template value specialization? More on the PR coming soon. Thoughts?

Cheerio!

**Comment by kartikdutt18** [comment]
Makes sense. Looking forward to the PR.

**Comment by divyanshugit** [comment]
If it is available, Can I work on this ?

**Comment by jonpsy** [comment]
@divyanshugit sorry, I'm already working on this 😁. Check the PR I've cross referenced with this issue.

**Comment by divyanshugit** [comment]
That's perfectly fine :)

**Comment by kartikdutt18** [comment]
Keep open.

**Comment by jonpsy** [comment]
Seconded, give me a week or two to get back.

**Comment by kartikdutt18** [comment]
Keep Open.

**Comment by Abilityguy** [comment]
Hey @kartikdutt18 , is this still open?
If no one is working on it, I would like to take a shot at it.

**Comment by kartikdutt18** [comment]
Hey @Abilityguy,
I think @jonpsy was working on this. I'm not sure if he is still working on this as his PR is now closed. Unless he is still working on it, feel free to take up this issue.
Regards.

**Comment by RishabhGarg108** [comment]
Hey @Abilityguy , are you currently working on this? If not, then I would like to take this issue. Thanks!

**Comment by Abilityguy** [comment]
Hey @RishabhGarg108 , feel free to take it up if @jonpsy is not working on it.

**Comment by RishabhGarg108** [comment]
Thanks! I am working on this.

**Comment by RishabhGarg108** [comment]
Just a clarification, @Abilityguy , recently you have added the data::StratifiedSplit. Shall I also template that too ?

**Comment by jonpsy** [comment]
> Hey @RishabhGarg108 , feel free to take it up if @jonpsy is not working on it.

Sorry, things came in between so I couldn't complete. You can refer my PR for inspiration for working on it, it's near 80% done.

**Comment by Abilityguy** [comment]
> Just a clarification, @Abilityguy , recently you have added the data::StratifiedSplit. Shall I also template that too ?

I don't think there is a need to template the Stratified Splits. Getting it to work with matrices and fields would be complex and not of much use according to me. You could also have a quick chat in the IRC for an opinion on this.

**Comment by RishabhGarg108** [comment]
> I don't think there is a need to template the Stratified Splits. Getting it to work with matrices and fields would be complex and not of much use according to me.

In that case, I will first try to work with the `data::Split` because first I need to learn some concepts like template metaprogramming. And as you are saying it would be quite complicated, then It would be too much to handle at one time for me. So maybe I will do it once I am done with this one.

**Comment by RishabhGarg108** [comment]
@kartikdutt18 since #2746 is now merged, I hope this issue is resolved now. Can we close this ?

**Comment by kartikdutt18** [comment]
Agreed.
