### ISSUE TITLE
Distribution of Go-Bindings Package

### ISSUE THREAD

**Issue by Yashwants19** [mlpack/mlpack#2463]
Hi there, As we know go-bindings is merged in the library, but for the distribution of the package we have to make some efforts. These are the following tasks which have to be done for package distribution :

- [x] Creating a repository namely mlpack-go, where we will place our automatically-generated go-bindings.
- [x] Copy the auto-generated bindings to the repo. Currently we have to remove `capi/.cpp` and `.so` files before copying the bindings to the repo, but this can be managed by some clean-up script. In #2460 I have tried to remove the stress of deleting `capi/.cpp` before copying the bindings to repo, but we still have to manage those `.so` files. I think so @rcurtin is working on release script of julia, which we can also used for go(It will also require a clean script too) as well.
- [x] Add `MAKEFILE` to the mlpack-go repo, this will help us to automatically install all the binary files properly that are essential for the bindings.
- [x] Add `readme.md` to the mlpack-go, which will guide the user that how the user can install/use the bindings.
 - [x] Add meta tag in our website(mlpack.org repo), So as we can use `go get mlpack.org/v1/mlpack`.
```
  <!-- go get imports -->
  <meta name="go-import" content="mlpack.org/v1/mlpack git https://github.com/mlpack/mlpack-go">

  <!-- redirection to godoc documentation -->
  <meta name="go-source" content="mlpack.org/v1/mlpack _ https://github.com/mlpack/mlpack-go/tree/master{/dir} https://github.com/mlpack/mlpack-go/blob/master{/dir}/{file}#L{line}">
```
   ** These meta tag should appear as early as possible in the HTML source code, to avoid any possible parsing errors.
- [x] Optional Add travis/azure ci build that can help us to check whether `MAKEFILE` is working correct after every new release.
- [x] Optional Add `Dockerfile` which lets us build mlpack Docker image which we can then use to build and run mlpack applications in Docker containers.

Hi @rcurtin if you can help with first, second and fifth tasks, it will be a great help. For other tasks I can open a PR one-by-one.

Thank you.

**Comment by rcurtin** [comment]
@Yashwants19 thanks for opening this issue!

I created the repository https://github.com/mlpack/mlpack-go ; want to open a PR there for the third and fourth tasks?

If you can provide a set of directions similar to https://github.com/mlpack/mlpack.jl/blob/master/rel/deployment.md , I can try and use them to upload new versions of the bindings. :)

I'll do the fifth thing and update the website once `go get mlpack.org/v1/mlpack` works. :+1:

**Comment by Yashwants19** [comment]
# How to deploy a new mlpack version to mlpack-go.

This process isn't automatic, and the steps below can be refined as time goes on
into an automated script:

 1. Check out mlpack code.
 2. Configure and build the `go` target: `make go`
 3. Copy the Go bindings (`build/src/mlpack/bindings/go/src/mlpack.org/v1/mlpack`)
    to the root of mlpack-go repository. (This Go-bindings path is according to mlpack-git and not the latest release. )
 4. Remove all the `.so` files.
```sh
rm -f *.so *.so.*
```
 5. Manually change the `PACKAGE_VERSION` in `MAKEFILE`. (Still we have to add this file in the repository.)
 6. Commit any changed files and any added files in `root` and `capi/` folder of mlpack-go repository.

**Comment by Yashwants19** [comment]
> I'll do the fifth thing and update the website once go get mlpack.org/v1/mlpack works. :+1:

For the use `go get -u -d mlpack.org/v1/mlpack` we have to add those meta-tags to our website, else we are not able use `mlpack.org/v1/mlpack`. It will be great if you can add those meta-tags after 2nd task, this will be also helpful for the 3th task.

**Comment by Yashwants19** [comment]
Sorry didn't mention before but for the latest release(3.2.2) we have to made some extra efforts for deploy.
At step 4. we also have to remove .cpp and .hpp files.
```sh
rm -f *.so *.so.* capi/*.cpp capi/*.hpp
```
And edit the import path of `tests/go_binidng_test.go` from `"mlpack/bindings/go/mlpack"` to `"mlpack.org/v1/mlpack"`.

**Comment by rcurtin** [comment]
Ok, I've pushed some first attempts at changes to the mlpack/mlpack-go repository.  But I am not sure if this is completely right.  Do you want to take a look and let me know if I should change anything?  Also, if you think it's easier, you can just open a PR and I can merge it in. :+1:

**Comment by Yashwants19** [comment]
Hi @rcurtin this is looking great. I can use `go get -u -d github.com/mlpack/mlpack-go` smoothly. Now if you can add meta-tags in our website, then may be we are ready use `go get -u -d mlpack.org/v1/mlpack`. Tomorrow I will open a PR both `readme.md` and `MAKEFILE`.
Thank You.

**Comment by Yashwants19** [comment]
I have opened PRs for adding tests file, `Makefile` and add instruction in `README.md` file.

**Comment by rcurtin** [comment]
Ok, I added the vanity import to https://www.mlpack.org/v1/mlpack:
https://github.com/mlpack/mlpack.org/compare/a383cb51831ad7f85d68e5ca5cdbcdaca7924f68...e698fd61c78bbdc11b835bdf1b8fd783ddac2c8d

I tested `go get -u mlpack.org/v1/mlpack` and it succeeded. :tada:

**Comment by Yashwants19** [comment]
Hi I tested this with complete build process, this is looking great. :tada:
Thank you for adding those vanity imports.

**Comment by rcurtin** [comment]
Hey @Yashwants19, this looks basically complete except for one thing:

> Optional Add travis/azure ci build that can help us to check whether MAKEFILE is working correct after every new release.

What are you thinking on this, is this still something we should do?  Or should we go ahead and close this issue if everything is handled well enough for now?

**Comment by Yashwants19** [comment]
Everything is looking great. 
I am not sure why, but [pkg.go.dev](https://pkg.go.dev/mlpack.org/v1/mlpack?tab=doc) is not detecting `LICENSE` correctly.

>>Optional Add travis/azure ci build that can help us to check whether MAKEFILE is working correct after every new release.

> What are you thinking on this, is this still something we should do? 

I think so we should add this, as Julia provides Yggdrasil check before any release provided to the user or Python(mlpack-wheels) provides travis checks or R will provide CRAN checks. Let me know What do you think?

**Comment by rcurtin** [comment]
You're right, this would be nice support to have.  It looks like mlpack/mlpack-go#6 will do the job; thanks so much for taking the time to do that!  Once I see that pass the Travis build, I'll merge it in, and then we can resolve this issue.  Awesome work! :tada:

**Comment by rcurtin** [comment]
Awesome, I think we can resolve this now.  Great work @Yashwants19! :rocket:
