### ISSUE TITLE
Input datasets format for K Nearest-neighbors algorithms. 

### ISSUE THREAD

**Issue by saanumm82** [mlpack/mlpack#2472]
Hi, 

I am trying to use mlpack C++ API  'KNN' or 'NeighborSearch<NearestNeighborSort, EuclideanDistance, arma::mat >'  to find 'k' nearest neighbors.

Here is my sample code - 

#include <mlpack/methods/neighbor_search/neighbor_search.hpp>
using namespace mlpack::neighbor;
arma::mat data;
data::Load("1.csv", data);
KNN a(data);
// The matrices we will store output in.
arma::Mat<size_t> resultingNeighbors;
arma::mat resultingDistances;
a.Search(5, resultingNeighbors, resultingDistances);

--------------------------------------------------------------------
'1.csv' file content. 

2,12,3
2,5,5
5,3,1
3,2,2
3,6,4
1.5,9,6
7,2,7
6,1,8
3.8,3,9

I have below questions w.r.t above code and 1.csv file - 

1) Please let me know, '1.csv' should have always only 2 column? ie  first column represents x-axis points  and 2nd column represents y-axis points as KNN internally calculates distance between 2 points?
2) If input 'data' format is multiple rows and multiple columns, then how KNN internally works?

and also another question on  Command-Line 'mlpack_knn'

mlpack_knn -r dataset.csv -n neighbors_out.csv -d distances_out.csv -k 5 -v

In above command, 'dataset.csv' example input datasets are not given in mlpack website. Please let me know where can i find sample datasets of 'dataset.csv. 

Please help.

**Comment by rcurtin** [comment]
Hi @saanumm82, hopefully these answers below are helpful:

> Please let me know, '1.csv' should have always only 2 column? ie first column represents x-axis points and 2nd column represents y-axis points as KNN internally calculates distance between 2 points?

Actually in your example `1.csv` can have any number of columns; the number of columns is the dimension of each point.  So if there are 2 columns, then each column will correspond to the x and y axis; if there are 3, each column corresponds to the x, y, and z axes, etc.  Each row in the input CSV correponds to one point.

> If input 'data' format is multiple rows and multiple columns, then how KNN internally works?

Given that each row of the data is a point and each column is a dimension, then internally the `KNN` class will compute the k nearest points to each point.

> In above command, 'dataset.csv' example input datasets are not given in mlpack website. Please let me know where can i find sample datasets of 'dataset.csv.

That's just a placeholder, you could use any file there.  Here's a simple file of 3-dimensional test data: https://github.com/mlpack/mlpack/blob/master/src/mlpack/tests/data/test_data_3_1000.csv

**Comment by saanumm82** [comment]
Thanks a lot for your help. Now i got clear picture on this. 
Currently, i am maintaining 2 files.  '1.csv' for datasets and 'labels.txt' for label for each datasets  as i need to predict a new labels for test datasets based on K Nearest-neighbors.

Here are the '1.csv' datasets

2,12
2,5
5,3
3,2
3,6
1.5,
7,2
6,1
3.8,3

'labels.txt' file has labels for above datasets.

1
0
1
0
1
0
1
1
0

Now i want to predict a label for points (3,4) ( reading 3,4 from 'testData.csv') So i have written below code to predict a new label based on 4 Nearest-neighbors labels. 

#include <mlpack/methods/neighbor_search/neighbor_search.hpp>
using namespace mlpack::neighbor;
arma::mat data;
data::Load("1.csv", data);
KNN a(data);
// The matrices we will store output in.
arma::Mat<size_t> resultingNeighbors;
arma::mat resultingDistances;

arma::mat testData;
data::Load("testData.csv", testData, true);
a.Search(testData,3, resultingNeighbors, resultingDistances);

arma::Row<size_t> labels;
data::Load("labels.txt", labels);

int NumOfOnes = 0;
int NumOfZeros = 0;

for (size_t i = 0; i < resultingNeighbors.n_elem; i++)
{
           if(labels.at(kdNeighbors(i)) == 0)
                        NumOfZeros++;
                else if(labels.at(kdNeighbors(i)) == 1)
                        NumOfOnes++;
}

 if(NumOfZeros > NumOfOnes)
     cout<<"new label is: 0"<<endl;
else if(NumOfOnes > NumOfZeros)
      cout<<"new label is: 1"<<endl;
else
   cout<<"both are equal"<<endl;

return 0;
}

Please let me know is the correct way to predict a new label for points (3,4). Any sample code to solve this example is appreciated.  Please help.

**Comment by saanumm82** [comment]
Hi Ryan Curtin and Team,

Please help on above solution.

**Comment by rcurtin** [comment]
Hi @saanumm82, at a quick glance the code looks to be correct to me.  Perhaps you should write some tests too to make sure that your implementation is correct, instead of relying just on my quick look at the code?

**Comment by saanumm82** [comment]
Hi Ryan Curtin, 
Thanks for the update.
I have already written test code to test the implementation. It's working as expected.

I see some inconsistency between class  'KNN'  and  DecisionTree where as DecisionTree class takes 2nd argument as datasets labels but 'KNN' class doesn't take labels as arguments ie the reason i was getting confused.

However, now looks good to me. Thanks a lot for your support and help on this.

**Comment by rcurtin** [comment]
Great to hear the code works.  Our `KNN` class is not a classifier (though I would love to have an internal implementation of a `KNNClassifier` of course).  Instead it just performs the k-nearest-neighbor search task, which is an unlabeled task, and then provides the results for that. :+1:

**Comment by saanumm82** [comment]
Once again thanks for your help and support.
