### ISSUE TITLE
Go bindings bug: returning pointer to a local variable

### ISSUE THREAD

**Issue by lozhnikov** [mlpack/mlpack#2482]
I was fixing build warnings and I've found an issue.

`src/mlpack/bindings/go/mlpack/capi/cli_util.cpp:125`

```c++
const char* mlpackGetParamString(const char* identifier)
{
  std::string val = CLI::GetParam<std::string>(identifier);

  // The pointer will be freed after return!
  return val.c_str();;
}
```

It's definitely an error. I'm not sure how to fix. Unfortunately, I'm not familiar with go.

**Comment by rcurtin** [comment]
Nice catch!  I think it could suffice here to literally just do `return CLI::GetParam<std::string>(identifier).c_str();`.  In that situation, `GetParam` will return a `const std::string&`, which would not be freed as soon as the function returned.  @Yashwants19 let me know what you think.

**Comment by Yashwants19** [comment]
Thanks for reporting the issue @lozhnikov. Hi @rcurtin, this solution looks great to me, I have tried to resolve the bug in #2483.
Thank you.
