### ISSUE TITLE
Linking errors in building mlpack with armadillo

### ISSUE THREAD

**Issue by ljsun** [mlpack/mlpack#2490]
There are something wrong when I run `make` ，
`[  0%] Linking CXX shared library ../../lib/libmlpack.dylib
Undefined symbols for architecture x86_64:
....
ld: symbol(s) not found for architecture x86_64`
but armadillo can be found in the dictionary /usr/local/include, an my os is MacOS10.15.2

**Comment by shrit** [comment]
@ljsun  Do you have more output from make?

**Comment by shrit** [comment]
if not can you do `make VERBOSE=1`?

**Comment by ljsun** [comment]
> @ljsun Do you have more output from make?

the more output is 
`[  0%] Linking CXX shared library ../../lib/libmlpack.dylib
Undefined symbols for architecture x86_64:
  "___kmpc_critical", referenced from:
      bool arma::diskio::load_csv_ascii<int>(arma::SpMat<int>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      arma::SpMat<int>::sync_csc() const in load.cpp.o
      arma::SpMat<int>::init(arma::SpMat<int> const&) in load.cpp.o
      bool arma::diskio::load_csv_ascii<unsigned int>(arma::SpMat<unsigned int>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      arma::SpMat<unsigned int>::sync_csc() const in load.cpp.o
      arma::SpMat<unsigned int>::init(arma::SpMat<unsigned int> const&) in load.cpp.o
      bool arma::diskio::load_csv_ascii<unsigned long>(arma::SpMat<unsigned long>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      ...
  "___kmpc_end_critical", referenced from:
      bool arma::diskio::load_csv_ascii<int>(arma::SpMat<int>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      arma::SpMat<int>::sync_csc() const in load.cpp.o
      arma::SpMat<int>::init(arma::SpMat<int> const&) in load.cpp.o
      bool arma::diskio::load_csv_ascii<unsigned int>(arma::SpMat<unsigned int>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      arma::SpMat<unsigned int>::sync_csc() const in load.cpp.o
      arma::SpMat<unsigned int>::init(arma::SpMat<unsigned int> const&) in load.cpp.o
      bool arma::diskio::load_csv_ascii<unsigned long>(arma::SpMat<unsigned long>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      ...
  "___kmpc_for_static_fini", referenced from:
      _.omp_outlined. in gaussian_distribution.cpp.o
      _.omp_outlined. in gamma_distribution.cpp.o
      _.omp_outlined..44 in gamma_distribution.cpp.o
      _.omp_outlined..45 in gamma_distribution.cpp.o
      _.omp_outlined. in diagonal_gaussian_distribution.cpp.o
      _.omp_outlined..40 in diagonal_gaussian_distribution.cpp.o
      _.omp_outlined..41 in diagonal_gaussian_distribution.cpp.o
      ...
  "___kmpc_for_static_init_8u", referenced from:
      _.omp_outlined. in gaussian_distribution.cpp.o
      _.omp_outlined. in gamma_distribution.cpp.o
      _.omp_outlined..44 in gamma_distribution.cpp.o
      _.omp_outlined..45 in gamma_distribution.cpp.o
      _.omp_outlined. in diagonal_gaussian_distribution.cpp.o
      _.omp_outlined..40 in diagonal_gaussian_distribution.cpp.o
      _.omp_outlined..41 in diagonal_gaussian_distribution.cpp.o
      ...
  "___kmpc_fork_call", referenced from:
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in gaussian_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Mat<double> >(arma::Mat<double>&, arma::eOp<arma::Mat<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Col<double> >(arma::Mat<double>&, arma::eOp<arma::Col<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_scalar_times>::apply_inplace_plus<arma::eOp<arma::subview_col<double>, arma::eop_log> >(arma::Mat<arma::eOp<arma::subview_col<double>, arma::eop_log>::elem_type>&, arma::eOp<arma::eOp<arma::subview_col<double>, arma::eop_log>, arma::eop_scalar_times> const&) in gamma_distribution.cpp.o
      arma::eOp<arma::Col<double>, arma::eop_log>::elem_type arma::accu_proxy_linear<arma::eOp<arma::Col<double>, arma::eop_log> >(arma::Proxy<arma::eOp<arma::Col<double>, arma::eop_log> > const&) in diagonal_gaussian_distribution.cpp.o
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in diagonal_gaussian_distribution.cpp.o
      void arma::eglue_core<arma::eglue_plus>::apply<arma::Mat<double>, arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double> >(arma::Mat<double>&, arma::eGlue<arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double>, arma::eglue_plus> const&) in diagonal_gaussian_distribution.cpp.o
      ...
  "___kmpc_global_thread_num", referenced from:
      bool arma::diskio::load_csv_ascii<int>(arma::SpMat<int>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      arma::SpMat<int>::sync_csc() const in load.cpp.o
      arma::SpMat<int>::init(arma::SpMat<int> const&) in load.cpp.o
      bool arma::diskio::load_csv_ascii<unsigned int>(arma::SpMat<unsigned int>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      arma::SpMat<unsigned int>::sync_csc() const in load.cpp.o
      arma::SpMat<unsigned int>::init(arma::SpMat<unsigned int> const&) in load.cpp.o
      bool arma::diskio::load_csv_ascii<unsigned long>(arma::SpMat<unsigned long>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      ...
  "___kmpc_push_num_threads", referenced from:
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in gaussian_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Mat<double> >(arma::Mat<double>&, arma::eOp<arma::Mat<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Col<double> >(arma::Mat<double>&, arma::eOp<arma::Col<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_scalar_times>::apply_inplace_plus<arma::eOp<arma::subview_col<double>, arma::eop_log> >(arma::Mat<arma::eOp<arma::subview_col<double>, arma::eop_log>::elem_type>&, arma::eOp<arma::eOp<arma::subview_col<double>, arma::eop_log>, arma::eop_scalar_times> const&) in gamma_distribution.cpp.o
      arma::eOp<arma::Col<double>, arma::eop_log>::elem_type arma::accu_proxy_linear<arma::eOp<arma::Col<double>, arma::eop_log> >(arma::Proxy<arma::eOp<arma::Col<double>, arma::eop_log> > const&) in diagonal_gaussian_distribution.cpp.o
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in diagonal_gaussian_distribution.cpp.o
      void arma::eglue_core<arma::eglue_plus>::apply<arma::Mat<double>, arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double> >(arma::Mat<double>&, arma::eGlue<arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double>, arma::eglue_plus> const&) in diagonal_gaussian_distribution.cpp.o
      ...
  "_omp_get_max_threads", referenced from:
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in gaussian_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Mat<double> >(arma::Mat<double>&, arma::eOp<arma::Mat<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Col<double> >(arma::Mat<double>&, arma::eOp<arma::Col<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_scalar_times>::apply_inplace_plus<arma::eOp<arma::subview_col<double>, arma::eop_log> >(arma::Mat<arma::eOp<arma::subview_col<double>, arma::eop_log>::elem_type>&, arma::eOp<arma::eOp<arma::subview_col<double>, arma::eop_log>, arma::eop_scalar_times> const&) in gamma_distribution.cpp.o
      arma::eOp<arma::Col<double>, arma::eop_log>::elem_type arma::accu_proxy_linear<arma::eOp<arma::Col<double>, arma::eop_log> >(arma::Proxy<arma::eOp<arma::Col<double>, arma::eop_log> > const&) in diagonal_gaussian_distribution.cpp.o
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in diagonal_gaussian_distribution.cpp.o
      void arma::eglue_core<arma::eglue_plus>::apply<arma::Mat<double>, arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double> >(arma::Mat<double>&, arma::eGlue<arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double>, arma::eglue_plus> const&) in diagonal_gaussian_distribution.cpp.o
      ...
  "_omp_in_parallel", referenced from:
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in gaussian_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Mat<double> >(arma::Mat<double>&, arma::eOp<arma::Mat<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Col<double> >(arma::Mat<double>&, arma::eOp<arma::Col<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_scalar_times>::apply_inplace_plus<arma::eOp<arma::subview_col<double>, arma::eop_log> >(arma::Mat<arma::eOp<arma::subview_col<double>, arma::eop_log>::elem_type>&, arma::eOp<arma::eOp<arma::subview_col<double>, arma::eop_log>, arma::eop_scalar_times> const&) in gamma_distribution.cpp.o
      arma::eOp<arma::Col<double>, arma::eop_log>::elem_type arma::accu_proxy_linear<arma::eOp<arma::Col<double>, arma::eop_log> >(arma::Proxy<arma::eOp<arma::Col<double>, arma::eop_log> > const&) in diagonal_gaussian_distribution.cpp.o
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in diagonal_gaussian_distribution.cpp.o
      void arma::eglue_core<arma::eglue_plus>::apply<arma::Mat<double>, arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double> >(arma::Mat<double>&, arma::eGlue<arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double>, arma::eglue_plus> const&) in diagonal_gaussian_distribution.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libmlpack.3.2.dylib] Error 1
make[1]: *** [src/mlpack/CMakeFiles/mlpack.dir/all] Error 2
make: *** [all] Error 2`

**Comment by ljsun** [comment]
> if not can you do `make VERBOSE=1`?

`make VERBOSE=1` did not work

**Comment by ljsun** [comment]
Can anyone help me？

**Comment by ljsun** [comment]
Could anyone help me

**Comment by kartikdutt18** [comment]
Hey @ljsun, are you building from source?

**Comment by ljsun** [comment]
> Hey @ljsun, are you building from source?

yes, I download the source from `wget https://www.mlpack.org/files/mlpack-3.2.2.tar.gz`

**Comment by ljsun** [comment]
@kartikdutt18 yes, I download the source from wget https://www.mlpack.org/files/mlpack-3.2.2.tar.gz

**Comment by kartikdutt18** [comment]
In your CMakeFlags could add the following : `USE_OPENMP=OFF`.
Also since you are on OSX, you could use `brew install mlpack`

**Comment by ljsun** [comment]
I think the reason is that `armadillo ` could not be found, but `armadillo ` is in my path `/usr/local/include`

**Comment by kartikdutt18** [comment]
> In your CMakeFlags could add the following : USE_OPENMP=OFF.
Also since you are on OSX, you could use brew install mlpack

Could you try this, we do have an issue with linking OpenMP on new OSX. Maybe this should fix it.

**Comment by zoq** [comment]
@kartikdutt18 good idea just, if you can test with `cmake -DUSE_OPENMP=OFF ..` instead of `cmake ..` that would be great. If that works we could see if the changes proposed in https://github.com/mlpack/mlpack/pull/2412 work on your system as well.

**Comment by ljsun** [comment]
@kartikdutt18 @zoq `cmake -DUSE_OPENMP=OFF ..` worked, but i ran into another problem 
`Referenced from: /usr/local/lib/libarmadillo.9.90.1.dylib    Reason: image not found`

**Comment by zoq** [comment]
I guess in the `make` stage? Can you remove the build folder and start and start with a clean build?

**Comment by kartikdutt18** [comment]
> If that works we could see if the changes proposed in #2412 work on your system as well.

@zoq, The fix from #2412 works on my system. (It's the one that I have installed). If I don't use it and I try compiling with openmp then it throws, `Unknown symbols`.

**Comment by ljsun** [comment]
@zoq it not worked, the main reason is `dyld: Library not loaded: @rpath/libhdf5.103.dylib`

**Comment by kartikdutt18** [comment]
@ljsun, Could you try installing mlpack 3.3.2 instead, It will have the fix from #2328 that might fix the issue with hd5 lib.

**Comment by ljsun** [comment]
@kartikdutt18 my version is already 3.3.2

**Comment by zoq** [comment]
Can you test if the solution in https://github.com/mlpack/mlpack/issues/1069#issuecomment-475402035 works, this is probably a brew packaging problem.
