### ISSUE TITLE
Updating the Style Guide.

### ISSUE THREAD

**Issue by kartikdutt18** [mlpack/mlpack#2496]
The following points are put up for discussion and if needed they can be updated in the style guide.

1. Redundant return in else statement.
Terminating a function with a return statement wrapped around an else statement seems redundant. A few of them were removed in #2491. 

2. Style Guide for lambda functions
I think we are trying to add lambda functions in one the PR (can't remember which), we already have some lambda functions in the models repo. Might be a nice idea to update style guide with lambda functions.

Kindly let me know what you think.
Regards.

**Comment by zoq** [comment]
@kartikdutt18 thanks for starting a discussion about this. Regarding point number one, either is fine for me, I slightly lean towards to not introduce another else case, don't think this will lead to any performance improvement in either direction in most cases.

About the second point, do you have a concrete example? I'm not sure what the preferred lambda function style might look like.

**Comment by favre49** [comment]
> About the second point, do you have a concrete example? I'm not sure what the preferred lambda function style might look like.

An example of this is [here](https://google.github.io/styleguide/cppguide.html#Formatting_Lambda_Expressions). Most places I've seen follow the same type of thing -  just do the same formatting as for a function.

**Comment by rcurtin** [comment]
Sure, I don't think it would be a bad idea to add some style guide for lambdas.  I think the Google idea is fine although I guess with our style their snippet would actually be, e.g.,

```
digits.erase(std::remove_if(digits.begin(), digits.end(), [&blacklist](int i)
    {
      return blacklist.find(i) != blacklist.end();
    }),
    digits.end());
```
(I think I got that right?  Basically just I wrapped the `{` and then the wrapped lines are indented 4 spaces.)

**Comment by rcurtin** [comment]
Hey @kartikdutt18 and @favre49, what do you want to do with this issue?  I'm happy to make changes to the style guide---it certainly seems like nobody was opposed to what's suggested here.  If you want to propose a section to add to the style guide, we can go ahead and do that. :+1:

**Comment by kartikdutt18** [comment]
Sure, I will make leave a comment here with the changes and if that makes sense we can merge it in the style guidelines wiki.

**Comment by kartikdutt18** [comment]
I'm sorry I lost track of this issue. Here is a sample that I think we can add. If this makes sense we can add to the wiki.

## Lambda Functions
Lambda functions can be used to encapsulate code that is passed to another method. The brace placement will follow the same guidelines as other functions i.e. The opening braces of lambda function will also be indented. An example of lambda function is shown below.
```
digits.erase(std::remove_if(digits.begin(), digits.end(), [&blacklist](int i)
    {
      return blacklist.find(i) != blacklist.end();
    }),
  digits.end());
```

**Comment by rcurtin** [comment]
@kartikdutt18 this looks good to me.  I'll let it sit for a few days in case there are any other comments, then add it to the style guide.  I think that the `digits.end()` should be indented twice, though:

```
digits.erase(std::remove_if(digits.begin(), digits.end(), [&blacklist](int i)
    {
      return blacklist.find(i) != blacklist.end();
    }),
    digits.end());
```

Correct me if I misunderstood. :+1:

**Comment by kartikdutt18** [comment]
Ahh yes, what you wrote is correct. Thanks for the fix.

**Comment by rcurtin** [comment]
Thank you @mlpack-bot for reminding me!  I updated the style guide. :smile:
