### ISSUE TITLE
Decision Stump Error

### ISSUE THREAD

**Issue by danyvarghese** [mlpack/mlpack#2501]
Hi

While running the code I get an error as follows

statistics.hpp:44:44: error: ‘decision_stump’ is not a member of ‘mlpack’
 typedef mlpack::adaboost::AdaBoost<mlpack::decision_stump::DecisionStump<>> ADABOOST_DS;

can you please help me to sort out this?

**Comment by rcurtin** [comment]
Hi @danyvarghese, some time ago (a few years I think) we changed the `DecisionStump<>` class to actually be a variant of our `DecisionTree<>` class.  You can still use the `DecisionStump<>` name, but now it's in the `tree` namespace.  So, your code should be:

```
typedef mlpack::adaboost::AdaBoost<mlpack::tree::DecisionStump<>> ADABOOST_DS;
```

Note that the functionality is slightly different for the old and new decision stumps, but AdaBoost should still produce good models either way.

May I ask if this is an example from documentation somewhere?  If so, I can update the documentation for correctness. :+1:
