### ISSUE TITLE
Remove .swp files

### ISSUE THREAD

**Issue by kolbma** [mlpack/mlpack#2504]
There are some left swp files (from editor I guess) in the source bundle.

$ find mlpack-3.3.2.orig -name "*.swp"
mlpack-3.3.2.orig/src/mlpack/methods/decision_tree/.decision_tree_impl.hpp.swp
mlpack-3.3.2.orig/src/mlpack/methods/decision_tree/.best_binary_numeric_split_impl.hpp.swp
mlpack-3.3.2.orig/src/mlpack/methods/decision_tree/.all_categorical_split_impl.hpp.swp

**Comment by zoq** [comment]
Thanks for the report, we should add `.swp` to https://github.com/mlpack/mlpack/blob/master/.gitignore to make sure we don't checkin swap files. Do you want to open a PR to remove the files, don't feel obligated?

**Comment by rcurtin** [comment]
#2510 fixes the issue and is merged now.  Thanks for the report @kolbma! :+1:
