### ISSUE TITLE
Following up with a TODO in NewCXX11.cmake

### ISSUE THREAD

**Issue by birm** [mlpack/mlpack#2509]
In https://github.com/mlpack/mlpack/blob/master/CMake/NewCXX11.cmake it's recommended that come the far-off date of late 2016 or min cmake 3.1, that the contents of that file should be moved to the main cmakelists. Are we still interested in doing so?

**Comment by rcurtin** [comment]
Our minimum CMake version is now 3.3.2, so I think we can totally move it to the main CMake configuration.  `NewCXX11.cmake` in particular is used in `src/mlpack/CMakeLists.txt`.  If you want to go ahead and do it please feel free! :+1:
