### ISSUE TITLE
undefined reference to sgssv and sgssvx

### ISSUE THREAD

**Issue by brightprogrammer** [mlpack/mlpack#2511]
[ 18%] Linking CXX executable ../../../../bin/mlpack_adaboost
/usr/bin/ld: /usr/lib/libarmadillo.so: undefined reference to `sgssv'
/usr/bin/ld: /usr/lib/libarmadillo.so: undefined reference to `sgssvx'
collect2: error: ld returned 1 exit status
make[2]: *** [src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/build.make:109: bin/mlpack_adaboost] Error 1
make[1]: *** [CMakeFiles/Makefile2:2558: src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 20%] Linking CXX executable ../../../../bin/mlpack_approx_kfn
/usr/bin/ld: /usr/lib/libarmadillo.so: undefined reference to `sgssv'
/usr/bin/ld: /usr/lib/libarmadillo.so: undefined reference to `sgssvx'
collect2: error: ld returned 1 exit status
make[2]: *** [src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/build.make:109: bin/mlpack_approx_kfn] Error 1
make[1]: *** [CMakeFiles/Makefile2:2585: src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
[r00t3r@titan build]$

**Comment by zoq** [comment]
Hello, can you tell us more about your system, armadillo version, OS, compiler, also did you use qmake instead of make?

**Comment by rcurtin** [comment]
This looks like a failure to link against LAPACK or BLAS.  If you've done a custom installation of Armadillo please let us know how it was configured. :+1:

**Comment by brightprogrammer** [comment]
Thanks for replying so soon... I've reinstalled my operating system and then installed mlpack form package manager... You can mark this as closed
