### ISSUE TITLE
Compilation problem using conda on CentOS 7 with devtoolset

### ISSUE THREAD

**Issue by gscarella** [mlpack/mlpack#2532]
Hello,

I have compilation problems  with mlpack, using conda on CentOS 7.
I'm using devtoolset-9 and  mlpack installation was successful with conda. But I got some errors when I compiled basic examples with mlpack in my conda environment.
I obtained several "undefined reference" error messages. Here is the beginning of the compilation errors

`/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: OBJ/essai_lars.o: in function 'mlpack::bindings::cli::ParseCommandLine(int, char**)':
/home/gscarella/.conda/envs/testA/include/mlpack/bindings/cli/parse_command_line.hpp:43: undefined reference to 'mlpack::CLI::Parameters()'`
`/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/gscarella/.conda/envs/testA/include/mlpack/bindings/cli/parse_command_line.hpp:77: undefined reference to 'boost::program_options::options_description::find(std::string const&, bool, bool, bool) const'`
`/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/gscarella/.conda/envs/testA/include/mlpack/bindings/cli/parse_command_line.hpp:96: undefined reference to 'mlpack::util::PrefixedOutStream::operator<<(std::string&)'`
`/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/gscarella/.conda/envs/testA/include/mlpack/bindings/cli/parse_command_line.hpp:133: undefined reference to 'mlpack::CLI::HasParam(std::string const&)'`
`/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/gscarella/.conda/envs/testA/include/mlpack/bindings/cli/parse_command_line.hpp:136: undefined reference to 'mlpack::CLI::ProgramName()'`
`/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/gscarella/.conda/envs/testA/include/mlpack/bindings/cli/parse_command_line.hpp:136: undefined reference to 'mlpack::util::GetVersion()' `
....

It seems that  some symbols (B5cxx11 for example which stands for [abi:cxx11]) present in the mlpack library file are missing in my object file, so there are errors at linking. The problem should come from devtoolset on CentOS 7.
Is there a way to have mlpack functional with conda on CentOS 7?

Thanks

**Comment by zoq** [comment]
Hello @gscarella can you post the command you use to build your example as well? Also, looks like you build the current master branch right?

**Comment by gscarella** [comment]
Hello,

I installed mlpack with conda on the CentOS server in my conda environment (named testA)

`conda create -n testA`
`conda activate testA`
`conda install -c conda-forge mlpack`

So mlpack version is 3.3.2.
To compile the example (see after)
`mkdir -p OBJ bin`
`g++ -std=c++11 -g -fopenmp -I/home/gscarella/.conda/envs/testA/include  -c essai_lars.cpp -o OBJ/essai_lars.o`
`g++ -std=c++11 -g -fopenmp -o bin/essai_lars.exe OBJ/essai_lars.o -L/home/gscarella/.conda/envs/testA/lib/ -lboost_serialization -lboost_program_options -lboost_unit_test_framework  -larmadillo -lmlpack`
                 
The compilation of the object file was ok, but I got errors for the exe file (see previous message). 
                                                                                
The same commands work on Ubuntu servers (18 or 20). There is a known bug with 
devtoolset on CentOS 7 (see https://bugzilla.redhat.com/show_bug.cgi?id=1546704 )
                                                                                
My question is: is it possible to use mlpack with conda on CentOS 7?
Thanks                                                                  
 
[essai_lars.cpp](https://github.com/mlpack/mlpack/files/4959165/essai_lars.cpp.txt)

**Comment by rcurtin** [comment]
Hmm, I do think that may be related to #1546704, but I'm not familiar enough with conda to really say.

By the way, in your example code, you aren't using any of the functions of `CLI` so you could remove this code:

```
#include <mlpack/core/util/cli.hpp>
#define BINDING_TYPE BINDING_TYPE_CLI
#include <mlpack/core/util/mlpack_main.hpp>
```

> It seems that some symbols (B5cxx11 for example which stands for [abi:cxx11]) present in the mlpack library file are missing in my object file, so there are errors at linking.

I don't see `B5cxx11` in your output anywhere, maybe I missed it?  If you can supply the relevant information there it could be helpful too.

Now I do know that conda has gotten code like this to compile before.  If you can install mlpack via conda and get the `mlpack_lars` program, that's basically a variant on the code that you posted and should have all the same symbols in it.  So the question might be best asked to the conda maintainers of how to compile this code in the exact same way that they did for their distribution---and maybe that's not with `devtoolset-9`, but instead a toolchain supplied by conda?

(Another workaround would be to not use conda for this.  I believe I pushed mlpack-3.3.2 to the EPEL7 repository, so you could just install `mlpack-devel` via `dnf` or `yum` and then compile your program using the mlpack headers and libraries installed on the system.)

**Comment by gscarella** [comment]
Hello,                                                                                                                                                                                                           
Thanks for your answer                                                                                                                                                                                           
                                                                                                                                                                                                                 
To explain more about the B5cxx11 missing symbol with devtoolset, there is a  compilation error for "mlpack::CLI::Parameters()" (as an  example). In the library file we have                                                                 
`% nm libmlpack.so | grep -i "Parameters"`                                                                                                                                                                       
`00000000000e6bb0 T _ZN6mlpack3CLI10ParametersB5cxx11Ev`                                                                                                                                                         
In the object file                                                                                                                                                                                               
`% nm OBJ/essai_lars.o|grep -i "Parameters"                           `                                                                                                                                          
 `                U _ZN6mlpack3CLI10ParametersEv`                                                                                                                                                                
Using c++filt to decode                                                                                                                                                                                          
` % c++filt _ZN6mlpack3CLI10ParametersB5cxx11Ev`                                                                                                                                                                 
`mlpack::CLI::Parameters[abi:cxx11]()`                                                                                                                                                                           
` % c++filt _ZN6mlpack3CLI10ParametersEv`                                                                                                                                                                        
`mlpack::CLI::Parameters()`                                                                                                                                                                                      
                                                                                                                                                                                                                 
So the library file contains [abi:cxx11] which is missing in the object file hence one compilation error.                                                                                                        
                                                                                                                                                                                                                 
It seems to work using the compiler installed from conda (installing gxx_linux-64 in the conda environment), I didn't think about that.                                                                                                                             
And rpm package (mlpack-3.3.0) works well but sometimes it may not be so easy to have it installed.

Thanks again

**Comment by rcurtin** [comment]
I see, glad to hear you could work around the issue using the conda-supplied compiler.  Honestly I am not sure that much else could be done in this case, at least not from our side.  I'll go ahead and close this issue since I think it's resolved now, but if I misunderstood and there is still something that needs to be handled, please don't hesitate to comment and we can reopen the issue and try to figure it out. :)
