### ISSUE TITLE
Issue in mlpack::data::Load

### ISSUE THREAD

**Issue by PratibhaT** [mlpack/mlpack#2537]
Hi,
I'm getting this error
` undefined reference to bool mlpack::data::Load<double>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, arma::Mat<double>&, bool, bool)'
collect2: error: ld returned 1 exit status'`

In these lines of code.

```
#include <mlpack/core.hpp>
#include <mlpack/prereqs.hpp>
#include <mlpack/methods/linear_svm/linear_svm.hpp>
#include <ensmallen.hpp>
....
mlpack::data::Load("/home/ptripathi/Datasets_pcd/SFMTA_v3_long_d88ce61f6c8c4f0f83142b98e654a15f/train.csv", train_data);
mlpack::data::Load("/home/ptripathi/trackable_csv/test_sfmta_multi.csv", test_data);
....

```

I've added FindArmadillo.cmake, FindEnsmallen.cmake and FindMLPACK.cmake. In my cmake/ .
And following lines in my CMakeLists.txt

```
find_package(OpenMP)
if (OPENMP_FOUND)
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
endif()

find_package(Armadillo 8.400.0 REQUIRED)
find_package(MLPACK REQUIRED)
find_package(Ensmallen 1.10.0)

target_link_libraries(quanergy_qortex
  ${ARMADILLO_LIBRARIES}
  ${ENSMALLEN_LIBRARIES}
  ${Boost_LIBRARIES}
  ${MLPACK_LIBRARY}
)
```

**Comment by rcurtin** [comment]
Hi @PratibhaT,

Are you sure CMake is linking against the right library?  If `MLPACK_LIBRARY` is a very old version, or if you have local headers for a new version of mlpack but `MLPACK_LIBRARY` corresponds to an older version of mlpack, this could cause exactly the errors you are seeing here.  It might be worth taking a look through your system to see if there are multiple versions of mlpack on it. :+1:

**Comment by rcurtin** [comment]
(You could also do, e.g., `VERBOSE=1 make` in your CMake project to see the exact compilation and linking commands that are being called.)
