### ISSUE TITLE
Probable error in gradient function of BatchNorm

### ISSUE THREAD

**Issue by mrityunjay-tripathi** [mlpack/mlpack#2549]
#### Issue description

I spotted a probable error in the Gradient test of the BatchNorm layer. Probably the following lines in `ann_layer_test.cpp` suppressed the errors.
https://github.com/mlpack/mlpack/blob/f500227c6492c8cdcabd407b3bd028565c99f218/src/mlpack/tests/ann_layer_test.cpp#L4070-L4075
I doubt if gradient error can ever be 0.1. Ideally, it should be somewhere around 1e-07, even then mlpack uses 1e-05 in most of the cases.
When I tried to get the original and estimated gradients, I got the [this](https://pastebin.com/YTVAY6df) result. We can see that all gradients after the 20th element are correct to significant decimal places but before that none are matching. By this, I think maybe some part of the code is correct while some part has some error.

#### Your environment

 * operating system: Ubuntu 18.04
 * compiler: gcc 7.5.0
 * version of dependencies (Boost/Armadillo): Boost- 1.70 and Armadillo - 9.850.1

#### Steps to reproduce

Just put these lines in `ann_test_tools.hpp` after line 163.
```cpp
printf("Original and Estimated Gradients:\n");
for (size_t i = 0; i < estGradient.n_elem; ++i)
{
  printf("%zu) %.17lf    %.17lf\n", i, orgGradient(i), estGradient(i));
}
```
...then obviously build mlpack and test with following command:
`bin/mlpack_test -t ANNLayerTest/GradientBatchNormWithMiniBatchesTest`

#### Expected behavior

Gradient check should pass with a tolerance of at least 1e-05.

#### Actual behavior

Gradient check fails when tolerance of 1e-05 is used.

**Comment by kartikdutt18** [comment]
I think the expression is correct and the model trains / converges well. I think Atrous Conv layer has an even higher tolerance so we can probably add that to the list above. Also in  the BatchNorm Test you can have a lower tolerance of 1e-2/3 if you don't use a Conv layer in the test.

**Comment by mrityunjay-tripathi** [comment]
@kartikdutt18 : I think [this](https://stackoverflow.com/a/47506918/9231123) explains it well.
