### ISSUE TITLE
Text classification

### ISSUE THREAD

**Issue by kshunmugaraj** [mlpack/mlpack#2554]
Hi,
I am looking for Text classification example code,  mainly on Text pre-processing and Tokenizing and Vectoring text to use it in ML libraries.

**Comment by zoq** [comment]
Hello, I'm not sure are you looking for something like word2vec?

**Comment by zoq** [comment]
Also mlpack implements one-hot encoding.

**Comment by kshunmugaraj** [comment]
Thanks for the reply,  i am working on email classification problem, for that i wanted to do text pre-processing and TFIDF vector. So was looking for sample code.

**Comment by zoq** [comment]
There are some examples using TFIDF here: https://github.com/mlpack/mlpack/blob/2b27e6c11f4e6d76080ae43a43d447934a0b7624/src/mlpack/tests/string_encoding_test.cpp#L715 also https://fedoramagazine.org/spam-classification-with-ml-pack/ might be helpful, because you mentioned mail classification.

**Comment by kshunmugaraj** [comment]
Thanks, thanks a lot for your time. Will check it.
