### ISSUE TITLE
Loading a dataset with categorical variable with help of DatasetMapper object

### ISSUE THREAD

**Issue by shawnbrar** [mlpack/mlpack#2571]
I was trying loading the [iris](http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data) dataset and the last column in the dataset is a categorical one. So while reading the documentation I found out that this could probably be done with the help of the [5th function overload](https://www.mlpack.org/doc/mlpack-3.3.2/doxygen/namespacemlpack_1_1data.html#a9af06d46f91871c42f38e30aac5d4666) of `mlpack::data::Load` function. In this we have to specify a `DatasetMapper` object. But I am having some trouble to figure out how to specify a `DatasetMapper` object. If you could please help me in doing so.

**Comment by rcurtin** [comment]
Hi @shawnbrar, this should be pretty straightforward, you can do it like this:

```
arma::mat matrix;
data::DatasetInfo info;
data::Load("iris.csv", matrix, info);
```

Here's a relevant tutorial: https://www.mlpack.org/doc/mlpack-3.3.2/doxygen/formatdoc.html#formatcatcpp

Let me know if we can clarify anything else. :+1:
