### ISSUE TITLE
Undefined references with both distro packages and custom build

### ISSUE THREAD

**Issue by rlichtenwalter** [mlpack/mlpack#2573]
I am trying to build a project with the mlpack shared library on Ubuntu 18.04. I think I must be missing something obvious, but I'm not sure what it might be and would appreciate some help. I first tried the distro packages via

sudo apt-get install libmlpack2 libmlpack-dev

Then I followed the GNU/Linux build instructions, including altering LD_LIBRARY_PATH to include the target installation path of /usr/local/lib.

Compiling with these flags:

-std=c++14 -Wall -Wextra -Werror -Wpedantic -Wno-unused-local-typedefs -fopenmp -larmadillo -lmlpack -L/usr/local/lib -I/usr/local/include -O3 -march=native -flto -fomit-frame-pointer -D NDEBUG

Here are the undefined references I get:

/tmp/cciTAPCc.ltrans0.ltrans.o: In function `mlpack::kmeans::KMeans<mlpack::metric::LMetric<2, true>, mlpack::kmeans::SampleInitialization, mlpack::kmeans::MaxVarianceNewCluster, mlpack::kmeans::ElkanKMeans, arma::Mat<double> >::Cluster(arma::Mat<double> const&, unsigned long, arma::Row<unsigned long>&, arma::Mat<double>&, bool, bool) [clone ._omp_fn.0]':
<artificial>:(.text+0x3b87): undefined reference to `mlpack::Log::Assert(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/cciTAPCc.ltrans0.ltrans.o: In function `mlpack::kmeans::KMeans<mlpack::metric::LMetric<2, true>, mlpack::kmeans::SampleInitialization, mlpack::kmeans::MaxVarianceNewCluster, mlpack::kmeans::ElkanKMeans, arma::Mat<double> >::Cluster(arma::Mat<double> const&, unsigned long, arma::Mat<double>&, bool)':
<artificial>:(.text+0x8fb1): undefined reference to `mlpack::Log::Info'
<artificial>:(.text+0x8fb6): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0x8fc1): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(unsigned long)'
<artificial>:(.text+0x8fd0): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0x901a): undefined reference to `mlpack::Log::Info'
<artificial>:(.text+0x9023): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0x902e): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(unsigned long)'
<artificial>:(.text+0x903d): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0x904d): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(double)'
<artificial>:(.text+0x905c): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0x90ba): undefined reference to `mlpack::Log::Info'
<artificial>:(.text+0x90bf): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0x90da): undefined reference to `mlpack::Log::Info'
<artificial>:(.text+0x90df): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0x90ea): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(unsigned long)'
<artificial>:(.text+0x90f9): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0x9193): undefined reference to `mlpack::Log::Info'
<artificial>:(.text+0x9198): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0x91a3): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(unsigned long)'
<artificial>:(.text+0x91b2): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0x91c4): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(std::ostream& (*)(std::ostream&))'
<artificial>:(.text+0x91cf): undefined reference to `mlpack::Log::Info'
<artificial>:(.text+0x91d4): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(unsigned long)'
<artificial>:(.text+0x91e3): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0x91ee): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(std::ostream& (*)(std::ostream&))'
<artificial>:(.text+0x929e): undefined reference to `mlpack::math::randGen'
<artificial>:(.text+0x93ae): undefined reference to `mlpack::math::randGen'
<artificial>:(.text+0x948e): undefined reference to `mlpack::math::randGen'
<artificial>:(.text+0x949b): undefined reference to `mlpack::math::randUniformDist'
<artificial>:(.text+0x94a3): undefined reference to `mlpack::math::randUniformDist'
<artificial>:(.text+0x9623): undefined reference to `mlpack::math::randGen'
<artificial>:(.text+0x9645): undefined reference to `mlpack::math::randGen'
<artificial>:(.text+0x9669): undefined reference to `mlpack::math::randGen'
<artificial>:(.text+0x9688): undefined reference to `mlpack::math::randGen'
<artificial>:(.text+0x96a4): undefined reference to `mlpack::math::randGen'
/tmp/cciTAPCc.ltrans0.ltrans.o:<artificial>:(.text+0x96b1): more undefined references to `mlpack::math::randGen' follow
/tmp/cciTAPCc.ltrans0.ltrans.o: In function `mlpack::kmeans::KMeans<mlpack::metric::LMetric<2, true>, mlpack::kmeans::SampleInitialization, mlpack::kmeans::MaxVarianceNewCluster, mlpack::kmeans::ElkanKMeans, arma::Mat<double> >::Cluster(arma::Mat<double> const&, unsigned long, arma::Mat<double>&, bool)':
<artificial>:(.text+0x9fdb): undefined reference to `mlpack::Log::Fatal'
<artificial>:(.text+0x9fe0): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0x9fef): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0xa010): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0xa031): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0xa040): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(std::ostream& (*)(std::ostream&))'
<artificial>:(.text+0xa053): undefined reference to `mlpack::Log::Fatal'
<artificial>:(.text+0xa058): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0xa067): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0xa085): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0xa090): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(unsigned long)'
<artificial>:(.text+0xa09f): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0xa0ae): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(std::ostream& (*)(std::ostream&))'
<artificial>:(.text+0xa13a): undefined reference to `mlpack::Log::Warn'
<artificial>:(.text+0xa13f): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0xa14e): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(std::ostream& (*)(std::ostream&))'
<artificial>:(.text+0xa161): undefined reference to `mlpack::Log::Warn'
<artificial>:(.text+0xa166): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0xa175): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
<artificial>:(.text+0xa184): undefined reference to `mlpack::util::PrefixedOutStream::operator<<(std::ostream& (*)(std::ostream&))'

**Comment by rcurtin** [comment]
Hi @rlichtenwalter,

This looks to me like interference between the distro and hand-compiled packages.  Specifically, the symbols `mlpack::Log::Info`, etc., do not exist in libmlpack.so.2, but they do in libmlpack.so.3.  So I bet that your program is using mlpack 3 headers for compilation, in `/usr/local/include/`, but it's trying to link against mlpack 2 in `/usr/lib/libmlpack.so.2` instead of `/usr/local/lib/libmlpack.so.3` (if that file exists).

So, the options are probably to try and debug the order in which the linker is trying to determine what to link against, or just `apt-get purge libmlpack-dev libmlpack2` and I think things should work. :)

**Comment by rlichtenwalter** [comment]
Hi @rcurtin.

That was one of my thoughts too, but purging those packages, completely cleaning my project, and then rebuilding my project gives exactly the same errors. I shouldn't need to rebuild mlpack itself after the purge, should I?

**Comment by rcurtin** [comment]
Hmm, sometimes this can be an argument ordering issue.  Try the `-L` arguments before the `-l` arguments?  (Also, is `/usr/local/lib/libmlpack.so` the same version as the headers installed in `/usr/local/include/mlpack/`?  (Also, there aren't any stray mlpack headers in `/usr/include/` or anything, somehow left after the purge?))

**Comment by rlichtenwalter** [comment]
Just to provide you with more information, because I left this out, I'm building version 3.3.2.

After doing the purge I also manually purged via:

rm -rf /usr/include/mlpack
rm -f /usr/lib/libmlpack*

Assume that catches it all. Just rebuilt 3.3.2 from scratch (totally removed the download and staging dir) post apt purge and manual purge/check. It builds fine, but when I try to compile my project against it, I get those same link time errors. I'm at a loss. Is there any way I can provide more information to you that could help? I tried placing -L before -l, though it seems that /usr/local/lib is being searched anyhow, but no help there.

**Comment by rcurtin** [comment]
Hmmm, so what I would want to know is what `libmlpack.so` that gcc is trying to link against but I'm not sure how to get it.  Can you do `ls -lh /usr/local/lib/*mlpack*` and maybe we can see what mlpack libraries are in there?  (Hopefully only one!)

Also, I assume you did `make install` after you rebuilt from scratch?

**Comment by rlichtenwalter** [comment]
I'll see if I can do one better; let's look for everything anywhere on the system!

user@host:/$ sudo find / -name 'libmlpack.so*'
/tmp/mlpack-3.3.2/build/lib/libmlpack.so
/tmp/mlpack-3.3.2/build/lib/libmlpack.so.3
/tmp/mlpack-3.3.2/build/lib/libmlpack.so.3.3
/usr/local/lib/libmlpack.so.3
/usr/local/lib/libmlpack.so.3.3
/usr/local/lib/libmlpack.so

The version from the build is the only thing anywhere on the system. And for headers in mlpack include subdirectories:

user@host:/$ sudo find / -type d -name 'mlpack'
/tmp/mlpack-3.3.2/src/mlpack
/tmp/mlpack-3.3.2/src/mlpack/bindings/julia/mlpack
/tmp/mlpack-3.3.2/src/mlpack/bindings/go/mlpack
/tmp/mlpack-3.3.2/src/mlpack/bindings/python/mlpack
/tmp/mlpack-3.3.2/build/src/mlpack
/tmp/mlpack-3.3.2/build/src/mlpack/CMakeFiles/Export/lib/cmake/mlpack
/tmp/mlpack-3.3.2/build/include/mlpack
/tmp/mlpack-3.3.2/build/include/mlpack/bindings/go/mlpack
/tmp/mlpack-3.3.2/build/include/mlpack/bindings/python/mlpack
/usr/local/include/mlpack
/usr/local/include/mlpack/bindings/go/mlpack
/usr/local/include/mlpack/bindings/python/mlpack
/usr/local/lib/cmake/mlpack
/usr/local/lib/python3.7/site-packages/mlpack-3.3.2-py3.7-linux-x86_64.egg/mlpack

Nothing outside the build directory and install target directory here either.

Yes, I'm doing make install with each build. Thanks for hanging with me on this. Let me know if there's any other helpful information I can provide!

**Comment by rlichtenwalter** [comment]
Agreed that it's odd. I'm not as experienced as you, probably, but I've done a fair amount of GNU/Linux sysadmin and software development work, and I've never run into this. I also haven't ever had a problem linking anything else in this particular environment. I still feel like I must be doing something ill-advised and overlooking it, but it seems like there must be some very strange interaction happening.

It's actually not totally trivial for me to bring up a stock Ubuntu container in the Domino environment. Did you happen to try reproducing anywhere and were you able? Other than attempting to reproduce the issue in stock (which I can't believe would have this linking issue) anything else I should be looking at?

**Comment by rlichtenwalter** [comment]
@rcurtin Okay! So the Domino environment won't operate the Ubuntu 18.04 image *completely* stock, but all I did was install a very minimal set of supporting packages that should definitely not be an issue and set up user information. Then I worked through the VSCode plugin. In short, it's essentially stock, and I *did* have the same linking issue.

**Comment by rlichtenwalter** [comment]
And another update. On a hopeful hunch, I tried swapping out ld for gold, and it linked! It seems like we should still get to the bottom of this, so I'm happy to continue diagnostic work. That said, it seems like I have a working binary now.

**Comment by rcurtin** [comment]
Oh, interesting!  I have never played with gold.  I actually did not have a chance to look into this over the weekend, but I'll see if I can learn a bit about gold and try to use it later today to reproduce the problem that you're seeing in a simple Ubuntu Docker container.  Thanks for digging!  I think we can get somewhere with this. :)

**Comment by rlichtenwalter** [comment]
Sounds great! Thanks for all the effort. And just to be clearer in my language, the link issue was with ld, and gold was the linker that worked. I wonder if you'll be able to reproduce at all, though, and looking forward to hearing the outcome.

**Comment by rcurtin** [comment]
I tried creating an Ubuntu 18.04 container, compiling mlpack using the gold linker (with CMake I used `-DCMAKE_CXX_FLAGS="-fuse-ld=gold" -DCMAKE_C_FLAGS="-fuse-ld=gold"`), and then installing to `/usr/local/lib/` with `sudo make install`.

Following this I created a simple program that used the `mlpack::kmeans::KMeans<>` object, and then tried to compile using the GNU `ld` linker like so:

```
g++ -I/usr/local/include -L/usr/local/lib -o test test.cpp -larmadillo -lmlpack -fopenmp
```

However, this succeeded.  I also tried with `gold`:

```
g++ -fuse-ld=gold -I/usr/local/include -L/usr/local/lib -o test test.cpp -larmadillo -lmlpack -fopenmp
```

And this also succeeded.

So, I don't seem to be able to easily reproduce the issue.  As a whim, what happens when you install directly to `/usr/lib/`, with, e.g., `-DCMAKE_INSTALL_PREFIX=/usr/`?  If you do that, then `libmlpack.so` should be on the linker search path.  But, I'm really not sure this will make a difference, since the verbose output from earlier seemed to indicate that the library was successfully being found.

I'm a little bit stumped here---to my understanding, ld and gold should have equivalent functionality.  So maybe there is something about the Domino environment that causes this issue?

**Comment by rlichtenwalter** [comment]
In my case, the failure occurred when I compiled mlpack with the ld linker rather than gold, so no special CMake flags for gold, then linked against it with ld. I haven't used gold in compilation of mlpack. Did you happen to also try that (build mlpack with ld, link against it with ld)? That's what failed.

I have switched to installing libraries to /usr/lib via the CMake parameter: still linker errors.

If you try using ld all the way through on the ubuntu:18.04 public docker image and are still unable to reproduce the error, then the Domino environment becomes the only outstanding variable, though based on everything I know, I cannot understand how it could be.

**Comment by rcurtin** [comment]
Hmm, I actually did try it all four ways (mlpack linked with ld, program linked with gold; and, mlpack linked with gold, program linked with ld; then the two combinations), and wasn't able to reproduce the issue.  So I am somewhat stumped.

But I do have some strange ideas. Is it possible that there is some SELinux policy or similar in this container that is disallowing the linker from using `libmlpack.so`? I am not sure exactly and I'm not an expert on security policy, but maybe some specific container configuration disallows linker access to local .sos or something?

This is a very unexpected issue---past that shot in the dark, I don't really have any other ideas. 👍
