### ISSUE TITLE
How to run neighbor_search from methods? 

### ISSUE THREAD

**Issue by Aminah1992** [mlpack/mlpack#2580]
I finally run mlpack correctly; but unfortunately when I try to run knn_main.cpp from "methods" file 38 error show.
How to run the ready code in src/mlpack/methods/

When I try to run one of them errors occured!!

Error (active)	E0020	identifier "PRINT_DATASET" is undefined	k-nn	C:\mlpack\mlpack\src\mlpack\methods\neighbor_search\knn_main.cpp	52	

Error (active)	E0077	this declaration has no storage class or type specifier	k-nn	C:\mlpack\mlpack\src\mlpack\methods\neighbor_search\knn_main.cpp	38	
![Untitled](https://user-images.githubusercontent.com/69873647/90966988-94983900-e4e1-11ea-9502-882c29abb38f.png)

Error	C1189	#error:  "Unknown binding type!  Be sure BINDING_TYPE is defined if you are "        "including <mlpack/core/util/mlpack_main.hpp>.";	k-nn	C:\mlpack\mlpack\build\include\mlpack\core\util\mlpack_main.hpp	423	

I put in properties-> C/C++ -> General -> Additional Include Directories
C:\mlpack\mlpack\build\include
C:\mlpack\armadillo\include
C:\boost\

I put in properties -> Linker -> General -> Additional Library Directories 
C:\boost\lib64-msvc-14.2\
I put in properties -> Linker -> input-> Additional Dependencies 
C:\mlpack\mlpack\build\Debug\

Please help is needed.

**Comment by zoq** [comment]
Did you follow https://www.mlpack.org/doc/mlpack-3.3.2/doxygen/build_windows.html or one of the tutorials at the end? It's possible to build the knn methods only, but from the screenshot above it looks like you build is based on: https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/neighbor_search/CMakeLists.txt and not https://github.com/mlpack/mlpack/blob/master/CMakeLists.txt?

If you just wanted to build the knn methods, I would recommend to follow the windows instructions and at the point where you build you can call `make mlpack_knn` instead of `make` only to build the specific module.

**Comment by Aminah1992** [comment]
Yes, you are right. And, yes I just want mlpack_knn. 
 I followed the steps that you recommend, but another errors shows up.

![Untitled](https://user-images.githubusercontent.com/69873647/90990875-8adc0780-e5ad-11ea-8ff5-863fbb12da4f.png)


Thank you so much.

**Comment by zoq** [comment]
From the first picture it looks like mlpack can't find armadillo, one of the dependencies mlpack needs for building. Did you install armadillo and is it in the correct location?

**Comment by Aminah1992** [comment]
Yes I did. This is the path of armadillo
C:\mlpack\armadillo 

This is the path of mlpack 
C:\mlpack\mlpack

**Comment by Aminah1992** [comment]
Help is needed here, please.

**Comment by rcurtin** [comment]
Hi @Aminah1992, it looks like you haven't followed the Windows build guide: https://www.mlpack.org/doc/mlpack-3.3.2/doxygen/build_windows.html

Can you try following that fully? Based on your screenshot it looks like CMake isn't being run.

If you're trying to run CMake from Visual Studio and it isn't running correctly, take a look at the output of the failed CMake run, and that can be helpful for diagnosing what could have gone wrong. :+1:

**Comment by Aminah1992** [comment]
Hello @rcurtin , actually I followed every single step in Windows guide. And I could run cmake from command prompt.
![Untitled](https://user-images.githubusercontent.com/69873647/91623456-3fa66800-e9a4-11ea-8d91-9225fc8f3085.png)
![Untitled1](https://user-images.githubusercontent.com/69873647/91623507-6b295280-e9a4-11ea-86d5-a30d1e73e866.png)

**Comment by Aminah1992** [comment]
Hi @rcurtin, 

I did it again from scratch, and every thing is okay until I run a sample code.
I got this run time error.

![Untitled](https://user-images.githubusercontent.com/69873647/91639601-79b54f80-ea20-11ea-9705-72a45c823626.png)

**Comment by Aminah1992** [comment]
I think my problem is from Properties
How to link a program to mlpack 

![Untitled](https://user-images.githubusercontent.com/69873647/91642538-c9057b00-ea34-11ea-9ba4-7df7fe47b8ec.png)

**Comment by zoq** [comment]
Looking at the output, it looks like it can't find the boost header files, can you make sure, `AdditionalIncludeDirectories` is set correctly, it should look similar to:

https://github.com/mlpack/mlpack/blob/933537d4342d82ded35d8470dee59b696f328cdc/doc/examples/sample-ml-app/sample-ml-app/sample-ml-app.vcxproj#L107

You might have to adapt the version and file path.

Same for `AdditionalDependencies`, it should look similar to:

https://github.com/mlpack/mlpack/blob/933537d4342d82ded35d8470dee59b696f328cdc/doc/examples/sample-ml-app/sample-ml-app/sample-ml-app.vcxproj#L112

Hope this is helpful.

**Comment by Aminah1992** [comment]
Thank you, I will try it right away.

**Comment by Aminah1992** [comment]
Yes, you are right. The "sample-ml-app.vcxproj" file has incorrect paths. I changed these paths to the right once, but still have the same errors. 

![Untitled](https://user-images.githubusercontent.com/69873647/91669306-9636b200-eb1c-11ea-93ff-b4da495b9e35.png)

**Comment by Aminah1992** [comment]
I did all the steps again. Here are some screenshots

Here are the screenshot when building Armadillo.sln 
![building Aramdillo](https://user-images.githubusercontent.com/69873647/91748538-ca67ac80-ebc8-11ea-9b77-79b0e0c22ee1.png)

Here are the screenshot when running cmake on build directory in mlpack. I notice that Julia is missing and python is missing. What shell I do ?
![building mlpack](https://user-images.githubusercontent.com/69873647/91748801-36e2ab80-ebc9-11ea-8fcd-f83614c965d0.png)

Here are the screenshot when building mlpack.sln
![building mlpack sln](https://user-images.githubusercontent.com/69873647/91748683-069b0d00-ebc9-11ea-9f2d-7694796629a5.png)

**Comment by zoq** [comment]
`data.csv` is not part of the mlpack repo, you can use: https://github.com/mlpack/mlpack/blob/master/src/mlpack/tests/data/iris_train.csv as an example file. Also, you can ignore the Python and Julia warnings, if you want to use the C++ interface.

**Comment by Aminah1992** [comment]
Okey, I understand. But how about the runtime error ?
it is from the file "prefixedoutstream_imp.hpp"
line 140 
throw std::runtime_error("fatal error; see Log::Fatal output");

**Comment by zoq** [comment]
That's a result from `Log::Fatal` which returns since it can't fine the file.

**Comment by Aminah1992** [comment]
Which file ?
So, is it problem from building mlpack or from coding ?

 I put a sample code and set the Additional Include Directories to boost, Armadillo and mlpack. 

What is the right way of using mlpack?

**Comment by Aminah1992** [comment]
The error is that it can't find Armadillo !!
I followed the windows tutorial latterly.

This is the error 
![Untitled](https://user-images.githubusercontent.com/69873647/92159298-db692580-ee35-11ea-86c6-7380807c4836.png)

Here are the paths of mlpack and armadillo 
![Untitled1](https://user-images.githubusercontent.com/69873647/92159347-eae86e80-ee35-11ea-85d1-f414bc8c0cc9.png)

**Comment by Aminah1992** [comment]
Thank you, 
The problem has been solved

Is there a mlpack metric for laplacian score?

**Comment by Aminah1992** [comment]
Thank you

The problem has been solved.
