### ISSUE TITLE
Will k-medians or k-mediods methods be added?

### ISSUE THREAD

**Issue by zdcrandall** [mlpack/mlpack#2582]
Hi! I am fairly new to mlpack (I only found it a week ago) and I am trying to familiarize myself. I could not find an implementation of k-medians or k-mediods algorithms in the documentation, although I did find k-means! I also did not see anything about them in pull requests or the issues that already exist. Are there plans to add either of these algorithms in the future? Do they exist and I just missed it? Thank you for your help!

**Comment by rcurtin** [comment]
Hi @zdcrandall, those would be great to add!  One of the nice things about our k-means implementation is that it's not just the standard Lloyd's algorithm---there are also several accelerated variants, like Elkan's algorithm, Hamerly's algorithm, and so forth.  I think that k-medians and k-mediods could also have the same kind of optimizations applied to them, though it may not be a trivial conversion.

So, personally, I think it would be great to implement these.  If you're interested in contributing them, or if someone else is, they would be gladly accepted!  We should definitely try to at least implement the Hamerly or Lloyd accelerations though (I think it should be straightforward).

Hopefully this helps---let me know if I can clarify anything. :)

**Comment by zdcrandall** [comment]
@rcurtin Thank you for the informative and friendly response! I do not think that I will be able to contribute this, unfortunately, but I agree it would be great to see them implemented!
