### ISSUE TITLE
Add clang-format to the project

### ISSUE THREAD

**Issue by mikkac** [mlpack/mlpack#2585]
Hi guys, I wanted to start making more contributions to the project, but I noticed, that no clang-format is used (AFAIK no formatter at all). Instead, there are style guidelines defined in [DesignGuidelines](https://github.com/mlpack/mlpack/wiki/DesignGuidelines#style-guidelines)
To be honest, it's getting hard when you contribute to multiple projects at once- it's impossible to remember about all of the rules. Usage of formatter makes things easier.

If you are interested, I could prepare some .clang-format reflecting rules from [DesignGuidelines](https://github.com/mlpack/mlpack/wiki/DesignGuidelines#style-guidelines) (more or less), but I would suggest that some decision-making person could choose one of available base styles (Google, LLVM, Mozzilla, etc.) and decide what style options should differ from the chosen style.

What do you guys think?

**Comment by rcurtin** [comment]
This could be really nice for sure.  It's been discussed in #1203, so you could find some more comments and concerns there.  I imagine that the design guidelines couldn't really be captured very well by clang-format (the style guidelines seem easy though)?

I think actually the style guidelines in https://github.com/mlpack/mlpack/wiki/DesignGuidelines#style-guidelines are pretty close to some base styles, and I don't think it would be a big problem to either adapt the clang-format script for a few quirks we've chosen, or to simply decide as a community that we should remove those quirks.  However, I'm not exactly sure which base style we're closest to.  If you've set up clang-format before and want to lead this effort, I'd be happy to help provide input where it's useful.

**Comment by rcurtin** [comment]
For what it's worth, we do have a style checker that runs in Jenkins on PRs.  But currently we don't have a good way to run that locally.

**Comment by mikkac** [comment]
@rcurtin Thanks for the answer :) I will surely go through those issues in free time and will get back to you. Thanks

**Comment by rcurtin** [comment]
Awesome!  And our style guide is changeable if we need; probably good not to make huge changes, but for smaller changes that make it easier to use `clang-format` it should be easy to get widespread agreement. :+1:

**Comment by Aakash-kaushik** [comment]
Hey @mikkac can I help with this issue ?

**Comment by mikkac** [comment]
Hey @Aakash-kaushik sure- I'm bit occupied lately so I didn't have time to move forward this topic. You are free to propose any solution :smiley_cat:

**Comment by Aakash-kaushik** [comment]
Great I will start with this. :)
