### ISSUE TITLE
Problem with exceptions and OpenMP

### ISSUE THREAD

**Issue by jknightmmcs** [mlpack/mlpack#2589]
#### Issue description

I've managed to find a problem of a following sort:

Let's say that I create RandomForest object with dataset/labels parameters supplied.

For some reason (I didn't dig through that, incoming call parameters are correct - double-checked), once in 10-15 calls I get an std::logic_error exception instead of a trained object (Row::subvec illegal access out of range). 

Because exception is thrown inside OpenMP context, there is no way for me to catch it and try again, program simply crashes.

Turning OpenMP off makes it possible, so I recompiled mlpack without it, and now everything works as desired. After an exception, second retraining with the same dataset usually ends up with a valid object.

I think that for each thread there should be a mechanism of catching exceptions and rethrowing them inside a caller thread, otherwise, multithreading shouldn't be used at all.

#### Your environment

 * version of mlpack: 3.3.2
 * operating system: debian stretch
 * compiler: gcc 9.3.0, compiled from source
 * version of dependencies (Boost/Armadillo): [will add that tomorrow]
 * any other environment information you think is relevant: nothing

#### Steps to reproduce

---

#### Expected behavior

Exceptions should be rethrown inside a caller thread when calling ctrs and methods of objects.

#### Actual behavior

They can't be caught by a caller thread, program dies with SIGABRT.

**Comment by rcurtin** [comment]
Hey @jknightmmcs, thanks for the report.  You are right that exceptions thrown inside of an OpenMP context are hard to deal with, and I want to leave this issue open until we handle that correctly.

But, if you are getting `std::logic_error` exceptions, maybe we should debug that?  Generally in mlpack, errors don't tend to be particularly recoverable (of course this is not an excuse!), so if an exception is being thrown during training, this is definitely not a normal thing and it's not desired.  Would you mind telling me more about the dataset?  If you can reproduce this, or provide a minimum working example, maybe we can find if something else is wrong, or if there is some edge case with the dataset that isn't being handled right or something like this.

**Comment by jknightmmcs** [comment]
@rcurtin, thanks for the response! This seems to be off-topic here, so, when I'll have enough time (in the next week or so), I'll create another issue with minimum working example and headerless dataset.
