### ISSUE TITLE
repeated use of internal Armadillo functionality

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/mlpack#2596]
Internal function "arma::diskio::guess_file_type()" has been marked as deprecated in Armadillo 9.800+, in order to allow mlpack to transition to another solution and to avoid using internal armadillo functionality (which is subject to change and/or removal without notice).

This was popping up as a warning during compilation of mlpack.

However, the current "fix" in mlpack (by @Yashwants19) seems to be a repetition of the same problem (ie. another use of internal functionality) in order to avoid the deprecation warning. Instead of using "arma::diskio::guess_file_type()", mlpack now uses "arma::diskio::guess_file_type_internal()". Clearly this is not the intended result.

See https://github.com/mlpack/mlpack/commit/49f782ad95fc8af41ca23b8ca45442a36808a5a0#r41903672

Related: https://github.com/mlpack/mlpack/pull/2135

**Comment by rcurtin** [comment]
Fixed in #2602.  Thanks for reporting @conradsnicta. :+1:
