### ISSUE TITLE
building mlpack from source failed while accessing 'guess_file_type_internal' from 'arma::disko'

### ISSUE THREAD

**Issue by ashishsiyag** [mlpack/mlpack#2601]
build % make
[  0%] Updating arma_config.hpp (if necessary)
[  0%] Built target mlpack_arma_config
Moving header files to include/mlpack/
[  0%] Built target mlpack_headers
[  1%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/data/load.cpp.o
In file included from /Users/siyagashish/Desktop/open-source/mlpack-3.4.0/src/mlpack/core/data/load.cpp:13:
/Users/siyagashish/Desktop/open-source/mlpack-3.4.0/src/mlpack/core/data/load_impl.hpp:124:30: error: 
      'guess_file_type_internal' is a private member of 'arma::diskio'
    loadType = arma::diskio::guess_file_type_internal(stream);
                             ^
/usr/local/include/armadillo_bits/diskio_bones.hpp:49:37: note: declared private
      here
  inline arma_cold static file_type guess_file_type_internal(std::istream& f);
                                    ^
In file included from /Users/siyagashish/Desktop/open-source/mlpack-3.4.0/src/mlpack/core/data/load.cpp:13:
/Users/siyagashish/Desktop/open-source/mlpack-3.4.0/src/mlpack/core/data/load_impl.hpp:192:32: error: 
      'guess_file_type_internal' is a private member of 'arma::diskio'
      loadType = arma::diskio::guess_file_type_internal(stream);
                               ^
/usr/local/include/armadillo_bits/diskio_bones.hpp:49:37: note: declared private
      here
  inline arma_cold static file_type guess_file_type_internal(std::istream& f);
                                    ^
2 errors generated.
make[2]: *** [src/mlpack/CMakeFiles/mlpack.dir/core/data/load.cpp.o] Error 1
make[1]: *** [src/mlpack/CMakeFiles/mlpack.dir/all] Error 2
make: *** [all] Error 2

How can this be resolved ?

**Comment by ashishsiyag** [comment]
This is what I got while executing 'cmake../'

% cmake ../
-- cotire 1.7.10 loaded.
-- Could NOT find Ensmallen (missing: ENSMALLEN_INCLUDE_DIR) (Required is at least version "2.10.0")
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 27% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 31% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 34% complete]
-- [download 35% complete]
-- [download 36% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 39% complete]
-- [download 40% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 44% complete]
-- [download 45% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 48% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 51% complete]
-- [download 52% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 55% complete]
-- [download 56% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 61% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 67% complete]
-- [download 68% complete]
-- [download 69% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 73% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 76% complete]
-- [download 77% complete]
-- [download 78% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 81% complete]
-- [download 82% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 85% complete]
-- [download 86% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 89% complete]
-- [download 90% complete]
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 94% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
* Closing connection 0
-- Successfully downloaded ensmallen into /Users/siyagashish/Desktop/open-source/mlpack-3.4.0/build/deps/ensmallen-2.14.1/
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
CMake Warning at CMakeLists.txt:582 (message):
  txt2man not found; man pages will not be generated.


-- Not building Markdown bindings.
-- Not building Python bindings.
-- Go not found: Found unsuitable version "go version go1.15 darwin/amd64
", but required is at least "1.11.0" (found /usr/local/bin/go)
cannot find package "gonum.org/v1/gonum/mat" in any of:
	/usr/local/Cellar/go/1.15/libexec/src/gonum.org/v1/gonum/mat (from $GOROOT)
	/Users/siyagashish/go/src/gonum.org/v1/gonum/mat (from $GOPATH)
-- Gonum not found (missing: GONUM_VERSION_STRING) 
-- Not building Go bindings; the following modules are not available: 
    - Go
    - Gonum
-- Could NOT find R_roxygen2 (missing: R_ROXYGEN2) 
-- Could NOT find R_Rcpp (missing: R_RCPP) 
-- Could NOT find R_RcppArmadillo (missing: R_RCPPARMADILLO) 
-- Could NOT find R_RcppEnsmallen (missing: R_RCPPENSMALLEN) 
-- Could NOT find R_BH (missing: R_BH) 
-- Could NOT find R_testthat (missing: R_TESTTHAT) 
-- Not building R bindings, Following modules are not available:
    - roxygen2
    - Rcpp
    - RcppArmadillo
    - RcppEnsmallen
    - BH
    - testthat
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/siyagashish/Desktop/open-source/mlpack-3.4.0/build

**Comment by conradsnicta** [comment]
the associated bug fix is in this PR: https://github.com/mlpack/mlpack/pull/2597

**Comment by rcurtin** [comment]
Thanks @conradsnicta; I'm in the process of resurrecting the other PR you suggested there, hopefully that will be open later today (currently debugging a test).

@ashishsiyag you could either apply that PR to your branch, or another workaround would be to use an older version of Armadillo.

**Comment by ashishsiyag** [comment]
while executing my 'cmake ../' I am getting such response, previously I installed go 1.15, now uninstalled and installed 1.11.0, still it is unable to find go and various other files. how to get them resolved ?

build % cmake ../             
-- cotire 1.7.10 loaded.
-- Found Ensmallen: /usr/local/include (found suitable version "2.14.0", minimum required is "2.10.0") 
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
CMake Warning at CMakeLists.txt:582 (message):
  txt2man not found; man pages will not be generated.


-- Not building Markdown bindings.
-- Not building Python bindings.
-- Go not found: Found unsuitable version "", but required is at least "1.11.0" (found /usr/local/bin/go)
-- Gonum not found (missing: GONUM_VERSION_STRING) 
-- Not building Go bindings; the following modules are not available: 
    - Go
    - Gonum
-- Could NOT find R_roxygen2 (missing: R_ROXYGEN2) 
-- Could NOT find R_Rcpp (missing: R_RCPP) 
-- Could NOT find R_RcppArmadillo (missing: R_RCPPARMADILLO) 
-- Could NOT find R_RcppEnsmallen (missing: R_RCPPENSMALLEN) 
-- Could NOT find R_BH (missing: R_BH) 
-- Could NOT find R_testthat (missing: R_TESTTHAT) 
-- Not building R bindings, Following modules are not available:
    - roxygen2
    - Rcpp
    - RcppArmadillo
    - RcppEnsmallen
    - BH
    - testthat
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/siyagashish/Desktop/open-source/mlpack-3.4.0/build

**Comment by rcurtin** [comment]
It looks like the configuration still succeeds.  If you're not intending to build the Go bindings, you don't need to worry about those messages.  If you *are* intending to build the Go bindings, can you provide the outputs of `/usr/local/bin/go version`?

**Comment by ashishsiyag** [comment]
`siyagashish@Ashishs-MacBook-Air bin % /usr/local/bin/go version`
`go version go1.15 darwin/amd64`

**Comment by ashishsiyag** [comment]
@rcurtin I intend to work on issue #2592 , so before starting with it, I wanted to get mlpack running on my system.

**Comment by rcurtin** [comment]
@ashishsiyag in that case, I wouldn't worry about the Go bindings---you shouldn't need them for development. :+1:

**Comment by jeffin143** [comment]
Hi @ashishsiyag , since you would be working on #2592  I don't think go bindings are necessary just run a sample program to check if everything else is good 
And rest you are good to go

Welcome to the community

**Comment by ashishsiyag** [comment]
Sorry to keep bothering you, running `make mlpack_test` builds successfully but running the tests `bin/mlpack_test` returns error.

`siyagashish@Ashishs-MacBook-Air build % make mlpack_test`          
`[  0%] Updating arma_config.hpp (if necessary)`
`[  0%] Built target mlpack_arma_config`
`Moving header files to include/mlpack/`
`[  0%] Built target mlpack_headers`
`[ 34%] Built target mlpack`
`[100%] Built target mlpack_test`

`siyagashish@Ashishs-MacBook-Air build % bin/mlpack_test -t KNNTest`
`Test setup error: no test cases matching filter or all test cases were disabled`

`siyagashish@Ashishs-MacBook-Air build % bin/mlpack_test           `
`Running 1256 test cases...`
`unknown location:0: fatal error: in "AsyncLearningTest/OneStepQLearningTest": memory access violation at address: 0x11105693a: non-existent physical address`
`/Users/siyagashish/Desktop/open-source/mlpack-3.4.0/src/mlpack/tests/async_learning_test.cpp:37: last checkpoint: "OneStepQLearningTest" test entry`

`*** 1 failure is detected in the test module "mlpackTest"`

**Comment by jeffin143** [comment]
@ashishsiyag , Please refer https://github.com/mlpack/mlpack/pull/2572#issuecomment-678107849 , We recently had some changes with test
https://github.com/mlpack/mlpack/pull/2572#issuecomment-678107849

you can run `./bin/mlpack_catch_test "[KNNTest]"` 

 also about the second issue, can you run 2-3 times to check if that happens every time , I think  it is a random failure, Also The are some memory access violation possible , We have a issue open for that

**Comment by ashishsiyag** [comment]
I deleted the build repo, created new dir build, 
`$ mkdir build`

`$ cd build`

`$ cmake ../`
`-- Configuring done`
`-- Generating done`
`-- Build files have been written to: /Users/siyagashish/Desktop/open-source/mlpack-3.4.0/build`

`$ make mlpack_knn -j1'`
`[100%] Built target mlpack`
`Scanning dependencies of target mlpack_knn`
`[100%] Building CXX object src/mlpack/methods/neighbor_search/CMakeFiles/mlpack_knn.dir/knn_main.cpp.o`
`[100%] Linking CXX executable ../../../../bin/mlpack_knn`
`[100%] Built target mlpack_knn`

`$ make mlpack_test`
`[100%] Linking CXX executable ../../../bin/mlpack_test`
`[100%] Built target mlpack_test`

`$ bin/mlpack_test -t KNNTest`
`Test setup error: no test cases matching filter or all test cases were disabled`

Then I tried with other method logistic regression
`$ make mlpack_logistic_regression`
`[100%] Linking CXX executable ../../../../bin/mlpack_logistic_regression`
`[100%] Built target mlpack_logistic_regression`

`$ bin/mlpack_test -t LogisticRegressionMainTest`
`Running 19 test cases...`
`unknown location:0: fatal error: in "LogisticRegressionMainTest/LRNoResponses": memory access violation at address: 0x10930393a: non-existent physical address`
`/Users/siyagashish/Desktop/open-source/mlpack-3.4.0/src/mlpack/tests/main_tests/logistic_regression_test.cpp:68: last checkpoint: "LRNoResponses" test entry`

`*** 1 failure is detected in the test module "mlpackTest"`

I don't how to resolve this, now I am trying to install mlpack to the system and run it through a program, see if that works.

**Comment by jeffin143** [comment]
@ashishsiyag please read the above comment and linked comment we migrated some of the test from boost to catch 

bin/mlpack_test -t KNNTest is wrong 

And knn is in not in mlpack_test it's in mlpack_catch_test , mlpack_catcg_test are all test written in catch where is the other one is boost

So please build ` make mlpack_catch_test ` and then run

bin/mlpack_catch_test "[KNNTest]"

**Comment by ashishsiyag** [comment]
`siyagashish@Ashishs-MacBook-Air build % bin/mlpack_catch_test "[KNNTest]"`
`mlpack version: mlpack 3.4.0`
`armadillo version: 9.900.3 (Nocturnal Misbehaviour)`
`zsh: bus error  bin/mlpack_catch_test "[KNNTest]"`
