### ISSUE TITLE
getting error in building mlpack

### ISSUE THREAD

**Issue by 1sarthakbhardwaj** [mlpack/mlpack#2606]
CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1947 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.65.1

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_unit_test_framework

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:440 (find_package)

-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
CMake Warning at CMakeLists.txt:582 (message):
  txt2man not found; man pages will not be generated.

-- Julia not found (missing: JULIA_EXECUTABLE) (Required is at least version "0.7.0")
-- Julia not found; not building Julia bindings.
-- Not building Markdown bindings.
-- Not building Python bindings.
-- Go not found (missing: GO_EXECUTABLE) (Required is at least version "1.11.0")
-- Gonum not found (missing: GONUM_VERSION_STRING) 
-- Not building Go bindings; the following modules are not available: 
    - Go
    - Gonum
-- R not found (missing: R_EXECUTABLE) (Required is at least version "4.0")
-- Could NOT find R_roxygen2 (missing: R_ROXYGEN2) 
-- Could NOT find R_Rcpp (missing: R_RCPP) 
-- Could NOT find R_RcppArmadillo (missing: R_RCPPARMADILLO) 
-- Could NOT find R_RcppEnsmallen (missing: R_RCPPENSMALLEN) 
-- Could NOT find R_BH (missing: R_BH) 
-- Could NOT find R_testthat (missing: R_TESTTHAT) 
-- Not building R bindings, Following modules are not available:
    - R
    - roxygen2
    - Rcpp
    - RcppArmadillo
    - RcppEnsmallen
    - BH
    - testthat
-- Configuring incomplete, errors occurred!
s!

-->

#### Issue description
this is the error showing when I am building mlpack in my system.
$ wget https://www.mlpack.org/files/mlpack-3.4.0.tar.gz
$ tar -xvzpf mlpack-3.4.0.tar.gz
$ mkdir mlpack-3.4.0/build && cd mlpack-3.4.0/build
$ cmake ../
$ make -j4  # The -j is the number of cores you want to use for a build.
$ sudo make install

#### Your environment

 * version of mlpack:3.4.0
 * operating system:ubuntu 18.04
 * compiler:tilix
 * version of dependencies (Boost/Armadillo):Armadillo
 * any other environment information you think is relevant:

**Comment by rcurtin** [comment]
Do you have the boost unit test framework installed? The error messages indicates that it is not installed.

**Comment by 1sarthakbhardwaj** [comment]
i have done same as directed in this page
https://www.mlpack.org/doc/mlpack-git/doxygen/build.html#build_dep

after your suggestion I have installed boost unit test framework but it is
showing a lot more files that are not found what about that.




-- Julia not found (missing: JULIA_EXECUTABLE) (Required is at least
version "0.7.0")
-- Julia not found; not building Julia bindings.
-- Not building Markdown bindings.
-- Not building Python bindings.
-- Go not found (missing: GO_EXECUTABLE) (Required is at least version
"1.11.0")
-- Gonum not found (missing: GONUM_VERSION_STRING)
-- Not building Go bindings; the following modules are not available:
    - Go
    - Gonum
-- R not found (missing: R_EXECUTABLE) (Required is at least version "4.0")
-- Could NOT find R_roxygen2 (missing: R_ROXYGEN2)
-- Could NOT find R_Rcpp (missing: R_RCPP)
-- Could NOT find R_RcppArmadillo (missing: R_RCPPARMADILLO)
-- Could NOT find R_RcppEnsmallen (missing: R_RCPPENSMALLEN)
-- Could NOT find R_BH (missing: R_BH)
-- Could NOT find R_testthat (missing: R_TESTTHAT)
-- Not building R bindings, Following modules are not available:
    - R
    - roxygen2
    - Rcpp
    - RcppArmadillo
    - RcppEnsmallen
    - BH
    - testthat
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- CXX target mlpack cotired.
-- CXX target mlpack_test cotired.
-- CXX target mlpack_catch_test cotired.
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found
components:  doxygen dot
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Configuring done
-- Generating done

**Comment by zoq** [comment]
As long as you don't want to build the R, Julia or Go bindings you can ignore the warnings.

**Comment by blackhat-7** [comment]
I faced the same issue even after installing boost, but just removing the "build" directory that I had made and then redoing cmake ../ after creating a new "build" directory solved the problem.
So in short just run the following commands in the mlpack dir after installing all the necessary dependencies:
```
rm -r build
mkdir build
cd build && cmake../
```
