### ISSUE TITLE
Facing problem when adding a new distance metric to mlpack.

### ISSUE THREAD

**Issue by ASQWZXED** [mlpack/mlpack#2610]
Hi, I tried to write a distance metric, but there are two errors. I don't know how to remove them.

This is my code:

#include <mlpack/core.hpp> 
#include <mlpack/methods/neighbor_search/neighbor_search.hpp> 

using namespace std;
using namespace mlpack;
using namespace mlpack::neighbor;
using namespace mlpack::metric;

class ExampleMetric
{
	// Default constructor is required.
	ExampleMetric() { }
	// The example metric holds no state, so we can mark Evaluate() as static.
	template<typename VecTypeA, typename VecTypeB>
	static double Evaluate(const VecTypeA& a, const VecTypeB& b)
	{
		
		return arma::exp(-((arma::square(arma::abs(a[0] - b[0]))) / (arma::sqrt(2))));
	}
};

void mlModel()
{
	 
	arma::mat data;
	data::Load("iris_train.csv", data, true);
	NeighborSearch<NearestNeighborSort, ExampleMetric> model(data);

	arma::Mat<size_t> neighbors; 
	arma::mat distances;
	model.Search(2, neighbors, distances);

	for (size_t i = 0; i < neighbors.n_elem; ++i)
	{
		cout << "Nearest neighbor of point " << i << " : "
			<< neighbors[i] << " and the Distance : "
			<< distances[i] << ".\n";
	}
}

int main()
{
	mlModel();
	return 0;
}

This is the error:
![Untitled](https://user-images.githubusercontent.com/69873647/92419231-e0e7a800-f174-11ea-802f-a535fd23929e.png)

**Comment by UtR491** [comment]
Make you constructor and `Evaluate` function public. The [second error](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2248?view=vs-2019) says they are private(default). For the [first error](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2338?view=vs-2019) may be sharing the code in `hrectbound.hpp` will help?

**Comment by ASQWZXED** [comment]
He @UtR491, I put them public and the second error disappear. 
First error I put my code in  hrectbound.hpp file and another error shows up.
 I know that I have to put my code in a .hpp file, but I don't know which one.
![Untitled](https://user-images.githubusercontent.com/69873647/92468501-efb57580-f1db-11ea-8f10-9206fede43f1.png)
Thank you for helping

**Comment by UtR491** [comment]
Umm, I am not sure that I get what you mean.The error is in line 57 of `hrectbound.hpp` can you share the code here?

**Comment by ASQWZXED** [comment]
Yes, sure.

This is line 57
static_assert(meta::IsLMetric<MetricType>::Value == true,
      "HRectBound can only be used with the LMetric<> metric type.");

Here is the screenshot.
![Untitled](https://user-images.githubusercontent.com/69873647/92497961-b04e4f80-f202-11ea-8ff9-1c352f577913.png)

**Comment by UtR491** [comment]
Maybe just copy paste the entire code here?:sweat_smile: So that I can see what is in the meta namespace and where the Value variable becomes false?

**Comment by ASQWZXED** [comment]
Here is the code That I wrote: 

#include <iostream>
#include <mlpack/core.hpp> 
#include <mlpack/methods/neighbor_search/neighbor_search.hpp> 


using namespace std;
using namespace mlpack;

using namespace mlpack::neighbor;
using namespace mlpack::metric;

class ExampleMetric
{
public:
	ExampleMetric() { }
	template<typename VecTypeA, typename VecTypeB>
	static double Evaluate(const VecTypeA& a, const VecTypeB& b)
	{
		
		return arma::exp(-((arma::square(arma::abs(a[0] - b[0]))) / (arma::sqrt(2))));
	}
};

void mlModel()
{
	arma::mat data;

	data::Load("iris_train.csv", data, true);

	
	
	NeighborSearch<NearestNeighborSort, ExampleMetric> model(data);
	


	arma::Mat<size_t> neighbors; // Matrices to hold 
	arma::mat distances; // the results 


	model.Search(2, neighbors, distances);


	for (size_t i = 0; i < neighbors.n_elem; ++i)
	{
		cout << "Nearest neighbor of point " << i << " : "
			<< neighbors[i] << " and the Distance : "
			<< distances[i] << ".\n";
	}
}
int main()
{
	mlModel();
	return 0;
}

**Comment by kartikdutt18** [comment]
Hey @ASQWZXED,
In the above code could make all functions public by adding `public:` after the opening bracket.

**Comment by UtR491** [comment]
@kartikdutt18 I was wondering what is `hrectbound.hpp` doing here?

**Comment by kartikdutt18** [comment]
I think this issue might be relevant, #1149. Kindly let me know if this is of any help.

**Comment by ASQWZXED** [comment]
Yes, you are right. When I put the type of tree as #1149 it works. 
But another errors comes up, it is from the formula that I have wrote.

It is from this line 
return arma::exp(-((arma::square(arma::abs(a - b))) / (arma::sqrt(2))));

![Untitled](https://user-images.githubusercontent.com/69873647/92516293-a8e86f80-f21d-11ea-83ef-bdbefdda7379.png)

**Comment by kartikdutt18** [comment]
> arma::exp(-((arma::square(arma::abs(a - b))) / (arma::sqrt(2))));
In the above line, we can't use sqrt in arma namespace for scaler type (here, 2). Here we would use the one in std namespace.
So the expression should be :
```
arma::exp(-((arma::square(arma::abs(a - b))) / (std::sqrt(2))));
```

Also note that you need to return a double and not a vector / arma type.

**Comment by ASQWZXED** [comment]
Okay, I figured out. 
But there is an error about converting from const vector to double .

![Untitled](https://user-images.githubusercontent.com/69873647/92557184-4e2e3280-f274-11ea-804f-b1e355f6f163.png)

**Comment by kartikdutt18** [comment]
Yeah, because as above, you are returning a vector instead of double. I think you need to correct the expression. In C++ return type is specified at time of function declaration and whatever you return must match that type. This might be [useful](https://www.w3schools.com/cpp/cpp_functions.asp).

**Comment by ASQWZXED** [comment]
Okay, I have several stupid questions, I spent hours on this project but it needs more time and it is my first time dealing with mlpack. 

First question about the data in the file such as iris_train.csv . Is each row a data and its dimensions? I couldn't figure out how to read it. I want a data points with dimensions for knn.
Second question about  mlpack::kernel::LaplacianKernel    is it the laplacian score for feature selection like in this paper
 https://papers.nips.cc/paper/2909-laplacian-score-for-feature-selection.pdf 


Thank you so much for helping

**Comment by ASQWZXED** [comment]
It is the same.
Thank you
