### ISSUE TITLE
The given MLAlgorithm requires the numClasses parameter

### ISSUE THREAD

**Issue by GLmontanari** [mlpack/mlpack#2614]
Hello!
I'am facing this issue upon build of this short piece of code:

```
int numClasses = 2;
double validationSize = 0.2;
SimpleCV<DecisionTree<>, Accuracy> scv(validationSize, testData, testLabel, numClasses);
```
where `testData` and `testLabel` are non empty.

I have tried more or less all the constructors for `SimpleCV` but I get the same error

> C2338 The given MLAlgorithm requires the numClasses parameter

located in cv_base_impl.hpp at line 28

What is the correct way to do it?

I am using mlpack-3.3.2 and Visual Studio 2017 on Windows 10, SDK version 10.0.17763.0.
Release + x64.

**Comment by GLmontanari** [comment]
Sorry. I have just noticed that the type of numClasses should be `size_t` and not `int`.
I wasted a lot of time just because the compiler wasn't signaling the type mismatch but it was quite a simple case.
Closing the issue.

**Comment by rcurtin** [comment]
@GLmontanari a little while ago I encountered the same issue and it was a bit time-consuming.  Sorry that you encountered it too!  I opened https://github.com/mlpack/mlpack/pull/2617 which hopefully should improve the error output there.  Let me know what you think. :+1:
