### ISSUE TITLE
How to use KNN with Laplacian ?

### ISSUE THREAD

**Issue by ASQWZXED** [mlpack/mlpack#2616]
I want to write run KNN with k>1 using lapacian.

When I put it like that an error shows up.
NeighborSearch < NearestNeighborSort, mlpack::kernel::LaplacianKernel, arma::mat, mlpack::tree::RPTree> KNN(data);

The error:

Error C2338	HRectBound can only be used with the LMetric<> metric type.	lack	C:\DEV\vcpkg\installed\x64-windows\include\mlpack\core\tree\hrectbound.hpp	57

**Comment by rcurtin** [comment]
`NeighborSearch` is for kNN in metric spaces.  But `LaplacianKernel` is not a metric, it's a kernel.  It has different properties.  If your goal is to find points with maximum `LaplacianKernel::Evaluate()` values between them, then you probably want to use the `FastMKS` class, which is built for similarity search in non-metric spaces with kernels. :+1:

**Comment by ASQWZXED** [comment]
Hello @rcurtin 
Okay I understand. I want to use KNN but I thought I could use laplacian to measure the similarity between neighbors in KNN.


When I run a sample code for KNN I got errors.
Could you please help?
 
![Untitled](https://user-images.githubusercontent.com/69873647/93004767-d2253a80-f552-11ea-9f9d-7709b510cc39.png)

**Comment by ASQWZXED** [comment]
Hi @rcurtin 

I run this code for KNN. 

#include <iostream>
#include <mlpack/core.hpp> 
#include <mlpack/methods/neighbor_search/neighbor_search.hpp>
using namespace mlpack;
using namespace mlpack::neighbor;
using namespace std;
using namespace arma;


void mlModel() {
arma::mat data;
data::Load("iris_train.csv", data, true);
KNN a(data);

// The matrices we will store output in.
arma::Mat<size_t> Neighbors;
arma::mat Distances;

a.Search(5, Neighbors, Distances);

for (size_t i = 0; i < Neighbors.n_cols; ++i)
{
	cout << "Nearest neighbor of point " << i << " : "
		<< Neighbors.col(i).t() << " and the Distance :                 "
		<< Distances.col(i).t() << ".\n";
}

data::Save("Distances.csv", Distances, true);
data::Save("Neighbors.csv", Neighbors, true);

}
int main()
{
	mlModel();
	return 0;
}

The code has no problem

The problem is that, the data in the Console is different form the data in the Neighbors.csv, and Distances.csv.

It seems the data in Console is the correct one because in the files some times the point become a neighbor to its self and some times not!!

Is there a problem in the code?

**Comment by ASQWZXED** [comment]
Please, help is needed here.
