### ISSUE TITLE
mnist_cnn.cpp bug - exception thrown 

### ISSUE THREAD

**Issue by lewisj34** [mlpack/mlpack#2623]
#### Issue description

Hello. I've tried running the mnist_cnn.cpp file essentially identical to the way it was provided [here in the mlpack examples github repo](https://github.com/mlpack/examples/blob/master/mnist_cnn/mnist_cnn.cpp)

`Exception thrown at 0x00007FFFEEC912DE (vcruntime140.dll) in mnist_cnn.exe: 0xC0000005: Access violation reading location 0x0000019EFBC5B000.`

#### Your environment

 * version of mlpack: 3.4.1
 * operating system: Windows 10 
 * compiler: Microsoft C++ compiler
 * version of dependencies (Boost/Armadillo): 1.7.4, 9.9.2

#### Steps to reproduce

Just run [this in visual studio or whatever IDE you use](https://github.com/mlpack/examples/blob/master/mnist_cnn/mnist_cnn.cpp) but make the modification in the train function as shown below: 

`model.Train(trainX,
        trainY,
        optimizer,
        ens::PrintLoss(),
        ens::ProgressBar(),
        // Stop the training using Early Stop at min loss.
        ens::EarlyStopAtMinLoss(25));`

Notice how the lamda function was removed in the EarlyStopAtMinLoss. 

#### Expected behavior

The model trains 

#### Actual behavior

`Exception thrown at 0x00007FFFEEC912DE (vcruntime140.dll) in mnist_cnn.exe: 0xC0000005: Access violation reading location 0x0000019EFBC5B000.`

And looking at the call stack it looks like it is messing up in: 

'mnist_cnn_from_mlpack_website.exe!mlpack::ann::Convolution<mlpack::ann::NaiveConvolution<mlpack::ann::ValidConvolution>,mlpack::ann::NaiveConvolution<mlpack::ann::FullConvolution>,mlpack::ann::NaiveConvolution<mlpack::ann::ValidConvolution>,arma::Mat<double>,arma::Mat<double>>::Gradient<double>(const arma::Mat<double> && error, arma::Mat<double> && gradient, arma::Mat<double> &&) Line 361	C++'

Any help would be appreciated as I am new to this library.

Cheers!

**Comment by kartikdutt18** [comment]
Hey @lewisj34,
I made the changes you suggested i.e. change lambda function to 25 in EarlyStopMinLoss. It works fine for me. If possible, could you also share the complete code, it might help in getting more info.
Thanks.

**Comment by lewisj34** [comment]
Hey @kartikdutt18 thanks for looking into this 

[here](https://github.com/lewisj34/mnist_cnn) is the repo with my code

**Comment by kartikdutt18** [comment]
I tried the code in the above repo. It works for me. I'm using OSX and maybe this problem is associated with windows only not sure. Here is the output.
<img width="1134" alt="Screenshot 2020-09-16 at 8 55 15 PM" src="https://user-images.githubusercontent.com/39593019/93358318-f341a000-f85e-11ea-93a0-45b70a2a53a3.png">

**Comment by lewisj34** [comment]
Alright. Thanks for your help. 

Something must have gone wrong with my build in CMake. I'll try that process again and close this for now.

**Comment by kartikdutt18** [comment]
No worries, maybe you could try reaching out to a windows user on the IRC for this issue, they might provide better insight.
cc : @rcurtin

**Comment by rcurtin** [comment]
Hey @lewisj34, if @kartikdutt18 wasn't able to reproduce it I probably won't be able to either.  (I don't have a Windows machine.)  Let us know if you have success once you've reconfigured CMake, etc. :+1:

If it does fail again, maybe can you provide a full backtrace so we can know where it's failing?  Or, at least, what part of `main.cpp` we are in when it fails.

**Comment by lewisj34** [comment]
All good fellas!!!!!!! I got it working.

Thanks for your help my dudes!!
