### ISSUE TITLE
Add Copy and Move Constructor in every layer

### ISSUE THREAD

**Issue by geekypathak21** [mlpack/mlpack#2625]
### What is the desired addition or change?
Right now we don't have implementation of copy and move constructors in layer which is causing memory issues.

### What is the motivation for this feature?
Follow #2314 to see the memory issues we were facing.

### If applicable, describe how this feature would be implemented.
For reference take a look at #2583 copy and move constructors of `Linear` layer.

### Additional information?
These layers require copy and move constructors also make sure to add tests. We can basically use `CheckCopyFunction()` and `CheckMoveFunction()` (check #2583) for testing in case of `FFN` otherwise we have to add something like these functions for testing.
 * [x]   LinearLayer
 * [ ]   AdaptiveMaxPooling
 * [ ]   AdaptiveMeanPooling
 * [ ]   AddMerge
 * [ ]   AtrousConvolution
 * [ ]   BatchNorm
 * [ ]   BilinearInterpolation
 * [ ]   Concat
 * [ ]   ConcatPerformance
 * [ ]   Concatenate
 * [x]   Convolution
 * [ ]   Dropconnect
 * [x]   Dropout
 * [ ]   FastLstm
 * [ ]   Glimpse
 * [ ]   GRU
 * [ ]   Highway
 * [ ]   Join
 * [ ]   LayerNorm
 * [x]   Linear3D
 * [ ]   LinearNoBias
 * [ ]   Lookup
 * [x]   LSTM
 * [ ]   MaxPooling
 * [ ]   MeanPooling
 * [ ]  MiniBatchDiscrimination
 * [ ]  MultiheadAttention
 * [ ]  MultiplyConstant
 * [ ]  MultilplyMerge
 * [x]  NoisyLinear
 * [ ]  PositionalEncoding
 * [ ]  RBF 
 * [ ]  RecurrentAttention
 * [ ]  ReinforceNormal
 * [ ]  Reparameterization
 * [ ]  Select
 * [x]  Sequential
 * [ ]  SpatialDropout
 * [ ]  WeightNorm
 * [ ]  TransposedConvolution
 * [ ]  VirtualBatchNorm

**Comment by heisenbuug** [comment]
Hey, there is a long list of layers, I hope I can start with `AdaptiveMaxPooling`
Or is there any specific order to implement these?

**Comment by kartikdutt18** [comment]
Taking up BatchNorm and Convolution layers. Thanks for opening the issue.

**Comment by gaurav-singh1998** [comment]
Hi, I'd like to take up MaxPooling and MeanPooling. Thanks.

**Comment by codeboy5** [comment]
Taking up `AdaptiveMeanPooling` and `Dropout`. Thanks !

**Comment by Shravanpmk** [comment]
Hi , I would like to contribute to this , can anyone please help me on how to start with this & How to make my contribution ?

**Comment by MohomedShalik** [comment]
Hi, I would like to contribute to this repository, any advice would be appreciated

**Comment by RishabhGarg108** [comment]
Hey everyone, I am new to mlpack and open source and looking to work on this issue. Can someone please guide me how to start on this issue. Thanks.

**Comment by RishabhGarg108** [comment]
I am taking `Linear3D` and `LinearNoBias`. Thanks!

**Comment by heisenbuug** [comment]
Taking up AddMerge

**Comment by AvikantSrivastava** [comment]
I would like to take LSTM and GRU

**Comment by Abilityguy** [comment]
Taking up FastLstm.

**Comment by indrajeet2000** [comment]
Hi @himanshupathak21061998, I would like to work on AddMerge layer.

**Comment by AvikantSrivastava** [comment]
If no one is working on MaxPooling and MeanPooling, I would like to take it.

**Comment by gauravghati** [comment]
I'm taking `RecurrentAttention` and `ReinforceNormal`.

**Comment by Anmol2001** [comment]
I am taking `Reparameterization` and `Select`

**Comment by abhivarma07** [comment]
Hey , I am new to open source projects and really excited to contribute to MLpack .
So any pre-requisites to start ? or can I just take up this issue ?? 
What are the layers that are still left to get copy and move constructors ? 
Thanks in advance for helping :) .

**Comment by hello-fri-end** [comment]
Hi ! Are there any layers that are left?

**Comment by deeplearningera** [comment]
Hi there, taking up  Sequential and RBF.

**Comment by deeplearningera** [comment]
@kartikdutt18 We can work on this issue or not?

**Comment by kartikdutt18** [comment]
If this hasn't been done, please feel free to take up this issue.

**Comment by deeplearningera** [comment]
> 
> 
> If this hasn't been done, please feel free to take up this issue.

Sure, Thanks!

**Comment by SuvarshaChennareddy** [comment]
I'll take up LayerNorm.

**Comment by dnabanita7** [comment]
taking up max pooling and mean pooling

**Comment by StevenPhang22** [comment]
I'll work on Highway

**Comment by Shashank-Shet** [comment]
May I work on TransposedConvolution?

**Comment by rcurtin** [comment]
I have been working on the refactoring of the ANN code in #2777, and those changes significantly modify the ANN code in such a way that new implementations of copy and move constructors and operators would likely be hard to merge.

So, I think for now we should "pause" this one until that refactoring is complete.  I *think* that what will likely happen is that we will merge #2777 with support for some, but not all, layers, and then we will have to have an issue to transition each individual layer to the "new" style that uses inheritance instead of boost::visitor, and during that transition is when this issue will be handled.

I'll post another update here as that becomes more clear.

**Comment by rcurtin** [comment]
Now that #2777 is merged, any non-adapted layers do have copy and move constructors!  So I think we can call this handled.  Of course, as we adapt the rest of the layers, they will need copy and move constructors, but I think that will happen naturally and there is no need for a specific issue for it.  Thank you to everyone who helped out here!
