### ISSUE TITLE
 The data in the Console is different form the data in the Neighbors.csv, and Distances.csv. Where is the error ?

### ISSUE THREAD

**Issue by ASQWZXED** [mlpack/mlpack#2628]
I run this code for KNN.

#include
#include <mlpack/core.hpp>
#include <mlpack/methods/neighbor_search/neighbor_search.hpp>
using namespace mlpack;
using namespace mlpack::neighbor;
using namespace std;
using namespace arma;

void mlModel() {
arma::mat data;
data::Load("iris_train.csv", data, true);
KNN a(data);

// The matrices we will store output in.
arma::Mat<size_t> Neighbors;
arma::mat Distances;

a.Search(5, Neighbors, Distances);

for (size_t i = 0; i < Neighbors.n_cols; ++i)
{
cout << "Nearest neighbor of point " << i << " : "
<< Neighbors.col(i).t() << " and the Distance : "
<< Distances.col(i).t() << ".\n";
}

data::Save("Distances.csv", Distances, true);
data::Save("Neighbors.csv", Neighbors, true);

}
int main()
{
mlModel();
return 0;
}

The code has no problem

The problem is that, the data in the Console is different form the data in the Neighbors.csv, and Distances.csv.

It seems the data in Console is the correct one because in the files some times the point become a neighbor to its self and some times not!!

Is there a problem in the code?

**Comment by ASQWZXED** [comment]
![1](https://user-images.githubusercontent.com/69873647/93721674-6a966d00-fb9a-11ea-8011-b54450dd9604.png)

**Comment by rcurtin** [comment]
C++ is zero indexed (array indexes start from 0). Your program printing row numbers is one indexed. If you subtract one from the row number, the results are correct. This is expected behavior. :+1:

**Comment by ASQWZXED** [comment]
You are right, 

Thank you so much.

**Comment by ASQWZXED** [comment]
Is the knn pairwise similarity? 
From the output it is a pairwise similarity but I want to be sure 100%.

**Comment by rcurtin** [comment]
When using the `mlpack_knn` command-line program, the distance metric used is the Euclidean distance.

**Comment by ASQWZXED** [comment]
What I understand is that, if I use Euclidean distance, squared Euclidean distance and Manhattan distance, then the result will be pairwise similarity. 

But if I use chebyshev Distance then the result will not be a pairwise similarity. 

Am I right? 
Please rectify me if this is wrong. 
Thank you

**Comment by rcurtin** [comment]
If you use the Euclidean distance, squared Euclidean distance, Manhattan distance, *or* Chebyshev distance, all of these return *distances* not pairwise similarity.  Those are different things.

**Comment by ASQWZXED** [comment]
Hello @rcurtin, that is really good, because this is what I am looking for.
Okay, how can I print out the tree contents ?

Please I need an answer for this question. I have tried many build in functions but I couldn't print out the leaves and the detailed about tree.

**Comment by ASQWZXED** [comment]
Hello @rcurtin, that is really good.

Thank you.
