### ISSUE TITLE
DecisionTree performing poorly  on simple datasets

### ISSUE THREAD

**Issue by GLmontanari** [mlpack/mlpack#2630]
#### Issue description

Hello, 

I'm trying to fine tune a DecisionTree classifier. The call to Optimize() returns the first value in each vector of parameters instead of looking for the best ones.

#### My environment

 * version of mlpack: 3.4.1
 * operating system: Windows 10
 * compiler: msvc 14.6
 * version of dependencies (Boost/Armadillo): boost 1.64, armadillo 9.900.1

#### Steps to reproduce

Here is my code.

```
	double test_perc = 0.5;
	size_t numClasses = 2;
	double validationSize = 0.2;
	arma::vec leaf_sizes{ 2, 5, 10, 15, 20, 30 };
	arma::vec min_splits{ 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9 };
	arma::vec depths{ 2, 3, 5, 10, 13, 20 };

	mlpack::data::Split(data, labels, train_x, test_x, train_y, test_y, test_perc);

	mlpack::hpt::HyperParameterTuner<mlpack::tree::DecisionTree<>,
		mlpack::cv::Accuracy,
		mlpack::cv::SimpleCV, 
		ens::GridSearch> hpt(validationSize, train_x, train_y, numClasses);

	// grid search + get best model
	size_t best_leaf, best_depth;
	double best_split;

	std::tie(best_leaf, best_split, best_depth) = hpt.Optimize(leaf_sizes, min_splits, depths);

	mlpack::tree::DecisionTree<> clf = hpt.BestModel();
	std::cout << "Best score: " << hpt.BestObjective() << "\n";
	std::cout << "min_leaf_split: " << best_leaf << "\n";
	std::cout << "max_depth: " << best_depth << "\n";
	std::cout << "min_split_gain: " << best_split << "\n";
```

#### Expected behavior

I was expecting to find the best choice for each parameter in the `std::tie` but got the first value from each vector instead.

#### Actual behavior

Moreover. I always get Best score = 1 while I am getting lower (and more credible) accuracy scores, around 95% using other libraries.

p.s.: should I attach the data I used?

**Comment by GLmontanari** [comment]
Changing dataset solved the problem. Closing this issue.

**Comment by GLmontanari** [comment]
![test2](https://user-images.githubusercontent.com/43607219/93992780-43a08c80-fd8e-11ea-8889-46aa01634ebe.png)

**Comment by GLmontanari** [comment]
Actually the DecisionTree seems to struggle on too simple problems, like the above one.
If for instance I labeled reddish pixels as class "0" and bluish pixels as class "1". I would get a poor result even though the Best score return from the function hpt.BestObjective() is = 1;

**Comment by GLmontanari** [comment]
Some rows from the data file are like these:
```
labels, r, g, b
0,164,73,163
0,164,73,163
1,232,162,0
1,232,162,0
```

And here is how I fed it to the classifier:
```
	// LOAD
	printf("Loading Data...\n");
	arma::mat full;
	mlpack::data::DatasetInfo info;
	mlpack::data::Load(filename, full, info, false, true);

	printf("Splitting data:...\n");
	arma::mat data = full.submat(arma::span(1, 3), arma::span::all);  // data only

	arma::rowvec lb = full.row(0);
	arma::Row<size_t> lb_u = arma::conv_to<arma::Row<size_t>>::from(lb);

	// TRAIN TEST SPLIT
	arma::mat trainData;
	arma::mat testData;
	arma::Row<size_t> trainLabel;
	arma::Row<size_t> testLabel;
	mlpack::data::Split(data, lb_u, trainData, testData, trainLabel, testLabel, 0.65);
	std::cout << trainLabel.n_cols << " samples are being evaluated...\n";
	// TRAINING + VALIDATION
	size_t numClasses = 2;
	double validationSize = 0.2;

	arma::Col<size_t> leaf_sizes{ 2, 5, 10, 15, 20, 30 };
	arma::vec min_splits{ 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9 };
	arma::Col<size_t> depths{ 2, 3, 5, 10, 13, 20, 30 };

	// hpt
	mlpack::hpt::HyperParameterTuner<mlpack::tree::DecisionTree<>,
		mlpack::cv::Accuracy,
		mlpack::cv::SimpleCV> hpt(validationSize, trainData, trainLabel, numClasses);

	size_t best_leaf, best_depth, best_class;
	double best_split;

	printf("Searching grid parameters and generating cube...\n");
	std::tie(best_leaf, best_split, best_depth) = hpt.Optimize(leaf_sizes, min_splits, depths);

	std::cout << "Best score: " << hpt.BestObjective() << "\n";
	std::cout << "min_leaf_split: " << best_leaf << "\n";
	std::cout << "max_depth: " << best_depth << "\n";
	std::cout << "min_split_gain: " << best_split << "\n";
	mlpack::tree::DecisionTree<> clf = hpt.BestModel();
```

**Comment by GLmontanari** [comment]
Here is how I generate a "prediction image" using opencv:

```
#include <opencv2/opencv.hpp>

// A color palette
cv::Vec3b palette[4] = { cv::Vec3b(36, 28, 237),  // red
	cv::Vec3b(76, 177, 34),  // green
};

cv::Mat src_img = cv::imread("test.png", cv::IMREAD_UNCHANGED);
cv::Mat dst_img(src_img.rows, src_img.cols, CV_8UC3); // prediction image

for (size_t i = 0; i < src_img.rows; i++)
{
	for (size_t j = 0; j < src_img.cols; j++)
	{
		uchar x = src_img.at<cv::Vec4b>(i, j).val[0];
		uchar y = src_img.at<cv::Vec4b>(i, j).val[1];
		uchar z = src_img.at<cv::Vec4b>(i, j).val[2];
		
                arma::rowvec xp = { (double)x, (double)y, (double)z };  // Classify needs 'double'
		int prediction = (int)(clf.Classify(xp));
		dst_img.at<cv::Vec3b>(i, j) = palette[prediction];
	}
}

cv::imshow("decision", dst_img);
cv::waitKey(0);
```

The idea is to assign each pixel of the image a class, red or green.

**Comment by GLmontanari** [comment]
Even though the score seems perfect:
![valos](https://user-images.githubusercontent.com/43607219/93995612-86b02f00-fd91-11ea-94c2-283aea0748fc.PNG)

The final result is not:
![decision](https://user-images.githubusercontent.com/43607219/93995661-97f93b80-fd91-11ea-899a-928b40774879.png)
Here I applied a black mask to the background.
The four points on the left should be "red" while the points on the red "green".

Can anyone help?

**Comment by GLmontanari** [comment]
Shameful. My fault: I was calling my routine twice, so the second time it performed the classification on the decision image from the previous round. Closing this issue.

**Comment by rcurtin** [comment]
@GLmontanari no worries!  Glad you got it worked out.  If you have issues in the future, please feel free to report them too.  I wonder if the default parameters for `DecisionTree` could be tuned to be better in general, but it doesn't look like that might have been part of the problem here. :+1:
