### ISSUE TITLE
getting error when using command make -j4

### ISSUE THREAD

**Issue by 1sarthakbhardwaj** [mlpack/mlpack#2632]
i have previously build ml pack as i have changed my device i am facing an error which i have not faced earlier
i am doing as folow: 

$ wget https://www.mlpack.org/files/mlpack-3.4.1.tar.gz
$ tar -xvzpf mlpack-3.4.1.tar.gz
$ mkdir mlpack-3.4.1/build && cd mlpack-3.4.1/build
$ cmake ../
$ make -j4  # The -j is the number of cores you want to use for a build.
$ sudo make install 

then this error is stopping the making

[ 50%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/decision_stump_test.cpp.o
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____0()’:
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:44:78: warning: ‘mlpack::decision_stump::DecisionStump<MatType>::DecisionStump(const MatType&, const arma::Row<long unsigned int>&, size_t, size_t) [with MatType = arma::Mat<double>; size_t = long unsigned int]’ is deprecated [-Wdeprecated-declarations]
   44 |   DecisionStump<> ds(trainingData, labelsIn.row(0), numClasses, inpBucketSize);
      |                                                                              ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:30:1: note: declared here
   30 | DecisionStump<MatType>::DecisionStump(const MatType& data,
      | ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:47:43: warning: ‘void mlpack::decision_stump::DecisionStump<MatType>::Classify(const MatType&, arma::Row<long unsigned int>&) [with MatType = arma::Mat<double>]’ is deprecated [-Wdeprecated-declarations]
   47 |   ds.Classify(testingData, predictedLabels);
      |                                           ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:149:6: note: declared here
  149 | void DecisionStump<MatType>::Classify(const MatType& test,
      |      ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____2()’:
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:80:78: warning: ‘mlpack::decision_stump::DecisionStump<MatType>::DecisionStump(const MatType&, const arma::Row<long unsigned int>&, size_t, size_t) [with MatType = arma::Mat<double>; size_t = long unsigned int]’ is deprecated [-Wdeprecated-declarations]
   80 |   DecisionStump<> ds(trainingData, labelsIn.row(0), numClasses, inpBucketSize);
      |                                                                              ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:30:1: note: declared here
   30 | DecisionStump<MatType>::DecisionStump(const MatType& data,
      | ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____4()’:
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:108:78: warning: ‘mlpack::decision_stump::DecisionStump<MatType>::DecisionStump(const MatType&, const arma::Row<long unsigned int>&, size_t, size_t) [with MatType = arma::Mat<double>; size_t = long unsigned int]’ is deprecated [-Wdeprecated-declarations]
  108 |   DecisionStump<> ds(trainingData, labelsIn.row(0), numClasses, inpBucketSize);
      |                                                                              ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:30:1: note: declared here
   30 | DecisionStump<MatType>::DecisionStump(const MatType& data,
      | ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:111:43: warning: ‘void mlpack::decision_stump::DecisionStump<MatType>::Classify(const MatType&, arma::Row<long unsigned int>&) [with MatType = arma::Mat<double>]’ is deprecated [-Wdeprecated-declarations]
  111 |   ds.Classify(testingData, predictedLabels);
      |                                           ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:149:6: note: declared here
  149 | void DecisionStump<MatType>::Classify(const MatType& test,
      |      ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____6()’:
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:139:78: warning: ‘mlpack::decision_stump::DecisionStump<MatType>::DecisionStump(const MatType&, const arma::Row<long unsigned int>&, size_t, size_t) [with MatType = arma::Mat<double>; size_t = long unsigned int]’ is deprecated [-Wdeprecated-declarations]
  139 |   DecisionStump<> ds(trainingData, labelsIn.row(0), numClasses, inpBucketSize);
      |                                                                              ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:30:1: note: declared here
   30 | DecisionStump<MatType>::DecisionStump(const MatType& data,
      | ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:142:43: warning: ‘void mlpack::decision_stump::DecisionStump<MatType>::Classify(const MatType&, arma::Row<long unsigned int>&) [with MatType = arma::Mat<double>]’ is deprecated [-Wdeprecated-declarations]
  142 |   ds.Classify(testingData, predictedLabels);
      |                                           ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:149:6: note: declared here
  149 | void DecisionStump<MatType>::Classify(const MatType& test,
      |      ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____8()’:
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:169:78: warning: ‘mlpack::decision_stump::DecisionStump<MatType>::DecisionStump(const MatType&, const arma::Row<long unsigned int>&, size_t, size_t) [with MatType = arma::Mat<double>; size_t = long unsigned int]’ is deprecated [-Wdeprecated-declarations]
  169 |   DecisionStump<> ds(trainingData, labelsIn.row(0), numClasses, inpBucketSize);
      |                                                                              ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:30:1: note: declared here
   30 | DecisionStump<MatType>::DecisionStump(const MatType& data,
      | ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:172:43: warning: ‘void mlpack::decision_stump::DecisionStump<MatType>::Classify(const MatType&, arma::Row<long unsigned int>&) [with MatType = arma::Mat<double>]’ is deprecated [-Wdeprecated-declarations]
  172 |   ds.Classify(testingData, predictedLabels);
      |                                           ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:149:6: note: declared here
  149 | void DecisionStump<MatType>::Classify(const MatType& test,
      |      ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____10()’:
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:204:78: warning: ‘mlpack::decision_stump::DecisionStump<MatType>::DecisionStump(const MatType&, const arma::Row<long unsigned int>&, size_t, size_t) [with MatType = arma::Mat<double>; size_t = long unsigned int]’ is deprecated [-Wdeprecated-declarations]
  204 |   DecisionStump<> ds(trainingData, labelsIn.row(0), numClasses, inpBucketSize);
      |                                                                              ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:30:1: note: declared here
   30 | DecisionStump<MatType>::DecisionStump(const MatType& data,
      | ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:207:43: warning: ‘void mlpack::decision_stump::DecisionStump<MatType>::Classify(const MatType&, arma::Row<long unsigned int>&) [with MatType = arma::Mat<double>]’ is deprecated [-Wdeprecated-declarations]
  207 |   ds.Classify(testingData, predictedLabels);
      |                                           ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:149:6: note: declared here
  149 | void DecisionStump<MatType>::Classify(const MatType& test,
      |      ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____12()’:
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:296:64: warning: ‘mlpack::decision_stump::DecisionStump<MatType>::DecisionStump(const MatType&, const arma::Row<long unsigned int>&, size_t, size_t) [with MatType = arma::Mat<double>; size_t = long unsigned int]’ is deprecated [-Wdeprecated-declarations]
  296 |   DecisionStump<> ds(dataset, labels, numClasses, inpBucketSize);
      |                                                                ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:30:1: note: declared here
   30 | DecisionStump<MatType>::DecisionStump(const MatType& data,
      | ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____14()’:
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:323:26: warning: ‘void mlpack::decision_stump::DecisionStump<MatType>::Classify(const MatType&, arma::Row<long unsigned int>&) [with MatType = arma::Mat<double>]’ is deprecated [-Wdeprecated-declarations]
  323 |   d.Classify(data, labels);
      |                          ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:149:6: note: declared here
  149 | void DecisionStump<MatType>::Classify(const MatType& test,
      |      ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:342:57: warning: ‘mlpack::decision_stump::DecisionStump<MatType>::DecisionStump(const MatType&, const arma::Row<long unsigned int>&, size_t, size_t) [with MatType = arma::Mat<double>; size_t = long unsigned int]’ is deprecated [-Wdeprecated-declarations]
  342 |   DecisionStump<> ds(trainingData, labelsIn.row(0), 4, 3);
      |                                                         ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:30:1: note: declared here
   30 | DecisionStump<MatType>::DecisionStump(const MatType& data,
      | ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:345:43: warning: ‘void mlpack::decision_stump::DecisionStump<MatType>::Classify(const MatType&, arma::Row<long unsigned int>&) [with MatType = arma::Mat<double>]’ is deprecated [-Wdeprecated-declarations]
  345 |   ds.Classify(testingData, predictedLabels);
      |                                           ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:149:6: note: declared here
  149 | void DecisionStump<MatType>::Classify(const MatType& test,
      |      ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____16()’:
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:373:67: warning: ‘mlpack::decision_stump::DecisionStump<MatType>::DecisionStump(const MatType&, const arma::Row<long unsigned int>&, size_t, size_t) [with MatType = arma::Mat<long long int>; size_t = long unsigned int]’ is deprecated [-Wdeprecated-declarations]
  373 |   DecisionStump<arma::imat> ds(trainingData, labelsIn.row(0), 4, 3);
      |                                                                   ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:30:1: note: declared here
   30 | DecisionStump<MatType>::DecisionStump(const MatType& data,
      | ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:379:43: warning: ‘void mlpack::decision_stump::DecisionStump<MatType>::Classify(const MatType&, arma::Row<long unsigned int>&) [with MatType = arma::Mat<long long int>]’ is deprecated [-Wdeprecated-declarations]
  379 |   ds.Classify(testingData, predictedLabels);
      |                                           ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:149:6: note: declared here
  149 | void DecisionStump<MatType>::Classify(const MatType& test,
      |      ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____18()’:
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:411:20: warning: ‘double mlpack::decision_stump::DecisionStump<MatType>::Train(const MatType&, const arma::Row<long unsigned int>&, size_t, size_t) [with MatType = arma::Mat<double>; size_t = long unsigned int]’ is deprecated [-Wdeprecated-declarations]
  411 |       inpBucketSize);
      |                    ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:60:8: note: declared here
   60 | double DecisionStump<MatType>::Train(const MatType& data,
      |        ^~~~~~~~~~~~~~~~~~~~~~
/home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:418:20: warning: ‘double mlpack::decision_stump::DecisionStump<MatType>::Train(const MatType&, const arma::Row<long unsigned int>&, const rowvec&, size_t, size_t) [with MatType = arma::Mat<double>; arma::rowvec = arma::Row<double>; size_t = long unsigned int]’ is deprecated [-Wdeprecated-declarations]
  418 |       inpBucketSize);
      |                    ^
In file included from /home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump.hpp:237,
                 from /home/sarthak/mlpack-3.4.1/src/mlpack/tests/decision_stump_test.cpp:13:
/home/sarthak/mlpack-3.4.1/src/mlpack/methods/decision_stump/decision_stump_impl.hpp:79:8: note: declared here
   79 | double DecisionStump<MatType>::Train(const MatType& data,
      |        ^~~~~~~~~~~~~~~~~~~~~~
[ 50%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/decision_tree_test.cpp.o
[ 50%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/feedforward_network_test.cpp.o
[ 50%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/init_rules_test.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/mlpack/tests/CMakeFiles/mlpack_test.dir/build.make:204: src/mlpack/tests/CMakeFiles/mlpack_test.dir/dcgan_test.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 51%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/image_load_test.cpp.o
[ 51%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/imputation_test.cpp.o
[ 51%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/kernel_pca_test.cpp.o
[ 51%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/kernel_test.cpp.o
[ 52%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/kernel_traits_test.cpp.o
make[1]: *** [CMakeFiles/Makefile2:4016: src/mlpack/tests/CMakeFiles/mlpack_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 52%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/kfn_test.cpp.o
[ 52%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/kmeans_test.cpp.o
[ 52%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/knn_test.cpp.o
[ 53%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/linear_regression_test.cpp.o
[ 53%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/load_save_test.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/build.make:148: src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/ann_layer_test.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:3989: src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by rcurtin** [comment]
Your system has run out of memory during compilation.  Try building with fewer cores---either `make -j2` or even just `make` should succeed if there is enough RAM on the system.

**Comment by RishabhGarg108** [comment]
I too faced the same issue. Try running the following commands sequentially :- 

1. cmake -D BUILD_TESTS=OFF ../
2. make -j1
3. cmake -D BUILD_TESTS=ON ../
4. make -j1

It worked for me and I hope it will work for you too.
