### ISSUE TITLE
Issue while building mlpack in windows

### ISSUE THREAD

**Issue by AnimeshMaheshwari22** [mlpack/mlpack#2634]
When I run the command cmake -G "Visual Studio 16 2019" -A x64 -DBLAS_LIBRARIES:FILEPATH="D:/mlpack/mlpack/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" -DLAPACK_LIBRARIES:FILEPATH="D:/mlpack/mlpack/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" -DARMADILLO_INCLUDE_DIR="D:/mlpack/armadillo/include" -DARMADILLO_LIBRARY:FILEPATH="D:/mlpack/armadillo/build/Debug/armadillo.lib" -DBOOST_INCLUDEDIR:PATH="D:/boost/boost" -DBOOST_LIBRARYDIR:PATH="D:/boost/boost/libs" -DDEBUG=OFF -DPROFILE=OFF ..

I face the following error: 
 Could NOT find Boost (missing: unit_test_framework) (found suitable version
  "1.66.0", minimum required is "1.58")
How should I fix this?

Thanks

**Comment by rcurtin** [comment]
It looks like the `unit_test_framework` from Boost is not installed.  Can you make sure that is installed on your system?  If that's not it, you might have `BOOST_LIBRARYDIR` set incorrectly.

**Comment by AnimeshMaheshwari22** [comment]
> It looks like the `unit_test_framework` from Boost is not installed. Can you make sure that is installed on your system? If that's not it, you might have `BOOST_LIBRARYDIR` set incorrectly.

I would like your advice on this matter. I tried installing boost-test through vcpkg. Should that work?

**Comment by shrit** [comment]
@AnimeshMaheshwari22 I think it should work, did you try to build mlpack?

**Comment by zoq** [comment]
@AnimeshMaheshwari22 Not sure, maybe the version is different, can you post the content of `D:/boost/boost/libs`? The directory should contain all the necessary boost dependencies.

**Comment by AnimeshMaheshwari22** [comment]
I could solve this issue by using a different version(boost_1_71_0-msvc-14.2-64) of the boost library. But I am curious to know how to build the library using boost_1_66_0 so that anyone using that version can do it as well.

**Comment by zoq** [comment]
If you can post the content of the folder, maybe that could bring as any further.
