### ISSUE TITLE
Fix the Azure Build for Windows.

### ISSUE THREAD

**Issue by kartikdutt18** [mlpack/mlpack#2641]
Hey everyone,
As most of you can see, We haven't had a green build on Azure for the past few days. This mainly arises due to a catch test failure on Windows VS15 due to RandomForestSerialization Test. This issue aims to attract attention to the same and hopefully resolve the same.

Please feel free to take up this issue. I am also marking this issue as a good first issue.
Thanks.

**Comment by Abilityguy** [comment]
Hi @kartikdutt18 , I had made the PR on moving Random Forest from boost tests to catch2 tests. I can take this up.

**Comment by kartikdutt18** [comment]
Hey @Abilityguy, Great. Let me know if you face any issues. Thanks.

**Comment by zoq** [comment]
@kartikdutt18 @Abilityguy https://github.com/mlpack/mlpack/pull/2642 should fix the issue.
