### ISSUE TITLE
How can I use tree in KNN? 

### ISSUE THREAD

**Issue by ASQWZXED** [mlpack/mlpack#2656]
How can I print the content and the leaves of the tree?
Also, if you use pairwise then why there is a tree ?

Please, help is needed here.

**Comment by rcurtin** [comment]
> How can I print the content and the leaves of the tree?

You can write a loop to recurse through it.  I would be careful when doing this, because often these trees are very large.  Try something like this:

```
std::stack<TreeType*> s;
s.push(&tree);
while (!s.empty())
{
  TreeType* node = s.top();
  s.pop();

  std::cout << "node has " << node->NumPoints() << " points, "
      << node->NumChildren() << " children, and "
      << node->NumDescendants() << " descendants." << std::endl;

  for (size_t i = 0; i < node->NumChildren(); ++i)
    s.push(&node->Child(i));
}
```

You would want to adapt that code to whatever your need is.

>  Also, if you use pairwise then why there is a tree ?

I don't know what you mean.  If you are talking about KNN, it *does not compute pairwise similarity*.  It computes *distances*.  For details, consult the paper: https://arxiv.org/pdf/1304.4327.pdf and anything referenced therein.

**Comment by ASQWZXED** [comment]
Thank you so much,


________________________________

**Comment by ASQWZXED** [comment]
Could you please see this code? Where is the error?

Thank you so much for your help.
________________________________

**Comment by zoq** [comment]
> Could you please see this code? Where is the error?

Don't see code here.

**Comment by ASQWZXED** [comment]
@zoq Here,
![Untitled](https://user-images.githubusercontent.com/69873647/95123939-67cf7680-075b-11eb-89c2-9b21e2beeb70.png)

**Comment by zoq** [comment]
The `RStarTree` is not part of the std `namespace`, it's part of the `mlpack::tree` namespace, so it should be `mlpack::tree::RStarTree`, at least that's one issue. Looking at the console output it looks like there are a couple more?

**Comment by ASQWZXED** [comment]
Hi @zoq 
I correct that but still there are punch of errors that I don't know where is it coming from.

Please see the attached pictures 
![KNN](https://user-images.githubusercontent.com/69873647/95249904-0f16e100-0822-11eb-93b8-c03ee45796cd.png)
![KNN1](https://user-images.githubusercontent.com/69873647/95249906-10480e00-0822-11eb-9575-751846a088aa.png)

**Comment by ASQWZXED** [comment]
Hello, @rcurtin, @zoq 

Sorry for keeping asking you these questions. It may be basic questions for you, but I spent many hours trying to figure out how to print it.
I just want to print the leaf nodes and their parents as groups, each group have a parent with its leaf nodes.
![KNN](https://user-images.githubusercontent.com/69873647/95690901-b7161b00-0c23-11eb-8133-ae24dce6070e.png)
![KNN1](https://user-images.githubusercontent.com/69873647/95690904-bb423880-0c23-11eb-9b77-f8788aee7a9f.png)


Thank you so much for your previous help.

**Comment by ASQWZXED** [comment]
@rcurtin, @zoq 

Please, help is needed here.
