### ISSUE TITLE
Could not build mlpack.dll on windows

### ISSUE THREAD

**Issue by kenanking** [mlpack/mlpack#2658]
Hi Everyone!
I could build mlpack.lib according to the doucment on [https://www.mlpack.org/doc/stable/doxygen/build_windows.html](https://www.mlpack.org/doc/stable/doxygen/build_windows.html). But I could not build mlpack.dll according to this.
![image](https://user-images.githubusercontent.com/43688468/95020200-6a1ecb80-069c-11eb-8ea7-78a341aa2b88.png)
![image](https://user-images.githubusercontent.com/43688468/95020206-773bba80-069c-11eb-9928-1bd37f6a1f70.png)

A link problem occured when I tried to build the mlpack.dll.

**Comment by zoq** [comment]
Hello, for building `.dll` did you specific `BUILD_SHARED_LIBS` in the cmake step?
