### ISSUE TITLE
More probabolistic prediction methods

### ISSUE THREAD

**Issue by alexhallam** [mlpack/mlpack#2667]
### What is the desired addition or change?

With the exception of one or two methods, most regression methods in MLPack only predict point estimates. It would be nice to have distributional predictions.

### What is the motivation for this feature?

Point estimates are not enough.

### If applicable, describe how this feature would be implemented.

Each method may need its own approach. For random forests, all of the leaves are kept. For regression, probability distributions are assumed.

**Comment by czgdp1807** [comment]
> For regression, probability distributions are assumed.

Any references for this? Like the probability should be applied on weights/bias? Something like, https://arxiv.org/abs/1505.05424

**Comment by alexhallam** [comment]
Sorry, this would have to be taken model-by-model and I was thinking more in regression settings. Things that come to mind are quantile regression or quantile random forests. The tools I am most familiar with on the random forest side are [ranger](https://arxiv.org/pdf/1508.04409v1.pdf) which has really good performance and [skit-garden's](https://scikit-garden.github.io/examples/QuantileRegressionForests/.) QuantileRegressionForests

**Comment by rcurtin** [comment]
Hey @alexhallam, it's not everything, but we did recently add the `BayesianLinearRegression` class and the `bayesian_linear_regression()` binding: https://www.mlpack.org/doc/stable/cli_documentation.html#mlpack_bayesian_linear_regression

Contributions are totally welcome, by the way, if you have anything in mind. :smile:
