### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by BoltonBailey** [mlpack/mlpack#2670]
#### Issue description

When I install mlpack, then try to import the emst function, I get an error:

```
0:12:04 directory #=# pip3 install mlpack 
Collecting mlpack
  Downloading mlpack-3.4.1-cp38-cp38-macosx_10_9_x86_64.whl (12.9 MB)
     |████████████████████████████████| 12.9 MB 1.2 MB/s 
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from mlpack) (1.0.3)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from mlpack) (1.18.1)
Collecting cython>=0.24
  Downloading Cython-0.29.21-cp38-cp38-macosx_10_9_x86_64.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 56.3 MB/s 
Requirement already satisfied: pytz>=2017.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas->mlpack) (2020.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas->mlpack) (2.8.1)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.6.1->pandas->mlpack) (1.14.0)
Installing collected packages: cython, mlpack
Successfully installed cython-0.29.21 mlpack-3.4.1
WARNING: You are using pip version 20.0.2; however, version 20.2.3 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m pip install --upgrade pip' command.
0:12:11 directory #=# python3 analysis.py 
Traceback (most recent call last):
  File "analysis.py", line 3, in <module>
    from mlpack import emst
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mlpack/__init__.py", line 11, in <module>
    from .adaboost import adaboost
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mlpack/adaboost.cpython-38-darwin.so, 2): Library not loaded: @rpath/libmlpack.3.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mlpack/adaboost.cpython-38-darwin.so
  Reason: image not found
```

#### Your environment

 * version of mlpack: mlpack-3.4.1
 * operating system: macOS 10.15.6
 * compiler:
 * version of dependencies (Boost/Armadillo):
 * any other environment information you think is relevant:

#### Steps to reproduce

You can see the commands I ran in the terminal output above

#### Expected behavior

The import should not fail

#### Actual behavior

The import failed

**Comment by rcurtin** [comment]
Hey @BoltonBailey, thanks for the report.  It looks like for some reason PyPI OS X builds don't actually include the mlpack libraries!  I will work on trying to figure out why that is.  In the meantime, if you want, you could download mlpack and build the Python bindings from source (just set `-DPYTHON_EXECUTABLE=$(which python3) -DBUILD_PYTHON_BINDINGS=ON` during the CMake configuration step, then `make` and `sudo make install`... I think that will work).  Let me know if I can clarify anything about that, and I'll post an update here when I work out the issue. :+1:

**Comment by BoltonBailey** [comment]
Doing what you suggested, I got an error when I ran cmake, telling me it could not build R bindings. I don't have R installed on my system.

```
(base) 11:54:49 build #=# cmake ../ -DPYTHON_EXECUTABLE=$(which python3) -DBUILD_PYTHON_BINDINGS=ON
-- cotire 1.7.10 loaded.
-- Could NOT find Ensmallen (missing: ENSMALLEN_INCLUDE_DIR) (Required is at least version "2.10.0")
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
...
-- [download 99% complete]
-- [download 100% complete]
* Closing connection 0
-- Successfully downloaded ensmallen into /Users/boltonbailey/mlpack-3.4.1/build/deps/ensmallen-2.14.2/
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
CMake Warning at CMakeLists.txt:584 (message):
  txt2man not found; man pages will not be generated.


-- Not building Markdown bindings.
-- Found Gonum: gonum.org/v1/gonum/mat  
-- R not found (missing: R_EXECUTABLE) (Required is at least version "4.0")
-- Could NOT find R_roxygen2 (missing: R_ROXYGEN2) 
-- Could NOT find R_Rcpp (missing: R_RCPP) 
-- Could NOT find R_RcppArmadillo (missing: R_RCPPARMADILLO) 
-- Could NOT find R_RcppEnsmallen (missing: R_RCPPENSMALLEN) 
-- Could NOT find R_BH (missing: R_BH) 
-- Could NOT find R_testthat (missing: R_TESTTHAT) 
CMake Error at src/mlpack/bindings/R/CMakeLists.txt:64 (message):
  Could not Build R Bindings, Following modules are not available:

      - R
      - roxygen2
      - Rcpp
      - RcppArmadillo
      - RcppEnsmallen
      - BH
      - testthat


-- Configuring incomplete, errors occurred!
See also "/Users/boltonbailey/mlpack-3.4.1/build/CMakeFiles/CMakeOutput.log".
(base) 11:55:09 build #=# cmake ../ -DPYTHON_EXECUTABLE=$(which python3) -DBUILD_PYTHON_BINDINGS=ON
```

**Comment by BoltonBailey** [comment]
Ok, I installed Ensmallen and ran it again, and this time it worked. I was able to make mlpack and import correctly. Thank you for your help and I appreciate your looking into the PyPI problem.

**Comment by BoltonBailey** [comment]
Another report on this, after downloading mlpack using these instructions and running emst(), I got a segmentation fault. Should I open a new ticket for this?

**Comment by rcurtin** [comment]
Oh, that's unfortunate, sorry that happened. :( This issue is fine, can you paste the command and output here?  Also, is it possible there are multiple versions of mlpack installed on your machine?

**Comment by rcurtin** [comment]
Hey @BoltonBailey, I think I've fixed this on PyPI... I was able to run the following locally on an OS X system:

```
$ pip install mlpack
$ python
>>> import mlpack
>>> from mlpack import pca
>>> import numpy as np
>>> x = np.random.rand(10, 10)
...
>>> pca(x, new_dimensionality=5, verbose=True)
...
```

And that all seemed to work, indicating to me that the dependent libraries are now being included.  Can you give that a shot and let me know if that works for you too?

**Comment by BoltonBailey** [comment]
I can confirm that I can import the emst function and run it on a 10 by 10 random array, so the import and library problem is resolved. 

Running it on my 117956 by 3 array, I get a segmentation fault. Not sure what's causing this, its actually mystifying because it runs perfectly fine on a random array of the same size and dtype as my data, it just seems to fail on my data specifically. I'll try to resolve this myself, and if I think something else is wrong I'll open another ticket. Thanks so much for your help @rcurtin.

**Comment by rcurtin** [comment]
That's strange... can you reproduce the issue with the command-line programs?  I can try too if you can supply the dataset.  (Are there duplicate points in your dataset?  Try filtering them?  If that is the issue I think we need to figure out better error output! :smile:)

Anyway, glad that it worked!  And thank you again for reporting it---I had no idea it was an issue. :+1:

**Comment by BoltonBailey** [comment]
I just found that my data had some inf and nan values in it, it seems this was causing the segfault. Totally my fault. Removing those data points, it works perfectly, start to finish. I guess its up to mlpack maintainers if they want to do some kind of sanitization before these algorithms run, but it would have been helpful for me. Thanks again.

**Comment by rcurtin** [comment]
@BoltonBailey good point.  This is something I've thought about for a while but have never actually moved on.  I wrote up an idea in #2679; hopefully we'll get it implemented at some point in the future and that should make these types of errors easier to spot. :+1:
