### ISSUE TITLE
SimpleDQN/QLearning saving/loading

### ISSUE THREAD

**Issue by rnarcin** [mlpack/mlpack#2676]
Hello guys, I have several questions about simpleDQN and QLearning. Let's assume that I have defined FFN and then constructed simpleDQN from it. I defined policy, replay, hyperparameters and created an agent. The agent was trained by very big amount of time. Now i would like to:
1) save current learning progress of agent to the file, make some tweaks/changes to the environment and load saved agent so it can learn further.
2) save corresponding trained FFN to the file, load it by the other program and feed it with states to get appropriate actions.

ad 1. Is there any way to save QLearning agent so after reloading it will match EXACTLY the same point of learning progress before saving?
ad 2. Is there any way to save FFN of agent to the file? QLearning agent has field Network, but its type of simpleDQN so it has not serialize method

**Comment by zoq** [comment]
Hello @rnarcin you can use `data::Save` and `data::Load` to save/load the network/agent, see https://github.com/mlpack/examples/blob/3df47a86027418bcb5601b828decef360357c8b4/mnist_cnn/mnist_cnn.cpp#L213-L220 for an example.

You are right you can't save the simpleDQN at this point, but what you can do is to construct a network outside of the simpleSQN and pass it, here is an example - https://github.com/mlpack/examples/blob/master/reinforcement_learning_gym/lunar_lander_dqn.ipynb

That would allow you to save/load the instantiated and passed network. I hope that makes sense. Happy to clarify anything further.
