### ISSUE TITLE
Add 'sanity check' option to bindings

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#2679]
### What is the desired addition or change?

In #2670, one of the issues encountered was that there was a NaN or Inf in the dataset, but mlpack did not issue any errors other than crashing.  Although we focus on fast implementations, it can be really confusing to users who aren't expecting to need to make sure that all of their data is sanitized for the method at hand (and also our methods don't always document what "sanitized" means!).

So, it is possible to have the best of both worlds, at least for the bindings.  This is (finally) a step towards #891. 

What we could do is add an option to *every* binding called `no_sanity_checks` (or similar).  If this option is specified, nothing happens.  If the option is *not* specified, then when we are preprocessing any matrix arguments to bindings, we would take a pass over the matrix and check that there are no NaNs or Infs.  This will not capture every single possible failure mode of our bindings, which sometimes have more restrictive requirements, but it will at least be a big step in this direction.

If the user wants to avoid the checks, they can simply set the `no_sanity_checks` option to save a little extra time.

### What is the motivation for this feature?

Better error handling and output for simple cases.

### If applicable, describe how this feature would be implemented.

You can define an option pretty easily in `src/mlpack/core/util/mlpack_main.hpp`.  Take a look at, for instance, the definition of `"verbose"` throughout that file; we could make another `PARAM_FLAG` there for `no_sanity_checks` pretty easily.

Then, we need to do something with that option.  So, we need to modify how `mlpackMain()` is called for every binding.  For the command-line bindings, this is simple---we can simply add it to the `int main()` function defined in `mlpack_main.hpp`.  For the other bindings it is a little bit more tricky; we would have to handle it differently for each one.  I think that it can be done like this:

 - Go: modify `src/mlpack/bindings/go/go_method.cpp.in` to call the sanity check function first.
 - Julia: modify `src/mlpack/bindings/julia/julia_method.cpp.in` in much the same way.
 - Markdown: this one is documentation; the option can be ignored.
 - Python: I think this one is a little bit more tricky.  We'll have to bind another function into `src/mlpack/bindings/python/mlpack/io.pxd` and probably implement it in `src/mlpack/bindings/python/mlpack/io_util.hpp` (or elsewhere?), and then call out to that function in the generated code in `print_pyx.cpp` just before calling `mlpackMain()`.
 - R: I'm not sure on this one yet.  I think we'll have to do the same type of strategy as for Python.

### Additional information?

This can be just a starting point.  The idea for now is just to check for NaNs and Infs, but later we could extend this into a binding-specific system where each binding could set some properties it requires for input.  (For instance, PCA requires a data matrix whose covariance has no negative eigenvalues.)

I hope to find some time to get to this one, but it might be a while, and if anyone is looking for a way to contribute or get involved with the automatic binding system, this would be a nice way.  So I'll mark it as 'help wanted', and if someone gets to it before me, awesome! :smile:

### Status

 - [x] Main utility function in IO (thanks @NippunSharma!)
 - [x] Python bindings (thanks @NippunSharma!)
 - [ ] command-line bindings
 - [ ] Julia bindings
 - [ ] Go bindings
 - [ ] R bindings

**Comment by heisenbuug** [comment]
I wanna work on this @rcurtin. So what I figured out till now:

- We have to edit `src/mlpack/core/util/mlpack_main.hpp` : Here we just have to add `no_sanity_checks` in the same way `verbose` is added, ie inside `PARAM_FLAG` 

Currently 
```
PARAM_FLAG("verbose", "Display informational messages and the full list of "
    "parameters and timers at the end of execution.", "v");
```
After edit
```
PARAM_FLAG("verbose", "no_sanity_checks", "Display informational messages and the full list of "
    "parameters and timers at the end of execution.", "v");
```

- Also one doubt where do we have to implement this function? 

- Once the implementation is done, I just have to make function calls as suggested.

**Comment by rcurtin** [comment]
Hi @heisenbuug, the `PARAM_FLAG()` parameter is meant to define just one parameter.  You would need to add another one for `no_sanity_checks` and you would also need to add appropriate documentation for it.  See the documentation for `PARAM_FLAG` in `src/mlpack/core/util/param.hpp`.

For the second part, that's probably a reasonable way to do it. :+1:

**Comment by NippunSharma** [comment]
hi @rcurtin I was able to reproduce this issue (i think so) in python.

Code: 

    from mlpack import linear_regression
    import pandas as pd
    import numpy as np
    
    df = pd.read_csv("data.csv")
    x_train = df[["col1", "col2"]].values
    y_train = df["y"].values
    
    print("Training data")
    print(x_train)
    
    d = linear_regression(input_model=None, lambda_=0., test=np.array([[0, 0]]),
                          training=x_train, training_responses=y_train)
    
    output_model = d["output_model"]
    output_preds = d["output_predictions"]
    
    print("Test predictions")
    print(output_preds)

data.csv:

    col1,col2,y
    ,2,3
    2,3,4
    4,5,6
    7,8,9

output:

    $ python test.py
    Training data
    [[nan  2.]
     [ 2.  3.]
     [ 4.  5.]
     [ 7.  8.]]
    Test predictions
    [nan]

There is a `nan` value inside the training data but instead of throwing any error we just get a `nan` output.
Is this the issue you were talking about ?
Also, I see that this issue has been inactive for quite some time now. Can I work on this ?

**Comment by heisenbuug** [comment]
I am sorry @rcurtin  I was not able to work on this, I started working on some other issues, my bad. You can take this up @NippunSharma...

**Comment by RAVANv2** [comment]
Hii @rcurtin I would like to go with this issue!!! 
 Can I?

**Comment by NippunSharma** [comment]
Hi @RAVANv2 , thanks for wanting to contribute but I have started already started working on this, maybe you can take some other issue :)

**Comment by NippunSharma** [comment]
Hi @rcurtin I have opened #2787 , which adds `no_sanity_checks` option to the python bindings. Please take a look at it whenever you have time.

**Comment by rcurtin** [comment]
Python bindings are done with #2787.  I added a 'status' section to the top in case anyone wants to try any of the other languages.  It should be easier now that @NippunSharma has laid the groundwork with the `CheckInputMatrices()` function. :+1:

**Comment by Anmol2001** [comment]
Hi ! I want to work on this issue with other remaining languages.

**Comment by rcurtin** [comment]
Hi @Anmol2001, I haven't seen any PRs for other languages yet, so please feel free to go ahead. :+1:  Please use the `CheckInputMatrices()` functions that @NippunSharma wrote. :)

**Comment by Anmol2001** [comment]
Hi @rcurtin , In GO binding,  what I have thought of doing is  is After modifying `src/mlpack/core/util/mlpack_main.hpp.` for PARAM_FLAG, I need to modify 2 files in GO, `src/mlpack/bindings/go/go_method.cpp.in`(just calling CheckInputMatrices() before mlpackMain()) and `src/mlpack/bindings/go/go_option.hpp`(as verbose is also there).

**Comment by NippunSharma** [comment]
Hey @Anmol2001, are you still working on the GO bindings? If not I would like to have a shot at it.

**Comment by Anmol2001** [comment]
Hi @NippunSharma  Actually I was busy with my project idea , but I will continue on this (GO). You can try with other bindings like Julia.

**Comment by Anmol2001** [comment]
I am getting error while installing Go Bindings on the `make install` command
`Building CXX object src/mlpack/methods/lsh/CMakeFiles/mlpack_go_lsh.dir/__/__/bindings/go/build/lsh.cpp.o
c++: internal compiler error: Killed (program cc1plus)`

I am using [this](https://www.mlpack.org/doc/stable/doxygen/go_quickstart.html) documentation for installing GO bindings.

**Comment by rcurtin** [comment]
@Anmol2001 looks like you're running out of RAM... maybe use fewer cores when compiling?

**Comment by Anmol2001** [comment]
@rcurtin I was already using single core and i have tried using -j1 as well as -j4 but the error remains same. Also few days back , I have submitted a draft proposal  on Adding Image quality metrics which also included the metric which is used in the VMAF by Netflix. Looking for your feedback : )

**Comment by NippunSharma** [comment]
@Anmol2001 I am not completely sure about this but, take a look [here]( https://github.com/mlpack/mlpack-go/blob/1958871f884cf93224f11a852cb511cb87cb115b/Makefile#L78), in this Makefile in this line it is automatically using all cores. @rcurtin can you confirm this?
