### ISSUE TITLE
22 tests fail on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [mlpack/mlpack#2687]
Tests in version 3.4.2 fail on FreeBSD 12.2:

```
The following tests FAILED:
	  1 - CallbackTest (Failed)
	  2 - DrusillaSelectTest (Failed)
	  4 - FastMKSTest (Failed)
	  6 - HPTTest (Failed)
	  7 - HyperplaneTest (Failed)
	  8 - InitRulesTest (Failed)
	  9 - LinearSVMTest (Failed)
	 10 - LocalCoordinateCodingTest (Failed)
	 12 - LogisticRegressionTest (Failed)
	 13 - LSHTest (Failed)
	 14 - MatrixCompletionTest (Failed)
	 16 - QLearningTest (Failed)
	 17 - QDAFNTest (Failed)
	 19 - SerializationTest (Failed)
	 20 - TerminationPolicyTest (Failed)
	 25 - FastMKSMainTest (Failed)
	 26 - LinearSVMMainTest (Failed)
	 27 - LCCMainTest (Failed)
	 28 - LogisticRegressionMainTest (Failed)
	 29 - LSHMainTest (Failed)
	 30 - PerceptronMainTest (Failed)
	 31 - catch_test (Bus error)
```

For example:
```
$ /usr/ports/math/mlpack/work/.build/bin/mlpack_test -t CallbackTest
Running 10 test cases...
unknown location(0): fatal error: in "CallbackTest/FFNCallbackTest": memory access violation at address: 0x800d0d2de: object specific hardware error
/usr/ports/math/mlpack/work/mlpack-3.4.2/src/mlpack/tests/callback_test.cpp(42): last checkpoint: "FFNCallbackTest" test entry

*** 1 failure is detected in the test module "mlpackTest"


$ "/usr/ports/math/mlpack/work/.build/bin/mlpack_test" "-t" "LogisticRegressionTest"
Running 26 test cases...
unknown location(0): fatal error: in "LogisticRegressionTest/LogisticRegressionFunctionRandomEvaluate": memory access violation at address: 0x800d0d2de: object specific hardware error
/usr/ports/math/mlpack/work/mlpack-3.4.2/src/mlpack/tests/logistic_regression_test.cpp(53): last checkpoint: "LogisticRegressionFunctionRandomEvaluate" test entry

*** 1 failure is detected in the test module "mlpackTest"
```

**Comment by rcurtin** [comment]
`object specific hardware error`

I have never seen this error before... are you sure something is not wrong with the system you are using?

**Comment by yurivict** [comment]
> I have never seen this error before... are you sure something is not wrong with the system you are using?

Everything else seems to be fine.

**Comment by rcurtin** [comment]
I really truly can't find any information about that particular error.  There is a suggestion somewhere that the machine might not have enough available RAM.  Past that, I really don't think I have any idea how to start debugging this one. :(  Maybe someone else has some ideas?

**Comment by zoq** [comment]
Let me build mlpack on my FreeBSD system.

**Comment by yurivict** [comment]
I encountered this problem after updating the FreeBSD port /usr/ports/math/mlpack to 3.4.2 and then running ```make test``` there.

**Comment by zoq** [comment]
So a previous version was already installed?

**Comment by yurivict** [comment]
> So a previous version was already installed?

No.

**Comment by yurivict** [comment]
On FreeBSD this can be reproduced with
1. cd /usr/ports/math/mlpack
2. change the version in Makefile to 3.4.2
3. run make makesum test

**Comment by zoq** [comment]
Alright, thanks for the instruction.

**Comment by yurivict** [comment]
So what do I do about these failures?

**Comment by rcurtin** [comment]
None of us have been able to reproduce these issues, and they have never been seen on any other platform or by any other user.  I have some belief that this is specific to your setup.  If I were you I might check the exact commands being used for build with `VERBOSE=1 make`, and make sure that these are actually what you expect on your system.  Sorry I can't provide any better support.
