### ISSUE TITLE
cannot perform neighbor search, building error(compiled without openmp support)

### ISSUE THREAD

**Issue by Di-ashX** [mlpack/mlpack#2693]
mlpack version: 3.4.2
error:
Starting build...
Build finished with error:
                          In file included from /usr/local/include/mlpack/prereqs.hpp:125,
                                                                                                           from /usr/local/include/mlpack/core.hpp:67,
                                                                         from /home/professor/projects/mlp/mlp.cpp:7:
                       /usr/local/include/mlpack/core/util/arma_config_check.hpp:50:21: note: #pragma message: mlpack was compiled with OpenMP support, but you are compiling without OpenMP support.  This will almost certainly cause irreparable disaster.  Either enable OpenMP support in your application (e.g., add -fopenmp to your compiler command line), or, recompile mlpack *without* OpenMP support.
                             50 |     #pragma message "mlpack was compiled with OpenMP support, but you are \
                     |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       51 | compiling without OpenMP support.  This will almost certainly cause \
                                                                                       | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                   52 | irreparable disaster.  Either enable OpenMP support in your application (e.g., \
                                                                | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                       53 | add -fopenmp to your compiler command line), or, recompile mlpack *without* \
                                                 | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                     54 | OpenMP support."
                                                                | ~~~~~~~~~~~~~~~~     
                                                                                       /usr/bin/ld: /tmp/ccgAAr1I.o: in function `mlpack::neighbor::NeighborSearch<mlpack::neighbor::NearestNS, mlpack::metric::LMetric<1, false>, arma::Mat<double>, mlpack::tree::KDTree, mlpack::tree::BinarySpaceTree<mlpack::metric::LMetric<1, false>, mlpack::neighbor::NeighborSearchStat<mlpack::neighbor::NearestNS>, arma::Mat<double>, mlpack::bound::HRectBound, mlpack::tree::MidpointSplit>::DualTreeTraverser, mlpack::tree::BinarySpaceTree<mlpack::metric::LMetric<1, false>, mlpack::neighbor::NeighborSearchStat<mlpack::neighbor::NearestNS>, arma::Mat<double>, mlpack::bound::HRectBound, mlpack::tree::MidpointSplit>::SingleTreeTraverser>::Search(unsigned long, arma::Mat<unsigned long>&, arma::Mat<double>&)':
                                           /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:708: undefined reference to `mlpack::Timer::Start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
                                                                    /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:757: undefined reference to `mlpack::Log::Info'
               /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:757: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(unsigned long)'
   /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:757: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
                                                                                   /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:758: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(std::ostream& (*)(std::ostream&))'
                                                                                          /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:759: undefined reference to `mlpack::Log::Info'
                                     /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:759: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(unsigned long)'
                         /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:759: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
           /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:760: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(std::ostream& (*)(std::ostream&))'
                  /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:805: undefined reference to `mlpack::Log::Info'
                                                           /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:805: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(unsigned long)'
                                               /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:805: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
                                 /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:806: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(std::ostream& (*)(std::ostream&))'
                                        /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:807: undefined reference to `mlpack::Log::Info'
                                                                                 /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:807: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(unsigned long)'
                                                                     /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:807: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
                                                       /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:808: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(std::ostream& (*)(std::ostream&))'
                                                              /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:826: undefined reference to `mlpack::Log::Info'
         /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:826: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(unsigned long)'
                                                                                           /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:826: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
                                                                             /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:827: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(std::ostream& (*)(std::ostream&))'
                                                                                    /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:828: undefined reference to `mlpack::Log::Info'
                               /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:828: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(unsigned long)'
                   /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:828: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(char const*)'
     /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:829: undefined reference to `mlpack::util::PrefixedOutStream::operator<<(std::ostream& (*)(std::ostream&))'
            /usr/bin/ld: /usr/local/include/mlpack/methods/neighbor_search/neighbor_search_impl.hpp:836: undefined reference to `mlpack::Timer::Stop(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
                                                 /usr/bin/ld: /tmp/ccgAAr1I.o: in function `mlpack::bound::HRectBound<mlpack::metric::LMetric<1, false>, double>& mlpack::bound::HRectBound<mlpack::metric::LMetric<1, false>, double>::operator|=<arma::subview<double> >(arma::subview<double> const&)':
                /usr/local/include/mlpack/core/tree/hrectbound_impl.hpp:516: undefined reference to `mlpack::Log::Assert(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
                           /usr/bin/ld: /tmp/ccgAAr1I.o: in function `unsigned long mlpack::tree::split::PerformSplit<arma::Mat<double>, mlpack::tree::MidpointSplit<mlpack::bound::HRectBound<mlpack::metric::LMetric<1, false>, double>, arma::Mat<double> > >(arma::Mat<double>&, unsigned long, unsigned long, mlpack::tree::MidpointSplit<mlpack::bound::HRectBound<mlpack::metric::LMetric<1, false>, double>, arma::Mat<double> >::SplitInfo const&, std::vector<unsigned long, std::allocator<unsigned long> >&)':
                                    /usr/local/include/mlpack/core/tree/perform_split.hpp:151: undefined reference to `mlpack::Log::Assert(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
                                             /usr/bin/ld: /tmp/ccgAAr1I.o: in function `double mlpack::bound::HRectBound<mlpack::metric::LMetric<1, false>, double>::MinDistance<arma::subview_col<double> >(arma::subview_col<double> const&, std::enable_if<IsVector<arma::subview_col<double> >::value, void>::type*) const':
                                      /usr/local/include/mlpack/core/tree/hrectbound_impl.hpp:173: undefined reference to `mlpack::Log::Assert(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
                                                 /usr/bin/ld: /tmp/ccgAAr1I.o: in function `mlpack::bound::HRectBound<mlpack::metric::LMetric<1, false>, double>::MinDistance(mlpack::bound::HRectBound<mlpack::metric::LMetric<1, false>, double> const&) const':
                                                                      /usr/local/include/mlpack/core/tree/hrectbound_impl.hpp:230: undefined reference to `mlpack::Log::Assert(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
                                                                                 collect2: error: ld returned 1 exit status

                             The terminal process terminated with exit code: -1.

**Comment by rcurtin** [comment]
Are you linking against mlpack in your build? Your compiler will need the flag `-lmlpack`.

**Comment by yatishgoel** [comment]
this worked for me 
g++ filename.cpp -std=c++11 `pkg-config --libs mlpack`

**Comment by NippunSharma** [comment]
adding `-fopenmp` when building worked for me

**Comment by Prath06** [comment]
This works for me 
both g++ and gcc
