### ISSUE TITLE
compilation warnings due to deprecated matrix initialisation via <<

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/mlpack#2699]
In [Armadillo 10.x](http://arma.sourceforge.net/download.html), matrix initialisation via `<<` is deprecated.   This comes up as lots of warnings during mlpack compilation.
For example, see `src/mlpack/tests/ann_layer_test.cpp`:
https://github.com/mlpack/mlpack/blob/58870ad8fe355aa5c843c95d6020c932d3636d69/src/mlpack/tests/ann_layer_test.cpp#L2011-L2014

Instead of using `<<`, the preferred way is to use C++11 [braced initialiser lists](http://arma.sourceforge.net/docs.html#element_initialisation).  Examples:

    vec v = { 1, 2, 3 };
    
    mat A = { {1, 3, 5},
              {2, 4, 6} };

Using C++11 braced initialiser lists will also work with earlier versions of Armadillo, such as 8.400.

(related: https://github.com/mlpack/mlpack/issues/2523)

**Comment by zoq** [comment]
I'm wondering what the reason behind the change is, is it to keep things simple?

**Comment by conradsnicta** [comment]
@zoq Using `<<` for matrix initialisation pre-dates the existence of C++11.  For Armadillo 10.x, the minimum supported C++ standard has been increased to  C++11, where the braced initialiser list is a superior solution (ie. cleaner and more efficient).

**Comment by rcurtin** [comment]
This is a really nice first issue for anyone looking to get started contributing to mlpack.  It's not particularly exciting but could expose you to a good part of the codebase. :)  Basically all we need to do is replace everywhere where we use `<<` with the braced initializer lists that Conrad suggests.  I think most of the usages of this should be in `src/mlpack/tests/`, but there may be other places too.

**Comment by zoq** [comment]
> @zoq Using `<<` for matrix initialisation pre-dates the existence of C++11. For Armadillo 10.x, the minimum supported C++ standard has been increased to C++11, where the braced initialiser list is a superior solution (ie. cleaner and more efficient).

Thanks for the clarification, makes sense.

**Comment by Abilityguy** [comment]
I can take this up.

**Comment by GauravSarkar** [comment]
@rcurtin  I am new to mlpack . I want to contribute towards this issue so that I get familiar to the codebase.

**Comment by GauravSarkar** [comment]
@conradsnicta @zoq  @rcurtin  I have sent  a PR regarding the issue. Please kindly check and merge.

**Comment by RishabhGarg108** [comment]
I would like to work on this issue. Thanks!

**Comment by RishabhGarg108** [comment]
I am getting an error while using braces to initialize an `arma::mat` having one column. For matrices with more than one columns, brace initializer is working fine. The error message is

ambiguous overload for ‘operator=’ (operand types are ‘arma::Mat<long unsigned int>’ and ‘<brace-enclosed initializer list>’)
Someone please help me.

**Comment by conradsnicta** [comment]
@RishabhGarg108 If you think it's a bug, create a small self-contained program which shows the issue and report it at the Armadillo repo: https://gitlab.com/conradsnicta/armadillo-code

**Comment by RishabhGarg108** [comment]
Hey @conradsnicta , I created an issue as you mentioned. Please check it [here](https://gitlab.com/conradsnicta/armadillo-code/-/issues/168). Thanks!
