### ISSUE TITLE
shouldn't we use venv?

### ISSUE THREAD

**Issue by pradkrish** [mlpack/mlpack#2700]
I am a newcomer to mlpack and while building mlpack, I noticed that there is no mention of using virtual environment, which is the standard way of building any package these days, anywhere in the documentation. Shouldn't that be mentioned in the documentation? I can make a PR for this as a way of dipping my feet.

**Comment by rcurtin** [comment]
mlpack is not a Python package, although it does have the ability to build Python bindings.  So venv is not relevant to mlpack's build process.

**Comment by pradkrish** [comment]
Good point, I agree with that. At least it's worth mentioning how people usually do it. In this way, someone new to this whole thing will at least know what is the right thing to do.

**Comment by rcurtin** [comment]
I don't understand what you're suggesting.  Virtual environments don't make sense for a C++ build.  Our README and Doxygen documentation already describe how to build the package.  Did I overlook what you mean?

**Comment by pradkrish** [comment]
I could be wrong here. This line from the README `if you would like to use or build the mlpack Python bindings, make sure that the following Python packages are installed. Since we can access C++ APIs from python, I thought doing it inside a venv can help not to mix configuration up with other packages.

**Comment by pradkrish** [comment]
feel free to close this issue if no action is required.

**Comment by rcurtin** [comment]
At least personally I think that if someone is building the Python bindings by hand, they will necessarily need to know a little bit about their Python environment---after all, they should specify `PYTHON_EXECUTABLE` as a CMake option.  I wouldn't be opposed to clarifying the working there to something like `make sure that the following Python packages are installed in the environment corresponding to the Python executable being used as PYTHON_EXECUTABLE` or similar.  Realistically, I suspect that most Python users will be installing from pip or conda, but in any case, if you want to try and update that documentation please do feel free. :+1:

**Comment by pradkrish** [comment]
Sure, users typically do pip install. I was thinking about contributors. They may want to check their implementations by calling it from python. Using a venv as a development environment is the right way to go about it especially if they are also contributing to other packages.

**Comment by pradkrish** [comment]
By the way, I am not able to build python bindings. I run cmake with the following options, yet it's unable to build python bindings.

`cmake -D DEBUG=ON -D PROFILE=ON -DCEREAL_INCLUDE_DIR=/home/MYUSERNAME/repos/cereal-1.3.0/include/ PYTHON_EXECUTABLE=/home/MYUSERNAME/python_environments/mlpack_venv/bin/python ../`

any idea why? :thinking:

**Comment by rcurtin** [comment]
Can you paste the error output?  I can't help debug unless I see that.  Also, if you specify `PYTHON_EXECUTABLE` in the CMake command that should be done with `-D`: `-D PYTHON_EXECUTABLE=...` (you can see basic CMake documentation for more details). :+1:

**Comment by pradkrish** [comment]
of course, sorry for not adding the logs, I reran it with 
`cmake -D DEBUG=ON -D PROFILE=ON -DCEREAL_INCLUDE_DIR=/home/MYUSERNAME/repos/cereal-1.3.0/include/ -D PYTHON_EXECUTABLE=/home/MYUSERNAME/python_environments/mlpack_venv/bin/python ../`

```
.
.
.
-- Not building Markdown bindings.
-- Not building Python bindings.
can't load package: package gonum.org/v1/gonum/mat: cannot find package "gonum.org/v1/gonum/mat" in any of:
	/usr/lib/go-1.13/src/gonum.org/v1/gonum/mat (from $GOROOT)
	/home/pradeep/go/src/gonum.org/v1/gonum/mat (from $GOPATH)
-- Gonum not found (missing: GONUM_VERSION_STRING) 
-- Not building Go bindings; the following modules are not available: 
    - Gonum
-- Could NOT find R_roxygen2 (missing: R_ROXYGEN2) 
-- Could NOT find R_Rcpp (missing: R_RCPP) 
-- Could NOT find R_RcppArmadillo (missing: R_RCPPARMADILLO) 
-- Could NOT find R_RcppEnsmallen (missing: R_RCPPENSMALLEN) 
-- Could NOT find R_BH (missing: R_BH) 
-- Could NOT find R_testthat (missing: R_TESTTHAT) 
-- Could NOT find R_Rcereal (missing: R_RCEREAL) 
-- Not building R bindings, Following modules are not available:
    - roxygen2
    - Rcpp
    - RcppArmadillo
    - RcppEnsmallen
    - BH
    - testthat
    - Rcereal
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/MYUSERNAME/repos/mlpack/build
```

I am not worried about building Go and R bindings. I am only interested in python bindings

**Comment by rcurtin** [comment]
There's no error in that output (only warnings).  But you have to specify `-DBUILD_PYTHON_BINDINGS=ON` if you want to build Python bindings, and then you can additionally optionally specify `PYTHON_EXECUTABLE` if you have a specific Python interpreter you want to use.

**Comment by pradkrish** [comment]
Jesus, of course, thanks. I totally missed that option, never build a new package with children around (note to oneself) :) Thanks.

**Comment by rcurtin** [comment]
No worries!  Hopefully it should work now. :+1:
