### ISSUE TITLE
Cereal Compiling CMake problem in /CMakeList.txt

### ISSUE THREAD

**Issue by rxng8** [mlpack/mlpack#2702]
#### Issue description

I have encountered the problem when I tried to build the mlpack from the master branch (not the current release 3.4.2). The problem is about cereal package not being installed when I execute the command `cmake ../`. We can build normally from the version 3.4.2 because its /CMakeList.txt does not have the line `find_package(cereal "${CEREAL_VERSION}" REQUIRED)` as in line 416 the same file in the master branch.

#### Your environment

 * version of mlpack: master branch
 * operating system: Ubuntu20
 * compiler: 
 * version of dependencies (Boost/Armadillo):
 * any other environment information you think is relevant: 

#### Steps to reproduce

Build cmake from master branch, without any cereal package installed.

#### Expected behavior

We should write cmakelist to automatically download, setup, and configure for us, not having to manually install any package.

#### Actual behavior

Currently `apt-get install cereal` just install version 0.x.x of cereal, which is not compatible with the current requirement of the mlpack package. So even when we install cereal package, it still does not work.

**Comment by Yashwants19** [comment]
@rxng8 You must use `apt-get install libcereal-dev` for installing the required cereal package.

**Comment by rxng8** [comment]
Thanks ! That definitely help! Is it neccessary to edit cmakelist so that it automatically download and install. If yes then I can work on it!

**Comment by zoq** [comment]
@Yashwants19 incorporates cereal in https://github.com/mlpack/mlpack/pull/2685.

**Comment by rxng8** [comment]
Great!
