### ISSUE TITLE
I am unable to install the mlpack package on Windows 10.

### ISSUE THREAD

**Issue by Prath06** [mlpack/mlpack#2710]
I am unable to install the mlpack package on Windows 10.

command: pip install mlpack
message:

ERROR: Could not find a version that satisfies the requirement mlpack (from versions: none)
ERROR: No matching distribution found for mlpack

_Originally posted by @Prath06 in https://github.com/mlpack/mlpack/issues/2176#issuecomment-726250848_

**Comment by Prath06** [comment]
Please help me.
I am using Python 3.7.x on Windows 10

**Comment by NippunSharma** [comment]
There is no need to do pip install. If you have installed mlpack on your system then you can simply import mlpack in python. Refer to [this](https://github.com/mlpack/mlpack#6-using-mlpack-from-python)

**Comment by zoq** [comment]
Also there is no pip package for Windows at this point, so you have to either build it manually or have to wait until the pip package is ready.

**Comment by Prath06** [comment]
Thanks for the help. But it is available in : https://pypi.org/project/mlpack/

**Comment by zoq** [comment]
For Linux and macOS, but not for Windows, at least not yet.
