### ISSUE TITLE
Adding a FAIL message when data::Load is used in test files.

### ISSUE THREAD

**Issue by Abilityguy** [mlpack/mlpack#2715]
### What is the desired addition or change?
Adding a ```FAIL()``` message whenever we use ```data::Load()``` to load data in the testing suite.
After a discussion [here](https://github.com/mlpack/mlpack/pull/2671#issuecomment-726784957), it was decided that opening an issue on this would be a good idea.

### What is the motivation for this feature?

If there is an error in loading the file, there are instances where the test case can pass (if test case depends on input size) even though there is an error in loading the file.

Even if the test doesn't depend on the input size in any way, I think it would be a good idea to add the ```FAIL()``` message just to ensure better testing and debugging.

Most of the files in the testing suite (```src/mlpack/tests```) use the ```FAIL()``` message feature but there are a few files that don't. 

### If applicable, describe how this feature would be implemented.

Basically you have to wrap the loading statement into an if clause with a ```FAIL()``` message.

Replace ```data::Load(x, y)``` with
``` 
if (!data::Load(x, y))
  FAIL("Unable to load data x!");
```
Replace ```data::Load(x, y, z)``` with
``` 
if (!data::Load(x, y, z))
  FAIL("Unable to load data x!");
```
Replace ```data::Load(x, y, z, p)``` with
``` 
if (!data::Load(x, y, z, p))
  FAIL("Unable to load data x!");
```
Replace ```data::Load(x, y, z, p, q)``` with
``` 
if (!data::Load(x, y, z, p, q))
  FAIL("Unable to load data x!");
```
Note: Do not replace the ```data::Load()``` enclosed within a ```REQUIRE()``` call. This change only has to be made for free ```data::Load()``` calls not enclosed in any other function call. 

### Additional information?

These are the files where the change should be made.
If I have missed out any files, let me know in the comments.
It would be good if we try to break this down into multiple Pull Requests of 5-10 files since it would be easier to review.

- [x] akfn_test.cpp
- [x] aknn_test.cpp
- [x] callback_test.cpp
- [x] cf_test.cpp
- [x] decision_tree_test.cpp
- [x] facilities_test.cpp
- [ ] feedforward_network_2_test.cpp
- [ ] feedforward_network_test.cpp
- [ ] io_test.cpp
- [ ] kfn_test.cpp
- [ ] knn_test.cpp
- [ ] krann_search_test.cpp
- [ ] ksinit_test.cpp
- [ ] lars_test.cpp
- [ ] lin_alg_test.cpp
- [ ] lmnn_test.cpp
- [ ] load_save_test.cpp
- [ ] lrsdp_test.cpp
- [ ] lsh_test.cpp
- [ ] matrix_completion_test.cpp
- [ ] nbc_test.cpp
- [ ] nystroem_method_test.cpp
- [ ] one_hot_encoding_test.cpp
- [ ] pca_test.cpp
- [ ] quic_svd_test.cpp
- [ ] radical_test.cpp
- [ ] random_forest_test.cpp
- [ ] svd_incremental_test.cpp
- [ ] svdplusplus_test.cpp
- [ ] main_tests/cf_test.cpp
- [ ] main_tests/hmm_generate_test.cpp
- [ ] main_tests/hmm_loglik_test.cpp
- [ ] main_tests/hmm_train_test.cpp
- [x] main_tests/preprocess_split_test.cpp 
- [ ] main_tests/hmm_viterbi_test.cpp
- [ ] main_tests/preprocess_imputer_test.cpp

These would be a good start for new contributors to dive into the codebase.

**Comment by NippunSharma** [comment]
Hi, I am taking up `akfn_test.cpp`, `aknn_test.cpp`, `callback_test.cpp`, `cf_test.cpp`, `decision_tree_test.cpp` and `facilities_test.cpp`

**Comment by heisenbuug** [comment]
Hey @Abilityguy, I think we can write a script to automate this one:
`file = open(../feedforward_network_2_test.cpp')
with open("../feedforward_network_2_test.cpp", "rt") as fin:
    with open("feedforward_network_2_test.cpp", "wt") as fout:
        for line in fin:
            if(line.find('data::Load') != -1):
                newLine = ' if (!' + line[0:-2] + ') \n  FAIL("Unable to load data x!"); \n'
                fout.write(line.replace(line, newLine))
                print(newLine)
            else:
                fout.write(line)
`
I think running this python script should do the thing, but I think I need to go through the changes once it's done coz this script won't consider comments and stuff and that can mess up...
Shall I give it a try?

**Comment by Abilityguy** [comment]
Looks good @heisenbuug . You can give it a try.
Only issue with this script is that the ```FAIL()``` message dosen't include the dataset name.

**Comment by heisenbuug** [comment]
Cool, I will add it, it will be some basic file processing stuff only...

**Comment by heisenbuug** [comment]
> Looks good @heisenbuug . You can give it a try.
> Only issue with this script is that the `FAIL()` message dosen't include the dataset name. It would help better when debugging if it did.

I am facing one issue, there are some parts of code where:
```
  REQUIRE(
      data::Load("test_file.csv", test, false, true, arma::arma_binary)
      == true);
```
So as REQUIRE is not on the same line so it will change that as well but it should not, any suggestions @Abilityguy

**Comment by Abilityguy** [comment]
In your python script, you could remove spaces and if the previous characters include ```REQUIRE```. 
Or you could use the ```re``` module in python to write some sort of regex I believe.

But I don't think this case pops up that often so manually weeding it out also makes sense.

**Comment by heisenbuug** [comment]
Yea, I am done with it, making a PR...
Most of the cases were covered, I made a few changes to the script. I think most of the cases will be covered.

**Comment by maksimdrachov** [comment]
Hi,
New to opensource, so possibly a bit slow.

I'm going to take a crack at the following five:
- feedforward_network_2_test.cpp
- feedforward_network_test.cpp
- io_test.cpp
- kfn_test.cpp
- knn_test.cpp

Thanks!

**Comment by NippunSharma** [comment]
Hi @maksimdrachov, I think all these files are already taken by @heisenbuug in PR #2717

**Comment by Abilityguy** [comment]
> Hi @maksimdrachov, I think all these files are already taken by @heisenbuug in PR #2717

Right. This issue will be completed once the two PRs are merged. 
You could take a look at other 'good first issues' [here](https://github.com/mlpack/mlpack/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22). They are good starters for new contributors to the codebase.

**Comment by kushagrabhushan** [comment]
Hi. I'm very new to the open-source community. I'd like to help contribute here. Can someone tell me how to get started?

**Comment by heisenbuug** [comment]
Hii @kushagrabhushan, this issue is already solved. 
You can get started by choosing an issue that has a flag marked as `good first [issue`(here)](https://github.com/mlpack/mlpack/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) to get started.

**Comment by Abilityguy** [comment]
Keep Open.
PR #2717 is yet to be merged.

**Comment by rcurtin** [comment]
@Abilityguy what else needs to be done for #2717?  Should we reopen it and make a few fixes and merge it?

**Comment by Abilityguy** [comment]
@rcurtin I had requested for changes in the PR based on your [comment](https://github.com/mlpack/mlpack/pull/2717#pullrequestreview-536109228). Making these changes should make the PR ready for merge.

**Comment by heisenbuug** [comment]
Hey @rcurtin and @Abilityguy, sorry for not following up, I will complete this ASAP...

**Comment by rcurtin** [comment]
Sounds good---I'd be happy to get it merged whenever it's ready. :+1:

**Comment by rcurtin** [comment]
I think this issue is handled now that #2844 is merged so I'll go ahead and close it. :+1: (Let me know if not and we can reopen it, but I *think* everything is handled. :))

**Comment by Abilityguy** [comment]
Yes. Everything is handled and this issue is now resolved. Thanks everyone for the help! 👍🏼
