### ISSUE TITLE
Program received signal SIGSEGV,Segmentation fault        prefixedoutstream_impl.hpp:51 

### ISSUE THREAD

**Issue by cetcjinjian** [mlpack/mlpack#2721]
#### Issue description
i compile the "simple logging example "

```c++
#include <mlpack/core.hpp>
#include <mlpack/core/util/io.hpp>
// This definition below means we will only compile for the command line.
#define BINDING_TYPE BINDING_TYPE_CLI
#include <mlpack/core/util/mlpack_main.hpp>
using namespace mlpack;
static void mlpackMain()
{
  Log::Debug << "Compiled with debugging symbols." << std::endl;
  Log::Info << "Some test informational output." << std::endl;
  Log::Warn << "A warning!" << std::endl;
  Log::Fatal << "Program has crashed." << std::endl;
  Log::Warn << "Made it!" << std::endl;
}
```
with the command " g++ -o test test.cpp -DDEBUG -g -rdynamic -lmlpack -fopennmp"
the code is compiled normally, but when i run the ./test,it cause core dump
then debug with gdb
it shows 

```bash
Program received signal SIGSEGV, Segmentation fault.
mlpack::util::PrefixedOutStream::BaseLogic<char const*> (this=this@entry=0x6f9640 <mlpack::Log::Debug>, val=@0x7fffffffdb48: 0x4ce758 "Compiled with debugging symbols.")
    at /usr/src/debug/mlpack-3.4.2/src/mlpack/core/util/prefixedoutstream_impl.hpp:51
warning: Source file is more recent than executable.
51	  convert.setf(destination.flags());


```

#### Your environment

 * version of mlpack:3.4.2
 * operating system:centos-release-7-8.2003.0.el7.centos.x86_64
 * compiler:gcc 7.3.1
 * version of dependencies (Boost/Armadillo):boost: 1.74  armadillo: 8.6
 * any other environment information you think is relevant:

**Comment by NippunSharma** [comment]
I don't think it is the problem but it should be `-fopenmp`.

**Comment by cetcjinjian** [comment]
> I don't think it is the problem but it should be `-fopenmp`.

yes,spell error

**Comment by rxng8** [comment]
can you include the path in the project tree to the testing file?
