### ISSUE TITLE
Adding Data pre-processing utils to mlpack

### ISSUE THREAD

**Issue by heisenbuug** [mlpack/mlpack#2722]
### What is the desired addition or change?

As discussed a bit in the [PR](https://github.com/mlpack/examples/pull/137). I suggested the idea of adding some data processing functionality to mlpack. 

I compiled a list of features that can be implemented: 
- [x] **head()**: returns top 5 rows
- [x] **tail()**: returns bottom 5 rows
- [x] **info()**: Already implemented, I was thinking maybe we could add the count of non-null values in front of each attribute, let me know if you guys think it's useful.
- [x] **describe()**: This will return `count` `mean` `std` `25%` `50%(median)` `75%` `max` `min` we can take help of armadillo to implement this method. [this](http://arma.sourceforge.net/docs.html#stats_fns) and [this](http://arma.sourceforge.net/docs.html#running_stat) (Already started working on this one)
- [ ] **hist()**: To get the feel of the data, we can either plot it attributes wise or calling a single method which will plot a histogram for all numerical values. We can use [this](https://github.com/lava/matplotlib-cpp) to plot histograms. Just a single file so easy to handle the dependency. 
- [ ] **valueCount()**: list out all the unique values of any specific attribute
- [x] A method to find the data type of the attributes. 
- [ ] If the attribute is categorical then we might need to convert it into numerical values, a function for that will also be helpful. 
- [x] adding a constructor that can take an already-constructed matrix and DatasetInfo(great suggestion by @rcurtin)

I will be adding more features to the list, this seems good enough to get started.
### What is the motivation for this feature?

Loading and creating models is just a part of Machine Learning. The time we invest in understanding data is very important. Based on the nature and properties of datasets we can decide which model to implement. 
My goal is also to create a `Getting Started with ML with mlpack` tutorial, where I will explain everything from feature engineering to model selection to model accuracy. I think this will be a very good starting point for many users. So to make the process more fluid I am planning to implement certain functions to include functionality that would give info about datasets. Like `.info()` `.describe()` from `pandas`

 
### If applicable, describe how this feature would be implemented.

I have already implemented a bit [here](https://github.com/heisenbuug/Data-Pre-Processing/blob/main/data.cpp)

### Additional information?

There are some points which we need to discuss before starting the implementation. My concerns:
* Currently I made a class `Data`, so to access `.info()` we have to initialize the object of `Data`, I hope the new class won't be a problem. Although I think this is a decent way to initialize, I am open to any better design suggestions.

* Where to put this class exactly.

* Before starting I think we should list down some basic features so that I can start working and then keep discussing more possible features.

### Feature Description/Discussion
`valueCounts`: I've implemented a function that will list out all the unique values of any specific attribute. As this feature is more useful with strings only I had to use file processing and extract each row(basically I parsed the whole data file again). I think this will be resource-intensive, but I think this is a needed feature. Any thoughts on this?

`hist`: For implementing hist method I thought I would be using `matplotlib.cpp`, but it requires a working installation of python matplotlib, that might increase dependencies, anyone has any suggestions?

**Comment by RishabhGarg108** [comment]
Thanks for opening this issue. I think it would be an awesome thing to have.
No one can deny the fact that most of the time we are just messing around with the data in machine learning. So, in my opinion, it would be great to have a `Data` class and in it we can have all of the pre-processing methods at our disposal.
Some of the utilities other than what you mentioned could be :-

1. A function to remove outliers. In this the user can either clip the data at some percentile value or could pass in the minimum and maximum values and the values outside the range could be dropped.
2. A method to easily add or drop new rows or columns.
3. A method to apply some transformation to a specific column/row/whole dataset.
4. And the most useful one would be to query certain rows or columns from the dataset based on some conditions. 

This seems like a great thing to work on. And I would definitely love to assist you with this.

**Comment by heisenbuug** [comment]
Hey, @RishabhGarg108 thank you for the feedback and suggestions, once we have a discussion we can start working on this one, I am very excited to work on this.

**Comment by AvikantSrivastava** [comment]
Hey, @heisenbuug @shrit  I've been working on a similar CSV processing module.
Here is the code https://github.com/AvikantSrivastava/Neural-Nets-from-scratch-in-C-Cuda/blob/main/helper/csv.h
Do tell me if you feel I could help you with anything.

**Comment by heisenbuug** [comment]
I updated the issue and added a small list of features for now. 
@zoq any suggestions or comments? 
Also, where will we put this class?

**Comment by shrit** [comment]
It will be easier to review the code by opening a pull request.
@heisenbuug under `core/data` will be fine

**Comment by heisenbuug** [comment]
> It will be easier to review the code by opening a pull request.
> @heisenbuug under `core/data` will be fine

ok, @shrit I am working on the describe method, once it's done I will make a PR.

**Comment by jeffin143** [comment]
@heisenbuug You can take the some of the bits from https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/preprocess/preprocess_describe_main.cpp

**Comment by heisenbuug** [comment]
@rcurtin, Hey I am sorry for being late on this, I've updated the code and also updated the issue and added a new section `Feature Description/Discussion` where we can document or update any specific feature if we need to track it for a long time.

**Comment by rcurtin** [comment]
@heisenbuug sounds good.  It's probably worth taking a look at the style and design guide (https://github.com/mlpack/mlpack/wiki/DesignGuidelines) to make sure that what you're implementing matches the conventions we are using. :+1:  I'll take a look at #2727 when I have a chance.

**Comment by deeplearningera** [comment]
Is it still open for contributions or done almost?

**Comment by heisenbuug** [comment]
Heyyy @deeplearningera actually we are changing things a bit before working on this. We are planning to use existing functionality more...I will update the issue to reflect everything...

**Comment by swaingotnochill** [comment]
@heisenbuug can u please update the issue and give a brief on how can we solve it. I would like to work on this issue, if it's fine with u.

**Comment by AditiThirdEye** [comment]
For the second last task would it be okay if I implement one hot encoding?
Along with that I would also like to work on value count and hist function.
If that is okay then can you please assign this issue to me.

Regards, 
Aditi

**Comment by AditiThirdEye** [comment]
What can I do to contribute to this thread?
I known one hot encoding for the second last issue and also have idea about the unmarked task from the task list, can you please guide me how can I contribute.

Regards, 
Aditi

**Comment by heisenbuug** [comment]
@AditiThirdEye we already have [one hot encoding](https://github.com/heisenbuug/mlpack/blob/master/src/mlpack/core/data/one_hot_encoding.hpp) in mlapck.

Maybe you can start looking at `hist`?
We can use `matplotlib.cpp`. It's a single header file.

There is also [this](https://github.com/mlpack/mlpack/pull/2727) PR which I made
but it requires many changes and might have to alter the code completely. 
I will soon start working on this again. 
@rcurtin also mentioned the use of `xtensor`.
We also need to explore that angle.

Go through the whole discussion once.

In the meantime you can start working on `hist` we can integrate it once we setup
a base class for `DataFrame`

**Comment by AditiThirdEye** [comment]
Surely I'll start looking into the hist, got it 👍🏼

**Comment by AditiThirdEye** [comment]
@heisenbuug , 
I have made this [PR](#3039 ) which include implementation of the histogram plotting function.
Can you please review it and guide me how can I improve my contribution.

Thanks

**Comment by Ashutosh-codes** [comment]
Hello @heisenbuug 
I am new to contibution. I have learnt algorithms in machine learning and know the maths behind it.
Can you please guide me how can I contribute to this or any other thread. It would be  very helpful for me.
Thanks
