### ISSUE TITLE
The mlpack build failed after using make command

### ISSUE THREAD

**Issue by Lokesh-Jawale** [mlpack/mlpack#2741]
c++: fatal error: Terminated signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/mlpack/methods/kde/CMakeFiles/mlpack_kde.dir/build.make:82: src/mlpack/methods/kde/CMakeFiles/mlpack_kde.dir/kde_main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3063: src/mlpack/methods/kde/CMakeFiles/mlpack_kde.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
^Cmake[2]: *** [src/mlpack/methods/neighbor_search/CMakeFiles/mlpack_knn.dir/build.make:82: src/mlpack/methods/neighbor_search/CMakeFiles/mlpack_knn.dir/knn_main.cpp.o] Interrupt
make[2]: *** [src/mlpack/methods/neighbor_search/CMakeFiles/mlpack_kfn.dir/build.make:82: src/mlpack/methods/neighbor_search/CMakeFiles/mlpack_kfn.dir/kfn_main.cpp.o] Interrupt
make[2]: *** [src/mlpack/methods/cf/CMakeFiles/mlpack_cf.dir/build.make:82: src/mlpack/methods/cf/CMakeFiles/mlpack_cf.dir/cf_main.cpp.o] Interrupt
make[1]: *** [CMakeFiles/Makefile2:3414: src/mlpack/methods/neighbor_search/CMakeFiles/mlpack_kfn.dir/all] Interrupt
make[1]: *** [CMakeFiles/Makefile2:2658: src/mlpack/methods/cf/CMakeFiles/mlpack_cf.dir/all] Interrupt
make[1]: *** [CMakeFiles/Makefile2:3441: src/mlpack/methods/neighbor_search/CMakeFiles/mlpack_knn.dir/all] Interrupt
make: *** [Makefile:160: all] Interrupt

**Comment by rcurtin** [comment]
@Lokesh-Jawale I'm guessing that your system doesn't have enough RAM to compile mlpack.  Try compiling with only one core (i.e. `make` instead of `make -jX`), and try closing down other applications while compiling mlpack so that more RAM is available.  Typically compiling mlpack's tests with one core requires ~2-3GB of RAM. :+1:

**Comment by Lokesh-Jawale** [comment]
@rcurtin I tried building the mlpack with only ( make ) but it is still showing me the same error.

c++: fatal error: Terminated signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/mlpack/methods/cf/CMakeFiles/mlpack_cf.dir/build.make:82: src/mlpack/methods/cf/CMakeFiles/mlpack_cf.dir/cf_main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2658: src/mlpack/methods/cf/CMakeFiles/mlpack_cf.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

**Comment by rcurtin** [comment]
How much RAM do you have?  I suspect it isn't enough.

**Comment by Lokesh-Jawale** [comment]
I have 4gb ram and i3 2.30Ghz processor and 2gb nvidia graphics card.
What are the minimum system requirements for building mlpack.

**Comment by zoq** [comment]
Depending on how much memory you already use, this might be not enough, when you build mlpack you can track the free memory with `free -m` or `htop`. An easy solution might be to increase the SWAP size, if you already build with `make -j1`.

**Comment by Lokesh-Jawale** [comment]
I am new to open source and I want to contribute to the mlpack but I am unable to build it due the above issues(less ram) 
can I just install mlpack instead of building it from the source and get familiar with it.
Or is it important to build mlpack from source and explore it .

**Comment by shrit** [comment]
@Lokesh-Jawale What system are you using?

**Comment by Lokesh-Jawale** [comment]
fedora 33
intel i3 2.30Ghz
4gb ram
2gb swap

**Comment by shrit** [comment]
If it is very complicated to compile mlpack on your system, you can install mlpack directly if you are using `Fedora`. I believe that the Fedora package manager has a mlpack package inside.

**Comment by Lokesh-Jawale** [comment]
I have installed mlpack from package manager as you said.
Is it necessary to build mlpack from source if I want to contribute to mlpack?
I am new to open source can you please guide on how to get started?

**Comment by Sirish07** [comment]
Hey, I think you can increase your swap space (there are resources available on the net) and try building once again using "make" command.

**Comment by Lokesh-Jawale** [comment]
@Sirish07 Thanks for the solution . It worked for me.
