### ISSUE TITLE
build fail without MPL code included

### ISSUE THREAD

**Issue by allingo** [mlpack/mlpack#2743]
I had follow https://github.com/mlpack/mlpack/tree/3.4.2/src/mlpack/core/arma_extend. then build failed.

mlpack/src/mlpack/methods/bayesian_linear_regression/bayesian_linear_regression_main.cpp:110:1:   required from here
/usr/local/include/boost/serialization/access.hpp:116:9: error: ‘class arma::Mat<double>’ has no member named ‘serialize’

how to fix this?

**Comment by rcurtin** [comment]
Hey @allingo, make sure that you don't `#include <armadillo>` before `#include <mlpack/core.hpp>`.  This restriction won't exist in future versions of mlpack.  Basically, mlpack patches Armadillo during inclusion, but it can't do this if Armadillo has already been included.
