### ISSUE TITLE
Problem with LARS when successive calls

### ISSUE THREAD

**Issue by gscarella** [mlpack/mlpack#2749]
Hello,

### Issue description
I have a problem with LARS when I make several successive solutions with it, in Lasso computations (for an Active Set method).                                                                                 
One solution never ends and causes a memory leak (which is annoying) while the problem doesn't seem to be degenerated.

It seems there happens a problem of numerical precision in LARS::Train, it gets stuck in the main loop.                                                                                                                   

### My environment
* mlpack version: 3.4.2
* armadillo  version:  9.900.4
* boost   version: 1.74.0 
* The problem was encountered on Linux (Ubuntu 20 and CentOS 7).

I join an example with a data file.

#### Expected behavior
In the example, code should terminate and print "Computation completed"

#### Actual behavior
In the example, execution gets stuck and raises a memory leak at Neuron 7, iteration 3                                                                                                                                                       

Do you  know a way to solve the problem ?
Thanks
G. Scarella

[test_lars.cpp](https://github.com/mlpack/mlpack/files/5636443/test_lars.cpp.txt)
[data_field.bin](https://github.com/mlpack/mlpack/files/5636435/data_field.bin.txt)

**Comment by rcurtin** [comment]
Hi @gscarella, thank you so much for the clear, easy-to-reproduce example.  I can indeed see that for some reason LARS is not converging in this case, but the reason is not trivially obvious to me yet.  As I find time I will try to dig to the bottom of what is wrong. :+1:  As a workaround, I am not sure if it will work, but you could try changing the `useCholesky` parameter, or changing the value of `lambda1`, for instance.

**Comment by gscarella** [comment]
Hello,

I tried with useCholesky set to false but the problem remains.

To be more clear: at line 22 in test_lars.cpp, when the loop goes from Neuron 4 to 9 (= the last Neuron), computation completes but when the loop goes from neuron 0 to 9 as in the attachment, it doesn't work and gets stuck at Neuron 7.

Thanks

**Comment by rcurtin** [comment]
@gscarella this was a very strange edge case that took a while to dig to the bottom of, but I think that I have solved it.  Can you try the fix in #2767 and see if this solves your problem completely?  The test case you gave now does complete successfully, but I haven't verified the results in any other way. :+1:

**Comment by gscarella** [comment]
Thanks a lot @rcurtin  for the fix!
So the example in the bug report works for me too now.
But I have a large number of other examples to test with Lars solver, it may take me several days to check that everything is ok.
I will report it if a problem is found.

**Comment by rcurtin** [comment]
@gscarella sounds good.  I'll merge the LARS fix shortly, and then we can keep this issue open in case you find some other issue. :+1:
