### ISSUE TITLE
Issue with libhdf5.so.103

### ISSUE THREAD

**Issue by PranavReddyP16** [mlpack/mlpack#2754]
While running the make command I keep getting the output : /usr/bin/ld: warning: libhdf5.so.103, needed by /usr/lib/libarmadillo.so, not found (try using -rpath or -rpath-link)

I have even used export LD_LIBRARY_PATH=/usr/local/lib (which is where libmlpack.so is on my system) but the error persists. 

Below is the stderr output when I run make : 
https://pastebin.com/ZqsqKbr0

Any help is greatly appreciated

**Comment by shrit** [comment]
@PranavReddyP16  Can you do  `locate libhd5.so` please?

**Comment by PranavReddyP16** [comment]
@shrit this is the output I got : 
/home/pranav/anaconda3/pkgs/hdf5-1.10.4-hb1b8bf9_0/lib/libhdf5.so
/home/pranav/anaconda3/pkgs/hdf5-1.10.4-hb1b8bf9_0/lib/libhdf5.so.103
/home/pranav/anaconda3/pkgs/hdf5-1.10.4-hb1b8bf9_0/lib/libhdf5.so.103.0.0
/usr/lib/libhdf5.so
/usr/lib/libhdf5.so.200
/usr/lib/libhdf5.so.200.0.0

**Comment by shrit** [comment]
@PranavReddyP16 As you can see you do not have `libhd5.so.103` installed you have only `libhd5.so.200`
The other one is installed by anaconda. If you do not activate anaconda environment, armadillo will never find `libhdf.s0.103`

**Comment by PranavReddyP16** [comment]
Oh yeah that makes sense thanks. I'm guessing it's better to install libhd5.so.103 instead of activating conda every time I want to run make?

**Comment by PranavReddyP16** [comment]
@shrit thanks a lot after a few more tweaks everything works fine. I really appreciate the help
