### ISSUE TITLE
issue compiling mlpack programs

### ISSUE THREAD

**Issue by PranavReddyP16** [mlpack/mlpack#2758]
I was able to build mlpack perfectly fine but when I try to compile any mlpack program using `g++ main.cpp -o main -lmlpack -larmadillo -fopenmp -std=c++11` I get the following error : 

/usr/bin/ld: warning: libarmadillo.so.9, needed by /usr/local/lib/libmlpack.so, may conflict with libarmadillo.so.10
/usr/bin/ld: /usr/lib/libarmadillo.so.9: undefined reference to `H5Ovisit'
collect2: error: ld returned 1 exit status

I am unable to figure out the best way to go about fixing this. Any help is appreciated.

for reference, this is the program I am trying to compile : 

`#include<mlpack/core.hpp>
#include<mlpack/methods/neighbor_search/neighbor_search.hpp>

using namespace mlpack;
using namespace mlpack::neighbor;
using namespace mlpack::metric;

int main()
{
    arma::mat data;
    data::Load("dataset.csv", data, true);

    NeighborSearch<NearestNeighborSort, ManhattanDistance> nn(data);

    arma::Mat<size_t> neighbors;
    arma::mat distances;

    nn.Search(1, neighbors, distances);

    for(size_t i=0;i<neighbors.n_elem;i++)
    {
        std::cout<<"Nearest neighbor of point "<<i<<" is point "<<neighbors[i]<<" and the distance is "<<distances[i]<<std::endl;
    }
}`

Thanks in advance

**Comment by zoq** [comment]
From the error message it looks like you have armadillo 10.x and 9.x installed, can you make sure there is only one version installed, or you link against the version you build mlpack with?

**Comment by PranavReddyP16** [comment]
@zoq I have reinstalled armadillo and made sure there is only one version on my system. Now I'm getting the error :
 
/usr/bin/ld: warning: libarmadillo.so.9, needed by /usr/local/lib/libmlpack.so, not found (try using -rpath or -rpath-link)

along with a bunch of other errors.But when I run `locate libarmadillo.so` it gives the result : 
/usr/lib/libarmadillo.so
/usr/lib/libarmadillo.so.9
/usr/lib/libarmadillo.so.9.800.3

Is there any reason it's not being recognized?

**Comment by zoq** [comment]
Make sure `/usr/lib/` in in your `LD_LIBRARY_PATH`, so you might have to add it, `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/`. Also you can also build with: `g++ -L/usr/lib/`.

**Comment by PranavReddyP16** [comment]
@zoq I've tried both but im getting the same error for some reason. I actually tried setting the variable before and that didn't work. Now even when I tried linking with -L there's no difference either
