### ISSUE TITLE
Adding Gaussian Process Regressor

### ISSUE THREAD

**Issue by NippunSharma** [mlpack/mlpack#2764]
### What is the desired addition or change?
Adding a Gaussian Process Regressor into mlpack.

### What is the motivation for this feature?
GP regression is a powerful tool which can handle non linear data as well. It provides us with the confidence intervals along with 
the mean prediction values. It would be a great addition to the probabilistic methods (#2667) in mlpack.

### If applicable, describe how this feature would be implemented.
Some discussion is present inside #851 but there is definitely room for more discussion. 
Here is a reference to a paper [Gaussian Processes for Regression](https://papers.nips.cc/paper/1995/file/7cce53cf90577442771720a370c3c723-Paper.pdf) .
Also, [this](https://arxiv.org/pdf/1809.01913.pdf) paper helped me a lot in understanding the concept and implementation.

**Comment by NippunSharma** [comment]
If everyone agrees on this I can start working on this ?

**Comment by jeffin143** [comment]
Welcome @NippunSharma from all of us , I think this would be a nice addition to the code base

**Comment by NippunSharma** [comment]
Thanks @jeffin143 I will start working on this and try to open a PR soon.

**Comment by NippunSharma** [comment]
can we keep this open ? as discussed with @rcurtin on IRC this is not the right time for adding a gaussian process regressor but we might want to add the same in the future.

**Comment by bmmogensen** [comment]
I'm interested in using mlpack for GPR. Could you share some of the reasons why this is a bad time for adding a GPR to mlpack?

**Comment by rcurtin** [comment]
What I wrote at the time in the chat was this:

> GP regressors would be nice to add, but at least I am not a GP expert so I don't know that I could do a good job of reviewing the PR

> maybe; in any case, unless we have someone knowledgeable about GP regressors to review the PR, it might not be a great idea to implement it---we could miss some important detail, or implement something that's not the best algorithm, etc.

If we have enough GP expertise amongst ourselves to manage to carefully review the code and consider all the issues related with it, then I think it could be just fine.  I can do my best, but I definitely shouldn't be the only set of eyes looking at it. :)

**Comment by bmmogensen** [comment]
I'd be happy to make a thorough review and doing comparisons with other tools once a PR is in place

**Comment by heisenbuug** [comment]
Heyy, I've contributed a bit to the library now, and I want to dive deeper so if it's okay I would like to start working on this.
I will start by reading the discussions and the paper mentioned. 
Let me know if there is anything important that I should study before starting to work on this.
