### ISSUE TITLE
Use of Centroid of clusters in DBSCAN ?

### ISSUE THREAD

**Issue by Anmol2001** [mlpack/mlpack#2765]
Hi all, I was going through the DBSCAN implementation and when I came  across : 
  src/mlpack/methods/dbscan/dbscan_impl.hpp 
I found that there is calculation of centroid of clusters in DBSCAN, but **DBSCAN is a density based scanning algorithm and** **there is no use of centroid of clusters** in it as it used the concept of epsilon , minpoints. Also I have gone through the Centroid function in the documentation and it is mentioned to use for K means clustering. 

So does it mean something else? If so, then a little explanation in comments will be appreciated. I have attached the part of code where it is calculated for clarity 😃.
````
// Now calculate the centroids.
  centroids.zeros(data.n_rows, numClusters);

  // Calculate number of points in each cluster.
  arma::Row<size_t> counts;
  counts.zeros(numClusters);
  for (size_t i = 0; i < data.n_cols; ++i)
  {
    if (assignments[i] != SIZE_MAX)
    {
      centroids.col(assignments[i]) += data.col(i);
      ++counts[assignments[i]];
    }
  }

  // We should be guaranteed that the number of clusters is always greater than
  // zero.
  for (size_t i = 0; i < numClusters; ++i)
    centroids.col(i) /= counts[i];

  return numClusters;
}
````

**Comment by rcurtin** [comment]
You can see that there are a few overloads of `Cluster()`.  The one that does the real work of DBSCAN is not the one you've pointed out.  The code here is a convenience to the user, who may not just want cluster assignments but also the centroids associated with each cluster.

**Comment by Anmol2001** [comment]
@rcurtin Yes, there are overloads of `Cluster()` (which has overloading for DBSCAN) , but I was referring here to `Centroid()`. Secondly as you said that additional information of centroids may be provided to the user but in many cases except spherical clusters, the centroid may lie outside the cluster, so will that be okay to provide it to the user?

**Comment by rcurtin** [comment]
There is no function called `Centroid()`.  I don't understand what you are asking here.  This functionality is provided as a convenience to the user, so that *if* they want to compute the centroids of their clusters afterwards, they do not need to do that manually.  If it is a setting where it does not make sense to compute the centroids of their clusters, they can call an overload of `Cluster()` that does not return centroids.

**Comment by Anmol2001** [comment]
@rcurtin now it's clear .Thanks a lot .I am new here, and trying to get started.

**Comment by Anmol2001** [comment]
The concern was discussed and understood. : )
