### ISSUE TITLE
Disabling all the bindings by default.

### ISSUE THREAD

**Issue by RishabhGarg108** [mlpack/mlpack#2773]
As discussed yesterday in the IRC, some of the bindings are by default being built with cmake and it is cumbersome to manually switch them off since for most cases, people don't need them. So it might be a good idea to disable all of them by default.
For this, there are to approaches :- 
1. To disable all the bindings by default. (suggested by @rcurtin and definitely a valid approach)
2. To add another option `-DBUILD_BINDINGS=OFF`. This option could be given precedence over all other `BUILD_X_BINDINGS` and it will enable/disable all of the bindings at once. (This option could be useful if lets say we add or change any `xx_main.cpp` file and we want to test if all bindings are correctly working or not.)

I think both the approaches are fine, and we can do whatever fits best for most.

**Comment by rcurtin** [comment]
This is a nice issue for someone who has a little bit of knowledge with CMake and is looking to contribute. :+1:  I'd suggest the first of the two approaches (I think it would be easier), but either works.

**Comment by RishabhGarg108** [comment]
I would like to go ahead with this. Through this issue, I can probably one more skill to my bag. :)
I would go with the first approach.
Can you suggest me where shall I start looking ?
Thanks!

**Comment by jeffin143** [comment]
@RishabhGarg108 You can toggle the following https://github.com/mlpack/mlpack/blob/4d01fe5e911faec3fb450550ec6272a09c55eade/CMakeLists.txt#L64 , It is currently ON by default you can switch it off and same with others

**Comment by RishabhGarg108** [comment]
Thanks @jeffin143 !

**Comment by Yashwants19** [comment]
Addressed in #2782.
