### ISSUE TITLE
c++: fatal error: Killed signal terminated program cc1plus

### ISSUE THREAD

**Issue by BJWiley233** [mlpack/mlpack#2775]
Hi,
My build always fails around 84% when building the first *test.cpp because it runs out of memory.  I only have 8GB memory.  Is it required to build these tests?  Or is there a way to do it with less memory.
Brian

**Comment by shrit** [comment]
Hello,
If you can, would it be possible to increase the size of your swap partition?
This might help in resolving the issue.
Also, try to reduce the number of core used. By using `make -j1`
Do not hesitate in asking if the problem persists.

**Comment by BJWiley233** [comment]
Thanks seems to be working now.  I now have issue that building with R bindings cannot find my Rcpp package.  Is there no -D options to set the libraries location for R?  On linux this would be under `/home/user/R/x86_64-pc-linux-gnu-library/4.0` but the binary is under `/usr/bin/R`.

**Comment by BJWiley233** [comment]
Seems like since using root privileges my R `.libPaths()` needs to be update to also include that folder.  Let me try setting that.

**Comment by BJWiley233** [comment]
Ugh almost there.  Now got error from this file in R bindings.  Seems there is missing a ')' in the build in file `src/mlpack/bindings/R/cmake_install.cmake:41` see below.  Is this an error in the generated file from `make` or just a one off mistake?
```

execute_process(
         COMMAND R CMD INSTALL mlpack_3.4.2.tar.gz
         WORKING_DIRECTORY /home/coyote/Downloads/mlpack-3.4.2/build/src/mlpack/bindings/R
```

**Comment by BJWiley233** [comment]
Look like you are missing a ")" here in file `mlpack/src/mlpack/bindings/R/CMakeLists.txt`.  Also package is spelled wrong but nobody will care :)
![Selection_019](https://user-images.githubusercontent.com/26236052/102678818-cca24680-4178-11eb-9a40-2a6846930a2f.png)

**Comment by BJWiley233** [comment]
One last question since I got mlpack to finish installing.  It installed the R bindings as package to my R library but during installation it found my anaconda `site-packages` folder for some requirements which is good and I assumed that the mlpack python package would also be installed under the anaconda `site-packages` but it's only in the `build` bindings directory.  So now I don't know where to move everything in the `build../../bindings/python` folder.  Can I just move the `mlpack` and `mlpack.egg-info` folder to my `site-pcakages`?  I don't need those `generate***.cpp` files right?  Also after that I can just delete the entire `mlpack-3.4.2` folder including build directory right?  Cause its nearly 10GB in size.  C++ compiles and binaries work fine under local folders.

**Comment by jeffin143** [comment]
Cc @Yashwants19 , since you have written the code , could you answer

**Comment by pietglas** [comment]
About the memory greediness: would it be an idea to add this as a warning in the readme for eager and unexperienced people? :) My computer crashed when i tried to built the first time. Increasing swap size and building single core indeed resolved the issue, i needed about 8 gb of free memory.

**Comment by rcurtin** [comment]
@BJWiley233 I believe moving the `mlpack/` folder into `site-packages` should work, and I think the only files that should be necessary are the `.py`, `.pyx`, `.pxd`, and `.so`/`.dylib` files (depending on if you're on Linux or OS X).  The `generate_*.cpp` and `generate_*` programs shouldn't be necessary.

@pietglas yeah, that would be a good idea for now.  But we have had *lots* of reports like this one recently, and we've been digging into why mlpack takes *so much* compiler memory (it didn't used to).  We have some preliminary results if you're interested in #2777, but we still have yet to decide on a strategy and then move forward on it---so it could be a little while until these issues are fully worked out and the compilation RAM footprint is smaller. :+1:

**Comment by Yashwants19** [comment]
Thanks @jeffin143 for including me here. Thanks @BJWiley233 for reporting the issue -- definitely R-bindings installation process is not working properly. Soon I will open a PR to resolve this. :+1:

**Comment by r00t3r-god** [comment]
I know this has been already answered, but I faced the same problem today while building mlpack.. [this](https://stackoverflow.com/a/47374605/9138660) worked for me

**Comment by BJWiley233** [comment]
So I just realized that the python bindings got installed to `/usr/local/lib/python3.7/site-packages/mlpack-3.4.2-py3.7-linux-x86_64.egg/mlpack` instead of `/home/coyote/anaconda3/lib/python3.7/site-packages` despite setting the `-D` flag for `PYTHON_EXECUTABLE=/home/coyote/anaconda3/bin/python` in full cmake call below.  I don't even have a python installation in my `/usr/local/bin`.  Is there possibility to eventually set a cmake parameter to indicate the location of the python installation.  It seems to default to `/usr/local`?

```
cmake -D DEBUG=ON -D PROFILE=ON -D BOOST_ROOT=$BOOST -D ARMADILLO_INCLUDE_DIR=/usr/include -D ARMADILLO_LIBRARY=/usr/lib/x86_64-linux-gnu/libarmadillo.so -D BUILD_CLI_EXECUTABLES=ON -D BUILD_PYTHON_BINDINGS=ON -D PYTHON_EXECUTABLE=/home/coyote/anaconda3/bin/python -D BUILD_R_BINDINGS=ON -D R_EXECUTABLE=/usr/bin/R -D BUILD_TESTS=ON -D ENSMALLEN_INCLUDE_DIR=/usr/local/include -D DOXYGEN_EXECUTABLE=/usr/bin/doxygen ../
```

**Comment by rcurtin** [comment]
@BJWiley233 #2797 is merged now, so now you can specify `PYTHON_INSTALL_PREFIX` and it should install to the desired location. :+1:  Feel free to reopen this issue or open a new one if you find any more problems. :)
