### ISSUE TITLE
Block Kyrlov Method Potentially Unstable 

### ISSUE THREAD

**Issue by lltempacc** [mlpack/mlpack#2796]
The Block Krylov Method is potentially unstable in floating-point arithmetic, https://arxiv.org/pdf/2002.01387.pdf (see algorithm 10). A Block Lanczos method can be implemented (algorithm 11 or another Lanvzos variant) to alleviate this issue.

**Comment by zoq** [comment]
Wow great survey, thanks for the reference, have to take a closer look.

**Comment by hello-fri-end** [comment]
Is this issue still open? I can read up on Block Lanczos method and try to implement it.

**Comment by lltempacc** [comment]
I am glad you like the survey. The implementation of Block Lanczos should be mostly straightforward. However, an issue is that for systems where these methods converge slowly (small spectral gap) is that many subspace iterations may be needed to converge the singular values/vectors. The double reorthogonalization step scales poorly with this (as you need to reorthogonalize against all previous basis vectors)  and hence efficient Lanczos methods have been significantly investigated in the literature. (This is also mentioned in the provided reference). The "ultimate" implementation would be a Block Lanczos method where partial reorthogonalization is used or an implicitly restarted Lanczos algorithm.

**Comment by hello-fri-end** [comment]
Thank you for the response. I'm relatively new to Machine Learning. I'll give the article a thorough read and let you know if I face any issues. :)

**Comment by hello-fri-end** [comment]
I'm sorry for the late response. It took me a while to get my head around Randomized SVDs. I found a reference online for the Block Lanczos method with partial reorthogonalization:

http://www.math.kent.edu/~reichel/publications/blklbd.pdf ( Algorithm 2.1)

Is this what are you were talking about?

**Comment by rcurtin** [comment]
It would be great, if we implement this, to try and find a test case where block Krylov is unstable but block Lanczos works fine.  Definitely would be super awesome to add though. :+1:

**Comment by lltempacc** [comment]
> I'm sorry for the late response. It took me a while to get my head around Randomized SVDs. I found a reference online for the Block Lanczos method with partial reorthogonalization:
> 
> http://www.math.kent.edu/~reichel/publications/blklbd.pdf ( Algorithm 2.1)
> 
> Is this what are you were talking about?

Sorry for the very late reply - I missed the notifications. 

Yes, something like algorithm 2.1 is what I was talking about. I haven't found any specific problems people have used where BK is unstable but BL is stable for these randomized methods. Although, I believe any very poorly conditioned matrix should work...
