### ISSUE TITLE
Errors from Static Code Analysis Report

### ISSUE THREAD

**Issue by gauravghati** [mlpack/mlpack#2798]
#### Issue description
- Below is the list of errors and warnings from the static code analysis report of PVS-studio.
- For more details like the error type and line number of the error, you can view  [the HTML format](https://gauravghati.github.io/StaticCodeAnalysisReport/) of the report.
- You can pick any of the unchecked errors from the list, and work on them.

#### Steps to resolve a few issues
- Take a look at [#2745](https://github.com/mlpack/mlpack/pull/2745/), an example of `LSTM Layer` for move assignment operators, make sure to add tests.

#### list of the errors and warnings -
- [x] 1) **mlpack/src/mlpack/methods/adaboost/adaboost_model.hpp**	26	warn V690 
`The 'AdaBoostModel' class implements a move constructor but lacks the move assignment operator. It is dangerous to use such a class.`

- [x] 2) **mlpack/src/mlpack/methods/adaboost/adaboost_model.cpp**	74	warn V794 
`The assignment operator should be protected from the case of 'this == &other'.`

- [x] 3) **mlpack/src/mlpack/core/tree/hrectbound.hpp**	54	warn	V690 
`The 'HRectBound' class implements a move constructor, but lacks the move assignment operator. It is dangerous to use such a class.`

- [x] 4) **mlpack/src/mlpack/core/tree/ballbound.hpp** 32	warn	V690 
`The 'BallBound' class implements a move constructor, but lacks the move assignment operator. It is dangerous to use such a class.`

- [x] 5) **mlpack/src/mlpack/core/tree/hollow_ball_bound.hpp** 33	warn	V690 
`The 'HollowBallBound' class implements a move constructor, but lacks the move assignment operator. It is dangerous to use such a class.`

- [x] 6) **mlpack/src/mlpack/core/tree/hollow_ball_bound_impl.hpp**	82	warn	V794 
`The assignment operator should be protected from the case of 'this == &other'.`

- [x] 7) **mlpack/src/mlpack/core/tree/cellbound.hpp**	75	warn	V690 
`The 'CellBound' class implements a move constructor, but lacks the move assignment operator. It is dangerous to use such a class.`

- [x] 8) **mlpack/src/mlpack/core/tree/rectangle_tree/r_tree_split_impl.hpp**	441	err	V758 
`The 'range' reference becomes invalid when temporary object returned by a function is destroyed.`

- [x] 9) **mlpack/src/mlpack/core/tree/rectangle_tree/discrete_hilbert_value.hpp**	29	warn	V690 
`The 'DiscreteHilbertValue' class implements a move constructor, but lacks the move assignment operator. It is dangerous to use such a class.`

- [x] 10) **mlpack/src/mlpack/methods/amf/update_rules/svd_incomplete_incremental_learning.hpp**	53	err	V730 
`Not all members of a class are initialized inside the constructor. Consider inspecting: currentUserIndex.`

- [x] 11) **mlpack/src/mlpack/methods/amf/update_rules/svd_complete_incremental_learning.hpp**	56	err	V730 
`Not all members of a class are initialized inside the constructor. Consider inspecting: currentUserIndex, currentItemIndex.`

- [x] 12) **mlpack/src/mlpack/methods/amf/update_rules/svd_complete_incremental_learning.hpp**	172	err	V730 
`Not all members of a class are initialized inside the constructor. Consider inspecting: n, m, isStart.`

- [x] 13) **mlpack/src/mlpack/methods/amf/termination_policies/simple_residue_termination.hpp**	42	warn	V730 
`Not all members of a class are initialized inside the constructor. Consider inspecting: residue, iteration, normOld, nm.`

- [x] 14) **mlpack/src/mlpack/methods/range_search/range_search.hpp**	42	warn	V690 
`The 'RangeSearch' class implements a move constructor, but lacks the move assignment operator. It is dangerous to use such a class.`

- [x] 15) **mlpack/src/mlpack/methods/range_search/range_search_impl.hpp**	261	warn	V1004 
`The 'referenceTree' pointer was used unsafely after it was verified against nullptr. Check lines: 257, 261.`

- [x] 16) **mlpack/src/mlpack/methods/fastmks/fastmks.hpp**	63	warn	V690 
`The 'FastMKS' class implements a move constructor, but lacks the move assignment operator. It is dangerous to use such a class.`

- [x] 17) **mlpack/src/mlpack/methods/fastmks/fastmks_model.hpp**	34	warn	V690 
`The 'FastMKSModel' class implements a move constructor, but lacks the move assignment operator. It is dangerous to use such a class.`

- [x] 18) **mlpack/src/mlpack/methods/fastmks/fastmks_model.cpp**	73	warn	V794 
`The assignment operator should be protected from the case of 'this == &other'.`

- [x] 19) **mlpack/src/mlpack/methods/hmm/hmm_model.hpp**	33	warn	V690 
`The 'HMMModel' class implements a move constructor, but lacks the move assignment operator. It is dangerous to use such a class.`

- [x] 20) **mlpack/src/mlpack/methods/hoeffding_trees/hoeffding_tree.hpp**	61	warn	V690 
`The 'HoeffdingTree' class implements a copy constructor, but lacks the copy assignment operator. It is dangerous to use such a class.`

- [x] 21) **mlpack/src/mlpack/methods/hoeffding_trees/hoeffding_tree_model.cpp**	64	warn	V794 
`The assignment operator should be protected from the case of 'this == &other'.`

- [x] 22) **mlpack/src/mlpack/methods/hoeffding_trees/hoeffding_tree_model.cpp**	92	warn	V794 
`The assignment operator should be protected from the case of 'this == &other'.`

- [x] 23) **mlpack/src/mlpack/methods/kde/kde.hpp**	88	warn	V690 
`The 'KDE' class implements a move constructor, but lacks the move assignment operator. It is dangerous to use such a class.`

- [x] 24) **mlpack/src/mlpack/methods/kmeans/dual_tree_kmeans_rules_impl.hpp**	160	warn	V519 
`The 'adjustedScore' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 159, 160.`

- [x] 25) **mlpack/src/mlpack/methods/kmeans/dual_tree_kmeans_rules_impl.hpp**	21	err	V730 
`Not all members of a class are initialized inside the constructor. Consider inspecting: lastBaseCase.`

- [ ] 26) **mlpack/src/mlpack/methods/lars/lars.cpp**	420	warn	V688 
`The 'activeSet' local variable possesses the same name as one of the class members, which can result in a confusion.`

- [x] 27) **mlpack/src/mlpack/methods/preprocess/scaling_model.hpp**	29	warn	V690 
`The 'ScalingModel' class implements a move constructor, but lacks the move assignment operator. It is dangerous to use such a class.`

- [ ] 28) **mlpack/src/mlpack/methods/ann/layer/reparametrization_impl.hpp**	68	err	V562 
`It's odd to compare a bool type value with a value of double type.`

- [x] 29) **mlpack/src/mlpack/methods/ann/layer/reinforce_normal_impl.hpp**	23	warn	V730 
`Not all members of a class are initialized inside the constructor. Consider inspecting: reward, deterministic.`

- [x] 30) **mlpack/src/mlpack/methods/ann/layer/recurrent_attention_impl.hpp**	30	err	V730 
`Not all members of a class are initialized inside the constructor. Consider inspecting: outSize.`

- [x] 31) **mlpack/src/mlpack/methods/reinforcement_learning/q_networks/categorical_dqn.hpp**	56	warn	V730 
`Not all members of a class are initialized inside the constructor. Consider inspecting: atomSize, vMin, vMax.`

- [x] 32) **mlpack/src/mlpack/methods/amf/termination_policies/incomplete_incremental_termination.hpp**	36	warn	V730 
`Not all members of a class are initialized inside the constructor. Consider inspecting: incrementalIndex, iteration.`

- [x] 33) **mlpack/src/mlpack/methods/amf/termination_policies/complete_incremental_termination.hpp**	37	warn	V730 
`Not all members of a class are initialized inside the constructor. Consider inspecting: incrementalIndex, iteration.`

**Comment by rxng8** [comment]
Is this issue available? I can work on some of the checkbox.

**Comment by gauravghati** [comment]
@rxng8 Yes, Issue is available, go ahead.

**Comment by hello-fri-end** [comment]
Is there something left to do here?

**Comment by rcurtin** [comment]
Looks like basically everything is done now thanks to @rxng8; I checked all the boxes that were checked in #2807.  The only ones remaining now are (26) and (28).  (I think they should be pretty straightforward.)
