### ISSUE TITLE
title icon

### ISSUE THREAD

**Issue by aresword** [mlpack/mlpack#2799]
![image](https://user-images.githubusercontent.com/64397104/103653928-2dff4d80-4fa0-11eb-8b76-80945c5a8ca6.png)

![image](https://user-images.githubusercontent.com/64397104/103653969-3d7e9680-4fa0-11eb-883d-7dc8fe9edd24.png)

Ah,I think you should add an icon to make your website more beautiful.

**Comment by zoq** [comment]
@aresword ohh yeah that would be great, I guess we could use https://www.mlpack.org/static/img/mlpack-logo.svg.

Also the icon should probably go into the static folder here - https://github.com/mlpack/mlpack.org/tree/master/html, we have another repository for the website - https://github.com/mlpack/mlpack.org.

**Comment by ashish-hacker** [comment]
Is someone working on this? Or can I take this?

**Comment by zoq** [comment]
Just merged, https://github.com/mlpack/mlpack.org/pull/42 which solves the issue.
