### ISSUE TITLE
Master doesn't compile on Ubuntu 21.04

### ISSUE THREAD

**Issue by dmalecaut** [mlpack/mlpack#2800]
#### Issue description

Master doesn't compile on Ubuntu 21.04

#### Your environment

 * version of mlpack: master
 * operating system: Ubuntu 21.04
 * compiler: GCC 10.2.1
 * version of dependencies (Boost/Armadillo): develop/10.1.x branches
 * any other environment information you think is relevant: Under docker

#### Actual behavior

Compiler error generated:

FAILED: src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/adaboost_main.cpp.o
/usr/bin/c++ -DARMA_NO_DEBUG -DMLPACK_GIT_VERSION -DNDEBUG -I/portstrap-repo/mlpack/mlpack/src -I/root/portstrap/boost/include -I/root/portstrap/cereal/include -I/root/portstrap/ensmallen/include -I/root/portstrap/armadillo/include -Isrc/mlpack/.. -Wall -Wextra -f
template-depth=1000 -Wno-unused-function -O3 -Wno-unknown-pragmas -O3 -DNDEBUG -DBINDING_TYPE=BINDING_TYPE_CLI -std=gnu++11 -MD -MT src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/adaboost_main.cpp.o -MF src/mlpack/methods/adaboost/CMakeFiles/mlpack_ada
boost.dir/adaboost_main.cpp.o.d -o src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/adaboost_main.cpp.o -c /portstrap-repo/mlpack/mlpack/src/mlpack/methods/adaboost/adaboost_main.cpp
In file included from /root/portstrap/armadillo/include/armadillo:594,
                 from /portstrap-repo/mlpack/mlpack/src/mlpack/core/arma_extend/arma_extend.hpp:17,
                 from /portstrap-repo/mlpack/mlpack/src/mlpack/prereqs.hpp:83,
                 from /portstrap-repo/mlpack/mlpack/src/mlpack/methods/adaboost/adaboost_main.cpp:34:
/root/portstrap/armadillo/include/armadillo_bits/auxlib_meat.hpp: In static member function 'static bool arma::auxlib::solve_square_fast(arma::Mat<typename T1::elem_type>&, arma::Mat<typename T1::elem_type>&, const arma::Base<typename T1::elem_type, T1>&)':
/root/portstrap/armadillo/include/armadillo_bits/auxlib_meat.hpp:4354:34: warning: typedef 'eT' locally defined but not used [-Wunused-local-typedefs]
 4354 |   typedef typename T1::elem_type eT;
      |                                  ^~
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[48/140] Building CXX object src/mlpack/methods/lsh/CMakeFiles/mlpack_lsh.dir/lsh_main.cpp.o
FAILED: src/mlpack/methods/lsh/CMakeFiles/mlpack_lsh.dir/lsh_main.cpp.o
/usr/bin/c++ -DARMA_NO_DEBUG -DMLPACK_GIT_VERSION -DNDEBUG -I/portstrap-repo/mlpack/mlpack/src -I/root/portstrap/boost/include -I/root/portstrap/cereal/include -I/root/portstrap/ensmallen/include -I/root/portstrap/armadillo/include -Isrc/mlpack/.. -Wall -Wextra -f
template-depth=1000 -Wno-unused-function -O3 -Wno-unknown-pragmas -O3 -DNDEBUG -DBINDING_TYPE=BINDING_TYPE_CLI -std=gnu++11 -MD -MT src/mlpack/methods/lsh/CMakeFiles/mlpack_lsh.dir/lsh_main.cpp.o -MF src/mlpack/methods/lsh/CMakeFiles/mlpack_lsh.dir/lsh_main.cpp.o.
d -o src/mlpack/methods/lsh/CMakeFiles/mlpack_lsh.dir/lsh_main.cpp.o -c /portstrap-repo/mlpack/mlpack/src/mlpack/methods/lsh/lsh_main.cpp
In file included from /root/portstrap/armadillo/include/armadillo:594,
                 from /portstrap-repo/mlpack/mlpack/src/mlpack/core/arma_extend/arma_extend.hpp:17,
                 from /portstrap-repo/mlpack/mlpack/src/mlpack/prereqs.hpp:83,
                 from /portstrap-repo/mlpack/mlpack/src/mlpack/methods/lsh/lsh_main.cpp:13:
/root/portstrap/armadillo/include/armadillo_bits/auxlib_meat.hpp: In static member function 'static bool arma::auxlib::solve_square_fast(arma::Mat<typename T1::elem_type>&, arma::Mat<typename T1::elem_type>&, const arma::Base<typename T1::elem_type, T1>&)':
/root/portstrap/armadillo/include/armadillo_bits/auxlib_meat.hpp:4354:34: warning: typedef 'eT' locally defined but not used [-Wunused-local-typedefs]
 4354 |   typedef typename T1::elem_type eT;
      |                                  ^~
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.

**Comment by zoq** [comment]
Hello @dmalecaut most probably you run out of memory, in some situations mlpack needs about 6GB of free memory. There are some ways you can workaround the issue e.g. by disabling some of the bindings or executables, another option would be to increase Swap or build with less cores.

Can you track the free memory during build?

**Comment by dmalecaut** [comment]
Hi @zoq increasing the memory limit to 8gb and swap space to 2gb did the trick (as opposed to the default 2gb and 1gb respectively). I severely underestimated how much of a memory hog templates can be!

Many thanks!
