### ISSUE TITLE
About Great Firewall of China

### ISSUE THREAD

**Issue by aresword** [mlpack/mlpack#2802]
GFW blocked normal download. Actually,it's difficult to solve such a problem.
Many articles told me to do this in powershell:
$env:HTTP_PROXY="localhost:port" 
$env:HTTPS_PROXY="localhost:port" 
I found that didn't work, I don't know why, but I found a simple solution to this problem.
1.Visit the error website by proxy
2.Save page as...
3.Find the empty file in the "/vcpkg/downloads/temp", copy its name.
4.Put the correct file into "/vcpkg/downloads" and rename it to the empty file's name.
Fortunately,there isn't many files can't be downloaded.
The files on this website can't be downloaded because of GFW: raw.githubusercontent.com

**Comment by aresword** [comment]
Why?I didn't add 'bug report' label.

**Comment by aresword** [comment]
It is said that foreigners hate Chinese now. It embarrassed me. I just hope we don't have a political stance on academic issues.
:)

**Comment by rcurtin** [comment]
Ahh, that's unfortunate.  Does it work to download directly from mlpack.org?

**Comment by zoq** [comment]
Yeah, I guess if you can access mlpack.org e.g. if you can download - https://www.mlpack.org/files/mlpack-3.4.2.msi we could put the Vcpkg package on mlpack.org as well.
