### ISSUE TITLE
A typo in wiki page

### ISSUE THREAD

**Issue by ashish-hacker** [mlpack/mlpack#2805]
#### Problem location
[link](https://github.com/mlpack/mlpack/wiki/SummerOfCodeIdeas)

#### Description of problem
It's a typo. It should be "In recent" rather than "Inr ecent".
![Screenshot from 2021-01-13 16-16-56](https://user-images.githubusercontent.com/54330052/104442248-d02fbe80-55ba-11eb-901e-6a5127c7d75a.png)

**Comment by zoq** [comment]
You are absolutely right, fixed, thanks.

**Comment by zoq** [comment]
Btw. nice picture is that you in the helicopter?

**Comment by ashish-hacker** [comment]
I wish it's mine, But it's not haha. It's a random pic from internet, I liked the view of the pic and also it's kinda reminds me of GitHub (Feels weird?) haha. 
Btw glad you also liked it.

**Comment by ashish-hacker** [comment]
Btw why is this issue still open? 
I am looking at the codebase of mlpack and beginner friendly issues to start collaborating : )

**Comment by zoq** [comment]
> I wish it's mine, But it's not haha. It's a random pic from internet, I liked the view of the pic and also it's kinda reminds me of GitHub (Feels weird?) haha.
> Btw glad you also liked it.

Yeah, the picture is really nice.

> I am looking at the codebase of mlpack and beginner friendly issues to start collaborating : )

Nice, let us know if there is anything we can help with.

> Btw why is this issue still open?

No reason, closing it now.
