### ISSUE TITLE
Relevance Vector Machine

### ISSUE THREAD

**Issue by mercierc** [mlpack/mlpack#2809]
### What is the desired addition or change?
I have a code for the Relevance Vector Machine and bayesian linear regression associated with an ARD prior at the same time.

### What is the motivation for this feature?
I appreciate this model for its sparsity and its ability to handle non linear data. As a probability model, it returns pdf intead of a point estimate and optimizes automatically thanks to a bayesian inference.

### If applicable, describe how this feature would be implemented.
Because this model uses kernels, I inspired me from the kernel pca of mlpack. In order to be consistent, I used templates for
the kernel choice but I am know wondering if it is the best solution. All the methods of my class work fine, but I face some errors
and complications due to the template structure in my mlpack_rvm_regression.cpp. I would like to know if it is worth to continu in this way or if it exists a better solution.

### Additional information?
I would like to share you the .hpp and the _impl.hpp in order allow you to judge if it's worth it.

**Comment by jeffin143** [comment]
Hi @mercierc , You have aldeardy contributed Bayesian ridge regression ❤️  and we would love another model to be part of our arsenal, Please go ahead and open a pull request so that someone might help you and provide you with the suggestions.

**Comment by rcurtin** [comment]
100% agreed with @jeffin143! :+1:
