### ISSUE TITLE
Bayesian Linear Regression Usage on a Real World Dataset

### ISSUE THREAD

**Issue by naveenmiriyalu** [mlpack/mlpack#2816]
Hi Folks,
   I am currently working on comparing MLPACK(latest master commit) with various software stacks. I have found  mlpack benchmarks github(https://github.com/mlpack/benchmarks]) served as good starting point to get to know the benchmarks and their usage.
   I am having difficulties in trying to understand the output of the bayesian linear regression .
 I have taken the higgs dataset ( https://archive.ics.uci.edu/ml/datasets/HIGGS) and took the 2-22 columns as input and the 23 columns as the response and supplied to the bayesian linear regression algorithm using the command line below 
`./bin/mlpack_bayesian_linear_regression -i br_in.csv -r br_resp.csv `

The output of the command line -
```
[WARN ] Should pass one of '--predictions_file (-o)', '--output_model_file (-M)', or '--stds_file (-u)'; no results will be saved!
[INFO ] input detected
[INFO ] Loading 'br_in.csv' as CSV data.  Size is 22 x 11000000.
[INFO ] Loading 'br_resp.csv' as raw ASCII formatted data.  Size is 11000000 x 1
[INFO ] Execution parameters:
[INFO ]   center: 0
[INFO ]   help: 0
[INFO ]   info:
[INFO ]   input_file: 'br_in.csv' (0x0 matrix)
[INFO ]   input_model_file:
[INFO ]   output_model_file:
[INFO ]   predictions_file: ''
[INFO ]   responses_file: 'br_resp.csv' (1x0 matrix)
[INFO ]   scale: 0
[INFO ]   stds_file: ''
[INFO ]   test_file: ''
[INFO ]   verbose: 1
[INFO ]   version: 0
[INFO ] Program timers:
[INFO ]   bayesian_linear_regression: 1.611834s
[INFO ]   loading_data: 82.079186s (1 mins, 22.0 secs)
[INFO ]   total_time: 84.061142s (1 mins, 24.0 secs)
```
I dont think I am doing it in  a right manner as the 0x0 matrix indication suggests something is off. It would be really helpful if you guys could suggest a proper method or a proper dataset with appropriate parameters to be passed .

**Comment by rcurtin** [comment]
Hi @naveenmiriyalu, I'm not sure what the objective of your simulation is.  Actually there is a bug in the code that's never been addressed that causes it to sometimes output `0x0 matrix` incorrectly.  I'll open an issue for that, but I don't think that you need to be worried due to this output:

```
[INFO ] Loading 'br_in.csv' as CSV data.  Size is 22 x 11000000.
```

Anyway, like the warning says, no results are being saved anywhere:

```
[WARN ] Should pass one of '--predictions_file (-o)', '--output_model_file (-M)', or '--stds_file (-u)'; no results will be saved!
```

Based on the timer output, it looks like the model is taking 1.6s to train:

```
[INFO ]   bayesian_linear_regression: 1.611834s
```

but then nothing is being done with the computed model, so the program just exits.

Hopefully this answers your question---if not let me know and I can try again. :)

**Comment by naveenmiriyalu** [comment]
@rcurtin Thanks a  lot for your answer :) This helps as the message 0x0 was a bit misleading .  I am looking at mlpack for opportunities to analyze and improve the performance of  MKL and OpenBLAS software libraries for machine learning algorithms/workloads .

**Comment by rcurtin** [comment]
Ok, I opened #2817 to track the misleading output. :+1:

That's an exciting task you're working on, and I think we have a good set of algorithms that work MKL or OpenBLAS pretty hard. :)

**Comment by naveenmiriyalu** [comment]
Hi @rcurtin . Its interesting to see how these algorithms work . I have stumbled upon the [(http://mlpack.org/datasets/)] from the mlpack benchmarks github. 
1. May I know the source/origin  of these datasets from where these are taken from ? 
2. Are these datasets extended from the original dataset to include more features ?
3.  I have observed that there is good use of OpenBLAS and the matrix operations generated are GEMM kernels etc and the generated matrix sizes for multiplication depend on the dataset features and rows .

**Comment by rcurtin** [comment]
Most---but not all---are from here: https://archive.ics.uci.edu/ml/datasets.php

In general the only preprocessing that may have been done is to labels (for labeled datasets), where we may have changed the labels from whatever they were originally to lie in the range `[0, numClasses - 1]`.  Everything else *should* be original or close to it.
