### ISSUE TITLE
CLI bindings give incorrect matrix size output

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#2817]
#### Issue description

The CLI bindings sometimes show `0x0` as the matrix size incorrectly.  See the reproduction below.

Note that this isn't the case with every binding!  Most likely, this is because sometimes `std::move()` on a matrix held in `IO`, and then at the end of the program, when the size of the matrix is computed for printing, the matrix is empty, so a size of `0x0` is given.

I am not sure what the best way to solve this is and I think there could be multiple ways to do it.  The problematic code, as described above, is in `src/mlpack/bindings/cli/end_program.hpp`, in the function `EndProgram()`.  `EndProgram()` will in turn call `GetPrintableParam()` (in `get_printable_param.hpp`) for the appropriate type, and for matrix types, the function `GetMatrixSize()` is called.

Refactoring all of the bindings to *not* use `std::move()` is a bad idea, and so maybe a better solution might be to modify the CLI binding code---or even the IO code overall---so that the size of a matrix is correctly cached.

#### Your environment

 * version of mlpack: git master
 * operating system: Debian sid
 * compiler: g++ 10.2.1
 * version of dependencies (Boost/Armadillo): Boost 1.74.0, Armadillo 10.1.2
 * any other environment information you think is relevant:

#### Steps to reproduce

```
$ mlpack_knn -r ~/datasets/covertype.csv -v -M model.bin
```

#### Expected behavior

```
[INFO ] Using reference data from Loading '/archive/datasets/covertype.csv' as CSV data.  Size is 54 x 581012.
[INFO ] '/archive/datasets/covertype.csv' (54x581012 matrix).
[INFO ] Building reference tree...
[INFO ] Tree built.
[INFO ] 
[INFO ] Execution parameters:
[INFO ]   algorithm: dual_tree
[INFO ]   distances_file: ''
[INFO ]   epsilon: 0
[INFO ]   help: 0
[INFO ]   info: 
[INFO ]   input_model_file: 
[INFO ]   k: 0
[INFO ]   leaf_size: 20
[INFO ]   neighbors_file: ''
[INFO ]   output_model_file: model.bin
[INFO ]   query_file: ''
[INFO ]   random_basis: 0
[INFO ]   reference_file: '/archive/datasets/covertype.csv' (54x581012 matrix)
[INFO ]   rho: 0.7
[INFO ]   seed: 0
[INFO ]   tau: 0
[INFO ]   tree_type: kd
[INFO ]   true_distances_file: ''
[INFO ]   true_neighbors_file: ''
[INFO ]   verbose: 1
[INFO ]   version: 0
[INFO ] Program timers:
[INFO ]   loading_data: 1.621414s
[INFO ]   total_time: 3.798423s
[INFO ]   tree_building: 2.176808s
```

#### Actual behavior

```
[INFO ] Using reference data from Loading '/archive/datasets/covertype.csv' as CSV data.  Size is 54 x 581012.
[INFO ] '/archive/datasets/covertype.csv' (54x581012 matrix).
[INFO ] Building reference tree...
[INFO ] Tree built.
[INFO ] 
[INFO ] Execution parameters:
[INFO ]   algorithm: dual_tree
[INFO ]   distances_file: ''
[INFO ]   epsilon: 0
[INFO ]   help: 0
[INFO ]   info: 
[INFO ]   input_model_file: 
[INFO ]   k: 0
[INFO ]   leaf_size: 20
[INFO ]   neighbors_file: ''
[INFO ]   output_model_file: model.bin
[INFO ]   query_file: ''
[INFO ]   random_basis: 0
[INFO ]   reference_file: '/archive/datasets/covertype.csv' (0x0 matrix)
[INFO ]   rho: 0.7
[INFO ]   seed: 0
[INFO ]   tau: 0
[INFO ]   tree_type: kd
[INFO ]   true_distances_file: ''
[INFO ]   true_neighbors_file: ''
[INFO ]   verbose: 1
[INFO ]   version: 0
[INFO ] Program timers:
[INFO ]   loading_data: 1.621414s
[INFO ]   total_time: 3.798423s
[INFO ]   tree_building: 2.176808s
```

(You can see the difference here on the `reference_file` line.)

#### Other notes

If you're interested in working on this issue, I'd first suggest spending some time familiarizing yourself with the structure of the CLI bindings (and possibly the other bindings) in order to propose a good solution.  Whatever strategy is chosen is likely to have various ramifications, so it's probably worth discussing the strategy here first before implementation.  So, for that reason, there's no need to ask whether or not you can work on this issue---propose a solution, and then we can discuss it and converge on a strategy for implementation.

Also, this problem may exist for bindings to other languages too in other forms---but I have not rigorously checked.

**Comment by shubhamabhang77** [comment]
Is there anyone working on this? I would like to work on this.It would help me get started.

**Comment by shubhamabhang77** [comment]
@rcurtin Is there anyone working on this? I would like to work on this.It would help me get started.

**Comment by rcurtin** [comment]
Sure, go for it @shubhamabhang77. :+1:

**Comment by shubhamabhang77** [comment]
Hey @rcurtin, i had a doubt. what is significance of this line(line no. 262) from ```src/mlpack/methods/neighbor_search/knn_main```
```
arma::mat referenceSet = std::move(IO::GetParam<arma::mat>("reference"));
knn->BuildModel(std::move(referenceSet), searchMode, epsilon);
```

Because if I remove the first ```std::move``` , then, I am getting the desired output as mentioned above. 

And one more thing, if I try to get the size of matrix immediately after the second line, it show ```0x0 matrix```.

**Comment by NippunSharma** [comment]
Hey @shubhamabhang77 `std::move` is used whenever copying is expensive. In the case you mentioned, the `reference` matrix can be large and hence it might not be a good idea to copy it, therefore we "move" it . But moving can make the source empty (which is exactly the reason that we are getting `0x0` size of the matrix). But as mentioned in the description, it may not be a good idea to remove `std::move` , hence a better solution might be to just store the size of the matrix before `std::move` is called.

**Comment by shubhamabhang77** [comment]
Oh got it.
I am not sure where can we cache the size, I mean , in what variable? Can we use this structure```util::param``` ?

**Comment by shubhamabhang77** [comment]
We can have three variables called ```is_size_calculated``` initially set to false and ```matrixcols``` ```matrixrows```. When first time ```getMatrixSize()``` is getting called we will turn ```is_size_calculated``` to true and save the matrix size to ```matrixcols``` and ```matrixrows```. I was thinking about this. Is it feasible?

**Comment by NippunSharma** [comment]
`GetMatrixSize` really only calls the `n_rows` and `n_cols` attributes of an `arma::mat` (that is given as a parameter) and returns a string that contains the rows and cols. So, you can find the rows and cols of the matrix without the use of `GetMatrixSize` also. Creating `matrixcols` and `matrixrows` as attributes to the `ParamData` class might be a good idea. Some complications can arise where you will have parameters that are not matrices and might not have the `n_rows` and `n_cols` attributes. But I guess you can check for it manually. I think it is best to see what @rcurtin thinks about this before you start working on this any further.

**Comment by rcurtin** [comment]
I'm not opposed to adding some matrix-only members to `ParamData`.  Another way to achieve the same goal would be to change the type that's actually held by the `boost::any` in `ParamData`.  Right now, for type `arma::mat`, it doesn't hold an `arma::mat`---instead, it holds `std::tuple<arma::mat, std::string>`.  The first element of that tuple is the filename to load the matrix from.  You can see that in line 54 of `src/mlpack/bindings/cli/get_param.hpp`:

```c++
  typedef std::tuple<T, typename ParameterType<T>::type> TupleType;
  TupleType& tuple = *boost::any_cast<TupleType>(&d.value);
  const std::string& value = std::get<1>(tuple);
```

So, you could change `TupleType` to be `std::tuple<arma::mat, std::string, size_t, size_t>`, and during loading, set the last two members to be the loaded rows and columns of the matrix.  Then, in `get_printable_param_impl.hpp`, you could use those two members to print the size.  (You might have to also adapt some other functions in `cli/` that expect an Armadillo type to only have two members.)

I hope this makes sense---let me know if I can clarify anything. :+1:

**Comment by shubhamabhang77** [comment]
Yeah that makes more sense. I will look into this.

**Comment by rcurtin** [comment]
This is actually still an issue, so I'll leave it open.

**Comment by NippunSharma** [comment]
Hey, @rcurtin. I have created #2933 that attempts to solve this issue. Please take a look at it whenever you get time.

**Comment by NippunSharma** [comment]
@rcurtin can we close this? now that #2933 is merged.

**Comment by rcurtin** [comment]
Oh, good point!  I forgot to close this.  Nice work in #2933!  I'll go ahead and close this. :+1:
