### ISSUE TITLE
Runtime crashes in Google Colab when wrong input shape is given.

### ISSUE THREAD

**Issue by NippunSharma** [mlpack/mlpack#2818]
#### Issue description

While using `adaboost` (through python bindings) inside google colab environment the runtime restarts automatically instead of throwing an error when wrong input shape is given.

#### Your environment

 * version of mlpack: 3.4.2
 * operating system: Ubuntu 18.04 (or whatever google colab provides you with)

#### Steps to reproduce

Refer to the following [notebook](https://colab.research.google.com/drive/15T-A8AS117Nob0V7IGoDU_WPNx9g4VH6?usp=sharing)

#### Expected behavior

An error should be thrown.

#### Actual behavior

Runtime crashes and restarts thus deleting all local variables.

**Comment by rcurtin** [comment]
That's not good---is there any backtrace at all or anything?

**Comment by NippunSharma** [comment]
No, there was no backtrace or any other output. Do you have any idea as to why this might be happening ?

**Comment by rcurtin** [comment]
Hmm, can you try running it in a local Python session?  I wonder if the C++ code is throwing an exception, but this is not being propagated back to Python correctly.

**Comment by NippunSharma** [comment]
Same thing is happening locally, the kernel dies after I run the cell.

**Comment by rcurtin** [comment]
Sorry, I meant to try it in a local Python session, not in a local notebook environment. :+1:

**Comment by NippunSharma** [comment]
It gives the following error message:
`Segmentation fault (core dumped)` 
after I run the file.

**Comment by NippunSharma** [comment]
Actually this is the first time I facing this error so had to read a little about the error message and it is thrown whenever we try to do read and write on a read only location of memory or a freed block of memory.

Following is the code that gives the error. Note that the program runs fine when I comment `model_2` and just use `model_1`.

    from mlpack import adaboost
    from sklearn.datasets import load_iris
    data = load_iris()
    
    from sklearn.model_selection import train_test_split
    
    # Creating training and testing matrices
    X_train, X_val, y_train, y_val = train_test_split(data.data, data.target, stratify=data.target, test_size=25, random_state=42, shuffle=True)
    '''
    # Passing the correct shapes here.
    model_1 = adaboost(input_model=None, iterations=1, labels=y_train, 
                            training=X_train, tolerance=1e-10, weak_learner="decision_stump",
                            verbose=False, test=X_val)
    '''
    
    # Note that here I am passing the wrong shape for "labels" parameter.
    # It should be "y_train" but I am passing "y_train[:100]" instead.

    # This should through an error instead.
    model_2 = adaboost(input_model=None, iterations=1, labels=y_train[:100],
                            training=X_train, tolerance=1e-10, weak_learner="decision_stump",
                            verbose=False, test=X_val)

**Comment by rcurtin** [comment]
Oh wow, it segfaults... I suspect this could also be reproduced (in an easier to debug format) by running the `mlpack_adaboost` binding with the data you used for `model_2`.  I guess you could just save `y_train[:100]` and `X_train` to CSV.

**Comment by NippunSharma** [comment]
Following is the message with `DEBUG=ON`:

    ./mlpack_adaboost --training_file data.csv --labels_file labels.csv --weak_learner "decision_stump"
    [DEBUG] Compiled with debugging symbols.
    [WARN ] Should pass one of '--output_model_file (-M)', '--output_file (-o)', or '--predictions_file (-P)'; no results will be saved!
    
    error: Row::subvec(): indices out of bounds or incorrectly used
    terminate called after throwing an instance of 'std::logic_error'
      what():  Row::subvec(): indices out of bounds or incorrectly used
    Aborted (core dumped)

**Comment by NippunSharma** [comment]
Update:
I tested this for `decision_tree`, `random_forest` and `linear_svm` also.
There is no `FATAL` output for `decision_tree` or `random_forest` but `linear_svm` correctly throws a `FATAL` output.
Following are the outputs:
#### Decision Tree
    ./mlpack_decision_tree --training_file data.csv --labels_file labels.csv
    [DEBUG] Compiled with debugging symbols.
    [WARN ] Should pass one of '--output_model_file (-M)', '--probabilities_file (-P)', or '--predictions_file (-p)'; no output will be saved!
    
    error: Row::subvec(): indices out of bounds or incorrectly used
    terminate called after throwing an instance of 'std::logic_error'
      what():  Row::subvec(): indices out of bounds or incorrectly used
    Aborted (core dumped)

#### Random Forest
    ./mlpack_random_forest --training_file data.csv --labels_file labels.csv
    [DEBUG] Compiled with debugging symbols.
    [WARN ] Should pass one of '--test_file (-T)', '--output_model_file (-M)', or '--print_training_accuracy (-a)'; the trained forest model will not be used or saved!
    free(): invalid pointerfree(): invalid pointer
    
    free(): invalid pointer
    free(): invalid pointer
    free(): invalid pointerfree(): invalid pointer
    free(): invalid pointer
    
    Aborted (core dumped)

#### Linear SVM

    ./mlpack_linear_svm --training_file data.csv --labels_file labels.csv
    [DEBUG] Compiled with debugging symbols.
    [WARN ] Should pass one of '--output_model_file (-M)', '--predictions_file (-P)', or '--probabilities_file (-p)'; no output will be saved!
    [FATAL] The labels must have the same number of points as the training dataset.
    
    [FATAL] [bt]: (1) :0 stat:
    [FATAL] [bt]: (2) :0 stat:
    [FATAL] [bt]: (3) :0 stat:
    [FATAL] [bt]: (4) :0 stat:
    [FATAL] [bt]: (5) :0 stat:
    [FATAL] [bt]: (6) :0 stat:
    terminate called after throwing an instance of 'std::runtime_error'
      what():  fatal error; see Log::Fatal output
    Aborted (core dumped)

**Comment by rcurtin** [comment]
Nice digging!  What happens if you call linear SVM from the Python bindings with the incorrect size?  Does that return correct output and not crash?

**Comment by NippunSharma** [comment]
`Linear SVM` returns the correct output for python bindings also.

#### Linear SVM Python Bindings
    $ python3 linear_svm.py 
    [FATAL] The labels must have the same number of points as the training dataset.
    
    Traceback (most recent call last):
      File "linear_svm.py", line 15, in <module>
        model = linear_svm(input_model=None, labels=y_train[:100],
      File "mlpack/linear_svm.pyx", line 334, in mlpack.linear_svm.linear_svm
    RuntimeError: fatal error; see Log::Fatal output

**Comment by rcurtin** [comment]
Ah, so then the issue here is that we aren't properly giving `Log::Fatal` output when matrices aren't of the correct size.  I guess that we need to add stricter error checking to each of our bindings to catch situations like this before passing to the algorithm in question.

**Comment by rcurtin** [comment]
I thought about it a little bit more.  Perhaps what we really need here is an audit to make sure that every binding correctly checks the shapes of its inputs.  For some reason I am remembering that there was some work done recently that, I think(?), added a general function to check that, e.g., two matrices had the same columns and issued an error if not.  But maybe I am misremembering.  Anyway, if one doesn't exist, we could implement some checking functions in `src/mlpack/core/util/param_checks.hpp`, and then make sure that each binding uses them.  What do you think?  To me it seems like it would be a good idea to open an issue for this, and if you want to do that, please feel free!  If not, I'll open it, your call. :)

**Comment by NippunSharma** [comment]
Opening an issue for this is a good idea. I will do the same. After digging deeper I found that for linear SVM we are actually explicitly checking for matching columns [here](https://github.com/mlpack/mlpack/blob/bf837f950b728bf08b80ccc696c6bc0d296e54af/src/mlpack/methods/linear_svm/linear_svm_main.cpp#L281) but I was not able to find any such checks for decision tree in the main.cpp file. One solution can also be to individually add these checks to main.cpp file for all methods but that might be cumbersome and we will have to take care of this whenever a new method is added in the codebase. So as you stated, adding these checks to all the bindings individually might be the better option here.

**Comment by NippunSharma** [comment]
@rcurtin I have created the issue. I have written the description as detailed and thorough as I could with an approach to implement it in some of the bindings. Can you please take a look at it ? I just want to be sure that the approach that I have written is fine or not ?

**Comment by rcurtin** [comment]
Thanks for opening that @NippunSharma!  Sorry it took me a week to get back to this.  Actually we don't need to modify the CLI bindings or Python bindings at all.  Instead we can simply implement functions like `RequireSameSize({ "training", "test" })` and `RequireSameDimension({ "training", "test" })`.  These functions would just throw an error if the `training` and `test` matrices were specified and didn't have the same size or dimension.  We could call them right at the top of each binding, inside of `mlpackMain()`.

Do you think you could modify the description a bit to reflect the idea above?

Also, it would probably be a good idea to make a checklist of all the bindings, since they each need to be audited---we need to check them each individually and see if we can add any size checks to them (if they aren't already there). :+1:

**Comment by onikolskyy** [comment]
Hey guys,
I would be happy to make my first commit with a fix for adaboost bindings.
However, I get a `permission denied` for my `github` acc when I try to push a new branch with the commit.
Do I need some extra rights or does the contribution pipeline work differently?

**Comment by rcurtin** [comment]
@onikolskyy yeah, you'll need to push to your own fork of mlpack (instead of trying to push to this repository) and then open a PR like that. :+1:

**Comment by deeplearningera** [comment]
Hello everyone, I would like to contribute to this issue. Upon reading above conversation, I have understood that there is problem with the input shape. Whenever we give incorrect shape, runtime restarts automatically and we need to initialize variables again. The problem is that we want that at runtime an error message should be displayed. You have also discussed about various algorithms such as decision tree, svm, etc. Can you please summarize in which algorithms error is displayed at run time and in which it is not? Also can you assign me any task?

**Comment by NippunSharma** [comment]
Hey @deeplearningera, we still have to find in which methods this problem occurs. You can look at #2820 for more details. If you wish you can work and see in which methods this problem occurs and comment on the issue thread itself. I will update the checklist. If you want to work on implementing the checks that solve this issue you can ask on #2820 as there might be some people who are already working on this, it is totally up to you.

**Comment by NippunSharma** [comment]
We should keep this open.
