### ISSUE TITLE
MLPACK examples

### ISSUE THREAD

**Issue by jbensabat** [mlpack/mlpack#2819]
Hello 
I have managed to build mlpack for MSVC 2019 under windows 10
I would like now to use mlpack in a series of examples.
I seee in the distribution that there is a very long test sequence, which for now is less useful to me.
Are there individual examples that I could start from and trace the results ?
best
jac

**Comment by zoq** [comment]
You can find some examples in the [examples repository](https://github.com/mlpack/examples), some of them are in a notebook, the [tutorials section](https://www.mlpack.org/doc/stable/cli_documentation.html#tutorials) has some examples as well and the [tests](https://github.com/mlpack/mlpack/tree/master/src/mlpack/tests) are often mini examples as well.

**Comment by jbensabat** [comment]
Hi 
thanks for your answer 
I have ran the tests one at the time (120 tests) in debug mode and this is what I have found out:
115 passed 
1 failed dcgan_test.cpp -> (DCGANMNISTTest;dcgan.Train(trainData, optimizer);
3 were partially successful:
ann_layer_test.cpp failure in (GradientGRULayerTest;REQUIRE(CheckGradient(function) <= 1e-4);)
callback_test.cpp failure in (RBMCallbackTest;model.train)
recurrent_network_test.cpp failure in GRUDistractedSequenceRecallTest;GRUBatchSizeTest

1 did not compile 
function_test.cpp did not compile as the optimizers directory is missing 

is there something I am missing ?
thanks
jac

**Comment by zoq** [comment]
Some tests are probabilistic so it's possible that they fail, however we try to keep the fail rate low, so I'll take a look at the tests and maybe increase the tolerance.

> function_test.cpp did not compile as the optimizers directory is missing

Did you compile the tests manually? Because if you use the make build pipeline (cmake, make) it should build all the  executables for you.

**Comment by jbensabat** [comment]
Hi
thanks for your reply 
ann_layer_test.cpp failure in (GradientGRULayerTest;REQUIRE(CheckGradient(function) <= 1e-4);) 
probably due to a lack of convergence to the set threshold 

callback_test.cpp failure in (RBMCallbackTest;model.train)
recurrent_network_test.cpp failure in GRUDistractedSequenceRecallTest;GRUBatchSizeTest
there were exceptions related to uninitialized variables 

unction_test.cpp did not compile as the optimizers directory is missing
I installed mlpack using CMAKE. it did not install the optimizers, or the ensmallen package. I will check if there is a switch for that in CMAKE

thanks 
jac

**Comment by jbensabat** [comment]
Checked 
it does not install the optimizers directory 
I copied the ensmallen include files into an optimizers directory under mlpack/core but 
the namespace mlpack::optimization; is missing 
best
jac

**Comment by zoq** [comment]
If ensmallen isn't found it will be automatically downloaded there should be a directory called `deps` in the build folder. Can you check if it's there?

**Comment by jbensabat** [comment]
hi 
yes there is  deps directory below the CMAKE Build directory and inside there is a ensmallen archive and ensmallen-2.15.1 directory
best
jac

**Comment by zoq** [comment]
Okay, so cmake was able to download the package, now I'm wondering why it's not picked up during testing? Do you have compiler error message besides `the namespace mlpack::optimization; is missing` is missing?

**Comment by rcurtin** [comment]
`mlpack::optimization` hasn't existed for years... are you sure that you are using a recent release of mlpack?

**Comment by jbensabat** [comment]
Hi
I am using the recent release of mlpack - no doubt 
I think that the confusion stems from the fact that the test "function_test.cpp" in the tests directory is not relevant anymore 
best 
jac

**Comment by zoq** [comment]
> function_test.cpp

You are right, thanks for pointing that out, removed in https://github.com/mlpack/mlpack/pull/2823.

**Comment by jbensabat** [comment]
thanks a lot for your support. Now that I know that mlpack works, I shall start learning how to utilize it 
best regards
jac

**Comment by apisani1** [comment]
Hi. function_test.cpp is still included in the test files on the version that can be downloaded from mlpack.org.

That one has the same version number that the one in github but a different release date.

I built mlpack using the one in mlpack.org. Shall I rebuild it using the one in github?

Best Regards,

Antonio

**Comment by apisani1** [comment]
The versions in mlpack.org and GitHub are definitely very different despite the same version number. It must be a posting error.

I rebuild it using the GitHub version and tested using the tests on the same version and everything is working now (I still get some warnings while compiling it).

I suggest that you check the download link at mlpack.org.

Best Regards,\

Antonio

**Comment by rcurtin** [comment]
Can you provide more information about the version numbers?  mlpack 3.4.2 is old and will be replaced soon with mlpack 4; there has been a lot of refactoring.  If you are using the git master branch, this is going to be mlpack 4 and it is very different than mlpack 3.4.2.

**Comment by apisani1** [comment]
Well, maybe I misspoke, The examples at GitHub do compile, but I do get a lot of warnings and errors when I run them.

This is the summary I got:

===============================================================================
test cases:     1300 |     1293 passed | 7 failed
assertions: 32756225 | 32756218 passed | 7 failed

This is an example of the error I got:

/..../sparse_coding_test.cpp:112: FAILED:
due to unexpected exception with message:
  Mat::col(): index out of bounds

**Comment by apisani1** [comment]
> Can you provide more information about the version numbers? mlpack 3.4.2 is old and will be replaced soon with mlpack 4; there has been a lot of refactoring. If you are using the git master branch, this is going to be mlpack 4 and it is very different than mlpack 3.4.2.

Well, now I am really confused. When I go to GitHub using this address:

https://github.com/mlpack/mlpack

I see that the latest version is 3.4.2.
 
But, as I said, this code is very different as the one in mlpack.org, as an example, the one in GitHub is an include only library and the one in mkpack.org is not.

The tests in the version in mlpapack.org does not compile and the tess in the version in GitHub do compile but give runtime errors and warnings.

This is an example of the runtim eerrors I got when running the version in GitGub:

/..../sparse_coding_test.cpp:112: FAILED:
due to unexpected exception with message:
Mat::col(): index out of bounds

Thaks for your help sorting this out.

Best Regards,

Antonio

**Comment by apisani1** [comment]
> Can you provide more information about the version numbers? mlpack 3.4.2 is old and will be replaced soon with mlpack 4; there has been a lot of refactoring. If you are using the git master branch, this is going to be mlpack 4 and it is very different than mlpack 3.4.2.

 I don't see any newer release:

https://github.com/mlpack/mlpack/releases

I apology in advance if it is a newbie mistake.

Thanks,

Antonio

**Comment by apisani1** [comment]
After decompressing a few data files, I got an "All tests passed" message but I still got a lot of error messages

mlpack version: mlpack 3.4.3
armadillo version: 11.2.4 (Classic Roast)
[WARN ] The batch size for optimizing BiasSVD is 1.
[WARN ] The batch size for optimizing RegularizedSVD is 1.
[WARN ] The batch size for optimizing BiasSVD is 1.
[WARN ] The batch size for optimizing SVDPlusPlus is 1.
[WARN ] The batch size for optimizing RegularizedSVD is 1.
[WARN ] The batch size for optimizing BiasSVD is 1.
[WARN ] The batch size for optimizing SVDPlusPlus is 1.
[WARN ] The batch size for optimizing RegularizedSVD is 1.
[WARN ] The batch size for optimizing BiasSVD is 1.
[WARN ] The batch size for optimizing RegularizedSVD is 1.
[WARN ] The batch size for optimizing BiasSVD is 1.
[WARN ] The batch size for optimizing SVDPlusPlus is 1.
[WARN ] The batch size for optimizing RegularizedSVD is 1.
[WARN ] The batch size for optimizing BiasSVD is 1.
[WARN ] The batch size for optimizing SVDPlusPlus is 1.
[WARN ] The batch size for optimizing RegularizedSVD is 1.
[WARN ] The batch size for optimizing RegularizedSVD is 1.
[WARN ] The batch size for optimizing BiasSVD is 1.
[WARN ] The batch size for optimizing BiasSVD is 1.
[WARN ] The batch size for optimizing SVDPlusPlus is 1.
[WARN ] The batch size for optimizing SVDPlusPlus is 1.
[WARN ] The batch size for optimizing RegularizedSVD is 1.
[WARN ] The batch size for optimizing RegularizedSVD is 1.
[WARN ] The batch size for optimizing RegularizedSVD is 1.

warning: solve(): system is singular (rcond: 3.62383e-18); attempting approx solution
[WARN ] KFoldCV::TrainAndEvaluate(): fold 0 returned a score of nan; ignoring when computing the average score.
[WARN ] KFoldCV::TrainAndEvaluate(): fold 1 returned a score of nan; ignoring when computing the average score.
[WARN ] KFoldCV::TrainAndEvaluate(): all folds returned invalid scores!  Returning 0.0 as overall score.
--info: At Most 1 required but received 2
The following argument was not expected: --unknown
[WARN ] KDE::Evaluate(): querySet is empty, no predictions will be returned
[WARN ] KDE::Evaluate(): querySet is empty, no predictions will be returned
[WARN ] RANN-RS: RANN guarantee fails on 0 queries.
[WARN ] RANN-TSS: RANN guarantee fails on 0 queries.
[WARN ] RANN-TSD: RANN guarantee fails on 0 queries.
[WARN ] RANN-TSS (cover tree): RANN guarantee fails on 0 queries.
[WARN ] RANN-TSD (cover tree): RANN guarantee fails on 0 queries.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.

warning: solve(): system is singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.52834e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system is singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.52834e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system is singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.52834e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system is singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.52834e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system is singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.52834e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system is singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.52834e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system is singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.52834e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system is singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.52834e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system is singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.52834e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system is singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.52834e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system is singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.52834e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.05025e-17); attempting approx solution
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.

warning: solve(): system is singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.52834e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system is singular (rcond: 1.05025e-17); attempting approx solution
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Cannot open file 'noextension'; load failed.
[WARN ] Could not detect type of file 'noextension' for writing.  Save failed.
[WARN ] Cannot open file 'nonexistentfile_______________.csv'; load failed.
[WARN ] Unable to detect type of 'test_file.csv'; load  failed. Incorrect extension?
[WARN ] 'test_file.csv' is not a standard csv file.
[FATAL] Matrix in file 'test_file.csv' is not a vector, but instead has size 2x2!

[FATAL] Matrix in file 'test_file.csv' is not a vector, but instead has size 2x2!

[WARN ] 'test_file.csv' is not a standard csv file.
[WARN ] Loading 'test_file.bin' as raw binary formatted data; but this may not be the actual filetype!
[FATAL] Cannot open file 'nonexistentfile.arff'. 

[FATAL] Parse error at line 14 token 0: category "c" not in the set of known categories for this dimension ("A", "B", "C", "D").

[WARN ] LoadCSV::TransposeParse(): wrong number of dimensions (3) on line 1; should be 4 dimensions.
[WARN ] LoadCSV::NonTransposeParse(): wrong number of dimensions (3) on line 1; should be 4 dimensions.
[WARN ] The batch size for optimizing SVDPlusPlus is 1.
===============================================================================
All tests passed (32825581 assertions in 1300 test cases)

**Comment by apisani1** [comment]
> Can you provide more information about the version numbers? mlpack 3.4.2 is old and will be replaced soon with mlpack 4; there has been a lot of refactoring. If you are using the git master branch, this is going to be mlpack 4 and it is very different than mlpack 3.4.2.

I am using the master at github. I could not find the version number.

Thanks,

Antonio

**Comment by rcurtin** [comment]
Ok, great, thanks for all the info.  Here's the state of things---

 * The version you are using, which you got from Github, is under development and will soon be released as mlpack 4.  So, this explains why it's different than what's on the website (the website has the stable version, which is 3.4.2).
 
 * There are lots of changes between mlpack 3 and 4, and these can make the examples not work correctly.  There are still a few open PRs such as #3269, #3270, and others that need to be merged before we really put effort into making sure the examples work right.  So, some will work with mlpack 3, some with mlpack 4 ... it's not an ideal situation and I apologize for that.
 
 * All the output in the test is not a problem (you can see at the bottom it writes `All tests passed`).  Some recent refactorings made the "muted" test output appear again, and so when #3275 is merged, all of the scary-looking messages will go away.

So, overall, I know it is a bit of a confusing situation, but I promise, it will get better once we release mlpack 4 and bring everything else (website, examples repo, models repo, and so on) up to date.  Sorry for the inconvenience!
