### ISSUE TITLE
Clustering with Pre-computed distances in DBSCAN

### ISSUE THREAD

**Issue by Nirhar** [mlpack/mlpack#2821]
Does DBSCAN have the facility where we can provide pre-computed distances for clustering (like in MATLAB and sklearn in python)? Does it cluster only based on euclidean distances or is there an option of providing other metrics like cosine similarity etc?

**Comment by rcurtin** [comment]
(I'm assuming you're using C++.  If you're using the bindings to other languages, the options are more limited.)

In the `DBSCAN<>` class, you can control these things through the `RangeSearchType` class.  So, e.g., if you want to use the Manhattan distance, you can use `range::RangeSearch<metric::ManhattanDistance>` as the first template parameter of `DBSCAN<>`.

If you already have precomputed distances that you want to use with DBSCAN, the easiest way to do that would be to write a class that stores those precomputed distances and then implements this method (just like `RangeSearch`):

```
void Search(const arma::mat& queryPoints,
            const math::Range& range,
            std::vector<std::vector<size_t>>& neighbors,
            std::vector<std::vector<double>>& distances)
```

and the expectation is that method will, for each query point in `queryPoints`, return a `std::vector<size_t>` of indices and a `std::vector<double>` of distances that contain all points within the range `range`.

Personally, I don't see a lack of precomputed distance support as a big deal.  Computationally speaking, representing the precomputed distance matrix takes size `O(N^2)` where `N` is the number of points in the dataset.  So if `N` is even a little bit large---think like 20k or more---just the memory requirement to store that precomputed distance matrix is too high and it typically can't be represented.  But if `N` is small, then the range search computation should be pretty fast anyway using mlpack's default tree-based implementation!

Anyway, hopefully this clarifies things.  Let me know if I can add any more to the answer above. :+1:

**Comment by Nirhar** [comment]
Thanks for your explanation! I've got some clarity on how this works.
