### ISSUE TITLE
IO class is not thread safe

### ISSUE THREAD

**Issue by NippunSharma** [mlpack/mlpack#2832]
#### Issue description

This bug was first encountered by @rcurtin. 
The `IO` class defined in `src/mlpack/core/util/io.hpp` is a singleton class which is not thread safe.  This means that multiple threads can change the contents of `IO` class at the same time (and also make more than one objects, which is not desired as `IO` is a singleton). Below I have described a simulation to show exactly this.

#### Your environment

 * version of mlpack: check the branch [here](https://github.com/NippunSharma/mlpack/tree/threadsafe_temp)
 * operating system: Ubuntu 20.04
 * compiler: gcc

#### Steps to reproduce

If you also wish to run the simulation you can follow the steps below:
 1) You have to make some temporary tweaks to the `IO` class. You can see [here](https://github.com/mlpack/mlpack/compare/master...NippunSharma:threadsafe_temp) all the changes that I made.
 2) Now run the `make` command and `make install` (installing is not necessary but I did it).
 3) Then, I wrote a basic program that uses the `IO` class directly, you can find it [here](https://pastebin.com/zJTqAAGD).
 4) Then I ran the program once with No Multithreading and once with Multithreading enabled (2 threads).

#### Expected behavior

Both the outputs must be `FOO` or `BAR` (anyone of these two based on which of `ThreadFoo` or `ThreadBar` is called first, in my case it was mostly `FOO`).

#### Actual behavior

Both the outputs are different (one is `FOO` and other is `BAR`).

#### Basic Description about the simulation

In this simulation we are calling the `GetSingleton` method in the `IO` class that returns the single instance of the class. Each time that we are calling `GetSingleton` we can provide a `std::string value` which is used to initialize the instance if it does not exist already (this value is stored inside `value_`). By using this kind of setup we can see whenever multiple instances are created by accessing `value_`. In the main program I have defined 2 functions namely `ThreadFoo` and `ThreadBar` each of which calls `GetSingleton` with different values (`FOO` and `BAR` respectively) and prints `value_`. So, if only a single instance is created then only one of `FOO` or `BAR` should get printed else if more than one instance is created then both `FOO` and `BAR` should be printed.

I know that this is a complex simulation and not something we see in practical scenario. So, if you have faced anything related to this issue while using the bindings please feel free to comment below. In any case this is an issue that needs to be fixed.

**Comment by NippunSharma** [comment]
Hey @rcurtin I was looking at this simulation and it turns out that the changes that I did to IO class were actually causing it create multiple instances, my bad. I have fixed those changes, you can see the commit [here](https://github.com/mlpack/mlpack/commit/e109ca7ffa17987234193d02b949d514c2093082), I think everything is correct now and surprisingly according to the simulation results the IO class is coming out to be thread safe. Both the outputs are same (either `BAR` or `FOO`). Can you take a look at it ?

**Comment by rcurtin** [comment]
IO is *definitely* not threadsafe.  Try calling different `mlpackMain()`s simultaneously. :+1:

**Comment by NippunSharma** [comment]
Hi @rcurtin , I was trying to call different `mlpackMain()` simultaneously, as you suggested. I am not sure whether what I am trying to do is correct or not. Can you take a look and tell if this is what you mean?

    #include <bits/stdc++.h>
    using namespace std;
    
    void threadTask(string output_model_name)
    {
      string cmd = "mlpack_random_forest --training_file data.csv --labels_file ";
             cmd +=  "labels.csv --output_model_file ";
             cmd +=  output_model_name + " -v";
      const char *command = cmd.c_str();
      system(command);
    }
    
    int main()
    {
      thread thread_obj_1(threadTask, "model_1.bin");
      thread thread_obj_2(threadTask, "model_2.bin");
      thread_obj_1.join();
      thread_obj_2.join();
    }

Can we call 2 `mlpackMain()` simultaneously using this?
Also I am not sure about what error to look for so that I would know that `IO` is not threadsafe?

**Comment by shrit** [comment]
@NippunSharma What does it gives when you un this code?

**Comment by shrit** [comment]
Let us stress it a little bit
```c++
int main()
{
  std::vector<std::thread> threads;
  for(int i = 0; i < 10; ++i) {
    threads.push_back(std::thread[&]()
    {
      string cmd = "mlpack_random_forest --training_file data.csv --labels_file ";
             cmd +=  "labels.csv --output_model_file ";
             cmd +=  model.bin + " -v";
      const char *command = cmd.c_str();
      system(command);
     });
   }
  for(auto& thread : threads) {
    thread.join();
  }
}




```

**Comment by shrit** [comment]
@NippunSharma try this one, and let me know about the results,

**Comment by rcurtin** [comment]
This won't work because you are running different processes, so each process ends up with its own `IO` singleton.  Instead, if you want to reproduce the issue, you would need to have each thread access `IO` directly and then call `mlpackMain()`.  Honestly, I think it might be easier to reproduce it from Julia, just calling a bunch of different bindings simultaneously.  If it doesn't crash outright, it's very likely to produce strange or incorrect results.

**Comment by NippunSharma** [comment]
@rcurtin okay, I get it now. 
I tried a different method now. I wrote some sort of a test like written in `tests/main_tests` that checks for thread safety.
It looks like follows:

```c++
#define BINDING_TYPE BINDING_TYPE_TEST
static const std::string testName = "ThreadSafetyTest";

#include <mlpack/core.hpp>
#include <mlpack/core/util/mlpack_main.hpp>
#include "test_helper.hpp"

// remove all the "std::move" from adaboost_main.cpp.
#include <mlpack/methods/adaboost/adaboost_main.cpp> 

#include "../test_catch_tools.hpp"
#include "../catch.hpp"

using namespace mlpack;

struct ThreadSafetyTestFixture
{
 public:
  ThreadSafetyTestFixture()
  {
    // Cache in the options for this program.
    IO::RestoreSettings(testName);
  }

  ~ThreadSafetyTestFixture()
  {
    // Clear the settings.
    bindings::tests::CleanMemory();
    IO::ClearSettings();
  }
};


TEST_CASE_METHOD(ThreadSafetyTestFixture, "ThreadSafetyTest",
                 "[ThreadSafetyMainTest][BindingTests]")
{
  arma::mat trainData;
  if (!data::Load("vc2.csv", trainData))
    FAIL("Unable to load train dataset vc2.csv!");

  arma::Row<size_t> labels;
  if (!data::Load("vc2_labels.txt", labels))
    FAIL("Unable to load label dataset vc2_labels.txt!");

  arma::mat testData;
  if (!data::Load("vc2_test.csv", testData))
    FAIL("Unable to load test dataset vc2.csv!");

  SetInputParam("training", std::move(trainData));
  SetInputParam("labels", std::move(labels));
  SetInputParam("test", std::move(testData));

  std::vector<std::thread> threads;
  for(int i = 0; i < 10; ++i) {
    threads.push_back(std::thread(mlpackMain));
  }

  for(auto& thread : threads) {
    thread.join();
  }
}
```
Then I run this test individually for checking any errors. Is this a valid method to check for thread safety?
While running this I encountered some errors, which were due to `std::move` in the `adaboost_main.cpp` file, so I had to remove them temporarily.

**Comment by rcurtin** [comment]
Did you get an error?  If you got an error, it's a valid method to check for thread safety.  Personally I would suggest using a number of different bindings, but this is hard from C++ (hence, why I personally found this originally in Julia).  The whole idea is to get each thread to look for *different* information from the `IO` singleton, which is shared across all threads.

**Comment by jeffin143** [comment]
This is done :) yoooo
