### ISSUE TITLE
ToLower function returns NULL

### ISSUE THREAD

**Issue by ayushsingh11** [mlpack/mlpack#2838]
#### Issue description

The ToLower function should return the input case in lower case.

#### Your environment

 * version of mlpack: 3.4.2
 * operating system:ubuntu
 * compiler:g++
 * version of dependencies (Boost/Armadillo):
 * any other environment information you think is relevant:

#### Steps to reproduce

One can run the following code:
#include <mlpack/core.hpp>
#include <mlpack/core/util/to_lower.hpp>
int main(){
	std::string a;
	mlpack::util::ToLower("ABC", a);
	std::cout << a;
	return 0;
}

#### Expected behavior

The string "abc" should have had been printed.

#### Actual behavior

Nothing was printed.

**Comment by rcurtin** [comment]
Wow, you are right, it doesn't seem to succeed.  I played with it for just a second and it looks like changing the implementation of `ToLower()` to use `std::back_inserter()` instead seems to succeed:

```c++
inline void ToLower(const std::string& input, std::string& output)
{
  std::transform(input.begin(), input.end(), std::back_inserter(output),
      [](unsigned char c){ return std::tolower(c); });
}
```

I opened a PR in #2839.  Thanks for the report!

**Comment by ayushsingh11** [comment]
Thanks @rcurtin 
Glad it would be solved now.
