### ISSUE TITLE
Question for Python bindings

### ISSUE THREAD

**Issue by onikolskyy** [mlpack/mlpack#2843]
Trying to set up a local dev environement and build from source as described in Documentation.

However, after running cmake with `BUILD_PYTHON_BINDINGS=ON`, `make`ing all targets and trying to `import mlpack`, I am getting 

```
  from .test_python_binding import test_python_binding
ModuleNotFoundError: No module named 'mlpack.test_python_binding'
```
The file `test_python_binding.pyx` is located in the same directory as `__init__.py` as expected 

The `PYTHONPATH` variable is set as needed, because python seems to find the package but not it's submodules.

Definitely not sure if it is a bug or a local issue but perhaps there is a fast solution?

Many thanks in advance

**Comment by NippunSharma** [comment]
Hmm, have you set the `LD_LIBRARY_PATH` variable ? If not you will have to do `make install` also.

**Comment by rcurtin** [comment]
Can you provide the exact commands you're using?  Like Nippun pointed out, you may need to set `LD_LIBRARY_PATH` to `lib/` inside of your build directory (that contains `libmlpack.so`, which many of the bindings depend on).  Typically, when I test the Python bindings in that way (without installing), I run python from `build/src/mlpack/bindings/python/` as `PYTHONPATH=. LD_LIBRARY_PATH=/path/to/build/lib/ python`.

**Comment by onikolskyy** [comment]
It's a **conda** issue I guess -- found out that it appears only in a **conda** environment (also when `PYTHONPATH` and `LD_LIBRARY_PATH` are set correctly). 
So, the fix for me was working with disabled **conda**

**Comment by NippunSharma** [comment]
Maybe it is a conda issue, I do not know much about conda as I use pip along with virtualenv for making an environment, then while running cmake I pass the python executable for the virtual environment. If you want to create a virtual environment you can try this approach.
