### ISSUE TITLE
RL tutorial example error

### ISSUE THREAD

**Issue by pogo85** [mlpack/mlpack#2849]
#### Problem location

https://www.mlpack.org/doc/stable/doxygen/rltutorial.html
#### Description of problem
When I try to run the example using the custom FFN network, it throws:
 `error: 'class mlpack::ann::FFN<mlpack::ann::MeanSquaredError<>, mlpack::ann::GaussianInitialization>' has no member named 'ResetNoise'`
but works when using SimpleDQN class.

**Comment by zoq** [comment]
Thanks for the info, the `FFN` does not implement the `ResetNoise` method, I'll update the tutorial.

**Comment by heisenbuug** [comment]
Heyy @zoq 
What's the solution here? Do we implement the method?

**Comment by gunnxx** [comment]
@heisenbuug 
`QLearning` expects an object which has `ResetNoise` method (e.g. `SimpleDQN`, `DuelingDQN`) because it calls the method during training. You are passing an `FFN` object (which has no `ResetNoise` method) to `QLearning`. The solution is to wrap your `FFN` object to a DQN object.
```
FFN<MeanSquaredError<>, GaussianInitialization> network(
        MeanSquaredError<>(), GaussianInitialization(0, 0.001));
network.Add<Linear<>>(4, 128);
network.Add<ReLULayer<>>();
network.Add<Linear<>>(128, 128);
network.Add<ReLULayer<>>();
network.Add<Linear<>>(128, 2);
SimpleDQN<> model(network);
```
