### ISSUE TITLE
Mlpack master doesn't build

### ISSUE THREAD

**Issue by jeffin143** [mlpack/mlpack#2852]
#### Issue description

The master branch doesn't build on mac os 

#### Your environment

 * version of mlpack: master 
 * operating system: mac os Big Sur (11.2.1)
 * compiler:
 * version of dependencies (Boost/Armadillo):
 * any other environment information you think is relevant:

#### Steps to reproduce

Here is the logs 

~/Documents/mlpack master ⇡5194 *10 ❯ rm -rf build                                                                                                                                                                                   21:07:57
~/Documents/mlpack master ⇡5194 *10 ❯ mkdir build                                                                                                                                                                                    21:08:02
~/Documents/mlpack master ⇡5194 *10 ❯ cd build                                                                                                                                                                                       21:08:17
~/Documents/mlpack/build master ⇡5194 *10 ❯ cmake -DBUILD_JULIA_BINDINGS=OFF -DBUILD_GO_BINDINGS=OFF -DBUILD_R_BINDINGS=OFF -DBUILD_PYTHON_BINDINGS=ON  ../                                                                          21:08:18
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cotire 1.7.10 loaded.
-- Found Armadillo: /usr/local/lib/libarmadillo.dylib (found suitable version "9.900.1", minimum required is "8.400.0") 
-- Could NOT find StbImage (missing: STB_IMAGE_INCLUDE_DIR) 
-- [download 100% complete]
-- [download 0% complete]
-- [download 6% complete]
-- [download 12% complete]
-- [download 19% complete]
-- [download 25% complete]
-- [download 31% complete]
-- [download 37% complete]
-- [download 44% complete]
-- [download 50% complete]
-- [download 56% complete]
-- [download 62% complete]
-- [download 68% complete]
-- [download 75% complete]
-- [download 81% complete]
-- [download 87% complete]
-- [download 93% complete]
-- [download 100% complete]
* Closing connection 0
* Closing connection 1
-- [download 100% complete]
-- [download 0% complete]
-- [download 25% complete]
-- [download 49% complete]
-- [download 74% complete]
-- [download 98% complete]
-- [download 100% complete]
* Closing connection 0
* Closing connection 1
-- Successfully downloaded stb into /Users/jeffin.sam/Documents/mlpack/build/deps/stb/
-- Found Ensmallen: /usr/local/include (found suitable version "2.12.1", minimum required is "2.10.0") 
-- Found cereal: /usr/local/include (found suitable version "1.3.0", minimum required is "1.1.2") 
-- Found Boost: /usr/local/include (found suitable version "1.72.0", minimum required is "1.58")  
-- Found OpenMP_C: -Xclang -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -Xclang -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found Git: /usr/bin/git (found version "2.24.3 (Apple Git-128)") 
-- Updated gitversion.hpp.
-- Regenerating arma_config.hpp.
CMake Warning at CMakeLists.txt:567 (message):
  txt2man not found; man pages will not be generated.

-- Not building Julia bindings.
-- Not building Markdown bindings.
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.17") 
-- Found PY_distutils: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils  
-- Found PY_Cython: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Cython  
-- Found PY_numpy: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy  
-- Found PY_pandas: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas  
-- Not building Go bindings.
-- Not building R bindings.
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- CXX target mlpack cotired.
-- CXX target mlpack_test cotired.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jeffin.sam/Documents/mlpack/build
~/Documents/mlpack/build master ⇡5194 *10 ❯ make                                                                                                                                                                                 45s 21:09:07
Scanning dependencies of target mlpack_arma_config
[  0%] Updating arma_config.hpp (if necessary)
[  0%] Built target mlpack_arma_config
Scanning dependencies of target mlpack_gitversion
[  0%] Updating gitversion.hpp (if necessary)
-- Found Git: /usr/bin/git (found version "2.24.3 (Apple Git-128)") 
-- gitversion.hpp is already up to date.
[  0%] Built target mlpack_gitversion
Scanning dependencies of target mlpack_headers
Moving header files to include/mlpack/
[  0%] Built target mlpack_headers
Scanning dependencies of target pkgconfig
[  0%] Generating mlpack.pc (pkg-config) file.
[  0%] Built target pkgconfig
[  0%] Generating CXX prefix source src/mlpack/cotire/mlpack_CXX_prefix.cxx
[  1%] Generating CXX prefix header src/mlpack/cotire/mlpack_CXX_prefix.hxx
[  1%] Building CXX precompiled header src/mlpack/cotire/mlpack_CXX_prefix.hxx.pch
Scanning dependencies of target mlpack
[  1%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/bindings/cli/print_help.cpp.o
[  1%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/bindings/tests/clean_memory.cpp.o
[  1%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/data/detect_file_type.cpp.o
[  1%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/data/load_csv.cpp.o
[  2%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/data/load_image.cpp.o
[  2%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/data/load.cpp.o
[  2%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/data/save_image.cpp.o
[  2%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/discrete_distribution.cpp.o
[  2%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/gaussian_distribution.cpp.o
[  3%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/laplace_distribution.cpp.o
[  3%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/regression_distribution.cpp.o
[  3%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/gamma_distribution.cpp.o
[  3%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/diagonal_gaussian_distribution.cpp.o
[  3%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/kernels/epanechnikov_kernel.cpp.o
[  3%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/kernels/pspectrum_string_kernel.cpp.o
[  4%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/columns_to_blocks.cpp.o
[  4%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/lin_alg.cpp.o
[  4%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/random.cpp.o
[  4%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/random_basis.cpp.o
[  4%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/tree/cosine_tree/cosine_tree.cpp.o
[  4%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/backtrace.cpp.o
[  5%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/io.cpp.o
[  5%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/log.cpp.o
[  5%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/prefixedoutstream.cpp.o
[  5%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/program_doc.cpp.o
[  5%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/singletons.cpp.o
[  5%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/timers.cpp.o
[  6%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/version.cpp.o
[  6%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/adaboost/adaboost_model.cpp.o
[  6%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/bayesian_linear_regression/bayesian_linear_regression.cpp.o
[  6%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/block_krylov_svd/randomized_block_krylov_svd.cpp.o
[  6%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/cf/cf_model.cpp.o
[  6%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/fastmks/fastmks_model.cpp.o
[  7%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/gmm/gmm.cpp.o
[  7%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/gmm/diagonal_gmm.cpp.o
[  7%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/hoeffding_trees/hoeffding_tree_model.cpp.o
[  7%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/kde/kde_model.cpp.o
[  7%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/lars/lars.cpp.o
[  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/linear_regression/linear_regression.cpp.o
[  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/local_coordinate_coding/lcc.cpp.o
[  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/matrix_completion/matrix_completion.cpp.o
[  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/neighbor_search/unmap.cpp.o
[  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/quic_svd/quic_svd.cpp.o
[  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/radical/radical.cpp.o
[  9%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/randomized_svd/randomized_svd.cpp.o
[  9%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/range_search/rs_model.cpp.o
[  9%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/rann/ra_util.cpp.o
[  9%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/rann/ra_model.cpp.o
[  9%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/softmax_regression/softmax_regression.cpp.o
[  9%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/softmax_regression/softmax_regression_function.cpp.o
[ 10%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_autoencoder/sparse_autoencoder.cpp.o
[ 10%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_autoencoder/sparse_autoencoder_function.cpp.o
[ 10%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_autoencoder/maximal_inputs.cpp.o
[ 10%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_coding/sparse_coding.cpp.o
[ 10%] Linking CXX shared library ../../lib/libmlpack.dylib
Undefined symbols for architecture x86_64:
  "___kmpc_critical", referenced from:
      bool arma::diskio::load_csv_ascii<int>(arma::SpMat<int>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      arma::SpMat<int>::sync_csc() const in load.cpp.o
      arma::SpMat<int>::init(arma::SpMat<int> const&) in load.cpp.o
      bool arma::diskio::load_csv_ascii<unsigned int>(arma::SpMat<unsigned int>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      arma::SpMat<unsigned int>::sync_csc() const in load.cpp.o
      arma::SpMat<unsigned int>::init(arma::SpMat<unsigned int> const&) in load.cpp.o
      bool arma::diskio::load_csv_ascii<unsigned long>(arma::SpMat<unsigned long>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      ...
  "___kmpc_end_critical", referenced from:
      bool arma::diskio::load_csv_ascii<int>(arma::SpMat<int>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      arma::SpMat<int>::sync_csc() const in load.cpp.o
      arma::SpMat<int>::init(arma::SpMat<int> const&) in load.cpp.o
      bool arma::diskio::load_csv_ascii<unsigned int>(arma::SpMat<unsigned int>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      arma::SpMat<unsigned int>::sync_csc() const in load.cpp.o
      arma::SpMat<unsigned int>::init(arma::SpMat<unsigned int> const&) in load.cpp.o
      bool arma::diskio::load_csv_ascii<unsigned long>(arma::SpMat<unsigned long>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      ...
  "___kmpc_for_static_fini", referenced from:
      _.omp_outlined. in gaussian_distribution.cpp.o
      _.omp_outlined. in gamma_distribution.cpp.o
      _.omp_outlined..47 in gamma_distribution.cpp.o
      _.omp_outlined..48 in gamma_distribution.cpp.o
      _.omp_outlined. in diagonal_gaussian_distribution.cpp.o
      _.omp_outlined..43 in diagonal_gaussian_distribution.cpp.o
      _.omp_outlined..44 in diagonal_gaussian_distribution.cpp.o
      ...
  "___kmpc_for_static_init_8u", referenced from:
      _.omp_outlined. in gaussian_distribution.cpp.o
      _.omp_outlined. in gamma_distribution.cpp.o
      _.omp_outlined..47 in gamma_distribution.cpp.o
      _.omp_outlined..48 in gamma_distribution.cpp.o
      _.omp_outlined. in diagonal_gaussian_distribution.cpp.o
      _.omp_outlined..43 in diagonal_gaussian_distribution.cpp.o
      _.omp_outlined..44 in diagonal_gaussian_distribution.cpp.o
      ...
  "___kmpc_fork_call", referenced from:
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in gaussian_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Mat<double> >(arma::Mat<double>&, arma::eOp<arma::Mat<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Col<double> >(arma::Mat<double>&, arma::eOp<arma::Col<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_scalar_times>::apply_inplace_plus<arma::eOp<arma::subview_col<double>, arma::eop_log> >(arma::Mat<arma::eOp<arma::subview_col<double>, arma::eop_log>::elem_type>&, arma::eOp<arma::eOp<arma::subview_col<double>, arma::eop_log>, arma::eop_scalar_times> const&) in gamma_distribution.cpp.o
      arma::eOp<arma::Col<double>, arma::eop_log>::elem_type arma::accu_proxy_linear<arma::eOp<arma::Col<double>, arma::eop_log> >(arma::Proxy<arma::eOp<arma::Col<double>, arma::eop_log> > const&) in diagonal_gaussian_distribution.cpp.o
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in diagonal_gaussian_distribution.cpp.o
      void arma::eglue_core<arma::eglue_plus>::apply<arma::Mat<double>, arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double> >(arma::Mat<double>&, arma::eGlue<arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double>, arma::eglue_plus> const&) in diagonal_gaussian_distribution.cpp.o
      ...
  "___kmpc_global_thread_num", referenced from:
      bool arma::diskio::load_csv_ascii<int>(arma::SpMat<int>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      arma::SpMat<int>::sync_csc() const in load.cpp.o
      arma::SpMat<int>::init(arma::SpMat<int> const&) in load.cpp.o
      bool arma::diskio::load_csv_ascii<unsigned int>(arma::SpMat<unsigned int>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      arma::SpMat<unsigned int>::sync_csc() const in load.cpp.o
      arma::SpMat<unsigned int>::init(arma::SpMat<unsigned int> const&) in load.cpp.o
      bool arma::diskio::load_csv_ascii<unsigned long>(arma::SpMat<unsigned long>&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in load.cpp.o
      ...
  "___kmpc_push_num_threads", referenced from:
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in gaussian_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Mat<double> >(arma::Mat<double>&, arma::eOp<arma::Mat<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Col<double> >(arma::Mat<double>&, arma::eOp<arma::Col<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_scalar_times>::apply_inplace_plus<arma::eOp<arma::subview_col<double>, arma::eop_log> >(arma::Mat<arma::eOp<arma::subview_col<double>, arma::eop_log>::elem_type>&, arma::eOp<arma::eOp<arma::subview_col<double>, arma::eop_log>, arma::eop_scalar_times> const&) in gamma_distribution.cpp.o
      arma::eOp<arma::Col<double>, arma::eop_log>::elem_type arma::accu_proxy_linear<arma::eOp<arma::Col<double>, arma::eop_log> >(arma::Proxy<arma::eOp<arma::Col<double>, arma::eop_log> > const&) in diagonal_gaussian_distribution.cpp.o
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in diagonal_gaussian_distribution.cpp.o
      void arma::eglue_core<arma::eglue_plus>::apply<arma::Mat<double>, arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double> >(arma::Mat<double>&, arma::eGlue<arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double>, arma::eglue_plus> const&) in diagonal_gaussian_distribution.cpp.o
      ...
  "_omp_get_max_threads", referenced from:
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in gaussian_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Mat<double> >(arma::Mat<double>&, arma::eOp<arma::Mat<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Col<double> >(arma::Mat<double>&, arma::eOp<arma::Col<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_scalar_times>::apply_inplace_plus<arma::eOp<arma::subview_col<double>, arma::eop_log> >(arma::Mat<arma::eOp<arma::subview_col<double>, arma::eop_log>::elem_type>&, arma::eOp<arma::eOp<arma::subview_col<double>, arma::eop_log>, arma::eop_scalar_times> const&) in gamma_distribution.cpp.o
      arma::eOp<arma::Col<double>, arma::eop_log>::elem_type arma::accu_proxy_linear<arma::eOp<arma::Col<double>, arma::eop_log> >(arma::Proxy<arma::eOp<arma::Col<double>, arma::eop_log> > const&) in diagonal_gaussian_distribution.cpp.o
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in diagonal_gaussian_distribution.cpp.o
      void arma::eglue_core<arma::eglue_plus>::apply<arma::Mat<double>, arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double> >(arma::Mat<double>&, arma::eGlue<arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double>, arma::eglue_plus> const&) in diagonal_gaussian_distribution.cpp.o
      ...
  "_omp_in_parallel", referenced from:
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in gaussian_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Mat<double> >(arma::Mat<double>&, arma::eOp<arma::Mat<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_log>::apply<arma::Mat<double>, arma::Col<double> >(arma::Mat<double>&, arma::eOp<arma::Col<double>, arma::eop_log> const&) in gamma_distribution.cpp.o
      void arma::eop_core<arma::eop_scalar_times>::apply_inplace_plus<arma::eOp<arma::subview_col<double>, arma::eop_log> >(arma::Mat<arma::eOp<arma::subview_col<double>, arma::eop_log>::elem_type>&, arma::eOp<arma::eOp<arma::subview_col<double>, arma::eop_log>, arma::eop_scalar_times> const&) in gamma_distribution.cpp.o
      arma::eOp<arma::Col<double>, arma::eop_log>::elem_type arma::accu_proxy_linear<arma::eOp<arma::Col<double>, arma::eop_log> >(arma::Proxy<arma::eOp<arma::Col<double>, arma::eop_log> > const&) in diagonal_gaussian_distribution.cpp.o
      arma::arma_rng::randn<double>::fill(double*, unsigned long long) in diagonal_gaussian_distribution.cpp.o
      void arma::eglue_core<arma::eglue_plus>::apply<arma::Mat<double>, arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double> >(arma::Mat<double>&, arma::eGlue<arma::eGlue<arma::eOp<arma::Col<double>, arma::eop_sqrt>, arma::Gen<arma::Col<double>, arma::gen_randn>, arma::eglue_schur>, arma::Col<double>, arma::eglue_plus> const&) in diagonal_gaussian_distribution.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libmlpack.3.4.dylib] Error 1
make[1]: *** [src/mlpack/CMakeFiles/mlpack.dir/all] Error 2
make: *** [all] Error 2

#### Expected behavior

The build failed 

#### Actual behavior
 
it should build

**Comment by zoq** [comment]
Can you run another test with `cmake -DUSE_OPENMP=OFF`?

**Comment by jeffin143** [comment]
Successful build with `cmake -DUSE_OPENMP=OFF`

**Comment by jeffin143** [comment]
@zoq https://github.com/mlpack/mlpack/pull/2412#issuecomment-629906719

**Comment by zoq** [comment]
> @zoq [#2412 (comment)](https://github.com/mlpack/mlpack/pull/2412#issuecomment-629906719)

Thanks, let's work on #2412.

**Comment by zoq** [comment]
With #2412 merged, let's close this one.
