### ISSUE TITLE
Predicting with a DQN model/agent

### ISSUE THREAD

**Issue by MarkFischinger** [mlpack/mlpack#2855]
I want to use a Predict function on a DQN model/agent. Is there a possible way to do so?
My attempt:
 ```cpp
model.Predict(testData, assignments); 
std::cout<<assignments<<std::endl;
```

Output:
```
-0.0013
-0.0195
-0.0040
-0.0046
-0.0099
```

**The Problem:** 
Unfortunately, the output is always the same, although the input is different. In the training you get different actions with the same data. 
Is there another way to get a Predict? There is an `agent.Train()` function is there also a kind of `agent.Predict()` that I am not aware of?

Link to the full code: https://github.com/mlpack/mlpack/issues/2801#issue-781307680

(Input size got reduced to 6000 and the actions extended to 5; I added a function which creates the datasets; I want to add a Predict method at the end)

Attached are two datasets I have used in the Prediction.
[1.txt](https://github.com/mlpack/mlpack/files/6078937/1.txt)
[2.txt](https://github.com/mlpack/mlpack/files/6078938/2.txt)

**Comment by zoq** [comment]
Do you think you could switch to the `SimpleDQN` class, you don't have to use the default network that is defined you can also define your own, https://github.com/mlpack/examples/blob/master/reinforcement_learning_gym/acrobot_dqn/acrobot_dqn.ipynb is one example.  `SimpleDQN`  provides a `Predict` method.

**Comment by MarkFischinger** [comment]
@zoq Thanks for your answer I will try to implement it and as soon as I am done I will get back to you.

**Comment by MarkFischinger** [comment]
@zoq The predicting works , but now I have the problem that I do not know how to save and load the model, 
because I can not save the `SimpleDQN<> model(module);` (model).
Error:
`error: 'class mlpack::rl::SimpleDQN<>' has no member named 'serialize'`

I could save the module, but the weights do not change.
**Is there a way to save and load the model properly?**

**Comment by zoq** [comment]
> @zoq The predicting works , but now I have the problem that I do not know how to save and load the model,
> because I can not save the `SimpleDQN<> model(module);` (model).
> Error:
> `error: 'class mlpack::rl::SimpleDQN<>' has no member named 'serialize'`
> 
> I could save the module, but the weights do not change.
> **Is there a way to save and load the model properly?**

Ohh, right, we should add the `serialize` method to the class as well. For now, would you could do is save `model.Parameters()` but you said they don't change?

**Comment by MarkFischinger** [comment]
@zoq There is the `Module` and the `Model`, [Code](https://github.com/mlpack/examples/blob/f87a2d16ee32c5c582cefacd5b58e957e2ad0dd4/reinforcement_learning_gym/acrobot_dqn/acrobot_dqn.cpp#L106). The weights of the `module` don't change, but the `model` weights change, which should not be an issue, because as you suggested you can save and load the `model.Parameters()` and **everything works fine**. Thank you for your help!

Code:
````
data::Save("./model.txt", "model", model.Parameters(), true);
data::Load("./model.txt", "model", model.Parameters(), true);

**Comment by MarkFischinger** [comment]
@zoq The model now saves correctly, but I now have a new problem. Loading works too, but the predictions are always the same, even if I use different weights.

[Testing Code](https://gist.github.com/MarkFischinger/9fdfb51560381a557240caf00ab49fa8)

**Output**
Weights (If other model is used also other values): 
```
Weights:
-0.403841
-10097.6
```
Prediction (Always the same, even if other weights are applied):
```
Assignments:
3.3744e+09
-1.1161e+10
1.2627e+10
```
**Other Models Ouput:**
```
Weights:
-0.293936
-17437.3
```
```
Assignments:
3.3744e+09
-1.1161e+10
1.2627e+10
```

**Comment by MarkFischinger** [comment]
@zoq It would be best if I could just load the model into the [Training Code](https://gist.github.com/MarkFischinger/b8a893ac87b4b6320cd704a87a56f29b) at the beginning, but this is apparently not possible, because the model is always reset to other parameters when you create the agent. 

(There are comments in the training code at the important places:  `// NOTE for Question:`)

**Comment by MarkFischinger** [comment]
@zoq There is a problem with the [`q_learning_impl.hpp`](https://github.com/mlpack/mlpack/blob/051b80b72eca752257a6d51c455b91e2fd534892/src/mlpack/methods/reinforcement_learning/q_learning_impl.hpp#L55), because the weights are reset. If I now want to load old weights then these are reset, too. Is it necessary to reset the weights there or is it possible to include an if statement if they should be reset?
