### ISSUE TITLE
Padding fails in Mean Pooling Backward() function

### ISSUE THREAD

**Issue by hello-fri-end** [mlpack/mlpack#2858]
#### Issue description
Simple test code
`

     arma::mat input;  

    arma::mat output;

    arma::mat delta;

     input.ones(100,1);

    MeanPooling<> module(3,3,1,1);

     module.InputWidth() = 10;

     module.InputHeight() = 10;

    module.Forward(input, output);

     module.Backward(input, output, delta);
`

#### Output
error: Mat::operator(): index out of bounds
terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::operator(): index out of bounds
Aborted (core dumped)

**Comment by onikolskyy** [comment]
hello, @hello-fri-end, I could reproduce the error
I would like to try to fix it. I will write tomorrow (Berlin time) if I found something

**Comment by onikolskyy** [comment]
Just made a PR.

#2865 

Would you mind looking through the code changes if they make sense?
