### ISSUE TITLE
Missing methods for BayesianLinearRegression

### ISSUE THREAD

**Issue by xlindo** [mlpack/mlpack#2879]
**Default constructor** and **parameters set/get methods** are missing in BayesianLinearRegression, similar to #2857 

[https://mlpack.org/doc/mlpack-git/doxygen/bayesian__linear__regression_8hpp_source.html](https://mlpack.org/doc/mlpack-git/doxygen/bayesian__linear__regression_8hpp_source.html)

**Comment by rcurtin** [comment]
Hey @xlindo, thanks for the report. :+1:  I added those methods in #2885.

The default constructor actually does exist---all four of the parameters to the constructor are optional, so you can simply leave them unset.
