### ISSUE TITLE
Running individual test suits fails on M1 macbook

### ISSUE THREAD

**Issue by RishabhGarg108** [mlpack/mlpack#2882]
#### Issue description
When running some test suites I get a `zsh: bus error`
Although running all the test cases using `./bin/mlpack_test`, it runs fine. But, when I run it with some particular ones, then it fails.

The following is a list of those tests that throw the error. (**Its not an exhaustive list.**):-

1. AdaBoost
2. AKFN
3. AKNN
4. ANNDist
5. ANNLayerTest
6. ANNRegularizerTest
7. ANNVisitorTest
8. ArmadilloSVDTest
9. AsyncLearningTest
10. BiasSVDTest
11. CallbackTest
12. CFTest
13. CLIOptionTest
14. ConvolutionalNetworkTest
15. CosineTreeTest
16. CVTest
17. DBSCANTest
18. DecisionTreeTest
19. DistributionTest
20. DrusillaSelectTest
21. FeedForwardNetworkTest
22. GMMTest
23. HMMTest
24. HyperplaneTest
25. InitRulesTest

The output on the console looks like
```
mlpack version: mlpack git-6cd97a7a4
armadillo version: 10.2.0 (Cicada Swarm)
Filters: [InitRulesTest]
zsh: bus error  ./bin/mlpack_test "[InitRulesTest]"
```

#### Your environment

 * version of mlpack: Latest mlpack master branch.
 * operating system: macOS Big Sur version 11.2.2
 * hardware: M1 Macbook Air
 * compiler: clang
 * version of dependencies (Boost/Armadillo): Armadillo: 10.2.0 and Boost: 1.75.0
 * cmake version: 3.19.6
 * terminal: zsh (default that comes with macbook)
 * any other environment information you think is relevant:

#### Steps to reproduce
1. Build mlpack's master branch from source.
2. run `./bin/mlpack_test "[<any of the tests mentioned in list above>]"`

#### Expected behavior
Test should run without any error.

#### Actual behavior
zsh bus error is thrown.

**Comment by shrit** [comment]
@RishabhGarg108 Thank you for opening the issue.
Would be possible to give more details about each error, since a few of us have the new M1 Mac which might be a little hard to reproduce the issue.
can you run `./bin/mlpack_test -s -r console [TagName]`
Please change the `TagName` with test suit tag that you can find in each test file.

**Comment by shrit** [comment]
@RishabhGarg108  In addition, let me know if these errors are related to anything similar to `DualCoverTree`

**Comment by RishabhGarg108** [comment]
Hey @shrit , I ran it for the `DecisionTreeTest`. The output was very long so I am putting the pastebin link https://pastebin.com/qmEmyTdg . I have never used pastebin before, so please confirm if you are able to see it. If not then I will simply paste it here :)

**Comment by RishabhGarg108** [comment]
> @RishabhGarg108 In addition, let me know if these errors are related to anything similar to `DualCoverTree`

Can you tell me which test suite to run to check this `DualCoverTree` ?

**Comment by RishabhGarg108** [comment]
For the `AKFNTest`, I am pasting the last few lines only.
```
/Users/ishanki/projects/mlpack-1/src/mlpack/tests/akfn_test.cpp:127: PASSED:
  REQUIRE( std::abs((distancesExact[i]) - (distancesApprox[i])) <= (0.05) * std::abs(distancesExact[i]) )
with expansion:
  0.0137579909 <= 0.066163731

/Users/ishanki/projects/mlpack-1/src/mlpack/tests/akfn_test.cpp:127: PASSED:
  REQUIRE( std::abs((distancesExact[i]) - (distancesApprox[i])) <= (0.05) * std::abs(distancesExact[i]) )
with expansion:
  0.0070474116 <= 0.0657021454

/Users/ishanki/projects/mlpack-1/src/mlpack/tests/akfn_test.cpp:127: PASSED:
  REQUIRE( std::abs((distancesExact[i]) - (distancesApprox[i])) <= (0.05) * std::abs(distancesExact[i]) )
with expansion:
  0.006685366 <= 0.0654758314

zsh: bus error  ./bin/mlpack_test -s -r console "[AKFNTest]"
```

For the `KNNTest`
```
/Users/ishanki/projects/mlpack-1/src/mlpack/tests/knn_test.cpp:163: PASSED:
  REQUIRE( distancesOut[i] == Approx(sqrt(correctDistances[i])).epsilon(1e-7) )
with expansion:
  1.0 == Approx( 1.0 )

/Users/ishanki/projects/mlpack-1/src/mlpack/tests/knn_test.cpp:162: PASSED:
  REQUIRE( neighborsOut[i] ==correctNeighbors[i] )
with expansion:
  1 == 1

/Users/ishanki/projects/mlpack-1/src/mlpack/tests/knn_test.cpp:163: PASSED:
  REQUIRE( distancesOut[i] == Approx(sqrt(correctDistances[i])).epsilon(1e-7) )
with expansion:
  1.4142135624 == Approx( 1.4142135624 )

zsh: bus error  ./bin/mlpack_test -s -r console "[KNNTest]"
```

**Comment by shrit** [comment]
Here is more info about the bus error `SIGBUS` https://en.wikipedia.org/wiki/Bus_error.
How much RAM do you have on your system?

**Comment by RishabhGarg108** [comment]
8GB RAM and 2GB swap

**Comment by shrit** [comment]
It is surprising, it should not be the case. Also, since we do not know anything about the architecture of the new M1. It might extremely hard to debug the issue.
I would start by testing the RAM by finding some software that does memory tests, maybe you were unlucky and the RAM is damaged. Also, it is true that this is extremely rare.
Also if you can monitor the memory usage when the test is failing that would be a great plus.
I would recommend finding the underlying issue that matches all these errors. I mean the piece of code that is causing the issue. Therefore, would it be possible that you find which test is failing and whether it is the same each time when you run the test suite?

**Comment by RishabhGarg108** [comment]
If it were a RAM issue, then shouldn't it be failing when I run other applications too? Like I haven't faced any failure on other apps since the last 2.5 months.
Also, I build mlpack regularly (which I kind of think like a stress test for RAM and processor :)) and I haven't yet faced any error in that. 

Also, If there were any issue with some particular test cases, then those should also fail when I run all the tests altogether. But this isn't the case. I tried it many times and each time when I run all the tests, it passes. But, the moment I run any of the tests mentioned in the issue description, it just fails.

Could it be related to `catch2` by any chance ?

**Comment by shrit** [comment]
What does it reports at the end, when you run all these tests together
All tests passing? would it be possible to run all these tests and paste the results report at the end?

**Comment by shrit** [comment]
Also, would you run `[FastMKSTest]`? let me know if this one passes

**Comment by RishabhGarg108** [comment]
> What does it reports at the end, when you run all these tests together
> All tests passing? would it be possible to run all these tests and paste the results report at the end?

Below is the output that I am getting when running all tests together. If you meant to run it with `-s -r console` then please tell me, I can share the complete output too.
```mlpack version: mlpack git-0ad73bc2c
armadillo version: 10.2.0 (Cicada Swarm)
--info: At Most 1 required but received 2
The following argument was not expected: --unknown
===============================================================================
All tests passed (33374892 assertions in 2047 test cases)
```



> Also, would you run `[FastMKSTest]`? let me know if this one passes

```
ishanki@Ishankis-MacBook-Air build % ./bin/mlpack_test "[FastMKSTest]"
mlpack version: mlpack git-0ad73bc2c
armadillo version: 10.2.0 (Cicada Swarm)
Filters: [FastMKSTest]
===============================================================================
All tests passed (134034 assertions in 20 test cases)
```

**Comment by shrit** [comment]
The fact that all tests are passing makes the issue harder to judge, but, in my opinion, I do not think that the issue is related neither to `catch` nor to `mlpack`.
Would it always fails if you try any test independently?

**Comment by zoq** [comment]
I have seen the problem before, do you mind to run the same test with `bash`, I know macOS has switched from `bash` to `zsh` but maybe you can install bash?

**Comment by RishabhGarg108** [comment]
@zoq , bash is also throwing same error :(
```
Ishankis-MacBook-Air:build ishanki$ ./bin/mlpack_test "[DecisionTreeTest]"
mlpack version: mlpack git-0ad73bc2c
armadillo version: 10.2.0 (Cicada Swarm)
Filters: [DecisionTreeTest]
Bus error: 10
```

**Comment by zoq** [comment]
Thanks, wondering if this is a hardware issue, do you think you can put this on a USB stick or something and run the test from there?

**Comment by RishabhGarg108** [comment]
> Thanks, wondering if this is a hardware issue, do you think you can put this on a USB stick or something and run the test from there?

I didn't quite understand. Do you mean that I copy the entire mlpack directory to a pen drive and run the commands from there or something else ?

Also, I realised that the `catch2` tests don't run in parallel [see here](https://github.com/catchorg/Catch2/blob/devel/docs/limitations.md#running-multiple-tests-in-parallel). So, maybe we can convert the individual test suites into their own binaries which could be run in parallel.

My only problem right now is that I have to run all the tests even if I made a really small change to the codebase, and this takes quite some time (more than 5 min). This really slows me down. So, splitting into binaries will solve my problem and also speed up things for other users also. Running tests are not that heavy, thus most of the people will be able to utilise all their cores and get atleast 4x speedup while running tests.

What is your take on this @zoq @shrit ?

**Comment by rcurtin** [comment]
> Also, I realised that the catch2 tests don't run in parallel see here. So, maybe we can convert the individual test suites into their own binaries which could be run in parallel.

Actually, no need to split into many binaries... another idea would be to modify the CMake configuration so that CMake knows all the names of the different test suites, then maybe you can do something like this:

```
foreach (test_suite TEST_SUITE_NAMES)
  add_test(NAME "catch_test_$(test_suite)" COMMAND mlpack_test "[$(test_suite)]" WORKING_DIRECTORY ${CMAKE_BINARY_DIR})
endforeach ()
```

I think that code *might* be right but I'm not 100% sure.  Anyway, if we did that, then if you used `ctest` to run the tests, they would be run in parallel. :+1:

**Comment by rcurtin** [comment]
The patch in #2869 *might* fix the issues, maybe worth a shot?

**Comment by RishabhGarg108** [comment]
> ```
> foreach (test_suite TEST_SUITE_NAMES)
>   add_test(NAME "catch_test_$(test_suite)" COMMAND mlpack_test "[$(test_suite)]" WORKING_DIRECTORY ${CMAKE_BINARY_DIR})
> endforeach ()
> ```
> 
> I think that code _might_ be right but I'm not 100% sure. Anyway, if we did that, then if you used `ctest` to run the tests, they would be run in parallel. 👍

I am unable to understand how is this different from me writing the command on the terminal myself? Isn't CMake eventually running the commands automatically for us so that we don't have to individually run them on the terminal ourselves? I might be wrong here because of my limited knowledge of CMake, but if I am correct then I am not very sure this will fix the issue.


> The patch in #2869 _might_ fix the issues, maybe worth a shot?

I will surely try to run the patches and see if I am able to run the tests that it fixes 👍

**Comment by rcurtin** [comment]
> I am unable to understand how is this different from me writing the command on the terminal myself? Isn't CMake eventually running the commands automatically for us so that we don't have to individually run them on the terminal ourselves? I might be wrong here because of my limited knowledge of CMake, but if I am correct then I am not very sure this will fix the issue.

You're exactly right!  The only difference is that if I write, say, `ctest -jN`, that will spawn `N` of the tests in parallel.  If I were to do that from the command line, I'd have to do something like... `bin/mlpack_test [KNNTest]&; bin/mlpack_test [KFNTest]&; bin/mlpack_test [AKFNTest]&; ...` (basically I'd have to parallelize it myself).  If you use `ctest -j1` though, it will be exactly the same as just running each test sequentially from the command line.  Hopefully that clarifies things; let me know if not. :+1:

**Comment by RishabhGarg108** [comment]
I agree ctest can parallelize the tests but I am not sure if it will run or throw the bus error which it currently does when I run specific tests. I will give it a shot and see if it works. 👍  The code snippet for cmake that you gave above, in which file shall I put it?

**Comment by rcurtin** [comment]
That suggestion would go in `src/mlpack/tests/CMakeLists.txt`, but I really don't think it will help the bus error at all.  I just wrote it down as a way to run tests in parallel.

**Comment by zoq** [comment]
@RishabhGarg108 Do you mind to update https://github.com/mlpack/mlpack/blob/master/src/mlpack/tests/main.cpp so that returns 0 at the end instead of whatever session run returns (the number of tests)?

**Comment by RishabhGarg108** [comment]
@zoq I changed it to following
```
Catch::Session().run(argc, argv);
return 0;
```
but, It still gives the error.

**Comment by conradsnicta** [comment]
For posterity, this issue may be related to a bug in macOS and/or AppleClang.
* https://gitlab.com/conradsnicta/armadillo-code/-/issues/173
* https://gitlab.com/conradsnicta/armadillo-code/-/issues/187

There is a workaround for this bug in Armadillo 10.6
