### ISSUE TITLE
Incorrect implementation of ceil_mode in pooling layers

### ISSUE THREAD

**Issue by abh2k** [mlpack/mlpack#2886]
The ceil_mode in pooling layers of mlpack doesnot match the implementation of pytorch.
The below notebook can reproduce the difference.

**Comment by abh2k** [comment]
I will try to fix this.

**Comment by rcurtin** [comment]
I think the issue still exists, so I'll reopen this.

**Comment by abh2k** [comment]
Yes I fixed this for mean pooling but for max and lp, it needs to be resolved.

**Comment by abh2k** [comment]
@rcurtin @zoq  this can be closed. I fixed this in #2936 .
