### ISSUE TITLE
problematic tests with absolute differences

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/mlpack#2897]
While testing the development version of [Armadillo 10.4](https://gitlab.com/conradsnicta/armadillo-code/-/tree/10.4.x), I came across this oddity when running mlpack tests (using mlpack master as of 31 Mar 2021):

```
-------------------------------------------------------------------------------
/home/conrad/git/mlpack-master/src/mlpack/tests/ann_dist_test.cpp:232
...............................................................................

/home/conrad/git/mlpack-master/src/mlpack/tests/ann_dist_test.cpp:291: FAILED:
  REQUIRE( arma::max(arma::max(arma::abs(jacobianA - jacobianB))) <= 5e-3 )
with expansion:
  1.0642238764 <= 0.005
```
It turns out that the above assertion is triggered by a difference between the following two (approximate) values from jacobianA and jacobianB: `149868.678` and `149867.614`.

While the absolute difference is around `1.064`, the _relative difference_ is quite small.  The relative difference can be calculated using: `|x − y| / max( |x|, |y| )`.

I suggest to refactor mlpack tests in order to avoid using assertions which rely only on absolute differences.

As an aid, Armadillo has the [`approx_equal()`](http://arma.sourceforge.net/docs.html#approx_equal) function, which determines approximate equality of two matrices using absolute and/or relative differences.

**Comment by swaingotnochill** [comment]
@conradsnicta @zoq Can I work on this issue? If yes, can u just give me a brief on what points should I keep in mind while working on this issue?

**Comment by conradsnicta** [comment]
@swaingotnochill No problem from my side, but I recommend checking with @rcurtin and/or @zoq (or other senior mlpack developers) as they have better knowledge of the nature of the tests, built-in assumptions, any special considerations, etc.

In the first instance I suggest looking for tests which use absolute differences, and adapting them to additionally use relative differences. For example, investigate if the following test:
```
REQUIRE( arma::max(arma::max(arma::abs(jacobianA - jacobianB))) <= 5e-3 )
```
could be replaced by something like:
```
REQUIRE( arma::approx_equal(jacobianA, jacobianB, "both", 5e-3, 5e-3)  )
```

**Comment by swaingotnochill** [comment]
@conradsnicta thank you.

**Comment by FawwazMayda** [comment]
I think I ever encounter a resemble code which use some kind of Approximation in another test. Such as

`REQUIRE(input.at(i) == Approx(target.(i)).epsilon(1e-5)`

Is this the same thing that you mean sir @conradsnicta

**Comment by conradsnicta** [comment]
> Is this the same thing that you mean sir @conradsnicta

The code `REQUIRE( input.at(i) == Approx(target.(i)).epsilon(1e-5) )` does an equality comparison, while allowing a degree of leeway. It's related to what I reported, in the sense that the above code is similar to taking an absolute difference.  For example, it's similar to:  `REQUIRE( (input.at(i) - target.(i)) == Approx(0.0).epsilon(1e-5) )`.  Due to the limited precision of floating point numbers, the two expressions may have slightly different results.

You will also need to check with the documentation of the [Catch2](https://github.com/catchorg/Catch2) testing framework to see the exact meaning of `.Approx(x).epsilon()` and how it works in the context of `==`.

**Comment by zoq** [comment]
Using [`approx_equal()`](http://arma.sourceforge.net/docs.html#approx_equal) makes absolutely sense, we should have done it from the beginning. @swaingotnochill feel free to open a PR.

**Comment by FawwazMayda** [comment]
If I comprehend it correctly using `arma::approx_equal()` is the preferred way for the test that use to compare an equality (maybe a slightly equal) for two values. Currently I am working on this #2894 which related to activation function test (file: `activation_functions_test.cpp)` should I consider to refactor the activation function test to use `arma::approx_equal()` ? If so I would take this task and open a PR. Thanks

**Comment by zoq** [comment]
> If I comprehend it correctly using `arma::approx_equal()` is the preferred way for the test that use to compare an equality (maybe a slightly equal) for two values. Currently I am working on this #2894 which related to activation function test (file: `activation_functions_test.cpp)` should I consider to refactor the activation function test to use `arma::approx_equal()` ? If so I would take this task and open a PR. Thanks

Let's open another PR for the refactoring, makes it easier to review.
