### ISSUE TITLE
Outdated "Testing Guidelines" on the wiki page

### ISSUE THREAD

**Issue by RishabhGarg108** [mlpack/mlpack#2903]
#### Problem location

https://github.com/mlpack/mlpack/wiki/Testing-Guidelines#creating-tests

#### Description of problem

We have ported our test suites from Boost to catch2 in #2523. So, we can change the documentation to
```
We use `Catch2` as the unit test framework. For a detailed explanation of the usage, 
please refer to the [documentation](https://github.com/catchorg/Catch2/blob/devel/docs/Readme.md).
However, for a quick view, you can refer to the previously implemented test cases in 
`src/mlpack/tests/` under the appropriate sub-directory.
```

I think that github doesn't allow changes to wiki files from people other than the maintainers so I am unable to make a PR for it. 
@rcurtin @zoq, can you please update this?

**Comment by rcurtin** [comment]
Awesome, thanks for the fix!  Updated. :+1:

**Comment by zoq** [comment]
Thanks, I just added a reference to https://github.com/mlpack/mlpack/blob/master/src/mlpack/tests/README.md as well.
