### ISSUE TITLE
Upsampling Layer 

### ISSUE THREAD

**Issue by Davidportlouis** [mlpack/mlpack#2907]
I'm trying to implement a deep learning model for reconstructing noisy images using convolutional autoencoder, below i have outlined my encoder & decoder architecture
```
# Encoder Stack

# Encoder Stack
Convolution(in_channels=1, out_channels=16, kernel_size=3, padding=1) # 28x28x16
ReLU() 
MaxPool() # 14x14x16
Conventional(in_channels=16, out_channels=4, kernel_size=3, padding=1) # 14x14x4
ReLU()
MaxPool() # 7x7x4
```

```
# Decoder Stack

# Decoder Stack
Upsample((2,2))  # 14x14x4
Convolution(in_channels=4, out_channels=16, kernel_size=3, padding=1) # 14x14x16
ReLU()
Upsample((2,2)) # 28x28x16
Conventional(in_channels=16, out_channels=1, kernel_size=3, padding=1) # 28x28x1
Sigmoid()
```

It seems mlpack does not have an implementation for Upsample Layer, The Upsampling layer is a simple layer with no weights that will double the dimensions of input. Is there any alternative in mlpack

**Comment by hello-fri-end** [comment]
Hey @Davidportlouis, you can use  [`BilinearInterpolation` ](https://www.mlpack.org/doc/stable/doxygen/classmlpack_1_1ann_1_1BilinearInterpolation.html) layer for upsampling.
