### ISSUE TITLE
Incorrect implementation of Swish function ?

### ISSUE THREAD

**Issue by medias661** [mlpack/mlpack#2914]
After digging into the source of some activation function in mlpack I figured out that the current implementation of the Swish function somehow does not match the original [paper](https://arxiv.org/abs/1710.05941). The original paper means to have a beta parameter (B) to control the behavior of the function itself in which when B=1 the Swish become like SILU and when B=0 the Swish become like a scaled linear function but in the case of mlpack the implementation using the assumption of B always equal to 1 (B=1).

**Comment by zoq** [comment]
Correct what we implemented is what is called `Swish-1` in the paper, which is also what tf and pytorch implements. I don't mind to extend the function and introduce the trainable parameter.

**Comment by FawwazMayda** [comment]
What a good explanation by @medias661. Assume that I am going to fix the Swish activation function, do I have to remove the current `swish_function.hpp` and re-implement it in the layer as `swish_layer.hpp`? Also does the beta parameter will be supplied when instantiating the SwishLayer class or let the B parameters adjusted accordingly when doing training @zoq @medias661?

**Comment by zoq** [comment]
Let's implement it as a layer, also the parameter is passed to the constructor or can be modified via getter/setter.

**Comment by FawwazMayda** [comment]
@zoq if we create the new `swish_layer.hpp` the how about the old `swish_function.hpp`, do we need to remove it?
