### ISSUE TITLE
Error when Loading Model in SimpleDQN

### ISSUE THREAD

**Issue by MarkFischinger** [mlpack/mlpack#2915]
#### Issue description

If I want to reuse a saved model and load it back in a [SimpleDQN](https://mlpack.org/doc/mlpack-3.3.1/doxygen/classmlpack_1_1rl_1_1SimpleDQN.html), I get an error, even though it is the same architecture as before.

#### Your environment

 * version of mlpack: 3.4.2
 * operating system: Ubuntu 20.04
 * compiler: g++ 9.3.0
 * version of dependencies (Boost/Armadillo):  1.71.0 / 9.800.4

#### Steps to reproduce

Here are two code samples, which together cause this error. 
In the first code sample, [Code 1](https://gist.github.com/MarkFischinger/e5948542b9d76e4f24cc302cb210e999), you can train the model and save it. This code is not working, because I can't provide the Training Environment. Therefore I will provide an already trained [model.txt](https://gist.github.com/MarkFischinger/bd4a7e10be23889c7f11d7057c41649c).  
In the second code sample, [Code 2](https://gist.github.com/MarkFischinger/2d46146e582fcb5154c746dc27759035),  you should be able to Load and Test the model. Also not working, because of the missing Environment, but you could test this with an `arma::randu<arma::colvec>(200);` The error occurs at the `.Predict()` function in the second file. 

#### Expected behavior

Normally the output should be a Prediction from the SimpleDQN. This would contain the 3 float values of the weights in an `arma::mat`.

#### Actual behavior

I get the error message:  `Core Dump (Segmentation fault)`
This probably happening, because the model isn't loaded/used correctly, but I wasn't able to find the error.

**Comment by MarkFischinger** [comment]
I created this [Adjusted Testing File](https://gist.github.com/MarkFischinger/779bd1c56202b922d0aac9a0ab89ba89), so that you could if you want to, test the second code by yourself. I hope it helps!

**Comment by MarkFischinger** [comment]
Update: I also tried to implement the testing directly in the training and I get the same error. This is a strong indication that the error is caused by an error in the `.Predict()` method or something familiar.

**Comment by gunnxx** [comment]
Quick look, I think you have a typo there. Your network input i.e. `DiscreteActionEnv::State::dimension` is 200, while your dummy input data i.e. `observation` dimension is 2000. I was unable to load your model for no apparent reason. However, skipping the `data::Load()`, I was able to run your test file with `arma::randu<arma::colvec>(200)`. Additionally, I don't understand why you can get `Core Dump (Segmentation fault)` only. My error message is very explicit. Here's my complete output running your test file (skipping the load `data::Load()`)
```
8.400.0 (Entropy Bandit)
1.65.1
mlpack git-a7b8e1189
Building Network...
Build Network.
Starting Environment...
Started Environment.
Training...
terminate called after throwing an instance of 'std::logic_error'
  what():  FFN<>::Predict(): the first layer of the network expects 200 elements, but the input has 2000 dimensions!
Aborted (core dumped)
```

**Comment by MarkFischinger** [comment]
@gunnxx Oh, sorry about that, I really made a typo in `observation = arma::randu<arma::colvec>(2000);` it's just `arma::randu<arma::colvec>(200);` In my other code the dimension where correct.

>  I was unable to load your model for no apparent reason. 

This is my main issue. I still get an error when I try to load a model, even if all dimensions are the same and correct.

**Comment by MarkFischinger** [comment]
@gunnxx I also built a training file [here ](https://gist.github.com/MarkFischinger/b0978c549b520349cb7f1d4359f0f8b3)that should work without the environment. So you don't have to download my model.txt file, but you can create one on your own.

**Comment by gunnxx** [comment]
I tried to run your training file, but it failed. The error was `Unable to detect type of './model.txt'; incorrect extension? (allowed: xml/bin/json)`. I dug up the documentation and the code and found that:
- [The documentation](https://www.mlpack.org/doc/stable/doxygen/namespacemlpack_1_1data.html#af30f8bfca9b924d6d935c9f1fae91778) said that the allowed formats are `txt`, `xml`, and `bin`.
- [The header file](https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/data/save.hpp#L126) and [the implementation](https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/data/save_impl.hpp#L263) said that the allowed formats are `json`, `xml`, and `bin`.

I changed the name of the file from `model.txt` to `model.xml` and run your [training file](https://gist.github.com/MarkFischinger/b0978c549b520349cb7f1d4359f0f8b3), it succeed. I also run your [adjusted testing file](https://gist.github.com/MarkFischinger/779bd1c56202b922d0aac9a0ab89ba89) with `model.xml` and it also succeed.

**Comment by MarkFischinger** [comment]
@gunnxx Thank you very much for your help! Using an an `.xml` or `.bin` works! Everybody in the Future who might have the same problem: Make sure that you use the current `master` branch because I still got an error when using `mlpack 3.4.2 (the current stable version)`
