### ISSUE TITLE
error: Mat::init(): requested size is too large

### ISSUE THREAD

**Issue by lucasmaisonnave** [mlpack/mlpack#2921]
#### Issue description
I tried to implement a CNN model for my Chess AI but it doesn't work, the problem occurs during the training phase and throws me this error:
error: Mat::init(): requested size is too large
terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::init(): requested size is too large
Abandon (core dumped)

I can't find any solution to this problem and it does't seem to be related with the size of the data set because with only 768 rows and 1 colums I have the same issue. And with a simple Layers model I don't have any problem and the model can train.
If you want to reproduce the issue the code is available on my github : https://github.com/lucasmaisonnave/Machine-Learning/tree/main/mlpack.
The model is implemented in the main.cpp file and you can execute ./mlapp or the Makefile to start the program.

#### Your environment

 * version of mlpack:
 * operating system: Ubuntu
 * compiler: g++
 * version of dependencies (Boost/Armadillo):
 * any other environment information you think is relevant:

**Comment by rcurtin** [comment]
It might be a little while until I or someone can dig into this, but by any chance, are you able to put gdb on the code or something and get a backtrace of where the failing allocation is?  That could tell us a lot about what's going on.
