### ISSUE TITLE
wrong R2 calculation?

### ISSUE THREAD

**Issue by greenfish77** [mlpack/mlpack#2924]
I am using mlpack's linear regression,
and found that the evaluated R2 was wrong than I expected.
my evaluation code:
```c++
double r2 = mlpack::cv::R2Score::Evaluate(lr, training_x, training_y);
```
Sometimes very large negative r2 results have been reported.
So, I tried debugging with the code below referring to metrics/r2_score_impl.hpp.
```c++
int main(void) {
    double r2 = 0.0;
    arma::rowvec responses = {1,2,3};
    arma::rowvec predictedResponses = {4,5,6};

    double meanResponses = arma::mean(responses);

    // Calculate the numerator i.e. residual sum of squares.
    double residualSumSquared = arma::accu(arma::square(responses - predictedResponses));

    // Calculate the denominator i.e.total sum of squares.
    double totalSumSquared = arma::accu(arma::square(responses - meanResponses));

    // Handling undefined R2 Score when both denominator and numerator is 0.0.
    if (residualSumSquared == 0.0) {
        r2 = totalSumSquared ? 1.0 : DBL_MIN;
    } else {
        r2 = 1.0 - residualSumSquared / totalSumSquared;
    }
    std::cout << "result: " << r2 << std::endl;

    return 0;
}
```
If (1,2,3)->(4,5,6) then R2 must be obviously 1.
However, the result is as follows.
```
result: -12.5
```
I think 'metric' is one of the most important things in a machine learning framework.
However, the result came out unexpectedly, and I was shocked a lot.
I was worried that the wrong R2 was reported to many people who used mlpack.

I modified the code as follows.
```c++
int main(void) {
	double result = 0.0;
	arma::rowvec responses = {1,2,3};
	arma::rowvec predictedResponses = {4,5,6};

	double sum_x = arma::accu(responses);
	double sum_y = arma::accu(predictedResponses);
	double sum_xy = arma::accu(responses % predictedResponses);
	double sum_xx = arma::accu(arma::square(responses));
	double sum_yy = arma::accu(arma::square(predictedResponses));
	double count = static_cast<double>(responses.n_cols);
	double r2 = (count * sum_xy - sum_x * sum_y) / sqrt(((count * sum_xx - pow(sum_x, 2)) * (count * sum_yy - pow(sum_y, 2))));
	r2 = pow(r2, 2);
	std::cout << "result: " << r2 << std::endl;

	return 0;
}
```
The output is as expected.
```
result: 1
```
I have my own R2 function that is processed in a single for-loop.
But, it was implemented to show readability and armadillo call.
For optimization, it may be necessary to implement a single for-loop.

ps)
Have you ever tried to calculate the adjusted R2?
But, it was different from the adjusted R2 result calculated by hand.

**Comment by rcurtin** [comment]
I don't understand your example---based on what you wrote, `-12.5` is the answer I would expect.  In your code, you have:

```
    arma::rowvec responses = {1,2,3};
    arma::rowvec predictedResponses = {4,5,6};
```

but in this situation, `predictedResponses` are not the same as `responses`, so the R2 score will not be `1`.  If you were to set `predictedResponses` to be equal to `responses`, it should give `1` as output.

Let me know if I've overlooked something. :+1:

**Comment by greenfish77** [comment]
I found that you mean R2 as coefficient of determination. 
but, i meant R2 as the square of the pearson correlation coefficient.

https://ncalculators.com/statistics/r-squared-calculator.htm
I input 1,2,3 and 4,5,6, and click 'GENERATE WORK', it outputs R2 as 1.
it uses R2 as the square of the pearson correlation coefficient.
There are various formulas for R2, but different ones were used than I thought.

Since my company uses the pearson correlation coefficient for R2(0~1), I have to calculate R2 with my code.
I checked again and confirmed the correctness of the current mlpack's R2.
Sorry for the confusion and close the issue.

**Comment by rcurtin** [comment]
Ahh, I see---do you want to contribute your implementation as a metric like `PearsonCorrelation` or `PearsonR` or something?  Then we would have both and hopefully nobody else would have the issue that you had. :+1:

**Comment by greenfish77** [comment]
I am using mlpack with several modifications for my environment.

I prefer to evaluate with 10-fold-cv,
but mlpack's cv does not yield R2 and MSE at the same time, so it took twice as long.

By modifying that part, I am getting two evals with cv at once.
After testing some of these fixes internally, I will review them for future fixes.

**Comment by rcurtin** [comment]
That would be great!  Contributions and improvements are definitely welcome. :+1:
