### ISSUE TITLE
Make ExtraTrees accessible from bindings.

### ISSUE THREAD

**Issue by RishabhGarg108** [mlpack/mlpack#2932]
PR #2883 adds the `ExtraTrees`, but it is accessible only through C++. To make it accessible from bindings of other languages, it needs to be added to the bindings for the random forest.

It should be pretty straightforward to add. One approach that I have in my mind is to add another optional parameter which when set, will trigger the `ExtraTrees` algorithm. But, don't feel obligated to do it this way, there are tons of ways for doing this and feel free to explore other possibilities.

One thing to keep in mind while exploring is that the bindings are something with which the end-user interacts directly. So, do it in such a way so that it feels intuitive to the user.

**Comment by RishabhGarg108** [comment]
@rcurtin, mentioning you just to subscribe you to this issue :-)

**Comment by rcurtin** [comment]
Thanks for opening this @RishabhGarg108! :+1:

I think that the binding we would want to modify would be `src/mlpack/methods/random_forest/random_forest_main.cpp`, but I suppose it could be okay to create an additional `ExtraTrees` binding if we wanted.

**Comment by PranshuSrivastava** [comment]
Hey, I would like to work on this issue but I don't know how to work with bindings. Could you please recommend to me some articles or videos where I can learn about it?

**Comment by RishabhGarg108** [comment]
Hey @PranshuSrivastava, mlpack has its own system to generate bindings. Please refer to https://www.mlpack.org/doc/stable/doxygen/bindings.html tutorial. It is a comprehensive guide. Also, as rcurtin mentioned above, try to make a separate binding for `ExtraTrees`.

I hope that helps.

**Comment by PranshuSrivastava** [comment]
@RishabhGarg108  I went through the tutorial, so I need to write the interface by myself, and for the main function and the implementation I have to use the code from your pull request right?

**Comment by RishabhGarg108** [comment]
@PranshuSrivastava yes. You might also want to look at `src/mlpack/methods/random_forest/random_forest_main.cpp` for motivation since `ExtraTrees` is very similar to the `RandomForest`.

Also, that PR is merged, so you need not work on that PR explicitly. You can work on the latest master branch 👍

**Comment by PranshuSrivastava** [comment]
@RishabhGarg108 I tried to make the file. Please checkout my pull request.

**Comment by RishabhGarg108** [comment]
Keep open

**Comment by PranshuSrivastava** [comment]
![image](https://user-images.githubusercontent.com/37413698/130411425-a214c9f2-7008-4280-bf52-c9854e3dc00c.png)
These were the errors that I got with the mlpack_main.hpp file and the param file
