### ISSUE TITLE
What does `numClasses` mean in `Train()`'s parameters list for decision tree?

### ISSUE THREAD

**Issue by xlindo** [mlpack/mlpack#2941]
```cpp
 template<typename MatType, typename LabelsType>
  double Train(MatType data,
               LabelsType labels,
               const size_t numClasses,
               const size_t minimumLeafSize = 10,
               const double minimumGainSplit = 1e-7,
               const size_t maximumDepth = 0,
               DimensionSelectionType dimensionSelector =
                   DimensionSelectionType());
```

Thanks.

**Comment by rcurtin** [comment]
It is the number of unique elements in `labels`. :+1:

**Comment by xlindo** [comment]
> It is the number of unique elements in `labels`. 👍 (So, e.g., the number of possible classes in the data.) If your `labels` are sequential and start from 0 (so, in the two-class case, a label would be `0` or `1`), then you can compute `numClasses` as `arma::max(labels) + 1`.

Could you give me an explanation based on [https://sci2s.ugr.es/keel/dataset.php?cod=72](https://sci2s.ugr.es/keel/dataset.php?cod=72)?

There are `Features 40` and `Classes 11`. What I am confused are
1. If `numClasses` is specified by the unique elements in labels, why it should be set manually
2. How to set it

There is a test for the dataset mentioned above using decision tree.
```cpp
/* ... */
    arma::mat mlpack_texture_train_X, mlpack_texture_test_X;
    arma::rowvec mlpack_texture_train_y;

    mlpack::data::Load("../data/texture/texture_train_X.csv",
                       mlpack_texture_train_X);
    mlpack::data::Load("../data/texture/texture_train_y.csv",
                       mlpack_texture_train_y);

    std::shared_ptr<mlpack::tree::DecisionTree<>> mlpack_dt(
                                                   new mlpack::tree::DecisionTree<>);
   arma::Row<size_t> tmp_labels;
    tmp_labels = arma::conv_to<arma::Row<size_t>>::from(mlpack_texture_train_y);

    mlpack_dt->Train(mlpack_texture_train_X, tmp_labels,
                     14);
/* ... */
```

At last line, if it is set as `14` or less, then
```
error: Mat::operator(): index out of bounds
terminate called after throwing an instance of 'std::out_of_range'
  what():  Mat::operator(): index out of bounds
```
If is set as `15` or greater, all thing goes well.

**Comment by rcurtin** [comment]
Sure, happy to help!

1. We have it as a manual parameter for efficiency reasons.  `arma::max(labels) + 1` takes time to compute (we have to scan all the `labels`), but if you statically know when you write your program that there are only 10 classes, then you can save that time and just input the number of classes directly.

2. If labels don't start from 0 and aren't sequential, you want to use `data::NormalizeLabels()` to map them to `[0, numClasses)`.  You could use it like this:

```
arma::Row<size_t> mappedLabels;
arma::Col<size_t> labelMap;

NormalizeLabels(labels, mappedLabels, labelMap);

// Now you use `mappedLabels` in your code and model.
```

Then, if you compute predictions or something like that with `.Classify()`, you can use `labelMap` and `RevertLabels()` to map them back to their original values:

```
arma::Row<size_t> predictions;

model.Classify(testSet, predictions);
// `predictions` will be in the range [0, numClasses).

arma::Row<size_t> revertedPredictions;
RevertLabels(predictions, labelMap, revertedPredictions);
// Now, `revertedPredictions` will be in the range `{2, 3, 4, 9, 10, 7, 6, 8, 12, 13, 14}`/
```

Hopefully this helps!  Let me know if I can clarify anything.

**Comment by xlindo** [comment]
> Sure, happy to help!
> 
> 1. We have it as a manual parameter for efficiency reasons.  `arma::max(labels) + 1` takes time to compute (we have to scan all the `labels`), but if you statically know when you write your program that there are only 10 classes, then you can save that time and just input the number of classes directly.
> 2. If labels don't start from 0 and aren't sequential, you want to use `data::NormalizeLabels()` to map them to `[0, numClasses)`.  You could use it like this:
> 
> ```
> arma::Row<size_t> mappedLabels;
> arma::Col<size_t> labelMap;
> 
> NormalizeLabels(labels, mappedLabels, labelMap);
> 
> // Now you use `mappedLabels` in your code and model.
> ```
> 
> Then, if you compute predictions or something like that with `.Classify()`, you can use `labelMap` and `RevertLabels()` to map them back to their original values:
> 
> ```
> arma::Row<size_t> predictions;
> 
> model.Classify(testSet, predictions);
> // `predictions` will be in the range [0, numClasses).
> 
> arma::Row<size_t> revertedPredictions;
> RevertLabels(predictions, labelMap, revertedPredictions);
> // Now, `revertedPredictions` will be in the range `{2, 3, 4, 9, 10, 7, 6, 8, 12, 13, 14}`/
> ```
> 
> Hopefully this helps! Let me know if I can clarify anything.

Many thanks.
I think I should know more frequently used methods in mlpack for data preprocessing. Is there a guidance page?

**Comment by rcurtin** [comment]
Sure, happy to help!  I think the best documentation might just be the list of classes and functions in the `mlpack::data` namespace:

https://www.mlpack.org/doc/mlpack-3.4.2/doxygen/namespacemlpack_1_1data.html (for version 3.4.2)

https://www.mlpack.org/doc/mlpack-git/doxygen/namespacemlpack_1_1data.html (for git `master` branch)

Doxygen documentation isn't perfect, but hopefully that is helpful.  Also, maybe looking in the codebase in `src/mlpack/core/data/` is easier; I'm not sure, depends on your preference. :)

**Comment by xlindo** [comment]
> Sure, happy to help! I think the best documentation might just be the list of classes and functions in the `mlpack::data` namespace:
> 
> https://www.mlpack.org/doc/mlpack-3.4.2/doxygen/namespacemlpack_1_1data.html (for version 3.4.2)
> 
> https://www.mlpack.org/doc/mlpack-git/doxygen/namespacemlpack_1_1data.html (for git `master` branch)
> 
> Doxygen documentation isn't perfect, but hopefully that is helpful. Also, maybe looking in the codebase in `src/mlpack/core/data/` is easier; I'm not sure, depends on your preference. :)

Thanks.
This item can be closed.
