### ISSUE TITLE
Release build can't find stb

### ISSUE THREAD

**Issue by r3n4ud** [mlpack/mlpack#2944]
Recent changes have broken the 3.4.2 build.

Some improvements have been done in CMakeLists.txt on the STB downloading part. Now, an archive is downloaded instead of single header files. Unfortunately, the static service provided by https://www.mlpack.org/files/ reflects this changes but doesn't provide single headers needed by the release build...

OK, a solution is to checkout master but it seems preferable to guarantee that the latest release tag build.

**Comment by shrit** [comment]
Thanks for pointing out the issue, I will open pull request to keep the backward compatibility.

**Comment by rcurtin** [comment]
(I'm just going to reopen this until the website gets rebuilt.  Thanks for the report @r3n4ud!)

**Comment by rcurtin** [comment]
Okay, got everything rebuilt.  It should work now. :+1:

**Comment by r3n4ud** [comment]
It works! Thx!
