### ISSUE TITLE
UMAP implementation

### ISSUE THREAD

**Issue by bkmgit** [mlpack/mlpack#2948]
### Add UMAP implementation

Uniform Manifold Approximation and Projection is a useful technique for dimension reduction. It would be nice to have a portable implementation in mlpack.

### What is the motivation for this feature?

Dimension reduction is a useful pre-processing step for doing classification.

### If applicable, describe how this feature would be implemented.
An implementation in Python is at https://github.com/lmcinnes/umap and in Julia at https://github.com/dillondaudert/UMAP.jl

**Comment by zoq** [comment]
Hello @bkmgit is this something you like to work on, or should I mark this as "good first issue"?

**Comment by bkmgit** [comment]
@zoq Interested in adding this.

**Comment by rcurtin** [comment]
This would be great to add!  It would go along well with our PCA/KPCA/ICA implementations.
