### ISSUE TITLE
Higher order singular value decomposition

### ISSUE THREAD

**Issue by bkmgit** [mlpack/mlpack#2949]
### Add an implementation of the higher order singular value decomposition

The higher order singular value decomposition is a generalization of the singular value decomposition
that can enable more good dimension reduction and classification.

### What is the motivation for this feature?

It is an explainable algorithm that is helpful for machine learning tasks.

### If applicable, describe how this feature would be implemented.
It is described in
[Analyses and Tests of Handwritten Digit Recognition Algorithms](https://weber.itn.liu.se/~bersa48/files/thesisBerkantSavas.pdf)
[Tensor Decompositions and Applications](https://old-www.sandia.gov/~tgkolda/pubs/pubfiles/SAND2007-6702.pdf)
[Handwritten digit classification using higher order singular value decomposition](https://doi.org/10.1016/j.patcog.2006.08.004)
[Matrix Methods in Data Mining and Pattern Recognition](https://epubs.siam.org/doi/book/10.1137/1.9780898718867)

A distributed memory parallel implementation is available at https://gitlab.com/tensors/TuckerMPI

**Comment by zoq** [comment]
Hello @bkmgit I like the idea, is this something you like to work on or should I mark this as "good first issue" as well?

**Comment by bkmgit** [comment]
@zoq Interested in adding this.

**Comment by bkmgit** [comment]
Related libraries:
- https://github.com/ShadenSmith/splatt
- https://tensors.lanl.gov/
- https://github.com/tensorly/tensorly
- https://github.com/TensorDecompositions/NTFk.jl
- https://github.com/lanaperisa/TensorToolbox.jl
- https://github.com/yunjhongwu/TensorDecompositions.jl

**Comment by rcurtin** [comment]
One issue here is that Armadillo only supports 3-d tensors; so going higher-order than that would either require some kind of wrapper class for an Armadillo object that can make it "act" higher-dimensional or some other solution.  For some of these decompositions, it might make sense to contribute them to Armadillo directly. :+1:

**Comment by bkmgit** [comment]
Ok. Thanks.
