### ISSUE TITLE
Is `DatasetInfo` a necessary parameter for Hoeffding Tree?

### ISSUE THREAD

**Issue by xlindo** [mlpack/mlpack#2962]
In `hoeffding_tree.hpp`, there is a default constructor without parameters, and also a `Train` method does not need `DatasetInfo`. 
But when using these two to avoid passing `DatasetInfo`, like,
```cpp
 std::shared_ptr<mlpack::tree::HoeffdingTree<>> mlpack_ht(
                                                  new mlpack::tree::HoeffdingTree<>());
// ... Loading data
try
{
    mlpack_ht->Train(mlpack_texture_train_X, tmp_labels);
}
catch (std::exception& e)
{
    std::cerr << e.what() << std::endl << std::endl;
}
```
an exception is thrown.
```shell
requested type of dimension 0, but dataset only has 0 dimensions
```

So is `DatasetInfo` a necessary parameter for Hoeffding Tree? Or is it possible to train a Hoeffding tree without passing in `DatasetInfo` **explicitly**?

**Comment by rcurtin** [comment]
Hey @xlindo, thanks for reporting this!  I played with the example and found that this is indeed a bug in the handling of new datasets.  I opened a PR, #2964, which should fix the issue.  If you'd like to try your code on that branch and see if it works, that would be great!

In any case, to answer the original question, it should be possible to train a Hoeffding tree without a `data::DatasetInfo`.  But, due to a bug in the code, that does not currently work.  It will, though, once #2964 is merged. :smile:

**Comment by xlindo** [comment]
> Hey @xlindo, thanks for reporting this! I played with the example and found that this is indeed a bug in the handling of new datasets. I opened a PR, #2964, which should fix the issue. If you'd like to try your code on that branch and see if it works, that would be great!
> 
> In any case, to answer the original question, it should be possible to train a Hoeffding tree without a `data::DatasetInfo`. But, due to a bug in the code, that does not currently work. It will, though, once #2964 is merged. 😄

Thanks a lot!
I will try it later.

**Comment by xlindo** [comment]
> Hey @xlindo, thanks for reporting this! I played with the example and found that this is indeed a bug in the handling of new datasets. I opened a PR, #2964, which should fix the issue. If you'd like to try your code on that branch and see if it works, that would be great!
> 
> In any case, to answer the original question, it should be possible to train a Hoeffding tree without a `data::DatasetInfo`. But, due to a bug in the code, that does not currently work. It will, though, once #2964 is merged. 😄

It works now. This issue can be closed. Thanks.

**Comment by xlindo** [comment]
> Hey @xlindo, thanks for reporting this! I played with the example and found that this is indeed a bug in the handling of new datasets. I opened a PR, #2964, which should fix the issue. If you'd like to try your code on that branch and see if it works, that would be great!
> 
> In any case, to answer the original question, it should be possible to train a Hoeffding tree without a `data::DatasetInfo`. But, due to a bug in the code, that does not currently work. It will, though, once #2964 is merged. 😄

For consistency with other classification algorithms, I thought there can be a optional parameter `num_classes=0`  of `Train(...)`.

**Comment by rcurtin** [comment]
> > Hey @xlindo, thanks for reporting this! I played with the example and found that this is indeed a bug in the handling of new datasets. I opened a PR, #2964, which should fix the issue. If you'd like to try your code on that branch and see if it works, that would be great!
> > In any case, to answer the original question, it should be possible to train a Hoeffding tree without a `data::DatasetInfo`. But, due to a bug in the code, that does not currently work. It will, though, once #2964 is merged. smile
> 
> For consistency with other classification algorithms, I thought there can be an optional parameter `num_classes=0` of `Train(...)`.

Nice point!  Let me add that to the changes in #2964. :+1:

**Comment by xlindo** [comment]
> > > Hey @xlindo, thanks for reporting this! I played with the example and found that this is indeed a bug in the handling of new datasets. I opened a PR, #2964, which should fix the issue. If you'd like to try your code on that branch and see if it works, that would be great!
> > > In any case, to answer the original question, it should be possible to train a Hoeffding tree without a `data::DatasetInfo`. But, due to a bug in the code, that does not currently work. It will, though, once #2964 is merged. smile
> > 
> > 
> > For consistency with other classification algorithms, I thought there can be an optional parameter `num_classes=0` of `Train(...)`.
> 
> Nice point! Let me add that to the changes in #2964. 👍

Many thanks.
This issue could be closed now.
