### ISSUE TITLE
Getter and setter methods for template parameters for `KMeans`

### ISSUE THREAD

**Issue by xlindo** [mlpack/mlpack#2967]
In `kmeans.hpp`, there are getter and setter methods for template parameters, e.g., 
 
```cpp
  //! Get the empty cluster policy.
  const EmptyClusterPolicy& EmptyClusterAction() const
  { return emptyClusterAction; }
  //! Modify the empty cluster policy.
  EmptyClusterPolicy& EmptyClusterAction() { return emptyClusterAction; }
```

This makes me confused. Once the algorithm is instanced, how could the inner types be modified? Or if there is other way to use these methods, please let me know that.

Thanks.

**Comment by rcurtin** [comment]
You can't change the type of `EmptyClusterPolicy` once you have made a `KMeans<>` object, but you can change and modify the one that is held.  So, for instance, if the `EmptyClusterPolicy` you were using stored some state, like, e.g., the maximum number of reclustering attempts or something, you could change that via modifying `kmeans.EmptyClusterAction()`, then calling `kmeans.Cluster()` again for different behavior. :+1:

**Comment by xlindo** [comment]
> You can't change the type of `EmptyClusterPolicy` once you have made a `KMeans<>` object, but you can change and modify the one that is held. So, for instance, if the `EmptyClusterPolicy` you were using stored some state, like, e.g., the maximum number of reclustering attempts or something, you could change that via modifying `kmeans.EmptyClusterAction()`, then calling `kmeans.Cluster()` again for different behavior. 👍

Sorry, I did not get your point. Could you give me an example to show how to change the parameter on a constructed object, e.g., change the `Metric()`?

**Comment by xlindo** [comment]
> You can't change the type of `EmptyClusterPolicy` once you have made a `KMeans<>` object, but you can change and modify the one that is held. So, for instance, if the `EmptyClusterPolicy` you were using stored some state, like, e.g., the maximum number of reclustering attempts or something, you could change that via modifying `kmeans.EmptyClusterAction()`, then calling `kmeans.Cluster()` again for different behavior. 👍

Sorry, I did not get your point. Could you give me an example to show how to change the parameter on an constructed object?

**Comment by rcurtin** [comment]
Of course, no problem... however, there are no `EmptyClusterPolicy` types that this functionality would be useful for.  So here is a new one that prints a string when it kills a cluster:

```
class KillEmptyClustersAndPrint
{
 public:
  KillEmptyClustersAndPrint(const std::string& str) : str(str) { }

  template<typename MetricType, typename MatType>
  void EmptyCluster(
      const MatType& data,
      const size_t emptyCluster,
      const arma::mat& oldCentroids,
      arma::mat& newCentroids,
      arma::Col<size_t>& clusterCounts,
      MetricType& metric,
      const size_t iteration)
  {
    std::cout << "Killing an empty cluster (" << emptyCluster << ")!  String: " << str << "\n";
    mlpack::kmeans::KillEmptyClusters::EmptyCluster(data, emptyCluster, oldCentroids, newCentroids, clusterCounts, metric, iteration);
  }

  std::string str;
}
```

Now, we can use this:

```
using namespace mlpack;
using namespace mlpack::kmeans;
using namespace mlpack::metric;

KillEmptyClustersAndPrint policy("hello");
KMeans<EuclideanDistance, SampleInitialization, KillEmptyClustersAndPrint> k(
    1000, EuclideanDistance(), SampleInitialization(), policy);

// The first run will print "hello" every time an empty cluster is killed.
arma::mat data(10, 10000, arma::fill::randu);
arma::mat centroids;
k.Cluster(data, 100, centroids);

// Now, let's change the string so it prints "goodbye".
k.EmptyClusterAction().str = "goodbye";
k.Cluster(data, 100, centroids);
```

Does that help?  This kind of functionality exists in several mlpack classes and it is provided for flexibility, for when a user provides a template class whose members they want to modify. :+1:

**Comment by xlindo** [comment]
> Of course, no problem... however, there are no `EmptyClusterPolicy` types that this functionality would be useful for. So here is a new one that prints a string when it kills a cluster:
> 
> ```
> class KillEmptyClustersAndPrint
> {
>  public:
>   KillEmptyClustersAndPrint(const std::string& str) : str(str) { }
> 
>   template<typename MetricType, typename MatType>
>   void EmptyCluster(
>       const MatType& data,
>       const size_t emptyCluster,
>       const arma::mat& oldCentroids,
>       arma::mat& newCentroids,
>       arma::Col<size_t>& clusterCounts,
>       MetricType& metric,
>       const size_t iteration)
>   {
>     std::cout << "Killing an empty cluster (" << emptyCluster << ")!  String: " << str << "\n";
>     mlpack::kmeans::KillEmptyClusters::EmptyCluster(data, emptyCluster, oldCentroids, newCentroids, clusterCounts, metric, iteration);
>   }
> 
>   std::string str;
> }
> ```
> 
> Now, we can use this:
> 
> ```
> using namespace mlpack;
> using namespace mlpack::kmeans;
> using namespace mlpack::metric;
> 
> KillEmptyClustersAndPrint policy("hello");
> KMeans<EuclideanDistance, SampleInitialization, KillEmptyClustersAndPrint> k(
>     1000, EuclideanDistance(), SampleInitialization(), policy);
> 
> // The first run will print "hello" every time an empty cluster is killed.
> arma::mat data(10, 10000, arma::fill::randu);
> arma::mat centroids;
> k.Cluster(data, 100, centroids);
> 
> // Now, let's change the string so it prints "goodbye".
> k.EmptyClusterAction().str = "goodbye";
> k.Cluster(data, 100, centroids);
> ```
> 
> Does that help? This kind of functionality exists in several mlpack classes and it is provided for flexibility, for when a user provides a template class whose members they want to modify. 👍

I see.
I was stuck in the modification for passing type.
So this means these setters are used for the modifications in the class (a determined type).
Thanks.

**Comment by rcurtin** [comment]
Yep, exactly!  The type is set at compile time via the template parameter.  But the actual instance can be modified at runtime. :+1:

**Comment by xlindo** [comment]
> Yep, exactly! The type is set at compile time via the template parameter. But the actual instance can be modified at runtime. 👍

Thanks.
This can be closed now.
