### ISSUE TITLE
Issues while executing mnist_vae_cnn example

### ISSUE THREAD

**Issue by yaro5** [mlpack/mlpack#2972]
I have a small issue while executing the example of convolutional VAE from "mlpack/examples/mnist_vae_cnn" (mnist_vae_cnn.cpp and vae_utils.hpp).

_Note: I have tried with other networks (MLP, a normal classification/regression CNN, even defining different architectures) and everything works fine._

I have compiled successfully the .cpp code from the example mlpack/examples/mnist_vae_cnn with mlpack 3.4.2 on Ubuntu 20.04.2 LTS. However, during execution it throws the following error: 

`Reading data ...
Training ...
Segmentation fault (core dumped)`

If I comment the line 

`std::cout << "Initial loss -> " << MeanTestLoss<MeanSModel>(vaeModel, train_test, 50) << std::endl;`

from the .cpp file, it throws the following error:

`Reading data ...
Training ...
error: addition: incompatible matrix dimensions: 0x0 and 14x14
terminate called after throwing an instance of 'std::logic_error'
  what():  addition: incompatible matrix dimensions: 0x0 and 14x14
Aborted (core dumped)`

I think it crashes at the Evaluate function, but no idea where is the origin and how to solve it.

My final goal is to implement an FCN with mlpack.

Any help or suggestion would be highly appreciated.

**Comment by shrit** [comment]
Hi @yaro5 thanks for opening the issue. 
We already have identified this issue, it is opened in the example repository [#84](https://github.com/mlpack/examples/issues/84).
I did not look into the code closely, but please feel free to open a pull request if you have any idea, or to identify the origin of the problem.

**Comment by shrit** [comment]
@yaro5, The issue has been solved in the master branch of `examples`, please download the latest version and let my know it is fine for you. I am closing this issue now. Thanks for opening it.

**Comment by yaro5** [comment]
@shrit thank you so much
