### ISSUE TITLE
How to construct an algorithm object at runtime?

### ISSUE THREAD

**Issue by xlindo** [mlpack/mlpack#2975]
For c++, there are always types for constructing an object.
Is there any way to construct an algorithm object based on input strings, which indicating the template parameters?

**Comment by shrit** [comment]
You would elaborate more on your question?
If you would like to see how mlpack algorithms are used, we have a set of examples in [example repository](https://github.com/mlpack/examples), a set of models in [model repository](https://github.com/mlpack/models).
if you did not find what you need, you can read the mlpack tests in the source code in `mlpack/src/tests`. Also, you can have a look at the mlpack CLI binding source code for a specific method. For instance, for a specific method, you can look at the source code, and see the `method_name_main.cpp

**Comment by xlindo** [comment]
> You would elaborate more on your question?
> 
> If you would like to see how mlpack algorithms are used, we have a set of examples in [example repository](https://github.com/mlpack/examples), a set of models in [model repository](https://github.com/mlpack/models).
> 
> if you did not find what you need, you can read the mlpack tests in the source code in `mlpack/src/tests`. Also, you can have a look at the mlpack CLI binding source code for a specific method. For instance, for a specific method, you can look at the source code, and see the `method_name_main.cpp

Once I want to construct an algorithm object, I need to indicate the template parameters.
But sometimes the template parameters are based on input, like reflection, e.g., "Euclidean" relates to `algo = new Algorithms<mlpack::metric::EuclideanDistance￼>()`. And this can hardly happen at runtime.
Is there any solution for this construction?

**Comment by zoq** [comment]
In this case you have to pre-define any possible options a user can select, this is what we do for some executables:

https://github.com/mlpack/mlpack/blob/66eecdc48d6c0c960fce18566d19ff27c6496116/src/mlpack/methods/kernel_pca/kernel_pca_main.cpp#L155-L183


is just one example.

**Comment by xlindo** [comment]
> In this case you have to pre-define any possible options a user can select, this is what we do for some executables:
> 
> https://github.com/mlpack/mlpack/blob/66eecdc48d6c0c960fce18566d19ff27c6496116/src/mlpack/methods/kernel_pca/kernel_pca_main.cpp#L155-L183
> 
> is just one example.

Thanks.

For example, if there is 
```cpp
template<typename A, typename B, typename C>
class Algo
{
};
```

If this means that I need pre-define A*B*C options for all possibilities?

**Comment by shrit** [comment]
You need to define `A, B, C` according to what you are using.

**Comment by xlindo** [comment]
> Yeah, unfortunately, to the best of my knowledge there is no way around this and you will have to manually create a mapping for each user string input to template type. However, it is possible to do better than an if statement with `A * B * C` cases; instead, you can do it with a total of `A + B + C` cases using helper functions like we do for the k-means binding:
> 
> https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/kmeans/kmeans_main.cpp#L215

Thanks, it seems to be a good example.

**Comment by xlindo** [comment]
> Yeah, unfortunately, to the best of my knowledge there is no way around this and you will have to manually create a mapping for each user string input to template type. However, it is possible to do better than an if statement with `A * B * C` cases; instead, you can do it with a total of `A + B + C` cases using helper functions like we do for the k-means binding:
> 
> https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/kmeans/kmeans_main.cpp#L215

Thanks.
This example seems to use RTTI to get the types for B and C. 
Can only RTTI solve this problem?

**Comment by xlindo** [comment]
> Yeah, unfortunately, to the best of my knowledge there is no way around this and you will have to manually create a mapping for each user string input to template type. However, it is possible to do better than an if statement with `A * B * C` cases; instead, you can do it with a total of `A + B + C` cases using helper functions like we do for the k-means binding:
> 
> https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/kmeans/kmeans_main.cpp#L215

Thanks for the good example, just got the point.
This issue could be closed now.

**Comment by rcurtin** [comment]
Awesome, happy to help. :+1:
