### ISSUE TITLE
There are some differences in the download version and git version

### ISSUE THREAD

**Issue by ICEJM1020** [mlpack/mlpack#2979]
#### Issue description

I'm a new developer using mlpack. So, I firstly download the zip from the WEB(https://mlpack.org/)), this is same as the github release version. When I using it, there are always error when I want to save a model. I found the error happened when using the boost serialization to serailize arma::Mat(both col and row). So, I search it a lot of times, and found that your team have faced this problem previously and write extern arma function. HOWEVER, I find the download version do not have the newest arma_extend, I think that is where the problem excutes. You should check if there are any other differences between download version and git version.
By the way, mlpack is very nice!!!

#### Your environment

 * version of mlpack: 3.4.2(both download release version and git code version I tried)
 * operating system: Windows10 20H2
 * compiler: MSVC14.1(VS2017)
 * version of dependencies (Boost/Armadillo): boost1.70, Armadillo10.2

**Comment by shrit** [comment]
@ICEJM1020 Thank you for opening your issue.
You would elaborate more on the issue that you are facing, maybe we can help you with it.
Currently, we are in the process of removing the boost library entirely. Therefore, you might find a difference between the release and the git master version. We have already removed boost::serialization and currently removing other parts of Boost too.
Hope that this answers your question.

**Comment by rcurtin** [comment]
Hey @ICEJM1020, to elaborate on what @shrit wrote, we haven't had a release in quite some time due to the refactoring that we are doing to remove Boost.  This means that mlpack version 3.4.2 is quite different than what is available in the git master branch.

Note that you can check out the `v3.4.2` tag if you want the git repository to reflect that version. :+1:
