### ISSUE TITLE
Utility methods for Decision Tree

### ISSUE THREAD

**Issue by RishabhGarg108** [mlpack/mlpack#2984]
### What is the desired addition or change?
Add some utility methods to the `DecisionTree` class (And `DecisionTreeRegressor` class once #2905 is merged). Some of the methods are:-
1. NumLeaves: Returns the number of leaves in the tree.
2. TreeDepth: Returns the maximum depth of the tree from the root node.
3. FeatureImportance: Returns an array that contains the importance of each feature.
4. DecisionPath: Given a point, return the path traversed from the root to the leaf for that point.

This list is merely indicative, not exhaustive. There might be some more utility functions that are equally important and I didn't mention. So, feel free to add to this list.

### What is the motivation for this feature?
To analyse the behaviour of trees, these utility methods come in very handy and are very frequently required. Having these methods will enhance our existing implementation.

### If applicable, describe how this feature would be implemented.
I have implemented `NumLeaves()` for `DecisionTreeRegressor` [here](https://github.com/RishabhGarg108/mlpack-1/blob/e05e8a266f4e70f8e3c43f5acb2f16a7a9c88854/src/mlpack/methods/decision_tree/decision_tree_regressor.hpp#L408). This can be used as a reference. Although, every method is different from others so implementations for each will be different. But one thing common to all is that we have to simply traverse the tree and collect the required information during traversal.

**Comment by ayushidoescoding** [comment]
I want to work on this.

**Comment by RishabhGarg108** [comment]
@ayushidoescoding, feel free to work on it :)

**Comment by ayushi2019031** [comment]
@RishabhGarg108  I wanted to confirm, so you have implemented the decision tree as per this PR (https://github.com/mlpack/mlpack/pull/2905), so should I contribute to this after
 the PR is merged?
 
 Thanks

**Comment by RishabhGarg108** [comment]
@ayushi2019031 At this moment, I would suggest that you can start with implementing any one of the above utilities in the `DecisionTree` class which we already have. The PR that I am working on is very volatile and It gets updated on a daily basis, so it will be a little tricky for you to work on it. Also, most of the utilities that we are talking about here are pretty generic and does not depend on whether the task is classification or regression. So, just pick something that you like and try it for the `DecisionTree` class.

Let me know if I can clarify anything else 👍

**Comment by ayushi2019031** [comment]
Okay thank you :) will start working on it now

**Comment by RishabhGarg108** [comment]
Found this https://arxiv.org/abs/1802.03888 paper for feature importance. Most of the libraries out there use this method.
