### ISSUE TITLE
When compiling C++ code with windows copy get 'updatePolicy': identifier not found

### ISSUE THREAD

**Issue by JackMBenson** [mlpack/mlpack#2987]
#### Issue description

I was completely unable to compile this until I edited the code int he q_learning.hpp header file. I removed the #if and #endif statements around line 167. Since that looked like it seemed to be the issue although I assume this will cause me some other problems down the line perhaps? Thought I'd mention the issue here though.
To be clear my file currently looks like this:

```
 //! Locally-stored updater.
  UpdaterType updater;

 typename UpdaterType::template Policy<arma::mat, arma::mat>* updatePolicy;

  //! Locally-stored reinforcement learning task.
  EnvironmentType environment;


```
#### Your environment

 * version of mlpack: The latest one (I couldn't find any other version information in the source files but I downloaded it yesterday or on the 17th of June 2021)
 * operating system: Windows 10
 * compiler: MSVC (visual studio 2019)
 * version of dependencies (Boost/Armadillo): boost is 1.76 and armadillo is 10.5.2
 * any other environment information you think is relevant: I installed ensmallen seperately through vcpkg

#### Steps to reproduce

No serious code was required, I just had this:
```
#include <mlpack/core.hpp>

#include <mlpack/methods/ann/init_rules/gaussian_init.hpp> // for gaussian initializa1tion
#include <mlpack/methods/reinforcement_learning/q_learning.hpp> // use Q learning
#include <mlpack/methods/reinforcement_learning/replay/random_replay.hpp> // use Replay memory
#include <mlpack/methods/reinforcement_learning/environment/cart_pole.hpp> // Environment Cart Pole
#include <mlpack/methods/reinforcement_learning/policy/greedy_policy.hpp> // Use greedy Policy
#include <mlpack/methods/reinforcement_learning/training_config.hpp> // To supply trainig config params
#include <mlpack/methods/ann/ffn.hpp> // for neural network 
#include <mlpack/methods/ann/layer/layer.hpp> // adding layer
#include <ensmallen.hpp> // updater (adam)
```

#### Expected behavior

You shouldn't have any issue compiling this I assume? When I editoed the line of code as mentioned above I didn't experience the issue anymore. Although did seem to get some warnings.

#### Actual behavior

and compiling that in visual studio 2019 - provided all the libs, dlls and include directories are in order - I expect you'd get the following error: 'updatePolicy': identifier not found.

**Comment by rcurtin** [comment]
Thanks for the report! I opened #2988 to fix the issue. You could work around the issue by including `ensmallen.hpp` before any of the mlpack headers. :+1:

**Comment by JackMBenson** [comment]
Oh, thanks that helps a lot.

**Comment by rcurtin** [comment]
#2988 is merged now, so the issue should be fixed.  Please feel free to open more issues if you have any! :+1:
