### ISSUE TITLE
SFINAE utility to check for template member functions.

### ISSUE THREAD

**Issue by RishabhGarg108** [mlpack/mlpack#3013]
### What is the desired addition or change?
With the SFINAE utilities which we have as of now, `HAS_MEM_FUNC` can only check for member functions that do not have templates. So, if we have something like:
```
class Foo
{
    template<typename T>
    void bar()
    {
        ...
    }
};
```

and we want to do a compile-time check if any class implements the function `bar()`, then the `HAS_MEM_FUNC` macro can't be used for it. So, it would be great to have a macro `HAS_TEMPLATE_MEM_FUNC` that can be used for this.

### What is the motivation for this feature?
I encountered a use case of it in #2905 and this might also be required in many places in future.

**Comment by jaskiratsingh2000** [comment]
Hey @zoq I am quite beginner and super interested to contribute towards this repo and this issue seems to be good but I am not sure that how to start with it. Can you please exactly let me know that what and where are the changes required?
I would be super grateful to your response. Thanks

**Comment by RishabhGarg108** [comment]
Hey @jaskiratsingh2000, mlpack uses SFINAE to do compile-time checks for checking if any class implements a member function of a particular form and many other checks. If you will take a look at `mlpack/core/util/sfinale_utility.hpp`, all the different macros used for these checks are defined there.

To solve this issue, you need to define another macro that can do the check described in the description of the issue.

The code there looks scary and I too don't understand how it's working. 😃 I would say start with looking at the existing macros and see how they are written and see a few places where they are used. Maybe it will help you to gain some understanding about it.

@rcurtin is our templates and template-metaprogramming expert. He might be able to clarify anything if you are stuck anywhere. :-)

**Comment by rcurtin** [comment]
Personally, I'm not sure if it's worth the effort to implement this until we actually need it, but I don't think it's a bad thing to add. :+1:
