### ISSUE TITLE
Change DecisionTree to DecisionTreeClassifier and similarly for other related classes.

### ISSUE THREAD

**Issue by RishabhGarg108** [mlpack/mlpack#3015]
The existing `DecisionTree` class in `methods/decision_tree/decision_tree.hpp` can only do classification. Once #3011 is merged, we will also have a `DecisionTreeRegressor`. So, to make it clearer we need to change that class to `DecisionTreeClassifier`.

The `DecisionTree` class is also used in `AdaBoost` and `RandomForest`. So, it makes sense to change them too to `AdaBoostClassifier` and `RandomForestClassifier`.

This will be a breaking change, but it won't be an issue because the next mlpack release will be a major release i.e. `mlpack 4.0`.

**Comment by Chandu-4444** [comment]
Hey @zoq, I think I can fix this. As far as I understood, the class names and all needs to be changed appropriately right? Correct me if I'm getting it wrong.

**Comment by RishabhGarg108** [comment]
@Chandu-4444 Correct! Make sure that you are updating the documentation too wherever required. Also, add a log in `HISTORY.md` stating the API change too 👍

**Comment by Chandu-4444** [comment]
Yeah, will do this.
