### ISSUE TITLE
Create BaseDecisionTree class to share code.

### ISSUE THREAD

**Issue by RishabhGarg108** [mlpack/mlpack#3016]
#3011 adds the `DecisionTreeRegressor`. This shares a lot of common code with the `DecisionTree` class. It is discussed in #2984 to add some utility methods and they are also common to both these classes. So, to avoid duplication of code, we can have a `BaseDecisionTree` class and the `DecisionTreeRegressor` and `DecisionTreeClassifier` can inherit from it.

**Caution:** These decision tree classes and their functions are called many times recursively in both training and prediction. So, we can't have any virtual function in the base class.

**Comment by rcurtin** [comment]
It's likely that code for creating children or doing prediction is quite duplicated in these two classes, and could be held in a base class.  But, @RishabhGarg108 is right, we should be careful to avoid `virtual` for this refactoring if the functions might be called repeatedly during training or prediction.
