### ISSUE TITLE
Question about the parameter checkInterval in Hoeffding Tree

### ISSUE THREAD

**Issue by DylanWangWQF** [mlpack/mlpack#3019]
Hi, I have a question about the parameter `checkInterval`. 
@rcurtin Sry for my noise.
```
// is Split
if (numSamples % checkInterval == 0)
```
What's the role of this param? We also don't pass the value from the command line.
Can we just replace it with the following check?
```
// is Split
if (numSamples > minSamples)
```

**Comment by rcurtin** [comment]
@DylanWangWQF no worries!  Happy to help.  You are right that we could do `if (numSamples > minSamples)`, but that means we would do the check for *every* sample we passed in.  That check does have some computational cost, so, we can choose to set `checkInterval` to, e.g., `10` if we want to only check to split every 10 samples.  That can make training a bit faster (but, of course, we check to see if the node should be split less often).

**Comment by DylanWangWQF** [comment]
@rcurtin 
Sry for the late reply!
I found that if we choose the small `checkInterval`, it will cause overfitting.
For example, for 5000 data samples with 5 features (assume all are categorical features with two values), if we choose `checkInterval =  60 or 100`, then we will get a complete binary tree, almost every path has 5 features (too many splits)

So could you give me some suggestions on choosing `checkInterval`? For example, 5000 samples for `checkInterval =  200`,  10000 samples for `checkInterval =  300 or more`?

**Comment by DylanWangWQF** [comment]
It seems that, with more and more data samples, the tree will be overfitting
