### ISSUE TITLE
Use AuxiliarySplitInfo to store all the split related info in DecisionTree and DecisionTreeRegressor.

### ISSUE THREAD

**Issue by RishabhGarg108** [mlpack/mlpack#3020]
### What is the desired addition or change?
Use the `NumericAuxiliarySplitInfo` and `CategoricalAuxiliarySplitInfo` to store all thee split related information rather than the data members like `classProbabilities` and `splitInfo`.

### What is the motivation for this feature?
The reason for this change is that right now we are using `classProbabilities` for storing the "split point" in `DecisionTree` which is a lot of wasted space for non-leaf nodes when we only need to store just one `size_t`. This will also give us the flexibility to store only the relevant information utilizing the least possible amount of space for any other splitting strategy in the future too.

### If applicable, describe how this feature would be implemented.

1. @rcurtin has written clearly the steps that need to be done [here](https://github.com/mlpack/mlpack/pull/2905#discussion_r653110795).
2. Another thing which we have to do here is to rename `AuxiliarySplitInfo` to `SplitInfo` because now it will store the actual split information rather than any supplementary split information.
3. Also, currently, the decision tree classes inherit from the `AuxiliarySplitInfo` classes. This is no longer required and we can simply store them as data members to simplify the implementation.

### Additional information?

To get the background information on this issue, you can read these [discussion 1](https://github.com/mlpack/mlpack/pull/2905#pullrequestreview-639317661), [discussion 2](https://github.com/mlpack/mlpack/pull/2905#discussion_r652263207), [discussion 3](https://github.com/mlpack/mlpack/pull/2905#discussion_r652266309). Disclaimer - These discussions are quite long. :)

**Comment by rcurtin** [comment]
This should help efficiency too, though it may be minor.  So we should do some timing simulations to double-check that when handling this issue. :)
