### ISSUE TITLE
New feature list for mlpack's parser

### ISSUE THREAD

**Issue by heisenbuug** [mlpack/mlpack#3024]
*  Handle quotes inside quotes
* `\tHello\t` and `Hello` are getting mapped differently.

Mlpack uses `DatasetMapper` class to handle non-numeric data.
But the current implementation doesn't handle `quotes` inside `quotes`

Example dataset
```
7,6,3,"This is a quoted string",4
3,4,8,"This is a quoted string",6
2,8,4,"This is "quotes" inside quotes",9
8,2,3,"This is, with a comma",3
```
Trying to load the above dataset gives this as output
```
[WARN ] LoadCSV::TransposeParse(): wrong number of dimensions (4) on line 2; should be 5 dimensions.
7 6 3 0 4
3 4 8 0 6
2 8 4 1 0
0 0 0 2 2
```

I even tried putting `\` before `"`
```
7,6,3,"This is a quoted string",4
3,4,8,"This is a quoted string",6
2,8,4,"This is \"quotes\" inside quotes",9
8,2,3,"This is, with a comma",3
```
But still the same error.

@rcurtin @zoq @shrit @conradsnicta I noticed this while I was removing `boost::spirit`.
Is this something that we need to cover? Are quoted quotes a valid entry in any `CSV` file?

**Comment by rcurtin** [comment]
Indeed, I think this is a bug.  I think there's no need to fix it during your GSoC project unless you have the extra bandwidth, but we should definitely fix it at some point. :+1:

**Comment by zoq** [comment]
I'm not sure I have seen a dataset that uses quotes, so I don't think there is a huge priority to support that, nevertheless if you see an easy solution to support quotes, go for it.
