### ISSUE TITLE
MLpack library issue - undefined reference to mlpack::*

### ISSUE THREAD

**Issue by rickarl** [mlpack/mlpack#3069]
### Issue description
When trying to compile sample mlpack code, for example covariance [here](https://mlpack.org/doc/mlpack-3.3.1/doxygen/sample.html), I am getting a lot of errors regarding 'undefined reference'. This affects mlpack::data, mlpack::log, mlpack::util, and probably more. From googling the errors I've found that the issue seems to plausibly be related to library linking. The closest issue to the one I am experiencing is this one: https://github.com/mlpack/mlpack/issues/2709

However, the various solutions and ideas presented in that link has not been able to solve it for me, so I am making a new issue. I am using CMake to build my files so CMake controls my compile options.

### Details
OS: Fedora 34
C compiler: g++ (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)

CMakeLists looks like [this](https://controlc.com/332a62dd)
Error output: https://controlc.com/41ddc96e
main.cpp is a literal copy of any sample mlpack code such as the one linked above.

### Further explanation
As you can see from the output, CMake cannot find any of the methods defined in mlpack.

For code, it's a copy paste of various samples like the ones above. I have tried various versions of includes and compile options in CMakeLists already.

When browsing my main.cpp file in VSC, it has no problem finding the HPP file for the various methods used such as Load, Save, etc.

libmlpack.so was installed in usr/local/lib64 by default, rather than usr/local/lib.
However, if I run export LD_LIBRARY_PATH="/usr/local/lib64/:$LD_LIBRARY_PATH", I can run for example mlpack_knn -h without getting a library link error.

I have checked that I don't have multiple installs of mlpack installed, as suggested in the issue linked above which apparently was the problem there.

If I try to compile main directly through g++, I instead get this error:
```
$: g++ main.cpp -o main -std=c++11 -Wall -Wextra -O3 -DNDEBUG -fopenmp -lmlpack 
/usr/bin/ld: /tmp/ccJDvi4v.o: undefined reference to symbol 'arma_H5Sclose'
/usr/bin/ld: /usr/lib64/libarmadillo.so.10: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

I have checked Armadillo is installed, I believe I installed it with package manager and not by building from source.

**Comment by shrit** [comment]
@rickarl For CMake: `-lmlpack` is not a compiler option. You should add the path of the mlpack library in `target_link_library`.
Also, you should mention in g++ `-larmadillo`. You need to add the path for the armadillo library in `target_link_library`.
Here is a link for `Makefile` example:
https://github.com/mlpack/examples/blob/master/mnist_cnn/Makefile

As you can see we are linking to armadillo and mlpack
Let me know if the issue persists.

**Comment by rickarl** [comment]
Thanks for the help, adding these to target_link_library seems to have solved the problem! I have not worked a lot with C++ or CMake before so I was unsure of how to setup the CMakeLists file.
