### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by zoq** [mlpack/mlpack#3072]
Hacktoberfest (https://hacktoberfest.digitalocean.com/) is an event hosted by DigitalOcean that partners with many organizations. In the past years, we had some contributions that indirectly came through the Hacktoberfest program.

Due to some concerns (https://blog.domenic.me/hacktoberfest/), each project has to opt-in to participate in the program. So I was wondering if anybody likes mlpack to participate, in this case we have to add a topic to the repo, or likes to stay away from the program.

**Comment by rcurtin** [comment]
At least personally I wasn't planning on getting a t-shirt from it (I already have too many GSoC shirts :smiley:).  Given the spam concerns, maybe it's best to see if someone in our community wants to participate and sign up then?  I don't think we got hit with spam nearly as badly as some of the most-affected organizations in previous years, so at least personally I don't think it's a problem to sign up if anyone here wants a shirt for their efforts. :)

But, it probably doesn't make sense to sign up unless someone here does explicitly want to participate.
