### ISSUE TITLE
Is there a metric code that can calculate roc_auc score?

### ISSUE THREAD

**Issue by ingbeeedd** [mlpack/mlpack#3074]
It's hard to find even if you look at doxygen.

**Comment by rcurtin** [comment]
Hey @ingbeeedd, sorry that things are hard to find. You are right that Doxygen isn't great for discovering what's available---it's not the best interface, but sometimes just searching the filenames in the codebase can be useful.

Metrics like ROC-AUC would be found here: https://github.com/mlpack/mlpack/tree/master/src/mlpack/core/cv/metrics

But, it looks like we currently don't have ROC-AUC implemented.  Sorry about that!  If you write an implementation, we'd be glad to review and merge it, or, maybe someone else in the community would be interested in writing one.

**Comment by rcurtin** [comment]
Definitely, feel free @srimadhan11.  Take a look at the existing metrics, and if you can match the API/design of those, then it should be an easy merge. :+1:

**Comment by SuvarshaChennareddy** [comment]
I would like to tackle this if @srimadhan11 is not currently working on it. 
However I do have one question; will this ROC_AUC metric implementation need to provide anything other than the Area Under the Receiver Operating Characteristic Curve (ROC AUC)?

**Comment by srimadhan11** [comment]
Hi @SuvarshaChennareddy, I am already working on this issue. If I couldn't submit PR within 3-4 days, then you please proceed with this issue.
