### ISSUE TITLE
Issue with training while using openCV

### ISSUE THREAD

**Issue by rickarl** [mlpack/mlpack#3077]
Having an issue with mlpack giving Floating point exception during training if I include openCV in my CMake, which I can't make heads or tail of.

To be precise, I have an older commit where everything works fine. I want to do some image resizing during preprocessing and install openCV. The next commit which results in the exception only has changes in CMakeLists.txt, adding the openCV library - not a single line of actual code using openCV is added, nor any library includes for it. All the changes:
![image](https://user-images.githubusercontent.com/76155230/137631073-b2f1d23f-8c47-4a30-9655-ee2a2be62466.png)

I have already ruled out the CURL include change. The exception disappears if I comment out $(OpenCV_LIBS) under target_link_libraries, so clearly that is the issue. OpenCV itself works fine if I use it - I can add and run code for resizing the images in my dataset and they are properly resized and everything. But once it starts training, whether I use openCV to resize or not, I get the floating point exception.

I have no idea why linking openCV makes MLPack training break down, and I'm wondering if anyone has any ideas here?

**Comment by zoq** [comment]
Do you see the issue already after the first iteration (training). Any chance you can share the model?

**Comment by shrit** [comment]
@sindre0830 Do you have anything related to the exception so we can see it? can you show us the error? would it be possible to have a GDB backtrace related to this issue?

**Comment by shrit** [comment]
Also, would you share with us the version of mlpack and the dependencies?
