### ISSUE TITLE
Compilation issue with linear_svm when MatType is not arma::mat

### ISSUE THREAD

**Issue by skyser2003** [mlpack/mlpack#3083]
#### Issue description

LinearSVM<MatType>::Shuffle function uses arma::mat to create variable `newData`,
which I think should be type `MatType` instead.

#### Your environment

 * version of mlpack: 3.4.2
 * operating system: Ubuntu 20.4
 * compiler: g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
 * version of dependencies (Boost/Armadillo): Default
 * any other environment information you think is relevant:

#### Steps to reproduce

Sample code:
```
arma::Mat<int> train_data;
StandardSGD optimizer;

LinearSVM<decltype(train_data)> svm;
svm.Train(train_data, labels, 2, optimizer);
```

Error message:
```
/usr/local/include/mlpack/methods/linear_svm/linear_svm_function_impl.hpp:118:13: error: conversion from ‘arma::subview_elem2<int, arma::Mat<long long unsigned int>, arma::Mat<long long unsigned int> >’ to non-scalar type ‘arma::mat’ {aka ‘arma::Mat<double>’} requested
  118 |   arma::mat newData = dataset.cols(ordering);
      |             ^~~~~~~
/usr/local/include/mlpack/methods/linear_svm/linear_svm_function_impl.hpp:120:11: error: no match for ‘operator=’ (operand types are ‘arma::Mat<int>’ and ‘std::remove_reference<arma::Mat<double>&>::type’ {aka ‘arma::Mat<double>’})
  120 |   dataset = std::move(newData);
      |   ~~~~~~~~^~~~~~~~~~~~~~~~~~~~
```

If you look here,
https://github.com/mlpack/mlpack/blob/3.4.2/src/mlpack/methods/linear_svm/linear_svm_function_impl.hpp#L118

```
// Re-sort data.
arma::mat newData = dataset.cols(ordering);
math::ClearAlias(dataset);
dataset = std::move(newData);
```

https://github.com/mlpack/mlpack/blob/3.4.2/src/mlpack/methods/linear_svm/linear_svm_function.hpp#L189
```
//! The datapoints for training.
MatType dataset;
```

`newData` is created from `LinearSVD<MatType>::dataset`,
whose default type is `MatType` which defaults to `arma::mat`( = `arma::Mat<double>`).
But `MatType` can be changed to `arma::Mat<int>`, `arma::Mat<float>`, etc any other numeric types.

So I guess type of `newData` should be `MatType`, not `arma::mat`.

**Comment by shrit** [comment]
@skyser2003 I see the issue, would you open a pull request to fix this bug?

**Comment by skyser2003** [comment]
https://github.com/mlpack/mlpack/pull/3084
Created it.

**Comment by shrit** [comment]
@skyser2003 #3084 has been merged I am closing this one, please feel free to re-open this issue if anything came up.
