### ISSUE TITLE
Building from source on Mac m1, 'omp.h' not found

### ISSUE THREAD

**Issue by proton991** [mlpack/mlpack#3085]
```
/Users/cuixinyu/Coding/c++/mlpack/build/deps/armadillo-10.3.0/include/armadillo:70:12: fatal error: 'omp.h' file not found
  #include <omp.h>
           ^~~~~~~
1 error generated.
CMake Error at /Users/cuixinyu/Coding/c++/mlpack/CMake/cotire.cmake:1885 (message):
  cotire: error 1 precompiling
  /Users/cuixinyu/Coding/c++/mlpack/build/src/mlpack/cotire/mlpack_CXX_prefix.hxx.
Call Stack (most recent call first):
  /Users/cuixinyu/Coding/c++/mlpack/CMake/cotire.cmake:3558 (cotire_precompile_prefix_header)

```

**Comment by rcurtin** [comment]
Hi @proton991, do you have OpenMP installed?

Can you tell us more about your setup?  What was the output of CMake?  What are the system details?

(This is why the issue template is there, by the way. :))

**Comment by zafar-hussain** [comment]
hi proton991,
-- do a "locate omp.h", and and make sure it is in the include path,
if not found, remove/reinstall the compiler with  recommended option.

if all else fails, pass USE_OPENMP=OFF to cmake, to build without openmp and then sort out the omp.h issue


cheers

**Comment by Sirish07** [comment]
I faced a similar issue. You can try `brew install libomp` (if it is not installed) to resolve the issue.
