### ISSUE TITLE
mlpack "Make" filed on Ubuntu

### ISSUE THREAD

**Issue by jingchen95** [mlpack/mlpack#3100]
Hi, does anyone have any idea of what happened here? I can't make it. Please help~ Many thanks!
I have hdf5 installed: usr/lib/aarch64-linux-gnu/hdf5/serial/libhdf5.so

nvidia@tegra-ubuntu:~/mlpack-3.4.2/build$ make
[  0%] Updating arma_config.hpp (if necessary)
[  0%] Built target mlpack_arma_config
Moving header files to include/mlpack/
[  0%] Built target mlpack_headers
[  1%] Generating mlpack.pc (pkg-config) file.
[  1%] Built target pkgconfig
[ 18%] Built target mlpack
[ 18%] Linking CXX executable ../../../../bin/mlpack_adaboost
CMakeFiles/mlpack_adaboost.dir/adaboost_main.cpp.o: In function `long arma::hdf5_misc::get_hdf5_type<unsigned long>()':
/usr/include/armadillo_bits/hdf5_misc.hpp:105: undefined reference to `arma_H5T_NATIVE_ULONG'
/usr/include/armadillo_bits/hdf5_misc.hpp:105: undefined reference to `arma_H5T_NATIVE_ULONG'
/usr/include/armadillo_bits/hdf5_misc.hpp:105: undefined reference to `arma_H5Tcopy'
CMakeFiles/mlpack_adaboost.dir/adaboost_main.cpp.o: In function `long arma::hdf5_misc::get_hdf5_type<double>()':
/usr/include/armadillo_bits/hdf5_misc.hpp:137: undefined reference to `arma_H5T_NATIVE_DOUBLE'
/usr/include/armadillo_bits/hdf5_misc.hpp:137: undefined reference to `arma_H5T_NATIVE_DOUBLE'
/usr/include/armadillo_bits/hdf5_misc.hpp:137: undefined reference to `arma_H5Tcopy'
CMakeFiles/mlpack_adaboost.dir/adaboost_main.cpp.o: In function `arma::hdf5_misc::hdf5_suspend_printing_errors::hdf5_suspend_printing_errors()':
/usr/include/armadillo_bits/hdf5_misc.hpp:750: undefined reference to `arma_H5Eget_auto'
/usr/include/armadillo_bits/hdf5_misc.hpp:753: undefined reference to `arma_H5Eset_auto'
CMakeFiles/mlpack_adaboost.dir/adaboost_main.cpp.o: In function `arma::hdf5_misc::hdf5_suspend_printing_errors::~hdf5_suspend_printing_errors()':
/usr/include/armadillo_bits/hdf5_misc.hpp:759: undefined reference to `arma_H5Eset_auto'
CMakeFiles/mlpack_adaboost.dir/adaboost_main.cpp.o: In function `bool arma::diskio::save_hdf5_binary<double>(arma::Mat<double> const&, arma::hdf5_name const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
/usr/include/armadillo_bits/diskio_meat.hpp:1178: undefined reference to `arma_H5Fis_hdf5'
/usr/include/armadillo_bits/diskio_meat.hpp:1183: undefined reference to `arma::H5check_version(unsigned int, unsigned int, unsigned int)'
/usr/include/armadillo_bits/diskio_meat.hpp:1183: undefined reference to `arma::H5open()'
/usr/include/armadillo_bits/diskio_meat.hpp:1183: undefined reference to `arma_H5Fopen'
/usr/include/armadillo_bits/diskio_meat.hpp:1183: undefined reference to `arma::H5check_version(unsigned int, unsigned int, unsigned int)'
/usr/include/armadillo_bits/diskio_meat.hpp:1183: undefined reference to `arma::H5open()'
/usr/include/armadillo_bits/diskio_meat.hpp:1183: undefined reference to `arma_H5Fcreate'
/usr/include/armadillo_bits/diskio_meat.hpp:1192: undefined reference to `arma_H5Screate_simple'
/usr/include/armadillo_bits/diskio_meat.hpp:1210: undefined reference to `arma_H5Gcreate'
/usr/include/armadillo_bits/diskio_meat.hpp:1214: undefined reference to `arma_H5Gopen'
/usr/include/armadillo_bits/diskio_meat.hpp:1229: undefined reference to `arma_H5Ldelete'
/usr/include/armadillo_bits/diskio_meat.hpp:1236: undefined reference to `arma_H5Dcreate'
/usr/include/armadillo_bits/diskio_meat.hpp:1246: undefined reference to `arma_H5Dwrite'
/usr/include/armadillo_bits/diskio_meat.hpp:1248: undefined reference to `arma_H5Dclose'
/usr/include/armadillo_bits/diskio_meat.hpp:1251: undefined reference to `arma_H5Tclose'
/usr/include/armadillo_bits/diskio_meat.hpp:1252: undefined reference to `arma_H5Sclose'
/usr/include/armadillo_bits/diskio_meat.hpp:1253: undefined reference to `arma_H5Gclose'
/usr/include/armadillo_bits/diskio_meat.hpp:1254: undefined reference to `arma_H5Fclose'
CMakeFiles/mlpack_adaboost.dir/adaboost_main.cpp.o: In function `bool arma::diskio::save_hdf5_binary<unsigned long>(arma::Mat<unsigned long> const&, arma::hdf5_name const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
/usr/include/armadillo_bits/diskio_meat.hpp:1178: undefined reference to `arma_H5Fis_hdf5'
/usr/include/armadillo_bits/diskio_meat.hpp:1183: undefined reference to `arma::H5check_version(unsigned int, unsigned int, unsigned int)'
/usr/include/armadillo_bits/diskio_meat.hpp:1183: undefined reference to `arma::H5open()'
/usr/include/armadillo_bits/diskio_meat.hpp:1183: undefined reference to `arma_H5Fopen'
/usr/include/armadillo_bits/diskio_meat.hpp:1183: undefined reference to `arma::H5check_version(unsigned int, unsigned int, unsigned int)'
/usr/include/armadillo_bits/diskio_meat.hpp:1183: undefined reference to `arma::H5open()'
/usr/include/armadillo_bits/diskio_meat.hpp:1183: undefined reference to `arma_H5Fcreate'
/usr/include/armadillo_bits/diskio_meat.hpp:1192: undefined reference to `arma_H5Screate_simple'
/usr/include/armadillo_bits/diskio_meat.hpp:1210: undefined reference to `arma_H5Gcreate'
/usr/include/armadillo_bits/diskio_meat.hpp:1214: undefined reference to `arma_H5Gopen'
/usr/include/armadillo_bits/diskio_meat.hpp:1229: undefined reference to `arma_H5Ldelete'
/usr/include/armadillo_bits/diskio_meat.hpp:1236: undefined reference to `arma_H5Dcreate'
/usr/include/armadillo_bits/diskio_meat.hpp:1246: undefined reference to `arma_H5Dwrite'
/usr/include/armadillo_bits/diskio_meat.hpp:1248: undefined reference to `arma_H5Dclose'
/usr/include/armadillo_bits/diskio_meat.hpp:1251: undefined reference to `arma_H5Tclose'
/usr/include/armadillo_bits/diskio_meat.hpp:1252: undefined reference to `arma_H5Sclose'
/usr/include/armadillo_bits/diskio_meat.hpp:1253: undefined reference to `arma_H5Gclose'
/usr/include/armadillo_bits/diskio_meat.hpp:1254: undefined reference to `arma_H5Fclose'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dpocon_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgbcon_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dsyrk_'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5Tequal'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5Tcreate'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dlangb_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgesdd_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dlange_'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5T_NATIVE_LONG'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgetrs_'
../../../../lib/libmlpack.so.3.4: undefined reference to `TLS init function for arma::mt19937_64_instance'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5Sget_simple_extent_dims'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgemm_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_ilaenv_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgels_'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5Ovisit'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5T_NATIVE_INT'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5T_NATIVE_USHORT'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dpbtrf_'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5T_NATIVE_ULLONG'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5Dopen'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgemv_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgesvd_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgesvx_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dasum_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dnrm2_'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma::mt19937_64_instance'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5Sget_simple_extent_ndims'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dtrtrs_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgtsv_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgelsd_'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5T_NATIVE_FLOAT'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dorgqr_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dpotrf_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dtrcon_'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5T_NATIVE_CHAR'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgbsv_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dsyev_'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5Tinsert'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgbsvx_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgeqrf_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgetrf_'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5Dget_type'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgetri_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dpotri_'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5T_NATIVE_LLONG'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dsyevd_'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5Dread'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dpotrs_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgecon_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgbtrf_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgbtrs_'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5Dget_space'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dtrtri_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dposv_'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5T_NATIVE_UINT'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dlansy_'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5T_NATIVE_SHORT'
../../../../lib/libmlpack.so.3.4: undefined reference to `arma_H5T_NATIVE_UCHAR'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dgesv_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_dposvx_'
../../../../lib/libmlpack.so.3.4: undefined reference to `wrapper2_ddot_'
collect2: error: ld returned 1 exit status
src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/build.make:113: recipe for target 'bin/mlpack_adaboost' failed
make[2]: *** [bin/mlpack_adaboost] Error 1
CMakeFiles/Makefile2:2604: recipe for target 'src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/all' failed
make[1]: *** [src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jingchen95** [comment]
Problem solved by "make -stdlib=libstdc++"

**Comment by swaingotnochill** [comment]
Closing this issue.
