### ISSUE TITLE
Can't get mlpack to build

### ISSUE THREAD

**Issue by BrendaMMaloff** [mlpack/mlpack#3102]
I'm trying to get mlpack installed and compiled and I'm having issues. I'm on a Windows machine. If I use the vcpkg command, I get the error "Error: mlpack[core] is only supported on 'uwp'". If I try to build each piece separately, I get all of the way down until the mlpack, when I try to use the cmake command, I get the error "CMake Error at CMakeLists.txt:70 (cotire): Unknown CMake command "cotire"."

I'm very new to all of this, so please let me know if I'm missing something or if there is something else I need to do first to make this work.

**Comment by RabbleRousy** [comment]
I also had this issue when building but can't quite remember how I continued...
I definetly stumbled upon this issue [#21310](https://github.com/microsoft/vcpkg/issues/21310) and maybe changing `uwp `to `!uwp` as described there fixed it for me, but not sure.

**Comment by shrit** [comment]
@BrendaMMaloff what version of mlpack you are using?

**Comment by BrendaMMaloff** [comment]
Mlpack 3.4.1. I believe that is the latest version. Is there I version I should be using?

  Brenda

**Comment by shrit** [comment]
This one is pretty old, we did not do any release in the last year because we are preparing in mlpack 4 in a couple of months.
Would you mind building the master version?

**Comment by BrendaMMaloff** [comment]
I don't know vcpkg that well.  I can pull the code from git, but how to I tell vcpkg to use that particular version then?

**Comment by BrendaMMaloff** [comment]
I got it building now.
