### ISSUE TITLE
Quick question: where did the optimization classes go?

### ISSUE THREAD

**Issue by RabbleRousy** [mlpack/mlpack#3104]
I am sorry for this stupid question, but I can't find the optimizer classes (in particular I want to use [`GradientDescent`](https://www.mlpack.org/doc/mlpack-3.0.4/doxygen/classmlpack_1_1optimization_1_1GradientDescent.html) optimizer). In the documentation they are listed under `mlpack/core/optimizations`, but I simply do not see that folder anywhere? Not in this repository, nor in my local mlpack directory... Where do I find these classes to include them in my code?

**Comment by RabbleRousy** [comment]
Just found it in the 3.x branch, I guess I built the wrong version..?

**Comment by shrit** [comment]
@RabbleRousy The optimizer class is part now of the ensmallen library see here: https://github.com/mlpack/ensmallen

**Comment by RabbleRousy** [comment]
Okay, so I need to also build & include ensmallen into my project, right? Thanks a lot!

**Comment by shrit** [comment]
Ensmallen is header-only, so there is nothing to build. You only need to include headers and compile mlpack code as usual

We have all classes functions, and optimizers from mlpack to ensmallen which is dedicated to mathematical optimization. If you would like to see how to use ensmallen with mlpack please refer to the example repository that can be found here: 
https://github.com/mlpack/exmaples

**Comment by RabbleRousy** [comment]
Alright, that'll do! Thanks a lot!!:)
