### ISSUE TITLE
Model()[x].Parameters() not available anymore

### ISSUE THREAD

**Issue by RabbleRousy** [mlpack/mlpack#3108]
#### Problem location

https://mlpack.org/doc/mlpack-3.1.0/doxygen/anntutorial.html#extracting_parameters_anntut

#### Description of problem

Tutorial says: 

`model.Model()[1].Parameters();`
In the example above, we get the weights of the second layer.

But `Model()[x]` returns a `LayerTypes<>` object which doesn't give me the function `Parameters()`. Maybe I am missing something.

**Comment by hello-fri-end** [comment]
Hi! I think you need you need to use boost visitor to get the weights of a specific layer. Try this:

```
arma::mat parametersX;
boost::apply_visitor(ParametersVisitor(parametersX),model.Model()([x]);
```

**Comment by RabbleRousy** [comment]
Thanks a lot, that approach worked! I guess the documentation should be updated nontheless, should this issue stay open?

**Comment by rcurtin** [comment]
I opened #3122 with a quick documentation fix here.  Thanks for pointing it out @RabbleRousy! :+1:

**Comment by rcurtin** [comment]
With #3122 merged, I think we can go ahead and close this. :+1:
