### ISSUE TITLE
How to properly use custom classes with mlpack?

### ISSUE THREAD

**Issue by RabbleRousy** [mlpack/mlpack#3109]
Hello again! 
I wrote 2 classes:
[`ClippedRectifierFunction`](https://gitlab.fsi.hochschule-trier.de/hetzers/chess/-/blob/master/ClippedReLU.hpp) by copying and modifying `rectifier_function.hpp`
and
[`LinearSplit`](https://gitlab.fsi.hochschule-trier.de/hetzers/chess/-/blob/master/LinearSplit_impl.hpp) by copying and modifiying `linear.hpp` and `linear_impl.hpp` (see [this issue](https://github.com/mlpack/mlpack/issues/3103) for why I need those layers).

**I would like to know if there is a way to use these classes in my project without editing mlpack source files.**

If I _do not_ add either of the two new classes to `layer_types.hpp` like this:

    template <typename InputDataType,
    typename OutputDataType, typename RegularizerType>
    class LinearSplit;

    // other declarations

    template <typename... CustomLayers>
    using LayerTypes = boost::variant<
        // other layers...
        BaseLayer<ClippedRectifierFunction, arma::mat, arma::mat>*,
        // other layers...
        LinearSplit<arma::mat, arma::mat, NoRegularizer>*,
        // other layers...
    >;
I get the following error:

    ffn.hpp(290,1): error C2664:
    'void std::vector<boost::variant< ... >>::push_back(const _Ty &)':
    cannot convert argument 1 from 'LayerType *' to 'const _Ty &'

Which seems logical to me, as I did not declare the new classes as valid LayerTypes. But when I try to add BOTH to the list like above, I get another error:

    make_variant_list.hpp(40,1): error C2977:
    'boost::mpl::list': too many template arguments

Which confirms my suspicion that modifying these source files is probably the wrong approach to begin with (because this would also cause my project to only run on my "version" of mlpack, making it unsharable). But how else can I make these custom classes work together with mlpack?

Thanks in advance!

**Comment by RabbleRousy** [comment]
### Update
After going through the documentation again I think I figured it out. I can use custom layers by adding them as the template parameter to LayerTypes upon network initialization ... ?
So this should do the trick:

    mlpack::ann::FFN<mlpack::ann::MeanSquaredError<>, mlpack::ann::RandomInitialization,
    mlpack::ann::LinearSplit<>, mlpack::ann::BaseLayer<mlpack::ann::ClippedRectifierFunction>> network;

But once I add either of the two layers, my program won't compile anymore, giving me `fatal error c1060: compiler is out of heap space`. I tried various possible solutions like `/Zm` option, but none worked...

### Questions

1. What causes the compiler issue and how do I fix it?
2. Is this approach to adding the custom layers correct?

**Comment by Aakash-kaushik** [comment]
Hey, so the error which tells you that thete are too many template arguments is because boost restrictions max number of templates to 50.
I think in layer types you can see we use more layer types and that is then passed to layer types.
You can add your two layers two more layer types and that should work.

**Comment by Aakash-kaushik** [comment]
Add your extra layers here: https://github.com/mlpack/mlpack/blob/802b6826b26f65abdf8436e22f94d503066ff908/src/mlpack/methods/ann/layer/layer_types.hpp#L229

**Comment by RabbleRousy** [comment]
> Hey, so the error which tells you that there are too many template arguments is because boost restrictions max number of templates to 50(i think).

Ok, great to know that this is the cause of the compiler error (will check tomorrow).

> Add your extra layers here:
> 
> https://github.com/mlpack/mlpack/blob/802b6826b26f65abdf8436e22f94d503066ff908/src/mlpack/methods/ann/layer/layer_types.hpp#L229

But that would still mean modifying the library code, is there no way to include custom layers without changing internal code?

**Comment by Aakash-kaushik** [comment]
@RabbleRousy i am not sure if there is one when you add any layer it expects to be of type `LayerType` and when you don't have your custom layers it might not have any layer to pass your argument to.
But i can totally be wrong here, someone else might have a better idea and understanding.

**Comment by RabbleRousy** [comment]
> Add your extra layers here:
> 
> https://github.com/mlpack/mlpack/blob/802b6826b26f65abdf8436e22f94d503066ff908/src/mlpack/methods/ann/layer/layer_types.hpp#L229

This does not fix the compiler issue (I guess because it's just nesting more template arguments within `MoreTypes`...)

Anyways, just exchanging some of the layers from `MoreTypes` which I don't use anways with my custom ones works. But as I have said, I would really like to find a way to use them **without** editing mlpack files.
### Can anyone help??

**Comment by rcurtin** [comment]
I think you should be able to use the `CustomLayers` template type for the `FFN` class.  So, for instance, you might write, e.g.,

```c++
FFN<NegativeLogLikelihood<>, RandomInitialization, ClippedRectifierFunction, LinearSplit> network;
```

and then you can add a `ClippedRectifierFunction` or `LinearSplit` layer to `network`.  If I am not mistaken, this should work.

However, it's also worth pointing out that we are currently in the process of refactoring the neural network code to use inheritance instead of `boost::visitor`.  This should significantly ease compilation time and memory concerns, and also it means that all you would have to do is inherit from a base layer class to make a custom layer.

**Comment by RabbleRousy** [comment]
Hi @rcurtin , thanks for your answer!
Unfortunately, I already tried that and get a compiler error (according to @Aakash-kaushik because there are to many template arguments):



> ### Update
> After going through the documentation again I think I figured it out. I can use custom layers by adding them as the template parameter to LayerTypes upon network initialization ... ? So this should do the trick:
> 
> ```
> mlpack::ann::FFN<mlpack::ann::MeanSquaredError<>, mlpack::ann::RandomInitialization,
> mlpack::ann::LinearSplit<>, mlpack::ann::BaseLayer<mlpack::ann::ClippedRectifierFunction>> network;
> ```
> 
> But once I add either of the two layers, my program won't compile anymore, giving me `fatal error c1060: compiler is out of heap space`. I tried various possible solutions like `/Zm` option, but none worked...
> 
> ### Questions
> 1. What causes the compiler issue and how do I fix it?
> 2. Is this approach to adding the custom layers correct?

So if you are familiar with that error or have any idea how to solve it, I would be really thankful!

> However, it's also worth pointing out that we are currently in the process of refactoring the neural network code to use inheritance instead of `boost::visitor`. This should significantly ease compilation time and memory concerns, and also it means that all you would have to do is inherit from a base layer class to make a custom layer.

That's great to hear, as that also was my first intuitive approach when trying to write custom layers!

**Comment by rcurtin** [comment]
Crap, sorry!  I overlooked that response.  A `C1060` means that the system is out of RAM, and unfortunately I don't think there are many tricks to work around that.  Problems like that are exactly why we are trying to move away from `boost::visitor`. :)  If you have some way to increase the available RAM, that could help, but I don't know of any other way...

**Comment by RabbleRousy** [comment]
Yeah I tried some ways to increase RAM but found none that worked for me. Anyways, I found a workaround by just replacing some of the `MoreTypes` Layers with my custom ones. Kinda ugly solution because it modifies library code, but I'll stick with it for now. Good to hear there is a better solution on it's way. Closing this now :)
