### ISSUE TITLE
Documentation for setting PATH variables for Python bindings in incomplete

### ISSUE THREAD

**Issue by dnabanita7** [mlpack/mlpack#3117]
#### Problem location
[This quickstart documentation for Python bindings for mlpack seems incomplete.](https://www.mlpack.org/doc/mlpack-3.4.2/doxygen/python_quickstart.html)

#### Description of problem

After following the steps to build mlpack from the source, not only the LD_LIBRARY_PATH should be added to PATH but also the python bindings path. I got a module not found error while defining mlpack in my python example. 
So, a ``PYTHONPATH=/path/to/build/src/mlpack/python`` should be added.

Second issue is ``pip install mlpack`` as well ``pip3 install mlpack`` or ``pip3 install mlpack-3.4.2`` gives an error of 
```
ERROR: Could not find a version that satisfies the requirement mlpack-3.4.2
ERROR: No matching distribution found for mlpack-3.4.2
```

**Comment by zoq** [comment]
I can't reproduce the pip issue, at least on my system (4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux) it works just fine. Can you tell us some more information about your system? I guess you are running Linux as well?

About the `PYTHONPATH` did you run `install` after the build step? The `PYTHONPATH` should be set in the install phase, If you skip that phase you have to set it as you mentioned, which is also mentioned in https://www.mlpack.org/doc/mlpack-git/doxygen/build.html see "Using mlpack without installing" section.

**Comment by dnabanita7** [comment]
I made a build and ran ``sudo make install`` but clearly somehow I had to set it by myself. 
Yes, I use Linux too. ``Linux naba-Predator-PH315-53 5.11.0-41-generic #45-Ubuntu SMP Fri Nov 5 11:37:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux``.  I think I don't have a PPA for it.

**Comment by dnabanita7** [comment]
I see, ``FindBoost`` is not getting the new version of ``Boost`` that is why I am getting an error
```
CMake Warning at /usr/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:442 (find_package)
```
which is not building anything.

**Comment by dnabanita7** [comment]
The issue was with my cmake version. I upgraded it. But still getting some issues with the build. 
[CMakeError.log](https://github.com/mlpack/mlpack/files/7798679/CMakeError.log)

**Comment by rcurtin** [comment]
Can you tell us more about your system and how it is set up?  Some of the output that you're showing doesn't make sense to me.  Specifically, the failure of `sudo apt-get install libmlpack-dev mlpack-bin`.  Are you perhaps using Ubuntu 21.04 or something?  I noticed that mlpack is only packaged for `bionic` and `focal`: https://packages.ubuntu.com/bionic/libmlpack-dev ... I'll have to file a bug report there.

I'm also a bit confused by the pthread linker issues; I can't reproduce them.  I created a new Ubuntu 21.04 container and successfully built mlpack inside it.  Did you manually install a compiler or something like this?

For the original issue you reported with the binding documentation, I wouldn't be opposed to adding a line indicating that if you don't install the bindings with `sudo make install`, that you may need to set `PYTHONPATH`.  But, we should probably debug the issues here first before we make a change. :)

**Comment by zoq** [comment]
To fix the boost issue you have to need to update - https://github.com/mlpack/mlpack/blob/05512c668ccca122095342b8a9f2aa9ec39a7853/CMakeLists.txt#L359 and add `1.78.0` and `1.78` to the list. We have an automated script that usually updates the file once there is a new version but that script broke (fixed it).

**Comment by dnabanita7** [comment]
>   Are you perhaps using Ubuntu 21.04 or something?

naba@naba-Predator-PH315-53:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute

>  Did you manually install a compiler or something like this?

I was already getting issues then I thought of installing one manually to check if issue persists.

>  But, we should probably debug the issues here first before we make a change. :)

I guess I have totally diverged from the main issue.

**Comment by dnabanita7** [comment]
> To fix the boost issue you have to need to update

Yes, I upgraded that. 

Now, the issue is its not building python or R or Go bindings but Julia bindings are successfully built.

**Comment by dnabanita7** [comment]
[CMakeOutput.log](https://github.com/mlpack/mlpack/files/7800487/CMakeOutput.log)
as per the above file, ``COLLECT_GCC_OPTIONS`` shows that ``-pthread`` linker is used instead of ``-lpthread``. Is that an issue?

According to [SO answer](https://stackoverflow.com/questions/64514666/what-does-performing-test-cmake-have-libc-pthread-failed-actually-mean), adding a linked like ``-lpthread`` will resolve the warning/error.

**Comment by dnabanita7** [comment]
So, I changed some lines in ``CMakeLists.txt``  to set ``PYTHON_BINDINGS`` to ON as well as for ``MARKDOWN_BINDINGS``. Why is it marked as off initially?

**Comment by rcurtin** [comment]
(responding in reverse chronological order :))

> So, I changed some lines in CMakeLists.txt to set PYTHON_BINDINGS to ON as well as for MARKDOWN_BINDINGS. Why is it marked as off initially?

You don't need to change those in `CMakeLists.txt`.  Take a look at the readme and documentation for building---you can specify their values from the `cmake` command-line call: `cmake -DBUILD_PYTHON_BINDINGS=ON ...`.

> as per the above file, COLLECT_GCC_OPTIONS shows that -pthread linker is used instead of -lpthread. So, after linking it is trying to configure on my x86_64 system. Is that a problem?

Nice digging!  In any case, those are just diagnostic messages issued by CMake as it attempts to figure out the version of the compiler on your system.  The important output from CMake is either a "configuration failed" message, or a "configuration succeeded"-type message, both of which will appear at the bottom of the CMake output.  You can also see if CMake was successful by checking the return code of the program (e.g. `echo $?` directly after running CMake).

It seems like everything else is working once you set `BUILD_PYTHON_BINDINGS` to `ON`?

**Comment by dnabanita7** [comment]
yes, everything is working fine. Thank you for the explanation.

**Comment by rcurtin** [comment]
:+1: awesome!  Should we go ahead and close this issue then, or are there other things to resolve?

**Comment by dnabanita7** [comment]
nope
