### ISSUE TITLE
No lib sub folder in Boost folder

### ISSUE THREAD

**Issue by yarin177** [mlpack/mlpack#3121]
Hi, I am following [this](https://www.mlpack.org/doc/mlpack-3.4.2/doxygen/build_windows.html)  for building mlpack on windows.
I'm having issues with the Boost prebuilt Windows binaries, I downloaded the exact one you showed the in tutorial, it says that I should Install or unzip to "C:\boost\".

Later on when creating Sample C++ ML App [it says](https://www.mlpack.org/doc/mlpack-3.4.2/doxygen/sample_ml_app.html):

Under C/C++ > General > Additional Include Directories add:
C:\boost\boost_1_71_0\lib\native\include

But there isn't such folder "lib" there is a "libs" folder but I think it's not the same:

![image](https://user-images.githubusercontent.com/51924888/147891549-0d413bda-ee94-4c74-b36f-b0b6d658388a.png)

**Comment by shrit** [comment]
What is the error message you are facing?

**Comment by zoq** [comment]
Maybe it got renamed, can you also post what is in the `libs` folder.
