### ISSUE TITLE
input_labels parameter in preprocess_split function can't be empty

### ISSUE THREAD

**Issue by dnabanita7** [mlpack/mlpack#3123]
#### Problem location
https://www.mlpack.org/doc/mlpack-3.4.2/python_documentation.html#preprocess_split

#### Description of problem
``d = preprocess_split(input=np.empty([0, 0]), input_labels=np.empty([0, 0], dtype=np.uint64), no_shuffle=False, seed=0, test_ratio=0.2, verbose=False)``    shows an error of 
```                     
error: Mat::row(): index out of bounds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mlpack/preprocess_split.pyx", line 167, in mlpack.preprocess_split.preprocess_split
RuntimeError: Mat::row(): index out of bounds
```
As per [line 159](https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/preprocess/preprocess_split_main.cpp), an empty array can't have ``input_labels``.

**Comment by rcurtin** [comment]
This can be fixed as part of #2820: a check on the input sizes would provide a much better error message here than what's currently encountered.  Thanks for the report!

**Comment by dnabanita7** [comment]
keep open

**Comment by dnabanita7** [comment]
keep open
