### ISSUE TITLE
incompatible matrix dimensions while training random forest algorithm

### ISSUE THREAD

**Issue by aminul-palash** [mlpack/mlpack#3127]
#### Issue description
Need urgent help!! please response. I'm getting this error while training random forest algorithm with a number of class 4. but it was a working file with less than 4 even 5 classes. How can i set optimal parameters for any number of classes? where model has to train different numbers of classes.  

error: addition: incompatible matrix dimensions: 4x4607182418800017408 and 4x1

error: addition: incompatible matrix dimensions: 4x4607182418800017408 and 4x1

error: addition: incompatible matrix dimensions: 4x4607182418800017408 and 4x1
terminate called after throwing an instance of 'std::logic_error'

error: addition: incompatible matrix dimensions: 4x4607182418800017408 and 4x1
  what():  addition: incompatible matrix dimensions: 4x4607182418800017408 and 4x1
terminate called recursively
Aborted (core dumped)

### code
```cpp
#include "mlpack/core.hpp"
#include "mlpack/methods/random_forest/random_forest.hpp"
#include "mlpack/methods/decision_tree/random_dimension_select.hpp"
#include "mlpack/core/cv/k_fold_cv.hpp"
#include "mlpack/core/cv/metrics/accuracy.hpp"
#include "mlpack/core/cv/metrics/precision.hpp" 
#include "mlpack/core/cv/metrics/recall.hpp"
using namespace mlpack;
using namespace mlpack::tree;
using namespace mlpack::cv;
int main()
{
    mat dataset;
    bool loaded = mlpack::data::Load("data.csv", dataset);
    if (!loaded)
        return -1;
    Row<size_t> labels;
    labels = conv_to<Row<size_t>>::from(dataset.row(dataset.n_rows - 1));
    dataset.shed_row(dataset.n_rows - 1);
    const size_t numClasses = 4;
    const size_t minimumLeafSize = 5;
    const size_t numTrees = 50;
    RandomForest<GiniGain, RandomDimensionSelect> rf;
    rf = RandomForest<GiniGain, RandomDimensionSelect>(dataset, labels,
        numClasses, numTrees, minimumLeafSize);
    Row<size_t> predictions;
    rf.Classify(dataset, predictions);
    const size_t correct = arma::accu(predictions == labels);
    cout << "\nTraining Accuracy: " << (double(correct) / double(labels.n_elem))<<endl;
    mlpack::data::Save("model.bin", "model", rf, false);

    return 0;
}
```

#### Your environment

 * version of mlpack: 
 * operating system: Ubuntu 20.+
 * compiler: g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
 * version of dependencies (Boost/Armadillo):
 * any other environment information you think is relevant:

#### Steps to reproduce

use this dummy dataset to reproduce the issue.

1,6,4,12,5,5,3,4,1,67,3,2,1,2,1,0,0,1,0,0,1,0,0,1
2,48,2,60,1,3,2,2,1,22,3,1,1,1,1,0,0,1,0,0,1,0,0,2
4,12,4,21,1,4,3,3,1,49,3,1,2,1,1,0,0,1,0,0,1,0,1,3
1,42,2,79,1,4,3,4,2,45,3,1,2,1,1,0,0,0,0,0,0,0,0,5

#### Expected behavior

it should work for the multi-class datasets. any number of classes can be added on dataset.

#### Actual behavior

when I increase class type on the dataset, it is giving these errors.

**Comment by rcurtin** [comment]
I think maybe your class labels are not correct.  They should be between 0 and the number of classes, but it looks like you are specifying `1, 2, 3, 5`, instead of `0, 1, 2, 3`.  You could use `mlpack::data::NormalizeLabels()` to do this, or you could manually modify your data.

**Comment by rcurtin** [comment]
It looks like this is solved.  I'll go ahead and close the issue.
