### ISSUE TITLE
doxygen latex formula output is pixelated and ugly

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#313]
**Reported by rcurtin on 7 Jan 44117159 03:39 UTC**
The summary kind of is self-explanatory here.  See, for example,

http://www.mlpack.org/doxygen.php?doc=kmtutorial.html

Anyway, it's like the resolution of the formulas is too low or something.  FORMULA_FONTSIZE is helpful (I have it set to 12 locally and probably will check that in) but the formulas are still pixelated and ugly.  There is probably a Doxyfile option somewhere that will help.

Migrated-From: http://trac.research.cc.gatech.edu/fastlab/ticket/326

**Comment by Kirizaki** [comment]
Here's some solution presented by <a href="http://tex.stackexchange.com/questions/4302/prettiest-way-to-typeset-c-cplusplus">Christian</a>.</p> He's pointing to ```resize package```. Later on I can try to implement and test it, because right now I'm in work and I'm not sure do we can use it.

**Comment by rcurtin** [comment]
That's definitely worth trying.  I'm not sure if the issue is at the LaTeX level or maybe something is happening after LaTeX is called, but if you have a chance to test it, let me know how it turns out.

**Comment by Kirizaki** [comment]
Yup, late this evening or tomorrow morning.

**Comment by lozhnikov** [comment]
I think I've fixed the issue in 26803dc and 69947df. These commits increase the resolution of the formulas and add MathJax Doxygen HTML output (disabled by default).
