### ISSUE TITLE
Subset Selection on data

### ISSUE THREAD

**Issue by VedangAsgaonkar** [mlpack/mlpack#3133]
### Motivation
Training models on large data sets consumes a lot of time and energy. Algorithms to select subsets of training data that best model the superset and performing training on these is a new paradigm in ML.

### Implementation ideas

An implementation similar to algorithms like GLISTER, Gradient matching etc. as mentioned in [DECILE](https://decile.org/) in C++ will better equip the library.

**Comment by rcurtin** [comment]
Agreed, this could be nice to add.  If you (or anyone else) are interested in adding it, we should add a C++ implementation, as well as a binding that can be used from other languages. :+1:
