### ISSUE TITLE
Mlpack - Layer dimensioning

### ISSUE THREAD

**Issue by kgei** [mlpack/mlpack#3141]
Hey guys,

I'm trying to implement a kind of autoencoder. For this i chose mlpack as ML library. The code compiles, but I am running into matrix dimension problems and segmentation faults, which I don't understand at this point. May someone can help me figure out the problems in my code?

```
#include <stdio.h>
#include <mlpack/core.hpp>
#include <mlpack/methods/ann/layer/layer.hpp>
#include <mlpack/methods/ann/ffn.hpp>

using namespace mlpack;
using namespace mlpack::ann;

arma::mat data_gen_one_hot(int N, int M) {
    arma::mat one_hot_data(N, M+1);
    one_hot_data.fill(0);
    for (int i=0; i<N; i++) {
        one_hot_data.at(i, M) = rand()%M;
        one_hot_data.at(i, one_hot_data.at(i, M)) = 1;
    }
    return one_hot_data;
}

int main()
{
    int N = 10000, M = 16;
    // Load the training set and testing set.
    arma::mat trainData;
    arma::mat one_hot_data_train = data_gen_one_hot(N, M);
    one_hot_data_train.save("one_hot_input_train.csv", arma::csv_ascii);
    data::Load("one_hot_input_train.csv", trainData, true);

    arma::mat testData;
    arma::mat one_hot_data_test = data_gen_one_hot(N, M);
    one_hot_data_test.save("one_hot_input_test.csv", arma::csv_ascii);
    data::Load("one_hot_input_test.csv", testData, true);

    arma::mat trainLabels = trainData.row(trainData.n_rows - 1);
    // std::cout << "trainlabels: " << trainLabels << "\n";
    arma::mat testLabels = testData.row(testData.n_rows - 1);
    trainData.shed_row(trainData.n_rows - 1);

    testData.shed_row(testData.n_rows - 1);
    // Initialize the network.
    FFN<> model;
    model.Add<Linear<> >(trainData.n_rows, trainData.n_cols);
    std::cout << "Hello 1\n";
    model.Add<SigmoidLayer<> >();
    model.Add<Linear<> >(trainData.n_rows, trainData.n_cols);
    model.Add<LogSoftMax<> >();
    std::cout << "Hello 2\n";
    // Train the model.
    model.Train(trainData, trainLabels);
    // Use the Predict method to get the predictions.
    std::cout << "Hello 3\n";
    arma::mat predictionTemp;

    model.Predict(testData, predictionTemp);
    arma::mat prediction = arma::zeros<arma::mat>(1, predictionTemp.n_cols);
    // Find index of max prediction for each data point and store in "prediction"
    for (size_t i = 0; i < predictionTemp.n_cols; ++i)
    {
    // we add 1 to the max index, so that it matches the actual test labels.
    prediction(i) = arma::as_scalar(arma::find(
        arma::max(predictionTemp.col(i)) == predictionTemp.col(i), 1)) + 1;
    }
    /*
    Compute the error between predictions and testLabels,
    now that we have the desired predictions.
    */
    size_t correct = arma::accu(prediction == testLabels);
    double classificationError = 1 - double(correct) / testData.n_cols;
    // Print out the classification error for the testing dataset.
    std::cout << "Classification Error for the Test set: " << classificationError << std::endl;
    return 0;
}
```

Thanks in advance :)

**Comment by rcurtin** [comment]
Hey @kgei,

We are actually in the process of refactoring our neural network support in #2777, so I think after that refactoring the task you are trying to do should get a lot easier.

In your case, just a quick glance at the code seems to indicate that you are encoding your data as *row-major*, but mlpack takes data as *column-major*: that is, each data point should be a column.  Thus, `data_gen_one_hot(N, M)`, which is meant to generate `N` points in `M` dimensions, should actually return a matrix of size `M` rows by `N` columns.

I think that should at least fix some of the issues here---it might actually fix them all, I'm not sure.

Further reference on this topic can be found here: https://www.mlpack.org/doc/mlpack-git/doxygen/matrices.html

I hope that's helpful! :+1:

**Comment by kgei** [comment]
Hey @rcurtin,

thanks for you response! I changed the code to output and compute with column-major matrices, but I still get a seg fault while training. The only setting this doesnt happen is, when I change my N, which is the number of samples to 10. But that is not very useful in training my NN ^^'
Do you have any other idea, where the segfault has its origin? Maybe I set the values for the Layers wrong? I'm not quite sure about those...

Thanks in advance :)

**Comment by rcurtin** [comment]
When I run the program that you pasted, I get this output:

```
Hello 1
Hello 2
terminate called after throwing an instance of 'std::logic_error'
  what():  matrix multiplication: incompatible matrix dimensions: 10000x16 and 10000x32
```

I believe the issue lies here:

```
    model.Add<Linear<> >(trainData.n_rows, trainData.n_cols);
    ...    
    model.Add<Linear<> >(trainData.n_rows, trainData.n_cols);
```

When adding a linear layer, the two parameters are the number of input dimensions and the number of output dimensions.  So you can see that the first layer you added has `trainData.n_cols` outputs, but then the next linear layer you add expects `trainData.n_rows` inputs.  So, those two should match.  Maybe you mean instead to have a hidden layer with `M` neurons?

```
    model.Add<Linear<> >(trainData.n_rows, M);
    ...    
    model.Add<Linear<> >(M, trainData.n_cols);
```

That last `trainData.n_cols` should be the number of outputs for the network, i.e., the number of classes, so maybe 2?  I think based on the code that `testLabels` only takes values `0` and `1`, so the correct number of output neurons for the network should be 2.  However, I don't know the intentions of your code so I could be wrong on that---just a suggestion.

Anyway, once the dimensions of the network match, the network should train successfully.  (Tuning it so it performs well may require some additional debugging on your part, not sure.) :+1:
