### ISSUE TITLE
is it possible to make iOS compatiblity for mlpack library like as OpenSSL library? 

### ISSUE THREAD

**Issue by mamunabcoder** [mlpack/mlpack#3142]
-> Need to create .a extension for mlpack library
-> Need to support iOS Simulator
-> Need to support iOS device 

Any suggestion or idea?

**Comment by zoq** [comment]
Hello, you should be able to set `BUILD_SHARED_LIBS=OFF` during the cmake step:

`cmake -DBUILD_SHARED_LIBS=OFF ..`

that will build a static library.

**Comment by mamunabcoder** [comment]
> Hello, you should be able to set `BUILD_SHARED_LIBS=OFF` during the cmake step:
> 
> `cmake -DBUILD_SHARED_LIBS=OFF ..`
> 
> that will build a static library.

Can you please help me to build the mlpack library?

I have facing below issues when I try to build mlapck library using cmake

bjit@Mahfuzurs-MacBook-Pro build % cmake  -D BUILD_SHARED_LIBS=OFF ../
-- cotire 1.7.10 loaded.
CMake Error at /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Armadillo (missing: ARMADILLO_LIBRARY) (found suitable
  version "10.8.2", minimum required is "9.800")
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindArmadillo.cmake:137 (find_package_handle_standard_args)
  CMakeLists.txt:297 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/bjit/Work/JASMY/RnD/mlpack/CMakeFiles/CMakeOutput.log".
See also "/Users/bjit/Work/JASMY/RnD/mlpack/CMakeFiles/CMakeError.log".

**Comment by mamunabcoder** [comment]
> Hello, you should be able to set `BUILD_SHARED_LIBS=OFF` during the cmake step:
> 
> `cmake -DBUILD_SHARED_LIBS=OFF ..`
> 
> that will build a static library.

I have been using **cmake -DBUILD_SHARED_LIBS=OFF ../** and **build .a file successfully**. When I used it into Xcode iOS project some compatibility error found so it's only compatibility only macOS. I want build it into iOS compatibility.

Can you please help me?
