### ISSUE TITLE
undefined symbol architecture error: arm64 in iOS project

### ISSUE THREAD

**Issue by mamunabcoder** [mlpack/mlpack#3145]
Below error found

> In file included from /Users/bjit/Downloads/mlpack-3.4.2/src/mlpack/tests/main.cpp:16:
> /Users/bjit/Downloads/mlpack-3.4.2/src/mlpack/tests/catch.hpp:5572:13: error: unrecognized instruction mnemonic, did you mean: bit, cnt, hint, ins, not?
>             CATCH_BREAK_INTO_DEBUGGER();
>             ^
> /Users/bjit/Downloads/mlpack-3.4.2/src/mlpack/tests/catch.hpp:5290:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
>     #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
>                                                                           ^
> /Users/bjit/Downloads/mlpack-3.4.2/src/mlpack/tests/catch.hpp:5269:34: note: expanded from macro 'CATCH_TRAP'
>     #define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
>                                  ^
> <inline asm>:1:2: note: instantiated into assembly here
>         int $3
>         ^
> 1 error generated.
> make[2]: *** [src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/main.cpp.o] Error 1
> make[1]: *** [src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/all] Error 2
> make: *** [all] Error 2

**Comment by rcurtin** [comment]
Try using the git master branch---I think that the version of catch included with mlpack-3.4.2 is too old for your compiler.  Alternately you could just not build the tests (configure CMake with `-DBUILD_TESTS=OFF`).

**Comment by mamunabcoder** [comment]
> Try using the git master branch---I think that the version of catch included with mlpack-3.4.2 is too old for your compiler. Alternately you could just not build the tests (configure CMake with `-DBUILD_TESTS=OFF`).
<img width="1198" alt="mlpack_" src="https://user-images.githubusercontent.com/6092413/153371493-6820eccf-9775-4e07-b082-5fe601417e2d.png">

Check below error log snapshots

**Comment by shrit** [comment]
@mamunabcoder You need to have boost serialization installed for mlpack 3.4.2.
As @rcurtin suggested, we highly recommend using the master branch instead of mlpack 3.4.2

**Comment by mamunabcoder** [comment]
> h instead of mlpack 3.4.2

is it possible to use direct master branch code?
 
When use master branch lots of issues found for building.

Also master branch code has some error:
Don't found mlpack_export.hpp file

**Comment by mamunabcoder** [comment]
I have created a iOS static library using mlpack code with all dependencies and the iOS static library build successful and create *.a file successfully. But when try use this iOS static library found lots arm64 related error.

Here is the error snapshots



Any suggestion or idea for mlpack library with all dependencies into iOS project.

<img width="1384" alt="static_lib_error" src="https://user-images.githubusercontent.com/6092413/154460608-12bed515-b13a-44b7-93a7-89a5e80a3d23.png">

**Comment by shrit** [comment]
You need to install boost serialization, it is a dependency that is used to serialize the model
