### ISSUE TITLE
How to build mlpack library for iOS compatibility?

### ISSUE THREAD

**Issue by mamunabcoder** [mlpack/mlpack#3148]
Last few days I have tried to build mlpack library for iOS compatibility but there is no proper way to build for iOS.

I have tried to create **CMake** toolchain for iOS but it's not working when created **CMake**.

I need support to build mlpack library with all dependencies.

_**It's urgent request, any idea or support are more appreciated.**_

Please help me to do this.

**Comment by zoq** [comment]
@mamunabcoder can you post the error message you get, I guess when you talk about the CMake toolchain you mean the Xcode generator - https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-ios-tvos-or-watchos?

**Comment by mamunabcoder** [comment]
> @mamunabcoder can you post the error message you get, I guess when you talk about the CMake toolchain you mean the Xcode generator - https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-ios-tvos-or-watchos?

Master branch cmake build error

> cmake  -D BUILD_SHARED_LIBS=OFF ../
> -- The C compiler identification is AppleClang 13.0.0.13000029
> -- The CXX compiler identification is AppleClang 13.0.0.13000029
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- cotire 1.7.10 loaded.
> CMake Error at /opt/local/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find Armadillo (missing: ARMADILLO_LIBRARY) (found suitable
>   version "10.8.2", minimum required is "9.800")
> Call Stack (most recent call first):
>   /opt/local/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
>   CMake/FindArmadillo.cmake:137 (find_package_handle_standard_args)
>   CMakeLists.txt:297 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/bjit/Work/JASMY/RnD/mlpack/build/CMakeFiles/CMakeOutput.log".
> See also "/Users/bjit/Work/JASMY/RnD/mlpack/build/CMakeFiles/CMakeError.log".

**Comment by mamunabcoder** [comment]
> Hmm, this is strange, it is telling that it could not find armadillo, but it is found as well.
> Maybe you are trying to cross-compile? If you are using the master branch, I would recommend downloading the dependencies automatically using the auto downloader by using `-DDOWNLOAD_DEPENDENCIES=ON` option in CMake.

Master branch **make** build error:

**cmake  -D BUILD_SHARED_LIBS=OFF -D DOWNLOAD_DEPENDENCIES=ON ../**
-- cotire 1.7.10 loaded.
-- Could NOT find Armadillo (missing: ARMADILLO_LIBRARY) (found suitable version "10.8.2", minimum required is "9.800")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 27% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 31% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 34% complete]
-- [download 35% complete]
-- [download 36% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 39% complete]
-- [download 40% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 44% complete]
-- [download 45% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 48% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 51% complete]
-- [download 52% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 55% complete]
-- [download 56% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 61% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 67% complete]
-- [download 68% complete]
-- [download 69% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 73% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 76% complete]
-- [download 77% complete]
-- [download 78% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 81% complete]
-- [download 82% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 85% complete]
-- [download 86% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 89% complete]
-- [download 90% complete]
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 94% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
-- Found Armadillo: /Users/bjit/Work/JASMY/RnD/mlpack/build/deps/armadillo-10.3.0/include (found version "10.3.0") 
-- Found StbImage: /opt/homebrew/include/stb/  
-- Found Ensmallen: /opt/homebrew/include (found suitable version "2.18.1", minimum required is "2.10.0") 
-- Could NOT find cereal (missing: CEREAL_INCLUDE_DIR) (Required is at least version "1.1.2")
-- [download 100% complete]
-- Found cereal: /Users/bjit/Work/JASMY/RnD/mlpack/build/deps/cereal-1.3.0/include (found version "1.3.0") 
-- Found Boost: /opt/homebrew/include (found suitable version "1.76.0", minimum required is "1.58")  
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Found Git: /opt/homebrew/bin/git (found version "2.34.1") 
-- Updated gitversion.hpp.
-- Regenerating arma_config.hpp.
CMake Warning at CMakeLists.txt:526 (message):
  txt2man not found; man pages will not be generated.


-- Not building Julia bindings.
-- Not building Markdown bindings.
-- Not building Python bindings.
-- Not building Go bindings.
-- Not building R bindings.
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- CXX target mlpack cotired.
-- CXX target mlpack_test cotired.
CMake Warning (dev) at /opt/local/share/cmake-3.22/Modules/GNUInstallDirs.cmake:376 (message):
  GNUInstallDirs_get_absolute_install_dir called without third argument.
  Using ${dir} from the caller's scope for compatibility with CMake 3.19 and
  below.
Call Stack (most recent call first):
  src/mlpack/CMakeLists.txt:166 (GNUInstallDirs_get_absolute_install_dir)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /opt/local/share/cmake-3.22/Modules/GNUInstallDirs.cmake:376 (message):
  GNUInstallDirs_get_absolute_install_dir called without third argument.
  Using ${dir} from the caller's scope for compatibility with CMake 3.19 and
  below.
Call Stack (most recent call first):
  src/mlpack/CMakeLists.txt:167 (GNUInstallDirs_get_absolute_install_dir)
This warning is for project developers.  Use -Wno-dev to suppress it.

> -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
> -- Found PkgConfig: /opt/homebrew/bin/pkg-config (found version "0.29.2") 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Users/bjit/Work/JASMY/RnD/mlpack/build
**> bjit@Mahfuzurs-MacBook-Pro build % make**
> [  0%] Updating gitversion.hpp (if necessary)
> -- Found Git: /opt/homebrew/bin/git (found version "2.34.1") 
> -- gitversion.hpp is already up to date.
> [  0%] Built target mlpack_gitversion
> [  0%] Updating arma_config.hpp (if necessary)
> [  0%] Built target mlpack_arma_config
> Moving header files to include/mlpack/
> [  0%] Built target mlpack_headers
> [  2%] Generating mlpack.pc (pkg-config) file.
> [  2%] Built target pkgconfig
> [  4%] Generating CXX prefix source src/mlpack/cotire/mlpack_CXX_prefix.cxx
> [  4%] Generating CXX prefix header src/mlpack/cotire/mlpack_CXX_prefix.hxx
> [  4%] Building CXX precompiled header src/mlpack/cotire/mlpack_CXX_prefix.hxx.pch
> Scanning dependencies of target mlpack
> [  4%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/bindings/cli/print_help.cpp.o
> [  4%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/bindings/tests/clean_memory.cpp.o
> [  4%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/bindings/tests/test_function_map.cpp.o
> [  6%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/data/detect_file_type.cpp.o
> [  6%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/data/load_image.cpp.o
> [  6%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/data/save_image.cpp.o
> [  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/discrete_distribution.cpp.o
> [  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/gaussian_distribution.cpp.o
> [  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/laplace_distribution.cpp.o
> [  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/regression_distribution.cpp.o
> [ 11%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/gamma_distribution.cpp.o
> [ 11%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/diagonal_gaussian_distribution.cpp.o
> [ 11%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/kernels/epanechnikov_kernel.cpp.o
> [ 13%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/kernels/pspectrum_string_kernel.cpp.o
> [ 13%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/columns_to_blocks.cpp.o
> [ 13%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/lin_alg.cpp.o
> [ 13%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/random.cpp.o
> [ 15%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/random_basis.cpp.o
> [ 15%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/tree/cosine_tree/cosine_tree.cpp.o
> [ 15%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/backtrace.cpp.o
> [ 17%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/io.cpp.o
> [ 17%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/log.cpp.o
> [ 17%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/params.cpp.o
> [ 17%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/prefixedoutstream.cpp.o
> [ 20%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/program_doc.cpp.o
> [ 20%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/singletons.cpp.o
> [ 20%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/timers.cpp.o
> [ 22%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/version.cpp.o
> [ 22%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/adaboost/adaboost_model.cpp.o
> [ 22%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/bayesian_linear_regression/bayesian_linear_regression.cpp.o
> [ 22%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/block_krylov_svd/randomized_block_krylov_svd.cpp.o
> [ 24%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/cf/cf_model.cpp.o
> [ 24%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/fastmks/fastmks_model.cpp.o
> [ 24%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/gmm/gmm.cpp.o
> [ 26%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/gmm/diagonal_gmm.cpp.o
> [ 26%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/hoeffding_trees/hoeffding_tree_model.cpp.o
> [ 26%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/kde/kde_model.cpp.o
> [ 26%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/lars/lars.cpp.o
> [ 28%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/linear_regression/linear_regression.cpp.o
> [ 28%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/local_coordinate_coding/lcc.cpp.o
> [ 28%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/matrix_completion/matrix_completion.cpp.o
> [ 28%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/neighbor_search/unmap.cpp.o
> [ 31%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/quic_svd/quic_svd.cpp.o
> [ 31%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/radical/radical.cpp.o
> [ 31%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/randomized_svd/randomized_svd.cpp.o
> [ 33%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/range_search/rs_model.cpp.o
> [ 33%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/rann/ra_util.cpp.o
> [ 33%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/rann/ra_model.cpp.o
> [ 33%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/reinforcement_learning/environment/env_type.cpp.o
> [ 35%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/softmax_regression/softmax_regression.cpp.o
> [ 35%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/softmax_regression/softmax_regression_function.cpp.o
> [ 35%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_autoencoder/sparse_autoencoder.cpp.o
> [ 37%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_autoencoder/sparse_autoencoder_function.cpp.o
> [ 37%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_autoencoder/maximal_inputs.cpp.o
> [ 37%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_coding/sparse_coding.cpp.o
> [ 37%] Linking CXX static library ../../lib/libmlpack.a
> [ 37%] Built target mlpack
> [ 40%] Building CXX object src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/adaboost_main.cpp.o
> [ 40%] Linking CXX executable ../../../../bin/mlpack_adaboost
> **ld: library not found for -lcrt0.o
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [bin/mlpack_adaboost] Error 1
> make[1]: *** [src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/all] Error 2
> make: *** [all] Error 2**

**Comment by mamunabcoder** [comment]
> `make` will build all the CLI bindings, what you want to use?

I want to use it into iOS project but still facing some issues to use it. I can't use it iOS project because of there are lots of error found specially for the "Undefined symbol architecture: arm64", Any mobile platform managed architectures.
