### ISSUE TITLE
How to build mlpack library for android compatibility?

### ISSUE THREAD

**Issue by z4zzaman** [mlpack/mlpack#3150]
Could you please help us to integrate mlpack library into the android project?
We tried several times to build this library into an android project but faild.

It would be helpful if you can give us the step-by-step instructions to cope up this library into the android project.

**Comment by zoq** [comment]
Hello @z4zzaman, I don't think someone from the community ever tried to package mlpack for Android, so I can't reference some step-by-step instructions. However since you said you already tried a couple of things, perhaps you can share the steps and we might be able to support you. Also, I would try to build the GitHub master branch, since it requires fewer dependencies. Also, would be interesting to know how your environment looks like, are you cross-compiling?

**Comment by z4zzaman** [comment]
Hi @zoq , I've included mlpack from the master branch, there is a dependency for boost and armadillo,  So I included those sources too, facing **C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)**  error when trying to build native-lip.cpp file which uses the mlpack library.

**Here is the project structure:**

![Screenshot_structure](https://user-images.githubusercontent.com/19678549/154460314-c4659da2-9060-4484-8052-362c1ed61db8.png)

**Here is my CMakeLists file:**
[CMakeLists.txt](https://github.com/mlpack/mlpack/files/8087956/CMakeLists.txt)

**Here is my app level gradle file:**
[build.gradle.txt](https://github.com/mlpack/mlpack/files/8087972/build.gradle.txt)

**Here is my main cpp file:**
[native-lib.txt](https://github.com/mlpack/mlpack/files/8087971/native-lib.txt)


Details of the error:

D:/JasmyLabo/MlPackBuild/app/src/main/cpp/include\boost/archive/detail/oserializer.hpp:374: undefined reference to `boost::archive::detail::basic_oarchive::save_pointer(void const*, boost::archive::detail::basic_pointer_oserializer const*)'
CMakeFiles/mlpackbuild.dir/native-lib.cpp.o: In function `void boost::archive::detail::save_non_pointer_type<boost::archive::binary_oarchive>::save_standard::invoke<arma::Col<double> >(boost::archive::binary_oarchive&, arma::Col<double> const&)':
D:/JasmyLabo/MlPackBuild/app/src/main/cpp/include\boost/archive/detail/oserializer.hpp:260: undefined reference to `boost::archive::detail::basic_oarchive::save_object(void const*, boost::archive::detail::basic_oserializer const&)'
CMakeFiles/mlpackbuild.dir/native-lib.cpp.o: In function `oserializer':
D:/JasmyLabo/MlPackBuild/app/src/main/cpp/include\boost/archive/detail/oserializer.hpp:114: undefined reference to `boost::archive::detail::basic_oserializer::basic_oserializer(boost::serialization::extended_type_info const&)'
CMakeFiles/mlpackbuild.dir/native-lib.cpp.o: In function `~oserializer':
D:/JasmyLabo/MlPackBuild/app/src/main/cpp/include\boost/archive/detail/oserializer.hpp:140: undefined reference to `boost::archive::detail::basic_oserializer::~basic_oserializer()'
CMakeFiles/mlpackbuild.dir/native-lib.cpp.o: In function `void boost::archive::save_access::save_primitive<boost::archive::binary_oarchive, unsigned long long>(boost::archive::binary_oarchive&, unsigned long long const&)':
D:/JasmyLabo/MlPackBuild/app/src/main/cpp/include\boost/archive/detail/oserializer.hpp:94: undefined reference to `boost::archive::detail::basic_oarchive::end_preamble()'
CMakeFiles/mlpackbuild.dir/native-lib.cpp.o: In function `void boost::archive::save_access::save_primitive<boost::archive::binary_oarchive, unsigned int>(boost::archive::binary_oarchive&, unsigned int const&)':
D:/Projects/MlPackBuild/app/src/main/cpp/include\boost/archive/detail/oserializer.hpp:94: undefined reference to `boost::archive::detail::basic_oarchive::end_preamble()'
CMakeFiles/mlpackbuild.dir/native-lib.cpp.o: In function `boost::archive::binary_oarchive& boost::serialization::smart_cast_impl::reference<boost::archive::binary_oarchive&>::polymorphic::cross::cast<boost::archive::detail::basic_oarchive>(boost::archive::detail::basic_oarchive&)':
D:/Projects/MlPackBuild/app/src/main/cpp/include\boost/serialization/smart_cast.hpp:(.text._ZN5boost13serialization15smart_cast_impl9referenceIRNS_7archive15binary_oarchiveEE11polymorphic5cross4castINS3_6detail14basic_oarchiveEEES5_RT_[_ZN5boost13serialization15smart_cast_impl9referenceIRNS_7archive15binary_oarchiveEE11polymorphic5cross4castINS3_6detail14basic_oarchiveEEES5_RT_]+0xc): undefined reference to `typeinfo for boost::archive::detail::basic_oarchive'
D:/Projects/MlPackBuild/app/src/main/cpp/include\boost/serialization/smart_cast.hpp:(.text._ZN5boost13serialization15smart_cast_impl9referenceIRNS_7archive15binary_oarchiveEE11polymorphic5cross4castINS3_6detail14basic_oarchiveEEES5_RT_[_ZN5boost13serialization15smart_cast_impl9referenceIRNS_7archive15binary_oarchiveEE11polymorphic5cross4castINS3_6detail14basic_oarchiveEEES5_RT_]+0x10): undefined reference to `typeinfo for boost::archive::detail::basic_oarchive'



Thanks in advance!

**Comment by shrit** [comment]
Would you use the master branch please? many thanks

**Comment by z4zzaman** [comment]
Hi @shrit, we are already using from the master branch, but facing these issues.

**Comment by shrit** [comment]
@z4zzaman Nope, You are using the 3.4.2. The master branch does not contain boost serialization.
