### ISSUE TITLE
Need libatomic (-latomic) on some platforms

### ISSUE THREAD

**Issue by barak** [mlpack/mlpack#3151]
The Debian package [mlpack 3.4.2-3 fails to build on some architectures]( https://buildd.debian.org/status/logs.php?pkg=mlpack&ver=3.4.2-3 ) with errors like
```
...
cd /<<PKGBUILDDIR>>/obj-i686-linux-gnu/src/mlpack/methods/linear_svm && /usr/bin/cmake -E cmake_link_script CMakeFiles/mlpack_linear_svm.dir/link.txt --verbose=1
/usr/bin/clang++ -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -ftemplate-depth=1000 -Wno-unused-function -pthread -g -O0 -ftemplate-backtrace-limit=0 -fopenmp=libomp -Wl,-z,relro -Wl,-z,now -rdynamic CMakeFiles/mlpack_linear_svm.dir/linear_svm_main.cpp.o -o ../../../../bin/mlpack_linear_svm  -Wl,-rpath,/<<PKGBUILDDIR>>/obj-i686-linux-gnu/lib: ../../../../lib/libmlpack.so.3.4 /usr/lib/libarmadillo.so /usr/lib/i386-linux-gnu/libboost_unit_test_framework.so /usr/lib/i386-linux-gnu/libboost_serialization.so -lm 
/usr/bin/ld: CMakeFiles/mlpack_linear_svm.dir/linear_svm_main.cpp.o: undefined reference to symbol '__atomic_load@@LIBATOMIC_1.0'
/usr/bin/ld: /usr/lib/i386-linux-gnu/libatomic.so.1: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
...
```
Apparently some architectures need [`-latomic`]( https://youtu.be/O_WLw_0DFQQ?t=85 ) on both compiler and linker invocation. See eg
* https://github.com/opencv/opencv/issues/15278
* https://gitlab.kitware.com/cmake/cmake/-/issues/21174

There is a cmake fragment for this, something like
* https://github.com/llvm-mirror/llvm/blob/master/cmake/modules/CheckAtomic.cmake

**Comment by zoq** [comment]
Hehe, the issue comes with an easter egg.

**Comment by zoq** [comment]
Opened https://github.com/mlpack/mlpack/pull/3153 which might fix the issue.

**Comment by barak** [comment]
> Hehe, the issue comes with an easter egg.

Yup! [🪺]( https://www.youtube.com/watch?v=O_WLw_0DFQQ&t=230s )

**Comment by rcurtin** [comment]
Hopefully with #3153 merged, this should be fixed now. :+1:
