### ISSUE TITLE
Can I compile mlpack using QNX?

### ISSUE THREAD

**Issue by liujie316316** [mlpack/mlpack#3156]

**Comment by zoq** [comment]
I am not aware of anybody who has tried this before, but if you have the necessary dependencies like armadillo, blas mlpack should be fine as well.

**Comment by shrit** [comment]
If you have a C and C++11 compatible compiler, I do not see any issue, but as @zoq said you will have to build the dependencies by yourself.
Use in preference the mlpack master branch, since it has fewer dependencies that require compilation.

**Comment by liujie316316** [comment]
Well,thank you!

**Comment by liujie316316** [comment]
> If you have a C and C++11 compatible compiler, I do not see any issue, but as @zoq said you will have to build the dependencies by yourself. Use in preference the mlpack master branch, since it has fewer dependencies that require compilation.

I have compiled necessary dependencies like armadillo and boost, but the error is when compiling library mlpack: /usr/lib/armadillo.so file in wrong format,Then I "file armadillo.so.10.8.1",no problem with format found。Can't QNX cross compile mlpack?
