### ISSUE TITLE
mlpack library build error

### ISSUE THREAD

**Issue by mamunabcoder** [mlpack/mlpack#3157]
I have try to build the mlpacl library found some build and saw that missing some methods.

Below error::

Showing Recent Messages
Undefined symbol: mlpack::math::randUniformDist

Undefined symbol: mlpack::math::randGen

Undefined symbol: mlpack::Timer::Start(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)

Undefined symbol: mlpack::Timer::Stop(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)

Undefined symbol: mlpack::util::PrefixedOutStream::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >& (*)(std::__1::basic_ostream<char, std::__1::char_traits<char> >&))

Undefined symbol: mlpack::Log::Warn

Undefined symbol: mlpack::Log::Fatal

Undefined symbol: mlpack::util::PrefixedOutStream::operat()
or<<(char const*)
![mlpac](https://user-images.githubusercontent.com/6092413/155532663-66c73d5c-0729-49df-94a3-f64c0116b1d9.jpg)

**Comment by rcurtin** [comment]
You need to link your application against mlpack.

**Comment by rcurtin** [comment]
I don't know how to simplify really... when you compile any C++ code, you must link against any libraries that you use. Specifically *how* you do this linking is something you should be able to learn about in the documentation for your compiler and build tools.

**Comment by zoq** [comment]
`g++ test.cpp -lmlpack -larmadillo` is what I use on my machine to build a test application that is linked against mlpack and armadillo, that command might not work on your system, and it looks like you are using some IDE as well, but perhaps the command is helpful.

**Comment by mamunabcoder** [comment]
> g++ test.cpp -lmlpack -larmadillo

Thanks 🙏 for your feedback.

Basically I am using Xcode IDE(that is Apple provided) to build mlpack with all dependencies Libraries. I am directly using mlpack source code and armadillo source code.

Then how can use above command to linking the mlpack and armadillo?

I am trying to fix this issues few days but still didn't.

**Comment by zoq** [comment]
I'm not an Xcode users, but I imagine you can find a bunch of tutorials how to build a library inside Xcode that has external dependencies and uses CMake as build system. One thing that might work right out of the box is to use the CMake XCode generator, which should generate a Xcode project for you that you can build. You can open Google and search for `cmake xcode generator`.

**Comment by mamunabcoder** [comment]
> I'm not an Xcode users, but I imagine you can find a bunch of tutorials how to build a library inside Xcode that has external dependencies

Thank you so much for your feedback.

Your understanding is correct and I am a Xcode user and I am try to build the mlpack source code as external source inside the Xcode. Also I am included all dependencies of mlpack inside the Xcode.

But whatever I have done found the issues.

Need some help from your side to use mlpack source inside Xcode.
