### ISSUE TITLE
mlpack master branch source code file not found error

### ISSUE THREAD

**Issue by mamunabcoder** [mlpack/mlpack#3158]
I am using master branch code to build but found file not found error

Below is the error
![file](https://user-images.githubusercontent.com/6092413/156140623-42d17f59-83bb-4e6b-9410-9e064c585ed0.jpg)

**Comment by shrit** [comment]
Did you install mlpack?

**Comment by mamunabcoder** [comment]
> Did you install mlpack?

I am direct using the master branch source code for build and using Xcode compiler. 
My pc environment is MacOS (M1). Last few weeks you have suggested to use the master branch code. Also I had tried to cmake build for master branch code but master branch code is build for MacOS (M1) pc. I am little bit disappointed to use this library lots of error of this library but there is no proper solution yet.

Can please help me to build the code?

**Comment by shrit** [comment]
You need to build mlpack before using it.
The build instructions are in the README on the front page in GitHub.
Xcode is not a compiler, it is an IDE and most IDE makes life much worse if you do not know how to configure them. IDEs are not out-of-box tools in most cases.
I never had any issue with building mlpack, our own CI infrastructure is green and building on Mac is passing perfectly as well.
You need to analyze the errors you are getting and look for them online, most of these errors are not related to mlpack at all.

For instance, what do you mean by this sentence? it doesn't make any sense to me:

`Also I had tried to cmake build for master branch code but master branch code is build error for MacOS (M1) pc`

**Comment by mamunabcoder** [comment]
> For instance, what do you mean by this sentence? it doesn't make any sense to me:

I had build the below command:
cmake  -D BUILD_SHARED_LIBS=OFF ../

Also make command using into terminal : make

When try to follow above process found make command failed.

**Comment by zoq** [comment]
If you post the error you get when you run `cmake` we can provide some hints how to solve it, without it we can just guess. Actually, we encourage everyone to use the template when they open an issue (it's there for a reason), the template asks for more details, which helps us to understand the issue and to help you to solve the issue.

The errors from the image, are not mlpack specific, it's how you are trying to build against a library.
