### ISSUE TITLE
MLPack Build for Arm64 from linux

### ISSUE THREAD

**Issue by nitolpalak** [mlpack/mlpack#3159]
OS: Ubuntu 20.04
Development environment: Desktop

I want to build a shared library or static library of mlPack for Arm64 architecture from my linux environment preferably using NDK-Build.
I have tried downloading the arm64 built file([libmlpack-dev_3.3.2-2_arm64.deb](https://launchpad.net/ubuntu/+source/mlpack/3.3.2-2/+build/19774415/+files/libmlpack-dev_3.3.2-2_arm64.deb)) from [this link](https://launchpad.net/ubuntu/+source/mlpack/3.3.2-2/+build/19774415). But here I found that libmlpack.so.3 file is missing so libmlpack.so file is shown broken. 
So, is there any reliable link to download the file or any reliable way to build the library from source for arm64 architecture?

**Comment by shrit** [comment]
is there any `.so` inside the package?

**Comment by rcurtin** [comment]
You can't just download random precompiled files from the internet and expect them to work on your setup.  Also, you downloaded an old version of mlpack, which is not a great idea.

If you want to *build* mlpack, then downloading a precompiled version is not what you want---you should follow the instructions in the README to compile.  Our build servers test against arm64 architecture and there should be no problem if your development environment is set up correctly. :+1:

**Comment by nitolpalak** [comment]
> is there any `.so` inside the package?

Yes. there are many .so files as following:
![image](https://user-images.githubusercontent.com/19832924/156246828-738642ec-afd9-431f-85bf-7ed82a086e3a.png)

**Comment by shrit** [comment]
Perfect, that is all what you need

**Comment by nitolpalak** [comment]
> You can't just download random precompiled files from the internet and expect them to work on your setup. Also, you downloaded an old version of mlpack, which is not a great idea.
> 
> If you want to _build_ mlpack, then downloading a precompiled version is not what you want---you should follow the instructions in the README to compile. Our build servers test against arm64 architecture and there should be no problem if your development environment is set up correctly. 👍

I understand that I can not just expect random precompiled files from internet to work. The issue is I am trying to use the mlpack as a dependent library of a program I am trying to build for android using NDK-Build. But if I use the .so file that I have built from source in my environment it shows 
```
ld: error: ~/jni/lib/libmlpack.so is incompatible with aarch64linux
```
And as far as I have understood, as I have built mlpack from source in my desk environment my .so file is not compatible for arm64 that I am trying to build my project for. 
Sorry if I missed something or misunderstood as I am new to cpp built system and cmake.
So, can you please point out what I am doing wrong or misunderstanding?

**Comment by nitolpalak** [comment]
> Perfect, that is all that you need. there is no difference between .so.3 and .so just a symbolic link toward the same thing

Thank you for your reply. I think I understand now that the full mlpack library was divided into multiple .so files. So, I need to link all of these .so files in my project. Is there a way to compile all these .so files together and build them into one?

**Comment by rcurtin** [comment]
Thanks for the clarification!  When you compile mlpack on your system, you will have to cross-compile it for arm64.  You can do this with the usual CMake cross-compilation utilities.  @shrit actually wrote up a tutorial if I remember right, but I can't seem to find it.  There is some documentation here: https://github.com/mlpack/mlpack/blob/master/board/crosscompile-toolchain.cmake

My memory of doing this, last time I tried, was that I set up a [buildroot environment](https://buildroot.org) and then used that as `CMAKE_SYSROOT`.  However, I may be missing a detail there.  I *think* that if you can find a tutorial on cross-compiling with CMake, it *should* work with our CMake configuration.

**Comment by shrit** [comment]
Sorry never had time to do proper documentation, I shall do it one day.
If you have any questions let me know, please.

**Comment by mamunabcoder** [comment]
> Thanks for the clarification! When you compile mlpack on your system, you will have to cross-compile it for arm64. You can do this with the usual CMake cross-compilation utilities. @shrit actually wrote up a tutorial if I remember right, but I can't seem to find it. There is some documentation here: https://github.com/mlpack/mlpack/blob/master/board/crosscompile-toolchain.cmake
> 
> My memory of doing this, last time I tried, was that I set up a [buildroot environment](https://buildroot.org/) and then used the root directory of that setup as the value of the variable CMAKE_SYSROOT when I configured the project with cmake. However, I may be missing a detail there. I think that if you can find a tutorial on cross-compiling with CMake, it should work with our CMake configuration.


Can you please help us to build the cross-compiling?
I can't understand where we using the cross-compiling toolchain.cmake into CMakeList.txt.

**Comment by shrit** [comment]
@mamunabcoder what is the host architecture and the target architecture that you are compiling for?

**Comment by mamunabcoder** [comment]
> @mamunabcoder what are the host architecture and the target architecture that you are compiling for?

Thank you so much for quick feedback.
The host architecture: macOS 

The target architecture:
For iOS device: arm64, arm7
For iOS simulator: arm64, i386 and x86_64

**Comment by shrit** [comment]
@mamunabcoder there is an issue was for the same problem but for android, I answered it here #3160 
Let me know if this helps you.

**Comment by nitolpalak** [comment]
I have been trying to create a buildroot environment for android arm64v8 to use the sysroot as my `CMAKE_SYSROOT`. For that I have been following the following steps:
1. I am using buildroot-2020.08.1
2. `make menuconfig`
```
    Target options → TargetArchitecture = AArch64 (Little Endian)
    Toolchain → Toolchain type = External
    Toolchain → Toolchain = Linaro AArch64
    Filesystem images → enable "tar the root file system"
```
for this configuration I followed: https://community.arm.com/oss-platforms/w/docs/499/build-a-buildroot-user-space

3. `make ARCH=arm64 BR2_JLEVEL=N -j 4`
It did not give any error.

After this, in mlpack master branch I ran: 
1. `mkdir build_arm64 && cd build_arm64`
2. Then the following command:
```
cmake -DDEBUG=OFF -DPROFILE=OFF -DBUILD_MARKDOWN_BINDINGS=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_GO_BINDINGS=OFF -DBUILD_JULIA_BINDINGS=OFF -DBUILD_R_BINDINGS=OFF -DCMAKE_TOOLCHAIN_FILE=../board/crosscompile-toolchain.cmake -DBOARD_NAME="RPI4" -DDISABLE_DOWNLOADS=OFF -DTOOLCHAIN_PREFIX=~/buildroot-2020.08.1/output/host/bin/aarch64-buildroot-linux-gnu- -DCMAKE_SYSROOT=~/buildroot-2020.08.1/output/host/arm64-buildroot-linux-gnu/sysroot ../
```
But it gives the following error:
![1](https://user-images.githubusercontent.com/19832924/157197605-d21126da-e114-42d8-86cb-c2aed8f2fced.PNG)

Any idea what I am doing wrong here? Thanks in Advance.

**Comment by nitolpalak** [comment]
Hello, @shrit @rcurtin ,

I am trying to build a program which is dependent on `mlpack` for android. For that I am using ndk-build. To make the library compatible for arm64 architecture, I have used [buildroot environment][2] 2020.08.1 to create the sysroot and aarch64-linux-gnu-gcc and aarch64-linux-gnu-g++. I have followed [this][3] link and set the following menuconfig to do that:
```
    Target options → TargetArchitecture = AArch64 (Little Endian)
    Toolchain → Toolchain type = External
    Toolchain  → Toolchain = Linaro AArch64
    Filesystem images → enable "tar the root file system"
```
Then, in mlpack/build folder I have run the following command as you mentioned in [this](https://github.com/mlpack/mlpack/issues/3160#issuecomment-1060010568) comment:
```
cmake -DDEBUG=OFF -DPROFILE=OFF -DBUILD_MARKDOWN_BINDINGS=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_GO_BINDINGS=OFF -DBUILD_JULIA_BINDINGS=OFF -DBUILD_R_BINDINGS=OFF -DCMAKE_TOOLCHAIN_FILE=../board/crosscompile-toolchain.cmake -DBOARD_NAME="RPI4" -DDISABLE_DOWNLOADS=OFF -DTOOLCHAIN_PREFIX=~/buildroot-2020.08.1/output/host/bin/aarch64-linux-gnu- -DCMAKE_SYSROOT=~/buildroot-2020.08.1/output/host/arm64-buildroot-linux-gnu/sysroot ../
```
But after I use the libmlpack.a file in `ndk-build`, I get the following error:
![Capture](https://user-images.githubusercontent.com/19832924/157374061-8f9c7d87-bfb2-451d-947d-83d213716bc0.PNG)
I see that the exception is asking me to `recompile with -fPIC`. But what I dont understand is do I need to add this flag while building my api with ndk-build or do I need to somehow add this flag while using the cmake command to build `libmlpack.a`?
Thank in advance.

**Comment by rcurtin** [comment]
Are you compiling your program that uses mlpack with `-fPIC`?  If so, try compiling without `-fPIC`---or, try modifying your configuration of how the mlpack static library is built so that it uses `-fPIC`.  I'm not 100% sure what is going on here, but hopefully my comment is at least a little helpful. :+1:

**Comment by benz0li** [comment]
Cross reference: https://bugs.r-project.org/show_bug.cgi?id=18326

**Comment by benz0li** [comment]
Simon Urbanek, 2022-04-27 09:59:44 UTC

> Just a quick comment: please note that this is not an issue for R since it doesn't get anywhere close to the limit, so this is really low priority (if an issue at all). Packages with exceptionally large sizes can handle their own flags. Some further research suggests the overrides are intentional due to performance issues on some platforms so you'd likely have to convince experts in that field that that such chage does not cause more harm that good. Given the earlier comments I'm certainly not touching this.

– https://bugs.r-project.org/show_bug.cgi?id=18326#c14

**Comment by benz0li** [comment]
Olivier Benz, 2022-05-02 09:08:27 UTC

> (In reply to Martin Maechler from [comment #18](https://bugs.r-project.org/show_bug.cgi?id=18326#c18))
> 
> > So couldn't the package maintainer of such large packages, e.g. Hannes for `duckdb` not simply add a line such as
> > ```
> > PKG_CXXFLAGS = -fPIC
> > ```
> > to the package specific `src/Makevars` file?
> 
> Yes he could.
> 
> > Or are you arguing that this should not be package specific, but arm64/aarch64 should always use `-fPIC` ?
> 
> IMHO arm64/aarch64 should always use `-fPIC`.
> 
> > IIUC, Simon argues that this could be suboptimal as it would affect the build of R and all (`src/` - using) packages (by default), when instead it's only needed for exceptionally large packages.
> 
> Simon uses `-fPIC` for Apple M1 (= arm64/aarch64), too.

**Comment by rcurtin** [comment]
Thanks for keeping us updated!

**Comment by benz0li** [comment]
The issue with the R package on Linux aarch64 remains: https://dl.b-data.ch/cran-install-all/aarch64/fpic/out/mlpack.out.

@rcurtin Should I open a new issue for this?

**Comment by rcurtin** [comment]
Yes, a new issue is probably the right call here.  I am not sure exactly what the issue is, and I wonder if the next release of mlpack will not have this problem simply because it does not have a boost dependency.

**Comment by gaurav-bhardwaj29** [comment]
Hey! Wanted to ask how to set up a **development environment** for mlpack in ubuntu? I have installed mlpack using : $ sudo apt-get install libmlpack-dev  and installed python dependencies and build it from source. What to do next? How to contribute and develop?
