### ISSUE TITLE
Load function maps every matrix cell to zero

### ISSUE THREAD

**Issue by Ferox98** [mlpack/mlpack#3161]
#### Issue description
I am using mlpack's load function to load a csv file containing both numeric and categorical features and ran into a problem. According to mlpack's documentation, I must specify a DatasetInfo variable to load data containing categorical features. Despite doing this, all of the matrix's cells have a value of zero. 

Here is the code I am using to load the dataset:
`arma::mat matrix1;`
`data::DatasetInfo datasetInfo;`
`data::Load("SalesData.csv", matrix1, datasetInfo);`
 `cout << matrix1 << endl;`

The first few rows of the dataset I am trying to load look like this:
`Date,Order ID,Customer Name,Product ID,Product Name,Quantity`
`2021-06-01,B0000001,Customer - 0001,P0001,Product - 0001,1.0`
`2021-06-01,B0000001,Customer - 0001,P0002,Product - 0002,1.0`
`2021-06-01,B0000001,Customer - 0001,P0003,Product - 0003,1.0`
`2021-06-01,B0000001,Customer - 0001,P0004,Product - 0004,1.0`
`2021-06-01,B0000001,Customer - 0001,P0005,Product - 0005,1.0`
#### Your environment

 * version of mlpack: 3.4.2
 * operating system: Ubuntu
 * compiler:
 * version of dependencies (Boost/Armadillo):
 * any other environment information you think is relevant:

#### Expected behavior

Dataset should be loaded into the armadillo matrix

#### Actual behavior

All of the matrix's entries have a value of zero

**Comment by shrit** [comment]
Would it be possible to use the mlpack from the master branch, please?
There has been a lot of refactoring in the last two years, and mlpack 3.4 is quite old now.
We have also refactored and improved the code related to the dataset mapper last year.
Let me know if you face the same issue with the new version
Thanks

**Comment by Ferox98** [comment]
Hi there,

Thank you for the answer! Yes it turns out I was using the outdated version of mlpack. Everything works properly once I updated mlpack to the latest version.

Thanks
