### ISSUE TITLE
Compile errors W10 VS2019 mlpack example

### ISSUE THREAD

**Issue by giofum** [mlpack/mlpack#3162]
Hello everybody!
Has anyone of you experimented this problem, or similar one?
I've correctly built armadillo and mlpack, but trying to compile a mlpack example with the following includes, leads to this:

#include <mlpack/core.hpp>
#include <mlpack/prereqs.hpp>
#include <mlpack/methods/ann/rnn.hpp>
#include <mlpack/methods/ann/layer/layer.hpp>
#include <mlpack/core/data/scaler_methods/min_max_scaler.hpp>
#include <mlpack/methods/ann/init_rules/he_init.hpp>
#include <mlpack/methods/ann/loss_functions/mean_squared_error.hpp>
#include <mlpack/core/data/split_data.hpp>
#include <ensmallen.hpp>

using namespace std;
using namespace mlpack;
using namespace mlpack::ann;
using namespace ens;

Gravità Codice Descrizione Progetto File Riga Stato eliminazione
Errore C2672 'core::v2::meta::all': non sono state trovate funzioni in overload corrispondenti MyExample d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp 316
Errore C2975 'Bs': argomento di modello non valido per 'core::v2::meta::all'. Prevista espressione costante in fase di compilazione MyExample d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp 316
Errore C2672 'core::v2::meta::none': non sono state trovate funzioni in overload corrispondenti MyExample d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp 337
Errore C2975 'core::v2::meta::none': argomento di modello non valido per 'Bs'. Prevista espressione costante in fase di compilazione MyExample d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp 337
Errore C2672 'core::v2::meta::all': non sono state trovate funzioni in overload corrispondenti MyExample d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp 417
Errore C2975 'Bs': argomento di modello non valido per 'core::v2::meta::all'. Prevista espressione costante in fase di compilazione MyExample d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp 417
Errore C2672 'core::v2::meta::none': non sono state trovate funzioni in overload corrispondenti MyExample d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp 435
Errore C2975 'core::v2::meta::none': argomento di modello non valido per 'Bs'. Prevista espressione costante in fase di compilazione MyExample d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp 435
Errore C2672 'core::v2::meta::all': non sono state trovate funzioni in overload corrispondenti MyExample d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp 859
Errore C2975 'Bs': argomento di modello non valido per 'core::v2::meta::all'. Prevista espressione costante in fase di compilazione MyExample d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp 859

**Comment by zoq** [comment]
Please share the commands you used to build/install mlpack, and also the commands you used to build the example.

**Comment by zoq** [comment]
Can you run the same test against the latest master branch, looking at the directory, I think you build mlpack 3.4.2?

**Comment by rcurtin** [comment]
Could this have to do with the merge of #3006?  I'm interested to see what the results of testing against the master branch are.

**Comment by GLmontanari** [comment]
I have your same issue with Visual Studio 2022 and mlpack 4.0.0
