### ISSUE TITLE
QNX_HOST environment variable not set

### ISSUE THREAD

**Issue by liujie316316** [mlpack/mlpack#3163]
I am compiling mlpack using QNX.Keep reporting the following errors:
CMake Error at CMakeLists.txt:28 (message):QNX_HOST environment variable not set!!!
I have added the following to CMakeLists.txt:
set (QNX_HOST “/data/QNX/qnx700/host/linux”)
set (QNX_TARGET “/data/QNX/qnx700/target/qnx7”)
But it still reports an error.
Does anyone know what I should do ?

**Comment by zoq** [comment]
@liujie316316 looks like Will was faster - https://stackoverflow.com/a/71399513.

**Comment by liujie316316** [comment]
> @liujie316316 looks like Will was faster - https://stackoverflow.com/a/71399513.

This bug has not been solved yet, which is described in more detail.https://stackoverflow.com/questions/71392941/qnx-host-environment-variable-not-set

**Comment by rcurtin** [comment]
It looks like you have multiple issues.   If you can isolate the problem better, it's a little bit easier to help.  The updated version in the StackOverflow post you linked to suggests that you have Armadillo configured incorrectly.  Make sure that `armadillo_bits/config.hpp` has its settings set correctly for whatever BLAS or LAPACK library you are using with Armadillo and mlpack.  Specifically I suspect that `ARMA_BLAS_UNDERSCORE` needs to be set, but it may not be that simple.
