### ISSUE TITLE
Can't setup mlpack on windows

### ISSUE THREAD

**Issue by tareknaser360** [mlpack/mlpack#3168]
Hi guys,
Can anyone help me set up mlpack on windows 11?
I tried:
     - pip install mlpack                                           "ERROR: Could not find a version that satisfies the requirement mlpack"
     - conda install -c conda-forge mlpack               "PackagesNotFoundError: The following packages are not available"
     
Is there any way I can install mlpack and use it in my jupyter notebooks without having to build it from scratch?

**Comment by rcurtin** [comment]
We haven't yet succeeded at building a Windows Python package. See, for instance, https://github.com/conda-forge/mlpack-feedstock/pull/18.  I wish I had a better answer than that but right now I don't.  I'm hopeful that the simplification of mlpack's dependencies with the upcoming mlpack 4 release will help, but we'll see.

**Comment by rcurtin** [comment]
I guess, I should add, you should be able to build the mlpack Python bindings on Windows without a problem; however, we just haven't managed to get them to build successfully on the PyPI or conda packaging systems (yet).

**Comment by tareknaser360** [comment]
Sorry I didn't understand what I should do from [conda-forge/mlpack-feedstock#18](https://github.com/conda-forge/mlpack-feedstock/pull/18)
Would it be easier if I used ubuntu on virtual box?
I only want to run mlpack and use it on machine learning examples using jupyter notebooks for python mainly. I don't want to build it for now

PS: I have no prior experience with linux or ubuntu

**Comment by rcurtin** [comment]
Yes, given what you wrote, personally I think you'd probably have an easier time using mlpack on Linux in a virtual machine.

**Comment by tareknaser360** [comment]
Ok I will do that.
Thank you for your help

**Comment by MahmoudHashem0** [comment]
Hello @tareknaser360 If you don't want to leave windows I think it is better to [install ubuntu as WSL] (https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-11-with-gui-support#1-overview)

it provides you with ubuntu terminal without leaving windows  then you can install mlpack as documented

I think the most easiest one is to install mlpack by pip
then you may need to install pip by running these two commands

$ sudo apt-get update
$ sudo apt-get install python3-pip

finally you can install ml pack by running this command
$ pip3 install mlpack

now you can import mlpack in python interpreter

>>> import mlpack

**Comment by tareknaser360** [comment]
Firstly, Thank you very much for your help
I can't import mlpack in jupyter notebook that I run in windows. 
Did you mean that I should run jupyter notebooks from Ubuntu terminal as well?

Also, Is there any way I can use mlpack with c++ on windows?

**Comment by MahmoudHashem0** [comment]
For your first question:
Yes I mean that you should run jupyter notebook 
From Ubuntu terminal

For your second question:
I think mlpack provides a documentation for that
Check this link https://www.mlpack.org/doc/mlpack-3.4.2/doxygen/build_windows.html

I hope it helps
