### ISSUE TITLE
Compile Error for Naive Bayes Filter

### ISSUE THREAD

**Issue by mueller-david-tud** [mlpack/mlpack#3169]
#### Issue description

Hi, thank you all for your hard work you put in into MLPack (both development and support).
I have the following minimal C++ example, where Compiling fails due to strange errors with armadillo
```
// Main.cpp
#include <mlpack/core.hpp>
#include <mlpack/methods/naive_bayes/naive_bayes_classifier.hpp>

int main(int argc, char *argv[]) {
  arma::Row<double> featureVec(5);
  arma::Row<double> probVec(5);
  size_t prediction;
  mlpack::naive_bayes::NaiveBayesClassifier<arma::mat> model;

  model.Classify<>(featureVec, prediction, probVec);
}
```
The according CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.7.2)
project(minimal)

set(CMAKE_CXX_STANDARD 17)
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Werror")
set(CMAKE_BUILD_TYPE Debug)
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -O0 -g")

find_package(MLPack)

include_directories(${MLPACK_INCLUDE_DIRS})
add_executable(minimal Main.cpp)
target_link_libraries(minimal ${MLPACK_LIBRARIES})
```
#### Your environment

 * version of mlpack: 3.4.2
 * operating system: Docker/Debian Bullseye
 * compiler: Debian clang version 11.0.1-2
 * version of dependencies (Boost/Armadillo):  Boost 1.74, Armadillo 1.10
 * any other environment information you think is relevant:

#### Steps to reproduce

Run `cmake` and `make` with  `cmake . && make`. 

#### Expected behavior

A compiled binary should be output.

#### Actual behavior

The following compilation error occurs:
```
In file included from /opt/minimal/Main.cpp:3:
In file included from /usr/include/mlpack/methods/naive_bayes/naive_bayes_classifier.hpp:250:
/usr/include/mlpack/methods/naive_bayes/naive_bayes_classifier_impl.hpp:274:16: error: no viable conversion from 'typename enable_if2<is_arma_type<Mat<double>>::value && resolves_to_vector<Mat<double>>::no, const Op<Mat<double>, op_max>>::result' (aka 'const arma::Op<arma::Mat<double>, arma::op_max>') to 'const double'
  const double maxValue = arma::max(logLikelihoods);
               ^          ~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/minimal/Main.cpp:11:9: note: in instantiation of function template specialization 'mlpack::naive_bayes::NaiveBayesClassifier<arma::Mat<double>>::Classify<arma::Row<double>, arma::Row<double>>' requested here
  model.Classify<>(featureVec, prediction, probVec);
        ^
1 error generated.
```

**Comment by zoq** [comment]
Thanks for the detailed report, you actually encountered an issue with the implementation, when you use `arma::Mat` as the mat model type. I'll open a PR with a fix, as a quick workaround you can switch to:

https://github.com/mlpack/mlpack/blob/b5dfa9561ba1106a19dae8cb663570cc960235ec/src/mlpack/methods/naive_bayes/naive_bayes_classifier_impl.hpp#L309-L312

**Comment by rcurtin** [comment]
It seems like changing line 274 in `naive_bayes_classifier_impl.hpp` to `const double maxValue = arma::max(logLikelihoods.col(0));` could be one fix.

**Comment by eshaanagarwal** [comment]
> It seems like changing line 274 in `naive_bayes_classifier_impl.hpp` to `const double maxValue = arma::max(logLikelihoods.col(0));` could be one fix.

I think that the suggested fix wont work if `ModelMatType` is a row or column vector. Should we deal with this by checking if its a vector or matrix and proceed accordingly ?

**Comment by rcurtin** [comment]
I would expect `ModelMatType` to always be a matrix type of some sort.  (It might not be a bad idea to add a static assertion for that, but we don't currently have a good infrastructure for statically testing types that's applied throughout all of our models.)

**Comment by eshaanagarwal** [comment]
> It seems like changing line 274 in `naive_bayes_classifier_impl.hpp` to `const double maxValue = arma::max(logLikelihoods.col(0));` could be one fix.

should we go ahead with this fix then ? If so, I would love to patch this up.

**Comment by conradsnicta** [comment]
An alternative solution would be to use the [.max() member function](http://arma.sourceforge.net/docs.html#min_and_max_member), which always returns a scalar.  For example, `const double maxValue = logLikelihoods.max();`

The `.max()` member function disregards whether the object is a vector, matrix, or cube, and simply returns the max across all elements.  This differs from the standalone `max()` function, which acts differently depending on whether the object is a vector or a matrix; this is to approximate the functionality of `max()` in Matlab.

**Comment by rcurtin** [comment]
Yeah---actually to me that sounds like the better solution here. :+1:
