### ISSUE TITLE
Can we use mlpack library in commercial applications?

### ISSUE THREAD

**Issue by robi56** [mlpack/mlpack#3170]

**Comment by zoq** [comment]
Hello @robi56 please checkout https://github.com/mlpack/mlpack/blob/master/LICENSE.txt since the answer depends on the version. If we are talking about the current master branch, the answer is yes you can use mlpack in a commercial application.

**Comment by rcurtin** [comment]
mlpack's been BSD-licensed since... a long time.  2014 I think?  Somewhere around then.  Anyway, previous to that it was LGPL, but that was like mlpack 2.x or even 1.x.  So as long as you follow the terms of the BSD license (which is pretty permissive) you should be just fine. :+1:

**Comment by robi56** [comment]
> Hello @robi56 please checkout https://github.com/mlpack/mlpack/blob/master/LICENSE.txt since the answer depends on the version. If we are talking about the current master branch, the answer is yes you can use mlpack in a commercial application.

Thank you for your reply. I have a question could you please explain why we can use mlpack master branch for commercial use and why we can't use 2.x and 3.x versions as commercial purposes.

**Comment by rcurtin** [comment]
@robi56 unless I am missing something the question is already answered.  You can use any version of mlpack you want so long as you abide by the terms of the license.  As I pointed out, the license changed from LGPL in earlier versions of mlpack to BSD, which is what it is licensed as now.

**Comment by zoq** [comment]
The main reason why I said, the master branch is that I was lazy. You can look at the `HISTORY.md` file:

https://github.com/mlpack/mlpack/blob/master/HISTORY.md#mlpack-1012

to get the exact version.
