### ISSUE TITLE
The seed of shuffle in mlpack.preprocess_split varies

### ISSUE THREAD

**Issue by MahmoudHashem0** [mlpack/mlpack#3171]
I need to get the same train and test samples (output) while running the method with the same parameters multiple times

example: output = mlpack.preprocess_split(input=dataset,
                                 test_ratio=0.3,
                                 seed = 2,
                                 no_shuffle = False)

I need to get the same output where the seed is still 2
and when make the seed = 0 the output varies every time

unfortunately the actual result is that the output varies even if the seed = 2 or any integer number

If this is a real issue needs to be solved so please assign me to solve it

**Comment by zoq** [comment]
`seed=0` will initialize the random generator with the time so you should see different results with `seed=0`:

https://github.com/mlpack/mlpack/blob/b5dfa9561ba1106a19dae8cb663570cc960235ec/src/mlpack/methods/preprocess/preprocess_split_main.cpp#L104

However `seed = 2 ` should return the same results for each run, what version are you currently using?

**Comment by MahmoudHashem0** [comment]
Thanks for your reply @zoq 

The version what I use is 3.4.2

I tried to install mlpack by two packages for Python

First one was pip

Second one was from source

Unfortunately both of them has the same results


The version from source is 3.4.2

The version from pip is 3.4.2

**Comment by zoq** [comment]
Thanks for the update, I can reproduce the results here as well.

**Comment by zoq** [comment]
Tested the C++ code as well, which returns the same result each time, so the seed works as expected. Do you like to take a closer look into the issue?

**Comment by zoq** [comment]
My current guess is that the binding detection does not work correctly in case it's not a binding test: 

https://github.com/mlpack/mlpack/blob/83e70110595eaf3cf3758f270433801e673615b2/src/mlpack/core/math/random.hpp#L42-L53

**Comment by MahmoudHashem0** [comment]
Thanks @zoq for your help.
Yes, I want to take a closer look into the issue and try to solve it.

**Comment by zoq** [comment]
Awesome thanks, let us know if you need any further information.

**Comment by MahmoudHashem0** [comment]
Ok I'll.
Please assign it to me if you don't mind.
