### ISSUE TITLE
building python from source on Linux isn't documented well

### ISSUE THREAD

**Issue by MahmoudHashem0** [mlpack/mlpack#3172]
I believe that you have a great documentation but there is a bit issue

In this link https://www.mlpack.org/getstarted.html

for build I choosed stable

for OS I choosed Linux

for Package I choosed source

for Language I choosed Python

then I this was the result:

apt-get install libboost-math-dev libboost-program-options-dev libboost-test-dev libboost-serialization-dev libarmadillo-dev binutils-dev libensmallen-dev libstb-dev python-pandas python-numpy cython python-setuptools wget 

wget -c http://mlpack.org/files/mlpack-latest.tar.gz -O - | tar -xz 
cd mlpack 
mkdir build 
cmake -DBUILD_PYTHON_BINDINGS=ON .. 
make 
make install 

In Python 
import mlpack 

I have found that we should run

mkdir build && cd build

instead of just

mkdir build 

as you have documented here https://www.mlpack.org/doc/stable/doxygen/build.html

**Comment by hello-fri-end** [comment]
> as you have documented here https://www.mlpack.org/doc/stable/doxygen/build.html

HI @MahmoudHashem0 ! It is clearly mentioned in that link that you need to `cd` into the build directory. I don't see any issue there.

**Comment by MahmoudHashem0** [comment]
>but there is a bit issue
>
>In this link https://www.mlpack.org/getstarted.html

Hi @hello-fri-end you are right but please open this link 👆 and you will find it.

The steps for python binding is provided in multiple links:

>First link: https://www.mlpack.org/getstarted.html


>Second link: https://www.mlpack.org/doc/stable/doxygen/build.html


The issue is in the first link not the second.

**Comment by zoq** [comment]
Thanks for the report, fixed in https://github.com/mlpack/mlpack.org/commit/11a7559b386633f3e0903d33f52232df94940103, will take some minutes to update and deploy the website.

**Comment by MahmoudHashem0** [comment]
Thanks alot for your attention @zoq 

Everything is clean now because of your quick support
