### ISSUE TITLE
Building on windows

### ISSUE THREAD

**Issue by Userthatsnamed** [mlpack/mlpack#3174]
Tried to build a Ann example... built following an up to date version of the tutorial from mlpacks github wiki of the Windows build I've done on vs 22 using packages 143.. it worked, but now it's playing up, it's down to 42 errors now an stuck there. It only finds ensmallen.hpp now, where as before it noticed an ran all headers.. when compiled/ran now on build + intellisense it will go from 42 errors to zero then back to 42 errors.  On build it has zero errors but it's still lit up with red lines.  I've played around with c/c++ and linker an made sure everything's up to date, but not sure how to get rid of this.

**Comment by zoq** [comment]
Can you share some details about your setup, what is your compiler, did you use pre-compiled version of the dependencies, what are the errors you get?

**Comment by Userthatsnamed** [comment]
msvc ,all is done the same as https://github.com/mlpack/mlpack/wiki/WindowsBuild  except I've added ensmallen to the includes. ensmallen header is found the rest aren't.
cannot open source file "mlpack/prereqs.hpp"
cannot open source file " mlpack/core.hpp"
cannot open source file " mlpack/methods/ann/loss_functions/mean_squared_error.hpp"
cannot open source file " mlpack/core/data/scaler_methods/min_max_scaler.hpp"
cannot open source file " mlpack/methods/ann/layer/layer.hpp"
cannot open source file "/core/data/split_data.hpp"
cannot open source file " mlpack/methods/ann/ffn.hpp"
cannot open source file " mlpack/methods/ann/init_rules/he_init.hpp"
 
includes directory as well as everything has the right path but it wont find anyhting
