### ISSUE TITLE
Iterator problems when replacing boost::heap::priority_queue with std::priority_queue

### ISSUE THREAD

**Issue by LiuZhuojin** [mlpack/mlpack#3175]
I'm trying to remove boost parts in mlpack like #3095 suggests. I chose to replace `boost::heap::priority_queue` in `mlpack/src/mlpack/core/tree/cosine_tree/cosine_tree.hpp`.  
 But in `mlpack/src/mlpack/core/tree/cosine_tree/cosine_tree.cpp`, the `begin()` and `end()` method of `boost::heap::priority_queue` is used, which returns an iterator of the container. But `std::priority_queue` does not have such a method and we can't directly access to the container of `std::priority_queue` since it's a protected member, thus the migration can't be done easily.

I looked up some solutions like [this](https://stackoverflow.com/questions/1185252/is-there-a-way-to-access-the-underlying-container-of-stl-container-adaptors) and [this](https://stackoverflow.com/questions/4484767/how-to-iterate-over-a-priority-queue), which define a struct that inherits the `std::priority_queue` class then access the protected member, then return to us.

I tested the returned iterator, I randomly generate some numbers and push them into `boost::heap::priority_queue` and `std::priority_queue`, and use the iterator to iterate over the underlying vector and output. It seems that they are equivalent.

So, this question might be silly, can use this solution to substitute the `begin()`s and `end()`s in cosine_tree.cpp? Since I don't have any software engineering experience, I think it's better to ask if this is acceptable.

**Comment by rcurtin** [comment]
Sorry for the slow response on this!  It took me a while to figure out where the past discussion was, but if you look in the mlpack chat channel archives for Jan. 28th, there was a discussion on this topic.  I'll paste it here:

> *Binesh Munukurthi*
>
> Hey, so I was trying to remove the boost::heap in this [issue](https://github.com/mlpack/mlpack/issues/3095) and I realised that the priority_queue in STL dosen't have an iterator which is necessary for this part of [code](https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/tree/cosine_tree/cosine_tree.cpp#L380).
So, if we want to get the elements in order we might have to empty the whole priority_queue and insert it again which can be computationally heavy 😅.
>
> I've tried looking at other alternatives like using a vector with functions push_heap and pop_heap to maintain the heap structure like the one mentioned [here](https://stackoverflow.com/questions/22368627/iterate-and-modify-c-priority-queue), but we wont get them in order if we simply traverse it.
> Can anyone give some suggestions or advice on this?

> *rcurtin*
>
>  couldn't you just use `top()` and `pop()` to get the elements in order? maybe I overlooked something

> *Binesh Munukurthi*
>
> But then we'll have to send the priority queue (treeQueue) as a copy into the function instead of a reference since it affects the original one, right?

> *rcurtin*
>
> oh, I see, interesting, let me think ...

> *Binesh Munukurthi*
>
> also in the previous case, we used to access all the elements in O(n) time but by popping all the elements it will lead to O(nlogn)

> *rcurtin*
>
> yeah, true (although I wouldn't expect that to be a noticeable performance hit)
> I suppose this is the reason we went with boost's implementation in the first place 😄
> it seems like the best solution here may unfortunately be a little tedious if the STL isn't providing the kind of data structure that we need
> you could use std::map here, and I think it would be fine---you'd need to just make sure that the elements sort by priority
> that may incur some extra O(log N) overhead for some operations, but I don't think it's so huge an issue (I'm also not sure anyone has ever complained about the runtime of the cosine tree)

> *Binesh Munukurthi*
>
> Can we use `std::set` here instead since we are only dealing with single elements?

> *rcurtin*
>
> yeah, I suppose so---all you need is a sorted iterable structure

> *Binesh Munukurthi*
>
> I was mostly fixated on how to use the priority queue in STL and didn't think much about the other data structures.
> Thanks for the help! 👍️

----

Anyway, that conversation was in a different direction than you were taking here, but maybe it is helpful.  At least from my perspective, one thing that's desirable here is the simplicity of the solution.  This code is not known to be a bottleneck, so at least personally I wouldn't worry *too* much about making it as efficient as humanly possible.  Instead, maybe it is better to follow either the idea above of using `std::map` with a custom sorting function, or the suggestion from one of the [links you posted](https://stackoverflow.com/questions/4484767/how-to-iterate-over-a-priority-queue):

> The official work-around is to use a vector instead and manage the priority-ness yourself with make_heap, push_heap and pop_heap.

I hope this is helpful!  Sorry if the conversation pasted out of the chat channel is awkwardly formatted.
