### ISSUE TITLE
Host image in mlpack server of GSoC Idea

### ISSUE THREAD

**Issue by jonpsy** [mlpack/mlpack#3179]
@zoq  Could you please host the following gif?
![example_1](https://user-images.githubusercontent.com/45007169/162232067-b0818d9a-c552-499c-9f3d-5827151cfb05.gif)

**Comment by zoq** [comment]
Looks like you went for the github url, let me know if you still want to have the image uploaded.

**Comment by jonpsy** [comment]
I'd still like to host please
