### ISSUE TITLE
parallelize R binding build

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mlpack/mlpack#3182]
### What is the desired addition or change?

parallelize R bindings build

### What is the motivation for this feature?

for now R bindings are built one file at a time thus making it *very* slow

**Comment by eddelbuettel** [comment]
Locally the general starting point is `~/.R/Makevars`.  One can generally only re-use one's cores so many times I usually get my parallelism when installing multiples packages going across several at once.  I think I did set `MAKEFLAGS` in the past but had issues with _some_ packages so I unset it locally.  

My secret weapon is `ccache` which makes life bearable on rebuilds but for initial builds one does generally have to wait.  (And for R, `ccache` needs some extra settings, I write about that [here](https://dirk.eddelbuettel.com/blog/2017/11/27/).)

`mlpack` is a big package.
