### ISSUE TITLE
algorithm.hpp error

### ISSUE THREAD

**Issue by NBarile** [mlpack/mlpack#3188]
#### Issue description

Hey guys
I Trying to run the exemple code, and i have this issue :
![image](https://user-images.githubusercontent.com/48790575/163416397-a6d17405-f8c4-48d1-bc76-aa76f83ecb4e.png)

Someone know how to resolve it ?

Thanks !

#### Your environment

 * version of mlpack: master branch
 * operating system: win 10
 * compiler: Visual Studio 2022 / Cmake
 * version of dependencies (Boost/Armadillo): Boost : boost_1_78_0-msvc-14.3-64 / Armadillo : 11.0.0

**Comment by zoq** [comment]
I'm pretty sure this is related to the changes from https://github.com/mlpack/mlpack/pull/3006. But I don't have an solution at this point, I'll see if I can reproduce the issue on my side.
