### ISSUE TITLE
Object detection

### ISSUE THREAD

**Issue by NBarile** [mlpack/mlpack#3189]
Hi guys

I have a simple question for you :
Did you know if mlpack can deteco object with a camera ?

I try to find a good library for oject detection, and I didn't see in the doc if mlpack can do that.

Thanks !

Ps: And if you have some exemple to me, please share me :D

**Comment by zoq** [comment]
I don't have a working example I can share, but we have https://github.com/mlpack/models/tree/master/models/yolo which can do object detection, but needs some wrapper code around it to get the camera image and call the model.
