### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'build/lib.linux-x86_64-3.9/mlpack/'  

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mlpack/mlpack#3193]
#### Issue description

I have this build failure

#### Your environment

 * version of mlpack: from git commit de94eee6881e33f1145d9d4a8b5380a5be8af36a
 * operating system: gentoo
 * compiler: gcc (Gentoo 11.2.1_p20220115 p4) 11.2.1 20220115
 * version of dependencies (Boost/Armadillo): boost-1.78.0 armadillo-10.8.2
 * any other environment information you think is relevant:
`cython-0.29.28`
`python-3.9.12`

I have this folder `src/mlpack/bindings/python/build/lib.linux-x86_64-cpython-39/mlpack` instead

#### Steps to reproduce

I'm using an ebuild that is WIP for gentoo overlay guru

#### Expected behavior

Build and install mlpack with python bindings

#### Actual behavior

```
cd /var/tmp/portage/sci-libs/mlpack-3.4.2_p20220408/work/mlpack-de94eee6881e33f1145d9d4a8b5380a5be8af36a/src/mlpack/bindings/python && /var/tmp/portage/sci-libs/mlpack-3.4.2_p20220408/temp/python3.9/bin/python /var/tmp/portage/sci-libs/mlpack-3.4.2_p20220408/work/mlpack-de94eee6881e33f1145d9d4a8b5380a5be8af36a/src/mlpack/bindings/python/copy_artifacts.py
Traceback (most recent call last):
File "/var/tmp/portage/sci-libs/mlpack-3.4.2_p20220408/work/mlpack-de94eee6881e33f1145d9d4a8b5380a5be8af36a/src/mlpack/bindings/python/copy_artifacts.py", line 23, in <module>
    for f in os.listdir(directory):
FileNotFoundError: [Errno 2] No such file or directory: 'build/lib.linux-x86_64-3.9/mlpack/'
make[2]: *** [src/mlpack/bindings/python/CMakeFiles/python.dir/build.make:74: python] Error 1
```

**Comment by zoq** [comment]
Thanks for the detailed report, I can see the same issue on the Linux build - https://dev.azure.com/mlpack/mlpack/_build/results?buildId=7916&view=logs&j=688aac9a-3c6e-57ec-6cd1-1ef0ff8c8547&t=2d971c59-09b9-52a6-559e-1d5f8654a2fe

I'll see if I can dig into this a little bit more.

**Comment by shubham1206agra** [comment]
Hey @Alessandro-Barbieri 

Can you send the output of `python -m sysconfig` ASAP?

**Comment by Alessandro-Barbieri** [comment]
https://gist.github.com/46fc3264f9d3864ca6abf55f791f9fd3

**Comment by shubham1206agra** [comment]
https://github.com/mlpack/mlpack/pull/3198
This will fix it.

**Comment by shubham1206agra** [comment]
@zoq Please close this issue.
