### ISSUE TITLE
Migrate Go to use Go Modules

### ISSUE THREAD

**Issue by shubham1206agra** [mlpack/mlpack#3201]
### What is the desired addition or change?
Right now, builds fail due to the missing version number of the `Gonum` package.
This occurs due to `go list` command returns the version only when we use Go modules.

### What is the motivation for this feature?
Adaption of Go binding to the newer version which by default requires modules.

### If applicable, describe how this feature would be implemented.
https://go.dev/blog/using-go-modules

**Comment by rcurtin** [comment]
This is worked around in #3200, but I agree, Go modules would probably be a better long-term fix. :+1:

**Comment by shubham1206agra** [comment]
Keep open.

**Comment by rcurtin** [comment]
Oops, mlpack-bot didn't listen :smile:

**Comment by DepressedSage** [comment]
Hi! I wanted to ask if anyone is working on this issue, if not I'd like to work on it :)

**Comment by shubham1206agra** [comment]
Yes please go ahead if you know how to do this.

**Comment by DepressedSage** [comment]
I know some basic GOlang so I thought this should help me understand how to use go modules etc better. If possible please do tell me a bit more about issue.
Sorry if this is a dumb question ^^;
