### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by NBarile** [mlpack/mlpack#3203]
Hi guys !
I trying to instal and use mlpack, and I have some problems / questions.
I folow this isntructions to install mlpack : https://www.mlpack.org/doc/stable/doxygen/sample_ml_app.html

1) Include directory:
I didin't find this include : "C:\boost\boost_1_71_0\lib\native\include" 
did you know what is the new include directory for boost ? I only have this files in my boost directory : 
![image](https://user-images.githubusercontent.com/48790575/167020319-bea258e3-d73d-4df6-8c58-a650fc5e0a38.png)

2) cereal error
When I trying to build the solutions, I have few errors with cereal (I think)
![image](https://user-images.githubusercontent.com/48790575/167020453-5a0744f9-bb4b-4cfb-8333-21df0dcbea91.png)
And so, i didn't know how to resolve it. I notice I had to download cereal to compile mlpackl with Cmake.

If you need more information, please ask me :D

Thanks a lot !

**Comment by rcurtin** [comment]
I think you need to ensure that cereal is in the set of include directories for your CNN project.

Also, luckily, the next version of mlpack will not have Boost at all, so we will be able to remove it from the build directions entirely. :)  In your case is there a `native/include/` directory under `lib64-msvc-14.3`?  Or maybe just `boost/` has the Boost headers?  Whichever directory has the headers of Boost is the one that you want. :+1:
