### ISSUE TITLE
Fix Broken Links to Documentation in README.md

### ISSUE THREAD

**Issue by Ansh-Sarkar** [mlpack/mlpack#3209]
#### Problem location

https://github.com/mlpack/mlpack/blob/master/README.md

#### Description of problem

Hi. I was trying to get started with the **Build From Source** steps, links to which are provided in the [README.md](https://github.com/mlpack/mlpack/blob/master/README.md) file in the root directory of the repository. It seems that a few of the links are broken, and hence result in a ```404 Page Not Found``` error .

Given below are the specific lines in the [README.md](https://github.com/mlpack/mlpack/blob/master/README.md) file along with the corrected URLs.

- [ ] Line 10   : https://www.mlpack.org/doc/mlpack-git/doxygen/index.html
       Correct URL : https://www.mlpack.org/doc/stable/doxygen/index.html

- [ ] Line 73   : https://www.mlpack.org/doc/mlpack-git/doxygen/tutorials.html
       Correct URL : https://www.mlpack.org/doc/stable/doxygen/tutorials.html

- [ ] Line 75   : https://www.mlpack.org/doc/mlpack-git/doxygen/index.html
       Correct URL : https://www.mlpack.org/doc/stable/doxygen/index.html

- [ ] Line 169 : https://www.mlpack.org/doc/mlpack-git/doxygen/build.html
       Correct URL : https://www.mlpack.org/doc/stable/doxygen/build.html

- [ ] Line 170 : https://www.mlpack.org/doc/mlpack-git/doxygen/build_windows.html
       Correct URL : https://www.mlpack.org/doc/stable/doxygen/build_windows.html

- [ ] Line 237 : https://www.mlpack.org/doc/mlpack-git/doxygen/build.html#build_config
       Correct URL : https://www.mlpack.org/doc/stable/doxygen/build.html#build_config

- [ ] Line 369 : https://www.mlpack.org/doc/mlpack-git/doxygen/tutorials.html
       Correct URL : https://www.mlpack.org/doc/stable/doxygen/tutorials.html

- [ ] Line 371 : https://www.mlpack.org/doc/mlpack-git/doxygen/index.html
       Correct URL : https://www.mlpack.org/doc/stable/doxygen/index.html

#### Extra Suggestions
```
383 | Github is used for bug tracking, and can be found at
384 | https://github.com/mlpack/mlpack/.
385 | It is easy to register an account and file a bug there, and the mlpack
386 | development team will try to quickly resolve your issue.
```
Do you think it would be a good idea to change the URL in line 384 : https://github.com/mlpack/mlpack to https://github.com/mlpack/mlpack/issues ? Because otherwise upon clicking the link, it takes you back to the same README.md page.

**Comment by Ansh-Sarkar** [comment]
Would love to fix this issue as my first contribution to the community.

**Comment by rcurtin** [comment]
Thanks for the report @Ansh-Sarkar!  What is actually happening here is that the mlpack-git doxygen build is failing:

http://ci.mlpack.org/job/mlpack - doxygen build/

I'll work on fixing that now, and then all the dead URLs should be fixed.

But, for your last comment, I agree, the issues link would be better than the repository URL, for exactly the reason you mention.  If you want to open a PR for that, please feel free!

**Comment by Ansh-Sarkar** [comment]
Oh ok. Sure. I'll open a PR for the change in the issues link right away. Thank You !

**Comment by rcurtin** [comment]
Thanks for opening the PR!  The doxygen build completed, so now all the URLs you pointed out are working. :+1:  Thanks again for the report!
