### ISSUE TITLE
Fixing Rest of the Broken Links in Documentation

### ISSUE THREAD

**Issue by Ansh-Sarkar** [mlpack/mlpack#3211]
#### Problem location

https://github.com/mlpack/mlpack - Exact locations are provided in the description of the issue.

#### Broken Links

Have been going through the ```mlpack``` , ```ensmallen``` and ```armadillo``` documentations. Stumbled across a few more links which seem to be broken or unreachable. Did a quick check of the other parts of the documentation as well.

https://mlpack.org/help.html gives a ```404 Not Found``` Error. Can replace it to point to : https://www.mlpack.org/docs.html
https://github.com/mlpack/mlpack/blob/9daf24f787b8497fd5ccc0f5ef2771cf0ce6248b/.github/ISSUE_TEMPLATE/2-question.md?plain=1#L13

https://gym.openai.com/envs/Acrobot-v1 gives a ```404 Not Found``` Error. 
Can replace with : https://www.gymlibrary.ml/environments/classic_control/acrobot
https://github.com/mlpack/mlpack/blob/9daf24f787b8497fd5ccc0f5ef2771cf0ce6248b/src/mlpack/methods/reinforcement_learning/environment/acrobot.hpp#L6

https://gym.openai.com/envs/CartPole-v0 gives a ```404 Not Found``` Error.
Can replace with : https://www.gymlibrary.ml/environments/classic_control/cart_pole
https://github.com/mlpack/mlpack/blob/9daf24f787b8497fd5ccc0f5ef2771cf0ce6248b/src/mlpack/methods/reinforcement_learning/environment/cart_pole.hpp#L6

https://gym.openai.com/envs/MountainCarContinuous-v0 gives a ```404 Not Found``` Error.
Can replace with : https://www.gymlibrary.ml/environments/classic_control/mountain_car_continuous
https://github.com/mlpack/mlpack/blob/9daf24f787b8497fd5ccc0f5ef2771cf0ce6248b/src/mlpack/methods/reinforcement_learning/environment/continuous_mountain_car.hpp#L7

https://gym.openai.com/envs/MountainCar-v0 gives a ```404 Not Found``` Error.
Can replace with : https://www.gymlibrary.ml/environments/classic_control/mountain_car
https://github.com/mlpack/mlpack/blob/9daf24f787b8497fd5ccc0f5ef2771cf0ce6248b/src/mlpack/methods/reinforcement_learning/environment/mountain_car.hpp#L6

https://gym.openai.com/envs/Pendulum-v0 gives a ```404 Not Found``` Error.
Can replace with : https://www.gymlibrary.ml/environments/classic_control/pendulum/
https://github.com/mlpack/mlpack/blob/9daf24f787b8497fd5ccc0f5ef2771cf0ce6248b/src/mlpack/methods/reinforcement_learning/environment/pendulum.hpp#L6

#### Unreachable Links

The site : https://rmf.io/cxx11/almost-static-if , cannot be reached.
https://github.com/mlpack/mlpack/blob/9daf24f787b8497fd5ccc0f5ef2771cf0ce6248b/src/mlpack/bindings/cli/third_party/CLI/CLI11.hpp#L906

**Comment by Ansh-Sarkar** [comment]
@shrit @zoq Any suggestions as to which links can replace https://rmf.io/cxx11/almost-static-if ? Or should we leave that as is.

**Comment by rcurtin** [comment]
Thanks for going through and finding these issues!

The comment in CLI11.hpp is a third-party library, so there's no reason for us to fix it.  We can just leave it as-is.

I can't comment on any of the gym.openai.com links, but I think https://www.mlpack.org/questions.html might be a better replacement for `help.html`.
