### ISSUE TITLE
[R] Package installation on aarch64 fails

### ISSUE THREAD

**Issue by benz0li** [mlpack/mlpack#3213]
#### Issue description

R Package installation fails: https://dl.b-data.ch/cran-install-all/aarch64/fpic/out/mlpack.out

#### Your environment

 * version of mlpack: 3.4.2
 * operating system: Debian 11 (bullseye)
 * architecture: aarch64
 * compiler: gcc
 * version of dependencies (Boost/Armadillo):
     *  Boost: 1.78
     *  Armadillo: 11.0.0
 * any other environment information you think is relevant:
     *  `*PICFLAGS` are set to `-fpic` in `/usr/local/lib/R/etc/Makeconf`.

#### Steps to reproduce

```bash
docker run --rm -ti registry.gitlab.b-data.ch/r/geospatial:4.1.3 bash -c "Rscript -e 'install.packages(\"mlpack\")'"
```

#### Expected behavior

Installation of R package succeeds.

#### Actual behavior

Installation of R package fails.

**Comment by benz0li** [comment]
Cross reference: https://bugs.r-project.org/show_bug.cgi?id=18326

**Comment by benz0li** [comment]
#### Workarounds

---

Compile R itself using `-fPIC`, as I have done with 4.2.0, so

```
docker run --rm -ti registry.gitlab.b-data.ch/r/geospatial:4.2.0 bash -c "Rscript -e 'install.packages(\"mlpack\")'"
```

succeeds.

---

Olivier Benz, 2022-05-02 09:08:27 UTC

> (In reply to Martin Maechler from [comment #18](https://bugs.r-project.org/show_bug.cgi?id=18326#c18))
> 
> > So couldn't the package maintainer of such large packages, e.g. Hannes for `duckdb` not simply add a line such as
> > ```
> > PKG_CXXFLAGS = -fPIC
> > ```
> > to the package specific `src/Makevars` file?
> 
> Yes he could.

– https://bugs.r-project.org/show_bug.cgi?id=18326#c19

The same goes for `mlpack`.

**Comment by benz0li** [comment]
Neither fixed in R source nor here.

**Comment by rcurtin** [comment]
Yes, sorry, haven't had a chance to look into this yet.

**Comment by benz0li** [comment]
Keeping the mlpack-bot happy...

**Comment by benz0li** [comment]
Martin Maechler, 2022-08-05 20:08:58 UTC

> Now committed such a [minimal change](https://github.com/r-devel/r-svn/commit/9f1a18466e218fac523390c3a8eb4730e03dd51e) to `configure.ac` (and `configure`).
> 
> A more daring change would removed (almost?) all of these non-defaults from  configure.ac and let default configuration "figure it out" or at least only listed the (few but very important) cases where to choose `-fpic` explicitly ...

– https://bugs.r-project.org/show_bug.cgi?id=18326#c22

**Comment by benz0li** [comment]
Will be fixed with the next minor release of R (4.2.2) as `*PICFLAGS` are now set to `-fPIC` for aarch64.

**Comment by rcurtin** [comment]
Just checking, it sounds here like on the mlpack side we don't need to do anything, and things will work when R 4.2.2 is released.  Is that correct?

**Comment by benz0li** [comment]
> Just checking, it sounds here like on the mlpack side we don't need to do anything, and things will work when R 4.2.2 is released. Is that correct?

That is correct.

**Comment by rcurtin** [comment]
Hey @benz0li, is there any way to see if this problem still exists?  mlpack 4.0.0 just got pushed to CRAN, and I wonder if some of the changes we made there might fix the problems you were seeing here (specifically, the fact that mlpack now has fewer dependencies and the main library itself is header-only).

**Comment by benz0li** [comment]
> Hey @benz0li, is there any way to see if this problem still exists?

Yes.

```R
docker run --rm -ti registry.gitlab.b-data.ch/r/geospatial:4.1.3 bash -c "Rscript -e 'options(repos = c(CRAN=\"https://cloud.r-project.org\")); install.packages(\"mlpack\")'"
```

> mlpack 4.0.0 just got pushed to CRAN, and I wonder if some of the changes we made there might fix the problems you were seeing here (specifically, the fact that mlpack now has fewer dependencies and the main library itself is header-only).

Installation of R package now succeeds on `linux/arm64/v8`.

---

#### My environment

 * version of mlpack: 4.0.0
 * operating system: Debian 11 (bullseye)
 * architecture: aarch64
 * compiler: gcc
 * version of dependencies (Boost/Armadillo):
     *  Boost: 1.78
     *  Armadillo: 11.0.0
 * any other environment information you think is relevant:
     *  `*PICFLAGS` are set to `-fpic` in `/usr/local/lib/R/etc/Makeconf`.

**Comment by benz0li** [comment]
Thank you @rcurtin

**Comment by rcurtin** [comment]
Awesome, great to hear! :+1:
