### ISSUE TITLE
Boost error

### ISSUE THREAD

**Issue by Userthatsnamed** [mlpack/mlpack#3221]
Using vs22, msvc, on Windows 10.
I'm getting the error Lnk1104 that says cannot open file libboost serialization vc140... I'm using 143 packages and I can't find anything to fix this error, I have tried basically every answer I could find but it's still there.
I have downloaded mlpack-3.4.2.msi.. and I'm wondering if it's only wanting 140, so is upgrading to 143 packages making it not compatible with mlpack?

**Comment by rcurtin** [comment]
Is it possible for you to use the git master branch?  We removed Boost as a dependency, so this problem you are encountering wouldn't exist. :)
