### ISSUE TITLE
Approximate nearest neighbor search

### ISSUE THREAD

**Issue by ThyrixYang** [mlpack/mlpack#3223]
Hi,

I remember that there is an efficient approximate nearest neighbor search module
in the ann namespace. However, I found that ann is replaced with artificial neural networks. In the neighbor namespace, I found a [RASearch](https://www.mlpack.org/doc/stable/doxygen/classmlpack_1_1neighbor_1_1RASearch.html) class. However, the document writes that "This class provides a generic manner to perform rank-approximate search via random-sampling". 
I remember that there is a implementation of ball-tree or dual-tree in mlpack,
but where are they now?

**Comment by rcurtin** [comment]
Hey @ThyrixYang, long time no see!  Hope things are well.  You can use the `NeighborSearch` class to do approximate search; the constructor allows you to specify an `epsilon` parameter that corresponds to the allowed relative error:

https://www.mlpack.org/doc/stable/doxygen/classmlpack_1_1neighbor_1_1NeighborSearch.html#affa7257868588792956a7f30493ae564

By default this will use dual-tree kd-tree search, but you can tune that to use, e.g., ball trees or similar, using the template parameters to `NeighborSearch`.

I hope this helps!  Let me know if I can clarify anything. :+1:
