### ISSUE TITLE
: error LNK2001: unresolved external symbol "__declspec(dllimport) class std::mersenne_twister_engine

### ISSUE THREAD

**Issue by newlinhan** [mlpack/mlpack#3227]
these are my code
`mode->rf_.Train(data, labels, numClasses, mode->num_trees_, mode->minimum_leaf_size_, mode->minimum_gain_split_, mode->maximum_depth_, mrds);`

these are my configs
![image](https://user-images.githubusercontent.com/67506097/174002243-109753c4-9507-4ed8-872a-7a896cdf0384.png)

![image](https://user-images.githubusercontent.com/67506097/174002363-125c07c8-7f89-4c1b-83f2-5a44874f1ce1.png)

![image](https://user-images.githubusercontent.com/67506097/174002440-de6b32d6-f8b3-44ef-be7c-663a93a5623e.png)

When I use the Train method of RandomForests, there will be the following error

: error LNK2001: unresolved external symbol "__declspec(dllimport) class std::mersenne_twister_engine<unsigned int,32,624,397,31,2567483615,11,4294967295,7,2636928640,15,4022730752,18,1812433253> mlpack::math::randGen" (__imp_?randGen@math@mlpack@@3V?$mersenne_twister_engine@I$0CA@$0CHA@$0BIN@$0BP@$0JJAILANP@$0L@$0PPPPPPPP@$06$0JNCMFGIA@$0P@$0OPMGAAAA@$0BC@$0GMAHIJGF@@std@@A)
 : error LNK2001: unresolved external symbol "__declspec(dllimport) class std::uniform_real_distribution<double> mlpack::math::randUniformDist" (__imp_?randUniformDist@math@mlpack@@3V?$uniform_real_distribution@N@std@@A)
: unresolved external symbol "public: static void __cdecl mlpack::Timer::Start(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Start@Timer@mlpack@@SAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
 error LNK2001: unresolved external symbol "public: static void __cdecl mlpack::Timer::Start(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Start@Timer@mlpack@@SAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
 : error LNK2001: unresolved external symbol "public: static void __cdecl mlpack::Timer::Stop(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Stop@Timer@mlpack@@SAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)

my compilation environment is vs2017,after using the vcpkg integrate install command of vcpkg, the above problem can be solved, but if I want to package my program into a dll file, after using the train of RandomForests, there will be a problem that the dynamic library cannot be loaded
![image](https://user-images.githubusercontent.com/67506097/174003940-dcaca848-bad0-409d-b00f-c9c32bad2118.png)

**Comment by rcurtin** [comment]
Based on the linking errors you gave, it seems like you are not linking against `mlpack.lib`?

For the runtime error, you may have to distribute the DLL dependencies of your DLL if you can't count on it being available on your user's system.  We do this for the mlpack MSI: we include all the DLLs you listed in the screenshot in the same directory as the command-line programs like `mlpack_random_forest.exe` and similar.

I hope this helps---I am not a Windows user, but hopefully some of the things I have learned over the years about Windows compilation can help here. :)

**Comment by newlinhan** [comment]
> 

Thank you very much for your answer, I solved my problem according to your method Thank you
