### ISSUE TITLE
Namespace mlpack::ann not declared error

### ISSUE THREAD

**Issue by Tanishq-Banyal** [mlpack/mlpack#3237]
```
error: 'mlpack::ann' has not been declared
   44 |     mlpack::ann::FFN<> model;
      |             ^~~
```

I installed mlpack on Ubuntu ARM, using `apt install libmlpack-dev`.

And i am including `mlpack/core.hpp`, and linking to `-lmlpack -fopenmp`, but I keep getting this error. Tried both GCC and Clang. What am i doing wrong ?

**Comment by rcurtin** [comment]
You'll also need to `#include <mlpack/methods/ann/ffn.hpp>`. :+1:

**Comment by Tanishq-Banyal** [comment]
Is there a header that includes everything mlpack has to offer ?

if not, what are the main headers i should include in mlpack ?

**Comment by Tanishq-Banyal** [comment]
Ok, One more question.

I have my input data as well as output data as `arma::Col<int8_t>`.

How do I use `int8_t` for input and output layer, while using `float` for layers in-between.

I don't want to use `double` for  everything because its totally unnecessary and also I am low on memory.

**Comment by shrit** [comment]
@Tanishq-Banyal I do not think that this is supported right now.
Are you low on memory for training ? Or for prediction?
If you would like, you can open an issue, so someone can pick it up and add it as a feature
