### ISSUE TITLE
Question about the Gini impurity used in Hoeffding Tree

### ISSUE THREAD

**Issue by DylanWangWQF** [mlpack/mlpack#3246]
To select the best attribute from the remained attributes at a leaf node, we would calculate the information gains for all remained attributes and compare the difference between the two best information gain values with the hoeffding bound. 

Formally, $G(a)-G(b)>\epsilon$, where $a$ and $b$ are the best and second-best attributes, $\epsilon$ is the hoeffding bound.

For information gain, $G(a)$ and $G(b)$ should be the highest and second-highest values.

But for Gini index, as we know, we would select the attribute with the smallest value as the best attribute in the general decision tree algorithm (CART).

So, **my question** is: if we choose Gini index as our split strategy in building a hoeffding tree, do we need to select the smallest and second-smallest values and then compare the difference with the hoeffding bound?

But in [existing hoeffding tree code ](https://github.com/mlpack/mlpack/blob/0259155841c48d5497c80db405cbc6ffc0100a42/src/mlpack/methods/hoeffding_trees/hoeffding_tree_impl.hpp) in this project , it seems that we would choose the highest and second-highest values for either information gain or gini index.

**Comment by SuvarshaChennareddy** [comment]
According to this [paper](https://homes.cs.washington.edu/~pedrod/papers/kdd00.pdf), `G` is a split evaluation function and could be either information gain OR Gini index.

**Comment by DylanWangWQF** [comment]
@SuvarshaChennareddy  Yes, I know this paper. In the general decision tree, we would choose the attribute with the highest information gain value while with the smallest Gini index value. 

That paper stated that we need to get the top two **_best_** attributes.  For information gain, **_best_** attributes are the attributes with the highest and second-highest values. But for the Gini index, **_best_** attributes are the attributes with the smallest and second-smallest values.

So in the implementation of using Gini index in the Hoeffding Tree, we should select the smallest and second-smallest values rather than the  highest and second-highest values.

**Comment by SuvarshaChennareddy** [comment]
I think the `G` here is the Gini gain. Gini gain is measure that is to be maximized like information gain.

**Comment by rcurtin** [comment]
@SuvarshaChennareddy is exactly right here---we are implicitly inverting the G by subtracting the children's gains from the parent gain, on lines 44-49 and 64-65.  As a result, we return the largest value (which is what the Hoeffding tree will select for) when the child gains are minimized. :+1:

**Comment by DylanWangWQF** [comment]
I get it. Thanks for your answer! @SuvarshaChennareddy  @rcurtin
