### ISSUE TITLE
Setting up development environment for mlpack

### ISSUE THREAD

**Issue by gaurav-bhardwaj29** [mlpack/mlpack#3248]
Hey! Wanted to ask how to set up a **development environment** for mlpack in ubuntu? I have installed mlpack using : $ sudo apt-get install libmlpack-dev and installed python dependencies and build it from source. What to do next? How to contribute and develop?

**Comment by conradsnicta** [comment]
@gaurav-bhardwaj29 You may want to uninstall libmlpack-dev.  It's an ancient version from 2 years ago (the codebase has changed considerably).  Instead get the master branch from the git repo.  Recommend to also install the latest versions of dependencies: armadillo, openblas, etc.

To contribute, implement a useful ML algorithm (or improve an existing one already in mlpack) and create a pull request directly at GitHub.  The proposed code should follow the existing style guidelines, and have associated tests.  If you're not familiar with how to use git, suggest to read through a few tutorials about git beforehand.

**Comment by gaurav-bhardwaj29** [comment]
I should build mlpack from the source or download the library directly?

**Comment by conradsnicta** [comment]
Build from source.  The source is the master branch of the git repo.

    git clone https://github.com/mlpack/mlpack.git
    cd mlpack
    mkdir build
    cd build
    cmake ..
    make -j 4
    sudo make install

In "make -j 4", change the 4 to the number of cores in your CPU.

* Armadillo: http://arma.sourceforge.net/download.html
* ensmallen: https://ensmallen.org/
* OpenBLAS: the pre-built development package that comes with Ubuntu / Fedora / Debian should be sufficient (named "openblas-dev" or similar); if a newer version is required, see https://github.com/xianyi/OpenBLAS/releases
* Cereal: the pre-built package that comes with Ubuntu / Fedora / Debian should be sufficient

For other dependencies, see the mlpack documentation: README.md and https://mlpack.org

**Comment by gaurav-bhardwaj29** [comment]
Hey, I followed the instructions and tried to build the library. When I passed `cmake ../` 
`gaurav@gb-dev:~/mlpack-3.4.2/build$ cmake ../
-- cotire 1.7.10 loaded.
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (LIBBFD)
  does not match the name of the calling package (Bfd).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  CMake/FindBfd.cmake:82 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:240 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at CMakeLists.txt:585 (message):
  txt2man not found; man pages will not be generated.


-- Julia not found (missing: JULIA_EXECUTABLE) (Required is at least version "0.7.0")
-- Julia not found; not building Julia bindings.
-- Not building Markdown bindings.
-- Not building Python bindings.
-- Go not found (missing: GO_EXECUTABLE) (Required is at least version "1.11.0")
-- Gonum not found (missing: GONUM_VERSION_STRING) 
-- Not building Go bindings; the following modules are not available: 
    - Go
    - Gonum
-- R not found (missing: R_EXECUTABLE) (Required is at least version "4.0")
-- Could NOT find R_roxygen2 (missing: R_ROXYGEN2) 
-- Could NOT find R_Rcpp (missing: R_RCPP) 
-- Could NOT find R_RcppArmadillo (missing: R_RCPPARMADILLO) 
-- Could NOT find R_RcppEnsmallen (missing: R_RCPPENSMALLEN) 
-- Could NOT find R_BH (missing: R_BH) 
-- Could NOT find R_testthat (missing: R_TESTTHAT) 
-- Not building R bindings, Following modules are not available:
    - R
    - roxygen2
    - Rcpp
    - RcppArmadillo
    - RcppEnsmallen
    - BH
    - testthat
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/GNUInstallDirs.cmake:376 (message):
  GNUInstallDirs_get_absolute_install_dir called without third argument.
  Using ${dir} from the caller's scope for compatibility with CMake 3.19 and
  below.
Call Stack (most recent call first):
  src/mlpack/CMakeLists.txt:166 (GNUInstallDirs_get_absolute_install_dir)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake-3.22/Modules/GNUInstallDirs.cmake:376 (message):
  GNUInstallDirs_get_absolute_install_dir called without third argument.
  Using ${dir} from the caller's scope for compatibility with CMake 3.19 and
  below.
Call Stack (most recent call first):
  src/mlpack/CMakeLists.txt:167 (GNUInstallDirs_get_absolute_install_dir)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Configuring done
CMake Warning (dev) at src/mlpack/CMakeLists.txt:22 (add_library):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

    /home/gaurav/mlpack-3.4.2/src/mlpack/methods/ann/gan/metrics/inception_score.hpp
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/mlpack/CMakeLists.txt:22 (add_library):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

    /home/gaurav/mlpack-3.4.2/src/mlpack/methods/ann/gan/metrics/inception_score_impl.hpp
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/gaurav/mlpack-3.4.2/build
`
And when I passed **make -j4** (as there are 4 cores in the CPU), the terminal crashed and closed halfway, and it is happening every time I run (I have attached the last few lines of the snippet below):
```
gaurav@gb-dev:~/mlpack-3.4.2/build$ make -j4
[ 58%] Built target mlpack_test
[ 58%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/binarize_test.cpp.o
cc1plus: warning: /home/gaurav/mlpack-3.4.2/build/src/mlpack/tests/cotire/mlpack_catch_test_CXX_prefix.hxx.gch: created with -gnone, but used with -gdwarf-2 [-Winvalid-pch]
cc1plus: warning: /home/gaurav/mlpack-3.4.2/build/src/mlpack/tests/cotire/mlpack_catch_test_CXX_prefix.hxx.gch: created with -gnone, but used with -gdwarf-2 [-Winvalid-pch]
cc1plus: warning: /home/gaurav/mlpack-3.4.2/build/src/mlpack/tests/cotire/mlpack_catch_test_CXX_prefix.hxx.gch: created with -gnone, but used with -gdwarf-2 [-Winvalid-pch]
cc1plus: warning: /home/gaurav/mlpack-3.4.2/build/src/mlpack/tests/cotire/mlpack_catch_test_CXX_prefix.hxx.gch: created with -gnone, but used with -gdwarf-2 [-Winvalid-pch]
[ 58%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/block_krylov_svd_test.cpp.o
cc1plus: warning: /home/gaurav/mlpack-3.4.2/build/src/mlpack/tests/cotire/mlpack_catch_test_CXX_prefix.hxx.gch: created with -gnone, but used with -gdwarf-2 [-Winvalid-pch]
[ 58%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/cf_test.cpp.o
cc1plus: warning: /home/gaurav/mlpack-3.4.2/build/src/mlpack/tests/cotire/mlpack_catch_test_CXX_prefix.hxx.gch: created with -gnone, but used with -gdwarf-2 [-Winvalid-pch]
[ 58%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/cli_binding_test.cpp.o
cc1plus: warning: /home/gaurav/mlpack-3.4.2/build/src/mlpack/tests/cotire/mlpack_catch_test_CXX_prefix.hxx.gch: created with -gnone, but used with -gdwarf-2 [-Winvalid-pch]
```

**Comment by conradsnicta** [comment]
@gaurav-bhardwaj29 Don't use mlpack 3.4.2, as it's seriously outdated and no longer maintained.  Instead, get the latest sources from the master branch at GitHub (git clone https://github.com/mlpack/mlpack.git)

mlpack (especially old versions like 3.4.2) may require a lot of memory to compile, so using all 4 cores may quickly exhaust your memory. In turn, this may lead to the terminal crashing and/or closing.

Change -j4 to -j2 or even -j1 if you don't have enough memory.

**Comment by gaurav-bhardwaj29** [comment]
As you mentioned, I cloned the repo and changed to -j2, and now it's working. Lastly, how do you add the executables to PATH and how to call them directly? I am using Pycharm
