### ISSUE TITLE
@conradsnicta As you mentioned, I cloned the repo and changed to -j2, and now it's working. Lastly, how do you add the executables to PATH and how to call them directly? I am using Pycharm and want to import the library.

### ISSUE THREAD

**Issue by gaurav-bhardwaj29** [mlpack/mlpack#3251]
@conradsnicta As you mentioned, I cloned the repo and changed to -j2, and now it's working. Lastly, how do you add the executables to PATH and how to call them directly? I am using Pycharm and want to import the library.

_Originally posted by @gaurav-bhardwaj29 in https://github.com/mlpack/mlpack/issues/3248#issuecomment-1200113995_

**Comment by conradsnicta** [comment]
This is not a bug report.  Try posting your questions to the mailing list: https://www.mlpack.org/mailman/listinfo/mlpack 
You can also try the online chat; see the links at https://www.mlpack.org/community.html
