### ISSUE TITLE
Error 2 in making mlpack

### ISSUE THREAD

**Issue by iajzenszmi** [mlpack/mlpack#3253]
#### Issue description
rom /home/ian/mlpack/mlpack-3.4.2/src/mlpack/tests/main.cpp:16:
/home/ian/mlpack/mlpack-3.4.2/src/mlpack/tests/catch.hpp:7947:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
 7947 |     constexpr static std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/boost/config/stdlib/libstdcpp3.hpp:78,
                 from /usr/include/boost/config.hpp:48,
                 from /usr/include/boost/serialization/serialization.hpp:13,
                 from /home/ian/mlpack/mlpack-3.4.2/src/mlpack/prereqs.hpp:86,
                 from /home/ian/mlpack/mlpack-3.4.2/src/mlpack/core.hpp:67,
                 from /home/ian/mlpack/src/mlpack/tests/cotire/mlpack_catch_test_CXX_prefix.cxx:4,
                 from /home/ian/mlpack/src/mlpack/tests/cotire/mlpack_catch_test_CXX_prefix.hxx:4:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from /home/ian/mlpack/mlpack-3.4.2/src/mlpack/tests/main.cpp:16:
/home/ian/mlpack/mlpack-3.4.2/src/mlpack/tests/catch.hpp:8006:45: error: size of array ‘altStackMem’ is not an integral constant-expression
 8006 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
make[2]: *** [src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/build.make:871: src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6441: src/mlpack/tests/CMakeFiles/mlpack_catch_test.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
(23:47 ian@ian-Aspire-One-753 mlpack)

#### Your environment

 * version of mlpack: as on github
 * operating system: linux Ubuntu
 * compiler:g++ / gcc
 * version of dependencies (Boost/Armadillo):
 * any other environment information you think is relevant:

**Comment by conradsnicta** [comment]
This is a know problem with old versions of the catch header, which is included with mlpack-3.4.2.  That version of mlpack is rather old and outdated at this stage.  Suggest that you instead obtain mlpack from the git master branch.

**Comment by conradsnicta** [comment]
See #3090 for more details
