### ISSUE TITLE
Compile error when #include <mlpack/methods/reinforcement_learning/q_learning.hpp>

### ISSUE THREAD

**Issue by richelbilderbeek** [mlpack/mlpack#3274]
#### Issue description

One gets a compile error when `#include <mlpack/methods/reinforcement_learning/q_learning.hpp>`.

#### Your environment

 * version of mlpack: 3 (installed with `apt`)
 * operating system: Ubuntu 22.04 Jammy Jellyfish LTS
 * compiler: g++
 * version of dependencies (Boost/Armadillo): 1.74  (installed with `apt`) 22 (installed with `apt`)
 * any other environment information you think is relevant: -

#### Steps to reproduce

```c++
#include <mlpack/core.hpp>
#include <mlpack/methods/reinforcement_learning/q_learning.hpp>

int main() { }
```

Note that this code is a simplified version from [https://www.mlpack.org/doc/stable/doxygen/rltutorial.html](https://www.mlpack.org/doc/stable/doxygen/rltutorial.html). I really went to the minimum here.

Also, this code can be found [here](https://github.com/richelbilderbeek/mlpack_example_2/blob/develop/main.cpp) with the GitHub Actions output log [here](https://github.com/richelbilderbeek/mlpack_example_2/actions/runs/3058558412/jobs/4934901468) and screenshot here:

![Screenshot from 2022-09-15 09-31-14](https://user-images.githubusercontent.com/2098230/190342805-0685f10b-8338-496d-be2a-14ca1a05d7cc.png)

#### Expected behavior

It should compile or give a clear error.

Note that [SF.11: Header files should be self-contained](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rs-contained), so ideally my reprex would be just `#include <mlpack/methods/reinforcement_learning/q_learning.hpp>`, where this file includes `mlpack/core.hpp` itsel.

#### Actual behavior

Compiling fails, with output:

```
/usr/bin/make -f Makefile.Release
make[1]: Entering directory '/home/richel/GitHubs/mlpack_example_2'
g++ -c -pipe -std=c++17 -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic -fopenmp -O2 -std=gnu++1z -Wall -Wextra -fPIC -DNDEBUG -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o release/main.o main.cpp
In file included from /usr/include/mlpack/methods/reinforcement_learning/q_learning.hpp:190,
                 from main.cpp:2:
/usr/include/mlpack/methods/reinforcement_learning/q_learning_impl.hpp: In member function ‘void mlpack::rl::QLearning<EnvironmentType, NetworkType, UpdaterType, PolicyType, ReplayType>::TrainAgent()’:
/usr/include/mlpack/methods/reinforcement_learning/q_learning_impl.hpp:188:3: error: ‘updatePolicy’ was not declared in this scope
  188 |   updatePolicy->Update(learningNetwork.Parameters(), config.StepSize(),
      |   ^~~~~~~~~~~~
/usr/include/mlpack/methods/reinforcement_learning/q_learning_impl.hpp: In member function ‘void mlpack::rl::QLearning<EnvironmentType, NetworkType, UpdaterType, PolicyType, ReplayType>::TrainCategoricalAgent()’:
/usr/include/mlpack/methods/reinforcement_learning/q_learning_impl.hpp:299:3: error: ‘updatePolicy’ was not declared in this scope
  299 |   updatePolicy->Update(learningNetwork.Parameters(), config.StepSize(),
      |   ^~~~~~~~~~~~
make[1]: Leaving directory '/home/richel/GitHubs/mlpack_example_2'
make[1]: *** [Makefile.Release:197: release/main.o] Error 1
make: *** [Makefile:42: release] Error 2
09:12:53: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project mlpack_example_2 (kit: Desktop)
When executing step "Make"
09:12:53: Elapsed time: 00:14.
```

**Comment by conradsnicta** [comment]
mlpack 3 is outdated and no longer maintained.  Suggest that you obtain the current development version from the git master branch, and retry your code on that.

**Comment by rcurtin** [comment]
I think if you are able to use the git master branch, you should hopefully have an easier time too---the headers have all been simplified very much, so you should be able to just `#include <mlpack.hpp>` and have no further issues.  There are some other changes there before we release mlpack 4 too, like flattening all namespaces so that everything is in `mlpack::` (but that is [not merged yet](https://github.com/mlpack/mlpack/pull/3269)).

**Comment by richelbilderbeek** [comment]
Sounds great, thanks for the help!

(of course, it is weird that is error was present in version 3, but hey, let's move on :-) )
