### ISSUE TITLE
linux GCC mlpack-3.4.2 make failed:undefined reference to `arma::mt19937_64_instance'

### ISSUE THREAD

**Issue by zzy728772024** [mlpack/mlpack#3280]
#### Issue description

when I built mlpack-3.4.2 on my server ,I met this problem:

/usr/bin/ld: ../../../../lib/libmlpack.so.3.4: undefined reference to `arma::mt19937_64_instance'
/usr/bin/ld: ../../../../lib/libmlpack.so.3.4: undefined reference to `TLS init function for arma::mt19937_64_instance'

#### Your environment

 * version of mlpack: 3.4.2
 * operating system: ubuntu1~20.04.1
 * compiler:GCC 9.4.0
 * version of dependencies (Boost/Armadillo): Boost :1.71.0 ; Armadillo: 10.8.2
 * any other environment information you think is relevant: no

#### Steps to reproduce

I use cmake to build malpack from source code, after cmake successfully, when I make it, the problem will appear .

#### Expected behavior

make successfully.

#### Actual behavior

make failed.

Thanks very much!
![makeerror](https://user-images.githubusercontent.com/65691551/191652433-16f47e25-5a96-4370-b168-ef78cc9feca8.png)

**Comment by conradsnicta** [comment]
mlpack 3 is outdated and no longer maintained. Suggest that you obtain the current development version from the git master branch.  When compiling your code, link with armadillo.

**Comment by zzy728772024** [comment]
Thanks for conradsnicta!  Since I am not a root user, I compiled from source code, and I compiled Armadillo without pre-compiling and installing OpenBLAS and LAPACK, which caused the problem.
