### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by mkleanthous** [mlpack/mlpack#3295]
Hello,

I used to be able to download the dataset from here http://www.mlpack.org/datasets/ml-20m/ratings-only.csv.gz but not seems that the whole folder is gone. Did it moved to another location? Is there a way to download those again?

Thanks,
Marios

**Comment by rcurtin** [comment]
You're right!  I am looking into it now.  I just redeployed the website for the mlpack 4 release, so let me figure out where in the website deployment scripts that directory is getting lost...

**Comment by rcurtin** [comment]
Ok, I fixed the Jenkins deploy scripts so the datasets are now successfully copied during the website build.  Thank you so much for pointing this out!  If there are further issues please do not hesitate to point them out. :)
