### ISSUE TITLE
Problem with directory structure and header file

### ISSUE THREAD

**Issue by crankyastrologer** [mlpack/mlpack#3303]
When installing the mlpack repository using vcpkg first header file as mentioned in the guide was not present and when I copied it from the git repository it was pointing to a different path. Specifically this was the path
```
#include "mlpack/methods/adaboost.hpp"
```
instead of this
```
#include "mlpack/methods/adaboost/adaboost.hpp"
```
any idea why this is happening

**Comment by rcurtin** [comment]
What version of mlpack are you using?  The documentation you are referencing is for mlpack 4.

**Comment by crankyastrologer** [comment]
Well, that seems to be the issue vcpkg is installing 3.4.1. Is there a need no raise an issue regarding this in vcpkg as mentioned in the documents?

**Comment by rcurtin** [comment]
Ahh, good idea; I opened https://github.com/microsoft/vcpkg/issues/27616, let's see what happens. :)

**Comment by crankyastrologer** [comment]
cool :)
