### ISSUE TITLE
The test executable mlpack_test isn't built

### ISSUE THREAD

**Issue by yurivict** [mlpack/mlpack#3314]
It required this patch to build:
```
--- src/mlpack/tests/CMakeLists.txt.orig        2022-11-15 09:59:36 UTC
+++ src/mlpack/tests/CMakeLists.txt
@@ -4,7 +4,7 @@ message("YURI: in tests")
 
 # mlpack test executable.
 add_executable(mlpack_test
-  EXCLUDE_FROM_ALL
+  #EXCLUDE_FROM_ALL
   ${MLPACK_TEST_SRCS}
  
   # Tests for neural network code (and reinforcement learning code).
```

Version: 4.0.0
cmake-core-3.24.3_1
FreeBSD 13.1

**Comment by rcurtin** [comment]
Thanks for the report @yurivict!  I spent a while thinking about the right solution here, but I agree with your patch in the end.  I opened a PR in #3316.  There is a little bit more to it too.  This will be a part of the 4.0.1 release (we are still collecting little configuration bugfixes, but that should happen soon enough).
