### ISSUE TITLE
Softmax Regression Module

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#332]
**Reported by siddharth 950 on 25 Oct 44352452 14:00 UTC**
Adding code for an implementation of Softmax Regression. The file also contains the data being used to test the implementation using the file 'softmaxRegression.cpp'. Tests are yet to be written.

Migrated-From: http://trac.research.cc.gatech.edu/fastlab/ticket/349

**Comment by apir8181** [comment]
I found that the implementation of softmax regression haven't add the intercept term. Because all separating plane crossing the origin on 3 dimension spaces can't split those points well, it is reasonable that the test accuracy is low.

I will try to fix this.

**Comment by rcurtin** [comment]
Looks like I forgot to close this ticket; apir8181 fixed this lack of intercept problem quite a while ago.  The tests now work and everything.
