### ISSUE TITLE
mlpack - Python: LARS throws runtime error 

### ISSUE THREAD

**Issue by demoronator** [mlpack/mlpack#3324]
#### Your environment

 * version of mlpack: mlpack Python 4.0.0.post1, 4.0.0, 3.4.2
 * operating system: Ubuntu 20.04.5 LTS

#### Steps to reproduce
Code:
```python
train_x = [
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
    [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
]
train_y_px = [0.0, 0.5, 1.0]
lars_px = mlpack.lars(input_=train_x, responses=train_y_px,
                      lambda1=0.1, lambda2=0.1,
                      verbose=True)
```
Result:
```
[FATAL] Number of responses must be equal to number of rows of X!
```

#### Expected behavior

The rows of X(input_) and responses are the same as three.
So it should return the dictionary without error.

#### Actual behavior
It throws a runtime error.

**Comment by rcurtin** [comment]
Indeed, your input looks reasonable and it should work.  Out of curiosity, does the code succeed if you specify `train_x` in a transposed form?  (Or `train_y_px` in a transposed form?)

**Comment by demoronator** [comment]
Didn't try, but I would like to give it a go. How do I specify it in a transposed form?

**Comment by demoronator** [comment]
I tried
```Python
train_y_px = [
    [0],
    [0.5],
    [1],
]
```
It also failed.

**Comment by rcurtin** [comment]
Thanks for the report.  It took a while to dig into it, but I found that the LARS method (and specifically LARS) happens to have a bug with how it is handled in the Python bindings, and some other languages too.  If you want to read the details, check out #3327.

Until that PR is merged and released, you can work around the bug by transposing your X data matrix, like this:

```
train_x = [
    [0.0, 0.5, 1.0],
    [0.0, 0.5, 1.0],
    [0.0, 0.5, 1.0],
    [0.0, 0.5, 1.0],
    [0.0, 0.5, 1.0],
    [0.0, 0.5, 1.0],
]
```

mlpack 4.0.1 will be released soon (next couple weeks?) with a fix.

Thanks so much again for the report, and if you find more issues in the future please do not hesitate to report them! :+1:

**Comment by demoronator** [comment]
Great. Thank you!

**Comment by rcurtin** [comment]
mlpack 4.0.1 is released now, so this should be solved.  Thanks again for the report! :+1:
