### ISSUE TITLE
FFN model regularizer type??

### ISSUE THREAD

**Issue by coderboyisongithub** [mlpack/mlpack#3326]
I am building a neural network using FFN using your documentation tutorial
`https://mlpack.org/doc/mlpack-3.2.2/doxygen/anntutorial.html`
but I am getting following error..

`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'mlpack::LinearType<arma::mat,mlpack::NoRegularizer>::LinearType(const size_t,RegularizerType)': cannot convert argument 2 from 'int' to 'RegularizerType'	mlpack test	E:\Software\mlpack\mlpack\src\mlpack\methods\ann\layer\multi_layer.hpp	168	
`
I am using visual studio 2019.
c++std 17
mlpack 4.0.0
what is wrong???

**Comment by shrit** [comment]
The answer is very simple, you see that the docs you are looking at is mlpack 3.2.2 and the version of mlpack you are using is mlpack 4

**Comment by coderboyisongithub** [comment]
what to do then why I am not able to design neural network??

**Comment by chetanpandey1266** [comment]
You can follow this [tutorial](https://github.com/mlpack/mlpack/blob/4.0.0/doc/tutorials/ann.md).
