### ISSUE TITLE
transition to arma::Row<size_t> for holding labels

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#333]
**Reported by rcurtin on 24 Aug 44382272 18:27 UTC**
Often in mlpack's supervised learning methods, the type `arma::Col<size_t>` is used to hold labels.  However, data is column-major, which means each dimension is a row.  Therefore, it makes sense that labels should also be a row, and the type `arma::Row<size_t>` should be used instead.

The reason that `arma::Col<size_t>` was originally used was convenience.

Files where `arma::Col<size_t>` is used to hold labels are listed below.  Note that changes in these files will probably mean that the tests will have to be modified too.

 * ./core/data/normalize_labels.hpp
 * ./core/data/normalize_labels_impl.hpp

 * ./core/tree/cover_tree/cover_tree.hpp
 * ./core/tree/cover_tree/cover_tree_impl.hpp

 * ./methods/cf/cf.hpp
 * ./methods/cf/cf_impl.hpp
 * ./methods/cf/cf_main.cpp

 * ./methods/det/dtree.cpp
 * ./methods/det/dtree.hpp
 * ./methods/det/dt_utils.cpp

 * ./methods/emst/dtb.hpp
 * ./methods/emst/dtb_rules.hpp
 * ./methods/emst/dtb_rules_impl.hpp
 * ./methods/emst/union_find.hpp

 * ./methods/gmm/em_fit.hpp
 * ./methods/gmm/em_fit_impl.hpp
 * ./methods/gmm/gmm.hpp
 * ./methods/gmm/gmm_impl.hpp

 * ./methods/hmm/hmm.hpp
 * ./methods/hmm/hmm_impl.hpp
 * ./methods/hmm/hmm_train_main.cpp
 * ./methods/hmm/hmm_viterbi_main.cpp

 * ./methods/kmeans/allow_empty_clusters.hpp
 * ./methods/kmeans/kmeans.hpp
 * ./methods/kmeans/kmeans_impl.hpp
 * ./methods/kmeans/kmeans_impl_openmp.hpp
 * ./methods/kmeans/kmeans_main.cpp
 * ./methods/kmeans/max_variance_new_cluster.hpp
 * ./methods/kmeans/max_variance_new_cluster_impl.hpp
 * ./methods/kmeans/random_partition.hpp
 * ./methods/kmeans/refined_start.hpp
 * ./methods/kmeans/refined_start_impl.hpp

 * ./methods/naive_bayes/naive_bayes_classifier.hpp
 * ./methods/naive_bayes/naive_bayes_classifier_impl.hpp

 * ./methods/nca/nca.hpp
 * ./methods/nca/nca_impl.hpp
 * ./methods/nca/nca_main.cpp
 * ./methods/nca/nca_softmax_error_function.hpp
 * ./methods/nca/nca_softmax_error_function_impl.hpp

Migrated-From: http://trac.research.cc.gatech.edu/fastlab/ticket/350

**Comment by jaskaran1** [comment]
I'd like to work on this one.

**Comment by rcurtin** [comment]
Udit has already submitted patches for this, but I have not yet had a chance to go through them.  I will take care of this when I have time.  This is a serious overhaul of code and needs to be handled carefully.
