### ISSUE TITLE
preprocess_split() takes at least 1 positional argument (0 given)

### ISSUE THREAD

**Issue by chetanpandey1266** [mlpack/mlpack#3336]
#### Issue description

I am trying out the random forest code in this [quickstart](https://github.com/mlpack/mlpack/blob/4.0.0/doc/quickstart/python.md) but I am getting this error

#### Your environment

 * version of mlpack: `mlpack 4.0.0.post1` 
 * operating system: `Ubuntu 22.10`

#### Steps to reproduce

Install the mlpack python package using `python3 install mlpack` and run the random forest code in the quickstart mentioned above

#### Expected behavior
The code should have given the intended accuracy

#### Actual behavior
I am getting this error
```shell
Traceback (most recent call last):
  File "/home/chetan/Coding/mlpack/python/doc.py", line 12, in <module>
    output = mlpack.preprocess_split(check_input_matrices=True,input=dataset, input_labels=labels, test_ratio=0.3)
  File "mlpack/preprocess_split.pyx", line 27, in mlpack.preprocess_split.preprocess_split
TypeError: preprocess_split() takes at least 1 positional argument (0 given)
```

**Comment by chetanpandey1266** [comment]
Yeah sure I'll raise a PR with the required changes

**Comment by rcurtin** [comment]
Since #3337 is merged, I think we can close this now.  Thanks @chetanpandey1266!
