### ISSUE TITLE
C2672 error while building sample-ml-app (mlpack 4.0.0)

### ISSUE THREAD

**Issue by sudhanshukuthe** [mlpack/mlpack#3338]
Hello,

I got this compiler error even after switching from c++14 standard to c++17 standard!
Is there a problem with "algorithm.hpp"  file of mlpack 4.0.0? 
Please help! 

I am using Microsoft Visual Studio 2022 version.
Followed every single step listed on: https://github.com/mlpack/mlpack/blob/4.0.0/doc/user/build_windows.md

My aim is to run this trial-
https://github.com/mlpack/mlpack/blob/4.0.0/doc/user/sample_ml_app.md

![Error list](https://user-images.githubusercontent.com/48419407/206927064-5de0d2ac-83d1-4c2f-b143-fd4f9f542a37.JPG)

The below screenshot highlights lines in "algorithm.hpp" which causing errors!! 

![algorithm_hpp](https://user-images.githubusercontent.com/48419407/206927203-1cf2844d-a914-41bc-91c7-4ddd6b41b4c3.jpg)

![Error list](https://user-images.githubusercontent.com/48419407/206927235-861adfc7-dc27-40e3-ac00-7006cd0cfe7d.JPG)

**Comment by rcurtin** [comment]
Did you also set `/Zc:__cplusplus` in your compiler options?

**Comment by sudhanshukuthe** [comment]
> Did you also set `/Zc:__cplusplus` in your compiler options?

Yes, it solved the issue :-) Many thanks.....
