### ISSUE TITLE
Compilation of source code in "c++ quick start" fails

### ISSUE THREAD

**Issue by cuzzuky87** [mlpack/mlpack#3340]
#### Problem location

The source code `cpp_quickstart_1.cpp` in [mlpack in C++ quickstart](https://github.com/mlpack/mlpack/blob/master/doc/quickstart/cpp.md)

#### Description of problem

The source code fails to compile due to missing empty angle brackets.
The relevant section is below

```cpp
  // Create the RandomForest object and train it on the training data.
  RandomForest r(trainDataset,
                 trainLabels,
                 7 /* number of classes */,
                 10 /* number of trees */,
                 3 /* minimum leaf size */);

```

**Comment by rcurtin** [comment]
Are you using the latest release of mlpack?  The class is called `RandomForest` as of mlpack 4.0.0, not `RandomForest<>`.  (Sorry for the compatibility breakage.)

**Comment by rcurtin** [comment]
I tested locally and it compiles fine.  If you have further problems, please feel free to post a comment :)
