### ISSUE TITLE
Problem with DecisionTree Classify()

### ISSUE THREAD

**Issue by Blakjak88** [mlpack/mlpack#3356]
I tried to run some sample code on DecisionTree and the Classify function expects predictions to be of type arma::Row<size_t> which is unsigned. Using MLPACK 4.0.0
[vc2.csv](https://github.com/mlpack/mlpack/files/10380894/vc2.csv)
[vc2_lables.txt](https://github.com/mlpack/mlpack/files/10380896/vc2_lables.txt)
[vc2_test.csv](https://github.com/mlpack/mlpack/files/10380897/vc2_test.csv)
 on Visual Studio loaded with VCPKG.

Compiling code on Visual Studio 2022 gives error as follows:

Error code: C4146.   "unary minus oprator applied to usigned type, rsult still unsigned. "

The error is in mlpack file:   load_numveric_csv.hpp   line 52.

Code is:

```
#include <mlpack/mlpack.hpp>

using namespace std;
using namespace mlpack;

int main()
{
  arma::mat       dataset;
  arma::Row<size_t> labels;
  data::Load("vc2.csv", dataset);
  data::Load("vc2_labels.txt", labels);

  DecisionTree<GiniGain, BestBinaryNumericSplit, AllCategoricalSplit, AllDimensionSelect> d(dataset, labels, 2, 1);

  cout << "child:" << d.NumChildren() << endl;
  cout << "dt.NumClasses():" << d.NumClasses() << endl;

  arma::mat testData;
  data::Load("vc2_test.csv", testData);
  arma::Row<size_t> predictions;
  d.Classify(testData, predictions);
  predictions.print("prediction:");
  return 0;
}
```

csv and txt files referenced in code are attached.

**Comment by Blakjak88** [comment]
... I should add that the labels are strings in the attached file and need to be mapped to numbers, but this does not impact the compilation failure.

**Comment by Blakjak88** [comment]
Looking at the code for the template function:

```
template<typename eT>
bool LoadCSV::ConvertToken(eT& val,  const std::string& token)
```

A check needs to be made to see if the type being loaded is unsigned or not.

Line 52 says:

```
val = neg ? -(std::numeric_limits<eT>::infinity()) : std::numeric_limits<eT>::infinity();
```

which fails to compile if the type of eT is unsigned.

**Comment by Blakjak88** [comment]
OK - I have Googled this error code and it appears it is a Microsoft Visual Studio bug which has never been fixed.

I read that this should be a warning and not an error.

It can be suppreseed by adding the following #2721 

```
#pragma warning(disable:4146)
```

**Comment by rcurtin** [comment]
Thanks for the comprehensive report.  I'm not against working around this in our codebase.  Just for fun, I opened a PR: https://github.com/mlpack/mlpack/pull/3357

Can you try that and see if that successfully works around the issue?  I used SFINAE to avoid ever calling unary minus on an unsigned type.  (Or, at least, I think I did.  Let's see if it works. :))
