### ISSUE TITLE
Using convolutional layer with non square filters

### ISSUE THREAD

**Issue by AllIAskOfYou** [mlpack/mlpack#3365]
Hey,

I'm trying to create a convolutional nn with mlpack, and as soon as I use a filter that doesn't have the same width as height I get an error. The code to recreate the problem is as follows:

``` c++
#include <mlpack.hpp>

using namespace arma;
using namespace mlpack;
using namespace mlpack::ann;
using namespace std;

int main()
{
	mat X(100, 2);
	mat Y(1, 2);

	FFN<> model;
	model.Add<Convolution>(16, 5, 3);    // if I were to use a (3, 3) filter or (5, 5) it would work
	model.Add<ReLU>();
	model.Add<Linear>(3);
	model.Add<Softmax>();

	model.InputDimensions() = { 10, 10, 1 };

	model.Train(X, Y);
}
```

I'm probably doing something wrong here, but I can't find anything much on convolutional layers or whatever seems to be the problem here.
The error I get is:
``` c++
Exception thrown at 0x00007FF8C954CD29 in sample-ml-app.exe: Microsoft C++ exception: std::logic_error at memory location 0x0000000FB63C9CB8.
Unhandled exception at 0x00007FF8C954CD29 in sample-ml-app.exe: Microsoft C++ exception: std::logic_error at memory location 0x0000000FB63C9CB8.
```

Thanks for the help,
Have a wonderful day

**Comment by AdarshSantoria** [comment]
I think the reason behind this is your Visual Studio Debugger which allows you to configure it to break when exceptions are thrown. I tried this in Ubuntu terminal and getting the `std::logic_error` what you are expecting
```
what():  Mat::init(): size is fixed and hence cannot be changed
```
You can change these settings in Visual Studio. The settings are found in the Debug->Windows->Exception Settings window.

**Comment by AllIAskOfYou** [comment]
Thanks for your answear. So does this mean that this exception can be ignored or just that the measage here is the:
``` c++
Mat::init(): size is fixed and hence cannot be changed
```
and that I should look into that?

**Comment by AdarshSantoria** [comment]
Yes.

**Comment by AllIAskOfYou** [comment]
I tried looking into it, but i didn't find a solution to my problem. It seems to me that this is some basic functionality and that it should work, unless I'm not using the api correctrly.
So any other suggestions are still very welcomed.

**Comment by rcurtin** [comment]
@AllIAskOfYou sorry for the slow response, I've been traveling.  I was hoping to take a look into reproducing this tomorrow or soon.  Stay tuned...

**Comment by AllIAskOfYou** [comment]
Okey, hope you've been doing well and thank you.

**Comment by rcurtin** [comment]
Thanks!  I took a look into the issue today and it is a very small bug.  #3376 has a patch.

**Comment by AllIAskOfYou** [comment]
Thank you, I'll try it out tomorrow.
