### ISSUE TITLE
Software paper authorship criteria question

### ISSUE THREAD

**Issue by sandeep-ps** [mlpack/mlpack#3370]
This question is related to the JOSS paper review https://github.com/openjournals/joss-reviews/issues/5026 and the checklist entry `General checks - Contribution and authorship: Has the submitting author (@rcurtin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?`

It's easy to determine that `@rcurtin` has made significant contributions to the software by looking at the git commits. To evaluate the second question above, I need to understand how the other co-authors were determined. Could you please share the authorship criteria for the remaining authors?

Also, https://www.mlpack.org/community.html doesn't contain all authors listed in the paper. Could that list be updated to include all authors in the software paper?

**Comment by rcurtin** [comment]
I asked people on the Contributors team if they were interested in being a part of the paper.  To be on the Contributors team, someone has to have contributed significantly to the effort and be nominated to the team as per the process in the [governance document](https://github.com/mlpack/mlpack/blob/master/GOVERNANCE.md).  It's a contributor's choice to add themselves to the list of authors/maintainers, and some people on the paper have chosen to not do that. :+1:

**Comment by sandeep-ps** [comment]
Thanks for sharing the details. I will close this issue.
