### ISSUE TITLE
Cross-compile guide (for Raspberry Pi 4)?

### ISSUE THREAD

**Issue by rodonguyen** [mlpack/mlpack#3378]
#### Problem location

https://github.com/mlpack/mlpack/blob/master/board/crosscompile-toolchain.cmake

#### Description of the problem

Hi, I'm trying to compile programs on Ubuntu 22.04 to run on a Raspberry Pi 4. However, the current information on this (particularly in crosscompile-toolchain.cmake) is quite insufficient. What are the main steps to make it work? If I succeed, I may be able to write documentation for it too. Thank you.

**Comment by rcurtin** [comment]
@shrit any thoughts on this one?  I remember that you showed me how to do this quite some time ago, but now it has been too long.  The main part that I remember is that I installed the [buildroot](https://buildroot.org/) toolchain and I think I had to adjust some paths in the `crosscompile-toolchain.cmake` file.  However, the rest of it escapes my memory.

**Comment by rodonguyen** [comment]
Yeah, I saw some discussion from a long time ago but seems like not many docs were added since. Hoping to see more detailed docs for it.

**Comment by shrit** [comment]
@rodonguyen here is the command that you need to use:
```
cmake -DDEBUG=OFF -DPROFILE=OFF -DBUILD_TESTS=ON -DBUILD_MARKDOWN_BINDINGS=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_GO_BINDINGS=OFF -DBUILD_JULIA_BINDINGS=OFF -DBUILD_R_BINDINGS=OFF -DCMAKE_TOOLCHAIN_FILE=../board/crosscompile-toolchain.cmake -DBOARD_NAME=RPI4 -DDISABLE_DOWNLOADS=OFF -DTOOLCHAIN_PREFIX=/home/jenkins/workspace/CrossCompile-mlpack-for-embedded-aarch64/aarch64--glibc--stable-2020.08-1/bin/aarch64-buildroot-linux-gnu- -DCMAKE_SYSROOT=/home/jenkins/workspace/CrossCompile-mlpack-for-embedded-aarch64/aarch64--glibc--stable-2020.08-1/aarch64-buildroot-linux-gnu/sysroot ../
```

**Comment by rodonguyen** [comment]
Thanks, Shrit, I will try it. 

Close the issue for now.
