### ISSUE TITLE
dependencies_installation_guide docs ?

### ISSUE THREAD

**Issue by rodonguyen** [mlpack/mlpack#3379]
#### Problem location

https://github.com/mlpack/mlpack/blob/master/README.md

#### Description of problem

Do you need an additional installation guide for the dependencies? I myself had a lot of trouble installing them and others may have it as well. (I don't know :) )

I plan to put it in `/doc/dependencies_installation_guide.md` and link it to the main README.md. 

What do you think? Say yes and I get into it.
Rodo

**Comment by shrit** [comment]
All dependencies are header only and they are downloaded automatically with cmake parameter `-DDOWNLOAD_DEPENDENCIES=ON` 
They do not need to be installed

**Comment by conradsnicta** [comment]
@rodonguyen It may be useful to first describe what exact issues you had with installing the dependencies.

On a typical Linux-based system the dependencies can be obtained through the system package manager (for example, apt, aptitude, yum, dnf, pacman).  If the dependencies are still not available, the CMake installer for mlpack can optioinally get them automatically, as mentioned by @shrit

**Comment by rcurtin** [comment]
Agreed---I'd like to avoid maintaining documentation for our dependencies, which could go out of date easily.  Better to simply point the users upstream. :+1:  I wouldn't be opposed to expanding Section 2 of the README slightly to point out the names of the required packages for common system package managers, and perhaps to link to the websites of the dependencies themselves.

**Comment by rodonguyen** [comment]
> All dependencies are header only and they are downloaded automatically with cmake parameter `-DDOWNLOAD_DEPENDENCIES=ON` They do not need to be installed

Thank you all for clarifying this issue. Apparently, I didn't read the docs closely enough and missed the `-DDOWNLOAD_DEPENDENCIES=ON` part.

Anyway, I think linking more info in the dependencies is a good idea. I will make a PR for it and hope to hear your feedback on that :) 

Your contribution to this project is amazing, @rcurtin @conradsnicta @shrit !

Best regards,
Rodo

**Comment by rodonguyen** [comment]
Here are some improvements for the README.md. Let me know what you think.

https://github.com/mlpack/mlpack/pull/3385

**Comment by rcurtin** [comment]
With #3386 merged, this is fixed, so I'll go ahead and close this issue. :+1:
