### ISSUE TITLE
1/core/arma_extend/Mat_extra_bones.hpp

### ISSUE THREAD

**Issue by Wemmons831** [mlpack/mlpack#3382]
I have installed mlpack with vcpkg following the instructions [here](https://github.com/mlpack/mlpack/blob/master/doc/user/build_windows.md). I have added C:\Users\wi\vcpkg\installed\x64-windows\include to my included files. However when I run try to compile I get this error `fatal error C1083: Cannot open include file: '1/core/arma_extend/Mat_extra_bones.hpp': No such file or directory
1>Done building project "mlpkkk.vcxproj" -- FAILED.` I have looked through all of the vcpkg files and I can not find any file `1/core/arma_extend/Mat_extra_bones.hpp`. Does anyone know where this file is

**Comment by rcurtin** [comment]
Thanks for the report. :+1:

Can you provide some more information about your project?  Specifically, it would be helpful to see what file is trying to include `Mat_extra_bones.hpp`.  That file is a part of mlpack: `Mat_extra_bones.hpp` should be in `mlpack/core/arma_extend/`, in the include directory that vcpkg installed mlpack into.  But I am a little confused why the path that is being included is `1/core/arma_extend/Mat_extra_bones.hpp`, and not `mlpack/core/arma_extend/Mat_extra_bones.hpp`.

It could be worth checking that `mlpack/core/arma_extend/arma_extend.hpp` is correct, and has the same contents as [it should](https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/arma_extend/arma_extend.hpp).

**Comment by Wemmons831** [comment]
The error is coming from armadillo_bits\Mat_bones.hpp(795,14). Following this path brings me to core/arma_extend/arma_extend.hpp line 18 where ARMA_EXTRA_MAT_PROTO is defined as mlpack/core/arma_extend/Mat_extra_bones.hpp 
 `#define ARMA_EXTRA_MAT_PROTO mlpack/core/arma_extend/Mat_extra_bones.hpp` and for some reason mlpack is evaluating to 1

**Comment by Wemmons831** [comment]
I think that the problem may reside in how vcpkg is handling mlpack as when I go into the mat_bones.hpp and change the line to just #include <mlpack/core/arma_extend/Mat_extra_bones.hpp> (I also did the same in SpMat_bones.hpp) I get 100+ syntax errors (deleting and reinstalling mlpack does not change anything). the error could also very well be on my side because I had to manually add mlpack to my project as vcpkg did not

**Comment by Wemmons831** [comment]
The errors are from a bunch of files but the majority of them is in the ball park of `error C2447: '{': missing function header (old-style formal list?)`

**Comment by rcurtin** [comment]
I don't use Windows so it's hard for me to know, but I think others are using vcpkg without problems.  Is it possible that there is a macro `mlpack` that's defined somewhere?  If you can track down whether and where that is defined, that's probably a step towards resolving the issue.
