### ISSUE TITLE
Homebrew support of previous versions

### ISSUE THREAD

**Issue by mircodemarchi** [mlpack/mlpack#3388]
I am developing a library that includes MLPACK and I evaluate the support of my library with a continuous integration system. Since I need to support my library on macOS, I do the MLPACK installation via Homebrew.  

Recently MLPACK has been updated to 4.0.1, which was also integrated to [homebrew-core](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mlpack.rb). However, compatibility to the previous version, 3.4.2, was not maintained. The changes from 3.4.2 to 4.0.1 are substantial, e.g. the move to header-only. Since my library was built on MLPACK 3, it is impossible for me to make the switch to MLPACK 4, since I have to ensure CI support on windows and ubuntu, as well as macOS, in which there is still no support for MLPACK 4 via apt and vcpkg. 

Can you please keep also version 3.4.2 on homebrew? 
It would be nice to be able to do the installation via the following command:  `brew install mlpack@3`

Thank you in advance
Mirco

**Comment by conradsnicta** [comment]
You'll have to contact the maintainers of the mlpack homebrew package.

From the side of mlpack developers, maintaining two separate versions would require effort that is probably beyond the available volunteer time and willingness.
