### ISSUE TITLE
Error in Alternating Matrix Factorization tutorial

### ISSUE THREAD

**Issue by AdarshSantoria** [mlpack/mlpack#3390]
#### Problem location

(https://github.com/mlpack/mlpack/blob/master/doc/tutorials/amf.md)

#### Description of problem

Some of the codes in the link throw errors and one such is -
```
#include <mlpack.hpp>

using namespace std;
using namespace arma;
using namespace mlpack;

int main()
{
  sp_mat V = randu<sp_mat>(100,100);
  // this will be sp_mat V = sprandu<sp_mat>(100,100,0.1); 
  mat W, H;

  SVDBatchFactorizer<sp_mat> svd;
  double residue = svd.Apply(V, W, H);
  // this will be double residue = svd.Apply(V, r, W, H); where r is any integer
}
```
I observed two changes here which I had written inside comments.

**Comment by rcurtin** [comment]
Thanks!  I think you are right about this.  Do you want to open a PR to fix the issue?

**Comment by AdarshSantoria** [comment]
Yes, I would love to do it.
