### ISSUE TITLE
Doxygen interpretation of documentation is not working properly.

### ISSUE THREAD

**Issue by theshoonyam** [mlpack/mlpack#3396]
### What am I trying to implement?
I was trying to get the doxygen interpretation of documentation. 

### Steps that I followed:

- install doxygen version: 1.9.1
- run doxygen -g inside mlpack folder 
- run doxygen

### What I got?
I have tried to paste a small portion of what command line produces.

`Generating docs for compound Catch::AssertionReaction...
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2544: warning: Member shouldDebugBreak (variable) of struct Catch::AssertionReaction is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2545: warning: Member shouldThrow (variable) of struct Catch::AssertionReaction is not documented.
Generating docs for compound Catch::AssertionHandler...
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2555: warning: Member AssertionHandler(StringRef const &macroName, SourceLineInfo const &lineInfo, StringRef capturedExpression, ResultDisposition::Flags resultDisposition) (function) of class Catch::AssertionHandler is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2567: warning: Member handleExpr(ExprLhs< T > const &expr) (function) of class Catch::AssertionHandler is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2570: warning: Member handleExpr(ITransientExpression const &expr) (function) of class Catch::AssertionHandler is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2572: warning: Member handleMessage(ResultWas::OfType resultType, StringRef const &message) (function) of class Catch::AssertionHandler is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2574: warning: Member handleExceptionThrownAsExpected() (function) of class Catch::AssertionHandler is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2575: warning: Member handleUnexpectedExceptionNotThrown() (function) of class Catch::AssertionHandler is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2576: warning: Member handleExceptionNotThrownAsExpected() (function) of class Catch::AssertionHandler is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2577: warning: Member handleThrowingCallSkipped() (function) of class Catch::AssertionHandler is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2578: warning: Member handleUnexpectedInflightException() (function) of class Catch::AssertionHandler is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2580: warning: Member complete() (function) of class Catch::AssertionHandler is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2581: warning: Member setCompleted() (function) of class Catch::AssertionHandler is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2584: warning: Member allowThrows() const -> bool (function) of class Catch::AssertionHandler is not documented.
Generating docs for compound Catch::MessageInfo...
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2600: warning: Member MessageInfo(StringRef const &_macroName, SourceLineInfo const &_lineInfo, ResultWas::OfType _type) (function) of struct Catch::MessageInfo is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2610: warning: Member operator==(MessageInfo const &other) const (function) of struct Catch::MessageInfo is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2611: warning: Member operator<(MessageInfo const &other) const (function) of struct Catch::MessageInfo is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2604: warning: Member macroName (variable) of struct Catch::MessageInfo is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2605: warning: Member message (variable) of struct Catch::MessageInfo is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2606: warning: Member lineInfo (variable) of struct Catch::MessageInfo is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2607: warning: Member type (variable) of struct Catch::MessageInfo is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2608: warning: Member sequence (variable) of struct Catch::MessageInfo is not documented.
Generating docs for compound Catch::MessageStream...
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2619: warning: Member operator<<(T const &value) (function) of struct Catch::MessageStream is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2624: warning: Member m_stream (variable) of struct Catch::MessageStream is not documented.
Generating docs for compound Catch::MessageBuilder...
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2628: warning: Member MessageBuilder(StringRef const &macroName, SourceLineInfo const &lineInfo, ResultWas::OfType type) (function) of struct Catch::MessageBuilder is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2633: warning: Member operator<<(T const &value) (function) of struct Catch::MessageBuilder is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2619: warning: Member operator<<(T const &value) (function) of struct Catch::MessageStream is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2638: warning: Member m_info (variable) of struct Catch::MessageBuilder is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2624: warning: Member m_stream (variable) of struct Catch::MessageStream is not documented.
Generating docs for compound Catch::ScopedMessage...
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2643: warning: Member ScopedMessage(MessageBuilder const &builder) (function) of class Catch::ScopedMessage is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2645: warning: Member ScopedMessage(ScopedMessage &&old) (function) of class Catch::ScopedMessage is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2648: warning: Member m_info (variable) of class Catch::ScopedMessage is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2649: warning: Member m_moved (variable) of class Catch::ScopedMessage is not documented.
Generating docs for compound Catch::Capturer...
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2657: warning: Member Capturer(StringRef macroName, SourceLineInfo const &lineInfo, ResultWas::OfType resultType, StringRef names) (function) of class Catch::Capturer is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2660: warning: Member captureValue(size_t index, std::string const &value) (function) of class Catch::Capturer is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2663: warning: Member captureValues(size_t index, T const &value) (function) of class Catch::Capturer is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2668: warning: Member captureValues(size_t index, T const &value, Ts const &... values) (function) of class Catch::Capturer is not documented.
Generating docs for compound Catch::Counts...
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2830: warning: Member operator-(Counts const &other) const (function) of struct Catch::Counts is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2831: warning: Member operator+=(Counts const &other) (function) of struct Catch::Counts is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2833: warning: Member total() const (function) of struct Catch::Counts is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2834: warning: Member allPassed() const (function) of struct Catch::Counts is not documented.
/home/aditya/Desktop/mlpack/src/mlpack/tests/catch.hpp:2835: warning: Member allOk() const (function) of struct Catch::Counts is not documented.
`

### What have I concluded?
Documentation is not serving the purpose for which it is intended for.

_I can work on this issue whenever I will get free time_

Thanks 
Adi

**Comment by rcurtin** [comment]
Glad you found #3331; and yeah, we chose to remove the Doxygen documentation because it was just too much to try and maintain the website, and it wasn't even easy to use.  I think it's still a good idea to keep the Doxygen-style comments in the code, since they are quite comprehensive.  This makes it easier for a maintainer or new contributor to understand what's going on internally.  But, there's no need anymore to keep specific Doxygen conventions like `//!`, for instance.  (I don't think it's worth going back through the code to change it, it seems like a lot of effort for little gain.)
