### ISSUE TITLE
Does MLPack have DataGenerator?

### ISSUE THREAD

**Issue by rodonguyen** [mlpack/mlpack#3419]
This is just a short question. 
Does MLPack have something like [ImageDataGenerator in Keras](https://towardsdatascience.com/image-data-generators-in-keras-7c5fc6928400)?

Cheers, Rodo

**Comment by rcurtin** [comment]
Maybe something discussed in the [Image Utilities Tutorial](https://github.com/mlpack/mlpack/blob/master/doc/tutorials/image.md) could be helpful?  I don't think the functionality is exactly the same, but maybe it is at least in the right direction, I hope.

**Comment by rodonguyen** [comment]
Thanks, @rcurtin.
I resolve this by implementing a simple `for` loop for now ✌🏾
