### ISSUE TITLE
Undefined reference to "arma_..."

### ISSUE THREAD

**Issue by Rand-0** [mlpack/mlpack#3433]
Hi,
I cannot use the data loading functions from tutorial (from arma, e.g. arma::mat) - after compilation I'm getting an error "Undefined reference to arma_H5T..." (... - multiple functions). I've installed mlpack using msys2 and I'm working with CodeBlocks.

**Comment by Rand-0** [comment]
Code I'm using:

#include <mlpack.hpp>

int main()
{
    arma::mat trainData;
    mlpack::data::Load("thyroid_train.csv", trainData, true);
    return 0;
}

**Comment by rcurtin** [comment]
Hey there, are you sure you're linking against the Armadillo library in your project?  If you are and you're still seeing this issue, can you tell me more about how you installed Armadillo?

**Comment by Rand-0** [comment]
Hey, I've tested by creating new project with:

#include <armadillo>

int main()
{
  arma::mat trainData;
}

And it's compiling without any errors. However, when I try to run the program from first comment, it's still getting the same problems.

I've installed the mlpack using: pacman -S mingw-w64-x86_64-mlpack - and it already installed Armadillo as dependency (it's shown as installed in msys).

**Comment by Rand-0** [comment]
Hey @conradsnicta, could you reopen this issue?

**Comment by conradsnicta** [comment]
@Rand-0 This might be a problem with the mingw Armadillo package.  It might be outdated, misconfigured, or simply broken.

As a direct workaround for the HDF5 problem, define `ARMA_DONT_USE_HDF5` before including the Armadillo header, followed by including the mlpack header:

    #define ARMA_DONT_USE_HDF5
    #include <armadillo>
    #include <mlpack.hpp>

If that doesn't work, suggest to remove the mingw Armadillo package and install Armadillo by hand: https://arma.sourceforge.net/download.html

When compiling your code, make sure you link with `-larmadillo`:

    g++ code.cpp -o code -O2 -larmadillo

If that doesn't work, define ARMA_DONT_USE_WRAPPER before including the Armadillo header and then manually link with openblas and lapack.

    #define ARMA_DONT_USE_WRAPPER
    #define ARMA_DONT_USE_HDF5
    #include <armadillo>
    #include <mlpack.hpp>

Command line:

    g++ code.cpp -o code -O2 -lopenblas -llapack

There is more info at the Questions page:  https://arma.sourceforge.net/faq.html

PS. Windoze (even with mingw) is not exactly the most reliable nor efficient platform for development or any scientific computing work.  You'll save yourself a truckload of headaches by using either macOS., or a Linux-based OS (such as Ubuntu or Fedora).

**Comment by Rand-0** [comment]
Okay, I've found the problem and the solution.

Basically, msys has older version of Armadillo which is installed as a dependency of mlpack package. When I manually replaced files from the older version with newer, this issue is no longer persisting.
