### ISSUE TITLE
Predict

### ISSUE THREAD

**Issue by ahmadabushaikha** [mlpack/mlpack#3446]
#### Issue description

Predict function does not seem to run for me. I keep getting the following error when running in my app:

Exception thrown at 0x00007FFCCEC3CD29 in QASRML.exe: Microsoft C++ exception: std::logic_error at memory location 0x000000FC2CCFE090.

I am new to MLPACK so maybe i missed something. 

I used the following code, the thyroid data set, to see if it runs. Train runs however the error shows when it reaches Predict. 

    // Load the dataset.
    arma::mat trainData;
    if (!data::Load("C:/QASR_2023/ML_TESTS/thyroid_train.csv", trainData))
        cout << "Cannot open thyroid_train.csv" << endl;

    arma::mat trainLabels = trainData.row(trainData.n_rows - 1);
    trainData.shed_row(trainData.n_rows - 1);
    trainLabels -= 1; // Labels should be from 0 to numClasses - 1.

    arma::mat testData;
    if (!data::Load("C:/QASR_2023/ML_TESTS/thyroid_test.csv", testData))
        cout << "Cannot load dataset thyroid_test.csv" << endl;

    arma::mat testLabels = testData.row(testData.n_rows - 1);
    testData.shed_row(testData.n_rows - 1);
    testLabels -= 1; // Labels should be from 0 to numClasses - 1.

    /*
     * Construct a feed forward network with trainData.n_rows input nodes,
     * hiddenLayerSize hidden nodes and trainLabels.n_rows output nodes. The
     * network structure looks like:
     *
     *  Input         Hidden        Dropout      Output
     *  Layer         Layer         Layer        Layer
     * +-----+       +-----+       +-----+       +-----+
     * |     |       |     |       |     |       |     |
     * |     +------>|     +------>|     +------>|     |
     * |     |     +>|     |       |     |       |     |
     * +-----+     | +--+--+       +-----+       +-----+
     *             |
     *  Bias       |
     *  Layer      |
     * +-----+     |
     * |     |     |
     * |     +-----+
     * |     |
     * +-----+
     */

    FFN<NegativeLogLikelihood> model;
    model.Add<Linear>(8);
    model.Add<Sigmoid>();
    model.Add<Dropout>();
    model.Add<Linear>(3);
    model.Add<LogSoftMax>();

    ens::RMSProp opt(0.01, 32, 0.88, 1e-8, trainData.n_cols * 10, -100);
    model.Train(trainData, trainLabels, opt, Report(),ProgressBar() );

    mat predictionTemp;
    model.Predict(testData, predictionTemp);
  
   double validMSE = ComputeMSE(trainLabels, predictionTemp);
     cout << "Mean Squared Error on Prediction data points: " << validMSE << endl;

#### Your environment

 * version of mlpack: mlpack-4.0.1.tar - downloaded from website 
 * operating system: windows
 * compiler: MSVS 2022
 * version of dependencies (Boost/Armadillo):Armadillo
 * any other environment information you think is relevant:

**Comment by rcurtin** [comment]
Do you have the text of the `std::logic_error`? If an exception was thrown it should have an accompanying error message, and that would be helpful for diagnosing what's gone wrong.

**Comment by aadi-raj** [comment]
Can you share the dataset so that I can reproduce the error?

**Comment by aryaman1202** [comment]
@rcurtin Please let me work over this issue, I would be highly grateful if given an opportunity to work for the same.
