### ISSUE TITLE
Are there examples how to load parameters into the model during creation instead of letting the model to auto-generate them?

### ISSUE THREAD

**Issue by yurivict** [mlpack/mlpack#3448]
I would like to import parameter values before training and export them after training.

Are there examples like this?

**Comment by mrdaybird** [comment]
You can save models along with their parameters and load the same. See this [example](https://github.com/mlpack/mlpack/blob/master/doc/tutorials/ann.md#saving--loading).

**Comment by yurivict** [comment]
Thank you.
