### ISSUE TITLE
use Armadillo diagonal GMM implementation when DiagonalConstraint is used with GMMs

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#345]
**Reported by rcurtin on 28 May 44631823 05:27 UTC**
The mlpack implementation of GMMs is hilariously inefficient.  A user will write this code:

```
GMM<EMFit<KMeans, DiagonalConstraint> > gmm(dataset);
```

but what this code will actually do is run the regular full-covariance EM algorithm, and then set all non-diagonal elements of each covariance matrix to 0 at the end of each EM iteration.  This is obviously not the right way to do it.

So the right thing to do is probably to specialize EMFit<..., DiagonalConstraint> so that it uses an algorithm specifically for diagonal covariances and not the entire covariance matrix.

Armadillo now contains an implementation of diagonal GMMs, which might be useful for this specialization.  If it will be used, one should ensure that the amount of memory being copied is minimal.

Migrated-From: http://trac.research.cc.gatech.edu/fastlab/ticket/363

**Comment by nikhilYadala** [comment]
@rcurtin , Is the problem solved? If not shall I start working on it?

**Comment by Lakshya1605** [comment]
@rcurtin Can I start working  on this??

**Comment by rcurtin** [comment]
Sure, feel free, nobody has submitted any PR.

**Comment by rcurtin** [comment]
Fixed via #1055.
