### ISSUE TITLE
Why not make mlpack a regular library?

### ISSUE THREAD

**Issue by yurivict** [mlpack/mlpack#3457]
#### Issue description

Including mlpack.hpp and building all code in all C++ modules takes a long time for each C++ module.

It also exposes compiler bugs like this one: https://github.com/llvm/llvm-project/issues/61750

Since mlpack grew quite large - why don't you consider to make it a regular C++ library instead of a headers-only library?

#### Your environment

 * version of mlpack: 4.0.1
 * operating system: FreeBSD 13.1
 * compiler: clang-14

**Comment by rcurtin** [comment]
A couple reasons, but mainly it's for ease of deployment---deploying mlpack gets way harder when you start having compiled parts of mlpack.  For instance, that made distributing the Python bindings (and getting their runtime linker path directories right) awful.  That's just the tip of the iceberg, there were all kinds of other little trickinesses too.  Having compiled libraries to link against was also confusing for lots of users; much better to just say "set your include directories right and don't worry about it".

If you want to reduce compilation overhead of mlpack, [here's](https://github.com/mlpack/mlpack#32-reducing-compile-time) the relevant section in the README.

**Comment by yurivict** [comment]
Thank you.
