### ISSUE TITLE
Are there examples of training of NN to evaluate a function?

### ISSUE THREAD

**Issue by yurivict** [mlpack/mlpack#3458]
I am trying to evaluate a function using this NN:
```
        FFN<> model;
        model.Add<Linear>(25);
        model.Add<Sigmoid>();
        model.Add<Linear>(30);
        model.Add<Sigmoid>();
        model.Add<Linear>(1/*numFunctionValues*/);
        model.Add<Sigmoid>();

        model.Train(trainData, trainLabels);
```

trainData is a matrix with function arguments.
trainLabels is a matrix with function values.

Training asserts here:
```
27│ template<typename MatType>
28│ double NegativeLogLikelihoodType<MatType>::Forward(
29│     const MatType& prediction,
30│     const MatType& target)
31│ {
32│   typedef typename MatType::elem_type ElemType;
33│   ElemType lossSum = 0;
34│   for (size_t i = 0; i < prediction.n_cols; ++i)
35│   {
36├───> Log::Assert(target(i) >= 0 && target(i) < prediction.n_rows,
37│         "Target class out of range.");
38│
39│     lossSum -= prediction(target(i), i);
40│   }
41│
42│   if (reduction)
43│     return lossSum;
44│
45│   return lossSum / target.n_elem;
46│ }
```

It expects some value to be a row index. Why?

Are there examples that train NN to evaluate a function?

**Comment by mrdaybird** [comment]
Can you specify, what kind of data you are passing to this model? Do the trainLabels contain negative values or are they not integers? If yes, you should try changing the Loss function you are using.

**Comment by rcurtin** [comment]
In this case it looks to me like you are trying to train a model for regression; but the `NegativeLogLikelihood` loss is for classification.  So, I think using `FFN<MeanSquaredError>` will fix your issue.

However, if you are actually doing classification (I am guessing not based on the fact that you have only one neuron in the last layer), make sure that:
 * your labels take values from `0` to `numClasses - 1`
 * the last layer of your network has `numClasses` neurons

**Comment by yurivict** [comment]
This makes sense.

Thank you for your help.
