### ISSUE TITLE
Cross-compile into a .so file for use in the Android system, but encountered an error due to a missing cotire file.

### ISSUE THREAD

**Issue by ltanme** [mlpack/mlpack#3459]
Cross-compile mlpack 3.4.2 on Ubuntu system with CMake version 3.20.0, targeting Android ARMv7 architecture and a minimum Android API level of 21

my env:
 ubuntu os  Linux **ubuntu** 5.15.0-69-generic #76~**20.04.1-**Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
cmake version **3.20.1**
NDK 
NU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

commandline:

cmake -DCMAKE_SYSTEM_NAME=Android  -DCMAKE_SYSTEM_VERSION=21  -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a  -DCMAKE_ANDROID_NDK=/usr/local/android-ndk-r25c   -DCMAKE_ANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-4.9  -DANDROID_NATIVE_API_LEVEL=21  -DANDROID_ABI=armeabi-v7a  ../src/mlpack
 

comandline response 

-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Error at CMakeLists.txt:60 (cotire):
  Unknown CMake command "cotire".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.20)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

please help me, Cross-compile mlpack 3.4.2 on Ubuntu system

**Comment by ltanme** [comment]
Doesn't mlpack 3.4.2 already include the cotire module? Why can't it find this module?

**Comment by conradsnicta** [comment]
mlpack 3.4.2 is outdated and no longer maintained.  Suggest to use the latest available release (4.0.1 at this time), downloadable directly from https://www.mlpack.org

**Comment by ltanme** [comment]
Hello,

@conradsnicta 
I downloaded the latest version of mlpack 4.0.1 from https://www.mlpack.org/ and tried to compile the so file for the Android platform. I want to put it in the jni directory of an Android app for Java to call. The main purpose is to use the C++ mlpack library to implement the linear regression method and run the Boston house price prediction demo. However, when I tried to compile using mlpack 4.0.1 on Ubuntu, I encountered the following error. I did not find any documentation on the official website regarding compiling for the Android platform or any relevant compilation documentation for applications on the Android platform.

Could you please take a look at the error and the compilation command I used?

[![iCdjsJ.md.png](https://i.328888.xyz/2023/03/30/iCdjsJ.md.png)](https://imgloc.com/i/iCdjsJ)

`twlhack@ubuntu:~/Desktop/mlpack-4.0.1/build$ cmake -DCMAKE_SYSTEM_NAME=Android  -DCMAKE_SYSTEM_VERSION=21  -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a  -DCMAKE_ANDROID_NDK=/usr/local/android-ndk-r25c   -DCMAKE_ANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-4.9  -DANDROID_NATIVE_API_LEVEL=21  -DANDROID_ABI=armeabi-v7a  ../src/mlpack
`

**Comment by ltanme** [comment]
show error message

`cmake -DCMAKE_SYSTEM_NAME=Android  -DCMAKE_SYSTEM_VERSION=21  -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a  -DCMAKE_ANDROID_NDK=/usr/local/android-ndk-r25c   -DCMAKE_ANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-4.9  -DANDROID_NATIVE_API_LEVEL=21  -DANDROID_ABI=armeabi-v7a  ../src/mlpack
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Android: Targeting API '21' with architecture 'arm', ABI 'armeabi-v7a', and processor 'armv7-a'
-- Android: Selected unified Clang toolchain
-- The C compiler identification is Clang 14.0.7
-- The CXX compiler identification is Clang 14.0.7
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Not building Julia bindings.
-- Not building Markdown bindings.
-- Not building Python bindings.
-- Not building Go bindings.
-- Not building R bindings.
CMake Error at CMakeLists.txt:18 (install):
  install FILES given no DESTINATION!


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.20)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
`

**Comment by shrit** [comment]
did you define a name for your project?

**Comment by ltanme** [comment]
add two line  in Cmakelist.txt 
project("libmlpackso")

install(TARGETS libmlpackso DESTINATION /root//home/twlhack/Desktop)

**Comment by ltanme** [comment]
Here is a detailed compilation log link.
https://raw.githubusercontent.com/ltanme/display/main/test/CMakeOutput.log

**Comment by conradsnicta** [comment]
@ltanme With mlpack 4.0 there is no .so (shared object) to generate. Instead, add the `src/mlpack` folder to your compiler's search path for include files and then use mlpack by including the mlpack header in your programs: `#include <mlpack.hpp>`. For gcc and clang compilers, use the `-I` switch to add a search path.

**Comment by conradsnicta** [comment]
@ltanme With mlpack 4.0 there is no .so (shared object) to generate. Instead, add mlpack's [`src`](https://github.com/mlpack/mlpack/tree/master/src) folder to your compiler's search path for include files and then use mlpack by including the mlpack header in your programs: `#include <mlpack.hpp>`. For gcc and clang compilers, use the `-I` switch to add a search path.

**Comment by conradsnicta** [comment]
@ltanme Sorry, you're on your own here.  The problem appears on your end (ie. in your setup or code), and not in mlpack.  We don't really have the time to debug external code.
