### ISSUE TITLE
Issue with namespace mlpack::ann

### ISSUE THREAD

**Issue by caidenmarley** [mlpack/mlpack#3460]
#### Issue description

I have just installed mlpack and i am trying to get familar with it so sorry if im being stupid but when i try to do 
using namespace mlpack::ann;
i get an error message that namespace mlpack has no member ann
#### Your environment

 * version of mlpack: 4.0.1
 * operating system: Windows 10
 * compiler: mingw
 * version of dependencies (Boost/Armadillo): Armadillo v12.0.1, Ensmallen v2.19.0
 * any other environment information you think is relevant: i have used vcpkg to install mlpack

#### Steps to reproduce
#define MLPACK_PRINT_INFO
#define MLPACK_PRINT_WARN
#include <mlpack/core.hpp>
#include <mlpack/methods/ann/layer/layer.hpp>
#include <mlpack/methods/ann/ffn.hpp>
#include <mlpack/methods/ann/layer/linear.hpp>
#include <mlpack/methods/ann/ann.hpp>
using namespace std;
using namespace arma;
using namespace mlpack;
using namespace mlpack::ann;

int main()
{
	mat trainData;
	data::Load("data.csv", trainData);

	mat trainTarget = trainData.row(trainData.n_rows - 1);
	trainData.shed_row(trainData.n_rows - 1);

	//model
	FFN<> model;
	model.Add<Linear<> >(trainData.n_rows, 8);
	model.Add<SigmoidLayer<> >();
}

this is my full code that i am using, i get error messages from the Linear template and the SigmoidLayer template, i am guessing this is due to the fact that the namespace isnt being registered
![mlpack error](https://user-images.githubusercontent.com/128224538/229192304-09785c95-107e-4c7e-84e3-ff6f5b6d1bd7.png)

#### Expected behavior
I expected this error message to not exist as im fairly certain that the mlpack::ann namespace does exist

#### Actual behavior
i get errors to do with the compiler as shown above

**Comment by rcurtin** [comment]
Yeah, the namespaces were removed and everything is now just under `mlpack::` as of mlpack 4.0.0. :+1:

**Comment by caidenmarley** [comment]
yea thank you i realised i was being stupid about 10 minutes after i posted it lol
