### ISSUE TITLE
Links in documentation not working

### ISSUE THREAD

**Issue by anablaz** [mlpack/mlpack#3461]
Hello, while getting familiar with the MLPack's repository I gathered some of the links that weren't active anymore.

Those were on Wiki, so I couldn't fix them:
#### Problem location: https://github.com/mlpack/mlpack/wiki  
Link: https://www.mlpack.org/docs/mlpack-git/doxygen/tutorials.html
Correct link: https://www.mlpack.org/docs.html (tutorials section) maybe https://github.com/mlpack/mlpack/blob/master/doc/tutorials/README.md 

#### Problem location: https://github.com/mlpack/mlpack/wiki/WindowsBuild
Link: http://keon.io/mlpack-on-windows/ However, the link above is very old - should I maybe remove it altogether?
Correct link: https://keon.github.io/mlpack-on-windows/
Link: https://www.mlpack.org/docs/mlpack-2.0.3/doxygen.php?doc=iodoc.html
Correct link: ?
Link: https://www.mlpack.org/irc/mlpack.20161214.html 
Correct link: ?

#### Problem location: https://github.com/mlpack/mlpack/wiki/DesignGuidelines
Link: https://fast-lab.org/
Correct link: ?

#### Problem location: https://github.com/mlpack/mlpack/wiki/ReleasePreparationGuide
Link: https://www.mlpack.org/var/www/www.mlpack.org/benchmark.html
Correct link: https://www.mlpack.org/benchmark.html

#### Problem location: https://github.com/mlpack/mlpack/wiki/SummerOfCodeIdeas
Link: http://knife.lugatgt.org/cgi-bin/mailman/listinfo/mlpack
Correct link: Not sure if it's meant to be this one, but it can be relevant: https://www.mlpack.org/mailman3/postorius/lists/mlpack-git.lists.mlpack.org/

Not Wiki (making a pull request):
#### Problem location: https://github.com/mlpack/mlpack/blob/master/GOVERNANCE.md
Link: https://github.com/orgs/mlpack/teams/contributors
Correct link: While the link is likely correct, it leads to a 404 page for most users.

#### Problem location: https://github.com/mlpack/mlpack/blob/master/README.md#31-additional-build-options
Link: https://conda-forge.org/packages/mlpack
Correct link:https://anaconda.org/conda-forge/mlpack 

#### Problem location: https://github.com/mlpack/mlpack/blob/master/doc/user/build_windows.md
Link: http://keon.io/mlpack-on-windows/
Correct link: https://keon.github.io/mlpack-on-windows/

**Comment by zoq** [comment]
Thanks for opening the issue.

> Problem location: https://github.com/mlpack/mlpack/blob/master/GOVERNANCE.md
> Link: https://github.com/orgs/mlpack/teams/contributors
> Correct link: While the link is likely correct, it leads to a 404 page for most users.

In this case, we can just remove the links, I can see it has a todo for adding the link to the `NumFOCUS leadership team` as well, which can be removed.

> Problem location: https://github.com/mlpack/mlpack/blob/master/README.md#31-additional-build-options
> Link: https://conda-forge.org/packages/mlpack
> Correct link:https://anaconda.org/conda-forge/mlpack

Nice catch.

> Problem location: https://github.com/mlpack/mlpack/blob/master/doc/user/build_windows.md
> Link: http://keon.io/mlpack-on-windows/
> Correct link: https://keon.github.io/mlpack-on-windows/

Nice catch.

**Comment by conradsnicta** [comment]
@zoq @rcurtin I recommend nuking the entire set of Wiki pages on GitHub, and moving any still necessary content to the mlpack website.  This is to considerably reduce the maintenance burden (and hence save time) by having all documentation related stuff in one spot, instead of having it spread across multiple sites.  Furthermore, this is also better for users, as there is one spot to find stuff.
