### ISSUE TITLE
Parameteric ReLU only applied when training?

### ISSUE THREAD

**Issue by mrdaybird** [mlpack/mlpack#3466]
In Forward method of Paramteric ReLU, there is the following _if condition_ in line 101: ([link](https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/ann/layer/parametric_relu_impl.hpp#L101))

```
 96 template<typename MatType>
 97 void PReLUType<MatType>::Forward(
 98     const MatType& input, MatType& output)
 99 {
100   output = input;
101   if (this->training)
102   {
103     #pragma omp for
104     for (size_t i = 0; i < input.n_elem; ++i)
105       output(i) *= (input(i) >= 0) ? 1 : alpha(0);
106   }
107 }
```
So the parametric relu is applied only when training the model and it works like a identity layer during inference/prediction. Is this the expected behaviour of PReLU?

**Comment by shubham1206agra** [comment]
> In Forward method of Paramteric ReLU, there is the following _if condition_ in line 101: ([link](https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/ann/layer/parametric_relu_impl.hpp#L101))
> 
> ```
>  96 template<typename MatType>
>  97 void PReLUType<MatType>::Forward(
>  98     const MatType& input, MatType& output)
>  99 {
> 100   output = input;
> 101   if (this->training)
> 102   {
> 103     #pragma omp for
> 104     for (size_t i = 0; i < input.n_elem; ++i)
> 105       output(i) *= (input(i) >= 0) ? 1 : alpha(0);
> 106   }
> 107 }
> ```
> 
> So the parametric relu is applied only when training the model and it works like a identity layer during inference/prediction. Is this the expected behaviour of PReLU?

Looks wrong
Please correct it in a PR.

**Comment by rcurtin** [comment]
I'm surprised this got overlooked, but I agree with @shubham1206agra.  It would be great to add a simple test: after training a simple network with PReLUs, a test could check that the output from `Predict()` was reasonable.
