### ISSUE TITLE
What is the best NN structure to approximate a function without bounds on arguments and values

### ISSUE THREAD

**Issue by yurivict** [mlpack/mlpack#3475]
I need to approximate a function that maps one vector space into another vector space. For example, there could be 15 arguments and 10 values. Both arguments and values can be of any fp numeric values.

I think that the last operator should be a non-linear one. But all non-linear operators have limited value range. For example, TanH value range is [-1, +1], and Sigmoid values range is [0, +1].

Such structure wouldn't work because of the argument and value range problem:
```
        FFN<mlpack::MeanSquaredError> model;
        model.Add<Sigmoid>(1000));
        model.Add<Sigmoid>();
        model.Add<Linear>(1000));
        model.Add<Sigmoid>();
        model.Add<Linear>(10);
        model.Add<Sigmoid>();
```

Is the best strategy to simply re-map all arguments and labels into a fixed range, like [-1,+1], and make sure that activation functions have the same range, or is there a more elegant solution?

**Comment by aadi-raj** [comment]
For input and output, you can use linear layer(hence, no need to scale down). In hidden layer units, you can place any activation function of your choice and as many layers. Neural network will adjust itself accordingly.

**Comment by yurivict** [comment]
Thank you!
