### ISSUE TITLE
Is there support for string feature values with preprocess_one_hot_encoding()?

### ISSUE THREAD

**Issue by evRivera** [mlpack/mlpack#3480]
I'm trying to do some preprocessing of my dataset with mlpack one hot encoding. My dataset includes categorical feature values and I'm seeing the following error when feeding the data to preprocess_one_hot_encoding():
`ValueError: could not convert string to float: 'abc'`

If I first convert the categorical (string) values to numerical values then preprocess_one_hot_encoding() works. Generally, one hot encoding is a technique that takes string values and encodes it to numerical values. **Does mlpack preprocess_one_hot_encoding() support string values?**

**Comment by rcurtin** [comment]
Sorry for the slow response here!  Right now `preprocess_one_hot_encoding()` doesn't support categorical features... but it seems obvious that it should.  I think it should be a simple code change (basically the input type of the binding just needs to be changed from a matrix to a categorical matrix), but I haven't had a chance to implement it yet.  Anyway, it's on my list, and I'll post an update when I can make that change (or if someone else gets to it before I do feel free 👍).

**Comment by evRivera** [comment]
Sounds good, thanks for the clarification and update!

**Comment by rcurtin** [comment]
Okay, I added the support in #3487.  Once that is merged, and once a new version of mlpack is released, you should be able to pass pandas DataFrames in to the binding.  Note that under the hood, what's actually happening is pretty much exactly the same as your workaround: we convert string values to integer values, then pass it to the one-hot encoding function.

**Comment by conradsnicta** [comment]
resolved in #3487

**Comment by evRivera** [comment]
thank you @rcurtin !
