### ISSUE TITLE
Make of mlpack does not generate libmlpack.so

### ISSUE THREAD

**Issue by wsrfad** [mlpack/mlpack#3482]
I cannot find any `add_library` command in CMakeLists.txt in any subfolder...And also after `make` I do not see any libs in lib folder.

`cmake -DDOWNLOAD_DEPENDENCIES=ON  -DBUILD_SHARED_LIBS=ON .. -DARMADILLO_INCLUDE_DIR=/path/Downloa
ds/armadillo-12.2.0/include/`
`make`

**Comment by rcurtin** [comment]
mlpack has been header-only since the 4.0.0 release, so there won't be any `libmlpack.so` generated. :+1:

**Comment by wsrfad** [comment]
Then why is `cmake` and `make` required. There are header only libraries like enum.h which does not require such build

**Comment by rcurtin** [comment]
You are right, you can just directly include the mlpack headers without using `cmake`.  But there are a handful of reasons why we have a build system:

 - mlpack is more than just a header-only C++ library; it also has bindings to other languages that build libraries and executables
 - CMake checks to ensure that all dependencies of mlpack (that's Armadillo, cereal, and optionally stb) are available on the system, which is a convenience to the user
 - optionally, CMake can also download any missing dependencies
 - configuring mlpack ensures that the version output is fully correct; if it is an unreleased git revision, the reported version will be the git commit hash after configuration

**Comment by wsrfad** [comment]
Thanks Ryan ! Now, it makes sense :)
