### ISSUE TITLE
linear_regression.cpp: undefined reference to `wrapper2_XXXX'

### ISSUE THREAD

**Issue by lyuhy** [mlpack/mlpack#3492]
I'm learning to use mlpack recently. It seems that armadllo and mlpack were installed well because the example codes can be compiled and run properly. However, when I tried to apply linear regression, the compiling error generated when the lines of lr.Train() or LinearRegression lr(da, la, 0.5)  were added.

The code is:
#include "targetver.h"
#include <stdio.h>
#include <tchar.h>
#include <random>
#include "mlpack/core.hpp"
#include "mlpack/methods/linear_regression/linear_regression.hpp"

using namespace arma;
using namespace mlpack;
using namespace mlpack::data;
using namespace mlpack::regression;
int main(){
mat da="1 2 3 4 5; 1 2 3 4 5; 1 2 3 4 5;1 2 3 4 5; 1 2 3 4 5; 1 2 3 4 5";
mat la3="1 2 3 4 5";
LinearRegression lr;
lr.Train(da,la3);
return0;}
***********************************
gcc command:
g++ -g -o t test.cpp -larmadillo -fopenmp -lboost_serialization -lmlpack -L/usr/local/lib/
**************************
Compiling error:
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text+0x52e): undefined reference to `wrapper2_dsyrk_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text+0xea5): undefined reference to `wrapper2_ddot_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text+0x1268): undefined reference to `wrapper2_dgemv_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text+0x1392): undefined reference to `wrapper2_dgemv_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text+0x219c): undefined reference to `wrapper2_ddot_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text+0x27e8): undefined reference to `wrapper2_dgemv_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text+0x3274): undefined reference to `wrapper2_dtrtrs_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text+0x3383): undefined reference to `wrapper2_dtrcon_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text+0x39ca): undefined reference to `wrapper2_dlansy_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text+0x39fa): undefined reference to `wrapper2_dpotrf_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text+0x3a49): undefined reference to `wrapper2_dpotrs_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text+0x3b31): undefined reference to `wrapper2_dpocon_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text+0x4bce): undefined reference to `wrapper2_dgemv_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text.hot+0x241): undefined reference to `wrapper2_dgemv_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text.hot+0x3cd): undefined reference to `wrapper2_dgemv_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text.hot+0x7ca): undefined reference to `wrapper2_dgemv_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma6auxlib16solve_approx_svdINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_8pod_typeEEESF_RKNS_4BaseISD_SC_EE[_ZN4arma6auxlib16solve_approx_svdINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_8pod_typeEEESF_RKNS_4BaseISD_SC_EE]+0x527): undefined reference to `wrapper2_ilaenv_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma6auxlib16solve_approx_svdINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_8pod_typeEEESF_RKNS_4BaseISD_SC_EE[_ZN4arma6auxlib16solve_approx_svdINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_8pod_typeEEESF_RKNS_4BaseISD_SC_EE]+0x698): undefined reference to `wrapper2_dgelsd_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma6auxlib16solve_approx_svdINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_8pod_typeEEESF_RKNS_4BaseISD_SC_EE[_ZN4arma6auxlib16solve_approx_svdINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_8pod_typeEEESF_RKNS_4BaseISD_SC_EE]+0x791): undefined reference to `wrapper2_dgelsd_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma6auxlib18solve_square_rcondINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeESF_RKNS_4BaseISD_SC_EE[_ZN4arma6auxlib18solve_square_rcondINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeESF_RKNS_4BaseISD_SC_EE]+0xe8): undefined reference to `wrapper2_dlange_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma6auxlib18solve_square_rcondINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeESF_RKNS_4BaseISD_SC_EE[_ZN4arma6auxlib18solve_square_rcondINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeESF_RKNS_4BaseISD_SC_EE]+0x115): undefined reference to `wrapper2_dgetrf_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma6auxlib18solve_square_rcondINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeESF_RKNS_4BaseISD_SC_EE[_ZN4arma6auxlib18solve_square_rcondINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeESF_RKNS_4BaseISD_SC_EE]+0x1c5): undefined reference to `wrapper2_dgetrs_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma6auxlib18solve_square_rcondINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeESF_RKNS_4BaseISD_SC_EE[_ZN4arma6auxlib18solve_square_rcondINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeESF_RKNS_4BaseISD_SC_EE]+0x299): undefined reference to `wrapper2_dgecon_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma6auxlib16solve_rect_rcondINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeESF_RKNS_4BaseISD_SC_EE[_ZN4arma6auxlib16solve_rect_rcondINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeESF_RKNS_4BaseISD_SC_EE]+0x26a): undefined reference to `wrapper2_dgels_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma6auxlib16solve_rect_rcondINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeESF_RKNS_4BaseISD_SC_EE[_ZN4arma6auxlib16solve_rect_rcondINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeESF_RKNS_4BaseISD_SC_EE]+0x774): undefined reference to `wrapper2_dgels_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma6auxlib16solve_rect_rcondINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeESF_RKNS_4BaseISD_SC_EE[_ZN4arma6auxlib16solve_rect_rcondINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeESF_RKNS_4BaseISD_SC_EE]+0xa76): undefined reference to `wrapper2_dtrcon_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma6auxlib16solve_rect_rcondINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeESF_RKNS_4BaseISD_SC_EE[_ZN4arma6auxlib16solve_rect_rcondINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeESF_RKNS_4BaseISD_SC_EE]+0xce2): undefined reference to `wrapper2_dtrcon_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_11subview_colIdEENS_9op_htransEEENS_3MatIdEEEEvRNS8_INT_9elem_typeEEERKNS_4GlueISA_T0_NS_10glue_timesEEE[_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_11subview_colIdEENS_9op_htransEEENS_3MatIdEEEEvRNS8_INT_9elem_typeEEERKNS_4GlueISA_T0_NS_10glue_timesEEE]+0x130): undefined reference to `wrapper2_dgemv_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_11subview_colIdEENS_9op_htransEEENS_3MatIdEEEEvRNS8_INT_9elem_typeEEERKNS_4GlueISA_T0_NS_10glue_timesEEE[_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_2OpINS_11subview_colIdEENS_9op_htransEEENS_3MatIdEEEEvRNS8_INT_9elem_typeEEERKNS_4GlueISA_T0_NS_10glue_timesEEE]+0x425): undefined reference to `wrapper2_dgemv_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma6auxlib23solve_band_rcond_commonINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeERKSE_yyRKNS_4BaseISD_SC_EE[_ZN4arma6auxlib23solve_band_rcond_commonINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeERKSE_yyRKNS_4BaseISD_SC_EE]+0x350): undefined reference to `wrapper2_dlangb_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma6auxlib23solve_band_rcond_commonINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeERKSE_yyRKNS_4BaseISD_SC_EE[_ZN4arma6auxlib23solve_band_rcond_commonINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeERKSE_yyRKNS_4BaseISD_SC_EE]+0x391): undefined reference to `wrapper2_dgbtrf_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma6auxlib23solve_band_rcond_commonINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeERKSE_yyRKNS_4BaseISD_SC_EE[_ZN4arma6auxlib23solve_band_rcond_commonINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeERKSE_yyRKNS_4BaseISD_SC_EE]+0x406): undefined reference to `wrapper2_dgbtrs_'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /usr/local/lib//libmlpack.a(linear_regression.cpp.o):linear_regression.cpp:(.text$_ZN4arma6auxlib23solve_band_rcond_commonINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeERKSE_yyRKNS_4BaseISD_SC_EE[_ZN4arma6auxlib23solve_band_rcond_commonINS_4GlueINS_3MatIdEENS_2OpINS_3RowIdEENS_9op_htransEEENS_10glue_timesEEEEEbRNS3_INT_9elem_typeEEERNSC_8pod_typeERKSE_yyRKNS_4BaseISD_SC_EE]+0x537): undefined reference to `wrapper2_dgbcon_'
collect2: error: ld returned 1 exit status
***************************************
when call cmake.. for armadillo:

-- *** set cmake policy CMP0025 to NEW
-- CMAKE_CXX_STANDARD = 11
-- Configuring Armadillo 12.3.90
-- Detected gcc 4.8.3 or newer
-- ARMA_USE_EXTERN_RNG = false
-- CMAKE_SYSTEM_NAME          = CYGWIN
-- CMAKE_CXX_COMPILER_ID      = GNU
-- CMAKE_CXX_COMPILER_VERSION = 11.3.0
-- CMAKE_COMPILER_IS_GNUCXX   = 1
--
-- *** Options:
-- BUILD_SHARED_LIBS         = ON
-- OPENBLAS_PROVIDES_LAPACK  = OFF
-- ALLOW_FLEXIBLAS_LINUX     = ON
-- ALLOW_OPENBLAS_MACOS      = OFF
-- ALLOW_BLAS_LAPACK_MACOS   = ON
-- BUILD_SMOKE_TEST          = ON
--
-- *** Looking for external libraries
-- Found BLAS: /usr/lib/libblas.dll.a
-- Found LAPACK: /usr/lib/liblapack.dll.a
-- FlexiBLAS_FOUND = false
--       MKL_FOUND = NO
--  OpenBLAS_FOUND = NO
--     ATLAS_FOUND = NO
--      BLAS_FOUND = YES
--    LAPACK_FOUND = YES
-- Found ARPACK: /usr/lib/libarpack.dll.a
-- ARPACK_FOUND = YES
-- Looking for SuperLU version 5
-- Could not find SuperLU
-- SuperLU_FOUND = NO
--
-- *** Result of configuration:
-- *** ARMA_USE_WRAPPER    = true
-- *** ARMA_USE_LAPACK     = true
-- *** ARMA_USE_BLAS       = true
-- *** ARMA_USE_ATLAS      = false
-- *** ARMA_USE_ARPACK     = true
-- *** ARMA_USE_EXTERN_RNG = false
-- *** ARMA_USE_SUPERLU    = false
--
-- *** Armadillo wrapper library will use the following libraries:
-- *** ARMA_LIBS = /usr/lib/libblas.dll.a;/usr/lib/liblapack.dll.a;/usr/lib/libarpack.dll.a
--
-- Copying /home/user/armadillo-code/include/ to /home/user/armadillo-code/tmp/include/
-- Generating /home/user/armadillo-code/tmp/include/config.hpp
-- CMAKE_CXX_FLAGS           =  -O2
-- CMAKE_SHARED_LINKER_FLAGS =
-- CMAKE_REQUIRED_INCLUDES   =
--
-- CMAKE_INSTALL_PREFIX     = /usr
-- CMAKE_INSTALL_LIBDIR     = lib
-- CMAKE_INSTALL_INCLUDEDIR = include
-- CMAKE_INSTALL_DATADIR    = share
-- CMAKE_INSTALL_BINDIR     = bin
-- Generating '/home/user/armadillo-code/ArmadilloConfig.cmake'
-- Generating '/home/user/armadillo-code/ArmadilloConfigVersion.cmake'
-- Generating '/home/user/armadillo-code/InstallFiles/ArmadilloConfig.cmake'
-- Generating '/home/user/armadillo-code/InstallFiles/ArmadilloConfigVersion.cmake'
-- Copying /home/user/armadillo-code/misc/ to /home/user/armadillo-code/tmp/misc/
-- Generating '/home/user/armadillo-code/tmp/misc/armadillo.pc'
-- *** configuring smoke_test
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/armadillo-code
****************************************
The mlpack version is 3.4.2

**Comment by rcurtin** [comment]
Just as an aside, life gets a little easier for linking if you move to mlpack 4.x, since mlpack is header-only and no longer has a boost dependency (so you could remove the `-lboost_serialization -lmlpack`).

The Armadillo configuration output looks correct, so I am wondering how you installed Armadillo.  Did the Armadillo headers get installed into `/usr/local/include/`, and the Armadillo libraries get installed into `/usr/local/lib/`?  As a guess, I wonder if adding `-I/usr/local/include/` to the compilation command will help.  Make sure there's only one version of Armadillo present on the system, and that the version being used by the compiler when including and when linking are the same.

**Comment by lyuhy** [comment]
Thanks for your advice. I chose the old version because I want to use mlpack in a platform based on C++11.

I checked armardillo's location and found that it was installed in usr/ not in usr/local/, so I uninstall the whole cygwin environment and reinstall mlpack and its related dependencies in usr/local/, however, same issue occurred. Also, -I/usr/local/include/ doesn't work.

**Comment by lyuhy** [comment]
And attached images are installed files in usr/local/include/ usr/local/lib/ and usr/local/bin/
<img width="311" alt="include" src="https://github.com/mlpack/mlpack/assets/135222383/b0ec7188-5bb1-4408-b5ed-dcbc89e2f504">
<img width="323" alt="bin" src="https://github.com/mlpack/mlpack/assets/135222383/a3f05e09-b517-4b6f-b007-1a76420400d6">
<img width="317" alt="lib" src="https://github.com/mlpack/mlpack/assets/135222383/e82917dd-c322-4fbe-a174-4f1bb5e14892">

**Comment by conradsnicta** [comment]
Old releases like mlpack 3.4.2 are no longer supported.  We don't really have the bandwidth for that.  If you wish to continue using mlpack 3.4.2, you're on your own.

Furthermore,  this issue does not appear directly tied to mlpack. The core problems seems to be an installation problem you have with Armadillo on Cygwin, a Linux-like emulation layer on Windows.  Cygwin has always been problematic, as at best it's a rough approximation of a proper Linux environment.

Suggest the following:
- manually remove all currently installed versions of Armadillo; this includes the runtime library and the header files; look in places like /usr/lib, /usr/lib64, /usr/local/lib, /usr/local/lib64, /usr/include, /usr/local/include, ...
- [download](https://arma.sourceforge.net/download.html) the latest version of Armadillo, and reinstall it
- make sure the armadillo example program runs on your setup
- upgrade your compiler to allow use of C++14, preferably GCC 11 or 12; the C++14 standard is supported by GCC since GCC 5.x (released in 2015, about 8 years ago)
- move to mlpack 4.1

If you can't get things working on Cygwin, either use WSL, or a proper Linux installation like Ubuntu, Fedora, AlmaLinux, RockyLinux, Debian, etc.
