### ISSUE TITLE
Is there a way to use mlpack in C++ with runtime polymorphism?

### ISSUE THREAD

**Issue by HeftyCoder** [mlpack/mlpack#3508]
Hello! I've been developing a framework for EEG and Eye-Gaze processing. I would like to include some traditional machine learning algorithms. Development is in C++ so I can maximize performance where I can.

I opted to use mlpack for machine learning implementations, but its static nature has made it difficult. I wanted to be able to use dynamic polymorphism for usage in a base classifier class. I'm relatively new to C++, so I thought I'd ask. Is this in any way possible, or should I expect lots of boilerplate code? Currently the hardest thing for me is the use of hyper-parameter tuning and cross-validation, since there is seemingly no way to break the tuning, the validation and the model into different components in the code.

I'd appreciate some help or whether I should opt for a different library for my needs. Its proven kind of difficult to find out of the box implementations in C++, though. Thanks a lot!

EDIT: I understand that template metaprogramming makes for a faster library by avoiding runtime virtual function calls. I would think the runtime cost would be inherent to each of the three, namely model - validation method - parameter tuning. Is it unwise to think that providing a base model, base validation method and base parameter tuning wouldn't hurt performance that much? I do realize it would probably be a major refactor and opposite to the libraries intentions.. I'm simply trying to understand if speed is that impacted if one would opt to switch a validation's model on the spot.

**Comment by rcurtin** [comment]
Hi there @HeftyCoder,

The biggest place that virtual function calls would have a noticeable difference is in inner loops; one example is, e.g., the distance metric used in k-nearest-neighbor search.  Another example would be a very cheap member function.  To make up a slightly contrived situation, imagine mlpack had a base learner class that implemented the function `GetNumberOfTrainingPoints()` (and also imagine that we cached that at training time for some reason...).  If a user writes a complicated function that calls `GetNumberOfTrainingPoints()` in some deep inner loop, then the vtable lookup penalty can be noticed there.  For this and similar reasons, mlpack has generally tried to avoid dynamic polymorphism.

(Of course, it is true that for larger functions, the vtable lookup penalty is generally unnoticeable.  For instance, if training the model takes even 10ms or some similarly small amount of time, one single vtable lookup at the start of that function is of negligible cost.  But that is a little besides the reasoning above.  I don't think there would be huge opposition to a change that also addressed the situations above, but you are right it would be a reasonably large refactoring.)

Anyway, to answer your original question more directly, I think that there are not many ways around the boilerplate here.  It would be relatively easy to write a single wrapper for a machine learning method, something like this:

```
class MyLogisticRegression : public BaseModel
{
  MyLogisticRegression( stuff ... ) : model( stuff ... ) { }
  
  virtual void Train( stuff ... ) { model.Train( stuff ... ); }
  
  LogisticRegression model;
};
```

and it may even be possible to use templates...

```
template<typename ModelType>
class MyModel : public BaseModel
{
  MyModel( stuff ... ) : model( stuff ... ) { }
  
  virtual void Train( stuff ... ) { model.Train( stuff ... ); }

  ModelType model;
};
```

The trick would just be settling on standardized parameters for `stuff ...`, but at least mlpack's `Train()` and `Predict()` APIs are consistent across learners (at least for the data and responses).

I hope this helps; let me know if I can clarify anything. :+1:

**Comment by HeftyCoder** [comment]
Thanks for the swift reply @rcurtin. I had read the reasoning behind using static polymorphism, so I had no problem understanding its usage. What I don't understand with that decision is that everything is completely static. Just like you mentioned, there should be functions where a look-up should not matter at all. Template type constraints might actually be useful for solving these issues, but it's a C++20 thing and I believe it won't be compatible with this library for some time.

To further clarify, I also see some decisions on separation of concerns that I can't wrap my head around. For example, all the performance metrics for classification problems call Classify inside the Evaluation method. That means that there is no out of the box way to get multiple metrics without classifying again (unless I'm missing something). Is the reason to accommodate cross-validation for large k? Or because of the general philosophy of not using dynamic polymorphism?

All in all, I should probably clarify on what I plan to do. I intend to build UIs for training, validating and perhaps tuning various models. For designing the UIs for specific model parameters, dynamic polymorphism wouldn't solve the issue. I need to map specific metadata for each classifier so I can build my UIs and connect them to mlpack. Essentially, I need to be able to pass the metadata to a method and receive common interfaces for tuning, cross-validation and the model. Currently I am in search for a metadata repository, like OpenML.

Do you think it would be possible to achieve what I want with mlpack without too much boilerplate?

**Comment by HeftyCoder** [comment]
Making abstractions for the models shouldn't be that hard. The major boilerplate I'm seeing is the hyper parameter tuner and cross validation. I'll try and think of something and update appropriately when I can!

**Comment by rcurtin** [comment]
As far as I know the CV and HPT parts of mlpack are a little underadvertised and underused, so I think there is some opportunity for improvement to their APIs and usability that is possible.  If you have any suggestions or patches that make your life way easier---or if there is some simple and standard use case that CV/HPT does not support that it should---the feedback would definitely be welcomed. :+1:
