### ISSUE TITLE
ensmallen not installed in installation directory when running make install

### ISSUE THREAD

**Issue by kiner-shah** [mlpack/mlpack#3517]
#### Issue description

When I run `make install` the ensmallen header files are not copied to the installation directory. I had to manually copy the folder else when I tried to compile a sample C++ file, I got a compilation error:
```
In file included from mlpack-4.2.0/build/installdir/include/mlpack/core.hpp:57,
                 from mlpack-4.2.0/build/installdir/include/mlpack.hpp:27,
                 from lr_sample.cpp:3:
mlpack-4.2.0/build/installdir/include/mlpack/core/hpt/hpt.hpp:18:10: fatal error: ensmallen.hpp: No such file or directory
   18 | #include <ensmallen.hpp>
      |          ^~~~~~~~~~~~~~~
```

#### Your environment

 * version of mlpack: 4.2.0
 * operating system: Ubuntu 22.04
 * compiler: g++ 11.3.0
 * version of dependencies (Boost/Armadillo): Armadillo 10.3.0
 * any other environment information you think is relevant:

#### Steps to reproduce

```
sudo apt-get install libblas-dev liblapack-dev
cd mlpack-4.2.0
mkdir build && cd build
cmake -DDOWNLOAD_DEPENDENCIES=ON -DDEBUG=ON -DCMAKE_INSTALL_PREFIX=$PWD/installdir ..
make install
```

#### Expected behavior

ensmallen include folder contents should get copied to `installdir/include`.
```
$ ls -oart installdir/include/
-rw-r--r-- 1 user   30101 Jun 16  2016 armadillo
-rw-r--r-- 1 user   66570 Nov 10  2020 stb_image_write.h
-rw-r--r-- 1 user  263262 Nov 10  2020 stb_image.h
-rw-r--r-- 1 user      98 Nov 10  2020 hash.md5
-rw-r--r-- 1 user    2970 Jun 17 01:17 mlpack.hpp
drwxr-xr-x 2 user   32768 Jul 30 18:27 armadillo_bits
drwxr-xr-x 6 user    4096 Jul 30 18:27 cereal
drwxr-xr-x 6 user    4096 Jul 30 18:27 ensmallen.hpp
drwxr-xr-x 6 user    4096 Jul 30 18:27 ensmallen_bits
drwxr-xr-x 5 user    4096 Jul 30 18:27 .
drwxr-xr-x 4 user    4096 Jul 30 18:27 mlpack
drwxr-xr-x 4 user    4096 Jul 30 18:27 ..
```

#### Actual behavior

ensmallen include folder contents aren't copied to `installdir/include`.
```
$ ls -oart installdir/include/
-rw-r--r-- 1 user   30101 Jun 16  2016 armadillo
-rw-r--r-- 1 user   66570 Nov 10  2020 stb_image_write.h
-rw-r--r-- 1 user  263262 Nov 10  2020 stb_image.h
-rw-r--r-- 1 user      98 Nov 10  2020 hash.md5
-rw-r--r-- 1 user    2970 Jun 17 01:17 mlpack.hpp
drwxr-xr-x 2 user   32768 Jul 30 18:27 armadillo_bits
drwxr-xr-x 6 user    4096 Jul 30 18:27 cereal
drwxr-xr-x 5 user    4096 Jul 30 18:27 .
drwxr-xr-x 4 user    4096 Jul 30 18:27 mlpack
drwxr-xr-x 4 user    4096 Jul 30 18:27 ..
```

**Comment by rcurtin** [comment]
Do you have the output from the `make install` step?  Maybe something went wrong there?  I tried this on my local system and ensmallen was successfully installed:

```
$ ls -l ~/mlpack-install-test/include/
total 20
drwxr-xr-x 48 ryan ryan 4096 Jul 31 12:24 ensmallen_bits
-rw-r--r--  1 ryan ryan 5084 Jan 28  2023 ensmallen.hpp
drwxr-xr-x  4 ryan ryan 4096 Jul 31 12:24 mlpack
-rw-r--r--  1 ryan ryan 2970 Jun 14 09:13 mlpack.hpp
```

(in my case I already had all the other dependencies, so downloading Armadillo, cereal, and STB weren't needed.)

Any other output you can give, e.g., from the CMake configure step, could be helpful too. :+1:

**Comment by rcurtin** [comment]
I spent a while trying to reproduce this in an Ubuntu 22.04 Docker container, using exactly the instructions you gave as well as a few variations, but I couldn't.  Each time ensmallen's headers are installed correctly.

Can you paste what's in `cmake_install.cmake`?  It should have a stanza about installing ensmallen.  Here is my example from the Docker container I was using:

```
if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include" TYPE DIRECTORY FILES "/root/mlpack-4.2.0/build/deps/armadillo-10.3.0/include/")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include" TYPE DIRECTORY FILES "/root/mlpack-4.2.0/build/deps/stb/include/")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include" TYPE DIRECTORY FILES "/root/mlpack-4.2.0/build/deps/ensmallen-2.19.1/include/")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include" TYPE DIRECTORY FILES "/root/mlpack-4.2.0/build/deps/cereal-1.3.0/include/")
endif()
```

**Comment by kiner-shah** [comment]
@rcurtin Unfortunately I cannot find the line for ensmallen in cmake_install.cmake.
[cmake_install.cmake.txt](https://github.com/mlpack/mlpack/files/12293446/cmake_install.cmake.txt)
Not sure, why it doesn't work on my system. You may close this issue if it's not reproducible. Thanks for the support.

**Comment by rcurtin** [comment]
If you have a way to reproduce it in a clean, e.g., Ubuntu Docker container (which I could then fully reproduce), I can look into it---otherwise I agree, I'm not sure what's going on here and not sure it's reproducible.  My last guess is just to nuke your build directory and try again (but maybe you already did that).

**Comment by kiner-shah** [comment]
@rcurtin Yes I tried deleting the build directory and retrying but didn't work. I think it's some issue in my system since on another system where I tried I couldn't reproduce the issue as well.

**Comment by mgaimann** [comment]
I got the same error, it appeared when I used this to build: 

```
cmake -S . -B build
cmake --build build --target install
```

It worked for me when I used these commands:
```
mkdir build && cd build/
cmake ..
make install
```
