### ISSUE TITLE
BLAS, LAPACK dependencies not installed when using DOWNLOAD_DEPENDENCIES flag

### ISSUE THREAD

**Issue by kiner-shah** [mlpack/mlpack#3519]
#### Problem location

https://github.com/mlpack/mlpack/blob/master/README.md#2-dependencies

#### Description of problem

The dependencies list that Armadillo is required, but mentions about BLAS, LAPACK requirement indirectly:
> If you are compiling Armadillo by hand, ensure that LAPACK and BLAS are enabled.

When using `DOWNLOAD_DEPENDENCIES` flag to download the required dependencies, it doesn't download BLAS, LAPACK and then the compilation fails. It should be added to the documentation that BLAS, LAPACK are required by Armadillo and thus are also dependencies. Also, better to include the commands for Ubuntu/Debian for installing those packages: `sudo apt-get install libblas-dev liblapack-dev`.

**Comment by conradsnicta** [comment]
The documentation is correct.

BLAS (preferably OpenBLAS) and LAPACK are direct dependencies of Armadillo, not mlpack.

mlpack doesn't directly call BLAS and LAPACK functions.  mlpack uses linear algebra (and related) functions via Armadillo.
