### ISSUE TITLE
Linker errors when building mlpack from source - Linux

### ISSUE THREAD

**Issue by kiner-shah** [mlpack/mlpack#3526]
#### Problem location
https://github.com/mlpack/mlpack/blob/4.2.0/README.md#31-additional-build-options

#### Description of problem

I have built mlpack from source code.

Here it mentions that to compile a program that uses mlpack we need to provide `-larmadillo` option. I tried but got linker error:
```
/usr/bin/ld: cannot find -larmadillo: No such file or directory
collect2: error: ld returned 1 exit status
```
I checked the installation directory where files are installed but couldn't find armadillo library. I came to know that armadillo can be used without runtime library from this [link](https://arma.sourceforge.net/faq.html#linking) as below:
```
g++ my_program.cpp -o my_program -O2 -I mlpack-4.2.0/build/installdir/include -DARMA_DONT_USE_WRAPPER -lblas -llapack
```

**Comment by conradsnicta** [comment]
@kiner-shah Not sure what the problem is here?  Suggest you install Armadillo either (1) using your package manager, or (2) download it from [here](https://arma.sourceforge.net/download.html) or [here](https://gitlab.com/conradsnicta/armadillo-code) and install it manually.  See the README.md file within the Armadillo archive for details on how to install it manually.

**Comment by kiner-shah** [comment]
@conradsnicta, I downloaded armadillo by using `DOWNLOAD_DEPENDENCIES=ON`
option when running CMake. And when I run `make install` it just copies the
header files into the installation directory and no library is created. But
the docs suggest to use `-larmadillo` option which doesn't work. To get my
example code to compile successfully, I had to use the options I stated
before, I was hoping if that can be added to the documentation for anyone
else facing the same issue.

**Comment by kiner-shah** [comment]
Thanks for the changes.
I had used autodownloader because I thought it would be a good idea to avoid installing libraries that are available system-wide and also, it seems like a very convenient feature :-) as it takes care of all required dependencies.
