### ISSUE TITLE
Can you include `mlpack.hpp` into the python wheel?

### ISSUE THREAD

**Issue by rdbisme** [mlpack/mlpack#3544]
### What is the desired addition or change?

I'd love to have the right matching header file into the python manylinux wheel to avoid the need of rebuilding all the dependencies of mlpack (Armadillo, openblas, etc...) on the manylinux image just to link against it. 

### What is the motivation for this feature?
I'm working on a Python compiled extension written in C++, and I'd love to use mlpack in it. Right now I'd probably need to provide a matching `hpp` file manually and do some manual shenanigans to link against openblas. Is there a way you might make it easier such that adding `mlpack` in the build-requires of `pyproject.toml` provides me with all I need to link against it? I think the only thing missing is the header file associated to the version the wheel is built with.

**Comment by rcurtin** [comment]
I see---I hadn't thought about this.  I think it could be possible and I think I see how, although I'm not 100% sure if I'm overlooking something.  Do you know of any other PyPI packages that ship C++ header files in the wheel that I could use an example for how this is commonly done?  I'm specifically interested in where they put the headers.  Then, from your end, how would I make it easy for you to get the include paths right?  I'll dig into what numpy does, but if you have other examples I'd love to look at them too.

**Comment by rdbisme** [comment]
> I see---I hadn't thought about this. I think it could be possible and I think I see how, although I'm not 100% sure if I'm overlooking something. Do you know of any other PyPI packages that ship C++ header files in the wheel that I could use an example for how this is commonly done? I'm specifically interested in where they put the headers. Then, from your end, how would I make it easy for you to get the include paths right? I'll dig into what numpy does, but if you have other examples I'd love to look at them too.

My favourite way would be something similar to `pybind11`. They include a `pybind11Config.cmake` in the wheel that I can use with `find_package(pybind11)` and everything works as expected. 

Another project is `pyarrow`, but in that case is easier because they ship pre-compiled packages of their c++ lib that can be used on manylinux adding some repos. 

The alternative might be to have an `rpm` repo that ships the include and can be added on all manylinuxes distros.

**Comment by rdbisme** [comment]
Not stale!

**Comment by rcurtin** [comment]
Yep, I'm planning on handling this with the 4.3.0 release (#3562). :+1:

**Comment by rcurtin** [comment]
Hey there @rdbisme, sorry it took a while to get this figured out.  I opened #3579, which will incorporate the fixes I added to future releases of mlpack.  Right now, mlpack version 4.3.0.post1 is building for PyPI, and wheels should probably start succeeding and getting uploaded by tomorrow.  When you install these wheels, they should have the following directories:

 * `mlpack/include/`: has all header files for mlpack
 * `mlpack/share/pkgconfig/mlpack.pc`: a pkgconfig file to include mlpack correctly

I followed the way pybind11 does it; hopefully everything works ok.  When the new version of wheels upload to PyPI, can you test and make sure I didn't miss anything?  My own local tests worked fine, but you may be intending to use this in a different way than I tested.

Thanks! :+1:
