### ISSUE TITLE
MLPACK_STRING_VIEW error

### ISSUE THREAD

**Issue by ZakyShan** [mlpack/mlpack#3549]
Hi,
Im Trying to use Mlpack for a project.
Im on windows and I have correctly build and linked everything and now when I want to use mlpack in my project I have this error:
identifier "MLPACK_STRING_VIEW" not defined in C:\mlpack\mlpack\src\mlpack\core\data\string_encoding_dictionary.hpp	113

I have no idea how to revolve this.

Can someone help me please ?

**Comment by rcurtin** [comment]
Can you tell us a little more about your project setup?  Specifically, what files are you including from mlpack?

**Comment by conradsnicta** [comment]
@ZakyShan mlpack 3.3.2 is outdated and no longer supported. The current version of mlpack is 4.2.1.

Is there a specific reason for using the old 3.3.2 version?

More recent documentation for building on Windows is here: https://github.com/mlpack/mlpack/blob/4.2.1/doc/user/build_windows.md

**Comment by ZakyShan** [comment]
Ty @conradsnicta for your response, I follow what you sended me and I still have the same issue "MLPACK_STRING_VIEW" not defined
![image](https://github.com/mlpack/mlpack/assets/66197353/6e0523c4-54bd-4493-bb1a-1ad4d2fee622)
I think Im doing something wrong but I cant get what :(

**Comment by ZakyShan** [comment]
I think it's because my mlpack is not build in c++17, how can I specifically ask to build in c++17 ?
I have tried to change in properties and also change in the CMakeLists.txt

**Comment by rcurtin** [comment]
Here's the updated version of the tutorial you were using: https://github.com/mlpack/mlpack/blob/4.2.1/doc/user/sample_ml_app.md

Try `#include <mlpack.hpp>`, not `#include <mlpack/core.hpp>`.  I think this will fix your issue.  I'm not sure how to change the C++ mode in Visual Studio (I'm not a VS user), but I think the include change should fix the problem.

**Comment by ZakyShan** [comment]
The issue is not in my project sample_ml_app but in my mlpack project, in the file string_encoding_dictionary.hpp I have an error on every MLPACK_STRING_VIEW not define because in the base.hpp file
`#elif __cplusplus < 201703L && defined(_MSC_VER)
  #error "When using Visual Studio, mlpack should be compiled with /Zc:__cplusplus and /std:c++17 or newer."
#else
  #include <any>
  #include <string_view>
  #define MLPACK_ANY std::any
  #define MLPACK_ANY_CAST std::any_cast
  #define MLPACK_STRING_VIEW std::string_view`
I have the error:  "When using Visual Studio, mlpack should be compiled with /Zc:__cplusplus and /std:c++17 or newer."
So it doesn't go in in the else for the attribution `#define MLPACK_STRING_VIEW std::string_view`

**Comment by ZakyShan** [comment]
Yes, that's what I done but it doesn't want to work.
(I set to C++17 then I build the solution)

**Comment by conradsnicta** [comment]
Because MSVC is "special" in many ways, there is an MSVC specific macro that indicates which version of the C++ standard is being used: `_MSVC_LANG`. This is in addition to `__cplusplus` macro, which may or may not reflect the actual setting of the C++ standard, depending on byzantine configuration options and compiler switches.

To check if MSVC is in something resembling C++17 mode, this can be used:

    #if defined(_MSVC_LANG)
      #if (_MSVC_LANG >= 201703L)
        #undef  MLPACK_HAVE_CXX17
        #define MLPACK_HAVE_CXX17
      #endif
    #endif

**Comment by rcurtin** [comment]
Ah, nice, that would be a good thing to include in the future.  According to [their documentation](https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170) if you specify the `/Zc:__cplusplus` option, then `__cplusplus` will be defined to be whatever the actual version of the standard being used is; so, @ZakyShan, make sure that that option is specified in addition to the `/std:c++17` option.  If that doesn't work, you'll need to look into what the value of `__cplusplus` is and try to figure out why it is not being set correctly (according to those two options).

**Comment by ZakyShan** [comment]
Thank you guys, my project can run.
I added /Zc:__cplusplus  in Configuration Properties > C/C++ > Command Line property page > Additional options: pane.

**Comment by rcurtin** [comment]
Awesome, glad you got it worked out. :+1: I'll go ahead and close the issue then.
