### ISSUE TITLE
Add accuracy measure for mlpack_logistic_regression ?

### ISSUE THREAD

**Issue by jamesstuartgunning** [mlpack/mlpack#3552]
I like the look of the cmdline mlpack_logistic_regression
Can a computation of the "accuracy" be dumped to stdout or similar for users?
This would be analogous to something like LogisticRegression.score() (in python )

LRG = linear_model.LogisticRegression(random_state = 0,solver = 'liblinear',fit_intercept=True,multi_class = 'auto')
LRG.fit(X,Y)
print("LogisticRegression Score ",LRG.score(X, Y))
-->

### What is the motivation for this feature?
It's a common very interesting measure and I don't see it in the demo code

### If applicable, describe how this feature would be implemented.
It's in the logistic_regression API already - just takes a few lines to print it out.

**Comment by rcurtin** [comment]
`mlpack_random_forest` has the argument `print_training_accuracy` that does the same thing---it would be easy to add and a nice feature.  Would you be interested in contributing the feature?

**Comment by rabbabansh** [comment]
@rcurtin can I take this issue up?

**Comment by jamesstuartgunning** [comment]
Hi All,
     I would be able to do this, but am very pressed for time. I would be grateful
for Ansh to do this!
Many thanks
James.

James Gunning
CSIRO
Clayton, Vic., Australia

________________________________

**Comment by indrasn0wal** [comment]
I would like to work on this issue. Can you assign me this issue?

**Comment by rcurtin** [comment]
This went stale and was closed, but with #3554 merged it is actually solved and will be included in the next stable release of mlpack. :+1:

**Comment by jamesstuartgunning** [comment]
Hi Ryan,
        This is great, thanks so much. And thanks for your work on what looks like a great project.
Cheers
James


James Gunning
CSIRO
Clayton, Vic., Australia
________________________________
