### ISSUE TITLE
Error in use of preprocess_split() in LinearRegression.

### ISSUE THREAD

**Issue by indrasn0wal** [mlpack/mlpack#3556]
### Problem location
mlpack Python documentation [(https://www.mlpack.org/doc/stable/python_documentation.html#class-linear_regression)]

### Description of the problem
preprocess_split() return a dictionary containing **_'test','test_labels','training','training_labels'_**. In the documentation example of LinearRegression. The way it's being used `X_test, y_test, X_train, y_train = preprocess_split(input_=X, input_labels=y, test_ratio=0.2)` will give string output and not a matrix, which should cause an error while doing `model.fit()`. I have attached the file regarding the error. One thing we can do is instead of returning the dictionary while using preprocess_split(), it can return matrix output, `X_test, y_test, X_train, y_train`. That way it will be easy to use. 
![Documentation_mlpack](https://github.com/mlpack/mlpack/assets/97403063/427f5a1b-5112-43e9-ae58-00d781daf208)
![error](https://github.com/mlpack/mlpack/assets/97403063/eea3e45a-6e97-4827-820e-8adea387477e)

**Comment by rcurtin** [comment]
I opened a patch in #3563 to fix the underlying code that generates the incorrect documentation.  Once that's merged and the next version of mlpack is released, the issue should be fixed in the online documentation. :+1:
