### ISSUE TITLE
Hierarchial Clustering Methods

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#356]
**Reported by abhinav on 19 Dec 44926540 22:50 UTC**
Sometimes, when we cannot decide how many clusters to choose, we can use Hierarchical Clustering Methods, as these are tailor made for this kind of clustering.
I have a month long vacation, and thinking of implementing this feature myself according to mlpack coding conventions.

Inspired by #370.

Migrated-From: http://trac.research.cc.gatech.edu/fastlab/ticket/374

**Comment by manish7294** [comment]
@rcurtin It seems like Hierarchial Clustering is still to be implemented or is there any open PR? If not I would like to start with agglomerative one. If that's fine please suggest me a good research paper for the same.
