### ISSUE TITLE
MPLACK failed build in x86 mode

### ISSUE THREAD

**Issue by WillaCao** [mlpack/mlpack#3566]
I have build mlpack project with VS2022 x86 native tools command prompt. But some errors were reported. Does mlpack not support x86 architecture? can you guys help me take a look? Thanks in advance!
#### Your environment

 * version of mlpack:
 * operating system:Windows 10
 * compiler:
 * version of dependencies (Boost/Armadillo):armadillo-10.7.4
 * any other environment information you think is relevant:

#### Steps to reproduce
1.git clone https://github.com/mlpack/mlpack F:\gitP\mlpack\mlpack
2.git -C "F:\gitP\mlpack\mlpack" clean -xdf
3.git -C "F:\gitP\mlpack\mlpack" fetch --recurse-submodules=no --force
4.git -C "F:\gitP\mlpack\mlpack" reset --hard bbde929
5.git -C "F:\gitP\mlpack\mlpack" remote prune origin
6.set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=x86 -arch=x86
7.set _CL_=/wd4251 /wd4244 /wd4291 /wd4018 /wd4275 /wd4250 /wd4996 %_CL_%
8.cd F:\gitP\mlpack\mlpack\build_x86
9.cmake -G "Visual Studio 17 2022" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DBLAS_LIBRARIES=F:\tools\mlpack\external\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a -DLAPACK_LIBRARIES=F:\tools\mlpack\external\OpenBLAS.0.2.14.1\lib\native\lib\x64\libopenblas.dll.a -DARMADILLO_INCLUDE_DIR=F:\tools\mlpack\external\armadillo-10.7.4\include -DARMADILLO_LIBRARY=F:\tools\mlpack\external\armadillo-10.7.4\lib\armadillo.lib -DBOOST_INCLUDEDIR=F:\tools\boost_1_67_0\x64 -DBOOST_LIBRARYDIR= F:\tools\boost_1_67_0\x64\lib64-msvc-14.1 -DCEREAL_INCLUDE_DIR=F:\tools\mlpack\cereal-1.3.0\include -DDEBUG=OFF -DPROFILE=OFF -DENSMALLEN_INCLUDE_DIR=F:\tools\mlpack\external\ensmallen-2.18.1\include ..
10.msbuild /m /p:Platform=Win32 /p:Configuration=Release /p:PreferredToolArchitecture=x64 mlpack.sln /t:Rebuild

#### Expected behavior
Build Pass.

#### Actual behavior
error LNK2019: unresolved external symbol _ddot_ referenced in function "public: static void __cdecl arma::syrk_vec<1,0,0>::apply<double,class arma::Mat<double> >(class arma::Mat<double> &,class arma::Mat<double> const &,double,double)" (??$apply@NV?$Mat@N@arma@@@?$syrk_vec@$00$0A@$0A@@arma@@SAXAAV?$Mat@N@1@ABV21@NN@Z)
error LNK2001: unresolved external symbol _dasum_
fatal error LNK1120: 12 unresolved externals

[mlpack_x86.log](https://github.com/mlpack/mlpack/files/13499069/mlpack_x86.log)

**Comment by rcurtin** [comment]
Do you need to link against 32-bit OpenBLAS instead?  I wonder if that is the issue here.  (I am not a Windows user and I am not experienced with MSVC, so I am only guessing.)
