### ISSUE TITLE
Multihead attention layer

### ISSUE THREAD

**Issue by AntoineDubois** [mlpack/mlpack#3573]
The description of the class **MultiheadAttentionType** explains that: 
"The attnMask and keyPaddingMask arguments are defined as a mask where 1 passes values and 0 masks them, unlike the original
paper which uses 0 to pass values and -inf to mask them."
However, in the test file **multihead_attention.cpp**, **attnMask** and **keyPaddingMask** are defined with 0 and -inf like below:
```
arma::mat attnMask = arma::zeros(tLen, sLen);
for (size_t i = 0; i < tLen; ++i)
{
  for (size_t j = 0; j < sLen; ++j)
  {
    if (i < j)
      attnMask(i, j) = std::numeric_limits<double>::lowest();
  }
}

arma::mat keyPaddingMask = arma::zeros(1, sLen);
keyPaddingMask(sLen - 1) = std::numeric_limits<double>::lowest();
```

How to properly define the attention and key padding masks?

**Comment by rcurtin** [comment]
Thanks for the report---I opened #3575 to fix the documentation.  0/-inf is what should be used, like you pointed out. :+1:
