### ISSUE TITLE
How to configure mlpack test case

### ISSUE THREAD

**Issue by shirishkumar23** [mlpack/mlpack#3581]
I am trying to build on Google Collab. It is taking a lot of time to build.Is there anyway to configure for only one test case?

**Comment by rcurtin** [comment]
The easiest way to do this is to change `src/mlpack/tests/CMakeLists.txt` and comment out the tests you aren't interested in building.  There's no way to specifically request to CMake that you only want to build one of the test files.  Also, mlpack does in general just take a long time to build the tests... there are a lot of them :)
