### ISSUE TITLE
in ver 4.3.0 I can`t import linear_svm

### ISSUE THREAD

**Issue by SccotMu** [mlpack/mlpack#3586]
after pip install mlpak. i want to import it, but failed. i found than in __init_.py file, there is no right way to import. here is the part of the code .
[__init__.py]
...
from .hmm_viterbi import hmm_viterbi
from .hoeffding_tree import hoeffding_tree
from .kde import kde
from .kernel_pca import kernel_pca
from .kmeans import kmeans
from .lars import lars
from .linear_svm import linear_svm
from .lmnn import lmnn
....

**Comment by rcurtin** [comment]
Can you provide more information on what you tried to do?  This is not enough for me to help debug your problem.

If you wanted to import `linear_svm()`, you would use `from mlpack import linear_svm`.

**Comment by SccotMu** [comment]
Thanks for your rely;
Here is screenshot of my code. And the error showed on the consol.
![15068](https://github.com/mlpack/mlpack/assets/52561068/29114c3f-c02d-4c61-a103-68975765e626)

**Comment by rcurtin** [comment]
The error says `Must pass either 'training' or 'input_model' or both!`.  Did you try consulting the `linear_svm()` documentation and ensure you were calling the function with correct arguments?

**Comment by SccotMu** [comment]
Thanks, I found the python_documentation, and now run normally.

**Comment by SccotMu** [comment]
Facing other question:
After reading the doc, I want to use trained model to predict one of embeddings as the formats in doc, but has error occured on line 84 :
[FATAL] Test data dimensionality (1) must be the same as the dimensionality of the training data (512)! 
What should i coding.Thanks!

![image](https://github.com/mlpack/mlpack/assets/52561068/aa0f8bfe-94f4-4e3a-b4e7-39ca6e822e80)
