### ISSUE TITLE
make install taking a lot of time in arm low end processor (1.5 GHz clock cycle)

### ISSUE THREAD

**Issue by Adarsh97** [mlpack/mlpack#3592]
Hi, 
I am installing mlpack in one of the systems with arm processor having clock cycle of 1.5 GHz, 2 Gb RAM, when i am doing make install , it is taking a lot of time, even with 6 hours it is not completed. Is this behaviour expected with the system ? 
The os version is ubuntu 22.04
mlpack version 4.3.2

**Comment by rcurtin** [comment]
mlpack's tests do indeed take a lot of time to build.  You don't have to build the tests if you just want to use mlpack (if you run `cmake` without specifying any options, the tests will not be built).

**Comment by Adarsh97** [comment]
I understood, I am now making only the required folders. So it is working fine. Thanks for your quick reply. I am closing the discussion.
