### ISSUE TITLE
error in loading csv file 

### ISSUE THREAD

**Issue by kumar-utkarsh0317** [mlpack/mlpack#3597]
my code is ::
`    bool load_status = data::load(arma::csv_name(argv[1], headers, arma::csv_opts::trans));
`

and i am getting the error like 
error: ‘csv_name’ is not a member of ‘arma’

csv_name is clearly mentioned in the armadillo documentation then why i am getting this error

**Comment by conradsnicta** [comment]
A few points:
* your version of Armadillo is probably outdated; `csv_name()` requires at least Armadillo 9.900; see [changelog](https://arma.sourceforge.net/docs.html#changelog)
* `mlpack::data::load()` and `arma::csv_name()` don't mix; the latter is only for the [`.load()`](https://arma.sourceforge.net/docs.html#save_load_mat) function from Armadillo

**Comment by kumar-utkarsh0317** [comment]
Hi,
Can I ask some more of my doubts here?
