### ISSUE TITLE
More support for tree-based regressors

### ISSUE THREAD

**Issue by smartmic** [mlpack/mlpack#3598]
Are there any plans to add more support for tree-based regression algorithms?
There is a `DecisionTreeRegressor`, but unfortunately not for `AdaBoost` or `RandomForest`. 
I have used these for regression tasks in Scikit-Learn, and they have worked well for certain tasks.
It would be great if I could switch to mlpack here as well.

I have no idea what the effort would be, but I wonder: aren't the corresponding classifiers already half the rent?
A tangential discussion has been started in https://github.com/mlpack/mlpack/issues/3015#issue-945435019

**Comment by rcurtin** [comment]
It would be nice to add both of those, but it's not completely trivial.  For `RandomForest` I think you can pretty much adapt the existing code and implement a `Predict()` function; for `AdaBoost`, I think there may be some algorithmic things that need to change a little (but I don't remember the details).  Anyway, if you or someone wanted to take the time to do it, I think it would be a nice contribution.  Ideally we can reuse some of the code from `RandomForest` or `AdaBoost`, but, my memory is that there were some irritating details that meant that wasn't easy for `DecisionTreeRegressor` and `DecisionTree`.

**Comment by Hetan07** [comment]
Hi! Could this be implementable by someone as a first issue who knows the algorithms working but have never worked and implemented them using code?

**Comment by shaojunjie0912** [comment]
waiting for it too....

**Comment by arthiondaena** [comment]
Hey @rcurtin, can I implement RandomForestRegressor and AdaBoostRegressor? Randomforest is pretty simple, and for AdaBoost there will some work to do.

**Comment by shapy051002** [comment]
Hey, is the AdaBoost merge completed already?
I wanted to apply for GSOC in this organisation and hence wanted to help with this issue, which is why im asking. 
Is this issue completed ?
