### ISSUE TITLE
Packit Integration

### ISSUE THREAD

**Issue by bkmgit** [mlpack/mlpack#3599]
### What is the desired addition or change?

Automate release generation with Packit

### What is the motivation for this feature?
Easier testing and maintenance

### If applicable, describe how this feature would be implemented.
Can do this in the downstream [Fedora repository](https://src.fedoraproject.org/rpms/mlpack), however doing this upstream can enable easier viewing of build test results for proposed additions to the code base.

Documentation is available at:
https://packit.dev/docs/fedora-releases-guide

**Comment by rcurtin** [comment]
Nice, I hadn't heard of Packit.  I think it would be better to do this downstream in the Fedora repository though, since it's Fedora/RHEL-specific. :+1:
