### ISSUE TITLE
Can not find  <execinfo.h>

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#360]
**Reported by lchenat on 18 Nov 44981965 12:44 UTC**
After running cmake ../ I run the make command and here is the process:

$ make
Scanning dependencies of target mlpack_headers
Moving header files to include/mlpack/
[  0%] Built target mlpack_headers
Scanning dependencies of target mlpack
[  0%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/discrete_distribution.cpp.o
[  1%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/gaussian_distribution.cpp.o
[  2%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/laplace_distribution.cpp.o
[  3%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/kernels/epanechnikov_kernel.cpp.o
[  4%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/kernels/pspectrum_string_kernel.cpp.o
[  5%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/lin_alg.cpp.o
[  6%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/random.cpp.o
[  6%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/optimizers/aug_lagrangian/aug_lagrangian_test_functions.cpp.o
[  7%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/optimizers/lbfgs/test_functions.cpp.o
[  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/optimizers/lrsdp/lrsdp.cpp.o
[  9%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/optimizers/lrsdp/lrsdp_function.cpp.o
[ 10%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/optimizers/sgd/test_function.cpp.o
[ 11%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/tree/cosine_tree/cosine_tree.cpp.o
[ 12%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/tree/mrkd_statistic.cpp.o
[ 12%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/cli.cpp.o
[ 13%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/cli_deleter.cpp.o
[ 14%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/log.cpp.o
/home/Administrator/mlpack-1.0.11/mlpack-1.0.11/src/mlpack/core/util/log.cpp:24:24: execinfo.hNo such file or directory
   #include <execinfo.h>
                        ^

src/mlpack/CMakeFiles/mlpack.dir/build.make:425: recipe for target 'src/mlpack/CMakeFiles/mlpack.dir/core/util/log.cpp.o' failed
make[*** [src/mlpack/CMakeFiles/mlpack.dir/core/util/log.cpp.o](2]:) Error 1
CMakeFiles/Makefile2:119: recipe for target 'src/mlpack/CMakeFiles/mlpack.dir/all' failed
make[*** [src/mlpack/CMakeFiles/mlpack.dir/all](1]:) Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

I have installed armadillo and I don't know how to deal with this problem.

Migrated-From: http://trac.research.cc.gatech.edu/fastlab/ticket/379

**Comment by rcurtin** [comment]
I'll try to reproduce this with Cygwin if I get a chance.  If this can be reproduced then the fix should be as straightforward as changing the logic a bit, so that if gnulib is being used on some platform where execinfo.h doesn't exist, then Log::Assert() doesn't print a backtrace at all.

**Comment by Kirizaki** [comment]
I think this issue is resolved and should be closed, because ```Log::Assert()``` doesn't use ```execinfo.h``` anymore. It's replaced by:
```
#ifdef HAS_BFD_DL
  #include "backtrace.hpp"
#endif
```
Check it in: <a href="https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/util/log.cpp#L10">log.cpp</a>.

**Comment by rcurtin** [comment]
You're right, we can now close this. :)
