### ISSUE TITLE
Negative loss in vae

### ISSUE THREAD

**Issue by Adarsh97** [mlpack/mlpack#3601]
Observation is I am seeing negative loss value while training as well as during evaluate function.
This is happening when our input is not in 0 to 1 range.
The model I am using is VAE. 
Is this expected?

**Comment by shrit** [comment]
please if you can share the output of the training, including the source code if you can

**Comment by Adarsh97** [comment]
I am using exactly this code https://github.com/mlpack/models/tree/master/vae/vae_mnist
Do we really need to keep our input in the [0,1] range ?
the mlpack version  i am using is 3.4.2.
The evaluate function is also returning negative loss values.
since the latest version 4 and above didn't have updated reparametrization layer, i can't use them

**Comment by Adarsh97** [comment]
Do i need to make any modification for the above code to work with negative numbers also ?
