### ISSUE TITLE
[Question] Can mlpack's random forest library complete the function of missing values filling?

### ISSUE THREAD

**Issue by shaojunjie0912** [mlpack/mlpack#3611]
Hi, I'm new to mlpack.

Recently I've been trying to implement missing values padding in a random forest way

Can mlpack's random forest library complete the function of missing value implementation?

Thanks a lot!

**Comment by shaojunjie0912** [comment]
Just like missForest.

**Comment by rcurtin** [comment]
mlpack doesn't have support like missForest, but there is an imputer for missing values:
https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/data/imputer.hpp

**Comment by shaojunjie0912** [comment]
Thanks, I will have a try.
