### ISSUE TITLE
Custom distance function

### ISSUE THREAD

**Issue by adokhugi** [mlpack/mlpack#3612]
I tried running DBSCAN with a custom distance function (that has been created by ChatGPT). I called DBSCAN with these parameters:

		DBSCAN<RangeSearch<
			CustomDistance,
			arma::mat,
			FloatKDTree>,
			OrderedPointSelection> dbscan(epsilon, minPoints, true);

In the end I got this error message:

static_assert failed: 'HRectBound can only be used with the LMetric<> metric type.'

I suspect that I should call DBSCAN with other parameters, but which?

**Comment by adokhugi** [comment]
I think I've found the culprit: it is not possible to use the metric with FloatKDTree. With StandardCoverTree however it should work.

**Comment by rcurtin** [comment]
Exactly: any binary space tree (of which KDTree is one) requires `LMetric` to be used.  `StandardCoverTree` will work, and I think `RTree`, `RStarTree`, and other R-tree variants will work too. :+1:
