### ISSUE TITLE
Build failing for no apparent reason (Visual Studio/C++ 17/Windows 11)

### ISSUE THREAD

**Issue by frisby-ninja** [mlpack/mlpack#3628]
I've just installed mlpack using the vcpkg tool, and it all went fine.

Now, I'm trying to use it (without CMake, just with normal 'C++ additional include directories' in Visual Studio - although I did use CMake originally with virtually the same result :/).

I've added all these directories to the include list:

C:\vcpkg-2024.01.12\packages\openblas_x64-windows\include
C:\vcpkg-2024.01.12\packages\cereal_x64-windows\include
C:\vcpkg-2024.01.12\packages\ensmallen_x64-windows\include
C:\vcpkg-2024.01.12\packages\armadillo_x64-windows\include
C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include

But I get this output log when running it: (Warnings are omitted so I  can upload without reaching char limit...)

```
1>------ Build started: Project: Empathy, Configuration: Debug x64 ------
1>Main.cpp
1>(compiling source file 'Main.cpp')
1>C:\vcpkg-2024.01.12\packages\ensmallen_x64-windows\include\ensmallen_bits\problems\aug_lagrangian_test_functions_impl.hpp(266,19): error C2665: 'abs': no overloaded function could convert all the argument types
1>(compiling source file 'Main.cpp')
1>C:\vcpkg-2024.01.12\packages\ensmallen_x64-windows\include\ensmallen_bits\problems\aug_lagrangian_test_functions_impl.hpp(275,15): error C2665: 'abs': no overloaded function could convert all the argument types
1>(compiling source file 'Main.cpp')
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\bayesian_linear_regression\bayesian_linear_regression_impl.hpp(72,19): error C2440: '=': cannot convert from 'const arma::eOp<arma::vec,arma::eop_scalar_div_pre>' to 'double'
1>(compiling source file 'Main.cpp')
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\bayesian_linear_regression\bayesian_linear_regression_impl.hpp(72,19):
1>No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\bayesian_linear_regression\bayesian_linear_regression_impl.hpp(76,34): error C2440: '=': cannot convert from 'const arma::eOp<T,arma::eop_scalar_div_pre>' to 'double'
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\bayesian_linear_regression\bayesian_linear_regression_impl.hpp(76,34): error C2440:         with
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\bayesian_linear_regression\bayesian_linear_regression_impl.hpp(76,34): error C2440:         [
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\bayesian_linear_regression\bayesian_linear_regression_impl.hpp(76,34): error C2440:             T=arma::rowvec
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\bayesian_linear_regression\bayesian_linear_regression_impl.hpp(76,34): error C2440:         ]
1>(compiling source file 'Main.cpp')
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\bayesian_linear_regression\bayesian_linear_regression_impl.hpp(76,34):
1>No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>(compiling source file 'Main.cpp')
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\lars\lars_impl.hpp(449,29): error C2440: '=': cannot convert from 'const arma::eOp<arma::eOp<arma::vec,arma::eop_sqrt>,arma::eop_scalar_div_pre>' to 'double'
1>(compiling source file 'Main.cpp')
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\lars\lars_impl.hpp(449,29):
1>No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\lars\lars_impl.hpp(470,29): error C2440: '=': cannot convert from 'const arma::eOp<arma::eOp<arma::vec,arma::eop_sqrt>,arma::eop_scalar_div_pre>' to 'double'
1>(compiling source file 'Main.cpp')
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\lars\lars_impl.hpp(470,29):
1>No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\lars\lars_impl.hpp(739,37): error C2440: '=': cannot convert from 'const arma::eOp<arma::eOp<arma::vec,arma::eop_scalar_plus>,arma::eop_sqrt>' to 'eT'
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\lars\lars_impl.hpp(739,37): error C2440:         with
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\lars\lars_impl.hpp(739,37): error C2440:         [
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\lars\lars_impl.hpp(739,37): error C2440:             eT=double
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\lars\lars_impl.hpp(739,37): error C2440:         ]
1>(compiling source file 'Main.cpp')
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\lars\lars_impl.hpp(739,37):
1>No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>(compiling source file 'Main.cpp')
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\sparse_coding\sparse_coding_impl.hpp(195,31): error C2440: 'initializing': cannot convert from 'const arma::eOp<arma::vec,arma::eop_scalar_times>' to 'double'
1>(compiling source file 'Main.cpp')
1>C:\vcpkg-2024.01.12\packages\mlpack_x64-windows\include\mlpack\methods\sparse_coding\sparse_coding_impl.hpp(195,31):
1>No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>(compiling source file 'Main.cpp')
1>(compiling source file 'Main.cpp')
1>Done building project "Empathy.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 17:13 and took 07.667 seconds ==========
```

This doesn't appear to be happening to anyone else, and I am completely stumped. :(
Thanks in advance!

**Comment by rcurtin** [comment]
Technically there is an apparent reason, it's all the errors that you have :smile: :smile: now, why those errors are happening is a different story...

Can you tell us what version of mlpack you're using, and what's in `Main.cpp`?

**Comment by frisby-ninja** [comment]
I'm afraid I only installed mlpack; not the command line tool. 
I followed https://github.com/mlpack/mlpack/blob/4.3.0/doc/user/build_windows.md so whatever that version is (I'm assuming latest) is the one I've got. (I don't know how to check the version apart from the windows command line...)

My Main.cpp doesn't contain anything related to mlpack. Instead, it links to Network.h, which contains (for now) an example I found somewhere (perhaps on this repo)
I'll share that code: (Network.h's mlModel method is linked to in a method named text_enter_callback)
#pragma once

#include <mlpack/mlpack.hpp>
#include <mlpack/methods/neighbor_search/neighbor_search.hpp>
#include <iostream>

using namespace std;
using namespace mlpack;
// NeighborSearch and NearestNeighborSort 
using namespace mlpack::neighbor;
// ManhattanDistance 
using namespace mlpack::metric;

void mlModel()
{
    // Armadillo is a C++ linear algebra library;  
    // mlpack uses its matrix data type. 
    arma::mat data;

    /*
    data::Load is used to import data to the mlpack,
    It takes 3 parameters,
        1. Filename = Name of the File to be used
        2. Matrix = Matrix to hold the Data in the File
        3. fatal = true if you want it to throw an exception
         if there is an issue
    */
    data::Load("data.csv", data, true);

    /*
    Create a NeighborSearch model. The parameters of the
    model are specified with templates:
        1. Sorting method: "NearestNeighborSort" - This
        class sorts by increasing distance.
        2. Distance metric: "ManhattanDistance" - The
        L1 distance, the sum of absolute distances.
        3. Pass the reference dataset (the vectors to
        be searched through) to the constructor.
     */
    NeighborSearch<NearestNeighborSort, ManhattanDistance> nn(data);
    // in the above line we trained our model or  
    // fitted the data to the model 
    // now we will predict 

    arma::Mat<size_t> neighbors; // Matrices to hold 
    arma::mat distances; // the results 

    /*
    Find the nearest neighbors. Arguments are:-
        1. k = 1, Specify the number of neighbors to find
        2. Matrices to hold the result, in this case,
        neighbors and distances
    */
    nn.Search(1, neighbors, distances);
    // in the above line we find the nearest neighbor 

    // Print out each neighbor and its distance. 
    for (size_t i = 0; i < neighbors.n_elem; ++i)
    {
        std::cout << "Nearest neighbor of point " << i << " is point "
            << neighbors[i] << " and the distance is "
            << distances[i] << ".\n";
    }
}

class Network {
public:
	

private:

};

**Comment by rcurtin** [comment]
Thanks for the update.  Is it possible there is a `dot()` function defined somewhere in the header files you are including?  What happens if you replace Main.cpp's code with the following?

```
#include <armadillo>

int main()
{
  arma::vec x(100, arma::fill::randu);

  double d = dot(x, x);

  std::cout << "d: " << d << std::endl;
}
```

Does that compile successfully?

**Comment by frisby-ninja** [comment]
Right off the bat, Visual Studio tells me: 
'no suitable conversion function from "arma::vec" to "double" exists'...

**Comment by rcurtin** [comment]
What if you change the code to this:

```
#include <iostream>

int main()
{
  double d = 5.0;
  double dd = dot(d, d);

  std::cout << dd << std::endl;
}
```

**Comment by frisby-ninja** [comment]
Compiles fine, and outputs '25'.

**Comment by rcurtin** [comment]
Where is `dot()` defined?  That's the mystery here.  If you can figure out what is defining `dot()` and undefine it, I think your mlpack code should compile fine.  Check the header files you're including or any other files.  (You might be able to get Visual Studio to point you to the definition of `dot()` too.)

**Comment by shrit** [comment]
these are linker errors for OpenBLAS

**Comment by shrit** [comment]
you need to link armadillo to OpenBLAS, it is a dependency, and since you are on Windows, I have no idea how this is done

**Comment by frisby-ninja** [comment]
Ah.
I may have to edit the arma code then.

**Comment by shrit** [comment]
you need to link against it. Also since I see there is a wrapper then you might be able to link against armadillo directly

Also, NO, DO NOT touch libraries code unless you know what are you doing

**Comment by frisby-ninja** [comment]
Right.
How exactly can I do that? I'm afraid I'm relatively new to C++ and the full Visual Studio experience...

**Comment by shrit** [comment]
google it, or YouTube it,  I have no idea because I never use Windows, since it is not something that you DO NOT want to use if you want to learn programming and computer science

**Comment by frisby-ninja** [comment]
Yes, I've found that out the hard way.
Thanks for the help!

**Comment by shrit** [comment]
The above problem should be fixed when this #3629 get merged, which is going to happen in a couple of hours

**Comment by frisby-ninja** [comment]
So I'll close this as completed, thanks again!

**Comment by frisby-ninja** [comment]
Actually, I'll just add this for the people who have this same issue:
The fix was to edit config.hpp as instructed here: https://gist.github.com/BERENZ/ff274ebbf00ee111c708
Then, as I'm on Visual Studio, I added the {OPENBLAS_DIR}/lib folder to Linker/General/Additional Library directories
After that, I added 'openblas.lib' to Linker/Input/Additional Dependencies
Finally, I copied the files under {OPENBLAS_DIR}/bin to the same folder as the output executable.
It now works!

**Comment by rcurtin** [comment]
Glad you got it working @frisby-ninja! :+1:
