### ISSUE TITLE
Build server on windows configuration

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#363]
**Reported by birm on 14 Mar 2014 12:45 UTC**
For anyone not following the nightly builds, the windows build server no longer seems to hang up on arma_traits, but now on cmake.

`C:\Jenkins\workspace\mlpack - windows\Compiler\VS2011\arch\win-i386\build>cmake -G "Visual Studio 11" -DCMAKE_INSTALL_PREFIX="$WORKSPACE\install" -DCMAKE_BUILD_TYPE=Debug -DARMADILLO_INCLUDE_DIR="C:\lib\armadillo-3.800.2\include\ " -DARMADILLO_LIBRARY="C:\lib\armadillo-3.800.2\Debug\armadillo.lib " -DICONV_HEADER="C:\lib\iconv-1.9.2.win32\include\iconv.h " -DICONV_LIBRARY="C:\lib\iconv-1.9.2.win32\lib\iconv.lib " -DLIBXML2_INCLUDE_DIR="C:\lib\libxml2-2.7.8.win32/include/ " -DLIBXML2_LIBRARIES="C:\lib\libxml2-2.7.8.win32\lib\libxml2.lib " -DZLIB_LIBRARY="C:\lib\zlib-1.2.5\lib\zlib.lib " -DBOOST_ROOT="C:\lib\boost\boost_1_53_0\ " -DLAPACK_LIBRARY="C:\lib\armadillo-3.800.2\examples\lib_win32\lapack_win32_MT.lib " -DBLAS_LIBRARY="C:\lib\armadillo-3.800.2\examples\lib_win32\blas_win32_MT.lib " "../repo" `
gives
`'cmake' is not recognized as an internal or external command,
operable program or batch file.`
Check out
 http://big.cc.gt.atl.ga.us:8080/job/mlpack%20-%20windows/Compiler=VS2011,arch=win-i386/211/console
for the full list of seemingly simple errors.
Maybe I (or someone else if they want to) could find out the source of these errors, and fix them.

**Comment by thirdwing** [comment]
Please see [this](https://gist.github.com/thirdwing/e3e0cd0843e7945e9013).

This is the configuration on my Windows machine. All the static libraries we need are compiled by myself using MinGW64, and you can download them using the links.

**Comment by rcurtin** [comment]
I think this is no longer an issue because AppVeyor is working.
