### ISSUE TITLE
Build OSX installer file

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#364]
**Reported by speet3 on 4 Aug 2011**
I know I need to do much more research into how this is done. I continue to hear that the environment is BSD-like, but I really don't know what it means to build a mac installation binary, yet. It should be published same as the tarball and windows installer.

**Comment by theaverageguy** [comment]
@rcurtin Any heads up for this? Guide me a bit please. :)

**Comment by rcurtin** [comment]
You'll have to do research on this one, like speet3 mentioned years ago.  Figure out how mlpack might be distributed on OS X, then create a solution.  There's not much guidance I can give you here; it's open-ended.

**Comment by darcyliu** [comment]
HI @rcurtin , I am working on this issue recently.
OSX Installer package (.pkg) can be created by pkgbuild / productbuild commands. Currently, We can write scripts to generate these packages. Later we can use these scripts in OS X build slaves. Is that suitable?

If so, what is the minimum supported OSX version? How about starting from the latest version OSX 10.11? Do we need create 32bit architecture package or just focus on 64bit?

It seems the Jenkins build servers ( http://knife.lugatgt.org:8088/ and http://big.cc.gt.atl.ga.us) are offline, 
or they are intranet services only?

**Comment by rcurtin** [comment]
The link for the build server is incorrect, it has been moved (for a number of administrative reasons) to http://big.mlpack.org:7780/ .  If you found some misleading documentation let me know and I can fix it.

Starting at the latest version of OS X (El Capitan) is fine with me, but I think ideally we should provide 64 and 32 bit packages for older versions too.  I don't know how far back we should aim for, but I would imagine once we get the package building on El Capitan, it'll be easy to port to older versions.

Another important thought is whether or not a .pkg is really the right way to go here; instead, would it be more appropriate to just make sure mlpack is packaged in Homebrew and MacPorts?  Let me know what you think.  If the packages are easy to build, it's certainly no issue to just have Jenkins build them periodically and make them available for anyone who wants them.
