### ISSUE TITLE
No module named 'mlpack.image_converter' during import in python at Mac.

### ISSUE THREAD

**Issue by eptitsyn** [mlpack/mlpack#3641]
#### Issue description

No module named 'mlpack.image_converter' during import in python at Mac computer.

#### Your environment

 * version of mlpack:  4.3.0.post1 Tag: cp310-cp310-macosx_11_0_arm64
 * operating system: Macos Sonoma 14.2.1 (23C71)
 * compiler: Python 3.10.13

#### Steps to reproduce

install mlpack with 'pip install mlpack'

import mlpack

#### Expected behavior

successful import

#### Actual behavior

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[59], line 1
----> 1 import mlpack

File ~/projects/page_rotation/.venv/lib/python3.10/site-packages/mlpack/__init__.py:63
     61 from .linear_regression_predict import linear_regression_predict
     62 from .linear_regression import *
---> 63 from .image_converter import image_converter
     64 __version__='4.3.0'

ModuleNotFoundError: No module named 'mlpack.image_converter'`

**Comment by Aditya-dom** [comment]
> Just make sure folder also contains an init.py, this allows it to be included as a package. 
> Not sure why the other answers talk about PYTHONPATH.

**Comment by rcurtin** [comment]
That answer is not correct.  I believe that the mlpack package posted on PyPI had a build error where STB was not found and resultantly the image converter functionality was not included, but I think this is only true for the macOS builds.  I wanted to look into this and post with a solution and say "the package is updated!" but I have not had a chance yet.

**Comment by 5advaith** [comment]
i am facing the same issue , i installed mlpack using pip in my m1 macbook air . 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[6], [line 16](vscode-notebook-cell:?execution_count=6&line=16)
     [13](vscode-notebook-cell:?execution_count=6&line=13) get_ipython().run_line_magic('matplotlib', 'inline')
     [15](vscode-notebook-cell:?execution_count=6&line=15) # For KDE and regression models.
---> [16](vscode-notebook-cell:?execution_count=6&line=16) import mlpack
     [18](vscode-notebook-cell:?execution_count=6&line=18) # For cross validation.
     [19](vscode-notebook-cell:?execution_count=6&line=19) from sklearn.model_selection import KFold 

ModuleNotFoundError: No module named 'mlpack.image_converter'

**Comment by conradsnicta** [comment]
addressed in #3660

**Comment by rcurtin** [comment]
There was still just one more thing to do, which was backport that fix to PyPI and get a new version uploaded.  I've been working on this, and I'm just about there, but the mlpack-wheels builds take forever so it's been a slow iteration process to ensure `image_converter` gets built correctly, etc...  Hopefully this should be done within a week, most of the time is just waiting.

**Comment by rcurtin** [comment]
I released mlpack 4.3.0.post2 to PyPI (it took a long time to rebuild all the wheels!) and these should all have `image_converter` included now.  Thanks for the report @eptitsyn!
