### ISSUE TITLE
Build windows installer package

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#365]
**Reported by speet3 on 8 Aug 2011**
Either NSIS or MSI, NSIS has a nice linux compiler, and MSI is the Microsoft supported installer format. In either case, the result needs to be published, probably in a similar location to the source tarball.

**Comment by thirdwing** [comment]
Do you have the requirement for MSI or exe format? Maybe I can give a try this weekend.

**Comment by rcurtin** [comment]
On Thu, Jan 08, 2015 at 03:40:46PM -0800, Qiang Kou (KK) wrote:
> Do you have the requirement for MSI or exe format? Maybe I can give a try this weekend.

Doesn't matter to me.  The goal would just be a Windows installer of
some sort that installs the mlpack executables (allknn, emst, etc.) and
the headers to somewhere on the system.  This will help a lot of people
who want to use mlpack on Windows.  Let me know if I can help out or
throw any hardware at it or something. :)

-- 
Ryan Curtin    | "Where we're going, we won't need eyes to see."
ryan@ratml.org |   - Dr. Weir

**Comment by thirdwing** [comment]
OK. I will try this or next weekend. I have used Inno setup to package software several times before. There shouldn't be much problem.

**Comment by II-Matto** [comment]
I was wondering if there are windows installers now?

**Comment by thirdwing** [comment]
You can find an old version from https://dl.dropboxusercontent.com/u/81699687/mlpack-setup-x86_64-1_0_12.exe

**Comment by II-Matto** [comment]
Many thanks! I just installed it, and found there is only *.a file. I guess this is compiled with mingw and cannot be used in visual studio?

**Comment by thirdwing** [comment]
Yes. This is compiled using MinGW-w64.

If you want to use it with VS, you probably need to compile it by yourself.

On Wed, Sep 2, 2015 at 10:44 AM, II-Matto <notifications@github.com> wrote:

> Many thanks! I just installed it, and found there is only *.a file. I
> guess this is compiled with mingw and cannot be used in visual studio?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mlpack/mlpack/issues/365#issuecomment-137108232>.
>



-- 
Qiang Kou
qkou@umail.iu.edu
School of Informatics and Computing, Indiana University

**Comment by II-Matto** [comment]
@thirdwing I just found the *.lib files which possibly can be used in visual studio. though they target only x86 platform. I will try to compile a x86 version with visual studio 2013.

**Comment by thirdwing** [comment]
Good luck! If you can compile and it works, you should share the project file and write down how to do it.

**Comment by II-Matto** [comment]
@thirdwing I have successfully build mlpack for x86 platform with Visual Studio 2013 and Intel C++ 15.0. I am preparing an article for it, and I will try to finish it within next week.

**Comment by II-Matto** [comment]
@thirdwing Somehow I made it to build mlpack for x64 platform with Visual Studio 2012 and Intel C++ 15.0. I will try to share the process and relevant files later. Too much work to do recently.

**Comment by rcurtin** [comment]
Finally closed after over seven years!  Now that is a nice feeling.  Thanks @gmanlan!
