### ISSUE TITLE
[R] - `verbose` argument has no effect

### ISSUE THREAD

**Issue by cgiachalis** [mlpack/mlpack#3675]
#### Issue description

It seems that the `verbose` argument has no effect.

``` r
set.seed(1234)
x <- matrix(rnorm(10*5), ncol = 5)

# KNN EXAMPLE
res <- mlpack::knn(query = x, reference = x, k = 3, verbose = TRUE)

# expected :

[INFO ] 11 node combinations were scored.
[INFO ] 100 base cases were calculated.


# MST EXAMPLE
res3 <- mlpack::emst(x, verbose = TRUE)

# expected :

[INFO ] 6 edges found so far.
[INFO ] 90 cumulative base cases.
[INFO ] 1 cumulative node combinations scored.
[INFO ] 9 edges found so far.
[INFO ] 164 cumulative base cases.
[INFO ] 2 cumulative node combinations scored.
[INFO ] Total spanning tree length: 14.9797

packageVersion("mlpack")
[1] ‘4.3.0.1’

```

`verbose` argument doesn't assign its value in the list of parameters that is passed on to the binding algorithm; instead it invokes an R internal function, `EnableVerbose()` or `DisableVerbose()` which wraps the C++ helper EnableVerbose/DisableVerbose and these C++ helpers then simply call `Log::Info.ignoreInput = false or true`;

So, `Log::Info.ignoreInput` is invoked not within the binding function and as a result has no effect (at least this is my understanding).

cc: @coatless

**Comment by rcurtin** [comment]
Thanks for the report @cgiachalis!  I dug into the issue, and it turns out that the reason it doesn't work is that there is one `Log::Info` in each translation unit (i.e. each .cpp file that gets compiled), and so basically the `EnableVerbose()` function modifies the wrong one.  I opened a fix in #3691.
