### ISSUE TITLE
Get rid of `arma::fill::zeros` when we upgrade the minimum armadillo version

### ISSUE THREAD

**Issue by shrit** [mlpack/mlpack#3681]
Hi, 

This issue is only a placeholder for the above task, that we will probably do when we move to C++17 sometime this summer.

**Comment by rcurtin** [comment]
Agreed, the only thing is we need to look and see when we can use `fill::none`---there are some cases where it is fine to leave the memory uninitialized, as we then set it immediately.  That can save a little bit of computation time.

**Comment by conradsnicta** [comment]
I recommend upgrading the minimum version of Armadillo to 10.8 as soon as Ubuntu 24.04 LTS comes out, scheduled for end of this month.  This would cover the two most recent Ubuntu LTS releases.

* Ubuntu 24.04 LTS has Armadillo 12.6.7
* Ubuntu 22.04 LTS has Armadillo 10.8.2
* Debian 12 has Armadillo 11.4.2
* Debian 13 (testing) has Armadillo 12.6.7
* RHEL EPEL 7 has Armadillo 10.8.2  (note: RHEL 7 is EOL in mid 2024)
* RHEL EPEL 8 & 9 has Armadillo 12.6.6 (subject to future upgrades)

**Comment by rcurtin** [comment]
Agreed, at that time it is also worth checking through the codebase for any ancient Armadillo compatibility code (sometimes it gets missed).

**Comment by shrit** [comment]
@conradsnicta we are scheduled to move to C++17 this summer, probably in June of July, at that time, we can take care of this as well.

**Comment by conradsnicta** [comment]
Related PR for bumping the minimum Armadillo version: #3760

**Comment by shrit** [comment]
This is done, waiting on the PR #3687 to be merged
