### ISSUE TITLE
[R] - Global option for 'verbose' argument

### ISSUE THREAD

**Issue by cgiachalis** [mlpack/mlpack#3692]
### What is the desired addition or change?

All algorithms have a `verbose` argument to display informational messages.  We need a way to enable/disable it at a global level (package); applied in all functions that have `verbose` argument.

### What is the motivation for this feature?
Efficiency

### If applicable, describe how this feature would be implemented.

We need to query a list of options for mlpack and return the desired option otherwise default to `FALSE`. 
In `R`  that's easy implementation:
```r
mlpack::knn(.,.,..., verbose = getOption("mlpack.verbose", FALSE) )
```
Now, if the user wants `verbose = TRUE` for all functions, then it's done in one line: `options(mlpack.verbose = TRUE)`

### Additional information?

A user case follows:

``` r
set.seed(1234)
x <- matrix(rnorm(10*5), ncol = 5)

# without global option for 'verbose' argument
foo <- function(x) {
list(knn3 = mlpack::knn(query = x, reference = x, k = 3, verbose = FALSE),
      knn10 = mlpack::knn(query = x, reference = x, k = 10, verbose = TRUE),
      mst = mlpack::emst(x, verbose = TRUE))
}

res <- foo(x)

# With  global option

options(mlpack.verbose = TRUE)

foo <- function(x) {
list(knn3 = mlpack::knn(query = x, reference = x, k = 3, verbose = FALSE), # no need  for information for kkn3
      knn10 = mlpack::knn(query = x, reference = x, k = 10),
      mst = mlpack::emst(x))
}
res <- foo(x)

```
ref https://github.com/mlpack/mlpack/pull/3691

**Comment by cgiachalis** [comment]
Yes ->  replacement of the logical value `FALSE` with `getOption("mlpack.verbose", FALSE)`.  That's it.

> what needs to happen to the R package to add something like that?

You're already told R what to do with `getOption("mlpack.verbose", FALSE)` . The `getOption` searches for `mlpack.verbose`  and if finds nothing then it  will return the default  value `FALSE`.   

By using the R function  `options()`  we change what  `getOption("mlpack.verbose", FALSE)` returns, e.g. `options(mlpack.verbose = TRUE)` then `getOption("mlpack.verbose", FALSE)`  returns `TRUE` unless you set directly `FALSE` as I did in the example above.

> I assume we need to specify that mlpack.verbose exists somewhere and also that its default value is FALSE

This is optional and yes you can do that by setting the default option when the package is loaded using somewhere:

```r

.onLoad <- function(libname, pkgname) {

  opt <- getOption("mlpack.verbose")

  if (is.null(opt)) {
    options(mlpack.verbose = TRUE)
  }

  invisible()
}
```
Normally, we add the above in a  `zzz.R.` file. 

cc @coatless , @eddelbuettel

**Comment by eddelbuettel** [comment]
@cgiachalis is correct.  While it is a global and flat namespace (eeek) a common pattern is to protect the actual value with a poor-man's namespace.  Hence 'mlpack.verbose' and not 'verbose'.  A sleeker but more involved way is stick per-package options into per-package environment ... but that is overkill, and our marginal cost to marginal changes ratio is too high.

So I am in favor of just using `getOption("mlpack.verbose", FALSE)` or the explicit initializer (I like that pattern and use it too).  Happy to expand as needed, I think I have examples for either in packages of mine.

**Comment by rcurtin** [comment]
Thanks for the suggestion @cgiachalis!  This is implemented now.  I expect that we'll release mlpack 4.4.0 in the next couple of days and then this will end up on CRAN shortly thereafter. :+1:

**Comment by cgiachalis** [comment]
Thanks!
