### ISSUE TITLE
bfd.h:35:2: error: #error config.h must be included before this header

### ISSUE THREAD

**Issue by ShevchenkoAlla** [mlpack/mlpack#3702]
I updated R, and all packages I usually use dippaseared. I perform 16s data analysis in R.
So, I am trying to install phyloseq package, and got errors

In file included from vendor/cigraph/vendor/glpk/api/prob.h:26,
from vendor/cigraph/vendor/glpk/api/advbas.c:23:
/home/alla/miniconda3/include/bfd.h:35:2: error: #error config.h must be included before this header
35 | #error config.h must be included before this header
| ^~~~~
In file included from vendor/cigraph/vendor/glpk/api/advbas.c:23:
vendor/cigraph/vendor/glpk/api/prob.h:103:7: error: unknown type name ‘BFD’
103 | BFD bfd; / BFD bfd[1:m,1:m]; */
| ^~~
make: *** [/usr/lib/R/etc/Makeconf:195: vendor/cigraph/vendor/glpk/api/advbas.o] Error 1
ERROR: compilation failed for package ‘igraph’

removing ‘/home/alla/R/x86_64-pc-linux-gnu-library/4.4/igraph’
ERROR: dependency ‘igraph’ is not available for package ‘phyloseq’
removing ‘/home/alla/R/x86_64-pc-linux-gnu-library/4.4/phyloseq’
The downloaded source packages are in
‘/tmp/RtmpPGwbcc/downloaded_packages’
Installation paths not writeable, unable to update packages
path: /usr/lib/R/library
packages:
codetools, lattice, MASS, Matrix, nlme, survival
path: /usr/local/lib/R/site-library
packages:
brew, cpp11, evaluate, prettyunits, remotes, rprojroot, rstudioapi,
withr
Warning messages:
1: In install.packages(...) :
installation of package ‘igraph’ had non-zero exit status
2: In install.packages(...) :
installation of package ‘phyloseq’ had non-zero exit status

I am not sure how to fix this, I would appreciate detailed explanations, because I am not programmer and it's hard to figure that out.

Thank you

**Comment by szhorvat** [comment]
The troubleshooting for igraph is [here](https://r.igraph.org/articles/installation-troubleshooting.html) and says [the following](https://r.igraph.org/articles/installation-troubleshooting.html#cannot-compile-igraph-from-sources-on-linux):

> If you have an Anaconda environment active, deactivate it _before_ compiling igraph. Having conda environments active are known to cause a number of issues, both during compilation and later during usage.

**Comment by ShevchenkoAlla** [comment]
> The troubleshooting for igraph is [here](https://r.igraph.org/articles/installation-troubleshooting.html) and says [the following](https://r.igraph.org/articles/installation-troubleshooting.html#cannot-compile-igraph-from-sources-on-linux):
> 
> > If you have an Anaconda environment active, deactivate it _before_ compiling igraph. Having conda environments active are known to cause a number of issues, both during compilation and later during usage.

Thank you, for the advice, I deactivated conda environment , but still no positive results


I tried a few things:


install.packages('igraph')



installing to /home/alla/R/x86_64-pc-linux-gnu-library/4.4/00LOCK-igraph/00new/igraph/libs
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘igraph’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/alla/R/x86_64-pc-linux-gnu-library/4.4/00LOCK-igraph/00new/igraph/libs/igraph.so':
  libopenblas.so.0: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/alla/R/x86_64-pc-linux-gnu-library/4.4/igraph’
Warning in install.packages :
  installation of package ‘igraph’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpDDxGhQ/downloaded_packages’
	
	
_________________________________________	
pak::pak("igraph/rigraph")


> pak::pak("igraph/rigraph")
                                                                            
→ Will install 1 package.
→ Will download 1 package with unknown size.
+ igraph   2.0.3.9015 [bld][cmp][dl] (GitHub: 56f1bfc) + ✔ libglpk-dev, ✔ libxml2-dev
✔ All system requirements are already installed.
  
ℹ Getting 1 pkg with unknown size
✔ Cached copy of igraph 2.0.3.9015 (source) is the latest build
✔ No downloads needed, all packages are cached
ℹ Building igraph 2.0.3.9015
✖ Failed to build igraph 2.0.3.9015 (1m 56.2s)                    
Error:                                                            
! error in pak subprocess
Caused by error in `stop_task_build(state, worker)`:
! Failed to build source package igraph.
Type .Last.error to see the more details.

<callr_error/rlib_error_3_0/rlib_error/error>
Error: 
! error in pak subprocess
Caused by error in `stop_task_build(state, worker)`:
! Failed to build source package igraph.
---
Backtrace:
1. pak::pak("igraph/rigraph")
2. pak::pkg_install(pkg, ...)
3. pak:::remote(function(...) get("pkg_install_do_plan", asNamespace("pak"))(.…
4. err$throw(res$error)
---
Subprocess backtrace:
 1. base::withCallingHandlers(cli_message = function(msg) { …
 2. get("pkg_install_do_plan", asNamespace("pak"))(...)
 3. proposal$install()
 4. pkgdepends::install_package_plan(plan, lib = private$library, num_workers = nw, …
 5. base::withCallingHandlers({ …
 6. pkgdepends:::handle_events(state, events)
 7. pkgdepends:::handle_event(state, i)
 8. pkgdepends:::stop_task(state, worker)
 9. pkgdepends:::stop_task_build(state, worker)
10. base::throw(pkg_error("Failed to build source package {.pkg {pkg}}.", …
11. | base::signalCondition(cond)
12. global (function (e) …



______________________________
BiocManager::install("igraph")

Error: package or namespace load failed for ‘igraph’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/alla/R/x86_64-pc-linux-gnu-library/4.4/00LOCK-igraph/00new/igraph/libs/igraph.so':
  libopenblas.so.0: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/alla/R/x86_64-pc-linux-gnu-library/4.4/igraph’

The downloaded source packages are in
	‘/tmp/RtmpDDxGhQ/downloaded_packages’
Installation paths not writeable, unable to update packages
  path: /usr/lib/R/library
  packages:
    codetools, lattice, MASS, Matrix, nlme, survival
  path: /usr/local/lib/R/site-library
  packages:
    brew, cpp11, evaluate, prettyunits, remotes, rprojroot, rstudioapi,
    withr
Warning message:
In install.packages(...) :
  installation of package ‘igraph’ had non-zero exit status
>

**Comment by rcurtin** [comment]
Hi there @ShevchenkoAlla, this doesn't look like an issue with mlpack to me, it looks related to some other R library. Although you already got some help here, I suspect you might have better success on other R forums. If mlpack is somehow implicated here and I missed it, let me know, but I don't see any evidence of it in your errors.

**Comment by ShevchenkoAlla** [comment]
> Hi there @ShevchenkoAlla, this doesn't look like an issue with mlpack to me, it looks related to some other R library. Although you already got some help here, I suspect you might have better success on other R forums. If mlpack is somehow implicated here and I missed it, let me know, but I don't see any evidence of it in your errors.

Hi, thank you :)
