### ISSUE TITLE
Switch from `-j 2` to `-j ${nproc}`

### ISSUE THREAD

**Issue by coatless** [mlpack/mlpack#3707]
Glancing at the runtime of the [R GitHub Actions workflow](https://github.com/mlpack/mlpack/blob/e851d0367ed2826e938eab02e77805f327185e42/.github/workflows/main.yml), I think we can use a few more cores. 

Currently, the number of cores is [set to 2](https://github.com/mlpack/mlpack/blob/e851d0367ed2826e938eab02e77805f327185e42/.github/workflows/main.yml#L119); however, GitHub Actions for public repositories allows for up to [4 cores/16 GB (`ubuntu-latest`) or 3 cores/7 GB (`macos-latest`)](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) to be present. 

I suppose this issue ticket is a note to switch: 

```
    env:
      MAKEFLAGS: "-j 2"
```

to:

```
    env:
      MAKEFLAGS: "-j $(nproc)"
```

Perhaps include this in the prior step as the `MAKEFLAGS` variables can be used when setting up R dependencies.

**Comment by rcurtin** [comment]
Want to give it a shot and see what happens?

In general I have noticed that compiling `mlpack_test` feels like it has gotten slower recently, perhaps due to our changes or perhaps due to changes to gcc, but I haven't looked deeply into it.

**Comment by coatless** [comment]
@rcurtin done in #3708. 

Not sure about the Azure pipelines aspect; but, I can look more in-depth later on.
