### ISSUE TITLE
Physics-Informed Neural Network possible with MLPack?

### ISSUE THREAD

**Issue by yvanblanchard** [mlpack/mlpack#3727]
Hello 
Is it possible to do PINN with this library, and if yes could you please share a basic tutorial ?
Thank you for sharing !

**Comment by conradsnicta** [comment]
@yvanblanchard mlpack is a volunteer driven project.  The neural network component within mlpack can be used and adapted in many use cases.  You can always contribute a tutorial or example codes on how to implement PINNs with mlpack.
