### ISSUE TITLE
Using Header-Only mlpack via CMake FetchContent and Automatic Dependency Download

### ISSUE THREAD

**Issue by mgaimann** [mlpack/mlpack#3734]
I was wondering whether using the mlpack headers is possible using CMake's [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) somehow.
Ideally, the dependencies would be automatically downloaded and built using -DCMAKE_DOWNLOAD_DEPENDENCIES=ON.
Has someone done this by chance and/or could provide a code snippet for doing this?

**Comment by shrit** [comment]
@mgaimann could you clarify more ? are you trying to integrate mlpack with your application ? what are you trying to do here ?
header only means that once you pulled the headers locally you can just point out in your makefile the location of these headers and that's it
