### ISSUE TITLE
How can I get params of linear regression?

### ISSUE THREAD

**Issue by ArtemJDS** [mlpack/mlpack#3767]
I followed the documentation and get the linear model.
```
lasso_model = output['output_model']

```

Now I want to get the coefficients of the regression. How can I do it. It seems to me that there is no function for this rn. 
I wasn't able to get them either by get_cpp_params or _get_cpp_params. Could you please sugget how I can do it.

**Comment by geekypathak21** [comment]
Hey, @ArtemJDS Can you share the full example code to replicate this issue `get_cpp_params` should work.
