### ISSUE TITLE
Mlpack failed to build with fatal error LNK1181: cannot open input file 'f2c.lib' with MSVC on Windows target arm64

### ISSUE THREAD

**Issue by spacelg** [mlpack/mlpack#3776]
Hi,

Mlpack failed to build with fatal error LNK1181: cannot open input file 'f2c.lib' with MSVC on Windows target arm64, it can reproduce on version 8af7aae on master branch. Could you please help look at this issue? Thanks in advance.

**Repro steps:**
1. Open VS2022 amd64 cmd.
2. git -C "C:\gitP" clone https://github.com/mlpack/mlpack mlpack\mlpack
3. vcpkg.exe install --recurse armadillo cereal ensmallen stb --triplet arm64-windows --clean-after-build
4. cd C:\gitP\mlpack\mlpack && mkdir build_arm64 && cd build_arm64
5. cmake -G "Visual Studio 17 2022" -A arm64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DDEBUG=OFF -DPROFILE=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DCMAKE_TOOLCHAIN_FILE=C:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=arm64-windows ..
6. msbuild /m /p:Platform=arm64 /p:Configuration=Release /p:PreferredToolArchitecture=x64 mlpack.sln /t:Rebuild

**Error log:**
[Build_arm64.log](https://github.com/user-attachments/files/16372965/Build_arm64.log)

**Error info:**
99>LINK : warning LNK4044: unrecognized option '/static'; ignored [C:\gitP\mlpack\mlpack\build_arm64\src\mlpack\methods\mlpack_nmf.vcxproj]
    99>LINK : warning LNK4044: unrecognized option '/static'; ignored [C:\gitP\mlpack\mlpack\build_arm64\src\mlpack\methods\mlpack_nmf.vcxproj]
    99>LINK : fatal error LNK1181: cannot open input file 'f2c.lib' [C:\gitP\mlpack\mlpack\build_arm64\src\mlpack\methods\mlpack_nmf.vcxproj]
         LINK : The linker is going to restart linking to generate a repro case
         Microsoft (R) Incremental Linker Version 14.41.34122.96
         Copyright (C) Microsoft Corporation.  All rights reserved.

**Comment by shrit** [comment]
mlpack only needs to link against BLAS and LAPACK, or OpenBLAS. The error is telling you that it is not able to find f2c.lib. I have no idea what this is but it should be a library that is related to linear algebra on Windows, Try first to find this library and check if it is installed and then link against it.
This error is not related to mlpack
