### ISSUE TITLE
mlpack.hpp missing from mlpack-4.4.0.msi

### ISSUE THREAD

**Issue by GLmontanari** [mlpack/mlpack#3782]
#### Issue description
Hi! I just downloaded the library from [https://www.mlpack.org/download.html], the mlpack-4.4.0.msi and the folder structure is not the same as if I clone the repo. In particular the `mlpack.hpp `file is missing, so I cannot to build the example solution with Visual Studio.
When I open the folder this is the content
![image](https://github.com/user-attachments/assets/38ed34cb-0b39-4d80-98c4-e7ecf227500c)

I follow the instructions on readme and copy the files in an include folder.
When I try to build the example app I get the following build error:

```
Build started at 09:25...
1>------ Build started: Project: sample-ml-app, Configuration: Debug x64 ------
1>stdafx.cpp
1>C:\mlpack\mlpack-4.4.0\Sources\examples\sample-ml-app\sample-ml-app\stdafx.h(18,10): error C1083: Cannot open include file: 'mlpack.hpp': No such file or directory
1>(compiling source file 'stdafx.cpp')
1>Done building project "sample-ml-app.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 09:25 and took 03,144 seconds ==========
```

And in fact I cannot find the file. `mlpack.hpp` is missing in the windows installer while is present if I clone the repo from github.
![image](https://github.com/user-attachments/assets/fabd2407-45ac-4d7f-9896-f4cca07ac3f7)

#### Your environment

 * version of mlpack: 4.4.0
 * operating system: Windows 11
 * compiler: 
 * version of dependencies (Boost/Armadillo): 11.4.2

**Comment by shrit** [comment]
it should be in the above directory as mlpack.hpp and the `mlpack` directory should be installed and you PC and not only the internal of `mlpack/` directory

**Comment by Yash8957** [comment]
You can try downloading and building it separately instead of downloading the library from above mentioned source.

**Comment by GLmontanari** [comment]
I know and I did. I just wanted to point out that if you make an
installation package, at least the example of the example folder should
work at first trial. No workarounds

Il lun 2 set 2024, 18:49 Yash Mishra ***@***.***> ha scritto:

**Comment by rcurtin** [comment]
Totally agreed @GLmontanari.  Working on a fix in #3788 now.

**Comment by rcurtin** [comment]
@GLmontanari thanks again for the report.  #3788 is ready, but not yet merged, so I mirrored the msi generated in the CI build: https://www.ratml.org/misc/mlpack-windows.msi, if you want to test it out or use it.  It has the latest code in the git `master` branch so it is technically newer than the latest release, but everything should be reverse compatible just fine if you want to use it. :+1:

**Comment by rcurtin** [comment]
#3788 is merged, so I'll go ahead and close this---the next stable release will have this fixed (and that link I gave will still work too).
