### ISSUE TITLE
Missing clustering section of mlpack docs

### ISSUE THREAD

**Issue by DonMaEn** [mlpack/mlpack#3784]
#### Problem location
https://www.mlpack.org/doc/index.html#clustering-algorithms

#### Description of problem
It looks like the clustering section of the mlpack.org docs is empty, which initially led me to believe that mlpack did not have any implementations of clustering algorithms. It was only later after I accidentally came across the mlpack doxygen page for DBScan than I realized it does have clustering algorithms. It might be worth adding a note in the empty clustering section about there being clustering methods which are implemented but don't have documentation yet so that new users like me don't get confused and decide they can't use mlpack because it doesn't have clustering.

**Comment by rcurtin** [comment]
Thanks for pointing this out @DonMaEn!  Originally the idea is that we would add parts of the documentation as it was done, but it never occurred to me that we should mark it as "under construction" :smile: I opened #3785 to address the issue.  I'm glad you dug around and realized that mlpack does have what you need---sorry that you had to dig extra hard to find it!

**Comment by bharatAmeria** [comment]
Hi guys,
Do mlpack have the support for clustering algorithms like DBSCAN, Mean-Shift clustering, BIRCH, Gaussian Mixture Model. If YES where can I find and If NOT can I giving a helping hand to build these algorithms support

**Comment by shrit** [comment]
yes check the CLI examples in the main source repository and the examples repository as you will find some examples on how to use these implementations

**Comment by bharatAmeria** [comment]
thanks @shrit for replying. Now my question regarding the above issue considering how can we add these examples or clustering algos to the clustering section of the mlpack documentation. Also to check the internal workings of the all mentioned clustering algos.

**Comment by DonMaEn** [comment]
Thanks for the quick response @rcurtin, the pull request looks great and perfectly addresses the issue.

**Comment by rcurtin** [comment]
Merged and after the next release the documentation on the website will be updated.  Thanks again for the report @DonMaEn!
