### ISSUE TITLE
Log::Fatal should give a backtrace of some sort

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#380]
If I write some mlpack code and have a snippet like

```
Log::Fatal << "Something is wrong!" << std::endl;
```

then the user just sees

```
[FATAL] Something is wrong!
```

One way to combat this is to give basic traces:

```
Log::Fatal << "Class::Method(): Something is wrong!" << std::endl;
```

but this leaves a lot to be desired, especially because `Class::Method()` may be somewhere deep inside of an algorithm where the user won't recognize the name of it, and thus will have no idea what's wrong.  If instead, they got some kind of backtrace, it would be quite helpful, i.e.

```
[FATAL] Something is wrong!
[FATAL]
[FATAL] In Class::Method(), called by
[FATAL]  OtherClass::OtherMethod(), called by
...
```

`Log::Assert()` in `src/mlpack/core/util/log.cpp` has a basic attempt to obtain a backtrace, but I suspect there is an easier way to do it.  (Maybe throwing an exception?)

**Comment by stephentu** [comment]
The code in `src/mlpack/core/util/log.cpp` seems to be the standard way of obtaining a backtrace in C++ (see http://panthema.net/2008/0901-stacktrace-demangled/). To be more portable, maybe use libunwind.

**Comment by sahmed95** [comment]
Can't we use __FUNCTION__ , __LINE__ or __FILE__ to find out the function or file with the Fatal error ?

**Comment by rcurtin** [comment]
You can't use `__FUNCTION__` since it's not standardized by ANSI C.  See this list:

https://docs.freebsd.org/info/cpp/cpp.info.Standard_Predefined.html

That gives you `__LINE__` and `__FILE__`, but that won't really help with a backtrace -- that will simply print the current location in the code (that may still be useful, of course).

**Comment by sahmed95** [comment]
Yeah,  I found some documentation on libunwind and could implement a simple code to backtrace inside a single file within different functions. Have to try on different classes with functions spread over multiple files. 
I still need some help on the Log::Fatal method and how it exits the program. Maybe the backtracing fucntion can be called just before the exit call to see the whole stack.

Link to implementation using libunwind : 
http://pastebin.com/BHgippet

Someone who worked on the mlpack / PrefferedStreamOutput file before can try to implement it..

**Comment by sahmed95** [comment]
I m trying to implement it too :-)...

**Comment by Kirizaki** [comment]
What about simple backtrace from c lib _<execinfo.h>_ ?

(http://www.gnu.org/software/libc/manual/html_node/Backtraces.html)

I already done some simple implementation which gives me similar output like this:
```
[bt]: (1) ./test(crash+0x24) [0x8c50]
[bt]: (2) ./test(foo4+0x10) [0x8c70]
[bt]: (3) ./test(foo3+0x10) [0x8c8c]
[bt]: (4) ./test(foo2+0x10) [0x8ca8]
[bt]: (5) ./test(foo1+0x10) [0x8cc4]
[bt]: (6) ./test(main+0x74) [0x8d44]
[bt]: (7) /lib/libc.so.6(__libc_start_main+0xa8) [0x40032e44]
```
At the beginning _backtrace_ gives mangled strings, after demangling and using libSegFault.so You can get some nice tracing with files / line number and functions, but more information You can find here:

(https://help.github.com/articles/markdown-basics/)

And I'm not sure what about portability of those methods.

**Comment by Kirizaki** [comment]
After good digging in C libs and some linux commands I prepared (external at the moment) pretty nice stack tracing.

<b>Please, test it in Your machine:</b> https://github.com/Kirizaki/stacktrace

Output should be:
```
/home/kirizaki/Projects/backtrace/traceExample/util/parent.cpp:Parent::ProtectedParentFoo():17
/home/kirizaki/Projects/backtrace/traceExample/util/parent.cpp:Parent::PublicParentFoo():12
/home/kirizaki/Projects/backtrace/traceExample/util/parent.cpp:Parent::Parent():6
/home/kirizaki/Projects/backtrace/traceExample/util/test.cpp:fooA(std::string):7
/home/kirizaki/Projects/backtrace/traceExample/util/test.cpp:fooB(int):15
/home/kirizaki/Projects/backtrace/traceExample/util/test.cpp:fooC(int):22
/home/kirizaki/Projects/backtrace/traceExample/util/test.cpp:main():27
```

While I'm implementing it in Log class, please feel free to comment what should be refactored. And after all I will try my best to add MSVC implementation too.

**Comment by Kirizaki** [comment]
I attached my stacktrace implementation and after calling ```Log::Assert(false, "My message!")``` I'm getting:
```
kirizaki@devAstation:~/Projects/backtrace/traceExample/util/stackMLPACK > g++ stack.cpp -o stack -I /usr/include/libxml2/ -lmlpack -ldl -g -rdynamic
kirizaki@devAstation:~/Projects/backtrace/traceExample/util/stackMLPACK > ./stack
[DEBUG] Compiled with debugging symbols.
[DEBUG] My message!
[DEBUG] Stacktrace:
[DEBUG] /home/kirizaki/Projects/backtrace/traceExample/util/stackMLPACK/stack.cpp:fooA():6
[DEBUG] /home/kirizaki/Projects/backtrace/traceExample/util/stackMLPACK/stack.cpp:fooB():11
[DEBUG] /home/kirizaki/Projects/backtrace/traceExample/util/stackMLPACK/stack.cpp:fooC():16
[DEBUG] /home/kirizaki/Projects/backtrace/traceExample/util/stackMLPACK/stack.cpp:main():21
kirizaki@devAstation:~/Projects/backtrace/traceExample/util/stackMLPACK > 
```
...and after ```Log::Assert(true, "My message!")```:
```
kirizaki@devAstation:~/Projects/backtrace/traceExample/util/stackMLPACK > g++ stack.cpp -o stack -I /usr/include/libxml2/ -lmlpack -ldl -g -rdynamic
kirizaki@devAstation:~/Projects/backtrace/traceExample/util/stackMLPACK > ./stack
[DEBUG] Compiled with debugging symbols.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Log::Assert() failed:My message!
Aborted
kirizaki@devAstation:~/Projects/backtrace/traceExample/util/stackMLPACK > 
```
Tomorrow I will finish with estetics and create Pull Request.

**Comment by Kirizaki** [comment]
After few changes:
https://github.com/Kirizaki/stacktrace.git

Please, test it (ubuntu/debian) and left feedback.

**Comment by stereomatchingkiss** [comment]
>You can't use __FUNCTION__ since it's not standardized by ANSI C. See this list:

I do not this would be helpful or not, but c++11 provide __func__ keyword, maybe worth to give it a shot

**Comment by Kirizaki** [comment]
```__func__```, ```__FUNCTION__``` or ```__PREETY_FUNCTION__``` don't give too much. I can write some extinguish algorithm which will retrieve names of functions and ```__FILE__```, but still I'm left without line, where ```__LINE__``` don't help either.

The simpliest way as I know is to "dump" output file with ```objdump``` which is provided in ```binutils-dev```. Then I can get some ```hex``` numbers from "relocations" of ```PC``` - I mean addresses which program counter was calling. After I should find those addresses in symbolic table or dynamic symbols table in section ```.text``` of ```objdump``` output where next to the names of functions are file's names and line numbers.

Even when I use ```libc``` libraries to get addresses of functions (like I actually do only to get addresses) You can go straight forward to symbolic table, but still I'm depending on ```objdump```.

For sure there is simple way to obtain all those informations but I think I'll need some 'hacky-tricks' to "dump" myself output file or go straight into stack.

That is why it's easier to depend on already prepared library ```bfd``` from ```binutils-dev``` because time to get full backtrace this way is equal to get backtrace only for one frame when I was searching through ```objdump```.

Of course those are my short experiences with debugging that is why please don't take them too seriously. ;)

**Comment by rcurtin** [comment]
Hey Kirizaki,

I'm really sorry for the slow response here.  I hope maybe you are still interested in this. :)

I think this is a really cool solution; I've tested on both g++ and clang on Linux and it works fine.  On OS X it doesn't seem to work though:

```
Failed to open executable!
: No such file or directory
Failed to open executable!
: No such file or directory
...
```

I also haven't tested on Windows.  At the very least, one of the things that we can do is integrate the support you've written here to be used if on Linux using `#ifdef`s.  What do you think?  If you're still interested, I think this would be a cool improvement. :)

**Comment by Kirizaki** [comment]
Hi there,<p> I'm really sorry too!<p> I was applying for very nice dev. job and due to many things connected with it I had to pass MLPACK for a while.<p> Of course I'm interested in implementing this in MLPACK, at the moment for Linux. To be honest, I tried to execute MLPACK in Windows but I got irritated too fast! <b>```T_T```</b> I'll try to put all ```#ifdef```s to my code until coming Sunday so We could prepare Makefile. <p>

**Comment by rcurtin** [comment]
I guess we can close this, because @Kirizaki's fix is implemented in master now and it is very nice.  Thanks again! :)

**Comment by Kirizaki** [comment]
I'm working now on ```mlpack::backtrace``` on Windows so maybe we could re-open this topic or should I create new?

**Comment by rcurtin** [comment]
I'd open a new ticket for that, if that's ok with you.

**Comment by Kirizaki** [comment]
No problem, go ahead.
