### ISSUE TITLE
matrix_completion_impl.hpp should be .cpp or have its functions inlined

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#381]
I was poking through the matrix completion code when I noticed that `matrix_completion_impl.hpp` is full of non-templatized functions that aren't marked `inline`.  This can be a problem if there are two separate compilation units that depend on `MatrixCompletion`; then there will be multiply-defined linker errors.

There are two possible ways to go, and both are easy: either we explicitly mark each function in `matrix_completion_impl.hpp` as `inline` so that the compiler doesn't provide symbols for the functions in separate compilation units, or we move `matrix_completion_impl.hpp` to `matrix_completion.cpp`.

But since I didn't write the code, I thought I'd open this issue so that you (@stephentu) could let me know what you want to do, and then either you can do it or I can do it, whatever, it's easy.  I figured if I waited until you showed up in IRC, I'd forget.  Hence the issue. :)

**Comment by stephentu** [comment]
I'll move it to a cpp file. I think I originally intended the code to have some templates, but then decided against it. I figured it wasn't wrong-- but you're right about the possible linker issues.

**Comment by stephentu** [comment]
closing
