### ISSUE TITLE
Add support for ccache 

### ISSUE THREAD

**Issue by eddelbuettel** [mlpack/mlpack#3840]
#### What is the desired addition or change?

Support `ccache` (for local use as well as at GitHub) 

Potentially `sccache` [its GH action](https://github.com/mozilla/sccache) can be used for even more distributed cache use, this is available as optional behavior of the main action.  For now, the focus is on just `ccache`.

#### What is the motivation for this feature?

`mlpack` is a large project with a lot of templated C++ code making compilation expensive.  Using `ccache` (and `sccache`) makes it very cheap to test localized changes.  In general headers are included only for needed features so a change in one method will not 'spill' over to other methods making the project an ideal beneficiary.  

Needless to say, other CI times such as running tests will not be impacted.

#### If applicable, describe how this feature would be implemented.

The simplest use case is to explicitly set two variables for `cmake` as I have done: 

```
    -DCMAKE_C_COMPILER_LAUNCHER=ccache \
    -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
```

Of course something can be added to `CMakeLists.txt` via (untested) A better approach is to do something like 

```cmake
# Check if ccache is available
find_program(CCACHE_PROGRAM ccache)

if(CCACHE_PROGRAM)
    message(STATUS "ccache found: ${CCACHE_PROGRAM}")

    # Enable ccache
    set(CMAKE_C_COMPILER_LAUNCHER ccache)
    set(CMAKE_CXX_COMPILER_LAUNCHER ccache)
    # Alternatively explicitly set compiler variables to use ccache
    #set(CMAKE_C_COMPILER   ${CCACHE_PROGRAM} ${CMAKE_C_COMPILER})
    #set(CMAKE_CXX_COMPILER ${CCACHE_PROGRAM} ${CMAKE_CXX_COMPILER})

else()
    message(STATUS "ccache not found")
endif()
```

#### Additional information?

Lots of projects use it by now.  Looking around my checked-out repos I see for example

Going beyond `ccache` to `sccache` seems like a very good idea too, I have less practical experience with `sccache` but would be happy to experiment in a test repo.  The action from Mozilla is said to be well-regarded.

```cmake
find_program(CCACHE_PROGRAM ccache)
if(CCACHE_PROGRAM)
  set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE "${CCACHE_PROGRAM}")
else()
  find_program(CCACHE_PROGRAM sccache)
  if(CCACHE_PROGRAM)
    set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE "${CCACHE_PROGRAM}")
  endif()
endif()
```

The 'global property' appears to automagically affect sub-builds.  One exception is the R tasks which are spawned a shell jobs.  R itself is not cmake aware, but one can affect this via the `make` invocation with e.g. a file `~/.R/Makevars` containing, at a minimum

```
CC=ccache gcc
CXX=ccache g++
CXX17=ccache g++
SHLIB_CXXLD=ccache g++
```

(and ditto for macOS and `clang/clang++` use).  Because R builds in per-session temporary directories one also has to tell `cmake` to ignore the directory path, and due to how R unpacks sources, use create time timestamps.  So these two values need to be appended to `ccache.conf`:

```
sloppiness = include_file_ctime
hash_dir = false
```

This can be tested locally, and I recommend it.  Running, say, `R CMD INSTALL somethinghere_1.2.3.tar.gz` twice and seeing the speedup directly is quite nice.

PS Alternatively, in another repo `cmake/Modules/FindCcache.cmake` has this which also consider `sccache` if present

```cmake
## cf https://stackoverflow.com/questions/1815688/how-to-use-ccache-with-cmake
## leading to https://invent.kde.org/kde/konsole/merge_requests/26/diffs
find_program(CCACHE_FOUND NAMES "sccache" "ccache")
set(CCACHE_SUPPORT ON CACHE BOOL "Enable ccache support")
if (CCACHE_FOUND AND CCACHE_SUPPORT)
  if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU" # GNU is GNU GCC
      OR "${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    # without this compiler messages in `make` backend would be uncolored
    set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -fdiagnostics-color=auto")
  endif()
  set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ${CCACHE_FOUND})
  set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ${CCACHE_FOUND})
  message(STATUS "Found ccache: ${CCACHE_FOUND}")
else()
  message(FATAL_ERROR "Unable to find ccache")
endif()
```

**Comment by eddelbuettel** [comment]
I checked on a (much) smaller test and demo cmake repo that the 'global property' appears to work for a `test/` directory and `ctest` use.  Which failed for me with `mlpack` but maybe someone with better `cmake` chops than me can look into that.

**Comment by rcurtin** [comment]
This would definitely be nice support to add.  I will jump on it eventually when I have time, but if someone else wants to take the initiative I'm happy to provide a review. :+1:

**Comment by eddelbuettel** [comment]
I can _definitely_ create a PR with the change above to set the global property.  It does the right thing: in a demo / tutorial repo it even even prefixes `gfortran` with `ccache`.  We would then have to sort out why it currently does not propagate `ccache` to all of the subbuilds ... but to some.

I will also try to set up a skunk repo with maybe just the R package tarball or some other subset and try an see what I can learn about `sccache` and persistent caching at GH.

**Comment by eddelbuettel** [comment]
Ok, I created a [skunkworks repo](https://github.com/eddelbuettel/mlpack-ci-tests) and [its actions](https://github.com/eddelbuettel/mlpack-ci-tests/actions) show this (with the usual amount of :x: and :heavy_check_mark: intertwined and 'programming in yaml' can be unforgiving).

**Comment by eddelbuettel** [comment]
This was done in #3842
