### ISSUE TITLE
GaussianDistribution should cache covariance matrix factorization

### ISSUE THREAD

**Issue by stephentu** [mlpack/mlpack#385]
The `GaussianDistribution` class is quite inefficient right now. It should factorize the covariance matrix on construction, not for each invocation of `Random()` or `Probability()`.

**Comment by rcurtin** [comment]
This is related to #215.

There is a slight issue with making this change: what happens to this code?

```
GaussianDistribution g(mean, covariance); // This factorizes 'covariance'.
g.Covariance() = newCovariance; // The new covariance isn't factorized.
```

It's easy enough to change the signature...

```
GaussianDistribution g(mean, covariance); // This factorizes 'covariance'.
g.Covariance(newCovariance); // This re-factorizes 'covariance'.
```

but now I can't make simple changes to the covariance while avoiding matrix copies.  So this code becomes impossible:

```
GaussianDistribution g(mean, covariance); // This factorizes 'covariance'.
// Recalculate covariance.
g.Covariance().zeros();
for (size_t i = 0; i < numPoints; ++i)
  g.Covariance() += x.col(i) * x.col(i).t(); // Or something like that.
```

Maybe the better API solution is to leave `GaussianDistribution::Covariance()` intact, allowing direct access to the covariance matrix, but make a note that if the covariance matrix is modified, the user *must* call something like `GaussianDistribution::InvertCovariance()` or whatever after the modification is done, or `Probability()` will return incorrect results.

**Comment by stephentu** [comment]
I thought about this, but I would just have made a setter method. How often do you change covariance?Would this be ok?

```
GaussianDistribution g(mean, covariance); // This factorizes 'covariance'.

// Recalculate covariance.
arma::mat newCovariance(g.Covariance().n_rows, g.Covariance().n_cols);
newCovariance.zeros();
for (size_t i = 0; i < numPoints; ++i)
  newCovariance += x.col(i) * x.col(i).t(); // Or something like that.

// Set and factorize newCovariance
g.Covariance(std::move(newCovariance));
```

No un-necessary copy, but needs un-necessary storage.  Forcing the user to call `InvertCovariance()` is too error prone IMO.

**Comment by rcurtin** [comment]
Ah, C++11 saves the day again!  That seems like a great solution to me.

**Comment by stephentu** [comment]
Cool, I'll get a PR up for this

**Comment by stephentu** [comment]
Ugh I thought this was going to be a trivial fix, but it turns out there are several places in the codebase doing the `dist.Covariance() = x` or stashing an lvalue reference to `dist.Covariance()`. I'll have to analyze each case separately and probably refactor some code. Point is, might take longer than I thought.

**Comment by rcurtin** [comment]
If you want to split the work, let me know what files you want me to work with, and I'm happy to bear part of the load. :)
