### ISSUE TITLE
Error in opening the redirected Community page from Contributing.md

### ISSUE THREAD

**Issue by Rishi2003Das** [mlpack/mlpack#3857]
#### Issue description

Request Page not found: 404 Error in opening the redirected Community page from Contributing.md . 

#### Your environment

 * version of mlpack: 4.5.1
 * operating system: Windows 11
 * version of dependencies (Boost/Armadillo): Armadillo

#### Steps to reproduce

Go to Contribution.md and in the first paragraph, you can notice a hyperlink named Community which is redirected to open the community page but it is not opening. 

#### Expected behavior

Expected to show the community page.

#### Actual behavior
![The Error Page](https://github.com/user-attachments/assets/864dfa80-a0ca-42ff-9236-b4da9ee5180b)

**Comment by Rishi2003Das** [comment]
Hi I am @Rishi2003Das ,  I can solve the issue and can do a PR to resolve it.

**Comment by conradsnicta** [comment]
resolved in #3858
