### ISSUE TITLE
setup travis CI builds

### ISSUE THREAD

**Issue by stephentu** [mlpack/mlpack#392]
we should setup travis CI builds so we can test pull requests before we merge them. also each git commit will get tested and we can spot regressions much faster

**Comment by stephentu** [comment]
So I've made progress on this. However, since we only get 50 minutes before the builds timeout, we need to hunt down the test which are taking too long. Here are the offenders now: http://big.cc.gt.atl.ga.us:8080/job/mlpack%20-%20nightly%20matrix%20build/arch=linux-i386,armadillo=armadillo-4.200.0,buildmode=debug/735/testReport/MLPACKTest/

**Comment by rcurtin** [comment]
I'll fix FastMKSTest.

**Comment by rcurtin** [comment]
(unless you want to, that is, but it shouldn't take long for me to do since I wrote the test...)

**Comment by stephentu** [comment]
By all means go ahead :) I'm just making this note for our own reference.

**Comment by rcurtin** [comment]
Hmm, do you think this is finished?  It looks to me like Travis is running the tests now, and automatically tries to build any pull requests, which is pretty excellent.

**Comment by rcurtin** [comment]
This seems done to me (reopen if desired). :)
