### ISSUE TITLE
libxml problem compiling kmeans (similar to #285)

### ISSUE THREAD

**Issue by fmaguire** [mlpack/mlpack#393]
Fresh build of mlpack on 64-bit linux (Arch) latest stable release following the standard install (`cmake ../; make; make test; make install`).

Cmake seems to find libxml correctly:

    -- Found LibXml2: /usr/lib64/libxml2.so (found suitable version "2.9.2", minimum required is "2.6.0") 

All tests pass and make install seems to run fine (binaries all work correctly).

However, when I try to follow the kmeans example compiling with:
     #include <mlpack/methods/kmeans/kmeans.hpp>
  
Gives the following error:

    /usr/local/include/mlpack/core/util/save_restore_utility.hpp:26:27: fatal error: libxml/parser.h: No such file or directory

This might be a very naive issue (and almost certainly similar to #285), clearly I need to correctly link libxml2 when compiling mlpack but I'm not quite sure how to go about that with cMake and I don't trust myself to correctly manually compile everything.

**Comment by rcurtin** [comment]
What you'll need to do is add the include directory `/usr/include/libxml2/` (I assume this is where Arch puts the libxml2 headers) to the compiler's search path.  From the command-line (using g++ or clang) this is easily accomplishable with `-I/usr/include/libxml2/`, and then you can link with `-lxml2`.  If you're using CMake to configure and build your application, then try this snippet:

```
find_package(LibXml2 2.6.0 REQUIRED)
include_directories(${LIBXML2_INCLUDE_DIR})
```

and then when you link your program, add libxml2 to the dependencies:

```
target_link_libraries(your_program
  ... # Other dependencies...
  ${LIBXML2_LIBRARIES})
```

Really this is sort of an unsatisfying solution, and the better solution will be a solution to #315 (or something like that) that makes the libxml2 dependency entirely internal to libmlpack.so.  But unfortunately this hasn't been done yet, so what I've written above is probably the best answer I can give for now...

Hopefully this is helpful.  If not, let me know, and I can elucidate further...

**Comment by fmaguire** [comment]
Thanks very much, solved it by modifying the cmake config as you suggested. Sorry for such a painfully simple issue!
