### ISSUE TITLE
liblapack linking issue

### ISSUE THREAD

**Issue by jaskaran1** [mlpack/mlpack#394]
I was building mlpack from source.After the make step, I get a linking error.
jaskaran@ubuntu:~/Desktop/mlpack-1.0.12/build$ make
Moving header files to include/mlpack/
[  0%] Built target mlpack_headers
[ 30%] Built target mlpack
Linking CXX executable ../../../../bin/cf
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zptgemm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_scopy'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_stpsv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_saxpy'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_srotg'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ztrsv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zhpr'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cswap'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_drot'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zgeru'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_stbsv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dsyr'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zher2'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cptgemm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cset'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zdrot'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ssyreflect'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_scnrm2'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_stbmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zpther2k'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cpthemm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cpttrsm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ztbsv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sspr'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_csyreflect'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dpttrmm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dscal'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dsyr2'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zGetNB'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ddot'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zaxpy'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cgeru'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ssymv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dzasum'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sptsyrk'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ztbmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_snrm2'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cptherk'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zhpmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cptsyr2k'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zgbmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dptgemm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ccopy'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dset'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cptsymm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sger'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cher2'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dGetNB'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_crotg'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zswap'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dtbsv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zdotc_sub'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zptherk'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ctpmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zpttrsm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ctrsv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dptsyrk'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zsyreflect'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dspr'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dtrsv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sptgemm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zgemv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cher'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ssbmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_caxpy'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sptsymm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cgerc'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dnrm2'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dsyreflect'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sdsdot'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_spttrmm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cscal'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_stpmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sspmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cdotu_sub'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ctbmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_icamax'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sscal'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sptsyr2k'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ssyr'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ctbsv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_drotmg'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_spttrsm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zhpr2'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ctpsv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zpthemm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dpttrsm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_strmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zcopy'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_idamax'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zscal'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cdotc_sub'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dtbmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sspr2'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cpther2k'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ztrmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zcopyConj'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zmoveConj'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zptsyrk'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cgemv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zcplxinvert'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cscalConj'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sasum'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zscalConj'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dcopy'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zaxpby'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cmoveConj'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_scasum'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_srotmg'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dtpsv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sdot'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_chpr2'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zhemv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zdotu_sub'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zptsyr2k'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_chbmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sswap'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ccplxinvert'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zptsymm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_izamax'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_drotg'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dtrmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ztpmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zher'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_srot'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dsdot'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ztpsv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_srotm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_daxpby'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sset'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zpttrmm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_daxpy'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dgemv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cpttrmm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ctrmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ccopyConj'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zgerc'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dgbmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dspr2'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sgbmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dptsyr2k'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dsymv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sgemv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dsbmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dasum'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_saxpby'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dswap'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_chpmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_isamax'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_caxpby'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dtpmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dptsymm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_chpr'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dznrm2'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_ssyr2'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_sGetNB'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zset'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zhbmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dger'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_chemv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cGetNB'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_csrot'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_dspmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_xerbla'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_drotm'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cptsyrk'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_cgbmv'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_zrotg'
/usr/lib/liblapack.so.3gf: undefined reference to `ATL_strsv'
collect2: ld returned 1 exit status
make[2]: *** [bin/cf] Error 1
make[1]: *** [src/mlpack/methods/cf/CMakeFiles/cf.dir/all] Error 2
make: *** [all] Error 2

**Comment by rcurtin** [comment]
Sorry for the slow response; I see you've closed the ticket.  What was the issue?  I was going to guess that libatlas wasn't installed or something like that once I tried to reproduce the problem.

**Comment by jaskaran1** [comment]
I switched to the default lapack

sudo update-alternatives --set liblapack.so.3gf /usr/lib/lapack/liblapack.so.3gf

**Comment by rcurtin** [comment]
Ah, okay, this is a packaging issue with ATLAS:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=624318

The workaround you used should work just fine.

**Comment by jaskaran1** [comment]
Finally,I've completed building mlpack from source.
But I didn't install libatlas.Will that pose a problem later on?

**Comment by rcurtin** [comment]
No, ATLAS is just a LAPACK/BLAS replacement.  As long as you have some LAPACK or BLAS equivalent installed (which you do), mlpack should work just fine.
