### ISSUE TITLE
Investigate implementing SGD for LRSDP

### ISSUE THREAD

**Issue by stephentu** [mlpack/mlpack#395]
SGD for LR-SDP is becoming more popular, and this paper http://arxiv.org/pdf/1411.1134v2.pdf lays the groundwork for some neat theoretical convergence results (in particular, how to choose step sizes). This is really cool stuff which we should investigate. 

This could be a fun project for someone looking to contribute code to mlpack.

**Comment by paarthneekhara** [comment]
I was going through the paper.. I was wondering if you expect 
"Algorithm 1 Alecton: Solve stochastic rank-1 matrix completion problem"
 this algorithm to be implemented or something beyond that. I am thinking of making my first contribution to mlpack.

**Comment by stephentu** [comment]
Hi @paarthneekhara!

This is sort of an open ended proposal. The point is, I'm not really satisfied w/ any of the SDP methods I worked on for mlpack-- we have LR-SDP which requires lots of hand-holding in practice, and we have this new primal-dual interior point method which, while theoretically sound, is quite slow in practice. If we could have something that (a) restricts the class of problems it solves but (b) scales well in practice and (c) has theoretical convergence guarantees, then that'd be awesome.

However, I don't want to just keep adding SDP solvers to mlpack (they impose maintenance burden) unless there is a clear win. Hence, it'd be cool to have an implementation of alecton, but I'd be hesitant to merge it unless it actually worked well. Since this is a newer algorithm, there is more risk of this happening. I want to warn you ahead of time, so that if you do decide to work on it and it doesn't work well, there won't be any hard feelings :smile:

If you're deterred by this, but still want to work on something related to SDPs in mlpack, I have a few "lower risk" ideas related to improving our existing solvers. Let me know.

**Comment by palashahuja** [comment]
@stephentu , is this task open right now ?

**Comment by abhinvgpta** [comment]
Hi @stephentu,
     Do you have any more ideas where I can start from? I'm familiar with the ann part and more than willing to look into issues related to it. Thanks.

**Comment by stephentu** [comment]
@abhinvgpta: Unfortunately not really. As I mentioned before this is an open ended project. I really should change the title to "investigate alternative methods for solving low rank SDPs". As I mentioned above, LR-SDP has its drawbacks. For problems like matrix completion, SGD seems to be a reasonable heuristic that works well in practice. Maybe that could be a first place to start.

**Comment by rcurtin** [comment]
Since LRSDP is a part of ensmallen now, I opened mlpack/ensmallen#73.  We can continue any discussion there. :+1:
