### ISSUE TITLE
Implement spectral based manifold learning algorithms

### ISSUE THREAD

**Issue by stephentu** [mlpack/mlpack#396]
It should be straightforward for us to provide implementations of various spectrally based manifold learning methods, such as laplacian eigenmaps, LLE, isomap, etc. The major obstacle right now is exposing the arpack generalized eigenvalue solver via armadillo. This shouldn't be too difficult, but may take some patience.

**Comment by stephentu** [comment]
Note that this wouldn't include MVU: we still need to work on our SDP solvers for MVU to become viable.

**Comment by rcurtin** [comment]
I'll work on the generalized eigenvalue solver once the ICML deadline is over (so, after the 6th).  We can push it to Armadillo and then for older versions, make the function available in `src/mlpack/core/arma_extend/`.

**Comment by stephentu** [comment]
that would be awesome :smile:

**Comment by stephentu** [comment]
Note: here is a neat reference implementation for the manifold learning methods: https://github.com/lisitsyn/tapkee

**Comment by theaverageguy** [comment]
I would like to work on this. Please let me know how much of it is done ?

**Comment by rcurtin** [comment]
Hi there, you're welcome to implement a manifold learning method.  Note that there are two PRs open for implementations that haven't been merged yet, so it probably does not make sense to replicate their work:
https://github.com/mlpack/mlpack/pull/439
https://github.com/mlpack/mlpack/pull/430

**Comment by Kavignon** [comment]
Are there any learning method I could check during the summer to implement ?

**Comment by rcurtin** [comment]
None of the ones proposed at the top of this issue have been incorporated, so I would say, if you want to add one, there is no problem with this. :)

**Comment by riaash04** [comment]
Hi, I would like to work on this. I went through the two open PRs to see how they have gone about their implementation, but could not get why they were not merged. Would be glad to get some directions.

**Comment by rcurtin** [comment]
Lack of time primarily.  If you want to adapt them and update them I'd be happy to get them merged in.  I think the code there is pretty out of date now.

**Comment by riaash04** [comment]
Ok, thanks. I am currently trying to implement Isomap. I should be able open a pull request in a few days.

**Comment by riaash04** [comment]
I have opened a pr #1759 , which implements isomap.
