### ISSUE TITLE
Saving and Loading Submatrices

### ISSUE THREAD

**Issue by mikemodanoxxx** [mlpack/mlpack#400]
Hi there,

there seems to be a problem when saving submatrices with the SaveRestoreUtility. When saving a normal object arma::mat obj, the elements are separated by commas. When saving something like obj.cols(0, 2), the elements are separated by pure whitespace. When loading such an object again into an arma::mat, only the first column of the data is loaded. The difference results from the specialisation for arma::mat matrices in the SaveRestoreUtility class. I don't know why this was implemented, as it works fine when the specialisation is just commented out (that's why I suggest that for solving the problem).

**Comment by rcurtin** [comment]
Hi there,

Thanks for reporting this.  The code in SaveRestoreUtility is due for an overhaul (see also #315) at some point, but this helps make it a bit simpler.  Hopefully the commit in abdfa0b should help.
