### ISSUE TITLE
SDP should have a more general linear operator constraint

### ISSUE THREAD

**Issue by stephentu** [mlpack/mlpack#401]
Our SDP abstraction right now only supports sparse and dense matrices. This is sufficiently general, but for some certain classes of constraints, quite suboptimal. 

As an example, suppose I want to have the constraint that the sum of all elements in the matrix is constant. While we can express this as `Tr((11^T) * X) = b`, this is quite inefficient to evaluate for something that could be expressed as `X.sum()`. 

Hence, it would be desirable to have a third type of constraint, "linearOperator", which is just a linear function which takes symmetric matrices to real numbers. The straightforward way to implement this would be a vector of `std::function` objects.

**Comment by chvsp** [comment]
Hi Stephen ( @stephentu ), I, quite frankly, don't have enough experience with mlpack as such but I am strongly motivated to learn about the same. I am interested, willing and motivated to solve this issue as it appears to make the mlpack interface more user friendly. Please provide me with the necessary inputs to get me to understand the same.

**Comment by stephentu** [comment]
Hi @chvsp: This task would be to prove a functional representation of a constraint. The API work is pretty minimal-- the main part would be integrating it into the optimizers. I don't think it's hard to do, but will require some understanding of how the optimizers work. Could be a good starter task.

**Comment by stephentu** [comment]
For instance, take a look at this file: https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/optimizers/sdp/lrsdp_function_impl.hpp, and think about how to add this 3rd constraint type in (we already have dense and sparse constraints).

**Comment by jennakwon06** [comment]
I am a GSoC applicant applying to implement frank-wolfe optimizer framework, and I would also be willing to pick up on this as part of the project!

**Comment by stephentu** [comment]
Hi @jennakwon06, please look at the discussion in #578. Someone has proposed to implement this for the time being, so I think I would focus on the frank-wolfe aspect for now.

**Comment by prasanna08** [comment]
Hi @stephentu I would like to work on this issue. I don't have much idea about SDP optimiser. I am interested in learning it. Can you help me to get started with this issue ?

**Comment by rcurtin** [comment]
Since this is a part of ensmallen now, I opened mlpack/ensmallen#72, and we can continue discussion there.
