### ISSUE TITLE
Getting started - xmllib2, libmlpack.so.1 and "undefined reference to mlpack" issue (Solutions to ticket 357,348,268) 

### ISSUE THREAD

**Issue by sahmed95** [mlpack/mlpack#402]
Pardon me if this seems trivial as I am new to mlpack,
I faced the following issues and found some solutions to them (for Ubuntu 14.04) :
Can these be updated in the wiki ? Or using a makefile for compilation solves all three issues ? 

1. While compiling, need to use -I /usr/local/libxml2/ (http://www.mlpack.org/trac/ticket/357)

Solution :
	Open terminal :
	export CPATH=/usr/local/include/libxml2/

2. Need to add path to libmlpack.so.1 while running ./a.out (http://www.mlpack.org/trac/ticket/348)

Solution :
	1. Create a new file in /etc/ld.so.conf.d/ called .conf
	(use sudo)
	Edit the file and add a line per directory of shared libraries (*.so files), it will look something like:
	/usr/local/lib/
	Reload the list of system-wide library paths:
	Run : 
	$sudo ldconfig

	Alternate : You can temporarily add path as LD_LIBRARY_PATH=/usr/local/lib/ 

3. Linking required while compiling as g++ file.cpp -lmlpack (http://www.mlpack.org/trac/ticket/268)
	This can be done by creating a makefile

**Comment by rcurtin** [comment]
The compilation issue with libxml2 is outstanding and needs to be resolved one way or another; there's already an issue open for that: #315 

If you're having trouble with installing mlpack, why not install from the Ubuntu repositories directly?  That is very much easier, and then libmlpack.so ends up in your linker's search path (in /usr/lib/ or similar, depending on the distribution) and the headers end up in the compiler's search path (in /usr/include/).  You still need to link against mlpack, but that's basic gcc knowledge.

I can't really incorporate anything here into the documentation; a lot of the paths you've suggested are specific to either your distribution or your install, and manually adding a hidden file to your ld.so.conf.d/ just for mlpack is not always the best solution, especially if you start installing lots of things in /usr/local/, like newer (or different) versions of system libraries, which can lead to the wrong library being loaded at runtime and eventual disaster (again, depending on the system, the modifications to the runtime linker configuration, and so forth).  Plus, the README.md file (in the master branch, at least) does mention that you may need to manually set your linker's search path with `LD_LIBRARY_PATH` (or something else, as usual, depending on the specifics of the system configuration).

If you find specific information in the wiki that's misleading or incorrect, please, open an issue so we can address it, but I really want to avoid hard-coding distribution-specific documentation, as it is subject to change---and when the distributions do change how they do things (which is quite often), then our documentation is out of date and users get confused...

**Comment by sahmed95** [comment]
Thank you. I guess installing from ubuntu repository is the best way...  I could install and run mlpack with the suggestions given. I tried to work around the libxml2 issue by manually #including the parent folder /libxml2 as the libxml folder resides inside it, but that's again not a very good idea I guess. Anyone working on the issue?   Or you want to completely do away with the dependency by writing new save / load functions? As part of GSoc ?

**Comment by rcurtin** [comment]
You can just add the libxml2 include path to GCC's search path by adding `-I/path/to/include/libxml2/` (which on your system, I guess, is `/usr/local/include/libxml2/`).  The right solution for libxml2 is either a complete redesign of the SaveRestoreUtility, or a refactoring that completely hides the libxml2 classes in `.cpp` files (so that the libxml2 headers aren't required by any of the mlpack headers).  If you're interested in trying to do that, please feel free, but I think the refactoring may be somewhat complex.  (We should probably discuss on that issue instead, if you're interested in continuing the discussion.)
