### ISSUE TITLE
SDP should deal with linearly dependent constraints somehow

### ISSUE THREAD

**Issue by stephentu** [mlpack/mlpack#404]
we need some strategy for dealing w/ a linearly dependent set of constraints. for LR-SDP, this isn't so big of a deal. but, this is especially key for the primal dual methods, which require this assumption so that various linear systems have unique solutions. we could either introduce a method which removes redundant constraints, or adapt the primal-dual method to handle degenerate linear systems.

**Comment by stephentu** [comment]
note that, if we want the MVU SDP to work, then this will be necessary

**Comment by palashahuja** [comment]
@stephentu , could you please give more information about this ?

**Comment by rcurtin** [comment]
@palashahuja: are you familiar with SDPs and LRSDP?  If not you should take a look into that first.  mlpack provides some code for solving SDPs (in src/mlpack/core/optimizers/sdp/) but it doesn't handle linear constraints nicely (you have to represent your linear constraint as an entire dense or sparse matrix which is often unwieldy and in some cases not possible).  So we need to find a way to adapt that code to deal with linear constraints more nicely.

**Comment by palashahuja** [comment]
@rcurtin , I have looked into LRSDP and SDP. What I am asking is how to deal with linear constraints ?

**Comment by rcurtin** [comment]
I don't know what you mean when you say "some sort of string".  This is, in my interpretation, an exploratory ticket: we don't currently have a good way to deal with linear constraints, and one needs to be designed.  So the goal is to design a nice solution for handling linear constraints.  It's possible this is already being handled by someone else in #578, so it might be better to try and avoid duplicating work here.

**Comment by stephentu** [comment]
@rcurtin: this task is slightly different than #578 (it took me a while to realize this). This tasks deals w/ the issue that currently the IP code assumes the nullspace of the A operator is trivial. This is not an easy task IMO, and I'm not sure what the current benefits are (nobody has ever complained about this).

**Comment by rcurtin** [comment]
Oops, you're right, I misread---I read "we need some strategy for dealing w/ linear constraints" but it actually says "we need some strategy for dealing w/ a linearly dependent set of constraints".  Sorry about that!

**Comment by rickllyxu** [comment]
@stephentu @rcurtin  Glad to tell you that, mvu based on primal-dual SDP solver **works**! I modify the file `mlpack/src/mlpack/tests/sdp_primal_dual_test.cpp` and the test case `SmallMvuSdp` works! I will commit codes after adjusting the code style.
Actually, the test case proves that primal-dual sdp solver can solve the mvu-sdp formulation. I will work on the step 3 tomorrow: Spectral
Embedding, i.e. Extract a low dimensional embedding from the dominant eigenvectors of the Gram matrix learned by semidefinite programming.

**Comment by rickllyxu** [comment]
A simple code to remove redundant constraints in MVU sdp formulation. :grinning:

**Comment by rcurtin** [comment]
Very nice, thanks for taking the time to work on that.  Honestly if we are able to restate the SDPs we work with to avoid including linearly dependent constraints (specifically for MVU), I think I would be happy to close this issue.  As pointed out earlier, nobody has ever complained about this issue, so I don't think we need to spent too much time figuring out a solution until it becomes more of a problem.

**Comment by rickllyxu** [comment]
OK, I think it should be linearly independent constraints if I filter the redundent nearest pairs. But some problems still exist. 
I wanted to solve the problem of MVU + LRSDP, and made the mvu + SDP as a starter. Of course I'd like to participate other ideas mentioned in GSoC idea lists.

**Comment by rickllyxu** [comment]
I have proved the constraints for MVU are linear dependence in paper if I filter the redundent nearest pairs. But the SDP solver (primal-dual interior-point method) still almost can not solve the sdp formulation of it ( however works for some cases). 
This goes back to the problem of the SDP solver, not the MVU. Though the linear dependence is satisfied, the sdp solver can not solve some sdp problems. I think this issue could be closed, and if someday someone complains the sdp solver, we need to perfect it.
Plz refer my comments in  #1381 for more detail.

**Comment by rcurtin** [comment]
We can continue discussion in mlpack/ensmallen#71, since this is now a part of ensmallen.
