### ISSUE TITLE
Error Compiling Lars.cpp on Windows

### ISSUE THREAD

**Issue by theSundayProgrammer** [mlpack/mlpack#424]
Using Visual Studio 2013 Release x64
In this function
void LARS::GivensRotate(const arma::vec::fixed<2>& x,
                        arma::vec::fixed<2>& rotatedX,
                        arma::mat& matG)
{
  if (x(1) == 0)  /////////////////////////////compiler error/////////////////////

The compiler error is (could be an issue with armadillo);
-------------------------------------------------------------------------------------------------------------------------
1>C:\Projects\CPP\mlpack\mlpack-1.0.12\src\mlpack\methods\lars\lars.cpp(431): error C3066: there are multiple ways that an object of this type can be called with these arguments
1>          c:\projects\include\armadillo_bits/Col_bones.hpp(198): could be 'const arma::subview_col<eT> arma::Col<eT>::operator ()(const arma::span &) const'
1>          with
1>          [
1>              eT=double
1>          ]
1>          c:\projects\include\armadillo_bits/Col_bones.hpp(198): or       'arma::subview_col<eT> arma::Col<eT>::operator ()(const arma::span &)'
1>          with
1>          [
1>              eT=double
1>          ]
1>          c:\projects\include\armadillo_bits/Col_bones.hpp(198): or       'double &arma::Mat<double>::operator ()(const arma::uword)'
1>          c:\projects\include\armadillo_bits/Col_bones.hpp(198): or       'const double &arma::Mat<double>::operator ()(const arma::uword) const'
1>          c:\projects\include\armadillo_bits/Col_bones.hpp(221): or       'double &arma::Col<double>::fixed<0x02>::operator ()(const arma::uword)'
1>          c:\projects\include\armadillo_bits/Col_bones.hpp(222): or       'const double &arma::Col<double>::fixed<0x02>::operator ()(const arma::uword) const'
1>          while trying to match the argument list '(int)'
---------------------------------------------------------------------------

The work around is
if (x[1] == 0)

**Comment by theSundayProgrammer** [comment]
(same error but error string formatted better)
lars.cpp(431): 
error C3066: there are multiple ways that an object of this type can be called with these arguments
          c:\projects\include\armadillo_bits/Col_bones.hpp(198): 
		  could be 'const arma::subview_col<eT> arma::Col<eT>::operator ()(const arma::span &) const'
          with
          [
              eT=double
          ]
		  
          c:\projects\include\armadillo_bits/Col_bones.hpp(198): 
		  'arma::subview_col<eT> arma::Col<eT>::operator ()(const arma::span &)'
          with
          [
              eT=double
          ]
          c:\projects\include\armadillo_bits/Col_bones.hpp(198): 'double &arma::Mat<double>::operator ()(const arma::uword)'
          c:\projects\include\armadillo_bits/Col_bones.hpp(198): 'const double &arma::Mat<double>::operator ()(const arma::uword) const'
          c:\projects\include\armadillo_bits/Col_bones.hpp(221): 'double &arma::Col<double>::fixed<0x02>::operator ()(const arma::uword)'
          c:\projects\include\armadillo_bits/Col_bones.hpp(222): 'const double &arma::Col<double>::fixed<0x02>::operator ()(const arma::uword) const'
          while trying to match the argument list '(int)'

**Comment by rcurtin** [comment]
Bad news for this one -- it's an MSVC compiler bug.  See yesterday's issue #421.  If you do write a workaround, please let me know so I can point other people towards it.

**Comment by theSundayProgrammer** [comment]
Thanks. I guess the error in
double Radical::DoRadical2D(const mat& matX)
{
 .....
    matJacobi(0, 0) = cosTheta;
 ...
 }
is the same. The workaround for this is to use
matJacobi.at(0,0) = cosTheta
