### ISSUE TITLE
Avoid inclusion of windows.h in timers.hpp or other mlpack headers

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#425]
This ticket comes out of #422.

Right now, on Windows, the header `<windows.h>` is included inside of `src/mlpack/core/util/timers.hpp` for the use of the `timeval` struct.  Because of the huge overhead that `windows.h` incurs when it is included, this can slow down compilation a fair amount (which is already slow because we are using complex template functionality of C++).

We can reduce this overhead significantly by refactoring `timers.hpp` and `timers.cpp` such that the `timeval` struct is not necessary in `timers.hpp` and instead used entirely within `timers.cpp`.  This should be a relatively easy refactoring job for someone who would like to make a first contribution to the library.

Thanks to theSundayProgrammer for pointing this issue out.

**Comment by abhinavagarwal07** [comment]
I think ```sys/time.h``` is used for ```timeval``` struct

**Comment by rcurtin** [comment]
That's not true on Windows: http://stackoverflow.com/questions/25615571/how-to-use-sys-time-h-in-window

**Comment by stereomatchingkiss** [comment]
Maybe I am off topic, is it possible to use std::chrono to replace timeval struct?I think it will be easier to port, and more flexible.

**Comment by rcurtin** [comment]
Yeah, we use C++11 now, so `std::chrono` is definitely a possible solution.  I've opened #498, a logical continuation of this ticket.
