### ISSUE TITLE
Linking against libc++ instead of the GNU libstdc++ on OSX.

### ISSUE THREAD

**Issue by zoq** [mlpack/mlpack#426]
Since we are using C++11 features we link against libstdc++ when using clang. libstdc++ is tried-and-tested, but it is a dead end on OSX that results in some problems like:

`error: no template named 'forward' in namespace 'std';`

Due to Apple not upgrading past GCC 4.2 for license reasons, Apple switched the standard library, so clang++ started to link against libc++ rather than libstdc++. The good news is that libc++ is specifically designed so that we can use it in the same process as libstdc++.

**Comment by zoq** [comment]
Patched in #8aa3abb00d.

@saketkc This should also fix the homebrew science build error. If you like we can create a patch against mlpack 1.0.12.

**Comment by saketkc** [comment]
Thanks, @zoq. I will update it.

**Comment by rcurtin** [comment]
Issue appears fixed, so I'm closing it.  If I shouldn't do that, then it can be reopened. :)
