### ISSUE TITLE
Is there a bug?

### ISSUE THREAD

**Issue by Ambier** [mlpack/mlpack#445]
Hi ,I readed the source code in mlpack,and find a place ,i think maybe it is a bug.
In file ,dtree.cpp ,in 43 line.
end specify the end point in datset ,but end(data.n_cols) ,it's wrong ,end(data.n_rows)

**Comment by Ambier** [comment]
Sorry,dataset is transport

**Comment by rcurtin** [comment]
Hi there, you are right that it is not a bug.  If you find any problems in the future, though, please feel free to open a new issue.
