### ISSUE TITLE
No C++11 compiler available!

### ISSUE THREAD

**Issue by talentjingjing** [mlpack/mlpack#447]
my GCC vision is 4.4.when cmake,it says "No C++11 compiler available!"

**Comment by rcurtin** [comment]
Hello there,

Your compiler is too old.  The minimum version of gcc required is 4.6.  If you upgrade your compiler, you should have no problem.

Thanks,

Ryan

**Comment by bdecato** [comment]
Hello,

Hopefully this is an easily fixed problem.  I am installing mlpack on my University cluster, and got the following error during the build:

>decato@hpc-login3 in build$ cmake ../
>-- The C compiler identification is GNU 4.4.7
>-- The CXX compiler identification is GNU 4.4.7
>-- Check for working C compiler: /usr/bin/cc
>-- Check for working C compiler: /usr/bin/cc -- works
>-- Detecting C compiler ABI info
>-- Detecting C compiler ABI info - done
>-- Check for working CXX compiler: /usr/bin/c++
>-- Check for working CXX compiler: /usr/bin/c++ -- works
>-- Detecting CXX compiler ABI info
>-- Detecting CXX compiler ABI info - done
>-- Checking for C++11 compiler
>-- Checking for C++11 compiler - unavailable
>CMake Error at CMakeLists.txt:8 (message):
>  No C++11 compiler available!

This doesn't make sense to me, because my default gcc compiler is C++11 ready:

>decato@hpc-login3 in build$ which gcc
>/usr/usc/gnu/gcc/4.8.1/bin/gcc

Any advice on what to check or previous experience is much appreciated, thank you!!

**Comment by saketkc** [comment]
@bdecato  It seems to be still picking `4.4.7`. 

```
The CXX compiler identification is GNU 4.4.7
```

Try:
```
export CC=/usr/usc/gnu/gcc/4.8.1/bin/gcc
export CXX=/usr/usc/gnu/gcc/4.8.1/bin/g++
```

**Comment by bdecato** [comment]
Problem solved, thanks!!
