### ISSUE TITLE
[Proposal]Add a function to visualize the results of sparse_autoencoder

### ISSUE THREAD

**Issue by stereomatchingkiss** [mlpack/mlpack#452]
If the users can see the result of encoder matrix, they will be easier to debug, I would like to write a function to visualize result of training.If mlpack already have this function, please close this proposal

1 : I suggest an api as following(base on shark)

template<typename InputType>
exportFiltersToPGMGrid(std::string const &fileName, arma::Mat<InputType> const &input, 
size_t width, size_t height);

Is this api good enough?

2 : which module it should belongs to?
ann?
method/sparseAutoencoder?
mlpack::data?
or others?

3 : do mlpack have any function to do the bilinear interpolation?

4 : add one more function to SparseAutoencoder

//return the encoder matrix(w1) of SparseAutoencoder
arma::Mat encoderMatrix() const;

If you agree on this suggestion, I will try to contribute a function to visualize the results of the encoderMatrix(W1 of the parameters, no bias)

**Comment by stereomatchingkiss** [comment]
The function already finished, if you need it and decided where should I placed it, please give me a reply.

Example : 

//.....after training
arma::Mat encoderMatrix = parameters.submat(0, 0, hiddenSize - 1, VisibleSize - 1);
exportFiltersToPGMGrid("encoder_result.pgm", encoderMatrix.t(), 28, 28);

**Comment by rcurtin** [comment]
I thought about it for a bit... I think this functionality may already exist (mostly).  The `data::Save()` function will save to PGM or PPM using Armadillo's support.  So, if you added a `Parameters()` accessor to `SparseAutoencoder`, maybe this would work:

```
SparseAutoencoder sa(...);
data::Save("encoder_result.pgm", sa.Parameters());
```

Does that do basically the same thing?

**Comment by stereomatchingkiss** [comment]
I think this cannot work, the function from armadillo will save the parameters directly, but to visualize the training results, you need to do some processing on the encoder matrix. For more details, you can refer to following page

http://deeplearning.stanford.edu/wiki/index.php/Visualizing_a_Trained_Autoencoder

**Comment by rcurtin** [comment]
Hm, so I'm hesitant to include the bilinear interpolation code, since (a) other toolkits could do it faster/better (i.e. save the PGM in the low resolution, then use ImageMagick command-line tools to make it larger for viewing) and (b) this type of visualization is going to be primarily useful for the case of autoencoders applied to images, which is not the only application of autoencoders.

What I do think could be useful though, is this:

 * Access to the `parameters` member of `SparseAutoencoder`.
 * A function which could, for a given hidden unit (or for all hidden units), return the input that maximally activates the hidden unit.  (I think part of your pastebin snippet does this.)  So basically I could do something like this:

```
SparseAutoencoder sa(...);

// Get the input that maximally activates hidden unit 0, storing the result in maximalInput.
arma::mat maximalInput; // Or should that be arma::vec...?
sa.MaximalInput(0 /* for hidden unit 0 */, maximalInput);
```

Then, if it was an image, you could call `maximalInput.reshape()` to set the size of the input correctly, then you could do bilinear interpolation and/or write it to a file and postprocess from there.

What do you think?  This is just a proposal here; I'd like to find a way to use the code you've written, especially if it's useful for you, but I want to figure out the way that it can be maximally useful across all use cases without adding too much complexity to the API.

**Comment by rcurtin** [comment]
(My comments here are only specific to the `SparseAutoencoder` code Siddharth wrote, in `src/mlpack/methods/sparse_autoencoder`; I don't know if zoq thinks this could be useful for the larger ANN code, which I think eventually `SparseAutoencoder` should be refactored to fit inside of.  For now we can just work with `SparseAutoencoder`, and figure out a potential merge later down the road, if that ends up working.)

**Comment by stereomatchingkiss** [comment]
>Then, if it was an image, you could call maximalInput.reshape() to set the size of the input correctly, >then you could do bilinear interpolation and/or write it to a file and postprocess from there.

Looks nice for me:). But I have a question

    sa.MaximalInput(0 /* for hidden unit 0 */, maximalInput);

why not just pass in the maximalInput?

    sa.MaximalInput(maximalInput);
    maximalInput.save(fileName, arma::pgm_binary);

**Comment by stereomatchingkiss** [comment]
>I think eventually SparseAutoencoder should be refactored to fit inside of

This remind me, there are other types of autoencoder, like transforming autoencoder, tied autoencoder, and maybe there will be more families of autoencoder pop out, and they could be sparse too. Maybe we should factor out the sparse constraint as another policy? That is, provide an Autoencoder class which allowed to add the sparsity as constraint, then this autoencoder will become SparseAutoencoder.

By the way, any interesting to implement those autoencoder?

**Comment by rcurtin** [comment]
> why not just pass in the maximalInput?

Correct me if I've misunderstood---there is a maximal input for each hidden unit in the autoencoder.  So if your autoencoder has 40 hidden units, then that's 40 different maximal inputs that you want.  So you could get each of them by calling `MaximalInput()` with the indices 0 to 39.  Alternately, if the input type is a vector type (`arma:;vec` or `arma::sp_vec` or something like that), then it would be easy to create a `MaximalInputs()` function instead that returned each maximal input in a column of the given matrix.  If you want to implement one of those, either works.

> This remind me, there are other types of autoencoder, like transforming autoencoder, tied autoencoder, maybe there will be more families of autoencoder pop out in the futures, and they could be sparse too. Maybe we should factor out the sparse constraint as another policy? That is, provide an Autoencoder class which allowed to add the sparsity as constraint, then this autoencoder will become SparseAutoencoder. If the sparsity is added, the tied autoencoder will become tied sparse autoencoder and so on.
> 
> How should we factored out that sparse constraint is a problem.
> 
> By the way, any interesting to implement other autoencoder?I would like to start from tied autoencoder first after SparseAutoencoder finished the refactor

Yeah, definitely I think more autoencoders is interesting, but I still think we should find a way to merge the codebase with the ANN code.  I haven't put sufficient thought into how to do that, though.  I think another one of the issues or pull requests you've opened has an idea for how to integrate the two.  Once the two were integrated, it would probably be a lot simpler to design arbitrary types of autoencoders.

**Comment by stereomatchingkiss** [comment]
> So if your autoencoder has 40 hidden units, then that's 40 different maximal inputs that you want.

 You are correct and this should be easy to code. But in the actual cases, I think the users(like) would more interesting on visualize the whole images rather than visualize a single maximal input. I think one api "MaximalInput(maximalInput)" should be enough for this case

**Comment by rcurtin** [comment]
Sounds good.  If you write the function and a test for it, and open a PR, I'll merge it in.

**Comment by stereomatchingkiss** [comment]
When I start to implement it, I find out make it as a global function maybe a better choice, because other families of autoencoders can use the same logic to visualize the training results.
   
    //api of SparseAutoencoder, get the w1 of sa
    const arma::mat w1() const; 

    //global api,generate the maximalInput
    MaximalInput(sa.w1().t(), maximalInput);

**Comment by rcurtin** [comment]
Let's put it in `methods/sparse_autoencoder` for now; it can be moved later.  The idea of a global function sounds good, but please consider naming `w1()` something more descriptive, like `Parameters()` (since the internal member is named `parameters`).

Why do you transpose in the input to `MaximalInput()`?  If that could be avoided, the function could be a little bit faster (possibly).

**Comment by stereomatchingkiss** [comment]
>Why do you transpose in the input to MaximalInput()? If that could be avoided, the function could be a little bit faster (possibly).

Fixed, have no idea how to write meaningful unit tests for this function, I visualize the results generated by the functions directly. However, I will create a pull request first, we can discuss about it at there

**Comment by rcurtin** [comment]
With #465 merged, I think this is done now.
