### ISSUE TITLE
Can not load csv file on windows

### ISSUE THREAD

**Issue by stereomatchingkiss** [mlpack/mlpack#467]
When I try to load a csv file as following, 

    0 1 2 3
    4 5 6 7

it always complain 

>Unable to detect type of 'softmax_data.txt'; incorrect extension?

Codes : 

    arma::mat trainData;
    data::Load("train.csv", trainData, true);

After checking, I bet that the csv file on windows(edit by notepad++) do not fit the load type of armadillo.
The load type return by

    arma::diskio::guess_file_type(stream) 

is 0.Maybe this is a bug of armadillo?

**Comment by rcurtin** [comment]
I think this is the same as #468, so if a fix happens there, we can close this issue too.
