### ISSUE TITLE
MaxVarianceNewCluster wrong distance to cluster mean

### ISSUE THREAD

**Issue by mikemodanoxxx** [mlpack/mlpack#469]
Hi there,

I think the MaxVarianceNewCluster template has an error in the computation of the distance between the mean of the maximum variance cluster and a data point (lines 73-74):
```
    double distance = arma::as_scalar(
          arma::var(data.col(i) - centroids.col(maxVarCluster)));
```

The distance here is the variance of the difference vectors and not the distance between the vectors. I think it should be
```
    double distance = metric::SquaredEuclideanDistance::Evaluate(
        data.col(i), centroids.col(maxVarCluster));
```
instead.

**Comment by rcurtin** [comment]
Thanks for pointing this out.  It looks like I found this some months ago and committed a fix to the master branch in 3bb8380; if you update to git master or apply that patch to your own code, that should fix the issue.
