### ISSUE TITLE
HMM simple example

### ISSUE THREAD

**Issue by davudadiguezel** [mlpack/mlpack#470]
Hello,
I am trying to use your library to build a labeled gmm-hmm-model, but I have trouble getting started. Have you some simple examples somewhere? I only found your tutorials, that don't really explain issues like:
How can I prepare an "already-trained" hmm?
How can I connect labels with emissions/observations?
How does a label-file/model-file/observation-file look like?

Greetings,
Davud

**Comment by rcurtin** [comment]
Hi Davud,

You are right that there is no HMM tutorial.  I'd like to write one at some point, but I haven't had the time.  If you are using the command-line interface, you have four programs available to you: `hmm_generate`, `hmm_loglik`, `hmm_train`, and `hmm_viterbi`.  You can use `--help` with each of these programs to get some information on what they do and how to use them.  Another place you could look, if you are writing C++ (which I think you may need to do for what you're trying to do) is in the tests: the file `src/mlpack/tests/hmm_test.cpp` may be helpful, for example.  The Doxygen documentation for the `HMM` class could also be useful: http://mlpack.org/docs/mlpack-git/doxygen.php?doc=classmlpack_1_1hmm_1_1HMM.html#details

> How can I prepare an "already-trained" hmm?

In C++, assuming you have the transition matrix and emission distribution information, you can set the transition matrix with `HMM::Transition()` (i.e. `hmm.Transition() = myTransitionMatrix`), and then you can set the emission distributions individually.  You mentioned using GMM-HMMs, so if you call `hmm.Emission(0)` you get back a `GMM` object, which will have weights, means, and variances that you can set individually; see http://mlpack.org/docs/mlpack-git/doxygen.php?doc=classmlpack_1_1gmm_1_1GMM.html#details for more information.

If you are trying to use the command-line, there isn't any support for that, so you would have to manually write the model file by hand... (more on that in a moment)

> How can I connect labels with emissions/observations?

I don't know what you mean.  If you use `hmm_train`, you pass in a sequence of observations with `--input_file` and their corresponding labels to `--labels_file`.  If you use C++, the API documentation should make this clear.

> How does a label-file/model-file/observation-file look like?

For label and observation files, mlpack supports many input file types, but the simplest will just be csv; one observation/label per line.  See mlpack.org/docs/mlpack-git/doxygen.php?doc=namespacemlpack_1_1data.html#ac3dd73bcdb8c2d990a3bb1aafe65af23 for more information.

For model files, boost::serialization is used, which currently can output models in xml, binary, or text (depending on the filename suffix you use).

I hope this is helpful.  Let me know if I can clarify anything.

Thanks,

Ryan

**Comment by davudadiguezel** [comment]
Hi Ryan,
thanks for the answer! What I still don't get is how the programm knows how the observations and the labels correspond. For example, if I have a labelfile that looks like:
Label_A
Label_B
Label_C
and an observation file like:
1  1  3
4  2  1
7  6  1
2  3  1
Will the program just correspond the first observation to label_A, the second to B and so on or can I somehow tell it how to correspond the observations to the labels? Can I create an observation file like:
Label_A  1  1  3
Label_A  4  2  1
Label_C  7  6  1
Label_B  2  3  1
or something similar? Or am I completely on the wrong track?
Thanks for the help,
Davud

**Comment by davudadiguezel** [comment]
Hi agian,
I figured out, that the labels have to be numbers and no words, right? and the labels and observations are indeed corresponding by order? I also managed to use hmm_train with some little test files and train a discrete hmm.

Now for the gmm hmm I will have to create a script that 
loads an observation sequence
creates a gmm
and than trains a hmm with that, right?

With the discrete hmm I experienced a dimension limit. Will there be a limit on gmm hmm, too? At the moment, my observations have 27 dimensions. Is this a problem?
Greetings,
Davud

**Comment by rcurtin** [comment]
Hi Davud,

You're right, the labels have to be numbers.  At some time in the future, it may be possible to change this, but for now, all mlpack data has to be numeric.  The labels should be from 0 to (n_classes - 1).

For the GMM HMM, if you're using the `hmm_train` program, you can load the observation sequence with the `-i` option (for the data) and the `-l` option for the labels.  You can specify that GMMs should be used with the options `-t gmm` and `-g $n` where `$n` is the number of Gaussians you want in each mixture.  The number of states in the model can be specified with the `-n` option.  The program will then train a GMM HMM with the given parameters, and you can save the generated HMM to a file with the `-o` option (i.e. `-o the_best_hmm_ever_created.xml`).

Once that's done, you can then use the other programs to perform various functionality with the trained HMM:

 - `hmm_generate` can generate sequences of emissions (and hidden states) randomly from a given HMM.
 - `hmm_viterbi` can evaluate the most likely sequence of hidden states given some observations and an HMM.
 - `hmm_loglik` can evaluate the log-likelihood of a sequence having a given set of hidden states for a given HMM.

You could also use `hmm_train` again to train with additional observations (use the `-m` option).

I hope this is helpful; let me know if I can clarify anything.

Can you tell me more about the dimension limit you experienced with the discrete HMM?  There should be no dimension limit (well, technically the dimension limit will be something like 18 quintillion, but I doubt that your data is that large...).  27-dimensional observations should not be an issue at all.

**Comment by davudadiguezel** [comment]
Hi Ryan,
thanks again for the fast answer.

I tried to do a little test run of hmm_train with 2 dim observation file. The error message was this:
[FATAL] Error in training sequence 0: only one-dimensional discrete observations allowed for discrete HMMs!
I entered the command like this:
$ ./hmm_train --type discrete -i test.csv -o test.txt  -l labels.csv -n 3
test.csv had 2 dimensions. Only a hand full numbers. I changed it to one dim and it worked like a charm. So I didn't mind any more. If you need any further information to reproduce, let me know. 
Thanks for the help, 
Davud

**Comment by rcurtin** [comment]
Ah, sorry, you're right.  I forgot about that restriction.  At the moment the `DiscreteDistribution` class only works with one-dimensional observations.  Realistically you can just transform your discrete observations to one dimension without any change in the model... if you have two dimensions that each take values between 0 and 9, then you could have one dimension that takes values between 00 and 99 (just concatenate the two dimensions).  This will give you the same HMM in the end.

It'd be possible to extend support for the discrete distribution to multiple dimensions more directly, but that hasn't been done at this time.

Anyway, you shouldn't have the problem with Gaussian or GMM HMMs.

**Comment by davudadiguezel** [comment]
Alright! I think this issue can be closed. Thanks for the help and for your work in this library!

**Comment by rcurtin** [comment]
Sure, I'm happy to help out.  Please feel free to open more issues if you need.  I'd like to write tutorials for the HMM and GMM functionality at some point, but time is always short...
