### ISSUE TITLE
CMake Windows 'No C++11 compiler available'

### ISSUE THREAD

**Issue by theSundayProgrammer** [mlpack/mlpack#475]
I get an error while using CMake (listed below).  The CMake GUI starts off by showing a combo-box listing Visual C++ compiler. But when it comes to the configuring it generates the said error. I am not familiar with CMake. 

------------------------------------------------------
Checking for C++11 compiler
Checking for C++11 compiler - unavailable
CMake Error at CMakeLists.txt:8 (message):
  No C++11 compiler available!

**Comment by theSundayProgrammer** [comment]
This is an issue with GUI. The command line works. Sorry for the inconvenience.

**Comment by rcurtin** [comment]
Unfortunately I'm not too experienced with the Windows CMake GUI (I've only used it a few times), so I don't think I can help any further there.  Probably the version of Visual Studio it's trying to use is incorrect, or something like that.
