### ISSUE TITLE
Temporary matrix (neighborPtr) being improperly deleted in neighbor_search_impl.hpp

### ISSUE THREAD

**Issue by lpsavalhais** [mlpack/mlpack#478]
File neighbor_search_impl.hpp
on method:
void NeighborSearch<SortPolicy, MetricType, MatType, TreeType, TraversalType>::
Search(const MatType& querySet,
       const size_t k,
       arma::Mat<size_t>& neighbors,
       arma::mat& distances)

At line 461:
---> delete neighborPtr; 

But in this case, when treeOwner is false, the matrix neighborPtr is not allocated with "new".

**Comment by rcurtin** [comment]
Nice catch!  Thanks so much for pointing this out.
