### ISSUE TITLE
Use profiling information during compilation

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#48]
**Reported by rcurtin on 15 Aug 40301853 01:20 UTC**
This should be a relatively simple task to set up (once the blocking bugs are resolved).

Using the testing framework set up in #18, tell the compiler to use profiling information to optimize FASTLIB.

We should see some speed gains from this.

Migrated-From: http://trac.research.cc.gatech.edu/fastlab/ticket/20

**Comment by yashsharan** [comment]
Is this issue this open?If yes ,I would like to work on this.Thanks

**Comment by rcurtin** [comment]
The issue has not been closed so it is not done.  You are free to look into it.

**Comment by Shandilya21** [comment]
Is this issue is still open or closed? If open I would like to work on this.
