### ISSUE TITLE
hmm dimension problem with zeros in first row

### ISSUE THREAD

**Issue by davudadiguezel** [mlpack/mlpack#480]
Hi,
when I run hmm_train or _viterbi on my observations the hmm program mistakes zero cells in the first row for empty cells. In consequence the program assumes there are less dimensions then there actually are.
Is this behaviour on purpose and can I avoid it without manipulating the first row of every obrservation file?
Greetings
Davud

**Comment by rcurtin** [comment]
Hi,

What do you mean by 'zero cells'?  Can you post an example file that causes the issue?

**Comment by davudadiguezel** [comment]
Hi,
I mean something like this. With zero as value in a cell.
[observationPKM.csv.txt](https://github.com/mlpack/mlpack/files/42471/observationPKM.csv.txt)
or something like
3 2 54 2 34 0 0 0 0 0 0 
as first row. The columns with the zero will be ignored.

**Comment by rcurtin** [comment]
Your CSV is malformed; take a look at the first line:

```
0.019098,0.053043,0,-1.179118,-0.040147,-0.728931,0,1.218595,0,-0.661137,0.104394,-0.564637,0,1.301586,0;420.082458;19.137304;-1885.803711;-0.420706;0.403104;-0.361714;0.727789;0.000000;0.000000;0.000000;0.000000;0.000000;0.000000;0.000000
```

The zeros are separated by semicolons, not commas.  Change it to commas, and you shouldn't have any problems loading the full 29 dimensions.

**Comment by davudadiguezel** [comment]
Thanks for the hint. Didn't notice the semicolons since I always opened the file in Calc.
Greetings
