### ISSUE TITLE
hmm_viterbi output

### ISSUE THREAD

**Issue by davudadiguezel** [mlpack/mlpack#484]
Hi again,
I have just a little question. The output of hmm_viterbi goes to a .csv file, but everything goes to just one row. When I opened it with calc it tells me, that the row has to many cells and not all data has been opened. So is there an easy way to change the output into more handy format. For example the labels file looks like this:
0
0
3
2
1
3
...
So I basicly want to know where to put a "\n" to get some newlines in the output.
Greetings
Davud

**Comment by rcurtin** [comment]
You're right, that makes sense to save things as a single column, not a single row.  I made a change in  5aaf0e4 so you can update your code and rebuild, or you can modify your existing file with this quick command: `cat output.csv | tr ' ' '\n'`.  Thanks for pointing this out!

**Comment by davudadiguezel** [comment]
Thanks, again! Always nice to work with you.
