### ISSUE TITLE
Build problem: DSO missing

### ISSUE THREAD

**Issue by cmmp** [mlpack/mlpack#490]
Hi,

I'm using Gentoo and I'm trying to build mlpack from source. I have reference blas and lapack installed, but I'm getting an error when building.

cmake output:

```
cassio@darkstar ~/tools/mlpack-1.0.12/build $ cmake -D ARMADILLO_INCLUDE_DIR=../../armadillo-6.200.4/include/ -D ARMADILLO_LIBRARY=../../armadillo-6.200.4/libarmadillo.so ../
-- ARMA_USE_WRAPPER is not defined, so all dependencies of Armadillo must be manually linked.
-- Using ATLAS for BLAS: /usr/lib64/libcblas.so
-- Using standard LAPACK: /usr/lib64/liblapack.so
-- Armadillo libraries: /usr/lib64/libcblas.so;/usr/lib64/liblapack.so
CMake Warning at CMakeLists.txt:75 (message):
  Armadillo configuration file
  (/home/cassio/tools/armadillo-6.200.4/include;/usr/include/armadillo_bits/config.hpp)
  does not exist!


-- Boost version: 1.56.0
-- Found the following Boost libraries:
--   program_options
--   unit_test_framework
--   random
-- Could NOT find Subversion (missing:  Subversion_SVN_EXECUTABLE) 
CMake Warning (dev) at src/mlpack/CMakeLists.txt:78 (add_custom_target):
  Policy CMP0037 is not set: Target names should not be reserved and should
  match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The target name "test" is reserved or not valid for certain CMake features,
  such as generator expressions, and may result in undefined behavior.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at CMakeLists.txt:292 (message):
  txt2man not found; man pages will not be generated.


-- Configuring done
-- Generating done
-- Build files have been written to: /home/cassio/tools/mlpack-1.0.12/build
```

make output:

```
[  0%] Built target mlpack_headers
[ 24%] Built target mlpack
[ 25%] Linking CXX executable ../../../../bin/cf
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/cf.dir/cf_main.cpp.o: undefined reference to symbol 'dnrm2_'
/usr/lib64/libblas.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/mlpack/methods/cf/CMakeFiles/cf.dir/build.make:101: recipe for target 'bin/cf' failed
make[2]: *** [bin/cf] Error 1
CMakeFiles/Makefile2:764: recipe for target 'src/mlpack/methods/cf/CMakeFiles/cf.dir/all' failed
make[1]: *** [src/mlpack/methods/cf/CMakeFiles/cf.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

From some research I did, this is probably a linking error related to the order the libraries are defined in the Makefile. But I'm not sure how to solve this considering cmake.

If there is any more information I can provide please tell me.

Thanks.

**Comment by rcurtin** [comment]
Hi there,

Use `ARMADILLO_INCLUDE_DIR=/home/cassio/tools/armadillo-6.200.4/tmp/include/` and I think your problem will be fixed.

The reason for this is that Armadillo, when built, creates a file 'config.hpp' which has various settings like whether or not the libarmadillo.so wrapper is created or used, whether or not to use ARPACK for sparse eigendecomposition, things like this.  But when this file is created, it (along with the rest of the headers) are put in `tmp/include/` as a staging step, then `tmp/include/` will be installed to `/usr/local/include/` or wherever you install to.

(Side note: on old versions of Armadillo, this directory used to be `build_tmp/include/`.  I think that's Armadillo 3 and earlier...)

In this case the warning given by CMake is the hint here:

```
CMake Warning at CMakeLists.txt:75 (message):
  Armadillo configuration file
  (/home/cassio/tools/armadillo-6.200.4/include;/usr/include/armadillo_bits/config.hpp)
  does not exist!
```

I wonder if that should be a fatal error instead...?

**Comment by cmmp** [comment]
Perfect. Thanks for the fast reply.

Indeed that solved the problem.

I had to manually build armadillo because the version available from stable Gentoo is older than what mlpack needs. I didn't make install it so it wouldn't conflict with the older gentoo provided version.

A fatal error would be better indeed. Also, I tried the github version and if I'm not mistaken I didn't even see that warning when trying to build (same linking error too).

Thanks again,
Cássio

**Comment by rcurtin** [comment]
Added a fatal error if config.hpp is not found in cec4ac4.  So hopefully that should help people with future similar issues.

With a bit more digging, I'm not sure why config.hpp doesn't exist in your situation, because it seems like Armadillo usually ships with a pre-configured config.hpp in include/armadillo_bits/.  Maybe this was not the case for 6.200.4...?

**Comment by cmmp** [comment]
I don't know. I have config.hpp on that location though:

```
cassio@darkstar ~/tools/armadillo-6.200.4/include/armadillo_bits $ ls -lh config.hpp
-rw-r--r-- 1 cassio cassio 7.2K Nov 10 02:42 config.hpp
```
