### ISSUE TITLE
When i try to install mlpack on my system, I'm getting a configuration error. Here is the log

### ISSUE THREAD

**Issue by vamshikumarkurva** [mlpack/mlpack#500]
[log.txt](https://github.com/mlpack/mlpack/files/91618/log.txt)

**Comment by rcurtin** [comment]
Hi, did you mean to close this?  The log shows you don't have boost serialization installed.  If you install that package, it should fix your issue.

**Comment by vamshikumarkurva** [comment]
Yes. I installed boost libraries from apt-get repository and compiled the mlpack successfully.
