### ISSUE TITLE
CMake issue with mlpack on Ubuntu

### ISSUE THREAD

**Issue by Fractally** [mlpack/mlpack#507]
Hey guys,

I am using the cmake gui to configure cmake. I have compiled Armadillo to use with mlpack. Armadillo found the following (cmake output): 

> MKL_FOUND = YES
> ACMLMP_FOUND = NO
> ACML_FOUND = NO
> OpenBLAS_FOUND = YES
> ATLAS_FOUND = NO
> BLAS_FOUND = YES
> LAPACK_FOUND = YES

When I ran cmake in my mlpack build directory, I get the following error:
> ARMA_USE_WRAPPER is not defined, so all dependencies of Armadillo must be manually linked.
Using MKL for LAPACK/BLAS: /usr/lib/liblapack.so;/opt/intel/mkl/lib/intel64/libmkl_intel_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;/opt/intel/mkl/lib/intel64/libmkl_rt.so;/opt/intel/lib/intel64/libiomp5.so;/opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
> CMake Error at CMake/FindArmadillo.cmake:196 (message):
  Cannot find LAPACK library, but ARMA_USE_LAPACK is set.  Try specifying
  LAPACK libraries manually by setting the LAPACK_LIBRARY variable.
Call Stack (most recent call first):
  CMakeLists.txt:113 (find_package)

I have tried to add the following entry to the mlpack cmake (with no luck): 
> LAPACK_LIBRARY = /usr/lib/liblapack.so

I have noticed that the field mkl_lapack_LIBRARY is empty in cmake. I also tried adding the path /usr/lib/liblapack.so to it with no luck. Any ideas? 

Thanks!

**Comment by rcurtin** [comment]
Hi there,

I think that I have fixed this in a7a05d8; the issue was, essentially, a typo in the CMake configuration scripts.  But I don't have a system with working MKL to test on; can you update to the latest git master and see if that fixes your issue?

Thanks!

**Comment by Fractally** [comment]
Thanks for the reply. I downloaded the latest version from github and the issue seems to have been resolved. I could configure and generate using cmake. I have tried compiling, but now have a load of undefined references to mkl_lapack_xxx, mkl_blas_xxx and mkl_iss_xxx. I guess the linking with MKL is incorrect. Will have to investigate. Closing this issue.
