### ISSUE TITLE
which part of mlpack is to partition the data points to different buckets according to distance?

### ISSUE THREAD

**Issue by acgtun** [mlpack/mlpack#529]
Thank you for your great work. I read some source code of mlpack. I focused on LSH since LSH splits data points to different buckets and data points with short distance will be clustered to the same cluster. Could you tell me which part of code is doing this or which program in mlpack can give me this results.

Now I want to split a set of high dimensional data to different clusters, and the data points in the same cluster are near.

Thanks.

**Comment by rcurtin** [comment]
Hi Haifeng,

I'm not 100% sure what you mean.  If you are looking for the LSH code, you can find it here:
https://github.com/mlpack/mlpack/tree/master/src/mlpack/methods/lsh

I suppose maybe you could use LSH to hash your points into different buckets, and then extract the buckets themselves?

If you're looking for a different algorithm to do high-dimensional clustering, all I can suggest is possibly k-means; I think that's the only technique mlpack has implemented that would be useful in your case.

I hope this helps... please let me know if I can clarify anything.

**Comment by acgtun** [comment]
Hi, Ryan,

Thank you very much. Yesterday I read the code of lsh_search.hpp and lsh_main.hpp. Yes, I use LSH to split my data points to different buckets, then in each buckets, I will do using general clustering since my data set is too huge to run k-mean or hierarchical clustering, it's about billion of data points.

**Comment by rcurtin** [comment]
Yeah, I think maybe LSH is your best bet here if you don't want to write much C++ code.  It might be easiest to just modify the LSHSearch class to get the functionality that you need.

**Comment by acgtun** [comment]
Hi, Ryan, Thanks a lot.

**Comment by rcurtin** [comment]
Glad I could be helpful. :)  If you end up implementing a new algorithm, and are interested in contributing it back to mlpack, I'd be happy to look over it.

I think there is nothing more to do with this issue, so I'm going to go ahead and close it.

**Comment by acgtun** [comment]
Yeah, thanks.
