### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [mlpack/mlpack#533]
I would like to point out that an identifier like "[`__MLPACK_CORE_HPP`](https://github.com/mlpack/mlpack/blob/9f1d08a74204f566399dc6ebd4a3fadc9b278bbf/src/mlpack/core.hpp#L7 "Update candidate")" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by rcurtin** [comment]
Sure, you're welcome to submit a patch.

**Comment by rcurtin** [comment]
Actually this might be a good task for someone looking to get involved with mlpack... change all the header guards at the top of every file to remove the underscores.  So I'll set a few tags here and maybe someone will find it interesting. :)

**Comment by elfring** [comment]
Do any more source code places [need another look for affected identifiers](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by rcurtin** [comment]
I think that only the header guards are incorrect (and all of them are incorrect); I don't think underscores are used anywhere else inside of mlpack.  It would probably be worth checking, though.

**Comment by ibrahim5253** [comment]
Is this still open? Can I work on this?

**Comment by Falit** [comment]
I have updated the pull request ..the build worked this time.. waiting for the merge :)

**Comment by rcurtin** [comment]
@ibrahim5253: Falit has already sent a PR, so it probably doesn't make sense to duplicate his work on this ticket.

**Comment by rcurtin** [comment]
Fixed with #537.
