### ISSUE TITLE
Neural Network: RNN test  Internal Compiler Error on MSVC

### ISSUE THREAD

**Issue by theSundayProgrammer** [mlpack/mlpack#534]
This is a Microsoft bug. I hope there is a work around:

...\mlpack\src\mlpack\methods\ann\rnn_impl.hpp(302): fatal error C1001: An internal error has occurred in the compiler.
  (compiler file 'msc1.cpp', line 1421)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  Please choose the Technical Support command on the Visual C++
   Help menu, or open the Technical Support help file for more information
  ...\mlpack\src\mlpack\methods\ann\rnn_impl.hpp(283): note: while compiling class template member function 'void mlpack::ann::RNN<std::tuple<mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::RecurrentLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &,mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &>,mlpack::ann::BinaryClassificationLayer,mlpack::ann::RandomInitialization,mlpack::ann::MeanSquaredErrorFunction>::Gradient(const arma::mat &,const size_t,arma::mat &)'
  ...\mlpack\src\mlpack\core\optimizers\sgd\sgd_impl.hpp(88): note: see reference to function template instantiation 'void mlpack::ann::RNN<std::tuple<mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::RecurrentLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &,mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &>,mlpack::ann::BinaryClassificationLayer,mlpack::ann::RandomInitialization,mlpack::ann::MeanSquaredErrorFunction>::Gradient(const arma::mat &,const size_t,arma::mat &)' being compiled
  ...\mlpack\src\mlpack\core\optimizers\sgd\sgd_impl.hpp(33): note: while compiling class template member function 'double mlpack::optimization::SGD<mlpack::ann::RNN<std::tuple<mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::RecurrentLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &,mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &>,mlpack::ann::BinaryClassificationLayer,mlpack::ann::RandomInitialization,mlpack::ann::MeanSquaredErrorFunction>>::Optimize(arma::mat &)'
  ...\mlpack\src\mlpack\methods\ann\rnn_impl.hpp(168): note: see reference to function template instantiation 'double mlpack::optimization::SGD<mlpack::ann::RNN<std::tuple<mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::RecurrentLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &,mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &>,mlpack::ann::BinaryClassificationLayer,mlpack::ann::RandomInitialization,mlpack::ann::MeanSquaredErrorFunction>>::Optimize(arma::mat &)' being compiled
  ...\mlpack\src\mlpack\core\optimizers\sgd\sgd_impl.hpp(22): note: while compiling class template member function 'mlpack::optimization::SGD<mlpack::ann::RNN<std::tuple<mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::RecurrentLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &,mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &>,mlpack::ann::BinaryClassificationLayer,mlpack::ann::RandomInitialization,mlpack::ann::MeanSquaredErrorFunction>>::SGD(DecomposableFunctionType &,const double,const size_t,const double,const bool)'
          with
          [
              DecomposableFunctionType=mlpack::ann::RNN<std::tuple<mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::RecurrentLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &,mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &>,mlpack::ann::BinaryClassificationLayer,mlpack::ann::RandomInitialization,mlpack::ann::MeanSquaredErrorFunction>
          ]
  ...\mlpack\src\mlpack\tests\recurrent_network_test.cpp(108): note: see reference to function template instantiation 'mlpack::optimization::SGD<mlpack::ann::RNN<std::tuple<mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::RecurrentLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &,mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &>,mlpack::ann::BinaryClassificationLayer,mlpack::ann::RandomInitialization,mlpack::ann::MeanSquaredErrorFunction>>::SGD(DecomposableFunctionType &,const double,const size_t,const double,const bool)' being compiled
          with
          [
              DecomposableFunctionType=mlpack::ann::RNN<std::tuple<mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::RecurrentLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &,mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &>,mlpack::ann::BinaryClassificationLayer,mlpack::ann::RandomInitialization,mlpack::ann::MeanSquaredErrorFunction>
          ]
  ...\mlpack\src\mlpack\tests\recurrent_network_test.cpp(108): note: see reference to class template instantiation 'mlpack::optimization::SGD<mlpack::ann::RNN<std::tuple<mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::RecurrentLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &,mlpack::ann::LinearLayer<arma::mat,arma::mat> &,mlpack::ann::BaseLayer<mlpack::ann::LogisticFunction,arma::mat,arma::mat> &>,mlpack::ann::BinaryClassificationLayer,mlpack::ann::RandomInitialization,mlpack::ann::MeanSquaredErrorFunction>>' being compiled

**Comment by rcurtin** [comment]
Is this VS2015 or an earlier version?

**Comment by theSundayProgrammer** [comment]
VS2015

On Thu, Mar 3, 2016 at 12:13 AM, Ryan Curtin <notifications@github.com>
wrote:

> Is this VS2015 or an earlier version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mlpack/mlpack/issues/534#issuecomment-191233840>.
>



-- 
Joseph Chakravarti Mariadassou
http://thesundayprogrammer.com

**Comment by rcurtin** [comment]
:(
I don't know what to tell you on this one then.  If you find a workaround that doesn't change the flexibility of the code, we can include it, but finding workarounds for C1001s is usually a nightmare.  I hear the Intel compiler generally gives better results, but I haven't tried that myself...

**Comment by zoq** [comment]
I was wondering if the FFN or CNN class goes through without any errors?

**Comment by theSundayProgrammer** [comment]
FFN and CNN are fine.

On Thu, Mar 3, 2016 at 9:44 AM, Marcus Edel <notifications@github.com>
wrote:

> I was wondering if the FFN or CNN class goes through without any errors?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mlpack/mlpack/issues/534#issuecomment-191475911>.
>



-- 
Joseph Chakravarti Mariadassou
http://thesundayprogrammer.com

**Comment by zoq** [comment]
In this case, we should be able to find a workaround. I have to setup a windows machine first, I guess I can use your tutorial for that? Any updates to make things easier? Or maybe I can use the modified mlpack windows version that @rcurtin mentioned, I can't remember the name of the project.

**Comment by rcurtin** [comment]
https://github.com/vespucciproject

Maybe AppVeyor would be useful to use for testing here.
Sometimes workarounds for MSVC like this involve stuff like reordering data members and other bizarre things.  I have no idea what will work here, though.

**Comment by zoq** [comment]
I fixed the issue in f58aa3662eae235f74ed8fc6ef1e3446. I'm going to go ahead and close this issue then.
