### ISSUE TITLE
can't make in ubuntu 14.04

### ISSUE THREAD

**Issue by mrbeann** [mlpack/mlpack#539]
[ 89%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/sgd_test.cpp.o
[ 90%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/serialization.cpp.o
[ 91%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/serialization_test.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [src/mlpack/tests/CMakeFiles/mlpack_test.dir/serialization_test.cpp.o] Error 4
make[1]: *** [src/mlpack/tests/CMakeFiles/mlpack_test.dir/all] Error 2
make: *** [all] Error 2

I get error here every time,Is this a bug?
what should I do ?

**Comment by rcurtin** [comment]
I'm pretty certain you don't have enough RAM in your system to compile mlpack.  Maybe you can try a larger swap file?  Still, it will be very slow.  Either way, this isn't a bug in mlpack, it's unfortunately a problem with your setup, so there's nothing I can do to help. :(

**Comment by mrbeann** [comment]
Thank you,Actually that's the problem, I found it just after I made the issue(I just use a VM with 1G ram before), sorry to make trouble.



liujiacheng0810@163.com
 
From: Ryan Curtin
Date: 2016-03-02 21:11
To: mlpack/mlpack
CC: mrbeann
Subject: Re: [mlpack] can't make in ubuntu 14.04 (#539)
I'm pretty certain you don't have enough RAM in your system to compile mlpack. Maybe you can try a larger swap file? Still, it will be very slow. Either way, this isn't a bug in mlpack, it's unfortunately a problem with your setup, so there's nothing I can do to help. :(
