### ISSUE TITLE
Could we change the response type of ann from arma::mat to arma::Row<size_t>?

### ISSUE THREAD

**Issue by stereomatchingkiss** [mlpack/mlpack#541]
I think it is easier for users to specify their label if they are one dimension only, is it possible for us to change it from ama::mat to arma::Row?Thanks

**Comment by rcurtin** [comment]
What about situations where a user is not using a neural network for classification, but instead for something where real-valued outputs are expected?

I'm not sure what the exact code being referenced here is, I just wanted to point that out as a possibility.

**Comment by stereomatchingkiss** [comment]
>but instead for something where real-valued outputs are expected?

Maybe we could change it from 

arma::Row<size_t>

to?

arma::Row<double>

I am mention about the codes of ffn, ann and rnn,things like 

`void Predict(arma::mat& predictors, arma::mat& responses);`

Could we add an overloaded function, like

`void Predict(arma::mat& predictors, arma::Row<double>& responses);`

To the class?

**Comment by rcurtin** [comment]
Maybe the response type should be a function of the type of the output layer?  I am not sure how feasible this is, just tossing the idea out there.

**Comment by rcurtin** [comment]
Since all the layers support templated `InputDataType` and `OutputDataType` parameters now, I think that this is resolved.
