### ISSUE TITLE
Comiling error on fast_mks_model.cpp.o

### ISSUE THREAD

**Issue by tpBull** [mlpack/mlpack#545]
I have trouble compiling the mlpack, stuck at fast_mks_model.cpp.o.
The error log is:
[  2%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/fastmks/fastmks_model.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
src/mlpack/CMakeFiles/mlpack.dir/build.make:629: recipe for target 'src/mlpack/CMakeFiles/mlpack.dir/methods/fastmks/fastmks_model.cpp.o' failed
make[2]: *** [src/mlpack/CMakeFiles/mlpack.dir/methods/fastmks/fastmks_model.cpp.o] Error 4
CMakeFiles/Makefile2:152: recipe for target 'src/mlpack/CMakeFiles/mlpack.dir/all' failed
make[1]: *** [src/mlpack/CMakeFiles/mlpack.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

I have already install all the dependencies followed by the instructions. Can anyone help me out?

**Comment by rcurtin** [comment]
You need more RAM.

**Comment by rcurtin** [comment]
(See also #539)

**Comment by tpBull** [comment]
Having changed the ram size. And here coms another bug.

In file included from /home/bull/Desktop/Parallels Shared Folders/Home/Downloads/mlpack-2.0.1/src/mlpack/methods/adaboost/adaboost.hpp:185:0,
                 from /home/bull/Desktop/Parallels Shared Folders/Home/Downloads/mlpack-2.0.1/src/mlpack/methods/adaboost/adaboost_main.cpp:38:
/home/bull/Desktop/Parallels Shared Folders/Home/Downloads/mlpack-2.0.1/src/mlpack/methods/adaboost/adaboost_impl.hpp: In member function ‘void mlpack::adaboost::AdaBoost<WeakLearnerType, MatType>::Train(const MatType&, const arma::Row<long unsigned int>&, const WeakLearnerType&, size_t, double) [with WeakLearnerType = mlpack::perceptron::Perceptron<>; MatType = arma::Mat<double>; size_t = long unsigned int]’:
/home/bull/Desktop/Parallels Shared Folders/Home/Downloads/mlpack-2.0.1/src/mlpack/methods/adaboost/adaboost_impl.hpp:137:38: warning: ‘crt’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     if ((i > 0) && (std::abs(rt - crt) < tolerance))
                                      ^
Linking CXX executable ../../../../bin/mlpack_adaboost
../../../../lib/libmlpack.so.2.0: undefined reference to `wrapper_ilaenv_'
../../../../lib/libmlpack.so.2.0: undefined reference to `wrapper_dgelsd_'
../../../../lib/libmlpack.so.2.0: undefined reference to `wrapper_dgesvx_'
../../../../lib/libmlpack.so.2.0: undefined reference to `wrapper_dnrm2_'
collect2: error: ld returned 1 exit status

**Comment by rcurtin** [comment]
How did you install Armadillo?
Did you specify `ARMADILLO_INCLUDE_DIR` manually?

If you built Armadillo manually in, e.g., `/path/to/armadillo/`, then you must set `ARMADILLO_INCLUDE_DIR` to `/path/to/armadillo/tmp/include/` ***not*** `/path/to/armadillo/include/`.  Kind of a weird gotcha, but that's the way Armadillo is configured.  If you install Armadillo instead through your system's package manager, this should not be an issue.
