### ISSUE TITLE
Reduce (or fix) warnings when compiling with Visual Studio

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#554]
When mlpack is built with Visual Studio, there are tons and tons of warnings; for instance, see this output:
https://ci.appveyor.com/project/mlpack/mlpack

A snippet of warnings:

```
C:\projects\mlpack\src\mlpack\..\mlpack/core/dists/discrete_distribution.hpp(55): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\..\mlpack/core/dists/discrete_distribution.hpp(55): warning C4244: 'argument': conversion from 'const size_t' to 'const double', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\..\mlpack/core/dists/discrete_distribution.hpp(104): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\..\mlpack/core/dists/laplace_distribution.hpp(61): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\..\mlpack/core/dists/laplace_distribution.hpp(104): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\..\mlpack/core/dists/laplace_distribution.hpp(105): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\..\mlpack/core/dists/laplace_distribution.hpp(107): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\..\mlpack/core/dists/gaussian_distribution.hpp(47): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\..\mlpack/core/dists/gaussian_distribution.hpp(48): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\..\mlpack/core/dists/gaussian_distribution.hpp(49): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\..\mlpack/core/dists/gaussian_distribution.hpp(50): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\..\mlpack/core/dists/gaussian_distribution.hpp(185): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\core\dists\gaussian_distribution.cpp(102): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\core\dists\gaussian_distribution.cpp(110): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\core\dists\gaussian_distribution.cpp(162): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\core\dists\gaussian_distribution.cpp(163): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\core\dists\gaussian_distribution.cpp(181): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\core\dists\gaussian_distribution.cpp(182): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
c:\projects\mlpack\src\mlpack\core\data\load_arff_impl.hpp(47): warning C4129: '%': unrecognized character escape sequence [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\..\mlpack/core/math/random.hpp(37): warning C4267: 'argument': conversion from 'size_t' to 'const arma::arma_rng::seed_type', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\..\mlpack/core/dists/discrete_distribution.hpp(55): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\..\mlpack/core/dists/discrete_distribution.hpp(55): warning C4244: 'argument': conversion from 'const size_t' to 'const double', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
C:\projects\mlpack\src\mlpack\..\mlpack/core/dists/discrete_distribution.hpp(104): warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data [C:\projects\mlpack\build\src\mlpack\mlpack.vcxproj]
```

Most of these errors will be from the same patterns throughout the code, so we should do what we can to fix them where possible.  At least for the conversion of `size_t` to `arma::uword`, I _think_ that we should be able to guarantee that in general, `size_t` is an equivalent type to `arma::uword` (but maybe the compiler just isn't catching it), so we should be able to avoid making those casts explicit everywhere.

**Comment by cloudhan** [comment]
I inspect it in VS2015 and found
`warning C4267: 'argument': conversion from 'size_t' to 'const arma::uword', possible loss of data` is caused by `ARMA_64BIT_WORD` is no defined, which results in a `typedef u32 uword;` in file `include\armadillo_bits\typedef_elem.hpp`

To solve this type of warning, just uncomment the line with `#define ARMA_64BIT_WORD
` in the file `armadillo_bits\config.hpp`.

However, this will result in a 8 bytes `uword`, when casting to a `int`, which is 4 bytes by default, you still lose data in this procedure.

There will still be many other `possible loss of data` warning for some casting between unsigned integer and float point, but I don't think this type of data loss can be solved with only a few lines of code.

**Comment by rcurtin** [comment]
Ideally `uword` should be set to the same size as `size_t`. But you are saying that this does not happen on 64-bit versions of Windows? If so we can `#define ARMA_64BIT_WORD` in `src/mlpack/core/arma_extend/arma_extend.hpp`, but we should only do this on 64-bit Windows. On 32-bit Windows we should not set `ARMA_64BIT_WORD` though.

Does that seem like a reasonable solution?

If there are other unsafe casts in mlpack I am surprised that gcc or clang don't seem to be picking them up.

**Comment by cloudhan** [comment]
I think uncomment  `#define ARMA_USE_CXX11` instead should be a more reasonable solution.

reference: http://arma.sourceforge.net/docs.html#uword

    when using the new C++11 / C++14 standards, the default width is 64 bits on 64-bit platforms (as of Armadillo 5.000)

**Comment by rcurtin** [comment]
But it sounds like on Windows, `ARMA_USE_CXX11` must not be enabled because `ARMA_64BIT_WORD` is not enabled on Windows, causing the conversion warning emails.

**Comment by cloudhan** [comment]
hmm, on my local test, `conversion from 'size_t' to 'const arma::uword', possible loss of data` is eliminated when `ARMA_USE_CXX11` is enabled and `ARMA_64BIT_WORD` remain disabled by default. I think you'd better test it on appveyor?

**Comment by rcurtin** [comment]
Sorry, I think my last comment was actually unclear, so you can ignore it...

I don't know if your system is different than AppVeyor.  One easy way to test would be to open a PR, then AppVeyor will automatically build.

Another way to explicitly disable `ARMA_64BIT_WORD` is to define `ARMA_32BIT_WORD`.  I am pretty sure that in general, `ARMA_USE_CXX11` is not enabled when the compiler is Visual Studio though, because VS has incomplete C++11 support.

I don't think that we should enable `ARMA_USE_CXX11` support on Windows because it's been explicitly disabled by the Armadillo maintainer, and enabling it might cause problems for some parts of Armadillo (possibly including parts that are not used in mlpack now but may be used later).  Instead I think maybe we should define either `ARMA_64BIT_WORD` or `ARMA_32BIT_WORD` when on Windows, depending on the architecture.  That would probably accomplish the same result of fixing those warnings.
