### ISSUE TITLE
Optimizer transition: Adam, Adadelta

### ISSUE THREAD

**Issue by zoq** [mlpack/mlpack#555]
We recently decided to use the optimizer in core/optimizers for the network modules instead of writing special optimizer just for the network modules. However, we already implemented some methods that aren't available for the rest of mlpack like Adam, Adadelta and RMSprop (methods/ann/optimizer). Actually, that's not true, we reimplemented RMSprop in da1207a9e6407e835 and made the optimizer available for the rest of mlpack. It should be fairly easy to reimplement the other two methods as well.

**Comment by sshkhrnwbie** [comment]
I am new to mlpack and open-source in general and would like to work on this issue. I understand that you expect implementations of the Adam and Adadelta optimizers in core similar to the new implementation of RMSprop but what should be done with the optimizers in the ann module? 

Right now I have downloaded the papers and am trying to understand the optimizers. I will try to finish this as fast as I can.

**Comment by zoq** [comment]
You can basically use the RMSprop or the SGD optimizer in core/optimizers as a basis, to reimplement Adam and Adadelta. 

So, take a look at the RMSprop ann implementation  (ann/optimizer/rmsprop.hpp) and compre the implementation with the new RMSprop implementation in core/optimizers/rmsprop_impl.hpp. 

Once there is an Adam and Adadelta implementation in core/optimizers, I'll go and delete the ann/optimizer folder.


It would be great if you could start with one of the optimizers (Adam or Adadelta). Maybe someone likes to pick up the other optimizer, if not you are more than welcome to reimplement Adam and Adadelta.

**Comment by awhitesong** [comment]
@zoq I'll take up Adadelta if not both.

**Comment by vasanthkalingeri** [comment]
Then I will be working on Adam first.

**Comment by anamariabs** [comment]
Hi! I implemented the transition on Adam. If you could have a look, that would be great. https://github.com/anamariabs/mlpack/tree/master/src/mlpack/core/optimizers/adam

**Comment by zoq** [comment]
Looks good to me, please open a pull request, that also includes the test.

**Comment by vasanthkalingeri** [comment]
@zoq, unfortunately, I worked on the same code, but I have added the tests as well here #560

**Comment by anamariabs** [comment]
#561

**Comment by zoq** [comment]
Okay, maybe we can avoid such situations in the future by assigning the task to the first person who says, I like to work on the issue.

I take a quick look at the pull requests and maybe we can find a way to include both requests.

```adam_impl.hpp``` is basically the same so I like to use that from @vasanthkalingeri, but the test is kind of different, @vasanthkalingeri created a new file instead of updating the old test. So I would use the test from @anamariabs, also @anamariabs added a CMakeLists.txt file to build the optimizer wich is great, so I would also use that. If you both agree, maybe you can update the pull request in that direction?

Since @sshkhrnwbie was the first who said he would like to work on the issue I assign the issue to him, Adadelta is still open. Sorry @awhitesong, but I guess that's the best way to avoid such situations.

**Comment by anamariabs** [comment]
I guess this is sort of my fault. I wanted to get familiar with the code, and all the tasks proposed on the mlpack gsoc site on the projects you mentor were sort of taken by someone else. So i just went along with one to find out if I can solve it and learn something in the process. Sure, it's fine by me to merge the pull requests. Also, if you could suggest me some different tasks, I'd like that. Thanks.

**Comment by vasanthkalingeri** [comment]
@zoq , that will be great to do from next time. I just finished implementing adadelta with tests here https://github.com/vasanthkalingeri/mlpack/tree/master/src/mlpack/core/optimizers/adadelta. I am trying to make a pull request for this that does not include Adam, will be sending a pull request shortly.

@anamariabs , it was a genuine communication gap so neither of us are to blame.

**Comment by awhitesong** [comment]
@zoq Sure :)

**Comment by MurtyShikhar** [comment]
@zoq I would like to work on Adadelta.

**Comment by zoq** [comment]
@anamariabs @vasanthkalingeri If you agree with my solution it would be great if you both could update your pull requests, if not it's fine, In this case, I'll go and work with the first pull request.

@MurtyShikhar It looks like @sshkhrnwbie delete his response to the issue, I'm not sure if this was a mistake. If he doesn't respond in the next two days I guess this issue is open again and you are free to work on this.

**Comment by vasanthkalingeri** [comment]
@zoq , I have updated the pull request to include only adam_impl.hpp, #568

**Comment by vasanthkalingeri** [comment]
@zoq Here is the pull request for AdaDelta #569 , I have added CMakeLists and modified the old test file.

**Comment by anamariabs** [comment]
@zoq I deleted adam_impl.hpp from my request #571
