### ISSUE TITLE
 ARMADILLO_INCLUDE_DIR-NOTFOUND/armadillo_bits/config.hpp not found!

### ISSUE THREAD

**Issue by ruch1** [mlpack/mlpack#558]
The C compiler identification is GNU 4.8.1
The CXX compiler identification is GNU 4.8.1
Check for working C compiler: C:/Program Files (x86)/CodeBlocks/MinGW/bin/gcc.exe
Check for working C compiler: C:/Program Files (x86)/CodeBlocks/MinGW/bin/gcc.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Program Files (x86)/CodeBlocks/MinGW/bin/g++.exe
Check for working CXX compiler: C:/Program Files (x86)/CodeBlocks/MinGW/bin/g++.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Checking for C++11 compiler
Checking for C++11 compiler - available
Looking for backtrace
Looking for backtrace - not found
Could NOT find Backtrace (missing:  Backtrace_LIBRARY Backtrace_INCLUDE_DIR) 
CMake Error at CMake/FindArmadillo.cmake:327 (message):
  ARMADILLO_INCLUDE_DIR-NOTFOUND/armadillo_bits/config.hpp not found! Cannot
  determine what to link against.
Call Stack (most recent call first):
  CMakeLists.txt:113 (find_package)

why is this happening?
I have installed armadillo separately .
I have seen one such issue but their backtrace tree was found..here is coming. not found

**Comment by ruch1** [comment]
can somebody guide me through the steps how to include mlpack to  my cpp code ?

**Comment by rcurtin** [comment]
Hi there,

I think your problem is that you have to specify `ARMADILLO_INCLUDE_DIR` and `ARMADILLO_LIBRARY` as options to CMake.  Try that and I think that should fix your problem.

**Comment by ruch1** [comment]
thank you .it worked for me
