### ISSUE TITLE
problem with boost root 

### ISSUE THREAD

**Issue by ruch1** [mlpack/mlpack#563]
Checking for C++11 compiler
Checking for C++11 compiler - available
Armadillo libraries: C:/Users/Hp pc/Desktop/soft/armadillo_build/libarmadillo.dll
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/FindBoost.cmake:1247 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.60.0

  Boost include path: C:/boost_1_60_0

  Could not find the following Boost libraries:

          boost_program_options
          boost_unit_test_framework
          boost_serialization

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:186 (find_package)

CMake Warning (dev) at src/mlpack/CMakeLists.txt:85 (add_custom_target):
  Policy CMP0037 is not set: Target names should not be reserved and should
  match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The target name "test" is reserved or not valid for certain CMake features,
  such as generator expressions, and may result in undefined behavior.
This warning is for project developers.  Use -Wno-dev to suppress it.

Configuring incomplete, errors occurred!
See also "C:/Users/Hp pc/Desktop/soft/mlpack mbuild/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Hp pc/Desktop/soft/mlpack mbuild/CMakeFiles/CMakeError.log".

i build file in c:\boost_1_60_0
i have tried everything  but it is not configuring

**Comment by zoq** [comment]
Have you tried to set ```BOOST_INCLUDEDIR``` and ```BOOST_LIBRARYDIR```? Something like:
```
-DBOOST_INCLUDEDIR:PATH="C:\boost_1_60_0\include" -DBOOST_LIBRARYDIR:PATH="C:\boost_1_60_0\lib"
```
Make sure that the folder contains all necessary libraries.

**Comment by rcurtin** [comment]
Also this depends on your Boost distribution but the include paths and library paths may actually be under `C:\boost_1_60_0\boost` not `C:\boost_1_60_0\`.

**Comment by ruch1** [comment]
I have tried all this . any other thing that might be wrong ?

**Comment by rcurtin** [comment]
If you say "I have tried all this" but haven't provided any output or detailed information on your system or what you have tried, it's very hard to help.  Since I have no log information or anything like this to go off of, the best I can do is link you to this wiki page: https://github.com/mlpack/mlpack/wiki/WindowsBuild

Maybe something that you find in there could be helpful.
