### ISSUE TITLE
AllkNNTest failing in 3 test cases

### ISSUE THREAD

**Issue by uzipaz** [mlpack/mlpack#573]
I recently installed mlpack and tried running some test programs from source such as allknn_test.cpp by running mlpack_test -t AllkNNTest and this the output I got:
Running 21 test cases...
mlpack_test: /home/ozair/programming/mlpack/src/mlpack/../mlpack/core/tree/rectangle_tree/rectangle_tree_impl.hpp:882: bool mlpack::tree::RectangleTree<MetricType, StatisticType, MatType, SplitType, DescentType>::ShrinkBoundForPoint(const vec&) [with MetricType = mlpack::metric::LMetric<2, true>; StatisticType = mlpack::neighbor::NeighborSearchStat<mlpack::neighbor::NearestNeighborSort>; MatType = arma::Mat<double>; SplitType = mlpack::tree::RStarTreeSplit; DescentType = mlpack::tree::RStarTreeDescentHeuristic; arma::vec = arma::Col<double>]: Assertion `false' failed.
unknown location(0): fatal error in "KNNModelTest": signal: SIGABRT (application abort requested)
/home/ozair/programming/mlpack/src/mlpack/tests/allknn_test.cpp(1027): last checkpoint
unknown location(0): fatal error in "KNNModelMonochromaticTest": std::runtime_error: Timer::Start(): timer 'tree_building' has already been started
/home/ozair/programming/mlpack/src/mlpack/tests/allknn_test.cpp(1027): last checkpoint
unknown location(0): fatal error in "NeighborPtrDeleteTest": std::runtime_error: Timer::Start(): timer 'tree_building' has already been started
/home/ozair/programming/mlpack/src/mlpack/tests/allknn_test.cpp(1115): last checkpoint

*** 3 failures detected in test suite "mlpackTest"

It seems that the test is failing on three test cases:
KNNModelTest
KNNModelMonochromaticTest
NeighborPtrDeleteTest

It seems like there is assertion failure at line 882 when allocating a RectangleTree object. Also, in source file allknn_test.cpp, in BOOST_AUTO_TEST_CASE(KNNModelMonochromaticTest), we are declaring an array of type KNNModel, at line 1052, while assigning a new kNNModel object at the highest index of the array, the code at the line references to models[0] instead of models[9], Hence, at the inner loop where the program is accessing the models array at i = 9, I think this will cause a memory exception because the object at this location was not assigned. But, I've yet to rebuild the program and test it out for myself yet.

Regards.

**Comment by rcurtin** [comment]
Can you tell me more about the system you are running this on?  Is it some exotic hardware or something?  I haven't seen this problem anywhere.

**Comment by uzipaz** [comment]
'exotic hardware' lol

I have an ASUS laptop that I bought in 2014. Specs are

-Computer-
Processor		: 4x Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz
Memory		: 5994MB (1514MB used)
Operating System		: Ubuntu 14.04.4 LTS
User Name		: ozair (Ozair Shafiq)
Date/Time		: Mon 14 Mar 2016 03:51:25 PM NDT
-Display-
Resolution		: 1366x768 pixels
OpenGL Renderer		: Unknown
X11 Vendor		: The X.Org Foundation
-Multimedia-
Audio Adapter		: HDA-Intel - HDA Intel PCH
-Input Devices-
 Lid Switch
 Sleep Button
 Power Button
 AT Translated Set 2 keyboard
 Video Bus
 Asus WMI hotkeys
 HDA Intel PCH Headphone
 HDA Intel PCH HDMI/DP,pcm		: 3=
 USB2.0 HD UVC WebCam
 ETPS/2 Elantech Touchpad
 SteelSeries Rival Gaming Mouse
 SteelSeries Rival Gaming Mouse
 SteelSeries Rival Gaming Mouse
-Printers-
No printers found
-SCSI Disks-
ATA HGST HTS725050A7
HL-DT-ST DVDRAM GUA0N

**Comment by rcurtin** [comment]
I cherry-picked a fix from @lozhnikov (f77416e) from #556.  Basically, my changes to the R tree changing `-DBL_MAX` to `std::numeric_limits<ElemType>::min()` was incorrect; I should have used `lowest()` instead.  This causes failures, but only sometimes, which is why the Travis build didn't catch it and why I didn't see this before now.
