### ISSUE TITLE
Low-rank constraint matrices in LRSDP

### ISSUE THREAD

**Issue by epatters** [mlpack/mlpack#578]
In many applications of LRSDP, the constraint matrices A have very low rank. In my case, they are rank 1. For the problem sizes that interest me, even forming all those matrices would exhaust my memory. Does mlpack have special support for low-rank matrices? (It doesn't look like it, but I'm experienced with neither Armadillo nor mlpack.)

**Comment by stephentu** [comment]
Hi,

This is related to #401. You're right, currently we only support general sparse and dense matrices, but have no way of handling say, A_i = aa^T efficiently. I'm hoping somebody picks up #401 as part of GSOC, but who knows. Your best bet right now would probably be to either handroll your own LRSDP, or make the appropriate edits to mlpack. Sorry that I don't have anything better to suggest ( I don't think there are any decent open source LRSDP libraries out there, surprisingly since so many people use it! )

**Comment by epatters** [comment]
Yes, it is surprising that there are so few LRSDP implementations out there.

I'd be willing to work on getting this into mlpack. I know my way around C++, though not mlpack specifically.

**Comment by stephentu** [comment]
Cool. I don't think it will be that hard to get it into LRSDP. I'd punt on supporting the IP solver for now (just throw a runtime exception if a user sets these generalize constraints and calls the IP solver). I think the easiest way to do it is provide a `LinearConstraint` callback which supports two operations: 1) evaluation of `Tr(A_i * UU^T)`, which takes as input `U` and returns a double, and 2) evaluation of `(Tr(A_i * UU^T) - b_i) A_i U`, which takes as input a `U` and `b_i` and returns (or say does `+=` to an input) an n x r matrix. This is needed for computing gradients .

**Comment by epatters** [comment]
Thanks for the pointers. I'll give it a shot.

**Comment by rcurtin** [comment]
@epatters: a contribution would be greatly appreciated; there's lots of cool stuff that could be done with the LRSDP code, but time has always prohibited that on my end.

Another thing to consider might be a refactoring of the `SDP` class; right now, you specify your objective matrix type as a template parameter, but then you can have arbitrary numbers of constraints represented by sparse or dense matrices.  But this approach doesn't scale to constraints that should be represented differently, like the `LinearConstraint` class that Stephen just suggested.

I haven't put much thought into this, but I think it would be really nice and make your problem easy to solve if a user could write something like:

```
// This SDP just has a sparse matrix constraint.
SDP<SparseMatrixConstraint> sdp;
// This SDP has both dense and linear constraints.
SDP<DenseMatrixConstraint, LinearConstraint> sdp2;
// This SDP has all three.
SDP<SparseMatrixConstraint, DenseMatrixConstraint, LinearConstraint> sdp3;
```

That could probably be accomplished through variadic templates, and then some nice functionality could be provided to set each constraint.  I haven't thought this through completely, this is just a comment made with maybe three minutes worth of thought.

Anyway, I'm happy to help out, so let me know if you have any questions.  My ideas above may or may not be applicable---don't feel obligated to take them as suggestions (maybe they don't even work, I don't know).

**Comment by epatters** [comment]
@rcurtin: Thanks for the suggestion. I've been thinking about how to most cleanly implement this feature.

The approach via variadic templates is interesting, but making that work would probably require some [template black magic](http://stackoverflow.com/questions/27941661). Now appetites for these things vary, but that's a bit much for me. Or maybe you had something else in mind?

What do you think about using either a traditional inheritence-based approach or `std::function`? There is some additional runtime overhead compared to templates, but it should be negligible compared to the linear algebra.

**Comment by epatters** [comment]
Upon further thought, I do think there is an important reason to handle classes of constraints differently, as in the template approach: the optimal order of the calculations depends on the type of the constraint. When computing `L = 2*S*R`, with dense constraints you want to sum `S` first then multiply `S*R` (as is done currently), while with rank-1 constraints you compute each `a a^T R` efficiently and then sum.

**Comment by stephentu** [comment]
@epatters: i definitely agree that the code you execute should depend on the type of constraint. however, I also agree that variadic templates is black magic, and I think it would be fine to check this information at runtime and branch.

**Comment by rcurtin** [comment]
For consistency I'd like to go with the templated approach (inheritance isn't used anywhere else in mlpack), so if you're okay with it I will refactor your code to use templates when it's done.

**Comment by rcurtin** [comment]
I'm going to go ahead and close this one for inactivity---it's been quite a while.  If you'd like to reopen it and continue working on it, feel free.
