### ISSUE TITLE
CMake commands are mixed uppercase and lower case

### ISSUE THREAD

**Issue by ajjl** [mlpack/mlpack#583]
CMake commands are sometimes given in upper and lower case. Previously uppercase commands had been required but now commands are case-insensitive and lowercase commands are preferred. Conversion to lowercase commands have been implemented in other open source projects such as ITK vxl and BRAINSTools, and is the preferred style for KDE.

KDE reference: 
https://community.kde.org/Policies/CMake_Coding_Style#Upper.2Flower_casing

**Comment by rcurtin** [comment]
I would agree with changing everything to lowercase.  If you'd like to submit a patch, I'm happy to incorporate it; otherwise, I'm going to leave it as an open issue for someone who's looking to get involved.

**Comment by ajjl** [comment]
Awesome, I'll put a patch set through ASAP!

**Comment by ajjl** [comment]
See pull request #584
