### ISSUE TITLE
Perceptron documentation

### ISSUE THREAD

**Issue by armanschwarz** [mlpack/mlpack#594]
I am hugely impressed with the scope and quality of this package. Having said that, I am struggling to find documentation on how to perform, for example, perceptron training with mplack.

I have built the "perceptron" binary, which provides some information including an example for how to train a perceptron, giving the following example line;

perceptron -t training_data.csv -l training_labels.csv -m perceptron.csv

However, I do not see any documentation or examples for any of these csv files. What is the form of these files? More specifically, where is this information documented? I am less interested in a step-by-step guide on how to train a perceptron and more interested in where to find reliable documentation to do so.

**Comment by rcurtin** [comment]
Hi Arman,

Thanks for the kind words about mlpack.  But it sounds like maybe our documentation is not good enough.  Do you think that if I wrote a tutorial called "Data formats in mlpack" which detailed the types of input that mlpack will expect, this would clarify the issue?

As a quicker response to the problem at hand, `training_data.csv` should be a CSV with one point per row.  So the three-point dataset with the points (1, 0), (2, 2), and (-1, -1) would be

```
1, 0
2, 2
-1, -1
```

and then `training_labels.csv` should contain one label per line corresponding to each training point.  So if, e.g., the label of the first two points was 0 and the label of the second point was 1, then the `training_labels.csv` file should be

```
0
0
1
```

The last file will be an output file that saves the parameters of the perceptron.

It looks like you are using an old version of mlpack (1.0.12?).  I think maybe the documentation is a little clearer in the newest release (2.0.1), so I'd recommend upgrading.  Also, the formats that you can save the model in are expanded (you can save as xml, bin, or txt).

I hope this is helpful... let me know if I can clarify further.

**Comment by armanschwarz** [comment]
Hi rcurtin,

That was very helpful, yes. Obviously I'm a newcomer so it's hard for me to say with certainty whether this would be equally useful to others, but for what it's worth I would encourage you to add this to the documentation.

I have found myself depending heavily on the unit tests as a source of documentation, so any efforts to improve unit test coverage would also help me (and hopefully others) understand the nitty gritty a bit better.

Thanks again for the quick input.

**Comment by rcurtin** [comment]
Sure, sorry for the slow response; I was away last week.  I wrote some basic documentation earlier, and I'll polish it and commit it soon and let you know where to find this.

Nice profile picture, by the way. :)

**Comment by rcurtin** [comment]
Okay, I wrote up some documentation here that should be helpful:
http://www.mlpack.org/docs/mlpack-git/doxygen.php?doc=formatdoc.html

Please let me know if you think anything in there can be clarified.  Thanks!
