### ISSUE TITLE
Test programs failing on loading data from disk

### ISSUE THREAD

**Issue by uzipaz** [mlpack/mlpack#597]
I recently cloned the repository and tried to follow the build instructions given in README file and suggested by rcurtin to building with debug, profile = off, that will make the library execute faster for performance. I am compiling using the command 'cmake .. -DDEBUG=OFF -DPROFILE=OFF' and then installing by using 'sudo make install' in the build directory. Then, I run mlpack_test by ./mlpack_test -t FeedForwardNetworkTest and it fails. The error is

Running 3 test cases...
[FATAL] Cannot open file 'thyroid_train.csv'. 

unknown location(0): fatal error in "VanillaNetworkTest": std::runtime_error: fatal error; see Log::Fatal output
[FATAL] Cannot open file 'thyroid_train.csv'. 

unknown location(0): fatal error in "DropoutNetworkTest": std::runtime_error: fatal error; see Log::Fatal output
[FATAL] Cannot open file 'thyroid_train.csv'. 

unknown location(0): fatal error in "DropConnectNetworkTest": std::runtime_error: fatal error; see Log::Fatal output

*** 3 failures detected in test suite "mlpackTest"

I try running ./mlpack_test -t AllkNNTest and it fails aswell with a similar error.

Running 21 test cases...
/home/ozair/programming/mlpack/src/mlpack/tests/allknn_test.cpp(666): fatal error in "DualTreeVsNaive1": Cannot load test dataset test_data_3_1000.csv!
/home/ozair/programming/mlpack/src/mlpack/tests/allknn_test.cpp(700): fatal error in "DualTreeVsNaive2": Cannot load test dataset test_data_3_1000.csv!
/home/ozair/programming/mlpack/src/mlpack/tests/allknn_test.cpp(735): fatal error in "SingleTreeVsNaive": Cannot load test dataset test_data_3_1000.csv!
unknown location(0): fatal error in "DualCoverTreeTest": std::invalid_argument: requested value of k (5) is greater than the number of points in the reference set (0)
/home/ozair/programming/mlpack/src/mlpack/tests/allknn_test.cpp(787): last checkpoint
unknown location(0): fatal error in "DualBallTreeTest": std::invalid_argument: requested value of k (5) is greater than the number of points in the reference set (0)
/home/ozair/programming/mlpack/src/mlpack/tests/allknn_test.cpp(858): last checkpoint

*** 5 failures detected in test suite "mlpackTest"

I was very hesitant to make a topic about this here because I think its a problem on my end. But I've been trying to compile and build this using the instructions given and all the data-set files actually do exist in the build folder. I tried changing file permissions of the build folder using chmod command and that didn't work and I am not an expert in linux, hence I don't know what I am doing wrong.

I tried asking for solution for this on the IRC channel for a couple days now and with no response, hence, I am making the topic here.

Regards.

**Comment by zoq** [comment]
All datasets are in the build directory. So you need to start the test inside the build directory: ```bin/mlpack  -t FeedForwardNetworkTest``` instead of calling ```mlpack  -t FeedForwardNetworkTest```inside the test folder.

**Comment by uzipaz** [comment]
Quote from zoq
'All datasets are in the build directory. So you need to start the test inside the build directory'

that is exactly what I'm doing, I go to build/bin and run ./mlpack_test from there.

**Comment by zoq** [comment]
I know, but you should go to ```build```and in that location you call ```bin/./mlpack_test``` or ```bin/mlpack_test```. Note the bin in front of ```mlpack_test```.

**Comment by zoq** [comment]
So instead of:

```
cd build/bin
mlpack_test -t FeedForwardNetworkTest
```

you should use:

```
cd build/
bin/mlpack_test -t FeedForwardNetworkTest
```

Does this sound reasonable?

**Comment by uzipaz** [comment]
That sounds absolutely reasonable and makes complete sense. I had the impression that you need to be in the build/bin directory to run the programs and hence the programs failing to load data because they are not present in the same directory.

I am re-building the library right now and will let you know about the results but I think this certainly answers my question. Thank you for answering.

**Comment by uzipaz** [comment]
This certainly works... Thanks again for answering and being patient.... I really appreciate it...
