### ISSUE TITLE
possible usecases for data preprocessing tool

### ISSUE THREAD

**Issue by keon** [mlpack/mlpack#599]
I am on the designing stage of the dataset and experiment tools (explained in the wiki: https://github.com/mlpack/mlpack/wiki/SummerOfCodeIdeas#dataset-and-experimentation-tools)

I have a design draft, which I have submitted via GSoC, but I'd like to make the blueprint firm before getting into actual coding.

It would be a real help to know what you guys feel the most needed.
In order to find that out, I want to know possible usecases while preprocessing.
Most frequently used methods, alternative tools, and all the other information regarding it help.

Thank you,
Keon Woo Kim

**Comment by stereomatchingkiss** [comment]
Following are my personal opinions, just take it as reference.

>It would be a real help to know what you guys feel the most needed

1 : Split a dataset into a training and test set(#523 may give you some helps)
2 : Checking a dataset for loading problems and printing errors, the api/cli should be able to give users imputation strategies for missing variables, give warning to invalid, problematic values
3 : converting categorical features into binary features (or numeric features)

The command line tools I feel the most needed are
1 : mlpack_datatools_trans
2 : mlpack_datatools_stats
3 : mlpack_datatools_math
4 : mlpack_datatools_eval
5 : mlpack_datatools_io

About the mlpack_datatools_io, I am not sure it is a good idea to increase dependency of mlpack or not, it would be great if you could make them as optional for users. In short, the dependency would not affect the build process if the users do not need those features which rely on external libraries.

About the time-zone, which time-zone you want to support?How do users specify the format of the time-zone?Boost date_time may help you save some headaches.

>I want to know possible usecases while preprocessing.

By usual I do not check the validity of the data, just assume they are valid, I think I can't help you about this part. 

>Most frequently used methods, alternative tools, and all the other information regarding it help.

About the statistic part, armadillo and boost accumulators provide a lot of useful functions, sometimes I also use the function of opencv to do the statistic when I am doing computer vision tasks.

About the database manipulation, I always rely on Qt5, whatever, it is too big if your purpose is provide database manipulation only. 

I could help you do the test on windows platform(win8, vc2015 64bits)

**Comment by keonkim** [comment]
@stereomatchingkiss thanks for the comment! I really wanted something like the feedback you gave. You listed the five things you need in the command line tool, but that is every component I written in the proposal. So I was wondering if the numbering is ordered by the importance?

**Comment by rcurtin** [comment]
@stereomatchingkiss: can you explain what each of the programs do?  We should merge in #523 soon, sorry that I haven't gotten to that yet (it's on my list).

**Comment by rcurtin** [comment]
Ack, sorry, I think all this information is in the proposal.  I should have looked there first, sorry.

**Comment by stereomatchingkiss** [comment]
>So I was wondering if the numbering is ordered by the importance? 

Yes. 

>sorry that I haven't gotten to that yet (it's on my list).

Don't mind and thanks for your reply.

**Comment by keonkim** [comment]
@stereomatchingkiss and about the time-zone, I was referring to time transformation.
Users will be able to filter time with certain time gap(like time zone), seasonality, trending.
It could also involve changes in features, i guess, when users make transitions from time to seasonality.

**Comment by rcurtin** [comment]
There's no support in mlpack for time data, only continuous real-valued data, so any "time transformation" would probably need to be to/from `double` or `size_t` or something similar.  Can you explain more of what you had in mind?  I don't know what you mean by seasonality.  Thanks!

**Comment by keonkim** [comment]
@rcurtin Some people might be more interested in how a season might affect the result instead of continuous date and time. So in this case, I thought instead of making the feature numeric, splitting them into categories might produce a more accurate prediction.

**Comment by stereomatchingkiss** [comment]
> I thought instead of making the feature numeric, splitting them into categories might produce a more accurate prediction. Same goes for gap, and etc..

Do you mean you want to make the mlpack support format as following?

    33.33 44.666 winter 2014/05/06

If this is what you mean, maybe let the users able to transform the winter and 2014/05/06 into number could solve the problem.

**Comment by rcurtin** [comment]
I guess since the project is done, we can close this ticket. :)
