### ISSUE TITLE
Why the compiler will crash when building serialization_test.cpp

### ISSUE THREAD

**Issue by shvikeray-gelo** [mlpack/mlpack#602]
My English is not good, I hope you can understand what I mean.

mlpack version 2.0.1

I in raspbian(Rapsberry PI operating system, adapted from the debian) build this project, hardware is raspberry pi 2(armhf), use of GCC and g + + version is 4.9.2

I just use the "make" command to build all the target, all the other were successfully built, Including mlpack_test other source files when I use command "make -k".

But only one, the serialization_test.cpp will cause the compiler to crash, and no report why.

**Comment by shvikeray-gelo** [comment]
The last output is:
[ 53%] Built target mlpack_allkrann
[ 53%] Built target mlpack_softmax_regression
[ 54%] Built target mlpack_sparse_coding
[ 54%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/serialization_test.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
src/mlpack/tests/CMakeFiles/mlpack_test.dir/build.make:1227: recipe for target 'src/mlpack/tests/CMakeFiles/mlpack_test.dir/serialization_test.cpp.o' failed
make[2]: *** [src/mlpack/tests/CMakeFiles/mlpack_test.dir/serialization_test.cpp.o] Error 4
make[2]: Target 'src/mlpack/tests/CMakeFiles/mlpack_test.dir/build' not remade because of errors.
CMakeFiles/Makefile2:2472: recipe for target 'src/mlpack/tests/CMakeFiles/mlpack_test.dir/all' failed
make[1]: *** [src/mlpack/tests/CMakeFiles/mlpack_test.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
make: Target 'default_target' not remade because of errors.

**Comment by zoq** [comment]
I'm pretty certain you don't have enough RAM in your system to compile mlpack. Maybe you can try a larger swap file?

**Comment by shvikeray-gelo** [comment]
1G RAM not enough?

**Comment by rcurtin** [comment]
Sometimes 1GB of RAM is not enough to compile mlpack; you may want to try more.  Possibly there are compiler options that could be used to decrease the RAM footprint if necessary?  I am not familiar enough with g++ to know those options.

**Comment by shvikeray-gelo** [comment]
If so, the RAM of raspberry PI can't be increased,unlike personal computer.
For zoq proposa: "Maybe you can try a larger swap file?", how to do that on debian

**Comment by cloudhan** [comment]
@shvikeray-gelo You may need an enough large external storage device and then try this for [Swap Partition](https://wiki.archlinux.org/index.php/swap#Swap_partition) or a [Swap File](https://wiki.archlinux.org/index.php/swap#Remove_swap_file) on an existing partition

**Comment by zoq** [comment]
Probably, another option  is to modify the CMake file and to remove all parts you don't need. Like if you have no intention to run the serialization test comment/remove out ```serialization_test.cpp``` in ```src/mlpack/tests/CMakeLists.txt```. I build mlpack on an rpi with 256MB RAM some time ago, so there is definitely a version that should work.

**Comment by shvikeray-gelo** [comment]
serialization_test.cpp can be remove? 
I ware use 'swapon -s' command, at normal, /etc/swap used is 0, but it's used all(102396B) when compile serialization_test.cpp

**Comment by zoq** [comment]
Take a look at the src/mlpack/tests/CMakeLists.txt file and comment the ```serialization_test.cpp``` use '#'. Maybe afterwards it will complain about FastMKS, but let's see.

**Comment by shvikeray-gelo** [comment]
thanks a lot, I make a 1G swap partition, and compile angin success, although the link still have some problems

**Comment by zoq** [comment]
If you tell us more, about your problems, we can probably help. I guess, I can also setup my own rpi to reproduce your problems, if that helps.

**Comment by rcurtin** [comment]
I think the linker issue is now in #606 so I'm going to go ahead close this one.
