### ISSUE TITLE
segmentation fault in using sgd while increasing number of function

### ISSUE THREAD

**Issue by ranjan1990** [mlpack/mlpack#607]
For my research purpose I was using sgd to fit a function.
There is no  segmentation fault if   number of function  is less( about 10).
But when I tried  with number of function >=15 it got segmentation fault.
I thought may be memory allocation of visitationOrder  array has created a problem but it is not the case.
But I think the error is different. please see the debug error.I am unable to figure out the problem 
(https://github.com/ranjan1990/mlpack_optimization/blob/master/error)

Please let know whether it is bug in sgd  or am I making some mistake using it ?
https://github.com/ranjan1990/mlpack_optimization/blob/master/find_equ.cpp

*I have compiled mlpack with option  "-D DEBUG=ON -D PROFILE=OFF -D ARMA_EXTRA_DEBUG=ON "

**Comment by zoq** [comment]
So without knowing the dimension of your data. My first guess is, that your data has less rows as 20.

The optimizer calls the ```Evaluation``` function for every sample (i = 0; i < NumFunctions), so if you write ```arma::mat Ri=data.row(i);```in your ```Evaluation``` function you should make sure, that you have enough samples.

**Comment by ranjan1990** [comment]
My data has   >20 rows.
Here is my dataset. https://github.com/ranjan1990/mlpack_optimization/blob/master/traj.txt
Any  help will be appreciated!

**Comment by rcurtin** [comment]
Hi Ranjan,

Your data has 20 rows on disk, but Armadillo stores matrices in a column-major form, so these matrices are transposed at load time.  See http://mlpack.org/docs/mlpack-git/doxygen.php?doc=matrices.html for more information (a more detailed tutorial is coming too but I have not pushed it yet).

Try using `.col()` where you are using `.row()` and this will probably help fix the issue.

Thanks,

Ryan

**Comment by ranjan1990** [comment]
Hello Ryan,
Previously I was using mat.load()  now changed it to  mlpack::data::Load()  and also now using row( ) to .col( ). Still I am getting same error. (segmentation fault).
Here is the code.  https://github.com/ranjan1990/mlpack_optimization/blob/master/find_equ.cpp .
Data : https://github.com/ranjan1990/mlpack_optimization/blob/master/traj.txt

**Comment by ranjan1990** [comment]
So here is the fault !  MyFunction::Gradient()  is not defined properly  in  https://github.com/ranjan1990/mlpack_optimization/blob/master/find_equ.cpp . 
The 'i' parameter to the Gradient() method indicates which of the functions, the gradient is being taken for.
