### ISSUE TITLE
SGD performing optimization on same order of visitation at each rotation

### ISSUE THREAD

**Issue by uzipaz** [mlpack/mlpack#608]
In the main loop inside SGD::Optimize function,

At the beginning of a rotation on training Samples and if shuffle is enabled, we call arma::shuffle on visitationOrder vector to randomize the order in which the SGD will revisit the samples next time.

Since, arma::shuffle relies on a random number generator, whenever it is called, the armadillo library does not seem to reset/change the seed value for the rng, hence, I think it would be a good idea to reset the seed value before calling arma::shuffle on visitationOrder at line 83 by calling arma::arma_rng::set_seed_random() or another appropriate function.

Regards.

**Comment by rcurtin** [comment]
Hi there Ozair,

It's actually a bad idea for debugging and reproducibility to set the seed.  Setting the seed (preferably by calling `math::RandomSeed()`, but the Armadillo function you mentioned works too) should be done at a higher level than SGD.  If the seed is set inside of the SGD class, then if I have a bug that I am trying to track down, it becomes very hard if I can't easily set the seed to one specific value (or leave it as the default).  If anything it may be worth adding a bit to the documentation or one of the tutorials (probably a tutorial is the better place) noting that it might be useful to set the random seed at a higher level.
