### ISSUE TITLE
Asking for Armadillo 4.***, 6.*** installed

### ISSUE THREAD

**Issue by judelove** [mlpack/mlpack#609]
Hello all, I do not know how to go about this. I have Armadillo 6.7***. When I am running cmake for ml-pack it throws an error that implies that it needs a minimum version of 4.* for Armadillo and it got 6.***.

However it goes on to say that it can not find Armadillo. I have attached a screen shot.
![armadillo](https://cloud.githubusercontent.com/assets/4677601/14427183/478c923a-ffeb-11e5-89d2-0fec09e0a5d6.PNG)

**Comment by judelove** [comment]
Sorry, I resolved this. My C++ skills are way too low.

**Comment by rcurtin** [comment]
Hey Jude,

Glad to hear you got it worked out.  I think the issue was that you need to compile Armadillo after you download it.  If you have more problems in the future, feel free to open issues and we will try to help! :)

Thanks,
Ryan
