### ISSUE TITLE
Windows 10 installation version

### ISSUE THREAD

**Issue by jaelim** [mlpack/mlpack#613]
Hello, Is anyone using MLpack on Windows 10? I have tried to install it with mingw, cmake tool without success. I used VC2015 IDE, but I guess that's not probably recommended? Any suggestion would be appreciated.

**Comment by zoq** [comment]
Hello, it is definitely possible to build mlpack on Windows using mingw or VC2015. We configured appveyor to build mlpack for every commit using VC2015. The process is quite simple, so if you prefer to build mlpack using VC2015 I can guide you through the process. If you prefer mingw I guess @thirdwing is the expert, and could provide some tips.

**Comment by rcurtin** [comment]
This file might be useful:
https://github.com/mlpack/mlpack/blob/master/.appveyor.yml
I think maybe you can extract the instructions from there and adapt it to your environment; maybe it will take a bit of translation and work, but it should be possible.

**Comment by jaelim** [comment]
@zoq Hi, Thanks for replying back. I don't know if you recommend using CMake 3.5.1 to build a project, then open the project solution in VC2015 to complete the process. I got stuck at generating a project. Please find below screenshot files:
![capture1](https://cloud.githubusercontent.com/assets/7217547/14472468/262ea2dc-00a8-11e6-9121-70c4ba8e073e.PNG)
![capture2](https://cloud.githubusercontent.com/assets/7217547/14472469/262f8a76-00a8-11e6-92f6-f41b4686cf78.PNG)

**Comment by jaelim** [comment]
@zoq if you don't mind, could you please walk me through steps in VC2015?

**Comment by stereomatchingkiss** [comment]
I wrote down the steps at [here](http://qtandopencv.blogspot.my/2015/09/deep-learning-04-compile-mlpack-1012-on.html), this compilation setup still work for me.

However, the information are outdated already, the compilation process could become easier. 

1 : Some of the dependencies should be able to omit, like libxml
2 : OpenBLAS and lapack, maybe you could download prebuild version(ps : I am not sure this could work)

If you find out better way, or part of the dependencies could be removed, some libs could use the prebuild version, please write it down on this post, thanks.

**Comment by zoq** [comment]
As @rcurtin already pointed out you could take a look at the ```.appveyor.yml``` file, but I can guide you through the process if you like. Maybe you are able to join us on irc ```#mlpack```?

There are basically two ways, to get all the dependencies to build mlpack. The first way, is to manually build everything, that's what @stereomatchingkiss describes in his blog post. The second way, is to use NuGet, which is something like apt-get for debian. It makes things a lot easier and less time consuming.

e.g. by running the following commands you get all the necessary dependencies including OpenBLAS:

```
nuget install boost
nuget install boost_unit_test_framework-vc140
nuget install boost_program_options-vc140
nuget install boost_random-vc140
nuget install boost_serialization-vc140
nuget install boost_math_c99-vc140
nuget install OpenBLAS
```

**Comment by jaelim** [comment]
@zoq @stereomatchingkiss Hi, Did you use 32 or 64 bit version VC15? I got this error mentioning of finding no C++11 compiler. I was able to build with mingw64, but there's no VC project solution to work with. I guess it's because I used non-VC compiler so no VC solution file.

![capture3](https://cloud.githubusercontent.com/assets/7217547/14476130/d3c6414a-00ba-11e6-8a5c-e8659589bd83.PNG)

**Comment by jaelim** [comment]
@zoq @stereomatchingkiss I noticed that in CXX11.cmake you had this defined:

macro(check_for_cxx11_compiler _VAR)
    message(STATUS "Checking for C++11 compiler")
    set(${_VAR})
    if((MSVC AND (MSVC10 OR MSVC11 OR MSVC12)) OR
       (CMAKE_COMPILER_IS_GNUCXX AND NOT ${CMAKE_CXX_COMPILER_VERSION} VERSION_LESS 4.6) OR
       (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND NOT ${CMAKE_CXX_COMPILER_VERSION} VERSION_LESS 3.1) OR
       (CMAKE_CXX_COMPILER_ID STREQUAL "Intel" AND NOT ${CMAKE_CXX_COMPILER_VERSION} VERSION_LESS 12.0))
        set(${_VAR} 1)
        message(STATUS "Checking for C++11 compiler - available")
    else()
        message(STATUS "Checking for C++11 compiler - unavailable")
    endif()
endmacro()

So according to this I should use a version MSVC12 or less?

**Comment by jaelim** [comment]
@zoq what is **Backtrace_LIBRARY Backtrace_INCLUDE_DIR**? And this means **"MSVC" will no longer be dereferenced when the policy is set to NEW**?

![capture4](https://cloud.githubusercontent.com/assets/7217547/14476395/6563bb90-00bc-11e6-8342-516d62d6eea8.PNG)

**Comment by jaelim** [comment]
@zoq this is bugging issue in cmake_gui. when you link mlpack with armadillo, you have to type in lib filename as follow, or otherwise you can't just set it to dir_path. otherwise it fails to generate build project solution.

![capture5](https://cloud.githubusercontent.com/assets/7217547/14477023/334b7a68-00c0-11e6-9eed-1739ad1f35ea.PNG)

**Comment by zoq** [comment]
Okay, good to know that! I don't use the cmake gui, but the gui should also work just fine.

MSVC10 OR MSVC11 OR MSVC12 are the versions that comes with C++11 features. But, I'm almost sure, you need at least MSVC14 which is the latest VC++ version to build the master branch.

So, here is the problem, we changed the CXX11.cmake file some days ago to support MSVC14. Here is the updated file: https://github.com/mlpack/mlpack/blob/master/CMake/CXX11.cmake

Also, don't worry about Backtrace, it's only supported on linux, just ignore the warning.

**Comment by jaelim** [comment]
@zoq btw what is **appveyor.yml** and does it work like a script you can execute in command prompt?

**Comment by jaelim** [comment]
@stereomatchingkiss Hi, Thanks for your help. I was wondering what are these in your instruction?

`set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
add_definitions(-DARMA_64BIT_WORD)
add_definitions(-DNOMINMAX) `

**Comment by stereomatchingkiss** [comment]
set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)

If I remember correctly, If you do not specify this option
You would not see the lib compile by visual c++, you can find the details at [here](https://cmake.org/cmake/help/v3.4/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html). This option should be able to omit if you are building static lib(better link to MD or MDd since many prebuild binary are doing that).

    add_definitions(-DARMA_64BIT_WORD)

Make armadillo able to accept more data, else it may running out of memory even your ram is big enough.

    add_definitions(-DNOMINMAX)

visual c++ define min max macro which has the same name as the min max of std::min and std::max, this macro asked the compiler do not use these macro(macro do not respect scope)

**Comment by jaelim** [comment]
@zoq can you able to help me decipher the meaning of all these errors?
![capture6](https://cloud.githubusercontent.com/assets/7217547/14478304/6a97d2ce-00c9-11e6-93bf-0bdc5fc34556.PNG)

**Comment by jaelim** [comment]
@zoq apparently there's no mlpack.lib in here
![capture7](https://cloud.githubusercontent.com/assets/7217547/14478349/d459f444-00c9-11e6-9119-401402a74d6f.PNG)

**Comment by zoq** [comment]
Visual Studio doesn't support unsigned indices as featured in OpenMP 3.0. It's fixed in https://github.com/mlpack/mlpack/commit/50629c1d76780dc0c37c24b1dedb7794f4aa5447#diff-03121247ee7da9d71da250e352f01aa8

So, I guess once you changed ```src/mlpack/methods/det/dt_utils.cpp``` accordingly it should solve a bunch of the other errors.

**Comment by jaelim** [comment]
@zoq sorry more errors reported...
![capture8](https://cloud.githubusercontent.com/assets/7217547/14478737/4e5e0d2c-00cd-11e6-9a4c-9ec55e8420b9.PNG)
![capture9](https://cloud.githubusercontent.com/assets/7217547/14478738/4e5e6a2e-00cd-11e6-8798-0e165152c972.PNG)
![capture10](https://cloud.githubusercontent.com/assets/7217547/14478739/4e5ff81c-00cd-11e6-8232-b1cf04911033.PNG)

**Comment by zoq** [comment]
Can you change the Visual Studio build configuration to Release?

**Comment by jaelim** [comment]
@zoq Hi, I think it worked by switching to Release configuration. I still don't understand why the errors were produced in Debug config.

**Comment by jaelim** [comment]
@stereomatchingkiss Hi, Thanks again for explaining. I'm using CMake 3.5.1 Gui software for my installation. When you add these 3 extra instructions in the CMakeLists.txt, will it be detected automatically in CMake_gui as you configure and generate?
![capture8](https://cloud.githubusercontent.com/assets/7217547/14500033/4f2547f6-0155-11e6-8162-bdbd1bcb6939.PNG)

**Comment by jaelim** [comment]
@stereomatchingkiss apparently, I can't open CMakeLists.txt in CMake gui tool. I believe you need to define them manually. Are these instructions assigned with boolean values? For instance, you make this TRUE
`set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)`
and as well as enable these by assigning TRUE values:
```
add_definitions(-DARMA_64BIT_WORD)
add_definitions(-DNOMINMAX)
```

**Comment by stereomatchingkiss** [comment]
>I still don't understand why the errors were produced in Debug config.

Maybe you are mixing the libraries of debug build and release build, in the world of c++, debug and release library do not guarantee to provide same symbol and ABI, if you mixed them together, the best case is you can not compile your program, the worst case is it may generate subtle bugs from time to time, these bugs could make you scratch your head seriously if you do not know what was happen.

On windows, things become even more complicated(arggghhhh), your debug/release library need to link to correct runtime library, do not mixed them together if you do not want to spend several days, weeks even months to find out those evil bugs(I know a company confuse by those bugs more than 10 years, ridiculous?But this is true case).

Open your vc project, go to properties-.>C/C++->Code generation->Runtime library

There will be four types of library to choose

MD, MDd, MT, MTd

The library will small d means debug, without it means release, "M" mean multithread(old vc provide single thread lib, I think it is obsolete now)."D" mean dynamic, "T" mean static. If it is dynamic, that means you will need the dll come with vc if you want your program able to run, if it is static, that means you would not need them(but I haven't tried on this one, please correct me if I am wrong).

    set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)

I think you are right, the meaning of ON is same as true. You would not need this if you compile the armadillo as static lib. Go to properties->General->Configuration type->set it to static library



    add_definitions(-DARMA_64BIT_WORD)
    add_definitions(-DNOMINMAX)

This is same as adding macro definition in the project

ex : 
      #define NOMINMAX

**Comment by jaelim** [comment]
@zoq I dont' know if this is of a serious concern, but my anti-virus program detected this particular file as a threat. Should it be a security vulnerability if I put it in the exclusion list?
![capture](https://cloud.githubusercontent.com/assets/7217547/14503714/1e6b5fe0-0166-11e6-8140-02a3ee353e52.PNG)

**Comment by rcurtin** [comment]
Personally I would report that file as a false positive or submit it to another website like VirusTotal to get a better analysis.  If you compiled that program by hand, and it was not otherwise modified, there shouldn't be any reason for it to be malicious.

**Comment by jaelim** [comment]
@stereomatchingkiss Hi, thanks again. So if I have these configured like it's fine?
![capture](https://cloud.githubusercontent.com/assets/7217547/14504311/1ca9964c-0169-11e6-9141-7f4c43e60bd5.PNG)
And the properties-.>C/C++->Code generation->Runtime library, this is what I see
![capture](https://cloud.githubusercontent.com/assets/7217547/14504363/5e5dcd2e-0169-11e6-90e5-8c6c00558774.PNG)
But in properties->General->Configuration type
![capture](https://cloud.githubusercontent.com/assets/7217547/14504410/90603212-0169-11e6-9d85-09ddbabd9bfc.PNG)
Its config type is static. So is this why the reason for errors?

**Comment by stereomatchingkiss** [comment]
>Hi, thanks again. So if I have these configured like it's fine?

I think this is nothing wrong, configuration types could be dll or lib on different libraries,but the setting of runtime library must be the same on different libraries.In short, if the runtime library of armadillo is MD, than other's library should be MD too.

The other things you need to care about is the compatibility of the vc compiler do not give any promise of backward compatibility, if you build the libraries by version A, than all of the libraries better build with version A. 

Even you do not follow the advices, your program may still compile and run, but you may bug by some weird issues(alien values, crash and other undefined behavior)

**Comment by jaelim** [comment]
@stereomatchingkiss @zoq @rcurtin Thanks so much. You've been extremely helpful!

**Comment by darcyliu** [comment]
It is wonderful that if we can install mlpack using NuGet. 

    nuget install mlpack

It seems that 'armadillo' is not supported right now. I would like to help but I sorry that I am not working on Windows platform recently.

**Comment by zoq** [comment]
I agree, an mlpack nuget package would be great. I think once masterblaster is stable, and we have some kind of a windows machine, we can do that. We could create a nuget package for every release and probably even provide nightly builds.

> It seems that 'armadillo' is not supported right now. I would like to help but I sorry that I am not working on Windows platform recently.

There is an nuget armadillo package (https://www.nuget.org/packages/Armadillo/), but it doesn't use OpenBlas which would be at least in my opinion the better option.

**Comment by stereomatchingkiss** [comment]
>OpenBlas which would be at least in my opinion the better option.

I tried openBLAS and BLAS before, it is atleast three times faster on my laptop(Y410p).

**Comment by keonkim** [comment]
I uploaded the instructions on my [blog](http://keon.io/mlpack-on-windows.html)

**Comment by Kirizaki** [comment]
Did anyone check @keonkim solution?

**Comment by zoq** [comment]
Yes, you might have to adjust some parameters, some packages have been updated since then. e.g. boost version, the latest version is now 1.61 instead of 1.60.

**Comment by Kirizaki** [comment]
I've already verified @keonkim solution to build mlpack under VisualStudio2015.

Big thanks to @keonkim :+1:

**Comment by rcurtin** [comment]
Let's go ahead and close this then, since the process for building on VS2015 seems to be known and tested.  @Kirizaki, feel free to open new tickets if you like.
