### ISSUE TITLE
Intel MKL issues with linear_regression & lars

### ISSUE THREAD

**Issue by gopalakr** [mlpack/mlpack#629]
I had to disable MKL and recompile armadillo and mlpack to get around an mkl issue, which did solve the following problem.

Heres the debug info for a linear regression run

$> ~/mlpack/usr/local/bin/mlpack_linear_regression -t /tmp/n20train.csv -r /tmp/ny1.csv -T /tmp/n20test.csv -p /tmp/nyout1.csv -v

 [INFO ] Loading '/tmp/n20train.csv' as CSV data. Size is 30 x 20000. 
 [INFO ] Loading '/tmp/ny1.csv' as raw ASCII formatted data. Size is 1 x 20000. 
Intel MKL ERROR: Parameter 4 was incorrect on entry to DGELSD. 
[INFO ] Loading '/tmp/n20test.csv' as CSV data. Size is 30 x 20000. 
[FATAL] The model was trained on 18446744073709551615-dimensional data, but the test points in '/tmp/n20test.csv' are 30-dimensional!

**Comment by rcurtin** [comment]
What versions of Armadillo, MKL, mlpack, and gcc are you using, and on what platform?  I don't have a copy of MKL at the moment, so I can't reproduce, but if you can provide all the versioning information, that will make reproducing this issue easier.  Thanks!

**Comment by gopalakr** [comment]
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1) 
libarmadillo.so.6.700.4
mlpack-2.0.0
l_mkl_11.3.0.109

**Comment by rcurtin** [comment]
There was never any chance to look into this one.  I'm sorry about that.  If you are still having the issue with updated sources, let me know and I will reopen the issue and be sure to look into it on a quicker timescale.
