### ISSUE TITLE
crash with mlpack::util::CLIDeleter::CLIDeleter()'

### ISSUE THREAD

**Issue by oliveriopt** [mlpack/mlpack#631]
Hi,
i think is an error very simple but I cannot find the solution.
I have this code
#include <cstdlib>
#include <mlpack/core.hpp>

using namespace std;

int main(int argc, char** argv) {

    return 0;
}

but when it reads the header after compilation, it crashes:

/usr/local/include/mlpack/core/util/cli_deleter.hpp:35: undefined reference to `mlpack::util::CLIDeleter::CLIDeleter()'

some clues?
thanks!

**Comment by rcurtin** [comment]
Are you linking against mlpack?  (`-lmlpack`)

**Comment by oliveriopt** [comment]
thanks, yes,  Iam using netbeans and I putted the option -lmlpack, i will test directly in the shell, thanks

**Comment by oliveriopt** [comment]
using shell script :(

user@UbuntuPC:~/Desktop$ g++ -std=c++11 -lmlpack main.cpp
/tmp/ccybjY8g.o: In function `__static_initialization_and_destruction_0(int, int)':
main.cpp:(.text+0xf34): undefined reference to `mlpack::util::CLIDeleter::CLIDeleter()'
main.cpp:(.text+0xf43): undefined reference to `mlpack::util::CLIDeleter::~CLIDeleter()'
collect2: error: ld returned 1 exit status

ideas?
thanks!

**Comment by oliveriopt** [comment]
the answer is the position of the option -l
user@UbuntuPC:~/Desktop$ g++ -std=c++11  main.cpp -lmlpack

**Comment by rcurtin** [comment]
Great, glad you got it figured out!
