### ISSUE TITLE
No arguments to 'isinf' that depend on a template parameter...

### ISSUE THREAD

**Issue by judelove** [mlpack/mlpack#632]
So, I realized many of the windows G++s can not compile mlpack, switched to Ubuntu and got progress past attempted windows10 installations till I stumbled on this. Before I try and solve it does anyone have an easy fix:

"there are no arguments to 'isinf' that depend on a template parameter, so a declaration of 'isinf' must be available [ -fpermissive] if(isnan(cNorm) || isinf(cNorm)), in kmeans_impl.hpp:178:36. 

I am using the .gz file linked to on the mlpack.org site, not a git clone, if that helps.  

regards

Jude

**Comment by rcurtin** [comment]
Hey Jude,

Sorry that you had problems compiling mlpack on Windows.  The issue you are having now can be fixed either by changing line 178 of `src/mlpack/methods/kmeans/kmeans_impl.hpp` and replacing `isnan()` with `std::isnan()` (it occurs twice).  Or, you can use the git master branch, which incorporates this fix.  Soon we will be releasing mlpack 2.0.2 which will have this issue solved.

This is the same issue as #522.

Thanks!

Ryan

**Comment by judelove** [comment]
Thanks for the prompt response will resume tomorrow and hope to go further.
