### ISSUE TITLE
Wrong number of mapping while Loading

### ISSUE THREAD

**Issue by keonkim** [mlpack/mlpack#658]
For testing purpose, I Loaded a simple csv like the one below.
```
1, 1, 1
1, 1, 1
 , 1, 1  <-- intentionally put missing value here
1, 1, 1
```
But it recognizes wrong number of mappings and modifies the csv in a wrong way.
```
[INFO ]         0   1.0000   1.0000   1.0000
[INFO ]         0   1.0000   1.0000   1.0000
[INFO ]    1.0000   1.0000   1.0000   1.0000
[INFO ] 
[INFO ] dataset info: 
[INFO ] 2 mappings in dimension 0.
[INFO ] 0 mappings in dimension 1.
[INFO ] 0 mappings in dimension 2.
```
Funny thing is that when I tried this,
```
1, 1, 1
 , 1, 1 <-- intentionally put missing value here
1, 1, 1
1, 1, 1
```
the result was different
```
[INFO ]         0   1.0000   1.0000   1.0000
[INFO ]    1.0000   1.0000   1.0000   1.0000
[INFO ]    1.0000   1.0000   1.0000   1.0000
[INFO ] 
[INFO ] dataset info: 
[INFO ] 2 mappings in dimension 0.
[INFO ] 0 mappings in dimension 1.
[INFO ] 0 mappings in dimension 2.
```
And the lastly when I tried with the following,
```
 , 1, 1  <-- intentionally put missing value here
1, 1, 1
1, 1, 1
1, 1, 1
```
It finally showed the right number of mappings
```
[INFO ]         0   1.0000   1.0000   1.0000
[INFO ]    1.0000   1.0000   1.0000   1.0000
[INFO ]    1.0000   1.0000   1.0000   1.0000
[INFO ] 
[INFO ] dataset info: 
[INFO ] 1 mappings in dimension 0.
[INFO ] 0 mappings in dimension 1.
[INFO ] 0 mappings in dimension 2.
```

The code I used for loading the file is:
```
  arma::mat data;
  data::DatasetInfo info;
  data::Load(inputFile, data, info,  true);
  Log::Info << data << endl;

  Log::Info << "dataset info: " << endl;
  for (size_t i = 0; i < data.n_rows; ++i)
  {
    Log::Info << info.NumMappings(i) << " mappings in dimension "
        << i << "." << endl;
  }
```

Thanks for reading this long post.

**Comment by stereomatchingkiss** [comment]
@keonkim Hi, the function, data::Load do the right thing, it deceive your eyes because you ask it to transpose the data. Following codes should make things clear

```
arma::mat data;
data::DatasetInfo info;
bool const fatal = true;
bool const transpose = false;
data::Load("simple00.csv", data, info, fatal, transpose);
std::cout << data << endl;
```

**Comment by keonkim** [comment]
@stereomatchingkiss I get that blank data is mapped to 0, but I don't understand why it returns different number of mappings even if I only put one string value.

**Comment by keonkim** [comment]
I tried with 
```
11, 101, 1001
12 , 102, 1002
13, 103, 1003
14, 104, 1004
```
which successfully transposed to:
```
[INFO ]    1.1000e+01   1.2000e+01   1.3000e+01   1.4000e+01
[INFO ]    1.0100e+02   1.0200e+02   1.0300e+02   1.0400e+02
[INFO ]    1.0010e+03   1.0020e+03   1.0030e+03   1.0040e+03
```
But when I replaced 12 with a, the result was
```
[INFO ]             0   1.0000e+00   1.3000e+01   1.4000e+01
[INFO ]    1.0100e+02   1.0200e+02   1.0300e+02   1.0400e+02
[INFO ]    1.0010e+03   1.0020e+03   1.0030e+03   1.0040e+03
[INFO ] 2 mappings in dimension 0.
```
which means that 11 and 12 are mapped as categories. (which I also think it is unintended?)

**Comment by stereomatchingkiss** [comment]
@keonkim I think the behavior is correct, let us use non-tranpose case to discuss the behavior

codes : 

```
try{
        arma::mat data;
        data::DatasetInfo info;
        bool const fatal = true;
        bool const transpose = false;
        data::Load("simple00.csv", data, info, fatal, transpose);
        std::cout << data << endl;
        std::cout<<"dimensions == "<<info.Dimensionality()<<std::endl;

        Log::Info << "dataset info: " << endl;
        for (size_t i = 0; i < data.n_rows; ++i)
        {
            std::cout << info.NumMappings(i) << " mappings in dimension "
                      << i << "." << endl;
        }
    }catch(std::exception const &ex){
        std::cerr<<ex.what()<<std::endl;
    }
```

Before we transpose, mlpack treat every columns as an example, every row as a dimension
every dimension represent one type of feature(height, weight, color, etc).

After we know how mlpack treat the data, everything are simple

input data

a,    b,        c
b, 102, 1002
c, 103, 1003
d, 104, 1004

What would you expect?Since every row represent to a feature, we know that a,b,c at row 0 should map to different numeric value.Because Every row represent to different features, we know that a,b,c,d at column 0 should map to one numeric value. What are the output?

output : 

 0.000000e+00   1.0000e+00   2.0000e+00
 0.000000e+00   1.0200e+02   1.0020e+03
 0.000000e+00   1.0300e+02   1.0030e+03
 0.000000e+00   1.0400e+02   1.0040e+03

As expected, right?
3 mappings in dimension 0.
1 mappings in dimension 1.
1 mappings in dimension 2.
1 mappings in dimension 3.

So, why it looks like that?



a,    b,        c
b, 102, 1002
c, 103, 1003
d, 104, 1004

**Comment by stereomatchingkiss** [comment]
@keonkim After more test, you think you are correct, the behavior really weird

Following examples, all of them without transpose

11,     12,    a,   14 
101,   102,  103,  104
1001, 1002, 1003, 1004

Will output

0.000000e+00   1.0000e+00   2.0000e+00   1.4000e+01
1.0100e+02   1.0200e+02   1.0300e+02   1.0400e+02
1.0010e+03   1.0020e+03   1.0030e+03   1.0040e+03

dimensions == 3
3 mappings in dimension 0.
0 mappings in dimension 1.
0 mappings in dimension 2.

But this input work

a,     12,    c,   14 
101,   102,  103,  104
1001, 1002, 1003, 1004

output 

 0.000000e+00   1.2000e+01   1.0000e+00   1.4000e+01
   1.0100e+02   1.0200e+02   1.0300e+02   1.0400e+02
   1.0010e+03   1.0020e+03   1.0030e+03   1.0040e+03

dimensions == 3
2 mappings in dimension 0.
0 mappings in dimension 1.
0 mappings in dimension 2.

I will look into this bug and try to fix it, maybe this could be solved after a few hours

**Comment by stereomatchingkiss** [comment]
@keonkim I think you are right, after some test, I think there really has some bugs.

input : 

11,     12,    c
101,   102,  103
1001, 1002, 1003

output : 

0.000000e+00   1.0000e+00   2.0000e+00
1.0100e+02   1.0200e+02   1.0300e+02
1.0010e+03   1.0020e+03   1.0030e+03

dimensions == 3
3 mappings in dimension 0.
0 mappings in dimension 1.
0 mappings in dimension 2.

it works if the input is 

a,     12,    13
101,   102,  103
1001, 1002, 1003

**Comment by keonkim** [comment]
@stereomatchingkiss thanks for the response!
I will further investigate and come back.
