### ISSUE TITLE
Issue a fatal error when any ambiguous parameters are detected

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#671]
The mlpack command-line programs use the `PARAM_STRING`, `PARAM_DOUBLE`, and other macros to define input parameters.  But it is possible that I could write:

```
PARAM_STRING("param1", "Parameter 1 documentation.", "p");
PARAM_STRING("param2", "Parameter 2 documentation.", "p");
```

You can see that `-p` now specifies two things. If you run the program and specify "-p", you will get an error like

```
option '-p' is ambiguous and matches '--param1' and '--param2'
```

But you only get that error when the option is specified.  So it is possible for a program writer to write a program with ambiguous options, test it (but not test every parameter), and not realize that there is a duplicate parameter.  I know this is true because I have done exactly that many times!

It should be possible, when options are registered, to catch this situation.  The `PARAM_*` macros expand to a global definition of a `mlpack::util::Option<>` object, which registers itself with the `mlpack::CLI` class.  I think that when options register, we should check to see that the short form of that option (and the long form) are not already specified, and if they are, we should call `Log::Fatal` with an error.

The relevant code can be found all in `src/mlpack/core/util/`.  I think this would be a good task for someone new to mlpack, so let me know if I can clarify anything.

**Comment by keonkim** [comment]
> someone new to mlpack
@rcurtin that sounds like me. I can do it. 
It might take some time though as I am not familiar with macros.

**Comment by rcurtin** [comment]
Sure, if you like.  Here is some quick reading on macros, they are not so hard: https://gcc.gnu.org/onlinedocs/cpp/Macros.html

You can see the definition of the `PROGRAM_*` macros in `src/mlpack/core/util/cli.hpp`.  Let me know if I can explain anything further :)

**Comment by keonkim** [comment]
kind of brute-forced, but I think this is the simplest way without changing much code.
[changes here](https://github.com/mlpack/mlpack/pull/680/files#diff-ce922101a2dfeea7357ac875874789fdR46)

**Comment by keonkim** [comment]
done in #680
