### ISSUE TITLE
string util seems to be unused anymore

### ISSUE THREAD

**Issue by keonkim** [mlpack/mlpack#685]
I left this unchanged because it felt I need to ask this before just deleting it.
Can I delete the files below?

 * [string_utill.hpp](https://github.com/mlpack/mlpack/blob/d2e353468b8fce9fc1ee46799860f3860c4c8db9/src/mlpack/core/util/string_util.hpp) 

* [string_util.cpp](https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/util/string_util.cpp)

**Comment by rcurtin** [comment]
Yep, this used to be used when we had `ToString()` methods but I removed these in c673742 so I agree we can delete this now.
