### ISSUE TITLE
A tiny bug in client

### ISSUE THREAD

**Issue by cypro666** [mlpack/mlpack#697]
My version of mlpack is 2.0.1 git-4fa39b6:

When I run mlpack_softmax_regression like:
```
~/mlpack/build$ ./bin/mlpack_softmax_regression -t iris.csv -l iris_labels.txt --output_model_file o.csv
[WARN ] None of --output_model, --test_labels, or --predictions_file are set; no results from this program will be saved.
```
nothing more....

In line 46 of softmax_regression_main.cpp , `output_model_file` was registed as an arg name, 
but in line 24 and line 113 and 137 lost the `_file` suffix!!!

```
PARAM_STRING("input_model_file", "File containing existing model (parameters).", "m", "");
const string outputModelFile = CLI::GetParam<string>("output_model") ...
data::Save(CLI::GetParam<std::string>("output_model") ...
```

In fact `input_model` has the same problem.

My version of boost::program_options is 1.58 

mlpack's clients(executables in method dir) is wonderful and easy using, but the arguments parser based on boost maybe unnessesary?

**Comment by keonkim** [comment]
@cypro666 Thanks for the report! 
I recently discovered this too, and it will soon be fixed as pull request #680 is merged.
[fixed file](https://github.com/keonkim/mlpack/blob/e99c282cf599be647b31e0159bcd91b5ff4821f0/src/mlpack/methods/softmax_regression/softmax_regression_main.cpp#L96)
