### ISSUE TITLE
missing license header for verbatim copies from armadillo codebase

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/mlpack#702]
Hi guys,

The file mlpack/src/mlpack/core/arma_extend/fn_ind2sub.hpp contains verbatim copies of the ind2sub() and sub2ind() functions from armadillo codebase (v7.100). The file was introduced by @nilayjain and merged in #683. Even though it's open source code and the functions are straightforward, the corresponding license must still be respected.

MLPACK is licensed under BSD, while Armadillo is licensed under MPL v2. So, the fn_ind2sub.hpp file must have a header stating the copyright and that the functions are licensed under MLP v2.

**Comment by rcurtin** [comment]
Yep, I had previously thought this fell under Section 3.3 of the MPL:

```
3.3. Distribution of a Larger Work

You may create and distribute a Larger Work under terms of Your choice, provided that You also comply with the requirements of this License for the Covered Software. If the Larger Work is a combination of Covered Software with a work governed by one or more Secondary Licenses, and the Covered Software is not Incompatible With Secondary Licenses, this License permits You to additionally distribute such Covered Software under the terms of such Secondary License(s), so that the recipient of the Larger Work may, at their option, further distribute the Covered Software under the terms of either this License or such Secondary License(s).
```

but now that I look into it, this is not the case---the BSD license is not a "Not Incompatible Secondary License" (or whatever the correct terminology is).  So, you're right, we have to put the license there.  I've taken care of this in 7783497.

If you find anything else wrong, please let us know.  I am not a trained intellectual property lawyer, so I make no claims that everything is done exactly right; I only claim it's "kinda mostly" done right. :)

**Comment by conradsnicta** [comment]
thanks for sorting this out :)
