### ISSUE TITLE
I need all the dlls required to run mlpack on Windows 

### ISSUE THREAD

**Issue by illidanswp** [mlpack/mlpack#704]
I'm trying to run mlpack on Windows(10) with vs2015 x64, but the error " ***.dll is missing" keeps showing up again and again. I've got "libopenblas.dll", "cyggfortran-3.dll", "cyggcc_s-seh-1.dll" and "libgcc_s_seh-1.dll" by all kinds of means(It has taken me a long time).Finally after I got the "libgcc_s_seh-1.dll", a new error(code 0xc000007b) occurred(this error occurs probably because 64-bit program uses 32-bit dll, according to google). I'm not quite sure whether this error is caused by "libgcc_s_seh-1.dll" or the next dll required(if it happens to exist on my computer but is not the right version). I have no other way but to ask for help here. So I wonder if it's possible to provide all the dlls for us.

**Comment by zoq** [comment]
Do you use a pre built version of mlpack, or did you build mlpack yourself?

**Comment by illidanswp** [comment]
Indeed I've tried the pre built version you provided in #659(How to build mlpack with visual studio 2013), and I've also built mlpack(successfully), but both cases have the same problems, as described above.

**Comment by zoq** [comment]
Okay, so, if you tell us more about your setup e.g. how the ``PATH`` parameter looks like and which command you used to produce the error e.g. by calling ``mlpack_pca -h``, I do my best to reproduce the error.

**Comment by illidanswp** [comment]
Thank you for your patience.
---------------------------------1st-----------------------------------------
![qq 20160624083641](https://cloud.githubusercontent.com/assets/8843561/16324621/8c115404-39e8-11e6-9a14-a20b60f81ab0.png)
----------------------------------2nd---------------------------------------
![qq 20160624084203](https://cloud.githubusercontent.com/assets/8843561/16324625/97efc918-39e8-11e6-9120-b39f0c33c45a.png)
these two pics show the cases where I got the error, one is to run any of the pre built tools you provided, either directly or by command line; the other is trying to include it in vs2015 project.
--------------------------------------------3rd--------------------------------------------
![qq 20160624085708](https://cloud.githubusercontent.com/assets/8843561/16324785/36969604-39ea-11e6-8a21-11c11238d23e.png)
In vs2015 project, the Additional Include Directories is set to _mlpack_include_ directory(shown in 3rd pic), Additional Library Directories is set to _mlpack_lib_ directory(shown in 1st pic) and _mlpack.dll_ has been added into Additional Dependencies.
The following two pics are PATHs, one is user path and the other is system path.
----------------------------------------4th-----------------------------------------
![qq 20160624090329](https://cloud.githubusercontent.com/assets/8843561/16324874/f80c76fa-39ea-11e6-92a2-1e51585fee5d.png)
----------------------------------------5th------------------------------------------
![qq 20160624090448](https://cloud.githubusercontent.com/assets/8843561/16324876/ff97ebca-39ea-11e6-8595-b9fb9478f937.png)

**Comment by stereomatchingkiss** [comment]
libgcc_s_dw2-1.dll
libgcc_s_seh-1.dll
libgfortran-3.dll
liblapack.dll
libopenblas.dll
libquadmath-0.dll
libwinpthread-1.dll

These are the dll needed on my laptop(y410p, windows 10 64bits). If I remember correct, I compile the openBLAS and lapack by the fortran compiler come with mingw.

**Comment by illidanswp** [comment]
@stereomatchingkiss Thank you. Would you please give me a copy of your dll files, since I wonder if I can get the right version. My Email is [illidanswp@gmail.com](url)

**Comment by Kirizaki** [comment]
@illidanswp Try mlpack wiki: [Using mlpack in other applications under Visual Studio 2015](https://github.com/mlpack/mlpack/wiki/WindowsBuild#using-mlpack-in-other-applications-under-visual-studio-2015). This should help you.
