### ISSUE TITLE
Check if SortStruct provides any benefit.

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#712]
This comes from the discussion of #699: we are not sure if using `SortStruct` instead of `pair<double, size_t>` provides any speedup. So we should check, and then pick the better of the two approaches.

**Comment by lozhnikov** [comment]
I wrote a simple test. With `-O3` `std::pair` is faster then `SortStruct`.
If `n=100M`:
```
SortStruct results:
sorted[0].n = 26200464
fill duration = 1620ms
sort duration = 17090ms
std::pair results:
sorted[0].n = 26200464
fill duration = 1597ms
sort duration = 12287ms
```
[main.cpp.zip](https://github.com/mlpack/mlpack/files/340894/main.cpp.zip)

**Comment by lozhnikov** [comment]
I realized that we do not sort huge amounts of data. I corrected the test.
With `-O3` `std::pair` is a little bit faster.
If `n = 10`, `numIterations = 100M`:
```
SortStruct results:
unnecessaryCodeRemovalPreventer = 1.09091e+08
sort duration = 33621ms
std::pair results:
unnecessaryCodeRemovalPreventer = 1.03127e+08
sort duration = 29536ms
```
[main2.cpp.zip](https://github.com/mlpack/mlpack/files/340950/main2.cpp.zip)

**Comment by rcurtin** [comment]
Results on my system with gcc:

```
$ ./main2
SortStruct results:
unnecessaryCodeRemovalPreventer = 1.09092e+08
sort duration = 21890ms
std::pair results:
unnecessaryCodeRemovalPreventer = 1.20977e+08
sort duration = 18936ms
```

and with clang:

```
SortStruct results:
unnecessaryCodeRemovalPreventer = 1.0909e+08
sort duration = 81754ms
std::pair results:
unnecessaryCodeRemovalPreventer = 1.01206e+08
sort duration = 80806ms
```

clang is much slower!  I also had one more test I wanted to do---using the default comparator for `std::pair`.  So I removed the third argument from line 74 of main2.cpp and switched the order of the pair to hold double first then size_t.

gcc:

```
SortStruct results:
unnecessaryCodeRemovalPreventer = 1.09092e+08
sort duration = 21970ms
std::pair results:
unnecessaryCodeRemovalPreventer = 1.26484e+08
sort duration = 19171ms
```

clang:

```

```
SortStruct results:
unnecessaryCodeRemovalPreventer = 1.09091e+08
sort duration = 80945ms
std::pair results:
unnecessaryCodeRemovalPreventer = 1.14581e+08
sort duration = 82204ms
```

So I guess the best solution is to use `std::pair`, but with the lambda, as you have it written.

**Comment by rcurtin** [comment]
Since the R+ and R++ trees are merged, I think we have a solution here so I'll go ahead and close this.
