### ISSUE TITLE
Test had stuck in 2.0.2

### ISSUE THREAD

**Issue by dongli** [mlpack/mlpack#718]
I am trying to build MLPACK 2.0.2 on OS X 10.11. The compilation is OK, but the test had stuck for half a day, and it is still running when I write this line.

**Comment by rcurtin** [comment]
Are you using OpenBLAS?  I think I have seen this issue with OpenBLAS but I did not manage to dig in far enough to really debug it.

Can you try running the test with verbose output and seeing what it is hanging on?
```
mlpack_test --report_level=detailed --log_level=test_suite
```

**Comment by dongli** [comment]
Yes, I am using OpenBLAS 0.2.18.

```
...
/opt/starman/packages/mlpack/mlpack-2.0.2/src/mlpack/tests/cf_test.cpp:33: Entering test case "CFGetRecommendationsAllUsersTest"

error: pinv(): svd failed
unknown location:0: fatal error: in "CFTest/CFGetRecommendationsAllUsersTest": std::runtime_error: pinv(): svd failed
...
unknown location:0: fatal error: in "CFTest/CFGetRecommendationsQueriedUserTest": std::runtime_error: Timer::Start(): timer 'cf_factorization' has already been started
...
unknown location:0: fatal error: in "CFTest/SerializationTest": std::runtime_error: Timer::Start(): timer 'cf_factorization' has already been started
...
/opt/starman/packages/mlpack/mlpack-2.0.2/src/mlpack/tests/cosine_tree_test.cpp:21: Entering test suite "CosineTreeTest"
/opt/starman/packages/mlpack/mlpack-2.0.2/src/mlpack/tests/cosine_tree_test.cpp:30: Entering test case "CosineTreeNoSplit"
```

The test stuck here.

**Comment by dongli** [comment]
I dug for the statement which stuck, and found it is:

```
CosineTree ctree(data, epsilon, delta);
```

**Comment by dongli** [comment]
I looked into `mlpack-2.0.2/src/mlpack/core/tree/cosine_tree/cosine_tree.cpp`, and found it use Monte Carlo, so I tested Armadillo with the following codes:

```
#include <iostream>
#include <armadillo>

using namespace std;
using namespace arma;

int main(int argc, char const* argv[])
{
    cout << "check 1" << endl;
    cout << arma_rng::randn<double>() << endl;
    cout << "check 2" << endl;
    return 0;
}
```

And the output is

```
check 1
```

It stuck here too! I tried Armadillo 6.700.7 and 7.200.2, both have this problem. I don't know if this is related.

**Comment by rcurtin** [comment]
I think that a simple workaround here is to not use OpenBLAS but that is not a good workaround.  Another simple workaround might be to set the number of threads to 1 by setting the environment variable `OPENBLAS_NUM_THREADS=1`.

That's not a solution of course, but it might keep you going while I figure out what is going on.  I seem to remember having come across some OpenBLAS issue that was similar to this, but I did not come to a conclusion on how to fix it.  Now it looks like I have to find a conclusion. :)

**Comment by dongli** [comment]
Thanks. I will also keep looking for a better solution.

**Comment by rcurtin** [comment]
Did the `OPENBLAS_NUM_THREADS=1` workaround work, by the way?

**Comment by dongli** [comment]
I debugged the above small testing code on Armadillo, and use `lldb` to see which part causes the problem. Then I found the following infinite loop in `random.tcc` bared in `libstdc++`:

```
   1798		    do
   1799		      {
   1800			__x = result_type(2.0) * __aurng() - 1.0;
-> 1801			__y = result_type(2.0) * __aurng() - 1.0;
   1802			__r2 = __x * __x + __y * __y;
   1803		      }
   1804		    while (__r2 > 1.0 || __r2 == 0.0);
(lldb)
```

where `__x` and `__y` are always -1, so `__r2` is always 2.

BTW, I am using GCC 6.1.0 compiled by myself, so it is the problem of `libstdc++`? Sorry, it is not related to MLPACK actually.

**Comment by dongli** [comment]
I found it may be the bug in Armadillo, since I tried the following codes which is OK:

```
#include <iostream>
#include <random>

using namespace std;

int main(int argc, const char *argv[])
{
    mt19937_64 rng;
    normal_distribution<double> dist;

    cout << dist(rng) << endl;

    return 0;
}
```
which should call the same random functions as in `arma_rng::randn<double>()`.

**Comment by dongli** [comment]
@rcurtin  After rebuilt Armadillo, the tests of MLPACK are all passed!

**Comment by rcurtin** [comment]
Let me see if I can reproduce this issue, and if so, we can report it upstream to Armadillo and they can make a fix.

**Comment by dongli** [comment]
Homebrew installed Armadillo does not have this problem, because in `include/armadillo_bits/config.hpp` it has:

```
#if defined(ARMA_USE_WRAPPER)
  #if defined(ARMA_USE_CXX11)
    #if !defined(ARMA_USE_EXTERN_CXX11_RNG)
/* #undef ARMA_USE_EXTERN_CXX11_RNG */
    #endif
  #endif
#endif
```

I don't know how does Homebrew do this, since I follow the same procedure to build Armadillo.

**Comment by dongli** [comment]
I think this can be closed now, since it is a bug in Armadillo.
