### ISSUE TITLE
GammaDistribution Implementation is Incomplete

### ISSUE THREAD

**Issue by mentekid** [mlpack/mlpack#733]
My GammaDistribution implementation (https://github.com/mlpack/mlpack/pull/729) is incomplete. Here's a summary of what's missing:
- `Probability(arma::vec&)`: A function that gives the probability of a given observation
- `LogProbability(arma::vec&)`: A function that gives the log probability of a given observation.
- `Random()`: Return a gamma-distribution random datapoint.
- `Train(observations, probabilities)`: A function that fits the observations with given probabilities (sort of like the job done by Train(observations), but weighted).

I implemented this class mainly to have a way to fit a Gamma to observation data, but this should be completed to be usable as an mlpack distribution.

I think the Train(observations, probabilities) could be quite straightforward - the three main statistics needed for the Train(observations) function to work is log(mean(observations)), mean(observations) and mean(log(observations)). If we replace mean(.) with weightedMean(., probabilities), it should work similarly well. I might be wrong on this though.

**Comment by rcurtin** [comment]
This is nearly done, but the `Train(observations, probabilities)` function isn't done yet.  Here is some discussion on how that might be done:

https://github.com/mlpack/mlpack/pull/751#discussion_r73780816

**Comment by aditya1315** [comment]
@rcurtin I can take this up. I will try to implement it and get back to you in a few days?

**Comment by rcurtin** [comment]
@aditya1315: you are more than welcome to do this.  If you open a PR, be sure that it follows the style guidelines (found on the wiki under the page 'DesignGuidelines') and that it has some tests to go along with it.  Thanks!

**Comment by aditya1315** [comment]
@rcurtin, I saw discussion on the #751 thread and spent some time on it. Your solution seems to work. So should I base the code your solution and go ahead with testing it?

Regarding the tests - mantekid suggests a way but it gives NaN sometimes. So how should I proceed in this?

Thanks in advance

**Comment by rcurtin** [comment]
@aditya1315: yes, I agree that your approach is reasonable.  You can base the code on what I wrote, and then write some tests for it.  The testing will be the hard part though, I suspect. :)

I wonder if the NaN values for the test are the result of zero values being passed to the training of the distribution.  The Gamma distribution can't handle zero-valued observations (its PDF is 0 at x=0).

**Comment by yashu-seth** [comment]
@mentekid @rcurtin What is the status of this issue?

**Comment by rcurtin** [comment]
@yashu-seth: it is still an open issue.  The `Train(probabilities, observations)` overload is the only thing that's missing.  There's a link to some discussion in #751 that talks about that.  If you'd like to do this and submit a PR, it would be appreciated.

**Comment by yashu-seth** [comment]
@rcurtin Okay. I will look into this and submit a PR ASAP.
