### ISSUE TITLE
Use Enum Type to define different possible search modes, in neighbor search class.

### ISSUE THREAD

**Issue by MarcosPividori** [mlpack/mlpack#750]
About the implementation of NeighborSearch class, I think we should define a enum type like:

```
enum SearchMode
{
    NAIVE_MODE,
    SINGLE_MODE,
    DUAL_MODE
};
```

This way, constructors will be clearer, instead of using combinations of boolean values.

For example, we could have:

```
 NeighborSearch(const MatType& referenceSet, SearchMode mode, double epsilon, MetricType metric);
```

Instead of:

```
 NeighborSearch(const MatType& referenceSet, bool naive, bool singleMode, double epsilon, MetricType metric);
```

Also, the implementation will be clearer, because we could use `switch` statement when analysing the 3 possible situations.

**Comment by rcurtin** [comment]
I agree with this idea.  If we want to do it before mlpack 3.0.0, that's fine, we just have to remember reverse compatibility.

Seems like there is a lot of reverse compatibility going on, maybe a 3.0.0 release is not so far away...

**Comment by rcurtin** [comment]
This actually won't be completed until mlpack 3.0.0 when #768 is merged, but I guess, since we already have the code ready to go, maybe there is no reason to have this ticket open anymore and I should close it again...!
