### ISSUE TITLE
Refactor `RSModel` and `RAModel` to parallel `NSModel` and use `boost::variant`

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#756]
In 86a9852, `NSModel` was refactored to clean up a lot of the duplicated code and instead use `boost::variant` plus the visitor paradigm.  We should also apply these changes to `RSModel` and `RAModel`.

A good place to start here would be to look at the changes in 86a9852, and apply them to the very similar classes `RSModel` for range searching and `RAModel` for rank-approximate nearest neighbor search.

`NSModel` can be found in `src/mlpack/methods/neighbor_search/ns_model.hpp` and `src/mlpack/methods/neighbor_search/ns_model_impl.hpp`.
`RSModel` can be found in `src/mlpack/methods/range_search/rs_model.hpp` and `src/mlpack/methods/range_search/rs_model_impl.hpp`.
`RAModel` can be found in `src/mlpack/methods/rann/ra_model.hpp` and `src/mlpack/methods/rann/ra_model_impl.hpp`.

This could be a good issue for someone new who is looking to contribute their first PR.

**Comment by ferbncode** [comment]
Hi, i would like to work on this issue. Thanks :).

**Comment by rishabhkumar296** [comment]
Hi, I would like to work on this issue.

**Comment by rcurtin** [comment]
RSModel is done with #866, now only RAModel remains.

**Comment by Trion129** [comment]
Can I work on the RAModel part?

**Comment by rcurtin** [comment]
@Trion129: #889 is already open, so you may want to find something else so that you don't duplicate work.

**Comment by shardulparab97** [comment]
Hi @rcurtin , I wanted to ask which part of the issue is yet pending, since RSModel is complete and issue #889 works on RAModel. I am interested in contributing to MLPack, can you please help me out. Thanks! :)

**Comment by rcurtin** [comment]
@shardulparab97: sorry for the slow response.  You're right that both are done, so I think we can close this issue.  Thanks for pointing it out! :+1:  There are lots of other issues we've labeled `help wanted` or `good first issue`, so maybe you could find one of those that interests you and contribute to that issue?

Hope this helps!
