### ISSUE TITLE
TWO Mapping Objects for DatasetMapper

### ISSUE THREAD

**Issue by keonkim** [mlpack/mlpack#758]
Current `maps` object for DatasetMapper can be described as maps of
`map<dimension, pair<bimap<string, MappedType>, numMappings>>` (NumMappings usually being numeric primitive types.)

I think having multiple map policies can be simplified by having to two mapping objects. 
One for mapping categories, one for mapping invalid values.
For validation & imputation purposes we could have another mapper (I will call it invalidMaps for now). Which looks like:
```
// MapType = same as before: map<dimension(size_t), pair<bimap<string, MappedType(numeric)>, numMappings>>; 
// InvalidMapType = maps<string, std::pair<std::pair<dimension(size_t), point(size_t)>, numInvalidMappings(size_t)>>;
MapType maps;
InvalidMapType invalidMaps;
```
invalidMaps and maps serve two different purposes.
maps is used as usual (mapping categorical feature to numeric feature).
invalidMaps is used as temporary holder for future imputation. Both x and y coordinates have to be stored in order to track the invalid values, since every invalid values are turned to NaNs.

Ultimately, I think this way we could simplify the use of only one mapping policy instead of many.
What do you think of this idea?

**Comment by stereomatchingkiss** [comment]
// MapType = maps<dimension, bimap<string, MappedType>>;
MapType maps;
size_t numMappings;

How do you keep track of the number of mappings of each dimension?Do
you mean we could just

record the number of total mappings?


>Ultimately, I think this way we could simplify the use of only one mapping policy instead of many.

Could you show us some examples?Thanks

**Comment by rcurtin** [comment]
I agree with @stereomatchingkiss, I'm not sure I understand how this would simplify things.

**Comment by keonkim** [comment]
Sorry several ideas got mixed up while writing the issue. I am writing a sample program and a more clear explanations on the issue. Will be done by tomorrow.

**Comment by keonkim** [comment]
discarded this approach.
