### ISSUE TITLE
General Defeatist Search Traverser.

### ISSUE THREAD

**Issue by MarcosPividori** [mlpack/mlpack#761]
Hi,
We want to provide a general *Defeatist Search Traverser* for every *TreeType*, as we do with `SingleTreeTraverser` and `DualtreeTraversers`.
This discussion started in the PR https://github.com/mlpack/mlpack/pull/747:
+ https://github.com/mlpack/mlpack/pull/747#issuecomment-237901505
+ https://github.com/mlpack/mlpack/pull/747#issuecomment-238137161
+ https://github.com/mlpack/mlpack/pull/747#issuecomment-238985341
+ https://github.com/mlpack/mlpack/pull/747#issuecomment-239206014
+ https://github.com/mlpack/mlpack/pull/747#issuecomment-239602549
+ https://github.com/mlpack/mlpack/pull/747#issuecomment-239870358
+ https://github.com/mlpack/mlpack/pull/747#issuecomment-239872121

If you agree, I prefer the name: `SingleTreeGreedyTraverser`, instead of `SingleTreeDefeatistTraverser`.

**Comment by rcurtin** [comment]
I agree, I think `SingleTreeGreedyTraverser` is just fine for a name.  I think we can write a completely general traverser; I don't think it needs to be tree-specific.

**Comment by MarcosPividori** [comment]
Closed after  PR https://github.com/mlpack/mlpack/pull/762 was merged!
