### ISSUE TITLE
User rvalue references to set a given reference tree in RASearch, RangeSearch, FastMKS, and DualTreeBoruvka

### ISSUE THREAD

**Issue by MarcosPividori** [mlpack/mlpack#773]
Update the code to include changes similar to the ones included in the PR: https://github.com/mlpack/mlpack/pull/765

**Comment by itabhiyanta** [comment]
Hi Marcos

I would like to take up this issue. I am reading #765 to understand the issue. I am completely new to mlpack and machine learning. I have gone through the getting involved page.
http://www.mlpack.org/involved.html
So I am at the point where it is suggested to jump in and contribute.
Do you have any update/alternate way in which I should approach this (other than going through #765)?
Kindly advise.
Rohit

**Comment by akanuraj200** [comment]
@itabhiyanta 
Hello Rohit

I already have a PR (#799) in motion for the `FastMKS` and `DualTreeBoruvka` part of this issue. I had planned on updating `RASearch` and `RangeSearch` too as soon as i get some time, but you are free to try your hand at these two. 

#765 is a good place to start. You might want to take a look at all the discussion there. They are helpful in understanding what is being implemented. 

All the best :)

**Comment by aneesh2312** [comment]
@akanuraj200 I would like to try RASearch and RangeSearch as I am new here, and would like to start with something labeled easy. Are you working on it? Or can I?

**Comment by itabhiyanta** [comment]
Hi

I haven't started so you may pick it up.
Rohit

**Comment by akanuraj200** [comment]
> @akanuraj200 I would like to try RASearch and RangeSearch as I am new here, and would like to start with something labeled easy. Are you working on it? Or can I

Hello @aneesh2312 
I am not working on `RASearch` and `RangeSearch` currently. You are free to try your hand at them.
All the best. :)

**Comment by abhinavrai44** [comment]
Hi,
I would like to take this issue. Can I also try to solve the problem or is it allotted ?

**Comment by aneesh2312** [comment]
@abhinavrai I am working on it..

**Comment by Lakshya1605** [comment]
@aneesh2312 are you still working on it ?If no i would like to work on this issue .Thank You!!

**Comment by aneesh2312** [comment]
@Lakshya1605 I have done RAsearch, but I never got time to finish RangeSearch.. You can take RangeSearch...

**Comment by Lakshya1605** [comment]
@aneesh2312 Could you please give an overview of what is expected to be done .
Thank You !!!
