### ISSUE TITLE
unable to  build mlpack

### ISSUE THREAD

**Issue by hunk3749** [mlpack/mlpack#776]
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
CMake Error at CMake/FindArmadillo.cmake:326 (message):
  ARMADILLO_INCLUDE_DIR-NOTFOUND/armadillo_bits/config.hpp not found! Cannot
  determine what to link against.
Call Stack (most recent call first):
  CMakeLists.txt:133 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by rcurtin** [comment]
Hi there, do you have Armadillo installed?

**Comment by hunk3749** [comment]
when i tried to install dependencies for mlpack it shows this-
dhanpal@dhanpal-HP-Pavilion-15-Notebook-PC:~$ sudo apt-get install libboost-math-dev libboost-program-options-dev
[sudo] password for dhanpal: 
Sorry, try again.
[sudo] password for dhanpal: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost-program-options-dev is already the newest version.
libboost-math-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
dhanpal@dhanpal-HP-Pavilion-15-Notebook-PC:~$

**Comment by zoq** [comment]
Can you also check if ``libarmadillo-dev`` is already installed and probably post the output?

**Comment by hunk3749** [comment]
it is installed but and older version which is not compatible with the mlpack
would you please guide me installing the Armadillo >= 4.100.0 on my ubuntu 12.04

**Comment by zoq** [comment]
If you are able to upgrade your OS, that would be the easiest way, if not you could use the armadillo version from ``ppa:comp-phys/stable``:

```
sudo apt-add-repository -y ppa:comp-phys/stable
sudo apt-get update
sudo apt-get install libarmadillo-dev
```

**Comment by hunk3749** [comment]
ok after installing newest version i am getting this error-
dhanpal@dhanpal-HP-Pavilion-15-Notebook-PC:~$ sudo -s
[sudo] password for dhanpal: 
root@dhanpal-HP-Pavilion-15-Notebook-PC:~# cd mlpack-2.0.3
root@dhanpal-HP-Pavilion-15-Notebook-PC:~/mlpack-2.0.3# cd build
root@dhanpal-HP-Pavilion-15-Notebook-PC:~/mlpack-2.0.3/build# cmake ../
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Found Armadillo: /usr/lib/libarmadillo.so (found suitable version "7.400.2", required is "4.100.0")
-- Armadillo libraries: /usr/lib/libarmadillo.so
CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1202 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.46.1

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.49 (or
  newer).

  The following Boost libraries could not be found:

          boost_program_options
          boost_unit_test_framework
          boost_serialization

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:213 (find_package)


-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp 
-- Found Git: /usr/bin/git 
-- Regenerating arma_config.hpp.
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
CMake Warning at CMakeLists.txt:358 (message):
  txt2man not found; man pages will not be generated.


-- Configuring incomplete, errors occurred!
root@dhanpal-HP-Pavilion-15-Notebook-PC:~/mlpack-2.0.3/build# cmake ../
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Armadillo libraries: /usr/lib/libarmadillo.so
CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1202 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.46.1

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.49 (or
  newer).

  The following Boost libraries could not be found:

          boost_program_options
          boost_unit_test_framework
          boost_serialization

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:213 (find_package)


-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
CMake Warning at CMakeLists.txt:358 (message):
  txt2man not found; man pages will not be generated.


-- Configuring incomplete, errors occurred!
root@dhanpal-HP-Pavilion-15-Notebook-PC:~/mlpack-2.0.3/build# cmake ../
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Armadillo libraries: /usr/lib/libarmadillo.so
CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1202 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.46.1

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.49 (or
  newer).

  The following Boost libraries could not be found:

          boost_program_options
          boost_unit_test_framework
          boost_serialization

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:213 (find_package)


-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
CMake Warning at CMakeLists.txt:358 (message):
  txt2man not found; man pages will not be generated.


-- Configuring incomplete, errors occurred!

**Comment by hunk3749** [comment]
sorry for above wrong reply but after installing newest version of armadillo i am getting this error-
dhanpal@dhanpal-HP-Pavilion-15-Notebook-PC:~/mlpack-2.0.3/build2$ cmake ../
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Found Armadillo: /usr/lib/libarmadillo.so (found suitable version "7.400.2", required is "4.100.0")
-- Armadillo libraries: /usr/lib/libarmadillo.so
CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1202 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.46.1

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.49 (or
  newer).

  The following Boost libraries could not be found:

          boost_program_options
          boost_unit_test_framework
          boost_serialization

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:213 (find_package)


-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp 
-- Found Git: /usr/bin/git 
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
CMake Warning at CMakeLists.txt:358 (message):
  txt2man not found; man pages will not be generated.


-- Configuring incomplete, errors occurred!

**Comment by zoq** [comment]
Your boost version is also outdated:

```
Boost version: 1.46.1

Boost include path: /usr/include

Detected version of Boost is too old. Requested version was 1.49 (or
newer).
```

you could use the version from: ``ppa:boost-latest/ppa``:

```
sudo add-apt-repository -y ppa:boost-latest/ppa
```

**Comment by hunk3749** [comment]
again i am getting the same error after following you and pasting sudo add-apt-repository -y ppa:boost-latest/ppa in my terminal iand getting this-dhanpal@dhanpal-HP-Pavilion-15-Notebook-PC:~$ sudo add-apt-repository -y ppa:boost-latest/ppa
[sudo] password for dhanpal: 
gpg: keyring `/tmp/tmphh4slP/secring.gpg' created
gpg: keyring `/tmp/tmphh4slP/pubring.gpg' created
gpg: requesting key 029DB5C7 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmphh4slP/trustdb.gpg: trustdb created
gpg: key 029DB5C7: public key "Launchpad boost-latest" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK

**Comment by zoq** [comment]
Looks like I've missed one step, you also have to update the boost package e.g.:

```
sudo apt-get install libboost-math-dev libboost-program-options-dev libboost-test-dev libboost-serialization-dev
```

**Comment by hunk3749** [comment]
do apt-get install libboost-math-dev libboost-program-options-dev libboost-test-dev libboost-serialization-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost-program-options-dev is already the newest version.
libboost-serialization-dev is already the newest version.
libboost-test-dev is already the newest version.
libboost-math-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
dhanpal@dhanpal-HP-Pavilion-15-Notebook-PC:~$

**Comment by zoq** [comment]
can you test:

```
sudo apt-get install libboost1.54-all-dev
```

**Comment by hunk3749** [comment]
sudo apt-get install libboost1.54-all-dev
[sudo] password for dhanpal: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libboost1.54-all-dev
E: Couldn't find any package by regex 'libboost1.54-all-dev'

**Comment by zoq** [comment]
hm, that's strange, I can't test it right now, but maybe you have to update the packages repo:

```
sudo apt-get update
sudo apt-get install libboost1.54-all-dev
```

**Comment by hunk3749** [comment]
thank you
please tell me how to build and install mlpack-2.0.3 because i unable to follow documentation instructions

**Comment by zoq** [comment]
So I was wondering if the ``4 not upgraded`` packages are the boost packages. Can you post the output of:

```
apt-get upgrade
```

**Comment by hunk3749** [comment]
i have successfully installed boost but while building mlpack and executing make command i am getting this error-
make
Scanning dependencies of target mlpack_arma_config
[  0%] Updating arma_config.hpp (if necessary)
-- Regenerating arma_config.hpp.
[  0%] Built target mlpack_arma_config
Scanning dependencies of target mlpack_headers
Moving header files to include/mlpack/
[  0%] Built target mlpack_headers
Scanning dependencies of target mlpack
[  0%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/discrete_distribution.cpp.o
In file included from /home/dhanpal/mlpack-2.0.3/src/mlpack/../mlpack/core.hpp:223:0,
                 from /home/dhanpal/mlpack-2.0.3/src/mlpack/core/dists/discrete_distribution.hpp:18,
                 from /home/dhanpal/mlpack-2.0.3/src/mlpack/core/dists/discrete_distribution.cpp:14:
/home/dhanpal/mlpack-2.0.3/src/mlpack/../mlpack/core/dists/gaussian_distribution.hpp:41:42: error: both ‘const’ and ‘constexpr’ cannot be used here
make[2]: *** [src/mlpack/CMakeFiles/mlpack.dir/core/dists/discrete_distribution.cpp.o] Error 1
make[1]: *** [src/mlpack/CMakeFiles/mlpack.dir/all] Error 2
make: *** [all] Error 2

**Comment by zoq** [comment]
That's an gcc issue (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54086) which was fixed in 4.7. So I think, you have to update your gcc version:

```
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install g++-4.8
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
export CC=gcc-4.8
export CXX=g++-4.8
```

rebuild mlpack (remove the build directory).

**Comment by hunk3749** [comment]
thank you very much

**Comment by rcurtin** [comment]
It seems this is resolved, so I will go ahead and close the issue.
