### ISSUE TITLE
pkg-config support?

### ISSUE THREAD

**Issue by eddelbuettel** [mlpack/mlpack#777]
I am currently building a small project against MLPACK and its library.  I use standard tools to 'find' where `libmlpack.so` may be installed.  

One solution that has emerged over the years is support for [pkg-config](https://en.wikipedia.org/wiki/Pkg-config).  This seems to have originated from the desktop world but is clearly used in other places.  Take for example [nlopt](http://ab-initio.mit.edu/wiki/index.php/NLopt) which has support:

```bash
edd@max:~$ pkg-config nlopt --cflags       # on Ubuntu, and headers in /usr/include

edd@max:~$ pkg-config nlopt --libs         # ditto, no -L needed
-lnlopt -lm
edd@max:~$ pkg-config nlopt --version      # useful for 'minimal version x.y.z ?' comp.
0.29.1
edd@max:~$ 
```

Getting these results back is way faster and easier than fiddling with `auto*` or `cmake`.  (There are older, one-off variants other projects have, i.e. `gsl-config` is very similar.  I will not name another big project starting with B and ending in oost for its awful alternative ;-) .) 

Here, [nlopt](http://ab-initio.mit.edu/wiki/index.php/NLopt) has [this file](https://github.com/stevengj/nlopt/blob/master/nlopt.pc.in) in its GitHub repo:

```make
prefix=@CMAKE_INSTALL_PREFIX@
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: NLopt
Description: nonlinear optimization libary
Version: @NLOPT_VERSION_STRING@
Libs: -L${libdir} -lnlopt@NLOPT_SUFFIX@ -lm
Cflags: -I${includedir}
```

and this paragraph in its [`CMakeLists.txt`](https://github.com/stevengj/nlopt/blob/master/CMakeLists.txt):

```cmake
# pkgconfig file
if (UNIX OR MINGW)
  configure_file (${CMAKE_CURRENT_SOURCE_DIR}/nlopt.pc.in ${CMAKE_CURRENT_BINARY_DIR}/nlopt.pc @ONLY)
  install (FILES ${CMAKE_CURRENT_BINARY_DIR}/nlopt.pc DESTINATION ${RELATIVE_INSTALL_LIB_DIR}/pkgconfig)
endif ()
```

I haven't `pkg-config`-ified a library myself, but would try to work up a pull request if you like the idea.  
Of course, you being fluent at CMake when I am not it would also be very nice if you just carried this over :)  It looks simple enough, and would be really useful.   Thoughts?

**Comment by rcurtin** [comment]
Yes, let me do this tomorrow or later this week.  I agree that pkg-config support would be nice.

**Comment by eddelbuettel** [comment]
Did you get a chance to look at this?

**Comment by rcurtin** [comment]
It turns out it's a little more complex than I had hoped.  I think I'll have a PR ready tomorrow.

**Comment by rcurtin** [comment]
With #782 merged this should be solved, and you should be able to use pkg-config when the next release of mlpack is done (a few weeks is what I expect for that).
