### ISSUE TITLE
"undefined reference" when complie "adaboost_test.cpp"

### ISSUE THREAD

**Issue by kc420** [mlpack/mlpack#779]
/usr/bin/ld: /tmp/ccQ9Gcrj.o: undefined reference to symbol '_ZN5boost7archive6detail17basic_iserializerC2ERKNS_13serialization18extended_type_infoE'
//usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.58.0: error adding symbols: DSO missing from command line

Compile option:
[cmd: ['g++', '/home/cwind/Downloads/tests/adaboost_test.cpp', '-std=c++11', '-o', '/home/cwind/Downloads/tests/adaboost_test', '-lmlpack', '-larmadillo']]

I try to compile the first file in "/tests", but can't make it..

**Comment by kc420** [comment]
I found that I should use cmake....
It seems that CMakeLists doesn't open c++11,  and I fixed it.
Then I encountered this:
[100%] Linking CXX executable mlpack_test
/usr/bin/ld: CMakeFiles/mlpack_test.dir/quic_svd_test.o: undefined reference to symbol 'wrapper_dgetri_'
//usr/lib/libarmadillo.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/mlpack_test.dir/build.make:1810: recipe for target 'mlpack_test' failed
make[2]: *** [mlpack_test] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mlpack_test.dir/all' failed
make[1]: *** [CMakeFiles/mlpack_test.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rcurtin** [comment]
Hi there, we need a lot more information on what you are doing before we can help. The mlpack CMake configuration does support C++11, so it seems possible that your modifications are what have caused the linking to fail. Have you seen the mlpack build tutorial? I would suggest following that.

**Comment by kc420** [comment]
I have built and installed mlpack follow the tutorial:
http://mlpack.org/docs/mlpack-2.0.3/doxygen.php?doc=build.html#build
Do you mean that?



When I build the tests without modification, error message shows:


Scanning dependencies of target mlpack_test
[  1%] Building CXX object CMakeFiles/mlpack_test.dir/mlpack_test.o
[  2%] Building CXX object CMakeFiles/mlpack_test.dir/adaboost_test.o
In file included from /usr/include/c++/5/cstdint:35:0,
                 from /usr/local/include/mlpack/prereqs.hpp:30,
                 from /usr/local/include/mlpack/core.hpp:207,
                 from /home/cwind/Desktop/Downloads/tests/adaboost_test.cpp:14:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /usr/local/include/mlpack/prereqs.hpp:65:0,
                 from /usr/local/include/mlpack/core.hpp:207,
                 from /home/cwind/Desktop/Downloads/tests/adaboost_test.cpp:14:



After I add this to CMakeLists:

include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
CHECK_CXX_COMPILER_FLAG("-std=c++0x" COMPILER_SUPPORTS_CXX0X)
if(COMPILER_SUPPORTS_CXX11)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
elseif(COMPILER_SUPPORTS_CXX0X)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
else()
        message(STATUS "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support. Please use a different C++ compiler.")
endif()

(I copied it from stackoverflow)

The error I've posted occurred after ran to 100%

**Comment by rcurtin** [comment]
Did you run cmake in the tests/ directory?  You should not do that; you should do it just as the guide says.  When you build mlpack, it will build `mlpack_test`, which you can then run in order to run the tests.

**Comment by kc420** [comment]
I have run the tests successfully.Thank you!
And I suggest add this test procedure to the build/install guide, so if we encountered an issue, we can make sure it's not about build/install.

**Comment by rcurtin** [comment]
e801f30 updates the documentation a bit; thanks for the suggestion!
