### ISSUE TITLE
unable to  build mlpack getting error while executing make command

### ISSUE THREAD

**Issue by hunk3749** [mlpack/mlpack#780]
make
Scanning dependencies of target mlpack_arma_config
[  0%] Updating arma_config.hpp (if necessary)
-- Regenerating arma_config.hpp.
[  0%] Built target mlpack_arma_config
Scanning dependencies of target mlpack_headers
Moving header files to include/mlpack/
[  0%] Built target mlpack_headers
Scanning dependencies of target mlpack
[  0%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/discrete_distribution.cpp.o
In file included from /home/dhanpal/mlpack-2.0.3/src/mlpack/../mlpack/core.hpp:223:0,
                 from /home/dhanpal/mlpack-2.0.3/src/mlpack/core/dists/discrete_distribution.hpp:18,
                 from /home/dhanpal/mlpack-2.0.3/src/mlpack/core/dists/discrete_distribution.cpp:14:
/home/dhanpal/mlpack-2.0.3/src/mlpack/../mlpack/core/dists/gaussian_distribution.hpp:41:42: error: both ‘const’ and ‘constexpr’ cannot be used here
make[2]: *** [src/mlpack/CMakeFiles/mlpack.dir/core/dists/discrete_distribution.cpp.o] Error 1
make[1]: *** [src/mlpack/CMakeFiles/mlpack.dir/all] Error 2
make: *** [all] Error 2

**Comment by rcurtin** [comment]
Hi, @zoq already gave you a response to this issue in #776. Please try what he suggested and don't open duplicate issues. Technically, this isn't even an issue---there is no bug in mlpack, you are using a too old compiler.
