### ISSUE TITLE
Error in running cmake command "$make", "No targets specified and no makefile found.  Stop." 

### ISSUE THREAD

**Issue by prashantkn94** [mlpack/mlpack#791]
Hi, I have been trying to Build mlpack on my pc following the steps given on this [http://www.mlpack.org/docs/mlpack-2.0.3/doxygen.php?doc=build.html] page.Everything was fine, all dependencis were installed and there were no errors till I had to run the command  "$ make" and the error message I got is "make: *** No targets specified and no makefile found.  Stop.". Please help me resolving the issue, Thanks.
Further Details:
OS - "Ubuntu   16.04"
I am trying to build - "stable mlpack-2.0.3"

**Comment by rcurtin** [comment]
Hi there Prashant,

Can you provide some more output on what you did?  My first guess is that you ran 'make' from the wrong directory.  If you can paste the CMake output too, that would probably be helpful.

**Comment by prashantkn94** [comment]
Thanks for the assistance,
This time I went into the build directory and ran "cmake ../" and the error I got is this.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Armadillo libraries: /usr/lib/libarmadillo.so
CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
  Unable to find the requested Boost libraries.
 Boost version: 1.58.0
 Boost include path: /usr/include
Could not find the following Boost libraries:
   boost_unit_test_framework
    boost_serialization
 Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:213 (find_package)
-- Could NOT find Git (missing:  GIT_EXECUTABLE) 
CMake Warning (dev) at src/mlpack/methods/neighbor_search/CMakeLists.txt:39 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "mlpack_knn".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/mlpack/methods/neighbor_search/CMakeLists.txt:47 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "mlpack_kfn".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/mlpack/methods/rann/CMakeLists.txt:42 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "mlpack_krann".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
CMake Warning at CMakeLists.txt:358 (message):
  txt2man not found; man pages will not be generated.
-- Configuring incomplete, errors occurred!
See also "/home/prashant/mlpack-2.0.3/build/CMakeFiles/CMakeOutput.log".
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
I tried installing boost through "sudo apt-get install libboost-all-dev", But after running "cmake" again the error was same as above. I guess cmake is unable to find the location of these boost libraries. Also SInce I am new to cmake I am assuming by "CMake output" you mean "CMakeOutput.log" ?? ,Anyways since the output is very long I am posting this pastebin [http://pastebin.com/rUGuFYyc] link.

**Comment by prashantkn94** [comment]
After running "sudo apt-get install cmake libblkid-dev e2fslibs-dev libboost-all-dev libaudit-dev" I was able to run cmake successfully This is the message I got:
-- Armadillo libraries: /usr/lib/libarmadillo.so
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
--   unit_test_framework
--   serialization
-- Could NOT find Git (missing:  GIT_EXECUTABLE) 
CMake Warning (dev) at src/mlpack/methods/neighbor_search/CMakeLists.txt:39 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "mlpack_knn".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/mlpack/methods/neighbor_search/CMakeLists.txt:47 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "mlpack_kfn".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/mlpack/methods/rann/CMakeLists.txt:42 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "mlpack_krann".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
CMake Warning at CMakeLists.txt:358 (message):
  txt2man not found; man pages will not be generated.


-- Configuring done
-- Generating done
-- Build files have been written to: /home/prashant/mlpack-2.0.3/build
 
But when I am runnign "cmake" after this I am getting this error:
cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.

Please let me know what am I missing here.Thanks very much.

**Comment by rcurtin** [comment]
Ok, great, glad you got it worked out! :)
