### ISSUE TITLE
need help getting this installed on a Mac

### ISSUE THREAD

**Issue by vbilaniuk** [mlpack/mlpack#793]
Hello!  I successfully installed the dependencies on a Mac (and I've compiled programs using them so I know they work), and I even managed to install mlpack without error using cmake, however when I try to compile one of the sample programs, I get this error:

/usr/local/include/mlpack/core/data/serialization_shim.hpp:48:56: error: a space is required between consecutive right angle brackets (use '> >')
            typename boost::enable_if<boost::is_class<U>>::type*,

Actually, I get many errors similar to that, until it gives up and quits (fatal error: too many errors emitted, stopping now [-ferror-limit=]).  It basically dies on nearly every line in every mlpack header.

I googled and found very little on this, except another project that ran into a similar issue:
https://github.com/symengine/symengine/issues/344

I just haven't the faintest idea how to do what they did.

I'm presently using Clang version 7.3.0, recently downgraded from 8 because 8 breaks CUDA :-(

I'm willing to entertain the idea of installing gcc (or an even older Clang) if it's possible to do that without completely breaking everything that's already installed and working with Clang.  But I'm really hoping someone here has seen this before and knows what to do.

**Comment by rcurtin** [comment]
Hi there Vicky,

Try adding `-std=c++11` to the command-line when you compile your program (or possibly `-std=c++0x` depending on how old the compiler is).  Does that help?

Thanks,
Ryan

**Comment by vbilaniuk** [comment]
On 2016-09-27 8:26 PM, Ryan Curtin
      wrote:
    
    
      Hi there Vicky,
      Try adding -std=c++11 to the command-line when
        you compile your program (or possibly -std=c++0x
        depending on how old the compiler is). Does that help?
      Thanks,
        Ryan
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mlpack/mlpack","title":"mlpack/mlpack","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mlpack/mlpack"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rcurtin in #793: Hi there Vicky,\r\n\r\nTry adding `-std=c++11` to the command-line when you compile your program (or possibly `-std=c++0x` depending on how old the compiler is).  Does that help?\r\n\r\nThanks,\r\nRyan"}],"action":{"name":"View Issue","url":"https://github.com/mlpack/mlpack/issues/793#issuecomment-250038061"}}}
    
    
    Hello, thanks so much for your help!  This ended up working:
    
    g++ myprogram.cpp -o myprogram -O2 -larmadillo -std=c++11 -lmlpack
    
    Vicky

**Comment by rcurtin** [comment]
Great, glad to hear you got it worked out. :)
