### ISSUE TITLE
`target_compile_features` from NewCXX11.cmake produce an error with LLVM's clang

### ISSUE THREAD

**Issue by thejonan** [mlpack/mlpack#796]
Trying to build mlpack with OpenMP support on MacOS X (10.11.6) led me to using [llvm](http://www.llvm.org)'s clang (installed via [Homebrew](http://brew.sh) ). With appropriate `cmake` command that almost worked:

```
LDFLAGS=-L/usr/local/opt/llvm/lib CFLAGS=-I/usr/local/opt/llvm/include CPPFLAGS=-I/usr/local/opt/llvm/include\ -std=c++0x cmake -D CMAKE_C_COMPILER=clang-omp -D CMAKE_CXX_COMPILER=clang-omp++ ../
```

(`clang-omp` and `clang-omp++` are symlinks to llvm's binaries).

However, there was an error referring to `target_compile_features` directive in `CMake/NewCXX11.cmake` file:

```
CMake Error at CMake/NewCXX11.cmake:4 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "Clang"

  version 3.8.1.
```

**Comment by rcurtin** [comment]
Ugh: http://stackoverflow.com/questions/28119552/no-known-features-for-cxx-compiler-when-compiling-with-msvc-2013

Looks like what I will have to do is add a flag you can specify to CMake to force CMake to believe that the compiler is a C++11 compiler and bypass the check in `NewCXX11.cmake`.

**Comment by thejonan** [comment]
Sounds like it can help. However, I've tried manually adding the `-std=c++11` flag to `CPPFLAGS` when invoking `cmake`. No success.

**Comment by thejonan** [comment]
Sorry, I've just made another test and this time it worked, so _yes_ your suggestion will do the job.

Here's what I did:
- Commented NewCXX11.cmake inclusion as before
- Added `-D "CMAKE_CXX_FLAGS=-I/usr/local/opt/llvm/include -std=c++11"` to cmake-'s arguments.

**Comment by rcurtin** [comment]
Yep, that will work.  I am writing up a patch now to make this easier and I will let you know when it's done and how it works.

**Comment by rcurtin** [comment]
Okay, I added some changes that should fix this issue.  If the compiler is not detected as a valid C++11 compiler, you can do specify the `-DFORCE_CXX11=ON` option and that will force CMake to treat the C++ compiler as having valid C++11 support.  You may also need to specify extra CXXFLAGS like with `-DCMAKE_CXX_FLAGS="-std=c++11"` or something like that.  Let me know if there are any problems with that.

**Comment by thejonan** [comment]
Successfully building. Thanks.
