### ISSUE TITLE
Building mlpack with llvm's clang yields template parenthesis error

### ISSUE THREAD

**Issue by thejonan** [mlpack/mlpack#797]
While trying to build mlpack wth OpenMP support using [llvm](http://www.llvm.org)'s `clang` compiler on MacOS 10.11.6 (refer to issue #796), and after commenting the NewCXX11.cmake directive to avoid the `cmake`'s error. The building process starts, but with the following error:

```
In file included from /Users/jonan/CCC/IDEAConsult/ExCAPE/libs/mlpack/src/mlpack/../mlpack/core/data/load_arff.hpp:54:
/Users/jonan/CCC/IDEAConsult/ExCAPE/libs/mlpack/src/mlpack/../mlpack/core/data/load_arff_impl.hpp:46:66: error: a space is required
      between consecutive right angle brackets (use '> >')
      typedef boost::tokenizer<boost::escaped_list_separator<char>> Tokenizer;
                                                                 ^~
                                                                 > >
```

**Comment by rcurtin** [comment]
This should be fixed if you use the `FORCE_CXX11` CMake option and set `CMAKE_CXX_FLAGS` to include `-std=c++11`.
