### ISSUE TITLE
Possible OpenMP parallelization issues in LSHSearch implementation

### ISSUE THREAD

**Issue by thejonan** [mlpack/mlpack#801]
I've accidentally stumbled on this. In the `lsh_search_impl.hpp` file, method 

```
void LSHSearch<SortPolicy>::Search()
```

there is this OpenMP statement:

```
  #pragma omp parallel for \
      shared(resultingNeighbors, distances) \
      schedule(dynamic)\
      reduction(+:avgIndicesReturned)
```

which is all fine, except that shared variables are not explicitly protected against racing conditions, namely the `BaseCase` method which actually modifies them, lacks any `#pragma atomic` or `#pragma critical` directives (both implementation of this method in the same file).

**Comment by rcurtin** [comment]
I don't think this is an issue because that parallel for loop is over the queries.  Each call to `BaseCase()` can only affect one column of the `resultingNeighbors` and `distances` variables, and `BaseCase()` will not be called with the same index `i` by two different threads.

**Comment by thejonan** [comment]
Oh, yes, I see. This is potentially prone to errors with different matrix implementations, I guess.
