### ISSUE TITLE
DET documentation error

### ISSUE THREAD

**Issue by thejonan** [mlpack/mlpack#805]
In the documentation for DET (http://www.mlpack.org/docs/mlpack-git/doxygen.php?doc=dettutorial.html) it says:

> Note that the logarithm of the density estimates are saved; this allows smaller values to be saved.

While, the actual code is like this:

```
return std::exp(std::log(ratio) - logVolume)
```

Which, is essentially equal to `ration / Volume`, without the logarithm part.

**Comment by rcurtin** [comment]
I agree---fixed in 0a7fd0e.

**Comment by thejonan** [comment]
Thanks.
