### ISSUE TITLE
install warning, should be ignored?

### ISSUE THREAD

**Issue by gmcather** [mlpack/mlpack#806]
in the process of installing, some warning happens, should it be ignored?

/home/yao/work/mlpack/src/mlpack/tests/ub_tree_test.cpp: In member function ‘void UBTreeTest::SingleTreeTraverserTest::test_method()’:
/home/yao/work/mlpack/src/mlpack/tests/ub_tree_test.cpp:307:40: warning: ‘mlpack::neighbor::NeighborSearch<SortPolicy, MetricType, MatType, TreeType, DualTreeTraversalType, SingleTreeTraversalType>::NeighborSearch(const MatType&, bool, bool, double, MetricType) [with SortPolicy = mlpack::neighbor::NearestNeighborSort; MetricType = mlpack::metric::LMetric<2, true>; MatType = arma::Mat<double>; TreeType = mlpack::tree::UBTree; DualTreeTraversalType = mlpack::tree::BinarySpaceTree<mlpack::metric::LMetric<2, true>, mlpack::neighbor::NeighborSearchStatmlpack::neighbor::NearestNeighborSort, arma::Mat<double>, mlpack::bound::CellBound, mlpack::tree::UBTreeSplit>::DualTreeTraverser; SingleTreeTraversalType = mlpack::tree::BinarySpaceTree<mlpack::metric::LMetric<2, true>, mlpack::neighbor::NeighborSearchStatmlpack::neighbor::NearestNeighborSort, arma::Mat<double>, mlpack::bound::CellBound, mlpack::tree::UBTreeSplit>::SingleTreeTraverser]’ is deprecated [-Wdeprecated-declarations]
       UBTree> knn1(dataset, false, true);
                                        ^
In file included from /home/yao/work/mlpack/src/mlpack/../mlpack/methods/neighbor_search/neighbor_search.hpp:597:0,
                 from /home/yao/work/mlpack/src/mlpack/tests/ub_tree_test.cpp:3:
/home/yao/work/mlpack/src/mlpack/../mlpack/methods/neighbor_search/neighbor_search_impl.hpp:248:1: note: declared here
 NeighborSearch<SortPolicy, MetricType, MatType, TreeType, DualTreeTraversalType
 ^
/home/yao/work/mlpack/src/mlpack/tests/ub_tree_test.cpp:312:31: warning: ‘mlpack::neighbor::NeighborSearch<SortPolicy, MetricType, MatType, TreeType, DualTreeTraversalType, SingleTreeTraversalType>::NeighborSearch(const MatType&, bool, bool, double, MetricType) [with SortPolicy = mlpack::neighbor::NearestNeighborSort; MetricType = mlpack::metric::LMetric<2, true>; MatType = arma::Mat<double>; TreeType = mlpack::tree::KDTree; DualTreeTraversalType = mlpack::tree::BinarySpaceTree<mlpack::metric::LMetric<2, true>, mlpack::neighbor::NeighborSearchStatmlpack::neighbor::NearestNeighborSort, arma::Mat<double>, mlpack::bound::HRectBound, mlpack::tree::MidpointSplit>::DualTreeTraverser; SingleTreeTraversalType = mlpack::tree::BinarySpaceTree<mlpack::metric::LMetric<2, true>, mlpack::neighbor::NeighborSearchStatmlpack::neighbor::NearestNeighborSort, arma::Mat<double>, mlpack::bound::HRectBound, mlpack::tree::MidpointSplit>::SingleTreeTraverser]’ is deprecated [-Wdeprecated-declarations]
   KNN knn2(dataset, true, true);
                               ^
In file included from /home/yao/work/mlpack/src/mlpack/../mlpack/methods/neighbor_search/neighbor_search.hpp:597:0,
                 from /home/yao/work/mlpack/src/mlpack/tests/ub_tree_test.cpp:3:
/home/yao/work/mlpack/src/mlpack/../mlpack/methods/neighbor_search/neighbor_search_impl.hpp:248:1: note: declared here
 NeighborSearch<SortPolicy, MetricType, MatType, TreeType, DualTreeTraversalType
 ^
/home/yao/work/mlpack/src/mlpack/tests/ub_tree_test.cpp: In member function ‘void UBTreeTest::DualTreeTraverserTest::test_method()’:
/home/yao/work/mlpack/src/mlpack/tests/ub_tree_test.cpp:334:41: warning: ‘mlpack::neighbor::NeighborSearch<SortPolicy, MetricType, MatType, TreeType, DualTreeTraversalType, SingleTreeTraversalType>::NeighborSearch(const MatType&, bool, bool, double, MetricType) [with SortPolicy = mlpack::neighbor::NearestNeighborSort; MetricType = mlpack::metric::LMetric<2, true>; MatType = arma::Mat<double>; TreeType = mlpack::tree::UBTree; DualTreeTraversalType = mlpack::tree::BinarySpaceTree<mlpack::metric::LMetric<2, true>, mlpack::neighbor::NeighborSearchStatmlpack::neighbor::NearestNeighborSort, arma::Mat<double>, mlpack::bound::CellBound, mlpack::tree::UBTreeSplit>::DualTreeTraverser; SingleTreeTraversalType = mlpack::tree::BinarySpaceTree<mlpack::metric::LMetric<2, true>, mlpack::neighbor::NeighborSearchStatmlpack::neighbor::NearestNeighborSort, arma::Mat<double>, mlpack::bound::CellBound, mlpack::tree::UBTreeSplit>::SingleTreeTraverser]’ is deprecated [-Wdeprecated-declarations]
       UBTree> knn1(dataset, false, false);
                                         ^
In file included from /home/yao/work/mlpack/src/mlpack/../mlpack/methods/neighbor_search/neighbor_search.hpp:597:0,
                 from /home/yao/work/mlpack/src/mlpack/tests/ub_tree_test.cpp:3:
/home/yao/work/mlpack/src/mlpack/../mlpack/methods/neighbor_search/neighbor_search_impl.hpp:248:1: note: declared here
 NeighborSearch<SortPolicy, MetricType, MatType, TreeType, DualTreeTraversalType
 ^
/home/yao/work/mlpack/src/mlpack/tests/ub_tree_test.cpp:339:31: warning: ‘mlpack::neighbor::NeighborSearch<SortPolicy, MetricType, MatType, TreeType, DualTreeTraversalType, SingleTreeTraversalType>::NeighborSearch(const MatType&, bool, bool, double, MetricType) [with SortPolicy = ml

**Comment by rcurtin** [comment]
Yeah, this is just because a test was using a deprecated function.  You can ignore the warning.  It will be fixed as soon as I merge #768, which should happen today.
