### ISSUE TITLE
How to organize the data?

### ISSUE THREAD

**Issue by illidanswp** [mlpack/mlpack#809]
I'd like to use the hmm tools, the problem is how to organize the data in the training file. My data is a sequence of 3-dimension points as one input. If the file is written like this
1, 2, 3
4, 5, 6 ...
it will be treated as many inputs of 3-integer sequence, but what I want is something like this
(1,2,3), (4,5,6),(7.8,9)
(11,12,13),(14,15,16),(17,18,19) ...
Please help

**Comment by illidanswp** [comment]
I'd like to use the hmm tools, the problem is how to organize the data in the training file. My data is a sequence of 3-dimension points as one input. If the file is written like this
`1, 2, 3
4, 5, 6
...`
it will be treated as many inputs of 3-integer sequence, but what I want is something like this
`(1,2,3), (4,5,6),(7.8,9)
(11,12,13),(14,15,16),(17,18,19)
...`
Please help

**Comment by rcurtin** [comment]
Hi there,

If you are using a discrete distribution (`--type discrete`), then multidimensional observations aren't supported.  It would not be impossible to support multidimensional discrete distributions (but there will be no relation between dimensions), but currently the code doesn't do that.  I think that we should leave this issue open until multidimensional support is added for HMMs.  For now, you might consider "collapsing" your dimensions: suppose that each of your three dimensions takes values between 0 and 7 (so, 3 bits).  Then given `(a, b, c)` you map to a single-dimension value of `2^6 * a + 2^3 * b + c`.  That will cost performance but it will be a workaround for now.  You could also use a Gaussian HMM if the dimensions are not categorical (`--type gaussian`).

Sorry that the support you are looking for is currently not there.

**Comment by illidanswp** [comment]
Hi, thank you for your suggestion. Indeed I'm  intending to use gmm type, it supports mulidimension, right? So would you please tell me how to write my input file so that each row will be treated as an observed sequence of several 3-dimension points? Btw, I am working with command-line programs, so I need to write my data in a file.

**Comment by rcurtin** [comment]
Ah, okay, sorry that I misunderstood the question.  Glad that you got it figured out---feel free to ask any questions in the future if you have them.  I'll go ahead and close the issue and then open a new issue for the multidimensional discrete distribution.

**Comment by rcurtin** [comment]
Handled by #830, so now git master branch and the next release of mlpack will support multidimensional discrete distributions like you are looking for.  Thanks @MikeLing!
