### ISSUE TITLE
Missing "mlpack/mlpack_export.hpp"

### ISSUE THREAD

**Issue by gkalman1** [mlpack/mlpack#819]
One cannot compile master branch, or any real part of it, because "mlpack_export.hpp" is not in the repository.

**Comment by gkalman1** [comment]
Sorry, kill this. I am having CMake issues.

**Comment by rcurtin** [comment]
Glad to hear you got it working; if you find problematic documentation or something misleading that caused you to have this problem, feel free to open another issue and we can look into it.
