### ISSUE TITLE
Implementation of ne_test.cpp.

### ISSUE THREAD

**Issue by yanjundream** [mlpack/mlpack#822]
Hi, this is jun and I am doing something about NEAT but I am a newer in this field. The tutorial of "Summary of Neuroevolution Algorithms Implementation" is very nice. However I still do not know how to use mlpack to run the ne_test.cpp program. Could you give some more clue to do that? Thanks!

**Comment by zoq** [comment]
Hello, writing tests in mlpack is done with the Boost Unit Test Framework: http://www.boost.org/doc/libs/1_58_0/libs/test/doc/html/utf.html If you make a test suite called "TestSuite" (BOOST_AUTO_TEST_SUITE(TestSuite)), and then build ``mlpack_test`` (``make mlpack_test``), you can run only the tests in that test suite with ``bin/mlpack_test -t TestSuite``. A specific test case called 'TestCase' (BOOST_AUTO_TEST_CASE(TestCase)) could be run with 'bin/mlpack_test -t TestSuite/TestCase'.

So once you build Bang's ne branch you can run the complete test suite "NETest" with ``bin/mlpack_test -t NETest`` and the NEAT xor test case with ``bin/mlpack_test -t NETest/NENeatXorTest``. Let us know if that helps and if we should clarify anything.

**Comment by Lakshya1605** [comment]
Is this still open if yes i would like to work on it . Thank You!!!

**Comment by zoq** [comment]
Hello @Lakshya1605, this isn't an actual issue since the test already exists and the point was to figure out how to run the test suite.
