### ISSUE TITLE
Link not working in Building mlpack Under Windows

### ISSUE THREAD

**Issue by yashu-seth** [mlpack/mlpack#829]
@keonkim's link in [Building mlpack Under Windows](https://github.com/mlpack/mlpack/wiki/WindowsBuild) is not working. Can someone please help me with building mlpack under windows.

The not working link is - http://keon.io/mlpack-on-windows.html

**Comment by Kirizaki** [comment]
Hi, try this link: https://overdosedblog.wordpress.com/2016/08/15/once_again/

**Comment by rcurtin** [comment]
Looks like Keon's link changed to http://keon.io/2016/06/04/mlpack-on-windows.html. I've updated the wiki. @kirizaki: nice page, can I add it to the wiki too? :)

**Comment by Kirizaki** [comment]
Sure!

**Comment by yashu-seth** [comment]
@Kirizaki @rcurtin Thanks. Can I use any environment other than visual studio 2015 like eclipse?

**Comment by keonkim** [comment]
oops sorry, I changed the blog template

**Comment by rcurtin** [comment]
The link is fixed now so I am going to go ahead and close the issue.
