### ISSUE TITLE
I want to try Naive Bayes and Random forest, but they aren't in mlpack, Is it useful to implete  them? 

### ISSUE THREAD

**Issue by hongguangguo** [mlpack/mlpack#837]
If yes, I would like to contribute .

**Comment by rcurtin** [comment]
Hi there, Naive Bayes is in mlpack; see the `mlpack_nbc` program or `src/mlpack/methods/naive_bayes/`.  Random forests are not implemented yet but I need them for a paper I am working on so I am trying to implement them.  If there is some other technique you would like to implement, please do feel free to contribute it.
