### ISSUE TITLE
Cannot build mlpack

### ISSUE THREAD

**Issue by Lakshya1605** [mlpack/mlpack#838]
Hi, 
Sorry if I'm overlooking something.But when i am trying to build mlpack i am facing the following error.
Though this issue is same as #804 , i have tried all possible methods mentioned there but still this problem exists.Please help me out.

[ 25%] Linking CXX executable ../../../../bin/mlpack_preprocess_split
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o: In function `boost::program_options::typed_value<std::string, char>::xparse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&) const':
preprocess_split_main.cpp:(.text._ZNK5boost15program_options11typed_valueISscE6xparseERNS_3anyERKSt6vectorISsSaISsEE[_ZNK5boost15program_options11typed_valueISscE6xparseERNS_3anyERKSt6vectorISsSaISsEE]+0x19): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o: In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::string const&, std::string const&, int)':
preprocess_split_main.cpp:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKSsS4_i[_ZN5boost15program_options16validation_errorC5ENS1_6kind_tERKSsS4_i]+0x31): undefined reference to `boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)'
preprocess_split_main.cpp:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKSsS4_i[_ZN5boost15program_options16validation_errorC5ENS1_6kind_tERKSsS4_i]+0x49): undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::string const&, std::string const&, std::string const&, int)'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o: In function `boost::program_options::typed_value<std::string, char>::name() const':
preprocess_split_main.cpp:(.text._ZNK5boost15program_options11typed_valueISscE4nameEv[_ZNK5boost15program_options11typed_valueISscE4nameEv]+0x29): undefined reference to `boost::program_options::arg'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o: In function `boost::program_options::typed_value<double, char>::name() const':
preprocess_split_main.cpp:(.text._ZNK5boost15program_options11typed_valueIdcE4nameEv[_ZNK5boost15program_options11typed_valueIdcE4nameEv]+0x29): undefined reference to `boost::program_options::arg'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o: In function `void boost::program_options::validate<double, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, double*, long)':
preprocess_split_main.cpp:(.text._ZN5boost15program_options8validateIdcEEvRNS_3anyERKSt6vectorISbIT0_St11char_traitsIS5_ESaIS5_EESaIS9_EEPT_l[_ZN5boost15program_options8validateIdcEEvRNS_3anyERKSt6vectorISbIT0_St11char_traitsIS5_ESaIS5_EESaIS9_EEPT_l]+0x3ac): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o:(.rodata._ZTVN5boost15program_options16validation_errorE[_ZTVN5boost15program_options16validation_errorE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o:(.rodata._ZTVN5boost15program_options20invalid_option_valueE[_ZTVN5boost15program_options20invalid_option_valueE]+0x30): more undefined references to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const' follow
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o:(.rodata._ZTVN5boost15program_options11typed_valueISscEE[_ZTVN5boost15program_options11typed_valueISscEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o:(.rodata._ZTVN5boost15program_options11typed_valueIdcEE[_ZTVN5boost15program_options11typed_valueIdcEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../../../../lib/libmlpack.so.2.1: undefined reference to `boost::program_options::to_internal(std::string const&)'
../../../../lib/libmlpack.so.2.1: undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
../../../../lib/libmlpack.so.2.1: undefined reference to `boost::program_options::detail::cmdline::set_additional_parser(boost::function1<std::pair<std::string, std::string>, std::string const&>)'
../../../../lib/libmlpack.so.2.1: undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::string, std::allocator<std::string> > const&)'
../../../../lib/libmlpack.so.2.1: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
collect2: error: ld returned 1 exit status
src/mlpack/methods/preprocess/CMakeFiles/mlpack_preprocess_split.dir/build.make:99: recipe for target 'bin/mlpack_preprocess_split' failed
make[2]: *** [bin/mlpack_preprocess_split] Error 1
CMakeFiles/Makefile2:887: recipe for target 'src/mlpack/methods/preprocess/CMakeFiles/mlpack_preprocess_split.dir/all' failed
make[1]: *** [src/mlpack/methods/preprocess/CMakeFiles/mlpack_preprocess_split.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rcurtin** [comment]
Can you tell me more about your system?  What OS?

What's the output when you ran `cmake` to configure the project?

And can you run `VERBOSE=1 make` and paste the output?

**Comment by Lakshya1605** [comment]
> Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

After runnig cmake -D DEBUG=OFF -D PROFILE=OFF ../ 
the output is as below 

> 

 -- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Armadillo: /usr/lib/libarmadillo.so (found suitable version "6.500.5", minimum required is "4.200.0") 
-- Armadillo libraries: /usr/lib/libarmadillo.so
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
--   unit_test_framework
--   serialization
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Regenerating arma_config.hpp.
CMake Warning (dev) at src/mlpack/methods/neighbor_search/CMakeLists.txt:37 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "mlpack_knn".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/mlpack/methods/neighbor_search/CMakeLists.txt:45 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "mlpack_kfn".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/mlpack/methods/rann/CMakeLists.txt:42 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "mlpack_krann".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
CMake Warning at CMakeLists.txt:442 (message):
  txt2man not found; man pages will not be generated.


-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lakshya/mlpack-2.1.0/build

After running VERBOSE=1 make
 

> [ 25%] Linking CXX executable ../../../../bin/mlpack_preprocess_split
cd /home/lakshya/mlpack-2.1.0/build/src/mlpack/methods/preprocess && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/mlpack_preprocess_split.dir/link.txt --verbose=1
/usr/bin/c++    -Wall -Wextra -ftemplate-depth=1000 -O3 -fopenmp   CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o  -o ../../../../bin/mlpack_preprocess_split -Wl,-rpath,/home/lakshya/mlpack-2.1.0/build/lib: -rdynamic ../../../../lib/libmlpack.so.2.1 -lrt -larmadillo -lboost_program_options -lboost_unit_test_framework -lboost_serialization 
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o: In function `boost::program_options::typed_value<std::string, char>::xparse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&) const':
preprocess_split_main.cpp:(.text._ZNK5boost15program_options11typed_valueISscE6xparseERNS_3anyERKSt6vectorISsSaISsEE[_ZNK5boost15program_options11typed_valueISscE6xparseERNS_3anyERKSt6vectorISsSaISsEE]+0x19): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o: In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::string const&, std::string const&, int)':
preprocess_split_main.cpp:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKSsS4_i[_ZN5boost15program_options16validation_errorC5ENS1_6kind_tERKSsS4_i]+0x31): undefined reference to `boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)'
preprocess_split_main.cpp:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKSsS4_i[_ZN5boost15program_options16validation_errorC5ENS1_6kind_tERKSsS4_i]+0x49): undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::string const&, std::string const&, std::string const&, int)'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o: In function `boost::program_options::typed_value<std::string, char>::name() const':
preprocess_split_main.cpp:(.text._ZNK5boost15program_options11typed_valueISscE4nameEv[_ZNK5boost15program_options11typed_valueISscE4nameEv]+0x29): undefined reference to `boost::program_options::arg'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o: In function `boost::program_options::typed_value<double, char>::name() const':
preprocess_split_main.cpp:(.text._ZNK5boost15program_options11typed_valueIdcE4nameEv[_ZNK5boost15program_options11typed_valueIdcE4nameEv]+0x29): undefined reference to `boost::program_options::arg'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o: In function `void boost::program_options::validate<double, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, double*, long)':
preprocess_split_main.cpp:(.text._ZN5boost15program_options8validateIdcEEvRNS_3anyERKSt6vectorISbIT0_St11char_traitsIS5_ESaIS5_EESaIS9_EEPT_l[_ZN5boost15program_options8validateIdcEEvRNS_3anyERKSt6vectorISbIT0_St11char_traitsIS5_ESaIS5_EESaIS9_EEPT_l]+0x3ac): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o:(.rodata._ZTVN5boost15program_options16validation_errorE[_ZTVN5boost15program_options16validation_errorE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o:(.rodata._ZTVN5boost15program_options20invalid_option_valueE[_ZTVN5boost15program_options20invalid_option_valueE]+0x30): more undefined references to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const' follow
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o:(.rodata._ZTVN5boost15program_options11typed_valueISscEE[_ZTVN5boost15program_options11typed_valueISscEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o:(.rodata._ZTVN5boost15program_options11typed_valueIdcEE[_ZTVN5boost15program_options11typed_valueIdcEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../../../../lib/libmlpack.so.2.1: undefined reference to `boost::program_options::to_internal(std::string const&)'
../../../../lib/libmlpack.so.2.1: undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
../../../../lib/libmlpack.so.2.1: undefined reference to `boost::program_options::detail::cmdline::set_additional_parser(boost::function1<std::pair<std::string, std::string>, std::string const&>)'
../../../../lib/libmlpack.so.2.1: undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::string, std::allocator<std::string> > const&)'
../../../../lib/libmlpack.so.2.1: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
collect2: error: ld returned 1 exit status
src/mlpack/methods/preprocess/CMakeFiles/mlpack_preprocess_split.dir/build.make:99: recipe for target 'bin/mlpack_preprocess_split' failed
make[2]: *** [bin/mlpack_preprocess_split] Error 1
make[2]: Leaving directory '/home/lakshya/mlpack-2.1.0/build'
CMakeFiles/Makefile2:887: recipe for target 'src/mlpack/methods/preprocess/CMakeFiles/mlpack_preprocess_split.dir/all' failed
make[1]: *** [src/mlpack/methods/preprocess/CMakeFiles/mlpack_preprocess_split.dir/all] Error 2
make[1]: Leaving directory '/home/lakshya/mlpack-2.1.0/build'
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
lakshya\  build $

**Comment by rcurtin** [comment]
Thanks for the output.  I don't see anything immediately wrong but we can keep digging. :) Can you tell me how you installed boost on this system?

**Comment by Lakshya1605** [comment]
Using "sudo apt-get install libboost-all-dev" command

**Comment by rcurtin** [comment]
Do you have another version of boost installed in /usr/local/lib/ or anything?  See if you can find a copy of libboost_program_options.so somewhere else on your system, maybe the linker is using that one by accident.  Is it possible you updated your system while building?  That might cause an issue.

**Comment by Lakshya1605** [comment]
No i don't think there is any copy because "locate libboost_program_options.so " returns only a single result "/usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.58.0" and yes i think i updated the system while building

**Comment by rcurtin** [comment]
If you updated the system while building, can you remove the entire build directory and start over?  That may be the issue.

**Comment by Lakshya1605** [comment]
Tried removing the entire build directory and start over but it doesn't work .I think there is some problem in my system , Working fine in Virtual Box though thank you.

**Comment by rcurtin** [comment]
Ok, good to hear you got it sorted out. I'm going to go ahead and close this issue then.

**Comment by Lakshya1605** [comment]
@rcurtin  Sorry but i am not sure where to post this also i don't want to spam the issue tracker with questions like this but can you please help me out .Whenever i try to send mail to mailing list i get error like the below .

Delivery to the following recipient failed permanently:

     mlpack@cc.gatech.edu

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain cc.gatech.edu by mxip2a.gatech.edu. [130.207.160.232].

The error that the other server returned was:
550 #5.1.0 Address rejected.


----- Original message -----

DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20161025;
        h=mime-version:from:date:message-id:subject:to;
        bh=9dtwOh0Qd8issXNcZd+g6MoWsI/lsQab6gk6D47fEqo=;
        b=RePxX2g83qbv0WlsSa3G29P9aTCCZN13Go+Ds3wJXitMkElVYCakX6FfbtTcEJyRyq
         +vVaW8EO67IzmghVKjhswcQNsRhu6VvbMLSwZOmb6C8Tc7lXziOykVpx7QIh++GAPv0T
         oCjVq5zIghQC3AkbiQ6zLNcZql7O9XGMLWWy+1Mb8EgnR++XZatZlA3F8jClRX7Hp576
         LV675F6AOInWB3I0GzEO1lV9N76PZNH7awnL0Ij+z1Rq3ljZWGnfn4LCsafFASbWlhsC
         Fbt5LFvio3gVRIxhmQ4kDrcOWuKrQWVFI8gMnhq4WUgQskKhGrnn+b6dCLkiqP9L/6J4
         Zh6g==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
        bh=9dtwOh0Qd8issXNcZd+g6MoWsI/lsQab6gk6D47fEqo=;
        b=VIH2xzKxjTsFad4QX6Ri1RuPqKwVOGtOeth2KdjDm20h2ozId+p7dnjDkHYlKKuAWj
         N2QK8pFg/9XQEzYO+E10djmPeeILrK74P4aqWCz3QFqaF0qQkGQTJTd0VH5/ypwWYrxP
         RZJZ9Dl+wCMsXTU1b8aq6tg+42CxLZlyS1FGnvTWTuMLI0olrsGHO72pNWoN9fsRIGdT
         iOOn/1ybI2VkyXtQ4uuLoBPeZakSpVhvlEENOJ8ZW/KXxj1iJAyzIlGv1OKtGXERGnHA
         W//2C43snpMzTkNAgbBo2oAr8vobGstUA9y8/VYlNNmwFRqGfKCJKhjGrhwzNPlOxCPb
         5tzQ==
X-Gm-Message-State: AIkVDXK8qRd435zjoDxRtx+cQ+CEE5VcObnvlo67fPo9nW5a+mUbXc0iP4sYFEBiZRGVXzMbhWdQn6eNhbmdXQ==
X-Received: by 10.202.71.131 with SMTP id u125mr4606792oia.170.1482394259667;
 Thu, 22 Dec 2016 00:10:59 -0800 (PST)
MIME-Version: 1.0
Received: by 10.157.24.113 with HTTP; Thu, 22 Dec 2016 00:10:59 -0800 (PST)
From: Lakshya Agrawal <zeeshan.lakshya@gmail.com>
Date: Thu, 22 Dec 2016 13:40:59 +0530
Message-ID: <CAE0ivFzziQBkRWfjyGcQw71jB4ULNWVy79O3+uuMKCUeWcN5aw@mail.gmail.com>
Subject: Getting Started
To: mlpack@cc.gatech.edu
Content-Type: multipart/alternative; boundary=001a113e54f643bf5505443acf78

**Comment by rcurtin** [comment]
Sorry, the links were wrong. The mlpack mailing lists have moved to http://lists.mlpack.org/mailman/listinfo/mlpack and http://lists.mlpack.org/mailman/listinfo/mlpack-git .

Note that you must be subscribed to the list to send a post.

I updated the website and repository to ensure all the links are up to date. Sorry about the confusion.
