### ISSUE TITLE
Is there a recommended plotting library?

### ISSUE THREAD

**Issue by mas-dse-greina** [mlpack/mlpack#843]
It doesn't look like mlpack plots figures (e.g. plotting the linear regression).

Can anyone recommend good C++ packages they use with their mlpack work?

Thanks.
-Tony

**Comment by rcurtin** [comment]
Hi Tony,

You're right, mlpack doesn't plot figures.  Typically if I need figures I'll import data into Octave or something like that to plot with.  Other options might be to use gnuplot's C++ interface (http://gnuplot.sourceforge.net/links.html) or maybe something in this list: http://stackoverflow.com/questions/296199/is-there-any-out-of-the-box-2d-3d-plotting-library-for-c

Hopefully something in there is helpful. :)

**Comment by mas-dse-greina** [comment]
Thanks Ryan. I can get gnuplot to work well when I run from a standard console C++ program, but am having trouble using wxWidgets with it. I'm guessing that wxWidgets is suppressing the console window that gnuplot wants to print to. I'll keep at it to see if I can find the work around. If you can think of anything, please send it my way.

Merry Christmas.
-Tony

**Comment by rcurtin** [comment]
Will do; please feel free to send an update if you find a fix or anything.  Personally I haven't ever used wxWidgets so I don't know if I will think of anything. :)  I'll go ahead and close this issue---feel free to reopen if needed.
