### ISSUE TITLE
Novice building mlpack

### ISSUE THREAD

**Issue by 5465869** [mlpack/mlpack#849]
Hi I know this is kind of pitiful, but I'm trying to start contributing and I am struggling to build mlpack on my Mac. downloaded the latest version and I am kind of confused whether I need to download and build the dependencies to build mlpack or whether those are for functionality. I created a "build" directory in the mlpack-2.1.1 directory then typed the command cmake ../ but nothing happens. Do I need to install CMake or is it included in the mlpack download. Sorry I can't follow the tutorial. Any help would be appreciated

**Comment by zoq** [comment]
Hello and welcome. All dependencies mentioned are required to build mlpack:

```
  Armadillo     >= 4.200.0
  Boost (program_options, math_c99, unit_test_framework, serialization)
  CMake         >= 2.8.5
```

Since you are on Mac OS you could either use homebrew or MacPorts to install the dependencies. E.g. using homebrew:

```
brew install homebrew/science/armadillo
brew install cmake
brew install boost
```

installs all necessary dependencies. Afterwards just follow the install steps:

```
mkdir build
cd build
cmake ..
make
```

**Comment by 5465869** [comment]
Thank you so much! Looks like it built without any issues.
