### ISSUE TITLE
Trouble solving linking errors 

### ISSUE THREAD

**Issue by sam0410** [mlpack/mlpack#881]
The program mentioned in this [overdosed blog ](https://overdosedblog.wordpress.com/) is working fine.
But when I try to run the covariance code in
[this mlpack tutorial](http://www.mlpack.org/docs/mlpack-2.1.1/doxygen.php?doc=sample.html)
I get sixteen “linker 2019” errors.

unresolved external symbol sdot_ referenced in function “double __cdecl arma::blas::dot(unsigned __int64,double const *,double const *)” (??$dot@N@blas@arma@@YAN_KPEBN1@Z LINE 1

unresolved external symbol ddot_ referenced in function “double __cdecl arma::blas::dot(unsigned __int64,double const *,double const *)” (??$dot@N@blas@arma@@YAN_KPEBN1@Z LINE 1

and many more

Iam new to visual studio and mlpack. Please help!

**Comment by rcurtin** [comment]
I think your issue is that you need to link against armadillo.lib / armadillo.dll too.

**Comment by Kirizaki** [comment]
Linking against ```armadillo.lib``` is in [2. Compiler Additional Include Directories](https://github.com/mlpack/mlpack/wiki/WindowsBuild#2-compiler-additional-include-directories)

**Comment by sam0410** [comment]
Thanx @rcurtin  and @Kirizaki !
I have already copied all the .lib and .dll files as mentioned in the overdosed tutorial and linked it in my project. But still the error persists..
Please help

**Comment by sam0410** [comment]
Also I noticed that in the mentioned tutorial it is written 
"mlpack.lib/dll (depends on how mlpack and armadillo target was compiled)
armadillo.lib/dll (same as above)"
I have a mlpack.dll file and armadillo.lib. Does it have something to do with the error?
Thanx!

**Comment by Kirizaki** [comment]
In section [4. Linker Additional Dependencies](https://github.com/mlpack/mlpack/wiki/WindowsBuild#4-linker-additional-dependencies) you provide ```C:/libraries/mlpack.lib``` or ```C:/libraries/mlpack.dll```? (Same question for ```armadillo.lib/dll```

I'm working with ```.lib```'s

**Comment by rcurtin** [comment]
Another thought might be to ensure that Armadillo is properly configured so it's linked against BLAS and LAPACK.  (Or maybe you need to link directly against BLAS and LAPACK in your project?  It depends on the Armadillo configuration.)

**Comment by sam0410** [comment]
@Kirizaki  I have linked it against mlpack.lib file (I have both mlpack.dll and mlpack.lib  files)
If I try to link it against mlpack.dll file it gives a LNK1107 error saying mlpack.dll is an invalid or corrupt file
And regarding armadillo, I have linked the .dll file
Thanx!

**Comment by sam0410** [comment]
@rcurtin  can you please tell me how to check that armadillo is linked with blas and lapack ?
Iam using armadillo-7.500.2 and mlpack-2.1.0 (in 64 bit)
Thanx for your help!

**Comment by zoq** [comment]
Hello, can you past the output of the additional dependencies and additional library directories here?

**Comment by sam0410** [comment]
Thanks for the reply @zoq !

Additional Dependencies  - C:\projects\libs\mlpack.lib;C:\projects\libs\armadillo.lib;%(AdditionalDependencies)
Additional library directories- C:\projects\libs;%(AdditionalLibraryDirectories)
(where the libs folder includes all that is mentioned in [this tutorial](https://github.com/mlpack/mlpack/wiki/WindowsBuild#3-compiler-additional-library-directories)

Output that I got -
1>------ Build started: Project: ConsoleApplication1, Configuration: Debug x64 ------
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol sdot_ referenced in function "double __cdecl arma::blas::dot<double>(unsigned __int64,double const *,double const *)" (??$dot@N@blas@arma@@YAN_KPEBN1@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol ddot_ referenced in function "double __cdecl arma::blas::dot<double>(unsigned __int64,double const *,double const *)" (??$dot@N@blas@arma@@YAN_KPEBN1@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol sgemv_ referenced in function "void __cdecl arma::blas::gemv<double>(char const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemv@N@blas@arma@@YAXPEBDPEBH1PEBN21212PEAN1@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol dgemv_ referenced in function "void __cdecl arma::blas::gemv<double>(char const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemv@N@blas@arma@@YAXPEBDPEBH1PEBN21212PEAN1@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol cgemv_ referenced in function "void __cdecl arma::blas::gemv<double>(char const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemv@N@blas@arma@@YAXPEBDPEBH1PEBN21212PEAN1@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol zgemv_ referenced in function "void __cdecl arma::blas::gemv<double>(char const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemv@N@blas@arma@@YAXPEBDPEBH1PEBN21212PEAN1@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol sgemm_ referenced in function "void __cdecl arma::blas::gemm<double>(char const *,char const *,int const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemm@N@blas@arma@@YAXPEBD0PEBH11PEBN21212PEAN1@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol dgemm_ referenced in function "void __cdecl arma::blas::gemm<double>(char const *,char const *,int const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemm@N@blas@arma@@YAXPEBD0PEBH11PEBN21212PEAN1@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol cgemm_ referenced in function "void __cdecl arma::blas::gemm<double>(char const *,char const *,int const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemm@N@blas@arma@@YAXPEBD0PEBH11PEBN21212PEAN1@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol zgemm_ referenced in function "void __cdecl arma::blas::gemm<double>(char const *,char const *,int const *,int const *,int const *,double const *,double const *,int const *,double const *,int const *,double const *,double *,int const *)" (??$gemm@N@blas@arma@@YAXPEBD0PEBH11PEBN21212PEAN1@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol ssyrk_ referenced in function "void __cdecl arma::blas::syrk<double>(char const *,char const *,int const *,int const *,double const *,double const *,int const *,double const *,double *,int const *)" (??$syrk@N@blas@arma@@YAXPEBD0PEBH1PEBN212PEAN1@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol dsyrk_ referenced in function "void __cdecl arma::blas::syrk<double>(char const *,char const *,int const *,int const *,double const *,double const *,int const *,double const *,double *,int const *)" (??$syrk@N@blas@arma@@YAXPEBD0PEBH1PEBN212PEAN1@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol sgesv_ referenced in function "void __cdecl arma::lapack::gesv<double>(int *,int *,double *,int *,int *,double *,int *,int *)" (??$gesv@N@lapack@arma@@YAXPEAH0PEAN00100@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol dgesv_ referenced in function "void __cdecl arma::lapack::gesv<double>(int *,int *,double *,int *,int *,double *,int *,int *)" (??$gesv@N@lapack@arma@@YAXPEAH0PEAN00100@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol cgesv_ referenced in function "void __cdecl arma::lapack::gesv<double>(int *,int *,double *,int *,int *,double *,int *,int *)" (??$gesv@N@lapack@arma@@YAXPEAH0PEAN00100@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol zgesv_ referenced in function "void __cdecl arma::lapack::gesv<double>(int *,int *,double *,int *,int *,double *,int *,int *)" (??$gesv@N@lapack@arma@@YAXPEAH0PEAN00100@Z)
1>C:\Users\Samikshya\Desktop\mlpack\mlpack application 1\x64\Debug\ConsoleApplication1.exe : fatal error LNK1120: 16 unresolved externals
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by zoq** [comment]
Thanks, can you also link against libopenblas (add to Additional Dependencies), and tes if that works?

**Comment by sam0410** [comment]
Thanks a lot @zoq !
I added libopenblas.dll.a file to additional dependencies and it worked !

**Comment by zoq** [comment]
Glad it worked out.

Since we only test that mlpack builds on windows using appveyor's continues integration service and most of us usually don't use windows, we rarely see these issues. On the other hand, I've noticed a higher interest in using mlpack on windows, so I guess we should improve our test infrastructure. Also, perhaps we should mention the issue in the windows wiki, something like if you see this error, link against openblas.

**Comment by sam0410** [comment]
Also, in the installation of mlpack in windows [tutorial](https://github.com/mlpack/mlpack/wiki/WindowsBuild) ,we might add the following as **"Notes for linking mlpack in an application"**-
1. In case of BLAS linking errors, add  _libopenblas.dll.a_ file from _mlpack-2.1.0\packages\OpenBLAS.0.2.14.1\lib\native\lib\x64_ or _mlpack-2.1.0\packages\OpenBLAS.0.2.14.1\lib\native\lib\x32_ (depending upon the configuration) to additional dependencies of the project
2. In case of error 
_"The program can't start because mlpack.dll is missing from your computer.Try reinstalling the program to fix this problem._"
copy the  _mlpack.dll_ file from _mlpack-2.1.0\build_ into the current project folder   [according to this IRC channel discussion](http://www.mlpack.org/irc/mlpack.20161214.html)

**Comment by rcurtin** [comment]
I updated the tutorial page with the comments you suggested, and you got it all working, so I'm going to go ahead and close this issue.

**Comment by sam0410** [comment]
Thanks a lot @rcurtin !

**Comment by Sebastiaanvh319** [comment]
Thanks!! for this issue
I was struggling with this for hours, now it works by adding 'libopenblas.dll.a' file to additional dependencies
