### ISSUE TITLE
MDL penalty for decision tree splits

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#883]
There's a new decision tree implementation in `src/mlpack/methods/decision_tree/`.  This implementation is pretty similar to J48 from Weka or C4.5 (but not exactly the same).  The basic structure of finding a split is:

  1. Calculate gain for all possible splits.
  2. Pick split with the best gain.

In this implementation, the splits themselves are determined by the `NumericSplitType` and `CategoricalSplitType` template parameters, and the gain function is the `FitnessFunction` template parameter.

In order to reduce overfitting, often a penalty parameter is applied to the gain.  In C4.5, the penalty that's used is called the 'minimum descriptor length' (MDL) penalty, and the penalized gain is calculated as

```
penalized gain = gain - log2(number of children / sum of weights)
```

where a binary split has `number of children = 2`, and the `sum of weights` refers to the sum of the instance weights over all points (see #882), and if instance weights are not being used, then the sum of weights is just equal to the number of points in the set that's being split.

A PR to fix this should have an implementation of this MDL penalty that can be turned on or off by the user (probably through template parameters but not necessarily), and tests to ensure that the MDL penalty calculation works.

**Comment by micyril** [comment]
I would like to work on this issue. I guess we can start with the case when instance weights are not being used since they are not supported yet. I'm going to investigate the code base more closely, and after that some questions probably will arise.

**Comment by rcurtin** [comment]
Yeah, that's fine---in either case, when instance weights are added, it should be very easy to generalize the MDL support.

**Comment by micyril** [comment]
It took some time for me to investigate the code more, as well as making myself closely familiar with git and the workflow of Github-based development (since I didn't contribute to large Github-based projects before). I think an appropriate implementation for this issue is to create a decorator (template-based) for what called FitnessFunction in the class DecisionTree. It will allow to keep existing code unchanged, what generally is considered as a good practice. It stays a bit tricky for me how to write appropriate tests, since I haven't yet investigated whether you encourage to write pure unit tests with the use of mock classes for template parameters. I'm going to find it out by reading more tests, but don't hesitate if you have some suggestions.

**Comment by rcurtin** [comment]
This sounds reasonable to me.  We haven't used any mock objects for testing but I am not sure that there is any particular reason.  Personally I think it's adequate to test the low-level components on their own (where you wouldn't need to mock anything) and then test the higher-level components assuming that the lower-level components work.  But in either case, what I've found is that with complex algorithms the testing strategy generally can't be "ensure that the code works absolutely properly" but instead "ensure that the code isn't horribly wrong and seems to maybe work right".  So for everything we do the best we can, but basically no testing strategy of ours is perfect.

When you say decorator, I assume you mean adding a template parameter to `GiniGain` or `InformationGain`?  That seems reasonable to me.  You could either use a standalone functor class, or you could just use a boolean template parameter---the call is yours.  I guess that a standalone functor would allow easier inclusion of other types of penalties too, so it is probably a more robust approach.

**Comment by micyril** [comment]
So, being more specific I propose to create a class with the following interface:
```
template<typename FitnessFunction>
class MDLPenalty
{
public:
  static double Evaluate(const arma::Row<size_t>& labels, const size_t numClasses);
};
```
It probably should also include a static function `double Range(const size_t)`, I haven't yet figured it out. When we want to use it, we create a decision tree by calling something like `DesicionTree<MDLPenalty<GiniGain>>(...)`.

**Comment by rcurtin** [comment]
That seems reasonable, but consider adding the penalty as, e.g., a fourth template template parameter to the `DecisionTree` class.  The default could be `NoPenalty` or something like that, and then `MDLPenalty` could be used if the user wanted.

**Comment by micyril** [comment]
So, if I understand the suggestion in the right way, the result template arguments for the class DecisionTree should be like this.
```
template<typename FitnessFunction = GiniGain,
         template<typename> class NumericSplitType = BestBinaryNumericSplit,
         template<typename> class CategoricalSplitType = AllCategoricalSplit,
         template<typename> class Penalty = NoPenalty,
         typename ElemType = double,
         bool NoRecursion = false>
class DecisionTree 
```
I guess this template interface will be more self-documenting from user's prospective.

**Comment by rcurtin** [comment]
Yeah, that seems like a reasonable approach to me.

**Comment by micyril** [comment]
@rcurtin, should we apply the MDL penalty while calculating a gain when there is no split?

**Comment by micyril** [comment]
Is my question understandable? Do I need to reformulate it?

**Comment by rcurtin** [comment]
Sorry, I hadn't gotten to this yet.  If no split is found, then in my view there's no reason to add an MDL penalty because we wouldn't be adding any children.  The idea of the MDL penalty is that you apply it when you create more and more children to keep the tree from making too many children.

**Comment by micyril** [comment]
@rcurtin, you're right, but the question is about something different. To decide whether we need to do a split we compare a gain before any splitting and a gain after finding a split with the highest gain. It makes sense to me if the MDL penalty should be used not only to choose a split that is less prone to cause overfitting , but also to effect deciding whether we need to make a split at all (as it also can help prevent overfitting). So, the question was whether we need to apply the MDL penalty while calculating a gain before any splitting. 

While implementing the penalty I assumed that we need to apply it in the described case by setting number of children equal to 1, but the problem arose in the testing stage. There I realized that under the MDL penalty the difference between the best theoretical gain from a binary split and the gain before splitting is not greater than 0 for the implemented fitness functions (gini and information gain). For example, if we consider gini gain and the following values and labels
```
arma::vec values("0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7")
arma::Row<size_t> labels("0 0 0 0 1 1 1 1"); 
```
then the gain before splitting is
-0.5 - log2(1 / 8) = -0.5 + 3.0 = 2.5
and after the best split
0 - log2(2 / 8) = 0 + 2.0 = 2.0
so, we will choose to not split, which is undesired behavior I believe. In the case of information gain the gains would be 2.0 and 2.0 accordingly, so we would still choose to not split. 

I guess the possible solution is to implement the formula
`penalized gain = gain - coefficient * log2(number of children / sum of weights)`
where `coefficient` is defined by a user and can be set to something like 0.25 as a default value.

**Comment by rcurtin** [comment]
Ah, right, sorry that I misunderstood your question.  Thanks for the clarification.

Here is the paper that introduced the MDL penalty:
https://arxiv.org/pdf/cs/9603103.pdf
The relevant part is on page 4 in the top half.

I think that I wrote the penalty wrong in the description, too---it should be `log2(number of children - 1) / sum of weights`.  The `- 1` must be added because the idea is to only add a penalty related to the number of extra values you would need to hold for the new split.  Otherwise the sum of weights actually is a positive addition to the penalty instead of a scaling.

In either case, I think that no penalty should be applied to the "before splitting" gain calculation, and I think that is what the Weka and C4.5 implementations do.

Let me know if I can clarify anything.

**Comment by micyril** [comment]
I have read the third section of the paper, and it seems like the proposed penalty is applied only to numerical splits, while the formula is actually `gain - log2(number of distinct numeric values - 1) / sum of weights `. Here `number of distinct numeric values - 1` is equal to amount of possible thresholds, and the idea is that we want penalize splits with many possible thresholds (as they are more prone to overfit data). 

The author of the paper also discussed a standard penalty for all types of splits - using gain ratio instead of gain. To calculate gain ratio we divide gain by split entropy (it depends on the number of children of the split and the amount of points in each child).

**Comment by ViswanathBalla22** [comment]
hi @zoq , Can you assign this to me
