### ISSUE TITLE
Support for categorical datasets with mlpack_decision_tree program

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#885]
Right now the `mlpack_decision_tree` program does not support categorical datasets---it only supports numeric datasets.  So I can do

```
$ mlpack_decision_tree -t data.csv -l labels.csv
```

and all the features will be treated as numeric.  But I can't pass, e.g., `data.arff` to the program, which contains categorical features.  We should refactor the program `decision_tree_main.cpp` in the same way as `src/mlpack/methods/hoeffding_tree/hoeffding_tree_main.cpp` so that it accepts categorical datasets also.

A PR to fix this issue should have a tested `decision_tree_main.cpp` program that accepts .arff files too, and properly serializes models with categorical features for later re-use.  So, e.g., the following should work:

```
$ mlpack_decision_tree -t data.arff -l labels.csv -T test_data.arff -P P.csv -p p.csv -M model.bin
$ mlpack_decision_tree -m model.bin -T test_data.arff -P P2.csv -p p2.csv
```

and after that, `P.csv` should be the same as `P2.csv`, and `p.csv` should be the same as `p2.csv`.

**Comment by jonathanhfriedman** [comment]
@rcurtin I'd like to work on this.

**Comment by rcurtin** [comment]
Sure, feel free, but be aware, there will probably be some gotchas when you submit a PR. :)  The categorical dataset support in mlpack is somewhat immature, so there may be some parts that aren't documented well, etc.

**Comment by chvsp** [comment]
Hi @jonathanhfriedman. I have been involved with this issue for a day. I apologize for not letting you know but I wanted to be sure, I knew the solution before I commit to solving this issue. I think the solution lies in replacing `arma::mat` to `data::DatasetInfo` when we initialize the training data in `decision_tree_main.cpp`. @rcurtin Kindly correct me if I am wrong.
 It would be great if we can collaborate to get this done. Cheers!

**Comment by jonathanhfriedman** [comment]
@chvsp I've barely started working on this, so feel free to take this one :)

**Comment by shreya-03** [comment]
@rcurtin I  worked on this using python and would like to work on this too.

**Comment by chvsp** [comment]
Hi @shreya-03, I am working on this issue. I am fine with collaborating to fix this issue.

Hi @rcurtin, I was reading the code for ARFF file loader and I found that our code doesn't support the `@relation`, `@attribute`, `@data` declarations in upper case, even though the official documentation for the file format specifies that these declarations are case insensitive. I think it would be a quick and useful fix as many datasets in the UCI repository have them in upper case. Your thoughts?

**Comment by rcurtin** [comment]
I'm surprised I didn't already convert all input strings to lowercase before reading. If you want to make that change (and provide associated test case) that seems fine to me. If not, then can you open an issue for it?

**Comment by chvsp** [comment]
@rcurtin, Yes I will make the required changes and submit a PR. If I have understood it correctly, you want me to provide a standalone test case for this?

**Comment by haritha1313** [comment]
@rcurtin I would like to work on this issue if it is still open.

**Comment by haritha1313** [comment]
@rcurtin I've been going through the code and as far as I understand decision tree class does support categorical data and the work to be done is only to make categorical datasets in .arff format supportable. This means that only decision_tree_main.cpp needs edit. Please correct me if I am wrong.

**Comment by rcurtin** [comment]
@haritha1313: that is correct, you will only need to modify `decision_tree_main.cpp`.
