### ISSUE TITLE
More optimizer methods

### ISSUE THREAD

**Issue by zoq** [mlpack/mlpack#893]
An optimizer is one of basically two parts to evaluate/optimize a method. mlpack already implements some optimizers like Stochastic Gradient Descent or RmsProp but there are still some interesting approaches out there that could be of interest. In particular, I would really like to see an implementation of the SMORMS3[1], the Nesterov's Accelerated Gradient[2] and AdaGrad[3] method.

1.  Simon Funk's SMORMS3 - http://sifter.org/~simon/journal/20150420.html
2. Advances in Optimizing Recurrent Networks, Yoshua Bengio et al. - https://arxiv.org/abs/1212.0901
3. Adaptive Subgradient Methods for Online Learning and Stochastic Optimization, John Duchi et al. - http://jmlr.org/papers/v12/duchi11a.html

The goal of this ticket is to implement the mentioned methods and to write tests for each method like we already did for the existing optimizer methods. Realistically you can look at some of the other optimizers in ``src/mlpack/core/optimizers`` for examples; The corresponding test suites are in ``src/mlpack/tests``. Note, if you write a suite called ``TestSuite`` ``(BOOST_AUTO_TEST_SUITE(TestSuite))``, and then build ``mlpack_test`` (``make mlpack_test``), you can run only the tests in that test suite with ``bin/mlpack_test -t TestSuite``.  And a specific test case called ``TestCase (BOOST_AUTO_TEST_CASE(TestCase))`` could be run with 'bin/mlpack_test -t TestSuite/TestCase'.

**Comment by ivmarkp** [comment]
Hi @zoq, I would like to work on this task. Will open separate PRs for each.

**Comment by zoq** [comment]
Hello @ivmarkp sounds good. Do you mind if we split the work, maybe someone else is also interested in implementing one of mentioned optimization algorithms? So maybe can you start with one, and if there is an algorithm left, once you finished you take the next one. What do you think? We could use this issue as an entrance coordination point, so if you agree just tell me the algorithm you like to start with and I modify the issue description accordingly.

**Comment by nish21** [comment]
If @ivmarkp agrees, I'd like to work on this as well.

**Comment by hxidkd** [comment]
if there is any optimizer methods left, I'd like to work on this as well.

**Comment by ivmarkp** [comment]
Hi @zoq, you are right. Splitting the work sounds like a good idea as its meant to be an entrance task. I've actually started working on the first optimizer i.e. SMORMS3 so I'd like to continue working on it.

Hi @nish21, you are welcome to work on this. :)

**Comment by zoq** [comment]
Okay, great, so @ivmarkp works on SMORMS3, @nish21 can decide between Nesterov's Accelerated Gradient and AdaGrad (let us know which one you like to work on) because he was second and @hxidkd takes what's left, does that sounds fair?

**Comment by nish21** [comment]
@zoq I don't mind taking either of the two. Since I'm currently working on implementing FTRL optimizer (I'm sorry it's taking time, was quite busy last week) maybe @hxidkd can take up what he's comfortable with and I'll take the remaining one.

**Comment by zoq** [comment]
Yeah, fine with me @hxidkd your decision.

**Comment by arunreddy** [comment]
Looks like implementing an optimizer algo is a good place to start. Hey @zoq,  Can I do AdaDelta(https://arxiv.org/abs/1212.5701), an extension of AdaGrad?

**Comment by zoq** [comment]
Hello @arunreddy momentum SGD is another interesting method.

**Comment by arunreddy** [comment]
@zoq, I was infact looking at it. That was the missing piece in the list of algos implemented. Thanks.

**Comment by hxidkd** [comment]
@zoq  @nish21   I'm reading the AdaGrad paper, so I'd like to choose it

**Comment by arunreddy** [comment]
Hey @zoq, taking up "Incorporating Nesterov Momentum into Adam" next.

**Comment by zoq** [comment]
@arunreddy Okay, I've looked at the paper and besides that the empirical validation isn't fair for every case, I think it's a nice idea. Do you also integrate the AdaMax method, as @ivmarkp has done for the Adam algorithm in #887?

**Comment by kris-singh** [comment]
@hxidkd i am sorry i didn't see the comments earlier. I actually implemented the adagrad just now. If you want you can incorporate nestrov momentum in that. Again i am sorry.
@zoq if its okay i would like to submit a PR for adagrad.

**Comment by arunreddy** [comment]
@zoq, I agree with empirical validation being not so exhaustive. May be once we have most of the optimizers, we can definitely compare the optimizers using some mainstream datasets. I can integrate the AdaMax method too.

**Comment by sinjan25** [comment]
@zoq I want to work on this issue too. But in the comments section I noticed that a few guys are already working. So, should I go for a new one?

**Comment by zoq** [comment]
@sinjan25  There is an open PR for each method, so I think as long as you don't have an interesting idea, I'm gonna close this issue.

**Comment by arunreddy** [comment]
@zoq: For Nesterov with Adam based on the paper "Incorporating Nesterov Momentum into Adam", I am planning to move AdaMax updates into a policy class. It is currently handled using a boolean flag passed to the constructor. And at the same time add two more policy classes. NesterovAdam and NesterovAdaMax. That makes it 4 different updates:
1. Adam
2. AdaMax
3. NesterovAdam
4. NesterovAdaMax

Is it ok to proceed in that direction?

**Comment by zoq** [comment]
@arunreddy Sounds great!

**Comment by abhinavmoudgil95** [comment]
@zoq I feel that AdaDelta can also be ported to policy class like AdaGrad in #942 to reduce code duplication. Should I go ahead and submit a PR for this?

**Comment by zoq** [comment]
@abhinavmoudgil95 I agree, if you like feel free to open a PR.

**Comment by sourabhvarshney111** [comment]
@zoq I have implemented Nesterov Adam. Should I proceed to add Nesterov Adamax too?

**Comment by zoq** [comment]
NadaMax from the "Incorporating Nesterov Momentum into Adam" report? If you like go for it, would be great to see an implementation.

**Comment by sourabhvarshney111** [comment]
Getting no clear idea from the report. Also not finding an report on it. But still I would try to inculcate the Adamax and NAG together to get the NadaMax algorithm.

**Comment by sourabhvarshney111** [comment]
I have got an idea about how to do it from the two algorithms Nadam and Adamax. But have got no paper on that. I would do that from that idea.

**Comment by zoq** [comment]
In case of NadaMax you have to abstract the idea from the Nadam and the Adam/AdaMax method, you can start by comparing the Adam and AdaMax code, if you need any help let me know.

**Comment by sourabhvarshney111** [comment]
Got that. Thanks

**Comment by zoq** [comment]
1 and 3 is implemented and there is an open PR for method number 2, so I close this one.
