### ISSUE TITLE
Upper Camel Case

### ISSUE THREAD

**Issue by zoq** [mlpack/mlpack#902]
As I implemented the first activation function in ``src/mlpack/methods/ann/activation_functions`` I used Lower Camel Case for the function names instead of Upper Camel Case as used throughout the codebase and as stated in the design guidelines: https://github.com/mlpack/mlpack/wiki/DesignGuidelines

The goal of this ticket is to find and to replace them with the correct style:

```
fn -> Fn
deriv -> Deriv
inv -> Inv
```

**Comment by sam0410** [comment]
Hi @zoq !
I'll pull a request soon !

**Comment by sam0410** [comment]
Hi @zoq !
I created a pull request for this.

**Comment by sam0410** [comment]
Hi @zoq !
The PR is now ready to merge. Please review the same
Thanks!

**Comment by zoq** [comment]
Fixed in 5215c3df3ec.
