### ISSUE TITLE
arma::colvec behaving as arma::mat

### ISSUE THREAD

**Issue by Lakshya1605** [mlpack/mlpack#908]
May be I am doing something wrong.
It turns out that In the test files  arma::colvec and arma::rowvec
are treated as arma::mat. So even arma::colvec is able to load matrices rather than just column vector.

I have tried out something like this in "load_save_test.cpp"
arma::mat A(5,5, fill::randu);
arma::colvec coltest(A)

It should throw an std::logic_error while doing this.
But gives no error .In fact I also tried printing "coltest" and it gets printed same as A.
Thank You !!!

**Comment by rcurtin** [comment]
Hi Lakshya,

Can you provide a minimum working example to show the problem?  i.e. something that I could compile with gcc that shows the problem.  The details here are a little fuzzy so it would be difficult to reproduce exactly what's happened here.

**Comment by Lakshya1605** [comment]
@rcurtin  One thing what you can do is you can go to the "test" directory open "load_save_test.cpp" and change any "arma::mat" to "arma::colvec" and rebuild. After running that particular test suite ,you fill find that it gives no error.I did something like below -> After opening "load_save_test.cpp"  changed arma::mat to arma::colvec in "LoadCsvTest" .
`BOOST_AUTO_TEST_CASE(LoadCSVTest)
{
  fstream f;
  f.open("test_file.csv", fstream::out);

  f << "1, 2, 3, 4" << endl;
  f << "5, 6, 7, 8" << endl;

  f.close();
( - )arma::mat test;
(+) arma::colvec test;
  BOOST_REQUIRE(data::Load("test_file.csv", test) == true);

 (-) BOOST_REQUIRE_EQUAL(test.n_rows, 4);
 (-)BOOST_REQUIRE_EQUAL(test.n_cols, 2);
 (+)std::cout << test << std::endl;
 (-)for (int i = 0; i < 8; i++)
 (-)   BOOST_REQUIRE_CLOSE(test[i], (double) (i + 1), 1e-5);

  // Remove the file.
  remove("test_file.csv");
}
`
After that i rebuild it using `make mlpack_test`.
And after running the test suite `bin/mlpack_test LoadSaveTest` I expected an error but to my shock I got no error. My output was as below.
`Running 43 test cases...
   1.0000   2.0000   3.0000   4.0000
   5.0000   6.0000   7.0000   8.0000

[WARN ] 'test_file.csv' is not a standard csv file.
[WARN ] 'test_file.csv' is not a standard csv file.

*** No errors detected
`
Where as I expected an error like 
`error: Mat::init(): requested size is not compatible with column vector layout
unknown location(0): fatal error in "LoadCSVTest": std::logic_error: Mat::init(): requested size is not compatible with column vector layout`

Also i tried copying "load_save_test.cpp" into a  separate file in my local directory and then modifying the code as above and compiling using "gcc" and executing it gave error as expected.
Hope I was clear enough .Please let me  know if I can provide any more clarifications
Thank You !!!.

**Comment by rcurtin** [comment]
Oh, I know what is happening here.  When you compile mlpack with the CMake option `DEBUG=OFF`, for speed, Armadillo does not do any runtime checks.  I bet, if you compile with `DEBUG=ON`, then you will get the error that you expect.

I suppose, for the test that you are writing, then, the test will only be successful when `DEBUG=ON`.  Therefore you can enclose the test in

```
#ifdef DEBUG
BOOST_AUTO_TEST_CASE(...)
{
...
}
#endif
```

and then the test will only be run when `mlpack_test` is compiled with debugging symbols.

For the second point, copying `load_save_test.cpp` to a different directory isn't likely to work.  That file depends on several other files, which you would also need to copy, and then when you compiled you would need to set the include directories correctly and the library directories correctly.  This can be a big task.  To get an idea of the actual gcc command that is being run to compile each individual file, run `VERBOSE=1 make`.  But note that even that will not give you the exact command you would need to compile only `load_save_test.cpp` into its own separate program.  It's definitely easier just to do `make mlpack_test`, even though it can take a long time.

**Comment by rcurtin** [comment]
I think this question is answered, so I'm going to go ahead and close this issue.  If there is something I can clarify or something I left answered, feel free to reopen it.
