### ISSUE TITLE
[decision tree]if no label file specified, make the last column of training data as label

### ISSUE THREAD

**Issue by ThyrixYang** [mlpack/mlpack#912]
I'm working on the benchmark script of mlpack_decision_tree method. And I found that a labels_file must be specified. But most dataset takes the last column as label in training data. May I add this feature?

**Comment by rcurtin** [comment]
Sure, this is a reasonable feature addition.  Take a look at some of the other command-line programs---they have this support built in.  I think, for instance, that `mlpack/methods/naive_bayes/nbc_main.cpp` does.  So you can use that as a starting point.

**Comment by rcurtin** [comment]
Fixed in #918.
