### ISSUE TITLE
dangerous use of internal Armadillo structures

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/mlpack#915]
I've noticed that the code uses a whole bunch of internal Armadillo structures and functions. This is not a good idea. The following commit uses internal Armadillo structures such as unwrap and Proxy, which are not guaranteed to be stable across Armadillo releases.
commit: https://github.com/mlpack/mlpack/commit/2e6aa3e2229b4f0afb3c0425aa18d2c276dd20cf

As per the [Armadillo API Version Policy](http://arma.sourceforge.net/docs.html#api_additions), _the underlying internal implementation details may change across consecutive minor versions_. Only the functions explicitly documented in http://arma.sourceforge.net/docs.html are guaranteed to be stable.

There is also a further issue: due to the heavy use of template meta-programming within Armadillo, the use of the _auto_ keyword is problematic.

**Comment by conradsnicta** [comment]
See also my comments in https://github.com/mlpack/mlpack/pull/895

**Comment by rcurtin** [comment]
Hi Conrad,

I appreciate the comments.  I know where you are coming from, but us "breaking the rules" like this is nothing new and something we've often had to do to get the goals that we want.  Sometimes, we do pay the price for this when things change, and this is ok---we generally end up with some amount of #ifdef's to wrap/backport/forward-port the support that we actually need to accomplish our goals.

I'll address #895 comments there.

Thanks,

Ryan

**Comment by conradsnicta** [comment]
I believe in many cases it's entirely feasible to avoid using internal armadillo structures. I've provided a specific examples in the comments to https://github.com/mlpack/mlpack/pull/895

**Comment by rcurtin** [comment]
Yes, I see what you mean now, thanks for the clarification.  Possibly my imagination is lacking. :)
