### ISSUE TITLE
Make Load() fail correctly when not in debugging mode for column vectors

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#920]
@Lakshya1605 just contributed some nice support that allows us to call `data::Load()` with column vectors and row vectors.  That could clean up a lot of the code that loads labels (which need to be one dimensional).

But the problem is, when the file that is loaded has more than one dimension, no exception is thrown when mlpack is compiled without debugging symbols (`-DDEBUG=OFF`, the default).  However, we would like some kind of failure to happen, of course, otherwise users will have their data incorrectly loaded silently and will encounter weird errors later in their code.

This should be a simple fix at its core; we should not have to do anything crazy like partially load the CSV or anything, we should be able to do this with existing Armadillo functionality.

**Comment by sam0410** [comment]
Hi @rcurtin !
I would work on this

**Comment by sam0410** [comment]
Hi @rcurtin!
I was thinking of this-
In row vector, we can check the number of lines(rows) in the file and that should be equal to one, otherwise, an error is thrown.
In column vector, we can find number of spaces(excluding spaces which are there in the beginning and the end) in the first row of the file input, if it is not equal to zero, we can throw an error.
Can I go on and implement this?
Thanks!

**Comment by rcurtin** [comment]
Like I wrote:

> This should be a simple fix at its core; we should not have to do anything crazy like partially load the CSV or anything, we should be able to do this with existing Armadillo functionality.

I am fairly convinced this can be done without having to open the file manually.

**Comment by SND96** [comment]
Hello @rcurtin!
I was thinking we could use data::load for both loading the same data into a column/row vector and a matrix. We could then use the size() function to check whether the column/row vector has the same dimensions as the matrix. If not, an error will be shown.
If this is feasible, can I go on and implement this?

**Comment by rcurtin** [comment]
That doubles the loading time.  That won't be a good idea.

**Comment by sam0410** [comment]
We can just load it into a matrix and check the size of matrix if number of columns =1 or number of rows=1

**Comment by SND96** [comment]
@sam0410  Since `data::load()` can now be called with column/row vectors, wouldn't using a matrix for loading and then converting that to a vector not use that new functionality at all?

**Comment by sam0410** [comment]
Hi @SND96 ! I was thinking,it would be loaded to a vector later and new matrix which we created will be destroyed after the function scope is over,

**Comment by SND96** [comment]
@sam0410 I had suggested something similar but that would double the load time as rcurtin had said before.

**Comment by sam0410** [comment]
@SND96 I think what I suggested would be more faster than loading it twice and checking sizes twice. Anyways, let's look for a better solution.

**Comment by jayantsaraf** [comment]
hello @rcurtin, i would like to take this issue.
but i am unable to figure out the fil in which changes should be made. can you help me?

**Comment by rcurtin** [comment]
@jayantsaraf: it looks like possibly other people are already working on it.  You will want to take a look in `src/mlpack/core/data/` to find the implementation.

I think that if there are no functions for Armadillo that can be useful here, then it may be better to reimplement the overloads of `Load()` and `Save()` for `Col` and `Row` in such a way that they first load into a matrix without transposing, and then check that the matrix contains only one row or column.  In that way we could detect the problem.

**Comment by jayantsaraf** [comment]
i am a beginner. so it would be better if you could help me step by step.
i opened the load file. now what should i do?

**Comment by rcurtin** [comment]
@jayantsaraf: I am sorry to say, there is no time for me to help at that level of depth.  I would suggest that you spend time with basic programming resources.  mlpack is a complex and difficult-to-understand library... it might not be a great first choice for a beginner.

**Comment by jayantsaraf** [comment]
okay thank you for your precious time.
i will be very grateful if you can suggest me some other organisation in which i can contribute for gsoc

**Comment by rcurtin** [comment]
I can't recommend any other organizations because I know nothing of your skill set, background, and interests, and I also am not fully familiar with the list of mentoring organizations. Try looking at the list of mentoring organizations on the Summer of Code website.

**Comment by rcurtin** [comment]
I ended up fixing this as part of the process for merging #931.  The relevant commit is 81a26dec3 in case anyone is interested in looking at the changes.
