### ISSUE TITLE
error in installing boost in centOS

### ISSUE THREAD

**Issue by sam0410** [mlpack/mlpack#926]
after instlalling boost and all the other devel tools required, 
In the build folder of mlpack,after `cmake -DCMAKE_CXX_COMPILER=/opt/rh/devtoolset-2/root/usr/bin/g++ ../ ` , i wrote `make` and the following errors came up.

Moving header files to include/mlpack/
[  0%] Built target mlpack_headers
[  0%] Updating arma_config.hpp (if necessary)
[  0%] Built target mlpack_arma_config
[ 29%] Built target mlpack
Linking CXX executable ../../../../bin/mlpack_sparse_coding
CMakeFiles/mlpack_sparse_coding.dir/sparse_coding_main.cpp.o: In function `void boost::serialization::throw_exception<boost::archive::archive_exception>(boost::archive::archive_exception const&)':
sparse_coding_main.cpp:(.text._ZN5boost13serialization15throw_exceptionINS_7archive17archive_exceptionEEEvRKT_[_ZN5boost13serialization15throw_exceptionINS_7archive17archive_exceptionEEEvRKT_]+0x1d): undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/mlpack_sparse_coding] Error 1
make[1]: *** [src/mlpack/methods/sparse_coding/CMakeFiles/mlpack_sparse_coding.dir/all] Error 2
make: *** [all] Error 2
I don't know how to remove these errors, please help.
Thanks in advance!

**Comment by ThyrixYang** [comment]
Did you install boost with package manager on centos? I think the boost library is not correctly installed.

**Comment by sam0410** [comment]
Hi @ThyrixYang !
When I  write `./bjam` for building boost, following errors pop up. 

Performing configuration checks

    - 32-bit                   : no  (cached)
    - 64-bit                   : yes (cached)
    - arm                      : no  (cached)
    - mips1                    : no  (cached)
    - power                    : no  (cached)
    - sparc                    : no  (cached)
    - x86                      : yes (cached)

Building the Boost C++ Libraries.


    - symlinks supported       : yes (cached)
    - C++11 mutex              : no  (cached)
    - lockfree boost::atomic_flag : yes (cached)
    - Boost.Config Feature Check: cxx11_auto_declarations : no  (cached)
    - Boost.Config Feature Check: cxx11_constexpr : no  (cached)
    - Boost.Config Feature Check: cxx11_defaulted_functions : no  (cached)
    - Boost.Config Feature Check: cxx11_final : yes (cached)
    - Boost.Config Feature Check: cxx11_hdr_mutex : no  (cached)
    - Boost.Config Feature Check: cxx11_hdr_tuple : no  (cached)
    - Boost.Config Feature Check: cxx11_lambdas : no  (cached)
    - Boost.Config Feature Check: cxx11_noexcept : no  (cached)
    - Boost.Config Feature Check: cxx11_nullptr : no  (cached)
    - Boost.Config Feature Check: cxx11_rvalue_references : no  (cached)
    - Boost.Config Feature Check: cxx11_template_aliases : no  (cached)
    - Boost.Config Feature Check: cxx11_thread_local : no  (cached)
    - Boost.Config Feature Check: cxx11_variadic_templates : yes (cached)
    - has_icu builds           : no  (cached)
warning: Graph library does not contain MPI-based parallel components.
note: to enable them, add "using mpi ;" to your user-config.jam
    - zlib                     : yes (cached)
    - bzip2                    : yes (cached)
    - iconv (libc)             : yes (cached)
    - icu                      : no  (cached)
    - icu (lib64)              : no  (cached)
    - native-atomic-int32-supported : yes (cached)
    - native-syslog-supported  : yes (cached)
    - pthread-supports-robust-mutexes : yes (cached)
    - compiler-supports-visibility : yes (cached)
    - compiler-supports-ssse3  : yes (cached)
    - compiler-supports-avx2   : yes (cached)
    - gcc visibility           : yes (cached)
    - long double support      : yes (cached)
warning: skipping optional Message Passing Interface (MPI) library.
note: to enable MPI support, add "using mpi ;" to user-config.jam.
note: to suppress this message, pass "--without-mpi" to bjam.
note: otherwise, you can safely ignore this message.
    - zlib                     : yes (cached)
    - bzip2                    : yes (cached)

Component configuration:

    - atomic                   : building
    - chrono                   : building
    - container                : building
    - context                  : building
    - coroutine                : building
    - coroutine2               : building
    - date_time                : building
    - exception                : building
    - fiber                    : building
    - filesystem               : building
    - graph                    : building
    - graph_parallel           : building
    - iostreams                : building
    - locale                   : building
    - log                      : building
    - math                     : building
    - metaparse                : building
    - mpi                      : building
    - program_options          : building
    - python                   : building
    - random                   : building
    - regex                    : building
    - serialization            : building
    - signals                  : building
    - system                   : building
    - test                     : building
    - thread                   : building
    - timer                    : building
    - type_erasure             : building
    - wave                     : building

...patience...
...patience...
...patience...
...patience...
...patience...
...patience...
...found 14764 targets...
...updating 8 targets...
gcc.compile.c++ bin.v2/libs/python/build/gcc-4.8.2/release/link-static/threading-multi/numpy/dtype.o
libs/python/src/numpy/dtype.cpp: In static member function ‘static boost::python::numpy::dtype boost::python::numpy::detail::builtin_float_dtype<16>::get()’:
libs/python/src/numpy/dtype.cpp:28:53: error: ‘NPY_FLOAT16’ was not declared in this scope
         static dtype get() { return DTYPE_FROM_CODE(NPY_FLOAT ## bits); } \
                                                     ^
libs/python/src/numpy/dtype.cpp:14:91: note: in definition of macro ‘DTYPE_FROM_CODE’
     dtype(python::detail::new_reference(reinterpret_cast<PyObject*>(PyArray_DescrFromType(code))))
                                                                                           ^
libs/python/src/numpy/dtype.cpp:61:1: note: in expansion of macro ‘BUILTIN_FLOAT_DTYPE’
 BUILTIN_FLOAT_DTYPE(16);
 ^
libs/python/src/numpy/dtype.cpp:28:73: warning: control reaches end of non-void function [-Wreturn-type]
         static dtype get() { return DTYPE_FROM_CODE(NPY_FLOAT ## bits); } \
                                                                         ^
libs/python/src/numpy/dtype.cpp:61:1: note: in expansion of macro ‘BUILTIN_FLOAT_DTYPE’
 BUILTIN_FLOAT_DTYPE(16);
 ^
In file included from /usr/lib64/python2.6/site-packages/numpy/core/include/numpy/ufuncobject.h:234:0,
                 from ./boost/python/numpy/internal.hpp:29,
                 from libs/python/src/numpy/dtype.cpp:11:
/usr/lib64/python2.6/site-packages/numpy/core/include/numpy/__ufunc_api.h: At global scope:
/usr/lib64/python2.6/site-packages/numpy/core/include/numpy/__ufunc_api.h:196:1: warning: ‘int _import_umath()’ defined but not used [-Wunused-function]
 _import_umath(void)
 ^

    "g++"  -ftemplate-depth-128 -O3 -finline-functions -Wno-inline -Wall -pthread -m64  -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_STATIC_LIB -DNDEBUG  -I"." -I"/usr/include/python2.6" -I"/usr/lib64/python2.6/site-packages/numpy/core/include" -c -o "bin.v2/libs/python/build/gcc-4.8.2/release/link-static/threading-multi/numpy/dtype.o" "libs/python/src/numpy/dtype.cpp"

...failed gcc.compile.c++ bin.v2/libs/python/build/gcc-4.8.2/release/link-static/threading-multi/numpy/dtype.o...
...skipped <pbin.v2/libs/python/build/gcc-4.8.2/release/link-static/threading-multi>libboost_numpy.a(clean) for lack of <pbin.v2/libs/python/build/gcc-4.8.2/release/link-static/threading-multi>numpy/dtype.o...
...skipped <pbin.v2/libs/python/build/gcc-4.8.2/release/link-static/threading-multi>libboost_numpy.a for lack of <pbin.v2/libs/python/build/gcc-4.8.2/release/link-static/threading-multi>numpy/dtype.o...
...skipped <pstage/lib>libboost_numpy.a for lack of <pbin.v2/libs/python/build/gcc-4.8.2/release/link-static/threading-multi>libboost_numpy.a...
gcc.compile.c++ bin.v2/libs/python/build/gcc-4.8.2/release/threading-multi/numpy/dtype.o
libs/python/src/numpy/dtype.cpp: In static member function ‘static boost::python::numpy::dtype boost::python::numpy::detail::builtin_float_dtype<16>::get()’:
libs/python/src/numpy/dtype.cpp:28:53: error: ‘NPY_FLOAT16’ was not declared in this scope
         static dtype get() { return DTYPE_FROM_CODE(NPY_FLOAT ## bits); } \
                                                     ^
libs/python/src/numpy/dtype.cpp:14:91: note: in definition of macro ‘DTYPE_FROM_CODE’
     dtype(python::detail::new_reference(reinterpret_cast<PyObject*>(PyArray_DescrFromType(code))))
                                                                                           ^
libs/python/src/numpy/dtype.cpp:61:1: note: in expansion of macro ‘BUILTIN_FLOAT_DTYPE’
 BUILTIN_FLOAT_DTYPE(16);
 ^
libs/python/src/numpy/dtype.cpp:28:73: warning: control reaches end of non-void function [-Wreturn-type]
         static dtype get() { return DTYPE_FROM_CODE(NPY_FLOAT ## bits); } \
                                                                         ^
libs/python/src/numpy/dtype.cpp:61:1: note: in expansion of macro ‘BUILTIN_FLOAT_DTYPE’
 BUILTIN_FLOAT_DTYPE(16);
 ^
In file included from /usr/lib64/python2.6/site-packages/numpy/core/include/numpy/ufuncobject.h:234:0,
                 from ./boost/python/numpy/internal.hpp:29,
                 from libs/python/src/numpy/dtype.cpp:11:
/usr/lib64/python2.6/site-packages/numpy/core/include/numpy/__ufunc_api.h: At global scope:
/usr/lib64/python2.6/site-packages/numpy/core/include/numpy/__ufunc_api.h:196:1: warning: ‘int _import_umath()’ defined but not used [-Wunused-function]
 _import_umath(void)
 ^

    "g++"  -ftemplate-depth-128 -O3 -finline-functions -Wno-inline -Wall -pthread -fPIC -m64  -DBOOST_ALL_NO_LIB=1 -DNDEBUG  -I"." -I"/usr/include/python2.6" -I"/usr/lib64/python2.6/site-packages/numpy/core/include" -c -o "bin.v2/libs/python/build/gcc-4.8.2/release/threading-multi/numpy/dtype.o" "libs/python/src/numpy/dtype.cpp"

...failed gcc.compile.c++ bin.v2/libs/python/build/gcc-4.8.2/release/threading-multi/numpy/dtype.o...
...skipped <pbin.v2/libs/python/build/gcc-4.8.2/release/threading-multi>libboost_numpy.so.1.63.0 for lack of <pbin.v2/libs/python/build/gcc-4.8.2/release/threading-multi>numpy/dtype.o...
...skipped <pstage/lib>libboost_numpy.so.1.63.0 for lack of <pbin.v2/libs/python/build/gcc-4.8.2/release/threading-multi>libboost_numpy.so.1.63.0...
...skipped <pstage/lib>libboost_numpy.so for lack of <pstage/lib>libboost_numpy.so.1.63.0...
...failed updating 2 targets...
...skipped 6 targets...


How do I solve these errors? 
Thanks in advance!

**Comment by ThyrixYang** [comment]
Hi, @sam0410 , I suggest you install via yum, ie.
sudo yum install boost-devel
The package manager will deal with the dependencies automatically. Have you tried this approach?

**Comment by sam0410** [comment]
Hi @ThyrixYang 
yum contains outdated version of boost and mlpack build was failling because it needs boost version >=1.49
Thanks for your patience!

**Comment by ThyrixYang** [comment]
I tried to build boost on my machine and failed too :).....My os is ubuntu16.04, I have no idea to deal with this now.

**Comment by rcurtin** [comment]
I am confused, in the first post you say that you have boost installed, in the second you show some errors while compiling boost.  Can you provide the current state of boost on your system?

**Comment by sam0410** [comment]
sorry for the the confusion @rcurtin.
I initially installed boost via yum and it was not supporting mlpack build, as it was outdated.
I tried installing boost from source and errors come up.
Thanks for your patience!

**Comment by rcurtin** [comment]
No, but this still doesn't make sense.  In your original report, you had boost installed and mlpack was properly configured and building.  If mlpack configured successfully, then your boost version was 1.49 or newer.  What had you done that got you to the situation you were in when you filed this ticket, with mlpack successfully configured?

**Comment by sam0410** [comment]
Hi @rcurtin !
I tried building boost and and the given errors popped up. even after that I tried building mlpack and mlpack failed to build 100%, it stopped at 30% and the errors which I posted earlier came up.
Please help me build mlpack after this.
Thanks.

**Comment by rcurtin** [comment]
Unfortunately I can't help because what you are saying does not make sense.  Therefore I can't understand the situation that you are in and I can't provide any advice.  Again, in your first post, you had mlpack properly configured with CMake, which you cannot do without a recent-enough Boost installation.  So it seems like your system has Boost, so I am not sure why you are trying to compile Boost by hand.

**Comment by sam0410** [comment]
Hi @rcurtin !
Like I said, my system had outdated boost in the first place. That is the reason I tried compiling boost by hand. and faced this.

**Comment by rcurtin** [comment]
Please carefully read what I am saying; this will be the third time I write it.  It is _not possible_ to get the error that you originally opened this bug with if the Boost version on your system is out of date.  So either there is new-enough Boost on your system and you don't know it, or you have modified something in the configuration scripts that you aren't telling me.

**Comment by ThyrixYang** [comment]
@sam0410 , the CMake will check the version of boost, if the version is out of date. It will fail on the cmake step, so you can't go to make. You can find the boost files in your path, which version have you installed? If not installed, then you should search for installation guide on centos. Go to centos or boost community and irc to ask this question would be better. I agree with rcurtin: if you have installed all dependencies correctly, and followed the build guide of mlpack, all will go well. Maybe you can do these one by one and try again.

**Comment by sam0410** [comment]
Thanks !
You were right @rcurtin , there was boost already there, and I was unaware of it. I upgraded the existing, and it worked fine.
Thanks a lot!

**Comment by rcurtin** [comment]
Great, glad you got it worked out.
