### ISSUE TITLE
GMMTest/GMMTrainEMOneGaussian fails when component co-variance is close to 0

### ISSUE THREAD

**Issue by shikharbhardwaj** [mlpack/mlpack#932]
Parent issue : #922 

Test in `src/mlpack/tests/gmm_test.cpp`.

The test uses `BOOST_REQUIRE_CLOSE` to check the equality of floating point numbers, which is based on Knuth's tolerance predicate. It compares the relative errors of the numbers to a required tolerance %. The problem arises when the numbers are close to 0 where the relative errors can grow arbitrarily large. This leads to the test failing randomly, as is shown by the multiple instance outputs [here](https://gist.github.com/shikharbhardwaj/d757d9ef9dec5424fe3d65800409c9a9), whenever the co-variance of the component is close to 0. 

The same can be spotted on many failed Travis builds, such as [this one](https://travis-ci.org/mlpack/mlpack/builds/210031049).

Relevant discussion on StackOverflow : http://stackoverflow.com/questions/29196130/boost-check-close-fails-even-if-the-two-values-are-below-the-threshold

Possible solutions : 

 * Use [`BOOST_CHECK_SMALL`](http://www.boost.org/doc/libs/1_34_0/libs/test/doc/components/test_tools/reference/BOOST_CHECK_SMALL.html) on the difference between the values of the computed value and correct value. The tolerance here has to be a multiple of `std::numeric_limits<double>::epsilon()`, but I am unaware of the error propagation in the EM algorithm implemented here. Since this method ignores the relative errors, it may cause problems when the values are large.

 * Conditionally check if the value to be tested is close to 0, and use different methods to establish an equality in that case.

**Comment by rcurtin** [comment]
Hi Shikhar,

Nice catch.  I agree, we can do something like:

```
if (std::abs(a) < 1e-5)
  BOOST_REQUIRE_SMALL(b, 1e-5); // or similar
else
  BOOST_REQUIRE_CLOSE(a, b, 1e-5);
```

This is done in lots of other tests too; I'm not sure why it isn't done here.  Looks like `GMMTrainEMMultipleGaussians` may also have the same issue.

**Comment by shikharbhardwaj** [comment]
Hi Ryan,

Thanks for looking into this. I'll create a PR with the changes.
