### ISSUE TITLE
Build on Windows using WSL

### ISSUE THREAD

**Issue by NaxAlpha** [mlpack/mlpack#936]
Hi everyone,

I was trying to compile mlpack on different platform and then I came across _Bash On Ubuntu On Windows_. Looking at various articles regarding its compatibility and performance, I tried to compile using given [documentation](http://www.mlpack.org/docs/mlpack-git/doxygen.php?doc=build.html) on mlpack website:

* Clone Repository
* Install Dependencies
* Configure CMake
* `make -j8` (**Highly reactive**)
* Finally `make install`

And yes, it compiled flawlessly and successfully within 10 min (8 CPUs, 8 GB RAM). But there is a warning that, if one uses `make -j8`, this increases number of jobs to compile but each compile job can take from 500MB to 3 GB RAM, so peak RAM usage can exceed 8 GB. So, If one has less RAM, use simple `make` or `make -j2` to compile. Although it takes more time to compile but uses lesser RAM.

**Comment by rcurtin** [comment]
Hi @NaxAlpha, if there is somewhere in the documentation that suggests using multiple cores, it may be useful to point out that using more cores will use more RAM.  But I can't find anywhere in the documentation that says that, so I don't think there is anything to be changed.

Is there any actual issue to solve here, or is this just a note?  If so I'll solve the issue, otherwise I'll go ahead and close this.

Thanks,
Ryan

**Comment by NaxAlpha** [comment]
Hi @rcurtin, `make` allows to compile using multiple jobs, which makes compiling quicker. [Here](https://www.gnu.org/software/make/manual/html_node/Parallel.html) is article which tells how to use multiple jobs (better if multiple cores). Following is screenshot of my system:

![screenshot 5](https://cloud.githubusercontent.com/assets/11090613/23939336/00b5a530-0982-11e7-94cb-d551a0133eb2.png)

Besides this is not an issue. It is just a note to compile mlpack on windows using WSL and multiple cores.

**Comment by rcurtin** [comment]
Right, I typically use `make -j8` on my 8-core desktop... unfortunately mlpack is a big library and there is a lot to compile, so even then it can take a long time.

Thank you for writing up the note, I will go ahead and close the issue (to try and keep the issue list of manageable size) and then people in the future can refer to this issue or when they are searching for similar problems they may come across it.
