### ISSUE TITLE
Creating uniform interface for Logistic Regression and softmax regression

### ISSUE THREAD

**Issue by sagarbhathwar** [mlpack/mlpack#941]
Since Logistic regression is a specific case of Softmax regression(K=2), isn't it better to provide a uniform interface for both Softmax regression and Logistic Regression.

For example:, Logistic regression has the following methods:
```
template<typename VecType>
  size_t Classify(const VecType& point,
                  const double decisionBoundary = 0.5) const;

void Classify(const MatType& dataset,
                arma::mat& probabilities) const;

double ComputeError(const MatType& predictors,
                      const arma::Row<size_t>& responses) const;
```

which are absent in Softmax Regression.

Likewise, the `Serialize` function of Softmax regression is absent in Logistic regression.:
```
template<typename Archive>
  void Serialize(Archive& ar, const unsigned int)
  {
    using mlpack::data::CreateNVP;

    ar & CreateNVP(parameters, "parameters");
    ar & CreateNVP(numClasses, "numClasses");
    ar & CreateNVP(lambda, "lambda");
    ar & CreateNVP(fitIntercept, "fitIntercept");
  }
```

I feel that since Logistic regression is a logical subset of Softmax regression, they should have uniform interface. If this should reasonable, I can take it up and send a PR

Another suggestion:

In logistic regression:
```
void Classify(const MatType& dataset,
                arma::mat& probabilities) const;
```
This function is actually computing probabilities. The name sounds a little misleading. What I suggest is create a method named `ComputeProbabilities` (and `ComputerClassProbabilities` for softmax regression) and deprecate the previous Classify method, So that a cleaner interface is provided.

A doubt in softmax regression:
```
double Train(const arma::mat &data, const arma::Row<size_t>& labels,
               const size_t numClasses);
```

This method takes number of classes as a parameter, but since `numClasses` is already a class member, I feel this parameter is redundant. Are my thoughts right or is there an explanation for this? Would really like to know the design decision behind this since I am new to Open Source Contributions and can learn a lot

If above suggested changes look fine, I can make the changes and open a PR

Thanks

**Comment by rcurtin** [comment]
Hi Sagar,

I'm not sure why you opened another issue for this when Kirill had already opened (and solved) another virtually identical issue.  I see there are some other questions to address though. So:

 * `Predict()` -> `Classify()` is already handled for softmax regression.
 * `Serialize()` already exists for both logistic and softmax regression.
 * We should avoid having too many differently named methods in `LogisticRegression`, so even though the overload that provides only class probabilities is a little bit of a stretch, it is sufficiently similar to the other overloads that we should not add a different name for it.
 * When you train `SoftmaxRegression` you are not training incrementally: you are starting with a new model. Therefore allowing the user to specify the number of classes in the dataset is an extra convenience.

I hope this clarifies things; let me know if not.

**Comment by sagarbhathwar** [comment]
Hi Ryan

Sorry if opening a new issue was wrong. I'm new to Open Source contribution you see. Apologies

- `Predict()` -> `Classify()` has been taken care of. But some `Classify` methods, like classifying a single point of type `arma::Row<size_t>` and computing probabilities can be added to softmax regression
- Sorry, I missed `Serialize()` by oversight
- Sure, sounds good
- Yes, that sounds fair too. Thanks for the explanation

Thank you again

**Comment by rcurtin** [comment]
No worries, I was new once too. :)

I do agree that the extra overloads of `Classify()` could be added to softmax regression.  If you would like to do this, feel free---but be sure to add some tests to `softmax_regression_test.cpp` for the new overload.  I'll go ahead leave this issue open then; if you want to do that, then we can close it after the PR is merged.

**Comment by sagarbhathwar** [comment]
#954 I've created the PR. Please review the changes
