### ISSUE TITLE
Regarding Linear Regression and LARS

### ISSUE THREAD

**Issue by s1998** [mlpack/mlpack#963]
As of now linear regression has constructor : 
`LinearRegression::LinearRegression(`
`const arma::mat& predictors,`
   `                                                       const arma::vec& responses,`
`                                                       const double lambda,`
`                                                       const bool intercept,`
`                                                       const arma::vec& weights)`
And training method as : 
` LinearRegression::Train(`
`const arma::mat& predictors,`
`                                     const arma::vec& responses,`
`                                     const bool intercept,`
`                                     const arma::vec& weights)`

And LARS has constructor : 
`LARS(`
`const arma::mat& data,`
`         const arma::vec& responses,`
`         const bool transposeData = true,`
`          const bool useCholesky = false,`
`          const double lambda1 = 0.0,`
       `const double lambda2 = 0.0,`
       `const double tolerance = 1e-16);`
And training method as : 
`void Train(`
            `const arma::mat& data,`
             `const arma::vec& responses,`
             `arma::vec& beta,`
             `const bool transposeData = true);

Since all the methods are column major (i.e. each input is a column vector) in mlpack, is it a good idea to convert these to column major form too ? 

Also since decision stump and perceptron (though it is less frequently used) have weights as 3rd parameter in the train method, does it sound reasonable to change the above mentioned methods (Train and constructor) to have weights as the third parameter ? (Similar to issue [929](https://github.com/mlpack/mlpack/issues/929) )
(It will be good to have uniform interface across the library and also help in simplifying the cross validation project)

Modified APIs may look like : 
`LinearRegression(`
`const arma::mat& predictors,`
   `                                                       const arma::rowvec& responses,`
` const arma::vec& weights,`
`                                                       const double lambda,`
`                                                       const bool intercept)`

` LinearRegression::Train(`
`const arma::mat& predictors,`
`                                     const arma::rowvec& responses,`
`                                     const arma::rowvec& weights`
`                                     const bool intercept)`

`LARS(`
`const arma::mat& data,`
`         const arma::rowvec& responses,`
`         const bool transposeData = true,`
`          const bool useCholesky = false,`
`          const double lambda1 = 0.0,`
       `const double lambda2 = 0.0,`
       `const double tolerance = 1e-16);`

`void Train(`
            `const arma::mat& data,`
             `const arma::rowvec& responses,`
             `arma::vec& beta,`
             `const bool transposeData = true);`

This will also probably eliminate the `transposeData` variable.

Also `LARS::Predict` will be changed. 
`void Predict(const arma::mat& points,`
           `   arma::vec& predictions,`
`const bool rowMajor = false) const;`

It will look like
`void Predict(const arma::mat& points,`
           `   arma::rowvec& predictions)`
and will have one less variable.

**Comment by rcurtin** [comment]
We should aim such that `arma::rowvec` is used for weight vectors, regression responses, and predictions.  So `Train(const arma::mat&, arma::rowvec&)` for `LARS` and `LinearRegression`.  The reason for this is that typically, if the data is 'm x n' where 'n' is the number of points, then you would want your labels, weights, or predictions to correspondingly be '1 x n' and not 'n x 1'.  Therefore, with column-major data, `arma::rowvec` is the right type to use.

There's no need to remove the `rowMajor` parameter from `LARS::Predict()`; read the documentation closely to see why that is there and why we should leave it there.  `lars_main.cpp` explicitly makes use of that functionality for speed.

@micyril: I just want to make sure, switching to `rowvec` does not contradict anything we have previously discussed?

**Comment by micyril** [comment]
Ryan, I think it will be fine, even though it's not that important for cross validation and hyper parameter tuning modules in the light of my last comment in [#929](https://github.com/mlpack/mlpack/issues/929).

**Comment by micyril** [comment]
I'm going to start working on the issue. Should we just adapt the new interface (where for `responses` we have `arma::rowvec` instead of `arma::vec`) for the existing implementation by transposing `arma::rowvec` to `arma::vec`, or is it better to change the implementation internally?
