### ISSUE TITLE
make mlpack_test failed

### ISSUE THREAD

**Issue by TriLoo** [mlpack/mlpack#968]
Hi everyone, 
    when I try to install mlpack on my ubuntu14.04 and after `cmake ../`, go to `make` but failed. compile information shows that it cann't find the library `libhdf5_hl.s0.10` , so I copied these files from my anaconda/lib dir into `/usr/lib`, this problem seemed to be solved. 
    Then I tried to `make mlpack_test` again, but  failed again showing that 

`
Moving header files to include/mlpack/
[  0%] Built target mlpack_headers
[  1%] Updating arma_config.hpp (if necessary)
[  1%] Built target mlpack_arma_config
[ 35%] Built target mlpack
Linking CXX executable ../../../bin/mlpack_test
CMakeFiles/mlpack_test.dir/drusilla_select_test.cpp.o: In function `bool arma::sp_auxlib::eigs_sym<double, arma::SpMat<double> >(arma::Col<double>&, arma::Mat<double>&, arma::SpBase<double, arma::SpMat<double> > const&, unsigned int, char const*)':
drusilla_select_test.cpp:(.text._ZN4arma9sp_auxlib8eigs_symIdNS_5SpMatIdEEEEbRNS_3ColIT_EERNS_3MatIS5_EERKNS_6SpBaseIS5_T0_EEjPKc[_ZN4arma9sp_auxlib8eigs_symIdNS_5SpMatIdEEEEbRNS_3ColIT_EERNS_3MatIS5_EERKNS_6SpBaseIS5_T0_EEjPKc]+0x408): undefined reference to `wrapper_dsaupd_'
drusilla_select_test.cpp:(.text._ZN4arma9sp_auxlib8eigs_symIdNS_5SpMatIdEEEEbRNS_3ColIT_EERNS_3MatIS5_EERKNS_6SpBaseIS5_T0_EEjPKc[_ZN4arma9sp_auxlib8eigs_symIdNS_5SpMatIdEEEEbRNS_3ColIT_EERNS_3MatIS5_EERKNS_6SpBaseIS5_T0_EEjPKc]+0x8cb): undefined reference to `wrapper_dseupd_'
collect2: error: ld returned 1 exit status
make[3]: *** [bin/mlpack_test] Error 1
make[2]: *** [src/mlpack/tests/CMakeFiles/mlpack_test.dir/all] Error 2
make[1]: *** [src/mlpack/tests/CMakeFiles/mlpack_test.dir/rule] Error 2
make: *** [mlpack_test] Error 2
` 

Looks like that I didn't install `libarmadillo` properly... I'm not sure...
by the way, I can make `mlpack_pca` successfully. I don't 

Thank you...

**Comment by rcurtin** [comment]
Can you tell me how you installed Armadillo?  I think you are right that something is not right about how it was installed.

**Comment by TriLoo** [comment]
Thanks for reply. I justed fixed this error by installing armadillo with source code insteading `apt-get install libarmadillo-dev`.

**Comment by rcurtin** [comment]
Yep, that was going to be my suggestion. :)  Glad you got it worked out!  I'll go ahead and close this.
