### ISSUE TITLE
How can I uninstall mlpack after building from source?

### ISSUE THREAD

**Issue by gan3sh500** [mlpack/mlpack#973]
I built it from source and did a make install. Googling suggested make uninstall but I cannot find any uninstall in the folder where I did make install. Installation is in Ubuntu 16.04.

**Comment by zoq** [comment]
Hello, if you used the default install path you can uninstall the components with:

```bash
# remove lib
rm  /usr/local/lib/libmlpack*

# remove header files
rm -r /usr/local/include/mlpack

# remove executables
rm /usr/local/bin/mlpack_*
```

I hope this is helpful.

**Comment by rcurtin** [comment]
CMake doesn't provide uninstallation support by default, unfortunately.  What @zoq suggested above should work.
