### ISSUE TITLE
Add style check to Travis-CI tests

### ISSUE THREAD

**Issue by amoudgl** [mlpack/mlpack#978]
Right now, we manually review each PR for style issues. Instead, we can enforce some basic style rules using Travis-CI for matching the mlpack coding conventions. Not sure if this issue has already been discussed previously in mlpack community, just thought of giving a suggestion.

**Comment by nish21** [comment]
I believe this is the same as #420? Even I was wondering if this of interest to mlpack?

**Comment by amoudgl** [comment]
Thanks @nish21 for referring to the original issue. I think I should close it then and continue the discussion on the original issue. Thanks!
