### ISSUE TITLE
2.2.0 build error, Ubuntu 14.04

### ISSUE THREAD

**Issue by oepoemoepoe** [mlpack/mlpack#984]
Hi,

I get a linking error when building mlpack 2.2.0 on ubuntu 14.04 and could not find out how to resolve it. I followed the installation instructions on your website. Thanks in advance for any help :)

> [  1%] Updating arma_config.hpp (if necessary)
[  1%] Built target mlpack_arma_config
Moving header files to include/mlpack/
[  1%] Built target mlpack_headers
[  2%] Generating mlpack.pc (pkg-config) file.
[  2%] Built target pkgconfig
[  2%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/data/load_csv.cpp.o
[  3%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/data/load.cpp.o
[  3%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/discrete_distribution.cpp.o
[  4%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/gaussian_distribution.cpp.o
[  4%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/laplace_distribution.cpp.o
[  5%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/regression_distribution.cpp.o
[  6%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/dists/gamma_distribution.cpp.o
[  6%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/kernels/epanechnikov_kernel.cpp.o
[  7%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/kernels/pspectrum_string_kernel.cpp.o
[  7%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/columns_to_blocks.cpp.o
[  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/lin_alg.cpp.o
[  8%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/random.cpp.o
[  9%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/math/random_basis.cpp.o
[ 10%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/optimizers/aug_lagrangian/aug_lagrangian_test_functions.cpp.o
[ 10%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/optimizers/gradient_descent/test_function.cpp.o
[ 11%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/optimizers/lbfgs/test_functions.cpp.o
[ 11%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/optimizers/sgd/test_function.cpp.o
[ 12%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/tree/cosine_tree/cosine_tree.cpp.o
[ 12%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/backtrace.cpp.o
[ 13%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/cli.cpp.o
[ 14%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/cli_deleter.cpp.o
[ 14%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/log.cpp.o
[ 15%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/option.cpp.o
[ 15%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/prefixedoutstream.cpp.o
[ 16%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/singletons.cpp.o
[ 16%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/timers.cpp.o
[ 17%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/util/version.cpp.o
[ 18%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/cf/cf.cpp.o
[ 18%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/det/dtree.cpp.o
[ 19%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/det/dt_utils.cpp.o
[ 19%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/fastmks/fastmks_model.cpp.o
[ 20%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/gmm/gmm.cpp.o
[ 20%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/lars/lars.cpp.o
[ 21%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/linear_regression/linear_regression.cpp.o
[ 22%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/local_coordinate_coding/lcc.cpp.o
[ 22%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/matrix_completion/matrix_completion.cpp.o
[ 23%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/neighbor_search/unmap.cpp.o
[ 23%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/quic_svd/quic_svd.cpp.o
[ 24%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/radical/radical.cpp.o
[ 24%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/randomized_svd/randomized_svd.cpp.o
[ 25%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/range_search/rs_model.cpp.o
[ 26%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/rann/ra_util.cpp.o
[ 26%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/regularized_svd/regularized_svd_function.cpp.o
[ 27%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/softmax_regression/softmax_regression_function.cpp.o
[ 27%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_autoencoder/sparse_autoencoder_function.cpp.o
[ 28%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_autoencoder/maximal_inputs.cpp.o
[ 28%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/sparse_coding/sparse_coding.cpp.o
Linking CXX shared library ../../lib/libmlpack.so
[ 28%] Built target mlpack
[ 28%] Building CXX object src/mlpack/methods/preprocess/CMakeFiles/mlpack_preprocess_binarize.dir/preprocess_binarize_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_preprocess_binarize
[ 28%] Built target mlpack_preprocess_binarize
[ 29%] Building CXX object src/mlpack/methods/preprocess/CMakeFiles/mlpack_preprocess_describe.dir/preprocess_describe_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_preprocess_describe
[ 29%] Built target mlpack_preprocess_describe
[ 29%] Building CXX object src/mlpack/methods/preprocess/CMakeFiles/mlpack_preprocess_imputer.dir/preprocess_imputer_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_preprocess_imputer
[ 29%] Built target mlpack_preprocess_imputer
[ 30%] Building CXX object src/mlpack/methods/preprocess/CMakeFiles/mlpack_preprocess_split.dir/preprocess_split_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_preprocess_split
[ 30%] Built target mlpack_preprocess_split
[ 31%] Building CXX object src/mlpack/methods/adaboost/CMakeFiles/mlpack_adaboost.dir/adaboost_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_adaboost
[ 31%] Built target mlpack_adaboost
[ 31%] Building CXX object src/mlpack/methods/approx_kfn/CMakeFiles/mlpack_approx_kfn.dir/approx_kfn_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_approx_kfn
[ 31%] Built target mlpack_approx_kfn
[ 32%] Building CXX object src/mlpack/methods/cf/CMakeFiles/mlpack_cf.dir/cf_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_cf
[ 32%] Built target mlpack_cf
[ 32%] Building CXX object src/mlpack/methods/dbscan/CMakeFiles/mlpack_dbscan.dir/dbscan_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_dbscan
[ 32%] Built target mlpack_dbscan
[ 33%] Building CXX object src/mlpack/methods/decision_stump/CMakeFiles/mlpack_decision_stump.dir/decision_stump_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_decision_stump
[ 33%] Built target mlpack_decision_stump
[ 33%] Building CXX object src/mlpack/methods/decision_tree/CMakeFiles/mlpack_decision_tree.dir/decision_tree_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_decision_tree
[ 33%] Built target mlpack_decision_tree
[ 34%] Building CXX object src/mlpack/methods/det/CMakeFiles/mlpack_det.dir/det_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_det
[ 34%] Built target mlpack_det
[ 34%] Building CXX object src/mlpack/methods/emst/CMakeFiles/mlpack_emst.dir/emst_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_emst
[ 34%] Built target mlpack_emst
[ 35%] Building CXX object src/mlpack/methods/fastmks/CMakeFiles/mlpack_fastmks.dir/fastmks_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_fastmks
[ 35%] Built target mlpack_fastmks
[ 36%] Building CXX object src/mlpack/methods/gmm/CMakeFiles/mlpack_gmm_generate.dir/gmm_generate_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_gmm_generate
[ 36%] Built target mlpack_gmm_generate
[ 36%] Building CXX object src/mlpack/methods/gmm/CMakeFiles/mlpack_gmm_probability.dir/gmm_probability_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_gmm_probability
[ 36%] Built target mlpack_gmm_probability
[ 37%] Building CXX object src/mlpack/methods/gmm/CMakeFiles/mlpack_gmm_train.dir/gmm_train_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_gmm_train
[ 37%] Built target mlpack_gmm_train
[ 37%] Building CXX object src/mlpack/methods/hmm/CMakeFiles/mlpack_hmm_generate.dir/hmm_generate_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_hmm_generate
[ 37%] Built target mlpack_hmm_generate
[ 38%] Building CXX object src/mlpack/methods/hmm/CMakeFiles/mlpack_hmm_loglik.dir/hmm_loglik_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_hmm_loglik
[ 38%] Built target mlpack_hmm_loglik
[ 38%] Building CXX object src/mlpack/methods/hmm/CMakeFiles/mlpack_hmm_train.dir/hmm_train_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_hmm_train
[ 38%] Built target mlpack_hmm_train
[ 39%] Building CXX object src/mlpack/methods/hmm/CMakeFiles/mlpack_hmm_viterbi.dir/hmm_viterbi_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_hmm_viterbi
[ 39%] Built target mlpack_hmm_viterbi
[ 40%] Building CXX object src/mlpack/methods/hoeffding_trees/CMakeFiles/mlpack_hoeffding_tree.dir/hoeffding_tree_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_hoeffding_tree
[ 40%] Built target mlpack_hoeffding_tree
[ 40%] Building CXX object src/mlpack/methods/kernel_pca/CMakeFiles/mlpack_kernel_pca.dir/kernel_pca_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_kernel_pca
[ 40%] Built target mlpack_kernel_pca
[ 40%] Building CXX object src/mlpack/methods/kmeans/CMakeFiles/mlpack_kmeans.dir/kmeans_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_kmeans
[ 40%] Built target mlpack_kmeans
[ 41%] Building CXX object src/mlpack/methods/mean_shift/CMakeFiles/mlpack_mean_shift.dir/mean_shift_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_mean_shift
[ 41%] Built target mlpack_mean_shift
[ 42%] Building CXX object src/mlpack/methods/lars/CMakeFiles/mlpack_lars.dir/lars_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_lars
[ 42%] Built target mlpack_lars
[ 43%] Building CXX object src/mlpack/methods/linear_regression/CMakeFiles/mlpack_linear_regression.dir/linear_regression_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_linear_regression
[ 43%] Built target mlpack_linear_regression
[ 43%] Building CXX object src/mlpack/methods/local_coordinate_coding/CMakeFiles/mlpack_local_coordinate_coding.dir/local_coordinate_coding_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_local_coordinate_coding
[ 43%] Built target mlpack_local_coordinate_coding
[ 44%] Building CXX object src/mlpack/methods/logistic_regression/CMakeFiles/mlpack_logistic_regression.dir/logistic_regression_main.cpp.o
In file included from /home/user01/Downloads/mlpack-2.2.0/src/mlpack/methods/logistic_regression/logistic_regression.hpp:253:0,
                 from /home/user01/Downloads/mlpack-2.2.0/src/mlpack/methods/logistic_regression/logistic_regression_main.cpp:16:
/home/user01/Downloads/mlpack-2.2.0/src/mlpack/methods/logistic_regression/logistic_regression_impl.hpp: In instantiation of ‘void mlpack::regression::LogisticRegression<MatType>::Classify(const MatType&, arma::Row<long unsigned int>&, double) const [with MatType = arma::Mat<double>]’:
/home/user01/Downloads/mlpack-2.2.0/src/mlpack/methods/logistic_regression/logistic_regression_main.cpp:282:60:   required from here
/home/user01/Downloads/mlpack-2.2.0/src/mlpack/methods/logistic_regression/logistic_regression_impl.hpp:129:44: warning: ‘void mlpack::regression::LogisticRegression<MatType>::Predict(const MatType&, arma::Row<long unsigned int>&, double) const [with MatType = arma::Mat<double>]’ is deprecated (declared at /home/user01/Downloads/mlpack-2.2.0/src/mlpack/methods/logistic_regression/logistic_regression_impl.hpp:101) [-Wdeprecated-declarations]
   Predict(dataset, labels, decisionBoundary);
                                            ^
Linking CXX executable ../../../../bin/mlpack_logistic_regression
[ 44%] Built target mlpack_logistic_regression
[ 44%] Building CXX object src/mlpack/methods/lsh/CMakeFiles/mlpack_lsh.dir/lsh_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_lsh
[ 44%] Built target mlpack_lsh
[ 44%] Building CXX object src/mlpack/methods/naive_bayes/CMakeFiles/mlpack_nbc.dir/nbc_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_nbc
[ 44%] Built target mlpack_nbc
[ 45%] Building CXX object src/mlpack/methods/nca/CMakeFiles/mlpack_nca.dir/nca_main.cpp.o
Linking CXX executable ../../../../bin/mlpack_nca
CMakeFiles/mlpack_nca.dir/nca_main.cpp.o: In function `main':
nca_main.cpp:(.text.startup+0x1905): undefined reference to `bool mlpack::data::Load<unsigned int>(std::string const&, arma::Mat<unsigned int>&, bool, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/mlpack_nca] Error 1
make[1]: *** [src/mlpack/methods/nca/CMakeFiles/mlpack_nca.dir/all] Error 2
make: *** [all] Error 2

**Comment by rcurtin** [comment]
I see... can you tell me what architecture your computer is? (i386/x86_64/something else)  I think I might know what this issue is.

**Comment by rcurtin** [comment]
Ah actually one more question---do you have mlpack installed on the system in any other way? i.e. maybe you ran `apt-get install libmlpack-dev` or installed an older version of mlpack earlier or something.

**Comment by oepoemoepoe** [comment]
My system is 4.4.0-72-generic #93~14.04.1-Ubuntu x86_64.
I did not have installed libmlpack-dev prior to building, however I did now in order to already start developing :)

**Comment by rcurtin** [comment]
Hi there,

This actually was a bug I could reproduce that happens with old Armadillo versions.  I released mlpack 2.2.1, which fixes the issue.

Thanks for reporting this!

**Comment by oepoemoepoe** [comment]
You're welcome - thanks a lot for fixing!
