### ISSUE TITLE
Documentation wrong about Kmeans InitialPartitionPolicy 

### ISSUE THREAD

**Issue by oepoemoepoe** [mlpack/mlpack#988]
Hi,

the documentation [1] states that
typename InitialPartitionPolicy = SampleInitialization
however it is in kmeans.hpp
typename InitialPartitionPolicy = RandomPartition

[1] http://www.mlpack.org/docs/mlpack-2.2.1/doxygen.php?doc=classmlpack_1_1kmeans_1_1KMeans.html

**Comment by rcurtin** [comment]
What version of mlpack are you using? In 2.0.0 and newer the default is `SampleInitialization` just like in the documentation.  So I don't see the inconsistency.

**Comment by oepoemoepoe** [comment]
I'm sorry, I confused my mlpack versions :/

**Comment by rcurtin** [comment]
No worries, glad you got it sorted out. :)
