### ISSUE TITLE
the newest build did not install mlpack_allknn?

### ISSUE THREAD

**Issue by ThyrixYang** [mlpack/mlpack#992]
after I've build and installed mlpack, I only have these files in /usr/local/bin

mlpack_adaboost*         mlpack_krann*
mlpack_approx_kfn*       mlpack_lars*
mlpack_cf*               mlpack_linear_regression*
mlpack_dbscan*           mlpack_local_coordinate_coding*
mlpack_decision_stump*   mlpack_logistic_regression*
mlpack_decision_tree*    mlpack_lsh*
mlpack_det*              mlpack_mean_shift*
mlpack_emst*             mlpack_nbc*
mlpack_fastmks*          mlpack_nca*
mlpack_gmm_generate*     mlpack_nmf*
mlpack_gmm_probability*  mlpack_pca*
mlpack_gmm_train*        mlpack_perceptron*
mlpack_hmm_generate*     mlpack_preprocess_binarize*
mlpack_hmm_loglik*       mlpack_preprocess_describe*
mlpack_hmm_train*        mlpack_preprocess_imputer*
mlpack_hmm_viterbi*      mlpack_preprocess_split*
mlpack_hoeffding_tree*   mlpack_radical*
mlpack_kernel_pca*       mlpack_range_search*
mlpack_kfn*              mlpack_softmax_regression*
mlpack_kmeans*           mlpack_sparse_coding*
mlpack_knn*

And I think allknn did not be installed

Up-to-date: /usr/local/lib/libmlpack.so.2.0
-- Up-to-date: /usr/local/lib/libmlpack.so.2
-- Up-to-date: /usr/local/lib/libmlpack.so
-- Up-to-date: /usr/local/bin/mlpack_preprocess_split
-- Up-to-date: /usr/local/bin/mlpack_preprocess_binarize
-- Up-to-date: /usr/local/bin/mlpack_preprocess_describe
-- Up-to-date: /usr/local/bin/mlpack_preprocess_imputer
-- Up-to-date: /usr/local/bin/mlpack_adaboost
-- Up-to-date: /usr/local/bin/mlpack_approx_kfn
-- Up-to-date: /usr/local/bin/mlpack_cf
-- Up-to-date: /usr/local/bin/mlpack_dbscan
-- Up-to-date: /usr/local/bin/mlpack_decision_stump
-- Up-to-date: /usr/local/bin/mlpack_decision_tree
-- Up-to-date: /usr/local/bin/mlpack_det
-- Up-to-date: /usr/local/bin/mlpack_emst
-- Up-to-date: /usr/local/bin/mlpack_fastmks
-- Up-to-date: /usr/local/bin/mlpack_gmm_train
-- Up-to-date: /usr/local/bin/mlpack_gmm_generate
-- Up-to-date: /usr/local/bin/mlpack_gmm_probability
-- Up-to-date: /usr/local/bin/mlpack_hmm_train
-- Up-to-date: /usr/local/bin/mlpack_hmm_loglik
-- Up-to-date: /usr/local/bin/mlpack_hmm_viterbi
-- Up-to-date: /usr/local/bin/mlpack_hmm_generate
-- Up-to-date: /usr/local/bin/mlpack_hoeffding_tree
-- Up-to-date: /usr/local/bin/mlpack_kernel_pca
-- Up-to-date: /usr/local/bin/mlpack_kmeans
-- Up-to-date: /usr/local/bin/mlpack_mean_shift
-- Up-to-date: /usr/local/bin/mlpack_lars
-- Up-to-date: /usr/local/bin/mlpack_linear_regression
-- Up-to-date: /usr/local/bin/mlpack_local_coordinate_coding
-- Up-to-date: /usr/local/bin/mlpack_logistic_regression
-- Up-to-date: /usr/local/bin/mlpack_lsh
-- Up-to-date: /usr/local/bin/mlpack_nbc
-- Up-to-date: /usr/local/bin/mlpack_nca
-- Up-to-date: /usr/local/bin/mlpack_knn
-- Up-to-date: /usr/local/bin/mlpack_kfn
-- Up-to-date: /usr/local/bin/mlpack_nmf
-- Up-to-date: /usr/local/bin/mlpack_pca
-- Up-to-date: /usr/local/bin/mlpack_perceptron
-- Up-to-date: /usr/local/bin/mlpack_radical
-- Up-to-date: /usr/local/bin/mlpack_range_search
-- Up-to-date: /usr/local/bin/mlpack_krann
-- Up-to-date: /usr/local/bin/mlpack_softmax_regression
-- Up-to-date: /usr/local/bin/mlpack_sparse_coding

what is the problem?

**Comment by rcurtin** [comment]
Ah, good point.  The `mlpack_allknn` and `mlpack_allkfn` programs are replaced by `mlpack_knn` and `mlpack_kfn`, but the old names are supposed to be preserved for reverse compatibility until mlpack 3.0.0.

When you filed this bug, I noticed that this is not actually the case on installation, so I committed da1df467c and will release mlpack 2.2.2 with the fix shortly.  (I still have one other problem I want to fix before releasing a bugfix version.)

Thanks for pointing it out! :)
