### ISSUE TITLE
not able to compile on ubuntu 16.04 x64

### ISSUE THREAD

**Issue by vik975** [mlpack/mlpack#998]
I generated make files using cmake -D DEBUG=ON -D PROFILE=ON ../ and then make 
. Got following errors . I ma using ubuntu 16.04 x64.  Can some one please help , what could be the issue. 
 The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0 and boost is 1.58.0

[  1%] Updating arma_config.hpp (if necessary)
[  1%] Built target mlpack_arma_config
Moving header files to include/mlpack/
[  1%] Built target mlpack_headers
[  2%] Generating mlpack.pc (pkg-config) file.
[  2%] Built target pkgconfig
[  2%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/data/load_csv.cpp.o
In file included from /usr/include/boost/lexical_cast/detail/converter_lexical.hpp:51:0,
                 from /usr/include/boost/lexical_cast/try_lexical_convert.hpp:34,
                 from /usr/include/boost/lexical_cast.hpp:32,
                 from /usr/include/boost/math/constants/constants.hpp:18,
                 from /usr/include/boost/math/special_functions/gamma.hpp:24,
                 from /home/vikash/mlpack/mlpack-2.2.2/src/mlpack/../mlpack/prereqs.hpp:43,
                 from /home/vikash/mlpack/mlpack-2.2.2/src/mlpack/../mlpack/core.hpp:218,
                 from /home/vikash/mlpack/mlpack-2.2.2/src/mlpack/core/data/load_csv.hpp:18,
                 from /home/vikash/mlpack/mlpack-2.2.2/src/mlpack/core/data/load_csv.cpp:12:
/usr/include/boost/container/container_fwd.hpp:271:4: internal compiler error: Segmentation fault
    }
    ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
src/mlpack/CMakeFiles/mlpack.dir/build.make:62: recipe for target 'src/mlpack/CMakeFiles/mlpack.dir/core/data/load_csv.cpp.o' failed
make[2]: *** [src/mlpack/CMakeFiles/mlpack.dir/core/data/load_csv.cpp.o] Error 1
CMakeFiles/Makefile2:201: recipe for target 'src/mlpack/CMakeFiles/mlpack.dir/all' failed
make[1]: *** [src/mlpack/CMakeFiles/mlpack.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zoq** [comment]
Are you able to test it with another compiler (version) or probably clang? You can specify the compiler with: ``cmake -DCMAKE_CXX_COMPILER=/path/to/clang++ ..``

**Comment by rcurtin** [comment]
This one seems strange to me, gcc doesn't usually give internal compiler errors on mlpack.  Part of me wonders if you have some bad RAM.  You could check with memtest.

**Comment by vik975** [comment]
Thanks for the help. With clang++ (clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)) , the compilation went through.

 I tried with the sudo memtester 1024 5. Everything went OK. But since I am running Ubuntu on a VBox . Will that have an effect?. I will investigate further what could be the problem with gnu c++, will let you guys know if I find anything useful.

**Comment by rcurtin** [comment]
Ah, I didn't know if you were in a VM.  I don't know if memtest will give reasonable results inside of a VM, maybe it is worth checking the RAM on the host OS.

**Comment by vik975** [comment]
Windows10 memory diagnostics did not report any error.

**Comment by zoq** [comment]
How much memory have you allocated for the VM? Perhaps it's not enough.

**Comment by vik975** [comment]
The problem was indeed memory (RAM). Although the RAM allocated for the VM was 4096 MB(so, 4 Gb and 96 Mb). But sometimes free RAM  drops between 109-500Mb during the compilation(checked using free -m on guest)  . So, I had to close all of the application on the guest. And I also closed some of the application on host   like Visual Studio, majority of chrome tabs etc..) then,  the compilation on the VM went through fine.  I do not know why the processes on the host machine should effect the VM RAM consumption. But the problem is now solved . MLPACK compiles using gnu compilers- Thanks for help.

**Comment by rcurtin** [comment]
Ok, good to know that a lack of available host RAM can affect the VM in this way.  I will keep that in mind to suggest to people in the future who have similar problems. :)  Thanks for the update!  I'll go ahead and close this ticket since you have everything working.
